### ISSUE TITLE
NPC's do not save their positions correctly

### ISSUE THREAD

**Issue by StillSwingin** [CitizensDev/Citizens2#100]
After I had created tons of NPC's and changed where they were looking at I restarted my server (I did /citizens save before btw) and when I entered all this NPC had changed their pose. Is it a bug or something from my config? How can I fix it?
Thank you

**Comment by mcmonkey4eva** [comment]
If anyone wants to pull request a fix for this, please do. For now, I'm making this issue 'not likely to happen', sorry.
