### ISSUE TITLE
[Question] What is the current status of SQL?

### ISSUE THREAD

**Issue by FlyingPikachu** [CitizensDev/Citizens2#1002]
My server has several *hundred* NPCs that I get "[Sentinel] NPC ### has a null spawn point" errors for post-startup because we deleted a world, and seemingly the best way to resolve this would be to manually delete each npc block in the config. If SQL were finished, we could just delete all rows containing that world. I see SQL listed on the Wiki's TODO page. What is the progress as of this time?

[22:43:06] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f950f8e-b64d852 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[22:43:32] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.21-SNAPSHOT (build 1451)
[22:43:47] [Server thread/INFO]: [Sentinel] Enabling Sentinel v0.9 (build 70)
[22:43:06] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f950f8e-b64d852 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[22:43:32] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.21-SNAPSHOT (build 1451)
[22:43:47] [Server thread/INFO]: [Sentinel] Enabling Sentinel v0.9 (build 70)

**Comment by mcmonkey4eva** [comment]
Part of the problem is that the concept of a Citizens NPC and the concept of an SQL row are not compatible.
An NPC can have a thousand and one pieces of data on it, or only one.
SQL rows have a specific number of columns, each containing precisely one piece of data.
An NPC's data is structure in a tree-shape.
An SQL row is... a straight line, a row, not-at-all-a-tree, ...
These two separate styles of data do not go together that well.

If you want to auto-delete things programmatically, I have good news for you:
YAML is significantly easier to edit programmatically or even by hand, than SQL is.

If Citizens did add database support, it would be more reasonable to use a database such as a MongoDB or similar, where `Document`s are the main component, rather than `Row`s.

But then, why would we want database support at all?
Citizens saves are inherently local: An NPC is attached to a specific world file like an entity, and should not be shared between servers (doing so will cause unusual behavior at best).
A local file with its own internal structure is the only method that really makes sense for Citizens based on the above.

**Comment by fullwall** [comment]
As mcmonkey said, the problem with traditional SQL is that all of our data is currently in a hierarchical format, which cannot be easily translated to SQL. I could possibly implement a hierarchical database such as MongoDB.

**Comment by FlyingPikachu** [comment]
It's a shame I won't be seeing it anytime soon. You both make a good point that the Citizens config is complex, although one upside to having database support would be the ability to manipulate data of multple NPCs at once. However, I still feel it could be simplified to rows. Here's a quick example:

| id  | name          | location (world,x,y,x,yaw.pitch) | spawned | speech | talk-close | random-talker |
| -- |:--------------:|:---------:|:----------:|:-------: |:-----------:|:----------------:|
| 1   | pen             | world, 1, -4, 5, 1,  0     | true         |     chat | true          | false                 |
| 2   | pineapple   |   world_nether, -5, 100, 3, 1,  1     | true          |  chat   | true         |  true     |
| 3   | apple          |    world_end, 5,  -48, 22, 1,  -8  | false        |   chat  | false     | false        |

...and so on, using commas for seperators and NULL values for optional traits such as Sentinel.

**Comment by mcmonkey4eva** [comment]
It's relevant that traits are 100% optional and do not exist in the base code, but rather external plugins.

A server admin can add a new trait or remove an old trait at any time.

Also a trait can have any unspecified amount of custom data associated with it.

Some traits even have 100% dynamic data management, in which they do not have a pre-determined set of options, but rather create and destroy options every time they save to Citizens.

**Comment by FlyingPikachu** [comment]
Sorry, I meant NULL values for traits or parts of traits which are not being used. There would be columns for them regardless. When in use, let's say for an equipment trait, a custom Bow might look something like this:

| hand (type, amount, durability, mdata)  | lore (comma or other char to separate lines)          | displayname (let's say none in this case)| repaircost | enchantments | enchantment-levels |
| ------------ |:------------------------------------------------------:|:---------:|:----------:|:-------:|:---:|
| bow,1,0,0   | The letters MM4E are remarkably, *etched into the limb.*         | (NULL)     | 0         |     ARROW_KNOCKBACK,ARROW_FIRE,DURABILITY | 2,1,3|

For these dynamic options I suppose they would need to create and destroy columns as needed? I don't mean to push the subject, just interested in how feasible it is for the future :)

**Comment by mcmonkey4eva** [comment]
That doesn't respond to the problem:
**Citizens,** insofar as the saving/loading portion that would build an SQL database, **literally is not aware what traits exist or will exist later,** and thus cannot put null slots for them.

Further, it establishes issues of its own:
What if there are **two** items in the equipment? What about **two hundred**?

**Comment by FlyingPikachu** [comment]
If there is no list of possible traits, how does Citizens currently populate the config? Surely, if an equipment trait *can* exist, we can create a column for it with a NULL value until it *does* exist, if ever.

For your specific issue, we would anticipate a type, amount, durability, mdata, and meta fields, as Citizens already appears to do in saves.yml, for each slot/column (hand, helmet, chestplate, leggings). See example, meta excluded for simplicity

| hand (type, amount, durability, mdata)  | chestplate (type, amount, durability, mdata)         | leggings (type, amount, durability, mdata)| boots (type, amount, durability, mdata) |
| ------------ |:------------------------------------:|:---------:|:----------:|
| bow,1,0,0   | leather_chestplate,1,0,0         | (NULL)     | diamond_boots,1,0,0         |

**Comment by mcmonkey4eva** [comment]
`If there is no list of possible traits, how does Citizens currently populate the config? Surely, if an equipment trait can exist, we can create a column for it with a NULL value until it does exist, if ever.`
Dynamic creation. We can't just create a NULL for every possible (for example) Sentinel option, because the Citizens API codebase doesn't know or care that Sentinel is a thing.

And that accounts for a standard equipment set, but what about dynamically sized inventories?
What about dynamically sized sets of data, such as the Sentinel targets lists?

**Comment by FlyingPikachu** [comment]
I see your point. In that case, where the Citizens codebase does not specifically recognize Sentinel (or any other plugin for that matter), I suppose it would be up to that plugin to create and store its own data, whether in the Citizens table or its own. Of course, the latter deviates from the current setup of everything being in one place/file, but some traditions are meant to be broken.

Inventories and targets would just be a (potentially long) list of items separated by commas, which in code would be iterated over. HyperConomy has accomplished this.

**Comment by mcmonkey4eva** [comment]
Let's jump back for a moment, and assume that's all fine... but what about this bit I mentioned earlier:
`But then, why would we want database support at all?`
`Citizens saves are inherently local: An NPC is attached to a specific world file like an entity, and should not be shared between servers (doing so will cause unusual behavior at best).`
`A local file with its own internal structure is the only method that really makes sense for Citizens based on the above.`

**Comment by FlyingPikachu** [comment]
Well, being able to organized and manipulate the data of multple NPCs at once, I had assumed there must have been some reason to have added it to the TODO list at one point ([link](https://wiki.citizensnpcs.co/TODO)). Looking at the revision history, maybe @fullwall might remember?

Also with all due respect, I doubt sharing the data between servers would cause much odd behavior. As long as there are no concurrent modifications to the database, it might be useful to have the same NPC instances on 2 servers, in a gaming network for example. Or, kill X npc on one server for Y reward on the next. The possibilities are endless.

But for me I'm just lazy and don't want to pan through a 1 MB saves.yml for a few hours lol

**Comment by mcmonkey4eva** [comment]
`But for me I'm just lazy and don't want to pan through a 1 MB saves.yml for a few hours lol`
I don't understand, in what situation is editing SQL rows any easier than editing YAML data - assuming you have the correct tools to work with those?
It's a short few lines of code either way...
`it might be useful to have the same NPC instances on 2 servers, in a gaming network for example`
Duplicate the relevant data properly, sharing it live will be odd. Server A, an NPC dies. What happens on Server B? Does its match NPC die? When Server A npc respawns, where does it respawn at? It's stored last-known-location is wherever Server B's NPC is at, not where it died, ...
`Or, kill X npc on one server for Y reward on the next` That'd require a separate plugin managing rewards regardless. Which is free to use SQL itself without requiring Citizens to.

**Comment by FlyingPikachu** [comment]
If the data were in SQL format, I could query all rows which contain the world I wish to delete NPCs for and drop all those rows. Whereas with YAML my current method is to get an NPC id from the server log errors, find and carefully select that block in saves.yml, delete and repeat... a few hundred times. What is this line of code you speak of for YAML? Very, very interested.

Nothing would happen on Server B unless the death event is triggered for the NPC on Server B, at which point it would check the database. However if its desired that it die, a setting or plugin (perhaps Sentinel in this case) could make it happen. Could be a problem if they both died at once, in which case might want to keep the last-known-location locally (in a variable, even) since I figure that wouldn't need to persist a restart. Or, could add a server-id column to check.

And yes, but having a database for this separate plugin to look at would be phenomenal.

**Comment by fullwall** [comment]
Yes, I agree with you @FlyingPikachu it would be good to have a query language that you could use for Citizens data. We actually had a piece of code that is similar to your dynamic tables idea, but it ended up not working too reliably for highly nested data common to other plugins. Basically, we'd need to change the API first and make everyone rewrite their code to implement SQL properly. NoSQL would be a better alternative.

**Comment by mcmonkey4eva** [comment]
YAML being a bit generic, has a fair few options for how to accomplish what you need.
This site is one example: http://yaqluator.com/
Or just write a miniprogram in: Java, JavaScript, C#, Python, Denizen, any other reasonably capable language ever...

`Or, could add a server-id column to check.`... Which now adds a whole new layer of unnecessary complexity to an unnecessarily complex addition already being built by you...

`And yes, but having a database for this separate plugin to look at would be phenomenal.` ... how?

**Comment by mcmonkey4eva** [comment]
Oh, a way to quickly query data is a much more reasonable idea. That one, we could set up potentially... not from an external DB, I don't think though...

**Comment by FlyingPikachu** [comment]
Thanks, fullwall. Shame to hear that didn't work out. I'm curious what sort of API changes would be needed, but I ought to familiarize myself with the plugin more before I ask that.

Mcmonkey, I'll look into those YAQL expression, looks like a dream come true. You're right, I could use another language too but I was hoping the SQL options I found in the Citizens config might actually work.

A server-id column would be a bad idea, but it is an option.

Plugins could check the database if only a few pieces of Citizens-related data are needed, rather than hooking into the plugin directly. This includes websites and web-based applications. And I think you'd be surprised at the speed of SQL.

**Comment by fullwall** [comment]
@FlyingPikachu currently NPC storage is exposed in the API as a DataKey: https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/util/DataKey.java - similar to Bukkit's YamlConfiguration. Due to the way keys are represented as hierarchical strings separated by '.' this API would need to be rewritten to accommodate SQL. However, the API is exposed in the Trait class and so it would have to be a gradual migration.

**Comment by FlyingPikachu** [comment]
Interesting stuff. That seems challenging but not impossible. Hoping I can find time to look into this more in the future.

Thank you both for your help and insight!
