### ISSUE TITLE
Be able to set NPC to armor stand to have them sit.

### ISSUE THREAD

**Issue by DocCodeSharp** [CitizensDev/Citizens2#1003]
I am working on a server for quite some time and i always thought it would be cool if we could set the NPC from Citizens to say an armor stand and hide the armor stand to give the illusion that the NPC was sitting down. 
Something like /npc addvehicle and it would add an armor stand under the NPC and have the npc sit on the armor stand.

From there we can just use normal Minecraft to edit and change the location of the armor stand and make it invisible.

**Comment by mcmonkey4eva** [comment]
Citizens has a way to do that, it's currently API only.
You can call this and related API's through Denizen fairly easily: https://wiki.citizensnpcs.co/Denizen
EG you would do `/ex animate <npc> animation:sit`

**Comment by ABUDoctor** [comment]
Good idea, but I don't want to have to keep relying on other plugins if a version update happens and I'm stuck waiting to update and no knowing what problems can happen. It would be nice if this was built into Citizens.

**Comment by YepImRobbie** [comment]
Would like to see this, a hobo sitting down'd be nice.

**Comment by TheZenKitteh** [comment]
Any word on this? I'd like to see this too.

**Comment by mcmonkey4eva** [comment]
@TheZenKitteh @YepImRobbie If you want to see it... do it. It's available (as long as you run Denizen alongside Citizens), allowing you to use `/npc sit`.
This issue is just to have a pure-Citizens option for when that might be needed (for the most part it isn't, as anywhere you can run Citizens you can also run Denizen).
