### ISSUE TITLE
Server freeze (15 sec)

### ISSUE THREAD

**Issue by Nishh** [CitizensDev/Citizens2#1005]
Stacktrace at freeze:  http://pastie.org/10980594
Server version: Paper-842 (PaperSpigot 1.10.2)
Citizens version: 2.0.21 (build 1437)
Citizens config: http://pastie.org/10980596
Citizens saves.yml: http://pastebin.com/eV94vSnE
Plugin list: http://pastie.org/10980601

No error on log.
npcs are not moving. including head rotation. (this is not a problem)

**Comment by fullwall** [comment]
Seems like a chunk loading / disk problem
