### ISSUE TITLE
[Bug] Evoker Model?

### ISSUE THREAD

**Issue by PhivianFilms** [CitizensDev/Citizens2#1006]
I don't see anything abnormal in config and nothing shows in server log when this begins to happen.  I have the latest version of minecraft client, server client, and citizens download. I went to use evoker type for a npc and my npc's started freaking out (by that I mean they continuously look around in random directions all the time) and some of my other npc's will mimic me but everything they express is inverted (if I look left they will look right). Then after I stop my server the evoker model disappears and keeps spawning EVOKER_FANGS in it's place each time I go to use the type or load up my server. I have not been able to stop any of my other npc's awkward behavior either...

If you have any suggestions as how to fix this I would love to try them nothing I seem to do fixes anything, it just keeps getting worse...

**Comment by fullwall** [comment]
Fixed saving/loading of evokers in the latest build.

**Comment by PhivianFilms** [comment]
Define "latest build" for me? In version 2.0.21 evokers revert to EVOKER_FANGS upon reload... I downloaded another of the latest version and I can't reproduce this "freaking out glitch" anymore, it must have been corrupted... But I can confirm that evokers disappear on reload...

**Comment by mcmonkey4eva** [comment]
Latest build available http://ci.citizensnpcs.co/job/Citizens2/

**Comment by PhivianFilms** [comment]
@mcmonkey4eva Yes this is the build I'm using, this is the one that has the two bugs I have specified...

**Comment by fullwall** [comment]
@PhivianFilms you sure? should be Citizens2 build 1453

**Comment by PhivianFilms** [comment]
Remove this from your priorities, this must have been coincidental or something...
