### ISSUE TITLE
[Feature Request]About NPC visualization

### ISSUE THREAD

**Issue by DoloStar** [CitizensDev/Citizens2#1007]
Server ver: paperspigot 1.8.8
Maybe can add a new function to controls whether the specified player can see the specified NPC ?

**Comment by mcmonkey4eva** [comment]
To 1.8? Nope, we don't add new features to old versions.
However,
The Denizen side-plugin https://wiki.citizensnpcs.co/Denizen supports 1.8 and supports exactly this feature. Might try that out.
