### ISSUE TITLE
Head rotates, but body no!

### ISSUE THREAD

**Issue by FabioZumbi12** [CitizensDev/Citizens2#1008]
Hi,

I having a issue qhere when i go close to my npc, it looks to me, but when i go away, the head get back to the default position, but the body no:

https://gyazo.com/adc87530f060acbfa866ae3d855e6a47

Using Paperclip 1.11 and Latest CItizens version.

**Comment by FabioZumbi12** [comment]
And why its too hard to set the NPC looking direction? :(

I tryng to set head looking position at 1hour and cant. I just tryed with /npc path, /npc pose, /npc move,  but always npc still looking to south.

**Comment by R3D7uP** [comment]
I'm also having the same issue on my server! I tried making a thread of Spigot, but no one got back to me, so hopefully someone can shed some light on this issue here ^.^

**Comment by mcmonkey4eva** [comment]
Can you replicate on build 1461 or higher from the dev page?
http://ci.citizensnpcs.co/job/Citizens2/
