### ISSUE TITLE
Text editor not working with BungeeCord MultiChat

### ISSUE THREAD

**Issue by rob1998** [CitizensDev/Citizens2#1010]
Found a possible bug, if I want to edit the text of a npc it gives me the editor message. However, when I type 'add' (without quotes) to try to add some text it will just send it as a chat message and not as a command for citizens. I think it's because of MultiChat. Are there other people with this problem, or maybe even people with a solution?

**Comment by Imothep80** [comment]
Hello Rob,

how you fix this Problem?
