### ISSUE TITLE
Nameplate visibility broken [Bug]

### ISSUE THREAD

**Issue by NASH0XX** [CitizensDev/Citizens2#1011]
Hello.

In the latest devbuild of Citizens (citizens 2.0.21-SNAPSHOT) and when also using Spigot 1.10.2 the nameplate visibility option is broken/does not work. Using /npc name won't disable the nameplate.

There are no errors in the console.

**Comment by fullwall** [comment]
What entity type? It's disabling for me.

**Comment by fullwall** [comment]
If it's player please check that use-scoreboard-teams is set to true in your config.
