### ISSUE TITLE
Server freezes when NPC gravity is disabled

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens2#1013]
The server console gets spammed with errors when an NPCs gravity is disabled and after a while players are unable to login because the server freezes. (http://pastie.org/10983459)

Server version: PaperSpigot version git-Paper-963 (MC 1.11) 
Plugin version: Citizens v2.0.21 - SNAPSHOT (build 1459)

**Comment by fullwall** [comment]
Something is setting the NPC velocity too high upwards - a plugin maybe? Doesn't seem related to gravity
