### ISSUE TITLE
Give citizen multiple weapons?

### ISSUE THREAD

**Issue by CurtainHumper** [CitizensDev/Citizens2#1014]
1. I would like to give my guards swords for melee fights, and bows for ranged fights. 
If I am in equip-mode, I can only give them one weapon. (e.g. when I give a bow/arrows to a NPC holding a sword, it drops the sword). When I go in their inventory and try to simply place a second weapon in there, it just disappears. 
I have tried it with autoswitch-mode on and off.

2. Can you please explain what the 'guided waypoint provider' does? 

Thanks alot!

**Comment by Namnodorel** [comment]
For the first one: If you want real combat including switching weapons etc. You'll need a custom Trait, like Sentinel (https://github.com/mcmonkey4eva/Sentinel). It will allow you to customize the combat of your NPCs.

**Comment by Nutty101** [comment]
You need to type **offhand** to put items into the second hand on an npc.  Also what Namnoderel said will fix the fighting portion.

I could very well be wrong, but I think the guided way-point will progress to the next point only when a player is in a certain range. Thus guided mode (Never used it myself).

**Comment by fullwall** [comment]
Guided waypoint provider means that it will only pathfind between points specified by the guided provider instead of trying to pathfind dynamically for itself.
