### ISSUE TITLE
Zombiemod and Skeletontype

### ISSUE THREAD

**Issue by doitliketyler** [CitizensDev/Citizens2#1015]
I previously had setup some NPCs as zombie husks and skeleton strays but now I'm getting these errors:

17.12 18:59:15 [Server] ERROR [Citizens] The trait skeletontype failed to load for NPC ID: 4.
17.12 18:59:15 [Server] ERROR [Citizens] The trait zombiemodifier failed to load for NPC ID: 4.

The previous commands I was suggested no longer either. Any ideas?

**Comment by Xenmai** [comment]
As of 1.11, each zombie and skeleton type are their own mob type. If your setup is from an older version, it might be the issue. So now you can adjust the mob type directly to husk without needing to make it a zombie and then change a modifier. Hope this helps.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

**Comment by doitliketyler** [comment]
Thats exactly what it was. Thanks so much!
