### ISSUE TITLE
Not working on 1.8.7 minecraft useing spigot

### ISSUE THREAD

**Issue by TechnicNetwork** [CitizensDev/Citizens2#1016]
In this issue, please include:
- 1.8.7 minecraft
- spigot 1.8.7
-bungee
i paied for the plugin and i put it on my server and when i do /pl it comes up red

**Comment by Nutty101** [comment]
What version are you trying to use? For that version you need to get older ones, as they only support 1.10>1.11 on 2.0.21.   2.0.20 was 1.10 if i recall.  

You will need to use the last 2.0.16 for that version if I recall. Check the link below for that version.
https://dev.bukkit.org/projects/citizens/files/901556

**Comment by mcmonkey4eva** [comment]
Alternately, this link: https://wiki.citizensnpcs.co/Versions lists the latest build for each version

**Comment by fullwall** [comment]
Also, bear in mind that modpacks generally don't work with citizens.
