### ISSUE TITLE
NPC Autoswitch/NPC Inventory/Dropping Diamonds {BUG}

### ISSUE THREAD

**Issue by Adamantyte** [CitizensDev/Citizens2#1017]
I'm using the latest version of citizens and sentinel with minecraft version 1.11 and I want my npc to switch from a sword to a bow when in combat. The sentinel at first will be equipped with a bow and a single arrow since I have /sentinel needammo set to false. Then I use /npc inventory to equip a sword. I've noticed when trying /npc inventory, if the npc is spawned, whatever you put in or take out will not work, the NPC must be unspawned to edit its inventory. So i kill the sentinel, run /npc inventory and equip a bow, arrow, and sword and it works. Respawn the sentinel and run /sentinel autoswitch and he begins switching weapons. The sentinel will shoot with the bow and arrow from a distance and when close enough, will use the sword and mellee. I then run /citizens save to save everything. But I notice after a server restart the sentinel becomes bugged and does not work. The sentinel frequently switches between the sword and a diamond for some reason. When I check his /npc inventory (while spawned) it shows he has only a sword equipped and another sword equipped in the last slot, as well as a diamond in his inventory. This is an issue because i dont want my sentinels dropping diamonds every kill. ALSO, when i am near the sentinel he will not shoot the bow or even melee attack until i kill it, fix his inventory and equip the bow and arrow back. If i dont do that, he will just wander around and only attack with the sword if i am directly near him, wont chase or anything. Anyone else have this  issue?

**Comment by michaeldriskell** [comment]
Im having this issue too. I cant edit any NPCs inventory. Im on the newest version of Spigot 1.12 and the lastest version of Citizens 2 as well.

**Comment by fullwall** [comment]
Probably a sentinel / citizens conflict, that may be fixed. @mcmonkey4eva can confirm

**Comment by mcmonkey4eva** [comment]
Should be fine on latest versions.
