### ISSUE TITLE
[Bug] Sometimes NPCs vanish

### ISSUE THREAD

**Issue by Brokkonaut** [CitizensDev/Citizens2#1021]
Sometimes NPCs are no longe visible, we had this happening with Cats, Polar Bears and Cows (but not with Player-NPCs or Villager-NPCs)

The NPC is no longer visible, but if I teleport to it (/npc tp), I go to the position where the NPC should be. If I teleport the NPC to me (/npc tphere), it is visible again.

Citizens: Build 1456
Server:  git-Paper-963 (1.11)

**Comment by TheWranger** [comment]
Getting this error as well, happening with my skeleton and zombie NPCs.

**Comment by MusicScore** [comment]
Can confirm that this bug exists on build 1420 on the latest Spigot 1.10.2 build. Currently cannot confirm on the latest build on either 1.10.2 or 1.11.
