### ISSUE TITLE
All NPCs walking North Look East.

### ISSUE THREAD

**Issue by Ditronian** [CitizensDev/Citizens2#1022]
On Spigot 1.11 and the latest development build as of this post (also on the latest stable release), all npcs walking north on paths have their heads locked facing sideways to the East.  Whilst walking any other direction, they are correctly looking dead ahead.

No errors are being thrown, and toggling /npc look on and off seems to have no effect on the bug.  We also tried setting a pose to try and keep the NPC looking straight ahead, but this also had no effect.

Thanks for all the hard work guys.

**Comment by mikroskeem** [comment]
Can confirm. all NPC-s are looking east.

`/version` output on my server:
```
This server is running Paper version git-Paper-"c8fb4667" (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
```

**Comment by fullwall** [comment]
Should be fixed

**Comment by mikroskeem** [comment]
Thanks :+1:! Keep up the good work and merry christmas! :) :gift: :christmas_tree:
