### ISSUE TITLE
Could not fetch entity id mapping fields

### ISSUE THREAD

**Issue by Classic36MC** [CitizensDev/Citizens2#1025]
I came across this today when loading my server, no idea what caused it. The NPCs are invisible but the sounds can still be heard.

_[09:51:39 INFO]: [Citizens] Could not fetch entity id mapping fields: Can not set static final net.minecraft.server.v1_11_R1.RegistryMaterials field net.minecraft.server.v1_11_R1.EntityTypes.b to net.citizensnpcs.nms.v1_11_R1.util.CustomEntityRegistry._

The NPCs don't become visible at all, I've tried /citizens reload; restarting my server and updating Spigot to the latest.

Minecraft/Spigot Version: 1.11.2
Citizens version: 2.0.21 Build 1461

**Comment by fullwall** [comment]
Which plugins are you using?

**Comment by Classic36MC** [comment]
Running Java 8. Only occured after I added HeadPets and GadgetsMenu to my server. About to do some testing though.

**Comment by Classic36MC** [comment]
Resolved - caused by HeadPets.
