### ISSUE TITLE
NoSuchMethodError: nms.v1_11_R1.EnchantmentManager.a(Lnms/v1_11_R1/EntityLiving;)I

### ISSUE THREAD

**Issue by mikroskeem** [CitizensDev/Citizens2#1027]
[Stack trace](https://paste.nightsnack.cf/raw/rihomasaxi)  
Server version: `This server is running Paper version git-Paper-"ebeab924" (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`  
Citizens2 version: `Citizens v2.0.21-SNAPSHOT (build 1462)`

Testing same thing on Spigot:  
[Stack trace](https://paste.nightsnack.cf/raw/uvuxodizol)  
Server version: `CraftBukkit version git-Spigot-7d78b81-0fb3f8b (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT`

Happened when I spawned skeleton with golden sword in hand (`npc.getTrait(Equipment.class).set(EquipmentSlot.HAND, new ItemStack(Material.GOLD_SWORD, 1));`)

_EDIT: Added information about Spigot too._

**Comment by fullwall** [comment]
Fixed
