### ISSUE TITLE
All citizens dev builds after 2016/Nov/26 consume too much CPU

### ISSUE THREAD

**Issue by Eredrim** [CitizensDev/Citizens2#1029]
All my problem description is in the title. Citizens consume too much CPU. When I hit mobs, they fall step by step (lag). The latest version which works for me is the latest release. There is no trace in logs.
Problem is the same with Spigot 1.11 and Spigot 1.11.2
I tried to start the server only with citizens, and the problem still the same. So it is well a Citizens problem.

**Comment by mcmonkey4eva** [comment]
Can you narrow it down to a specific build # from http://ci.citizensnpcs.co/job/Citizens2/

**Comment by fullwall** [comment]
Can you use any plugin like MassiveLag to get more accurate timings on where this is happening?

**Comment by Eredrim** [comment]
Really strange. After to be victim of this bug during 3 weeks, I can't reproduce it. I'm really sorry.
