### ISSUE TITLE
Request:  Ability to set a destination without a pathfinder

### ISSUE THREAD

**Issue by Nutty101** [CitizensDev/Citizens2#1030]
Not sure if this is an option. is it or would it be possible to set a destination (1 or 2 blocks away) with out the use of the pathfinder? Since I am already finding my own path, it's kinda redundant to re-find a path.  I have been tempted to build a navigator but that would cause more issues with other citizens plugins that rely on looking at the is-navigating portion of the NPC navigator to see if the NPC is busy.

**Comment by fullwall** [comment]
Why not just move the NPC yourself? Currently this is exposed via NMS.setDestination but can think of a way to put it into the Navigator API a little better.

**Comment by Nutty101** [comment]
I had toyed with that, but never got it working right.  If i recall i needed to set more items to make it work, yaw etc. Will look at it again tomorrow, brain is toast tonight. Thanks again.
