### ISSUE TITLE
NPC's in tablist are not shown in alphabetical order, but a vanilla tablist would be.

### ISSUE THREAD

**Issue by 2F4Uof2b2t** [CitizensDev/Citizens2#1031]
Adding NPC's to the world and changing the config to have them show up on tablist works fine, but they are not shows in-order from A-z.

Is this intentional? If it isn't, can it be fixed?

**Comment by mcmonkey4eva** [comment]
I would recommend just ... not having them show up on the tablist.
The option is only there as a temporary measure until some issues are fixed.

If you're trying to fake there being players online, that's a good way to get blacklisted by Mojang.

**Comment by fullwall** [comment]
I believe tablist order is clientside anyway.
