### ISSUE TITLE
Server Crashes Every Time I Warp to a Location

### ISSUE THREAD

**Issue by TheLastBlockbender** [CitizensDev/Citizens2#1032]
I know that the issue is with Citizens because I tried all the other plugins and this one caused the crash. I'm not sure if there is a corrupt entity in the area or not near the location of the warp.
This is a bug description:
Here's the error:
https://hastebin.com/yezogehari.md
Here's the config:
https://hastebin.com/urufukiduv.swift
Minecraft version: 1.10.2
Citizens version: 2.0.21-SNAPSHOT

**Comment by mcmonkey4eva** [comment]
It looks like you either have a corrupt chunk, or an NPC pathing into too high a distance. (IE it's loading too many chunks just trying to calculate a path)

The error is in chunk loading, but specifically chunk loading induced by an NPC calculating its path.

**Comment by TheLastBlockbender** [comment]
Ok I fixed it, thank you sooo much! I would have never found it:)
