### ISSUE TITLE
citizens generating way too many exceptions

### ISSUE THREAD

**Issue by mpld15** [CitizensDev/Citizens2#1037]
i seem to be having a bug on my server with citizens, im getting this error roughly ten times a second:
[22:15:37 WARN]: [Citizens] Task #12023 for Citizens v2.0.21-SNAPSHOT (build 1437) generated an exception
the version is in the error. because of getting this error so much i am unable to use console as it is lagging it out. please fix or send me a message on how to fix it!
       
                                             -Mpld

**Comment by fullwall** [comment]
Please paste the full exception and reopen the issue
