### ISSUE TITLE
Weird pathfind 1.9 > 1.11

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1038]
Hello!

I'm currently working with a minigame called ZombieSurvival I use Citizens2 to setTarget at the players. I have noticed a weird pathfinding bug in 1.9 > 1.11 because this bug did not exist in 1.8(If I run the minigame at spigot 1.8 and a supported citizens version the bug does not appear).

**Bug:**
Let's see if I can explain this...
If I stand on the second floor, the zombie rather chooses to be at the first floor but as near me as possible. Picture: https://i.gyazo.com/6b338a1ea77ef2a76130fcce26018c7a.jpg

Why doesn't he walks around the house, up the stairs and to me because the setTarget is aggressive. Screeenshots: https://i.gyazo.com/9a670fc2c826ce05649b16c729147405.png
https://i.gyazo.com/478f8d68175254ba2a340346253286ed.png
https://i.gyazo.com/99a3d7a0ebbeedaa8179e3a717d7947b.png

When the zombies stays under me instead of walking up to me: https://i.gyazo.com/8c988dbf788a300f431066484f880aff.png

Maybe I need to add something to my code to prevent this? Because I had to add stuckAction to prevent the teleporting (which wasn't an issuse in 1.8 as well).

Little bit of my code:
`						npc = registry.createNPC(EntityType.ZOMBIE, "Zombie");
						npc.spawn(loc);
						np = npc.getNavigator().getDefaultParameters().stuckAction(null);
						np.updatePathRate(10);
						np.range(180);
						np.stuckAction(null);
						npc.setProtected(false);`

**Comment by Namnodorel** [comment]
Have you tried to set the PathFindingRange higher? Maybe the zombie is unable to detect a better path because it may not scan on such a high range...

**Comment by File14** [comment]
@Namnodorel 
How to set it higher? I have set np.range(180) isn't that enough?

**Comment by File14** [comment]
"Maybe the zombie is unable to detect a better path because it may not scan on such a high range..."

Well, is it possible in 1.8 so why not now then?...

**Comment by File14** [comment]
@fullwall Any ideas?

**Comment by fullwall** [comment]
Can you try with the new pathfinder?

**Comment by File14** [comment]
The new pathfinder is very buggy. https://i.gyazo.com/fed28720683b602c8ec1ebf2923fc4ea.gif

**Comment by File14** [comment]
@fullwall Can you tell me why it's broken in the 1.9 > 1.11 but not in 1.8?

**Comment by fullwall** [comment]
@File14 probably because Minecraft's pathfinder changed and became more complex in 1.9.

**Comment by File14** [comment]
@fullwall ah ok, so you didn't make this path finding system?

**Comment by fullwall** [comment]
@File14 the new pathfinder is from Citizens, the old one is Minecraft's. There seems to be some bugs with stairs with the old one. The new one should pathfind properly but it still uses Minecraft's movement system so there are some  bugs with the spinning. If you turn on pathfinding debugging you should see if it's working or not.

**Comment by File14** [comment]
@fullwall ah ok. But let's say you do fixes. Then your fixes will only be made for 1.11 right? Becuase people are using my minigame from 1.8 > 1.11 :/

**Comment by fullwall** [comment]
@File14 I can fix it for 1.10 and 1.11.

**Comment by File14** [comment]
Ok hmm
