### ISSUE TITLE
[BUG]Cant set npc type

### ISSUE THREAD

**Issue by adamwbb** [CitizensDev/Citizens2#1039]
#CRITICAL BUG

-Issue
Unable to set npc type to any mobs game outputs : 
Java.lang.IllegalArgumentException: Unsupported Entity Type  (insert hostile mob name here)

- Console Log
10.01 02:40:32 [Server] INFO adamwbb issued server command: /npc type zombie
10.01 02:40:32 [Server] WARN java.lang.IllegalArgumentException: unable to find valid entity superclass for class class net.citizensnpcs.nms.v1_11_R1.entity.ZombieController$EntityZombieNPC
10.01 02:40:32 [Server] WARN at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.registerEntityClass(NMSImpl.java:745)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.util.NMS.registerEntityClass(NMS.java:180)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.<init>(AbstractEntityController.java:16)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.nms.v1_11_R1.entity.MobEntityController.<init>(MobEntityController.java:21)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.nms.v1_11_R1.entity.ZombieController.<init>(ZombieController.java:26)
10.01 02:40:32 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10.01 02:40:32 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10.01 02:40:32 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10.01 02:40:32 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
10.01 02:40:32 [Server] WARN at java.lang.Class.newInstance(Class.java:433)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.npc.EntityControllers.createForType(EntityControllers.java:20)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:158)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:1842)
10.01 02:40:32 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.01 02:40:32 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10.01 02:40:32 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.01 02:40:32 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:483)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
10.01 02:40:32 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
10.01 02:40:32 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
10.01 02:40:32 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
10.01 02:40:32 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
10.01 02:40:32 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
10.01 02:40:32 [Server] WARN at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
10.01 02:40:32 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
10.01 02:40:32 [Server] WARN at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
10.01 02:40:46 [Multicraft] Skipped 36 lines due to rate limit (30/s)

-Versions
Spigot 1.11.2
Citizens 2.0.21 SNAPSHOT
Issue persists on all builds form late december 2016 to January 7 2017

**Comment by mcmonkey4eva** [comment]
Can you provide a list of active plugins?

**Comment by adamwbb** [comment]
AsyncWorldEditInjector, CoreProtect, dynmap, WorldEdit, MOTDChange_By_Yapperyapps, HealthBar, Essentials, AdminFun_By_Yapperyapps, Lift, PlugMan, godPowers, WorldGuard, AsyncWorldEdit, DragonDeaths, SlimeMobs, EssentialsProtect, Stargate, EditableSign, EssentialsGeoIP, EssentialsChat, Barrels, EssentialsAntiBuild, PermissionsEx, BroadcastPlugin_By_Yapperyapps, CS-CoreLib, CreeperHeal, ViaVersion, Stats, Vault, BloodMoon, MassiveCore, EnjinMinecraftPlugin, CreativeGates, Trading, PlotSquared, WorldSpawn, Multiverse-Core, SeparateWorldItems, Citizens, Multiverse-NetherPortals, SensibleToolbox

**Comment by fullwall** [comment]
Looks like a plugin conflict, try disabling plugins that edit entities one by one.
