### ISSUE TITLE
Spawning a Baby Zombie?

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1040]
Hello,

How to spawn a Baby Zombie using the API? I can only spawn a normal zombie and I cannot cast it in the Ageable because then I'll get an error. Is there a way to setBaby in Citizens API?

**Comment by mcmonkey4eva** [comment]
Give it the Age trait: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/Age.java

**Comment by File14** [comment]
Ok, thanks! :)

**Comment by ScuroK** [comment]
What should i do after adding the trait? I didnt find anything in the wiki :(
