### ISSUE TITLE
I Made an npc called &e&ltest ~ ~ ~ benzix plots and now my name is stuck as that on tab and my nametag!

### ISSUE THREAD

**Issue by Benzix123** [CitizensDev/Citizens2#1043]
Hi, this is a bug i made an npc called &e&ltest ~ ~  ~ Benzix plots and even tho i despawn the npc on tab and in minecraft my nametag is still &e&ltest ~ ~  ~ Benzix plots :( please tell me how to fix this bug :( (i already tried deleting and reinstalling the plugin) thanks! -Benzix
My Server: benzixnetwork.mcpro.co
Version: 1.11.2

**Comment by mcmonkey4eva** [comment]
Scoreboard issue: find and delete the scoreboard.

Alternately, create a new NPC labeled with `&f`'s with benzix in the right spot to trick the system into overriding one scoreboard with the other.

**Comment by Benzix123** [comment]
Ok thanks i'll try that :)

**Comment by Benzix123** [comment]
nope :( that didn't seem to work... so how do i delete the scoreboard?

**Comment by mcmonkey4eva** [comment]
`/scoreboard` command ... work from there, it won't be pretty.
Could potential find your scoreboard data file and delete it if you don't use scoreboards already.

**Comment by Benzix123** [comment]
i have never used any scoreboards... so what should i do?

**Comment by mcmonkey4eva** [comment]
Shutdown the server,
locate and delete the file 'scoreboard.dat' (likely within your main world folder) (EG, `server/world/data/scoreboard.dat`)
then restart the server

**Comment by Benzix123** [comment]
ok but i'm not on the main world i'm on the world plots

**Comment by mcmonkey4eva** [comment]
Then same concept but for that world.
or all worlds.

**Comment by Benzix123** [comment]
when i go into the Data folder it's just stronghold.dat and village.dat

**Comment by Benzix123** [comment]
but in my world folder there is a scoreboard.dat (i deleted it)

**Comment by mcmonkey4eva** [comment]
![Scorebard](http://i.imgur.com/OTlZHCG.png)
http://i.imgur.com/OTlZHCG.png
^ don't know what to tell you if that file's missing...

**Comment by mcmonkey4eva** [comment]
... or it got misplaced. Alright then. Should be fixed now once you restart

**Comment by Benzix123** [comment]
ok restarting now

**Comment by Benzix123** [comment]
Thanks a ton! it's fixed :D if you ever decide to play on my server i will give you a dev rank!
