### ISSUE TITLE
EnderDragon Control Issues

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1045]
Hello,

Is it possible to setPhase on the EnderDragon using Citizens API? And is it possible to make the dragon destroy blocks?

- File14

**Comment by mcmonkey4eva** [comment]
You can interact with the dragon as if it were a regular entity, but AI is not going to work for an NPC... disabling default AI is the entire point of NPCs!

**Comment by File14** [comment]
hm okay

**Comment by File14** [comment]
I tried to make the enderdragon go slower using baseSpeed/speed but it made the Enderdragon to spin around really weird, is it possible to fix?

I also tried with Slowness potion but that didn't do anything.

**Comment by fullwall** [comment]
Fixed
