### ISSUE TITLE
Npc freezes and console spam + Crazy flying - Bug

### ISSUE THREAD

**Issue by xBiscuit** [CitizensDev/Citizens2#1046]
Npcs are moving around or going into water, and randomly they freeze and console gets spammed with this http://pastebin.com/fbBx6HbT
Minecraft version 1.11.2
Citizens version 2.0.21-SNAPSHOT (build 1465)
Thanks
Flyable also makes the citizen go crazy... It doesn't fly at all. It ends up teleporting around and freezing.. weird..

**Comment by fullwall** [comment]
Spigot version?

**Comment by fullwall** [comment]
Latest build should help

**Comment by xBiscuit** [comment]
thanks mate, also my minecraft version is my spigot version, but its probably too late for that
Thanks 👍

**Comment by xBiscuit** [comment]
Also, I know AI is hard to work with, but even with the new AI, npcs are scared to fly.. Even if they have flyable and gravity off, they stay on the ground going in circles while i'm on top of a tree. Is it possible to change their ai in such a manner that they can be airborne all the time? fly up a tree if it has to? Idek, thanks in advance anyways 👍

**Comment by xBiscuit** [comment]
Ill put that in a new issue
