### ISSUE TITLE
Player looks up immediately after killing other player.

### ISSUE THREAD

**Issue by midnjerry** [CitizensDev/Citizens2#1048]
Bug Description

I noticed killing other players (not NPCs) would force my head to look directly up... especially when landing head shots on my opponent.

I found Citizens was one of the plugins using an onPlayerDeath handler.  After disabling Citizens I no longer looked up after killing an opponent.  When I re-enabled it, I started looking up again.

I'm using SPigot 1.11.2 - Citizens2 2.0.21 Snapshot

**Comment by mcmonkey4eva** [comment]
This *shouldn't* happen (at least not directly caused by Citizens) on current versions
