### ISSUE TITLE
Can't find a single working 1.9.4 version

### ISSUE THREAD

**Issue by infered5** [CitizensDev/Citizens2#1049]
I'm trying to find a version of Citizens to work with Spigot 1.9.4

Tried many verisons of both Citizens and Spigot, as of right now I'm using Citizens-2.0.21-SNAPSHOT on Spigot version git-Spigot-798f32d-0cd0397 MC: 1.9.4
API version 1.9.4-R0.1-SNAPSHOT

Below is the error logs I get, regardless of citizens or Spigot version. Must be 1.9.4, the citizens version can be anything and it can be any spigot 1.9.4.

What's the most stable combination?

`
17.01 14:26:44 [Server] INFO Enabling Citizens v2.0.21-SNAPSHOT (build 1464)
17.01 14:26:44 [Server] ERROR v2.0.21-SNAPSHOT (build 1464) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.
17.01 14:26:44 [Server] INFO Disabling Citizens v2.0.21-SNAPSHOT (build 1464)
17.01 14:26:44 [Server] INFO Enabling Shopkeepers v1.72
17.01 14:26:44 [Server] ERROR Potentially incompatible server version: v1_9_R2
`

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Versions
