### ISSUE TITLE
Config restarting

### ISSUE THREAD

**Issue by sharkybushbaby** [CitizensDev/Citizens2#1050]
Like a couple people Im having issues with NPCs walking down and upstairs. (or any block that takes them to another level stair, slab ,block) and also with them Activating plates and going through open doors. (not fences for some reason)
I Have Changed my "new path finder" to true. as Ive seen has been an "thing" with 1.11 latest.
pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    new-finder-open-doors: true
    attack-range: 3.0625
    use-new-finder: true

But when I restart my server or Start my server it goes back to original config where its set to false?

Any advice please. 

im running bukkitserver 1.11.2
and citizens 2.0.21

thanks for your time.

**Comment by fullwall** [comment]
Try setting the config while the server is turned off.
