### ISSUE TITLE
Flyable is buggy

### ISSUE THREAD

**Issue by xBiscuit** [CitizensDev/Citizens2#1051]
With the new dev build, the flyable is a bit less glitchy (now he moves around a bit more), but theres a few things i would like to point out:
Flying is very fast (doesn't use the /npc speed value)
Flying is inconsistent (It likes to stay on the ground a lot)
It flies past the target location very fast, and then turns back... instead of flying at a steady rate towards target

These are just my observations.. Thanks for all your help!

**Comment by fullwall** [comment]
Is this still buggy? There were some bug fixes since this issue.
