### ISSUE TITLE
Protection state not working.

### ISSUE THREAD

**Issue by TheLimeGlass** [CitizensDev/Citizens2#1052]
**This works**
Boolean test = npc.isProtected();

**This doesn't work**
npc.setProtected(false);

Please check out the protection state method. I'm 99% sure it does nothing in the damage event. It's always in protected state for the damage event after spawning an Npc. This is critical for my server as I want to allow damaging for Citizens.

The value gets set but it never actually uses the protection state in the damage event or something. The protection state is false but still can't deal damage. Spawning a NPC from command and adding vulnerable works and allows for damaging, but using the API doesn't.

Also this only applies on PLAYER entity type citizens.

Spigot version: 1.11 R0.1 and same error with 1.11.2 R0.1
Citizens version: 2.0.21 Build 1464

**Comment by fullwall** [comment]
Can't reproduce this. Plugin conflict?

**Comment by TheLimeGlass** [comment]
There were no plugins. I don't think it happens anymore when you spawn a citizen, pretty late reply, but I think the API is still funky when handling protection stuff.

**Comment by fullwall** [comment]
The API is very simple, all it does is set the metadata value. 
`
        data().setPersistent(NPC.DEFAULT_PROTECTED_METADATA, isProtected);`

**Comment by TheLimeGlass** [comment]
When I tested it back in the day none of that stuff worked.
