### ISSUE TITLE
Wander mode broken

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1053]
I am trying to understand waypoints in wander mode. It appears to be broken = BUG.

Environment: Spigot 1.11.2 latest, Citizens 2.0.21-SNAPSHOT (build 1467), Sentinel 1.0 (build 90), and a full array of the usual plugins to support Multiverse.

Setup: I created a Citizens/Sentinel tamed wolf, inside a 10x10 box, min={ 10 3 10 }, max={ 20 3 20 }, walls too high to jump. I set waypoints=wander. I observed that the dog wandered, but in a very small area. I stopped the server and edited saved.yml to set the location at the center of the box { 15.5 3 15.5 } and wander.xrange=wander.yrange=7.

What happens: The dog wanders, but only in a 4x4 (approx) square in the NW corner of the box.

What should happen: I would like dog to wander the entire box. I do not find documentation for the wander nodes, so I'm not sure what I might change to achieve this. Any guidance appreciated.

**Comment by malonnnn** [comment]
I can attest to this.

https://www.twitch.tv/malonnnn/v/115424884

**Comment by fullwall** [comment]
Try latest build. Also added a text command you can use in /npc path

**Comment by SlimeDog** [comment]
Are there instructions for the path editor in wander mode?

**Comment by SlimeDog** [comment]
Spigot 1.11.2, Citizens build 1471. The dog still just wanders off. Relevant data from saves.yml
>       waypoints:
>         linear:
>           points:
>             '0':
>               location:
>                 world: world
>                 x: '-86.5'
>                 y: '69.0'
>                 z: '221.5'
>                 yaw: '-90.0'
>                 pitch: '0.0'
>         provider: wander
>         wander:
>           xrange: 7
>           yrange: 7
>       sentinel:
>         stats_ticksSpawned: 30388071
>         stats_timesSpawned: 2130
>         stats_arrowsFired: 0
>         stats_potionsThrow: 0
>         stats_fireballsFired: 0
>         stats_punches: 628
>         stats_attackAttempts: 2604
>         stats_damageTaken: 7.497600088119507
>         stats_damageGiven: 489.7479998469353
>         range: 20.0
>         damage: -1.0
>         armor: -1.0
>         health: 20.0
>         ranged_chase: false
>         close_chase: true
>         invincible: false
>         fightback: true
>         attackRate: 30
>         healRate: 30
>         guardingUpper: 0
>         guardingLower: 0
>         needsAmmo: false
>         safeShot: true
>         respawnTime: 100
>         chaseRange: 100.0
>         enemyDrops: false
>         enemyTargetTime: 0
>         stats_snowballsThrown: 0
>         stats_eggsThrown: 0
>         stats_skullsThrown: 0
>         stats_pearlsUsed: 0
>         attackRateRanged: 30
>         speed: 2.0
>         greet_range: 10.0
>         autoswitch: false
>         accuracy: 0.0
>         spawnPoint:
>           world: world
>           x: '-86.5'
>           y: '69.0'
>           z: '221.5'
>           yaw: '-90.0'
>           pitch: '0.0'

**Comment by malonnnn** [comment]
I can confirm this issue as well

**Comment by fullwall** [comment]
You want to use the x/y range as a limit. Tracking that usecase in this issue now https://github.com/CitizensDev/Citizens2/issues/1331
