### ISSUE TITLE
Citizens using a ton of resources in 1.9.4 compared to 1.8.8 [Bug]

### ISSUE THREAD

**Issue by andrewleppala** [CitizensDev/Citizens2#1054]
http://i.imgur.com/RfDzjce.png

Screenshot taken with the Top plugin, which greatly helps monitor resource use on servers.

Relevent plugin versions:

Spigot 1.9.4 R0.1 Snapshot (build#53)
Citizens 2.0.18-SNAPSHOT
Quests 2.7.4
MythicMobs 2.5.1
MythicLib 1.0.1

Ever since I began updating my server from 1.8.8 to 1.9.4, the Citizens plugin has been using a good 90%+ of my total resources. It is very low when there are no citizens present and my server has a great many of them. (50+). Since Citizens build 1308, has the save file for Citizens been changed or optimized in a way that is more efficient and I am simply using an outdated version?

All citizens are players, taking skins from Mojang's servers. This was not an issue in 1.8.8.

**Comment by fullwall** [comment]
Hmm... not really sure what that plugin is showing me. Can you use something like MassiveLag instead to provide more accurate information?
