### ISSUE TITLE
Wont allow to add Quests as a trait? 

### ISSUE THREAD

**Issue by ursuchamuggle** [CitizensDev/Citizens2#1055]
As a server owner, I want to add quests to a NPC, It doesn't allow me. I type /trait Quests and it replies with "Couldn't change Quests: Trait not found" What do I do?

**Comment by mcmonkey4eva** [comment]
... install a quests plugin?

**Comment by ursuchamuggle** [comment]
I installed the quests plugin, It doesn't work.

**Comment by mcmonkey4eva** [comment]
Then go talk to the quests plugin developers about it - something went wrong with that installation of quests plugin, and they'd be the ones to tell you what you're doing wrong.
