### ISSUE TITLE
BUG(?): Invalid plugin.yml

### ISSUE THREAD

**Issue by MitesMC** [CitizensDev/Citizens2#1056]
First found out of this issue when I noticed that Citizens wasn't appearing in my plugins list. Then after some digging, I found this also while restarting the server.

**Error log:** [https://pastebin.com/DXsd9UNV](https://pastebin.com/DXsd9UNV)
Running Minecraft 1.11.2 (Spigot)

Tried to check on the plugin.yml and this appeared:
http://imgur.com/QEguLZF

I've tried downloading earlier dev builds and never had any luck. Still getting the same error shown on the screenshot. I've even gone down to as far as the November builds. Stopped trying as it seems like the issue is still present even on earlier builds.

**Comment by mcmonkey4eva** [comment]
You have a corrupted zip file, please redownload it - potentially from an alternate source (bukkit | spigot | jenkins | ...)

**Comment by MitesMC** [comment]
Interesting to note that **all** versions/builds I downloaded from jenkins were corrupt. Maybe this is something that needs to be looked into. The one from Bukkit seems to be working fine. Thank you :)

**Comment by mcmonkey4eva** [comment]
yeah for some reason it's given a corrupt build to every 1 in a few thousand users for unknown reasons. You're one of the unlucky ones :/
