### ISSUE TITLE
Navigator instantly teleports

### ISSUE THREAD

**Issue by PYRRH4** [CitizensDev/Citizens2#1057]
Hi !

I'm trying to make a simple NPC moving, but it doesn't work.
Using versions : Spigot 1.11 and Citizens 2.0.21

My code :
```
NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, "Notch");
npc.spawn(location);
npc.getNavigator().setTarget(loc);
```

No errors in the console or anything else.
I'm probably misusing something, but I can't find my error. Please let me know :+1:

**Comment by mcmonkey4eva** [comment]
A teleport means the distance was too great and you need to increase the pathfinding range.

**Comment by PYRRH4** [comment]
Problem solved
