### ISSUE TITLE
Pathfinding bug that ruins npcs

### ISSUE THREAD

**Issue by GMoon777** [CitizensDev/Citizens2#1058]
With the new version of the path finding npcs do not follow a correct path through doors or round corners they simply teleport i.e. "Pop" through walls jump over things etc, this ruins immersion and looks really buggy, when switching back to the old path finding the npcs correctly go round corners and through tight spaces but cannot go up stairs or open doors, I am using the latest dev build of citizens with spigot 1.11.2, please could you fix the path finding! Thank you

**Comment by fullwall** [comment]
Can you screenshot the problematic path?
