### ISSUE TITLE
feature request: disable citizens & sentinel debug

### ISSUE THREAD

**Issue by NLBlackEagle** [CitizensDev/Citizens2#1059]
Hello,

I have tried to disable debug for citizens & sentinel but sadly did not found any way to do so. ( Here's an example of the log: https://hastebin.com/ayopuheluq.md

Sentinel Config: https://hastebin.com/cutejibuba.php
Citizens Config: https://hastebin.com/ureyoxocos.swift

I'm also using Denizen so if there is a way to counter this using denizen please tell me all about it!

Thanks and greetings, NLBlackEagle

**Comment by mcmonkey4eva** [comment]
None of that's debug, that's standard-rate command output.

If you're using a Denizen 'execute' command, use the "`silent`" argument.
