### ISSUE TITLE
Banners without basecolor will give fatal saves error

### ISSUE THREAD

**Issue by Rouchesta** [CitizensDev/Citizens2#1060]
Hi all,

A new problem appear on my server about Citizens.
the save.yml file is not yet updated by the plugin and generate an error (see image link).
When we try to create a new NPC, the save.yml is not updated... and at the next server restart it come back to the last save.yml file 3 days ago.

When i try to type this command /citizens save here is the result 👍 
Error : http://hpics.li/e164b6a
Minecraft Bukkit 1.10.2 and Citizens 2.0.21_Snapshot

Thank you for support.
Have a nice day.

**Comment by fullwall** [comment]
Can you pastebin your saves.yml?

**Comment by Rouchesta** [comment]
Thanks for the fast answer.
Here is the pastebin.

http://pastebin.com/f8JAyx50

**Comment by Rouchesta** [comment]
yes i did.
Is it aroblem ?

**Comment by mcmonkey4eva** [comment]
It looks like the banner or shield item you gave lacked a base color, and Citizens at the present time does not know what to do when the base color is entirely missing.
I'm not sure whether that'd be best classified as a bug with Citizens that it doesn't handle that, or simply erroneous input that Citizens should less fatally warn about.

**Comment by Rouchesta** [comment]
I removed the npc with banner and color and it now works again.
Thanks for support ;-)

**Comment by mcmonkey4eva** [comment]
I'd like to keep this issue open, as this needs a citizens-side fix:
Either:
- Handle the banner without basecolor neatly, or
- give a cleaner warning (non-fatal) when a bad banner is input

**Comment by mcmonkey4eva** [comment]
This was fixed :) 
Basecolor is now optional!
