### ISSUE TITLE
New Doc

### ISSUE THREAD

**Issue by Origonz** [CitizensDev/Citizens2#1061]
When i search i find tuto but it's old version, there are lot of commands who don't work because we have not the doc, so if you want i can do the doc if you give me code-source.
thanks for your plugin it's great !

**Comment by mcmonkey4eva** [comment]
Code source is right here. You're on the github page. Wat.

**Comment by Origonz** [comment]
where are command in code source ?

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/tree/master/main/src/main/java/net/citizensnpcs/commands
