### ISSUE TITLE
/npc create test --type vex (Vex does not stay in position, he moves into the ground)

### ISSUE THREAD

**Issue by i9hdkill** [CitizensDev/Citizens2#1062]
This server is running Paper version git-Paper-1042 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[01:59:52 INFO]: Checking version, please wait...
[01:59:53 INFO]: You are 1 version(s) behind

           =====[ Citizens v2.0.21-SNAPSHOT (build 1469) ]=====

Use /npc create test --type vex

Npc moves ~2 blocks into the ground after spawned for the first time.
Also happens after using /npc rename or citizens reload

Does not happen when using /npc tphere

**Comment by fullwall** [comment]
Fixed, although this disables gravity. If you think gravity is still important for Vex NPCs let me know, as there are some issues with how noclip is implemented for Vex NPCs.
