### ISSUE TITLE
Npc's appear on the tablist

### ISSUE THREAD

**Issue by timr2000** [CitizensDev/Citizens2#1063]
In this issue, please include:
- Using bungeetablist, lastest build, any fix for this?
- citizens config: http://pastebin.com/xTWZ4v5X
- Server version: 1.11.2

**Comment by fullwall** [comment]
You have tablist.disable set to true, try setting it to false?

**Comment by timr2000** [comment]
Then i've got this.. http://prntscr.com/e2qoyo

**Comment by comonier** [comment]
npc list
npc select <id>
npc tp
npc select
npc playerlist
done now u removed this npc from tablist.
