### ISSUE TITLE
Pathfinding issues lead to huge lags

### ISSUE THREAD

**Issue by SharkROAR** [CitizensDev/Citizens2#1068]
I'd like to report a bug that occured to us

![2017-02-01_00 21 21](https://cloud.githubusercontent.com/assets/1337229/22488741/0768a2b8-e814-11e6-9209-60d2690c02e1.png)

We are using Citizens v2.0.21-SNAPSHOT (build 1465) and the **new finder**.
The setting as seen on the screenshot causes massive server lags, probably because of the algorithm trying to figure out a way to the player.

After switching to the old finder, the lags were gone.

Also, Citizens seem to dislike stairs... They seem to get quite confused on them and can't reach the player. (However, this doesn't generage huge lags as the previous scene)
After removing the stairs seen in the picture, the NPC had no problem walking towards the player.

**Comment by fullwall** [comment]
What is your pathfinding range?

**Comment by lolzelig** [comment]
Exact same issue - Build 1481 and pathfinding range 25

**Comment by fullwall** [comment]
Added a new setting to allow you to control this issue.
