### ISSUE TITLE
Templates not working when the skin is a mob

### ISSUE THREAD

**Issue by malonnnn** [CitizensDev/Citizens2#1069]
/npc create 'magma' --type magma_cube
/template create magmacubetemplate

/npc create person
/template apply magmacubetemplate
/npc despawn
/npc spawn

This results in the "person" npc taking on the skin of "magma" and not looking like a magma cube.

Citizens2 build #1469

**Comment by malonnnn** [comment]
any chance this could be looked at soon?

**Comment by malonnnn** [comment]
I bought the premium version because this is such a great plugin!

**Comment by malonnnn** [comment]
Just hoping for some magic in this area

**Comment by fullwall** [comment]
Can you post your templates.yml?
