### ISSUE TITLE
Citizens appears red in my plugins list

### ISSUE THREAD

**Issue by Malembo** [CitizensDev/Citizens2#1073]
Dear Citizens Plugin Developers,
My name is malembo, also a developer, anyways, I tried to load citizens into my plugins list(with plugman) and everytime it comes in, it appears red and I can't do any of the commands. My server version is CraftBukkit 1.8.8 and everything is fine except for the plugin so, if you can give me some feedback about it, that would be awesome!

Kind Regards,
Malembo
Managing Deputy Director of MCLR and HoD

**Comment by mcmonkey4eva** [comment]
Don't use plugman, restart your server to recognize plugin changes.

**Comment by Ismail2004** [comment]
Same but i cant turn it green and im only ussing essentials litebans

**Comment by mcmonkey4eva** [comment]
Also ensure you have the correct version https://wiki.citizensnpcs.co/Versions
