### ISSUE TITLE
Who needs a cape?

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1076]
BUG: Spigot 1.11.2, Citizens 2.0.21-SNAPSHOT (build 1470)

I created a NPC with the following:
> npc type PLAYER
npc skin _myPlayerName_
npc rename Jack

It works exactly as expected. Looks just like me. :)
I copied it:
> npc select Jack
npc copy
npc rename Blue

Blue has a cape, with the letters OF on the back.

I copied it again:
> npc select Blue
npc copy
npc rename Red

Red does not have a cape. Questions:

- Where did the cape originate?
- How do I get rid of it?

**Comment by SlimeDog** [comment]
Yikes! Even though the NPC is wearing my skin, if I rename it Blue, it gets a cape. I would surmise that the real player Blue has a cape. But that should not affect the NPC. Can this be fixed?

**Comment by fullwall** [comment]
Use /npc skinlayers --cape false

**Comment by SlimeDog** [comment]
Thanks. Works like a charm.

BTW, **OF** is the _OptiFine_ donator cape.
