### ISSUE TITLE
NPCs spam Tablist

### ISSUE THREAD

**Issue by kobe686** [CitizensDev/Citizens2#1077]
So this has been an issue for me for many versions of citizens and minecraft but I still have the problem. I have 15 or so NPCs around my spawn and whenever you are around spawn, they spam in and out of the tab list. I have it disabled in the config too.

**Comment by mcmonkey4eva** [comment]
This is an oddity imposed on us by minecraft/mojang currently; not much we can do about it :/

**Comment by kobe686** [comment]
I figured as much but I recently played on another server and they used citizens but they didn't seem to have the issue

**Comment by kobe686** [comment]
And when I say recently, I mean a few minutes ago

**Comment by InkSurfer6V** [comment]
Im Having The Same Problem

**Comment by XLordalX** [comment]
Same issue, there are servers which have supposedly fixed it, so I doubt it's not fixable if even mc/mojang related.

**Comment by ediTv2** [comment]
Would like the proof that this is mc related... Cause there's actions that can be taken to prevent this issue from happening, but could actually attempt to look into the issue from a development point of view.

**Comment by fullwall** [comment]
Duplicate
