### ISSUE TITLE
Npc can't walk on slab

### ISSUE THREAD

**Issue by phloo75** [CitizensDev/Citizens2#1078]
This is a bug. My npc's can't walk down from any slabs. Nothing wierd in the console or anything 
I'm useing minecraft 1.11.2 and V2.0.21 -snapshot (Build 1470) citizens2 and i have tried the newest version from bukkit aswell (2.0.21 (MC 1.10-1.11.2))

https://gyazo.com/767db763df2a5d70682a24bcba3ffa64

- phloo75

**Comment by mcmonkey4eva** [comment]
try switching the `use-new-finder` setting in the config to the opposite of whatever it currently is

**Comment by fullwall** [comment]
Redirecting to #1171
