### ISSUE TITLE
Carpets cannot be equipped to Llama NPCs

### ISSUE THREAD

**Issue by Classic36MC** [CitizensDev/Citizens2#1080]
Carpets cannot be equipped to Llama NPCs with /equip. Instead, an error is returned in the console.

Error: http://pastebin.com/Ht3AwX5B

Citizens Version: Build 1471
Spigot Version: CraftBukkit version git-Spigot-b4417b8-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) - 3 versions behind

**Comment by Classic36MC** [comment]
@fullwall This is still an issue with the latest Citizens build & latest Spigot build.

**Comment by Pugabyte** [comment]
bump

**Comment by fullwall** [comment]
Check latest build

**Comment by fullwall** [comment]
Fixed
