### ISSUE TITLE
[Feature Request] Change shulker color

### ISSUE THREAD

**Issue by Eredrim** [CitizensDev/Citizens2#1081]
Hello,
Since Minecraft 1.11, it possible to change shulker color. Can you add a /npc shulker command as that exists for sheep ?

**Comment by gdavid04** [comment]
Shulkers don't have colors, only shulker boxes have. But shulker box is a block, not an entity.

**Comment by mcmonkey4eva** [comment]
Shulkers can actually change color.

**Comment by Eredrim** [comment]
There is a color tag for shulkers as you can here : http://minecraft.gamepedia.com/Shulker#Data_values

**Comment by fullwall** [comment]
Added
