### ISSUE TITLE
Citizens 2 not loading on my 1.8.8 server

### ISSUE THREAD

**Issue by Tigercraft01** [CitizensDev/Citizens2#1084]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

I was going to use Citizens2 and Command npc along side each other for a minigame that I will be running on my server. I have Spigot 1.8.8 and Citizens2 2.0.21 and have tried 2.0.17 and had the same result.

Here is a link to the citizens startup logs outputted by the console. [http://pastebin.com/nSKa3Get](http://pastebin.com/nSKa3Get)

**Comment by mcmonkey4eva** [comment]
You need 2.0.16 for that - https://wiki.citizensnpcs.co/Versions

**Comment by Tigercraft01** [comment]
Thank you for your help @mcmonkey4eva citizens2 works now.
