### ISSUE TITLE
/npc sit cmd has bug now

### ISSUE THREAD

**Issue by econowill** [CitizensDev/Citizens2#1085]
npc sit cmd has a bug like below!

a npc sits on a tip of the arrow!

![2017-02-20_11 18 56](https://cloud.githubusercontent.com/assets/7900163/23109663/7e0d42e4-f75e-11e6-9efd-6d9fb632a4e9.png)

**Comment by mcmonkey4eva** [comment]
Hahaha that's great. USe `/ex animate <npc> sit` instead of `/npc sit` to fix that.

**Comment by econowill** [comment]
hmm.... than how to toggle them?
to cancel sit?

**Comment by mcmonkey4eva** [comment]
It's either the same command repeated, or that with `unsit` or something weird like that.
