### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1087]
Hello,

Once I spawn a mob(npc), is it possible to set via the API so you can't push the mob? 

/File14

**Comment by Firemonkey08** [comment]
Did u try to set the gamemode 1? Or u could try to set vulnerable. Hope it helps, but I didn´t test it...

**Comment by File14** [comment]
@fullwall

**Comment by mcmonkey4eva** [comment]
They should be pushable when vulnerable, and not pushable when not.

**Comment by File14** [comment]
Is that possible to set using the API? If so, how?

**Comment by mcmonkey4eva** [comment]
I believe that's `npc.setProtected(bool)`

**Comment by File14** [comment]
Ok, I'll test that.

**Comment by File14** [comment]
Okay, so is it possible to just prevent players to push the mob. I know setProtected does this but I still want the player to be able to hit the npc. (Minigame)

Any thoughts? @fullwall

**Comment by File14** [comment]
Solved using NPCPushEvent.
