### ISSUE TITLE
NPCS dissapears on chunk unloads

### ISSUE THREAD

**Issue by ElixirCraft** [CitizensDev/Citizens2#1088]
In this issue, please include:
- NPCS dissapers on chunk unload (tested & verified that)
- No need link of config (while i disabled plugin for unloading chunks NPC wont dissapear anymore)
- paperspigot 1.8.8 (tried with spigot 1.8.8) same thing happens (citizens v2.0.16 build:1267)

**Comment by mcmonkey4eva** [comment]
We're minimally able to assist in such an old version.

Also, NPCs are supposed to go away on chunk unloads, entities aren't allowed to be in unloaded chunks...
