### ISSUE TITLE
Issues With /npc type and other MOB skins

### ISSUE THREAD

**Issue by InfernalAsh** [CitizensDev/Citizens2#1091]
Hello, Me and a friend run a spigot 1.11.2 server. NPC's work for players such as /npc create Infernal_Ash but as soon as you use /npc [player] --type [mob] it produces the mob as you can hear and edit it with commands but not visibly see it. Its a server side issue as I've tried from multiple desktops with multiple logins. Everyone can hear the npc but not see it. The same lack of visibility occurs when making a npc a player then using the /npc type [mob] command with that mob selected.

No errors or reports in the console, any ideas?

Many thanks,
Infernal

**Comment by mcmonkey4eva** [comment]
That could happen if you have a gamerule or plugin that blocks mob spawning.

It could also be caused by a plugin that does NMS work in an interfering way.

**Comment by InfernalAsh** [comment]
Thank you for the swift reply. I have only set firetick, weather tick and mob griefing to false. In terms if plugins apart from mythic mobs there aren't really any plugins that are involved in mob spawning. Not entirely sure what the cause can be? May try removing plugins one by one if you think that's best?

Infernal

**Comment by mcmonkey4eva** [comment]
If you have a lot of plugins, do a binary removal (Remove half, then add back half of that half, or remove half of the remaining half) but yeah that basic concept.

**Comment by InfernalAsh** [comment]
Hello, the server is still being balanced out but to say we have a lot of plugins is a stretch in honesty. I believe we have 10 at the most including skullapi, permissions ex, mythicmobs (with its dependencies), quests, world edit, admincommands and hold signs. Can't see how they would cause an issue though. I'll try tommorrow if you still think it's a possibility.

Many thanks,

Infernal

**Comment by Dewmd66** [comment]
I am also having this exact issue, I have done a binary removal of my plugins already (you recommended this on another thread) and it did not fix it.

Plugin list:
AAC
Advanced Portals
Citizens
Enjin
Essentials Chat
EssentialsX
Factions
KeepChunks
Orebfuscator
PermissionsEX
Quests
Residence
Sentinel
SignShop
Vault
Worldedit
Worldquard.


@InfernalAsh do any of these plugins correspond with what you have installed?
