### ISSUE TITLE
fix the pathfinding bug

### ISSUE THREAD

**Issue by Volkenstein666** [CitizensDev/Citizens2#1092]
latest version everything
npc's can path up stairs but not down
tested on borg-picard
full video here - path debug enabled

http://www.dailymotion.com/video/x5dazhs

**Comment by mcmonkey4eva** [comment]
How DARE you use the account of the guy who stole my username D:<

**Comment by mcmonkey4eva** [comment]
What's your config, and that NPC's configuration?
