### ISSUE TITLE
Waypoint trigger bugs

### ISSUE THREAD

**Issue by Kyzderp** [CitizensDev/Citizens2#1093]
**Several issues:**
1. Triggers don't load upon plugin reload/server reload/server restart.
2. Delay triggers don't work, they make the NPC stop and never resume.
2.5. Delay triggers delay at the "wrong" waypoint.
3. Some text messages are messed up.
4. Unable to remove triggers.

**I tried this on several versions:**
- Citizens v2.0.21-SNAPSHOT (build 1472) on spigot-1.10.2-R0.1-b986 (has custom patch, but probably unrelated)
- Citizens v2.0.20 on spigot-1.10.2-R0.1-b986 (same as above, patched)
- I also forked the repo and tried compiling on commit 0c833e25668c4a695556605c5cd3b6869d9f77dc, which was right before the 1.11 additions, and ran this on spigot-1.10.2-b945

**Issue 1:** Triggers don't load upon plugin reload/server reload/server restart.
They do get saved in saves.yml, but they aren't loaded, and when the next save occurs it's no longer in the file.

Steps to reproduce:
- /npc path
- create a path
- "triggers > add > speed > 2"
- speed trigger works fine
- /citizens save
- check saves.yml, the speed trigger will be there
- /citizens reload
- NPC no longer has the speed trigger
- /citizens save
- check saves.yml, speed trigger no longer there

**Issue 2:** Delay triggers don't work, they make the NPC stop and never resume. If they didn't do that, they delay at the "wrong" waypoint sometimes.
The delay triggers didn't work at all with v2.0.20 and v2.0.21, they made the NPC stop at the waypoint. I then tried compiling 0c833e25668c4a695556605c5cd3b6869d9f77dc, I don't remember if the NPC stopping happened in the beginning already, but I know I got it to work after I made changes to LinearWaypointProvider, which was to reduce the "within range" threshold to 2 in .locationWithinRange(). However, it would sometimes pause on the wrong waypoint. I added debug statements in setPaused() and figured out that the pause was getting called multiple times at the waypoint.

As an example, if I made 3 points, the NPC will run 0 -> 1 -> 2 -> 0 -> 1 etc. If I set a delay of 100 ticks on point 0, when the NPC runs from 2 -> 0 and reaches 0 it will pause. But sometimes it will pause again while still there, which results in a pause of double the intended time. Other times, it will pause normally, but then as it runs from 0 -> 1 it gets the pause again, which results in pausing for 100 ticks at point 1 as well. Excerpt of logs with the debug statements:

```
[01:38:50] [Server thread/INFO]: pause
[01:38:55] [Server thread/INFO]: pause
[01:38:55] [Server thread/INFO]: resume
[01:39:00] [Server thread/INFO]: pause
[01:39:00] [Server thread/INFO]: resume
[01:39:05] [Server thread/INFO]: pause
[01:39:05] [Server thread/INFO]: resume
[01:39:10] [Server thread/INFO]: pause
[01:39:10] [Server thread/INFO]: resume
[01:39:15] [Server thread/INFO]: pause
[01:39:15] [Server thread/INFO]: resume
[01:39:20] [Server thread/INFO]: resume
[01:39:20] [Server thread/INFO]: pause
```

After letting that run for a few minutes, I think eventually the scheduled tasks got so messed up that the NPC was pausing even at point 2 too, or it was just me not paying enough attention to where it was stopping. I suspect that the issue with the delay trigger in v2.0.20 and v2.0.21 is that the NPC just keeps getting paused on the same point so it never moves.

**Issue 3 and 4:** Some text messages are messed up. Unable to remove triggers. This is on v2.0.21, did not try on other versions.
This is what shows when I am in trigger editor and have added a trigger:

Entered the waypoint trigger editor.
	Type add to begin adding triggers and remove to remove triggers.
	Type triggers to enter the waypoint trigger editor.
	Current triggers are:
	- Speed change to 1.000000

- Typed "remove"

?citizens.editors.waypoints.triggers.remove.promptEnter in the index of the trigger to delete or back to return to the edit prompt. Current triggers are:
	1. Speed change to 1.000000?

- Typed "1"

Index must be in the range 1-1.

Trying to remove "1" from a list of 2 triggers also doesn't work, tells me that 1 is not in the range 1-2. The remove prompt is one of the unlocalized texts, I think there's at least one other somewhere but I don't remember where.

**Comment by fullwall** [comment]
@Kyzderp Most of these should be fixed in the latest build.

**Comment by Kyzderp** [comment]
Sorry um, am I missing something? You said latest build but I don't see an updated build on Jenkins, the latest one is Feb 23? Thanks for the very quick reply btw.

**Comment by mcmonkey4eva** [comment]
Sorry about that confusion, need build pushed through. Jenkins build 1473.

**Comment by Kyzderp** [comment]
Everything works, thanks!
