### ISSUE TITLE
There is no compatible version for 1.9.4 (Minecraft v1_9_R2)

### ISSUE THREAD

**Issue by enight0000** [CitizensDev/Citizens2#1095]
[Citizens] v2.0.21-SNAPSHOT (build 1463) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.
[Citizens] v2.0.19-SNAPSHOT (build 1374) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.

**Comment by mcmonkey4eva** [comment]
1.9 is really old, you need 2.0.18 https://wiki.citizensnpcs.co/Versions

**Comment by enight0000** [comment]
Thanks!
