### ISSUE TITLE
NPC's duplicate upon reload

### ISSUE THREAD

**Issue by Plasmacytic** [CitizensDev/Citizens2#1096]
**Bug Report**

For some reason whenever I reload using **/citizens reload**, for two of my NPC's (Players Plasmacytic and Krazykree24), they always replicate themselves. So even after i delete the ones I don't need, if i reload they just duplicate again so I have 3 Plasmacytics standing inside eachother at different positions, and 2 krazykree24's standing inside eachother at different positions.
Possible fix?

Not sure if its relevant but:
Server log: http://pastebin.com/HTp78QFb
Citizens Config: http://pastebin.com/xtKfCdB3
Minecraft Version: Craftbukkit 1.11.2
Citizens Version: 2.0.21-SNAPSHOT (build 1473)

**Comment by RickyB98** [comment]
I was about to report this issue, too. Running on build 1463.

**Comment by crazyhorse961** [comment]
Could it be releated to my one i guess? https://github.com/CitizensDev/Citizens2/issues/1102

**Comment by RickyB98** [comment]
I worked around the issue by creating a registry for my plugin and only creating a new NPC if it was not in that registry first. But previously it just spawned multiple NPCs one on top of the other.

**Comment by mcmonkey4eva** [comment]
Check for errors in log files. If you find any, post them. Also consider avoiding using `/citizens reload` command in general.

This issue could also be a plugin conflict if it's happening to specific NPCs (what makes those NPCs special? Perhaps some other plugin is interacting with them for some reason)

**Comment by RickyB98** [comment]
The issue is quite old so I don't even remember what was going on, but what exactly is the point of a plugin reload command where its use is discouraged? Plugin reload commands should do what you expect them to do and they're there to replace `/reload`. Discouraging its use doesn't seem like a clean fix to it not working.

**Comment by RickyB98** [comment]
In my view, it's supposed to reload (perhaps respawning) the entities that are being used as NPCs, clear whatever cache, reload traits, etc. But if you really think it's useless then just remove it? I just don't see the point in discouraging the use of a feature, it leads to misunderstanding.

**Comment by mcmonkey4eva** [comment]
It can be useful in some cases.

... But those cases aren't relevant here, nor to most situations.
Respawning entities... yeah it does that. Why do you want that happening, outside of dev/debug stuff?
Clear caches/etc... yes... but why, other than dev/debug stuff?
Those aren't things you randomly do day-to-day as a normal user.

**Comment by RickyB98** [comment]
Not sure if the OG was talking as a normal user or as a developer. I think at the time my report was dev-oriented, hence why I didn't really understand why you were discouraging it.
