### ISSUE TITLE
"Premium" Spigot plugins

### ISSUE THREAD

**Issue by hiimgush** [CitizensDev/Citizens2#1099]
I'm not sure if you have a problem with this, but I feel it would upset me if I were to release something so vast only for people to add small functions to it and sell it for nearly $10 a pop.

https://www.spigotmc.org/resources/statusblock.2602/

Sorry if I'm coming off as hostile, it just seems so scummy to me.

**Comment by Namnodorel** [comment]
I don't think we can do anything about that. It's perfectly fine to use Citizens as a dependency for any project, if people pay ten bucks for something that small it's their problem... I mean, it's not like he's selling Citizens, just a small thing that he did with it.

**Comment by AnthonyAMC** [comment]
just... wow... i don't even feel bad for the idiots that actually pay for such a simple thing.

**Comment by fullwall** [comment]
Yeah, not much we can do about this.
