### ISSUE TITLE
[BUG?] NPCs staying on tablist, blank names. Stop responding to nearby players when this happens.

### ISSUE THREAD

**Issue by shilofax** [CitizensDev/Citizens2#1100]
Server Log: http://pastebin.com/8PESPvYr

Citizens Config: http://pastebin.com/utTNVeyA

After a server reboot. 15 Minutes or so passes, and this happens: https://gyazo.com/3939b9e77df08b51be0e05ea0bbeaf30

Npcs appear as players on the tablist, and stay put. (I know it's normal for them to flicker).

After this happens, no NPCs react to lookclose, seen here: https://gyazo.com/3c7d26437bbc0dda04ef02eab7fd620b

This also appears to break dynmap from updating. Any insight, or fix regarding this would be appreciated. I've tried Spigot and Paperspigot 1.11.2, using the latest dev builds, and latest recommended builds of citizens.

Thanks in advance.

**Comment by fullwall** [comment]
Do the NPCs have similar names?
