### ISSUE TITLE
NPC Reappearing (once deleted) after restart/citizens reload

### ISSUE THREAD

**Issue by crazyhorse961** [CitizensDev/Citizens2#1102]
Basically, you spawn a NPC, delete it and reload/restart, it reappears.
I do use spigot 1.11.2 and the latest dev build of citizens for 1.11.2

**Comment by MusicScore** [comment]
Have you tried using ```/citizens save``` before doing ```/citizens reload```? I've found that to be the cause of this kind of issue a few times.

**Comment by crazyhorse961** [comment]
Hello,
I didnt and ill soon test. 
Thank you

**Comment by crazyhorse961** [comment]
The problem still occurs

**Comment by gdavid04** [comment]
Try /reload
It reloads anything, but it has no problems like this.

**Comment by crazyhorse961** [comment]
Reload will broke plugins, and it's like doing /citizens reload & /citizens save
Thank you for the help tho

**Comment by gdavid04** [comment]
For me, it doesn't broke any plugins.

**Comment by mcmonkey4eva** [comment]
@gdavid04 `/reload` is very dangerous: haven't you ever read the warning that appears when you use it?!

**Comment by crazyhorse961** [comment]
I agree to @mcmonkey4eva , also, are you able to mark this as bug report and it has been fixed in dev builds?

**Comment by mcmonkey4eva** [comment]
@crazyhorse961 it's not necessarily a bug with Citizens, usually issues of this category are caused by other plugins or wholly invalid data being on an NPC. We'll need a lot more information before we can provide much help :/

I would recommend starting seeing if you can replicate this on a server without any other plugins, or with a fresh saves file.

**Comment by crazyhorse961** [comment]
I do only have 1 plugin incompatible with Citizens, i contacted that author and said that the plugin couldn't cause that.
Ill now test on a clean enviroment

**Comment by AaronMcHale** [comment]
We have the same issue, deleting an NPC, then doing /citizens save, then /citizens reload causes the deleted NPCs to re-appear

**Comment by mcmonkey4eva** [comment]
If you get any errors in console/logs, please do post them.
Otherwise, server restarts should suffice. (If a full restart also has the issue, there should definitely be an error somewhere in the log files!)
