### ISSUE TITLE
Citizens2 API setHealth?

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1103]
Hello,

is it possible to setHealth using the API of Citizens2? If so, how? :)

**Comment by mcmonkey4eva** [comment]
you would get the entity, and set the health of that.

If you want it to persist when not spawned, you have to make or use a trait.

Citizens does not have one itself, but Denizen comes with a Health trait.

**Comment by File14** [comment]
Ok thanks! @mcmonkey4eva
