### ISSUE TITLE
Citizens CustomEntityRegistry class overriding the RegistryMaterials class

### ISSUE THREAD

**Issue by brainsynder-Dev** [CitizensDev/Citizens2#1104]
Hello, I am the Developer of SimplePets. I am making this because people that download my plugin have been contacting me saying that Citizens is making the pets from my Pets plugin not show up. I did some research and found that its because Citizens is overriding the RegistryMaterials class. I would like to know if I should use your CustomEntityRegistry.class for when a server has Citizens and my plugin on it, or is there another way I could register my mobs without Conflicting?

**Comment by mcmonkey4eva** [comment]
I think the most modern method to register an entity is to do exactly the same trick Citizens is currently doing (more or less copypaste the code), as it should chain properly.
