### ISSUE TITLE
Path API?

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1105]
Hello,

Is it possible to set a path for a npc. I have a list of Locations and first I want the NPC to walk to the first path location, then second etc. Is there an API to do this? Instead of using setTarget(loc)

**Comment by Nutty101** [comment]
There might be other methods, but you need to make a WaypointProviderand/or BehaviorGoalAdapter and respond to the events to tell the NPC the next location to travel to.

**Comment by File14** [comment]
Hm ok. :)
