### ISSUE TITLE
API: Set NPCs skin using signature & control the NPCs arm

### ISSUE THREAD

**Issue by itpao25** [CitizensDev/Citizens2#1106]
Hi, i have two questions about the APIs of citizens. 

- How can i set the NPCs skin using the value "**Texture Value**" or "**Texture Signature**"?
(Example , using mineskin.org ). I would sets a skin, but I don't know any accounts that wearing this skin

- How can I control the NPCs arm? (For example, to raise the arm)

Thanks.

**Comment by Nutty101** [comment]
I bought a couple accounts just to hold my skins. Then i set them, log them and save. You need to have the UUID from the account to make it work (My assumption). Cause I have never had luck with just replacing the player-skin-textures and player-skin-signature from a different skin.

Not sure you can pose a PLAYER NPC type's arms, you can on the armor stand if I am correct.

**Comment by itpao25** [comment]
@Nutty101 If I change the skin of my account 
changing the skin will change even the NPC?
Is there a way to keep the skin version? (NPC will be deleted and recreated continuously)

**Comment by Nutty101** [comment]
Use /npc skin -p [accountname] and it will keep it for you.

**Comment by itpao25** [comment]
@Nutty101 I use the APIs to create the npc continuously

**Comment by Nutty101** [comment]
I'd use the command for that command as an example to code that. I do it in one of my plugins to switch skins on the fly.

`    @Command(
            aliases = { "npc" },
            usage = "skin (-c -p -f) [name]",
            desc = "Sets an NPC's skin name, Use -p to save a skin snapshot that won't change",
            modifiers = { "skin" },
            min = 1,
            max = 2,
            flags = "cp",
            permission = "citizens.npc.skin")
    @Requirements(types = EntityType.PLAYER, selected = true, ownership = true)
    public void skin(final CommandContext args, final CommandSender sender, final NPC npc) throws CommandException {
        String skinName = npc.getName();
        if (args.hasFlag('c')) {
            npc.data().remove(NPC.PLAYER_SKIN_UUID_METADATA);
        } else {
            if (args.argsLength() != 2)
                throw new CommandException();
            npc.data().setPersistent(NPC.PLAYER_SKIN_UUID_METADATA, args.getString(1));
            if (args.hasFlag('p')) {
                npc.data().setPersistent(NPC.PLAYER_SKIN_USE_LATEST, false);
            }
            skinName = args.getString(1);
        }
        Messaging.sendTr(sender, Messages.SKIN_SET, npc.getName(), skinName);
        if (npc.isSpawned()) {
            SkinnableEntity skinnable = npc.getEntity() instanceof SkinnableEntity ? (SkinnableEntity) npc.getEntity()
                    : null;
            if (skinnable != null) {
                skinnable.setSkinName(skinName, true);
            }
        }
    }`

**Comment by fullwall** [comment]
It's tricky, the API for skins is bad right now. You can get the skin signature/texture after it has been applied and store that if you want using the NPC metadata, or fetch it yourself. As Nutty101 said there's an example here: https://github.com/CitizensDev/Citizens2/blob/59f67c02b9d7e5da7923e91a9ae1da0db857ec8d/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L1453

I don't know if you can pose the arm directly, but you can swing it using PlayerAnimation if that's what you mean?

**Comment by MrDienns** [comment]
Bumping this. @fullwall @mcmonkey4eva, this is a must-have API functionality in my opinion. The API is lacking a pretty serious feature right now. For my own server, I'm constantly spawning NPC's through the API, and as I need to spawn dozens, and later on hundreds NPC's with different skins, it's obviously not an option to buy Minecraft accounts all the time, I simply want to use a texture and signature value. That way, we can re-use Minecraft accounts and their skins. NPC's aren't saved (persisted) to the config file either. I would kindly ask for this future to be added since the API is really lacking without it.

**Comment by Nutty101** [comment]
@MrDienns:  Not sure if this will help, but here is what I do. The API is actually there if you want to use it.

> 
                trait.getNPC().data().remove(NPC.PLAYER_SKIN_UUID_METADATA);
                trait.getNPC().data().remove(NPC.PLAYER_SKIN_TEXTURE_PROPERTIES_METADATA);
                trait.getNPC().data().remove(NPC.PLAYER_SKIN_TEXTURE_PROPERTIES_SIGN_METADATA);
                trait.getNPC().data().remove("cached-skin-uuid-name");
                trait.getNPC().data().remove("cached-skin-uuid");
                trait.getNPC().data().remove(NPC.PLAYER_SKIN_UUID_METADATA);

                // Set the skin
                trait.getNPC().data().set(NPC.PLAYER_SKIN_USE_LATEST, false);
                trait.getNPC().data().set("cached-skin-uuid-name", trait.currentLocation.player_Skin_Name);
                trait.getNPC().data().set("cached-skin-uuid", trait.currentLocation.player_Skin_UUID);
                trait.getNPC().data().setPersistent(NPC.PLAYER_SKIN_UUID_METADATA, trait.currentLocation.player_Skin_Name);
                trait.getNPC().data().setPersistent(NPC.PLAYER_SKIN_TEXTURE_PROPERTIES_METADATA, trait.currentLocation.player_Skin_Texture_Metadata);
                trait.getNPC().data().setPersistent(NPC.PLAYER_SKIN_TEXTURE_PROPERTIES_SIGN_METADATA, trait.currentLocation.player_Skin_Texture_Signature);

                if (trait.getNPC().isSpawned()) {

                    SkinnableEntity skinnable = trait.getNPC().getEntity() instanceof SkinnableEntity ? (SkinnableEntity) trait.getNPC().getEntity() : null;
                    if (skinnable != null) {
                        Skin.get(skinnable).applyAndRespawn(skinnable);

                    }
                }

**Comment by MrDienns** [comment]
@Nutty101 Really appreciate the help, however, the code seems to simply take the most recent skin of the player instead of using the texture & signature I specified. Could you add me on Discord? MrDienns#7809 I'll donate you some if you help me out fix it ;)

**Comment by fullwall** [comment]
An API was recently added to do this.
