### ISSUE TITLE
Zombie-Baby not possible anymore

### ISSUE THREAD

**Issue by ScuroK** [CitizensDev/Citizens2#1107]
Hello 

Im using Citizens on spigot 1.11.2. Before there was /npc zombiemod but it seems not there anymore.
if i add the age-trait i also cant change anything. So how can i actually make a baby-zombie??

Can you tell me the steps?

**Comment by mcmonkey4eva** [comment]
Look through the `/npc` commands, Iirc there's an `age` sub-command or something for that.

**Comment by ScuroK** [comment]
Not working. It tells me "mob {0} can not be aged"

**Comment by ScuroK** [comment]
pls test it yourself if you think im wrong

**Comment by fullwall** [comment]
Fixed
