### ISSUE TITLE
Citizens and PaperSpigot 1.9.4

### ISSUE THREAD

**Issue by Blueyescat** [CitizensDev/Citizens2#1108]
## **Description**
Citizens 2 not works with PaperSpigot
I tried with 3-4 versions of  #Citizens.

## **Server Log**
`[Thread-138/INFO]: [Citizens] Enabling Citizens v2.0.17-SNAPSHOT (build 1316)`
`[Thread-138/ERROR]: [Citizens] v2.0.17-SNAPSHOT (build 1316) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.`
`[Thread-138/INFO]: [Citizens] Disabling Citizens v2.0.17-SNAPSHOT (build 1316)`

## **Minecraft & Citizens Version**
`This server is running Paper version git-Paper-773 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)`

`Citizens v2.0.17-SNAPSHOT (build 1316) `

**Comment by mcmonkey4eva** [comment]
http://ci.citizensnpcs.co/job/Citizens2/1371/ 
Need this version ^ for 1.9.4 MC

**Comment by Blueyescat** [comment]
Working! Thanks!
