### ISSUE TITLE
Doesent Work On Modded Server?

### ISSUE THREAD

**Issue by AcelaKing** [CitizensDev/Citizens2#1110]
Im not sure if this is a bug, however I am using KCauldron 1.7.10.  No Citizens version I try works.  If need I can include more detail later.  Any ideas?

**Comment by mcmonkey4eva** [comment]
Tried the unofficial Cauldron version?
 https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by litjohn50** [comment]
Hi mcMonkey 

The DropBox link does not work anymore.

**Comment by mcmonkey4eva** [comment]
This is supposedly a valid link for it: 

Https://www.dropbox.com/s/rs4n0i51mwxze9u/citizens-2.0.13-1.7.10-Cauldron-B1.jar
