### ISSUE TITLE
config

### ISSUE THREAD

**Issue by sharkybushbaby** [CitizensDev/Citizens2#1111]
I posted this back in January too. didnt get anything.  ANYTHING would be an answer

The config resets itself after i edit it. 
stopped server. edited, saved... start server... config reverts back.

even when i delete it. edit it externally and upload edited version. still reverts back.
version 
2.0.21 snapshot. on 1.11.2

**Comment by mcmonkey4eva** [comment]
Config should only revert if the config file was editing while server running, or there was an unrelated FTP type of error, or there was an error in the config file's text.

**Comment by sharkybushbaby** [comment]
The server was 100% stopped. 
and the only changes made were this. ..

pathfinding:
    default-distance-margin: 2
    update-path-rate: 50
    new-finder-open-doors: true
    attack-range: 3.0625
    use-new-finder: true

**Comment by mcmonkey4eva** [comment]
I don't know what to tell you. Citizens cannot revert a config when the server is not even running. it's likely something else in your setup is broken (FTP / server management / etc)
