### ISSUE TITLE
Creating NPC Problem

### ISSUE THREAD

**Issue by BiGUNMAN** [CitizensDev/Citizens2#1113]
When I type /npc create, I get the following issue:
http://i.imgur.com/rvVZJX9.png

/npc help gives me no permissions:
http://i.imgur.com/7p3mlme.png

I use LuckPerms, but my account also has OP.
All my commands work other then creation and help apparently, I can tp, change types, etc.

- Minecraft & Citizens version if relevant
http://i.imgur.com/wnulGFv.png

I tried most recent Citizens (dev build), and the SpigotMC build.

I've created NPCs before on my server, so this issue makes no sense to me.

**Comment by mcmonkey4eva** [comment]
You somehow don't have permission to use the commands. Either you're not properly Op, or your permission plugin is overriding that. Either way, try giving yourself citizens permissions in the plugin.

**Comment by BiGUNMAN** [comment]
How would I do that? I don't see any option within Citizens to do that? Or do you imply something else?

**Comment by mcmonkey4eva** [comment]
... The permission plugin you use? You'd give permission... via your permission plugin...
