### ISSUE TITLE
Hostile mobs not working and occasional npc loss

### ISSUE THREAD

**Issue by CoryRoryss** [CitizensDev/Citizens2#1115]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

Hi i am here because there seems to be an issue with my citizens2.
the problem is that hostile mobs arent working. for example, when i type /npc type zombie  , it says
"Please report this error: [See console]  java.lang.IllegalArgumentException: Unsupported Entity Type ZOMBIE"
This error came out of no where. i did not update it or anything. other sources told me it may be another plugin interfering with it so i disabled all of them except for citizens and the error continued. another source said to make sure hostile mobs are enabled in the world i am in, which they have always been.  i thought maybe the version i was using was broken or something so i used previous versions only to encounter the same thing.  the version i was initially using was : 	"citizens-2.0.21-SNAPSHOT.jar"
regardless of which version i use the same error occurs. (Even using the original citizens) Thanks alot for helping~ and please respond soon.

**Comment by fullwall** [comment]
Can't reproduce this... what does /pl say?

**Comment by CoryRoryss** [comment]
TTA CoreProtect WorldEdit NoPluginDisplay DoubleJump BlockCommand CommandBlocker CrackShot EasySetSpawn ActionHealth Votifier NoCheatPlus ChatReaction VotingPlugin ChestRestock mcMastery ExpHealth PermissionsEx Command_Blocker mcMMO Levels Vault ChairStairs BloodMoon PlayerParticles MassiveCore Essentials SimpleRename CTSNC Citizens EssentialsKitManager ASkyBlock EssentialsChat Multiverse-Core Factions Shopkeepers MythicMobs CrazyEnchantments MyPet ScoreboardStats HolographicDisplays WarpPortals Quests CratesPlus
