### ISSUE TITLE
Command Wont Trigger By Normal Players

### ISSUE THREAD

**Issue by EpicRoamer** [CitizensDev/Citizens2#1117]
So I Have The Menu GUI  Plugin And So I Made It So The Mob/Citizen I Have Would Trigger The Command By Right Clicking The Mob But It Wouldent Work For Normal Players But It Would Work For OP Players
Please Help

**Comment by mcmonkey4eva** [comment]
Check your permissions configuration?

**Comment by EpicRoamer** [comment]
I Did But I Count Find The Right One
