### ISSUE TITLE
Hide Block Animations & Sounds from Other Players

### ISSUE THREAD

**Issue by Elxafil** [CitizensDev/Citizens2#1118]
With Denizen I'm creating a questing plugin that hides players from each other when they're in a questing area that way other players can't intefere with the quest but players hidden from each other can still see and hear other players opening chests, hitting noteblocks, etc. so I was wondering how I can detect when a player opens a chest or something and then hide it from all the players in that region?

**Comment by MusicScore** [comment]
This link will be especially useful to you: https://one.denizenscript.com/denizen/evts

You can use events such as `on player clicks block` and its variants, which includes `on player (right/left) clicks (<material>) (with <item>) (in <area>)` and `on player (right/left) clicks block (with <item>)`. You can do something like this:

```
example_script:
  type: world
  events:
    on player right clicks chest:
    - determine passively cancelled
    - animatechest <context.location> open sound:true <player>
```

The above script simulates the chest opening, but then you'd need a GUI to accompany it. From here, you can use other scripts, such as inventory scripts, to simulate the chest opening and having content in it. An example of a script to simulate this might be:

```
example_script:
  type: world
  events:
    on player right clicks chest:
    - determine passively cancelled
    - animatechest <context.location> open sound:true <player>
    - if <in@<player.uuid> Cool Loot chest.notable_name||null> == null
    {
      - inventory open 'd:in@generic[size=27;title=&ss6Cool Loot;contents=li@i@example_item|i@air|i@air|i@another_item]'
    }
    else
    {
      - inventory open 'd:<in@<player.uuid> Cool Loot chest>'
    }

    on player closes inventory:
    - if <context.inventory.title> == '&ss6Cool Loot'
    {
      - note '<context.inventory>' 'as:<player.uuid> Cool Loot chest'
    }
```

**Comment by Arctomium** [comment]
How would you run this in a Worldguard Region though?

**Comment by MusicScore** [comment]
You can either note the area yourself by grabbing the area as a cuboid. An example of a command is:
`- note <cu@[l@corner 1]|[l@corner 2]> as:example_cuboid`

Or you can install Depenizen so that you can note the area by grabbing the WorldGuard region as a cuboid. An example of a command is:
`- note <region@[region name].cuboid> as:example_cuboid`

Once you have the area you want noted in Denizen, you can use the example script I gave you and just add an area argument for the `on player clicks block` event. A script for simulating opening a chest in only a certain area may possibly look like this:
```
example_script:
  type: world
  events:
    on player right clicks chest in example_cuboid:
    - determine passively cancelled
    - animatechest <context.location> open sound:true <player>
    - if <in@<player.uuid> Cool Loot chest.notable_name||null> == null
    {
      - inventory open 'd:in@generic[size=27;title=&ss6Cool Loot;contents=li@i@example_item|i@air|i@air|i@another_item]'
    }
    else
    {
      - inventory open 'd:<in@<player.uuid> Cool Loot chest>'
    }

    on player closes inventory:
    - if <context.inventory.title> == '&ss6Cool Loot'
    {
      - note '<context.inventory>' 'as:<player.uuid> Cool Loot chest'
      - animatechest <l@the location for the chest> close sound:true <player>
    }
```

**Comment by mcmonkey4eva** [comment]
This is a Denizen question, not a Citizens issue.
