### ISSUE TITLE
NPC Dont show in proper location when spawn and when run /tphere

### ISSUE THREAD

**Issue by zmw1234** [CitizensDev/Citizens2#1119]
This issue seems to be a bug big 
Whenever I make a NPC it does not appear in front of me instead it shows in a whole other 

location and the same thing happens when I go to select a NPC and run /tphere 

Citizen version citizens-2.0.21-SNAPSHOT.jar	server version 1.10

**Comment by mcmonkey4eva** [comment]
Possibly a conflict with some other plugin (region protection / similar that might be denying player entry to an area)?
