### ISSUE TITLE
NPC nametags

### ISSUE THREAD

**Issue by Namnodorel** [CitizensDev/Citizens2#1120]
Hey, its me again... I looked into the nametag issue from #1101 even more, and the problem seems to be the following:

Minecraft makes its entire nametag-system work over the CustomName-Attribute normal Entity-Objects have. The only exception are players, where the nametags work over scoreboards (wtf you doing Mojang). Then again the scoreboards seem to only work with player _names_, not their UUIDs. So when you create multiple player NPCs with the same name, all their nametags are managed by one scoreboard. When one of the NPCs dies, the scoreboard confuses some things and changes (or deletes) the nametag option for the scoreboard, which results in all the other NPCs having their nametag shown, too. 

My personal dirty workaround was to set the name for the GameProfile in HumanController.createEntity() to the first 16 characters of the UUID of the NPC. But this is of course not foolproof and can definetely not be added into the main Citizens plugin. So I brought the issue back here again, to hear some ideas how to solve this problem in a more elegant way and possibly one we can include into Citizens.

**Comment by boozterpvp** [comment]
asdasdsadasd

**Comment by mcmonkey4eva** [comment]
Solution: don't have a lot of NPCs with the same name that all need scoreboard stuff set.

A good way to cleanly do this if you want them to seemingly have the same name, is to make their root name be a mess of color codes (which don't visually display but work well for making names be interpreted as unique), and use prefix/suffix on scoreboard for the actual name.
