### ISSUE TITLE
NPC that is other type than Player disappears

### ISSUE THREAD

**Issue by Tim3game** [CitizensDev/Citizens2#1122]
**Description**
Hello, I want to have on my server NPCs not only for decorate purposes, but with functions that are implemented in my plugin and interact with Citizens2 via CitizensAPI. When I started to use the CitizensAPI, but all of a sudden, when I create an NPC, after a short time it disappear. I couldn't fix it, so I removed the future for now. But now when I create a NPC via the /npc create command, and change it to some other type else than player, it disappear, but I don't know why.

**Citizens config.yml**
[https://pastebin.com/RAeJRFXW](https://pastebin.com/RAeJRFXW)

**Evidence**
[http://imgur.com/a/m94Xo](http://imgur.com/a/m94Xo)

**Comment by boozterpvp** [comment]
Just delete you hole server and that fix the problem i promise.

**Comment by Tim3game** [comment]
Wow, nice joke, now I help you, kill your self, it fixes all your problems.

**Comment by mcmonkey4eva** [comment]
@Tim3game please don't troll on other issues.

**Comment by mcmonkey4eva** [comment]
Non-players disappearing is usually a plugin conflict.

**Comment by Tim3game** [comment]
Ok, it's a problem with my plugin, but the only thing I do with NPCs is I checking the NPCRightClickEvent, nothing else. And I used the ProtocolLib plugin, but that's not the problem, because I took the API out from my plugin. What could be the problem, have you any idea ?

**Comment by NABrr** [comment]
I have JUST posted an issue for a similar thing. Didn't read this was here. My personal issue with NPCs disappearing was having BKCommonLib installed. I had wanted to use the plugin to make trains... I'd really like trains, but I guess I can hold off so my NPCs will work properly. Shops and quests are more important than transportation. I just removed BKCommonLib and poof, they were all back.

**Comment by Tim3game** [comment]
I don't know if it was the reloads or ProtocolLib, but I uninstalled ProtocolLib and started to restart the server instead of reloading and it fixed the problem with missing NPC's that are other types then Player and the entities that were missing was fixed too (one of manny other problems :D). Maybe it was ProtocolLib, maybe the reloads, but for now I waiting for maybe a new version of ProtocolLib and hoping it doesn't come back :)

**Comment by NABrr** [comment]
Strange, I have ProtocolLib installed with default Citizens2 and have had no issues. Might've been from reloading on your part then. I had an issue where all NPCs disappeared, had to do with render distance in the server.properties file

**Comment by mcmonkey4eva** [comment]
@Tim3game NEVER use `/reload`: It displays a warning saying it'll mess things up for a reason!

**Comment by Tim3game** [comment]
I know that, but I don't update my plugin so regulary now (maybe 2-5 times a day instead of 20 times in 1 hour) and for the future I need to find a better solution for that, because my players go nuts when I restarting my server because of a little change in my plugin :D

**Comment by Dinoosawruss** [comment]
If you have done /reload before what can we do to get the npc's to stop disappearing

**Comment by Dinoosawruss** [comment]
It is still happening and I dont have protocol lib

**Comment by mcmonkey4eva** [comment]
@Dinoosawruss fully restart the server.
