### ISSUE TITLE
Can't do trait sentry command

### ISSUE THREAD

**Issue by boozterpvp** [CitizensDev/Citizens2#1123]
Okey when i do /trait sentry this come up: an internal error occurred while attempting to perform this command . What should i do? Please help me! ;(

**Comment by Tim3game** [comment]
Delete your server, install newest version of Citizens and BOOM... It will work, trust me, I am a professional

**Comment by mcmonkey4eva** [comment]
@boozterpvp please don't troll on other issues.

**Comment by mcmonkey4eva** [comment]
Sentry has been discontinued; download Sentinel instead: https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md
