### ISSUE TITLE
Citizens 2

### ISSUE THREAD

**Issue by Kane16x** [CitizensDev/Citizens2#1125]
Recently my friend and I opened up a server (1.9.4 Skyblock Craftbukkit) and we are not able to run citizens or citizens 2, could we get some help? it worked in the past now it won't.

**Comment by Kane16x** [comment]
can i get some help?

**Comment by Gewad** [comment]
Hi,

How do you mean doesn't work? If you perform /pl and your server does it not show up or is it red?
Or don't the NPC's show up? Are you using the right commands? Explain your issues.

Examples of things you can include:

- Copies of the possible error messages.
- The build that you are using(it says when you do /citizens)
- At which point in the process the plugin doesn't work.

**Comment by Kane16x** [comment]
It's red when I do /pl (CraftBukkit 1.9.4)

**Comment by Kane16x** [comment]
Also will it mess with "ASkyblock" plugin?

**Comment by Kane16x** [comment]
hello?

**Comment by mcmonkey4eva** [comment]
Make sure you have the right version from https://wiki.citizensnpcs.co/Versions

**Comment by Kane16x** [comment]
Thanks, You may lock the thread now. Its fixed Ill report if i have anymore though.
