### ISSUE TITLE
HumanNPC Very High Memory Usage

### ISSUE THREAD

**Issue by BlackBeltPanda** [CitizensDev/Citizens2#1127]
Citizens version: 2.0.21-SNAPSHOT (build 1465)
MC version: 1.11.2 git-Paper-1072

Citizen's EntityHumanNPC seems to be utilizing a very large amount of memory. Not sure if this is a memory leak, but I only have 5 or 6 Human NPCs on my server.

Screenshot of memory analysis: 
![memory](https://cloud.githubusercontent.com/assets/5866087/25110380/963a182c-23b1-11e7-9869-997724f1b1fe.png)

I have the HeapDump, as well, if you need it.

**Comment by Brokkonaut** [comment]
This must be something different, because there were no advancements in 1.11.2

**Comment by fullwall** [comment]
Can you please redo this with an up to date spigot and Citizens?
