### ISSUE TITLE
Any way to count players in world without including the NPCs?

### ISSUE THREAD

**Issue by mpivchev** [CitizensDev/Citizens2#1129]
#getPlayers().size() counts the NPCs as well, any way to avoid that?

**Comment by mcmonkey4eva** [comment]
That shouldn't happen by default: check config and related settings. PlayerList stuff is relevant.

**Comment by mpivchev** [comment]
It only counts NPCs that are invisible, for some reason

**Comment by mpivchev** [comment]
Any way to fix this?

**Comment by mcmonkey4eva** [comment]
Invisible NPCs are forced onto the playerlist, because invisibility doesn't function otherwise :/

**Comment by mpivchev** [comment]
Scheisse. Is there another way to hide nameplates that don't require NPCs or do I just have to hardcore all the subtractions

**Comment by mcmonkey4eva** [comment]
uh... I don't actually know what you're trying to accomplish tbh.

But er, perhaps a non-player NPC will be of use to you? (EG a zombie or whatever)

**Comment by mpivchev** [comment]
Well the NPCs are normal game selection NPCs with hidden nameplates. I'm trying to create a custom placeholder that displays the player count per world (since I'm beginning with just one server)

**Comment by BurnyDaKath** [comment]
Java 8's `Bukkit.getOnlinePlayers().stream().filter(p -> p.getLocation().getWorld() == world)` would be a really good solution, since NPCs are not counted in Bukkit.getOnlinePlayers() (tested, or I would have problems with many of my custom plugins).
