### ISSUE TITLE
NPC Saves.yml Bug Report

### ISSUE THREAD

**Issue by Curtis73** [CitizensDev/Citizens2#1131]
Hello there,
Whenever I attempt to load citizens, this error comes up:

Error:
https://pastebin.com/UrYk66YA

Saves:
https://pastebin.com/h0YCj8AM

I am running the latest Citizens snapshot and Minecraft 1.11.2

This error has come out of nowhere - it was working, then when I went away, the error started coming up and citizens stopped working.

Thanks in advance!

**Comment by mcmonkey4eva** [comment]
I'm seeing a lot of `*id019` type notation in there that... doesn't belong at all...

... I hope you have clean backup copies of your saves file!

**Comment by Curtis73** [comment]
Yeah, I have backups
Do I need to remove the *id019?
