### ISSUE TITLE
Player npc do not spawn

### ISSUE THREAD

**Issue by rutihfrutti** [CitizensDev/Citizens2#1132]
- This is a bug description
- 1.11 Minecraft & Citizens version 2.0.21 
When typing /npc create and a players name the npc does not show up. We've tried creating other mobs like wolves, and that works. We've even tried deleting and reinstalling the plugin, and tried using other versions. Always same issue.

**Comment by mcmonkey4eva** [comment]
That type of thing is often a conflict with another plugin.

**Comment by rutihfrutti** [comment]
Do you have any examples?
