### ISSUE TITLE
NPC spawnpoint [feature suggestion]

### ISSUE THREAD

**Issue by FrankHeijden** [CitizensDev/Citizens2#1134]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant
Heya,

Is there a way to set the anchor of a NPC as the respawnpoint of the NPC? Or just a command like /npc spawnpoint to set the spawnpoint of the npc, so when it dies it respawns at that place?

Would love to see this!
-Frank

**Comment by mcmonkey4eva** [comment]
NPCs don't generally die or respawn in base Citizens.
That functionality is added by separate plugins.
Sentinel being a good example of a plugin that does that - Sentinel has a `/sentinel spawnpoint` option, and most other plugins that give a respawn also have a spawnpoint control somewhere.

**Comment by FrankHeijden** [comment]
Can i also use sentinel only for the spawnpoint? And not for the other features?

**Comment by mcmonkey4eva** [comment]
If you want, sure.  Or Denizen `health` trait for that. Or whatever you please.
Not sure what you're even doing to be at this stage tbh.

**Comment by FrankHeijden** [comment]
Lol, i want a npc to be vulnerable for fun and when players let him die it needs to respawn at a certain loc.

**Comment by mcmonkey4eva** [comment]
Well, achieve that using Sentinel or Denizen or any other plugin that makes that very easily done.
