### ISSUE TITLE
Can't play sleep animation

### ISSUE THREAD

**Issue by MatArtz** [CitizensDev/Citizens2#1135]
- Minecraft 1.11.2
- citizens-2.0.21-SNAPSHOT
I can play sit, sneak... but I can't play the sleep animation I don't know if it's my mistake or a bug and I got no errors.

public static NPC spawnNPC(Location loc, String Skin, String Name)
{
NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, Name);
npc.data().setPersistent(NPC.PLAYER_SKIN_UUID_METADATA, Skin);
npc.data().setPersistent(NPC.PLAYER_SKIN_USE_LATEST, false);
npc.spawn(loc);
		
return npc;
}

NPC npc = spawnNPC(p.getLocation(), p.getName(), CubeLife.getRoleName(p, false, true));
PlayerAnimation.SLEEP.play((Player)npc.getEntity());

**Comment by mcmonkey4eva** [comment]
Sleep animation got weird in minecraft, it requires a bed in some specific position relative to the player entity to play correctly.

**Comment by MatArtz** [comment]
Could anyone help me to realize this or it's too difficult?

**Comment by fullwall** [comment]
The client actually checks that a bed is nearby these days. You have to put a bed nearby and be in night to get the animation to play.

**Comment by Arctomium** [comment]
Try this plugin: https://www.spigotmc.org/resources/nunpcdestinations-create-living-npcs-1-8-3-1-11.13863/

It comes with an addon animation plugin that allows you to set locations and have NPCs sleep at them, it's also got fishing, fishing and keeping the fish in inventory, opening chests and opening chests then emptying all the items into it.

**Comment by mcmonkey4eva** [comment]
I submitted a PR to fix this issue (and basically any other sleeping issues): https://github.com/CitizensDev/Citizens2/pull/2029
