### ISSUE TITLE
i found error in NPCSpawnEvent

### ISSUE THREAD

**Issue by jomjonejame** [CitizensDev/Citizens2#1136]
I'm created NPC in world and when teleport to npc it's show error in console

MC 1.8.8
Citizens version: 2.0.16-SNAPSHOT (build 1267)
Error Link : https://pastebin.com/VjAU6ryh

**Comment by mcmonkey4eva** [comment]
Update your server and Citizens. We can't support a build that old.

**Comment by jomjonejame** [comment]
If I do not want to update my server version Can I update Citizens?

**Comment by mcmonkey4eva** [comment]
You can try the most recent version for your server version from https://wiki.citizensnpcs.co/Versions but that's also a minimally-supported version (IE if it doesn't work, we can't do much more for you there...)

**Comment by jomjonejame** [comment]
This problem get fixed with update ProtocolLib to version 4.2.1

Thanks for the help.
#mcmonkey4eva
