### ISSUE TITLE
Using BlockBreaker API?

### ISSUE THREAD

**Issue by cjunekim** [CitizensDev/Citizens2#1137]
Hello

There is a BlockBreaker API. As I understand it, it is used to make NPC break blocks.

I am developing plugins(through Jython and ScriptCraft) that uses Citizens API. How can I use the BlockBreaker API to make NPC break blocks? I couldn't find any examples.

**Comment by mcmonkey4eva** [comment]
It's not the simplest API to use but there are some samples. https://github.com/mcmonkey4eva/Denizen/blob/master/plugin/src/main/java/net/aufdemrand/denizen/scripts/commands/npc/BreakCommand.java#L81 <-- Denizen implementation of a one-line break command.

I would recommend using Java or Denizen script to interact with things like this best, though it should be simple enough to translate to any sufficiently featured script language that's compatible with either Citizens or general Java reflection.
