### ISSUE TITLE
Controllable trait

### ISSUE THREAD

**Issue by XakepSDK** [CitizensDev/Citizens2#1139]
I use this trait. Everything is fine, but i can't control some mobs rotation. E.g. horse/ghast rotation. And players speed won't set to mounted mob speed.(Slow horse, slow ender dragon).
Command /npc controllable has same issue.

**Comment by BurnyDaKath** [comment]
This is most likely due to server software (Bukkit, Spigot or such) or Minecraft bugs. I have myself experienced such bugs in my own code, trying different methods (clearing pathfinder goals, NoAI tags, packets spam and such), yet have found no ways to fix.
