### ISSUE TITLE
Citizens Scoreboard Bug

### ISSUE THREAD

**Issue by mecray** [CitizensDev/Citizens2#1140]
Hey.

When I was using Citizens before I added a scoreboard plugin, the /npc name command was working fine. Now, /npc name does not do anything and the NPC's name pops right back up.

Thanks

**Comment by mcmonkey4eva** [comment]
It's probably the other plugin's fault, based on your description...

Note that NPC names are partially scoreboard based!

**Comment by mecray** [comment]
Yeah, but all scoreboard plugins that I have tried cause the NPC names to appear.

**Comment by mcmonkey4eva** [comment]
well... all scoreboard plugins you tried are disruptive to NPC scoreboard functionality, I guess.
