### ISSUE TITLE
setFlying - NavigationCompleteEvent not called

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1143]
Hello!

I have an issue.

If I set an NPC setFlying(true) and if it's a non-flying mob in Minecraft the NavigationCompleteEvent will not be called once the entity reaches the setTarget location, but if it's a flying entity in Minecraft, as a Blaze the event is called. Please fix so the event will be called. @fullwall

**Comment by fullwall** [comment]
What's your path distance margin?
