### ISSUE TITLE
NPC respawns on death point (bug?)

### ISSUE THREAD

**Issue by RokkoEffe** [CitizensDev/Citizens2#1146]
I created an NPC and then typed /npc  vulnerable. When I kill NPC, he respawns at the death point, NOT at the creation point. Is this normal? How to set NPC spawn at the creation point?

**Comment by mcmonkey4eva** [comment]
An NPC doesn't know it's creation point, it knows only where it was last for respawning purposes.

You need to add an additional trait to track a spawn point, such as the Denizen-provided `health` trait or the Sentinel trait.
