### ISSUE TITLE
Citizens Problem With ProtocolLib

### ISSUE THREAD

**Issue by Blazinnn** [CitizensDev/Citizens2#1147]
I just recently downloaded citizens with the lastest verion off of https://dev.bukkit.org/projects/citizens/files
and now my server won't load.  Without Citizens my Protocol Lib works fine and the other way around.  When I try this with a local server, the protollib loads while the citizens plugin doesn't but this is my log to my multicraft server, lastest.log > https://hasteb.in/awuboyejob.css
The citizens version I have does match my 1.11 server.
Citizens config when its working,
https://hasteb.in/ifilavomih.xml
Please Help me and Thanks!

**Comment by mcmonkey4eva** [comment]
Please use pastebin https://pastebin.com/ (not hastebin!)
and paste the *full* log, not a partial log - that log bears no mention of Citizens.
Also ensure you are using the latest build from http://ci.citizensnpcs.co/job/Citizens2/ and not any other site

**Comment by Blazinnn** [comment]
I'm using the same build from that website and that was all that was the full log after adding citizens with protocollib.  I'll double check later if another plugin is causing this problem when I have time.

**Comment by mcmonkey4eva** [comment]
You... definitely do not post the full log.
Also, the link you posted as a source for your Citizens build does _not_ provide the save build as what I linked.

**Comment by Blazinnn** [comment]
Oh well they both were 2.0.21 so I though they were the same and idk where to get my full log thats the only thing that was in my lastest.log, my server won't even load so i guess the full log didnt load. Thanks for helping though!

**Comment by Blazinnn** [comment]
Thanks for helping, I the server some how fixed itself. After a while I added Citizens back and the server loaded it!
