### ISSUE TITLE
Giveing a nickname to citizen

### ISSUE THREAD

**Issue by Managuchi** [CitizensDev/Citizens2#1148]
- I don't sure is this feature is in the citizen plugin already yet but i find nowhere about it it commands page
about set nickname to citizen (e.g. spawn citizen with Notch skin and the name tag above him is Lobby),
- spigot 1.8.8

**Comment by mcmonkey4eva** [comment]
`/npc create Lobby`
`/npc skin Notch`

**Comment by Managuchi** [comment]
wow, i forgot to find command via /npc help thxx
