### ISSUE TITLE
NPC permission builds up over time, causing Server.broadcastMessage() lag

### ISSUE THREAD

**Issue by malonnnn** [CitizensDev/Citizens2#1151]
**Original Thread:**
http://forum.enginehub.org/threads/lag-from-broadcast.16958/#post-35036

**Condensed Version:**
Using the broadcast() function of CommandHelper (send message to all players online) I experience lag after some time. I believe this is due to the fact that my server spawns an NPC, applies a template for a few seconds, then despawns the NPC.

**Response from CommandHelper author:**
First off, absolutely nothing fancy is going on in CommandHelper here. It simply sends the string to Bukkit to broadcast. So any plugin that uses Server.broadcastMessage() is going to have these same symptoms.

So I dug into the Craftbukkit code. (i'll try not to get too technical) It's checking the permissions for every human entity on the server, regardless if you specify a permission or not in broadcast(). (it defaults to bukkit.broadcast.user) But that's not why it's getting worse over time. I dug into how the PermissionSubscriptions are populated and it seems that they're added whenever permissions are recalculated, and only removed when a player disconnects or if it's explicitly called. **Citizens would probably have to do this manually when their NPCs unload.** (unless they simply don't expect permissions to be recalculated for NPCs. This might be done by a permissions plugin.) I don't see any of these methods being used when I search for them in Citizens Github. **So maybe that's why this is happening. Every time you spawn an NPC, it adds it to PermissionSubscriptions list and checks its permissions when broadcast() is run. But since it's never removed from this list (since NPCs can't "disconnect"), it keeps building up.**

**Comment by mcmonkey4eva** [comment]
What permissions plugin are you using?

**Comment by malonnnn** [comment]
pex, latest version

**Comment by malonnnn** [comment]
This is how I'm showcasing the skins
`
    runas(~console,'/npc select '.@npcID)
    runas(~console,"/npc spawn")
    runas(~console,"/template apply @class")
    runas(~console,"/npc moveto --x @x --y @y --z @z")
    runas(~console,"/npc despawn")
`

**Comment by malonnnn** [comment]
Please, any word on this? This would be extremely nice to have fixed

**Comment by malonnnn** [comment]
I did re-write my code a bit so that there is far less spawning and despawning, now only templates being applied frequently, but it continues to happen.

It has become my belief that CHANGING TEMPLATES is what's causing the issue, as it's spawning a new player character for each template change.

So, can anyone confirm if switching templates may cause such a memory leak?

**Comment by malonnnn** [comment]
Can I attempt to write a fix and submit it as a PR?

**Comment by malonnnn** [comment]
I have done a timings report here:

https://timings.aikar.co/?id=d2e77e89bee243638f5bb27851ff72e4

I can see enormous spikes in Citizens::templates which I use frequently, which I suspect is the cause.

**Comment by BurnyDaKath** [comment]
Honestly myself I would recommend using Java 8's `Bukkit.getOnlinePlayers().forEach(p -> p.sendMessage(...));` if all usages of the method are custom plugins, this does not do unnecessary checks and should not cause any problems with NPCs. Also you can `.stream().filter(p -> p.hasPermission(...))` if that is necessary - this does not ask NPCs anything still. However, this does not output the message to the console, so you would need either `System.out.println(...)` or `Bukkit.getConsoleSender().sendMessage(...)` (second is for colorful output).

**Comment by malonnnn** [comment]
@BurnyDaKath 

Yes, but this affects every plugin that uses broadcastMessage, and I don't have the capability to re-write every plugin to that method

**Comment by BurnyDaKath** [comment]
@malonnnn If you can, you could modify the Citizens sources instead until bugfix arrives.

**Comment by malonnnn** [comment]
@BurnyDaKath Oh! I understand what you mean now, I didn't get it before. Okay, I will check that shit out

**Comment by malonnnn** [comment]
@fullwall I'm too stupid to figure out exactly what's wrong, this issue is out of my league, I barely even comprehend the issue

**Comment by malonnnn** [comment]
If it makes any difference, I changed the way I was spawning templates, but the issue remains

`
    runas(~console,"/template apply @class")
    runas(~console,"/npc moveto --x @x --y @y --z @z")
`

**Comment by fullwall** [comment]
Does the latest build help?

**Comment by malonnnn** [comment]
WIth the new build, whenever I do /template apply <whatever>, the NPC gets disguised as not as the template but as /npc skin

I have a pre-made template called Superman, but when i do /template apply superman, he looks as if I had done /npc skin Superman instead

I'll continue to poke around to see if I can figure anything else out. Thank you, though!!! I hugely appreciate the effort, I do not wish for that to go un-noticed.

**Comment by malonnnn** [comment]
@fullwall 

Okay, the results are in! The bug is fixed! I started the server up on friday, let it run all day saturday, and sunday there is still NO LAG! Thank you!!!!!!!!!!!!!!!!!

**Comment by mcmonkey4eva** [comment]
woot!
