### ISSUE TITLE
Citizens doesn't work with 1.12 pre 2

### ISSUE THREAD

**Issue by Fonzee9** [CitizensDev/Citizens2#1152]
Please update :) I need this plugin

**Comment by mcmonkey4eva** [comment]
We don't generally build compatibility for pre-releases.

Waste of effort.

Keep your server on the primary supported server version.

**Comment by Fonzee9** [comment]
But so many plugins have already been updated. Examples GriefPrevention, FastAyncWorldedit,FurnitureLib,Orebfuscator. Plus the api should stay the same so it should work for the official release.

**Comment by mcmonkey4eva** [comment]
Citizens doesn't use Spigot API much, it uses deep internal NMS code. It's not a simple matter to port Citizens to a new version.

**Comment by Fonzee9** [comment]
I really need this plugin on 1.12 pre 2 this sucks!!!

**Comment by mcmonkey4eva** [comment]
I doubt you _really need_ it on a brand new unsupported testing-only version.

**Comment by Fonzee9** [comment]
I would love to have it this is the only plugin that doesn't work for me and i have 60 plugins

**Comment by Fonzee9** [comment]
Plus if you update it now it should work on the official release so i don't think its a waste of time.

**Comment by Fonzee9** [comment]
Spigot states: 1.12 is now the developed version, 1.11.2 builds will show as outdated when running /version. We still support these builds, but most bugfixes will only go to 1.12 pre 2.

Notice the most bugfixes will only go to 1.12 pre 2
