### ISSUE TITLE
Display npc shield

### ISSUE THREAD

**Issue by jobensingh** [CitizensDev/Citizens2#1153]
In this issue, please include:
- feature 
- Minecraft: 1.10.2

Is their any way to make a npc hold right click, for my case I want to be able to have npc hold right click on their shield so it is visible. If there is any other way let me know. Thanks

**Comment by mcmonkey4eva** [comment]
You achieve this through a quick Denizen ( https://wiki.citizensnpcs.co/Denizen ) script.
pretty much just `- animate <npc> start_use_offhand_item`

**Comment by jobensingh** [comment]
It worked Thanks!
