### ISSUE TITLE
Can't change pose of npc (Citizens ORIGINAL, not 2)

### ISSUE THREAD

**Issue by TheBoredG** [CitizensDev/Citizens2#1154]
This is kinda like a bug for me but I cannot do /npc pose. It just says "Pose: 1/1" and that's it. I am using Minecraft 1.8.9, and Citizens, not Citizens2. If someone could help and give me the command to make the npc in a sleeping pose, I will be very happy. Thanks!

**Comment by mcmonkey4eva** [comment]
Update to Citizens2; the original Citizens is not in any way supported!

**Comment by 123123b** [comment]
I also have this problem too, except I'm on citizens 2
 https://imgur.com/a/pphtJ

**Comment by OskarZyg** [comment]
This is really late, but it is one of the first things to show up on google, so to pose the selected NPC, the command is: `/npc pose -a`
