### ISSUE TITLE
Denizen doesn't seem to work.

### ISSUE THREAD

**Issue by TheBoredG** [CitizensDev/Citizens2#1155]
Hi there, I am using Citizens 2 on Minecraft 1.11.2 with Denizen but it doesn't seem to work but Citizens works. If someone can help me, I'll be very happy. Thank you all!

**Comment by mcmonkey4eva** [comment]
what do you mean it doesn't work? Does it give an error message in your console?

**Comment by TheBoredG** [comment]
Yes, I tried to execute the Citizens commands that Denizen included in chat and in console. All it says is that there is an internal error so I cannot do anything. I tried this with /npc sleep so...

**Comment by mcmonkey4eva** [comment]
That command only works if the NPC is on a bed.
Try `/denizen` or similar to see if the plugin is loaded at all.

Either way, check your server logs: There might be an error message (if there is, please post it!)

**Comment by TheBoredG** [comment]
Still doesn't work, when I do /plugins Denizen is there. This is the error on the console:

Unexpected exception while parsing console command "denizen" org.bukkit.command.CommandException: Unhandled exception executing command 'denizen' in plugin Denizen v1.0.1-SNAPSHOT (build 1630) at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:629) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:615) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:397) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112] Caused by: java.lang.NullPointerException at net.aufdemrand.denizen.Denizen.onCommand(Denizen.java:1242) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.11.2.jar:git-Bukkit-6e3cec8] ... 8 more

**Comment by TheBoredG** [comment]
Another thing is, that /npc sleep doesn't work anywhere, even on a bed.

**Comment by mcmonkey4eva** [comment]
Make sure to run SPIGOT.jar and not CRAFBUKKIT.jar - They're similar in functionality, but Spigot adds additional options that Denizen relies on!

**Comment by TheBoredG** [comment]
1. I am using a free server hosting website, so I cannot access the main .jar files to do this. There is a 'File Manager' but the only things I can open within the browser, is .yml files and .txt and other text files, and .jar files are opened via download.
2. I am using Bukkit, and when I used Spigot as the server type, Citizens was not there.

**Comment by mcmonkey4eva** [comment]
What do you mean Citizens wasn't there? perhaps your server host reset plugins after switching to Spigot, or you set the wrong Spigot version?

**Comment by TheBoredG** [comment]
Spigot was on the latest version, and the server host shows all plugins. I don't know if this helps but, the host is called server.pro

**Comment by mcmonkey4eva** [comment]
Well... Citizens and Denizen both definitely work fine on latest Spigot 1.11.2
(NOT on spigot 1.12!)

If you're sure you had everything in the correct configuration, and it didn't work, then it's quite likely the server host has something weird, and the only solution would be to contact them.

**Comment by TheBoredG** [comment]
Well, thanks for helping, but I couldn't find a solution. If you want to, you can join my server and help me on there, with the IP of ### RPKnightMC.serv.gs

**Comment by mcmonkey4eva** [comment]
If you want, feel free to chat with the Denizen team on the new Discord group available at https://discord.gg/Q6pZGSR
