### ISSUE TITLE
Sentinel. /sentinel chaserange. When I use this command NPC still chases the player around the whole place and when the player is killed the npc stays at the player's death spot and doesn't go back to its respawn point.

### ISSUE THREAD

**Issue by BashtaTiEMaika** [CitizensDev/Citizens2#1157]
Hello. I installed Sentinel and everything is working fine, however when I make a npc and make it a sentinel it chases the player around the whole place. When I use /sentinel chaserange 5 the npc doesn't chase the player for 5 blocks but around the whole place again. And when a player goes near the npc like 10/15 blocks away from the npc the npc starts running at the player and doesn't stop chasing him. When the NPC kills a player the NPC stays at the player's death spot and doesn't go back to the NPC's spawnpoint that I set with /sentinel spawnpoint. Help pls ! Thanks.

**Comment by mcmonkey4eva** [comment]
set an `/npc path` point to mark its guard location. Also, set the other range values...
