### ISSUE TITLE
Npcs Invisible/But not default

### ISSUE THREAD

**Issue by Hadesone11** [CitizensDev/Citizens2#1158]
In this issue, please include:
**- whether this is a bug description or a feature request**
My problem, most likely it's me doing something wrong.
**- Link to server log & Citizens config if relevant (using e.g. pastie.org)** 
**- Minecraft & Citizens version if relevant**
citizens v2.0.21-SNAPSHOT build 1474
Minecraft 1.11.2

So I just have a question that I havn't been able to find out through googling. I have a problem creating npc's of types. The default works but if I specify type such as player, pig, or blaze the npc is invisible. In the case of the blaze it makes noise and i can remove it; but it's invisible. I was wondering if i need to add images or something somewhere in the folders

**Comment by mcmonkey4eva** [comment]
Check for conflicting plugins, anything else that interacts with mobs may cause issues...

**Comment by Hadesone11** [comment]
I don't have any plugins that interact with mobs other than nolagg

**Comment by mcmonkey4eva** [comment]
Try running with nolagg disabled - if that doesn't help, check other plugins that are in any way related.

**Comment by BurnyDaKath** [comment]
The bug is indeed present when doing sounds none command. Try other silencing ways using configurations.
