### ISSUE TITLE
Scripts (JS) do not load on reload.

### ISSUE THREAD

**Issue by BurnyDaKath** [CitizensDev/Citizens2#1160]
This is a bug report.

NPCs do not run scripts on server reload. Here is a simple script I called dance.js:
```
var tick = 0;

function run(npc) {
	tick = tick + 1;
	if (tick >= 20) tick = 0;
	npc.getEntity().setSneaking(tick >= 10);
}
```

Then I do /npc script --add dance.js, the NPC "dances". After doing /reload, the NPC stops "dancing". To make script load I have to do /npc script --remove dance.js and then repeat first command (just doing the first command does not work, but that is understandable).

Spigot 1.11.2-R0.1-SNAPSHOT with Citizens #1474.

**Comment by mcmonkey4eva** [comment]
NEVER `/reload` - also the JS engine is minimally supported, we recommend using Denizen for scripting. https://wiki.citizensnpcs.co/Denizen

**Comment by BurnyDaKath** [comment]
JS feels better for me as an professional coder, and /reload is our best way to minimize waiting and to improve efficiency (do not worry, memory is managed and works fine when reloading, and all other plugins are made compatible with reloading). I guess I will have to fix the bug myself for the network or create custom plugin implementation based on citizens sources. Anyway, thanks for reply.

**Comment by BurnyDaKath** [comment]
Want to notify that this happens not only when reloading - also restarts do not start scripts.
