### ISSUE TITLE
Citizens Error with Towny

### ISSUE THREAD

**Issue by Yhenko** [CitizensDev/Citizens2#1162]
1.8.8 server spigot
last version Citizens from dev.bukkit.
Towny version 0.91.2.0
Plugin error and appear red in /pl

29.05 13:07:52 [Server] ERROR Could not pass event CreatureSpawnEvent to Towny v0.91.2.0
29.05 13:07:52 [Server] INFO org.bukkit.event.EventException
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1015) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:182) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
29.05 13:07:52 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
29.05 13:07:52 [Server] INFO at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onCreatureSpawn(TownyEntityListener.java:305) ~[?:?]
29.05 13:07:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO ... 12 more
29.05 13:07:52 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
29.05 13:07:52 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Multicraft] Skipped 8 lines due to rate limit (30/s)
29.05 13:07:52 [Server] ERROR Could not pass event CreatureSpawnEvent to Towny v0.91.2.0
29.05 13:07:52 [Server] INFO org.bukkit.event.EventException
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1015) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:182) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
29.05 13:07:52 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
29.05 13:07:52 [Server] INFO at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onCreatureSpawn(TownyEntityListener.java:305) ~[?:?]
29.05 13:07:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO ... 12 more
29.05 13:07:52 [Server] ERROR Could not pass event CreatureSpawnEvent to Towny v0.91.2.0
29.05 13:07:52 [Server] INFO org.bukkit.event.EventException
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:52 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Multicraft] Skipped 109 lines due to rate limit (30/s)
29.05 13:07:53 [Server] ERROR Could not pass event CreatureSpawnEvent to Towny v0.91.2.0
29.05 13:07:53 [Server] INFO org.bukkit.event.EventException
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1015) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:182) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
29.05 13:07:53 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
29.05 13:07:53 [Server] INFO at com.palmergames.bukkit.towny.listeners.TownyEntityListener.onCreatureSpawn(TownyEntityListener.java:305) ~[?:?]
29.05 13:07:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
29.05 13:07:53 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:53 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:53 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO ... 12 more
29.05 13:07:53 [Server] ERROR Could not pass event CreatureSpawnEvent to Towny v0.91.2.0
29.05 13:07:53 [Server] INFO org.bukkit.event.EventException
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:53 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [custom.jar:git-Spigot-21fe707-e1ebe52]
29.05 13:07:59 [Multicraft] Skipped 131 lines due to rate limit (30/s)

**Comment by mcmonkey4eva** [comment]
Towny error.
(Possibly related to an incorrect Citizens version https://wiki.citizensnpcs.co/Versions )

Also, update your server to 1.11.2
