### ISSUE TITLE
Issue with Holographic Menus and Citizens

### ISSUE THREAD

**Issue by PABerwen** [CitizensDev/Citizens2#1163]
I'm not sure exactly what causes the issue, but having both of these plugins on my server causes the menu buttons from Holographic Menus to not function(clicking them does nothing).

No errors or warnings related to these plugins are listed in the server log.

I'm not sure if there's anything that can be done, if the dev of HM would have to make changes, or if this is just an unavoidable conflict due to the nature of these plugins.

Thanks for your time, apologies if this has been covered previously.

Spigot : 1.11.2
Citizens : 2.0.21
Holographic Menus : "Final Release"

**Comment by mcmonkey4eva** [comment]
That'd be a fault to discuss with the holographic plugin developer
