### ISSUE TITLE
Citizens not working

### ISSUE THREAD

**Issue by Prokopiss** [CitizensDev/Citizens2#1165]
I tried every version of mc 1.8.x-1.9.x
and every version of Citizens nothing at all!

**Comment by Prokopiss** [comment]
https://pastebin.com/UV0gm29p

**Comment by mcmonkey4eva** [comment]
Mate.
https://wiki.citizensnpcs.co/Versions
Download the version that matches your server - ideally update your server to a supported version to make plugin usage easier (1.8.8, 1.9.4, 1.10.2, or 1.11.2)

If you can't figure this out _STILL_ after this maybe you shouldn't be running a server?

**Comment by Prokopiss** [comment]
I can't find a proper premade server [1.8.8]

**Comment by Prokopiss** [comment]
nvm found one
