### ISSUE TITLE
Pathfinding bug and mount restriction

### ISSUE THREAD

**Issue by Goetheus** [CitizensDev/Citizens2#1166]
Hi devs!

First of all, thank you to maintain this awesome plugin through years!
Since some weeks, I try to create some path with NPC, but I have bugs... :/

Versions:
- Minecraft 1.11.2
- Citizens 2.0.21
- Sentinel 1.0.1
- Spigot 1.11.2

**The bad behaviour:** NPCs can't follow the path, they rotate randomly, and sometimes suddenly teleport.
I have no error in console.

With a horse, it stopped to follow its path if we mount it! And sometimes it stop its path to eat grass. Greedy horse!

A little GIF of one of bad effects: https://gifyu.com/image/bmmp

Thank you for help!

**Comment by mcmonkey4eva** [comment]
Sorry for incredibly late reply (issues page is a mess)

Might be good to swap around the pathfinder mode setting (`use-new-finder` boolean setting). Basically just change it to the opposite of whatever it currently is, which might solve the issue immediately there...

**Comment by mcmonkey4eva** [comment]
Please reply below if this is still an issue.
