### ISSUE TITLE
I may be doing this wrong. Citizens not working

### ISSUE THREAD

**Issue by orikalin** [CitizensDev/Citizens2#117]
[[FIXED]]

This is my first minecraft server, and I've gotten everything else so far running smoothly, however I am trying to use Citizen along with HyperConomy and HyperMerchant to make a shop NPC for my Pixelmon 3.3.3 server, which is running on Mod_Cauldron_1.7.10-1.1231.01.206

My issue that whenever I try to use any of citizens commands... literally nothing happens.
I do not get an 'unknown command' message, but nothing else happens, not even in the console.
same story when I type citizens into the console as well.

In addition, I know this is an issue with HyperMerchant, but it says "An internal error occured while attempting to perform this command" whenever I try to use any commands with it. I only state this because I have feeling these issues go hand in hand.

[[EDIT UPDATE]]
if I type /clerk it tells me "Citizens is not loaded. NPCs are unavailable at this time."
but I have citizens properly installed:
http://gyazo.com/1604584a9313b6941ccec59acb898a24

[[EDIT UPDATE 2]]
It seems I may be dumb, and trying to run a plugin that is not updated for 1.7.10.... I just realized how long it has been since citizen updated last... with this in mind, is there any alternate to citzens that I can use with Hypermerchant? or should I just scrap the idea of using Hyperconomy all together to make NPC shops on my 1.7.10 server?
If the latter is my only option, may I ask what a good set of plugins is to get my own custom server shop running?

[[EDIT UPDATE 3]]
Fixed the entire issue after looking through HyperConomy's builds and noticing that the latest build reverted to 1.7.9.
Using build #441 with the latest build of HyperMerchant has solved my issue! I will leave this here in case anyone runs into a similar issue!

Citizens version:
Version: 2.0.13-SNAPSHOT (build 1130)

HyperMerchant version:
Version: 1.56.1

Hyperconomy version:
Version: 0.974.57

**Comment by petitecolier** [comment]
It works! Thanks so much you saved our server.
