### ISSUE TITLE
Can't find the correct Citizens Version!

### ISSUE THREAD

**Issue by galoti** [CitizensDev/Citizens2#1172]
- Hello! Where i can find the latest Citizens Version for Cauldron 1.7.10?(B2 i think) I only found this version: citizens-2.0.13-1.7.10-Cauldron-B1.jar
- B2 download link is off... upload again plz

**Comment by mcmonkey4eva** [comment]
@bloodmc was the author and uploader of that file - up to him to reprovide it...

**Comment by galoti** [comment]
Thanks, I will talk to him

**Comment by mcmonkey4eva** [comment]
Supposedly this is a link 

Https://www.dropbox.com/s/rs4n0i51mwxze9u/citizens-2.0.13-1.7.10-Cauldron-B1.jar

**Comment by bloodmc** [comment]
@mcmonkey4eva 

https://www.dropbox.com/s/sn4451lffuvr8o0/citizens-2.0.13-1.7.10-Cauldron-B2.jar
