### ISSUE TITLE
A* pathfinding strategy and jumping

### ISSUE THREAD

**Issue by cjunekim** [CitizensDev/Citizens2#1173]
The currently default MCNavigationStrategy isn't clever enough. When the NPC is near at the edge of a block and we are lower than them, they don't follow us. Have a look at the debug path:

![2017-06-06_18 48 06](https://cloud.githubusercontent.com/assets/9114235/26823492/cc4533da-4ae8-11e7-8500-d12b004b8a4d.png)

AStarNavigationStrategy is much better. However, when using that strategy, the NPC can jump limitlessly. When the player is above in the sky they can jump continously upto the player's height. Is it by design?

![2017-06-06_18 50 19](https://cloud.githubusercontent.com/assets/9114235/26823564/0ce0ed44-4ae9-11e7-9bdc-7d6734680e31.png)

**Comment by fullwall** [comment]
I am unable to reproduce this behaviour. What code are you using to cause the infinite jumping to happen? Are you sure it's not simply teleporting the NPC to the destination every time?

**Comment by cjunekim** [comment]
Thank you for your response.

First, have a look at the video clip I recorded:

![citizen_pathfinding](https://user-images.githubusercontent.com/9114235/26936175-db00f244-4ca8-11e7-9cef-65a782f148e3.gif)

The procedure to reproduce the behaviour follows:
 1. set use-new-finder: true in Citizens config.yml
 1. run the server
 1. connect the client
 1. /npc create Notch (for example)
 1. /trait sentinel
 1. /sentinel guard <playername>
 1. fly to the sky, at least 7 blocks higher (the default range in sentinel is 7)

 Notice that you have to have sentinel installed already. I used sentinel to make the NPC follow you. Sentinel does not provide any particular pathfinding algorithm -- it depends on Citizens'.

**Comment by fullwall** [comment]
Alright, I will test with Sentinel tonight.

**Comment by mcmonkey4eva** [comment]
That's a teleport.

Minecraft is coded to smooth out small-range movements like that, even though it _is_ almost surely just a teleport.

**Comment by fullwall** [comment]
Yes, this is expected behaviour - if the NPC is unable to find a path by default it will teleport to the destination.

**Comment by fullwall** [comment]
@cjunekim what do you mean? do you mean the follow distance or pathfinding to the center of a block versus the edge of a block?

**Comment by cjunekim** [comment]
I should have described it more precisely.

When the NPC is on a different level(this case higher than player's) from player's, and the NPC is located at the end block of that level, it stops to navigate. Watch the video:

![citizen_pathfinding_mc4](https://user-images.githubusercontent.com/9114235/27002293-36bff8ca-4e19-11e7-9c72-28184c81a7fb.gif)

Notch is the NPC and the other is the player. NPC is following the player. You can suppose:

trait.getNPC().getNavigator().setTarget(self.getPlayer().getLocation())

is running. As you can see the debug mode is on.

**Comment by fullwall** [comment]
I can't reproduce this.
