### ISSUE TITLE
skins not changing

### ISSUE THREAD

**Issue by ChristyKGrnKnght** [CitizensDev/Citizens2#1174]
So I'm working with a child on his server, and we're having problems with the Minecraft skins not changing. When he tries changing them (/npc skin username) he's getting this message now:
"Removing 1 from skin tracker due to DespawnReason.PENDING_RESPAWN.
Despawned 1 DespawnReason. PENDING_RESPAWN" and the skin doesn't change.

Earlier he was getting a message about authentication problems. Any suggestions?

**Comment by mcmonkey4eva** [comment]
`Earlier he was getting a message about authentication problems. ` this may indicate that the server has gone past its Mojang-granted skin read limits. EG if it's a shared server (IE you don't own the hardware running the Minecraft server), you can more or less guarantee the shared server has gone past its limit :/

The skin read limits are basically Mojang saying how rapidly you can use human skulls and player NPCs on any given IP address.

**Comment by ChristyKGrnKnght** [comment]
It's hosted on a paid site. I take it this would be something we'd have to contact the host about, though I'm not sure that would help. Thanks for the reply on this.... and all the work you do on Minecraft plugins in general.

**Comment by Tyloonie** [comment]
I have the same issue. Does anyone know where to contact the host or relieve your server from being flagged as spamming? :(

**Comment by mcmonkey4eva** [comment]
There's not really a fix, other than complaining to mojang about the poor system. :/
Or buying your own private IP address for your server.

**Comment by fullwall** [comment]
There is another skin issue, track it in https://github.com/CitizensDev/Citizens2/issues/1184 - for now I'm closing this one.
