### ISSUE TITLE
Question: Is it possible to make Cititzens work on a 1.4.7 MC Server with a 1.7.10 API?

### ISSUE THREAD

**Issue by Karlos96** [CitizensDev/Citizens2#1179]
My question is if it is possible to get a version which only checks if the version of the api is 1.7.10 not the mc-server.
Because we are running a 1.4.7 Modpack Server with a 1.7.10 API to accept most of the 1.7.10 Plugins.

greetings

karlos96

**Comment by mcmonkey4eva** [comment]
Citizens relies heavily on untouched minecraft internals that match the version it expects.
So: no, not possible, sorry :/

**Comment by Karlos96** [comment]
Alright Thanks ^^
