### ISSUE TITLE
Citizens uses to much preformance needs a preformance overhaul

### ISSUE THREAD

**Issue by Fonzee9** [CitizensDev/Citizens2#1181]
It really makes the preformance of your server terrible.
![2017-06-15_15 58 33](https://user-images.githubusercontent.com/21323258/27206164-949e74ba-5203-11e7-9107-c5c8f792b25c.png)

**Comment by Fonzee9** [comment]
Citizens is the first one for cpu usage

**Comment by mcmonkey4eva** [comment]
Spawn less NPCs, or make them do less things.

Citizens is exactly as perfomant as minecraft allows in that task: That task is 100% minecraft code running, just being triggered by Citizens.
(Telling each NPC to run through standard minecraft player updates)

There's nothing we can do about that.
