### ISSUE TITLE
Not compatible?

### ISSUE THREAD

**Issue by teamaonn** [CitizensDev/Citizens2#1182]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

Okay, it's obviously a bug...
No link on this one. Only error says "Not compatible with version 1.12" Then it says it's disabling it.
Citizens version is 2.0.21

**Comment by mcmonkey4eva** [comment]
run 2.0.22 for 1.12 support! Available at http://ci.citizensnpcs.co/job/Citizens2/
