### ISSUE TITLE
/citizens reload on Paper Spigot 1.12 Causes The Server To Freeze

### ISSUE THREAD

**Issue by Gonfonix** [CitizensDev/Citizens2#1186]
Version: Paper Spigot 1.12 and Latest Citizens Build.

When doing /citizens reload, it freezes the whole server. It hasn't done this before 1.12 until now.

**Comment by fullwall** [comment]
There's nothing in the console about it?

**Comment by Gonfonix** [comment]
nope. Nothing in the console. When I ran it on a test server, I didn't seem to have this issue so it may have been an error with a plugin. Here is my list. If you think one of them could be a cause, from experiences, then be sure to let know. I will go through them.

![screen shot 2017-06-18 at 3 31 12 pm](https://user-images.githubusercontent.com/5055478/27263776-9de7ee88-543e-11e7-95db-577227c85064.png)

**Comment by fullwall** [comment]
Try disabling PlugMan and ClearLag, it could be one of them... otherwise you may have to just start disabling them one by one.

**Comment by Gonfonix** [comment]
Okay I will try that.
