### ISSUE TITLE
Citizens doens't save data (+equip)

### ISSUE THREAD

**Issue by RokkoEffe** [CitizensDev/Citizens2#1188]
When I removed NPC, it disappeared, but even if I had typed /citizens save, when I typed /citizens reload, the NPC appears again. Also when I created NPC and then typed /citizens save+reload, it disappeared.

The second problem is equip data. I have equiped NPC with armor and shield, but after the server reload, there was NO armor and shield on NPC.

**Comment by mcmonkey4eva** [comment]
Version(s)?

**Comment by RokkoEffe** [comment]
Spigot 1.11.2
Citizens 2.0.22 SNAPSHOT #1480

**Comment by RokkoEffe** [comment]
Are you going to fix this? I have updated Citizens to #1481. The problem with created NPCs removing is solved now. BUT the problem with equipment not being saved is still actual.

**Comment by mcmonkey4eva** [comment]
That's not normal behavior, it needs investigation a bit... waiting on @fullwall

**Comment by RokkoEffe** [comment]
I have been experimenting now and found out that the armor is saving correctly, but the items in hand are not saving.

**Comment by RokkoEffe** [comment]
This problem is caused by "Heroes Minecraft RPG plugin". I had to allow NPCs to use weapons. BUT the problem with NPCs appears after removal still remains.

**Comment by DevIPv2** [comment]
I have recoded the plugin, look for the updated version on the site.

**Comment by mcmonkey4eva** [comment]
@DevIPv2 please do not lie to users.

**Comment by fullwall** [comment]
How are you equipping the NPC?

**Comment by RokkoEffe** [comment]
@fullwall /npc equip and then right-click with item in hand. BOTH OF these bugs are caused by Heroes Minecraft RPG.

**Comment by RokkoEffe** [comment]
All these problems was fixed on the #1484 snapshot, so this thread can be closed.

**Comment by DevIPv2** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/d807603768",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Sepp is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
