### ISSUE TITLE
Builder not working/throwing an error after doing /builder build

### ISSUE THREAD

**Issue by strc0pier** [CitizensDev/Citizens2#1191]
So yeah, the builder is not building anything with any of schematics.

https://pastebin.com/NG0Fq14p

This is the error that I receive as soon as I initiate the /builder build command

**Comment by strc0pier** [comment]
My minecraft server version is 1.12

**Comment by mcmonkey4eva** [comment]
That's out of our control, goes on Builder page: https://github.com/Morphan1/Builder/issues
