### ISSUE TITLE
Parrot Variants?

### ISSUE THREAD

**Issue by AaronStrange3** [CitizensDev/Citizens2#1194]
I am trying to set up a row of parrots with every variant, however, once I used: /npc parrot variant --variant blue, I was told to check the console and report this issue.  "Please report this error: [See Console]; java.lang.NullPointerException.null.

Console contained:

20.06 00:19:49 [Server] INFO AaronStrange issued server command: /npc parrot --variant blue
20.06 00:19:49 [Server] ERROR [Citizens] Cannot register a null trait. Was it registered properly?
20.06 00:19:49 [Server] WARN java.lang.NullPointerException
20.06 00:19:49 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.trait.Commands.parrot(Commands.java:68)
20.06 00:19:49 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20.06 00:19:49 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20.06 00:19:49 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20.06 00:19:49 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
20.06 00:19:49 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
20.06 00:19:49 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
20.06 00:19:49 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
20.06 00:19:49 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
20.06 00:19:49 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20.06 00:19:49 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20.06 00:19:49 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
20.06 00:19:49 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20.06 00:19:49 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
20.06 00:19:49 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
20.06 00:19:49 [Server] WARN at java.lang.Thread.run(Thread.java:748)

I have no idea what any of this is, this is my first time reporting an issue, and I have been at this computer all day just trying to figure out how to spawn a tamed parrot to a certain player through the console, only to give up and find an easy work-around later on.  The work around works perfectly thanks to citizens and commandnpcs, but it is only cosmetically bothering because I cannot change the parrot NPCs variant without the above happening.  Please tell me what I am doing wrong.

CITIZENS VERSION: 2.0.22-SNAPSHOT (1.12 ALPHA #1)

**Comment by fullwall** [comment]
Fixed in the latest build (http://ci.citizensnpcs.co)
