### ISSUE TITLE
Citizens 1.7.10 dont work!

### ISSUE THREAD

**Issue by llamaplay** [CitizensDev/Citizens2#1195]
Hi i am running an cauldron server and trying to use citizens plugin but always fail.
I managed to find build 1 for cauldron for citizens but now gives me error "Internal Exception: java.lang.NullPointerException" when i run the command /npc create Notch and i cant login on server any longer.
So could someone please give me the latest citizen cauldron 1.7.10 build download link ?

Best regards and thanks in advance!

**Comment by mcmonkey4eva** [comment]
This should be the correct link, probably (UNOFFICIAL)


https://www.dropbox.com/s/sn4451lffuvr8o0/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by llamaplay** [comment]
Download it but still cant login on server due to build 1 crash says "Internal Exception: java.lang.NullPointerException"

**Comment by mcmonkey4eva** [comment]
You'll probably have to clear away old data that is corrupted.

Worst case it may include your player or world files :/ - this is why you always have a test server separate from the live one!

**Comment by llamaplay** [comment]
Anything but not the world i really had it hard to make that server xD

**Comment by llamaplay** [comment]
I see it crashes only when i get back at the place where i inserted the npc.

**Comment by mcmonkey4eva** [comment]
Then you probably have to delete the chunk the NPC was in.

**Comment by llamaplay** [comment]
I already removed citizens folder on plugins directory but it did not change...

**Comment by llamaplay** [comment]
Nah build2 crashes also.

**Comment by mcmonkey4eva** [comment]
well, RIP. Likely a mod you have conflicts :/ not much we can do there

**Comment by llamaplay** [comment]
Mods : http://prntscr.com/fm8nbt
