### ISSUE TITLE
WHo removed my post ?

### ISSUE THREAD

**Issue by llamaplay** [CitizensDev/Citizens2#1196]
Who removed my post ?

"Hi i am running an cauldron server and trying to use citizens plugin but always fail.
I managed to find build 1 for cauldron for citizens but now gives me error "Internal Exception: java.lang.NullPointerException" when i run the command /npc create Notch and i cant login on server any longer.
So could someone please give me the latest citizen cauldron 1.7.10 build download link ?

Best regards and thanks in advance!"

**Comment by mcmonkey4eva** [comment]
Please do not spam: your post is still there, merely closed.
https://github.com/CitizensDev/Citizens2/issues/1195
