### ISSUE TITLE
[Question] Why do we need applyAndRespawn() in SKin.java?

### ISSUE THREAD

**Issue by Namnodorel** [CitizensDev/Citizens2#1197]
Well, the title basically says it all. Why do we need to respawn an NPC to apply the skin? I'm in a (admittedly quite specific) situation where I don't care about the skin, but my NPC mustn't be respawned, is there a way to circumvent the method for some NPCs?

**Comment by mcmonkey4eva** [comment]
Why can't you respawn the NPC?

**Comment by Namnodorel** [comment]
Gravity as well as noclip and visibility get turned on for the NPC when it is respawned. My code also needs to modify the NPC every tick, and it apparently loses the connection/reference/whatever to the NPC/its entity. That basically makes the execution of the code void, as it does nothing anymore.

**Comment by fullwall** [comment]
How are you setting the skin? If you don't respawn the NPC then the GameProfile is not set correctly.

**Comment by Namnodorel** [comment]
I am not setting the skin at all, I just set a name and Citizens uses the skin that player has. 
And the entity references are not the only problem. I also need a player to constantly be spectating the NPC, something that doesn't work well when the entity the player is spectating gets despawned. And sometimes I need to mess with the NMS-classes of the NPC (for example noclip), but every value I apply there is void as soon as the NPC gets respawned.

**Comment by mcmonkey4eva** [comment]
Any custom properties set by code can (and should) be easily maintained with a trait.
