### ISSUE TITLE
Not even sure, but MASSIVE Tps drop and lag spikes

### ISSUE THREAD

**Issue by devonkeith** [CitizensDev/Citizens2#1198]
Check out this timings report. https://timings.spigotmc.org/?url=lalibohosi

**Comment by mcmonkey4eva** [comment]
Might have an NPC trying for an impossible navigation?

**Comment by DevIPv2** [comment]
Hello devonkeith,
  Im a Developer of Citizens and im going to help resolve your case.

**Comment by DevIPv2** [comment]
You need to clean out your server,
*You need to start by increasing your -Xmx.*

**Comment by mcmonkey4eva** [comment]
@DevIPv2 please do not lie to users.

**Comment by devonkeith** [comment]
I have no walking NPCs. I set a few things to false in the config and it seems fine.

**Comment by Faxed** [comment]
Same thing's happening with us - We're using 1.11.2, but we're finding that the PlayerUpdateTask of Citizens is tanking the TPS, sometimes pulling it from 20 to 5 (with the only contributing plugin being Citizens). 

There's a total of about 20 NPCs, so it's nothing major, with all of them being stationary and few being talkative.

**Comment by loa-in-** [comment]
What is your server command-line? I.e. what parameters are you using for running java?

**Comment by lolzelig** [comment]
We too have big issues with citizens lately... TPS stay low and every so often lag spikes occur.
Even though I do have some sentinel guards I made sure every single one of them is stationary and has no target, yet still we have very low TPS. 

When analyzing the server, Citizens is the single most resource consuming plugin.

**Comment by DevIPv2** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/5350eed37b",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Sepp is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.

**Comment by fullwall** [comment]
Need profiling output to nail this down...
