### ISSUE TITLE
Click Event Issue

### ISSUE THREAD

**Issue by QueenKisaki** [CitizensDev/Citizens2#1201]
In this issue, please include:
- Possible bug
- https://pastebin.com/t59UB0yD
- Mc 1.11.2 and Citizens 2.0.22

I also have this post on Quests issue tracker as I'm not sure where the problem is coming from. The error comes up when we turn in quests.

**Comment by mcmonkey4eva** [comment]
Fault line is:
` 25.06 19:16:14 [Server] INFO at com.sucy.skill.cmd.CmdExp.execute(CmdExp.java:116) ~[?:?]`
Bug the creator of the plugin that has that signature ^
