### ISSUE TITLE
Cannot measure distance between worlds with a guarding sentinel

### ISSUE THREAD

**Issue by jaggy80** [CitizensDev/Citizens2#1202]
Console spamming error when Sentinel guarding a player that changes worlds

[Citizens] Exception while updating 50: Cannot measure distance between Hub and Survival.
https://pastebin.com/vftj304m

CraftBukkit version git-Spigot-23b6354-0481ae9 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Citizens v2.0.22-SNAPSHOT (build 1481)
Sentinel build 125

**Comment by fullwall** [comment]
Fixed
