### ISSUE TITLE
Authlib

### ISSUE THREAD

**Issue by Azim-D3Tm** [CitizensDev/Citizens2#1203]
This is bug request.
First things first - why do you even need mojang authentification in your plugin?
Whatever, but this closes up some custom cores with this error:
`java.lang.NoSuchMethodException: com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)`
To fix it, u can use server's authlib instead of directly asking mojang servers.
waiting for a patch <3

**Comment by mcmonkey4eva** [comment]
w... what?
Do you have a custom server jar that deleted the Mojang authentication engine for some reason?

We use that for loading skins from the primary skin server, which is the only valid way to acquire them.

Further, we do not support "cracked" setups. Leave the authentication engine intact (and the rest of your server within reason intact as well) if you expect support.
