### ISSUE TITLE
'Npc Assignment' and 'Npc Command' commands are not working

### ISSUE THREAD

**Issue by rayleigh123** [CitizensDev/Citizens2#1204]
i cant use both of these commands all of a sudden. and there is only this error

29.06 17:48:36 [Server] ERROR [Citizens] The trait triggers failed to load for NPC ID: 33.
29.06 17:48:36 [Server] ERROR [Citizens] The trait assignment failed to load for NPC ID: 33.
29.06 17:48:36 [Server] ERROR [Citizens] The trait triggers failed to load for NPC ID: 41.
29.06 17:48:36 [Server] ERROR [Citizens] The trait assignment failed to load for NPC ID: 41.
29.06 17:48:36 [Server] ERROR [Citizens] The trait triggers failed to load for NPC ID: 58.
29.06 17:48:36 [Server] ERROR [Citizens] The trait assignment failed to load for NPC ID: 58.
29.06 17:48:36 [Server] ERROR [Citizens] The trait triggers failed to load for NPC ID: 59.
29.06 17:48:36 [Server] ERROR [Citizens] The trait assignment failed to load for NPC ID: 59.

can somebody help me please ?

im using latest version of denizen and denizencore,

**Comment by mcmonkey4eva** [comment]
Check your startup logs for an error message (Meaning a Java exception stacktrace, a big dump of coded text and numbers)...

**Comment by rayleigh123** [comment]
wait i will send whole errors to you

**Comment by rayleigh123** [comment]
https://hastebin.com/eporufazek.vbs

**Comment by mcmonkey4eva** [comment]
That's not it, that's plugin `skript` breaking. Not relevant here.

**Comment by rayleigh123** [comment]
but still ./npc assign is not working. is it about skript ?

**Comment by mcmonkey4eva** [comment]
No. There's a different error you haven't posted most likely.

Particularly one from the Denizen plugin.

Or you just don't have the Denizen plugin properly installed at all.

**Comment by rayleigh123** [comment]
denizen looks green in ./pl and all other denizen commands are working well

**Comment by mcmonkey4eva** [comment]
I don't know what to tell you then. If you can't find the error that sourced it, then ... ???
