### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by fullwall** [CitizensDev/Citizens2#1206]
I would like to change the license of Citizens to GPL. If you are pinged here then you have current contributions in Citizens2 or CitizensAPI: please respond (or thumbs up) whether you agree to relicense your contributions to Citizens from the Open Software License (current) to GPL (proposed).

@mcmonkey4eva 
@aufdemrand 
@aPunch 
@Morphan1 
@liec0dez 
@Lolmewn 
@JCThePants 
@sanjay900 
@tkausl 
@XxCoolGamesxX 
@ritzdever
@Byteflux 
@tuxillator 
@scizzr 
@oloflarsson 
@leagris 
@Twillen

**Comment by tuxillator** [comment]
agree/thumbs up

**Comment by aufdemrand** [comment]
👍

- Jeremy

**Comment by fullwall** [comment]
On further consideration the GPL with an additional notice to allow usage as an API would be better.

**Comment by scizzr** [comment]
Agree

**Comment by mcmonkey4eva** [comment]
Solid 👍

**Comment by Morphan1** [comment]
👍 I'm down

**Comment by JCThePants** [comment]
Agree

**Comment by sanjay900** [comment]
Agree

**Comment by mcmonkey4eva** [comment]
Non-replies:
@aPunch 
@liec0dez 
@Lolmewn 
@XxCoolGamesxX 
@RitzDever (I don't think this user ever actually contributed anything here though - only 2 PRs that were closed, no merges)
@oloflarsson 

Also, the original post isn't quite a full list of contributing developers, even for at the time it was posted.

Either way, wondering what the plan regarding this is? @fullwall

**Comment by XxCoolGamesxX** [comment]
Agree

**Comment by liec0dez** [comment]
Agree - sorry I missed this!

**Comment by Lolmewn** [comment]
Weirdly enough I just got my first (email) notification from this. But it's a go for me.
