### ISSUE TITLE
Citizens 1.12

### ISSUE THREAD

**Issue by Ibiky** [CitizensDev/Citizens2#1208]
Hello, here is the question is simple, I would like to know if Citizen will be possible in 1.12?

**Comment by loa-in-** [comment]
Citizen already works on 1.12.

**Comment by Ibiky** [comment]
Ok thanks for your reply.

**Comment by loa-in-** [comment]
Here is the latest version: http://ci.citizensnpcs.co/job/Citizens2/
Worked for me.

**Comment by Ibiky** [comment]
Awesome it works, you're awesome continue like this ^^
