### ISSUE TITLE
Items Duplicating, Inventories Not Working

### ISSUE THREAD

**Issue by michaeldriskell** [CitizensDev/Citizens2#1209]
I cant edit the NPCs inventory. All of my NPCs have the trait Sentinel attached to them. The only way to change their inventory is to equip them with an item. If you try to drop an item into its inventory, the item disappears. But then when Im in the inventory and I pull the item I equipped them with, it duplicated the item. (in this case it was a diamond sword) I now have access to infinite diamond swords? Please fix this. Im on the latest version of spigot (1.12R0.1b1336) and latest version of Citizens 2.

I haven't purchased the plugin yet, but you have my word that when this is fixed and I can sell NPCs to players for in game money without worrying about dupe glitches and them not being able to access their inventories, I will definitely show my support and purchase it!

Has anyone else had this issue?

**Comment by mcmonkey4eva** [comment]
Are you testing in creative or survival mode?

**Comment by michaeldriskell** [comment]
Ive tested it in survival and creative. And after a fresh server restart.

**Comment by fullwall** [comment]
How are you editing the inventory? Can't reproduce this using /npc inventory

**Comment by michaeldriskell** [comment]
It only happens when I have sentinel added to its traits.

**Comment by mcmonkey4eva** [comment]
How is the Sentinel configured?
`/sentinel info`, what's your config, what commands were run on the Sentinel?

**Comment by michaeldriskell** [comment]
The default stats. If youre available to hop on my server and see, the IP is mcsplash.us

**Comment by mcmonkey4eva** [comment]
Sentinel doesn't do anything funky with the inventory by default - it only uses it to read current item.

**Comment by michaeldriskell** [comment]
Well when I edit a new NPC inventory it works just like it should but as soon as I add sentinel to it, it will delete the item if you add it to its inventory. and if you equip it with /sentinel equip and try to take it out of the inventory it duplicates it.

**Comment by mcmonkey4eva** [comment]
You sure you didn't EG accidentally active `needs ammo` mode?

**Comment by mcmonkey4eva** [comment]
or autoswitch?

**Comment by michaeldriskell** [comment]
yes Im sure
