### ISSUE TITLE
Install Problems Maybe

### ISSUE THREAD

**Issue by BugzMinecraft** [CitizensDev/Citizens2#1213]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

okay, I don't think this is a bug..
I don't need that because it will not fing work..
Thats the problem..

Okay, so i have tried multiple versions of citizens for my 1.8.8 server and it will not work.. Everytime i log on I do /pl and Citizens is red.. Please help on discord https://discord.gg/yvrtcN or in comments

**Comment by mcmonkey4eva** [comment]
Get the correct version from https://wiki.citizensnpcs.co/Versions
