### ISSUE TITLE
[Major] [1.12] Restarting wipes passive mobs of a kind from specific chunks if that mob exists as a NPC

### ISSUE THREAD

**Issue by i9hdkill** [CitizensDev/Citizens2#1214]
We are running into the issue that restarting our server (/restart or /Stop and start) wipes mobs from specific chunks when entering a chunk.

Let's say we have a sheep NPC at our spawn (Spawn is loaded all the time). Now, if we enter a chunk with sheeps, they are all gone.

It's reproducable and it's only happening since 1.12.
All other mobs are still there. Spawning a villager npc, restarting, despawns all villagers and so on.

We last had this bug with a custom 1.7 version of citizens for 1.7 cauldron.

Spigot 1.12 - built on 06.07.17
Citizens_Build1481
citizens save file: https://pastebin.com/u5KdhcGU
No errors in log of any kind.
It does not happen if we remove Citizens.

**Comment by fullwall** [comment]
Which are the NPCs that are problematic? I can't reproduce this.

**Comment by fullwall** [comment]
Can't reproduce this - created two NPC sheeps in different chunks, spawned a bunch of sheep and restarted the server but they were still there. Is there anything special you have to do?

**Comment by i9hdkill** [comment]
Forgot to mention that that only occurred after the second /restart and the following restarts. In addidtion to that, it's only in chunks nearby.

Our "setup":
sheep/villager npc at spawn.

Fly 1000 blocks(at least that you don't have the spawn chunks in view)
spawn 100 sheeps that are scattered around 4 chunks. (use F3 + G to view chunk borders)
logout in in one of these 4 chunks or use /restart.
Instantly login again. use /restart again.
login again.
Now sheeps are gone in one(or all) of these 4 chunks.

**Comment by fullwall** [comment]
I still can't reproduce this....

**Comment by i9hdkill** [comment]
Hm okay. 
We will try to narrow it down and report back if we did so. But we are only able to start next weekend.
