### ISSUE TITLE
high Pct Tick, low Average TPS, Task: HumanController$1(Single)

### ISSUE THREAD

**Issue by Tubih** [CitizensDev/Citizens2#1215]
Hello, 
we are running a spigot server with avg 15 players and about 40 npcs. The npcs are all just standing (doing nothing) and spread over a big map.
From time to time we get some big lag spikes and our average TPS is too low.
It would be very nice if you could have a look at this:

https://timings.spigotmc.org/?url=jitutewigi

Because its just a (virtual) gameserver, i dont think there is a way to change this settings: "-XX:+UseG1GC -XX:MaxGCPauseMillis=50 flags and increasing your -Xmx". 

ftp is possible, ssh is not
Spigot Version: 3fb9445-6e3cec8 (MC: 1.11.2)
Citizens v2.0.21-SNAPSHOT (build 1463)
Average TPS: 17.63
Server Load:   27.20%
Memory: 609MB / 8192MB (1387 allocated)

Thanks for help and ideas

**Comment by fullwall** [comment]
How many scoreboards are you using?

**Comment by Tubih** [comment]
none

**Comment by Tubih** [comment]
Still have this Problem with the new Snapshot.

Citizens v2.0.22-SNAPSHOT (build 1487)

Here are timings WITHOUT Citizen:
https://timings.spigotmc.org/?url=joyukonuna

Here are timings with Citizen:
https://timings.spigotmc.org/?url=qaketerije

There are about 40 npcs and we tested it with less but the number makes almost no difference.

**Comment by Tubih** [comment]
You already helped me with your first reply and i was **too stupid** to notice. Or i just thought i couldnt fix it myself. But after looking at the code at: https://github.com/CitizensDev/Citizens2/blob/master/v1_11_R1/src/main/java/net/citizensnpcs/nms/v1_11_R1/entity/HumanController.java
...i came to the conclusion that it might help to disable "player-scoreboard-teams: enable: true".
Very simple... very effective.
Thank you!

`       0.00%	   0.02%	  0.00 s	     0.01 ms	 0.0	       0.1k	    Task: HumanController$1(Single)`
