### ISSUE TITLE
setVelocity() not working on Minecart-NPCs

### ISSUE THREAD

**Issue by Namnodorel** [CitizensDev/Citizens2#1217]
Is there anything else to say? A freshly created minecart NPC will not move an inch when I set its velocity. It does work with usual minecarts though.
My guess for the reason would be that in `A_()` in `MinecartRideableController.java` does not call `super.A_()` in most cases, a method that seems to work on movement a lot.

**Comment by fullwall** [comment]
I have set it to use the normal minecart logic. Let me know if there are any issues with using minecraft's normal minecart logic,

**Comment by Namnodorel** [comment]
I'm not sure what you mean... Is "not accepting velocities" not an issue?

**Comment by mcmonkey4eva** [comment]
@Namnodorel he pushed a commit fixing the issue you described. It's in the latest dev build.

**Comment by Namnodorel** [comment]
Oh, I didn't see that. But still, the minecart refuses to move, even on the latest commit... Guess I was wrong with `A_()`

**Comment by fullwall** [comment]
Works for me.
