### ISSUE TITLE
Citizens2 Error

### ISSUE THREAD

**Issue by Jaysalina** [CitizensDev/Citizens2#1218]
Ok so, I downloaded both the Dev version of Citizens2 and the regular version for my 1.7.10 server. However to no prevail can I get Citizens2 to work. I need Citizens2, Sentry or Sentinel, and Builder. Whenever I try to use the command /npc create (name) it just errors and here is the error.

https://pastebin.com/Nc7qAsUE

Even when I was able to first create the NPC by using /npc create (name) --type (type) I would try to tp the npc to me but when it said it was tp'd to me it wouldn't show. So getting really really confused. I would also like to state that I am using  **FTB Infinity Evolved**. However I've seen servers like mine using it.

Any help would be greatly appreciated!!! <3

**Comment by mcmonkey4eva** [comment]
That's not 1.7.10, that's 1.7.10 MODDED VIA CAULDRON OR EQUIVALENT.
That's not compatible with a mainline version.
Lucky for you, we have an unofficial version for that we can link you to to try:

https://www.dropbox.com/s/sn4451lffuvr8o0/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by Jaysalina** [comment]
OMG THANK YOU SOO MUCH IT WORKED!!!! <3
