### ISSUE TITLE
Citizens not enabled

### ISSUE THREAD

**Issue by Warp8** [CitizensDev/Citizens2#1219]
Well I have a problem. I am running 1.12 spigot and for some reason citizens2 just wont activate. The server recognizes that it is TRYING to run but it just wont... 
![capture](https://user-images.githubusercontent.com/22381811/28039429-4b5003c8-6590-11e7-8221-f33878bad8c3.PNG)

I have tried almost all versions of citizens 2 except developers ($10.00)

**Comment by mcmonkey4eva** [comment]
Make sure you're running latest dev build: http://ci.citizensnpcs.co/job/Citizens2/
