### ISSUE TITLE
/npc name - player npc's

### ISSUE THREAD

**Issue by FrankHeijden** [CitizensDev/Citizens2#1221]
/npc name doesn't work on player NPC's. it gives an success output, but doesnt work

**Comment by fullwall** [comment]
Are you trying to rename or toggle nameplate visibility?

**Comment by FrankHeijden** [comment]
toggling

**Comment by mcmonkey4eva** [comment]
If an issue on latest versions: likely a conflict with some scoreboard management plugin (Citizens requires scoreboard alterations to make that command work)
