### ISSUE TITLE
Command for adding cmd

### ISSUE THREAD

**Issue by Stickmen1** [CitizensDev/Citizens2#1222]
Hello, how I can add cmd without permisson. I tried /npc cmdadd noperm <command> ,but didn't work

**Comment by mcmonkey4eva** [comment]
Generally for command-execution-by-an-NPC and NPC interaction in general, one would use Denizen https://wiki.citizensnpcs.co/Denizen

**Comment by Stickmen1** [comment]
I didn't found the command what I need

**Comment by mcmonkey4eva** [comment]
It's not so simple as a command - check the tutorials https://one.denizenscript.com/denizen/vids

**Comment by Stickmen1** [comment]
So, I think there is not that I need

**Comment by fullwall** [comment]
You mean give yourself permission or disable permissions for a command?
