### ISSUE TITLE
Citizens can earn achievements

### ISSUE THREAD

**Issue by Eredrim** [CitizensDev/Citizens2#1223]
Hello,

I have an issue with citizens (dev build #1484) on spigot 1.12 (git-Spigot-7228328-14b597f). My NPCs earn achievements when they do stuffs like kill a mob (with sentinel plugin). I already opened a ticket to McMonkey4Eva because I thought it was a sentinel bug: https://github.com/mcmonkey4eva/Sentinel/issues/173. He said me to open another one here.

Regards,

**Comment by fullwall** [comment]
Try the latest dev build.

**Comment by Eredrim** [comment]
I tried it. It doesn't work. The comportment is the same as at the beginning.

**Comment by Joannou1** [comment]
Getting extreme performance impacts from this:
![image](https://user-images.githubusercontent.com/997747/28198286-ed0606d0-6811-11e7-8054-9c64577985c9.png)

**Comment by fullwall** [comment]
Try the latest build

**Comment by Joannou1** [comment]
Seems good!
![image](https://user-images.githubusercontent.com/997747/28203463-b7688bde-682e-11e7-9f27-98df133702a2.png)

**Comment by Eredrim** [comment]
Ok, I tried the latest build. Performance seems better but there still is the achievements issue.

**Comment by LinearBotSystems** [comment]
Same achievements  are still there

**Comment by Tiplish** [comment]
Hi, i've achievments on my Sentinel NPC too :(

**Comment by fullwall** [comment]
I just made another update related to this, is it still an issue? Which achievements in particular are being achieved?
