### ISSUE TITLE
Feature Request: Make NPC's Leashable

### ISSUE THREAD

**Issue by sensorware** [CitizensDev/Citizens2#1224]
This is a feature request to make NPC's leash-able.

**Comment by fullwall** [comment]
Does /npc leashable not work?

**Comment by Nariko13** [comment]
It seems that the leash don't attach to the npc

It has to be an animal ? even on an NPC pig, set to controllable and leashable, the leash attack to him but disappear right after.

**Comment by fullwall** [comment]
They must be vulnerable as well.
