### ISSUE TITLE
Flicker with LeaderHeads plugin

### ISSUE THREAD

**Issue by FrankHeijden** [CitizensDev/Citizens2#1226]
Hello im having a small compatibility issue with LeaderHeads (plugin). When setting up such a LeaderBoard and you’ve added the npc’s to that board it will have a slight flicker exactly every 30 seconds. Its like they're resetting theirselves. 

Is this fixable?
The developer of LeaderHeads does respond to tickets etc, if you want you can also contact him for help.

Citizens version; latest developer beta
Spigot version; latest spigot 1.12 dev build

**Comment by fullwall** [comment]
Probably a scoreboard conflict, not sure how LeaderHeads use scoreboards though.

**Comment by mcmonkey4eva** [comment]
Can't help much from our end, that sounds like LeaderHeads is doing something weird...
