### ISSUE TITLE
Created NPC disappear

### ISSUE THREAD

**Issue by Darknesssp** [CitizensDev/Citizens2#1227]
I use the core of Spigot 1.10.2 and the latest version of your plug-in (also tested the latest versions to 1.10). And in each version of the plug-in NPS disappear as soon as I (or another player) re-enter the server. You can return the NPS only with the / citizens reload command, but if you restart again, they will disappear again. Settings plugin did not touch at all (I tried to change the values ​​- still disappear).
What could be the problem?

**Comment by Darknesssp** [comment]
Also, as an additional problem, NPS does not change the skin. I enter / npc skin (Nickname with skin), but the npc only turns 90 degrees, returns to its original position, and still stays in its previous skin relative to its name

**Comment by fullwall** [comment]
What server version are you using? Are you using online mode? Did you disable tablist somehow?

**Comment by Darknesssp** [comment]
Server version: 1.10.2 (the problem was also observed in version 1.10). I do not use the online mod and did not change the plugin settings. I downloaded the plugin and put it on the server without changing anything in it.

**Comment by mcmonkey4eva** [comment]
Do... you know what online mode is? Are you saying you're running an offline mode server?

**Comment by Darknesssp** [comment]
I know what online mode is. In my understending, of course.
And I ask you to excuse me if I do not understand something, because I am from Russia, and it is difficult to disassemble the help in another language. But, again, the online mode in my opinion is a mode that means a license server and a "pirate". In other words, online and offline modes. Or is something wrong? In my words, this value on my server is set to false

**Comment by mcmonkey4eva** [comment]
Yeah so you just admitted to piracy. GG.
Obviously, we cannot give support to pirates.
