### ISSUE TITLE
nameplate-visible: 'false' doesn't work

### ISSUE THREAD

**Issue by mpivchev** [CitizensDev/Citizens2#1228]
I wanted to hide the nameplates of the NPCs and it worked the first time, but after the next restart, it stopped doing what it's supposed to do. Any idea why this is happening?

Using MC 1.12

**Comment by mpivchev** [comment]
Anyone?

**Comment by fullwall** [comment]
Are you using /npc name to do this?

**Comment by LinearBotSystems** [comment]
I tried this doesn't work only after I renamed it it worked suddenly.
