### ISSUE TITLE
NPC Problems! HELP

### ISSUE THREAD

**Issue by CremationYT** [CitizensDev/Citizens2#1230]
Hey!

My name is Cremation, and I'm using your plugin Citizens/Command NPCs on my Network and I'm currently setting NPCs for my /server Kingdoms-1 custom gamemode and I'm trying to add a NPC and change the skin , but sadly it's not adding the skin. The weird part is that it's working in lobby-1 and skywars-1 but not Kingdoms PLEASE HELP...

**Comment by fullwall** [comment]
Can't reproduce, but try latest build as it has some skin changes.
