### ISSUE TITLE
please update it to 1.12 because now it dont work!

### ISSUE THREAD

**Issue by RJM29** [CitizensDev/Citizens2#1231]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

**Comment by mcmonkey4eva** [comment]
It /is/ updated to 1.12 http://ci.citizensnpcs.co/job/Citizens2/

**Comment by RJM29** [comment]
Oke I am sorry, maybe you could set a link from bukkit and spigot to here because I couldn't find that
