### ISSUE TITLE
Unable to move NPCs across worlds

### ISSUE THREAD

**Issue by ianguuima** [CitizensDev/Citizens2#1232]
I am trying to move an NPC to another world using both the /npc tphere command and the /npc moveto command. In the chat it says the NPC has moved but it actually hasn't, it stays where it was.

No error in the console either and I am using Citizens build 1371 with Spigot 1.9.4.

**Comment by LinearBotSystems** [comment]
No you can't even tpto won't work

**Comment by mcmonkey4eva** [comment]
Possibly an `/npc path` point set that's blocking the teleport?

Sorry for taking literally a year to reply, this issues page is a mess...

**Comment by mcmonkey4eva** [comment]
Please reply below if this is still an issue.
