### ISSUE TITLE
NPC with random capes?

### ISSUE THREAD

**Issue by AaronStrange3** [CitizensDev/Citizens2#1234]
Minecraft version 1.12, citizens version 2.0.22-SNAPSHOT.
I have encountered a bug where NPCs will spawn with a cape regardless if the player it is modeled after has one or not.  They seem to be happening at random.  Not all NPCs have one.

**Comment by YourPalJake** [comment]
There is a command to remove capes

**Comment by HVEVB** [comment]
Where would I find this command?

**Comment by mcmonkey4eva** [comment]
@HVEVB `/npc skinlayers --cape false`

**Comment by Devnando01** [comment]
> @HVEVB `/npc skinlayers --cape false`

thanks :)

**Comment by qwerty810** [comment]
It's not working...
