### ISSUE TITLE
NPC's not loading in.

### ISSUE THREAD

**Issue by Malusiii** [CitizensDev/Citizens2#1236]
Hello, I have a bug of which when the server admins oh this server use /npc create {username} the npc does not spawn, but when they use THEIR names (admins) it spawns them in. Not sure if this is a feature, but at the moment its a bug for me.

The server I'm on is using Citizens v2.0.22-SNAPSHOT (build 1479), i know there is an update, but is there anyway that this can be resolved. 
 [Version](https://cdn.discordapp.com/attachments/239055444662812672/336796684116033546/Screen_Shot_2017-07-18_at_4.09.35_AM.png)

**Comment by mcmonkey4eva** [comment]
Sorry for literally year late reply (issues page is a mess here)

If that happens on latest version, it's likely a conflict with some other plugin (player management / protection / etc. plugins are suspect - anything that would prevent a normal player from being there might also prevent most NPCs from being there)
