### ISSUE TITLE
NPC TAKING NO DAMAGE

### ISSUE THREAD

**Issue by sharkybushbaby** [CitizensDev/Citizens2#1237]
Npcs not taking damage. 
not too each other using sentinel or from a player or mob. 
Arrows. or sword or hits. 

Using latest version.

**Comment by MrRiptide** [comment]
Make sure they are vulnerable, you can toggle it by using: "/npc vulnerable", by default they will not take damage.

**Comment by sharkybushbaby** [comment]
Yeh Ive tried all Options. removed sentinel. added sentinel, made health really low. even npc v npc wont do anything.

**Comment by sharkybushbaby** [comment]
@mcmonkey4eva Can you let me know if this is a issue being looked at or if its something my end. Appreciate it. Go both latest versions of Citizens 2.0.22 and sentinel  1.3.1 . I am aware this is a transition stage for 1.12 just need to make sure its not me.

**Comment by mcmonkey4eva** [comment]
NPCs should be taking damage if well configured - might be a plugin conflict?

**Comment by sharkybushbaby** [comment]
k . Ill look into that. thanks for letting me know.

**Comment by sharkybushbaby** [comment]
@mcmonkey4eva Theres no plugin I specifically can see that would be stopping this from happening. as Before. on the 1.11 version they took damage fine. but Since the Update to 1.12 the only plugins ive updated are worldguard. (pvp allowed btw) essentials. (dontknow if theres anything in there). and sentinel. but even without Sentinel . they arnt taking Damage. They can however, give me damage.

**Comment by mcmonkey4eva** [comment]
I didn't change much that would affect the ability to receive damage in the update...

**Comment by sharkybushbaby** [comment]
@mcmonkey4eva  I owe you a huge apology for wasting your time. the Issue was not with this plugin. It was multiverse. Very sorry

**Comment by mcmonkey4eva** [comment]
hah, all good

**Comment by johng3587** [comment]
> @mcmonkey4eva I owe you a huge apology for wasting your time. the Issue was not with this plugin. It was multiverse. Very sorry

I know im a few years late, but im having the same issue in 1.16, could you elaborate on what multiverse was doing?
