### ISSUE TITLE
Is this compatible with craft-bukkit servers before i buy it?

### ISSUE THREAD

**Issue by lilmistermadness** [CitizensDev/Citizens2#1238]
Hi there,
             Is this compatible with craft-bukkit?

**Comment by mcmonkey4eva** [comment]
Generally it's targeted at Spigot, which is the only still-supported fork of CB out there.

**Comment by ryantheleach** [comment]
You can download Spigots fork of craftbukkit without the optimizations / Spigot API though.

**Comment by mcmonkey4eva** [comment]
But why would you intentionally get the version that lacks optimization and additional API, outside of development reasons?

**Comment by ryantheleach** [comment]
Because you want to retain as much Vanilla behaviour as possible, so players don't complain about mechanics changing. Think SciCraft servers.
