### ISSUE TITLE
[Solved ]Console Error When Skeleton Shot Someone

### ISSUE THREAD

**Issue by solarfavor** [CitizensDev/Citizens2#1239]
My server is paperspigot 1.10.2
Citizens Version 2.0.21
Log: https://hastebin.com/pevafojujo.vbs
When Skeleton shot s.o or npc this error spam.
Hope you patched this soon

**Comment by mcmonkey4eva** [comment]
Update Sentinel! http://ci.citizensnpcs.co/job/Sentinel/

**Comment by solarfavor** [comment]
Sorry for my stupidness . Just realise this a second ago :P
