### ISSUE TITLE
Error creating a new NPC

### ISSUE THREAD

**Issue by Enzo41814** [CitizensDev/Citizens2#1241]
This is an error or possible bug:
https://pastebin.com/ZvPF434R
Minecraft Server 1.12 (Compatible for versions 1.5.2-1.12)
IP: PotterWizard.tk

**Comment by mcmonkey4eva** [comment]
Do you perhaps have weird plugin managers, or asynchronizer type of plugins?

Or a corrupted server jar?

Something went wrong in the internal Java logic there...

**Comment by Enzo41814** [comment]
I thought the same thing, but when I checked the jar file everything was in order. I recently detected that there are other plugins that are also beginning to fail. If I find the solution, I'll let you know.
JAR: PaperSpigot-1.12-b1154.jar (https://yivesmirror.com/grab/paperspigot/PaperSpigot-1.12-b1154.jar).

**Comment by Enzo41814** [comment]
I found the mistake. The plugin "FeatherBoard 3.19.1" is responsible for the error.
