### ISSUE TITLE
Player NPC and Tablist

### ISSUE THREAD

**Issue by aurel85** [CitizensDev/Citizens2#1242]
Hi,

When a player makes a player's npc from the server, in the tab moves the player is moved up or down. Currently in the tab my players are ranked by rank but for the concerned people this is no longer the case. Note that if the player disconnects this solves the problem but it can return at any time. At the level of the animated names this also breaks that of the player concerned
In 1.11.2 I did not have this problem. I do not know if it is exclusively linked to Citizens but I not having nothing found that could solve the problem in the files config of the plugins, I open this issue.

To better understand here is an example (with the player jeuxdelajungle):
https://sandbox.fr/images/uploads/original/1500758630.png

Plugin tab that I use : https://www.spigotmc.org/resources/tab.1448/
AnimatedNames Plugin that I use : https://www.spigotmc.org/resources/animatednames.2175/
I use the last version of Spigot for Citizens (2.0.22 1.12 ALPHA # 1) and i test with build 1487 and the same problem.
I use PaperSpigot 1.12.

**Comment by ryantheleach** [comment]
If I understand correctly, what you expect to see is jeuxdelajungle listed here instead?

![image](https://user-images.githubusercontent.com/141554/28507633-8691acfa-7073-11e7-9a2d-edffb9c05db0.png)

**Comment by aurel85** [comment]
It's ok, and the fact that he has a npc of himself on the server causes him to find himself there in the tab.

**Comment by aurel85** [comment]
Resolved with the option player-scoreboard-teams (on false) in the config.
