### ISSUE TITLE
All enchantments are removed on reload

### ISSUE THREAD

**Issue by KukiCrumbles** [CitizensDev/Citizens2#1243]
In this issue, please include:
- Bug
- https://pastebin.com/1WaWAshZ 

So my resourcepack has items that have durabilities and are spawned with an unbreakable enchantment. Everytime I do /citizens reload it removes the enchantments of the item. So an unbreakable item turns to a breakable item. Citizens needs to keep the enchantment of the item in order for my 3D models to stay, but the problem is it isn't doing that.

**Comment by fullwall** [comment]
Reopen if this is still an issue. I can't reproduce this.
