### ISSUE TITLE
/npc  isn't working

### ISSUE THREAD

**Issue by DashJavii03** [CitizensDev/Citizens2#1246]
I have a bukkit server for 1.9 MC with plugins but whenever i try to put any /npc command it doesn't work. no error, no message neither crashes the game/server. I use the latest version of Citizens.
Server is free hosted at server.pro (If important where it is hosted, idk) On the console neither displays a message. i have ensured I have citizens installed, but it doesn't work. Any help pls?

**Comment by mcmonkey4eva** [comment]
- Latest (1.12) Citizens
- Bukkit 1.9
What are you expecting lol?
https://wiki.citizensnpcs.co/Versions

**Comment by DashJavii03** [comment]
I meant the latest it gives me for 1.9 sorry. anyways i'll try to drag the .jar to the server's plugins that i've just downloaded from that linkand see if that works
