### ISSUE TITLE
General slowness when using lots of templates

### ISSUE THREAD

**Issue by malonnnn** [CitizensDev/Citizens2#1250]
**The issue:**
Timings report says Citizens lags much more than other plugins
https://timings.aikar.co/?id=25b314719a1442dbab79deb6eed6027f#plugins

**Priority:**
Low

**Cause:**
I believe the cause is because I use a lot of templates. I run a superhero server with now more than 300 different heroes. 

I'll do my best to answer as many pre-emptive questions that I can

**How are you using Citizens?**
Example Gif: http://i.imgur.com/z8aMLmT.gif
I use it to showcase a superhero skin. On my server, when a player changes heroes, they also automatically become disguised as that superhero. Citizens is for showcasing the skin, as seen in the gif.

**But Citizens doesn't have a feature like this?**
I am using Commandhelper to basically script the console into running a few commands per button push.

```
    runas(~console,'/npc select '.@npcID)
    console('/npc select '.@npcID)
    if(@class != "remove"){
        runas(~console,"/template apply @class")
        runas(~console,"/npc moveto --x @x --y @y --z @z")
    }else{
        runas(~console,"/template apply remove")
        runas(~console,"/npc moveto --x @x --y @y --z @z")
    }
```

**Okay, but this is a complex issue, what configs are you using?**
All of my config files are synced to a github repo, which you can find here, to which I just pushed the latest update
https://github.com/malonnnn/ServerConfig/tree/master/Citizens

I'm sure you will maybe have additional questions, so please hit me up!

Edit:
Also, it was the spigot forums that said it was citizens lagging, not me, I'm not quite good enough to read timing reports
https://www.spigotmc.org/threads/need-someone-to-check-over-my-timings-report.259918/

**Comment by fullwall** [comment]
Templates are kind of complex, because they save the whole NPC to memory and then load them again. Can you post your templates.yml?
