### ISSUE TITLE
If I change my skin NPC skin <playername> don't work

### ISSUE THREAD

**Issue by Ironic8b498** [CitizensDev/Citizens2#1251]
In this issue, please include:
- bug I believe, if I change my skin to load a wanted skin on NPC it loads skin from before the changed my skin. If I run command again it will flash new skin then display my old skin before I changed my skin. I waited up to an hour trying before I gave up to make sure it wasn't a update thing for the skin on Minecraft servers. tried running /npc skin -c before I ran /npc skin -p <playername>
- Minecraft 1.11.2 & Citizens version v2.0.21-SNAPSHOT (build 1463)

**Comment by mcmonkey4eva** [comment]
If this behavior occurs still, restarting your server should fix it.
Sorry for not noticing this issue early, got lost somehow.
