### ISSUE TITLE
NPC not being saved

### ISSUE THREAD

**Issue by Demonkid1112** [CitizensDev/Citizens2#1252]
The citizens are not being saved to file, no issues on start up but this pops up on shut down
`28.07 10:16:10 [Server] ERROR Error occurred while disabling Citizens v2.0.22-SNAPSHOT (build 1487) (Is it up to date?)
28.07 10:16:10 [Server] INFO java.lang.NoClassDefFoundError: Lregalowl/hyperconomy/api/HEconomyProvider;
28.07 10:16:10 [Server] INFO at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_121]
28.07 10:16:10 [Server] INFO at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_121]
28.07 10:16:10 [Server] INFO at java.lang.Class.getDeclaredFields(Class.java:1916) ~[?:1.8.0_121]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.api.persistence.PersistenceLoader.getFieldsFromClass(PersistenceLoader.java:252) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.api.persistence.PersistenceLoader.getFields(PersistenceLoader.java:247) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.api.persistence.PersistenceLoader.save(PersistenceLoader.java:367) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:342) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:150) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:80) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:86) ~[?:?]
28.07 10:16:10 [Server] INFO at net.citizensnpcs.Citizens.onDisable(Citizens.java:246) ~[?:?]
28.07 10:16:10 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:346) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.spigotmc.RestartCommand.restart(RestartCommand.java:121) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:757) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
28.07 10:16:10 [Server] INFO Caused by: java.lang.ClassNotFoundException: regalowl.hyperconomy.api.HEconomyProvider
28.07 10:16:10 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
28.07 10:16:10 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
28.07 10:16:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
28.07 10:16:10 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
28.07 10:16:10 [Server] INFO ... 25 more`

**Comment by mcmonkey4eva** [comment]
Looks like a plugin conflict with the `Hyper` plugins.
