### ISSUE TITLE
Blacksmith NPC at Wiki?

### ISSUE THREAD

**Issue by HurricanKai** [CitizensDev/Citizens2#1255]
So this is an Feature request i think?
Well atleast thats what it says in the Citizens IRC, if this also is for the wiki i have no idea :D
So:
i found https://wiki.citizensnpcs.co/Blacksmith while i was looking for an easy solution to repair my items using an NPC.
but it isnt updated for the latest 1.12 snapshots.
so i now updated it myself [here](https://github.com/HurricanKai/Blacksmith)
i wanted to ask if i shoud open an pull request to the [wiki linked](https://github.com/instinxx/Blacksmith) page or what?

also i wanted to ask if it is possible to change the article a bit, if my updated is aprooved. so the 3 new variables in the default config are also in the wiki.

Thanks already!

btw, im sorry for my english =)

**Comment by fullwall** [comment]
I can add you as a wiki editor if you'd like.

**Comment by HurricanKai** [comment]
That woud be Great.
Can i then just change it?

**Comment by mcmonkey4eva** [comment]
Hey! Come talk to us on Discord https://discord.gg/Q6pZGSR
We can set your repo up to be the main one (wiki, CI, etc) if you want to be the maintainer
