### ISSUE TITLE
NPC acts as real player

### ISSUE THREAD

**Issue by PresidentxMC** [CitizensDev/Citizens2#1258]
I am experiencing the following bug:
my (custom) plugins recognise NPC's as real players

` @EventHandler
public void onDamage(EntityDamageEvent e) {
Entity victimEntity = e.getEntity();
Utils.b("test");
if(victimEntity.hasMetadata("NPC"))
Utils.b("this player is an npc. instanceof player ? "+(victimEntity instanceof Player));}`
(the Utils#b method sends a message to all players and the console, it's a debug method)
The first couple of times I hit the NPC, it doesn't output anything. But after doing it a few times it starts outputting "this player is an npc. instanceof player ? true"
It's the same regardless of whether I create the NPC through the API or through the command /npc create.
When I do /npc playerlist, regardless of whether or not it says "added" or "removed", it will first not output anything and after a few times start outputting.
In the config, I set:
 player:
    remove-from-list: true

Versions:
Minecraft: 1.12
PaperSpigot: git-paper-1154 (MC 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
Citizens: citizens-2.0.22-SNAPSHOT.jar (latest version)

**Comment by PresidentxMC** [comment]
Also: the NPCClickEvent isn't being fired. I have two listeners listening for it, one with a debug message that outputs the name of the clicked NPC and there is no output when I click an NPC

**Comment by fullwall** [comment]
You need to listen for NPCRight/LeftClickEvent specifically. The LeftClickEvent may be taking some of the debug output here. The entity should have the NPC metadata regardless of whether that setting is true or false - you can use CitizensAPI.getNPCRegistry().getNPC(entity) if you want a consistent way of getting the NPC (or check if instanceof NPCHolder).
