### ISSUE TITLE
Unknown mob network type id -1 

### ISSUE THREAD

**Issue by Dzanko2** [CitizensDev/Citizens2#1260]
>[2K [15:31:40 INFO]: Dzanko[/178.40.78.52:42342] logged in with entity id 609 at ([world]1299.7745002015122, 141.82636052179672, 1112.4737734532098) 
>[2K [15:31:40 INFO]: Dzanko lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1 
>[2K [15:31:40 INFO]: Dzanko left the game 
- Minecraft 1.12 and Citizens 2.0.22
 This doing for all players when join

**Comment by i9hdkill** [comment]
Guess you are using ViaVersion?

**Comment by Dzanko2** [comment]
Man, Thanks you so much!  :)
