### ISSUE TITLE
npc setname over 16 characters - Feature Request

### ISSUE THREAD

**Issue by scorixear** [CitizensDev/Citizens2#1261]
Hi, 
I am currently developing a faction plugin and I spawn custom NPC's with skins via command.
I also Add them to the tablist and I want to change the Name over their head to their jobs they are in plus their name.
This is obviously more than 16 characters so the String gets shortened.
But this regulation is just for playernames. I know that there can be more than 16 Characters in the name over the head (playernames on my server have that).
Could there be an option of only changing the name over the head

**Comment by mcmonkey4eva** [comment]
Er, what? The limit is much higher than 16 characters thanks to a pile of tricks we apply.
Make sure you're up to date running the latest Citizens builds, and hand reasonable settings!

**Comment by scorixear** [comment]
Oh, so you have that for minecraft 1.8?

**Comment by mcmonkey4eva** [comment]
Update your server to latest versions if you want realistic support .-.

**Comment by scorixear** [comment]
Oh well, Minecraft got out of being always used the latest version.
ove 30% of all Servers are still 1.8 and many users, especially from my server don't want minecraft 1.12 because it generally needs more game power wich lets the game lagg.
A lot of players want also still a unique, not overdone minecraft. 
So I thought, that a minecraft 1.8 support is reasonable.

**Comment by scorixear** [comment]
Well if thats not an option, I tried to change the name vie setCustomName and setCustomNameVisible
but the citizens-npc is not changing the name?
Have you got any blocks there? Because I could only see the same thing in your rename command.

**Comment by lhdev** [comment]
I'm seeing a similar issue, setting the name to &f(&6RANK&f) AReallyLongPlayerName truncates the display name.  The saves.yml file shows correctly.  Selecting the NPC shows the name correctly but the hologram name is truncated and doesn't show the rank.

**Comment by scorixear** [comment]
Yes, you can see that in the code at  the rename command.
They are getting the first Substring of the String if there are more Characters than 16. 
If you use the /npc rename command an error, saying that there are more than 16 Characters show up.
The problem is, that there is no real reason to shrink the name above the entity. And that there is no reason to count ColorCodes

**Comment by lhdev** [comment]
Also, if the string is longer than 16, character 17 is then consider character 1 and is returned as the name.
So "ThisIsAReallyLongName" will return the hologram name as "gName"

**Comment by scorixear** [comment]
Depends which version you use i think

**Comment by lhdev** [comment]
I'm using 2.0.22 (MC 1.10-1.12) on MC 1.12

**Comment by mcmonkey4eva** [comment]
@lhdev make sure you have scoreboard stuff enabled and functioning. It sounds like that component didn't work properly for you. (That's one of the main tricks we use to extend NPC names past the limit)

**Comment by lhdev** [comment]
@mcmonkey4eva Hey thanks, I do have the following in the config.yml in the npc section

  player-scoreboard-teams:
    enable: true

Are you referring to something else?  I looked over the documentation and will be the first to admit I could have overlooked it.

**Comment by mcmonkey4eva** [comment]
It could also be a conflict with any plugin that edits scoreboards.
Try setting a scoreboard team on a player or an NPC or whatever via commands, and give the team a prefix or suffix.
Then find out why that didn't work - as that's exactly what Citizens does, except through internal server calls instead of commands :P

**Comment by lhdev** [comment]
Any special considerations when using EssentialsX EssentialsXChat and PermissionsEX along with Citizens2?
