### ISSUE TITLE
[Request]NPC horse mount

### ISSUE THREAD

**Issue by Galactic-dragon** [CitizensDev/Citizens2#1265]
Can you  make NPC's  mount horses?

**Comment by co221133** [comment]
Yup :)
First, create a new NPC. With it selected, do the following command: /npc type horse
You can type /npc help to find the horse-related commands to figure out how to change the color/pattern/etc. Type /npc to get the horse's ID. After that, select the NPC you want to ride the horse. Then type: /npc mount --onnpc {NPC_Horse_ID} without the {}'s.

**Comment by Galactic-dragon** [comment]
Could i make the Horse act like  a real horse like being faster and jumping and such

**Comment by fullwall** [comment]
You would need a plugin for that
