### ISSUE TITLE
NPC's Killable with SkillAPI

### ISSUE THREAD

**Issue by co221133** [CitizensDev/Citizens2#1266]
Hiya guys. This is Minecraft 1.11.2.

Basically, I use SkillAPI to apply a slight damage buff to each player. It checks whenever a player attacks, and deals 10 additional damage to the player's target. However, this damage is separate from the player, and is able to kill NPC's who are otherwise invulnerable to damage/death. Basically, if a player with this skill punches an invincible NPC, the NPC will die.

I assume this is a bug. Any chance of it getting fixed?

**Comment by mcmonkey4eva** [comment]
That'd be an issue with SkillAPI, it's likely manually enforcing death of entities, which is something we can't do anything about from our end.

**Comment by co221133** [comment]
Gotcha, I'll go report it there. Thanks for your help.
