### ISSUE TITLE
NPC-Equipment-Editor

### ISSUE THREAD

**Issue by Loapu** [CitizensDev/Citizens2#1267]
Citizens uses the PlayerAsyncChatEvent to trigger if someone uses "offhand" or "helmet" to equip something in those slots. But if I use this event to cutstomise the chat it does not get triggered and I only write "offhand" or "helmet" into chat. The thing is inside the Text-Editor "add" and the other triggers work because they do not use the AsyncChatEvent. 

Hope you understand my problem.

Kind Regards,
Benjamin

**Comment by fullwall** [comment]
Fixed
