### ISSUE TITLE
Citizens conflict with ProjectKorra (Bending) plugin?

### ISSUE THREAD

**Issue by FearlessFrost** [CitizensDev/Citizens2#127]
I'm not sure if this is a problem on Citizen's end, but if I install citizens with the ProjectKorra plugin (Adds the ability to "bend" minecraft blocks like in Avatar: The Last Airbender), certain "moves" stop working, as in their animations don't function properly, they don't cause damage/interactions, etc. I have a bug report on their website (projectkorra.com) as well, but I don't seem to be getting any information on the problem.  As far as versions go, I've tried mutltiple versions of Citizens with versions of ProjectKorra, no luck for any. This also happened with the outdated version of ProjectKorra (Minecraft: The last Airbender). We're using Spigot 1.7.10 build 1595. 

Any help is greatly appreciated!

**Comment by Catpants** [comment]
I also have this issue, I have used latest dev builds, had this issue for a while, it disables phasechange, as well as interferes with airbending passives.

**Comment by FearlessFrost** [comment]
I never got around to responding to my original post here due to college and holidays, but I did find a 'fix' of sorts recently. 

I tested with the latest dev builds of both plugins on 1.8 Spigot without any luck, until I dumped my entire Citizens folder and let it regenerate. So far, it seems like all moves are working for now.

**Comment by Catpants** [comment]
How long has it been "fixed", because I did this and it was fixed for only a day, after a day, although I am still on 1.7.10
