### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Vallo92** [CitizensDev/Citizens2#1270]
When I install the plugin my server has an increase in memory usage that I do not have before. I only created 10 NPCs for my leaderboard (LeaderHeads plug).
- https://timings.aikar.co/?id=32e6b00681d146c7aadabb7f25d7a1c9
- Minecraft Spigot 1.12.1 - Citizens 2.0.22 (1.12 ALPHA #1) (last version)

**Comment by Kuzzzmaz** [comment]
помогите можно ли сесть на npc

**Comment by mcmonkey4eva** [comment]
@Kuzzzmaz this page is English only.

**Comment by mcmonkey4eva** [comment]
@Vallo92 I don't think that page reports anything to do with memory?

**Comment by fullwall** [comment]
Using #1272 as the main issue for this
