### ISSUE TITLE
Mermory leak with citizens

### ISSUE THREAD

**Issue by Brokkonaut** [CitizensDev/Citizens2#1272]
Since 1.12 we have huge problems with leaking memory. So I created a memory dump. EMT tells me this:

> 10.523 instances of "net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC", loaded by "org.bukkit.plugin.java.PluginClassLoader @ 0x5171425a8" occupy 413.796.184 (13,55%) bytes. These instances are referenced from one instance of "java.util.HashMap$Node[]", loaded by "system class loader"
>
> Keywords
org.bukkit.plugin.java.PluginClassLoader @ 0x5171425a8
java.util.HashMap$Node[]
net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC

http://cubeimage.de/images/2017/08/20/jFGJ.png

This is about two hours after restarting the server and we do not have 10523 NPCs, but only around 200.
I don't really know how to interpret it, but maybe someone of you knows.

Server: Paper 1.12.1 build 1191
Citizens: v2.0.22-SNAPSHOT (build 1487)

If you need any more information: I still have the memory dump, so i could create more reports

**Comment by xikage** [comment]
I analyzed a heap dump after experiencing the same issues and can confirm the findings here. From what I can gather it appears that Citizens NPCs are generating massive amounts of data related to the 1.12 player Advancements, all of which eats up incredible amounts of memory.

The heap dump I analyzed was 6gb in size and the majority of the memory being used was from Advancement data being retained by EntityHumanNPC

**Comment by fullwall** [comment]
Does the latest build help?

**Comment by xikage** [comment]
Ran the update for a few hours, still experiencing the issue.

**Comment by Brokkonaut** [comment]
I tested it too, the problem still exists.

**Comment by fullwall** [comment]
Made a new build - should help unless the advancements are being generated somewhere else.

**Comment by brutuscat2** [comment]
It doesn't appear to be an issue anymore after running the server for a few hours.

**Comment by SXRWahrheit** [comment]
Holy shit, I was wondering why RAM usage was so abysmal in 1.12. Thank you for reporting this. Will try the new build.

**Comment by xikage** [comment]
The latest update definitely improved things however the issue is still happening for me. It took much longer for the memory to max out this time though, but an analysis still shows advancement data is clogging things up.

**Comment by fullwall** [comment]
Thank you @xikage something must be generating advancements, it's hard to debug because the advancement code is awful and split among many files. I will continue looking on Monday.

**Comment by Brokkonaut** [comment]
I can confirm that the bug is not fixed. Isnt it possible to clear the NPCs Advancement data when the NPC is removed from the entities/players list? AdvancementDataPlayer.a() does that

**Comment by BlackBeltPanda** [comment]
Same as #1127 ?
