### ISSUE TITLE
How i change custom skins in npc's

### ISSUE THREAD

**Issue by ninomato** [CitizensDev/Citizens2#1273]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

**Comment by mcmonkey4eva** [comment]
`/npc skin Notch`

**Comment by ninomato** [comment]
Hi guys,
I am in doubt of how to put the skin of the link below in a npc of the plugin Citizens
Link of skin: http://www.minecraft-heads.com/custom/heads/humans/6585-lucio

Thanks for all!

**Comment by mcmonkey4eva** [comment]
Unfortunately "player head" sites aren't always directly compatible with NPCs.
The easiest way is to put the skin on a player and save it with `/npc skin NAMEHERE -p`
the player can change their skin away after that's saved.

**Comment by ninomato** [comment]
How do I take the npc cover? I put my skin on it but I do not have skin cover and it has a cover, is it because of the npc name that has a cover?
Image: http://imgur.com/a/M122y

**Comment by mcmonkey4eva** [comment]
`cover`?

**Comment by ninomato** [comment]
cape

**Comment by mcmonkey4eva** [comment]
Yeah if the NPC Name has a cape, it might give one to the NPC

**Comment by ninomato** [comment]
Ok, how i remove this cape without change npc name?

**Comment by mcmonkey4eva** [comment]
Could add a color code to the npc name, would make it the same name but not internally recognized as being that name

**Comment by fullwall** [comment]
Use /npc skinlayers --cape false
