### ISSUE TITLE
Can't move NPC head trougth API

### ISSUE THREAD

**Issue by checkium** [CitizensDev/Citizens2#1276]
When I teleport the NPC to a location with a specific yaw, his body moves but the head stays still.

**Comment by jorisguffens** [comment]
bump

Happens too with my code:

`
npc.spawn(loc);
npc.faceLocation(loc);
`

The npc is spawned on the right location but always looks to yaw: 0, pitch: 0
In the saves.yml file the yaw is NaN and pitch is 0.

We use paper 1.12.2 and citizens 2.0.22-SNAPSHOT

**Comment by mcmonkey4eva** [comment]
@jorisguffens that code is wrong, faceLocation is a TARGET to LOOK AT, not a location to gather a yaw from. A location looking at itself will of course produce a NaN.
