### ISSUE TITLE
Can't Use Citizens In 1.8

### ISSUE THREAD

**Issue by Woofydude** [CitizensDev/Citizens2#1277]
Whenever I download the newest 1.8.1 version and use it, it says https://image.ibb.co/jAqCcQ/2017_08_22.png. If you have a version for this, let me know.

Thanks!
Woofydude

**Comment by mcmonkey4eva** [comment]
Please update to 1.8.8, or any other "supportable" version. (1.9.4, 1.10.2, 1.11.2, 1.12.1)
