### ISSUE TITLE
Random Text in Chat When Hitting Things

### ISSUE THREAD

**Issue by Autopilot6532** [CitizensDev/Citizens2#1278]
This is a bug or something.

Every time I hit something alive (mobs, NPC/citizen, other players, lines of text with 1 character in each line gets placed in chat.

For mobs, 
1
a
is what placed in chat when you hit them. 

For my Sell All NPC
1
2
c
gets placed in chat when you hit him.

For my menu NPC
1
2
e
is what placed in chat for hitting him.

The image demonstrates what I am talking about. 

I tried reinstalling a different Citizens .jar file version, but it either is incompatible with my others plugins or the chat glitch still remains. 
It's also not the config folder as I removed that and it generated a brand new one, yet the error it's still spamming chat. 

![2017-08-22_21 58 49](https://user-images.githubusercontent.com/31265498/29597268-25d24c3c-8787-11e7-9751-ef0a908a9fb3.png)

**Comment by mcmonkey4eva** [comment]
That... doesn't sound like it'd be directly caused by Citizens, bar some debug getting stuck enabled by glitch somewhere...

**Comment by Autopilot6532** [comment]
If I didn't know 100% for sure it was Citizens, I wouldn't have said it was.

Haha, but it is Citizens causing this.

**Comment by mcmonkey4eva** [comment]
Can you replicate this on a server running nothing other than Citizens?

**Comment by Autopilot6532** [comment]
Well it's obviously not going to generate any errors if you're on a completely vanilla server w/ only Citizens added; if that was the case, every single person on here would be making this same exact post.

**Comment by mcmonkey4eva** [comment]
Then... it's not the fault of Citizens.
Lol.

**Comment by Autopilot6532** [comment]
I found out, it was actually Guards causing it.

**Comment by Autopilot6532** [comment]
I guess without Citizens, Guard doesn't work, that's why I thought it was Citizens.

**Comment by mcmonkey4eva** [comment]
Ah. Yep!
