### ISSUE TITLE
Issue: Npc can be moved by players

### ISSUE THREAD

**Issue by killertudse** [CitizensDev/Citizens2#1279]
Greetings.
Some of my players recently discovered a bug with the Citizens plugin.

It is actually possible to move an NPC by using a fishing rod. If you right click with the fishing rod and hit an npc, they will actually be moved. 

Thank you!

**Comment by mcmonkey4eva** [comment]
Are you running an up-to-date Citizens on 1.12.1 minecraft?

**Comment by killertudse** [comment]
Hello - Yes i am.
I can attempt to update to a newer build?

**Comment by brutuscat2** [comment]
I can reproduce this - it moves the NPC forward. I am using the latest dev build along with the latest Paper build (also happens on Spigot) on 1.12.1.

**Comment by killertudse** [comment]
Yes, exactly - heh.
As you can imagine this is causing a lot of issues. I was hoping the bug wouldnt spread, but slowly people just found out.

**Comment by Bodyash** [comment]
Also, NPC can be moved by explotion velocity, lighting and water\lava

**Comment by mcmonkey4eva** [comment]
BTW, as a "backup" for this,
Set a single point using `/npc path` for NPCs you want to remain in place.
That way if they get knocked out of their spot, they just walk on back!

**Comment by HurricanKai** [comment]
You can, Use an item, (if the NPC has one with an Knockback resistance, or make the NPC Invincible (no idea if that works but ...) [Minecraft Wik](https://minecraft.gamepedia.com/Attribute)

**Comment by fullwall** [comment]
It's tricky to fix this because Spigot's fishing API doesn't fully capture the fish event and there are other ways to move the NPC. I could make a command to make sure the NPC can't be moved but it would have to be added per-NPC. Is that OK?

**Comment by brutuscat2** [comment]
That would be fine.

**Comment by ElementalRealm** [comment]
didint fixed my problem at #1348

**Comment by fullwall** [comment]
I can't move the NPCs in the latest spigot/Citizens.

**Comment by fjeddy** [comment]
This issue has re-appeared in 1.15

**Comment by m31317015** [comment]
@fjeddy use /npc collidable
