### ISSUE TITLE
[Feature]Animation for NPC

### ISSUE THREAD

**Issue by Tiplish** [CitizensDev/Citizens2#1280]
Hello,

We have used Citizen so far ago now and there is something that i dream to be able to perform : animation of my NPC.

I use Betonquest and nuNPCDESTINATION for this but there is many thing that i can't do. 

For example, force my NPC to use his axe (close to a tree maybe) to simulate the action of getting logs. 

Or another thing : when players are not close to the NPC, my NPC move his head through the default position.

The idea is to have realistic movement for NPC and i would know if citizen could add animation as feature? Maybe there is already a way to do this?

Thanks :)

**Comment by mcmonkey4eva** [comment]
Citizens has this feature in the API.
If you want a quick command to use it, install Denizen: https://www.spigotmc.org/resources/denizen.21039/

You can do with that, EG: `/ex animate <npc> animation:arm_swing`
to cause your current selected NPC to swing its hand (and any held item)

**Comment by Tiplish** [comment]
:o So fast answer :D Me and my team used Denizen and i was afraid to have to develop a lot.

But if the feature is already in it, it's perfect. Thanks a lot ;)
