### ISSUE TITLE
Pitch Targeting Problem With Crackshot

### ISSUE THREAD

**Issue by TerraPrimal** [CitizensDev/Citizens2#1283]
(Copy and Pasta from Sentinel as requested by mcmonkey4eva https://github.com/mcmonkey4eva/Sentinel/issues/192)

Hi mcmonkey4eva,

It seems Sentinels with a CrackShot weapons don't target correctly when it comes to Pitch.
They seem to shoot only at eye level even if the target is above that. I have included two screenshots.
The firs is using a basic CS weapon (included) and it firing at the 2-3 block of the tower trying to shoot at the pigs. The second one is using a vanilla bow (correctly).
The green lines are arrows.

Thanks!
https://i.gyazo.com/34f1adf6f78059854097ac838412a7ef.png
https://i.gyazo.com/d482967524da45ad3e0878e684768a46.png
https://pastebin.com/YQQktc92

------

Added a small video showing this in action: https://youtu.be/kGz1Y9Gt2ys
As you can see, as long as the target is on the same level as the NPC the aiming is fine, as soon as its on a few blocks higher it can't hit the mob.

**Comment by fullwall** [comment]
Hmm... head pitch is controlled by ControllerLook which might explain this otherwise would need to look at Sentinel's code.

**Comment by fullwall** [comment]
@mcmonkey4eva is this still an issue?

**Comment by mcmonkey4eva** [comment]
I believe so yes, I haven't verified it but there are newer issues (such as #1454 ) with matching pitch troubles

**Comment by mcmonkey4eva** [comment]
This might be fixed by https://github.com/CitizensDev/Citizens2/commit/9f9647a6152527dd8fecfb58c75d2de17ead9039
Please let us know if it isn't!
