### ISSUE TITLE
Pathfinder bug: NPC blocked by open door

### ISSUE THREAD

**Issue by Rio6** [CitizensDev/Citizens2#1290]
When I'm using new pathfinder, the NPC gets too close to the wall, so when there's an open door on the side, the NPC would get blocked.

![recording-2017-08-30_09_42_22](https://user-images.githubusercontent.com/15951245/29884535-ab2558f2-8d68-11e7-9b0d-d144984a04a8.gif)

Without debug

![recording-2017-08-30_10_03_01](https://user-images.githubusercontent.com/15951245/29885155-a493632e-8d6a-11e7-85ba-b80735917b87.gif)

Citizens version 2.0.22
Spigot version 1.12.1-R0.1

Is there any way to solve it?

**Comment by Oruss7** [comment]
Same problem. Remove doors xD

**Comment by fullwall** [comment]
Try the latest update (assuming you are using the new pathfinder).
