### ISSUE TITLE
Permissions request

### ISSUE THREAD

**Issue by KingMyrrdin** [CitizensDev/Citizens2#1293]
Sorry for my english, but i'll try to explain it clearly.

**feature request** I guess,
Is there any possibility to set permissions for everyone npc individually?
I mean if for example one group have permission - citizens.npc.talk.<id> they can talk with npc.
Or not only talk, maybe deny interact completely if don't have that permission, becouse now like i see there's permission citizens.npc.talk witch allows to talk with every npc.

thanks, waiting for your answer

**Comment by mergu** [comment]
Hello! This can be very easily done by scripting with Denizen.
https://www.spigotmc.org/resources/denizen.21039/

Take a look, and join the Denizen/Citizens team over on our discord if you need help:
https://discord.gg/Q6pZGSR
