### ISSUE TITLE
WIKI - Link Broken

### ISSUE THREAD

**Issue by HurricanKai** [CitizensDev/Citizens2#1295]
have a look at: https://wiki.citizensnpcs.co/Characters

![image](https://user-images.githubusercontent.com/22711887/29969848-563c1c0c-8f22-11e7-8359-f3adc776cb66.png)

Is broken. The link give 500 back.

i also want to recommend
replacing 
![image](https://user-images.githubusercontent.com/22711887/29969867-7802a842-8f22-11e7-8741-10651d81d322.png)
and with that 
https://wiki.citizensnpcs.co/Sentry with an direct link to https://wiki.citizensnpcs.co/Sentinel
and replacing https://wiki.citizensnpcs.co/Sentinel with an direct link to https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md
because in my opinion, it makes no sense to redirect to an page which tells you to go to another page which tells you to go to another page.

**Comment by mcmonkey4eva** [comment]
Characters page updated per request.
Sentinel page passingly updated, I don't think there's a good autoredirect option? Not sure, but current form is fine.

**Comment by HurricanKai** [comment]
Thanks @mcmonkey4eva 
------
I also woud recommend removing  any UltraTrader references
like https://wiki.citizensnpcs.co/UltraTrader
because the 3 related extern pages
http://ultratrader.thedemgel.com/ - Not Reachabel
https://tenowg.ci.cloudbees.com/job/UltraTrader/ 403 - Acces denied
https://github.com/DemgelOpenSource/UltraTrader/ 404 - Unknown

**Comment by mcmonkey4eva** [comment]
Removed links to that page.
