### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by SamB440** [CitizensDev/Citizens2#1296]
https://timings.spigotmc.org/?url=temubijuna

As you can see the playerupdatetask has very bad performance causing tps to drop very low.

I'm using 1.12.1

**Comment by Brokkonaut** [comment]
You should run the timings a bit longer to get reliable results (10 minutes or more)

**Comment by SamB440** [comment]
Here https://timings.spigotmc.org/?url=maceribini idek how my server is still up

**Comment by mcmonkey4eva** [comment]
How many NPCs do you have?
What are they doing? (Walking paths, fighting mobs, ...?)

**Comment by SamB440** [comment]
About 50 I'd say, all contained in 1 place in the world. Most are walking. Nothing else

**Comment by mcmonkey4eva** [comment]
Walking is pricey, unfortunately. By default Citizens does a bit of cleverness to enhance walking accuracy, whereas Mojang rarely bothers. Citizens also, I note, does not do much in the way of "large group oriented" path finding, or repetition cleaning, but rather recalculates the path every time you instruct it, and, dependent on settings, it recalculates further as it moves along in case of sudden blockage.
A few things to try:
Reduce pathfinding range where possible.
Give shorter paths to NPCs where possible.
Ensure all given paths are unblocked. A 100% blocked path will wreck the pathfinder. A partially blocked path (IE complex obstacles) will cause noticeable slowing if overdone.

**Comment by SamB440** [comment]
Thanks, I removed all walking npcs and found some that were stuck. TPS improved dramatically after they got removed.
