### ISSUE TITLE
NPC skins sometimes dissapear

### ISSUE THREAD

**Issue by MithrandirCraft** [CitizensDev/Citizens2#1297]
Sometimes, the skins for the npc's on my network's hub dissapear. Here's an example of no skins being shown:
http://i.imgur.com/dLHcWc6.png

I don't know how I triggered this. All those npc's should have a skin, but they dissapeared.
Once I log back in they'll be there again.

However sometimes they do actually work. It also seems to differ between players. Sometimes some can see them, sometimes not. Sometimes they are there, and sometimes they are skinless.
It looks like a visual glitch which affects randomly, but is easy to trigger.

No errors on console.

Citizens Version (I think it's the free version, but some other staff may have purchased it):
2.0.22-SNAPSHOT (b1492)
Spigot for mc 1.12.1 (with Bungee)
Running on Java 8.

If I find out anything else I'll post it here.

More stuff:
- Some other plugins I tried have the same issue (Like BungeeNPC).

**Comment by Xenmai** [comment]
If I'm not mistaken, the Mojang skin service only accepts a certain amount of requests per unit of time. This means that, if you have a lot of NPCs with skins, they might stop sending the data back sometimes. It is a known issue and happens to all of us. I'm afraid I don't really know any way to solve that.
Feel free to correct me anybody if my explanation is incorrect.

**Comment by mergu** [comment]
This is a client-side bug, usually based on latency or server load. Mojang also limits skin requests, but if that was the issue your own skin would also not load. There _are_ ways to refresh your npcs using Denizen, though skins are not guaranteed to work even on the refresh and it'd be up to you to decide when to do the refreshing. 

Also, Citizens is free and open-source! The "paid" version on spigot is just a suggested donation :)

**Comment by fullwall** [comment]
Latest version makes skins permanent which should help with this.
