### ISSUE TITLE
Citizens pathfinding bug in water

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#1298]
Hello,

I'm just posting that : https://github.com/mcmonkey4eva/Sentinel/issues/201
Sentinel's author just replied that this is a Citizens bug.

Thanks.

**Comment by Blamo27** [comment]
@mcmonkey4eva Any news ? :/

**Comment by Midnight9746** [comment]
For me, citizens don't go anywhere in water, they just float there until the target comes back to land.

It could be a citizens bug, Try using /npc path and make an npc go through water, if it makes it. Then it's just the plugin's communication with each other.

You could try setting the sentinel npc to avoid water all together, so when it's target is in the water, it act like an enderman and walk around. Or maybe it's the range at which the npc chases you at. Try setting it higher to see if the npc would still try to go after you.

The close / range combat might be an issue, then again they could just be guarding you or walk on their own into this mess. So idk

**Comment by Blamo27** [comment]
@Midnight9746 What's your Citizens version ?

**Comment by Midnight9746** [comment]
Well my server is 1.12.2 and my Citizens version worked on 1.12.1, so it has to be the 1.12 version.

**Comment by Midnight9746** [comment]
It just says "2.0.22-snapshot (build 1487)"

**Comment by Blamo27** [comment]
@mcmonkey4eva @fullwall Any news ?

**Comment by fullwall** [comment]
Latest build includes a fix for the Citizens pathfinder.

**Comment by Blamo27** [comment]
@fullwall thanks ! 😄

**Comment by Blamo27** [comment]
@fullwall I'm affraid it's still not working properly. NPCs still don't know how to move in water. Here is a video demonstrating how a NPC tries to move from point A to point B (both red wools) when there is water involved.

https://cf-e2.streamablevideo.com/video/mp4/106zp.mp4?token=1521239930-RSJF%2BX6mEihpkOgTRQCcdRWWIBOUi09ObIxU%2BXWPvGY%3D

**Comment by fullwall** [comment]
Can you try with debug-pathfinding turned on?

**Comment by Blamo27** [comment]
It does work with newfinder. However, we can't seem to use that config option with our save.yml, because it considerably destroys our server performance, causing this :

https://cf-e2.streamablevideo.com/video/mp4/rky95.mp4?token=1521294301-lHecoEkz1O4PlCDtL14PQujgS7srfeVuZ1K0LbdVsRc%3D

Do you know why does it do that ? It seems like newfinder is making a ton of calculations... Note : we have a very heavy save.yml, if this can have an effect on that (over a thousand NPCs).

**Comment by Ferocimo** [comment]
We did numerous testing, and it IS caused by the size of our save.yml. The more NPCs we have, the more time the server takes to make this kind of calculations after a restart : that means that, if we have less NPCs but still a lot, after let's say 20 seconds, the server will stop lagging and the NPCs will normally walk again.
That isn't the case without new finder. This means we can't use new finder with too much NPCs. Do you know why ?

**Comment by Midnight9746** [comment]
Sounds like it's telling all of them to pathfind. But it should only tell the ones in loaded chunks.

**Comment by Blamo27** [comment]
@Midnight9746 We tried with different versions, and with the default configuration.

**Comment by Midnight9746** [comment]
Ah, understood. Are you forcing chunks to be active anywhere? (Just trying to figure out if you're NPCs are facing lag more than anything. If they are calculating new paths when no one is near them.)

I have the new paths, but under about 500 NPCS, and they don't lag like that.

**Comment by Ferocimo** [comment]
I don't think we have anything specific forcing chunks to be active.
I suspect the size itself of the save.yml file to be related to that issue (ours weighs over 9 mo).

**Comment by Midnight9746** [comment]
My NPCs did the same walking movement, but it was being ran on my pc, with tons of plugins. Once I've removed those, and made sure to solve lag. They fixed themselves.

If you want, I could try loading your citizens save on my server and figure out from there. Assuming they run as intended with like 76+ plugins, it might just be the spigot build or citizens build. In any case, I want to help you! :D (and I don't care for what citizens you have, just didn't want to run around a world spamming the create button lol).

**Comment by Ferocimo** [comment]
We actually managed to make it work in water without new-finder. In other terms, they now move normally in water, even without new-finder (which we don't want since it's lagging the server).

So, there's still that issue with new-finder, but it's not really a problem for us anymore. Thank you anyway for the help provided !

**Comment by mcmonkey4eva** [comment]
Update: per https://github.com/mcmonkey4eva/Sentinel/issues/262 it apparently works now with `new-finder`, but not with following an entity specifically (as in: `setTarget(Entity)` fails, but `setTarget(Location)` works.)

**Comment by fullwall** [comment]
Is this still an issue?

**Comment by mcmonkey4eva** [comment]
NPCs still are very bad at navigation in water. They seem to sometimes be able to get through, but very slowly.

**Comment by fullwall** [comment]
Tracking here https://github.com/CitizensDev/Citizens2/issues/2993
