### ISSUE TITLE
Citizens not working on my server

### ISSUE THREAD

**Issue by Seamonkeyking** [CitizensDev/Citizens2#1299]
Hi I recently just downloaded citizens on my 1.8.8 server..... My server does not recognize that citizens has been downloaded and I therefore cannot use the plugin.  Any help you can provide would be great!

**Comment by mcmonkey4eva** [comment]
Grab a way outdated version of Citizens to match your way outdated server here; https://wiki.citizensnpcs.co/Versions

**Comment by Seamonkeyking** [comment]
I tried that but it didn't work
do you have a recommended version for me to use

**Comment by mcmonkey4eva** [comment]
The version matching your server version on that page is the recommended one...

**Comment by Seamonkeyking** [comment]
Ok i will try again and let you know how it turns out

**Comment by Seamonkeyking** [comment]
will i also need a really outdated citizens CMD

**Comment by mcmonkey4eva** [comment]
If you want Citizens NPCs to execute commands or similar, use https://www.spigotmc.org/resources/denizen.21039/ which has full back support for even 1.8.8, old as it is.

**Comment by Seamonkeyking** [comment]
yeah I have a pvp server and pvp servers are best on 1.8 at least in my opinion

**Comment by Seamonkeyking** [comment]
ok well it appears to be working

**Comment by Seamonkeyking** [comment]
![2017-09-07_21 50 16](https://user-images.githubusercontent.com/20732284/30192634-9c5b91a6-9416-11e7-8a6a-be6d688568eb.png)
should i look like that?

**Comment by mcmonkey4eva** [comment]
That looks right :)
