### ISSUE TITLE
NPC names that are over 16 characters are getting truncated

### ISSUE THREAD

**Issue by Blackvein** [CitizensDev/Citizens2#1300]
When I name an NPC anything over 16 characters, the first 16 characters get dropped and the name over the NPC's head is the remainder of the String.

Example: Here i've named an NPC "mmynameissixteen" which is exactly 16 characters long: http://i.imgur.com/jLIPMy5.png

No problem, but if I make the NPC name "mmynameissixteencharacters" the first 16 get dropped and the name just becomes "characters": http://i.imgur.com/GPCFKaC.png

The proper full name still appears in /npc list, as well as the saves.yml but above the NPC's head it seems to not display correctly. This was tested on a blank server with nothing but Spigot and Citizens running.
Also player-scoreboard-teams.enable is set to true in the Citizens config.

Citizens v2.0.22-SNAPSHOT (build 1494)
Minecraft 1.12.1
CraftBukkit version git-Spigot-da42974-876d22c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by Pugabyte** [comment]
I am also experiencing this problem. I've heard from multiple sources that this is not what's supposed to happen

**Comment by mcmonkey4eva** [comment]
It's not supposed to happen... Citizens handles longer names by generating scoreboard prefix/suffix as needed to extend a full name. It's really weird to maintain sometimes though...

**Comment by mcmonkey4eva** [comment]
`npc rename` command is patched in latest dev build (it was not updating scoreboards correctly, the way that npc create did)

**Comment by Pugabyte** [comment]
This is not fixed for me on build 1548

**Comment by mcmonkey4eva** [comment]
@Pugabyte likely conflict with some scoreboard control plugin? Or you've accidentally disabled scoreboards in the Citizens config.
Rename command was broken before, but scoreboard setup in general works fine on latest builds.
I confirmed they work fine a few days ago while building the rename command patch.

**Comment by Pugabyte** [comment]
We confirmed it works on a test server, my bad. We'll do some research and see if we can figure out which plugin as there's a few we have that mess with scoreboards.
