### ISSUE TITLE
[Question] Is there a way to make NPC upside down?

### ISSUE THREAD

**Issue by thomasdaley2** [CitizensDev/Citizens2#1303]
I am looking to make an upsidedown cow in a "oven" at a spawn tarvern kitchen.... cannot see any commands that allow rotation but thought it best to ask

**Comment by mcmonkey4eva** [comment]
name it `Dinnerbone` or `Grumm`, either nameplate will cause any entity to flip upside down!
It's technically a minecraft easter egg.

**Comment by thomasdaley2** [comment]
Thank you!  




On Mon, Sep 11, 2017 at 8:59 PM +1000, "mcmonkey4eva" <notifications@github.com> wrote:












name it Dinnerbone or Grumm, either nameplate will cause any entity to flip upside down!

It's technically a minecraft easter egg.
