### ISSUE TITLE
I can't handle a NPC when it is out of my sight. Help me!

### ISSUE THREAD

**Issue by Yangoon1222** [CitizensDev/Citizens2#1304]
- Minecraft version : 1.8.9 (1.8.8)

Developing my plugin, I realized that I can't handle a NPC when it is out of my sight.

First, 'npc.getEntity()' doesn't work  when there aren't any player near the NPC.

Second, 'npc.getNavigator().setTarget(Entity entity, boolean attack)' also doesn't work in the same situation.

For solving these problems, I tried hard (decompiled Citizens plugin, wrote HumanController2 class extending HumanController class (HumanController class is related with npc.getEntity()) , wrote SkinUpdateTracker2 class extending SkinUpdateTracker class (SkinUpdateTracker class is related with navigation))

But, I failed.. Could you give any advice for me?

**Comment by mcmonkey4eva** [comment]
... change config settings / etc. to keep the entity spawned even when out-of-range of players?
(Keep-Chunks-Loaded and similar settings are relevant)

Also why did you decompile a plugin, when the source code is available right here on github...

**Comment by Yangoon1222** [comment]
I  set 'keep-chunk-loaded' option true, but I  still can't  solve the second problem. In my opinion, the second is related with the SkinUpdateTracker. When I saw the class, npc's navigating is shown to nearby player. But I want npc walk to the target even when it is out-of-range of players.

**Comment by Yangoon1222** [comment]
And I decompiled the plugin for seeing the source of 1.8.8 version.

**Comment by mcmonkey4eva** [comment]
Github includes a full back history for all versions.
Also, how about ... other settings?
Such as this: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/Settings.java#L80

**Comment by Yangoon1222** [comment]
Here is sad news..
I set 'skin-view-distance' option 10000.0 and after 100000.0, but the situation is the same.
It seems that NPC waits for me until I approach it closely, and starts navigation.

**Comment by mcmonkey4eva** [comment]
Oh, wonderful! Glad to hear it all works now!
