### ISSUE TITLE
[BUG] NPCs can be moved by using fishing rods

### ISSUE THREAD

**Issue by ConstructorLeo** [CitizensDev/Citizens2#1305]
Hi,

When you right-click an NPC with a fishing rod and then let go the NPC gets pulled by the fishing rod.
The server runs Spigot 1.9.2 and a citizens version that runs on 1.9.2.

**Comment by mcmonkey4eva** [comment]
Options available:
- Update your server
- Set a "/npc path" point to ensure the NPC stays in one place
- Create a custom trait or similar to lock the NPC in place

Best of luck!

**Comment by ConstructorLeo** [comment]
Hi,

How would you create a trait to lock the npc in place.

**Comment by mcmonkey4eva** [comment]
That requires Java codework.
