### ISSUE TITLE
More lag

### ISSUE THREAD

**Issue by SamB440** [CitizensDev/Citizens2#1306]
Hi!
Me again...
I'm having a lot of lag again from Citizens. I'm using 1.12. I've made sure there are NO stuck NPCs whatsoever, and I only have about 2 walking NPCs which are working fine. I've had the TPS dropping to 5. Using latest Citizens version. Any idea what's up?
https://timings.spigotmc.org/?url=qunulokeka

**Comment by mcmonkey4eva** [comment]
Would need a higher quality report than spigot timings

**Comment by SamB440** [comment]
What....??

**Comment by mcmonkey4eva** [comment]
Plugins or a profiler.
IIRC MassiveLag is an example of a plugin that gets clearer reports.

**Comment by SamB440** [comment]
That's $30 for a plugin I'm mostly likely only going to use once!! No thanks!! I already have to deal with PayPal disputes regarding chargebacks. Perhaps this? https://www.spigotmc.org/resources/lagmonitor.21348/

**Comment by mcmonkey4eva** [comment]
I didn't realize it cost money, I just used a name I recalled hearing, sorry.

Yeah that one you linked looks sufficient.

**Comment by SamB440** [comment]
I have found this spamming my console after enabling debug mode
12.09 09:18:07 [Server] INFO Repathfinding 18 due to speed change 12.09 09:18:07 [Server] INFO Repathfinding 16 due to speed change 12.09 09:18:07 [Server] INFO Repathfinding 11 due to speed change 12.09 09:18:08 [Server] INFO Repathfinding 11 due to speed change 12.09 09:18:08 [Server] INFO Repathfinding 16 due to speed change 12.09 09:18:08 [Server] INFO Repathfinding 19 due to speed change 12.09 09:18:09 [Server] INFO Repathfinding 18 due to speed change 12.09 09:18:10 [Server] INFO Repathfinding 11 due to speed change 12.09 09:18:11 [Server] INFO Repathfinding 11 due to speed change 12.09 09:18:11 [Server] INFO Repathfinding 19 due to speed change 12.09 09:18:11 [Server] INFO Repathfinding 18 due to speed change 12.09 09:18:12 [Server] INFO Repathfinding 18 due to speed change 12.09 09:18:12 [Server] INFO Repathfinding 11 due to speed change 12.09 09:18:12 [Server] INFO Repathfinding 16 due to speed change 12.09 09:18:13 [Server] INFO Repathfinding 19 due to speed change 12.09 09:18:14 [Server] INFO Repathfinding 11 due to speed change 12.09 09:18:14 [Server] INFO Repathfinding 18 due to speed change 12.09 09:18:14 [Server] INFO Repathfinding 19 due to speed change 12.09 09:18:15 [Server] INFO Repathfinding 16 due to speed change

**Comment by mcmonkey4eva** [comment]
That could be relevant, especially with high pathfinding ranges and/or difficult paths...

**Comment by SamB440** [comment]
I just tried removing them, there was a slight increase but nothing significant. I've also tried removing the Sentinel plugin, that did nothing. I've even gone through every single NPC and teleported to them and nothing seems out of the ordinary. I do, however, have NPCs sitting down. Could that mean anything?

**Comment by mcmonkey4eva** [comment]
Try removing them, see what happens? They might be bugging.

**Comment by SamB440** [comment]
![2017-09-12_16 19 19](https://user-images.githubusercontent.com/11319274/30333985-33c22b8c-97d6-11e7-92ab-5014e31e7024.png)
This is what happens to my TPS (see chat)

**Comment by SamB440** [comment]
Please help.. when I remove citizens the lag completely disappears.. my players are quitting now

**Comment by SamB440** [comment]
Ok, so, shockingly enough, I found an NPC that was stuck in a block (somehow) that didn't even have any pathfinding enabled. I moved it out of the block.. and you guessed (or not?) the TPS shot up. I would also like to mention that this was an NPC created by the Shopkeeper plugin that depends on Citizens - If you have this plugin, be careful as it could have been the cause here. Thanks for your help.
