### ISSUE TITLE
Conflict TouchHandler HologramDisplays

### ISSUE THREAD

**Issue by DimaTiunov** [CitizensDev/Citizens2#1308]
Conflicts with the plugin for creating holograms. I'm no longer working with the TouchHandler of the event on the hologram line. They are created at the expense of hidden entities slime. Pls fix this.

**Comment by mcmonkey4eva** [comment]
... In English?

**Comment by DimaTiunov** [comment]
I apologize for my level of language proficiency, I write as I can. TouchHandler an abstraction in which you can describe the player's interaction with the hologram line. The censuses overlap it, for whatever reason
![default](https://user-images.githubusercontent.com/5381110/30325775-36466e94-97f0-11e7-81a0-2fa527d652e1.png)

**Comment by mcmonkey4eva** [comment]
I'm sorry, I honestly don't understand.
Do you have any English speaking staff or players that understand the issue that may be able to assist in translation?

**Comment by DimaTiunov** [comment]
this code not work if install Citizens https://pastebin.com/dAaX5v5Q

**Comment by DimaTiunov** [comment]
Something is blocking the interaction with these slime

**Comment by mcmonkey4eva** [comment]
Might be an error in your NMS handling? Citizens overrides and replaces the NMS Slime Entity class with a custom one that extends the original.

**Comment by DimaTiunov** [comment]
This piece of code I got with the help of a decompiler and make changes there will be problematic
