### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

### ISSUE THREAD

**Issue by JoaquimPedro201** [CitizensDev/Citizens2#1309]
In this issue, please include:
It says please report this bug
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
citizens 1.8
Hope you understand :P

**Comment by mcmonkey4eva** [comment]
You seem to have downloaded the wrong version.
Find the one that matches your server version EXACTLY
https://wiki.citizensnpcs.co/Versions

**Comment by JoaquimPedro201** [comment]
I still have the same problem

**Comment by JoaquimPedro201** [comment]
i changed it but nothing

**Comment by mcmonkey4eva** [comment]
What version is your server?
What version did you download?

**Comment by JoaquimPedro201** [comment]
server is 1.8 and i download 1.8.1

**Comment by mcmonkey4eva** [comment]
Are you sure you're 1.8 and not EG 1.8.8?

**Comment by JoaquimPedro201** [comment]
its 1.8.8
xD so which one do i download

**Comment by mcmonkey4eva** [comment]
http://ci.citizensnpcs.co/job/Citizens2/1308/

**Comment by JoaquimPedro201** [comment]
ty bro
hope it works
