### ISSUE TITLE
What traits work on which Living Entities

### ISSUE THREAD

**Issue by harm27** [CitizensDev/Citizens2#1315]
Hi,

I am trying to workout what traits work on which Living Entities npc's. 
Since i am writing a plugin for my server so that i can give my users some sort of menu where they can configure the menu.

Harm (Harm27)

**Comment by fullwall** [comment]
Probably best to cross each trait off in the TraitManager. Generally, inventory-related stuff only works on LivingEntities, as well as things like Age etc. but it's really trait-specific.
