### ISSUE TITLE
NPC's all being moved to server spawn building?

### ISSUE THREAD

**Issue by GRRRillaNinja** [CitizensDev/Citizens2#1318]
In this issue, please include:
- Bug
- https://pastebin.com/bbRWk9hf
- Snapshot 2.0.22

NPCs are being moved from the place where I put them onto the top of my main spawn building? The only NPCs that aren't moved have a walking path associated with them.

**Comment by mcmonkey4eva** [comment]
Likely conflict with another plugin. (For example, one that prevents players from leaving spawn without a permission)
