### ISSUE TITLE
Armorstand Nameplates

### ISSUE THREAD

**Issue by Lyesmith** [CitizensDev/Citizens2#1319]
Possible bug? Current Minecraft and Citizens2. I used `/ex animate n@<NPCNAME> animation:sit` to make some NPCs sit. After the nightly server restart, they all now have "Armorstand" nameplates hovering underneath them. I asked in the Discord if there was a way to toggle those off and on, he suggested I report it as a possible bug. If any other info is needed I'll be happy to provide it.

**Comment by Ouroboros1992** [comment]
Got this too, seems to add another one after resetting as well so now i've got 2 armor stand nameplates under the npcs.

**Comment by fullwall** [comment]
Seems like an issue with denizen? @mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
should be fixed in latest dev build via https://github.com/CitizensDev/Citizens2/commit/e4f059683a3f111e34c35589177c39fe512ecb1b
