### ISSUE TITLE
Could not pass event PlayerTeleportEvent

### ISSUE THREAD

**Issue by killertunes** [CitizensDev/Citizens2#1320]
In this issue, please include:
- whether this is a bug description or a feature request
Bug Description

- Link to server log & Citizens config if relevant (using e.g. pastie.org)
[citizens_spartan_bug.txt](https://github.com/CitizensDev/Citizens2/files/1327453/citizens_spartan_bug.txt)

- Minecraft & Citizens version if relevant
Citizens 1494 thru 1488 didn't test back further. Minecraft 1.12.2.

I also reported it to the Spartan Dev.

**Comment by mcmonkey4eva** [comment]
That has nothing to do with Citizens.
That's Spartan... but the problem is on your end!
You need to use **Spigot** not CraftBukkit.
