### ISSUE TITLE
[BUG] NPC's doesn't speak new text since update from 1.9.4 to 1.12.1

### ISSUE THREAD

**Issue by Shaskalynae** [CitizensDev/Citizens2#1321]
Hello !

We tried to check how we could resolve this, but since we updated our servers from 1.9.4 to 1.12.1, the NPC's doesn't say any new text. Old ones still work, it's just when we add new text on an NPC or when we create a new NPC. I didn't try to edit existing ones. Maybe do I miss some basic NPC config as I don't really know how it works, but I did as before and it worked with the 1.9.4 version of Minecraft.

Copy a NPC doesn't help and permission citizens.ncp.talk is added to groups. Even on single player, it doesn't work.

- Citizens v2.0.22-SNAPSHOT (build 1487)
- Minecraft 1.12.1

I don't have any logs as I don't have access to them. I'll ask for them.

Thank you for your help !

Shaska.

**Comment by mcmonkey4eva** [comment]
For more capable and trusty NPC chatter, we advise the side-plugin Denizen ( https://wiki.citizensnpcs.co/Denizen ) which links in to Citizens to allow interesting scripts to be applied to an NPC.

**Comment by Shaskalynae** [comment]
Thank you, I'll take a look at this !

**Comment by Shaskalynae** [comment]
Mmmhhh... Not a solution because we already used Denizen and it made our servers slow down. Lot of lags. Tried it for 2 days then removed it and everything went back to a normal usage of the ressources.

**Comment by mcmonkey4eva** [comment]
That's quite unusual. Denizen does literally nothing on the server unless you tell it to do something.
The only reason I could see that happening is if it conflicted with another plugin in some unexpected way...

**Comment by Shaskalynae** [comment]
Yeah, maybe. I'll ask the boss to check if it's the same as before or if it's resolved now. As we updated to 1.12.1, we had to update some plugins, so let's hope :)

Anyway, if there is another way to resolve the problem I'm facing, I will really appreciate it. But what can I give you to find where the problem is ?

(And excuse my poor english, it's not my main langage)

**Comment by mcmonkey4eva** [comment]
Honestly I couldn't name anyone that even uses the Citizens simplified text system :/
So, I have no idea.

**Comment by Shaskalynae** [comment]
Mmmh... It seems that the problem is resolved now. But I don't know how and if someone dit something... Anyway, I'll check for Denizen now.

Thank you again !
