### ISSUE TITLE
The permission citizens.* does not allow creation and controlling of all mob types

### ISSUE THREAD

**Issue by Brokkonaut** [CitizensDev/Citizens2#1323]
Some mob types are missing like witherskeleton, guardian, husk, rabbit and probably more are missing

**Comment by mcmonkey4eva** [comment]
What permissions plugin?
It's possible you have a bad-tier one that relies on the plugin.yml listing every damn valid possibility, and we just haven't updated it for the new mobs...

**Comment by Brokkonaut** [comment]
Yes it relies on the plugin.yml entries and as far as I know thats how it is specified in the bukkit api.

https://www.reddit.com/r/admincraft/comments/1omv9j/how_do_permissions_actually_work_in_bukkitspigot/ccthz5r/

**Comment by mcmonkey4eva** [comment]
That's the old method, which better permissions plugins (like PEX) don't rely on at all.

**Comment by fullwall** [comment]
Added new ones.
