### ISSUE TITLE
Horse/Mule NPC's

### ISSUE THREAD

**Issue by MWFIAE** [CitizensDev/Citizens2#1326]
While profiling for the PlayerUpdateTask I noticed another thing, which is right at the top of the lagmonitor:

![image](https://user-images.githubusercontent.com/6072971/31317679-98a40506-ac45-11e7-9b5f-5aa9cbf01955.png)

I only have 2 Horse/Mule NPC's and they are just standing still, doing nothing. 
Also I'm wondering since it say onChunkLoad, but at the moment there isn't even anybody in this world. 
So nothing should load the chunk, but that's a problem on it's own. (as I don't think it's citizens fault)

**Comment by Midnight9746** [comment]
Are they on the playerlist?

(/npc playerlist)

That makes plugins see them as players, but I'm not sure if it sees them as *actual* logged in players. Also is the chunk they're in the spawn chunk? (or set to always be loaded)?

**Comment by fullwall** [comment]
This screenshot looks incorrectly captured. Nothing loads the chunk, unless it's in spawn.
