### ISSUE TITLE
save Issue pls help

### ISSUE THREAD

**Issue by ammarmc** [CitizensDev/Citizens2#1333]
spigot-1.8.8.jar
citizens-2.0.16-SNAPSHOT
when i save the npc its create more save.yml
saves.yml1781548879694811241.tmp
saves.yml1781548879694811221.tmp
saves.yml1781548879694811231.tmp

and more like 100 save.yml i delete in 1 day
and when i delete the npc and i save and reload the server the npc respawn 
 /npc delete 1 or /npc remove 1
and if i do 
 /npc despawn 1 the get delete but not from the save.yml 

pls help 
``
19.10 22:31:26 [Server] INFO CONSOLE issued server command: /list 
19.10 22:30:53 [Server] INFO Citizens saved.
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.npc.SimpleNPCDataStore$1.run(SimpleNPCDataStore.java:68)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.util.YamlStorage.save(YamlStorage.java:105)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:163)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
19.10 22:30:53 [Server] WARN java.lang.NullPointerException: Nodes must be provided.
19.10 22:30:53 [Server] INFO Saving Citizens...
19.10 22:30:53 [Server] INFO Citizens saved.
19.10 22:30:53 [Server] WARN at java.lang.Thread.run(Thread.java:745)
19.10 22:30:53 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
19.10 22:30:53 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
19.10 22:30:53 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
19.10 22:30:53 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
19.10 22:30:53 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.10 22:30:53 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.10 22:30:53 [Server] WARN at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:106)
19.10 22:30:53 [Server] WARN at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:92)
19.10 22:30:53 [Server] WARN at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
19.10 22:30:53 [Server] WARN at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
19.10 22:30:53 [Server] WARN at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
19.10 22:30:53 [Server] WARN at ch.njol.skript.lang.Effect.run(Effect.java:54)
19.10 22:30:53 [Server] WARN at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86)
19.10 22:30:53 [Server] WARN at ch.njol.skript.Skript.dispatchCommand(Skript.java:1040)
19.10 22:30:53 [Server] WARN at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576)
19.10 22:30:53 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
19.10 22:30:53 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
19.10 22:30:53 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:235)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
19.10 22:30:53 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
19.10 22:30:53 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.10 22:30:53 [Server] WARN at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.commands.AdminCommands.save(AdminCommands.java:64)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:446)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.npc.SimpleNPCDataStore.saveToDiskImmediate(SimpleNPCDataStore.java:75)
19.10 22:30:53 [Server] WARN at net.citizensnpcs.api.util.YamlStorage.save(YamlStorage.java:105)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103)
19.10 22:30:53 [Server] WARN at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:243)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:108)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:146)
19.10 22:30:53 [Server] WARN at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:142)
19.10 22:30:53 [Server] WARN at java.util.ArrayList$Itr.next(ArrayList.java:851)
19.10 22:30:53 [Server] WARN at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
19.10 22:30:53 [Server] WARN java.util.ConcurrentModificationException
19.10 22:30:53 [Server] INFO Saving

> Citizens...`

**Comment by mcmonkey4eva** [comment]
Update your server and all plugins, we cannot support such an old version, sorry. :/

**Comment by ammarmc** [comment]
ohh :( i can't do that because i created personal guard plugin using script  the plugin for 1.8.8 work good but the save.yml i delete like 100 in day 
saves.yml1781548879694811241.tmp
saves.yml1781548879694811221.tmp
saves.yml1781548879694811231.tmp
i wish you will support 1.8.8 again <3

**Comment by BloodEko** [comment]
Which Plugin is it, what is it doing ?

**Comment by mcmonkey4eva** [comment]
I'd be happy to help you get your system updated to more recent versions.
EG For guards, https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md is a good option to start with. If you mean `Skript`, there's updates to that available, if you mean `DenizenScript` that is updated and ready as well.

**Comment by ammarmc** [comment]
thanks yes im using  Skript not DenizenScript 
and if you will like to cheack the plugin on my server its have a lot of ideas  you can add to sentinel <3
