### ISSUE TITLE
NPC'S bugging in tablist

### ISSUE THREAD

**Issue by durson54** [CitizensDev/Citizens2#1337]
Hello, so I have this problem...NPC's are bugging in tablist like for not even 1 second and they disappear and it repeats...how can I fix it?
I'm using Spigot 1.12 , Citizens 2.0.22

**Comment by durson54** [comment]
bump

**Comment by durson54** [comment]
is anyone alive? O.o

**Comment by mcmonkey4eva** [comment]
That's a known thing. There's not much we can do about. Mojang's fault.

Also, have a little patience lol.

**Comment by durson54** [comment]
well, I have server for 2 years and It's still happenning so... :D
