### ISSUE TITLE
PlayerUpdateTask high CPU usage

### ISSUE THREAD

**Issue by lucko** [CitizensDev/Citizens2#1339]
Hi. Over the last few weeks, I've noticed consistently high timings for the PlayerUpdateTask.

We have a lot of pathfinding NPCs on our server, so I initially dismissed it as perhaps being reasonable. However, on closer inspection, it seems the part of the task which is consuming tick time isn't pathfinding.

Timings reports:
`Citizens::Task: net.citizensnpcs.util.PlayerUpdateTask (interval:1)count(15496)  total(11.44% 103.448s, 13.19% of tick)`

With approx 100 players online, that task is occupying around 13% of the tick.

However, profiling shows that the biggest CPU drain in the entity tick is clearing advancement progress.

![](https://i.imgur.com/XpGDrgo.png)

This behaviour was added by 0a6b954976df895ba0758f92ee4b6a7494728b97, has it since been preceded by 78992529e5f393e20ed7e7cd6f45a0667119e3e6? In other words is it still necessary?

I'm going to trial moving this

https://github.com/CitizensDev/Citizens2/blob/master/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/entity/EntityHumanNPC.java#L125-L129

to here

https://github.com/CitizensDev/Citizens2/blob/master/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/entity/EntityHumanNPC.java#L201

on the assumption that it doesn't really need to be executed every time the NPC is ticked? Perhaps that's a bad assumption..? I don't know.

I felt I should at least make you aware of this, in case there's a more obvious fix you know of. :)

**Comment by Cryptite** [comment]
We're having the issue differently ourselves. I've posted some profiling data in the other major issue about this: https://github.com/CitizensDev/Citizens2/issues/1325#issuecomment-349461105

**Comment by fullwall** [comment]
Try the latest build, it should be faster

**Comment by Cryptite** [comment]
This still eats up a pretty significant chunk of the server tick.
![image](https://user-images.githubusercontent.com/399721/37244444-b91b0a1a-244e-11e8-9a58-55eb97e1989c.png)

**Comment by fullwall** [comment]
Players are expensive to run, I'd need output from a better profiler to pin down the problem. Aikar's timings are not helpful in 99% of cases.

**Comment by Cryptite** [comment]
Here're another set of screencaps from YourKit and Timings:

![image](https://user-images.githubusercontent.com/399721/37429679-14b9673e-279e-11e8-8dae-7910f9e3e48c.png)

![image](https://user-images.githubusercontent.com/399721/37429692-1d850fbc-279e-11e8-955a-9a71720eba17.png)

**Comment by mcmonkey4eva** [comment]
That's largely just standard player/entity tick there according to the YourKit timings.

It's also... not in the slightest bit significant compared to overall timings. 0% of the full thread time, and about 2% of the main server tick.

**Comment by Cryptite** [comment]
Indeed it's not causing my server strain at the moment, but it's not an insignificant portion of the server tick. I do have a large player-count fight coming soonish and might be able to report back if it causes problems relative to player count.

**Comment by fullwall** [comment]
I'd trust YourKit's sampling over the timings plugin sampling, although I'm not sure you have the right settings there as it's all being rounded down to 0. I use jProfiler myself and it has an option to report time spent in function which would be more helpful if there is the same thing in YourKit.

**Comment by Cryptite** [comment]
Here's a different view: 

![image](https://user-images.githubusercontent.com/399721/37476953-76309fb8-2844-11e8-89e4-5a133928c4a5.png)

Time(ms) is "Time spent in the method **including** time spent in subcalls. 
Own Time (ms) is "Time spent in the method **excluding** time spent in subcalls"

**Comment by fullwall** [comment]
Eh, again this isn't really helpful because it's not an average, just a total. Even this view shows that 100/33,564 = 0.3% of time total was spent in EntityHumanNPC#B_() which seems really miniscule compared to the rest of the subcalls. Why do you think Citizens is the problem here?

**Comment by Cryptite** [comment]
Mostly just digging into whether it's causing much of a performance hit and it's eating up too much CPU than it needs to be.

**Comment by lucko** [comment]
Hi, thanks for responding & working on this fullwall <3

The patch I linked in the original post fixed the issue for me - I had a quick look at your latest commit and it looks like it will have the same effect. As far as I'm concerned this can be closed now. :)

**Comment by mcmonkey4eva** [comment]
Woo! :D
