### ISSUE TITLE
Citizens Plugin and CitizensCMD will not work

### ISSUE THREAD

**Issue by RarelyRoger** [CitizensDev/Citizens2#1340]
These are the errors for Citizens
29.10 16:45:35 [Server] ERROR [Citizens] Citizens implementation changed, disabling plugin.
29.10 16:45:35 [Server] INFO [Citizens] Disabling Citizens v2.0.22-SNAPSHOT (build 1487)
29.10 16:45:35 [Server] ERROR [Citizens] v2.0.22-SNAPSHOT (build 1487) is not compatible with Minecraft v1_8_R3 - try upgrading or downgrading Citizens. Disabling.
These are the errors for CitizensCMD
29.10 16:49:51 [Server] INFO [CitizensCMD] Enabling CitizensCMD v1.2.0
29.10 16:49:51 [Server] INFO [CitizensCMD] Citizens is needed for this plugin to work!
29.10 16:49:51 [Server] INFO [CitizensCMD] Citizens.jar is not installed on the server!
29.10 16:49:51 [Server] INFO [CitizensCMD] Shutting down...
29.10 16:49:51 [Server] INFO [CitizensCMD] Disabling CitizensCMD v1.2.0
if you can help me that would be great! thanks for taking your time to look at this problem!

**Comment by MusicScore** [comment]
You're using the wrong version of Citizens for your 1.8 server. Use this link to see which version you need: https://wiki.citizensnpcs.co/Versions

**Comment by RarelyRoger** [comment]
Thanks so much
