### ISSUE TITLE
teleport trigger in waypoint editor causes NPCs to sink into the ground

### ISSUE THREAD

**Issue by alanbecker** [CitizensDev/Citizens2#1343]
using citizens-2.0.22-SNAPSHOT.jar
minecraft version 1.12

When I set one of my NPC's waypoints as a teleport trigger, and then use "here", as soon as the NPC goes to that waypoint it sinks halfway into the ground of that waypoint location. Not at the location that I set.

Also when I type world:34:143:-34 as the coords it doesn't accept it. Is this the right syntax? it's asking for `world:x:y:z`. the world name is indeed world.

Thanks for your help.

**Comment by alanbecker** [comment]
i'm really eager to have this bug be fixed soon, I have 115,000 subscribers waiting to see this npc setup. essentially its a scene where it looks like many npcs are all going in one direction constantly. if i can get the npcs to go through the scene and then teleport back to the beginning, i can achieve this effect.

**Comment by fullwall** [comment]
Fixed, apologies for the delay

**Comment by mcmonkey4eva** [comment]
Fix was in: https://github.com/CitizensDev/Citizens2/commit/147a3e4c26646011a494cdf360685f38e08d9456
