### ISSUE TITLE
Name and Fishing Rod Bug

### ISSUE THREAD

**Issue by ElementalRealm** [CitizensDev/Citizens2#1346]
I have a bug on my server and i beleave its caused by something in the plugin. When I do /npc name it just doesnt do nathing i can't remove their names. And whenever I reset the server the /npc gamemode resets.
The problem is NPC's should be immortal but i can hit and move them with a fishing rod. I suposed the /npc gamemode 1 command would solve it but it doesn't. Can you help me?

**Comment by ElementalRealm** [comment]
Can any one help me? It's urgent

**Comment by mcmonkey4eva** [comment]
#1347 explains the closing of this.

**Comment by ElementalRealm** [comment]
reopened at #1348

**Comment by mcmonkey4eva** [comment]
"unrelated reason" yeah ok mate I guess you just can't read past a few sentences? not sure why you think me telling you there's already an open issue for this qualifies as "unrelated" but ok.
