### ISSUE TITLE
Fishing Rods / Vulnerable / Nametags

### ISSUE THREAD

**Issue by ElementalRealm** [CitizensDev/Citizens2#1348]
Hope this "Issue" is not closed again for unrelated things that have nathing about the bugs/problems my team have. Has I said:

I found some problems that impossibilitates me to use Citizens properly. I have the last build installed.
The problems are:

- I can't make /npc name to work. Before I updated the plugin it worked fine then i updated the RAM (doesn't affect the files) and the plugin it self and it stoped working. Can you help me? I need to make the nametags get vanish;

- I want my NPC's to be never moved, even if i dont add any value on the vunerability they can be moved and killed with fishing rods even if i do /npc gamemode 1;

- Every time I reset de server (even doing /npc save) they reset all the gamemodes of each npc;

This are all the problems im facing now. We all have though days @mcmonkey4eva hope you can answer this post I would be glad to be helped since I tried to fix it for anyways I know.
Im sorry if I got mad or if I overeacted im just facing problems with too many thing now i I have a date to finish our project.

**Comment by mcmonkey4eva** [comment]
Fishing rod: for the third time, defer to https://github.com/CitizensDev/Citizens2/issues/1279
npc name: Why is RAM relevant?! Check plugin/server/etc. updatedness
gamemode: Why are you setting gamemodes on NPCs, like, at all?

**Comment by ElementalRealm** [comment]
Im not setting it at all of them. I just did it once to check if it would solve the problem with the fishing rods.
How about the /npc name command? I didnt updated nathing else besides citizens it self (to last build) and the RAM (that doesnt affaect nathing)

**Comment by ElementalRealm** [comment]
About the fishing rod i already did it before i posted the issue here. The thing is they kill the npc (even when they are invunerable) with a fishing rod, somtehing like 50 hits later.

**Comment by ElementalRealm** [comment]
I fixed the nametag problem and the move problem without help. But I still need help making the NPC's imortal cause even on /npc gamemode 1 or just with /npc create <name> (that would make them imortal) I can kill them with a fishing rod. Can you help me?

**Comment by fullwall** [comment]
Can no longer reproduce this.
