### ISSUE TITLE
citizens save and relaod

### ISSUE THREAD

**Issue by Roy416** [CitizensDev/Citizens2#1349]
Using mc version on mc 1.12.1.  So after i restart the server. I create 2 npcs, decided i didnt like one so i removed it. did /citizens reload and all is good. When i create another one and removed it and did /citizens reload it comes back all the time. even after /citizens save and me waiting a few seconds. I even put the save delay to 0 to see if that would help but its not. help?

**Comment by mcmonkey4eva** [comment]
Defer to https://github.com/CitizensDev/Citizens2/issues/1335 for this issue.
