### ISSUE TITLE
How to choose and lock the "color" of the mobs-NPC like animals ?

### ISSUE THREAD

**Issue by Evewins** [CitizensDev/Citizens2#1355]
Hi :)
I don't know if it's a bug or if I am doing something wrong, but everytime the server restarts my animals-npc change colors randomly and I would like them to keep the same "skin". For example for bats.

Thanks !

**Comment by fullwall** [comment]
Do bats have different colors?

**Comment by Evewins** [comment]
I figured out it was a ressource pack called Soartex Fanver making this actually, it randomly changes the color of pigs, bats, and chickens !
