### ISSUE TITLE
Citizen Version 1116 for my 1.7.10 Spigot Server deleted, since supposed crashing my server. Please help!

### ISSUE THREAD

**Issue by ImScroll** [CitizensDev/Citizens2#1356]
Hello. Lately I've installed version 1166 on my citizens, and it worked for like the first time I started my server. Then after that, my server would crash every 5 minutes started. My hosting company said that it looks as if "Citizen NPCS" are causing the error. Please help me , for I really need citizens for my server. My server is a 1.7.10 spigot server as well.
Thanks to anyone that can help me.

Sincerely,
ImScroll

**Comment by HurricanKai** [comment]
1. Is there a reason you are not Wanting to update to at least 1.8?
2. Have you installed Citizens or Citizens 2?
3. If you have installed Citizens 2, did you download it from [here](http://ci.citizensnpcs.co/job/Citizens2/1166/)?

**Comment by ImScroll** [comment]
Yes, I'm just afraid that since my server is a spigot 1.7.10, and if I use a 1.8 citizens version, my 1.7.10 players won't see the NPCs.
I'll get you the log aswell.

**Comment by MusicScore** [comment]
Your debug from issue #1353 says that your Spigot version is 1.7.9, not 1.7.10. Please try this version for 1.7.9 first:
http://ci.citizensnpcs.co/job/Citizens2/1142/

**Comment by ImScroll** [comment]
My bad, yes it was Spigot 1.7.10. I thought it was Spigot 1.7.9, sorry I deeply apologize for that!

**Comment by MusicScore** [comment]
No no, it's not confusion. The error stacktrace you gave me specifically says your server is 1.7.9.

If the 1.7.9 version doesn't work, then I don't know why. I've tried Citizens on 1.7.10 before, and have not crashed.

**Comment by mcmonkey4eva** [comment]
Yeah just update to latest 1.12.2 
We can't support a server that ancient.
