### ISSUE TITLE
npc not in list after reload/restart

### ISSUE THREAD

**Issue by BasiliusFleischlein** [CitizensDev/Citizens2#1357]
some of my npc disapear from the /npc list after a server restart or using the command /reload

downloaded 2.0.22 (MC 1.10-1.12) from https://dev.bukkit.org/projects/citizens 

Plugins i use on the Server:

- ASkyBlock
- AsyncWorldEdit
- ChestRestock
- ChopTree3
- Citizens
- ClearLagg
- dtlTraders
- Essentials
- Guilds
- HolographicDisplays
- InfernalMobs
- Jobs
- LWC
- MinePacks
- MineWallet
- MultiInv
- Multiverse-Core
- Multiverse-Portals
- MythicMobs
- NametagEdit
- NewGods
- NPC Police
- NPCAuctions
- Parties
- PermissionEx
- PixelPrinter
- PlaytimeRewards
- PlugMan
- PyroWeather
- RecipeRedone
- Sentinel
- ShopChest
- SkinRestorer
- Towny
- TuxTwoLib
- Vault
- VoidSpawn
- WizardlyMagic
- WorldEdit
- WorldGuard

**Comment by Midnight9746** [comment]
When you created them, how soon did you /reload? Recent npcs despawn because the plugin loads the last save before they got made.

Use /citizens save before reloading, or wait a while for the server to auto save it.

**Comment by mcmonkey4eva** [comment]
NEVER use `/reload`
