### ISSUE TITLE
I can't start a plugin with 1.8

### ISSUE THREAD

**Issue by ItsNikola1** [CitizensDev/Citizens2#1358]
I try 1.8 , and 1.8.8!
Nothing!
Citizens and CommandNPC
![untitled](https://user-images.githubusercontent.com/34491083/33908193-e0d48f6a-df87-11e7-9668-c2049639bc4b.png)

**Comment by Mwthorn** [comment]
Have you tried these versions? https://wiki.citizensnpcs.co/Versions

**Comment by ItsNikola1** [comment]
OK,thanks i try this
