### ISSUE TITLE
Right-clicking npc will run command twice

### ISSUE THREAD

**Issue by axepex** [CitizensDev/Citizens2#136]
Someone help please if you can...

Whenever I right-click an NPC, it runs the command twice.

For example... to select an NPC named "Dude" with a stick, the console will return with:

Selected NPC Dude
Selected NPC Dude

---

Also, I use Quester... so when I right-click an NPC to complete an objective, it will run the right-click command twice.

Anyone seen this happen before?

**Comment by nodar86** [comment]
I'm having this exact problem with Sigot 1.10.2 and v2.0.20. I'm using ProQuests and every interaction with NPC-s triggers twice

**Comment by mcmonkey4eva** [comment]
That may be an issue with ProQuests, @nodar86 - if you're /sure/ it's not, open a **new** issue.

**Comment by nodar86** [comment]
Wow thanks, that was fast :O How could I check that?
