### ISSUE TITLE
1.9.4 citizens

### ISSUE THREAD

**Issue by Kudner** [CitizensDev/Citizens2#1361]
This is a feature request.
I want the newest build for citizens for be 1.9.4 compatible, because there is a bug with /npc glowing --color saying "null" that can be fixed by installing the latest build.

Is there another build for spigot citizens 2 compatible with 1.9.4 other than 2.0.18 (1.9.4 UPDATE #1)?

**Comment by mcmonkey4eva** [comment]
This may be made available at some point, but it is highly recommended you just run latest.

**Comment by mcmonkey4eva** [comment]
1.9 is basically unused really. If anyone's legitimately still using 1.9 in particular... stop. Update your server to latest 1.12.2, there's no reason for 1.9
