### ISSUE TITLE
High tick usage %

### ISSUE THREAD

**Issue by BBoyJD10** [CitizensDev/Citizens2#1362]
High tick using Citizens v2.0.22-SNAPSHOT (build 1496)

       9.57%	  10.19%	135.51 s	     5.09 ms	 1.0	      26.6k	    Task: PlayerUpdateTask(interval 1)

**Comment by fullwall** [comment]
How many player NPCs do you have? What are your server specs? Can you please use a proper profiler like WarmRoast? I can't debug the issue with this information.

**Comment by fullwall** [comment]
Please post any new info in this issue over here https://github.com/CitizensDev/Citizens2/issues/1339
