### ISSUE TITLE
Sentinel NPCs unequipping non leather armor and bows.

### ISSUE THREAD

**Issue by nrich588** [CitizensDev/Citizens2#1363]
I believe the issue may be related to the Heroes mod, but I am unsure. I am using the latest version of Spigot, Heroes, and Citizens. Upon equipping an NPC with non leather armor, they immediately remove it when interacted with. Bows will disappear on respawn but not swords or other weapons.

**Comment by mcmonkey4eva** [comment]
If you can confirm this happening on a server with only requirements (Spigot, Citizens, Sentinel) then reply below or open a new issue. If you can't replicate in that environment, it likely is just Heroes or another plugin.
