### ISSUE TITLE
/npc remove: not working

### ISSUE THREAD

**Issue by Oruss7** [CitizensDev/Citizens2#1364]
Hello,

Command despawn NPC but not remove it from config. Still spawn at server restart or config reload.

Citizens v2.0.22-snap build 1496
Spigot 1.12.2 (latest at this day)

I'm using denizen too.

Thanks

**Comment by mcmonkey4eva** [comment]
Defer to https://github.com/CitizensDev/Citizens2/issues/1335 for this issue.
