### ISSUE TITLE
[Feature Request] NPC's & Fishing Roids

### ISSUE THREAD

**Issue by ZEROOblivious** [CitizensDev/Citizens2#1366]
In this issue, please include:

Minecraft 1.12

Citizens - 2.0.22 (ALPHA #2) 

We have NPC's walking around our spawn or standing there on " Guard "

Players can hit the NPC's with Fishing Rods & push them around spawn. 
with /npc vulnerable that disables the damage noise the fishing rod makes but could we prevent the NPCs to stop moving?

**Comment by mergu** [comment]
Heya, since nobody got back to you, one solution is to set a path to the npc's resting spot using /npc path. That way, if players pull them, they walk back to their spot.

**Comment by fullwall** [comment]
So you want the NPC be vulnerable but also allow fishing rods to pull them?
