### ISSUE TITLE
Could not pass event ChunkLoadEvent to Citizens v2.0.22-SNAPSHOT (build 1493)

### ISSUE THREAD

**Issue by Fargus5** [CitizensDev/Citizens2#1367]
Please to find below an error occurred suddenly

https://github.com/BalrogGames/herosfaith/issues/16

**Comment by Fargus5** [comment]
With the build 1498 this problem has been fixed?

**Comment by fullwall** [comment]
java.lang.IllegalStateException: Asynchronous entity remove!

Seems like a plugin conflict. Try removing all other plugins apart from Citizens and see if the problem remains.

**Comment by Fargus5** [comment]
It seems to be fixed grace to some other fix in other plugins
