### ISSUE TITLE
Console Warning / Error Messages  { BUG }

### ISSUE THREAD

**Issue by ZEROOblivious** [CitizensDev/Citizens2#1368]
In this issue, please include:

Citizens - 2.0.22 (ALPHA #2).jar
Spigot 1.12.2 Server

--> Citizens Config Pastebin:  https://pastebin.com/FgqWp8YB

--> Citizens Console Error / WARN --> https://pastebin.com/vLkBfkaj

Currently having problems with some NPC's randomly despawning / Not saving!

**Comment by mcmonkey4eva** [comment]
Sorry for slow reply. Pastebin's were deleted so going to assume the issue is resolved. If not, please reply with functional and non-expiring links.
