### ISSUE TITLE
Potion Effect on mob npcs

### ISSUE THREAD

**Issue by johnsoncui02** [CitizensDev/Citizens2#1369]
Server Version: 11.12.1 snapshot spigot.jar
Citizens Version: 2.0.22 (1.12 ALPHA #2)

Issue:
Players are able to throw potions such as invisible potion to say a villager NPC and causes the villager to be invisible. In small servers it's easy to manage people like that, but is it possible to make the NPC invincible or immune to potion effects somehow? Thank you

**Comment by fullwall** [comment]
Fixed
