### ISSUE TITLE
Citizens not remembering armor stand state.

### ISSUE THREAD

**Issue by bobotje** [CitizensDev/Citizens2#1370]
Hi
Request/Bug Report
On the server we use Armor Stands Tools to modify armor stands to how we like it and so we can be more creative. The problem is the following, when we set the armor stand how we like it and we restart the server or reload the plugin. The armor stand NPC goes back to the original armor stand state.
- I was using MC 1.12.2, server 1.8.8, Citizens v2.0.16-snapshot (build 1267)

**Comment by mcmonkey4eva** [comment]
`I was using MC 1.12.2, server 1.8.8, Citizens v2.0.16-snapshot (build 1267)`
What?

Update server to latest. Also, figure out what version you're on at all.
