### ISSUE TITLE
Citizens Flicking (invisible from certain close distance)

### ISSUE THREAD

**Issue by EHEBrandon** [CitizensDev/Citizens2#1372]
Okay so is there a fix for the npcs glitching out basically turning invisible? Like they can be viewable one second then move the camera a bit they can start flickering and it seems they disappear only going a few blocks away. I have a multiverse server meaning more then one world in another world it isn't as bad as the other. I only have them for quest and tutorials so they stand still at their positions and they still seem to disappear all the time. Any fix or any news on a update anytime soon?

**Comment by mcmonkey4eva** [comment]
that's not a Citizens problem, likely a conflict with another plugin

**Comment by EHEBrandon** [comment]
I've been using the same plugins for a year now and it just started happening after buying premium version.

**Comment by mergu** [comment]
The 'premium version' is the exact same as the free one.
The Citizens spigot page:
![image](https://user-images.githubusercontent.com/29823405/34844570-f3ce45ba-f6df-11e7-8aef-c54bd88aaa9b.png)

**Comment by EHEBrandon** [comment]
I know that but what I meant was when I used a older version back when I had a server on 1.8 I never had this issue about two years later I make a new server bought this plugin to support dev and I'm having this issue when I never had it before. I made sure all my other plugins are up to date and they never conflicted with it two years ago.

**Comment by mergu** [comment]
Can you confirm that this bug is present in a clean spigot build with only the Citizens plugin installed?
