### ISSUE TITLE
Not working for 1.8 servers

### ISSUE THREAD

**Issue by SaltyThehHacker** [CitizensDev/Citizens2#1373]
The plugin will not work for my 1.8 server please help

**Comment by mcmonkey4eva** [comment]
update your server?

**Comment by SaltyThehHacker** [comment]
if I update it people in 1.8 can't use it

**Comment by mcmonkey4eva** [comment]
tell them to update their clients?

**Comment by SaltyThehHacker** [comment]
well I have had a 1.8.1 server in the pissed and people were pissed they can't use it in 1.8

**Comment by mergu** [comment]
minecraft is on version 1.12.2
