### ISSUE TITLE
how fix this?

### ISSUE THREAD

**Issue by josecuervo2016** [CitizensDev/Citizens2#1374]
In this issue, please include:
- whether this is a bug description or a feature request

It is a description of an error

- Link to server log & Citizens config if relevant (using e.g. pastie.org) 

https://pastebin.com/j78HZzsh

- Minecraft & Citizens version if relevant

Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[Citizens] Loading Citizens v2.0.16-SNAPSHOT (build 1267)

**Comment by mcmonkey4eva** [comment]
update your sever

**Comment by josecuervo2016** [comment]
My server is updated, the Dev of the Pvp Plugin says that it is because of the Citizen version and I try all of them and I throw away that error, as I solve it. It does not help me to say update, the server I want solutions,

**Comment by mcmonkey4eva** [comment]
`     

Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)` that is not an updated server. That is a server released in 2014. Four years old.

**Comment by josecuervo2016** [comment]
yes but it is the last version of 1.8 and for the pvp is the best in many servers have the same I'm asking for help with that error not to tell me that my spigot is older that I know.

**Comment by mcmonkey4eva** [comment]
update to latest and add a plugin that reverts the PvP to old style.

**Comment by josecuervo2016** [comment]
You are not giving me an answer if you do not know what is that error do not want me to change all the server friend, apart from the pvp of 1.8 you can not change it if you put the 1.12 there is no plugin that leaves the old system of pvp 1.7 and 1.8 so if you think you say the right things at least

**Comment by mcmonkey4eva** [comment]
there are multiple popular plugins that do that.
The error is related to your server being outdated and unsupported.

**Comment by MusicScore** [comment]
Your Citizens is even more outdated than your server lol. For a list of links for your appropriate version, please refer to this page: https://wiki.citizensnpcs.co/Versions

**Comment by josecuervo2016** [comment]
Well the plugin dev told me that it should be the version of the citizen thanks for that page I thought I had the latest version of citizen for spigot 1.8. this is the latest version for citizen 1.8 spigot?
http://ci.citizensnpcs.co/job/Citizens2/1308/

**Comment by mcmonkey4eva** [comment]
or... update your server.

**Comment by josecuervo2016** [comment]
MusicScore 👍  Thank you, update from that page the citizen and for now the error did not come out anymore. that's what I needed, not other comments that do not contribute anything, not everyone wants to use spigot 1.12

**Comment by mcmonkey4eva** [comment]
@MusicScore please do not encourage users to intentionally use unsupported version.
@josecuervo2016 please update your server.
