### ISSUE TITLE
Not Loading Player Heads

### ISSUE THREAD

**Issue by nexlemav** [CitizensDev/Citizens2#1376]
Spigot 1.12.2 & Citizens 2.0.22 alpha 2

I'm having an issue to where player heads aren't loading & once I remove this plugin they load fine. Is there a setting in the config to where player head will load again? I'm not getting any errors in console or in game.

**Comment by Midnight9746** [comment]
Yeah I'm having the same problem. It's essentially just Mojang's servers, they just changed the skin auth recently.

It works on the lastest versions, but for me it doesn't work on my actual server, only the one ran on my pc.

**Comment by fullwall** [comment]
I looked into this and it seems that player heads use the same skin fetching mechanism as Citizens does leading to rate limiting. I'm not sure how to fix this as it's fundamentally a rate limiting problem.
