### ISSUE TITLE
Command -p not working (null)

### ISSUE THREAD

**Issue by Zeuscp1** [CitizensDev/Citizens2#1377]
As the tittle says. when i use -p it just says null.

**Comment by mcmonkey4eva** [comment]
... what? What command?

**Comment by Zeuscp1** [comment]
Sorry, i tought you would know. When i want to set a skin to my npc i find the skin i like in internet, then i put it on my character. I spawn the npc. /npc create name then i use /npc skin nameofmycharacter.

all good, i have the name and the skin set up. 

Now when i use /npc skin -p to set the skin permanent so that i can change the skin of my character and set up more npc with skins. when i do that command, the game just tell me (null) in red. Everything is working but not that....I need help please

**Comment by Zeuscp1** [comment]
![untitled](https://user-images.githubusercontent.com/35397831/34910148-1ae11846-f87d-11e7-977b-1bfb0b141bac.png)

please help me i really need to fix this. look

**Comment by Zeuscp1** [comment]
Man, i fixed it, the command should be place like this. 

/npc create [name that you want for your npc] (Doesnt matter the skin)
Now, go and change your current skin for the one that you want the NPC to have. 
once changed, (you may need to restart the server or log out-in the server)
/npc skin yourname. Now the npc will have your skin but it will change if you change the skin of your character. We fix this, after done all this.
-/npc skin -p yourname.
now we can change our skin and the npc skin will remain the same. 
/npc skin -c to restart the skin to his original name-skin

Sorry if i wasnt clear enough. i just post all the process because i been looking in internet a couple of days and no one seems to know about the command, people are buying accounts to set skins.
