### ISSUE TITLE
null or air chat message when right click

### ISSUE THREAD

**Issue by HyperFierce** [CitizensDev/Citizens2#1380]
In version 2.0.22 (1.12 ALPHA #2) and 2.0.22 (1.12 ALPHA #1) when I create an NPC and right click the NPC whether I am Opped or De-Opped I receive a chat message saying as follows:
main
null or air
off
null or air
I have tried swapping between the second newest version and the newest. I have tried changing up some world guard permissions and I cannot figure out how to get rid of this chat message. I need to in order to properly show quests. Any help is appreciated. 
![2018-01-18_22 14 24](https://user-images.githubusercontent.com/35602933/35154940-13c5a58c-fcfa-11e7-90cb-592435cd30ec.png)

**Comment by mcmonkey4eva** [comment]
That doesn't look like it was output by Citizens.

**Comment by HyperFierce** [comment]
It only happens when I right click citizen NPC's though.

**Comment by HyperFierce** [comment]
Did you by any chance forget to remove debug messages?


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mcmonkey4eva** [comment]
Not Citizens, check for other plugins at fault.
