### ISSUE TITLE
NPC not talking

### ISSUE THREAD

**Issue by Zeuscp1** [CitizensDev/Citizens2#1381]
Hello, my npc are not talking. Last build

**Comment by Midnight9746** [comment]
I know I'm not exactly who you're expecting but sometimes my npcs don't talk to, and there's possible reasons for that.

In case you don't know, you need to give them something to say by doing:

/npc select id
(make sure you have the right one)

/npc text
(open editor)

Type 'add' in chat then type what you want them to say.

If you think you're done, you're not. You then need to do:

Type 'close' (have to still be in the editor, which you should be unless you exited)

That should make them a close talker, meaning if someone is near them they should talk to them.

Then type 'range #' with # being how many blocks in each direction should the player be within to receive messages from your npc. Such as 'range 5' makes it so when your 5 blocks, 4 blocks, 3/2/1 blocks away, it will talk to you.

There's also a another thing you can type which is 'random' but only if you want the npc to pick an entry you gave using 'add'.

The range one was at times my problem, but other problems *might* be a Plugin preventing their chat, might be world guard blocking chat in that region, or if somehow a player with the same name as the npc is muted on the server.

Something you could also try incase that didn't help is first making sure you do /citizens save to avoid the npc from reverting back to the last save (or disappearing if it didn't exist last save) and reload the plugin (/citizens reload)

Another thing for me was that the npc came back after the reload and would sometimes say 'Hi, I'm <NPC>' and have no other entires, so the best fix for that is simply removing that entry by typing 'remove' then the number it's listed as while in the text editor (the /npc)

Example:

0: I'm npc!

It be 'remove' then '0'.

If the npc continues to say it's an npc another thing you could try is deleting and spawning a new one in, or you can just go to the config file, find where it says the npcs name and edit the text to say what you want. Save and reload the server (or plugin).

If none of those helped you then, you could also look though the /npc help to see if there's another command that refers to talking, if I remember correctly there's a speech one. Which is oh right /npc speak, but that is only if you want to talk as the npc. Which you could set up command blocks to detect a player and then speak the message if the other fixes don't help.

I know it's not a plugin bug itself as it's a pretty good feature to be left to bugs. I know on my test server, npcs would say they're default 'Hi I'm <npc>' but setting them to not talk or changing the text seems to fix it for me.

I hoped I helped! :)

**Comment by Zeuscp1** [comment]
Hello! thanks for all the effort trying to help me out!. You don't know how much i appreciate it!. I would like to talk with you in a less formal way, discord maybe? I think i could use some help from you! Thanks!

https://discord.gg/QVNpVy

**Comment by Midnight9746** [comment]
I locked myself out of my discord account several months ago (I blame my old phone for dying on me with my two step verification and passwords codes), and refused to make a new one, 

sooo.. What about Skype?
I'm registered as MidnightMoonLite on Skype. I be happy to help you in a more formal matter! :)

**Comment by Zeuscp1** [comment]
I already added you!

**Comment by mergu** [comment]
We recommend Denizen for scripting npcs, as it's vastly easier and has many more features than Citizen's built-in interactions. Chat with us over on https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
`I locked myself out of my discord account several months ago (I blame my old phone for dying on me with my two step verification and passwords codes), and refused to make a new one,` you messed up and accept fault for the issue, but then refuse to make a new account? 0.o
Skype is pretty terrible, it was only ever really used because there was no good alternative before Discord.

**Comment by Midnight9746** [comment]
> but then refuse to make a new account? 0.o

Eh, I don't have to make a new account if I don't want it. I want it attached to the same email, not have to remake an email. Besides I'm still hoping to one day get my old phone to turn on, it's just the battery that needs replacing.

**Comment by mcmonkey4eva** [comment]
I hope you'll be able to join us on Discord at some point!
