### ISSUE TITLE
Cat AI resetting

### ISSUE THREAD

**Issue by MusicScore** [CitizensDev/Citizens2#1385]
Spigot 1.12.2, Citizens 1498

When I set down an ocelot-type NPC and right click it enough, it starts running off and doing what an ocelot would normally do.

**Comment by Midnight9746** [comment]
Eh the same thing happens with a wolf, I make it sit down and it forgets it's tamed and loses its collar. But it still does what sentinel tells it to do...

I'm glad I didn't post about this situation too and I'm just adding on about the fact that it's wolfs too.

**Comment by mcmonkey4eva** [comment]
Can't replicate this at all... any more info on this?
