### ISSUE TITLE
Error with "event EntityDamageByEntityEvent" when using trait/plugin Sentinel

### ISSUE THREAD

**Issue by ggggoodhunter** [CitizensDev/Citizens2#1388]
In this issue:
- Description: I used Sentinel plugin with Citizens. I added the trait to the npc and set the target to that npc, for example /sentinel addtarget zombie. After that, when the npc process to attack the target i get this error. The error occurs only when the npc takes damage.
- Link to server log: https://www.pastiebin.com/5a6c78e8ea8a3
- Link to Citizens config: https://www.pastiebin.com/5a6c7c3c76ca1
- Minecraft & Citizens version: MC-craftbukkit-1.12.2 and Citizen 2.0.22

**Comment by mcmonkey4eva** [comment]
Update to latest Spigot (Don't know how or why you're running dev-pseudo-craftbukkit)
Update Sentinel, you're somehow running a 1.11 targeted beta version of Sentinel.
