### ISSUE TITLE
lookclose doesn't work

### ISSUE THREAD

**Issue by X00LA** [CitizensDev/Citizens2#1390]
In this issue, please include:
- whether this is a bug description or a feature request
BUG: When I save my citizens with lookclose: false all is fine, but when I reload or restart the lookclose variable changes back to true.

- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
There's nothing in the logs.

- Minecraft & Citizens version if relevant
Minecraft 1.12.2
This server is running CraftBukkit version git-Spigot-9b8bba4-bdcc7c7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Citizens v2.0.22-SNAPSHOT (build 1498)

**Comment by mcmonkey4eva** [comment]
Are you editing the saves file directly? ... If so, don't do that, use in-game commands ...

**Comment by X00LA** [comment]
No, I doesn't edit the saves file. I only use the commands from chat in-game.

**Comment by fullwall** [comment]
Fixed
