### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Gaspa123** [CitizensDev/Citizens2#1391]
when i write /npc create [whatever] then this happen 
---> java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet 
I've server Spigot 1.8.8-R0.1

**Comment by Gaspa123** [comment]
And citizens 2.0.14 (alpha 1 for MC 1.8.1)

**Comment by mcmonkey4eva** [comment]
... 1.8.1 and 1.8.8 are not the same thing.

**Comment by Gaspa123** [comment]
Yup I see but server is compatible with versions 1.8-1.8.9

**Comment by mcmonkey4eva** [comment]
... Nope.

**Comment by Gaspa123** [comment]
Ok so do you have plugin for my type of server?

**Comment by mcmonkey4eva** [comment]
Strongly advise you update your server to latest.

Old versions are at https://wiki.citizensnpcs.co/Versions but are unsupported.
