### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Roy416** [CitizensDev/Citizens2#1395]
https://pastebin.com/rdK7Y3gZ

I'm also using a plugin called CitizensCMD

**Comment by mcmonkey4eva** [comment]
It looks like your saves file or the data attempting to be saved is corrupted heavily.

**Comment by Roy416** [comment]
hmhmmh

**Comment by Roy416** [comment]
I thought I fixed it since in the save.yml I had, it had old npcs from worlds that didnt exist, and had a bunch of spaces in the beginning of the yml. but the errors still continue. 
saves.yml: https://pastebin.com/GKxnqG8T

**Comment by Roy416** [comment]
Ill just create the npcs again
