### ISSUE TITLE
Citizens Blacksmith armor bug:

### ISSUE THREAD

**Issue by Serpano** [CitizensDev/Citizens2#1396]
Hello dear people,
Anyone of you Should surely know Citizens?
There is a tool (addon) called BlackSmith.

Source: https://wiki.citizensnpcs.co/Blacksmith

The following problem for a player:
He can weapons and repair tools but if he wants to fix a broken Iron Leggings there by right click this is tightened immediately.
And the NPC reports this is not the part is what you want to get fixed.
In order to do that, the armor part has to stay in the hand now it does not
If you make a right click it will be put on.

Sry for my bad english i hope you understand my problem i come from germany 

Minecraft: 1.11.2
Citizens Version: Citizens v2.0.22-SNAPSHOT (build 1481)

**Comment by mcmonkey4eva** [comment]
Of course we know Citizens... this is the Citizens issue page.

Blacksmith is a separately maintained plugin and is the task of the Blacksmith maintainer to deal with, not anyone from the Citizens team.
