### ISSUE TITLE
Problems with ocelots

### ISSUE THREAD

**Issue by xMrFrag** [CitizensDev/Citizens2#1397]
I state that I am an Italian mother tongue and I apologize for any grammatical errors. My problem, as mentioned, concerns ocelot. Do the procedure indicated to create the citizen, change the type in ocelot, I do "sit", and if I click the right button starts to wander around the map. How can I solve?

MC Version: 1.12-R0.1-Snapshot
Additional plugins: CitizensCMD 1.2.0
Plugin version: 2.0.22 compilation # 1500

I await a possible response,
regards.

**Comment by fullwall** [comment]
Does the latest build help?
