### ISSUE TITLE
[Bug] Invisible traits

### ISSUE THREAD

**Issue by Wani4ka** [CitizensDev/Citizens2#1398]
Server version: 1.11.R1
Citizens version: 2.0.22-SNAPSHOT (build 1487)

I use this code to create an NPC, assign it to ExampleTrait and spawn it:
`NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.IRON_GOLEM, "display name");`
`ExampleTrait et = new ExampleTrait("display name");`
`et.linkToNPC(npc);`
`npc.spawn(((Player) sender).getLocation());`
NPC usually spawns successfully, but sometimes it becomes invisible. I mean, creation is complete, but I can't see my created NPC. It also can be happenned after server reload (not restart). When I try to spawn another NPC using /npc create, it spawns successfully. Is this the problem of plugin or mine?

**Comment by fullwall** [comment]
That is not the correct way to link a trait to an NPC. You should register the class in the TraitFactory and call npc.addTrait(class) to properly add the trait.
