### ISSUE TITLE
Player NPC invisible

### ISSUE THREAD

**Issue by M450NC** [CitizensDev/Citizens2#1400]
In 1.12.2, I'm having an issue where any player NPCs (NPC with a real players name) are spawning invisible. Any non player NPCS are working as they should be. If I spawn a player npc and while invisible, change its name to a non player NPC, it spawns. 

Causing my server a lot of issues.

**Comment by M450NC** [comment]
Any ideas?

**Comment by mcmonkey4eva** [comment]
Might be a plugin conflict

**Comment by M450NC** [comment]
TAB was the plugin causing the issue.
