### ISSUE TITLE
NPCs Reset after Reload Or Restart

### ISSUE THREAD

**Issue by VipFTW** [CitizensDev/Citizens2#1401]
Ok, so I set up some NPCs for my server's crates using CrateReloaded and Citizens. BUT every time I do /reload or /restart the NPCs break and I have to go and add their commands again. This is really annoying because while players play I have to constantly be on to fix them (we have an auto restarter). I need an answer ASAP thanks.

Note:
No errors in console.
Server version Spigot 1.8.8

**Comment by mcmonkey4eva** [comment]
Update your server to latest.
Never use `/reload`.

**Comment by VipFTW** [comment]
The latest CrateReloaded version?

**Comment by VipFTW** [comment]
I need my server to be version 1.8.8

**Comment by mibby** [comment]
Citizens don't seem to save when you create them or delete them. You need to make sure you type ```/citizens save``` before you do any type of shutdown / restart after you have made changes to npcs.

**Comment by Owizardo** [comment]
I have the same issue, I remove about 40 NPCs and did /citizens save. Doing /NPC list, the NPC do remove correctly. I then do a server reload and all the NPCs I remove come back. On top of that, I tried to wipe everything by removing the plugin folder and restart. All the NPC come back ... whats the proper way of wiping?

**Comment by mcmonkey4eva** [comment]
@Owizardo you have to shut down the server, then delete files, then start it up. Deleting files while the server is running doesn't always work much.
