### ISSUE TITLE
NPC Dialogue speed.

### ISSUE THREAD

**Issue by DiggumFrog** [CitizensDev/Citizens2#1402]
Using Citizens 2.0.22

Might be a feature request depending on your answer to the question, which is...

...Is there any way to change the NPC chat speed? The time between messages seems a little slow and it's apparently too much to ask that people read. If the message speed were faster, it may encourage more people to engage the dialog, but after pouring through the commands wiki, help dialogs, and config I couldn't find a way to do it. If it does not exist, is it a possible add on? 

Thanks for your time!

**Comment by mergu** [comment]
Denizen was made for scripting NPCs! You can control every aspect of an npc with it.
Visit us at https://discord.gg/Q6pZGSR

**Comment by fullwall** [comment]
You can set custom chat delays per NPC and in the config.yml - if you want something more advanced use denizen.
