### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by LilSly** [CitizensDev/Citizens2#1406]
In this issue, please include:
Showing up red in plugin list
[21:57:23] [Server thread/ERROR]: [Citizens] v2.0.22-SNAPSHOT (build 1502) is not compatible with Minecraft v1_8_R1 - try upgrading or downgrading Citizens. Disabling
Using 1.8 spigot with via version to 1.12.x

**Comment by mergu** [comment]
Update your server

**Comment by LilSly** [comment]
All my other plugins are working

**Comment by mergu** [comment]
Your server is extremely outdated

**Comment by LilSly** [comment]
If i update to 1.12.2 via version will not allow 1.8 users tho

**Comment by mergu** [comment]
1.8 is over 2 years old at this point. Your players can very easily run 1.12.2 through the drop-down option on the Minecraft launcher.

Join us in discord for further discussion: https://discord.gg/Q6pZGSR

**Comment by LilSly** [comment]
My Minecraft users rather use 1.8.9 and such for pvp clients and forge mods!

**Comment by MrDienns** [comment]
@mergu actually, it's over 4 years old.
@LilSly Try updating to 1.12.2 and install ProtocolSupport in addition to some old mechanics PVP plugins. If you're gonna use 4 year old software (1.8), you're simply bound to run into issues. You really should not be using software like that.

**Comment by mergu** [comment]
@MrDienns Oh boy I'm getting old.
He visited our discord, and it seems his stubbornness in updating stems from appealing to hackers. We had him install an old build.

Should be closed
