### ISSUE TITLE
NPC teleporting to randomly places sometime.

### ISSUE THREAD

**Issue by AccioAce** [CitizensDev/Citizens2#1407]
Hello Author, 
I'm not sure If this is a bug but are NPC suppose to be able to teleport out of there own places where we set them. It has been happening it to me for some reason. Basically, NPC left there own place and random teleport somewhere for some reason sometimes.

MC lastest version

**Comment by mcmonkey4eva** [comment]
Unrelated plugins can often mistakenly teleport NPCs.
EG if the plugin forbids certain players access to an area, they will often also forbid NPCs.
