### ISSUE TITLE
NPC stops moving in its path - Help

### ISSUE THREAD

**Issue by Twi5TeD** [CitizensDev/Citizens2#1409]
Hello, im using the CitizensAPI to develop a plugin. I have noticed that if a player moves far enough from the NPC it stops moving on its Path. Is there anyway to allow NPC to still move without being near them?
as i want NPC to be able to move even when im not in the same world as them. i need to be able to do this as i want the NPC to be able to move and mine in a path but if a player is not near enough then the NPC will just stand still and do nothing.
im not sure if this would need to be added or if its already implemented so its worth a try at asking someone here thanks

**Comment by XXTen** [comment]
Also having this issue, really would appreciate any help.

**Comment by fullwall** [comment]
Can you post your config.yml?

**Comment by Twi5TeD** [comment]
[https://hastebin.com/tokerofowi.swift](url)
im using the citizens API not sure why config would be needed? but here it is anyway thanks for the reply

**Comment by fullwall** [comment]
I wonder if the chunk is unloading which is why I asked for your config. Do you have another plugin to keep the chunks loaded?

**Comment by Twi5TeD** [comment]
i even manually kept the chunk loaded by cancelling the ChunkUnloadEvent
the chunk is 100% loaded

**Comment by fullwall** [comment]
How far away do you get before it stops? Can you try setting the always-keep-loaded setting to true?

**Comment by Twi5TeD** [comment]
i have it set to true and approx 200 blocks away

**Comment by fullwall** [comment]
I am not able to reproduce this. Can you please paste your code?
