### ISSUE TITLE
API: No SkinnableEntity when using maven.

### ISSUE THREAD

**Issue by Demeng7215** [CitizensDev/Citizens2#1411]
I am currently using CitizensAPI to spawn NPCs with my plugin. However, I am unable to set the NPC's skin due to the fact that there is no SkinnableEntity class. This is what I put in <dependencies>:
`
            <dependency>
                <groupId>net.citizensnpcs</groupId>
                <artifactId>citizensapi</artifactId>
                <version>2.0.22-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
`
For the repo I used something like repo.citizensnpcs.co

I am pretty sure this is a problem on your side since my friend stated that he can find the SkinnableEntity class if he adds the Citizens.jar file in his dependencies directly. I am using Maven.
http://prntscr.com/ifm3rl

**Comment by alvarocduquia** [comment]
Use this:


        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizensapi</artifactId>
            <version>2.0.16-SNAPSHOT</version>
            <type>jar</type>
            <scope>compile</scope>
        </dependency>
        
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizens</artifactId>
            <version>2.0.16-SNAPSHOT</version>
            <type>jar</type>
            <scope>compile</scope>
        </dependency>

**Comment by mcmonkey4eva** [comment]
Don't use that either.

Use what you're already using but remove `api` from the artifactId.

You want just Citizens itself, not the API.

**Comment by Demeng7215** [comment]
I removed 'api' at the end of the artifact ID and it worked, issue closed.
