### ISSUE TITLE
[API] Setting NPC Armor

### ISSUE THREAD

**Issue by Demeng7215** [CitizensDev/Citizens2#1413]
I've been trying to set the NPC's armor through the API for over 2 hours now, and no luck. This is my code: 
https://pastebin.com/kVVVuf9k

This **should** be working, but it's not. The funny thing is that the item gets set properly to the hand, but the armor does not work. Here is a screenshot:
http://prntscr.com/ig1pug
This is probably because armor is not considered to be in the entity's inventory.

Citizens should have a method for setting NPC armor.
I am using the latest version of Citizens, 2.0.22 on Minecraft 1.12.2.

**Comment by mcmonkey4eva** [comment]
Might be related to skin control. An NPC is forcibly removed from the world and regenerated to make the skin update occur properly.

**Comment by Demeng7215** [comment]
@mcmonkey4eva Thanks for the input, I am going to leave this open to see if anyone knows a fix for this/has another response.

**Comment by mcmonkey4eva** [comment]
Did you... even test compensating for that problem?

**Comment by fullwall** [comment]
Try setting the Equipment trait as well.
