### ISSUE TITLE
[Bug] NPC Nametag Visibility

### ISSUE THREAD

**Issue by MrSwalbert** [CitizensDev/Citizens2#1414]
When you type "/npc name" the nametag is meant to disappear. It doesn't.

**Comment by fullwall** [comment]
Can you please post your config?

**Comment by MrSwalbert** [comment]
https://pastebin.com/c0FjiF0r

**Comment by MrSwalbert** [comment]
I am also using NameTagEdit. Could this be possibly interfering?

**Comment by CoffeeAC** [comment]
Im having the same problem and im using ColouredTags (effects tag above you & tablist) im thinking it is interfering

**Comment by MrSwalbert** [comment]
NTE is definitely hooking in as the prefix above the NPC is set to the NTE prefix. The problem I have is that when people log out, the NTE prefix disappears and it resets to a default nametag.

**Comment by JohOply** [comment]
I have the problem too
I use build 1504

/npc name seems work correctly with non-player type, and if the NPC name is unique

**Comment by mcmonkey4eva** [comment]
Might be fixed in newest version?
Were some recent related commits.
If it isn't, please reply below and I'll re-open this.

**Comment by UnioDex** [comment]
It didn't fix. I was using NameTagEdit as well. I removed NameTagEdit but nametags are still showing. Server version: 1.8
@mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
@UnioDex Update your server. There's no valid reason to run 1.8 on a server... use 1.12.2 latest, and add in backport plugins (ViaBackwards for supporting old clients, there are combat backdaters if you want that to be old style as well, etc.)

**Comment by UnioDex** [comment]
Well no time to update right now. I will update it in summer after my exams are finished. But since you add 1.8.8 support i thought you will give support for 1.8.8.
