### ISSUE TITLE
Massive Perfomance Issue

### ISSUE THREAD

**Issue by Fortepsai** [CitizensDev/Citizens2#1415]
After days of testing i have finaly found what is the source of this issue .
I had citizens on my server and after i have instaled Spartan AntiCheat every 2 hours i got massive usage of RAM and cpu so TPS dropped to 6 . 
Never had such an issue before.  Even when i have citizens alone its consuming so much of CPU and RAM anyway without Spartan on the server .
We are currently havig abour 150 npc and most of them are static. Roughly 30 sentry .

**Comment by fullwall** [comment]
Can you try using something like warmroast to make it easier for us to debug this issue?

**Comment by Fortepsai** [comment]
Ok i will do thatm but anyway we had to delete sentinels all of them and now its ok server is not crushing but citizens with 80 npc is really consuming our ram .

**Comment by mcmonkey4eva** [comment]
Closing until data provided, please reply when you have data and we'll reopen.
