### ISSUE TITLE
Citizens old npc data - B1504

### ISSUE THREAD

**Issue by AmazedMender16** [CitizensDev/Citizens2#1416]
Hello,

Im running citizens B1504 with leaderheads and featherboard, Leaderheads keeps updating the NPC's.. the old data is not being deleted by citizens2 which makes featherboard having over 160k of lines with old data timing out the server.

It basically keeps creating new Teams and not deleting the old data... Hope there is a fix for this available..

Server version: 1.12.2 latest version

**Comment by mcmonkey4eva** [comment]
(Fixed on Discord: disable `player-scoreboard-teams` in config)
