### ISSUE TITLE
Increasing the pathfinder range for Navigator

### ISSUE THREAD

**Issue by CompilableMC** [CitizensDev/Citizens2#1417]
Hey there;

I'm currently working on a drop out based system, is there any way i could really increase the pathfinder range in the config without the server actually crashing? I'm trying to develop something where an Enderdragon goes to a specified point, yet it either teleports or crashes (if the pathfinder range is increased) if it's far away; or goes to the location if it's in the range.

**Comment by fullwall** [comment]
What are you increasing it to? Is it running out of memory?

**Comment by CompilableMC** [comment]
I'd like to have it to 1000, probably 5000 even. What's the recommended memory for that?

**Comment by fullwall** [comment]
Absolute worst case is 1000^3 nodes, although you might expect closer to O(n) for a good heuristic. Is it possible to split your path up? Otherwise, I could implement a pathfinder which uses less memory.

**Comment by CompilableMC** [comment]
Anyway i could get your discord so i could discuss this in private?

**Comment by fullwall** [comment]
https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
You definitely don't want such a massive pathfinder range at all. For an enderdragon you might just have sent down a straight line with no pathfinding at all.
