### ISSUE TITLE
NPC skins not loading

### ISSUE THREAD

**Issue by CathrineEG** [CitizensDev/Citizens2#1418]
The skins of the NPC often do not work until the client goes in and out of the game; which wouldn't be a big issue if it was a rare thing - but it's very frequent

**Comment by sigmaroot** [comment]
Mojang changed the web path to all skins, thats the cause of this problem.

**Comment by sigmaroot** [comment]
But I'm having exact the same issue. No skin is loading anymore. Same was with dynmap. This all started a few weeks ago. Dynmap fixed it with a new url. Maybe Citizens has to do the same.

**Comment by mcmonkey4eva** [comment]
To my knowledge `skins.minecraft.net` was shut down by Mojang. All other services remain online.

Citizens does not use that service. Citizens actually uses the exact same skin lookup calls as is used by Minecraft itself - we use values gathered from NMS.

**Comment by sigmaroot** [comment]
Okay, but I'm not the only one experiancing this issue. #1404 is related and exactly the same.

We do use correct playernames they have a skin and are not limited by mojang requesting.

Old NPCs do work properly. Only when creating new ones, they show only a Steve skin.

Mojang also made some changes, that a skin cannot be received via playername but via UUID (not sure, read that somewhere else).

I'm using PaperSpigot, others (#1404) use Spigot. Dunno if that has to do something with that.

**Comment by Midnight9746** [comment]
Meanwhile, I came here too because of the same thing... and I assumed that you were using the skin.minecraft stuff....

Anyways, I hope to see it working again soon. I got a player who wants a Captain America guard, and that's kinda hard when it's just an Alex following them... lol

**Comment by mcmonkey4eva** [comment]
Skins seem to work on current version, but Mojang's servers have had a lot of errors lately, likely just that affecting you...

**Comment by Midnight9746** [comment]
@mcmonkey4eva any ideas on how to make the skins work?

**Comment by mcmonkey4eva** [comment]
Make sure your server and all plugins are up-to-date.

Make sure you're running a functionally connected server.

Make sure you're not running on a shared server (the IP your server has is exclusively used by your server.)

Test at various times of day to account for Mojang servers being very dumb recently.

**Comment by Midnight9746** [comment]
@mcmonkey4eva sometimes it works but it's mostly not.... So okay thanks... I do hope the servers stop being stupid, and everything is updated and our ip is only for us.

**Comment by Midnight9746** [comment]
@mcmonkey4eva I can confirm that it works on my computer, (with only vault and citizens) but it will not work when the host runs it. (Fluctis) It used to do it, and now it's not. (I even ran it with just vault and citizens).

I have the same version for both. Could the version of java be the issue?
