### ISSUE TITLE
Server crash BUG ISSUE

### ISSUE THREAD

**Issue by xxafthxx** [CitizensDev/Citizens2#1421]
Ok so this happened to me the other day. I'm running an rpg server with the Quests plugin, SKillAPI, and citizens. 
The issue is that whenever I left click an NPC or shoot it with a Skill from Skill API the server crashes. I can upload a full plugin config. But for now here are the server logs as well as a config file for the citizens.. The server was running smoothly.. then I taught it  would be a good Idea to archive the server. Since I was in-game while it was archiving the archiver game me a error so I stopped the archiving.

Please help!
P.S
Thank you.
[2018-02-21-12.txt](https://github.com/CitizensDev/Citizens2/files/1743880/2018-02-21-12.txt)

**Comment by mcmonkey4eva** [comment]
Just so you know, `AutoRestart` generated several errors, `sTablist.jar` failed to even load, you have a variety of outdated and misconfigured plugins in there...
The crash happened from:
`com.alessiodp.parties.players.PlayerManager.getPlayer(PlayerManager.java:75)`

My first guess here is that the "parties" plugin saw an NPC involved in a damage event and broke while trying to interpret the NPC to be a player.
