### ISSUE TITLE
NPC Shows wrong name, if on other world

### ISSUE THREAD

**Issue by Regnak85** [CitizensDev/Citizens2#1422]
Every last five citizens Dev Builds (Maybe even further)
Spigot 1.12.2

Example: Created Citizens on World A

Names, 1, 2, 3, 4, 5, 6

Created Citizens on World B.

Name: 10

Everythings fine. But, changing world, coming back to World B, it "shows" Name 5 for the Citizens Number 10.

It is the same Citizen as it should be, even if i do npc select, he says "Selected NPC 10"
But it shows the wrong name

If i do "citizens reload, he loads the correct name again, but after world change -> Name wrong again, its again citizens name 5

**Comment by mcmonkey4eva** [comment]
Is it perhaps a very long name (one that would require Scoreboard tricks to display)?
Where long just means more than 16 characters.

**Comment by Regnak85** [comment]
yeah, it is a "Long" Name.

NPC on World: Mauerlaeufer John

NPC on World 2: Hexenjaeger Spion

Now, NPC on World 2 shows everytime "Mauerlaeufer John"

**Comment by Midnight9746** [comment]
Did you by chance copy the first npc into the other world?

That happens to me, although I got an npc named "Dragon" and it sometimes takes a different name, but normally tries to combine it's name with another npc by the same name, but it's an actual dragon... by that it just goes: "Dragonon", I ended up toggling the nameplate, since the npc's chat works just fine.

**Comment by mcmonkey4eva** [comment]
This might be an issue of name trimming logic being a bit iffy.
`Hexenjaeger Spion` is 17 characters... which I believe under the current setup, will make its name `n` and its prefix `Hexenjaeger Spio`, which is very sub-optimal (both NPCs take name `n`, which means they share only a single scoreboard entry. Yikes!)

**Comment by mcmonkey4eva** [comment]
Added a fix for that in #1525
