### ISSUE TITLE
[API] SkinnableEntity is not documented.

### ISSUE THREAD

**Issue by Demeng7215** [CitizensDev/Citizens2#1423]
I can't find the usage of SkinnableEntity#setSkin(String) method on the Javadocs due to the fact that SkinnableEntity is part of Citizens, not CitizensAPI. Can someone let me know how to use SkinnableEntity#setSkin? I am guessing it should be setSkin(Player) or setSkin(String playername), but it may be a texture value like `eyJ0aW1lc3RhbXAiOjE1MTkzOTA3MTQ3NDcsInByb2ZpbGVJZCI6ImNhMTlhZjA0YTE1NjQ4MmVhMzVkM2Y1ZjQzNDk3NWI1IiwicHJvZmlsZU5hbWUiOiJJdHpEZW1lbmc3MjE1Iiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS84NDljNzliOGJlZjY4ZTk5NTk0OWVjYWIyMTAzMWU3ZjJjN2EwYjllZmY4YjZhMzg2MzYyMTRiNDRkYTYifX19`.
Maybe document this stuff as well? Or can somebody just tell me the usage of this?

**Comment by Demeng7215** [comment]
![screenshot_1](https://user-images.githubusercontent.com/27823562/36595287-99d8d334-186f-11e8-9290-47bf66fff689.png)
I am almost 100% sure it is the player name, but I am just confirming.

**Comment by mcmonkey4eva** [comment]
Docs can be seen from the source data: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/skin/SkinnableEntity.java#L46-L60

You can see there are separate methods for setting by player name or full available skin data set
