### ISSUE TITLE
NPC rapid skin checking

### ISSUE THREAD

**Issue by griffenx** [CitizensDev/Citizens2#143]
Using the latest dev build of citizens on spigot 1.8, if you assign a skin to an npc of a nonexistent account ("/npc skin asdf" for example), Citizens will continually try to update the skin, which effectively keeps respawning the NPC. What this used to do in 1.7 was it would check once, then just use the default skin if no account was found. This made it a helpful method for setting NPC's to the default skin.
This issue does not occur when you set the initial name of an NPC to a nonexistent account with the /npc create command (i.e. "/npc create asdf").

**Comment by noorkoteb** [comment]
cant u limit it by letting it save the skin file and replacing them everyday

http://www.spigotmc.org/resources/bukkitnpcs.1880/

**Comment by stopbox** [comment]
Sorry to poke in but why is my plugin mentioned here?

**Comment by noorkoteb** [comment]
because it says in features,

+ Bypass Mojang's skin loading limit per minute by saving the skin info to file.
+ NPC Saving/Loading Using UUID file names so no file conflicts.

this is the issue we are having the skin disappears or keeps refreshing
