### ISSUE TITLE
[Request] Stop walk and continue by timer or tick (time in game)

### ISSUE THREAD

**Issue by phoomin2012** [CitizensDev/Citizens2#1433]
Improve waypoint system such as
- Stop at waypoint and continue by event
Event to goto next waypoint such as
- Timer (5 seconds or 1 minute)
- Time in game (06:00 am or 0 tick)

**Comment by mcmonkey4eva** [comment]
As your needs for NPC handling complexity increases, it will become increasingly useful to enhance your Citizens setup through Denizen - https://www.spigotmc.org/resources/denizen.21039/
