### ISSUE TITLE
Bukkit Plugin Page is outdated

### ISSUE THREAD

**Issue by ZainlessBrombie** [CitizensDev/Citizens2#1434]
Minor issue:
1.9 compatibility is advertised to be available with the latest dev build. This may confuse people who want to run a server on e.g. 1.9 ;)
Also the "current version" is outdated
Cheers :)

**Comment by mcmonkey4eva** [comment]
I mean if you were reading the DBO plugin page you would click the big shiny link at the top that redirects you to the current page (on Spigot)...

**Comment by ZainlessBrombie** [comment]
Whouspie.. My fried mind thought that was a big caption for the text below ;)
