### ISSUE TITLE
[Citizens] v2.0.22-SNAPSHOT (build 1493) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.

### ISSUE THREAD

**Issue by nobodypromi** [CitizensDev/Citizens2#1435]
Hey, i paid 10$ for the Citizens plugin for MC_Version 1.9.4.
The problem is, that it isn't working. 

LOG:
[15:46:23 ERROR]: [Citizens] v2.0.22-SNAPSHOT (build 1493) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.

Everybody here would just say: Hey, just down or upgrade your server-version but i paid the mponey for the version, that i can use it on 1.9.4. If nobody can help me, is there a possibility to get back my money?

**Comment by mcmonkey4eva** [comment]
I'm not sure why you thought paying for the donation version on Spigot would get you an outdated build.

You can find older builds on https://wiki.citizensnpcs.co/Versions but you really really should just update your server.
