### ISSUE TITLE
Is there a way to refund?

### ISSUE THREAD

**Issue by nobodypromi** [CitizensDev/Citizens2#1437]
Hey,
i paid 10$ for a citizens plugin on spigot.
I didn't knew that it is a donation version.
I thought i have to pay it for the special version of the plugin for 1.9.4.
Is there a way to get this money back?
It was part of a donation of a player and i need the money to extend my Server. :(

**Comment by fullwall** [comment]
What's your email?

**Comment by nobodypromi** [comment]
My e-mail is: fantusgrafix.info@gmail.com

**Comment by nobodypromi** [comment]
Thank you! You are amazing! :) 👍
