### ISSUE TITLE
Cannot spawn npcs

### ISSUE THREAD

**Issue by gege12222** [CitizensDev/Citizens2#1438]
when i write: /npc create teszt --player
i get this error:
java.lang.noclassdeffounderror: net/minecraft/server/v1_8_R1/packet
- 1.8 bukkit server, 2.0.14 (alpha 1 for MC 1.8.1)

**Comment by mergu** [comment]
Update your server to 1.12.2

**Comment by mcmonkey4eva** [comment]
As well make sure to run the latest Citizens jar file.

**Comment by mcmonkey4eva** [comment]
About 3.7 percent of all minecraft servers run 1.8(flat). Most of those are servers that were abandoned after the initial 1.8 update but not shut down.
We are not going to try to provide support for such an old version.

Also the error you posted looks a lot like you're not even running that version.

You clearly do not know what the different versions are, and as such should not be choosing some random ancient unsupported version as your goal.

Run latest versions.
