### ISSUE TITLE
Villager type NPCs are invisible on creation

### ISSUE THREAD

**Issue by superjack010** [CitizensDev/Citizens2#1439]
I am having an issue with villager type NPCs being invisible on their creation. I am able to hear the villager making it's sounds, although I cannot see the NPC. All other types of NPCs spawn in just fine. Although my server uses Villagers as the main type of NPC. 

Server version: PaperSpigot ver 1342 (MC 1.12.2)
Citizens version: 2.0.22-SNAPSHOT  (build 1517)

I am using viarewind/viabackwards although I have tested without those plugins. I am also running dtltraders latest version. I have also tested without dtlTraders. I've tested in different worlds along with removing data files from essentials. I've cleared my Citizens folder and regenerated the folder.

**Comment by superjack010** [comment]
Update: All mobs are invisible. Not just villager. The only mob that works is the player.

**Comment by fullwall** [comment]
What plugins are you using?

**Comment by superjack010** [comment]
Quite a few: [Plugin list](https://i.imgur.com/2em6j9X.png)

**Comment by mcmonkey4eva** [comment]
Delete PlugMan for sure, also look for other plugins that might interfere with entity things and test the server with them removed.

**Comment by superjack010** [comment]
I've removed all the recent plugins we've added such as, armor stand editors, furniture plugins and plugman, although the error still persists. I am however getting this message on startup. Could this be a factor?

`Citizens] Enabling Citizens v2.0.22-SNAPSHOT (build 1517)
[Citizens] Could not fetch entity id mapping fields: Can not set static final net.minecraft.server.v1_12_R1.RegistryMaterials field net.minecraft.server.v1_12_R1.EntityTypes.b to net.citizensnpcs.nms.v1_12_R1.util.CustomEntityRegistry.`

**Comment by mcmonkey4eva** [comment]
Either you're not running an up-to-date Spigot server, or you have another plugin that modified the entity registry in a way not compatible with Citizens.

**Comment by superjack010** [comment]
Issue resolved. The plugin that was causing the error was a plugin called GadgetMenu.

**Comment by superjack010** [comment]
Gadget menu was the issue. We have solved this!
