### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by Cartierzimm** [CitizensDev/Citizens2#1442]
The skins will not load

**Comment by mcmonkey4eva** [comment]
Update your server.
Update your plugins.
Run in online mode.
Run on a dedicated machine with its own IP (not a generic minecraft hoster).
Don't request too many skin loads at once (Mojang will block you).
Make sure Mojang's servers are actually online (the Mojang skin server goes down a lot).

All else fails: provide some details!
