### ISSUE TITLE
Citizens NPCs despawn after time

### ISSUE THREAD

**Issue by nobodypromi** [CitizensDev/Citizens2#1446]
Hey,
I know, you are informed about this issue and i searched a long time
for Informations. I use
Citizens Version: Citizens (2.0.17-SNAPSHOT (build 1316)
on Spigot: v1.9_1 (1.9)
The rpboelm is like in title perfectly explained:
Npcs just disapear after time.
Plugins, which could remove them:
- ClearLagg
- MythicMobs

Because they remove mobs from the server.
The Npcs often just disapear, when the chunk or world is unloaded
and then they doesnt come back except i reload witch "/citizens reload".
Waht to do? Is there a fixxed version?

**Comment by mcmonkey4eva** [comment]
You're running an incredibly outdated server and outdated plugins.
Update.

Also, always test with risky side plugins removed. "ClearLagg" is a plugin which just despawns entities all the time. That's very likely to be related.
