### ISSUE TITLE
Feature Request - Duel Wielding

### ISSUE THREAD

**Issue by Midnight9746** [CitizensDev/Citizens2#1447]
I'm not sure if it had been requested.. (I've actually looked just to make sure, but don't know where else besides here to check). But anyways, I was wondering if it was possible to add 1.9's duel wielding to NPCs.

I want NPCs to hold two items sometimes, (not really use both items, I mean if they could shield block, that be cool, but not expected as it might not be that easy.), such as a sword and a shield, or a weapon and a torch. Something to create fighters, miners, and other type of NPCs with.

**Comment by mcmonkey4eva** [comment]
`/npc equip`
hold item
`offhand`

Note that 'offhand' is a chat message, not a command.
It will be parsed and equip the NPC correctly.

Regarding auto blocking with a shield, check: https://github.com/mcmonkey4eva/Sentinel/issues/70

**Comment by Midnight9746** [comment]
@mcmonkey4eva OH, well thanks! I had no idea that it was like that. I'm so happy lol
