### ISSUE TITLE
/npc glowing --color does not work

### ISSUE THREAD

**Issue by jiongjionger** [CitizensDev/Citizens2#1448]
I'm using the latest build(build 1524) with paper 1.12.2 and I've ensured that the data is saved successfully. I tried it many times and I tried to restart the server and the client, but nothing worked.

Glowing has always been black and cannot be changed.

http://ww2.sinaimg.cn/large/0060lm7Tly1fpkrfb2o35j30vf0oc4c9.jpg

**Comment by mcmonkey4eva** [comment]
Have you deleted + recreated the NPC?
Have you checked for interference from other plugins (particularly as relating to scoreboard logic)?
Have you tested with an ASCII name on the NPC? (As in, only English letters, no unicode in case there's an encoding issue.)

**Comment by jiongjionger** [comment]
Problems caused by FeatherBoard:(
