### ISSUE TITLE
NPCs bugging my tab

### ISSUE THREAD

**Issue by fred112f** [CitizensDev/Citizens2#1451]
Description: Whenever I create an npc of a player, my tab plugin begins to bug out and expand like more players are on the server. I disabled showing npcs on the tab, but it still is buggy. I am also not able to disable prefix etc. on npcs of a person.

Version: 1.12.2, latest version of citizens.

**Comment by mcmonkey4eva** [comment]
Issue is with the tablist modifying plugin.
Citizens needs to transmit tablist-like data to players to allow NPCs (player type) to display at all for clients.
Also prefix/suffix/color/etc. are scoreboard effects.
