### ISSUE TITLE
Command "/npc wolf -[a|s|t]" does not show any messages in chat

### ISSUE THREAD

**Issue by Qveshn** [CitizensDev/Citizens2#1453]
citizens 2.0.22 build #1524
Command /npc wolf -[a|s|t] now turn angry|sitting|tamed on/off. It's good! But no messages in chat with new status (new properties values)

**Comment by mcmonkey4eva** [comment]
A lot of commands inexplicably lack output in a lot of strange situations. We're trying to fix this when we notice ones that are wrong.

Do bear in mind you can type `/npc help wolf` or change wolf to any other command to see its usage info.

**Comment by Qveshn** [comment]
I also found one more bug here: 
command /npc wolf -i 
does not work

**Comment by mcmonkey4eva** [comment]
No output at all with `-i`?

**Comment by Qveshn** [comment]
command /npc wolf -i
Output:
>> Unknown flag: i
>> /npc wolf (-s(itting) a(ngry) t(amed) i(nfo)) --collar [hex rgb color|name]

**Comment by mcmonkey4eva** [comment]
Er, does your message above saying the command works and is good mean that https://github.com/CitizensDev/Citizens2/issues/1452 is invalid?

**Comment by mcmonkey4eva** [comment]
Submitted a non-critical patch for review at https://github.com/CitizensDev/Citizens2/pull/1457 - issue will be fixed when our lead developer confirms the patch.

**Comment by Qveshn** [comment]
no,no,no...
Command "/npc wolf -[a|s|t]" works perfectly (instead -a #1452), but no messages about what actions were done. It works quietly.
I thought (as it was in old versions) that there should be output after this command with new values for flags angry/sitting/tames.
If "-i" now works, then outputs after -[a|s|t] are optional and you can consider that this is trivial "bug" or invalid.
Thanks

**Comment by mcmonkey4eva** [comment]
This was fixed.
