### ISSUE TITLE
Command "/npc pose -a" does not move head vertically. Only horizontally.

### ISSUE THREAD

**Issue by Qveshn** [CitizensDev/Citizens2#1454]
Spigot 1.12.2
citizens 2.0.22 build #1524
Command "/npc pose -a" does not move head vertically. Only horizontally.
No errors in console.
I need to edit file saves.yml to turn his head vertically.

**Comment by mcmonkey4eva** [comment]
Is it specifically the pose command or do other rotation methods also fail to adjust pitch properly?

**Comment by Qveshn** [comment]
"/npc create steve" **does not** turn head vertically
"/npc create wolf --type wolf" **turn** head vertically
"/npc pose -a" does not move head vertically for any npc type

I don't know other commands to rotate head =(

**Comment by mcmonkey4eva** [comment]
`/npc lookclose` will rotate the NPC to face the nearest player, and is my usual route for angling NPCs. I just enable it, fly around til I like the angle, then turn it back off.

**Comment by Qveshn** [comment]
When I enable head rotate with command "/npc lookclose", then npc rotates his head to me.
But when I disable rotate (again this command) then he turn his head vertically to pitch: '0'.
I can set pitch value only manually in file saves.yml.
I've just noticed, that command **/npc tphere** also resets head vertical orientation to pitch: '0'.

**Comment by Qveshn** [comment]
Also I've noticed, that command "/npc tphere" resets his head to pitch=0 only if my "yaw" != his "yaw"

**Comment by Qveshn** [comment]
Just tested:
Command "/npc pose -a" also resets his pitch to 0 as command "/npc tphere" does.
It resets pitch to 0  if my "yaw" != his "yaw"

**Comment by mcmonkey4eva** [comment]
Pitch in general is broken at last check.
Redirect discussion of that to #1283
