### ISSUE TITLE
Shulker Problems- causing many other problems.

### ISSUE THREAD

**Issue by AaronStrange3** [CitizensDev/Citizens2#1458]
I was just adding buttons to a GUI, when I finished I made an alias for the GUI to open.  I restarted my server, and when I got back on all of my NPC's had despawned.  "Weird" I thought.  So I /citizens reload'ed and they all popped right back up.  I logged off, and then logged back on, and they were gone again.  Confused I looked into console and saw this:

25.03 01:39:00 [Server] INFO Exception while updating 191: null.
25.03 01:39:00 [Server] WARN java.lang.NullPointerException
25.03 01:39:00 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.setShulkerColor(NMSImpl.java:966)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.util.NMS.setShulkerColor(NMS.java:266)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.trait.ShulkerTrait.run(ShulkerTrait.java:31)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.entity.ShulkerController$EntityShulkerNPC.B_(ShulkerController.java:70)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.h(World.java:1603)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
25.03 01:39:00 [Server] WARN at java.lang.Thread.run(Unknown Source)
25.03 01:39:00 [Server] INFO Exception while updating 187: null.
25.03 01:39:00 [Server] WARN java.lang.NullPointerException
25.03 01:39:00 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.setShulkerColor(NMSImpl.java:966)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.util.NMS.setShulkerColor(NMS.java:266)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.trait.ShulkerTrait.run(ShulkerTrait.java:31)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:271)
25.03 01:39:00 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.entity.ShulkerController$EntityShulkerNPC.B_(ShulkerController.java:70)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.h(World.java:1603)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
25.03 01:39:00 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
25.03 01:39:00 [Server] WARN at java.lang.Thread.run(Unknown Source)

I saw that it was mentioning a shulker box, so I go to one of my shulker box npc's.  Before I even get to it, I HEAR THE LOUDEST, MOST SPAMMING-EST NOISE OF MY LIFE.  It sounds like the shulker box is repeatedly spawning over and over again in rapid succession.  It actually causes a bit of lag to be around.  Please help.  I have no idea what is happening.

Minecraft Ver: 1.12.2
Citizens: 2.0.22-SNAPSHOT
Spigot: 1.12.2 (updated: 3/24/18)

**Comment by AaronStrange3** [comment]
Udate: the sound might be the shulker box opening.  I haven't played around with it too much, and I am not that familiar with shulker box sounds.

**Comment by AaronStrange3** [comment]
Update:

25.03 19:38:56 [Server] WARN java.lang.NullPointerException
25.03 19:38:56 [Server] INFO Exception while updating 188: null.
25.03 19:38:56 [Server] WARN java.lang.NullPointerException
25.03 19:38:57 [Server] INFO Exception while updating 191: null.
25.03 19:38:57 [Server] WARN java.lang.NullPointerException
25.03 19:38:57 [Server] INFO Exception while updating 187: null.
25.03 19:38:57 [Server] WARN java.lang.NullPointerException
25.03 19:38:57 [Server] INFO Exception while updating 188: null.
25.03 19:38:57 [Server] WARN java.lang.NullPointerException
25.03 19:38:58 [Server] INFO Exception while updating 191: null.
25.03 19:38:58 [Server] WARN java.lang.NullPointerException
25.03 19:38:58 [Server] INFO Exception while updating 187: null.
25.03 19:38:58 [Server] WARN java.lang.NullPointerException
25.03 19:38:58 [Server] INFO Exception while updating 188: null.
25.03 19:38:58 [Server] WARN java.lang.NullPointerException
25.03 19:38:59 [Server] INFO Exception while updating 191: null.
25.03 19:38:59 [Server] WARN java.lang.NullPointerException
25.03 19:38:59 [Server] INFO Exception while updating 187: null.
25.03 19:38:59 [Server] WARN java.lang.NullPointerException
25.03 19:38:59 [Server] INFO Exception while updating 188: null.
25.03 19:38:59 [Server] WARN java.lang.NullPointerException
25.03 19:39:00 [Server] INFO Exception while updating 191: null.
25.03 19:39:00 [Server] WARN java.lang.NullPointerException
25.03 19:39:00 [Server] INFO Exception while updating 187: null.
25.03 19:39:00 [Server] WARN java.lang.NullPointerException
25.03 19:39:00 [Server] INFO Exception while updating 188: null.
25.03 19:39:00 [Server] WARN java.lang.NullPointerException
25.03 19:39:01 [Server] INFO Exception while updating 191: null.
25.03 19:39:01 [Server] WARN java.lang.NullPointerException
25.03 19:39:01 [Server] INFO Exception while updating 187: null.
25.03 19:39:01 [Server] WARN java.lang.NullPointerException
25.03 19:39:01 [Server] INFO Exception while updating 188: null.
25.03 19:39:01 [Server] WARN java.lang.NullPointerException
25.03 19:39:02 [Server] INFO Exception while updating 191: null.
25.03 19:39:02 [Server] WARN java.lang.NullPointerException
25.03 19:39:03 [Server] INFO Exception while updating 187: null.
25.03 19:39:03 [Server] WARN java.lang.NullPointerException
25.03 19:39:03 [Server] INFO Exception while updating 188: null.
25.03 19:39:03 [Server] WARN java.lang.NullPointerException
25.03 19:39:03 [Server] INFO Exception while updating 191: null.
25.03 19:39:03 [Server] WARN java.lang.NullPointerException
25.03 19:39:03 [Server] INFO Exception while updating 187: null.
25.03 19:39:03 [Server] WARN java.lang.NullPointerException
25.03 19:39:03 [Server] INFO Exception while updating 188: null.
25.03 19:39:03 [Server] WARN java.lang.NullPointerException
25.03 19:39:04 [Server] INFO Exception while updating 191: null.
25.03 19:39:04 [Server] WARN java.lang.NullPointerException
25.03 19:39:04 [Server] INFO Exception while updating 187: null.
25.03 19:39:04 [Server] WARN java.lang.NullPointerException
25.03 19:39:04 [Server] INFO Exception while updating 188: null.
25.03 19:39:04 [Server] WARN java.lang.NullPointerException

**Comment by mcmonkey4eva** [comment]
Make sure you're running latest Spigot (check `/version`, it will tell you if you're behind)
Make sure you're running latest Citizens2 dev build from http://ci.citizensnpcs.co/job/Citizens2/ (match the build number from `/version citizens` to the latest build number on that link)

If the error is occurring on latest versions:

Post that NPC's setup as visible in the `Citizens/saves.yml` file.

My first suspicious is that you make have spawned a shulker NPC that has an invalid color value.

**Comment by fullwall** [comment]
Use the latest build.

**Comment by AaronStrange3** [comment]
I am now running the latest spigot version (this fixed a lot of my other problems, thank you) but the shulker box is still FLIPPING OUT, so here is how it appears in the save.yml:

https://pastebin.com/EKtK3zKt

Now, through testing of my own, I found that when the shulker box was freshly spawned it was perfectly fine.  But, when I tried to open it up with /npc shulker --peek (any number) it turned green and started freaking out with the sounds.

**Comment by fullwall** [comment]
Looks like the colors are different to the DyeColors which is why it's turning green, not sure why the sounds are triggering.

**Comment by fullwall** [comment]
Latest build has a fix
