### ISSUE TITLE
Shulker box lookclose suggestion

### ISSUE THREAD

**Issue by AaronStrange3** [CitizensDev/Citizens2#1459]
> I thought of how `lookclose` made NPCs look at the player when they were close, and it made me think if shulker boxes could `openwhenclose`, where when the player walks up to the NPC (within a certain distance) the shulker box opens.

Citizens version 2.0.22 Build 1528
CraftBukkit version git-Spigot-c3093ef-aa25568
Minecraft 1.12.2

Shulker box NPCs are working perfectly fine.  Until their chunk is unloaded.  If a player teleports away, and then back, the shulker box spawns but does not open.  If a player relogs, the shulker box will spawn but not open.  Using `/npc shulker --peek 100` or any other variation of that will not open the shulker back up.  However, using `/citizens reload` will open them back up.  There are no errors in console to report.

**Comment by fullwall** [comment]
Try latest build
