### ISSUE TITLE
Can't see animal or any other type of citizen except player

### ISSUE THREAD

**Issue by TheColdEmeraldCODE** [CitizensDev/Citizens2#1460]
MC Version: 1.12.2
Citizens Version: 2.0.22 SNAPSHOT (build 1487)

As said in the title, anytime I change the type of citizen to anything but a player, It doesn't show! I can hear it but not see it. I've tried re-installing it, resetting the config, and re-logging! But still, NOBODY can see it! HELP!

CONFIG: [https://pastebin.com/9xa4EqGJ](https://pastebin.com/9xa4EqGJ)

PLZ

**Comment by mcmonkey4eva** [comment]
That version of Citizens is old, keep your copy of the plugin up to date - http://ci.citizensnpcs.co/job/Citizens2/

Do you have any other plugins that might interact with entities? It's likely another plugin is causing a conflict.

**Comment by TheColdEmeraldCODE** [comment]
thx

**Comment by TheColdEmeraldCODE** [comment]
well the problem is still going on.....

**Comment by TheColdEmeraldCODE** [comment]
build 1528

**Comment by mcmonkey4eva** [comment]
`Do you have any other plugins that might interact with entities? It's likely another plugin is causing a conflict.`

**Comment by TheColdEmeraldCODE** [comment]
hmmmm
these are all my plugins: https://pastebin.com/kxMM0se7

**Comment by mcmonkey4eva** [comment]
` GadgetsMenu`
Probably that one.

**Comment by TheColdEmeraldCODE** [comment]
I don't use that so ill uninstall it and restart the server... waiting for it

**Comment by mcmonkey4eva** [comment]
BTW Sentry definitely doesn't work in 1.12, might want to get Sentinel at some point.

Also I am closing this issue and refusing further support on the grounds of running cracked plugins (`RWG2-CRACKED`).
