### ISSUE TITLE
Blank line in tablist

### ISSUE THREAD

**Issue by define-evil** [CitizensDev/Citizens2#1461]
Minecraft version 1.12.2
Citizens version 2.0.22

When I tried to enable human NPC display in player tab list, the npcs' names showed up as blank lines. Here's what it looks like:

![2018-03-28_21 47 45](https://user-images.githubusercontent.com/30694106/38033127-df78ea74-32d1-11e8-97d4-7d0696eb911c.png)

I tried to enable the player list by editing the config and using `NMS.addOrRemoveFromPlayerList`, but either way results in blank lines.

My spigot and citizens plugin are the latest built version.

**Comment by mcmonkey4eva** [comment]
Step 1: Don't do that.

We do not support pretending your NPCs are real players.
