### ISSUE TITLE
/Npc Select not working

### ISSUE THREAD

**Issue by Fonzee9** [CitizensDev/Citizens2#1462]
1.12.2 PaperSpigot build 1373

Npc's don't get selected with /Npc Select.

**Comment by Fonzee9** [comment]
Yes this issue is still present in Spigot

**Comment by Fonzee9** [comment]
Latest EssentialsX fixes this! I updated it 20 minutes ago and now /Npc Select works! 👍

**Comment by Fonzee9** [comment]
/Npc Select worked for 5 minutes now it's not working again..

**Comment by mergu** [comment]
The video shows you looking at the feet of a bunch of tightly-packed NPCs from an odd angle. Try repositioning yourself in a less-strange spot, or right click on them with a stick instead of using the command.

**Comment by Fonzee9** [comment]
Thank you using the stick works well 👍
