### ISSUE TITLE
/npc wolf -a broken

### ISSUE THREAD

**Issue by ScuroK** [CitizensDev/Citizens2#1463]
right now /npc wolf -a does not work.
sometimes the red eyes appear but they turn normal after a short moment.

**Comment by mcmonkey4eva** [comment]
Make sure you're running an up-to-date dev build of Citizens from http://ci.citizensnpcs.co/job/Citizens2/ as this was patched very recently

**Comment by ScuroK** [comment]
jup it works. thanks alot <3
