### ISSUE TITLE
[Question] 1.7.10 build?

### ISSUE THREAD

**Issue by SpaicyGaming** [CitizensDev/Citizens2#1466]
Which is the build for 1.7.10 servers? The download link on spigotmc is broken

**Comment by mcmonkey4eva** [comment]
Why are you running a 1.7.10 server?! That's insanely old!

https://wiki.citizensnpcs.co/Versions is the outdated version list.

If you're using something like MCPC there's half-working ancient ports available like https://www.dropbox.com/s/mcm7g1gmyb6f820/citizens-2.0.11-1.7.2-Cauldron-B1.jar

Be aware: we cannot provide support for any of these ancient versions, or any guarantee of functionality.
