### ISSUE TITLE
Parrots crashing server?

### ISSUE THREAD

**Issue by AaronStrange3** [CitizensDev/Citizens2#1467]
I have been having this problem for awhile now, and I have never found the source of it... however, going through crash reports I think it's citizens causing it.  Every time a player tames a parrot, my server shortly crashes after.  

Here is the crash report:
https://pastebin.com/z1NnXtqp

Citizens v2.0.22-SNAPSHOT (build 1528)
I am in the process of updating to the newest version of citizens to try and fix the issue.

**Comment by mcmonkey4eva** [comment]
Not particularly likely to be Citizens. If it's not an actual NPC and the stacktrace doesn't say Citizens in it, it's probably not Citizens. Update all relevant plugins and backing server software. If the problem persists and there's any actual reason to potentially blame Citizens at that point, reply below or open a new issue.

**Comment by AaronStrange3** [comment]
This was what made me think it was citizens:

Entity being ticked --

Details:

    Entity Type: null (net.citizensnpcs.nms.v1_12_R1.entity.ParrotController.EntityParrotNPC)

    Entity ID: 2329593

    Entity Name: Parrot

    Entity's Exact location: -1909.00, 54.00, 1390.00

    Entity's Block location: World: (-1909,54,1390), Chunk: (at 11,3,14 in -120,86; contains blocks -1920,0,1376 to -1905,255,1391)

**Comment by AaronStrange3** [comment]
I will get to updating though and see if the problem is fixed.

**Comment by mcmonkey4eva** [comment]
All entity class types are swapped to Citizens ones as part of how Citizens works to enable custom NPC backed entities. If the entity isn't a real NPC, it will still be that class type but Citizens won't execute any code on it.

**Comment by AaronStrange3** [comment]
ah, gotcha
