### ISSUE TITLE
NPC no players Type are vanish

### ISSUE THREAD

**Issue by DrStillMinefolie** [CitizensDev/Citizens2#1468]
MC version : 1.12
Spigot version : 1.12

So, I don't know how, but all npc mob type has disappear, npc with player type are already visible. 

I don't have any suspect message in the consol. We don't have make anything on the server. 

I've try the last build just in case, but nothing happen. 

I can hear the NPC but not see it. 

Thank you if you have any idea. 

EDIT : We have a WitherBoss has NPC, and on the life bar of the npc (up of screen) we have "unknown" as his name.

**Comment by mcmonkey4eva** [comment]
Often a plugin conflict. Look for related plugins that may effect entities or custom entities. There's also a few plugins that entirely inexplicably break a lot of stuff that we get reports about, such as "GadgetsMenu".
