### ISSUE TITLE
NPC path: halt when a player is close

### ISSUE THREAD

**Issue by JohOply** [CitizensDev/Citizens2#1471]
Hello

Could you add feature which allows an NPC to be stopped when it walks and a player come to its?

For instance, a NPC walks into the city. When a player come, it gives information about weather. When player get away from it, NPC walks again. It could be nice to add a configurable range.

Please tell me if something is not clear
Thanks for reading

**Comment by mcmonkey4eva** [comment]
This has definitely been done before a few times in Denizen and should be simple to do using Denizen.
( https://www.spigotmc.org/resources/denizen.21039/ - https://wiki.citizensnpcs.co/Denizen )
just attach a Denizen script to an NPC with a proximity trigger and pause/resume waypoints commands. Throw in some chat commands.

**Comment by JohOply** [comment]
Thanks for your answer

I jus tried this script https://scripts.citizensnpcs.co/view/8b2zfh
I also execute "/npc assignment --set Talker"

Sometimes NPC ask the question, but it continues to move

Have you some tips/idea to fix it or other script?

**Comment by mcmonkey4eva** [comment]
I have no idea how you ended up finding that specific link or why you think that makes sense to try.
Denizen is designed to be open for anyone to figure out how to write it. The needs you have are incredibly simple. Everything you need in this case is covered by the tutorial videos at https://one.denizenscript.com/denizen/vids

**Comment by JohOply** [comment]
Thank you again! I watched some videos, it is an incredible plugin with a lot of possibilities! But it is also hard to understand at the begining.

I succeed to do something simple which work for my question! However I think I will have many questions in the future!

Have a nice day!
