### ISSUE TITLE
Skins not loading.

### ISSUE THREAD

**Issue by BlueYoshi68** [CitizensDev/Citizens2#1472]
Please include:
It just refuses to put skins on the NPCs.

There is no error and i havent changed the config what so ever.

Im using spigot-1.12.0-2017-06-08-a.jar and citizens 2.0.22-Snapshot

Ive only tried to make 1 npc a few different ways to try and fix it but no luck.

**Comment by mcmonkey4eva** [comment]
Use `/version` to see Spigot version and `/version Citizens` for Citizens plugin version.

Make sure, of course, that both are actually latest.
Which they probably aren't as your spigot jar name looks like it's version 1.12 flat from early 2017.
Which is very old.

**Comment by BlueYoshi68** [comment]
well i cant change versions, what version of citizens i need to use for that version

**Comment by mcmonkey4eva** [comment]
We can't provide support to outdated server software. Update your server or shut it down. It's nonsense to intentionally run an outdated version (especially a subpatch version diff), and it's a waste of everyone's time to complain about issues relating to outdated versions.

**Comment by BlueYoshi68** [comment]
You realize ive used a version of citizens on this before? I just need to know which one.

**Comment by mcmonkey4eva** [comment]
You realize we do not provide support to outdated versions? You just need to update your server to latest.

**Comment by BlueYoshi68** [comment]
Do you realize how irrational that sounds. You're telling me that you cant tell me a plugins version because "you dont provide support".  How up-tight do you gotta be, guy.

**Comment by BlueYoshi68** [comment]
Forget it, you're useless to me in this matter.

**Comment by mcmonkey4eva** [comment]
Do you realize how irrational that sounds. You're telling me you want to use some random outdated build instead of raising a few versions to use the current security patch. How moronic do you gotta be, guy.
