### ISSUE TITLE
Npc's take away the nametags of players with NameManager plugin.

### ISSUE THREAD

**Issue by Fonzee9** [CitizensDev/Citizens2#1473]
Npc's take away the nametags from NameManager when joining the server.

Paper 1.12 Build 1384 (Same issue with Spigot so Paper isn't the issue)

Citizens Build 1530

**Comment by Fonzee9** [comment]
For example i join the server and my name becomes white because a Npc overrides the nametag.

**Comment by mcmonkey4eva** [comment]
Do you have an NPC with the the same basic name as you?

If so: don't do that. At the minimum add a color code or special character to the name.

Some Minecraft systems and cheapo plugins will differentiate players by name, and mistakenly consider you equivalent to an NPC with your name.

**Comment by Fonzee9** [comment]
I just tried to add a color code and a special character to my npc's names my name still turns white in tab when i join my server.

**Comment by mcmonkey4eva** [comment]
Likely something wrong with the plugin that's doing that then?

**Comment by Fonzee9** [comment]
Same problem happens with Nametagedit i switched to NameManager to test it and same problem.
