### ISSUE TITLE
Skins not loading.. help

### ISSUE THREAD

**Issue by muzyeh** [CitizensDev/Citizens2#1475]
spigot-1.12.2
citizens-citizens-2.0.22-SNAPSHOT #1531
Use the latest version
Skin cannot be displayed....
I am sorry, my english is poor

**Comment by muzyeh** [comment]
Nobody knows.. ?
help..

**Comment by mcmonkey4eva** [comment]
Is there an error?
Are you on a shared server (or dedicated IP)?
Are you in online mode or offline mode?

There's so much relevant information here.

**Comment by muzyeh** [comment]
online mode
dedicated IP
not error

**Comment by mcmonkey4eva** [comment]
Not sure what to tell you. There's a lot of potential issues, especially if using non-standard configurations, shared servers, old server versions, etc.

**Comment by SirKillian** [comment]
I have the same issue on build 1537

**Comment by mcmonkey4eva** [comment]
We can't provide support with no information. It's generally an issue related to your server contacting Mojang services.
Feel free to open proper issues if you gather any relevant information and need help moving forward.

As a starting point, look at any of the 200 prior issues relating to skins, the majority of which were resolved for the users. https://github.com/CitizensDev/Citizens2/issues?utf8=%E2%9C%93&q=skin
There's a good chance you can find help with your specific skin-related issue in one of them.
