### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by AIphaDragon** [CitizensDev/Citizens2#1476]
Hello, we have been using your plugin for a long time and did not feel any problems on version spigot 1.11.2. Since the summer we wanted to upgrade to a new version (spigot 1.12.2), but we constantly faced the problem of memory leakage and only now we are sure that the problem is in this plugin. After installing version spigot 1.12.2, there is a problem with the memory and eventually crash the server. We have a citizens (build1530). Approximate number of NPCs: 200. At the time of the experiment, only 1 person entered the server. This problem is only on version spigot 1.12.2. 
config: https://pastebin.com/cyYQTK4e
saves: https://pastebin.com/Tzd6VZ57
crash: https://pastebin.com/zmRjngwe
timings: https://timings.spigotmc.org/?url=nimipugafa
wg report: https://pastebin.com/KAxBKJSu

If you need more pastebins, write. Thanks in advance for your help.

**Comment by fullwall** [comment]
Probably would need a report from a profiler to help track this down.

**Comment by mcmonkey4eva** [comment]
The crash stacktrace is on an NPC spawning in, and within PEX recalculating permissions for the NPC. This makes no guarantees of relevance as the crash log is a time out and thus the stack is somewhat random, but it may be connected.

**Comment by fullwall** [comment]
Since the crash is after a chunk load, there could be a number of things causing extra memory pressure at that moment

**Comment by AIphaDragon** [comment]
So, how can this problem be fixed? Or what report form what app do we need to make to send you a required report?
We are looking forward to your aswer

**Comment by mcmonkey4eva** [comment]
Any Java profiler data would assist (google "java profiler" and find any reasonable free one), they're generally able to get CPU usage stats and memory usage / allocation stats in a very precise way that will greatly assist in tracking down the root cause of memory or lag related issues. There are some that are tailored for Minecraft usage like Warmroast, though any good general Java profiler will do.

**Comment by AIphaDragon** [comment]
![81](https://user-images.githubusercontent.com/30160189/38750947-36d1259a-3f5f-11e8-97ed-a1b1a759f688.png)
Sorry that took so long. This is what you need?

**Comment by fullwall** [comment]
That screenshot isn't consistent with a memory leak - less than 1MB of objects allocated there. I am not sure what to make of it. @mcmonkey4eva ?

**Comment by mcmonkey4eva** [comment]
Yeah that doesn't look like problematic anything there. Possibly the profiler was run only in passing before screenshotted and shared?
@AIphaDragon we'd need to see results data related to the server starting to get bad, ideally run early on and allowed to collect data as it worsened.
Also, I'm not sure why you think there's a memory leak. If you're basing that off the red text on the timings page - yeah no that's not really super accurate that's just a suggestion of something to check for.
There was also a heapspace (memory usage) crash, but that was *after* the spigot watchdog freaked out. It looks like the server froze up and crashed, but secondary threads remained active and took almost an hour before using all memory while cycling on a dead server and crashing from that (likely they would have been building up memory while preparing things for the server itself to process, which never happens as that area of the server was crashed and gone).

I think more interesting is your CPU usage, which timings got confused at but does say that the NPC playerupdatetask (which runs every single tick) is using `22.59 ms` every tick on its own. Meaning, a solid half of every single tick time is used up handling NPC players (in pathfinding, etc.)

I'd take a look at what a profiler might say in regards to CPU usage, as it's possible the issue stems from the CPU being weighed down really hard.

For memory related issues, the best thing to do is find a time where it is heavily in use (memory is full of junk), and using an already-attached profiler, look at what the majority of live memory is (what Java objects are using the majority of memory space). Often a memory leak will have a single specific object type or just a few types using massive amounts of memory on their own (as leaks are generally certain objects building up and never going away).

**Comment by AIphaDragon** [comment]
This screenshot was taken after 10 minutes of server work. We cannot run a program on our server because we don't have a full access to it. So, we make tests only on localhost.
But still, we can make screenshots of longer work of server.
Also, we provided such tests on our test server on our hosting and noticed, that with Citizens plugin server works up to 6-8 hours without any players. Then, it crashes with an error, that we sent you earlier.

We will try to make a longer timing of server work

**Comment by mcmonkey4eva** [comment]
That crash was not sourced in an error nor was it sourced in Citizens.

**Comment by AIphaDragon** [comment]
After 4 hours 5 minutes
![96](https://user-images.githubusercontent.com/30160189/38902374-efb021fa-42a8-11e8-8995-fd98546dde92.png)
![97](https://user-images.githubusercontent.com/30160189/38902375-efcb5088-42a8-11e8-8d36-b787474d0e59.png)

After 5 hours 20 minutes
![103](https://user-images.githubusercontent.com/30160189/38902451-3996e420-42a9-11e8-8208-d0612632fc3e.png)
![104](https://user-images.githubusercontent.com/30160189/38902452-39b4461e-42a9-11e8-899c-da8a06616c2a.png)

With CPU problems. We will deal with the error.

**Comment by Kneesnap** [comment]
^ Appears related to my issue https://github.com/CitizensDev/Citizens2/issues/1464

**Comment by AIphaDragon** [comment]
CPU usage. Data for 5 hours.
![110](https://user-images.githubusercontent.com/30160189/38961494-7fd0e044-4371-11e8-8f6d-f83f27f9dd77.png)
![111](https://user-images.githubusercontent.com/30160189/38961496-7ff25120-4371-11e8-9004-ded33c360fa8.png)
![112](https://user-images.githubusercontent.com/30160189/38961497-80129746-4371-11e8-9553-d65fb8b90f22.png)
![113](https://user-images.githubusercontent.com/30160189/38961498-802e84ce-4371-11e8-9eae-ff7fc1b4c318.png)

After connecting the profiler, this message was received - https://pastebin.com/pvq0mf93. After 5 minutes of operation TPS fell sharply to 15 and then fell to 3. Without profilier, this situation was observed only after 8 hours. Most likely I'm doing something wrong...

**Comment by Kneesnap** [comment]
@AIphaDragon It looks like you're having the same issue I'm having. Use your profiler to track object allocations, instead of CPU usage.

**Comment by mcmonkey4eva** [comment]
As an up-ref:
#1495 led to a fix for a memory leak, may solve... eh, whatever this issue is... as well

**Comment by AIphaDragon** [comment]
We tested the plugin. Online: 30 people. Work time: 18 hours. Everything is stable. The problem is fixed. Thank you for solving the problem.
