### ISSUE TITLE
npcs appear and then disappear from tab list, also they disappear from world

### ISSUE THREAD

**Issue by intangir** [CitizensDev/Citizens2#148]
I have 47 npcs on my first world, but half of them disappear half the time, and not the same half

also i can see them all appearing on the tab list temporarily then disappearing

actually as i run up and down the hall

the closer ones in chunks already loaded are disappearing, while new ones in chunks being loaded seem to stay?

its like its removing ones already out

**Comment by fullwall** [comment]
Try the latest build please.

**Comment by Boosik** [comment]
Latest build fixed this issue for me.

**Comment by diwaly** [comment]
Yes work fine on build 1203. But the skins aren't always loaded.

**Comment by noorkoteb** [comment]
cant it be that u can manually insert skins into the npc file instead of checking with mojang servers because mojang has alot of issues in 1.8 skin check and stuff
