### ISSUE TITLE
Unable to change skin

### ISSUE THREAD

**Issue by Tyloonie** [CitizensDev/Citizens2#1481]
Hello, I'm not able to change any skins on my NPCs - so much for buying the newest version on Spigot, huh.

https://pastebin.com/CSwLnX0P

**Comment by mcmonkey4eva** [comment]
Newest version of Citizens is at http://ci.citizensnpcs.co/job/Citizens2/
Spigot release of Citizens is not latest.

You're also not running latest Spigot there, you're running Paper, which we do not officially support (Paper is a broken fork of Spigot).
