### ISSUE TITLE
Weird message when trying to create NPC

### ISSUE THREAD

**Issue by MiMic10110** [CitizensDev/Citizens2#1482]
When I am using "/npc create test" command, I get this message:
?Couldn't create NPC. Reason: Over the NPC limit of 0.?

Server: newest spigot from buildtools
Citizens: newest from jenkins

Thanks for any help!

**Comment by mcmonkey4eva** [comment]
Make sure you have all valid permissions for Citizens. If you're missing permissions, it might force you to a low or empty NPC limit value.
