### ISSUE TITLE
Npc's are still standing way off of their usual spot, even after all (i mean really ALL) plugin load/manage plugins were deleted from the servers

### ISSUE THREAD

**Issue by MrKiller01** [CitizensDev/Citizens2#1485]
The problem is persistent, the NPC's are all on top of my spawn building, on weird places. I gave all the info before, but this time the server generates no errors or whatsoever that I can show you.

I had removed all pluginmanagers I used on your advise, so now I have to stop and start the server every change... I know it is better, even if it takes more trouble for those online, but hey, Npc's that are floating above a building.... out of reach? no fun....

**Comment by MrKiller01** [comment]
I have been trying the following.
From backup I took as well as the saves.yml, an older version of citizens.jar and I had the snapshot version running Citizens-2.0.22_1.12.2 and I tried citizens-2.0.21-SNAPSHOT and to no avail..... All those NPC's are way off their original point. I dare not to delete the whole pluginfolder, and see if that helps if I make a new one, because some I made earlier are very extended in trading etc.
So, it is not the JAR file, it cannot be the config, as there is no coordinates, and the save file I tried from backup was from months before this weird behavior occurred.
Help!
Ps. not all npc's are affected, it looked like those that were in vicinity chunks of the spawn. A friend of mine had this guard walking next to her, and when she returned to my server I noticed that her NPC did act normal. Tp and move to coordinates does also not work. (for the affected)

**Comment by mcmonkey4eva** [comment]
Always run latest dev build from: http://ci.citizensnpcs.co/job/Citizens2/
It's very likely to be a server config or plugin conflict

Might be worthwhile to test on a copy of the server (download some server files to your home PC and run it locally) with various large changes being made to see if they will cure it, such as removing all other plugins (and if that works, add half of them back and see then, and repeat that process until you can narrow it down to a single plugin or two)

**Comment by MrKiller01** [comment]
@mcmonkey4eva , you said that it's very likely to be a server config or plugin conflict, well, what if I told you the Precious stoned i used on my spawn point, just outside the range of them, there were standing the NPC's. Better yet, when in a PS cityplotfield, I tphere a NPC, it says that it is transported to my place while actually it is not!. When i deleted the PS in the spawn and only left it with a wordguard region, the NPC's were able to listen to me as I asked them to come to me....
So, your theory is flawed. I ended up Mobhunting records standing NPC's that were also on top of my spawn, i adjusted the PS field so that they were standing outside of it, and the NPC's found their way back. If I am outside any PS region and ask any NPC to come tphere to me, it works. 
So, NPC, CITIZENS2 and PRECIOUSSTONES are not cooperating well at this time. I can only adjust the fields here and there, but that is not the solution.....  I am a bit concerned that the owner did not respond to this plea, so I hope you will, I'll go try to find Mr Mason and point him to this page..... (PreciousStones owner)

Thanks for thinking along with me, much appreciated....

**Comment by Swede37** [comment]
Just an observation:

I deactivated the Denizen plugin jar and restarted our server. ( testing to see what's spawning in invisible armorstands here and there) which was a bad move on my part. Even though all our  NPCs weren't explicitly tied into Denizen, ( using npcDestinations & Betonquest) we had many errors loading traits when the server restarted without Denizen. Probably necause it didn't shut down properly. And.... You guessed it... The NPCs were all awol having a party where they don't belong.

I'm not sure how this all ties in, but maybe Precious stones  is preventing your NPCs from saving correctly on shutdown/restart?

**Comment by mcmonkey4eva** [comment]
@Swede37 Denizen does two things at any given point in time:
Run functionality you told it to run via in-game commands (it adds a lot of things to NPCs that you might not even realize are part of Denizen rather than Citizens. It has commands even within `/npc` that are 100% handled by Denizen.)
And it runs functionality you told it to run via scripts.

It does not run anything else. It does not do anything on its own (unless some weird error occurs).

**Comment by MrKiller01** [comment]
I have send the PS owner this link and asked him to look at it, I do hope he will look at it and take the time to do something about it, even if it was contacting me, you, us!
