### ISSUE TITLE
/Spawn server crash

### ISSUE THREAD

**Issue by MooshroomStatus** [CitizensDev/Citizens2#1486]
Whenever I use /spawn or I die, my server crashes. I'm not sure what the cause is as it started happening out of nowhere.
MC Version: 1.12.2
Citizens: 2.0.22-SNAPSHOT build 1479
Here's the log I'm getting from the server. I can't read it, but I hope you can;
[https://pastebin.com/0xamF4A2](https://pastebin.com/0xamF4A2)

**Comment by mcmonkey4eva** [comment]
You're running very old plugins.
Please update to latest builds!
http://ci.citizensnpcs.co/job/Citizens2/
http://ci.citizensnpcs.co/job/Denizen/
