### ISSUE TITLE
NPC Body Rotation Cannot Be Controlled

### ISSUE THREAD

**Issue by kellarius** [CitizensDev/Citizens2#1487]
The npcs heads are easily posable with the /npc pose command (even if just horizontally, not sure if its a bug), and you can make his body face the direction you want with it:

![2018-04-17_18 30 09](https://user-images.githubusercontent.com/38477594/38899331-e6a3a54a-426d-11e8-8470-28572cec50c8.png)

However, when you go far away and come back, the NPC's body is reset to the original position, making it impossible to make a straigth-facing npc:

![2018-04-17_18 30 53](https://user-images.githubusercontent.com/38477594/38899354-f539deb2-426d-11e8-880a-d0d689cae158.png)

**Comment by fullwall** [comment]
Looks like more of a bug since /npc pose should set body and head yaw to be the same

**Comment by mcmonkey4eva** [comment]
In current version (`git-Spigot-766dab2-b9a2a74 (MC: 1.14)` and `Citizens version 2.0.25-SNAPSHOT (build 1654)`), head yaw is hopelessly broken. Have opened as new issue #1753 
Can recheck this after that's fixed.

**Comment by mcmonkey4eva** [comment]
Head yaw and body yaw are indeed set to the same value, and NPCs do indeed remain facing the correct direction after leaving and coming back.
However, body yaw would ideally not be the same head yaw, and instead be actually tracked on its own, as its underlying value is independent.

**Comment by mcmonkey4eva** [comment]
There's an experimental fix for this in current dev builds @ https://ci.citizensnpcs.co/job/Citizens2/
