### ISSUE TITLE
Invincible Npc's

### ISSUE THREAD

**Issue by jumpy72red** [CitizensDev/Citizens2#1488]
I have citizens 2 and a 1.12.2 server, but when I try to attack my citizens, they won't take damage!
![2018-04-19_09 07 17](https://user-images.githubusercontent.com/37401240/38979108-2fd51a2a-43b1-11e8-99f1-978e87f4aa82.png)

( My console doesn't want to give me any data but the config is here: https://pastebin.com/kypZCSg2 )

**Comment by mcmonkey4eva** [comment]
NPCs do not take damage by default in Citizens. They are not mobs, they are idle entities awaiting a purpose given to them. One option is to use Sentinel, which adds combat capabilities to the NPC
https://www.spigotmc.org/resources/sentinel.22017/

**Comment by jumpy72red** [comment]
Please help!
