### ISSUE TITLE
NPCs always facing south in 1.8.8

### ISSUE THREAD

**Issue by Estok** [CitizensDev/Citizens2#1492]
When I create npc on the lastest build (snapshot 2.0.22) it spawns in the right pitch and yaw some seconds later the npc would rotate to face south.

**Comment by Estok** [comment]
I have a plugin that depends on Citizens and all the users using it on 1.8.8 are messaging me with bug report messages which refer to this bug. Your plugin is compatbile with that version and should be completely functional. There are plenty of server running Spigot 1.8.8. I would be grateful if you fix that. Thanks for understanding.

**Comment by mcmonkey4eva** [comment]
There are plenty of servers that are incorrectly configured.
There is no reason to run 1.8

I would be grateful if you (and your users) update to 1.12.2 latest
