### ISSUE TITLE
Hide NPC's name when its empty.

### ISSUE THREAD

**Issue by Estok** [CitizensDev/Citizens2#1493]
Hiding the NPC's name when it's empty would be a nice feature. At least nicer than having an NPC with a blank rectangle on its head.

**Comment by MusicScore** [comment]
You can use `/npc name` to hide the nameplate.

**Comment by Estok** [comment]
That won't work on 1.8.8.

**Comment by mcmonkey4eva** [comment]
There's no reason to ever run Spigot 1.8.8...
Run latest Spigot 1.12.2
If you want to support outdated clients, check out plugins like ViaBackwards which allow older minecraft clients to connect.
If you want to run older style PvP, there's combat backdating plugins available as well.
