### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1495]
Test server
CentOS Linux release 7.5.1804
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
Spigot 1.12.2 latest

90+ plugins, all latest dev builds, including Citizens and dependents:
- citizens-2.0.22-b1541
- denizen-1.0.2-b1647
- DepenizenBukkit-1.0.0-b395
- sentinel-1.4.5-b165

I am trying to isolate memory leakage in plugins. The test server has 34 Citizens running across six worlds. To establish a baseline, there are no players connected (it's a test server).

Active plugins in this steady state:
- Plan :: generating data, frequently
- PyroWeather :: starting and stopping acid rain in one world, randomly
- StreetlightsAdvanced :: flipping some lights, every 12 MC hours

With Citizens and dependents disabled, the server runs comfortably with maxheap=3G and simplified GC (-XX:+UseG1GC). For example, in the three days since last startup, allocated memory started at 2.3G and is now only 2.8G (so there is some small leakage elsewhere, but relatively insignificant). Free memory ranges between almost none and 2.2G, as GC is exercised.

With Citizens and dependents enabled, maxheap is quickly fully allocated regardless of setting (between 3G and 8G tested so far), and the server crashes within two days as free memory is consumed. Testing has also been performed with the Aikar-recommended GC settings, with no apparent difference to the outcome.

So it is certainly suggestive, but not conclusive, that the memory leaks are due to Citizens and dependents.

Initial questions:

- Is this a known issue?
- How much memory should be allocated per NPC?
- How can I contribute to isolating this issue? My test server is available, if useful.

**Comment by SlimeDog** [comment]
For reference, this is a typical Essentials memory listing, with Citizens and dependents disabled:
```
[16:00:01 INFO]: CONSOLE issued server command: /mem
[16:00:01 INFO]: Uptime: 3 days 1 minute 31 seconds
[16:00:01 INFO]: Current TPS = 20
[16:00:01 INFO]: Maximum memory: 3,072 MB.
[16:00:01 INFO]: Allocated memory: 2,769 MB.
[16:00:01 INFO]: Free memory: 601 MB.
[16:00:01 INFO]: World "world": 256 chunks, 16 entities, 7 tiles.
[16:00:01 INFO]: World "world_blackdog": 256 chunks, 92 entities, 54 tiles.
[16:00:01 INFO]: World "world_city": 260 chunks, 245 entities, 524 tiles.
[16:00:01 INFO]: World "world_lobby": 256 chunks, 44 entities, 177 tiles.
[16:00:01 INFO]: World "world_luckyblock": 256 chunks, 3 entities, 10 tiles.
[16:00:01 INFO]: World "world_minigames": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: World "world_parkour": 256 chunks, 7 entities, 8 tiles.
[16:00:01 INFO]: World "world_skyblock": 256 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: World "world_void": 256 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: World "world_whitedog": 265 chunks, 3 entities, 14 tiles.
[16:00:01 INFO]: World "world_yellowdog": 257 chunks, 109 entities, 5 tiles.
[16:00:01 INFO]: Nether "world_blackdog_nether": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: Nether "world_city_nether": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: Nether "world_nether": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: Nether "world_skyblock_nether": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: Nether "world_whitedog_nether": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: Nether "world_yellowdog_nether": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: The End "world_blackdog_the_end": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: The End "world_city_the_end": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: The End "world_skyblock_the_end": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: The End "world_the_end": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: The End "world_whitedog_the_end": 0 chunks, 0 entities, 0 tiles.
[16:00:01 INFO]: The End "world_yellowdog_the_end": 0 chunks, 0 entities, 0 tiles.
```

**Comment by mcmonkey4eva** [comment]
Did you just... fork off from an existing issue, having the same issue as was mentioned in the original... but starting anew ignoring all posts and suggestions in the original issue?

If you want to be starting up a fork issue at least gather the data points from your own server as were requested from the original issue

**Comment by SlimeDog** [comment]
I wasn't sure that "extra objects" was the same as leakage. I didn't seem to have the same characteristics. If you think they are the same, I will read back.

**Comment by mcmonkey4eva** [comment]
A lot of my posts on #1476 referenced memory leaks very explicitly, and advised the usage of a java profiler to analyze them, which would be very useful here. A proper profiler should be able to pinpoint exactly what is using massive amounts of memory.

**Comment by SlimeDog** [comment]
I have HeapAnalyzer. Will that do?

**Comment by mcmonkey4eva** [comment]
Should work, yeah

**Comment by SlimeDog** [comment]
Would you like dumps every 12 hours or so, or just capture a crash?

**Comment by mcmonkey4eva** [comment]
Information gathered when it's about to crash (memory space almost all taken) would be ideal

**Comment by SlimeDog** [comment]
Link to heap dump sent via Spigot PM.

As I read it with HeapAnalyzer, there is a lot of memory associated with Citizens, including 2G+ in thousands of entries in HashMap$Node elements (for 34 Citizens NPCs). I have no idea if this is expected, reasonable, or not-so-much.

**Comment by mcmonkey4eva** [comment]
Got the file @SlimeDog thanks!

The memory leak is from player advancement data attached to NPCs. Of course it is .-.
@fullwall that advancement cleary thingy is going to need even more fixing!

Object path trace for reference:
https://i.imgur.com/rA2F03L.png

**Comment by SlimeDog** [comment]
Thanks. So my work here is done? :)

**Comment by SlimeDog** [comment]
Testing with citizens-2.0.22-b1542

**Comment by SlimeDog** [comment]
Configuration as above, except
- citizens-2.0.22-b1542

The result is the same, except that it took only one day instead of two to crash.
Link to new heap dump sent via Spigot PM.

**Comment by mcmonkey4eva** [comment]
You also have a massive number of NPC advancements that I'm working on tracing down atm... for reference on where they will be visible, they take a form like `./UNIVERSE/world/advancements/91974dcd-290f-21b1-a036-0bf8790eb9aa.json` (that's an example of one specific entry in your heap dump). I imagine that folder is flooded with files if they've been saving to disk, and if so might help to clear that out (or at least all version 2 uuids... that is, ids where the 3rd block - at `21b1` in that example - starts with a 2. For comparison, version 4 means a valid player and version 3 means an offline-mode player).

@fullwall 

From what I can see:
NMS class `CriterionTriggers` contains static references to `CriterionTrigger` implementations.
Each implementation class is very helpfully retaining a full list of every `AdvancementDataPlayer` instance it receives (in a map).

I think that pathway specifically needs to be cleared of data.

Tracing is similar to before: AdvancementProgress instances contained within the maps held by AdvancementDataPlayer which is held underneath the CriterionTriggers mess.
They have maps of the style `Map<AdvancementDataPlayer, CriterionTriggerKilled.a>`
The key is a reference in itself, and the `.a` subtyped value contains advancement data itself as well.

The most expensive CriterionTriggers are `CriterionTriggerInventoryChanged` and `CriterionTriggerRecipeUnlocked` for reference. Those contain 35% and then 32% of data waste, the next 5 down are 4%, 2x 3%, 2x 1% ... the rest are all extremely small usage. The lowest about 10 of them are all at 6174 instances, which I think means NPCs haven't ever triggered these. It's weird ones, like `CriterionTriggerVillagerTrade`.

**Comment by SlimeDog** [comment]
None of the NPC advancements appears to have been saved to disk. The ./UNIVERSE/world/advancements/ directory is empty, save for two valid players UUIDs.

**Comment by fullwall** [comment]
@mcmonkey4eva that is what PlayerAdvancementData.a() is meant to clear (although I admit I haven't gone through all the CriterionTriggers). Also if it was a CriterionTrigger it would show up as a large groups of objects in the heap, no?

**Comment by mcmonkey4eva** [comment]
@SlimeDog why are all those UUID's holding a player version ID (the `4` digit at the start of each third grouping)? They are not valid player UUIDs, and I don't believe NPCs should be holding player versioned UUIDs.

@fullwall Er, looked at the clearing code...
Class: `net.citizensnpcs.nms.v1_12_R1.util.EmptyAdvancementDataPlayer`
Method present:
```java
    @Override
    public void a() {
    }
```
The clear call:
```java
this.a();
```
See the problem there, right? :P 
I'm guessing either that should be `base.a();` or the `a()` override should be removed...

**Comment by SlimeDog** [comment]
I have no idea. They were created by Citizens and/or its dependents. I just copied the data from _Citizens/saves.yml_.

**Comment by SlimeDog** [comment]
Restarted tests with
- citizens-2.0.22-b1543
- denizen-1.0.2-b300
- DepenizenBukkit-1.0.0-b396
- sentinel-1.4.5-b165

**Comment by SlimeDog** [comment]
After approx 7 hours, configured 3G memory allocated, but lots of free memory (cyclically as GC does its magic). How much memory should I expect to be allocated per Citizen NPC?

I will test with higher configured memory after this test runs for a few days.

**Comment by mcmonkey4eva** [comment]
`How much memory should I expect to be allocated per Citizen NPC?`
It's hard to specify due to there being so many potential variables involved in that, but if the NPCs are not doing much they shouldn't be using much of any RAM.
If no leaks occur (no memory building up over time) then we're probably good on that front.

**Comment by SlimeDog** [comment]
Understood. Based on ^^^
```
With Citizens and dependents disabled ... 
allocated memory started at 2.3G and is now only 2.8G [after three days] ...
```
With the Citizens  and dependents in the mix, allocated memory quickly rises to the 3G configured. So I was wondering if maybe maxheap should be set higher. I'll try 4G in the next test, to see if it doesn't fill up at a higher level.

**Comment by SlimeDog** [comment]
Test with
- citizens-2.0.22-b1543
- denizen-1.0.2-b300
- DepenizenBukkit-1.0.0-b396
- sentinel-1.4.5-b165

Similar results. New pre-crash heap dump link sent via PM.

**Comment by SlimeDog** [comment]
Thanks for the insight. I passed it along (with a few politic elisions) to the LuckPerms team.

**Comment by mcmonkey4eva** [comment]
Actually, looking at that bit closer:
It might be an issue with the way Bukkit itself handles permissions (and Citizens not compensating for Bukkit being so stupid with perms), LuckPerms was just caught in the middle for being your permissions plugin, and isn't actually at fault.

**Comment by SlimeDog** [comment]
Thanks for the note on LuckPerms. I closed the ticket.

**Comment by mcmonkey4eva** [comment]
@fullwall as for the permissions issue:
`EntityHumanNPC` class defines a contained class `PlayerNPC`, that class has access to protected field `perm`... I believe that needs to be used in call `perm.clearPermissions();`, which should unregister the NPC from permissions subscriptions in Bukkit's nonsense system.

**Comment by SlimeDog** [comment]
Restarted tests with
- **citizens-2.0.22-b1545**

**Comment by SlimeDog** [comment]
24 hours into the latest test, allocated memory and free memory are stable on both servers (within the range of expected GC expansion/contraction). I'll leave the tests running for a few days, but it looks like the latest changes have done the trick, for my mix of Citizens NPCs. 👍

**Comment by SlimeDog** [comment]
Empty of players.

**Comment by SlimeDog** [comment]
Based on 2+ days of responsible memory/GC management, I think this issue is resolved. I will wait a day for other comments, then close.

**Comment by AIphaDragon** [comment]
I tested it on an empty server for 2 days. Everything works well. For complete certainty, tests on the server with players are still needed. Do you plan to test in the near future on your server with the players? Thank you in advance for your response.

**Comment by SlimeDog** [comment]
I cannot test on production server at present. Someone else will have to test with player load.

**Comment by AIphaDragon** [comment]
We tested the plugin. Online: 30 people. Work time: 18 hours. Everything is stable. The problem is fixed.

**Comment by SlimeDog** [comment]
Thanks @AIphaDragon.  Closing...

**Comment by SlimeDog** [comment]
More data: 15 days up, no issues. Awesome!
