### ISSUE TITLE
Plugin don't work in server but i did bought him on spigot

### ISSUE THREAD

**Issue by GekkeGlenn** [CitizensDev/Citizens2#1496]
Help me pls i have bought the plugin but if it is in my server and i do /pl citizens is red help me pls

**Comment by mcmonkey4eva** [comment]
What version is your server, what version of Citizens are you running?

**Comment by GekkeGlenn** [comment]
I have the viaversoin plugin.

That is the plugin that i can join on evry version

**Comment by mcmonkey4eva** [comment]
This does not answer the question. What version is your server?
Use `/version` to output the version data of your server.
Use `/version citizens` to output the version data of your copy of Citizens.

**Comment by GekkeGlenn** [comment]
/version says: "This server is running craftBukkit version
git-spigot-e000104-4cb3258 (MC:1.9.2) (Implementing API version 1.9.2-R0.1-snapshot)
Checking version, please wait...
You are 677 version(s) behind"

/version citizens says: "Citizens verion 2.0.18-snapshot (build 1364)
"

**Comment by GekkeGlenn** [comment]
But where can i download the latest Bukkit version????

**Comment by mcmonkey4eva** [comment]
Spigot wiki page explaining how to get the latest Spigot jar: https://www.spigotmc.org/wiki/buildtools/

**Comment by GekkeGlenn** [comment]
What is the difrents with spigot and bukkit

**Comment by mcmonkey4eva** [comment]
Bukkit is an API, and the name of the team that originally developed the server software involved. That team is entirely gone, and has been for several years now.
Spigot is a functional Minecraft server that is based on the Bukkit API, and is the name of the team currently maintaining this software.

**Comment by GekkeGlenn** [comment]
so spigot is better

**Comment by mcmonkey4eva** [comment]
That's not a relevant thing to say.
Spigot is the current server software.
Bukkit is not server software, it's an API.
You can't say one is better, as they are not equivalent.

**Comment by mcmonkey4eva** [comment]
Anyway, point is: Run latest Spigot, and latest Citizens2

If you encounter trouble with both updated, open a new issue

**Comment by GekkeGlenn** [comment]
I don't have spigot bud the latest version of bukkit and he is doing fine

**Comment by mcmonkey4eva** [comment]
You cannot run a server with Bukkit. That doesn't work. That isn't a thing that is physically possible to do.
Bukkit is an API. Bukkit is not executable server software.
