### ISSUE TITLE
Armor Stands and LookClose

### ISSUE THREAD

**Issue by Omanoctoa** [CitizensDev/Citizens2#1499]
Hello!
I've used Citizens2 for a while and it was a hit on our old server. I've recently started setting up a new server and I've encountered an unexpected issue. Before, when we had Armor Stand NPCs with heads (otherwise invisible) they could be set to LookClose and look at passing players (great for creeping people out). When I recently set up an Armor Stand NPC to lookclose....it did nothing. I've tried setting it as a Player (or spawning it as a player) then changing it to the ArmorStand type after enabling LookClose, but it loses the ability to look at players. Was this disabled or is it a bug? I know it worked in 1.11.2 but this is my first time testing it in 1.12 I think.

**Comment by mcmonkey4eva** [comment]
Are you testing on the latest dev build from http://ci.citizensnpcs.co/job/Citizens2/ and a fully updated Spigot 1.12.2 server?

**Comment by Omanoctoa** [comment]
As of the time of my posting, yes. It was a brand new server set up only a week before that, so Spigot and all the plugins in use were as up to date (dev versions mostly) as possible. I'll try it again with the latest "latest release" and see if that solves anything...

(Testing)

Yup, still nothing. My Armor Stand NPCs refuse to look at the player, while the player-type NPCs look no problem. I'm pretty sure I had them as Armor Stands last time, because I couldn't make the player NPCs invisible. Is there some way to do this?

On a side note, is there any link from the GitHub pages to the Jenkins builds? I had to use google to get to the dev builds because I couldn't find a direct link from here anywhere.

**Comment by mcmonkey4eva** [comment]
The README.md file links to the Spigot page, which links the development builds and a variety of other relevant resources

**Comment by mcmonkey4eva** [comment]
Tested and confirmed this issue is present (Citizens build 1695).

**Comment by fullwall** [comment]
Fixed
