### ISSUE TITLE
Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1267) (Is it up to date?)

### ISSUE THREAD

**Issue by End3rDNZ** [CitizensDev/Citizens2#1500]
Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1267) (Is it up to date?)

Eso me sale cuando inicio mi servidor con el plugin ese porfavor ayudenme :C

**Comment by mcmonkey4eva** [comment]
Download latest Citizens2: http://ci.citizensnpcs.co/job/Citizens2/
Ensure Spigot is latest: https://www.spigotmc.org/wiki/buildtools/
