### ISSUE TITLE
Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1267) (Is it up to date?) HELP!!!

### ISSUE THREAD

**Issue by End3rDNZ** [CitizensDev/Citizens2#1501]
Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1267) (Is it up to date?)

Eso me sale cuando inicio mi servidor con el plugin ese porfavor ayudenme :C

Download latest Citizens2: http://ci.citizensnpcs.co/job/Citizens2/
Ensure Spigot is latest: https://www.spigotmc.org/wiki/buildtools/

No sirvio tu cosa mcmonkey4eva

**Comment by SXRWahrheit** [comment]
You need to update Spigot and Citizens, like the error says. Opening more issues won't change the answer - it'll just make Monkey angry.

**Comment by mcmonkey4eva** [comment]
Please do not open duplicate issues.

Please just download the updates. Both links are valid and functional.
