### ISSUE TITLE
Translate locale langage dont work

### ISSUE THREAD

**Issue by KuroSenseii** [CitizensDev/Citizens2#1502]
- in the config file i put the fr langage in locale but after reload or reboot server the langage its all time in english. I have trying with fr and fr_FR but dont work

- spigot 1.12.2 and lasted citizens 2 build

**Comment by mcmonkey4eva** [comment]
Do you have an updated fr locale file? The reference one is very old https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/resources/messages_fr.properties
Contains only half the lines found in https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/resources/messages_en.properties

**Comment by KuroSenseii** [comment]
i see maybe its for that. I will take the file messages_en of the last build and I will do the complete translation.

**Comment by KuroSenseii** [comment]
translation:
    locale: fr_FR or fr ?

**Comment by mcmonkey4eva** [comment]
Have you put the language file in `plugins/Citizens/lang/` folder?

**Comment by KuroSenseii** [comment]
yes

**Comment by mcmonkey4eva** [comment]
Can you look in your console logs for any errors? It might have a relevant one

**Comment by KuroSenseii** [comment]
i have look that nothing error if you want to look https://hastebin.com/jidibidiqi.md

**Comment by mcmonkey4eva** [comment]
Oh, I see why.
In `Citizens.java`:
```
        setupTranslator();
        CitizensAPI.setImplementation(this);
        config = new Settings(getDataFolder());
```
The translator is loaded in before the Settings are loaded in, and thus it will always use the default locale.
@fullwall ^ That could definitely benefit from a fix.

**Comment by KuroSenseii** [comment]
thank for find the bug :D

**Comment by fullwall** [comment]
Try latest build
