### ISSUE TITLE
Skins Not Changing

### ISSUE THREAD

**Issue by DeathsValentine** [CitizensDev/Citizens2#1503]
I'm doing /npc skin [username], /npc skin -p, /npc skin [skinname] -p, and /npc create [username], but nothing is working. I've checked console and there are no errors but there is also nothing that seems to be going through to the plugin. This is just a few lines to show that nothing is happening.

27.05 22:08:43 [Server] INFO DeathsValentine issued server command: /npc remove
27.05 22:08:49 [Server] INFO DeathsValentine issued server command: /npc create Stoniasawsome
27.05 22:08:53 [Server] INFO DeathsValentine issued server command: /npc remove

**Comment by DeathsValentine** [comment]
This is what ended up popping up with the debug after I looked through what I could with the other things.

27.05 23:37:32 [Server] INFO Fetched profile a975b181-f7b7-4a8b-a743-8a428e216d58 for player Stoniasawsome
27.05 23:37:32 [Server] INFO Profile lookup for player 'Stoniasawsome' failed2: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService
27.05 23:37:32 [Server] INFO java.lang.ClassCastException: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService
27.05 23:37:32 [Server] INFO at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:290)
27.05 23:37:32 [Server] INFO at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:58)
27.05 23:37:32 [Server] INFO at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81)
27.05 23:37:32 [Server] INFO at com.destroystokyo.paper.profile.WrappedGameProfileRepository$PreProfileLookupCallback.onProfileLookupSucceeded(WrappedGameProfileRepository.java:62)
27.05 23:37:32 [Server] INFO at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63)
27.05 23:37:32 [Server] INFO at com.destroystokyo.paper.profile.WrappedGameProfileRepository.findProfilesByNames(WrappedGameProfileRepository.java:47)
27.05 23:37:32 [Server] INFO at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
27.05 23:37:32 [Server] INFO at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
27.05 23:37:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
27.05 23:37:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
27.05 23:37:32 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
27.05 23:37:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
27.05 23:37:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
27.05 23:37:32 [Server] INFO at java.lang.Thread.run(Thread.java:748)

**Comment by mcmonkey4eva** [comment]
Are you running latest dev build from http://ci.citizensnpcs.co/job/Citizens2/ as I noted earlier?

**Comment by DeathsValentine** [comment]
Yes the plugin.yml says 2.0.22-SNAPSHOT (build 1487)

**Comment by mcmonkey4eva** [comment]
That is very much _not_ the latest dev build from the link given.

**Comment by DeathsValentine** [comment]
Ahh let me redownload

**Comment by DeathsValentine** [comment]
Ah alright thanks I guess I was looking at the wrong build, thanks!
