### ISSUE TITLE
NPC Skin command not loading new skins

### ISSUE THREAD

**Issue by Iyoforeayo** [CitizensDev/Citizens2#1505]
Normally have no issue with the /npc skin <name> (-p) command on our server, but as of about a week or two ago, the command stopped working. When used, the NPC "flickers" like it's about to update the skin, but it just remains the default Alex/Steve. 

Don't see any errors console-side, or anything that might be blocking this from our end. Also seems to only be affecting new NPC skin changes - all skins created/edited on NPCs prior to a week or two ago are still fine (though trying to change their skins now also reverts them to Alex/Steve.) Have also tried reloading Citizens, which did not fix it either. Other NPC commands like /npc skinlayers still work fine - seems to just be /npc skin

Running MC v1.12.2, and Citizens v2.0.22 (Alpha2), on a dedicated server

**Comment by mcmonkey4eva** [comment]
Always run latest Citizens build: http://ci.citizensnpcs.co/job/Citizens2/
Always run latest Spigot build: https://www.spigotmc.org/wiki/buildtools/

That issue may be caused by rate-limiting (Mojang blocking your server's access to the skin servers)

**Comment by Iyoforeayo** [comment]
Ahh, my mistake - it seems we were one snapshot behind on our Citizens version. Updating to the latest seems to have fixed the issue!
