### ISSUE TITLE
[Bug] Incorrect display of name NPC

### ISSUE THREAD

**Issue by AIphaDragon** [CitizensDev/Citizens2#1506]
Version Citizens: 2.0.22 - build #1545
Version Server: Spigot 1.11.2-1.12.2
Describe: Hello. Long time ago noticed such a problem. It consists in the fact that the NPS changes its name by itself. In this case, the name "Распорядитель арены" was changed to "Гладиатор" and after a time such result: https://imgur.com/a/uDtuGLA (save.yml: https://pastebin.com/CgG0kT6m). We tried to change the name of this NPC again to "Гладиатор", after "&6&lГладиатор" and only the color changed: https://imgur.com/a/8vsuzEd. As soon as the name was changed to the original one - "Распорядитель арены", the situation was corrected: https://imgur.com/a/wVkhX3h. What could be the problem? Thanks in advance for your help.

**Comment by mcmonkey4eva** [comment]
The Russian text involvement makes this hard to track... and your English is very hard to understand as well.
I don't actually have any idea what problem you're describing.

**Comment by AIphaDragon** [comment]
Well.
Actaully, the problem was in fact, that after renaming NPC, its name displays incorrectly.
For example, we have NPC with name "Arena master" and then we changed to "Gladiator" and after a while it displays "Arena masGladiator". Although, in config files it is written correctly - "Gladiator". So, we would say, that after renaming NPC, it remains its old name mixed with new name

**Comment by mcmonkey4eva** [comment]
Possible related to #883 ?
Names longer than 16 characters don't always work fully correctly, especially with the `rename` command

**Comment by AIphaDragon** [comment]
Thank you, we will know
