### ISSUE TITLE
The command /npc name isn't working properly 

### ISSUE THREAD

**Issue by LazyDkk** [CitizensDev/Citizens2#1507]
So okay, when I was first setting up some NPCs for my server, I used the /npc name command to make the NPCs names invisible and everything worked fine at first, but then later when I returned to the server, the names were visible again. I tried using the command but now it didn't hide the name tags anymore. I've tried to check logs and console but was unable to find anything. 

I tried to mess a bit around with the NPCs in the save.yml file and if I changed it to "false" and restarted to reload the config, it was set back to true. And yes, I had saved.

I really have no idea what could cause this so all help is welcomed.

- LazyDk

**Comment by mcmonkey4eva** [comment]
Make sure you're running the latest version of Citizens from http://ci.citizensnpcs.co/job/Citizens2/
Previous versions had a bug with that

**Comment by LazyDkk** [comment]
Hmm I think I'm running Citizens 1 and not 2 so that might be the problem?

**Comment by LazyDkk** [comment]
But they are named the completely same thing? And how is it an old build when it labeles "working in 12) and came out in 2017?

**Comment by mcmonkey4eva** [comment]
Because the latest build came out in May 2018.

**Comment by LazyDkk** [comment]
Hmm yea okay. I'll give it a try, thanks.

**Comment by LazyDkk** [comment]
@mcmonkey4eva It's still not working. I've tried restarting to load in the plugin, tried creating a whole new NPC and stuff, but it's still not working.

**Comment by mcmonkey4eva** [comment]
Can you post a pastebin link to a clean server log (from initial startup to where you join and create an npc + use name command + `/citizens save`) and a pastebin of saves.yml (copied out *after* running the save command for the log)

**Comment by LazyDkk** [comment]
Well. There's nothing in the server log. No errors or anything and I've tried creating a new NPC and hide it's name but I'll try to use /citizens save

**Comment by mcmonkey4eva** [comment]
I'm not looking for errors I'm looking for general output, thus the request for a full log

**Comment by LazyDkk** [comment]
Tbh, I'm not sure if I can give out the console log. Or all the NPCs in the saves.yml file. But I can give you the part with the NPC I've been trying to fix?

**Comment by LazyDkk** [comment]
https://pastebin.com/csFvz43f

**Comment by LazyDkk** [comment]
But you could just tell me what you would be looking for in the log and I can tell you if I find it?

**Comment by mcmonkey4eva** [comment]
Why can't you give out the server log?
If any private data is included in it (Which shouldn't happen in the first place), censor it before posting

**Comment by LazyDkk** [comment]
But then I would still need to know what you're looking for so I don't censor it?

**Comment by LazyDkk** [comment]
Is it the loading part? Or when I create the NPC or what is it?

**Comment by mcmonkey4eva** [comment]
Don't censor data that isn't private.
Most data in a log isn't.

**Comment by LazyDkk** [comment]
Can't you just tell me what you're looking for because I'm not sure how I would even censor it? Is it where I create the NPC, remove the name and use /save??

**Comment by mcmonkey4eva** [comment]
Post a server log.
If you have any specifically private output in it, censor it (delete the private information from the post)

**Comment by LazyDkk** [comment]
Why is it so hard to say what you need?

**Comment by mcmonkey4eva** [comment]
Why is it so hard to post a server log?

**Comment by LazyDkk** [comment]
I asked first. I'll answer if you asnwer.

**Comment by LazyDkk** [comment]
... FIne. https://pastebin.com/viqLsb6k

**Comment by mcmonkey4eva** [comment]
Right off the bat, you're running a very outdated version of Spigot - update (see https://www.spigotmc.org/wiki/buildtools/ for info on how)
You also have an error with `InventoryLock.jar` entirely failing to load - you might want to remove that (it's erroring because it is compatible with Java 9 and up, and your server is running Java 8).
Also an error in Essentials loading - caused by the outdated Spigot version.

**Comment by LazyDkk** [comment]
Yea I know InventoryLock isn't working but I'm not gonna remove it yet. But should it work even tho I'm not running the latest version of spigot?

**Comment by LazyDkk** [comment]
But how would I use the BuildTool thing when It's not a local host server?

**Comment by LazyDkk** [comment]
Or do I just need to download the latest version of spigot?

**Comment by mcmonkey4eva** [comment]
Fix all visibly outstanding issues (load time errors, old versions, etc) before claiming issues please - often times such things cascade into accidentally creating an issue that isn't otherwise present.

If it continues not working after fixing both issues (broken plugins present, older Spigot jar), you may want to look at making a temporary second server containing only latest Spigot and Citizens build to see if the issue is present there - if it isn't, copy plugins from the real server over to the temporary server to see if the issue appears. Some plugins cause issues like this. A prime suspect here is anything related to scoreboard and/or entity control logic.

BuildTools is the only valid way to acquire an updated copy of Spigot. After you have it from BuildTools, you can push the file to your server.

**Comment by mcmonkey4eva** [comment]
No.
You follow the instructions on the BuildTools page to get a valid up to date Spigot jar.

**Comment by LazyDkk** [comment]
But what if I want to run 1.8? Then it would just automatically update to 1.12?

**Comment by mcmonkey4eva** [comment]
You're not running 1.8, you're running 1.12. You're running an older version of 1.12 though, and you should update that.

**Comment by LazyDkk** [comment]
I know I'm running 1.12... but I'm giving an example

**Comment by LazyDkk** [comment]
So what? I need to go to https://getbukkit.org/download/spigot and download the latest 1.12 version??

**Comment by mcmonkey4eva** [comment]
No, go to https://www.spigotmc.org/wiki/buildtools/ and follow the instructions to obtain an updated jar.

The link you posted (now removed) directs to an illegal website. Do not use that. (Per Minecraft EULA and Bukkit DMCA, it is illegal to post direct public links to any file directly containing the Minecraft code, excluding links posted by Mojang themself).

**Comment by LazyDkk** [comment]
Why is it illegal? It's the website I use if I need to download the spigot build for either coding purposes or to make a localhost server. How is it an illegal website?

**Comment by mcmonkey4eva** [comment]
As I wrote in my post:
`Per Minecraft EULA and Bukkit DMCA, it is illegal to post direct public links to any file directly containing the Minecraft code, excluding links posted by Mojang themself.`

**Comment by LazyDkk** [comment]
Then how would I get an older version of spigot or bukkit?

**Comment by MusicScore** [comment]
Using the `--rev <version>` argument, as specified by the Spigot BuildTools page.

**Comment by mcmonkey4eva** [comment]
^ rev argument as mentioned, and is described on the BuildTools page.
Also: Don't run an old version, ever.

**Comment by LazyDkk** [comment]
Hmm yea okay

**Comment by LazyDkk** [comment]
Why not? Btw, this would still only let me run the version on the server. What if I wanted to download spigot 1.10 for coding purpose?

**Comment by Xenmai** [comment]
As they said, the Spigot BuildTools Wiki Page explains how to get outdated versions, even though you should use an updated one.

**Comment by LazyDkk** [comment]
But wait... how can I use the BuildTool when my server is running through a host? I can't just make them install Git on their hosting pc? And it says on the build tool page that git is required.

**Comment by mcmonkey4eva** [comment]
There's no coding purpose to download 1.10
Write code for latest, run latest...

**Comment by MusicScore** [comment]
You can build the JAR on your own machine, and then give the host the JAR you compiled.

**Comment by LazyDkk** [comment]
When you code, you need to import a spigot or bukkit version (.jar file) to code with the features. And to get back to my original problem, how would I use the build tool? Because it says on the spigot page that the computer, running the server would need Git, installed. But my server is running through a host so how would I make them install Git?

**Comment by MusicScore** [comment]
Running the server itself does *not* require Git. Only building the JAR does.

**Comment by LazyDkk** [comment]
Well why does it then say so on the spigot website?

**Comment by LazyDkk** [comment]
"Prerequisites(top)
There are two applications necessary to use BuildTools: Git and Java."

**Comment by MusicScore** [comment]
You need Git to run BuildTools to build a Spigot JAR. A fully built Spigot JAR does not need Git to run.

**Comment by LazyDkk** [comment]
So okay, I make the BuildTools.bat file in the main folder? And what then? Do I just restart the server?

**Comment by MusicScore** [comment]
Did you read the Spigot page at all? It tells you quite clearly how to build a server JAR that you can just use, without all of this unnecessary folder management.

**Comment by LazyDkk** [comment]
Of course, I read it. Don't tell me I didn't. I'm just having troubles and asking questions

**Comment by LazyDkk** [comment]
So do I restart after I've created the file that it tells me to on the spigot website?

**Comment by MusicScore** [comment]
You upload the JAR you create to the host, do what the host says if they have a special way of handling user-uploaded JAR files, and then restart the server.

**Comment by LazyDkk** [comment]
Okay it's telling me on the spigot website that I would need to run some commands in terminal etc so I have no idea on how I would do this

**Comment by LazyDkk** [comment]
Ohh so I need to run it on *my* pc to get the lated version and then upload that version?

**Comment by MusicScore** [comment]
Yes.

**Comment by LazyDkk** [comment]
Just as I suspected. I've got the latest build version, updated everything and removed everything that caused any errors and the /npc name command is still not hiding the NPCs

**Comment by mcmonkey4eva** [comment]
As I wrote earlier:
`Fix all visibly outstanding issues (load time errors, old versions, etc) before claiming issues please - often times such things cascade into accidentally creating an issue that isn't otherwise present.

If it continues not working after fixing both issues (broken plugins present, older Spigot jar), you may want to look at making a temporary second server containing only latest Spigot and Citizens build to see if the issue is present there - if it isn't, copy plugins from the real server over to the temporary server to see if the issue appears. Some plugins cause issues like this. A prime suspect here is anything related to scoreboard and/or entity control logic.`

**Comment by LazyDkk** [comment]
Hmm how about NameTagEdit? Or FeatherBoard? I recently installed featherboard and I think the problem appeared not to long after that?

**Comment by mcmonkey4eva** [comment]
It could be either of those.
Do the testing I said to do.

**Comment by LazyDkk** [comment]
I'll do tomorrow. It's getting late. Thanks tho.

**Comment by LazyDkk** [comment]
Okay so it's pretty much as I expected. It's FeatherBoard that's causing the problem. But does anyone know how I would fix it? Removing FeatherBoard is off the table btw.
