### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by Castiella** [CitizensDev/Citizens2#1508]
<!-- 
Please include:

TIMINGS: https://timings.aikar.co/?id=97b59ee790e147d49c798691138b7c9a

- A detailed description of your issue or feature request

Citizens is flaring up a lot on my timings report, we only have 1 NPC - just wondering whats going on to cause this?

I know you said dont post Aikar timings but im not sure how to get the warmrroast one? please can you advise - sorry

**Comment by mcmonkey4eva** [comment]
Empty post?
Please accept my emptiest of responses.
