### ISSUE TITLE
Dancing Parrots

### ISSUE THREAD

**Issue by SirGoldman-git** [CitizensDev/Citizens2#1512]
Could you add a command that will make parrots dance all night long? :)

**Comment by mcmonkey4eva** [comment]
What.

**Comment by SirGoldman-git** [comment]
https://gyazo.com/a0f2c19382c4656d782938276bc128c7

**Comment by SirGoldman-git** [comment]
Just a command that will set a parrot to dance mode is all.

**Comment by mcmonkey4eva** [comment]
Ah you're asking for a command to enable a parrot animation that Minecraft has, I see

**Comment by SirGoldman-git** [comment]
Yes sir! :)

**Comment by Serializator** [comment]
According to a comment from 2008Choco, the dance animation is triggered client-side when there is a jukebox playing music nearby.

https://www.spigotmc.org/threads/nms-parrot-dance-server-side-or-client-side.254740/#post-2533890

Assuming that that is correct, if this was to be implemented it would require client-side block manipulation and that might not be something that Citizens2 should be doing.

Another problem would be the impossibility to specifically choose what parrot should be dancing to the music from the jukebox.

_As I said, everything I said is based on the assumption that the comment from 2008Choco is correct._

**Comment by mcmonkey4eva** [comment]
That ^ appears to be correct, that it's triggered entirely clientside :(

If you/anybody finds a way to safely trick it into working anyway, or a future Minecraft update enables this to be started serverside, please do reply below or open a new issue!
