### ISSUE TITLE
Can't create NPC

### ISSUE THREAD

**Issue by Jaffaaaa** [CitizensDev/Citizens2#1514]
When I do /NPC create <name> it comes up with: "Do you mean /npc rotate?"
Nothing comes up in console or logs when I do this and my citizens config is the default.

Server Version: Spigot 1.8.8-Snapshot (with ViaVersion)
Citizens Version: citizens-2.0.22-SNAPSHOT

Here's a gif of the problem: https://gyazo.com/5cf0251fa35485e2299cad6d418e1745

**Comment by mcmonkey4eva** [comment]
Update your server. https://www.spigotmc.org/wiki/buildtools/
1.8.8 is many years outdated, and cannot be supported.

You can use tools like ViaBackwards to run older clients on modern servers.
