### ISSUE TITLE
It is possible that the problems with Citizens

### ISSUE THREAD

**Issue by AIphaDragon** [CitizensDev/Citizens2#1515]
Version Citizens: build #1547
Version server: spigot 1.12.2
WG report: https://pastebin.com/7RAGt394
Spark profiler: https://sparkprofiler.github.io/?C3NpeUz4ZV
Timings (Aikar): https://timings.spigotmc.org/?url=wegibajase
Timings (Aikar): https://timings.spigotmc.org/?url=hubiyinate
Description: 
There are suspicions that the plugin provokes subversion after 14-15 hours of server operation. Could you look with your professional eye? Maybe we are wrong. Thanks in advance for your help.

**Comment by mcmonkey4eva** [comment]
`AdvancedMobArena` and world saving both seem to be weirdly time-consuming there.
Citizens doesn't look to be taking all that much time at all.
RAM usage is concerningly high - though it's hard to tell why from the information posted there. No particular reason to link that to Citizens though.

**Comment by AIphaDragon** [comment]
Thank you. You were right. Sorry for the trouble.
