### ISSUE TITLE
Citizens Clientside despawning

### ISSUE THREAD

**Issue by GGNoPotato** [CitizensDev/Citizens2#1516]
All NPCs will despawn after 'X' seconds - usually within 5 minutes. Leaving the server and rejoining fixes it. This is a client side bug as I had some people on 1.7 & 1.8 stop seeing the NPCs. 

For a temporary fix I made a plugin that executes /citizens save + /citizens reload every 30 seconds.

Doing this though prevents me from having any NPCs that will move and only allow me to use stationary NPCs.

I have searched for weeks on a solution and have not found anything yet so I decided to open a ticket here. Hope this can get resolved asap..

There are no error logs for Citizens, and TPS is 20 avg

I am using newest version of citizens on the dev build.

Also they despawn when the player 'respawns' or teleports. I noticed this by spawning back in and looking at the NPC's they end  up falling through the ground and keep falling into void.

**Comment by mcmonkey4eva** [comment]
Can you please post the output of each of these 3 commands:
- `/version`
- `/version citizens`
- `/plugins`

**Comment by GGNoPotato** [comment]
Server Version: https://i.imgur.com/Y03Cnmr.png
Citizens Version: 2.0.22 (Build 1545)
Plugins: https://i.imgur.com/1gspMpJ.png
https://i.imgur.com/3ZtpZdR.png

**Comment by mcmonkey4eva** [comment]
Server is heavily outdated and unsupportable (4ish years old!).
Server is running an unsupportable fork as well.

Please run latest Spigot 1.12.2 acquired from https://www.spigotmc.org/wiki/buildtools/
You can use plugins like ViaBackwards to support older clients, as well as PvP backdate plugins if you prefer the older style PvP.
There is not any valid reason to run a 1.8.8 server

**Comment by GGNoPotato** [comment]
I have just now migrated my server to 1.12.2 and the issue still happens...

https://i.imgur.com/aX9k310.png

Same plugin list and most up to date citizens.

**Comment by SXRWahrheit** [comment]
Please run Spigot rather than Paper.

**Comment by mergu** [comment]
Thanks for updating to 1.12.2. Join us on discord for more assistance: https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
If you have any entity controlling plugins, lag clearing plugins, or anything of that nature, those would be first suspects as causing disappearance issues.

**Comment by GGNoPotato** [comment]
Yes I have removed any plugins causing lag clearing, or chunk control and it still occurs.
