### ISSUE TITLE
NPC color coded names change the end bracket in chat

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1517]
When an NPC has a color coded name that has a color as the last letter it make the end bracket color coded too

eg: &cJacko Meant to be (Jacko) in chat when NPC talks

but actually shows as

(Jacko) <= Notice the color coded end bracket. 

Also /npc path command doesn't always turn off properly,  **I have to use that because "exit" doesn't seem to work.**

Spigot version - This server is running Paper version git-Paper-1458 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Citizens version - 2.0.22-SNAPSHOT (build 1547)

**Comment by axemwa** [comment]
Sorry I didn't realise I couldn't use color in the example I put, heres what it's meant to look like (the post above) 

![image](https://user-images.githubusercontent.com/37608633/41550989-9890c64e-7369-11e8-9281-0272de8c023a.png)

**Comment by mcmonkey4eva** [comment]
Consider using Denizen https://www.spigotmc.org/resources/denizen.21039/ for NPC chatting setup instead, as it's much more capable and customizable.

What exactly is wrong with disabling `/npc path`? Is there an error occurring, or...?

**Comment by axemwa** [comment]
Ok will do and with /npc path it leaves ender eyes on the ground even after using toggle path and I can't remove them, ps it was in a would guard region

**Comment by mcmonkey4eva** [comment]
If you can replicate that issue (path debug not going away) without other plugins in the way (as WG might be causing the issue) please open a new issue post description that specific issue in as much detail as possible
