### ISSUE TITLE
The plugin is telling me that my players do not have permission to see the npc text, but nowhere is there an option for this permission to be changed

### ISSUE THREAD

**Issue by TCGCole** [CitizensDev/Citizens2#1518]
Please help?

I am using Bukkit and Citiens 2 (According to the photo used on the plugin) and this issue has started since I got the Plugin about a month and a half ago. I am running 1.12.2

**Comment by SXRWahrheit** [comment]
Please provide your Citizens and server versions, as well as a server log from startup to when the error occurs (with any sensitive data omitted).

**Comment by mcmonkey4eva** [comment]
Give permission `citizens.npc.talk` to any players that should receive the text.
(Using any permissions plugin for Spigot)
Also, consider using Denizen https://www.spigotmc.org/resources/denizen.21039/ for more powerful NPC chatter

**Comment by TCGCole** [comment]
How do I give them the permission though

**Comment by SXRWahrheit** [comment]
With a permissions plugin.

**Comment by TCGCole** [comment]
Ok so I have a permission Plugin (PermissionsEx) what Do I do now

**Comment by mcmonkey4eva** [comment]
Use any permissions plugin. It's a very basic part of a Spigot server. If you don't know what that is, don't run a server.

**Comment by mcmonkey4eva** [comment]
This is not your personal basic server guide channel. This is a place to post Citizens related issues.
