### ISSUE TITLE
Dependency 'org.bukkit:craftbukkit:1.12.1-R0.1-SNAPSHOT' not found

### ISSUE THREAD

**Issue by IgnatBeresnev** [CitizensDev/Citizens2#1519]
It's not under https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/bukkit/ either.

Any help with this one? I've been trying to solve it through local repo / direct file paths, but unsuccessful thus far.

**Comment by IgnatBeresnev** [comment]
> you should absolutely not be trying to touch the Citizens2 source code. 

Don't be a snob, it's not rocket science. With the help of BuildTools, it's all fine and dandy now.

As for why I'm trying to build it locally, I'm sorry that someone doesn't respect OOP, which may lead to ClassNotFoundError, and I want to fix it. It should really be `BaseMinecraftSessionService`, but oh well, I guess I shouldn't be doing this anyway.
https://github.com/CitizensDev/Citizens2/blob/772ab5fb7baa61a10941abcf2e1b6f3acbaaaab4/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/util/NMSImpl.java#L297

Thanks for the BuildTools tip though. and please don't look down on people, try to be more helpful instead.

**Comment by mcmonkey4eva** [comment]
I'm not being a snob with that comment, @IgnatBeresnev 
If you do not know where/how CraftBukkit dependencies are acquired, then you do not have experience with NMS work (They are required for any NMS work).
If you do not have experience with NMS work, your first entry should not be altering a messy+complicated large project like Citizens. (It should instead be practice projects).
