### ISSUE TITLE
Mob spawning issue caused by citizens? Verified through trail and error

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1520]
Ever since I added this version of Citizens mobs are spawning like crazy both animals and monsters in a short radius from players 200-600 mobs it's crazy. I have verified that this is the Citizens plugin through trail and error by deleting plugins onew by one eventually removing the citizens plugin the mobs stopped spawning like crazy. Is this something I have setup wrong in ocnfig or is this something to do with one of the recent update releases?

Latest log:
https://pastebin.com/3ixkAbXL

Citizens Config: 
https://pastebin.com/uEEXhVx1

Spigot + MC version: 

[23:49:19 INFO]: This server is running Paper version git-Paper-1467 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

![image](https://user-images.githubusercontent.com/37608633/41782144-947bd816-7678-11e8-9e6c-b14359e974a0.png)

![image](https://user-images.githubusercontent.com/37608633/41778462-0085b2bc-766e-11e8-9024-8313fcd52ed8.png)

**Comment by SXRWahrheit** [comment]
Please run a test server with only Citizens installed and report back if the issue persists. Additionally, check your server configuration settings for monster limits.

**Comment by axemwa** [comment]
Ok will do already tested monster limits and radius on default nothings changed on that end

**Comment by axemwa** [comment]
Looks like citizens must be conflicting with another plugin and causing the issue somehow cause when I remove all the other plugins and leave citizens on the mobs arent going crazy anymore

**Comment by SXRWahrheit** [comment]
:open_mouth:

**Comment by axemwa** [comment]
Deleting my config and saves ymls in citizens folder seems to have fixed it I'll send you a copy of the files that were causing the issue , not sure what was causing the siiue I may have entered something wrong in config? 

Saves.yml:

https://pastebin.com/zgeUyPrY

config.yml:

https://pastebin.com/aLs0RVSs

Also this is just a theory but would it be possible that monsters could be confusing players for npcs that have targetable switched on and has the same name as a player so when the player explores an area mobs spawn differently if that makes sense?

**Comment by mcmonkey4eva** [comment]
Your config contained:
```

  player:
    remove-from-list: false
```
The default and recommended value for this is `true`.

Turning it to `false` as you did does risk causing effects like what you see.

**Comment by axemwa** [comment]
Thankyou! :D

**Comment by aikar** [comment]
@mcmonkey4eva mind explaining what that config does that could relate to entity spawn rates?

**Comment by mcmonkey4eva** [comment]
@aikar it (when set to `true`) makes Player NPCs appear to most internal systems as just being Players... Minecraft, of course, arbitrarily scales difficulty based on the player count - and thus, having a lot of player NPCs while that setting is on means minecraft might scale difficulty based on there being a lot of players (far more than might actually be online). And thus... more entities spawned than otherwise would be happening.

**Comment by aikar** [comment]
@mcmonkey4eva, oh, that makes sense.

May I suggest an improvement if you detect the user is using Paper 1.12+, to implement a Listener for PlayerNaturallySpawnCreaturesEvent, and skip NPC's with this event.

Then they will not be considered for spawning / affect the cap.

**Comment by mcmonkey4eva** [comment]
@aikar that setting should not have been turned off in the first place, and anyone who turns it off intentionally should expect to see results like what happened here. This issue won't happen when the setting is left on (as is default).
I have no idea why the issue poster here turned it off.

(Side note: I accidentally wrote 'true' instead of 'false' in my prior post, and have edited the post to fix that)

**Comment by aikar** [comment]
@mcmonkey4eva I agree, But I assume you added this option for SOME reason? I was making a suggestion that for whatever that reason is, at least you could make it not have this entity spawn issue for Paper users (Spigot does not have an event for this part of the spawn process)

**Comment by axemwa** [comment]
@mcmonkey4eva as I said before in the previous post 

"Definately fixed it. **I just assumed player remove from list was meant to hide npc player names from the tab list for all npcs, I was testing it and must have forgotten I left it set to false."

My bad I won't do it again, might be worth removing it from future releases (if it causes issues no point having it there right?), or what @aikar suggested or at least put a warning above the option in the config for future releases so other people don't run into the same issue, cause some people love to test out a plugins capabilities especially if it's a good one like this.

**Comment by SXRWahrheit** [comment]
It's there for people who want that behavior.

If you have something that you want an NPC to do or a way you want them to behave that is non-standard, you can always write a trait and give it individual NPCs at your leisure.

**Comment by axemwa** [comment]
Fair enough my main point I was to make sure new users of this plugin are aware that this feature can cause issues for some people, its just a small comment in the config that needs to be added in config I reckon that will help out future users of the plugin a lot

**Comment by SXRWahrheit** [comment]
That's why it's true by default.

**Comment by axemwa** [comment]
That's irrelevant it won't stop people from changing it

**Comment by SXRWahrheit** [comment]
Correct! And then they, like you, can change it back.

This issue is closed. Please create a feature request issue if you would like to request a change.

**Comment by axemwa** [comment]
I knew that all I was suggesting is to make people aware of it before hand by adding a comment in the config to save all the trouble but obviously you don't have to it was just a suggestion nothing more I'm not too fussed whether you do it or not it was just for other peoples sakes.

**Comment by mcmonkey4eva** [comment]
If you don't know exactly what a config option does, don't touch it.

**Comment by axemwa** [comment]
Thats not the point I'm trying to make but ok...

**Comment by ryantheleach** [comment]
@axemwa An explicit example of someone wanting this behavior, is if a plugin used Citizens to replace players when combat logging.

You want the NPC to act like a player for all purposes.

**Comment by axemwa** [comment]
@ryantheleach I do use combattagplus which uses citizens to stop combat logging but having this option
'  player:
    remove-from-list: false'
on with this plugin (combattageplus) still causes the mobs to spawn at count levels of 700+.

So even if the purpose of that option was for that reason it sitll causes the mob spawning issue.

**Comment by mcmonkey4eva** [comment]
That plugin (or any other plugin) should not be asking you to alter the Citizens config like that.
The player list option can be set on a per-NPC basis, which that plugin can use (instead of changing the value for **all** npcs, as the config option does).

**Comment by mcmonkey4eva** [comment]
Anyway, this issue post is getting too long, summary point:

For the Citizens config, and any other delicate config file, absolutely do not ever alter any config values unless you know exactly what the alteration does.

There's not going to be a warning on config options about side effects... if you don't know exactly what the side effects of a config option are, you should not be touching it in the first place.
