### ISSUE TITLE
How to freeze NPC? Players moved NPC with fishing rods.

### ISSUE THREAD

**Issue by ItsTauTvyDas** [CitizensDev/Citizens2#1526]
Hello, How to freeze NPC? Players moved NPC with fishing rods.. How do I disable it? Or freeze NPC? Is there any freeze command (Feature Request)? Something in config? So many questions?

Server version: 1.11.2
Citizens version: 2.0.22-SNAPSHOT (build 1486)

**Comment by mcmonkey4eva** [comment]
You're running a version of Citizens that is a solid year out of date.
Update: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
Also update your server to 1.12.2 latest of course
