### ISSUE TITLE
Right click to text

### ISSUE THREAD

**Issue by nickswizle** [CitizensDev/Citizens2#1528]
how do you configure a npc to say the text when you right click? right now it only works if I enable the close option

**Comment by BloodEko** [comment]
The chat engine is a bit oudated. You might consider using denizen.
Install the denizen.jar , then restart server, then place a myNpc.yml with this content in denizen/scripts/

```
myNpc:
  type: assignment
  actions:
    on click:
    - chatt "Hello <player.name>!"
```

With `/npc assignment --set myNPC` you set the script.

**Comment by nickswizle** [comment]
I'll try it out thanks for the quick reply.
