### ISSUE TITLE
NPCs not talking when players get close

### ISSUE THREAD

**Issue by DeathsValentine** [CitizensDev/Citizens2#1529]
NPCs aren't talking to players when they get close to them even though they have the citizens.npc.talk permission set, They're talking to me just fine because I'm opped however so I'm not sure what the problem is. I tried downloading the latest version and setting talk-close as default true in the config files but that didn't work either.
![2018-07-05_10 05 45](https://user-images.githubusercontent.com/39684769/42337252-059e37ca-803b-11e8-8e43-693f24c5c5a9.png)

**Comment by mcmonkey4eva** [comment]
You might want to use Denizen ( https://www.spigotmc.org/resources/denizen.21039/ ) for Citizens NPC chatter control, as it adds more powerful controls to that.

**Comment by DeathsValentine** [comment]
Alright is there no way to fix this with just citizens?

**Comment by BloodEko** [comment]
You might look at my post here: https://github.com/CitizensDev/Citizens2/issues/1528

replace `on click` with `on enter proximity`
You can change the radius with this command, when look at the npc: `/ex trigger name:proximity state:true radius:5 npc:<pl.target>`

**Comment by DeathsValentine** [comment]
Ohh alright thanks! Apparently it is working just not for that one player and I'm not sure why
