### ISSUE TITLE
I can't move/delete the .jar file

### ISSUE THREAD

**Issue by Minutemini46** [CitizensDev/Citizens2#1530]
I downloaded the .jar file on: https://dev.bukkit.org/projects/citizens and when I tried to move the citizens plugin to my plugins folder for my server, It would not move the file. Then I tried to delete the file, but it would not delete it and now it is stuck on my computer. I was wondering if there was a way to move it or at least delete it. Thanks!

**Comment by mcmonkey4eva** [comment]
That sounds like you have an issue with basic computer operation, not Citizens. Contact the nearest available IT Department.
