### ISSUE TITLE
NPCs invisible in a certain world

### ISSUE THREAD

**Issue by Mowstyl** [CitizensDev/Citizens2#1531]
The server is running Paper version git-Paper-1488 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Citizens version 2.0.22-SNAPSHOT (build 1552)

I'm having problems with all the NPCs type player. They become invisible when in a certain the end world (not the main end).
I'm not attaching the logs because nothing is printed into the console when putting an npc in that world apart from the command used. It only happens with player characters and in a certain world.
Do I need to configure something special to allow skins in a certain world? It used to work until the last update.

**Comment by Mowstyl** [comment]
The plugin I use to manage worlds is Multiverse-Core

**Comment by mcmonkey4eva** [comment]
Can you pastebin your saves file? And name the specific world involved? And also pastebin a full server log file?

**Comment by Mowstyl** [comment]
Ok, after some testing I've discovered it only happens in a certain region of the world. I'll upload the log and the saves in a moment.

**Comment by Mowstyl** [comment]
It happens in all end worlds when outside the main island.

**Comment by Mowstyl** [comment]
The error happens when going far from the main island of the end world called Herobrine (i can upload it if you want) in all PaperSpigot (not spigot) versions after PaperSpigot-1.12.2-b1482 (included).

**Comment by Mowstyl** [comment]
I found what causes the error.
The error happens when going far from the main island of the end (i can upload it if you want) in all PaperSpigot (not spigot) versions after PaperSpigot-1.12.2-b1482 (included).
It happens if "keepSpawnInMemory" option from Multiverse-Core is set to false in that world and the NPCs are far from the spawn point.
I haven't tried to reproduce it in other worlds, and I've not tried to measure the distance needed to reproduce it. It happens to me at X28999800 Y139 Z28999573.
I hope this serves you. Thanks for your quick answer, good luck.

**Comment by mcmonkey4eva** [comment]
If it's only on an unofficial server fork with an unrelated plugin with a specific setting...
That's outside anything we can or need to deal with.
Disable the setting that caused it, or switch to an official server distribution...
