### ISSUE TITLE
(look not working) Npcs are freezing / stop having animations

### ISSUE THREAD

**Issue by sdkrocks** [CitizensDev/Citizens2#1532]
Hi,
I have an issue with the citizens NPCs where they stop working. Using npc look, after a short amount of time all npc's loose their animations and no longer stare at the player, they just stand in place. Citizens reload doesn't fix it, but a server restart does. This happens within 5 minutes of the server being up every time.   (no errors in console)

It also seems like they completly freeze, as trying to update them, (/npc name) or someting else has no effect until server restart.

config: https://pastebin.com/Pc0swcFA
(MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Citizens version 2.0.22-SNAPSHOT (build 1552)

Thanks!

**Comment by mcmonkey4eva** [comment]
Likely a conflict with another plugin - perhaps one that alters NPCs is accidentally disrupting Citizens' ability to control the entities of the NPCs.

**Comment by sdkrocks** [comment]
Thanks for the fast reply! 
I don't think it is another plugin, the only other one that I could see that would affect it is CitizensCmd - but this issue was happening before I added it. Ill try removing some anyway to see if it persists.

Here's my plugin list, let me know if one catches you eye that could be causing it:

AsyncWorldEditInjector, CoreProtect, LuckPerms, JoinCommands, ClearChat, PlaceholderAPI, PerWorldPlugins, ProtocolLib, AsyncWorldEdit, Frozen, Vault, ChatManager, VoidTP, WorldEdit, Essentials, ChangeSkin, SurvivalGames, PerWorldInventory, PlotSquared, Multiverse-Core, WorldGuard, SuperLobby, Citizens, ChestCommands, EssentialsChat, Multiverse-Portals, PyrCore, CustomCommands, HolographicDisplays, CitizensCMD

**Comment by mcmonkey4eva** [comment]
`ChangeSkin` probably screws with player-type entities, anything interacting with `ProtocolLib` is automatically suspicious, anything with `Async` in the name is probably dangerous, ...

**Comment by mcmonkey4eva** [comment]
Things that interact explicitly with Citizens are _less_ suspicious - they probably test with Citizens and make sure nothing goes wrong. Things that interact with Citizens _unintentionally_ (anything that touches entities/protocol data/etc) are much more suspicious as they can cause breakage with Citizens and not know it when they're working (as they don't explicitly test with Citizens loaded in)

**Comment by sdkrocks** [comment]
Thanks for your help - I went through each plugin until I found the culprit, waiting 5 minutes every time for the bug to happen.

Oddly enough it was ChatManager. It causes all NPCs to stop working after exactly 5 minutes.

Thanks!
