### ISSUE TITLE
Skins on npcs

### ISSUE THREAD

**Issue by mclegendary1** [CitizensDev/Citizens2#1533]
Hello, can you make NPC's take a skin from online players?

**Comment by mcmonkey4eva** [comment]
Yes. `/npc skin` command https://wiki.citizensnpcs.co/Skins

**Comment by mclegendary1** [comment]
But i have my launcher, so... it's don't take my skin, but from mojang(it's a little problem, but with plugins like idisguise i don't have that promblem).

**Comment by mcmonkey4eva** [comment]
Citizens specifically works with legal online mode minecraft, not cracked servers or heavily modded servers (mods of the form that require modding clients as well).

**Comment by mclegendary1** [comment]
:(
Okay
