### ISSUE TITLE
Is there a way for the skin to stay?

### ISSUE THREAD

**Issue by smoothsheev** [CitizensDev/Citizens2#1537]
Hi, I wanted to use skinned NPCs to decorate and liven up my server, and I was using it successfully by doing /npc skin (name) and then changing my skin and repeating.  The problem is that I wanted all the NPCs to retain the same skin that I set them too, but they keep on all updating to my latest skin. is there a way to stop this?

**Comment by mergu** [comment]
Make sure you're running latest spigot and latest citizens. NPCs should already retain their skin. Post your versions and build numbers

**Comment by mcmonkey4eva** [comment]
Run latest dev builds as mentioned: http://ci.citizensnpcs.co/job/Citizens2/
Check skin wiki page: https://wiki.citizensnpcs.co/Skins

If you have further issues, please post full details, including the outputs of `/version` and `/version citizens`
