### ISSUE TITLE
Sitting Glitch on reload/restart

### ISSUE THREAD

**Issue by DangerAngel97** [CitizensDev/Citizens2#1539]
The output of command `/version` on my server is: his server is running CraftBukkit version git-Spigot-642f6d2-6103339 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.22-SNAPSHOT (build 1541)  Website: http://www.citizensnpcs.co Authors: aPunch and fullwall

If you have an NPC sit it works fine. But, if you reload the plugin or restart the server then they glitch out and get lower into the ground. And if it's a 1 block thick floor they even glitch right through.

**Comment by mcmonkey4eva** [comment]
Try latest build on http://ci.citizensnpcs.co/job/Citizens2/
This issue may have been fixed recently

**Comment by DangerAngel97** [comment]
I already tried the latest build. The issue was a lot worse.

**Comment by mcmonkey4eva** [comment]
Much delayed but it's been actually fixed and verified more recently - run latest builds of Citizens via http://ci.citizensnpcs.co/job/Citizens2/ and latest dev builds of Denizen via http://ci.citizensnpcs.co/job/Denizen_Developmental/
