### ISSUE TITLE
NPC with minecraft skin not rotating properly

### ISSUE THREAD

**Issue by Apyrax** [CitizensDev/Citizens2#1540]
The output of command `/version` on my server is: this server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.22-SNAPSHOT (build 1540)

https://gyazo.com/d46746084fbc6e528d7627406f10346d

The npc will only face one direction and any rotation, it'll still snap its head to one direction 

It's only when I use a normal minecraft skin but it works fine with villagers.

**Comment by fullwall** [comment]
Try latest build

**Comment by mcmonkey4eva** [comment]
From dev builds at http://ci.citizensnpcs.co/job/Citizens2/ specifically, not Spigot/Bukkit.
