### ISSUE TITLE
How do I extract cached skins into .png format?

### ISSUE THREAD

**Issue by midnjerry** [CitizensDev/Citizens2#1542]
I'm a new dev working on another server - a quest type of server with Citizens2 NPCs.  I need to access the NPC skins for 3D rendering but I don't know how to extract the images from the cache.  How can I do this?

player-skin-textures: eyJ0aW1lc3RhbXAiOjE0OTI4MDMzNTg1OTYsInByb2ZpbGVJZCI6ImU4ZDBjYjQ3YjFhOTQ2Nzc5NzgxMzUzOTIxNzhmMzNkIiwicHJvZmlsZU5hbWUiOiIzNTNibGF6ZSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7Im1ldGFkYXRhIjp7Im1vZGVsIjoic2xpbSJ9LCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2Q1MzU2NDg1ZWU5OTg4YTdlNmE0ZTQ2YzdiODliNjk3MjlhYzNiY2Y4M2EzYzkyNzc4NTlkMmU5NTQzZWFjIn19fQ==

The output of command `/version` on my server is: 
This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: 
Citizens v2.0.22-SNAPSHOT build (1490)

**Comment by mcmonkey4eva** [comment]
that's base64 encoded.
You can decode that via a site like https://www.base64decode.org/ for ease
That one is:
`
{"timestamp":1492803358596,"profileId":"e8d0cb47b1a94677978135392178f33d","profileName":"353blaze","signatureRequired":true,"textures":{"SKIN":{"metadata":{"model":"slim"},"url":"http://textures.minecraft.net/texture/d5356485ee9988a7e6a4e46c7b89b69729ac3bcf83a3c9277859d2e9543eac"}}}
`
And when you open the link there, http://textures.minecraft.net/texture/d5356485ee9988a7e6a4e46c7b89b69729ac3bcf83a3c9277859d2e9543eac it's the raw skin png file

**Comment by mergu** [comment]
Every language has the ability to b64 decode as well. See https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html for java.

**Comment by midnjerry** [comment]
Awesome thanks!
