### ISSUE TITLE
Citizens API feature

### ISSUE THREAD

**Issue by IdkMan2** [CitizensDev/Citizens2#1543]
As we have NPCDespawnReason and it is pretty cool, there should be NPCSpawnReason too. It could help me a lot while developing some plugins.

**Comment by IdkMan2** [comment]
ADMIN_COMMAND;
TIMED_RESPAWN;
PLUGIN;
etc etc.

**Comment by fullwall** [comment]
Added

**Comment by IdkMan2** [comment]
❤️
