### ISSUE TITLE
Left bracket in NPC chat is always &a(LightGreen), even with sentinel greeting how do I fix?

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1544]
The output of command `/version` on my server is: **Paper version git-Paper-1523 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.23-SNAPSHOT (build 1562)**

Left bracket in NPC chat is always &a(LightGreen), even with sentinel greeting how do I fix? Here's a pic below to better describe the issue.

![image](https://user-images.githubusercontent.com/37608633/43475838-23221acc-9536-11e8-9c92-263f4acd9163.png)

Latest.log - https://pastebin.com/g20hTvBy

Citizens config.yml - https://pastebin.com/WE7C1nyn

**Comment by mergu** [comment]
Hiya, this can be easily fixed in Denizen using the `narrate` command. Denizen was specifically made to script NPCs. Join us on discord here: https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
You have a color code in the NPC name, and in the text.
You need to apply color codes to the text formatting options in your config to specifically control the colors of the brackets.

Also: I'm not sure if your config upload is wrong, or you just have an absolutely horrible font choice on your client, but your config shows brackets `[these square things]` but the screenshot looks more like parentheses `(these round things)`.

**Comment by axemwa** [comment]
Ah ok thanx that makes sense and yeah the font was a part of one of the selectable server resourcepacks that players can choose and I chose that font because it was the clearest/easiest one to read that I could find.

**Comment by axemwa** [comment]
Thanks I did this and it fixed it :)
'&7[&r<npc>&7]&r: <text>'
