### ISSUE TITLE
/npc name won't remove the nameplate for the PLAYER type.

### ISSUE THREAD

**Issue by gh422321** [CitizensDev/Citizens2#1545]
Title.

Running Citizens 2.0.22-SNAPSHOT (build 1487) on Spigot-1.12-Ro.1

`http://dbh.pw/i/77ntj.png`

**Comment by mcmonkey4eva** [comment]
The image link you provided is dead and/or a malware connected website.

Could you please upload it elsewhere - perhaps to imgur?

Also: please update to current Citizens builds from http://ci.citizensnpcs.co/job/Citizens2/

**Comment by gh422321** [comment]
1) My personal website. Here is re-upload: https://imgur.com/a/LQgLlL5

2) Updating to latest citizens build causes all non-player type npcs to go invisible.

**Comment by mcmonkey4eva** [comment]
Most likely a plugin conflict of some form.

Need to always be running most up-to-date Spigot for version (so 1.12.2 latest or 1.13.1 latest) and most up-to-date Citizens build from the CI page.

If all non-player NPCs are invisible, it's very likely a conflict with some other plugin, particularly one that manages entities directly (eg a pets plugin, a custom mobs plugin, etc) or via potentially-aggressive indirect management (eg a protection plugin like WorldGuard that might have been configured to block mobs in various ways)

**Comment by mcmonkey4eva** [comment]
Check for conflicting plugins. ie, test on a server without other plugins present - if it works there, slowly reintroduce plugins until it breaks again (then you know which plugin is conflicting).
If this isn't enough to find the fault, please reply below.

Be sure to update Citizens to latest dev build and Spigot to latest 1.12.2 or 1.13.1 build
