### ISSUE TITLE
Spawners Activation?

### ISSUE THREAD

**Issue by ad0ney** [CitizensDev/Citizens2#1546]
I'd like to propose adding a command that will allow NPC to activate spawners etc. if possible. I couldn't find anything about it.

The output of command `/version` on my server is: **(This server is running CraftBukkit version git-Bukkit-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.22-SNAPSHOT (build 1487))**

**Comment by SXRWahrheit** [comment]
Can you be more specific? You can already spawn mobs manually with Denizen.

https://one.denizenscript.com/denizen/cmds/spawn

**Comment by mcmonkey4eva** [comment]
I think `/npc playerlist` should cause some player-based things to activate that otherwise would not.
