### ISSUE TITLE
TabList issue still exists in 1.12.2

### ISSUE THREAD

**Issue by ApertureDevelopment** [CitizensDev/Citizens2#1549]
As I noticed when you walk sometimes the NPCs show up in the tab list without Name or Ping.
It was solved here:
#72

But I still have the issue.

The output of command `/version` on my server is: **git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.23-SNAPSHOT (build 1562)**

**Comment by mcmonkey4eva** [comment]
They should show up only momentarily and then be removed.

This is unfortunately a seemingly unfixable issue caused by changes to minecraft made in 1.7.6, where in that version and all past it, Player entities can only be spawned if they are on the tablist.
