### ISSUE TITLE
Turtle Shell cannot be set to helm slot..

### ISSUE THREAD

**Issue by TheTopCz** [CitizensDev/Citizens2#1550]
I want set turtle shell helmet, but it is not possible, the item is not taken as a helmet and npc we only put it in the hand ...

command: equip

This server is running CraftBukkit version git-Spigot-1503de9-53d3ac0 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

Citizens version 2.0.23-SNAPSHOT (build 1562)
Website: http://www.citizensnpcs.co
Authors: aPunch and fullwall
CitizensCMD version 2.0
Author: Mateus Moreira

**Comment by mcmonkey4eva** [comment]
Connected to 1.13 update, see issue #1534

**Comment by fullwall** [comment]
Fixed
