### ISSUE TITLE
Citizens v2.0.16-SNAPSHOT (build 1267) bug?

### ISSUE THREAD

**Issue by fabianosousa** [CitizensDev/Citizens2#1553]
I'm using the version:
Citizens v2.0.16-SNAPSHOT (build 1267)
[15:59:29] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Java 8 Update 172 (64-bit)

I disabled the config to not show the npc's.

npc:
  tablist:
    disable: true

Being that even so the npc's still appear.
not that they are constantly appearing.
when the player turns the head refreshes and returns to appear, if they walk with the tab they appear, then they disappear.
How do I solve this problem.
disabling it completely.

I used the version:
citizens-2.0.23-SNAPSHOT (build 1565)
http://ci.citizensnpcs.co/job/Citizens2/

Being that the problem still persists.

**Comment by mergu** [comment]
This isn't possible to fix. An NPC is a player, and to spawn a player they have to be put onto the tab list. Citizens immediately removes them from the tab list, which is why you see flickering. It's unavoidable.

**Comment by mcmonkey4eva** [comment]
Also, update your server. 1.8.8 is four years old now.
