### ISSUE TITLE
Phantom error

### ISSUE THREAD

**Issue by FrankHeijden** [CitizensDev/Citizens2#1554]
Error on startup: https://paste.md-5.net/yefahedose.avrasm

The output of command `/version` on my server is: **CraftBukkit version git-Spigot-fe3ab0d-bfb9131 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.23-SNAPSHOT (build 1566)**

**Comment by mcmonkey4eva** [comment]
Related to https://github.com/CitizensDev/Citizens2/issues/1534

**Comment by fullwall** [comment]
Can't reproduce this, seems like a plugin or reload issue. Which plugins are you using?

**Comment by FrankHeijden** [comment]
May it be because I used an older version (dev build) and then updated to the latest release on spigot?

**Comment by mcmonkey4eva** [comment]
@FrankHeijden your original post was on the still latest build.
1566 is latest.

Dev builds at http://ci.citizensnpcs.co/job/Citizens2/ are current builds, Spigot builds are almost always outdated.

**Comment by FrankHeijden** [comment]
Yea but I am using the 1.13 alpha *2 version from spigot. It also happens to be the same version as b1566, yes.

Also found I could not set the type of the NPC to phantom: https://paste.md-5.net/vecewofeba.avrasm

**Comment by fullwall** [comment]
So which plugins are you using?

**Comment by mcmonkey4eva** [comment]
If your plugin list is private information, you've done something horribly horribly wrong.

**Comment by fullwall** [comment]
@FrankHeijden same username

**Comment by mcmonkey4eva** [comment]
See https://wiki.citizensnpcs.co/Plugin_Conflict for information on debugging potential plugin conflicts.
