### ISSUE TITLE
NPCs are pushed when using the fishing rod

### ISSUE THREAD

**Issue by DardBrinza** [CitizensDev/Citizens2#1556]
I checked it out on the last Citizens build (#1566), on the last paper build (this one is almost the last), the problem is not solved in any way. As a crutch and a temporary solution I use /npc path for 1 block under NPC.

> version
[12:21:39 INFO]: This server is running Paper version git-Paper-1534 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[12:21:39 INFO]: Previous version: git-Paper-1416 (MC: 1.12.2)

> version citizens
[12:21:41 INFO]: Citizens version 2.0.22-SNAPSHOT (build 1547)
[12:21:41 INFO]: Website: http://www.citizensnpcs.co
[12:21:41 INFO]: Authors: aPunch and fullwall

**Comment by fullwall** [comment]
I can't reproduce this. Are you just right clicking the rod on the NPC? What mob type is the NPC?

**Comment by DardBrinza** [comment]
Type - player. Step away from NPC and throw him a fishing rod like a fish and he will pushed. Temporary solution for yourself - /npc gamemode creative

**Comment by fullwall** [comment]
Is this 1.12 only perhaps?

**Comment by DardBrinza** [comment]
Checked only on 1.12.2, on others I don't know.

**Comment by HipporunnerXTyler** [comment]
I have this same issue we run on spigot 1.12.2

**Comment by Tomographix** [comment]
I have the same issue on PaperSpigot 1.13.2 if that helps.
Running latest dev build as of today :)

**Comment by HipporunnerXTyler** [comment]
The solution to this is use a different 1.8 old combat plugin it's not citizens it's your combat plugin

**Comment by mcmonkey4eva** [comment]
Can't replicate on Spigot 1.14.2 and Citizens build 1695.


Likely an issue with old-combat plugins as was mentioned above.
