### ISSUE TITLE
Error when creating a NPC.

### ISSUE THREAD

**Issue by Redblock6YT** [CitizensDev/Citizens2#1558]
Hello!

I am having a issue when I create a npc. Here is the issue: https://imgur.com/a/KlUoh2l
Here is the console when I tried to exicute the command: https://pastebin.com/WiZ8xBK6
Here is my console log: https://pastebin.com/69qxHVcw

The output of command `/version` on my server is: https://imgur.com/a/Vl9vm4K
The output of command `/version citizens` on my server is: https://imgur.com/a/fc0ZPRS

Please tell me if there is a way to fix this.

Thanks and Best regards,
Redblock6

**Comment by mcmonkey4eva** [comment]
Update your server to run 1.12.2, and update Citizens to match.

You're running a 4 year old server and an even older Citizens build.

These are not supportable versions.

**Comment by Redblock6YT** [comment]
Well, I want 1.8 on my server so how do I match the citizens build?

**Comment by mcmonkey4eva** [comment]
You don't run a 1.8 server.

If you want old style combat, there are plugins that let you have that on 1.12.2 servers.
If you want 1.8 clients to be able to join, there are plugins that allow that on 1.12.2 servers.
