### ISSUE TITLE
startup redundancy ?

### ISSUE THREAD

**Issue by BloodEko** [CitizensDev/Citizens2#1562]
Hello!
As I've done now several tests with the citizens API, I noticed there might be some redundancy on startup. First it spawns npcs, then some seconds later it despawn npcs for setting skins, then it spawns npcs.

I question whether it might make sense at least to prevent the first spawn/despawn firering events.
As atm stuff that relies on these events is getting loaded first, then unloaded and loaded again.

- Log: https://one.denizenscript.com/haste/49580
- Spigot: 1.12.2 
- Citizens: build 1487

**Comment by mcmonkey4eva** [comment]
the way that [already] works ... is fine

**Comment by BloodEko** [comment]
I'd like to believe that too. Is there an example in which startup case it is useful to have the events firering like: _spawn despawn spawn_  instead of just _spawn_? Because yet for me it seems like pure redundancy.

**Comment by mcmonkey4eva** [comment]
it is fine the way it already works

**Comment by fullwall** [comment]
I know that people do use the events as they are set up now. It does appear a little redundant but the Spawn/DespawnReason is there for people to distinguish between them.
