### ISSUE TITLE
how to teleport via NPC using items

### ISSUE THREAD

**Issue by icansc187** [CitizensDev/Citizens2#1563]
how to teleport via NPC using items.

The output of command `/version` on my server is: **(1.11.2)**
The output of command `/version citizens` on my server is: **(1.13.1)**

**Comment by mcmonkey4eva** [comment]
Please don't post false information in an issue post.

Consider using Denizen to add advanced functionality like teleport tools and such, https://www.spigotmc.org/resources/denizen.21039/
