### ISSUE TITLE
Villagers disappearing 

### ISSUE THREAD

**Issue by 12339** [CitizensDev/Citizens2#1564]
I do know this doesn't follow the format, but I have no real explanation how this happen. It is a survival server with Citizens npcs in spawn, and eventually some of my villagers started disappearing. It happen to my friend too, it happen again and again. Once we disabled citizens villagers stopped disappearing.

**Comment by 12339** [comment]
https://github.com/CitizensDev/Citizens2/issues/1291 I found this issue by someone else too, I don't know why it hasn't been fixed yet

**Comment by fullwall** [comment]
I can't reproduce it easily. If you have a consistent way to make this happen on a clean server I can fix it much more easily.

**Comment by mcmonkey4eva** [comment]
Likely a conflict between some other plugin and Citizens caused the behavior. If you can gather any information that might help diagnose the issue, please reply below.
