### ISSUE TITLE
Compatible with Via Version

### ISSUE THREAD

**Issue by alexlazarev98** [CitizensDev/Citizens2#1565]
Hello.
When I run Citizens + ViaVersion players can't join the server.
In attempt of the player to come into the console writes:
`(Player) lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unknown mob network type id -1`

The output of command `/version` on my server is: **294(Spigot 1.12.2**
The output of command `/version citizens` on my server is: **1568(2.0.24)**

**Comment by mcmonkey4eva** [comment]
Post actual version output. Any alterations made to the output irrelevantizes and falsifies it.

Please also post the version of ViaVersion you have in use.

I will reopen this issue when that information is provided.

**Comment by alexlazarev98** [comment]
All in the screenshot
![screenshot_20180911201533](https://user-images.githubusercontent.com/37180406/45376223-f23a6000-b5ff-11e8-9043-dd9e2eca29a3.png)

**Comment by mcmonkey4eva** [comment]
Thank you!

That Spigot build looks a bit old (237 versions behind)! Might be relevant to update that: https://www.spigotmc.org/wiki/buildtools/

What client version are players attempting to connect from?

I'm not sure why you're running ViaVersion... you're running a 1.12.2 server, and ViaVersion doesn't yet support 1.13...

Are you perhaps also running ViaBackwards or ViaRewind, to allow in older clients?

**Comment by mcmonkey4eva** [comment]
will reopen this issue when the information requested above is provided.

**Comment by alexlazarev98** [comment]
Hello, sorry I didn't write for so long.
Now I use ViaVersion 1.5.2 and ProtocolSupport 4.28
Client versions: 1.8-1.13.1
Server version on screenshot
![screenshot_20180927185500](https://user-images.githubusercontent.com/37180406/46158611-e8169380-c286-11e8-88b5-c0c380ae060d.png)

**Comment by mcmonkey4eva** [comment]
ViaVersion in-and-of itself does not allow 1.8, 1.9, etc. clients to join a 1.12.2 server. I again request full information, particularly in answer to questions in previous posts.
