### ISSUE TITLE
Can't hide npc name for player type

### ISSUE THREAD

**Issue by ValerianV** [CitizensDev/Citizens2#1566]
I can't hide npc name when they are Player Type, even with the command /npc name
Plus, scoreboard objectifs is played under my npc names, and thats really annoying.

![image](https://user-images.githubusercontent.com/42415928/45332069-c753fb80-b56e-11e8-9e5a-778989a66af4.png)

version 
![image](https://user-images.githubusercontent.com/42415928/45332006-75ab7100-b56e-11e8-9856-67225fcb3411.png)

Citizens version 

![image](https://user-images.githubusercontent.com/42415928/45332029-9247a900-b56e-11e8-8a82-75e85544a400.png)

**Comment by fullwall** [comment]
What's your config?
