### ISSUE TITLE
Cached skins no longer here?

### ISSUE THREAD

**Issue by ItsGamingSoni** [CitizensDev/Citizens2#1567]
The output of command `/version` on my server is: 
**This server is running CraftBukkit version git-Spigot-eb3d921-b9f1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) - You are 237 version(s) behind**
The output of command `/version citizens` on my server is:
**Citizens version 2.0.22-SNAPSHOT (build 1552)**

I used to utilize the " /npc skin -p USERNAME " command 4 months ago, but when I tried to use it today it didn't show the param up.

Is this a bug or is it an intended feature? My server relies on cached skins and I'd love to know if there's a workaround to this.

**Comment by BloodEko** [comment]
-p is default now.

**Comment by mcmonkey4eva** [comment]
^ That. It's on by default, and the old functionality for when `-p` wasn't used is now `-l`. See for further reference: https://wiki.citizensnpcs.co/Skins
