### ISSUE TITLE
Citizens not starting

### ISSUE THREAD

**Issue by IWickGames** [CitizensDev/Citizens2#1574]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

Ok so I cant even do the Server log because I looked In it and even did a search and its like my sever is not even seeing the plugin at all. Therese no server log at all. Not even like s failed to start message just nothing! I don;t know why my server is 1.8.8 with ViaVersion and people can join with it but I don;t know why its doing this

**Comment by SXRWahrheit** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8

https://wiki.citizensnpcs.co/Versions
