### ISSUE TITLE
I can't find any compatible version for my server

### ISSUE THREAD

**Issue by xhanaZPR** [CitizensDev/Citizens2#1577]
Hi, I can't find a proper version of Citizen for my 1.13 server.
Here you can see I tried with an old version of CZ2 but I also tried with every newer version. And every one of them show me the same message : 

> [18:27:17 ERROR]: [Citizens] v2.0.23-SNAPSHOT (build 1556) is not compatible with Minecraft v1_13_R1 - try upgrading or downgrading Citizens. Disabling.
> [18:27:17 INFO]: [Citizens] Disabling Citizens v2.0.23-SNAPSHOT (build 1556)
> 

Bukkit version for MC 1.13
> [18:33:00 INFO]: This server is running CraftBukkit version git-Bukkit-1c7adf7 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

I did not touch the config file or any other, here is what I get each time :/
Do you have a solution I could try ?

**Comment by SXRWahrheit** [comment]
The latest versions of Citizens are targeted for 1.13.1; update your server to the latest 1.13.1 Spigot builds.
