### ISSUE TITLE
Citizens error mcpc 1.8.8

### ISSUE THREAD

**Issue by Poustmal** [CitizensDev/Citizens2#1579]
29.09 10:12:47 [Server] ERROR Could not pass event NPCRightClickEvent to Citizens v2.0.24-SNAPSHOT (build 1572)
29.09 10:12:47 [Server] INFO org.bukkit.event.EventException
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:419) [citizens-2.0.24-SNAPSHOT.jar:?]
29.09 10:12:47 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1315) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
29.09 10:12:47 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
29.09 10:12:47 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
29.09 10:12:47 [Server] INFO at net.citizensnpcs.util.Util.matchesItemInHand(Util.java:184) ~[?:?]
29.09 10:12:47 [Server] INFO at net.citizensnpcs.npc.NPCSelector.onNPCRightClick(NPCSelector.java:98) ~[?:?]
29.09 10:12:47 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
29.09 10:12:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.jar:git-Spigot-21fe707-e1ebe52]
29.09 10:12:47 [Server] INFO ... 24 more

**Comment by Poustmal** [comment]
![img_20180929_111527](https://user-images.githubusercontent.com/22281205/46243112-0391b380-c3d9-11e8-8c6f-bc157b536278.jpg)

**Comment by mcmonkey4eva** [comment]
To my knowledge MCPC never updated to 1.8 at all - Do you mean MC (Minecraft) 1.8?
Either way, see here: https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by Poustmal** [comment]
Yes minecraft 1.8

**Comment by Poustmal** [comment]
I mean mc 1.8

**Comment by Poustmal** [comment]
@mcmonkey4eva  open the issue

**Comment by mcmonkey4eva** [comment]
Read the answer I gave.

**Comment by Poustmal** [comment]
Yes but when im using latest spigot version,server reduces almost all free ram so I cant stay on latest spigot version

**Comment by mcmonkey4eva** [comment]
That sounds like you have memory leak issue, which is not something we're going to be able to fix for you here. Contact your server provider and/or spigot support as relevant.

**Comment by Poustmal** [comment]
ok..
