### ISSUE TITLE
Select NPCs not spawning

### ISSUE THREAD

**Issue by BiGUNMAN** [CitizensDev/Citizens2#1580]
I recently noticed the problem where certain NPC's aren't being spawned in my spawn. I did upgrade to async chunk loading (implemented in Paper Spigot).

This issue reoccurs every time I restart the server. I can after startup use /npc select, and /npc spawn to rectify the issue.

Here's the Citizens Debug: https://pastebin.com/FVeNdHd9

The output of command `/version` on my server is: Paper-317 (1.13.1)
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1573)

**Comment by mcmonkey4eva** [comment]
If you can replicate the issue on Spigot (NOT paper), let me know. Otherwise, out-of-boundary issue.
