### ISSUE TITLE
Blacksmith 1.13.1

### ISSUE THREAD

**Issue by jajamic** [CitizensDev/Citizens2#1581]
Hi,

Your plugin work but your additional: Blacksmith dosen t work, can you update for 1.13.1 ?

thx :)

**Comment by mcmonkey4eva** [comment]
Blacksmith is not our own plugin (it was made by someone else) and is not maintained (the original authors are gone and nobody wants to handle it themselves). It may be updated eventually but there's no particular guarantee. You might prefer making a script in Denizen to handle that functionality https://www.spigotmc.org/resources/denizen.21039/

**Comment by jajamic** [comment]
OK :/
My bad I don't know how use Denizen and I m using 1.13.1.

**Comment by mcmonkey4eva** [comment]
Learn how to use Denizen then? :D it's not hard!

**Comment by mcmonkey4eva** [comment]
I've self-assigned this as I'm likely going to be the one to do it eventually (update Blacksmith) but any other developers that want to take it are welcome to.

**Comment by mcmonkey4eva** [comment]
Build 141+ on http://ci.citizensnpcs.co/job/Blacksmith/ should function maybe. I've performed a minimalist fix and update to 1.13. Haven't particularly tested it, let me know if it's entirely broken.
