### ISSUE TITLE
npcs wont pathfind up half-slabs.. only down

### ISSUE THREAD

**Issue by WHiZSTA** [CitizensDev/Citizens2#1582]
I was noticing i couldn't get my npc to pathfind up a walkway.. and whenever he did he'd hop a fence and go up the grass on the side instead.. i finally decided to make the grass on the side of the path unpassable, to which he just went in a circle and never up the path. If i tped him to the top he would, however, go down it. I decided to try removing a half slab line to see if he could go up full blocks to the spot, and he could perfectly. i tried adding stairs instead of half slabs, and he will go up those as well. So the problem is isolated to going up half-slabs.

i use:
paper-342 (mc 1.13.1)
citizens build 1547 (2.0.24)

There was no output to the server console of issues.

**Comment by mcmonkey4eva** [comment]
Try changing the `use-new-finder` option in the Citizens config file to the opposite of whatever it is now (`false` to `true` or the reverse).

**Comment by WHiZSTA** [comment]
this did solve the problem, it was on the default of "false" Thank you.
