### ISSUE TITLE
delay trigger is buggy.

### ISSUE THREAD

**Issue by WHiZSTA** [CitizensDev/Citizens2#1583]
i'm having an absolutely horrid time with the delay trigger. i've wasted so many hours with it, and i noticed i'm not alone based on some spigot posts. The problem is sometimes it adds the delay and works fine, other times it adds the same delay and doesnt work for the npc to stop and wait.

i can't find a reason why this is happening, i even checked the save database, and they are identical in terms of trigger waypoint info. i've been trying with delays of 300ticks, and also with 60. 

the database for the working one contains:
 waypoints:
        linear:
          points:
            '0':
              location:
                world: world
                x: '-41.0'
                y: '96.0'
                z: '-486.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  delay: 100
                  type: delay
                '1':
                  lines:
                    '0': test2
                  radius: -1.0
                  type: chat
            '1':
              location:
                world: world
                x: '-41.0'
                y: '96.0'
                z: '-481.0'
                yaw: '0.0'
                pitch: '0.0'
            '2':
              location:
                world: world
                x: '-41.0'
                y: '96.0'
                z: '-476.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  lines:
                    '0': boo
                  radius: -1.0
                  type: chat
            '3':
              location:
                world: world
                x: '-36.0'
                y: '96.0'
                z: '-476.0'
                yaw: '0.0'
                pitch: '0.0'
            '4':
              location:
                world: world
                x: '-36.0'
                y: '96.0'
                z: '-481.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  lines:
                    '0': testing
                  radius: -1.0
                  type: chat
                '1':
                  delay: 100
                  type: delay
            '5':
              location:
                world: world
                x: '-36.0'
                y: '96.0'
                z: '-486.0'
                yaw: '0.0'
                pitch: '0.0'
        provider: linear

for the non-working one:

      waypoints:
        provider: linear
        linear:
          points:
            '0':
              location:
                world: world
                x: '13.0'
                y: '83.0'
                z: '-441.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  delay: 60
                  type: delay
                '1':
                  lines:
                    '0': '0'
                  radius: -1.0
                  type: chat
            '1':
              location:
                world: world
                x: '16.0'
                y: '87.0'
                z: '-460.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  lines:
                    '0': '1'
                  radius: -1.0
                  type: chat
            '2':
              location:
                world: world
                x: '14.0'
                y: '87.0'
                z: '-459.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  delay: 300
                  type: delay
                '1':
                  lines:
                    '0': '2'
                  radius: -1.0
                  type: chat

FYI the chat triggers always work whether the delay one works or not. also interestingly enough, where the chat is to fire after the delay, the chat is still delayed the right amount, while the npc keeps on walking.

i'm running the latest dev build of both citizens and paper.

**Comment by WHiZSTA** [comment]
here is a simpler example... just making an npc walk a straight line back and forth.. he walks fine... but i want him to wait at each end before continuing to the other end...

![2018-10-06_20 02 30](https://user-images.githubusercontent.com/18521070/46576845-23aa0f80-c9a3-11e8-9e88-ff5312c7ae02.png)

i add it to the one end... he doesn't stop.. i change to the other waypoint slot and add there too..  he doesn't stop there either.. he continues just walking back and forth with no delay.

his database:
      waypoints:
        linear:
          points:
            '0':
              location:
                world: world
                x: '16.0'
                y: '82.0'
                z: '-438.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  delay: 100
                  type: delay
            '1':
              location:
                world: world
                x: '7.0'
                y: '82.0'
                z: '-439.0'
                yaw: '0.0'
                pitch: '0.0'
              triggers:
                '0':
                  delay: 100
                  type: delay
        provider: linear

**Comment by fullwall** [comment]
What is your config? Having a hard time reproducing this.

**Comment by WHiZSTA** [comment]
[cit.zip](https://github.com/CitizensDev/Citizens2/files/2453650/cit.zip)
attached is the cfg and db..  i'll  dl the latest build and see if it can help narrow down the issue too

**Comment by fullwall** [comment]
I guess if the path is getting canceled/changed somehow before the NPC actually reaches each point then you would not get the delay. Maybe try increasing your default-distance-margin to 2?

**Comment by WHiZSTA** [comment]
![2018-10-07_01 45 05](https://user-images.githubusercontent.com/18521070/46578700-d2664400-c9d3-11e8-9df5-34e696bd50b1.png)
![2018-10-07_01 48 26](https://user-images.githubusercontent.com/18521070/46578701-d2664400-c9d3-11e8-8cc4-6569ee16941a.png)
k..  well i turned on path debugging too and updated to the new build.. i also increased that distance to 2,.. same issue and still nothing standing out as wrong.. it's all in th4e database, it adds correctly.. the npc just isnt stopping.. like i said if i have other triggers after the delay... they still delay properly but he just walks on by. as a sidenote, just to me more user friendly, having it output the triggers for each waypoint as you mouse scroll the waypoint slots, rather than only listing the first one's trigger.. would be very useful.

**Comment by fullwall** [comment]
Just added that, but still not able to reproduce... what version of Minecraft are you using?

**Comment by WHiZSTA** [comment]
07.10 06:51:46 [Server] INFO This server is running Paper version git-Paper-342 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

how can i better help you track down what is happening?

**Comment by mcmonkey4eva** [comment]
It shouldn't be relevant (I think) but just to try - would you be able to test with a standard latest-revision Spigot jar (instead of Paper)?
It *shouldn't* make a difference on this but with modded server jars it's good to be careful, just to make sure.

**Comment by WHiZSTA** [comment]
just tested on spigot, same issue.

**Comment by WHiZSTA** [comment]
this is just an observation and may mean nothing...  but it appears as if your trigger code is separate from your movement code, seeing the trigger is indeed waiting, whereas the NPC keeps moving... in my testing so far, the NPC seems to keep walking on the paths where the next part of his path is within the default distance margin of where he is supposed to stop.  for example, in the straight line scenario, he is already on the path that he would be ut on after the trigger would tell him its ok to move on. in fact he never really fully enters the waypoint block he's supposed to stop on even, he just touches the outer part of the block and keeps on going.

**Comment by WHiZSTA** [comment]
so i did test by adding barriers making them walk through the waypoints, it didn't help... however i did notice something else of interest when playing with the triggers...
![2018-10-08_09 22 02](https://user-images.githubusercontent.com/18521070/46611904-26108480-cadd-11e8-9250-0978679f9a51.png)
it claimed there were no triggers for the locations... even though they existed in the database. so i added a new one. and it comes back saying there were now two... but when i go back into /npc path and triggers it again says there are none... so perchance the npc isnt seeing the triggers even though they exist.

**Comment by fullwall** [comment]
try the latest build

**Comment by WHiZSTA** [comment]
it didn't solve the problem.. however, i did just do more testing and was trying to figure out what the difference was between the working and non-working npcs.. I FINALLY found it... if I add the /trait sentinel it won't delay for some reason... when i remove the trait.. it does delay as expected. literally, i can toggle the trait and you see it start and stop working properly. So would this be a bug with when traits are added it doesn't follow the delay or is this a bug specific to the sentinel code?

**Comment by mcmonkey4eva** [comment]
@WHiZSTA that would do it. Sentinel has systems to automatically override the waypoint system that are almost certainly causing the issue.
Specifically, Sentinel will:
- Pause waypoint navigation when the NPC enters combat or is told to guard a player
- Unpause waypoint navigation any other time.
The code there is a bit messy and I believe I can fix that.
It errs towards the side of unpausing navigation too much (rather than risking it being unpaused too little, which if that occurs means the NPC will be stuck in a bad spot and not return to guard location or patrol routes)

**Comment by mcmonkey4eva** [comment]
@WHiZSTA Try build DEV-191+ from http://ci.citizensnpcs.co/job/Sentinel/
It should fix the issue (per what I wrote in my comment above) by only unpausing waypoints when Sentinel is what paused them in the first place

**Comment by WHiZSTA** [comment]
uhg i hate to do this to you.. but i just noticed in my console log citizens is spamming like heck.. i disabled sentinel and its still spamming so it appears to be from one of the citizens updates..

09.10 04:12:06 [Server] INFO [Citizens] Exception while updating 4: null. 09.10 04:12:06 [Server] WARN java.util.ConcurrentModificationException 09.10 04:12:06 [Server] WARN at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) 09.10 04:12:06 [Server] WARN at java.util.ArrayList$Itr.remove(ArrayList.java:873) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:294) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:180) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:289) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437) 09.10 04:12:06 [Server] WARN at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.tick(NMSImpl.java:1041) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.util.NMS.tick(NMS.java:302) 09.10 04:12:06 [Server] WARN at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) 09.10 04:12:06 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) 09.10 04:12:06 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) 09.10 04:12:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) 09.10 04:12:06 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) 09.10 04:12:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) 09.10 04:12:06 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) 09.10 04:12:06 [Server] WARN at java.lang.Thread.run(Thread.java:748) 09.10 04:12:13 [Server] INFO [Citizens] Exception while updating 4: null. 09.10 04:12:13 [Server] WARN java.util.ConcurrentModificationException 09.10 04:12:13 [Server] WARN at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) 09.10 04:12:13 [Server] WARN at java.util.ArrayList$Itr.remove(ArrayList.java:873) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:294) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:180) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:289) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437) 09.10 04:12:13 [Server] WARN at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.tick(NMSImpl.java:1041) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.util.NMS.tick(NMS.java:302) 09.10 04:12:13 [Server] WARN at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) 09.10 04:12:13 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) 09.10 04:12:13 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) 09.10 04:12:13 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) 09.10 04:12:13 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) 09.10 04:12:13 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) 09.10 04:12:13 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) 09.10 04:12:13 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by mcmonkey4eva** [comment]
That's a separate issue - can you please make sure your server jar (Spigot) and all plugins are fully up to date - and if the error persists when fully up to date, please open a new separate issue.
