### ISSUE TITLE
NPC Skins not showing up

### ISSUE THREAD

**Issue by DarkTheDev1** [CitizensDev/Citizens2#1587]
The output of command `/version` on my server is: **(Spigot 1.13.1)**
The output of command `/version citizens` on my server is: **(citizens2.0.24)**

-Issue is that the player NPC skins do not show up when I load them into the server. There is only 1 error in the server so I hope that it is an easy fix. I tried /npc create  [playerName] and also /npc skin [playerName] but neither work. They are still steves.

-LOG of the console for Citizens is 
11.10 17:05:50 [Server] INFO [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1567)
11.10 17:05:51 [Server] INFO [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1567)
11.10 17:05:51 [Server] INFO [Citizens] Could not fetch NMS field REGISTRY: [[REGISTRY.
11.10 17:05:51 [Server] INFO [Citizens] Could not fetch entity id mapping fields: null.

**Comment by mcmonkey4eva** [comment]
Neither of the things you posted are the output of the version command.

Update your server and all plugins.

If the issue remains, please post the actual output of the version command.
