### ISSUE TITLE
Skins  only loading after a relog since 1.8 spigot

### ISSUE THREAD

**Issue by leversandpulleys** [CitizensDev/Citizens2#159]
Skinned NPC's will appear as a glitched Steve or a non-glitched Alex until relogging. This happens frequently, perhaps even most of the time, but is not the case at the actual moment of skinning. Further, relogging only seems to affect NPC's in one's line of sight and doing so appears to revert some  other NPC's that just moments earlier were properly skinned. 

We began encountering this issue after going to Spigot 1.8. We are using v2.0.14 build 1195. Respawning the NPC will not usually (maybe never?) fix the issue. A relog seems to be necessary. Two players entering the same area at the same time may both see the proper skins or only one of them may see the proper skins. There does not appear to be much that is consistent with this bug.

Many thanks for your time and attention.

**Comment by fullwall** [comment]
Try the latest build please.
