### ISSUE TITLE
1.8.8 right NPC right Click NoSuchMethodError

### ISSUE THREAD

**Issue by voodootje0** [CitizensDev/Citizens2#1591]
When you right-click a citizen on 1.8.8 spigot it will give an exception.
https://haste.jartexnetwork.com/uruqepeloq.apache

Server version:
![image](https://user-images.githubusercontent.com/6852308/46917248-1b665b80-cfc5-11e8-9553-20e43bddcd55.png)
(On normal 1.8.8 spigot it also doesn't work)

Citizens version:
![image](https://user-images.githubusercontent.com/6852308/46917262-3c2eb100-cfc5-11e8-8ca3-3d16bbbdf331.png)

**Comment by fullwall** [comment]
Check latest build.
