### ISSUE TITLE
Why when i type npc remove that not reset id number?

### ISSUE THREAD

**Issue by comonier** [CitizensDev/Citizens2#1592]
were can i reset all id numbers ?
i have removed all npcs
npc list = nothing
i just already clean saves.yml 
restart the server.
but ever time i make a new npc it start from the last id number created

i have created 5 npcs, i have removed 5 npcs
why citizens did not reset the id number list, why it still counting on next saved old last id.
npc create jannedoe
npc list, id 6 ¬¬
how can i reset it count ? please ?

**Comment by mcmonkey4eva** [comment]
id's are meant to never repeat, ever. If you really really want to start the id counter over, delete the `saves.yml` file in the `plugins/Citizens` folder.

**Comment by comonier** [comment]
deleted saves.yml still counting new npc number id 7

**Comment by mcmonkey4eva** [comment]
... You did it wrong then.

Bear in mind that the server must be fully stopped before you can alter most critical files, and only started running again after.

**Comment by comonier** [comment]
ok worked now ty
