### ISSUE TITLE
/npc cmdadd command missing

### ISSUE THREAD

**Issue by hihihoholalalolo1227** [CitizensDev/Citizens2#1596]
/npc cmdadd command is missing when i just installed the plugin so i cannot use commands when doing a event with the npc. its output is: Unknown command

The output of command `/version` on my server is: [01:11:15 INFO]: This server is running CraftBukkit version git-Bukkit-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[01:11:15 INFO]: You are 985 version(s) behind
The output of command `/version citizens` on my server is: [01:11:55 INFO]: Citizens version 2.0.16-SNAPSHOT (build 1267)
[01:11:55 INFO]: Website: http://www.citizensnpcs.co
[01:11:55 INFO]: Authors: aPunch and fullwall

**Comment by mcmonkey4eva** [comment]
`/npc cmdadd` is not a command that exists or ever has existed.
Also, you're running an unsupportably outdated server. See for info: https://wiki.citizensnpcs.co/Minecraft_1.8
