### ISSUE TITLE
Crash at server starting after updating from 1.12.2 to 1.13.2

### ISSUE THREAD

**Issue by Damien0503** [CitizensDev/Citizens2#1599]
Hello,

I've got troubles with Citizens while updating to the last build in 1.13.2. My original config.yml et saves.yml are from 1.12.2 but while starting server in 1.13.2, it makes it crash.

Here is the crashreport : https://pastebin.com/8j3aFLQG
Config.yml : https://pastebin.com/9xLs8gQW

Citizens version: 2.0.24-SNAPSHOT (build 1583)
Serveur version : Paper version git-Paper-392 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Thanks for helping ^^

**Comment by AlanMullett** [comment]
The issue is that CraftBukkit has updated some field names between 1.13.1 and 1.13.2, things like the a,b,c,d,e,f in BoundingBox are now minX, minY, minZ, maxX, maxY, maxZ.

I've hacked my version to make it work and it's a quick process so hopefully a proper version will be out soon.

**Comment by mergu** [comment]
A working 1.13.2 build is already out. Please update before making an issue:
http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/
