### ISSUE TITLE
SkullMeta not saving

### ISSUE THREAD

**Issue by andfont** [CitizensDev/Citizens2#1600]
We can not assign heads, I perform the process that I have always done, npc select, npc equip and then I give it the head but it does not accept it and it does not assign it, please fix this bug thanks!

version Citizens 2.0.24-SNAPSHOT (build Unknown)

**Comment by mcmonkey4eva** [comment]
A: You can use `helmet` (type it in chat while in the equipment editor) to put any item on an NPC's head (even if it doesn't normally recognize it)
B: You're running some unknown/custom build of Citizens. Grab an official build here: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
@fullwall looks like skull support was accidentally dropped in the 1.13 updates from the list here:
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/editor/GenericEquipper.java#L82
1.12 item name was `SKULL_ITEM`,
1.13 item names are `PLAYER_HEAD`, `DRAGON_HEAD`, `CREEPER_HEAD`, `ZOMBIE_HEAD`, `SKELETON_SKULL`, and `WITHER_SKELETON_SKULL`

**Comment by andfont** [comment]
It happens to me with the official version for that reason I am looking at the code to fix it but this error happens in the latest version of citizen there is no way to put a head in a ALDEANO for example as I could do before. when it is solved you tell me friend xD

**Comment by mcmonkey4eva** [comment]
@andfont again, type `helmet` in chat with the equipment editor open while holding the head

**Comment by andfont** [comment]
ooo ok now yes thanks! I already got it okk XD

**Comment by andfont** [comment]
the heads personalized with TEXTURES do not work out badly !, only works the ones that OWNER has but not those of https://minecraft-heads.com/ for example it does not accept them :(

**Comment by andfont** [comment]
the texture is lost, the head is not maintained but the texture is lost, the skin is lost, but the exact head is not lost

**Comment by andfont** [comment]
the head is not lost, but if the texture

**Comment by andfont** [comment]
but it is lost when you restart the server, at first it is maintained but when restarting it loses the texture of: https://minecraft-heads.com/

**Comment by mcmonkey4eva** [comment]
That's an additional issue that will also need to be addressed, then.

@fullwall likely the CitizensAPI item persistence/storage system needs to be updated for 1.13 NBT structures. In particular for this issue, skull handling: https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/util/ItemStorage.java#L162 needs to be updated. Looks like for the `PlayerHead` 1.13 item, there's the root level NBT key `SkullOwner` (whereas that 1.12 code seems to reference `skull.owner` as the key name).

**Comment by axemwa** [comment]
I also get this problem in 1.13.2 when giving an NPC a player head in their mainhand and saving with /citizens save it saves it in saves.yml like normal with UUID's skin details etc, but after restarting the server the UUID/skin info for the head is gone and replaced with details for a normal head in config and the NPC is left carrying a normal steve player head ingame without textures/skins

**Comment by axemwa** [comment]
Can see the player head being held in this vid, it used to have textures
https://youtu.be/T7hmV-yu6LY

**Comment by mcmonkey4eva** [comment]
After looking at it a bit more closely:
Well, first, my previous post was pretty off-the-point, guess I wasn't paying attention while writing it.
But...
It appears there isn't an API for controlling non-current skull skins in Bukkit. The `SkullMeta` interface just tracks the owner as a current player (effectively by name, for some reason). The implementation of it (`CraftMetaSkull`) has:
`    private GameProfile profile;`
which is not accessible by any API but is the actual full data needed.
@fullwall It looks like the ideal actual solution on this is to defer the implementation of that data to NMS modules, which can read the `GameProfile` object via reflection and return the full profile data (including unique skin texture data as a key requirement).

**Comment by axemwa** [comment]
Yeah seems pretty technical lol but looks like you have a solution gl :P

**Comment by fullwall** [comment]
@mcmonkey4eva there is skullmetaprovider now which does that. Is it doing it at the wrong time?

**Comment by mcmonkey4eva** [comment]
Have confirmed that skull skin tracking functions perfectly in test versions: `git-Spigot-766dab2-b9a2a74 (MC: 1.14)` and `Citizens version 2.0.25-SNAPSHOT (build 1654)`

**Comment by axemwa** [comment]
@mcmonkey4eva This issue is occurring again using, 
Citizens version 2.0.25-SNAPSHOT (build 1737)
Denizen version 1.1.0-SNAPSHOT (build 992-DEV)
Sentinel version 1.9.2 (build 266)

and this is what one of the NPC's settings look like after I restart, even though it remembers the texture of the held item it doesn't seem to apply it and they player_head in the NPC's hand looks like a steve head. May need to re-open the issue if u are able to reproduce
