### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by neox91120** [CitizensDev/Citizens2#1601]
Hi this isn't really an issue?
I'd like to give to a certain rank/group  a npc to player.
What i mean is that, i can let a player do whatever he likes with 1 npc and only 1.
Like some sort of pet.
He can rename it, change it's skin, create a path, tp it wherever for example.
But not do any of those things to other npc like those that are found in spawn.

Thanks in advance and excuse my english im not english ^^

**Comment by mcmonkey4eva** [comment]
Citizens has functionality for this natively.
Just give those ranks access to the specific permission nodes they needed, *excluding* the `citizens.admin` node (to prevent them from editing NPCs that aren't their own) and including the `citizens.npc.limit.1` node (to limit them to just 1 NPC)
See a list of permission nodes here: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/resources/plugin.yml#L33 (note that they only go to line 436, after that they repeat)
