### ISSUE TITLE
NPC having issues walking over buttons on ground

### ISSUE THREAD

**Issue by ParadiddlePride** [CitizensDev/Citizens2#1605]
When my NPC walks over a button that's been placed on the ground, the button pops into the air and also creates an error in console. Floating button seen here: http://prntscr.com/lciowl

Error being created: https://pastebin.com/PKydvcYT
Citizen's config: https://pastebin.com/myMSz8bx

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-f6a273b-db10914 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1586)

**Comment by mcmonkey4eva** [comment]
For the error: update to latest dev build from http://ci.citizensnpcs.co/job/Citizens2/
Also, update Spigot to latest 1.13.2 using BuildTools

If the button still glitches out with latest builds we can test that (I don't think that should at all because by Citizens, likely an unrelated plugin, but we can verify that after you update if it still occurs)

**Comment by ParadiddlePride** [comment]
Alright, so versions are now:

This server is running CraftBukkit version git-Spigot-e4d0c66-f3f2fe5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens version 2.0.24-SNAPSHOT (build 1589)

No errors in console, but issue is still there: http://prntscr.com/lcj9sr

**Comment by mergu** [comment]
verified - seems to reset nearby buttons & levers to the ceiling *only near waypoints along the chosen path*. buttons over 2 blocks away from waypoints aren't affected

images:
![image](https://user-images.githubusercontent.com/29823405/47770583-4f749880-dcb6-11e8-9755-c33aeb57f729.png)
![image](https://user-images.githubusercontent.com/29823405/47770618-7337de80-dcb6-11e8-9010-25dbeeac5679.png)
