### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Midnight9746** [CitizensDev/Citizens2#1606]
I had just came back to check a past issue of mine for another thread and noticed this
![2018-11-01](https://user-images.githubusercontent.com/30037006/47834927-9a9eb200-dd6f-11e8-8aca-8a610ee38cd5.png)
Why do I have a repository and who do I transfer it to (or do I just delete it?).

**Comment by mcmonkey4eva** [comment]
You made a fork. By clicking the fork button.
Read about forks on GitHub: https://help.github.com/articles/fork-a-repo/

You can just delete it.

**Comment by Midnight9746** [comment]
Thanks, I didn't realize I created a fork in the past.
