### ISSUE TITLE
Problem with skins on NPC.

### ISSUE THREAD

**Issue by NoWayCZ** [CitizensDev/Citizens2#1608]
![fuzo](https://user-images.githubusercontent.com/44753569/47968498-26178c00-e06b-11e8-87ed-b1b581fb2b34.png)

The output of command `/version` on my server is: spigot 1.12.2 - R0.1 - snapshot
The output of command `/version citizens` on my server is: 2.0.22

I have problem with skin on my server for cracked users. When I create npc with premium name or I change skin to premium name then skin don´t work. I use on my server skinsrestorer. Log from server and console are clear. Just skins don´t work. Screenshot: https://ctrlv.cz/shots/2018/11/04/QqNi.png

**Comment by mcmonkey4eva** [comment]
Skins do not work on illegal servers.

https://wiki.citizensnpcs.co/Cracks
