### ISSUE TITLE
NPC Disappearing 

### ISSUE THREAD

**Issue by AccioAce** [CitizensDev/Citizens2#1610]
Hello Staff,
This bug needs to be fixed asap. NPC keep disappearing after a restart.

- Thanks

**Comment by mcmonkey4eva** [comment]
Are you perhaps experiencing this issue: https://github.com/CitizensDev/Citizens2/issues/1332 ?
If so, post there or Subscribe to notifs from it.
If not, will need more information.

**Comment by AccioAce** [comment]
I'm not 100% sure I mean after restarting the NPC just disappears from there current spot. We need to keep replacing the NPC with /npc list then /npc select and then tp them back. This is one of the major bug but it could be related.
