### ISSUE TITLE
Diagonal Paths

### ISSUE THREAD

**Issue by Morphan1** [CitizensDev/Citizens2#1612]
At the moment, diagonal pathfinding causes NPCs to walk in a visually jarring zig-zag pattern ([see this short video as an example](https://i.gyazo.com/f0c64bd77b33f5e6fcce08e6a41f4e46.mp4)). It would be nice to have the option to automatically smooth out these paths for the sake of looking more natural.

**Comment by LogGits** [comment]
Can be achieved in using:
https://www.spigotmc.org/threads/hitboxes-and-ray-tracing.174358/

**Comment by fullwall** [comment]
Added (with some performance penalty)
