### ISSUE TITLE
/npc name

### ISSUE THREAD

**Issue by deluxx001** [CitizensDev/Citizens2#1614]
when writing / npc name does not delete the name from npc

**Comment by mergu** [comment]
please follow the issue template

**Comment by deluxx001** [comment]
where?

**Comment by SXRWahrheit** [comment]
When creating a new issue, there is a template.

![2018-11-08 16_17_29-new issue citizensdev_citizens2](https://user-images.githubusercontent.com/774463/48230792-d0e0c080-e371-11e8-8f39-8644d5cfebbb.png)

**Comment by mcmonkey4eva** [comment]
Likely a conflict with some plugin that interacts with the scoreboard system in some way.
As a particular example, `FeatherBoards` is a plugin known to be very broken in its scoreboard handling and will break `/npc name` and other scoreboard-based features.
If you're not sure which plugin(s) on your server might have a conflict here, follow the steps listed on this page: https://wiki.citizensnpcs.co/Plugin_Conflict

If you get stuck while trying this or go through the full testing process and can't find any conflicting plugins, please reply below and we'll reopen the issue.
