### ISSUE TITLE
Console error when using /npc skin

### ISSUE THREAD

**Issue by Noiknez** [CitizensDev/Citizens2#1619]
The NPC creation work, but when I do the command to change the npc skin I got an error message in the console "java.lang.NullPointerException: null"

Error log : https://pastebin.com/q5gBVC0Q

Server version : CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 

Citizen version : Citizens v2.0.22-SNAPSHOT (build 1552)

**Comment by mcmonkey4eva** [comment]
Looks like an Citizens command output translator error.
As a workaround, in the Citizens config change your translation to English (en), until the French (fr) translation is fixed. (I'm assuming you're using that one currently).

**Comment by Noiknez** [comment]
I restarted the server and no error

**Comment by Noiknez** [comment]
And yes I am using the french one, the text to change the skin is in english

**Comment by mcmonkey4eva** [comment]
In that case it may have been an OS induced file handling error or something, hitting on translation code by chance
