### ISSUE TITLE
Concerned about debug messages on startup

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1620]
Turned on debug and found these messages are they normal or does something look wrong here wasn't sure so thought I'd ask?

Debug messages - https://pastebin.com/5dXe1tBP

Citizens.yml - https://pastebin.com/Gz0SNcDL
saves.yml - https://pastebin.com/7vkqDA5D
latest.log - https://pastebin.com/bT828ff0

The output of command `/version` on my server is: **(PLEASE FILL IN)**

This server is running Paper version git-Paper-459 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

[18:02:09 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1592)
[18:02:09 INFO]: Website: http://www.citizensnpcs.co

**Comment by fullwall** [comment]
They are normal, they debug skin loading.

**Comment by axemwa** [comment]
Ah ok thanx for explaining.
That's strange I swear that account was still active on the statusblock on my 1.12.2 version of this server

**Comment by axemwa** [comment]
wow his name must have expired
