### ISSUE TITLE
Citizens: WorldGuard/Mob-Spawning prevents NPCs?

### ISSUE THREAD

**Issue by WanderingRaven** [CitizensDev/Citizens2#1621]
I have had many NPCs created for some time now.  Recently I updated to 1.13.2 and updated all the corresponding plugins (including Citizens).  Everything has been running fairly smooth until I installed WorldGuard and set up some regions and flags.  The first thing I did (to protect players at my spawn area from being bombarded by mobs) was to set mob-spawning to deny.  Immediately I noticed almost all of my NPCs were gone.  They still showed up in lists, and I was able to tphere them to me OUTSIDE the region.  Not sure why I couldn't get them to come up with mob-spawning off, I removed the flag.  That's when things got crazy.  It seemed like all 150+ NPCs teleported to the world spawn and my Citizens saves.yml file was overwritten for every single NPC's coords.  I was able to get an older version (3 days ago) and reset coords for about 90% of the NPCs, so will have to manually move only about 20 of them.  I'm not sure how to recreate this or if anyone else has had this issue.  All other traits and things like skins and names are all fine.  Thanks for the help, hope that was enough info. 

VERSIONS:
This server is running CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens version 2.0.24-SNAPSHOT (build 1592)
CitizensCMD version 2.1
WorldGuard version 7.0.0-SNAPSHOT;0dc5781

**Comment by mcmonkey4eva** [comment]
This would be an issue with WorldGuard (blocking NPC spawns - they should be checking for "NPC" metadata). We can't do anything to fix it within Citizens.
