### ISSUE TITLE
Quick Feature request : delay variable on /npc glowing

### ISSUE THREAD

**Issue by Ferocimo** [CitizensDev/Citizens2#1622]
Hello,

My suggestion is very simple : introducing a timer on the /npc glowing command.

For instance : /npc glowing 30
Makes the NPC glowing for thirty seconds.

This would be of great help for quest making : a NPC you have to kill is highlighted by the quest plugin for a few seconds using this command.

To make it perfect it would be nice to be able to specify NPC ID in the command : /npc glowing 6021 30
Would make the NPC 6021 glow for thirty seconds. 

If timed glowing isn't possible in a near future please let me know anyway so we can work on a way to circumvent the issue using some "glitchy" ways (needless to say, we would rather not...).

Thank you.

**Comment by mergu** [comment]
Heya, this is best suited for Denizen, an open-source scripting engine that directly hooks into Citizens. Any sort of interactions beyond "stand there and look pretty" are best for Denizen. Although it would be nice to be able to specify a duration on the glowing effect in Citizens, seems like a reasonable request.

For help questing and scripting Citizens beyond their current limitations, feel free to join us in the official Denizen/Citizens support discord: https://discord.gg/Q6pZGSR

Also: Citizens commands already support specifying an id using the `--id #` flag
