### ISSUE TITLE
NPCs doesnt move head, doesnt walk, and dissapears after reload. 

### ISSUE THREAD

**Issue by Florenthz** [CitizensDev/Citizens2#1626]
Hi there, I have this problem... When I create a new npc, it doesnt move the head, only the first second, later the npc does nothing doesnt walk, doesnt equip... If I try to make it walk using /path and placing some waypoints, npc doesnt move, only when I use /npc skin [name] npc walks only to the next waypoint... And if I try to equip, npc takes my item but I cant see it in its hand...
This is my config.yml:
https://dl.dropboxusercontent.com/s/pv73q93c2ce9n9z/config.yml
And this is the log that I found:
https://dl.dropboxusercontent.com/s/lzbzwkri7gxcfdl/log.txt
Excuse my wrong english...
Help please and greetings

**Comment by mcmonkey4eva** [comment]
make sure you're running
Latest Citizens from: http://ci.citizensnpcs.co/job/Citizens2/
and latest Spigot from: https://www.spigotmc.org/wiki/buildtools/

**Comment by Florenthz** [comment]
Im using Citizens-2.0.24-b1595.jar
But do I have to download Buildtools?
I do know how to download lastest Spigot in that link friend

**Comment by mcmonkey4eva** [comment]
You must use BuildTools. If you use any other method to acquire Spigot, you've likely given yourself malware. BuildTools is the only official distribution of Spigot and any other distribution is forbidden by law.
(there are sort-of exceptions for forks like Paper).

**Comment by mcmonkey4eva** [comment]
Also if you've used PlugMan or the `/reload` command or anything like that: that's a problem, can't do that.

**Comment by Florenthz** [comment]
I use /restart and I dont know something about Plugman

**Comment by Florenthz** [comment]
Where I have to place BuildTools,jar?

**Comment by mcmonkey4eva** [comment]
read the wiki page's instructions

**Comment by Florenthz** [comment]
Friend... I ran BuildTools.jar in Gut Bash... What I have to do now?

**Comment by Florenthz** [comment]
I have installed Citizens-2.0.24-b1595
and latest Spigot from BuildTools... but I have the same problem

**Comment by Florenthz** [comment]
03.12 20:53:15 [Server] INFO Florenthz issued server command: /citizens reload
03.12 20:53:15 [Server] WARN java.lang.IllegalArgumentException: unable to find valid entity superclass for class class net.citizensnpcs.nms.v1_13_R2.entity.WolfController$EntityWolfNPC
03.12 20:53:15 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.registerEntityClass(NMSImpl.java:800)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.util.NMS.registerEntityClass(NMS.java:222)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.<init>(AbstractEntityController.java:16)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.entity.MobEntityController.<init>(MobEntityController.java:21)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.entity.WolfController.<init>(WolfController.java:29)
03.12 20:53:15 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
03.12 20:53:15 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
03.12 20:53:15 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
03.12 20:53:15 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03.12 20:53:15 [Server] WARN at java.lang.Class.newInstance(Class.java:442)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.npc.EntityControllers.createForType(EntityControllers.java:20)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:103)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:50)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.Citizens.reload(Citizens.java:362)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:44)
03.12 20:53:15 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.12 20:53:15 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03.12 20:53:15 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.12 20:53:15 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
03.12 20:53:15 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
03.12 20:53:15 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
03.12 20:53:15 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
03.12 20:53:15 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
03.12 20:53:15 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648)

**Comment by Florenthz** [comment]
And when I use /citizens reload
almost all NPCs are deleted

**Comment by mcmonkey4eva** [comment]
You might have a different plugin messing up entities - can you post a plugin list?
