### ISSUE TITLE
WARN's spamming console after installing latest dev build of Citizens 1597

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1628]
[WARNS](https://pastebin.com/CFeGsZJE)
[Latest.log](https://www.dropbox.com/s/chwy69umhu9rvk8/latest.log?dl=1)

The output of command `/version` on my server is: **[22:11:10 INFO]: This server is running Paper version git-Paper-474 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **[22:11:33 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1597)**

**Comment by mcmonkey4eva** [comment]
Update your Spigot build, latest Citizens dev is compatible only with latest Spigot.

**Comment by axemwa** [comment]
Are you sure? Looks more like a pathfinding issue... Is paper no longer going to be supported?

**Comment by mcmonkey4eva** [comment]
Paper is or will be supported if they build against latest spigot or failing that, whenever they do build against the latest spigot release.

**Comment by mcmonkey4eva** [comment]
If latest paper is non-functional on this build you can use the previous build (1596) until they update.

**Comment by axemwa** [comment]
Yeah will do that now, thanks for replying

**Comment by mcmonkey4eva** [comment]
eh, sorry, meant 1595
Apparently a stray second build was made, so actually need to jump back 2.

**Comment by axemwa** [comment]
thanx it working now

**Comment by axemwa** [comment]
Ah ok if it's something paper has to fix should I create a new issue on paper issue tracker and get paper devs to look at it and reference this issue or do you think they will fix it anyway at some point?

**Comment by mcmonkey4eva** [comment]
The developers of paper have to do it, but it's not something you need to make an issue for probably. Literally Paper just needs to update their included copy of Spigot (since Paper is a fork of Spigot).

**Comment by axemwa** [comment]
Latest paper fixed the issue :) https://papermc.io/ci/job/Paper-1.13/changes
