### ISSUE TITLE
Using /npc sit seems to create a no named NPC ID that's selectable when attempting to reselect the NPC that's sitting, is this an invisible minecart?

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1631]
Explanation:
When using /npc sit, sometimes when attempting to re select the NPC it selects an empty NPC name and if u remove it the NPC stops sitting. (if you can't reproduce the issue with this method try the method below additionally)
I also noticed that when an NPC is sitting and you do the reload command he ends up 1 block higher than he was before, in general when NPC's are sitting it also looks like there's a bit of a gap from the ground where as it should be flush shouldn't it?

The output of command `/version` on my server is: **This server is running Paper version git-Paper-475 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1599)**

[Citizens.yml](https://pastebin.com/kWksfCiV)
[latest.log](https://www.dropbox.com/s/sz91dve0qr9bni4/latest.log?dl=1)
[WARN's](https://pastebin.com/Byuq2LWa) from /npc sel
Paste of no named ID whilst facing the same NPC
![image](https://user-images.githubusercontent.com/37608633/49696358-e3604b00-fbf8-11e8-9463-4a5ad0dea914.png)

**Comment by mcmonkey4eva** [comment]
It's an invisible armor stand. It's used for the sitting handling.

For the raising up over time: update Denizen to latest dev build (`/npc sit` is Denizen powered functionality)

**Comment by axemwa** [comment]
I updated to latest denizen build from this page http://ci.citizensnpcs.co/job/Denizen_Developmental/
but I can still select the armorstand for some reason, also the NPC sitting doesn't raise overtime it happens right after "/citizens reload"

Also I noticed there's also a denizen builds page here too http://ci.citizensnpcs.co/job/Denizen/
did I choose the right one? I use this one http://ci.citizensnpcs.co/job/Denizen_Developmental/

**Comment by mcmonkey4eva** [comment]
The latest dev build (from the link you used) is fine. (the other link is release builds).
Does it still raise when you reload? (Not counting however high it's already raised to)

The armor stand is just selectable. You can right click NPCs with a stick to more carefully select NPCs when there's multiple nearby.

**Comment by axemwa** [comment]
This seems to happen not only after reload but after restart aswell, I'm fairly certain anyway

**Comment by axemwa** [comment]
I'm still having this issue only now whenever I attempt to sit he sits in the air as before straight away

Using these

Citizens version 2.0.24-SNAPSHOT (build 1612)
Website: http://www.citizensnpcs.co
Authors: aPunch and fullwall
__________________________________________________
Sentinel version 1.7.6 (build 208)
 Author: mcmonkey
___________________________________________________
This server is running Paper version git-Paper-507 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
@axemwa then... move the NPC into the ground. Use `/npc sit -c` or `/npc sit --location <...>` or place the NPC on a stair block to make a nice seat.
Also armor stands are selectable as a glitch that's just kinda fine to leave in. Be careful what NPC you select (you can right click with a stick to select NPCs more easily/directly)

**Comment by axemwa** [comment]
Cool managed to get it to work with `/npc sit--location -192,62.5,259,world` 
Using `/npc sit -c` they seem to float still
