### ISSUE TITLE
NPC skins turning into Steve/Alex

### ISSUE THREAD

**Issue by Scabista** [CitizensDev/Citizens2#1632]
- Citizen player skins seem to load/unload, player side randomly. This will turn them into, or load them as steve/alex. Some players seem to report it happens more for npcs that are further away when they enter an area with npcs.
- https://gist.github.com/Scabista/c20c9534862ff2ae5c9f4b67a210f13f (No related console errors, or output)

- FOR LAG RELATED ISSUES: 35g memory. 100ish global npcs.

The output of command `/version` on my server is: https://imgur.com/jXJ6XD3
The output of command `/version citizens` on my server is: https://imgur.com/a/P3bNGeG

**Comment by mcmonkey4eva** [comment]
Both your Spigot jar and your Citizens jar are a bit outdated. Should probably update them both to start.

Some info on this wiki page might be relevant: https://wiki.citizensnpcs.co/Skins
But if I understand correctly it sounds like you're encountering an issue we've had in the past but that hasn't been reported in a while. I don't know offhand if it was ever completely fixed.

**Comment by mcmonkey4eva** [comment]
Run latest Citizens and latest Spigot 1.12.2

I didn't say update Minecraft, that's not required at the moment (1.13 is still new and is a tough change so we fully dual-support 1.12.2 and 1.13.2)

**Comment by axemwa** [comment]
I get this problem aswell in current latest dev/jenkins builds of citizens and I have to use /citizens reload to fix the skins. Sometimes the skins will fix them selves when either facing them at a certain angle or leaving and reentering the chunk

**Comment by mcmonkey4eva** [comment]
@LeafyMitsuwa you're running a version of Citizens that's about 1.5 years old now.

**Comment by axemwa** [comment]
This is what it's doing for me
https://youtu.be/T7hmV-yu6LY

**Comment by axemwa** [comment]
Using debug I get this on server start https://pastebin.com/B6JVYPt6

**Comment by Scabista** [comment]
Reload usually corrects it, at least for the person using the command, This isn't a fix though. What npcs have skin issues is player side, so some players may rarely experience the problem, while others get it more often. A player may see a npc with their skin, while another will see the same npc with a Steve/Alex skin.

**Comment by Scabista** [comment]
My console output? Lol. Well, I enabled debug and this is literally all that comes up in my console during launch.
https://i.imgur.com/6smvTDb.png

**Comment by axemwa** [comment]
Heres a log when the npc skins weren't working https://pastebin.com/HH2dKnZT
Leaveing and re-entering the chunk brings the skin back

**Comment by axemwa** [comment]
On another note when this message apppeared in console
Spawned id 159 due to chunk event at [-12,15]
if those are co-ordinates x & y I tp'd there and there's nothing there

**Comment by mcmonkey4eva** [comment]
Those are chunk coordinates (not block coordinates)
Which NPCs (names+skinnames+IDs) were missing skins?
At what point during that log (throughout the time the server was running, or only for part of it?)

**Comment by axemwa** [comment]
Pretty sure it was ALL of the NPC's in that chunk that were missing textures for their skin.

The NPC's were

![image](https://user-images.githubusercontent.com/37608633/50215172-1e6d3600-03d2-11e9-8d28-80f10e99a237.png)

I thought I'd also mention that all those NPCs are inside the main "world" spawn area which chunk stays loaded (that area is also in a worldguard region called spawn)

**Comment by axemwa** [comment]
Here's my [saves.yml](https://pastebin.com/WLBniTic)

**Comment by Scabista** [comment]
I wonder if this issue could have anything to do with having the free version?

**Comment by mergu** [comment]
It doesn't. There is no 'premium' version of Citizens.

From the spigot page:
```
This is posted as a premium resource to motivate the continued development of the plugin. If you would not like to contribute to development you are welcome to download the same versions for free here but please read 'Why premium?' below for more information.
```

**Comment by Scabista** [comment]
Just thought I'd mention this is still an issue.

**Comment by mergu** [comment]
So I can actually fairly reliably replicate skin loading issues in Citizens:
- [ ] Spawn an npc, equip a skin to it, walk straight back in a line watching it until it despawns
- [ ] Mark the despawn boundary
- [ ] If you walk inside the boundary while looking at the npc, loads fine every time:

![image](https://user-images.githubusercontent.com/29823405/51088565-3a44cd00-172f-11e9-83ea-62fb24d003b9.png)

- [ ] If you walk backwards (or straight down) into the boundary then turn to look at the npc, skin is usually steve/alex:

![image](https://user-images.githubusercontent.com/29823405/51088586-855ee000-172f-11e9-964f-4aa121bab42d.png)

So seems to have something to do with players not receiving the skin if they're not directly looking at the npc when it's spawned

**Comment by axemwa** [comment]
A temporary fix for this could be to add a new command `/citizens reload skins` and an option in config to apply the command when a player joins and/or when a player is in close proximity to an NPC. Only thing is you would have to do it in a way where it doesn't temporarily show the armorstand when it's reloading which players might notice

**Comment by axemwa** [comment]
Or can these settings below be tweaked somehow so that NPC skins show properly most of the time?
`  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0`

**Comment by axemwa** [comment]
Using these settings keeps the skins updated, doing this I didn't notice any major lag, I set retry delay to 20 so that if it fails then it will try to apply the skin every second until it is applied. I also set max-retries to 10 in the case that it constantly retries to apply the skin even if it's set at least it will only do it 10 times.
Lemme know if this temp solution works for anyone else

>   skins:
    max-retries: 10
    retry-delay: 20
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 50

**Comment by mergu** [comment]
Please don't spam issues. If you have more to add, edit your previous post.

**Comment by axemwa** [comment]
Sorry was trying to discuss a possible temp solution, I edited it together

**Comment by mcmonkey4eva** [comment]
I'm actually not able to replicate this while testing on 1.14, at least not via @mergu 's method (which I've previously verified to consistently produce a skin load failure in 1.13)

**Comment by SlimeDog** [comment]
Spigot 1.14
MC client 1.14.1-pre2
ViaVersion 2.1.0-1.14.1-pre2
Citizens 2.0.25-b1675, default configuration (in particular, retry-delay:120)

With this configuration, I am unable to replicate morgu's method, or any of my previous failure modes, including Alex at connection until player moved. Maybe this issue has been resolved.

**Comment by axemwa** [comment]
I getting this issue in 1.13.2 still but haven't tested in 1.14+ yet, definitely a client-side problem i reckon

**Comment by richiedevs** [comment]
got same issue here aswell
