### ISSUE TITLE
Citizens 2.0.24 snapshot

### ISSUE THREAD

**Issue by berrydelvy99** [CitizensDev/Citizens2#1633]
Hi, I have a problem: when I send the command /npc create (npcname) this appears to me:

"an internal error occurred while attempting to perform this command"

Thanks in advance!
![cattura](https://user-images.githubusercontent.com/42221608/49748375-c6358600-fca5-11e8-888b-44220dbae6a0.PNG)

**Comment by mcmonkey4eva** [comment]
Update spigot. You're running 1.13, need to be running 1.13.2
