### ISSUE TITLE
Skills not showing

### ISSUE THREAD

**Issue by ianguuima** [CitizensDev/Citizens2#1634]
I can't set skins in my npcs.
Is showing an error that I never had before: https://ghostbin.com/paste/d2ocx

The output of command `/version` on my server is: http://prntscr.com/ltbxzo
The output of command `/version citizens` on my server is: http://prntscr.com/ltby1k

**Comment by SXRWahrheit** [comment]
Is your server in online-mode? That appears to be an authentication issue. If your server is in online-mode, you could just be getting throttled.

https://wiki.citizensnpcs.co/Skins

**Comment by ianguuima** [comment]
No, isn't. But it always work perfectly, just now isn't working

**Comment by SXRWahrheit** [comment]
https://wiki.citizensnpcs.co/Cracks
