### ISSUE TITLE
NPCs disappear with Multiverse-Core

### ISSUE THREAD

**Issue by DragoSpiro98** [CitizensDev/Citizens2#1636]
I have two npcs for the shop, when I go to another world using Multiverse-Core (for exemple I go to Nether), and if anyone stay in the normal world, the npcs disappear. How can I solve this problem ? I'm not using BungeeCord.
(Sorry for my bad english)

![cattura](https://user-images.githubusercontent.com/33783684/50090437-cd5e1600-0208-11e9-8359-7c16f285bef0.PNG)

**Comment by mcmonkey4eva** [comment]
Update.
You're running a 4+ year old server with a 4+ year old copy of Citizens.
We cannot give functional support to any part of that.

At minimum update Citizens, but also see: https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by DragoSpiro98** [comment]
> Update.
> You're running a 4+ year old server with a 4+ year old copy of Citizens.
> We cannot give functional support to any part of that.
> 
> At minimum update Citizens, but also see: https://wiki.citizensnpcs.co/Minecraft_1.8

Thanks for help, the latest version of Citizens is the 2.0.24 ? https://dev.bukkit.org/projects/citizens/files/2636251

**Comment by mcmonkey4eva** [comment]
Builds of Citizens are at http://ci.citizensnpcs.co/job/Citizens2/

**Comment by DragoSpiro98** [comment]
> Builds of Citizens are at http://ci.citizensnpcs.co/job/Citizens2/

If I use spigot 1.13.2, I can't access with oldest Minecraft versions (1.8,1.9...), I'm using 
![cattura](https://user-images.githubusercontent.com/33783684/50152760-d7454f00-02c4-11e9-9c8f-b1949e8de633.PNG)

This are the latest versions of all three plugins.
So how can I use spigot 1.13.2 ?

**Comment by mcmonkey4eva** [comment]
Spigot 1.12.2 is also reasonably usable, being still a recent Spigot version.

ViaBackwards dev is working on an update to 1.13.2 but hasn't released it yet
