### ISSUE TITLE
NPC Doesn't Return to Wandering After Exiting Wander Region

### ISSUE THREAD

**Issue by Konvett** [CitizensDev/Citizens2#1637]
- Issue: When an NPC is given the sentinel trait, they lose their wandering settings. I've created an NPC, set a wandering Xradius and Yradius and defined a 1-block region. The NPC stays within the region initially, but after they enter combat, they won't return to the region or resume wandering.
- Server log: https://pastebin.com/qAMukhMP
- Citizens config: https://pastebin.com/BuyAy8Qp

The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-078a7f5-7fa173e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1599)**

**Comment by mcmonkey4eva** [comment]
Issues with Sentinel go on the Sentinel page: https://github.com/mcmonkeyprojects/Sentinel/issues

**Comment by mergu** [comment]
This isn't a Sentinel issue. This is a Citizens issue - NPCs outside of their wander region get stuck and cannot navigate back.

**Comment by fullwall** [comment]
Latest build should return to the closest region now.
