### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SlickNicky10** [CitizensDev/Citizens2#1638]
The output of command `/version` on my server is: This server is running Paper version git-Paper-1593 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.22-SNAPSHOT (build 1498)

I am using a server host called Minehut. They provide free player server hosting but you can get more feature by paying Credits. Their website is https://minehut.com . The issue I'm having is a memory leak. After 3 hours of uptime the server runs out of memory and the tps comes to a grinding halt, ive even come online to it being at 2.7TPS before. Some of the information you asked me to provide I simply cannot provide due to how Minehut works. If I ever can get logs I will reference them though.

**Comment by mcmonkey4eva** [comment]
Will reopen when you reply with further info
