### ISSUE TITLE
Server Crash with last Paper build

### ISSUE THREAD

**Issue by ZombieZone69** [CitizensDev/Citizens2#1639]
Hello, in advance sorry for my english, I use a translator. 
The problem comes from Citizens plugin combined with the latest version of Paper.
Indeed we must have at least 1 npc on the server and then when a player rejoin the server, he crash immediately.

- The output of command `/version` on my server is: 
Paper version git-Paper-486 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- The output of command `/version citizens` on my server is: 
Citizens version 2.0.24-SNAPSHOT (build 1598)
- Server logs during start : [https://pastebin.com/QEQ6wbKG](url)
- Citizens config : [https://pastebin.com/T7XCfe5Y](url)
- Crash report : [https://pastebin.com/pALRpfp9](url)

**Comment by mergu** [comment]
This is already fixed. Always update before making an issue: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

Please close this issue if updating fixes your problem

**Comment by ZombieZone69** [comment]
sorry :'(
