### ISSUE TITLE
When naming an NPC using more than one bold text removes the color from the 1st word of the name

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1640]
When (re)naming an NPC using more than one bold text removes the color from the 1st word 

Eg:
&e&lMike &8&lNolan

=

![image](https://user-images.githubusercontent.com/37608633/50188233-ce11bc00-0370-11e9-9b67-8b7627eb58d5.png)
(1st word should be yellow)

The output of command `/version` on my server is: **This server is running Paper version git-Paper-486 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1604)**

**Comment by mergu** [comment]
`&e&lMike &8&lNolan` = 18 characters long

Minecraft usernames are limited by 16 characters, meaning the first two get chopped off:
`&lMike &8&lNolan`

Citizens can get around this by using scoreboard magic. Make sure `player-scoreboard-teams` is enabled in your config.

We see a lot of cases where another plugin using scoreboards is treating npcs as normal players which will mess this up. Particularly FeatherBoard is bad about this. This is up to the plugin at fault to fix. Read more on plugin conflicts here: https://wiki.citizensnpcs.co/Plugin_Conflict

If it's a plugin conflict, this should be closed and you need to open an issue with the plugin at fault.

**Comment by mcmonkey4eva** [comment]
That glitch can happen even with perfectly functional scoreboard control.

Since it's a **color code** being cut off, it's possible that color code just got set into the prefix (and is doing nothing of use there, since it's not part of the base name).

One workaround option (if scoreboard control is fine) is to eat space somewhere in the base name - roughly 4 or 6 characters worth, to move `Mike` into the prefix (and `Nolan` be the base name).

So `&e&lMike &r&r&r &8&lNolan` or something like that.

**Comment by axemwa** [comment]
Ok thanx for the tips guys but does that mean I should close this and do the method mentioned instead, or should I keep the issue report open if it's going to be fixed?

**Comment by mcmonkey4eva** [comment]
Eh... both?
Try the solution mentioned for now, and we may in the future be able to automate corrections to color coding stuff.

**Comment by axemwa** [comment]
Ok, by both did u mean try the solution and close the issue report or try the solution and keep the report open?

**Comment by mergu** [comment]
Try the solution and keep this open
