### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by M4rtyn4** [CitizensDev/Citizens2#1641]
When I create npc server crashes. 
You cant connect to server after reboot. Every time someone tries to connect server crashes. You have to remove Citizens and everything goes back to normal. :(

Latest Spigot 1.13.2-R0.1-SNAPSHOT
Citizens v2.0.24-SNAPSHOT (build 1598)

[https://pastebin.com/WRaTne3v](url)

**Comment by mergu** [comment]
This is already fixed. Always update before making an issue: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

Please close this issue if updating fixes your problem

**Comment by M4rtyn4** [comment]
Thanks :) Sorry for being noob
