### ISSUE TITLE
citizens may have crashed my server (no such field error)

### ISSUE THREAD

**Issue by ozm8** [CitizensDev/Citizens2#1643]
Okay so i updated to the latest spigot and now it seems i get crashes which i think is to do with citizens. I even tried updating to the latest dev citizens 2 but no joy.

I'm on spigot 1.13.2 and using Citizens-2.0.24-b1604
Here is the crash report:  https://pastebin.com/zKrWrZxh

**Comment by mcmonkey4eva** [comment]
That crash report is **not** from latest Citizens, it's from a much outdated Citizens (1592).
Update to latest Citizens (which is 1604, which is not what you're running) and at the same time latest Spigot (which is also outdated in that log)
