### ISSUE TITLE
Even though tablist for citizens NPC's is disabled their names flash in tablist at certain times

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1646]
Citizens [config.yml](https://pastebin.com/8Pjm0e56)

Citizens NPC names flash in the tablist when sprinting and/or jumping accross chunks and sometimes when just going across a few blocks could be lag related maybe? Here is a video of the issue occurring
https://youtu.be/O80HvSwRGY4

Originally posted in this plugins thread - https://www.spigotmc.org/threads/animated-tab-tablist.268246/page-28#post-3260876

Authors response saying it could be citizens doing it - https://www.spigotmc.org/threads/animated-tab-tablist.268246/page-28#post-3261031

Could be the same as this issue mentioned last year
https://github.com/CitizensDev/Citizens2/issues/1337

The output of command `/version` on my server is: **This server is running Paper version git-Paper-488 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1604)**

**Comment by mcmonkey4eva** [comment]
This is a known + unfixable issue in all minecraft versions starting with 1.7.10

Basically: Mojang altered the way Minecraft player entities work to **require** a player entity be in the tab list to even be visible in the 3d world.
This is a problem for NPCs, so we managed to form the sort-of workaround for it that we put the NPC in the tablist, spawn the NPC, then remove it from the tablist, all within a fraction of a second, which makes it work without having to retain the NPC in the tablist. The side effect of this is, unfortunately, NPCs will momentarily flash into and out of the tab list when they're spawning in.

**Comment by axemwa** [comment]
Isn't there a way to make the NPC's join in vanish mode so that they dion't show up in tablist if that makes sense. Wouldn't that be possible?
