### ISSUE TITLE
Server shutdown after spawning npc [Paper-spigot 1.13.2]

### ISSUE THREAD

**Issue by DerFlamer12332** [CitizensDev/Citizens2#1649]
Hi, sorry for my bad english..
The Server start normally and i can spawn a Villager Npc for example.
The Problem is if i spawn a npc without the --type: /npc create [name]
My server shutdown instantly..

I hope you can tell me the problem.
Thank you and have a nice day!

Server Logs: https://pastebin.com/yZmVFq2M
Citizens Config: https://pastebin.com/5wubbXhq

The output of command `/version` on my server is: **(
![2018-12-28_13 12 43](https://user-images.githubusercontent.com/46220338/50515890-ad034680-0aa7-11e9-9301-340334efa9ca.png)
)**
The output of command `/version citizens` on my server is: **(
![2018-12-28_13 12 55](https://user-images.githubusercontent.com/46220338/50515897-b4c2eb00-0aa7-11e9-9be9-8d5ef4cd9471.png)
)**

**Comment by mcmonkey4eva** [comment]
You are running an outdated copy of Citizens. Please update: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by DerFlamer12332** [comment]
Thanks for the fast answer :) my bad
