### ISSUE TITLE
/npc skin -t problem

### ISSUE THREAD

**Issue by gilles353** [CitizensDev/Citizens2#1651]
Hello,
I do not feel like posting the config since it is the default one.
My problem is that when i use /skin -t (args) it says that a skin name is required.
This i also get when i just have more then 2 args. /skin x y
So i guess the feature is broken? Because i'd like to use my own skin files for my npc's

**Comment by mcmonkey4eva** [comment]
Uh... See skin information on the wiki page: https://wiki.citizensnpcs.co/Skins

**Comment by gilles353** [comment]
I've read the wiki. What i'm saying is that the command does not work.

**Comment by mcmonkey4eva** [comment]
It sounds more like you aren't entering the command correctly.
If you believe my assessment is incorrect (ie, you are entering it correctly): Please post exactly what you've tried entering. Also post the output of `/version citizens`.

**Comment by gilles353** [comment]
Version 2.0.24-SNAPSHOT (build 1591)
/npc skin -t [signature]
I think this is correct.
Even if i do /npc skin -t [uuid] [signature] it does not work.
On the wiki it says /npc skin -t [uuid] [data] [signature].
I have no clue what data means because of the poor documentation.
I tried to put the npc name, .... and everything i could think of in there and still it does not work.

**Comment by gilles353** [comment]
And i probably have an outdated build because i have not bought the spigot version. I just donwloaded the free version on bukkit.

**Comment by gilles353** [comment]
Nevermind. I figured it out. It seemed that the plugin magic's NPC function created some errors in the version of spigot i was using, that kept me from using some /npc commands. I solved it by getting a new spigot from the buildtools.

**Comment by mergu** [comment]
Awesome, sounds good. If all is fine feel free to close the issue.

**Comment by gilles353** [comment]
Ok. Still, thanks for trying to help. :p
