### ISSUE TITLE
Can't see NPC's only if I do /citizens reload ?

### ISSUE THREAD

**Issue by DennisFusha** [CitizensDev/Citizens2#1654]
-Well I don't see any NPC's I have to do /npc reload to see them but if I tp to antoher place the NPC's that should be there and then I have to do /npc reload again but then If I go back to the first place their are gone again....

The output of command `/version` on my server is:
The output of command `/version citizens` on my server is:
![image](https://user-images.githubusercontent.com/29520150/50595091-562eb000-0e9f-11e9-8298-e2e8215af34c.png)

**Comment by mcmonkey4eva** [comment]
Update Spigot and Citizens both to latest releases (Spigot latest 1.12.2 off buildtools, Citizens latest dev build from jenkins CI).

**Comment by DennisFusha** [comment]
Could you send me the latest 1.12.2 please?
Just the jar file because i'm not going to do buildtools because I don't know how lmao

**Comment by mcmonkey4eva** [comment]
I cannot send you that, as it's illegal to distribute copies of Minecraft outside of official channels. BuildTools is Spigot's way of legitimately distributing server jars.

If you don't know how, learn how: https://www.spigotmc.org/wiki/buildtools/

**Comment by mcmonkey4eva** [comment]
Can you post updated output of `/version` and `/version citizens`

**Comment by DennisFusha** [comment]
![image](https://user-images.githubusercontent.com/29520150/50662744-c1fc4000-0fa7-11e9-815e-6fcf54b5b8ca.png)

**Comment by DennisFusha** [comment]
And no I will not update to the latest 1.12.2 because the latest one is really buggy and kickes you every 2 min

**Comment by mcmonkey4eva** [comment]
`And no I will not update to the latest 1.12.2`
Then no we will not help with your issue.

If you have bugs with latest 1.12.2 spigot, contact spigot team for support with that.

**Comment by DennisFusha** [comment]
Lmao I already contacted them and they say they aren't fixing it because it's an older spigot,
