### ISSUE TITLE
Invisible NPC's

### ISSUE THREAD

**Issue by Crack3dC0d3** [CitizensDev/Citizens2#1655]
Isue:

Every single NPC in my server is invisible. Those who have armor are invisible but the armor is not. 
When i update the skin with /npc skin It shows the NPC again. But when i restart my server its gone

And No i dont use /reload that command is very very bad.

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1581)

CONFIG: https://pastebin.com/qeH4hBfp
Log: Nothing

**Comment by mcmonkey4eva** [comment]
Update Spigot to latest 1.12.2 version: https://www.spigotmc.org/wiki/buildtools/
Update Citizens to latest dev build: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by DennisFusha** [comment]
Happens to me to
