### ISSUE TITLE
/npc name not working

### ISSUE THREAD

**Issue by AloneSpace** [CitizensDev/Citizens2#1656]
By the topic, when I typing /npc name it doesn't visbility name

I use Citizens lastest-build
and paper-spigot1.13.2

**Comment by mcmonkey4eva** [comment]
`Citizens lastest-build` <-- that is not remotely close to a version number.
`paper-spigot1.13.2` <-- that is _part_ of a version number but not all of it.
Use `/version` and `/version Citizens` in-game to find the full version output of the server and plugins.

------

This functionality (`/npc name`) depends on Citizens scoreboard control, which tends to often be broken by unrelated plugins altering the server's scoreboard layout.
See here for info on how to fix trouble with that: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by mcmonkey4eva** [comment]
@SpicyYoze 
the `"NPC"` metadata check is sufficient for Citizens.
Can you please post a new issue for this? (As you aren't the original poster, and have a much more valid issue than the original poster, your issue we can probably actually fix)

**Comment by nossr50** [comment]
Yeah the scoreboard code came in after I left mcMMO, since returning I haven't had time to look at it and understand its nuances. So you're saying mcMMO is not changing the main scoreboard and this is a problem?

**Comment by mcmonkey4eva** [comment]
Yep.
It's made a separate scoreboard and moved players over to that, which means alterations to the main scoreboard (including the changes Citizens applies to put longer nameplates on NPCs) are not visible to players.

**Comment by nossr50** [comment]
So players can only have one active scoreboard, am I understanding that right?

Would this problem be solved if mcMMO used the 'main scoreboard'? I'm not sure I understand the difference yet so I'm going to have to go read up on it.

And to be honest, I'm not sure I'm a fan of mcMMO's scoreboard implementation, I might make it opt-in rather than how it currently functions (they are kind of shoved onto you in mcMMO currently).

From what I've gathered though, you guys are using the 'main scoreboard' to make names longer than they can be normally, and mcMMO is switching a players scoreboard so players never get to see these longer names.

**Comment by mcmonkey4eva** [comment]
`So players can only have one active scoreboard, am I understanding that right?`
Yep!
`Would this problem be solved if mcMMO used the 'main scoreboard'?`
Yep! That might be a bit messy to code though depending on how the current setup of scoreboard code in mcMMO is structured overall.
`From what I've gathered though, you guys are using the 'main scoreboard' to make names longer than they can be normally, and mcMMO is switching a players scoreboard so players never get to see these longer names.`
Yep!

**Comment by nossr50** [comment]
Alright thanks for helping speed up my understanding of the scoreboard interactions. I'll see if I can make our plugins more compatible.

**Comment by nossr50** [comment]
There's a temporary solution to this problem for people running mcMMO and Citizens

Until I implement a fix on my end (mcMMO dev here) I suggest you open /plugins/mcMMO/config.yml

And edit the following options to be false, this will disable the mcMMO scoreboard system until a proper fix is in place.

```yaml
Scoreboard:
    Types:
        Rank:
            Board: false
        Top:
            Board: false
        Stats:
            Board: false
        Inspect:
            Board: false
        Cooldown:
            Board: false
        Skill:
            Board: false

**Comment by nossr50** [comment]
https://github.com/mcMMO-Dev/mcMMO/commit/3dca32a226db4e8ea2993200482461764594e4dd Should be fixed now boys
