### ISSUE TITLE
NPCs don't have skins!!

### ISSUE THREAD

**Issue by 21Callcops** [CitizensDev/Citizens2#1659]
- All of my NPCs won't show their skins. They only show steve skins. 
- No error or warning logs in console
- http://prntscr.com/m3f9fh  http://prntscr.com/m3f9ih

The output of command `/version` on my server is: **(http://prntscr.com/m3f9qu)**
The output of command `/version citizens` on my server is: **http://prntscr.com/m3f9ih)**

**Comment by SXRWahrheit** [comment]
https://wiki.citizensnpcs.co/Cracks

https://wiki.citizensnpcs.co/Skins

**Comment by mcmonkey4eva** [comment]
The most immediately relevant link here is: https://wiki.citizensnpcs.co/Minecraft_1.8
But the skins link (posted by wahr) may also be useful.
