### ISSUE TITLE
Npc, nothing happens.

### ISSUE THREAD

**Issue by Zazalanz** [CitizensDev/Citizens2#166]
I've downloaded npc, and valut. They are both version 1.8 and i got config and its runnig.
But when i type chat ./npc create Zazalanz
Nothing happens, not even if i type /npc its like the plugin dosent Work, but its installed. i can do /help Citizens and it shows me all the commands?
Help please.

**Comment by eglbogle** [comment]
I'm running into the same issue. If you want, you could use my startup log instead.

**Comment by eglbogle** [comment]
04.01 14:27:53 [Server] INFO Plugin is up to date!
04.01 14:27:53 [Server] INFO check loop complete, no different found. Checking lengths...
04.01 14:27:53 [Server] INFO Comparing 5 to 5
04.01 14:27:53 [Server] INFO Comparing 4 to 4
04.01 14:27:53 [Server] INFO Comparing 1 to 1
04.01 14:27:53 [Server] INFO Running check loop...
04.01 14:27:53 [Server] INFO New version: 1.4.5
04.01 14:27:53 [Server] INFO Original version: 1.4.5
04.01 14:27:52 [Server] INFO Checking for Updates ... 
04.01 14:27:52 [Server] INFO AWE WorldEdit wrapper active, edit session set to net.coreprotect.worldedit.v5.CoreProtectEditSessionFactoryv5 canceled.
04.01 14:27:52 [Server] Startup Done (7.063s)! For help, type "help" or "?"
04.01 14:27:52 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
04.01 14:27:51 [Server] INFO [WARNING] Could not create a PluginDependencyProvider for: WorldGuard! (Are you sure the type is valid?) - Only WorldGuard 6.0 and after are supported
04.01 14:27:50 [Server] INFO Enabling EchoPet v2.6.0-b28
04.01 14:27:50 [Server] INFO Enabling EssentialsChat v2.13.1
04.01 14:27:50 [Server] INFO enabled.
04.01 14:27:50 [Server] INFO Enabling Multiverse-Inventories v2.5-b335
04.01 14:27:50 [Server] INFO 2 - Portals(s) loaded
04.01 14:27:50 [Server] INFO - Version 2.4-b548 Enabled - By Rigby and fernferret
04.01 14:27:50 [Server] INFO Enabling Multiverse-Portals v2.4-b548
04.01 14:27:50 [Server] INFO Enabling EssentialsSpawn v2.13.1
04.01 14:27:50 [Server] INFO Enabled
04.01 14:27:50 [Server] INFO Accepted EditSessionFactory of type org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory from org.primesoft.asyncworldedit.worldedit
04.01 14:27:50 [Server] INFO You have an old version of the plugin. Your version: 1.3, available version: 1.3
04.01 14:27:50 [Server] INFO Enabling AsyncWorldEdit v1.3
04.01 14:27:50 [Server] INFO Disabling Citizens v2.0.14-SNAPSHOT (build 1195)
04.01 14:27:50 [Server] ERROR v2.0.14-SNAPSHOT (build 1195) is not compatible with Minecraft v1.7.10 - try upgrading or downgrading Citizens. Disabling.
04.01 14:27:50 [Server] INFO Enabling Citizens v2.0.14-SNAPSHOT (build 1195)
04.01 14:27:50 [Server] INFO Essentials: Using bPermissions2 based permissions.
04.01 14:27:50 [Server] INFO [Vault][Economy] Essentials Economy hooked.
04.01 14:27:50 [Server] INFO 1.7.10-R0.1-SNAPSHOT
04.01 14:27:50 [Server] INFO git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)
04.01 14:27:50 [Server] INFO Bukkit version format changed. Version not checked.
04.01 14:27:49 [Server] INFO Enabling Essentials v2.13.1
04.01 14:27:49 [Server] INFO 0 regions loaded for 'creative'
04.01 14:27:49 [Server] INFO 0 regions loaded for 'Storage'
04.01 14:27:49 [Server] INFO 0 regions loaded for 'world_the_end'
04.01 14:27:49 [Server] INFO 0 regions loaded for 'world_nether'
04.01 14:27:49 [Server] INFO 1 regions loaded for 'world'
04.01 14:27:49 [Server] INFO Loaded configuration for world 'creative'
04.01 14:27:49 [Server] INFO (creative) All fire spread is disabled.
04.01 14:27:49 [Server] INFO (creative) Lava fire is blocked.
04.01 14:27:49 [Server] INFO (creative) Lighters are PERMITTED.
04.01 14:27:49 [Server] INFO (creative) TNT ignition is PERMITTED.
04.01 14:27:49 [Server] INFO Loaded configuration for world 'Storage'
04.01 14:27:49 [Server] INFO (Storage) All fire spread is disabled.
04.01 14:27:49 [Server] INFO (Storage) Lava fire is blocked.
04.01 14:27:49 [Server] INFO (Storage) Lighters are PERMITTED.
04.01 14:27:49 [Server] INFO (Storage) TNT ignition is PERMITTED.
04.01 14:27:49 [Server] INFO Loaded configuration for world 'world_the_end'
04.01 14:27:49 [Server] INFO (world_the_end) All fire spread is disabled.
04.01 14:27:49 [Server] INFO (world_the_end) Lava fire is blocked.
04.01 14:27:49 [Server] INFO (world_the_end) Lighters are PERMITTED.
04.01 14:27:49 [Server] INFO (world_the_end) TNT ignition is PERMITTED.
04.01 14:27:49 [Server] INFO Loaded configuration for world 'world_nether'
04.01 14:27:49 [Server] INFO (world_nether) All fire spread is disabled.
04.01 14:27:49 [Server] INFO (world_nether) Lava fire is blocked.
04.01 14:27:49 [Server] INFO (world_nether) Lighters are PERMITTED.
04.01 14:27:49 [Server] INFO (world_nether) TNT ignition is PERMITTED.
04.01 14:27:49 [Server] INFO Loaded configuration for world 'world'
04.01 14:27:49 [Server] INFO (world) All fire spread is disabled.
04.01 14:27:49 [Server] INFO (world) Lava fire is blocked.
04.01 14:27:49 [Server] INFO (world) Lighters are PERMITTED.
04.01 14:27:49 [Server] INFO (world) TNT ignition is PERMITTED.
04.01 14:27:49 [Server] INFO Enabling WorldGuard v5.9
04.01 14:27:49 [Server] INFO Enabling trails v3.0
04.01 14:27:49 [Server] INFO 5 - World(s) loaded.
04.01 14:27:49 [Server] INFO Preparing start region for level 4 (Seed: -923120650499391506)
04.01 14:27:49 [Server] INFO Zombie Aggressive Towards Villager: true
04.01 14:27:49 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
04.01 14:27:49 [Server] INFO Arrow Despawn Rate: 1200
04.01 14:27:49 [Server] INFO Item Merge Radius: 2.5
04.01 14:27:49 [Server] INFO Item Despawn Rate: 6000
04.01 14:27:49 [Server] INFO Experience Merge Radius: 3.0
04.01 14:27:49 [Server] INFO Clear tick list: false
04.01 14:27:49 [Server] INFO Chunks to Grow per Tick: 650
04.01 14:27:49 [Server] INFO View Distance: 10
04.01 14:27:49 [Server] INFO Max TNT Explosions: 100
04.01 14:27:49 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
04.01 14:27:49 [Server] INFO Max Entity Collisions: 8
04.01 14:27:49 [Server] INFO Sending up to 5 chunks per packet
04.01 14:27:49 [Server] INFO Structure Info Saving: true
04.01 14:27:49 [Server] INFO Random Lighting Updates: false
04.01 14:27:49 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
04.01 14:27:49 [Server] INFO Alternative Hopper Ticking: false
04.01 14:27:49 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
04.01 14:27:49 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
04.01 14:27:49 [Server] INFO Wheat Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Sapling Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Pumpkin Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Mushroom Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Melon Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Cane Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Cactus Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Nerfing mobs spawned from spawners: false
04.01 14:27:49 [Server] INFO Replace Blocks: [1, 5]
04.01 14:27:49 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
04.01 14:27:49 [Server] INFO Engine Mode: 1
04.01 14:27:49 [Server] INFO Anti X-Ray: true
04.01 14:27:49 [Server] INFO Mob Spawn Range: 4
04.01 14:27:49 [Server] INFO -------- World Settings For [creative] --------
04.01 14:27:49 [Server] INFO Loading World &amp; Settings - 'creative' - Env: NORMAL - Type: FLAT &amp; seed: -923120650499391506
04.01 14:27:49 [Server] INFO Preparing start region for level 3 (Seed: -673665793505396094)
04.01 14:27:49 [Server] INFO Zombie Aggressive Towards Villager: true
04.01 14:27:49 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
04.01 14:27:49 [Server] INFO Arrow Despawn Rate: 1200
04.01 14:27:49 [Server] INFO Item Merge Radius: 2.5
04.01 14:27:49 [Server] INFO Item Despawn Rate: 6000
04.01 14:27:49 [Server] INFO Experience Merge Radius: 3.0
04.01 14:27:49 [Server] INFO Clear tick list: false
04.01 14:27:49 [Server] INFO Chunks to Grow per Tick: 650
04.01 14:27:49 [Server] INFO View Distance: 10
04.01 14:27:49 [Server] INFO Max TNT Explosions: 100
04.01 14:27:49 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
04.01 14:27:49 [Server] INFO Max Entity Collisions: 8
04.01 14:27:49 [Server] INFO Sending up to 5 chunks per packet
04.01 14:27:49 [Server] INFO Structure Info Saving: true
04.01 14:27:49 [Server] INFO Random Lighting Updates: false
04.01 14:27:49 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
04.01 14:27:49 [Server] INFO Alternative Hopper Ticking: false
04.01 14:27:49 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
04.01 14:27:49 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
04.01 14:27:49 [Server] INFO Wheat Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Sapling Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Pumpkin Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Mushroom Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Melon Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Cane Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Cactus Growth Modifier: 100%
04.01 14:27:49 [Server] INFO Nerfing mobs spawned from spawners: false
04.01 14:27:49 [Server] INFO Replace Blocks: [1, 5]
04.01 14:27:49 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
04.01 14:27:49 [Server] INFO Engine Mode: 1
04.01 14:27:49 [Server] INFO Anti X-Ray: true
04.01 14:27:49 [Server] INFO Mob Spawn Range: 4
04.01 14:27:49 [Server] INFO -------- World Settings For [Storage] --------
04.01 14:27:49 [Server] INFO Loading World &amp; Settings - 'Storage' - Env: NORMAL - Type: FLAT &amp; seed: -673665793505396094
04.01 14:27:48 [Server] INFO Loading World &amp; Settings - 'world_the_end' - Env: THE_END - Type: NORMAL &amp; seed: 7277526153272938071
04.01 14:27:48 [Server] INFO Loading World &amp; Settings - 'world_nether' - Env: NETHER - Type: NORMAL &amp; seed: 6227567234084284424
04.01 14:27:48 [Server] INFO Loading World &amp; Settings - 'world' - Env: NORMAL - Type: NORMAL &amp; seed: 6227567234084284424
04.01 14:27:48 [Server] INFO - Version 10.0 - hooked into Essentials Economy for Multiverse-Core v2.4-b527
04.01 14:27:48 [Server] INFO - Version 2.4-b527 (API v14) Enabled - By Rigby, fernferret, lithium3141 and main--
04.01 14:27:48 [Server] INFO Enabling Multiverse-Core v2.4-b527
04.01 14:27:48 [Server] INFO Enabling Itemizer v1.4.7
04.01 14:27:48 [Server] INFO Using SQLite for data storage.
04.01 14:27:48 [Server] INFO CoreProtect version 2.10.0 is enabled!
04.01 14:27:48 [Server] INFO Enabling CoreProtect v2.10.0
04.01 14:27:48 [Server] INFO WEPIF: bPermissions detected! Using bPermissions for permissions
04.01 14:27:48 [Server] INFO Enabling WorldEdit v5.6.2
04.01 14:27:48 [Server] INFO plugins/bPermissions
04.01 14:27:48 [Server] INFO plugins/bPermissions/world
04.01 14:27:48 [Server] INFO Enabling bPermissions v2.10.7
04.01 14:27:48 [Server] INFO For reference, the main world's spawn location is at X: 228.0 Y: 64.0 Z: 131.0
04.01 14:27:48 [Server] INFO [CONFIG] World "world_the_end" has border radius 2500 at X: 0.0 Z: 0.0
04.01 14:27:48 [Server] INFO [CONFIG] World "world_nether" has border radius 2000 at X: 35.3 Z: 29.7
04.01 14:27:48 [Server] INFO [CONFIG] World "world" has border radius 5000 at X: 232.5 Z: 124.5
04.01 14:27:48 [Server] INFO [CONFIG] Border-checking timed task started.
04.01 14:27:48 [Server] INFO [CONFIG] Using elliptic/round border, knockback of 3.0 blocks, and timer delay of 5.
04.01 14:27:48 [Server] INFO Enabling WorldBorder v1.8.0
04.01 14:27:48 [Server] INFO Enabling listener manager...
04.01 14:27:48 [Server] INFO Enabling event system...
04.01 14:27:48 [Server] INFO Enabling Command Handler...
04.01 14:27:48 [Server] INFO Successfully connected to database!
04.01 14:27:48 [Server] INFO "Connecting to SQLite database..."
04.01 14:27:48 [Server] ERROR Flatfile storage is currently broken! Using SQLite...
04.01 14:27:48 [Server] INFO Enabling Data Manager...
04.01 14:27:48 [Server] INFO Enabling Player Handler...
04.01 14:27:48 [Server] INFO Enabling executable manager...
04.01 14:27:48 [Server] INFO Enabling Metrics...
04.01 14:27:48 [Server] INFO Enabling Playtime v1.4.5
04.01 14:27:48 [Server] INFO Preparing start region for level 2 (Seed: 7277526153272938071)
04.01 14:27:47 [Server] INFO Preparing start region for level 1 (Seed: 6227567234084284424)
04.01 14:27:47 [Server] INFO Preparing spawn area: 68%
04.01 14:27:46 [Server] INFO Preparing start region for level 0 (Seed: 6227567234084284424)
04.01 14:27:46 [Server] INFO Zombie Aggressive Towards Villager: true
04.01 14:27:46 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
04.01 14:27:46 [Server] INFO Arrow Despawn Rate: 1200
04.01 14:27:46 [Server] INFO Item Merge Radius: 2.5
04.01 14:27:46 [Server] INFO Item Despawn Rate: 6000
04.01 14:27:46 [Server] INFO Experience Merge Radius: 3.0
04.01 14:27:46 [Server] INFO Clear tick list: false
04.01 14:27:46 [Server] INFO Chunks to Grow per Tick: 650
04.01 14:27:46 [Server] INFO View Distance: 10
04.01 14:27:46 [Server] INFO Max TNT Explosions: 100
04.01 14:27:46 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
04.01 14:27:46 [Server] INFO Max Entity Collisions: 8
04.01 14:27:46 [Server] INFO Sending up to 5 chunks per packet
04.01 14:27:46 [Server] INFO Structure Info Saving: true
04.01 14:27:46 [Server] INFO Random Lighting Updates: false
04.01 14:27:46 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
04.01 14:27:46 [Server] INFO Alternative Hopper Ticking: false
04.01 14:27:46 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
04.01 14:27:46 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
04.01 14:27:46 [Server] INFO Wheat Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Sapling Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Pumpkin Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Mushroom Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Melon Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Cane Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Cactus Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Nerfing mobs spawned from spawners: false
04.01 14:27:46 [Server] INFO Replace Blocks: [1, 5]
04.01 14:27:46 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
04.01 14:27:46 [Server] INFO Engine Mode: 1
04.01 14:27:46 [Server] INFO Anti X-Ray: true
04.01 14:27:46 [Server] INFO Mob Spawn Range: 4
04.01 14:27:46 [Server] INFO -------- World Settings For [world_the_end] --------
04.01 14:27:46 [Server] INFO Zombie Aggressive Towards Villager: true
04.01 14:27:46 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
04.01 14:27:46 [Server] INFO Arrow Despawn Rate: 1200
04.01 14:27:46 [Server] INFO Item Merge Radius: 2.5
04.01 14:27:46 [Server] INFO Item Despawn Rate: 6000
04.01 14:27:46 [Server] INFO Experience Merge Radius: 3.0
04.01 14:27:46 [Server] INFO Clear tick list: false
04.01 14:27:46 [Server] INFO Chunks to Grow per Tick: 650
04.01 14:27:46 [Server] INFO View Distance: 10
04.01 14:27:46 [Server] INFO Max TNT Explosions: 100
04.01 14:27:46 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
04.01 14:27:46 [Server] INFO Max Entity Collisions: 8
04.01 14:27:46 [Server] INFO Sending up to 5 chunks per packet
04.01 14:27:46 [Server] INFO Structure Info Saving: true
04.01 14:27:46 [Server] INFO Random Lighting Updates: false
04.01 14:27:46 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
04.01 14:27:46 [Server] INFO Alternative Hopper Ticking: false
04.01 14:27:46 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
04.01 14:27:46 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
04.01 14:27:46 [Server] INFO Wheat Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Sapling Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Pumpkin Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Mushroom Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Melon Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Cane Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Cactus Growth Modifier: 100%
04.01 14:27:46 [Server] INFO Nerfing mobs spawned from spawners: false
04.01 14:27:46 [Server] INFO Replace Blocks: [1, 5]
04.01 14:27:46 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
04.01 14:27:46 [Server] INFO Engine Mode: 1
04.01 14:27:46 [Server] INFO Anti X-Ray: true
04.01 14:27:46 [Server] INFO Mob Spawn Range: 4
04.01 14:27:46 [Server] INFO -------- World Settings For [world_nether] --------
04.01 14:27:45 [Server] INFO Zombie Aggressive Towards Villager: true
04.01 14:27:45 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
04.01 14:27:45 [Server] INFO Arrow Despawn Rate: 1200
04.01 14:27:45 [Server] INFO Item Merge Radius: 2.5
04.01 14:27:45 [Server] INFO Item Despawn Rate: 6000
04.01 14:27:45 [Server] INFO Experience Merge Radius: 3.0
04.01 14:27:45 [Server] INFO Clear tick list: false
04.01 14:27:45 [Server] INFO Chunks to Grow per Tick: 650
04.01 14:27:45 [Server] INFO View Distance: 10
04.01 14:27:45 [Server] INFO Max TNT Explosions: 100
04.01 14:27:45 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
04.01 14:27:45 [Server] INFO Max Entity Collisions: 8
04.01 14:27:45 [Server] INFO Sending up to 5 chunks per packet
04.01 14:27:45 [Server] INFO Structure Info Saving: true
04.01 14:27:45 [Server] INFO Random Lighting Updates: false
04.01 14:27:45 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
04.01 14:27:45 [Server] INFO Alternative Hopper Ticking: false
04.01 14:27:45 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
04.01 14:27:45 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
04.01 14:27:45 [Server] INFO Wheat Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Sapling Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Pumpkin Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Mushroom Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Melon Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Cane Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Cactus Growth Modifier: 100%
04.01 14:27:45 [Server] INFO Nerfing mobs spawned from spawners: false
04.01 14:27:45 [Server] INFO Replace Blocks: [1, 5]
04.01 14:27:45 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
04.01 14:27:45 [Server] INFO Engine Mode: 1
04.01 14:27:45 [Server] INFO Anti X-Ray: true
04.01 14:27:45 [Server] INFO Mob Spawn Range: 4
04.01 14:27:45 [Server] INFO -------- World Settings For [world] --------
04.01 14:27:45 [Server] INFO Preparing level "world"
04.01 14:27:45 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
04.01 14:27:41 [Server] INFO Enabling mcMMO v1.5.00-b3547
04.01 14:27:41 [Server] INFO Connecting to SQLite
04.01 14:27:41 [Server] INFO Enabling LWC v4.4.0 (b881) (July 11, 2013)
04.01 14:27:41 [Server] INFO Enabled Version 1.5.0-b28
04.01 14:27:41 [Server] INFO [Chat] bPermssions2 found: Loaded
04.01 14:27:41 [Server] INFO [Vault][Chat] bPermissions2 hooked.
04.01 14:27:41 [Server] INFO [Permission] SuperPermissions loaded as backup permission system.
04.01 14:27:41 [Server] INFO [Permission] bPermissions 2 found: Loaded
04.01 14:27:41 [Server] INFO [Vault][Permission] bPermissions2 hooked.
04.01 14:27:41 [Server] INFO [Economy] Essentials Economy found: Waiting
04.01 14:27:40 [Server] INFO Enabling Vault v1.5.0-b28
04.01 14:27:40 [Server] INFO Loading EchoPet v2.6.0-b28
04.01 14:27:40 [Server] INFO Loading EssentialsChat v2.13.1
04.01 14:27:40 [Server] INFO Loading Multiverse-Inventories v2.5-b335
04.01 14:27:40 [Server] INFO Loading Multiverse-Portals v2.4-b548
04.01 14:27:40 [Server] INFO Loading EssentialsSpawn v2.13.1
04.01 14:27:40 [Server] INFO Loading AsyncWorldEdit v1.3
04.01 14:27:40 [Server] INFO Loading Citizens v2.0.14-SNAPSHOT (build 1195)
04.01 14:27:40 [Server] INFO Loading Essentials v2.13.1
04.01 14:27:40 [Server] INFO Loading WorldGuard v5.9

There's the startup log. Everything appears fine.

**Comment by mcmonkey4eva** [comment]
`Everything appears fine.`
Didn't read very carefully did you?
```
04.01 14:27:50 [Server] INFO Disabling Citizens v2.0.14-SNAPSHOT (build 1195)
04.01 14:27:50 [Server] ERROR v2.0.14-SNAPSHOT (build 1195) is not compatible with Minecraft v1.7.10 - try upgrading or downgrading Citizens. Disabling.
```

Get the correct version of C2 here: http://wiki.citizensnpcs.co/Versions

**Comment by eglbogle** [comment]
I did a brief skim over it. I found it later, and looked through one of the Citizens list of versions. I couldn't find a 1.7.10 version, but the closest I could find was 1.7.9. When I tried it, it ran into the same issue.

**Comment by mcmonkey4eva** [comment]
Look through the list I linked maybe.

**Comment by eglbogle** [comment]
I did. And it worked. Sorry, I'm kinda pre-occupied with a bunch of things right now. To the person that opened this issue, it's probably a version issue. But I agree, you should take the time to research a bit more into plugin-making before posting.

**Comment by Anora** [comment]
hmmm same  problem but if i use the 1.7.10 build i get this.

[06:44:44] [Server thread/INFO]: Anoras issued server command: /npc create (randomname)
[06:44:44] [Server thread/WARN]: java.lang.IllegalAccessError: tried to access field net.minecraft.pathfinding.PathNavigate.field_75521_i from class net.citizensnpcs.util.nms.PlayerNavigation
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:29)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:215)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:65)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:70)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:170)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:366)
[06:44:44] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:44:44] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[06:44:44] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:44:44] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[06:44:44] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[06:44:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[06:44:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[06:44:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[06:44:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[06:44:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by fullwall** [comment]
You're using cauldron - download a cauldron build.
