### ISSUE TITLE
My plugin wont work like /npc create //npc help

### ISSUE THREAD

**Issue by zLexxa** [CitizensDev/Citizens2#1662]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by mcmonkey4eva** [comment]
...
Please provide any information whatsoever.

**Comment by mergu** [comment]
You should at the very least be using 1.8.8. We recommend running 1.12.2 or 1.13.2, as 1.8 is old enough we can't provide support for it
