### ISSUE TITLE
Scoreboard confilct between mcMMO and Citizens2

### ISSUE THREAD

**Issue by SpicyYoze** [CitizensDev/Citizens2#1663]
Recently, I noticed that the /npc name command had stopped working randomly after some server changes. I isolated the issue to a conflict between mcMMO and Citizens. While mcMMO is enabled and the scoreboard is on the screen, toggling nameplates seemingly does nothing, while still toggling in the Citizens config to false.

I have left a detailed reply on this issue, https://github.com/CitizensDev/Citizens2/issues/1656#issuecomment-453047213 so I won't "double-post" here with the exact same info.

While this may be a fault of Citizens or mcMMO, I have linked this new issue to the developer so if need be, you can communicate easily. @nossr50

The output of command `/version` on my server is: Paper version git-Paper-498 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1605)

**Comment by nossr50** [comment]
I will look into making mcMMO more compatible with citizens, I'm not sure the implications of moving our scoreboards to the 'main' scoreboard just yet, as a temporary solution though I think I will be making mcMMO scoreboards optional and off by default (as I find them quite intrusive).

My design philosophy for mcMMO is to make it as compatible as it can be with other plugins, and the scoreboards stuff seems a bit too incompatible to be a default feature. I'll have to play with moving the scoreboard to the 'main' scoreboard sometime and seeing how that goes, right now I'm focusing on 2.1.0 so the priority of that will be low until 2.1.0 is out.

I'm still getting familiar with the new features in the Spigot/Bukkit API so I need to read up on scoreboards before I comment further.

**Comment by nossr50** [comment]
There's a temporary solution to this problem for people running mcMMO and Citizens

Until I implement a fix on my end (mcMMO dev here) I suggest you open /plugins/mcMMO/config.yml

And edit the following options

`Scoreboard:
    Types:
        Rank:
            Board: false
        Top:
            Board: false
        Stats:
            Board: false
        Inspect:
            Board: false
        Cooldown:
            Board: false
        Skill:
            Board: false`

**Comment by nossr50** [comment]
3dca32a226db4e8ea2993200482461764594e4dd

Well I made mcMMO use the main scoreboard and it seems to work perfectly and Citizens nameplates are functioning now on my local server, I'm going to consider this compatibility issue fixed, for now its in mcMMO 2.1.0 Snapshots so those waiting for a stable release can use the above method for temporary compatibility
