### ISSUE TITLE
Npc dont save old "dtl trader setup" 

### ISSUE THREAD

**Issue by SimbaZockt** [CitizensDev/Citizens2#1665]
**new create Npcs not saving**

The problem is i can click on the converted files. The npc show all fine and its all working.
But after the server restart it resets and i need to set the Converted file again.
No errors in logs! 

Converted npc files: http://prntscr.com/m6dcsr

Citizens Version: http://prntscr.com/m6dbkx
Spigot Version: http://prntscr.com/m6dbrk

**Comment by mcmonkey4eva** [comment]
This is not dtlTraders support. This is the **Citizens** issues page. Ask for help with dtlTraders wherever dtlTraders provides support at.
