### ISSUE TITLE
NPC name visibility issues

### ISSUE THREAD

**Issue by Scabista** [CitizensDev/Citizens2#1666]
Some players report seeing NPC names even if most players can not. I don't know if this could be related to using something like Optifine, as a few players with the issue claim they use it.
Also, possibly unrelated, sometimes "/name" dosnt hide npc names. 

https://gist.github.com/Scabista/c20c9534862ff2ae5c9f4b67a210f13f (No related console errors, or output)

FOR LAG RELATED ISSUES: 35g memory. 100ish global npcs.

The output of command /version on my server is: 1.12.2-R0.1-SNAPSHOT
The output of command /version citizens on my server is: 2.0.24-SNAPSHOT (Build 1604)

**Comment by mcmonkey4eva** [comment]
This functionality is related to Citizens scoreboard control - if other plugins are applying changes to the scoreboard, they may be interfering. See here: https://wiki.citizensnpcs.co/Plugin_Conflict

BTW `1.12.2-R0.1-SNAPSHOT` is not a Spigot version (it's a Minecraft version) and it's not the output of command `/version` - it's a small subset of that output.
