### ISSUE TITLE
VillagerProfession#setProfession Throws NPE

### ISSUE THREAD

**Issue by tchristofferson** [CitizensDev/Citizens2#1667]
The output of command `/version` on my server is: git-Spigot-29ab5e4-2bc7d1d (MC: 1.13.2)
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1604)

VillagerProfession#setProfession results in a NullPointerException
https://pastebin.com/NXC1YFpY

Code to replicate: https://pastebin.com/a6HpLKTQ
Server log: [latest.log](https://github.com/CitizensDev/Citizens2/files/2753586/latest.log)
Citizens config: [config.zip](https://github.com/CitizensDev/Citizens2/files/2753589/config.zip)

**Comment by tchristofferson** [comment]
The code works if I remove setting the profession, it spawns and everything works.

**Comment by mcmonkey4eva** [comment]
```java
VillagerProfession professionTrait = new VillagerProfession();
```
^ Nope. Can't construct trait classes directly. Instead, call the Citizens API to handle the trait initialization:
`npc.getTrait(VillagerProfession.class)`
