### ISSUE TITLE
Ok, how am I doing it this time?

### ISSUE THREAD

**Issue by MrKiller01** [CitizensDev/Citizens2#1668]
I hope I put the text in the right place this time..., if not, please tell me....
This is a request for additional plugins for Citizens2, I believe in a better communication between NPC's and actions that are not there yet.... for instance, the use of TrainCarts is a bit off since 1.13, so through commandblocks, signs and buttons I made it possible to work out the tickets that TrainCarts uses (can use)  Unfortunately it does not work anymore, so I was thinking, is there a way to let NPC's look into a list of tickets and offer them for sale at stations? to just get the tickets that are already in use by the plugin TrainCarts, but to remember commands for it, is harder for new people and tend to forget it fast...
So I was thinking that maybe this is possible to make a sort of universal plugin that reads a flat text file that has all stations, and i'm ofcourse concerned about the price, I don't know if distance can be measured from point of purchase to the selected destination, but if that is possible, it could be used for other things that have same structure... 
 
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by SXRWahrheit** [comment]
you didn't follow the instructions and this issue has nothing to do with Citizens, you need to ask the dev of the other plugin to add this

**Comment by mergu** [comment]
@SXRWahrheit The 'other plugin' doesn't exist. This is a request to write a new plugin, which is entirely out of the scope of Citizens support.

@MrKiller01 Please stop abusing this issue tracker. Only open issues with the Citizens plugin here.

**Comment by mcmonkey4eva** [comment]
This is just outright issue spam at this point.
@MrKiller01 Please stop posting random inane issues here.
