### ISSUE TITLE
Allow setting default NPCRegistry and NPCDataStore implementations

### ISSUE THREAD

**Issue by Silthus** [CitizensDev/Citizens2#1671]
Currently it is not possible to set a custom implementation of the data store or registry. 

It would great to allow overwriting the default data store and registry to allow for custom implementations, like discussed here: https://github.com/CitizensDev/CitizensAPI/issues/44

If wanted, I can also open a PR for this.

**Comment by fullwall** [comment]
How would load order work with this?

**Comment by fullwall** [comment]
Pushed a simple implementation.

**Comment by Silthus** [comment]
I will test it right away!

**Comment by Silthus** [comment]
First off thanks for the fast implementation. I did run some first tests and came accross an issue: the commands grab their NPCRegistry one time at initialization. If it changes they still run with the old registry.

Unfortunatly reloading does not work either as a workaround, since it does not reload the commands.

**Comment by Silthus** [comment]
Thanks for the very quick implementation and sorry about the fail PR :/

I did it from work where I can't compile craftbukkit due to proxy fuckups...

I won't do it again I promise :)

The change works well and I already tested it with my custom store implementation. All commands work like a charm and Npcs are saved to separate files.

Thanks!
