### ISSUE TITLE
High CPU consommation of citizens

### ISSUE THREAD

**Issue by Elytes** [CitizensDev/Citizens2#1673]
Hi !
I'm making a server since months, and I've got much problems with citizens consommation. Citizens takes 99% of total cpu consommation (1% are others plugins) and 1 second per 5.2 seconds of cpu's time is used for Citizens, and that's decreasing the average tps of the server. 
I'm using the version 2.0.24-SNAPSHOT (build 1591).
I've got 39 citizens and I will need much more in the future :/
I descreased retry delay while skin is lost, updated the packets update delay to 50 and pathfinding update path rate to 10 (i'm using the new finder with 5000 max iterations).
Much of these npc are moving with path and I forgot to use triggers so there is just a lot of waypoints where the npc needs to stop, but by looking at the source code, it seems that you don't load every waypoints each time the npc walks, so that wont makes the server lags uh ?
Tell me if you got any ideas to decrease cpu consommation ^^
Thanks

**Comment by mcmonkey4eva** [comment]
- Your build of Citizens is outdated, update: http://ci.citizensnpcs.co/job/Citizens2/
Naturally also ensure your Spigot build is fully up-to-date.

- Using the Spigot timings system (`/timings` command) to get some indication of lag sources more specifically (and post the results here for us to read)

- Post your config file.

- Be aware that NPCs walking paths can sometimes heavily use your server CPU power if they have to walk particularly complex paths or are being told to walk paths they can't walk (ie their path is blocked)

**Comment by Elytes** [comment]
https://timings.spigotmc.org/?url=rukemexima

[config.zip](https://github.com/CitizensDev/Citizens2/files/2776098/config.zip)

**Comment by mcmonkey4eva** [comment]
I don't know how or why you uploaded your config as a zip file but I repastebin'd that for anyone else trying to look at it: https://pastebin.com/2DU8KgMF

**Comment by Elytes** [comment]
Yeah sry, forgot that exists x) 
https://pastebin.com/SSx72RgV

**Comment by Elytes** [comment]
Yeah sry, forgot that, thanks ^^

**Comment by mcmonkey4eva** [comment]
The new timings link was recorded with Citizens loading in during the timings still. Please fix that.

You may want to switch `use-new-finder:` back to false in your config.

... I have no idea why you just pastebin'd the thing I already pastebin'd for you as a reply to me pastebinning it for you...

**Comment by Elytes** [comment]
Yeah sorry, i'm so tired right now so i'm getting stupid ^^
The problem is that I need use-new-finder for specifics npc, but not for every npc, but I didn't see command to do it ^^
How can I fix the timing link ? By doing /timings again ?

**Comment by mcmonkey4eva** [comment]
Turn timings on manually, not automatically.

**Comment by Elytes** [comment]
Ehm, that's really weird but it seems that the new citizens version that I installed corrected every lags, cause now, the plugin takes only 1/10 of the cpu's time ?? *_*

**Comment by Elytes** [comment]
Is this link is good ? 
https://timings.spigotmc.org/?url=venitijima

**Comment by Elytes** [comment]
I desactivated the use-new-finder and now, citizens is taking 1/3 cpu's time, I don't think that's cause of the use-new-finder:false, but it doesn't reduce lags :(
https://timings.spigotmc.org/?url=timoqixiti

**Comment by mcmonkey4eva** [comment]
That recording is from load time again

**Comment by Elytes** [comment]
This one is good ? https://timings.spigotmc.org/?url=hibujapoco

**Comment by Elytes** [comment]
I removed npc wich are using /npc path and the cpu consommation decreased a lot (citizens takes 3% approximativly), so is there a way to make npc move without consumming all cpu ressources ?

**Comment by mcmonkey4eva** [comment]
Usually in pathfinding is making a severe impact on a server, it's from NPCs walking complex or blocked paths.
It's possible you had that happening.

You also mentioned you have a custom plugin giving paths to NPCs: it's possible your plugin is at fault here, eg if it's giving new paths very rapidly or is giving complicated path requests
