### ISSUE TITLE
Can't see npc's 

### ISSUE THREAD

**Issue by DennisFusha** [CitizensDev/Citizens2#1674]
Everytime I start up my server some npc's are invisble but their armor isn't. 
But when I do citizens reload they are back but when you go somewhere and render them back in they are gone again and I have to do reload to get them back.

The output of command /version on my server is: This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command /version citizens on my server is: Citizens version 2.0.24-SNAPSHOT (build 1581)

Updating spigot&citizens doesn't work either

CONFIG: https://pastebin.com/qeH4hBfp
Log: Nothing

**Comment by mcmonkey4eva** [comment]
That's an older version of Citizens, please update: http://ci.citizensnpcs.co/job/Citizens2/
Make sure your copy of Spigot is up-to-date as well (latest Spigot 1.12.2 or 1.13.2 build)

If the NPC's are invisible but not armor, that sounds like invisibility potions (it might also be skin loading error, I'm not sure if that has effects like that or not)

Might be a plugin conflict, please follow the steps listed here to test that: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by DennisFusha** [comment]
Okay cool, it's 11:35 pm here i'll do that tommorow and come back with the answer.

**Comment by mcmonkey4eva** [comment]
If you can narrow down a specific interaction breaking or general cause (or replicate on a server with no other plugins / anything installed) we can help, until then... not much we can do.

**Comment by DennisFusha** [comment]
> If you can narrow down a specific interaction breaking or general cause (or replicate on a server with no other plugins / anything installed) we can help, until then... not much we can do.

it was a bug with multiverse so I changed to multiworld and that fixed the bug
