### ISSUE TITLE
NPC Player types disappearing

### ISSUE THREAD

**Issue by JRJ1116** [CitizensDev/Citizens2#1675]
When I try to create npc's of players, the server tells me that the npc was successfully created. However, when the player logs in (whom is the same as the npc), the npc disappears. But when the player logs out, the npc reappears. Ideally, the npc is always visible when a player is online or offline. Not entirely sure what to change to make that happen.
Server Log: https://pastebin.com/pn6ywSgK
Citizens Config: https://pastebin.com/nyei2bCn

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1605)

**Comment by mcmonkey4eva** [comment]
You're running an unsupported version of Spigot, update to 1.12.2 or 1.13.2 versions via BuildTools - https://www.spigotmc.org/wiki/buildtools/

**Comment by JRJ1116** [comment]
Updated to 1.12.2, still no difference

**Comment by mcmonkey4eva** [comment]
Can you post a current server log?
Ideally fix all unrelated errors in the log (if there are still as many as the one you've posted)
Among other things, that log _starts off_ with a message informing you that you randomly threw BungeeCord.jar into your plugins folder (Bungee is not a plugin)

**Comment by JRJ1116** [comment]
https://pastebin.com/ris4jxCP

**Comment by mcmonkey4eva** [comment]
That's still a 1.12 (not 1.12.2) server, and it still has the same errors. It looks the same log repasted

**Comment by JRJ1116** [comment]
My bad, copied the wrong log. This should be the correct one

https://pastebin.com/kq3Fayzv

**Comment by mcmonkey4eva** [comment]
Sorry for being slow on this.
It might be a plugin conflict - see here: https://wiki.citizensnpcs.co/Plugin_Conflict

Generally, try to not make NPCs that exactly match players. Throw in a color code to the nameplate, for example.
eg instead of `/npc create mcmonkey4eva` to spawn me in, you can do `/npc create &6mcmonkey4eva`
The color code will make the NPC not technically be the same as me, while still looking roughly the same.
