### ISSUE TITLE
How to access the different villager career?

### ISSUE THREAD

**Issue by madtomic** [CitizensDev/Citizens2#1677]
/npc profession | BLACKSMITH, LIBRARIAN, BUTCHER, FARMER, or PRIEST
These are the basic professions to set the NPC to.

>Any way to access the career in profession type? Besides the standard professions?
https://www.digminecraft.com/mobs/villager.php

Villager | Clothes | Profession ID | Career ID
-- | -- | -- | --
  | Brown Robe | 0 | 1 = Farmer 2 = Fisherman 3 = Shepherd 4 = Fletcher
  | White Robe | 1 | 1 = Librarian 2 = Cartographer
  | Purple Robe | 2 | 1 = Cleric
  | Black Apron | 3 | 1 = Armorer 2 = Weapon Smith 3 = Tool Smith
  | White Apron | 4 | 1 = Butcher 2 = Leatherworker
  | Green Robe | 5 | 1 = NitWit

**Comment by mcmonkey4eva** [comment]
Changing the career on an NPC would do literally nothing.
Changing the profession is all you need.

**Comment by madtomic** [comment]
I thought there are more cloth colors that is accessible?

**Comment by mcmonkey4eva** [comment]
No, as the page you linked explains: the profession alone determines clothing

**Comment by madtomic** [comment]
You stand correct. Thank you again.
