### ISSUE TITLE
Nameplate and sub nameplate

### ISSUE THREAD

**Issue by madtomic** [CitizensDev/Citizens2#1678]
I was wondering if this is something possible for villager NPC. 

Nameplate
Sub nameplate 

Over their heads?

**Comment by madtomic** [comment]
Haha, I just realized that I asked this very same question 3 years ago. So, anything change in 3 years that would let us do this now? https://github.com/CitizensDev/Citizens2/issues/500#issuecomment-136175963

**Comment by mcmonkey4eva** [comment]
Nope, same now as it was then (though holograms are very very simple to make now, I'm not sure if that was already the case in 2015 - either way, it's now literally just some properties on an armor stand as the basic setup for holograms)
