### ISSUE TITLE
Question: player type nameplate

### ISSUE THREAD

**Issue by madtomic** [CitizensDev/Citizens2#1679]
Is there a way to hide the nameplate for villager type?

I can use /npc name to hide nameplate for npc that is villager types but not player types.

**Comment by mcmonkey4eva** [comment]
`/npc name` and `/npc name -h` should work for any entity type

**Comment by madtomic** [comment]
I just check again. It don't work on npc player type

**Comment by madtomic** [comment]
Something better, I found a bug. When using /npc name it will toggle all the NPC names to off. This only seems to happen to player types

**Comment by mcmonkey4eva** [comment]
Trouble with NPC player-type nameplate control can happen when Citizens doesn't have proper control of the scoreboard.
See here: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by madtomic** [comment]
Thank you, I will report back if I have more issues.

**Comment by madtomic** [comment]
After playing around. This is how I was able to toggle it off for player type. This affects all npc that is player types.

First create, an npc with villager type, use npc name to toggle on and off.
after change that same npc to player type and now use npc name. this will toggle off for all the player type npcs.

**Comment by madtomic** [comment]
Edit: After server restarts, it will returns to normal.
I also found out when using /npc name -h, this will show the nameplate when looking at the NPC. different behavior than /npc name - which toggle nameplate off completely.
I am guessing -h is hidden when not looking at the npc.

**Comment by madtomic** [comment]
> 
> 
> `/npc name` and `/npc name -h` should work for any entity type

It don't seem to work for player types. Can you please fix this?

**Comment by mcmonkey4eva** [comment]
`-h` is not actually an option for player type I believe, forgot that in my earlier post.
The villager thing, I was not able to replicate.

Note another special exception with player types: Control is based on NPC *name* for player-type, meaning other player NPCs with the same name will be affected.
To avoid this you can add color codes into the NPC's name.
