### ISSUE TITLE
Got a system crash apparently due to a ticking player/NPC, might be due to the mounttrait trait

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1682]
Got a system crash apparently due to a ticking player/NPC, might be due to the mounttrait trait
because when I look in the npc's traits mounttrait is listed and in the crash report it says;

**Entity's Vehicle: --ERROR-- NullPointerException: null**
_________________________________________________________
[Crash Report](https://pastebin.com/YvQ5HpZD)
[Console Error](https://pastebin.com/i9FN5xhM)
[Latest Log (at the time)](https://pastebin.com/E43nXUer)

The output of command `/version` on my server is: 

**This server is running Paper version git-Paper-509 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: 

**[16:21:07 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1612)
[16:21:07 INFO]: Website: http://www.citizensnpcs.co
[16:21:07 INFO]: Authors: aPunch and fullwall**

**Comment by mcmonkey4eva** [comment]
That looks to be an async stability issue.
No relation to Citizens. Likely related to `FastAsyncWorldEdit` (being an async plugin) or `Skript` (doing async work at the time of crash).
May also be an issue with Paper itself.

**Comment by axemwa** [comment]
Now that you mention it "DummyFawe" was located in my plugin folder and I have since deleted it. Not sure how that got there... must have forgotten to remove it when I removed the main FAWE plugin a while ago. Thanx for replying

PS: Sorry if I have slow replies for this and other issues, I got back form hospital not long ago they had me on strong morphene so my mind is still a little jumbled still atm
