### ISSUE TITLE
BungeeCord + Skins

### ISSUE THREAD

**Issue by Movion** [CitizensDev/Citizens2#1683]
**BungeeCord! (Waterfall + PaperSpigot)**

The output of command `/version` on my server is: **(This server is running Paper version git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Previous version: git-Paper-1448 (MC: 1.12.2)
Checking version, please wait...
You are running the latest version)**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.24-SNAPSHOT (build 1604)**

Hello there,

i have the a question on the configuration for bungeecord servers and the skin function for citizens2.
I searched long in the wiki and i can only find the information about skins here: https://wiki.citizensnpcs.co/Skins

and i also know this is important:
You are running your server in ONLINE MODE (offline mode servers won't work!)

so im asking if there is any workaround for my bungeecord network. 
The Gateway is in online mode: https://pastebin.com/aaGCgYtd
And this is the config for the server im trying to run the Plugin: https://pastebin.com/5TsTtaXh

ofc it is in offline mode... so... how can i get the skins working on a bungee server? is there any bridge i have to install? or is there a better documentation for the /npc skin -t ? 
I also bought the plugin but im not sure if this is related in any case.
The testing with the latest official spigot for 1.12.2 version and bungee jar are ending in the same results. 

When i do /npc skin Movion the npc doenst get my skin. 

sorry for my bad english...

**Comment by mcmonkey4eva** [comment]
To my knowledge a properly configured spigot server on a bungee network should still work fine with player-type entity skins. I'm not really sure the details on that though...

**Comment by Movion** [comment]
well as i just acknowledge is that the skins are working... but only after a long time period. When i refresh or change the skin it falls back to the default skin. Is there a way to change that?

**Comment by mcmonkey4eva** [comment]
That is more likely to be a Mojang rate-limiting issue, which can happen if you have too many NPC skin and/or player skull lookups occurring in a short time span, or if you're using a generic rehosting service rather than a dedicated machine / VPS host.

**Comment by Movion** [comment]
is there anyway to reduce the request rate? im on a dedicated host and dont share my ip with any other server

**Comment by mcmonkey4eva** [comment]
Skins don't request themselves, it's down to how many requests _you_ make (or your players do) via `/npc skin` commands and player skull items.

If skins seem to be loaded to the server but aren't staying consistently applied to the NPCs, you might be encountering #1632
