### ISSUE TITLE
Phantom size (feature)

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#1685]
The output of command `/version` on my server is: **CraftBukkit version git-Spigot-573cdf2-dff66df (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.24-SNAPSHOT (build 1604)**

Hi,
Is it possible to allow the command _/npc size_ for Phantoms NPCs ? Currently it is not possible, we only can execute it on slimes, however Phantoms are sized entities !
Thanks !

**Comment by mcmonkey4eva** [comment]
That's currently possible already! `/npc phantom --size [size]`
