### ISSUE TITLE
Feature Request - Server Side Skins

### ISSUE THREAD

**Issue by jeddell** [CitizensDev/Citizens2#1686]
I love the plugin. Great for interactive gameplay on the server with quests. However The only issue I have is the difficulty in setting a skin to suite the theme Im trying to achieve.

Id like to make a suggestion that as well as having skins using the `/npc skin [nam] ` command, there be an option to load a skin from the server files. or even a custom Resource pack if  the server wants to go that way.  

I appreciate the work guys. keep it up

**Comment by mcmonkey4eva** [comment]
See the helper tool to achieve that here: https://wiki.citizensnpcs.co/Skins#Helpful_Tools

**Comment by mcmonkey4eva** [comment]
It's a Denizen script. The `Denizen` text on the wiki page links to the Denizen spigot page.
Denizen is a scripting engine that closely integrates with Citizens.

Feel free to ask for help with setup on the Citizens+Denizen shared Discord: https://discord.gg/Q6pZGSR
