### ISSUE TITLE
Metadata resets after restart.

### ISSUE THREAD

**Issue by VytskaLT** [CitizensDev/Citizens2#1688]
The output of command `/version` on my server is: „This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)“
The output of command `/version citizens` on my server is: „2.0.24-SNAPSHOT {build 1591}“

So when I set someone metadata on a npc. It works, but after restart there is no metadata.
I use the metadata for the API.

Commands to perform the bug:
/npc create testing
/npc metadata set abc abc
/stop

Computer Specs:
CPU: Intel Core i7-8700 3.20ghz
RAM: 16 gb ddr4
GPU: Nvidia GeForce 1060

I really need this fixed, because I need to set the metadata again and again for my plugins to work.

**Comment by mcmonkey4eva** [comment]
First: updating your server to 1.12.2 or 1.13.2 is strongly recommended: https://wiki.citizensnpcs.co/Minecraft_1.8
Minecraft 1.8 is a 5 year old version that is reasonably unsupportable. The wiki page linked includes information about how to get common things users want from a 1.8 server to work on more modern versions, including older style PvP and allowing older (1.8/etc) clients to connect to your modern server.

---

Metadata should be persistent on modern versions without issue. Ensure there are no errors in the console with `/citizens save` if the issue appears to persist on a modern version.
