### ISSUE TITLE
Error on load NPC with custom skins

### ISSUE THREAD

**Issue by BrainRTP** [CitizensDev/Citizens2#1690]
Hi, i have a bug, when i set custom skins (/npc skin -t <uuid> <data> <signature>)
<img width="831" alt="2019-02-03 23 22 02" src="https://user-images.githubusercontent.com/22731705/52180635-a5ebf880-280a-11e9-9d47-c01a7c53771f.png">
Error: https://pastebin.com/WMuWtGMk
And when rename NPC
Error: https://pastebin.com/v8Y34DFt
p.s <uuid> == ID NPC or random String/Integer?

**Comment by mcmonkey4eva** [comment]
Those errors are from WorldGuard and/or LuckPerms, not Citizens.
Report to them. Most likely WorldGuard.
