### ISSUE TITLE
Adding Command to NPC's Not working

### ISSUE THREAD

**Issue by adameg2305** [CitizensDev/Citizens2#1695]
The output of command `/version` on my server is: **1.8.8-R0.1**
The output of command `/version citizens` on my server is: **2.0.16-SNAPSHOT  (Build 1267)**
![image](https://user-images.githubusercontent.com/44293115/52290191-73a3dd80-2967-11e9-879f-1e9a466b2084.png)

 ISSUE:
Console: https://pastebin.com/cXH6KjJf
Citizens Config: https://pastebin.com/jbVXHT9R

The issue im having is i am creating a factions server and was changing a config file in a completly different plugin to citizens i then restart my server (Not doing /reload) everything loaded fine and then when i went to check on the NPC's i have at my spawn none of them work and the command /npc addcmd no longer existed. I have tried deleting the citizens.jar then redownloading the latest version however that has not fixed the problem.

I was wondering if anyone could help

**Comment by mcmonkey4eva** [comment]
1.8 versions are unsupported: https://wiki.citizensnpcs.co/Minecraft_1.8
Offline mode is unsupported: https://wiki.citizensnpcs.co/Cracks

Additionally your log paste shows you are running cracked plugins.

Please do not post here again.

You are running an outdated, unsupported, and multiple times over illegal server.

We are not going to help you.
