### ISSUE TITLE
API - Name Trait

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#1696]
So this is something that has not been developped for Citizens yet : a system to get the real name of each NPC, and not the displayed name. Here is an example :
I have a NPC named "Fisherman [Right Click]" and I want that others plugins can get "Fisherman" directly from Citizens instead of passing through other plugins, to show in dialogs or quests.
This trait will be useful to external plugins, it allows NPCs to have different names than the one who is showed above the head.
And inside Citizens plugin itself, it can be used in the Text system, to show NPC's name before a line of text...
Contact me if you need further informations,
Thanks,
SkytAsul

**Comment by mcmonkey4eva** [comment]
Denizen has included a `NicknameTrait` for 6+ years: https://github.com/DenizenScript/Denizen-For-Bukkit/blob/dev/plugin/src/main/java/net/aufdemrand/denizen/npc/traits/NicknameTrait.java

And basically nobody has ever used it.

The people that want a different name-above-head from the rest usually just hide the nameplate and stick a hologram in place, which achieves your goal exactly with about no other trouble.

Most plugins and code involving Citizens will just use the actual name value, trying to get all of that changed to make use of a separate nickname seems unlikely to happen (especially given the disinterest in the one provided by Denizen).

**Comment by SkytAsul** [comment]
And using Denizen is exactly what I don't wanted : using another plugin. I will use an hologram above the head, as you said. Thanks anyway for reply !
