### ISSUE TITLE
After restart player npc's

### ISSUE THREAD

**Issue by JoelDeadMach** [CitizensDev/Citizens2#1698]
** DO NOT IGNORE **
After restart the plugin gives an warning about humans.
and the npc's arent not loaded in-game.

Warning: https://paste.ofcode.org/gDyy3kuKPEUq4pM7ZSfW9a

The output of command `/version` on my server is: This server is running Paper version git-Paper-516 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1604)

**Comment by Morphan1** [comment]
Update Spigot (through BuildTools) and Citizens2 (https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/).

**Comment by mcmonkey4eva** [comment]
Yup, purely a bad versions issue. Update!
