### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by SamB440** [CitizensDev/Citizens2#1699]
The output of command `/version` on my server is: This server is running Paper version git-Paper-1596 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1612)

I am having a problem with the Citizens trait API. I coded a trait, plugin loads fine and everything, no errors, yet when I do /npc select then /trait add Guide it cannot find the trait.

Here is my plugin class: https://pastebin.com/Zrdi5fJe
And my trait class: https://pastebin.com/L7wXiEJK
plugin.yml: https://pastebin.com/CJEbunTY
Server log: [latest.log](https://github.com/CitizensDev/Citizens2/files/2857371/latest.log)

**Comment by mcmonkey4eva** [comment]
Remove `@TraitName("Guide")`

And do `         factory.registerTrait(TraitInfo.create(Guide.class).withName("guide"));`

The wiki page is a bit unmaintained - I've fixed it now to show the correct name registration setup. Sorry for the confusion on that.

**Comment by SamB440** [comment]
> 
> 
> Remove `@TraitName("Guide")`
> 
> And do ` factory.registerTrait(TraitInfo.create(Guide.class).withName("guide"));`
> 
> The wiki page is a bit unmaintained - I've fixed it now to show the correct name registration setup. Sorry for the confusion on that.

Thank you, that works. But sadly I have another problem; the NPCClickEvent doesn't seem to be registered. I added `System.out.println("click!");` before anything in the event but when i right or left click the NPC that does not get outputted.
