### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by PirataGu** [CitizensDev/Citizens2#1703]
Mine citizens and CommandNPC are not working in my server...
They appear on my plugin list on minecraft server but they are red so... they are not working (the green plugins mean that is working)
Can you please help me ?

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.17-SNAPSHOT (build 1316)

**Comment by mergu** [comment]
Your Citizens build is over 300 versions behind, update: https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/

Also, we recommend running 1.12.2 or 1.13.2. Here is some info on why that's a good idea: https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by PirataGu** [comment]
> 
> 
> Your Citizens build is over 300 versions behind, update: https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/
> 
> Also, we recommend running 1.12.2 or 1.13.2. Here is some info on why that's a good idea: https://wiki.citizensnpcs.co/Minecraft_1.8

but I want a minecraft server in 1.8... Do have you any possibility to work on 1.8.8?

**Comment by mergu** [comment]
The current Citizens build should work on 1.8.8 (see my link above), but we generally won't provide support if you request features or find bugs.

**Comment by mcmonkey4eva** [comment]
@PirataGu Read the wiki link regarding 1.8

It explains how to set your server up to run like 1.8
