### ISSUE TITLE
Citizens error

### ISSUE THREAD

**Issue by MatrixKhan** [CitizensDev/Citizens2#1707]
Getting this error https://pastebin.com/DFCHKyBY

Running Citizens https://i.imgur.com/OmcIPvH.png

Running tacospigot 1.8.9

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8

----

- Not latest Citizens (2.0.16 vs 2.0.24)
- Not a supportable version of Minecraft (1.8.9 vs 1.12.2 or 1.13.2)
- Not a supportable version of Spigot ("TacoSpigot" vs Spigot itself or in some cases Paper)

Update. See the wiki page linked for information on how to most effectively update without losing anything.
