### ISSUE TITLE
Trait removed after server crash

### ISSUE THREAD

**Issue by hugo4715** [CitizensDev/Citizens2#1711]
Citizens config: default
The output of command `/version` on my server is: http://prntscr.com/mvyn0g
The output of command `/version citizens` on my server is: http://prntscr.com/mvynab

I added a custom trait using `CitizensAPI.getTraitFactory().registerTrait(TraitInfo.create(TraitQuickPlay.class).withName("quickplay"));`

Everything is working wonderfully, but when the server crashes, the trait must be manually re-added to the npc, There are no errors or stacktraces in the logs so i don't know what to do. 
The trait is a really simple one, just handling a PlayerInteractEntityEvent at the npc. 
Since there is no errors, i am really confused to what i can do to fix this and need some help.

**Comment by mcmonkey4eva** [comment]
- Update your Citizens, that's very outdated - https://ci.citizensnpcs.co/job/Citizens2/
- Update your server to latest Spigot 1.12.2 or 1.13.2, as 1.8 is unsupportable - https://wiki.citizensnpcs.co/Minecraft_1.8
- Data tends to get lost when you crash without saving. To avoid losing data, save before you crash.
