### ISSUE TITLE
Name glitches

### ISSUE THREAD

**Issue by TheJavaDev** [CitizensDev/Citizens2#1712]
I am running Citizens 2.0.24 (build 1624) on my 1.12.2 Spigot server, and am experiencing weird name glitches. 
1) If I do /npc name and relog the name tag reappears
2) after I do 1 /npc name does not work anymore
3) If I create a new npc, do /npc name, then delete it, all the npcs of that type show their names again

Please help, this is driving me crazy since I have a lot of npcs

If any more information is needed, please request and I will provide it

**Comment by mcmonkey4eva** [comment]
Can you post a plugin list?

In particular plugins that might mess with scoreboards could be potentially relevant.
