### ISSUE TITLE
Citizens does not work on my server! I don't know the reason, help!

### ISSUE THREAD

**Issue by UnuralTas** [CitizensDev/Citizens2#1715]
This problem used to be. It appeared 2 days ago when the server starts as usual. Just going this time to the NPC server was not and the commands from the Citizens plugin did not work, although they show when you enter /npc (CitizensCMD Mod works fine). I don't know why, it just suddenly stopped working.
![2019-03-19_18 26 48](https://user-images.githubusercontent.com/48709874/54587750-2726e400-4a75-11e9-8663-8a95c6d1bb8f.png)

Here's what was written in the console and the log of this error:

[18:25:48] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1591) (Is it up to date?)
--
200 | java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
201 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
202 | at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_202]
203 | at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
204 | at net.citizensnpcs.Citizens.onEnable(Citizens.java:266) ~[?:?]
205 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
206 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
207 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
208 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
209 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
210 | at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
211 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
212 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
213 | at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
214 | at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
215 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
216 | Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
217 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
218 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
219 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
220 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
221 | ... 15 more

Please help! This is a great plugin that allows you to feel the reality in the minecraft! And now... He refuses to work. :(

**Comment by mcmonkey4eva** [comment]
You updated Spigot to the newest version... you have to update Citizens as well: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by UnuralTas** [comment]
> Вы обновили Spigot до последней версии... вы должны обновить граждан, а также: https://ci.citizensnpcs.co/job/Citizens2/

My server on Aternos, and there now there is no update. What am I to do? Wait?

**Comment by mcmonkey4eva** [comment]
Get a server host that allows you to update plugins from jar files.

**Comment by UnuralTas** [comment]
> Получить хост сервера, который позволяет обновлять плагины из jar файлов.

I don't know anything about servers, and I don't know how to do it. Is there any guides? Or can you explain?

**Comment by mcmonkey4eva** [comment]
- SpigotMC: https://www.spigotmc.org/wiki/spigot-installation/ 
- Minecraft Wiki: https://minecraft.gamepedia.com/Tutorials/Setting_up_a_Spigot_server
