### ISSUE TITLE
Citizens is disabled (version 1646)

### ISSUE THREAD

**Issue by aurel85** [CitizensDev/Citizens2#1717]
Hi,

With the latest version Citizens doesn't load on my server. I use PaperSpigot 1.13.2

Error : https://hastebin.com/azapoxoqad.cs

/version : 
![Capture](https://user-images.githubusercontent.com/24486147/54649479-ae427f00-4aaa-11e9-87d2-4a2b23f90782.PNG)

/version citizens : 
![Capture2](https://user-images.githubusercontent.com/24486147/54649485-b3073300-4aaa-11e9-8a19-013cf1db03c4.PNG)

Thank you in advance !

**Comment by mergu** [comment]
You'll either need to ask the paper team to pull upstream changes or use a previous citizens build until they do. Unless you ask, they tend to do this once every week or two.

**Comment by aurel85** [comment]
Ok thank you, I will make a issue at Paper.
