### ISSUE TITLE
NPC color codes in names are buggy

### ISSUE THREAD

**Issue by jaschoid** [CitizensDev/Citizens2#1718]
https://pastebin.com/2w0Upfmw
https://pastebin.com/X4XXKgkG

When i try to create NPC called "&c&lSurvival Games", 
![obrazek](https://user-images.githubusercontent.com/33392529/54716713-a6d8af80-4b56-11e9-8608-cfee8d43216d.png)
i get this, the name of the npc is just "&f&lSurvival Games" instead of "&c&lSurvival Games", like if the color codes would just randomly stop working. tried it with different name lenghts, it sometimes works, sometimes not. What am i doing wrong? Naming previous NPCs with color codes worked.

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1621)

**Comment by mergu** [comment]
Copied my response from discord to here (generally it's best to ask for help in discord first before opening an issue):
```
player names can only be 16 characters long
internally, citizens ups this to 48 chars by using scoreboard teams
i forget if work was done to carry the color codes from the prefix into the name/suffix
but it looks like the prefix is being set to &c, and the name to &lSurvival Games
so.. a few things
1) update everything (spigot + citizens)
spigot: https://www.spigotmc.org/wiki/buildtools/
citizens: https://ci.citizensnpcs.co/job/Citizens2
2) make sure you're testing this with no other plugins
3) if the above fails, try setting the name to something like &cderp&lSurvival Games to see if the color is being cut off in the middle
```

**Comment by mcmonkey4eva** [comment]
Color codes are carried over, but only 1 color code, not multiple (actually, that code needs some fixing up, will do soon)

Also if nameplate extension breaks, it's a plugin conflict related to scoreboard control - https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by jaschoid** [comment]
hey

just tried to remove all plugins except authme, citizens and commandnpc (hooks into citizens), and i still have the same issue. however, if switch the entity´s type to something else than player (skeleton for exapmle), the color in the name starts to work just fine

i have installed few shady plugins when the citizens were already installed, they are gone now, but i wonder if some of them couldnt edited these scoreboard settings in a way that bugs citizens now?

**Comment by mcmonkey4eva** [comment]
`just tried to remove all plugins except authme,`
https://wiki.citizensnpcs.co/Cracks
