### ISSUE TITLE
[Suggestion] Better and User-Friendly /npc equip

### ISSUE THREAD

**Issue by Drc-DEV** [CitizensDev/Citizens2#1723]
The /npc equip feature is a bit "outdated" and annoying to use. For example if you want to put something as the helmet of an npc and right-click it, it will be equipped in the hand. And you have to type "offhand" in chat in order to equip stuff in the offhand. This is really strange and not really easy to imagine for a new user.

My suggestion is to provide a simple GUI for the /npc equip instead of the current system
![image](https://user-images.githubusercontent.com/33911680/54939159-29cb8280-4f28-11e9-94ea-a22a9de38b82.png)
Something like this should work fine. The player just has to enter equip mode with /npc equip and then when the player clicks on the NPC, the GUI will open. Then the player can easily and quickly edit the full equipment of the NPC.

Hope you can get this done, because in my opinion it's really needed.

**Comment by mcmonkey4eva** [comment]
You can use `/npc inventory` and fill up the first row freely

**Comment by Drc-DEV** [comment]
/npc inventory is a different command with a different purpose. Anyways it does not work for me, items that I put inside just disappear.

**Comment by mcmonkey4eva** [comment]
Update Citizens, you're running an outdated copy, that was fixed.
