### ISSUE TITLE
Problem with plugin

### ISSUE THREAD

**Issue by NicWartego** [CitizensDev/Citizens2#1724]
Hi, I have server on Aternos on version 1.13.2 on Spigot and plugin doesn't working on console i have this message 

[12:57:24] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1605) (Is it up to date?)
--
300 | java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
301 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
302 | at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_202]
303 | at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
304 | at net.citizensnpcs.Citizens.onEnable(Citizens.java:266) ~[?:?]
305 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
306 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
307 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
308 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
309 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
310 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:809) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
311 | at org.bukkit.Bukkit.reload(Bukkit.java:604) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
312 | at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
313 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
314 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
315 | at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
316 | at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
317 | at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
318 | at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
319 | at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
320 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
321 | at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
322 | at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-5629554-4c8327f]
323 | at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-5629554-4c8327f]
324 | at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-5629554-4c8327f]
325 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-5629554-4c8327f]
326 | at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-5629554-4c8327f]
327 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
328 | Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
329 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
330 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[minecraft_server.jar:git-Spigot-5629554-4c8327f]
331 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
332 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
333 | ... 27 more

**Comment by SXRWahrheit** [comment]
You must run the latest Spigot AND the latest Citizens together if you use the newest version of either. Aternos does not allow custom jar uploads; get a host that does.

**Comment by NicWartego** [comment]
I have latest Spigot and the latest Citizens

**Comment by SXRWahrheit** [comment]
No you do not:

https://ci.citizensnpcs.co/job/Citizens2/

**Comment by NicWartego** [comment]
On Aternos this version is the latest.

**Comment by SXRWahrheit** [comment]
It is not ACTUALLY the latest version, that is the problem.

**Comment by mcmonkey4eva** [comment]
Get a better host. One that allows for you to upload plugin and server jars.
