### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NicWartego** [CitizensDev/Citizens2#1725]
Can I make citizen sits?

**Comment by mergu** [comment]
Install Denizen - it allows you to use `/npc sit` and a few other new citizens commands: https://ci.citizensnpcs.co/job/Denizen

**Comment by NicWartego** [comment]
Can I make Citizen attack me?

**Comment by mergu** [comment]
With Sentinel, yes: https://ci.citizensnpcs.co/job/Sentinel/

Please also see `Join us on Discord if you have any other questions or need help: https://discord.gg/Q6pZGSR`, and close this issue.

**Comment by mcmonkey4eva** [comment]
For info about Sentinel, see here: https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md and if interested in more info about Denizen other than via Discord see here: https://www.spigotmc.org/resources/denizen.21039/
But please do join the discord for discussion / help / info / etc.
