### ISSUE TITLE
Problems with /npc moveto --yaw (yaw) --pitch (pitch)

### ISSUE THREAD

**Issue by JOO200** [CitizensDev/Citizens2#1726]
I have problems with the command /npc moveto --yaw (yaw) --pitch (pitch).
After executing the command the NPC does spin arround but doesn't look to the defined direction. The output from `/npc moveto --yaw 0 --pitch 0` followed by `/npc moveto --pitch 0` results in a weird number at the yaw coordinate.

The server is a fresh setup, all configs are on default, latest Paper and Citizens version, no BungeeCord or Mods.

ServerLog: https://pastebin.com/VbkCMHFf

The output of command `/version` on my server is: git-Paper-588 (MC: 1.13.2)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1626)

**Comment by mcmonkey4eva** [comment]
Replication testing on Spigot e6eb36f (MC 1.13.2), Citizens 1626.
Usage in general, pitch works perfectly fine, yaw only rotates the body, not the head.
Output format is a mess (it's showing the Bukkit `Location#toString()` which is a mess).
However, the pitch and yaw values in the output format are correct, which the exception of yaw value in subsequent usages (that don't change the yaw) being very wrong.

It seems like I've replicated the issue but yaw and pitch are changed around. Is it possible you've mixed them up in your post @JOO200 ? Or are we actually seeing reversed results?

**Comment by JOO200** [comment]
You're right, my fault.
The messed up values are at the yaw-coordinate, not the pitch coordinate.

**Comment by mcmonkey4eva** [comment]
Might be fixed in build 1627.

**Comment by JOO200** [comment]
Yes, works fine now. Thanks for the fast fix.
