### ISSUE TITLE
spigot 1.13.2 can't load

### ISSUE THREAD

**Issue by p82183645** [CitizensDev/Citizens2#1727]
![image](https://user-images.githubusercontent.com/5382252/55271152-50503b80-52e3-11e9-8f52-fddff5a930c9.png)

The output of command `/version` on my server is: **(PLEASE FILL IN)** 1.13.2
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** build 1627

**Comment by mcmonkey4eva** [comment]
`The output of command /version on my server is: (PLEASE FILL IN) 1.13.2
The output of command /version citizens on my server is: (PLEASE FILL IN) build 1627`
Neither of those are the output of the relevant commands.

Either way - update Spigot, as that's the source of the error.
