### ISSUE TITLE
plugins can't load

### ISSUE THREAD

**Issue by p82183645** [CitizensDev/Citizens2#1729]
![image](https://user-images.githubusercontent.com/5382252/55319446-77f00100-54a7-11e9-82a4-44fd02318b11.png)

The output of command `/version` on my server is: **(PLEASE FILL IN)** 1.13.2 spigot (I use the latest version)
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** b1628

**Comment by mcmonkey4eva** [comment]
`1.13.2 spigot (I use the latest version)` No you don't, update Spigot (via buildtools of course https://www.spigotmc.org/wiki/buildtools/ )

This was already answered in https://github.com/CitizensDev/Citizens2/issues/1727 and https://github.com/CitizensDev/Citizens2/issues/1716

If you post another issue for this same thing I'm going to consider it spam and report you to GitHub staff.
