### ISSUE TITLE
Citizens 2 - Spamming Error On Console

### ISSUE THREAD

**Issue by One4Fun11** [CitizensDev/Citizens2#173]
I've Just Chance From Citizens To Citizens 2, after i download the right version (2.0.11 For MC 1.7.*), my server version is craftbukkit 1.7.2 R0.3, then the console is spamming some error message from Citizens 2, i don't know what is the problem, all i know this issue happen when i'm put the Citizens 2 plugin, and did the Citizens 2 need CitizensAPI, is it right?
http://pastebin.com/PPDA1ydZ

**Comment by fullwall** [comment]
Seems like a towny issue - ask them about it.
