### ISSUE TITLE
Sound Command. Where is the sounds?

### ISSUE THREAD

**Issue by AlexBanPer** [CitizensDev/Citizens2#1735]
I would like to know where I can find the list of sounds to enter, because everything I try to place appears to me the id does not exist.

The output of command `/version` on my server is: 1.13.2
The output of command `/version citizens` on my server is: 2.0.24

**Comment by mcmonkey4eva** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
