### ISSUE TITLE
1.13.2 Paper?

### ISSUE THREAD

**Issue by Darkweasam** [CitizensDev/Citizens2#1736]
Citizens wont load at all with the error below:

Error: https://hastebin.com/socivarite.js
Citizens config is clean installed, without changes to anything

Citizens version 2.0.24-SNAPSHOT (build 1605)
This server is running Paper version git-Paper-609 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
You're running a very outdated version of Citizens. Update.
https://ci.citizensnpcs.co/job/Citizens2/

**Comment by Darkweasam** [comment]
> 
10.04 03:53:44 [Server] INFO [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1628) 
10.04 03:53:45 [Server] ERROR Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1628) (Is it up to date?) 
10.04 03:53:45 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$PooledBlockPosition 
10.04 03:53:45 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181] 
10.04 03:53:45 [Server] INFO at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181] 
10.04 03:53:45 [Server] INFO at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?] 
10.04 03:53:45 [Server] INFO at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?] 
10.04 03:53:45 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] 
10.04 03:53:45 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$PooledBlockPosition 
10.04 03:53:45 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-e769fe4-068dab5] 
10.04 03:53:45 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181] 
10.04 03:53:45 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181] 
10.04 03:53:45 [Server] INFO ... 15 more

**Comment by mergu** [comment]
You also need to update your Spigot/Paper build. That log you just posted shows you running a build from last year.

**Comment by mcmonkey4eva** [comment]
You went out of your way to switch _from_ an updated Paper build _to_ an outdated Spigot build. Why?!
