### ISSUE TITLE
fawe compatibility

### ISSUE THREAD

**Issue by cicatrice74** [CitizensDev/Citizens2#1737]
Can u please add compatibility with latest FAWE for 1.13+ ?

**Comment by SXRWahrheit** [comment]
Why is this relevant to Citizens? Regardless, it's FAWE that needs to update and/or add compatibility, not Citizens.

**Comment by mcmonkey4eva** [comment]
This request makes no sense. What do Citizens and FAWE have to do with each other at all?

Also, a quick glance at your GitHub profile shows you run a cracked server. See information here: https://wiki.citizensnpcs.co/Cracks
