### ISSUE TITLE
Additional arguments to waypoint configuration

### ISSUE THREAD

**Issue by BehrRiley** [CitizensDev/Citizens2#1738]
> A detailed description of your issue or feature request

Currently, NPCs can be given waypoints to dictate their motion using three providers, and further optimization is done in the waypoint editors. Would like request additional arguments to specify locations and configuration through commands instead. Specifically interested in compatibility with Denizen to run commands based on script, rather than entering an editor and manually setting options

**Comment by mcmonkey4eva** [comment]
Would this not work better as a Denizen issue, if you want compatibility with Denizen?
There's already some options available like dNPC mechanism `add_waypoint`.

**Comment by BehrRiley** [comment]
> Would this not work better as a Denizen issue, if you want compatibility with Denizen?

I don't believe the mechanism work's for wandering, just for the linear provider

**Comment by mcmonkey4eva** [comment]
Added that (wandering support for the mechs) in the new Denizen dev build. For other features you want supported, open an issue at the Denizen repo.
