### ISSUE TITLE
Citizens throws "Is it up to date?" error

### ISSUE THREAD

**Issue by TheRealVicere** [CitizensDev/Citizens2#1739]
The output of command `/version` on my server is:
`This server is running CraftBukkit version git-Spigot-f09662d-7c395d4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

The output of command `/version citizens` on my server is:
`Citizens version 2.0.24-SNAPSHOT (build 1605)`

Citizens will not load upon starting the server. The error I get can be found here:
https://pastebin.com/5RtVCJnF

Please let me know how I can fix this.

**Comment by SXRWahrheit** [comment]
You are using an old build of Citizens. Please update (and also consider updating Spigot, just to be sure):

https://ci.citizensnpcs.co/job/Citizens2
