### ISSUE TITLE
Citizens NPC Vanishing + Losing Skins

### ISSUE THREAD

**Issue by InfinityAspire** [CitizensDev/Citizens2#174]
I've seen a few posts referencing these issues partially but none that are the same.

Using latest Spigot 1.8 Build
Using Citizens Dev Build #1200

Using approx 13 idle statues.
Spawning statues in has a 50/50 chance of getting the skin
Typing '/citizens reload' loads the correct skins after doing /citizens save to be safe
If I go 3-4 chunks away and come back, some of the NPC's are invisible. '/citizens reload' a few times brings a few of them back but never all.
On rare occasions it looks like a Steve statue is inside of the normal player one.

![image](https://cloud.githubusercontent.com/assets/9050130/5591835/02301972-9189-11e4-8b66-3e995febfd2c.png)
![image](https://cloud.githubusercontent.com/assets/9050130/5591836/0ba35b40-9189-11e4-8203-61766db88571.png)
![image](https://cloud.githubusercontent.com/assets/9050130/5591837/12feac8c-9189-11e4-9765-cc5be438ad57.png)

**Comment by CKGAR** [comment]
I can confirm this bug, as it is happening on my server with the same versions. NPCs which are set to mob types also disappear and do not reappear until ./citizens reload.

**Comment by fullwall** [comment]
Does it work with build 1190?

**Comment by InfinityAspire** [comment]
I cannot test this as my server has constant players, if someone else could verify please.

**Comment by CKGAR** [comment]
I can confirm this bug for all recent versions, as it has been in most if not all versions of me switching through Spigot and Citizens. I however cannot test and isolate the problem, because I have constant players as well. Hope this issue is resolved quickly, as it defeats the purpose of Citizens.

**Comment by fullwall** [comment]
Including 1190 @CKGAR ? Sorry but I'm having troubles isolating this bug because I do not have a big server to test on.

**Comment by CKGAR** [comment]
Are you implying for me to downgrade to the Dec. 1st build? Even if I'm running the latest build of Spigot?

**Comment by mcmonkey4eva** [comment]
Yeah, at least to test.

**Comment by CKGAR** [comment]
I'll test it out asap, but like I said I have 30+ people on constantly so I'll restart when pop dies down later!

**Comment by fullwall** [comment]
@CKGAR - coming up with a new approach that might work more reliably.

**Comment by fullwall** [comment]
Can you try with the latest build?

**Comment by CKGAR** [comment]
Sure, I'll try that one first

**Comment by CKGAR** [comment]
The most recent build fixes my issue. Thank you.
