### ISSUE TITLE
NPC's won't open doors with the new pathfinder

### ISSUE THREAD

**Issue by BehrRiley** [CitizensDev/Citizens2#1740]
No actual errors of citizens during the navigator, the npc just runs into the door and tries to walk through it, NPC just slides along the wall if the location is angled right
if you try and open the door for it, the NPC spam-shuts the door before it can enter
NPC also shuts the door if the NPC approaches the door it's navigating through if the door is left open, and runs into the door

Console: https://hastebin.com/fuqiquhiko.md
Config: https://hastebin.com/yoqagazuye.coffeescript

The output of command `/version` on my server is:
```
This server is running Paper version git-Paper-616 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-591 (MC: 1.13.2)
You are running the latest version
```

The output of command `/version citizens` on my server is:
```
Citizens version 2.0.24-SNAPSHOT (build 1629)
Website: http://www.citizensnpcs.co
Authors: aPunch and fullwall
```

**Comment by mcmonkey4eva** [comment]
Cannot replicate on
```
[21:40:19 INFO]: This server is running CraftBukkit version git-Spigot-f09662d-f40143e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[21:40:19 INFO]: You are 2 version(s) behind
```
and Citizens 1629

Perhaps local to paper, or related to interop with another plugin?
Please test a standard spigot server and/or a server with other plugins removed

**Comment by BehrRiley** [comment]
The only plugins are Denizen, Citizens, Sentinel, Vault and UPerms. removing UPerms and Vault didn't do anything, UPerms is just a permission plugin. 
Just tried again with a Spigot version and got the same result, only the NPC doesn't slam the door shut in it's face before it can get through the door. No errors in the console; do you want the startup again?

**Comment by mcmonkey4eva** [comment]
the `NPC just slides along the wall if the location is angled right` part is #1730 which is a replicated issue.

Slamming the door shut in its face is the unique point in this issue... if that doesn't replicate on Spigot, it's a Paper-induced error.

**Comment by BehrRiley** [comment]
```
[01:01:02 INFO]: This server is running CraftBukkit version git-Spigot-f09662d-7c395d4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[01:01:02 INFO]: Checking version, please wait...
[01:01:03 INFO]: You are running the latest version
```
My spigot was 10 behind, updated and it fixed the issue, it's alltogether a paper erorr then. thanks for the help

**Comment by mcmonkey4eva** [comment]
Wall sliding is an active issue even on current spigot (see the issue I linked above)
You already identified door slamming was fixed on your older spigot...
What exactly was fixed by the spigot update?

**Comment by BehrRiley** [comment]
The NPC opens the door now

**Comment by mcmonkey4eva** [comment]
Oh, right, makes sense. Good that that's all working. 

... Wonder what in paper broke door handling though...
