### ISSUE TITLE
Enchantments disappearing

### ISSUE THREAD

**Issue by Geeeeri** [CitizensDev/Citizens2#1741]
The output of command `/version` on my server is: 1.13.2-R0.1-SNAPSHOT
The output of command `/version citizens` on my server is: 2.2.24-SNAPSHOT (build 1626)
Config: https://pastebin.com/Tv3piaK7
Log: https://pastebin.com/5NXGP90s 
Problem: Items that are by default not possible to get such as command blocks with an enchantment disappear on restart.
Step 1: Give yourself a command block with  `/i command_block` or any other command.
Step 2: Enchant it with an anvil. (I gave it a mending enchantment)
Step 3: Give your NPC the item with `/npc equip`
Step 4: Reload/Restart your server and the item lost its enchantment.
Video of me doing this: https://streamable.com/u33ke

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
