### ISSUE TITLE
Enchantments disappearing - Online mode

### ISSUE THREAD

**Issue by Geeeeri** [CitizensDev/Citizens2#1742]
The output of command /version on my server is: 1.13.2-R0.1-SNAPSHOT
The output of command /version citizens on my server is: 2.2.24-SNAPSHOT (build 1626)
Config: https://pastebin.com/Tv3piaK7
Log: https://pastebin.com/JxT8zEDB
Problem: Items that are by default not possible to get such as command blocks with an enchantment disappear on restart.
Step 1: Give yourself a command block with /i command_block or any other command.
Step 2: Enchant it with an anvil. (I gave it a mending enchantment)
Step 3: Give your NPC the item with /npc equip
Step 4: Reload/Restart your server and the item lost its enchantment.
Video of my doing this while on a legit copy of minecraft with a legit server: https://streamable.com/nrli9

**Comment by mcmonkey4eva** [comment]
Please do not use the `/reload` command. Ever.
It breaks a lot of plugin functionality.

Is this issue specific to command blocks / similar only?

**Comment by mcmonkey4eva** [comment]
My guess to the solution here is that in this code: https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/util/ItemStorage.java#L253
The `addEnchantments` call should be changed to `addUnsafeEnchantments`.
The "safe" variant will refuse to add enchantments that don't belong on an item, while "unsafe" will appropriately bypass this.

**Comment by Geeeeri** [comment]
> Please do not use the `/reload` command. Ever.
> It breaks a lot of plugin functionality.
> 
> Is this issue specific to command blocks / similar only?
Understood.
Not sure what the exact problem is, works with legit items such as enchanted swords though. 
As you can see:  https://streamable.com/5q8x2 Same problem with structure block, structure void, other type of command blocks, barrier.

**Comment by Geeeeri** [comment]
That makes sense, thank you.
