### ISSUE TITLE
EnderDragon target getting stuck

### ISSUE THREAD

**Issue by maldahleh** [CitizensDev/Citizens2#1743]
The output of command `/version` on my server is: 1.13.2-R0.1-SNAPSHOT
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1626)

I am spawning in an ender dragon at a random coordinate, and setting the target for the dragon to be another position that is vertically above the spawn position, because I want the dragon to fly to the point vertically.

The NavigationStuckEvent is thrown, I assume because the random point may be one that is within blocks. Is there a way to make it so that the dragon breaks any blocks in its path?

**Comment by mcmonkey4eva** [comment]
I don't think you'd want to use the navigator _at all_ if you want the dragon just plowing through things... rather just push it along a straight line.

**Comment by maldahleh** [comment]
That's actually a fair point, thanks.
