### ISSUE TITLE
Citizens2 - 1.13 Error

### ISSUE THREAD

**Issue by MrDsa1** [CitizensDev/Citizens2#1744]
The fact is that I can’t install Citizens2 on Minecraft server 1.13 in any way, I’ve been able to install different versions of the plugin, from the newest to the oldest (fot version 1.13), constantly get an error in the console:

P.s Sorry for my English

> [21:41:06] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1605)
> [21:41:06] [Server thread/INFO]: Creating file: config.yml
> [21:41:06] [Server thread/ERROR]: [Citizens] v2.0.24-SNAPSHOT (build 1605) is not compatible with Minecraft v1_13_R1 - try upgrading or downgrading Citizens. Disabling.

**Comment by mergu** [comment]
1.13 is not a valid server version. It's unsupportable and full of bugs and dupe glitches. Update to 1.13.2
