### ISSUE TITLE
Server crashed by Citizens

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [CitizensDev/Citizens2#1745]
The output of command `/version` on my server is: **Paper(621) 1.13.2-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1631)**

I had problem, that my server started crashing suddenly and i found out the reason was Citizens. I wasnt changing anything, including spigot or plugin version, configuration or even most of npcs for months. Latest NPC i made was from a few days ago, but problem occured today in the night. When I updated plugin and spigot to newest versions the error still occured. So i deleted the saves.yml and then then i started pasting all npcs part after part to find this one, which is causing problems. But when i pasted them all the problem was not occuring anymore. I restarted server and everything was still working fine. But im scared, that it would happen again, so i writed this issue to get more information about this and how i can prevent this situations. Previous versions, on which issue occured for thefirst time was Paper 500 and Citizens 1605

saves.yml https://pastebin.com/dK3kwuJh
config.yml https://pastebin.com/MfJa3wYd
Crash https://pastebin.com/Ea211W2g
Full log https://pastebin.com/Eu40j2mi

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
