### ISSUE TITLE
Updated/Not working

### ISSUE THREAD

**Issue by QueenKisaki** [CitizensDev/Citizens2#1746]
Here is a full startup. Not sure why the latest update will not load: https://pastebin.com/ATwdNbTw

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 19.04 12:22:47 [Server] INFO Citizens version 2.0.24-SNAPSHOT (build 1626)
19.04 12:22:47 [Server] INFO Website: http://www.citizensnpcs.co
19.04 12:22:47 [Server] INFO Authors: aPunch and fullwall

**Comment by mcmonkey4eva** [comment]
Update your copy of Spigot (via buildtools) that one is outdated.
