### ISSUE TITLE
Unforeseen consequence of SkinnableEntity.setSkinPersistent()

### ISSUE THREAD

**Issue by Dymeth** [CitizensDev/Citizens2#1748]
For a long time, I could not understand why the _entity.getLocation()_ returns the initial position of the NPC, but not the current one. entity - this is an bukkit-object that is returned by _NPCRegistry.createNPC(...)_

Apparently, _SkinnableEntity.setSkinPersistent()_ changes the object inside the NPCRegistry.
To check it, I used the following code:
`Entity oldEntity = CitizensAPI.getNPCRegistry().createNPC(...);
...
((SkinnableEntity) oldEntity).setSkinPersistent(this.id, this.signature, this.value);
Entity newEntity = CitizensAPI.getNPCRegistry().getNPC(oldEntity).getEntity();
if (oldEntity == newEntity)
    System.out.println("equals");
else
    System.out.println("not equals");`
As a result, I received "not equals".

The _setSkinPersistent_ method does not return an Entity, so in order to get the correct entity location I had to use the following:
`entity = CitizensAPI.getNPCRegistry().getNPC(entity).getEntity();`

The output of command `/version` on my server is: git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1631)

**Comment by mcmonkey4eva** [comment]
Always use `npc.getEntity()`, never store the Entity object.

NPCs regularly respawn in-place when needed, skin changes is one such case where this is necessary.
