### ISSUE TITLE
Rabbit NPC Jumping while standing still

### ISSUE THREAD

**Issue by boyswithluv** [CitizensDev/Citizens2#1749]
When you create a rabbit NPC, they will keep jumping even though they should stay still

The output of command `/version` on my server is: *see screenshot below*
The output of command `/version citizens` on my server is: *see screenshot below*
![5aed24034322fad9df6788a41e9f6125](https://user-images.githubusercontent.com/7237978/56547827-cc564000-657e-11e9-89cb-8b8e24a2359a.png)

**Comment by fullwall** [comment]
Fixed in next build.
