### ISSUE TITLE
Task: Citizens$2(Single) is laggy on /timings paste

### ISSUE THREAD

**Issue by danmark2312** [CitizensDev/Citizens2#175]
I'm running the latest spigot build from buildtools.jar

My server has been getting this error recently in 1.8
       0.08%	 593.99%	  0.30 s	   296.99 ms	 0.0	       0.0k	    Task: Citizens$2(Single)

It seems to have a huge impact on my server along with other plugins, I got no clue where this comes from

**Comment by fullwall** [comment]
That is the save task which saves all NPCs to disk every so often. I don't think the run count will be very high on the timings but the timing is configurable in the Citizens settings.
