### ISSUE TITLE
Error occurred while enabling Citizens

### ISSUE THREAD

**Issue by CitrusFruit** [CitizensDev/Citizens2#1750]
The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
24.04 11:14:54 [Server] INFO This is a final build for 1.13.2.**
The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1605)**

Error: https://pastebin.com/kTKkLKKg

I looked through related issues and saw the latest Spigot needs to be used but I am using the latest 1.13.2 Spigot and I still get this error.

**Comment by mcmonkey4eva** [comment]
You're running an outdated copy of **Citizens** in this case. https://ci.citizensnpcs.co/job/Citizens2/
