### ISSUE TITLE
Citizens Not Creating | No command output | no errors

### ISSUE THREAD

**Issue by Adsnipers** [CitizensDev/Citizens2#1751]
hey, citizens plugin will not create citizens, when I do the command /npc create <name> it just does nothing, no errors in the console nothing. here is my list of plugins

![image](https://user-images.githubusercontent.com/38774365/56745379-9a7eec80-67bd-11e9-97db-bc8500a6c953.png)
Nothing comes up no matter what I type relating to citizens

**Comment by mcmonkey4eva** [comment]
Look in your **server console** (not some multicraft pseudoconsole or in-game chat or anything else) and **startup logs** for error messages. Most likely there is one.
The error is also quite likely to be a versions problem.
Please update to latest Spigot (via BuildTools) or Paper for 1.12.2 or 1.13.2,
and the final stable release of Citizens https://ci.citizensnpcs.co/job/Citizens2/1636/ (as work on 1.14 has begun)
