### ISSUE TITLE
Citizens wont really load

### ISSUE THREAD

**Issue by AdvancedGP** [CitizensDev/Citizens2#1755]
Spigot Version: 
https://imgur.com/a/cGv2lhB

Citizens Version:
2.0.24-SNAPSHOT (build 1604)

Problem:
https://hastebin.com/vifidewimi.cs
Citizens is loaded in my /plugin, commands "half" appear, like the commands exist, but show absolutely no output or error message in chat or console. no commands work. i never touched the config.

**Comment by mcmonkey4eva** [comment]
Update Citizens to latest stable 1.13.2 build: https://ci.citizensnpcs.co/job/Citizens2/1636/

(Newer builds are in-dev for 1.14, you're running a much much older build for 1.13-ish)
