### ISSUE TITLE
Trait where entity is looking around?

### ISSUE THREAD

**Issue by Sago92** [CitizensDev/Citizens2#1756]
Dear Development-Team,

I have a little question that coulnd't get answered by my research or over your wiki/help.

I am using the Citizens API for my NPC management for my in progress MMORPG Server.

I took a look into the available traits and ask myself if there is any trait where the NPC look randomly around. The LookClose Trait only looks at a player when he is nearby. Is there any trait or other trick how I can configure my NPC that it would move his head randomly around? Maybe in combination with the LookClose Trait?

Regards
Sascha

**Comment by fullwall** [comment]
If you are using the API yourself you can just add this trait. I will add an option though.

**Comment by Sago92** [comment]
I think you missunterstood my question. I already added the LookClose Trait and it works perfectly. I wanted to know if there is any Trait or setting for the NPC where it looks randomly around when for example no player is nearby. I know I could create a custom trait for this, but maybe I overlook something and this feature/trait already exists in Citizens

**Comment by mcmonkey4eva** [comment]
That's not an existing feature

**Comment by Sago92** [comment]
Thanks for the replay. Then I will create an own trait for this. Nevertheless would you add this topic as a feature request?

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/commit/53efb60b6826f5b262cbf1ed7075453ffef88f7a adds this

**Comment by Sago92** [comment]
Do you have an exampe how I setup this new property over the API?

![Screenshot](https://i.ibb.co/DGzcH7n/1.png)

**Comment by mcmonkey4eva** [comment]
Call the methods listed here: https://github.com/CitizensDev/Citizens2/commit/53efb60b6826f5b262cbf1ed7075453ffef88f7a#diff-22c18da05baaf10a71ee50d93f87f1bcR153
