### ISSUE TITLE
tablist in 1.14  flickers strongly

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#1757]
I have the version: Citizens-2.0.25-b1663.jar for spigot:
CraftBukkit version git-Spigot-47463c2-6de3aa1 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

It already works very well
Only with the tablist there s still problem it still flickers strongly

**Comment by Totten98** [comment]
Hi, I can confirm this bug, even with the tablist disabled on the config file they flicker on the tablist...
I can't figure out why unfortunately, but i just wanted to confirm that the bug is there :)

Totten98.

**Comment by fullwall** [comment]
Thanks, I've also confirmed.

**Comment by Blueeyestar** [comment]
The problem was fixed with the version : Citizens-2.0.25-b1666.
Good work :)

**Comment by Totten98** [comment]
Thanks a lot :) you're awesome!

Totten98.

**Comment by fullwall** [comment]
Please reoopen if there is still an issue.
