### ISSUE TITLE
Could not pass event ChunkUnloadEvent to Citizens v2.0.25-SNAPSHOT (build 1667)

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#1759]
Citizens build:(build 1667)

Spigot:CraftBukkit version git-Spigot-e4be9b0-5736cdc (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

unfortunately we found a long console error in the newest version. I hope you can fix the bug.

https://pastebin.com/7zibzQC4

**Comment by fullwall** [comment]
Does the latest build help

**Comment by Blueeyestar** [comment]
I'm testing it now and I'll let you know.

**Comment by Blueeyestar** [comment]
Unfortunately I have to inform you that there are still problems with the ChunkUnloadEvent.

https://pastebin.com/2nUGuA4m

**Comment by Blueeyestar** [comment]
also shopkeeper has this problem. is probably a homemade problem

https://hub.spigotmc.org/jira/browse/SPIGOT-4752

**Comment by fullwall** [comment]
What about the latest build?

**Comment by Blueeyestar** [comment]
hello, with the newest file Citizens-2.0.25-b1669.jar there are no more errors at the moment. So I think this is a good sign. Good work :)
