### ISSUE TITLE
Doesn't load with 1.7.10-SNAPSHOT build 1649

### ISSUE THREAD

**Issue by fujiboy4** [CitizensDev/Citizens2#176]
My server (BungeeCord) won't allow Citizens to load... I do use spigot (build 1649). I tried the latest and second latest of Citizens and it still doesn't work...  If they came out with a hidden craftbukkit/spigot that I didn't see please leave the download here.  Thx! :D

**Comment by mcmonkey4eva** [comment]
Older Citizens: http://wiki.citizensnpcs.co/Versions
Newer Spigot: http://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-8.36598/
Pick your favorite.
