### ISSUE TITLE
Navigation Doesn't Pause

### ISSUE THREAD

**Issue by tchristofferson** [CitizensDev/Citizens2#1762]
The output of command `/version` on my server is: git-Spigot-766dab2-8f2a45b (MC: 1.14)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1667)

`NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.VILLAGER, ChatColor.GREEN + "" + ChatColor.BOLD + "Stockbroker");`
`npc.setProtected(true);`
`npc.getNavigator().setPaused(true);`
`npc.getTrait(VillagerProfession.class).setProfession(Villager.Profession.FARMER);`
`stockbrokers.add(npc.getUniqueId());`
`npc.spawn(location);`

My code is above this is all I do. In 1.13.2 it works, but in 1.14 the villager still walks around. The npc.getNavigator().setPaused(true) doesn't work.

**Comment by fullwall** [comment]
Couldn't reproduce this. Are you sure it's not a problem with minecraft AI not being overriden properly?

**Comment by tchristofferson** [comment]
I'm not overriding anything. The only code I use is the code I pasted above.

**Comment by mcmonkey4eva** [comment]
This is likely related to an error with villager type NPCs in 1.14, which has been fixed in build 1670. Can you please test whether that build resolves the issue?

**Comment by tchristofferson** [comment]
Yup its fixed thanks!
