### ISSUE TITLE
NPC TYPE DOESNT WORK

### ISSUE THREAD

**Issue by naikyy** [CitizensDev/Citizens2#1767]
That problem appears when I use /npc type fox, or pig.. cow.. doesnt matter¨

https://pastebin.com/ZWTYzG5y

**Comment by fullwall** [comment]
Can you post your full startup log please

**Comment by naikyy** [comment]
https://pastebin.com/Eb8PWSfJ

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
