### ISSUE TITLE
1.14 Console Error on ChunkLoadEvent

### ISSUE THREAD

**Issue by Lix3nn53** [CitizensDev/Citizens2#1769]
The output of command `/version` on my server is: [22:10:12] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1eece4f-68e72f6 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
[22:10:12] [Server thread/INFO]: You are running the latest version

The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1671)

None of my NPC loads (I can't see any NPC in game) and I get this error on chunk load: http://pasted.co/e922715e

**Comment by mcmonkey4eva** [comment]
Could you please find
```yml
general:
  debug-mode: false
```
in your Citizens config, and set that to `true`, then cause the error message again, and paste any debug that appears just before or after an error message?

**Comment by Lix3nn53** [comment]
I didn't get to NPE at chunkLoadEvent this time but NPCs still doesn't load even if debug messages says otherwise. Full log this time: http://pasted.co/6f25fa05

**Comment by mcmonkey4eva** [comment]
`
[22:40:38] [Server thread/INFO]: Spawned id 54 due to chunk event at [-186,305]
[22:40:39] [Server thread/INFO]: Spawned id 45 due to chunk event at [-190,301]
[22:40:40] [Server thread/INFO]: Spawned id 19 due to chunk event at [-193,309]`
Were none of these NPCs spawned?

**Comment by mcmonkey4eva** [comment]
Er... also can you try removing `LibsDisguises `, which appears to be outputting a lot of errors (likely just not updated for 1.14?) and might even be causing problems.

**Comment by Lix3nn53** [comment]
Yes at least I can't see them in game. I remember at older version of citizens on 1.14 my villager NPCs spawned but moved. (there was a fix for Villagers still having AI)

I am removing some entities on chunk load/unload events but always check NPCRegistry#isNPC before removing.

Do I have to change somethings (other than villager professions) while updating to 1.14?
saves.yml: http://pasted.co/166748a6
Gonna remove LibsDisguises and try again

**Comment by mcmonkey4eva** [comment]
Are you running a cracked server?

**Comment by Lix3nn53** [comment]
Removing LibsDisguises disabled the plugin removes entities on chunk events. 
All Player type NPCs loaded except those named Character 1,...,Character 4 (there is an error for them)
None of my Villager type NPCs loaded.
log: http://pasted.co/febbeae0

Yes online-mode=false in server.properties atm. It runs on my computer. My launcher is original tho. Does it matter?

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by Lix3nn53** [comment]
Alright sorry for taking your time then but I am just reporting a bug. I don't think the bug is special to my case. I don't understand what you are telling me to do here.

**Comment by mcmonkey4eva** [comment]
Please replicate the issue on a legitimate online-mode server. And always exclusively run legitimate online-mode servers.

**Comment by Lix3nn53** [comment]
This server is running on my computer, so all I need to do "online-mode=true" and remove player.dat files? and see if error keep happening?

**Comment by mcmonkey4eva** [comment]
Yes. And never change it back to `false`.

**Comment by Lix3nn53** [comment]
Log: http://pasted.co/6755faec
My report is same as before: 
Removing LibsDisguises disabled the plugin removes entities on chunk events.
All Player type NPCs loaded except those named Character 1,...,Character 4 (there is an error for them)
None of my Villager type NPCs loaded.

**Comment by mcmonkey4eva** [comment]
Are those 4 actually failing to spawn, or is it just the error but actually spawning fine?
(That's a debug stacktrace, it shouldn't be an actual blocking error)

**Comment by Lix3nn53** [comment]
They don't spawn, maybe cause they are close to world spawn point? I tried teleporting away and back again, no change.

**Comment by Lix3nn53** [comment]
Figured out it was because of another plugin, sorry to take your time
