### ISSUE TITLE
I can't Spawn NPC in 1.13.2

### ISSUE THREAD

**Issue by SkyBule2** [CitizensDev/Citizens2#1770]
I can;t use ./npc create <Name> in 1.13.2 Citizens
I type this command later it will do nothing

This is my Log:

[15:34:44] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1591) (Is it up to date?)
--
274 | java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
275 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
276 | at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_202]
277 | at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
278 | at net.citizensnpcs.Citizens.onEnable(Citizens.java:266) ~[?:?]
279 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
280 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
281 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
282 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
283 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
284 | at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
285 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
286 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
287 | at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
288 | at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
289 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
290 | Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
291 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
292 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
293 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
294 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
295 | ... 15 more

**Comment by mcmonkey4eva** [comment]
Update, you're on a very old build: https://ci.citizensnpcs.co/job/Citizens2/
