### ISSUE TITLE
Skins updating without -l option

### ISSUE THREAD

**Issue by NLBlacky** [CitizensDev/Citizens2#1771]
I've started using Citizens2 very recently as I only found the plugins a few weeks ago.

Since changing my own skin for all the villagers I wanted (total of 9) I decided to use a popular minecraft skin list to find usernames with the skins I wanted. The names were taken from https://nl.namemc.com/minecraft-skins.

After finding the skins I wanted, I ran the command "/npc skin [NAME]". I did not include "-l" as I don't want the skins to update

Days after I selected the skins, I noticed that a few of the skins "updated". I assume this is the updated skin of the player. I did not include "-l" so I'm confused why this is happening. Now we're a few more days futher and almost half of the skins have changes to a new skin. I would like to know why this is happening when I ran the command to not have them updated.

The output of command `/version` on my server is: 
![image](https://user-images.githubusercontent.com/42154364/57299370-a67b8000-70d4-11e9-922a-bc89e4cd6507.png)

The output of command `/version citizens` on my server is: 
![image](https://user-images.githubusercontent.com/42154364/57299382-b1361500-70d4-11e9-9d44-5ac3443a5128.png)

**Comment by fullwall** [comment]
Can you please send a copy of your config and saves.yml?

**Comment by NLBlacky** [comment]
Actually I just found out about this config, and I assume it is why I'm having this issue?

  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0

**Comment by mcmonkey4eva** [comment]
You're using a significantly outdated version of Citizens, from when `-l` didn't exist and `-p` was for persistent.
Update: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by NLBlacky** [comment]
But I downloaded the latest version posted here? https://dev.bukkit.org/projects/citizens/files

You might want to update it there or inform people about the new download link?

**Comment by fullwall** [comment]
@mcmonkey4eva is correct but always remember to check your config.

**Comment by fullwall** [comment]
![Capture](https://user-images.githubusercontent.com/626985/57301258-2b818c00-710b-11e9-85d0-5835cbd010a1.PNG)
