### ISSUE TITLE
JavaDocs have too little information

### ISSUE THREAD

**Issue by derteufelqwe** [CitizensDev/Citizens2#1773]
The output of command `/version` on my server is: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
You are 1 version(s) behind
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1675)

The JavaDocs are not usefull at all. All they say is which Classes and methods exist, which I can also check in my IDE. A full documentation should also contain details about the Classes, what they do, where to be careful, etc. Functions should get the same information.
For even better documentation I would also love some ecample code in the docs or an indepth tutorial for the API.
But the main point ist just to add a more sophisticated documentation.

After asking for a tutorial / a better documentation to create advanced NPCs using the Java CitizensAPI, fullwall told me to create an issure.

**Comment by fullwall** [comment]
Which classes do you specifically want documented? Which tutorials do you want on the wiki?

**Comment by derteufelqwe** [comment]
Mainly on:
- How to create a better AI (documentation on Traits and Behaviour)
- How to properly use Goals
- How to make the NPCs use equipment (and how to set it. I had to predict it out of the real plugin)
- Standard Traits (My NPC.getTraits() had some Traits which I couldn't find in the docs.)
- How to make the NPCs speak and react on speech.
- NPC.data() command (What to the constants actually do and what values to assign to them)

This would make it way easier for developers to get started.

**Comment by fullwall** [comment]
I have added some JavaDocs, although there was already some for Traits, Behaviors and Goals. Sounds like the rest of it could be done using a list of default Traits on the wiki + some info on them.
