### ISSUE TITLE
I purchased Citizens2 on the spigot website a little over 3 hours ago and never got the download.

### ISSUE THREAD

**Issue by MrRayhonda** [CitizensDev/Citizens2#1775]
As the title says, I paid for the plugin and I do see that it says it may take over an hour but it's been over 3 now. I'm just worried is all. I hope to get the purchase confirmed asap so I can download the plugin and add it to my server quickly to get things rolling ^^ Thanks!

**Comment by mergu** [comment]
Hello! Give this link a try: https://ci.citizensnpcs.co/job/Citizens2
