### ISSUE TITLE
Npcs won't go though door with new pathfinder

### ISSUE THREAD

**Issue by Nupper** [CitizensDev/Citizens2#1776]
![image](https://user-images.githubusercontent.com/6026902/57587308-f4402000-74fa-11e9-8aca-7587ef44365c.png)
![image](https://user-images.githubusercontent.com/6026902/57587344-86e0bf00-74fb-11e9-9f59-2dfc94235dbb.png)

Doors open with pressure plate....but do not open without pressure plates

This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens version 2.0.25-SNAPSHOT (build 1675)

**Comment by jack-theripper** [comment]
https://github.com/jack-theripper/Citizens2/commit/07b473ad31ab7b452eae2c1b754cee03cdd5be0c
https://github.com/jack-theripper/CitizensAPI/commit/8eab2193e77817149768c52d66e7cf00b393ea91

**Comment by fullwall** [comment]
Implemented jack's fixes, thanks.
