### ISSUE TITLE
Error /npc create

### ISSUE THREAD

**Issue by Cerexus** [CitizensDev/Citizens2#1779]
https://pastebin.com/AvxmKsdN

The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-8043ebc-dd99c5b (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1692)**

**Comment by fullwall** [comment]
What's your startup log?

**Comment by Cerexus** [comment]
https://pastebin.com/tBALinGb


Fresh citzens setup without any setting.

**Comment by fullwall** [comment]
What JVM are you using?

**Comment by Cerexus** [comment]
Java 12

**Comment by mergu** [comment]
Minecraft & Spigot & Citizens are built to run on Java 8

**Comment by Cerexus** [comment]
Minecraft & Spigot have absolutly no problem with java 12. Java 8 is outdated. The performance on java 12 is better.

**Comment by Cerexus** [comment]
So do you add support for java 12 or have i go to java 11?:/

**Comment by fullwall** [comment]
Can you try and see if java 11 fixes the issue? If java 12 is the problem we can look into fixing it for that java.

**Comment by Cerexus** [comment]
Hm.. Okay I'll try it later but i would really prefer Java 12 bc i used myself some new features.. ^^ But if you say no, its okay :).

**Comment by fullwall** [comment]
Per https://bugs.openjdk.java.net/browse/JDK-8210496 Java 12 is the issue here.

**Comment by mergu** [comment]
Java 8 and 11 are the current LTS versions: https://minecraft.gamepedia.com/Tutorials/Update_Java

**Comment by fullwall** [comment]
I believe there is a solution for Java 12, just need to work it up a bit more tomorrow.

**Comment by Cerexus** [comment]
mergu But things like the GC are much better in newer Versions. 

Like I said, Minecraft and Spigot have no problems with Java 12.  My Client runs on it and my server.  



Fullwall, thank you for your help :) My Users really enjoy your Work and miss Citizens^^ You'll recieve a donation if i get one from my Users :)

**Comment by fullwall** [comment]
Should be fixed for java 12 now. Reopen if not.

**Comment by Cerexus** [comment]
I'll try later when i am at home. Thank you!
