### ISSUE TITLE
Move moduled traits out of modules

### ISSUE THREAD

**Issue by derteufelqwe** [CitizensDev/Citizens2#1783]
The output of command /version on my server is: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
You are 1 version(s) behind
The output of command /version citizens on my server is: Citizens version 2.0.25-SNAPSHOT (build 1675)

The documented / listed Traits by far not all traits available. I found about 3 - 4 Times
as many traits in the source code. But I can't always predict what these traits do (and mabe how to use them) just from the name.
Adding the missing traits to the docs and adding a description to all traits would be really helpful.
A few example I can remember atm are:
- BossBarTrait
- OcelotTrait
- LamaTrait

**Comment by mcmonkey4eva** [comment]
Those latter 3 traits are actually ... weird cases, as they don't quite exist where they probably should?
They're chopped into modules: https://github.com/CitizensDev/Citizens2/tree/master/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/trait
Which makes it rather messy to document them or to use them.
I think it'd be a relevant fix here to move those out of NMS modules, and simply chain their functionality calls into the relevant modules.
