### ISSUE TITLE
Access NPCRegistry after load

### ISSUE THREAD

**Issue by Sago92** [CitizensDev/Citizens2#1784]
Version of Citizens: Citizens-2.0.25-b1661

Dear Development Team,

I am using Citizens for my own NPC managment. In my plugin.yml of my own plugin I have the dependency and the load before of Citizens.

loadbefore: [Citizens]
depend: [Citizens]

The behavior that I am currently facing is, that after Citizens is loaded, that the NPCs theirself aren't loaded in the NPCRegistry yet. If I delay the access to the NPCRegistry by 3 or more seconds, the NPCs are loaded and I can use the iterator for my own entity management/assignment.

Because I have several logic that isn't delayed, it can cause some strange behavior in my plugin.

Is there any way, an event, a setting, a callback or something different I can use as a signal that the NPCs in the NPCRegistry are finally loaded?

**Comment by fullwall** [comment]
Yes, CitizensEnableEvent
