### ISSUE TITLE
Citizens failing to enable

### ISSUE THREAD

**Issue by CyanAppleHD** [CitizensDev/Citizens2#1785]
Hi there, I've downloaded Citizens to my Spigot server, and it loaded alright, however, when the server tried to enable the plugin the following message pooped up:
(I haven't touched the config or anything, it's a fresh new download of the plugin)

 17.05 17:33:58 [Server] INFO [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1626) 17.05 17:33:58 [Server] ERROR Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1626) (Is it up to date?) 17.05 17:33:58 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$PooledBlockPosition 17.05 17:33:58 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212] 17.05 17:33:58 [Server] INFO at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_212] 17.05 17:33:58 [Server] INFO at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[Citizens-2.0.24-b1626.jar:?] 17.05 17:33:58 [Server] INFO at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[Citizens-2.0.24-b1626.jar:?] 17.05 17:33:58 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.reload(CraftServer.java:807) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:570) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212] 17.05 17:33:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] 17.05 17:33:58 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$PooledBlockPosition 17.05 17:33:58 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-518206a-c4a67ee] 17.05 17:33:58 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212] 17.05 17:33:58 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] 17.05 17:33:58 [Server] INFO ... 27 more

The output of command `/version` on my server is: http://prntscr.com/npw1og
The output of command `/version citizens` on my server is: http://prntscr.com/npw2en

Is there anything I can do? I tried downloading multiple versions of spigot and Citizens but it doesn't work no matter the combination.

Thanks in advance to anyone who helps.

**Comment by mergu** [comment]
Hi there, thanks for opening an issue.

Fortunately this has already been resolved, you can fix the issue with some simple updates:
Citizens: https://ci.citizensnpcs.co/job/Citizens2
Spigot: https://www.spigotmc.org/wiki/buildtools/
or instead of Spigot, Paper: https://papermc.io/

Updating both of these should solve the issue

**Comment by CyanAppleHD** [comment]
I used multiple Citizens and Spigot, and it didn't work, but I'll give Paper a shot.

Thanks in advance.

**Comment by CyanAppleHD** [comment]
> 
> 
> Hi there, thanks for opening an issue.
> 
> Fortunately this has already been resolved, you can fix the issue with some simple updates:
> Citizens: https://ci.citizensnpcs.co/job/Citizens2
> Spigot: https://www.spigotmc.org/wiki/buildtools/
> or instead of Spigot, Paper: https://papermc.io/
> 
> Updating both of these should solve the issue

It worked, I am so happy. I've spent 3 days trying to fix it.
Thanks a lot :D

**Comment by mergu** [comment]
Great! Feel free to close the issue, glad to help
