### ISSUE TITLE
single NPC are not loaded

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#1786]
Spigot: CraftBukkit version git-Spigot-8043ebc-9bda413 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

Citizens: Citizens-2.0.25-b1692

I've generated a dragon I called Elliot from the spawn with Citizens. Unfortunately it disappears again and again! The other Npc remain. Even if I reload the file it stays gone. So I had to create the new one. I have already done this 3 times as you can see from the file. Why does the dragon disappear although it is stored in the save.yml?

  '121':
    name: Elliot
    uuid: 63ca7a33-e5f6-4a99-ad20-8f7e05cfcd16
    traits:
      lookclose:
        range: '5.0'
        enabled: true
        enableRandomLook: false
        randomLookDelay: 60
        randomPitchRange:
        - -10.0
        - 0.0
        randomYawRange:
        - 0.0
        - 360.0
        realisticlooking: false
      type: ENDER_DRAGON
      location:
        world: world
        x: '44.4934'
        y: '2126.9998'
        z: '320.5765'
        yaw: '-70.80338287353516'
        pitch: '6.960407257080078'
      spawned: true
      owner:
        owner: Blueeyestar
        uuid: a680274e-ab83-4f58-b56f-73f9c4f5994a
    traitnames: type,lookclose,mounttrait,spawned,location,owner
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true
  '122':
    name: ELLIOT
    uuid: 549ea8e0-d25a-4842-a54f-5774f4dd055a
    traits:
      location:
        world: world
        x: '43.2426'
        y: '2123.2766'
        z: '320.1684'
        yaw: '-89.7199935913086'
        pitch: '-7.9265899658203125'
      spawned: true
      lookclose:
        range: '5.0'
        enabled: true
        enableRandomLook: false
        randomLookDelay: 60
        randomPitchRange:
        - -10.0
        - 0.0
        randomYawRange:
        - 0.0
        - 360.0
        realisticlooking: false
      type: ENDER_DRAGON
      owner:
        owner: Blueeyestar
        uuid: a680274e-ab83-4f58-b56f-73f9c4f5994a
    traitnames: type,lookclose,mounttrait,spawned,location,owner
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true

**Comment by mcmonkey4eva** [comment]
Entities disappearing is a known issue with MC 1.14.x
1.14.x is **NOT** stable currently and should NOT be used for a live server.
