### ISSUE TITLE
Citizens Not Working

### ISSUE THREAD

**Issue by Ubalube** [CitizensDev/Citizens2#1787]
I am using a 1.13.2 server and I am trying to put Citizens on my server. Although when I type /npc create blahblah, nothing happens. It just doesn't do anything. I found something in console that says **Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1605) (Is it up to date?)** but I am using 1.13.2 spigot. 

The output of command `/version` on my server is: CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API Version 1.13.2-R0-1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1591)
[Console Log](https://pastebin.com/1gikTdjn)

**Comment by SXRWahrheit** [comment]
Please update both Spigot and Citizens; your Citizens build is almost 100 builds outdated.

https://ci.citizensnpcs.co/job/Citizens2/
https://www.spigotmc.org/wiki/buildtools/
