### ISSUE TITLE
Attackspeed for NPCs

### ISSUE THREAD

**Issue by Sago92** [CitizensDev/Citizens2#1788]
Dear Development Team,

I did some research but couldn't figure out if I have the possibility over the Citizens API to change the attack speed of a NPC.

Is there any implementation I can use that would archive that?

Regards

**Comment by mcmonkey4eva** [comment]
Citizens NPCs do not attack. If you want combat-capable NPCs, use Sentinel: https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md
