### ISSUE TITLE
Citizens /npc create Command Crashes Server

### ISSUE THREAD

**Issue by eglbogle** [CitizensDev/Citizens2#179]
Hello! I am running a Spigot server. When I do the /npc create [name] command, it creates an NPC, which crashes the server every time anyone goes near it. It isn't an error with the name length because I tried making an NPC with a name of 4 characters, and it still crashed the server. I have a detailed crash report here:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/3/15 7:39 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Handle needs to be an instance of: net.minecraft.server.v1_7_R4.DataWatcher
	at com.dsh105.echopet.libs.captainbern.wrapper.AbstractWrapper.setHandle(AbstractWrapper.java:37)
	at com.dsh105.echopet.libs.captainbern.wrapper.WrappedDataWatcher.<init>(WrappedDataWatcher.java:64)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.updateDatawatcher(EntityPacketPet.java:99)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.init(EntityPacketPet.java:120)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.onLive(EntityPacketPet.java:82)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.h(EntityPet.java:462)
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620)
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595)
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460)
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516)
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.dsh105.echopet.libs.captainbern.wrapper.AbstractWrapper.setHandle(AbstractWrapper.java:37)
	at com.dsh105.echopet.libs.captainbern.wrapper.WrappedDataWatcher.<init>(WrappedDataWatcher.java:64)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.updateDatawatcher(EntityPacketPet.java:99)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.init(EntityPacketPet.java:120)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPacketPet.onLive(EntityPacketPet.java:82)
	at com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.EntityPet.h(EntityPet.java:462)
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620)
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595)

-- Entity being ticked --
Details:
	Entity Type: Human-Pet (com.dsh105.echopet.compat.nms.v1_8_Spigot.entity.type.EntityHumanPet)
	Entity ID: 1940195
	Entity Name: entity.Human-Pet.name
	Entity's Exact location: 604.94, 41.35, 1032.02
	Entity's Block location: World: (604,41,1032), Chunk: (at 12,2,8 in 37,64; contains blocks 592,0,1024 to 607,255,1039), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460)
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516)

-- Affected level --
Details:
	Level name: creative
	All players: 1 total; [EntityPlayer['eglbogle'/404, l='creative', x=604.94, y=41.35, z=1032.02](eglbogle at 604.9439287025565,41.34831201497501,1032.0156735003602)]
	Chunk stats: ServerChunkCache: 634 Drop: 0
	Level seed: -923120650499391506
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (462,4,846), Chunk: (at 14,0,14 in 28,52; contains blocks 448,0,832 to 463,255,847), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 3629392 game time, 3716432 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 142407 (now: false), thunder time: 1740 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-431.11.2.el6.x86_64
	Java Version: 1.7.0_55, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 278655184 bytes (265 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
	JVM Flags: 5 total; -Xmx512M -Xms512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) true
   Plugins: { Playtime v1.4.5 com.rogue.playtime.Playtime [1Rogue, unlucky4ever], WorldBorder v1.8.0 com.wimbli.WorldBorder.WorldBorder [Brettflan], bPermissions v2.10.7 de.bananaco.bpermissions.imp.Permissions [codename_B], WorldEdit v5.6.2 com.sk89q.worldedit.bukkit.WorldEditPlugin [], CoreProtect v2.10.0 net.coreprotect.CoreProtect [Intelli], Itemizer v1.4.7 co.technius.itemizer.ItemizerPlugin [Technius], ProtocolLib v3.4.0 com.comphenix.protocol.ProtocolLibrary [Comphenix], Multiverse-Core v2.4-b527 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--], LWC v4.4.0 (b881) (July 11, 2013) com.griefcraft.lwc.LWCPlugin [Hidendra], mcMMO v1.5.00-b3547 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking], trails v3.0 me.kvq.plugin.trails.main [], WorldGuard v5.9 com.sk89q.worldguard.bukkit.WorldGuardPlugin [], Essentials v2.13.1 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], AsyncWorldEdit v1.3 org.primesoft.asyncworldedit.PluginMain [SBPrime], EssentialsSpawn v2.13.1 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], Multiverse-Portals v2.4-b548 com.onarandombox.MultiversePortals.MultiversePortals [Rigby, fernferret], Multiverse-Inventories v2.5-b335 com.onarandombox.multiverseinventories.MultiverseInventories [dumptruckman], EssentialsChat v2.13.1 com.earth2me.essentials.chat.EssentialsChat [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally], EchoPet v2.6.0-b28 com.dsh105.echopet.EchoPetPlugin [DSH105],}
   Warnings: DEFAULT
   Threads: { TIMED_WAITING Thread-14: [java.lang.Thread.sleep(Native Method), net.coreprotect.consumer.Consumer.run(Consumer.java:47), java.lang.Thread.run(Unknown Source)], TIMED_WAITING pool-6-thread-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty IO #2: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.ThreadSleepForever.run(SourceFile:63)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], RUNNABLE Signal Dispatcher: [], WAITING pool-6-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-7: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty IO #0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(Unknown Source), java.io.BufferedInputStream.fill(Unknown Source), java.io.BufferedInputStream.read(Unknown Source), java.io.FilterInputStream.read(Unknown Source), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:1506), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1153), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1117), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1105), net.minecraft.server.v1_7_R4.ThreadCommandReader.run(ThreadCommandReader.java:34)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Thread-9: [java.lang.Thread.sleep(Native Method), com.griefcraft.modules.credits.CreditsModule$CreditsTask.run(CreditsModule.java:110), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Thread-13: [java.lang.Thread.sleep(Native Method), net.coreprotect.thread.CacheCleanUp.run(CacheCleanUp.java:14), java.lang.Thread.run(Unknown Source)], WAITING MV-Inv Profile Write Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:208)], TIMED_WAITING Thread-11: [java.lang.Thread.sleep(Native Method), de.bananaco.bpermissions.imp.loadmanager.MainThread.check(MainThread.java:54), de.bananaco.bpermissions.imp.loadmanager.MainThread.run(MainThread.java:26)], TIMED_WAITING Craft Scheduler Thread - 51: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source), java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source), java.util.concurrent.SynchronousQueue.poll(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-6: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-8: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], WAITING pool-6-thread-10: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Unknown Source), org.bukkit.craftbukkit.v1_7_R4.CraftCrashReport.call(CraftCrashReport.java:28), net.minecraft.server.v1_7_R4.CrashReportSystemDetails.a(SourceFile:74), net.minecraft.server.v1_7_R4.CrashReport.h(CrashReport.java:45), net.minecraft.server.v1_7_R4.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_7_R4.CrashReport.a(CrashReport.java:230), net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1463), net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516), net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706), net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289), net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584), net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490), net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)], WAITING pool-6-thread-9: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], RUNNABLE Netty IO #1: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(Unknown Source), sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source), sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source), sun.nio.ch.SelectorImpl.select(Unknown Source), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Unknown Source)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.FileIOThread.b(SourceFile:44), net.minecraft.server.v1_7_R4.FileIOThread.run(SourceFile:23), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-4: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), net.minecraft.util.com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:73), org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Unknown Source)], WAITING pool-6-thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Unknown Source), java.util.TimerThread.run(Unknown Source)], TIMED_WAITING Thread-8: [java.lang.Thread.sleep(Native Method), com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:181), java.lang.Thread.run(Unknown Source)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.ReferenceQueue.remove(Unknown Source), java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)], WAITING pool-8-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)], WAITING Head Conversion Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(Unknown Source), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source), java.util.concurrent.LinkedBlockingQueue.take(Unknown Source), java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)],}
   Recent tasks from 93232-93262{WorldEdit:com.sk89q.worldedit.bukkit.SessionTimer@93269,}
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 12; [EntityPlayer['eglbogle'/404, l='creative', x=604.94, y=41.35, z=1032.02](eglbogle at 604.9439287025565,41.34831201497501,1032.0156735003602)]
	Is Modded: Definitely; Server brand changed to 'Spigot'
	Type: Dedicated Server (map_server.txt)

**Comment by mcmonkey4eva** [comment]
That looks like echopets is conflicting with Citizens or just nonfunctional entirely. Either way, report to them, not us.
