### ISSUE TITLE
unable to create donkey with chest

### ISSUE THREAD

**Issue by Lexo2011** [CitizensDev/Citizens2#1791]
The output of command `/version` on my server is: git-Spigot-1a3504a-dfa7563 (MC 1.13.2)  (Implementing API version 1.13.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1692)

You cannot create a NPC with the "Chested Donkey" Model because the command /npc horse cannot be run an a NPC with the type "donkey"

**Comment by fullwall** [comment]
Fixed
