### ISSUE TITLE
Passing offline player data through main thread causes exception thrown by luckperms

### ISSUE THREAD

**Issue by bwestcott-1** [CitizensDev/Citizens2#1792]
When trying to update npc skins, exception is thrown. Npc skin will still show, but will disappear after I log out. 

Console log: https://pastebin.com/CngrR97e
Config: https://pastebin.com/Y3qDJ0WU

The output of command `/version` on my server is: 1.13.2
The output of command `/version citizens` on my server is: LATEST

**Comment by mcmonkey4eva** [comment]
`The output of command /version citizens on my server is: LATEST`
Nope. That's not how that works. Actually do the commands, and actually copy the output.

... And the solution to your issue is to update all relevant plugins (Citizens, LuckPerms, and WorldGuard)

**Comment by bwestcott-1** [comment]
All the plugins are updated to their latest versions. I assumed you would understand what LATEST means considering I’m using the LATEST version of citizens

**Comment by mcmonkey4eva** [comment]
No, they aren't. Update.
"LATEST" means "I don't know what version I'm on and I don't care to check"

**Comment by bwestcott-1** [comment]
No it means “I downloaded the LATEST build from Jenkins, yesterday” market as “last successful build”.

**Comment by bwestcott-1** [comment]
Yes. They. Are. I made sure of that yesterday. I’m not clueless

**Comment by mergu** [comment]
We request people post exact output because we get a ton of issues saying "latest" when they're actually months or years behind. It's just standard policy, nothing to get snappy about. We recommend everyone, especially people who aren't clueless, to follow the issue template.

**Comment by bwestcott-1** [comment]
Sorry, responded poorly to passive aggressiveness. Fixed anyways, custom worldguard hook needed recoding
