### ISSUE TITLE
`/npc sit` (enabled or disabled) creates armor stands on restart

### ISSUE THREAD

**Issue by SXRWahrheit** [CitizensDev/Citizens2#1795]
![2019-05-27_18 46 45](https://user-images.githubusercontent.com/774463/58442323-d1dc0400-80af-11e9-9f9d-f49e5e58c02d.png)

(in the screenshot, I've already killed the armor stand)

**Comment by mcmonkey4eva** [comment]
Unable to replicate this in local testing on latest builds, no armor stands appear through a restart.
Please provide replication steps for a clean server.
