### ISSUE TITLE
Causing the server to crash on 1.14.2

### ISSUE THREAD

**Issue by 0xC1A551C** [CitizensDev/Citizens2#1798]
My server is crashing when I load a area where npc's have been saved.

Crash report: https://pastebin.com/djYESPEJ

My config is default as I removed everything. I created 3 NPC's named test, npc, and type villager named test2. I restarted my server and logged in - seemed ok. I restarted my server again and when I teleported to where the NPC's were the server crashed.

I should note I am using CMI as well, and I can also replicate the crash when I teleport using CMI.

> 
loading chunks in a chunkloadevent is bad bad idea in 1.14

The output of command `/version` on my server is: **Citizens-2.0.25-b1699** 
The output of command `/version citizens` on my server is: **Paper version git-Paper-53 (MC: 1.14.2)**

**Comment by mcmonkey4eva** [comment]
That's not a crash, that's a server freeze.
Villager entities lagging the server is a known issue with Spigot on 1.14.x, not specific to Citizens
