### ISSUE TITLE
Traits?

### ISSUE THREAD

**Issue by QueenKisaki** [CitizensDev/Citizens2#1802]
The output of command `/version` on my server is: **30.05 12:10:05 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-01d0f04-455023c (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
30.05 12:10:05 [Server] Server thread/INFO Checking version, please wait...
30.05 12:10:06 [Server] Thread-16/INFO You are running the latest version**

The output of command `/version citizens` on my server is: **30.05 12:10:47 [Server] Server thread/INFO Citizens version 2.0.25-SNAPSHOT (build 1699)
30.05 12:10:47 [Server] Server thread/INFO Website: http://www.citizensnpcs.co
30.05 12:10:47 [Server] Server thread/INFO Authors: aPunch and fullwall**

Citizens shopkeeper trait does not work, trait not found. I've tried every way (various spellings etc) to enter the trait for shopkeepers plugin and none of them are found. It used to work so not sure why.

**Comment by fullwall** [comment]
Ask shopkeeper's devs for help with this issue.
