### ISSUE TITLE
Inventory Issue When Using API

### ISSUE THREAD

**Issue by rcj0003** [CitizensDev/Citizens2#1804]
**Server Version Output**
[00:39:42 INFO]: This server is running CraftBukkit version git-TacoSpigot-"95870a93" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[00:39:42 INFO]: You are running the latest version
version Citizens

**Citizen Version Output**
[00:39:47 INFO]: Citizens version 2.0.25-SNAPSHOT (build 1700)
[00:39:47 INFO]: Website: http://www.citizensnpcs.co
[00:39:47 INFO]: Authors: aPunch and fullwall

**Issue Description**
When using the API, getting the Inventory trait and setting an item for a slot doesn't work.

I'm unsure what the issue is, as the item setting works fine. If you iterate through the inventory and print the item for the slot via the system output, set an item, and then iterate and print all the items again, it shows that it successfully set the item in the inventory.

However, this change is not reflected with the actual NPC. If you select the NPC and then do /npc inventory, the inventory is left untouched. For a starting inventory that is empty, after you set the item via the API, it is left empty when you check via /npc inventory (or by simply looking at the NPC).

I have tried everything possible, and the only way I was able to set inventory items was via the Equipment trait (which isn't really that helpful for what I hope to accomplish with the API).

(I should also note that I am using Sentinel, although I imagine it isn't causing the bug, as it just reads inventory from what I understand.)

**Comment by mcmonkey4eva** [comment]
We very strongly recommend you immediately update to a supportable server version, namely 1.12.2, 1.13.2, or possibly 1.14.x
Refer to this wiki page for information about how to update without losing the functionality you need: https://wiki.citizensnpcs.co/Minecraft_1.8

----

Beyond that, possibly improper API code usage. Can't know without seeing the actual code.
