### ISSUE TITLE
Unable to remove npcs

### ISSUE THREAD

**Issue by Noodleburg** [CitizensDev/Citizens2#1805]
I have 2 citizens that i decided to remove. have tried to but cant select them.  Had someone else dealing with plugins that made them but they left. I tried throwing them out of the world but the just keep re spawning. Have searched all my files and can not find them named. Was another citizen near them that i accidentally selected and deleted and its gone forever but they still exist. searched through the ingame list but fond no indication of there names to remove them. any help is appreciated Noodleburg

![2019-05-31_18 37 47](https://user-images.githubusercontent.com/51245588/58739062-6018f880-83d6-11e9-81d3-5a892017e874.png)

The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by mcmonkey4eva** [comment]
First: Update Citizens: http://ci.citizensnpcs.co/job/Citizens2/ and Spigot: https://www.spigotmc.org/wiki/buildtools/
Second: what are the NPCs you're trying to remove? Can you post a screenshot of them?
Have you tried selecting with both `/npc sel` and by right clicking them with a stick? Do they appear in `/npc list -a`?
