### ISSUE TITLE
NPC can't spawn/load with newest Spigot 1.14.2 (baafee9-043d31d)

### ISSUE THREAD

**Issue by mindw0rm** [CitizensDev/Citizens2#1806]
Creating a new NPC with the (currently) newest spigot version gives the following error:
`[Citizens] Task #4 for Citizens v2.0.25-SNAPSHOT (build 1701) generated an exception
java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_14_R1.Entity.bukkitEntity from class net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC
	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.getBukkitEntity(EntityHumanNPC.java:224) ~[?:?]`

This does _not_ happen with older spigot versions, for example git-Spigot-01d0f04-b7fea42 (3 versions behind - the newest other jar I still have. It also did not happen with the spigot version of three days ago; unfortunately I have neither the jar nor any logs, so I can't tell which version that was). 
The NPC I created with baafee9-043d31d is _not_ present in baafee9-043d31d, but is present if I load the same world with 01d0f04-b7fea42. 
I created another NPC with 01d0f04-b7fea42 and restarted the server with baafee9-043d31d: now the above error happens during startup; no NPCs are present - not even invisible (an issue with invisible NPCs is the reason why I do such reduced testing), `/npc select` selected nothing. 
However, `/npc list -a` lists the first one. 

Citizens is the only Plugin. The config.yml is the default config. 

The output of command `/version` on my server is: **git-Spigot-baafee9-043d31d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1701)**

Startup logs (both after both NPCs were already created) are attached for both spigot versions (also contain the output of `npc list -a`):
[startup-baafee9-043d31d.log](https://github.com/CitizensDev/Citizens2/files/3244793/startup-baafee9-043d31d.log)
[startup-01d0f04-b7fea42.log](https://github.com/CitizensDev/Citizens2/files/3244794/startup-01d0f04-b7fea42.log) (immediately after the run with baafee9-043d31d)

Log file of the creation of the world and the first NPC: 
[2019-06-02-1.log](https://github.com/CitizensDev/Citizens2/files/3244799/2019-06-02-1.log)

**Comment by mcmonkey4eva** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/fa71719350d15fd5d5091c4fe45ff2e86a95371c#nms-patches/Entity.patch :(
We'll have to patch for that

**Comment by Blueeyestar** [comment]
https://pastebin.com/rnT9kLdz
