### ISSUE TITLE
Llamas' Equipment, Inventory and Carpets

### ISSUE THREAD

**Issue by DKKitty** [CitizensDev/Citizens2#1807]
1) console has an absolute fit when trying to do /npc inventory on any llama npc (logs provided) /npc inventory appears to function without error on all other npc types

2) cannot equip carpet or chests to any colour or age llama npc using the /npc equip editor and right clicking, console shows no errors but nothing happens

console error for /npc inv when any llama npc is selected:
https://pastebin.com/7deERBMc

/version & /version citizens:
![image](https://user-images.githubusercontent.com/45343169/58767267-a8741a00-8580-11e9-9bf4-1494c932a0a8.png)

Citizens config: (couldnt attatch hope pastebin is ok)
https://pastebin.com/bf1zvH8W

ADDITIONAL INFO:

server was 17 versions behind on paper today when this error first occurred. i only updated paper to the latest build to eliminate the version as having cause the issue

**Comment by DKKitty** [comment]
ADDITIONAL INFO:

server was 17 versions behind on paper today when this error first occurred. i only updated paper to the latest build to eliminate the version as having cause the issue

**Comment by mcmonkey4eva** [comment]
Issue invalid; please follow the issue template.
