### ISSUE TITLE
Chunk load problem. paper-1.14.2 #65

### ISSUE THREAD

**Issue by successed** [CitizensDev/Citizens2#1809]
citizens version 

Citizens-2.0.25-b1702

server version latest paperspigot 1.14.2 #65 

NPCs do not appear when loading chunk.

when they execute this command, they come out.
"/citizens reload"

**Comment by mcmonkey4eva** [comment]
That issue is a known problem with Minecraft 1.14.x itself, refer to #1790

**Comment by successed** [comment]
> That issue is a known problem with Minecraft 1.14.x itself, refer to #1790

When will it be corrected?

**Comment by mcmonkey4eva** [comment]
whenever mojang releases a fix (1.14.3 is scheduled, which *might* fix it)

**Comment by successed** [comment]
When will 1.14.3 be released?

**Comment by mcmonkey4eva** [comment]
Whenever mojang releases it. I don't know, I don't work for mojang
