### ISSUE TITLE
Server stops after placing a human NPC?

### ISSUE THREAD

**Issue by jusjus112** [CitizensDev/Citizens2#181]
hey,

i have a problem with this plugin, when i place a npc from  a mob type.
It doesnt stop my server, but only when i place a human with a skin it stops my server and goes off.
I dont know how to fix this, and i have the version for minecraft 1.9
I hope you guys can help me.

**Comment by fullwall** [comment]
1.9 is not a valid MC version. Do you have the server log?

**Comment by jusjus112** [comment]
I have a server log, but it dont give me any errors!
It just say, "Stopping server" and restart him, then he dont give error except another plugin.
And why it isnt a valid version? I have
 2.0.13 (alpha 1 for MC1.7.9)

**Comment by fullwall** [comment]
Can you paste the full thing on http://pastebin.com?

**Comment by jusjus112** [comment]
here you go:
http://pastebin.com/1q2kW3DF

**Comment by fullwall** [comment]
The problem is with the plugin "TheNetworkSurvival" - it is not updated for MC 1.7.9.

**Comment by jusjus112** [comment]
Wtf, why. Thats not confilcted with the citizens right? Its a custom made pl

**Comment by fullwall** [comment]
No, it's conflicted with the NMS version of the server you're running. The package version for NMS has changed from v1_7_R2 to v1_7_R4.

**Comment by jusjus112** [comment]
I have done that, and edit my build path from craftbukkit 1.7.2 to spigot 1.7.10 and i have the same problem!

**Comment by mcmonkey4eva** [comment]
Once you edit your build path, you have to update your NMS code as well.

**Comment by jusjus112** [comment]
Of course i did that! I updated the code, and now i dont get error from my plugin!

**Comment by mcmonkey4eva** [comment]
.... So, everything is working now, or...?

**Comment by Morphan1** [comment]
1) if you don't know how to read errors caused by your own plugin, please go read up on that. 
2) your server seems to be in offline mode. I don't think we should be offering support for that. 

I hope you get it working :smiley:

**Comment by jusjus112** [comment]
And no, its not working i have the same problem! But, i have installed a disguise plugin, and when i disguise as a player, all players disconnected and when they join they crash. So its a thing with the skins or something!

And Morphan1 i know how to read my own error of course, and yes, my server is in offline mode. BUT i have a bungeecord proxy thats not in offiline mode, so my subs-servers are in offline and my bungee isnt!
