### ISSUE TITLE
Issue when updating paper 

### ISSUE THREAD

**Issue by slvlr** [CitizensDev/Citizens2#1810]
error on startup 

git-paper-59 (1.14.2) (works fine) when updating to paper 65 I get the following error:
https://pastebin.com/XfHaQRkp
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1699)

**Comment by mcmonkey4eva** [comment]
Update; that was fixed.
https://ci.citizensnpcs.co/job/Citizens2/
