### ISSUE TITLE
1.14.2 - Horse type NPCs have odd behaviour when being controlled

### ISSUE THREAD

**Issue by Ph4i1ur3** [CitizensDev/Citizens2#1811]
Please include:
- A detailed description of your issue or feature request
-->

The output of command `/version` on my server is: CraftBukkit version git-Spigot-baafee9-043d31d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1702)

- Test was run on a fresh install of Spigot's latest build for 1.14.2 using only the described citizens plugin version listed above
- Log has nothing visibly relevant in it.
- Config is 100% default, generated from the listed build above.
- it does seem to create some lag, but it's hard to tell with 1.14.2 generally having lag issues already (as you can notice with the framerates in the video)

Video of the issue: https://www.youtube.com/watch?v=W0ScLsywVOs&feature=youtu.be

- Mobs tested: Player NPCs, Zombies, Pig, Spider, Enderman, Horse, Skeleton_horse, Ender_Dragon
- Of the listed mobs, only the horses (horse, and skeleton_horse) displayed the issue.

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/7cb7b365072271cc4a701cb0bd02e983222222ed in build 1715+
