### ISSUE TITLE
Feature Request: Option to give a NPC a scoreboard "tag"

### ISSUE THREAD

**Issue by Stualyttle** [CitizensDev/Citizens2#1812]
Hello!

I use some commandblocks to apply effects and commands to npc's, This works!
The only problem I have is every time i restart the plugin, save it or restart the server, those scoreboard tags are gone..

Can there be a option to give npc's a scoreboard tag? so this does not happen?

Thank you!
~Stualyttle

`(command I use: "/scoreboard players tag @e[r=1,name=!Stualyttle] add CustomTag" and "/execute @e[tag=CustomTag] ~ ~ ~ custom command"`

**Comment by fullwall** [comment]
Done

**Comment by mcmonkey4eva** [comment]
Via the `/npc scoreboard` command, available in build 1725+
