### ISSUE TITLE
After creating the npc the server switches off

### ISSUE THREAD

**Issue by 666rucio666** [CitizensDev/Citizens2#1815]
**Hello boss! :D**       |   right away I say that I was helped by translator google  |

- At the moment when I type '/ npc create test' the server closes, the plugins are shut down and I have to restart the server again

- error log ---->  https://pastebin.com/4iLwGi4X

- /ver server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)  
  
- 2.0.24 (MC 1.10-1.13.2) 

- not applicable, I have a good equipment :)

I am asking for a positive consideration of my problem, and I wish you a good day :)

**Comment by 666rucio666** [comment]
and my configuration is default :)

**Comment by Ph4i1ur3** [comment]
https://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
- Did not follow issue template requirements.
- Issue is likely a version error.
Update Citizens to latest: https://ci.citizensnpcs.co/job/Citizens2/
and update Spigot to latest: https://www.spigotmc.org/wiki/buildtools/
