### ISSUE TITLE
Error when opening horse npc inventory

### ISSUE THREAD

**Issue by ChimpGamer** [CitizensDev/Citizens2#1816]
If I select a horse npc and execute /npc inventory it says Please report this error: [See console] java.lang.ArrayIndexOutOfBoudsException: 2

https://pastebin.com/sk1dh8Md <-- Full error

This server is running Paper version git-Paper-629 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-628 (MC: 1.13.2)
Checking version, please wait...
You are running the latest version

Citizens version 2.0.25-SNAPSHOT (build 1702)

**Comment by fullwall** [comment]
Try latest build
