### ISSUE TITLE
Can't see NPCs

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#1817]
The output of command `/version` on my server is: **Spigot 1.14.2 baafee9-7cc7719**
The output of command `/version citizens` on my server is: **2.0.25 build 1702**

Hello,
On my server there are many NPCs (all of them are players entities) but I can't see them. Even if I move them (/npc move), if I leave/join again... No way to see them. However, if I try to create a NPC, it will work and I will see it.

Here is the Citizens config.yml: https://pastebin.com/2VJQ1uiM

**Comment by mcmonkey4eva** [comment]
Please add the unique information you have onto the primary issue: #1790
