### ISSUE TITLE
Missing preferred location bundle (Paper server)

### ISSUE THREAD

**Issue by GhostFace54** [CitizensDev/Citizens2#1819]
My problem is that when I start my server, Citizens won't start because `[ERROR] [Citizens] Missing preferred location bundle.` I quite don't know what's the problem, I have put the plugin into my plugins folder though!
It's a first start of the plugin too, haven't touched config (Console errors: https://pastebin.com/JrWq8Gz0)
The output of command `/version` on my server is: Paper version git-Paper-493 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) 
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1703)

**Comment by mcmonkey4eva** [comment]
You can just ignore that message.
It just means there's not an available language translation for your server's preferences.

**Comment by GhostFace54** [comment]
Though I get an internal error

**Comment by GhostFace54** [comment]
Could you check the pastebin?

**Comment by mcmonkey4eva** [comment]
If you get an actual error (other than that message), post a separate issue for that

**Comment by mcmonkey4eva** [comment]
Oh that's just... update Paper.

**Comment by GhostFace54** [comment]
Oh well..

**Comment by GhostFace54** [comment]
Yep didn't work, will open a new thread
