### ISSUE TITLE
Npc' counting as players

### ISSUE THREAD

**Issue by Hazzana43** [CitizensDev/Citizens2#182]
On plugins such as tab or ezrankslite on the scoreboard they count all the player npcs causing the online players to lie and tell them all the players plus the npc's. Will this ever be fixed as it annoys a lot of people because of it being a huge glitch like logging on and you see most of them on tab for a good minute can this be fixed

PS this has nothing to do with all the other plugins used it its by citizen as I've tryed removing it and it worked fine

**Comment by Morphan1** [comment]
Um... Well first of all, I just wanna clarify it CAN still be the other plugin's fault. Removing Citizens gets rid of NPCs,  so yeah your NPCs won't show up.. If they... You know, don't exist.

**Comment by mcmonkey4eva** [comment]
@Hazzana43 Update Citizens, that was a bug in previous builds. The latest dev build should correct this.

**Comment by KyleLazo** [comment]
I'm using the lastest dev build & lastest Spigot build.
But it's still counting npcs in the player list.
Also, I've tried "/npc name" to toggle the name but it didn't work.

**Comment by fullwall** [comment]
Duplicate
