### ISSUE TITLE
Citizens disabled, using the last stable build

### ISSUE THREAD

**Issue by GhostFace54** [CitizensDev/Citizens2#1820]
My problem is that when I start my server, Citizens won't start because of some error that I pasted into pastebin (link below). I don't know what's the problem and I can't really fix it by myself!
It's a first start of the plugin too, haven't touched config (Console errors: https://pastebin.com/JrWq8Gz0)
The output of command `/version` on my server is: Paper version git-Paper-493 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) 
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1703)

**Comment by mcmonkey4eva** [comment]
Update Paper, you're about 150 builds behind
