### ISSUE TITLE
Citizens wont load and console error

### ISSUE THREAD

**Issue by Zoneman1972** [CitizensDev/Citizens2#1821]
Citizens wont load on startup and I'm getting the following error in console http://prntscr.com/o0pog2

The output of command `/version` on my server is: **(This server is running Paper version git-Paper-70 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.25-SNAPSHOT (build 1699)

**Comment by mcmonkey4eva** [comment]
I edited your post to fix the placement issue (you put your issue details in a place you can't normally see).
Update Citizens to latest https://ci.citizensnpcs.co/job/Citizens2/
