### ISSUE TITLE
1.14.x NPCs Disappearing

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#1822]
This is a redirect from the mess that was #1790

There's a variety of issues with Minecraft 1.14.x itself.
Please be aware that **Minecraft 1.14.x** is **NOT STABLE** and should **NOT** be used on a live server! This isn't specific to Citizens, this is a general situation. ~~1.14.3 is expected to come soon to fix many of the worst issues.~~

There seems to be a current problem with Citizens, that in many cases NPCs are not properly spawning themselves back in. This is likely related to chunk handling in 1.14.x.
Initially this was thought to be specific to villagers, however based on further reports it appears to apply to all NPCs.

The user post here: https://github.com/CitizensDev/Citizens2/issues/1790#issuecomment-495060329 indicates that the issue may be resolvable by forcibly loading chunks prior to NPCs spawning in.

**EDIT:** Also relevant information: several people are reporting that chunks around player-type NPCs remain loaded, which may be relevant

**Comment by mcmonkey4eva** [comment]
**possibly** workaround-patched in https://github.com/CitizensDev/Citizens2/commit/d0b358a27cb5e3a3395405b3a86bbeeabf198280 in build dev 1704

**Comment by Lix3nn53** [comment]
Thanks for the update! Looks like my "player" type NPCs are fixed but "villager" types are still doesn't spawn.

**Comment by LizzyTheOne** [comment]
My NPC's are still not spawning, and I updated to 1704. My spigot version is 1.14.x. The issue is, anytime I try to spawn an NPC, it states in chat it was successful, but no npc spawns.

**Comment by mcmonkey4eva** [comment]
That's a separate issue from this one then @LizzyTheOne

**Comment by AustinGarrettRichards** [comment]
Still a problem in build dev 1704. My non-player NPCs are vanishing when the chunk gets unloaded.

**Comment by Lix3nn53** [comment]
Tested with build dev 1706 and spigot 1.14.3, both Player and Villager NPCs are vanishing :(

**Comment by Kalevr1** [comment]
> Tested with build dev 1706 and spigot 1.14.3, both Player and Villager NPCs are vanishing :(

Sounds like the issue I had. Check your worldspawn and see if they are there.

**Comment by Lix3nn53** [comment]
> > Tested with build dev 1706 and spigot 1.14.3, both Player and Villager NPCs are vanishing :(
> 
> Sounds like the issue I had. Check your worldspawn and see if they are there. For me it looked like they were vanishing but they were actually warping to worldspawn.

They are not in world spawn but my NPCs around world spawn works fine. (Player type but other Player types doesnt work)

**Comment by AustinGarrettRichards** [comment]
The ones around your world spawn work because you probably have the chunks set to always loaded.

**Comment by YourCoalAlt** [comment]
This is still a problem with the latest build (1718).

**Comment by Lix3nn53** [comment]
Citizens-2.0.25-b1719 seems to fix my player npcs but villager types still doesnt spawn

**Comment by YourCoal** [comment]
After some testing, I stopped and restarted my server over 100 times, and the villager NPCs would spawn in only 70%ish of the time (b1719)

**Comment by Lix3nn53** [comment]
Any news about this issue? Can we except a fix since minecraft released final version for 1.14.x?

Still, human npcs are working fine while villagers doesnt spawn btw.

**Comment by SXRWahrheit** [comment]
My understanding is that the Citizens folks intend to keep trying to work on this issue, but Mojang pushed performance improvements etc. to 1.15. This seems entirely backwards to me, but you may have to wait until then as a result.

**Comment by fullwall** [comment]
At the moment I haven't been able to track down the source of the villager issue. It seems to be client-related which makes it harder.

**Comment by orange451** [comment]
Human NPCs are still disappearing for certain players. Relogging fixes it.

**Comment by Kalevr1** [comment]
In my case, NPCs disappear but I can still hear their footsteps and Sentinels still fire arrows even if I can't see them. I can frequently trigger this by selecting the NPC and doing "/npc tphere." Some NPCs seem immune in that they never disappear, some seldom disappear, and some always disappear with tphere. And yes, relogging often fixes it for all but one sentinel. 

I can definitely see how a bug that inconsistent would be a bear to track down but if there's any way I can help i.e., tests I could run or variable values that would be helpful, let me know.

**Comment by SkytAsul** [comment]
The problem is still there on the build 1738. I also noticed that it seems the entity isn't even created by the plugin for some NPCs: I've created a plugin who displays particles above the NPCs _only if the NPC has an attached NPC_ and... there is no particles until I do _/npc move_ to spawn the NPC.

**Comment by YourCoalAlt** [comment]
As of build 1737, my villager NPCs began despawning when chunks unload it looks like, not sure if this happened in previous versions and I was oblivious or if this a new problem.

**Comment by LegitSpeedmc** [comment]
uhh where is the download for 1.14 I did the latest build and it has an internal error

**Comment by Ph4i1ur3** [comment]
Only 1.12.2, 1.13.2, and 1.14.4 are supported

**Comment by LegitSpeedmc** [comment]
yeah I know but on bukkit it only show 10-1.13.2 build and I tried it on 1.14.4 server and it didn't work

**Comment by Ph4i1ur3** [comment]
This issue isnt a support thread. Consider joining the Discord.

**Comment by LegitSpeedmc** [comment]
thx for the help

**Comment by 0xC1A551C** [comment]
This is still an issue for me on the latest dev build with Paper 1.14.4 even after enabling the keep chunks loaded option.

**Comment by 0xC1A551C** [comment]
Fixed it by clearing citizens saves and paper.yml

**Comment by YourCoalAlt** [comment]
The original report was created under the influence that the issue was "likely related to chunk handling," but after playing around and having chunks force loaded, not force loaded, and not loading at all, it appears the problem most likely has nothing to do with chunks.

After conducting some searching, I am coming to the finization this is not a Citizens issue, but a Minecraft issue. Source: https://bugs.mojang.com/browse/MC-153904

**Comment by fullwall** [comment]
Please try the latest build.

**Comment by YourCoalAlt** [comment]
Using build 1762, I have restarted my server dozen times or so and the villagers have spawned 100% of the times. I won't call my testing conclusive yet, but it looks successful.

**Comment by YourCoalAlt** [comment]
Me and my friend have been testing a plugin I am making for the past few hours and use Citizens as a depend, not once have the NPCs failed to spawn. I think it's safe to call this successful.

**Comment by R4zzerYT** [comment]
1.15.X Trader Llama have the same problem.

**Comment by mcmonkey4eva** [comment]
@R4zzerYT that's definitely a completely separate issue. Post a separate issue.

**Comment by ilikestohack** [comment]
im having this issue on my server 1.15.2 and its the same 3

**Comment by mcmonkey4eva** [comment]
This is a resolved issue related to 1.14.x changes.

If you are having issues that seem similar, but are on 1.15, it is not the same issue. Please open a new issue if you have an issue.
