### ISSUE TITLE
Builder trait internal error not working

### ISSUE THREAD

**Issue by Someone865** [CitizensDev/Citizens2#1823]
the /version of my server is 1.12.2
the citizens version i am using is 2.0.24-snapshot (build 1605)

my issue is for the builder trait, when i try to use /builder build this is what i get in my console:
https://pastebin.com/j5NMstD7
in the chat it says an internal error occurred... yknow that stuff..... anyways ive tried many commands and many things, im trying to let it build the house schematic which is already in the builder folder and it  loads yea, but doing /builder build doesnt work

**Comment by mcmonkey4eva** [comment]
Builder is separate from Citizens.
A 1.12.x version is available here: https://ci.citizensnpcs.co/job/Builder/
Issues go in this repository here: https://github.com/mcmonkey4eva/Builder
Though be aware it's not likely to be updated anymore.
You might also look at this separate new version of builder on Spigot: https://www.spigotmc.org/resources/builder-reloaded.55326/
