### ISSUE TITLE
Crash on entering chunk with NPC

### ISSUE THREAD

**Issue by supertakeru** [CitizensDev/Citizens2#1824]
On entering chunk with NPC, server crashes and gives this error:
https://pastebin.com/r39rq8NY
This is not easily replicable, as sometimes I can come back with no problem, but this problem did occur!

The output of command `/version` on my server is: 1.14.2 Paper build 83
The output of command `/version citizens` on my server is: Citizens 2.0.25

**Comment by mcmonkey4eva** [comment]
The log that says `THIS IS NOT A BUG OR A CRASH`
You're posting that as a crash report?
No that is not a crash report. Your server froze... 1.14.x minecraft is unstable.

**Comment by MamiyaOtaru** [comment]
and it only does that (freezes) with citizens2.  Like immediately on encountering a Citizens NPC.  Pretty handy it locks things up and throws a "this is not a bug" error :)  I mean if 1.14 isn't supported, OK

**Comment by fullwall** [comment]
Your log tells us that this isn’t a citizens issue, it is a problem with chunk loading on your server after spawning a player (all in minecraft code).
