### ISSUE TITLE
When tablist is enabled for NPC's in config their names don't appear inside, just their head skin

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1826]
When tablist is enabled for NPC's in config their names don't appear inside it, just their head skin

The output of command `/version` on my server is: **Paper-631 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1670)**

Original post - https://www.spigotmc.org/threads/citizens-paid.99505/page-71#post-3437547

**Comment by mcmonkey4eva** [comment]
Please do not enable the tablist for NPCs. If NPCs are in the tablist, and look the same as real players, that violates Mojang's rules for servers (having fake players).

**Comment by axemwa** [comment]
Wait, that's a thing? I didn't realize fake players weren't allowed since there a plugins out there that specifically make fake players, if it's not allowed then why were such plugins approved for release on spigot.org and why is this even an option in the config. Just curious that's all.
An example of a plugin that makes fake players that look like real players is [BotMaker](https://www.spigotmc.org/resources/botmaker.64909/)

**Comment by mcmonkey4eva** [comment]
Minecraft also bans selling mods for monetary gain. Spigot has a premium resources page.
The original authors of the Bukkit project claim that Spigot's continued distribution of their work is illegal.
In short: Spigot really just doesn't care about the rules.

Faking players online is against Mojang's policy... for reasons I'm sure you can very easily guess honestly (tricking players to join your server through false claims that look real to normal players).

The option is there for the purpose of debugging issues with the tablist handling logic.

**Comment by axemwa** [comment]
Wow I gotta start reading their rules I had no idea, interesting.
Ah k my bad I thought it was intended for players
