### ISSUE TITLE
"/npc playerlist" command appears to do nothing, whether citizens tablist is enabled or not

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1827]
"/npc playerlist" command doesn't seem to work for adding or removing an NPC, whether tablist is enabled in the config or not it seems to have no function atm. They don't show in "/online" list either so I'm not sure whether this feature isn't working or if it's intended for something else, I'm stumped?

The output of command `/version` on my server is: **Paper-631 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1670)**

Original post - https://www.spigotmc.org/threads/citizens-paid.99505/page-71#post-3437547

**Comment by mcmonkey4eva** [comment]
That feature is intended for something entirely unrelated.
The "playerlist" is the internal per-world list of players within Spigot.
