### ISSUE TITLE
When tablist is disabled for citizens, any created NPCs seem to make the tablist flicker on occasion temporarily showing the NPC's

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1828]
When tablist is disabled for citizens the NPCs seem to make the tablist flicker on occasion temporarily showing the NPC's is this fixable?

The output of command `/version` on my server is: **Paper-631 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1670)**

Original post - https://www.spigotmc.org/threads/citizens-paid.99505/page-71#post-3437547

**Comment by mcmonkey4eva** [comment]
That's a known issue caused by Mojang's strange strict requirements. We cannot fix it.

**Comment by axemwa** [comment]
Ah I see dang, thanx for the quick reply
