### ISSUE TITLE
Not enabling plugin

### ISSUE THREAD

**Issue by Delmink** [CitizensDev/Citizens2#1829]
So i was looking through the console watching it try to enable and i get this, https://pastebin.com/MfCMvgfU
The output of command `/version` on my server is: **Spigot 1.13.2**
The output of command `/version citizens` on my server is: **(2.0.25-SNAPSHOT (build 1704)**

**Comment by mcmonkey4eva** [comment]
Update your Spigot server, you're running an outdated copy of Spigot 1.13.2
https://www.spigotmc.org/wiki/buildtools/

**Comment by Delmink** [comment]
interesting. Its hosted on RAMshard.

**Comment by mcmonkey4eva** [comment]
Hopefully they allow you to use your own server jar - you should almost never trust a host-provided jar to be good.
