### ISSUE TITLE
[1.14.2] IllegalStateException at server start

### ISSUE THREAD

**Issue by crysis992** [CitizensDev/Citizens2#1830]
After the Server started, this error is thrown: https://pastebin.com/mU9APLTf
But NPCs are working and are being still there.

In case you need the full startup logfile (latest.log)
https://pastebin.com/q2jQRCsy

The output of command `/version` on my server is: **This server is running Paper version git-Paper-94 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1704)**

**Comment by mcmonkey4eva** [comment]
```
 [13:23:31] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper 
```
This is a bug caused by Paper.
