### ISSUE TITLE
Nameplates not disappearing for some NPCs

### ISSUE THREAD

**Issue by ichbinashh** [CitizensDev/Citizens2#1831]
I've recently been trying to create a donator's hall of fame, but noticed that in some instances I can't fit the player's title and name, so I figured I'd remove the name plates and use signs.

This worked perfectly for the first few, but then I created one and realised that /npc name wasn't actually doing anything. It informs me that the nameplate visibility has been toggled, but it definitely hasn't.

Here's a screenshot to show that it is working for some - https://gyazo.com/66d035a355f376c437a2ba6c084849da

And for reference, if I select the one on the left it let's me freely toggle the name plate, appearing and disappearing every single time.

The output of command `/version` on my server is: **Paper(94) 1.14.2-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **Citizens v2.0.25-SNAPSHOT (build 1704)**

**Comment by JohnS19** [comment]
+1 
Same Citizens build and paper 105

**Comment by mcmonkey4eva** [comment]
- Your server and Citizens builds are out of date, update to latest builds and 1.14.3
- Do you have any scoreboard plugins on your server?
- Is `BatCity` the name of a player on your server (sometimes things get weird if an NPC's name matches a real player's name)

**Comment by ichbinashh** [comment]
I believe I now have the latest version for 1.14.3 with the exact same
issue (I can double check later).

Nothing visibly shows the scoreboard so I would assume not, but I don't
know for sure it there are any bts checks?

BatCity is the player's /nick and not his actual name

Thank you

**Comment by ichbinashh** [comment]
Just an update, I updated to **1709** and **Paper 120** and the issue still persists. It seems to be very hit and miss. I took what you said about player names into account, so I tried the process again in this order:

/npc create <a name that was 100% not registered to an account>
/npc name - Sometimes toggled, sometimes didn't. Only solution I found was to keep recreating with a different name until eventually it worked. One of those that did work also reappeared upon restarting.

When successful, I used /npc skin <playername> to adjust it to the desired skin, and for the most part was effective (other than that one mentioned above).

**Comment by orblazer** [comment]
I have probably found the reason of bug. For hide the nameplate we use scoreboard but if the server create an new scoreboard this broken the visibility.

_**NOTE** : This is same problem for collision bug_

For fix that we need send  an custom team with packet to player.
You can find my code here : https://pastebin.com/2aSznqn2

Thanks.

**Comment by martijnpu** [comment]
Same problem here, /npc name does nothing.
Version paper(81) 1.15.2
Citizen 2.0.26 (build 1815)

**Comment by mcmonkey4eva** [comment]
@orblazer (missed your comment at the time you posted it apparently) that is unlikely to be the same bug, as what you're encountering+fixing is a known issue wherein scoreboard plugins explicitly break all usage of `/npc name` and a few other things. It's so common we have a wiki page for it: https://wiki.citizensnpcs.co/Plugin_Conflict
I specifically asked the original user whether they have any scoreboard plugins for that reason. Also, the randomness of it (as opposed to 100% of the time) means it's most likely not caused by one.

@martijnpu If `/npc name` does *nothing* you have a scoreboard related plugin conflict. Refer to the same wiki link -> https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by orblazer** [comment]
@mcmonkey4eva Yes i have see that and i have just comment for propose an solution but i have reed the wiki page and yes my way is not an ideal because this could break some other scoreboard

**Comment by mcmonkey4eva** [comment]
Is this still a problem on latest builds of Citizens from https://ci.citizensnpcs.co/job/Citizens2/ ? There were several related commits made quite recently (related to how `/npc name` functions internally) that might have resolved the problem.

**Comment by martijnpu** [comment]
It's still not working for me. 
build 1921
paper 1.15.2

**Comment by mcmonkey4eva** [comment]
@martijnpu as said before, it's unlikely your issue is the same as this one.
Could you please join the Discord @ https://discord.gg/Q6pZGSR and talk to us in `#citizens` so we can figure out what your own issue is?
