### ISSUE TITLE
Villager NPC Biome Skins

### ISSUE THREAD

**Issue by jendeh** [CitizensDev/Citizens2#1832]
1.14 added new biome specific skins for villagers. I'm able to change a villager NPC's profession, but not it's biome. I believe there's 7 different skins (plains, taiga, savanna, jungle, desert, snow, & swamp) available for villagers. So if you could add a way to change the villager's biome that would great.

Also, this may already be a thing, I'm not sure, but villagers have different trade levels which changes the color of the token thing on their belt. Is there a command to change villager NPC's level?

Thanks!

**Comment by mcmonkey4eva** [comment]
The biome skins in Spigot are called the villager's "type": https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Villager.Type.html

**Comment by HexedHero** [comment]
When can we expect this?

**Comment by mcmonkey4eva** [comment]
This was added by https://github.com/CitizensDev/Citizens2/commit/74836f6cc3eae3b72c67186db7de81b4853bf9f0 for build 1710 and newer!

**Comment by HexedHero** [comment]
Sorry to re-open this but I'm doing /npc villager in Build 1717 and is just returning an unknown command

**Comment by mcmonkey4eva** [comment]
Er, there appears to have been a copypaste error in the relevant commit: https://github.com/CitizensDev/Citizens2/commit/74836f6cc3eae3b72c67186db7de81b4853bf9f0#diff-e20ed9822060b3655e47ad6eb4d6e0bbR379

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/Citizens2/commit/530e1750944f7c573827bcbc40bca7b8b1aa0ef2 for build 1718+
