### ISSUE TITLE
/npc create not working!

### ISSUE THREAD

**Issue by Superepic97** [CitizensDev/Citizens2#1833]
The output of command `/version` on my server is: **(1.14.1 and 1.14.2)**
The output of command `/version citizens` on my server is: **(Citizens 2.0.25 (1.14.2 ALPHA #2))**
When we do /npc create Test
It says that NPC is placed but there isn't any NPC.

**Comment by mcmonkey4eva** [comment]
Please actually follow the issue template. Post the output of the version commands as was requested.
