### ISSUE TITLE
Citizens Crashes the server on boot when it has saved entities

### ISSUE THREAD

**Issue by SymphonicYT** [CitizensDev/Citizens2#1834]
The output of command `/version` on my server is: `git-Paper-95`
The output of command `/version citizens` on my server is: `Citizens-2.0.25-b1704`

The issue is that whenever an NPC is created and then saved, upon rebooting the server this error occurs: https://pastebin.com/AxhsGcG8, and the server crashes.

Here is my citizens config too: https://pastebin.com/78yexqJ8

As well as the saves.yml: https://pastebin.com/075fW2tr

**Comment by Ph4i1ur3** [comment]
Just to be 100% clear

Everything in that dump you provided is prefaced with this:
[11:02:58] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-95 (MC: 1.14.2) ---

(I'm not officially affiliated with this repo in any way, but I think you're missing crucial information to your crash in this report.)

**Comment by Alphexon** [comment]
I've been experiencing the same issue and it's new to the most recent versions of Paper. This does not occur when Citizens is not installed on the server.

**Comment by mcmonkey4eva** [comment]
` it's new to the most recent versions of Paper.`
Then it's a paper problem.
