### ISSUE TITLE
NPCS do not interact with each other, nor are events fired that involve them interacting with each other

### ISSUE THREAD

**Issue by Australopithicus** [CitizensDev/Citizens2#1835]
For my plugin, I need NPCS to fight each other and I intended to write mechanics to make this possible using events such as NPCCollisionEvent and NPCPushEvent, but they do not work when two npcs touch each other. This may be because of the fact that NPCs are completely unhindered by each other when they collide or touch each other, but no where do I see an option that would make them be able to collide with each other or affect each other, so that NPCCollisionEvent and NPCPushEvent would work. I have tried toggling the settings collidable and vulnerable, and I have even tried changing "pushable" with denizens, but these do nothing.

**Comment by fullwall** [comment]
Since fixed
