### ISSUE TITLE
1.14.3-pre4 Server crashed creating NPC

### ISSUE THREAD

**Issue by YourCoalAlt** [CitizensDev/Citizens2#1836]
When attempting to generate an NPC, the following crash occured: https://pastebin.com/xGFPFy1E

The output of command `/version` on my server is: **git-Spigot-f16400e-6dde4b9**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1704)**

**Comment by mcmonkey4eva** [comment]
Citizens is compatible with 1.14.2, not prereleases

**Comment by mcmonkey4eva** [comment]
Update: latest builds (1705+) now target 1.14.3-pre4.
