### ISSUE TITLE
Server crashed in 2.0.25 build 1706

### ISSUE THREAD

**Issue by SamLam140330** [CitizensDev/Citizens2#1840]
I have update the citizens plugin from 2.0.25 build 1704 to 2.0.25 build 1706 and got error. When I back to 2.0.25 build 1704, it run fine. Here is the error log.
latest log: https://pastebin.com/UXnW2Bfc
crash reports: https://pastebin.com/VSrTPEgf
The output of command `/version` on my server is: git-Spigot-df0eb25-da071ec (MC: 1.14.2)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1706)

**Comment by mcmonkey4eva** [comment]
dev builds starting at build 1705+ are compatible with Spigot 1.14.3-pre4.
Build 1704 is the last one that targets 1.14.2

**Comment by SamLam140330** [comment]
OK, thank you
