### ISSUE TITLE
Cannot create NPC

### ISSUE THREAD

**Issue by Nightfirez1988** [CitizensDev/Citizens2#1841]
hello i want to create NPC on my server the output from my server  that i create it but i don´t see it .my server ist runnig on an linux disturbion with 10 gb ram an 6 cores. 
 this is my server log on start: https://pastebin.com/c75CRWcr
and this is my configuration from citizens :https://pastebin.com/ungiUr2m

The output of command `/version` on my server is: this server is runnig Craftbukkit version git-Spigot-4d24e36-5193f76(mc 1.14)(Implementing API version 1.14-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT(build 1704)
pls help me this is a grate plugin

**Comment by mcmonkey4eva** [comment]
Spigot 1.14 flat is unsupported. Use 1.14.2 for compatibility with Citizens build 1704, or 1.14.3 for compatibility with upcoming builds.
