### ISSUE TITLE
NPCs don't store crossbow information

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#1842]
The version of server and citizens:
http://cdn.hexedhero.com/u/OMktFh0v1P.jpg

Basically add any ammo to the crossbow and give it to an NPC, it'll hold it just fine with the loaded model then on restart it goes back to a normal crossbow with no ammo, basically just doesn't store the crossbow data.

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/CitizensAPI/commit/071805238f51312e943862ede9f7899e391f1672 for build 1711 and newer!
