### ISSUE TITLE
NPC Creation issue

### ISSUE THREAD

**Issue by TheGamersUnknown** [CitizensDev/Citizens2#1843]
NPC Creation issue,

Hello,

I just bought your plugin and am having issues when creating an NPC. I type /npc create (Test) and nothing works, I have also tried to do different types and still nothing, it will say it loaded the NPC, but it does not show the NPC in game. Please let me know if you need anything else from me, I hope I provided enough information for you.

More info down below:

Thanks,

(Server Log) 
https://pastebin.com/GMWDBLhT

Citizens config file:
https://pastebin.com/9kiCGeKp

The output of command `/version` on my server is: **(git-Spigot-4d24e36-5193f76 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **(v2.0.25-SNAPSHOT (build 1704))**

**Comment by SXRWahrheit** [comment]
1. That is not a complete server log. Always provide a complete server log from startup.
2. Citizens always supports the latest minor revision of Minecraft and only that revision of each major version. You should use the latest Citizens developer build from Jenkins with Spigot 1.14.3, or a slightly older Citizens build with Spigot 1.14.2. Under no set of circumstances should you be using Spigot 1.14; it is outdated, buggy, and unsupported.
3. Citizens is freely available and always will be, per the description on the Spigot page.

**Comment by TheGamersUnknown** [comment]
I haven't had any issues with 1.14... I can't really run 1.14.1 or 1.14.2 spigot because it keeps crashing and giving me errors... Any other way to fix this>?

**Comment by Ph4i1ur3** [comment]
If you need assistance with upgrading your server, to be compatible with citizens, feel free contact me on discord: Xeane#5619

**Comment by mcmonkey4eva** [comment]
Run 1.14.2 or 1.14.3

1.14 Minecraft is entirely unusable and unstable. Don't even try to run that 0.o
