### ISSUE TITLE
NPC isn't spawning

### ISSUE THREAD

**Issue by AccioAce** [CitizensDev/Citizens2#1844]
Hello,
There is a bug in 1.14.3 for NPC where when you "/npc create" it doesn't spawn at all. I am using the latest version.

- Thanks

**Comment by SXRWahrheit** [comment]
Pursuant to the issue template that you ignored, please provide a full server log from startup and the actual version of your Spigot and Citizens builds using `/version` and `/version Citizens`.

**Comment by AccioAce** [comment]
For the version: https://gyazo.com/5ff822ed9d3b09369ebff7724e64d072
Citizen Version: https://gyazo.com/d59a597fcc65daf932edb5638bd9f136

**Comment by SXRWahrheit** [comment]
Per my previous comment please provide a full server log from startup. You may paste the `latest.log` file on https://pastebin.com and provide the link.

**Comment by SXRWahrheit** [comment]
Additionally, you do *not* have the latest Citizens build. A new build for 1.14.3 was released yesterday.

**Comment by AccioAce** [comment]
Ah I see, thanks. I will test it.

**Comment by AccioAce** [comment]
Alright, using the dev build for now.

Thank you!
