### ISSUE TITLE
Make fish look like they are in water when in the air/on land

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#1846]
The version of server and citizens:
http://cdn.hexedhero.com/u/OMktFh0v1P.jpg

**Comment by mcmonkey4eva** [comment]
... what?

**Comment by HexedHero** [comment]
I'm not even sure if its possible but so they don't do the flapping shit when on land as an NPC, fun fact the Pufferfish looks perfectly normal like its swimming in the air.
http://cdn.hexedhero.com/u/NUCtSLT8g3.mp4

**Comment by fullwall** [comment]
Yeah we had a discussion on discord about this @mcmonkey4eva by default fish flop around while not in water. Should this behavior be removed for all fish or only when "protected"?

**Comment by fullwall** [comment]
Yeah we had a discussion on discord about this @mcmonkey4eva by default fish flop around while not in water. Should this behavior be removed for all fish or only when "protected"?

**Comment by HexedHero** [comment]
I'd personally say that the fish should never flop around (Maybe a setting to make them flop) but I don't know anyone that would want a flopping around NPC its just silly.

**Comment by mcmonkey4eva** [comment]
Fish no longer flop on land via https://github.com/CitizensDev/Citizens2/commit/2caadf5bad0c022aae466a61f33b17755725be49 in build 1713+!
I think a command to optionally allow them to flop would be a good thing to have though.

**Comment by HexedHero** [comment]
Doesn't seem to work?
http://cdn.hexedhero.com/u/WUGlEfyY2a.jpg
http://cdn.hexedhero.com/u/qbhmDxQKp6.jpg

**Comment by mcmonkey4eva** [comment]
They don't stand up currently, they just don't actively flop.

**Comment by HexedHero** [comment]
Ah, okay! I didn't read and rushed to test

**Comment by fullwall** [comment]
Looks like making them stand vertically is impossible as the rendering is decided clientside (in water status is not propagated via network).
