### ISSUE TITLE
Armor disappears from player npcs when set directly after spawn

### ISSUE THREAD

**Issue by domisum** [CitizensDev/Citizens2#1849]
When creating a NPC using this [code](https://github.com/domisum/CorpusculumLib/blob/master/src/main/java/de/domisum/lib/corpusculumlib/CorpusculumListener.java) the diamond helmet shortly appears, but then disappears. I would expect that the diamond helmet stays.

No console output appears.

I demonstrate this issue in this video: https://www.youtube.com/watch?v=ZUFl_UYFZYg

The output of command `/version` on my server is: **CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1717)**

**Comment by mcmonkey4eva** [comment]
Use the equipment trait (via `npc.getTrait(Equipment.class)`) to stably modify an NPC's equipment.

**Comment by mcmonkey4eva** [comment]
I'm going to say this should be classified as a feature request, for the Equipment trait to explicitly track any equipment added directly to the Bukkit entity.
