### ISSUE TITLE
1.7.10 Pathfinding, player navigation issue

### ISSUE THREAD

**Issue by jsnbrown1989** [CitizensDev/Citizens2#185]
I am getting this error in my console. I do have 39 other plugins installed, which admitted is a lot, but I have attempted to use Citizens in the past and gotten the same error but with much less plugins.

INFO Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.mojang.authlib.properties.PropertyMap.putAll(Lcom/google/common/collect/Multimap;)Z" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/npc/entity/HumanController$SkinFetcher, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, com/mojang/authlib/properties/PropertyMap, have different Class objects for the type mon/collect/Multimap;)Z used in the signature

**Comment by mcmonkey4eva** [comment]
Do you like... have two different copies of C2 installed or somethin'? That's a really weird error.

**Comment by jsnbrown1989** [comment]
Nope, just double check just to be certain I wasn't being an idiot. Lemme give you a list of installed plugins in case you know of a conflict: 

AnCasino.jar BanManager.jar BanManager.zip BuySkills.jar CommandDelay_v1.0.jar 	 CrateReloaded.jar CurrencyHandler.jar  Dynmap-1.9.4.1-forge-10.12.0.jar	EnjinMinecraftPlugin.jar	Essentials.jar EssentialsChat.jar EssentialsGroupManager.jar  EssentialsProtect.jar EssentialsSpawn.jar FramePicture.jar GAListener.jar 	GoogleAnalyticsPlugin.jar GriefPrevention-282.jar  HideAndCustomPlugins.jar Lift.jar Lockette.jar  LuckyBlocks_6.0.jar  Minetrends.jar  PixelGym1.7.2.jar ProtocolLib-3.4.0.jar  RegionSelfService-2.0.1a-SNAPSHOT.jar ScheduledAnnouncer-2.8.5.jar  SimpleChatChannels.jar Vault-1.4.1.jar Votifier.jar VotifierCount.jar  VoxelSniper-5.168.9-SNAPSHOT.jar WGCustomFlags.jar WGRegionEvents.jar  WGTimeFlags.jar WhatIsIt.jar WorldBorder.jar WorldEdit.jar WorldGuard.jar WorldGuard_Custom_Flags.zip YASFPlugin.jar citizens-2.0.13-SNAPSHOT.jar floAuction.jar prism-2.0-Beta8.jar

**Comment by mcmonkey4eva** [comment]
Hm... can you post the full exception stacktrace? Maybe there's some additional information hidden in it

**Comment by jsnbrown1989** [comment]
I apologize, where can I find this information at?

**Comment by mcmonkey4eva** [comment]
Uh... the full error message that you get in your console.

**Comment by jsnbrown1989** [comment]
Ok. Sorry for the late response. I think this is all of the error:

12.01 10:36:59 [Server] INFO ... 3 more
12.01 10:36:59 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
12.01 10:36:59 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
12.01 10:36:59 [Server] INFO at net.citizensnpcs.npc.entity.HumanController$SkinThread.run(HumanController.java:226)
12.01 10:36:59 [Server] INFO at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:161)
12.01 10:36:59 [Server] INFO at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.fillProfileProperties(HumanController.java:137)
12.01 10:36:59 [Server] INFO Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "com.mojang.authlib.properties.PropertyMap.putAll(Lcom/google/common/collect/Multimap;)Z" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/npc/entity/HumanController$SkinFetcher, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, com/mojang/authlib/properties/PropertyMap, have different Class objects for the type mon/collect/Multimap;)Z used in the signature
12.01 10:36:59 [Server] INFO at java.lang.Thread.run(Unknown Source)
12.01 10:36:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
12.01 10:36:59 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
12.01 10:36:59 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
12.01 10:36:59 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Citizens v2.0.13-SNAPSHOT (build 1166) generated an exception while executing task 70
12.01 10:36:59 [Server] WARN Exception in thread "Craft Scheduler Thread - 10" 
12.01 10:36:58 [Server] WARN at java.lang.Thread.run(Unknown Source)
12.01 10:36:58 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
12.01 10:36:58 [Server] WARN at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
12.01 10:36:58 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
12.01 10:36:58 [Server] WARN at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
12.01 10:36:58 [Server] WARN at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
12.01 10:36:58 [Server] WARN at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
12.01 10:36:58 [Server] WARN at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
12.01 10:36:58 [Server] WARN at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
12.01 10:36:58 [Server] WARN at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1129)
12.01 10:36:58 [Server] WARN at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1347)
12.01 10:36:58 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
12.01 10:36:58 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
12.01 10:36:58 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
12.01 10:36:58 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
12.01 10:36:58 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
12.01 10:36:58 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
12.01 10:36:58 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:366)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:170)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:70)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:65)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:215)
12.01 10:36:58 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:29)
12.01 10:36:58 [Server] WARN java.lang.IllegalAccessError: tried to access field net.minecraft.pathfinding.PathNavigate.field_75521_i from class net.citizensnpcs.util.nms.PlayerNavigation

**Comment by mcmonkey4eva** [comment]
Download this custom version of Citizens:  http://cauldron.minecraftforge.net/threads/citizens-2-for-cauldron-1-7-10-released.289/
Since  you're running MCPC/Cauldron.

**Comment by jsnbrown1989** [comment]
Ok. This resolves this issue. I seem to be having an issue with skins not working. I name the player my ign and the player's skin is still steve. I am under the impression that it would change skins to match whatever I was wearing. Is this true? If so, should I make a separate ticket for this or could you help me within this one?

**Comment by mcmonkey4eva** [comment]
IT /should/ do that and it does in testing...
Probably belongs.... https://github.com/CitizensDev/Citizens2/issues/159 here? Maybe. I thought we had a more straightforward issue for it but I can't find it.

**Comment by Anora** [comment]
seam that download no longer exist

**Comment by mcmonkey4eva** [comment]
@Anora Unfortunately, Cauldron is no longer supported by Cauldron's own developers :/ they took their site down and all related downloads with it...
