### ISSUE TITLE
Creating NPC crashes server every-time

### ISSUE THREAD

**Issue by AcesGamingUK** [CitizensDev/Citizens2#1850]
### A detailed description of your issue or feature request
_When i run '/npc create' the server crashed and goes into a bootloop
deleting the "saves" file is the only way to stop the boot loop_

### Link to server log & Citizens config
[Error Log](https://pastebin.com/6UwnLYu2) 
[Config](https://pastebin.com/pAL2mMf4)
[Saves File](https://pastebin.com/YmVdUY7m)

### The output of command 
`/version` on my server is: 
**```This server is running CraftBukkit version 
git-Spigot-935adb3-bf32933 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT) 
You are 5 version(s) behind ```**

### The output of command 
`/version citizens` on my server is: 
**```Citizens version 2.0.25-SNAPSHOT (build 1704)
Website: http://www.citizensnpcs.co
Author: fullwall ```**

**Comment by mcmonkey4eva** [comment]
Update: https://ci.citizensnpcs.co/job/Citizens2/
You're running a version of Citizens that's meant for Spigot 1.14.2, while you're on a Spigot 1.14.3 server.
