### ISSUE TITLE
Pufferfishes in their puffed state are just... broken.

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#1853]
https://cdn.hexedhero.com/u/A5ZFmpPHi7.mp4
Don't really need to say anything more. They just start moving in a random direction forever with a sound playing 24/7 where it sounds like a star wars scene.

**Comment by fullwall** [comment]
Try latest build on 1.14

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply. If the issue still happens on latest builds, please reply below and we'll reopen this.
