### ISSUE TITLE
1.14 server huge lag

### ISSUE THREAD

**Issue by Momonche** [CitizensDev/Citizens2#1855]
I post my issue on Sentinel github but maybe it's Citizens

https://github.com/mcmonkeyprojects/Sentinel/issues/300

**Comment by mcmonkey4eva** [comment]
Not caused by Citizens or Sentinel.

**Comment by Momonche** [comment]
Sure it's caused by Citizens

**Comment by Momonche** [comment]
@mcmonkey4eva The build #1719 fix the performance problem ?

**Comment by mcmonkey4eva** [comment]
It's meant primarily to fix deadlock issues on Paper. It may also help with some NPC spawning stability, and pooooooooossssibly performance.

**Comment by Momonche** [comment]
@mcmonkey4eva Okay ! Thank you, It's the first step to a good 1.14 version :)
I will do some test
