### ISSUE TITLE
Refund?

### ISSUE THREAD

**Issue by JustiinGER** [CitizensDev/Citizens2#1857]
Hey, is there any Way to Refund and when "Yes" how?
I buy the Plugin 60 Minutes ago to use them with a other Plugin and now i see thats only a Donation. :/
In my Country its very late (02:00 AM) and i doesn't see thats a free Version its available...
You make a good Job! But 10$ is many Money.
I knew, thats my own mistake, but please charge me back the Money. 
I probaly donate again if i think the plugin is very good and can integrate it well.
Greetings, Justiin.

**Comment by mcmonkey4eva** [comment]
Send a DM to fullwall on spigot, include your paypal email address in the message.
