### ISSUE TITLE
Timing out/crashing server

### ISSUE THREAD

**Issue by NoahS18** [CitizensDev/Citizens2#1859]
The output of command `/version` on my server is: 2.0.25-SNAPSHOT (build 1718)
The output of command `/version citizens` on my server is: git-Paper-123 (MC: 1.14.3) (I have tried using Spigot and same issue)

Description: When originally creating the NPC's in a world, it works perfectly. However if the server is restarted, upon joining the server it will time out, kicking all of the players and ultimately crashing. There are multiple worlds on the server, and this only happens from a single world (Name is Earth). I have NPC's in two total worlds (Spaceship and Earth), spawning in the world "Spaceship" never causes any issues after restarting but spawning in "Earth" always causes it to time out. Currently, the only way to fix this that I have found is to completely delete all of the NPC's from Earth and readd them. 

The output of command `/version` on my server is: 2.0.25-SNAPSHOT (build 1718)
The output of command `/version citizens` on my server is: git-Paper-123 (MC: 1.14.3) (I have tried using Spigot and same issue)

Logs: 
Citizens version 2.0.25-SNAPSHOT (build 1718)
Citizens Config: https://pastebin.com/8ptj3RL4
Logs: https://pastebin.com/0RVfL1EN

**Comment by DarkmanBree** [comment]
You are not the only one with a server crashing issue related to Citizens.
I have it too.

**Comment by NoahS18** [comment]
Yeah, it makes me feel better that it is a common issue. It only happens if my server is restarted which is the weird part. It works fine when I spawn them in.

**Comment by mcmonkey4eva** [comment]
This issue was already resolved, please update https://ci.citizensnpcs.co/job/Citizens2/
