### ISSUE TITLE
Nameplate toggle

### ISSUE THREAD

**Issue by earr** [CitizensDev/Citizens2#186]
I am using citizens 2 Build #1206 on my 1.8 spigot server. When i type /npc name it just says "nameplate visibility toggled" but nothing happens. The nameplate is still visible completely even if you are far away or behind a wall. please advise. (I am also using the latest version of vault if this helps)

**Comment by mcmonkey4eva** [comment]
There's no 1-click fix for hiding nameplates, unfortunately.
There are workarounds that work until we add proper functionality:
In this case, you can just mount a second, invisible NPC on top of the real NPC, which will effectively hide the nameplate.

**Comment by earr** [comment]
That is a good idea, thanks. What does the /npc name command do?

**Comment by mcmonkey4eva** [comment]
It's a relic of an outdated time... also it's not even base Citizens, I'm fairly sure that command was added by Denizen. It's either in line for deletion or is deleted in latest versions, I forget which.

**Comment by earr** [comment]
Thanks for your quick replies and all the hard work you're doing here!

**Comment by Terryjomjarry** [comment]
Please help me, how do I make an npc invisible and how do I mount a npc on another npc! 

Everytime I type /npc mount it just mounts my player on top, please help this would really be respected because I don't want to have to blow $10 on helpful mobs!
