### ISSUE TITLE
Plugin conflict with FeatherBoard

### ISSUE THREAD

**Issue by SkyHeroesDada11** [CitizensDev/Citizens2#1861]
Hello,

I can not create a npc with a name that is too long, nor with the nickname of a player, nor can I hide his name..
I saw that we had to report this problem and I have scoreboard plugin, is FeatherBoard (premium plugin) Maybe it would come from that? Please do something..
My server is on 1.12.2

**Comment by SXRWahrheit** [comment]
This is a problem with Featherboard that the Featherboard dev must resolve.

**Comment by SkyHeroesDada11** [comment]
"Supports any scoreboard or team plugin such as McMMO, HealthBar, ColoredTags, Citizens2, ..."

**Comment by SXRWahrheit** [comment]
Those plugins do not create conflicts because their scoreboards are well-managed. Featherboard forces itself into the scoreboard system and creates problems for other plugins that those plugins cannot resolve.

**Comment by mcmonkey4eva** [comment]
Make sure your copies of FeatherBoard and also Citizens are fully up to date on their latest versions.
The FeatherBoard dev has said in the past that current versions should be compatible though old versions might not be.
I have no idea how accurate/true that claim is though and don't make any guarantees.

A lot of scoreboard plugins just willfully make themselves the sole scoreboard controller on the server (thus breaking compatibility with Citizens and anything else that uses just the standard main scoreboard).

Any conflicts with scoreboard stuff is almost always the other plugin's problem, that we can't really solve here (short of completely redesigning our scoreboard system to be a bulletproof packet-based system, which ... should not be necessary).
