### ISSUE TITLE
NPCRegistry#getByUniqueId does not work

### ISSUE THREAD

**Issue by kangarko** [CitizensDev/Citizens2#1862]
My current situation is NPCs seem to call normal bukkit events for which we listen and store data in the players file. That is undesirable for NPCs and I am trying to stop this.

The problem is that calling the aforementioned method outputs null even though the given entity is a NPC. I was testing this using both NPCRegistry#getNPC and this method worked fine. Am I missing something or is this a problem in Citizens?

My code: ![a](https://i.imgur.com/EKiPcyI.png)

Server: **Paper-b125 (MC: 1.14.3)**
Citizens: **2.0.25-b1719**

Thanks

**Comment by fullwall** [comment]
First of all, .getNPC does not get by name, it casts to NPCHolder and retrieves it like that. Secondly, you are caching the player's UUID from bukkit and not the Citizens NPC UUID which is found by NPC#getUniqueId()

**Comment by kangarko** [comment]
Thanks. However there's no way for me to get the Citizens NPC since the PlayerCache invokes on player and entity related events where it only accepts the Bukkit entity's UUID.

So it is safe to assume that method on line 295 will never fire for NPCs and only perform the check on line 290?

**Comment by mcmonkey4eva** [comment]
Use the Entity object itself, as is in your first line. Don't use the entity UUID.

`So it is safe to assume that method on line 295 will never fire for NPCs` that depends on whether *you* call it... it's *your* code. We don't know what *your* code calls or won't call.
I will suggest that you make a point of *not* calling that ever at all (or at least not ever when you have any possible Entity object).

In some cases you can translate between entity UUID and NPC UUID by swapping the version bits, but I don't think this is guaranteed (the guaranteed method would be to loop over all spawned NPCs and compared their entity UUID to the UUID input you have... but that's better to just not do if possible for efficiency reasons).

**Comment by kangarko** [comment]
Thanks, got it.

Lastly is there a way to disable NPC's firing the living entity related events? So that I don't have to make an if statement for each event such as the EntityDamageEvent.

**Comment by mcmonkey4eva** [comment]
Nooope. Best to just have if statements wherever they belong.

**Comment by kangarko** [comment]
I'm afraid I can't do that. Not to mention thousands of plugins are listening to those events expecting a real player output. 

Can you add a toggle to the settings file of Citizens? "player-npc-fire-events"

**Comment by fullwall** [comment]
Unfortunately there's no easy way to do this because all these events are called deep in Spigot/NMS code.

**Comment by kangarko** [comment]
Got it. Will look for an alternative efficient solution, adding 58 statements is not.

**Comment by mcmonkey4eva** [comment]
@kangarko legitimate serious question: What's wrong with adding 58 statements?

**Comment by kangarko** [comment]
It's a code inefficiency. The longer the code with more statements the worse it gets to maintain and the higher the chances to break.

If something can be done simply, let it be done simply. Having one condition yields far better output in the long term than having 58. I am teaching beginners so I need to be strict on this one.
