### ISSUE TITLE
Console Error Spams

### ISSUE THREAD

**Issue by codgamerMC** [CitizensDev/Citizens2#1863]
- Rented a Server Hosting Company for my server and started having big performance issues related to 1.14.3 and switched to Paper on Recommendations and in my PC the older version of Citizens (1718) Worked fine with Paper but in the Server Host it did not, don't know why, same Jar and everything so updated to 1725 to be able to play and I have no issues relating to performance now or in game gameplay but I have that console spam which will eventually take a lot of space, wanted to know what that was, thanks!!
Server Log: https://pastebin.com/p3v6idRZ
Citizen Config File: https://pastebin.com/M0pQRjH1

The output of command `/version` on my server is: **(Paper Version git-Paper-129 MC 1.14.3)**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.25 SNAPSHOT Build 1725)**

**Comment by fullwall** [comment]
Fixed in build 1726
