### ISSUE TITLE
[Feature Request] Create an NPCOpenDoorEvent

### ISSUE THREAD

**Issue by KaruzoHikari** [CitizensDev/Citizens2#1864]
I personally have a plugin that checks when a player opens a door in order to execute some things there, and I'd like to do the same when the NPCs opened the door.
However, there's currently no event being called when a door is open by an NPC.

**Comment by mcmonkey4eva** [comment]
Was added via https://github.com/CitizensDev/CitizensAPI/commit/08aace9607ef7533d9f78e652a4a9c18c8213fe9 to Citizens build 1729+
