### ISSUE TITLE
npc limit

### ISSUE THREAD

**Issue by Saelman** [CitizensDev/Citizens2#1866]
<!--
** DO NOT IGNORE **
Hi, i have a question that may also be a issue. im unable to have anymore than 59 npc's, i know having more than that seems like a lot but im running a larger rpg server and theres alot of quests and npc traders around. so they build up quickly, not sure if this is a bug or if theres a limit to the npc's i can have. if theres anyway to change this limit please let me know. thanks
https://pastebin.com/Bf8Q1Bn8
The output of command `/version` on my server is: **(1.14.2)**
The output of command `/version citizens` on my server is: **(2.0.25-b1704)**

**Comment by mcmonkey4eva** [comment]
protip: you can edit your posts. I've remove the commentmark from your post here. In the future please just edit instead of posting a new issue entirely as you've done with #1867
