### ISSUE TITLE
Npc limit

### ISSUE THREAD

**Issue by Saelman** [CitizensDev/Citizens2#1867]
Description: Unable to have more than 59 npc's, running a larger rpg server so having a lot of npc's is a bit needed im able to spawn in  more than 59 but on a reload it causes the npc's to be removed and erased, i dont seem them in the files either, so they dont appear to be saved.
- https://pastebin.com/Bf8Q1Bn8

The output of command `/version` on my server is: **(1.14.2)**
The output of command `/version citizens` on my server is: **(2.0.25-b1704)**

**Comment by mcmonkey4eva** [comment]
There's no NPC limit. You most likely just have an error preventing the autosave from working. Check your console log.

Also: Update your server, 1.14.2 is unsupported. Use 1.14.3.

Also: You've failed to follow the issue template... please actually follow what it says to do, then reply below.

**Comment by Saelman** [comment]
https://pastebin.com/9h4xA8xN <----- Console Logs
https://pastebin.com/JpqpST60 <------ Config
New version of spigot is 1.14.3
New Version of citizens  is 2.0.25-b1730 

Sorry i wasnt able to post a server log yesterday, was having some issues with spam in console so it wouldnt have done ya any good.

The issue still persists after moving to 1.14.3, i have 61 npc's now, so, i got 2 of them to somehow save in (not really sure what caused this) Im not seeing any errors in console following the command, i should be a bit more exact tho. i can spawn in more than 61, but if i reload the plugin they are removed and not saved any. I do reload the plugin quiet a lot, so im not sure if i need to wait and give it time to save them before i reload the plugin.

**Comment by mcmonkey4eva** [comment]
A: That log is misformatted to the point of being near unreadable
B: That log literally does not contain a Citizens save operation. Use `/citizens save` (or stop the server) to save any changes.
C: You should avoid using `/citizens reload` as best as possible, that command **will** break things if you're not super careful with it.
D: "CMI" is known to cause a lot of issues. I highly recommend removing it and replacing it with anything else at all.
