### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ChickaChicko** [CitizensDev/Citizens2#1868]
I dont know how to do that when you right click npc the npc run a command or open a shop
please help

**Comment by mcmonkey4eva** [comment]
https://forum.denizenscript.com/viewtopic.php?f=13&t=149 <-- use this Denizen script with Denizen: https://www.spigotmc.org/resources/denizen.21039/

For more basic help please ask on Discord: https://discord.gg/Q6pZGSR
