### ISSUE TITLE
NPCs Desppawning upon server startup/NPC Names not appearing fully

### ISSUE THREAD

**Issue by codgamerMC** [CitizensDev/Citizens2#1869]
So every time I stop then Start my server I have 1 or 2 NPC always de spawning which is a huge problem considering they are part of the Main Quest which gives access to the main world and if the NPC de spawns and I can't go fix it then people can't play on the server because they cannot finish the quest, I would like to know why is that? Also some NPCs with names longer than 16 letters have parts of their first name cutoff which is also misleading in the questing because players can't read the name correctly which causes confusion, also on the same version of Citizens2, any ideas? I have tried Build 1730 with no luck either on the issue.
    Server Log: No Errors
    Citizen Config File: https://pastebin.com/M0pQRjH1

The output of command /version on my server is: (Paper Version git-Paper-129 MC 1.14.3)
The output of command /version citizens on my server is: (Citizens version 2.0.25 SNAPSHOT Build 1726)

**Comment by mcmonkey4eva** [comment]
First: always run latest builds https://ci.citizensnpcs.co/job/Citizens2/
Second: Test with Spigot instead of Paper (no idea if that matters, but try it)
Third: names longer than 16 characters are based on Scoreboard control, which is usually broken by plugin conflicts - see here: https://wiki.citizensnpcs.co/Plugin_Conflict
Fourth: if the NPCs not spawning properly are villagers, you likely are seeing this existing issue: https://github.com/CitizensDev/Citizens2/issues/1822

If the above linked issue is not the same as your own, please reply below with more detail (what NPCs are despawning? Specific ones? If so, post their data from `saves.yml`.)

**Comment by codgamerMC** [comment]
I changed to Paper because Spigot was giving me memory leaks and on a Server Host Memory is at a prime considering it is not cheap and Paper Optimizes it all the way in my experience thats why I changed, same issue no luck o n Build 1730 like I mentioned same problems, I didn't have the 16 character problem until I updated to Build 1728 and the despawning issue started happening like a few days ago and Paper version hasn't changed what changed was I updated to 1728 and those things appeared, and YES Specific NPC's. The name of NPCS are Hornas Glosk (I made 2 of them to see if it would help and problem persist on both) and on NPC Named Guide. Saves.yml Data: https://pastebin.com/UbGMxsuw

**Comment by codgamerMC** [comment]
Maybe a plugin list might suggest which plugins could cause a conflict?

![image](https://user-images.githubusercontent.com/10374236/61212502-7c47cf00-a6d0-11e9-91cd-793eb0b57f25.png)

**Comment by mcmonkey4eva** [comment]
Scoreboard related plugins are most likely to conflict. `TabList` sounds like a potentially relevant one. Follow the steps on the wiki page to actually find the culprit.
When you say they're despawning when you restart your server - you mean they just aren't spawning in automatically, right?

**Comment by codgamerMC** [comment]
Correct, they are there spawned with /npc spawn when it happens, but I shut off the server to reload updated plugins and when I start it again all of the NPCS spawn back except those two

**Comment by mcmonkey4eva** [comment]
Could you please test with Spigot

**Comment by codgamerMC** [comment]
My server had players so I created a copy of the server with all plugin configs the same and tried it both on Paper and Spigot and could not replicate the despawning/spawning error, tried shutting the server few times on each and no effect, they spawned back like they should, idk if it has to do that I put a dtltrader GUI on them so that plugin forces them to spawn back

**Comment by mcmonkey4eva** [comment]
That makes it really hard for us to do anything about the issue if you yourself cannot make it happen again with your own exact same setup.

**Comment by codgamerMC** [comment]
I will be looking into it, maybe it is the server host for some odd reason, I have been having weird issues with the host that I cannot replicated on my PC

**Comment by mcmonkey4eva** [comment]
Names should be fixed in build 1731+, there was an issue found (ref #1870 ).
For despawning, redirect to #1822
