### ISSUE TITLE
Build 1730 crashed ..

### ISSUE THREAD

**Issue by Rockiego** [CitizensDev/Citizens2#1871]
Build #1730  on a 1.14 server. /npc Create Blocks <Name of npc>
crashed the server. 

console: https://pastebin.com/gSnpQYAk
Crash log: https://pastebin.com/U41mvam2

**Comment by mcmonkey4eva** [comment]
Update your copy of Spigot to 1.14.3

MC 1.14 flat is a broken unusable sub-version.

**Comment by Rockiego** [comment]
sweet, works. now hope the rest of the plugins follow and dont break. 

Thanks
