### ISSUE TITLE
NPCS Instantly turn into a ticking entity upon creation

### ISSUE THREAD

**Issue by kwright02** [CitizensDev/Citizens2#1872]
Upon creating an NPC it spawns and then immediately turns into a Ticking entity that crashes the server and produces the following crash report: https://pastebin.com/f7Rfpfx1 The server can't be started unless saves.yml is deleted, and thus Citizens is unusable in this state.

Citizens Config: https://pastebin.com/pMSrcitB

The output of command `/version` on my server is: **git-Spigot-093165d-ba575a5 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.25-SBAPSHOT (build 1729)**

**Comment by fullwall** [comment]
Update to Minecraft 1.14.3
