### ISSUE TITLE
Support For 1.14 Crossbow Item in NPC Equipment

### ISSUE THREAD

**Issue by ShmoopyDoo** [CitizensDev/Citizens2#1877]
NPCs which have been equipped with a loaded crossbow will reset to an unloaded crossbow upon server restart
Version: https://i.imgur.com/2nXrQ84.png
Citizens Version: https://i.imgur.com/FmOolxv.png

**Comment by fullwall** [comment]
Can you try with the latest build please?

**Comment by ShmoopyDoo** [comment]
Sorry for the delay, it seems to work now, thanks!
