### ISSUE TITLE
Dolphins Pathfinding Very Buggy

### ISSUE THREAD

**Issue by ShmoopyDoo** [CitizensDev/Citizens2#1878]
Dolphin NPC are unable to path, regardless of whether or not they are set to follow waypoints or are set to wander. Setting them to swim or have no gravity etc also has no effect

Version: https://i.imgur.com/2nXrQ84.png
Citizens Version: https://i.imgur.com/FmOolxv.png

**Comment by fullwall** [comment]
The latest build should let them move a little bit but still a bit glitchy.

**Comment by mcmonkey4eva** [comment]
I've tested and confirmed that dolphin pathfinder underwater is uh... wildly spazzing out on the ocean floor, teleporting to destinations. Tropical_Fish, however, swim around at the surface and never complete the way to any points, just go back and forth while bouncing.

**Comment by fullwall** [comment]
Much improved, however axolotls do not yet have underwater gravity. Feel free to open a separate issue.
