### ISSUE TITLE
Villager glowing issue

### ISSUE THREAD

**Issue by Sean1472** [CitizensDev/Citizens2#1879]
Hello, I recently posted an issue about a glowing issue which has been somewhat solved. The player type glowing is now fixed but villager types still only glow white returning null in chat still when you try to change their glowing colour. 
See https://github.com/CitizensDev/Citizens2/issues/1852 for information on that.

It still does the same as the previous image in the other issue. 
https://imgur.com/ug7YjOH

This is on a fresh install of citizens on the newest dev build (1737)
Spigot version paper 1.13.2 - 624

**Comment by fullwall** [comment]
Added a message for this. Glowing color is only supported on Player NPCs I believe?

**Comment by mcmonkey4eva** [comment]
Supposedly it _used to be_ possible via potion effect colors, but is no longer. If this is wrong, please reply below with details so we can reopen this.
