### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by Victor-Sun** [CitizensDev/Citizens2#188]
Pathways do not work for ghasts.
I do not know if this was intentional or not, but ghasts do not move.

**Comment by crzyaznbro** [comment]
Any solution?

**Comment by mcmonkey4eva** [comment]
Sorry for the slow response.
@fullwall any ideas on this, or would you prefer I look into it for you?
(I can't at the time of writing, busy with something else).
This just seems like a 'forgot to override a method, can be fixed in two seconds' kind of problem.

**Comment by crzyaznbro** [comment]
So I guess the dev doesn't have a way to fix this?

**Comment by fullwall** [comment]
I haven't had time to get to this yet, seems like an issue with the flying navigator.

**Comment by mcmonkey4eva** [comment]
Is this still an issue in 1.8.3?

**Comment by crzyaznbro** [comment]
yes
