### ISSUE TITLE
Pathfinding on 1.13 not "dynamic" but rather "checkpointy"

### ISSUE THREAD

**Issue by MiniDigger** [CitizensDev/Citizens2#1880]
This is kinda hard to explain, its better seen in the video down below.
Basically the NPC doesn't seem to track me dynamically but checks like once a second, moves to that location and then tries to attack me. 
I talked to @mcmonkey4eva in discord trying to debug this, enabling `use-new-finder: true` didn't fix this, we also can't reproduce it on 1.14.
He said that this seems to be a general issue with citizens pathfinding, thats why I am reporting it here as opposed to the sentinel tracker.

Video: https://streamable.com/tr9zz
Video with path debug: https://streamable.com/t7jj6

Versions:
```
version
[12:21:44 INFO]: This server is running Paper version git-Paper-641 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[12:21:44 INFO]: Previous version: git-DyescapePaper-154ec17 (MC: 1.13.2)
[12:21:44 INFO]: You are running the latest version
version citizens
[12:22:02 INFO]: Citizens version 2.0.25-SNAPSHOT (build 1737)
[12:22:02 INFO]: Website: http://www.citizensnpcs.co
[12:22:02 INFO]: Author: fullwall
version sentinel
[12:22:06 INFO]: Sentinel version 1.9.2 (build 261)
[12:22:06 INFO]: Author: mcmonkey
```
Config: https://hasteb.in/axiyugud.yaml
(Sentinel Config: https://hasteb.in/otevokoc.yaml )

**Comment by mcmonkey4eva** [comment]
Specific to the call: `getNPC().getNavigator().setTarget(entity, false);`, and further specific to 1.13.2 servers.

It's behaving like it has its target set to the player's location every update cycle, rather than continually tracking towards the player (which it seems to more properly achieve on 1.14.4).

**Comment by fullwall** [comment]
Just to follow up on this - update-path-rate is set to 20 so it should update every second, the logic hasn't changed between 1.13.2 and 1.14.4 so unless there's some debug log output I'm not sure what to make of this issue.

**Comment by mcmonkey4eva** [comment]
Given the above, and the fact that 1.13 is now effectively a dead Minecraft version (per bStats, less than a single percentage point of all minecraft servers), gonna say this can be closed unless there's followup with good debug information (and, er, some reason why 1.13 should be bothered with at all lol)
