### ISSUE TITLE
1.14.4 Performance problem in server

### ISSUE THREAD

**Issue by successed** [CitizensDev/Citizens2#1881]
http://prntscr.com/ojcqw3

**Comment by mcmonkey4eva** [comment]
A screenshot of a paper timings report.
... Yeah, nope, that's not remotely useful to work with.
Follow the issue template and post actual info.

1.14.x in general (not specific to Citizens, all of minecraft 1.14.x) has significant performance problems. See also https://github.com/CitizensDev/Citizens2/issues/1848

**Comment by successed** [comment]
> A screenshot of a paper timings report.
> ... Yeah, nope, that's not remotely useful to work with.
> Follow the issue template and post actual info.
> 
> 1.14.x in general (not specific to Citizens, all of minecraft 1.14.x) has significant performance problems. See also #1848

Paper-146 (MC: 1.14.4)
https://timings.aikar.co/?id=f29e7fd91e194526aa589ee7f9040da4

**Comment by mcmonkey4eva** [comment]
Your timings show lag from
1: Strongest of all... donkeys.
2: Second-strongest: chunk loading.
Refer to #1848

**Comment by successed** [comment]
> Your timings show lag from
> 1: Strongest of all... donkeys.
> 2: Second-strongest: chunk loading.
> Refer to #1848

İ removed citizens plugin, and i have tps 20. I think you should take care of this.

**Comment by mcmonkey4eva** [comment]
Read #1848

**Comment by successed** [comment]
> Read #1848

i removed this plugin, t.y

**Comment by mcmonkey4eva** [comment]
![spam](https://i.alexgoodwin.media/i/misc/cc0a3d.png)
Please don't spam issues with your inability to read.
