### ISSUE TITLE
Server Crash 1.14.4

### ISSUE THREAD

**Issue by BlackRebbel** [CitizensDev/Citizens2#1882]
![2019-07-24_16 25 56](https://user-images.githubusercontent.com/53191833/61801847-c72fb800-ae2f-11e9-8562-1334de3806d1.png)
![2019-07-24_16 26 14](https://user-images.githubusercontent.com/53191833/61801849-c72fb800-ae2f-11e9-8568-7fb0936f365a.png)

https://pastebin.com/ijyD34SX - Config

`[16:24:19] [Server thread/INFO]: [Citizens] Could not fetch entity id mapping fields: net/minecraft/server/v1_14_R1/MinecraftKey.b()Ljava/lang/String; (loaded from file:/pro/bin/mc/spigot/1.14.4/spigot-1.14.4.jar by sun.misc.Launcher$AppClassLoader@f145b92e) called from class net.citizensnpcs.nms.v1_14_R1.util.CustomEntityRegistry (loaded from file:/home/gs-40785/plugins/Citizens-2.0.25-b1731.jar by org.bukkit.plugin.java.PluginClassLoader@e576d405)..`

When I create an npc and basicly type /npc fellow or /npc sential, for some reason it's crashing my server!

**Comment by mcmonkey4eva** [comment]
Update your copy of Citizens, you're running an outdated build.
