### ISSUE TITLE
Npcs disappeared and can't spawn any new ones

### ISSUE THREAD

**Issue by ggStranger** [CitizensDev/Citizens2#1883]
- Logged in today on my minehut server and all my npcs disappeared and when trying to recreate any new ones this error pops up: The image below has the versions and the error
![Screenshot (1)](https://user-images.githubusercontent.com/53266589/61800757-31605100-ae60-11e9-95f8-8fe7fb0b7079.png)

https://pastebin.com/JWvpM5uL The logs

**

**Comment by mcmonkey4eva** [comment]
Update to latest Citizens build and Spigot 1.14.4.
1.14.3 is no longer supported due to the release of 1.14.4
