### ISSUE TITLE
Cant give an NPC a Potion

### ISSUE THREAD

**Issue by Symnatics** [CitizensDev/Citizens2#1885]
Hello,
first of all, here are the Versions i use: http://prntscr.com/ojnhmg . Secondly, here is my Problem: If i give a Potion to an NPC via the Equipment Trait OR the Inventory Trait it will be removed after a few milliseconds from the inventory of the npc.. every other item i tried works..

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8
