### ISSUE TITLE
Invisible Humans on 1.14

### ISSUE THREAD

**Issue by orange451** [CitizensDev/Citizens2#1888]
Since I've updated to 1.14 in the last few days, I've been getting many reports of invisible NPCs.

My plugin creates human NPC entities that wander around the server. Some are hostile, some are not. I'm on the newest-current version of Citizens. I compiled it last night from the source code here to double check; They are still invisible, but only sometimes.

I haven't been able to reproduce what exactly makes them invisible. I tried manually forcing citizens to "respawn" the npc every few seconds, but that doesn't fix the issue. It also does not affect all players the same way. A human that is invisible on my screen might not be invisible on yours.

Please look into this, It's important for our server! :)

**Comment by mcmonkey4eva** [comment]
`I compiled it last night from the source code here to double check` don't do that, use the jenkins build server: https://ci.citizensnpcs.co/job/Citizens2/

Also please follow the issue template when posting issues. We cannot resolve issues that do not follow the template (which requests basic but critical information like version details).

You may be encountering the issue listed here: https://github.com/CitizensDev/Citizens2/issues/1822
Or you may be encountering a version issue (ie not running 1.14.4 latest with citizens latest)
or you may be encountering a plugin conflict ("TAB" is one that's been named a few times as causing things to go invisible in 1.14.x)
