### ISSUE TITLE
Problem spawning npc

### ISSUE THREAD

**Issue by CleetusChan** [CitizensDev/Citizens2#1889]
Spawn location could not be parsed or was not found. Please help.

**Comment by CleetusChan** [comment]
Also i typed this in /npc create Squidward --at -18.314 126 -355.163 world --type player

**Comment by mcmonkey4eva** [comment]
A: Please follow the issue template.
B: You formatted the create command wrong. Generally you probably just want `/npc create Squidward` and that's it, you don't have to specify the rest. If you want to specify a specific location inline for some reason, it's `x:y:z:world` not `x y z world`
