### ISSUE TITLE
Cannot ride NPCs

### ISSUE THREAD

**Issue by DeanUK** [CitizensDev/Citizens2#189]
I'm receiving this error when doing /npc control -m 
http://i.imgur.com/wXtEsPV.png
Console error: http://pastebin.com/HUTLqXM8
Using Spigot 1.8 and Citizens2 dev build 1206

**Comment by earr** [comment]
I was also getting issues on build 1206 (such as skins disappearing) I downgraded to 1190 to fix that though, and I can ride npcs fine.

**Comment by mcmonkey4eva** [comment]
Can't replicate. What Spigot version are you on?

**Comment by DeanUK** [comment]
Spigot version: http://i.imgur.com/Z9m74Ht.png

**Comment by mcmonkey4eva** [comment]
Update Spigot, that's outdated.

**Comment by DeanUK** [comment]
Updated to the latest Spigot. Issue still occurs

**Comment by sanjay900** [comment]
Theres a fix, change that setPassengerOf function to a mount in the code, i cant make a pr atm though. It was a recent change though that did it.

**Comment by fullwall** [comment]
@sanjay900 - in Controllable? Do you mean change 
        handle.setPassengerOf(getHandle()); to getHandle().mount(handle) ?

**Comment by sanjay900** [comment]
Yeah

**Comment by sanjay900** [comment]
I just tested it, it works fine by changing that

**Comment by Roos-Skywalker** [comment]
How do I change that?

**Comment by tronman2020** [comment]
/npc controllable

-----Original Message-----

**Comment by sanjay900** [comment]
Its in the code. Later versions of spigot removed setPassengerOf.

**Comment by Roos-Skywalker** [comment]
Tronman2020, I was referring to the code. I know that.
Sanjay90, I am not a programmer. I do not know what files to open to edit that line of text.

**Comment by mcmonkey4eva** [comment]
A pull request would be awesome.

**Comment by sanjay900** [comment]
Done.

**Comment by sanjay900** [comment]
@Roos-Skywalker The idea behind this is to get it fixed by @mcmonkey4eva or @fullwall so that you don't have to edit it yourself. Check my pull request though if you are really curious.

**Comment by sanjay900** [comment]
I made a request, though github is glitching up for me so im not sure if it worked

**Comment by mcmonkey4eva** [comment]
Yeah github's bugged ATM, but the PR went through :)

**Comment by sanjay900** [comment]
Awesome, Im gonna look into making NPC's support skin blobs, it opens up having NPC be skinnable without you having to have to skin on someone. I got it working earlier, but it was a bit buggy so im gonna try it again.

**Comment by mcmonkey4eva** [comment]
Oh. This was fixed.
