### ISSUE TITLE
Can't spawn npcs

### ISSUE THREAD

**Issue by CleetusChan** [CitizensDev/Citizens2#1890]
After the last post, It still doesn't work. Here are the logs
5.07 21:35:18 [Server] Server thread/WARN ... 33 more
25.07 21:35:18 [Server] Server thread/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
25.07 21:35:18 [Server] Server thread/WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
25.07 21:35:18 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
25.07 21:35:18 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
25.07 21:35:18 [Server] Server thread/WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
25.07 21:35:18 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:773)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:832)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:849)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:856)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1473)
25.07 21:35:18 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1619)
25.07 21:35:18 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:689)
25.07 21:35:18 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
25.07 21:35:18 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
25.07 21:35:18 [Server] Server thread/WARN at java.lang.reflect.Method.invoke(Method.java:498)
25.07 21:35:18 [Server] Server thread/WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
25.07 21:35:18 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
25.07 21:35:18 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
25.07 21:35:18 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
25.07 21:35:18 [Server] Server thread/WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination

**Comment by CleetusChan** [comment]
I ran /npc create Squidward

**Comment by mcmonkey4eva** [comment]
- Follow the issue template. If you open another issue that does not follow the template again I will just lock it.
- You don't need to open a new issue to reply. Just ... reply in the reply box at the bottom of the page.
- Update Citizens and/or your server, one of them is likely to be outdated. I can't tell you which because you have not followed the issue template.
