### ISSUE TITLE
Spigot Plugin

### ISSUE THREAD

**Issue by YuvalShoshan** [CitizensDev/Citizens2#1891]
Hello. I've purchase the plugin "Citizens" on Spigot, but never got it. It showed me I sent the money but still can't download it. Can you guys fix it please?

**Comment by mcmonkey4eva** [comment]
Ask Spigot about that?
Or just... download the free dev builds: https://ci.citizensnpcs.co/job/Citizens2/
Citizens is free, as is explained on the readme on the spigot page.

**Comment by YuvalShoshan** [comment]
I payed money for that plugin, so I want to get it. If i wont get it I would like to get refunded.

**Comment by mcmonkey4eva** [comment]
The plugin is FREE. Anyone can get it. The payment is a donation option, as is explained on the readme on the spigot page.
