### ISSUE TITLE
Citizens Fire Bug

### ISSUE THREAD

**Issue by tommy1235** [CitizensDev/Citizens2#1894]
The output of command `/version` on my server is: **1.8.8-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **2.0.16-SNAPSHOT**

Whenever anyone right clicks a player, they set on fire, after removing citizens, it no longer happens.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by mcmonkey4eva** [comment]
Also that bug almost certainly has nothing to do with Citizens
