### ISSUE TITLE
Help, Plugin Well Not Work When Making NPC

### ISSUE THREAD

**Issue by StormyBlueyss** [CitizensDev/Citizens2#1896]
Npc cannot be created when i try this pops up in console.

I do the correct command to make a NPC and it says Please report this error on console. 

This is what pops up:

29.07 18:03:01 [Server] Server thread/WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
29.07 18:03:01 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.07 18:03:01 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
29.07 18:03:01 [Server] Server thread/WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.07 18:03:01 [Server] Server thread/WARN at java.lang.reflect.Method.invoke(Method.java:498)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
29.07 18:03:01 [Server] Server thread/WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
29.07 18:03:01 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
29.07 18:03:01 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148)
29.07 18:03:01 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:688)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1619)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1473)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:37)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(SourceFile:9)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
29.07 18:03:01 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:856)

Please Help

**Comment by Ph4i1ur3** [comment]
- Update your server software
- follow the issue template

**Comment by StormyBlueyss** [comment]
Whats server software?

**Comment by mcmonkey4eva** [comment]
update Spigot to latest 1.14.4, also update Citizens to latest build
