### ISSUE TITLE
NPCs can't use doors properly in 1.13.2

### ISSUE THREAD

**Issue by KaruzoHikari** [CitizensDev/Citizens2#1897]
Hey there.
I have a pretty big issue with the Citizens plugin, as NPCs seem to get confused on how to use the doors properly.
Basically, once they try to go through the door, they either go just fine, or they close it, change the orientation and stop in there. Might be easy to understand with a few examples:

When the door is facing to the south or to the north and the hinge is on the left; it does this:
https://i.imgur.com/t2LHn9h.gif

However, when the door is facing to the north or south and hinge on the right, it works just fine:
https://i.imgur.com/ZnpCA8j.gif

If the door is facing east or west, it will open the door / go through it.

Not only it closes the door sometimes, but also it changes the orientation.
 -> With door facing SOUTH or NORTH, hinge on the LEFT, it changed to door facing EAST, hinge on the RIGHT and it will **close** the door.
 -> With door facing WEST or EAST, hinge on the LEFT, it changed to door facing EAST, hinge on the RIGHT and it will **open** the door.

Here's the log, in case it's needed. After running the command to move the NPC, nothing else is logged: https://pastebin.com/Rdh34bK1
The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1737)**

**Comment by mcmonkey4eva** [comment]
Your PR https://github.com/CitizensDev/CitizensAPI/pull/52 was pulled, so should be fixed now.
