### ISSUE TITLE
Baby villagers are moving

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#1901]
Latest Spigot 1.14.4 version (cbcc8e8-06efc9e), latest Citizens dev build (1738)

1.  /npc create someRandomName
2. /npc type villager
3. /npc age -1

From there, the baby villager NPC has started wandering in my house, as if its AI has not been removed.
It only happens the first time you create the NPC, if you change its type with _/npc type_ and then go back to a villager, the problem will disappear.
It seems to happen only with villagers.

Here are all the informations I gathered, I hope you will find the problem!

Kind regards,

SkytAsul

**Comment by mcmonkey4eva** [comment]
Confirmed + Replicated.

**Comment by mcmonkey4eva** [comment]
Should be fixed in latest builds (via commit autolinked above)
