### ISSUE TITLE
Error Citizen 1.14.3 

### ISSUE THREAD

**Issue by LightNox** [CitizensDev/Citizens2#1903]
08:58:56: java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
08:58:56: at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
08:58:56: at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
08:58:56: at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
08:58:56: at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
08:58:56: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
08:58:56: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
08:58:56: at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
08:58:56: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:58:56: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:58:56: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:58:56: at java.lang.reflect.Method.invoke(Method.java:498)
08:58:56: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
08:58:56: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
08:58:56: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
08:58:56: at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
08:58:56: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
08:58:56: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
08:58:56: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
08:58:56: at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831)
08:58:56: at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639)
08:58:56: at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
08:58:56: at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
08:58:56: at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
08:58:56: at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
08:58:56: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
08:58:56: at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
08:58:56: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
08:58:56: at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002)
08:58:56: at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995)
08:58:56: at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)
08:58:56: at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979)
08:58:56: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912)
08:58:56: at java.lang.Thread.run(Thread.java:748)
08:58:56: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
08:58:56: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
08:58:56: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
08:58:56: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
08:58:56: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
08:58:56: ... 33 more

**Comment by SXRWahrheit** [comment]
Citizens supports the latest minor revision of Minecraft, 1.14.4. You need to update your server.

**Comment by LightNox** [comment]
Oh it's annoying because all my other plugins only work in version 1.14.3, there is no possibility to have the version 1.14.3 of Citizens for it to work on my current server?

**Comment by LightNox** [comment]
you cant give me the 1.14.3 release for my server ?

**Comment by axemwa** [comment]
Did u try this version? 2.0.25 (1.14.3 BUILD #2) 
https://www.spigotmc.org/resources/citizens.13811/history
I'd suggest suggesting to your plugins authors to update to 1.14.4

**Comment by LightNox** [comment]
@axemwa Oh Thanks you so much it work now :D

**Comment by axemwa** [comment]
np :) can close issue now

**Comment by mcmonkey4eva** [comment]
`Oh it's annoying because all my other plugins only work in version 1.14.3`
@LightNox I really really doubt that ^
Most problems are cross-compatible between Minecraft updates, and the exceptions are usually still at least compatible between minor updates... only a very very small rare few were broken by the 1.14.3->1.14.4 update, Citizens unfortunately was in that rare few. Just update to latest build and latest Spigot 1.14.4, it's almost certain everything else (on latest builds) will work fine too.

@axemwa please don't encourage people to use outdated builds.

**Comment by axemwa** [comment]
I didn't encourage them to use outdated builds he asked for help and I answered, in fact if you read it correctly I actually encouraged/suggested them to contact the authors of their plugin to ask them to update?

**Comment by SXRWahrheit** [comment]
![2019-08-04 16_46_01-Error Citizen 1 14 3 · Issue #1903 · CitizensDev_Citizens2](https://user-images.githubusercontent.com/774463/62429693-63cb4300-b6d7-11e9-9ac9-d723a427c660.png)

This is you encouraging them to use an outdated build.

**Comment by axemwa** [comment]
Umm no it's not obviusly READ IT! Just cause I provided a link that's not encouragement

**Comment by mcmonkey4eva** [comment]
Chill, mate. Just asking you to please not link old builds or anything (if you link it they'll use it regardless of what you write :/ which I say from experience).

**Comment by axemwa** [comment]
I'm chill, sorry I get a bit too thorough when I try to explain myself plus I'm tired and haven't slept for 2 days. Peace all gonna crash out
