### ISSUE TITLE
[1.14.3] Error citizen disappear

### ISSUE THREAD

**Issue by brnxx** [CitizensDev/Citizens2#1906]
I am using the plugin for version **1.14.3** but when you restart the server, the npc will disappear!
And I have to spawn /npc [ID] all the time for it to appear again.
I can not upgrade to **1.14.4**. It is giving me error in the other plugins and my server is full.

![image](https://user-images.githubusercontent.com/49076883/62499329-a87adb00-b7b8-11e9-8aea-108d10ddeeb5.png)
![image](https://user-images.githubusercontent.com/49076883/62499368-cd6f4e00-b7b8-11e9-954b-ae3e6dccf692.png)

My NPC: 
![image](https://user-images.githubusercontent.com/49076883/62499491-4a022c80-b7b9-11e9-9953-25ba1231d8c0.png)

**Comment by SXRWahrheit** [comment]
You can upgrade to 1.14.4, you just choose not to. 1.14.3 is.not supported, this is not a bug.

**Comment by brnxx** [comment]
> 
> 
> You can upgrade to 1.14.4, you just choose not to. 1.14.3 is not supported, this is not a bug.

The plugin supports 1.14.3, it is there on the plugin site, in spigot. Has a build for 1.14.3

**Comment by SXRWahrheit** [comment]
Only 1.14.4 is supported.

**Comment by brnxx** [comment]
> 
> 
> Only 1.14.4 is supported.

![image](https://user-images.githubusercontent.com/49076883/62501753-9736cc00-b7c2-11e9-90da-677caea7f682.png)

**Comment by SXRWahrheit** [comment]
Only the current builds are supported. That is not a current builds. The current builds do not support 1.14.3. You were explicitly told this on the Discord, opened this issue anyway, and are continuing to reply to it after having been informed that 1.14.3 is not supported; you are spamming and abusing the issue system.

**Comment by brnxx** [comment]
> 
> 
> Only the current builds are supported. That is not a current builds. The current builds do not support 1.14.3. You were explicitly told this on the Discord, opened this issue anyway, and are continuing to reply to it after having been informed that 1.14.3 is not supported; you are spamming and abusing the issue system.

Is the plugin open source? Maybe I could fix this for my version.

**Comment by mcmonkey4eva** [comment]
`Is the plugin open source? ` ...
...................
..................................
I don't have enough dots on my keyboard for asking whether Citizens is open source on the Citizens GitHub page.

Either way: update to 1.14.4. We will not and cannot give support for a broken unsupported minecraft version. Almost all plugins that work on 1.14.3 will work on 1.14.4, Citizens is an extremely rare special case... and those rare few special cases, almost always will update quickly to the new version, as Citizens did.
