### ISSUE TITLE
Error with SLEEP Animation

### ISSUE THREAD

**Issue by TheCalypso** [CitizensDev/Citizens2#1907]
![image](https://user-images.githubusercontent.com/33781244/62531059-f7208780-b841-11e9-9637-97f31d64ac0e.png)

We just used the citizens plugin to make NPC in our Lobby. The goal is to click on the NPCs to be teleported to different servers. So far everything is working, however we would like some NPCs to sleep, squat. We have tried to use calls directly in NMS, passed by the API citizens and Denizens but nothing works. Cepedant we had an error https://pastebin.com/92wUTKHF
We have a side plugin made by us that allows you to add holograms above the head of the NPC or to control your posture (that's what does not work).
Thank you for your help.
TheCalypso

```
This server is running Paper version git-Paper-156 (MC:1.14.4) Implementing API version 1.14.4-R0.1-SNAPSHOT)
Checking version, please wait...
You are 3 version(s) behind

Citizens version 2.0.25-SNAPSHOT (build 1738)
Website: https://www.citizensnpc.co
Author: Fullwall
```

**Comment by mcmonkey4eva** [comment]
- I cleaned up the formatting on your issue post for you.

Yikes, looks like SLEEP was never reimplemented in 1.14: https://github.com/CitizensDev/Citizens2/blob/master/v1_14_R1/src/main/java/net/citizensnpcs/nms/v1_14_R1/util/PlayerAnimationImpl.java#L77

**Comment by TheCalypso** [comment]
Hello,

Thank you for your quick reply ! Make attantion the sneak is also broken! I think there is also a problem here. When we did our tests we had errors with the sleep and the sneak.

thank you so much

**Comment by mcmonkey4eva** [comment]
Do you have an error message from sneaking? It's likely to be a separate issue, so if you have an error message please post it as a new issue

**Comment by TheCalypso** [comment]
There are no error with sneak but nothing append, always stand, and isSneaking return true until we put stand.

**Comment by mcmonkey4eva** [comment]
That'd actually be an issue with Denizen or Spigot if so, as the Sneaking trait and `/npc sneak` command are in Denizen, and it calls out to Spigot code rather than Citizens (as there's a basic Bukkit API for `setSneaking`), https://github.com/DenizenScript/Denizen/issues

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/0c3d998a72e82d2e5af9bc3b11f59ad163f4b0b6
