### ISSUE TITLE
1.14.X Error

### ISSUE THREAD

**Issue by talhostic** [CitizensDev/Citizens2#1909]
Chat Error : Please report this error: [See console]
java.lang.NoClassDefFounfError:
net/minecraft/server/v1_14_R1/PathDestination

**Comment by SXRWahrheit** [comment]
You ignored the format for opening an issue, but my guess from your incomplete error is that you are running an unsupported version of Minecraft. Please ensure you are running the latest builds of Spigot or Paper for 1.14.4.

**Comment by talhostic** [comment]
No running version for 1.14 ?

**Comment by mcmonkey4eva** [comment]
Use 1.14.4.
1.14 flat and other early subversions are entirely unsupported (by us and by Minecraft itself)

**Comment by talhostic** [comment]
Ok thanks :)
