### ISSUE TITLE
NumberFormatException on 1.8 with ipv6

### ISSUE THREAD

**Issue by Mahagon** [CitizensDev/Citizens2#191]
https://gist.github.com/Mahagon/7aedea305a4a18bebd2d

I think there should be a ipv4 check or sth :o 

Im using this version on my 1.8 spigot server: 
http://dev.bukkit.org/bukkit-plugins/citizens/files/49-2-0-14-alpha-1-for-mc-1-8-1/

Citizens works fine, i just wanted you to know :D

**Comment by mcmonkey4eva** [comment]
That's not Citizens, that's `de.upsj.bukkit.advertising` generating that error.

**Comment by Mahagon** [comment]
Oh you are right 
my mistake sry
