### ISSUE TITLE
1.14.3 PathDestination Error

### ISSUE THREAD

**Issue by Fulserish** [CitizensDev/Citizens2#1910]
I am currently using version 1.14.3 of the plugin. Whenever I am attempting to make an NPC, let's call him "Bob", I end up getting an issue of which states "java.lang.NoClassDefFoundError:net/minecraft/server/v1_14_R1/PathDestination". The NPC is supposed to be a player-like NPC (skin change, all that stuff). I have linked below everything that is stated to be listed. Any help would be appreciated. Many thanks!

Server log:
https://pastebin.com/73HeHd1M

Citizens config:
https://pastebin.com/mYXefGq4

The output of the command `/version` on my server is: This server is running CraftBukkit version git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3) (Implementing API version 1.14.3-SNAPSHOT)
The output of the command `/version citizens` on my server is: Citizens version 2.0.25-SNAPSHOT (build 1732)

**Comment by mcmonkey4eva** [comment]
Update to 1.14.4
