### ISSUE TITLE
Create npc get big error in chat

### ISSUE THREAD

**Issue by bryantvdberg** [CitizensDev/Citizens2#1911]
The output of command `/version` on my server is: git paper 131 / mc version 1.14.3
The output of command `/version citizens` on my server is: 2.0.25 snapshot

get big error when try to create npc java.lang.noclassdeffounderror:net/minecraft/server/v1_14R1/PATH Destination

**Comment by mcmonkey4eva** [comment]
Update to Paper 1.14.4
