### ISSUE TITLE
No Hit Delay and a Damage Bug?

### ISSUE THREAD

**Issue by Saynax** [CitizensDev/Citizens2#1913]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-166 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: ** Citizens version 2.0.25-SNAPSHOT (build 1742)**
Citizens Config: default config, did not change anything
My problem: I dont have a hit delay when I hit a npc, also i kill the npc within a few hits without even a weapon and he doesnt deals me with many hits one single heart

**Comment by mcmonkey4eva** [comment]
Are you using Sentinel?
... if not, why aren't you?

**Comment by Symnatics** [comment]
I just made a small bot that fights against a player and everything works perfectly except that.. i use npc.getNavigator().setTarget(target, true) to let the bot attack the player.. didnt looked deeply into sentinel and if i can get this last things working i also wouldnt need it

**Comment by mcmonkey4eva** [comment]
Damage from that will always be 1 heart. If you want it to dynamically change according to the item being held... that's one of the things Sentinel does.

**Comment by mcmonkey4eva** [comment]
Use Sentinel if you want combat to just work properly... write your own logic if you want to write it yourself. Citizens doesn't provide stable combat functionality within itself, as that's a bit outside the idea of what Citizens _is_.
