### ISSUE TITLE
Confused User Needs Help

### ISSUE THREAD

**Issue by LegitSpeedmc** [CitizensDev/Citizens2#1917]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

Hello my name is LegitSpeedMC I am running a local server for 1.14.4 but for your citizens 2 plugin for CraftBukit it hasn't been updated to the lastest versions of the game but on spigoit it has I was wondering if you are ever going to update it anytime soon thanks alot for reading

**Comment by mcmonkey4eva** [comment]
You didn't follow the issue template and somehow put your description in the title.
I've fixed the post to at least have the description in the main body.

Latest Citizens builds can be found here: https://ci.citizensnpcs.co/job/Citizens2/
