### ISSUE TITLE
1.14.4 - Parrots still imitate sounds even if muted

### ISSUE THREAD

**Issue by Banaenschen** [CitizensDev/Citizens2#1919]
If you use /npc sound -n on a parrot npc it will still imitate other mob sounds.
Versions:
![Screenshot_1](https://user-images.githubusercontent.com/35613981/63229113-27323800-c1fd-11e9-93fb-30b469eecd9b.jpg)

**Comment by mcmonkey4eva** [comment]
Might be better in latest builds (via https://github.com/CitizensDev/Citizens2/commit/b3589e40f9810c7091645902f824a4a35c2841e5 )

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply. If there is still an issue, please reply with details and we'll reopen this.
