### ISSUE TITLE
NPC's stuck in air

### ISSUE THREAD

**Issue by Chronoken** [CitizensDev/Citizens2#1921]
Whenever you make an npc with paths to follow (/npc path) and either teleport him above ground or toss him into air, it gets stuck there.
This is a really old bug, i experienced it on 1.10.X, 1.12.X and it still occurs on 1.13.2 .

Config of the npc affected by this bug: https://pastebin.com/U2HcyhTK
Screenshot of the npc affected by this bug (with debug-pathfinding set to true): https://imgur.com/a/cE46EJp

Console log from debug-pathfinding: https://pastebin.com/iMtjyMZg

Minecraft Version: 1.13.2
Paper Version: 1.13.2 - 642
Citizens Version: 2.0.25-SNAPSHOT (build 1744)
Sentinel Version: 1.9.5 (build 287)

**Comment by mcmonkey4eva** [comment]
This was fixed via https://github.com/CitizensDev/Citizens2/issues/2264
