### ISSUE TITLE
Unable to create Wither NPCs

### ISSUE THREAD

**Issue by APimpNamedShane** [CitizensDev/Citizens2#1924]
A huge collection of mob NPCs disappeared, and I'm trying to remake some of them. The ENDER_DRAGON worked fine, but when I attempt to create a wither, the "regular" npc I'm trying to turn into a WITHER disappears, and I get a message:

 Please report this error: [See console]
java.lang.NullPointerException:null and the console spits out the pastebin content below.

The same thing happens when I attempt to create the NPC as a WITHER to begin with, except there's obviously nothing to disappear

https://pastebin.com/d7PBwz1V - Server log
https://pastebin.com/Hkey8QW2 - Citizens Config
https://pastebin.com/ZzMBR9M0 - Saves.yml

22.08 12:45:36 [Server] INFO This server is running Paper version git-Paper-146 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
22.08 12:45:36 [Server] INFO Previous version: git-Paper-162 (MC: 1.14.4)
22.08 12:45:36 [Server] INFO You are 29 version(s) behind
22.08 12:45:45 [Server] INFO Citizens version 2.0.25-SNAPSHOT (build 1717)
22.08 12:45:45 [Server] INFO Website: http://www.citizensnpcs.co
22.08 12:45:45 [Server] INFO Author: fullwall

**Comment by mcmonkey4eva** [comment]
Update: https://ci.citizensnpcs.co/job/Citizens2/
You're very far behind. Also update Paper while you're at it.
