### ISSUE TITLE
Code for NPC's Dissapearing?

### ISSUE THREAD

**Issue by Culup** [CitizensDev/Citizens2#1925]
Okay, I coded my own npc plugin and it works. But when a player goes too far anyway and unloads the chunks and comes back the npcs disappear. What was the code you used for this to work. I tried something with a runnable respawning them but that created a lot of lag. So what did you do for citizens?

**Comment by mcmonkey4eva** [comment]
This is entirely outside the scope of a GitHub issue.
Either way, all the source code is visible here... if you want to learn how Citizens works, get to reading...
