### ISSUE TITLE
Invisible armorstand buildup in chunks with NPC's

### ISSUE THREAD

**Issue by Raigna** [CitizensDev/Citizens2#1926]
Version : Paper-167 (MC-1.14.4)
Version Citizens : 2.0.25-SNAPSHOT (build 1744)
Timings Report : https://timings.aikar.co/?id=b4ad03a6f53b492ea1490f400ef27382#plugins

Since the move to 1.14.4 Invisible armorstands have been slowly building up over time in certain chunks near npcs and eventually crashing the server, when the server is restarted they are all destroyed but quickly build up again

I did a little investigating and discovered the cause is when holograms and NPC's are next to each other, at first I thought it was the holographic displays but i changed to holograms and the problem still persisted, I have also completely removed every plugin except a few and when Citizens is disabled the hologram plugin is fine but when enabled it begins to build up 1000's of armorstands again.

[config.zip](https://github.com/CitizensDev/Citizens2/files/3535259/config.zip)

**Comment by Raigna** [comment]
![2019-08-23_16 42 45](https://user-images.githubusercontent.com/47435063/63606028-18fe6600-c5c7-11e9-9608-3bd749edc998.png)
here is a picture of the server not long after a reset, I recently added lagassist and its now limiting the amount of armorstands being created but its just a patch not a fix

something else I noticed, it doesnt happen to all NPC's spawn npcs are fine its the ones away from spawn that have the problems so Im wondering if its when chunks unload since spawn is constantly loaded in???

**Comment by Raigna** [comment]
![2019-08-24_00 44 37](https://user-images.githubusercontent.com/47435063/63629186-8b436a80-c608-11e9-8897-3bfbcb9fa68d.png)
And this is a picture of the server after 6 hours of being up with a new timings report

https://timings.aikar.co/?id=7296a90dcd3544edbdff6dd91186080b

**Comment by Ph4i1ur3** [comment]
Update your paper. If that doesnt fix it, you have a complex plugin conflict, as I could not reproduce this issue with just Citizens and Holographic Displays alone.

**Comment by mcmonkey4eva** [comment]
The only time armor stands spawn from Citizens is when `/npc sit` is used (which is technically a Denizen command anyway). Those shouldn't get stuck around either way. If you are using `/npc sit`, investigate whether that's related and if it is causing problems please reply below with details.

Otherwise, plugin conflict testing time! https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by Raigna** [comment]
Version : Spigot (MC-1.14.4-R0-1-SNAPSHOT)
Version Citizens : 2.0.25-SNAPSHOT (build 1744)
New Timings: https://timings.aikar.co/?id=1b9f49d5079346e6b7975bd1d767db97#plugins

I recently reported a issue to you guys here, and was told a plugin was conflicting with something other than citizens so I did a little investigating and removed every plugin except holographic displays, citizens, lagassist and multiverse (i temporarily removed multiverse and lagassist and still had the same problems, i was only using lagassist to monitor the entities in the chunks). The only time the armorstands as I mentioned in the other post stop spawning was when citizens was disabled from the server. the ones in spawn are fine but any outside of the spawn area cause this lag

I have left a copy of the test server i created within the post for you to test out, the affected areas was in and around spawnworld x 993 y 29 z 507, but I was also getting problems within other areas too. the only thing that seems to stop it is changing the spawn area....making me think the spawn being the only constantly loaded chunk prevents more to spawn

p.s I changed the paper spigot to spigot to make sure it wasnt that but the problem still persists

Here is the test server I was using https://mega.nz/#!PSRA1CRL!16tdYRV0fXx7io_U3blF2fJ02jWcqrhHoPvIhCcdgDg
I havent included lagassist with it being a premium plugin

**Comment by Raigna** [comment]
P.S it may take upto 10 mins before the problem begins to show, you cant notice the lag until hours later but as you can see in the timings i posted they begin to build slowly up

**Comment by mcmonkey4eva** [comment]
` and removed every plugin except holographic displays, citizens, lagassist and multiverse `
Remove every plugin except Citizens.
Every one.
ESPECIALLY the hologram one, being the most likely related plugin.

Remember: Citizens literally doesn't create armor stands in the first place.

**Comment by Raigna** [comment]
I have and it works fine and I understand its holographic display creating the invisible armorstands and not the citizen plugin itself but I was just reporting a possible conflict between the two plugins when they have previously ran fine together pre 1.14.4. I have also reported the issue to the guys running holographic displays 

the reason I have reported it here too is that the conflict was not only with holographic displays but also the plugin holograms, both of them work fine until citizens is added and then they begin to cause similar problems
