### ISSUE TITLE
Large server load from NPC

### ISSUE THREAD

**Issue by Vitoldik** [CitizensDev/Citizens2#1927]
When will be fixed a large server load from NPC (MC: 1.14.4)?
TPS server drops to 0 after a time (5-10 hours)

The output of command `/version` on my server is: git-Paper-172 (MC: 1.14.4)
The output of command `/version citizens` on my server is: 2.0.25-SNAPSHOT (build 1744)

**Comment by Raigna** [comment]
I had the same problem and you may have seen that i figured out mine was caused due to invisible armorstands because of a problem with a hologram plugin and citizens, have you checked your timings and noticed a extra amount of amorstands that arent meant to be there???

**Comment by mcmonkey4eva** [comment]
Minecraft 1.14.x itself has severe performance problems, Citizens is a victim of this problem rather than its cause.
