### ISSUE TITLE
Citizens 2 crashing server when NPC is spawned

### ISSUE THREAD

**Issue by NeoEka** [CitizensDev/Citizens2#193]
Citizens 2 is crashing my minecraft server whenever I try to spawn an NPC. Crash report is here
http://www.pastebucket.com/74100

**Comment by mcmonkey4eva** [comment]
You're running the wrong version of Citizens.
Get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by NeoEka** [comment]
I tried the 1186 1.8, Doesn't start up as the server isn't 1.8. and I've tried the 1166 1.7.10 version which crashes the server.

**Comment by mcmonkey4eva** [comment]
https://www.youtube.com/watch?v=pzkS8k5iacw

All else fails, just update to Spigot 1.8

**Comment by NeoEka** [comment]
Can't update to spigot 1.8 since the rest of the plugins I use aren't 1.8.

**Comment by Diddyer** [comment]
I have the same problem only run 1166,

npc spawn = crash server

VERSION SERVER:
This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

VERSION CITIZENS:
Citizens v2.0.13-SNAPSHOT (build 1166)

Log:
http://pastebin.com/T5YDrXA8

**Comment by mcmonkey4eva** [comment]
Please comment below if you can replicate issues in Spigot 1.8.3 and we'll reopen the issue.
