### ISSUE TITLE
citizensnpcs.EventListen causing lag / lag spikes.

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#1930]
Paper dev 175 (Spigot 1.14.4)
Citizens2 dev 1744

Going through to micro-optimize wherever I can, I noticed Citizens' ``net.citizensnpcs.EventListen$1`` causing some performance hit / lag spikes. Is there any way to further optimize this check or settings that can be disabled? All my NPCs are static, non-moving, with commands attached to them by the plugin CitizensCMD.

![link1](https://i.imgur.com/cEPTwXr.png)
![link2](https://i.imgur.com/Z5zlIvZ.png)

Config: https://paste.ubuntu.com/p/SWD2jXhMRR/
Saves: https://paste.ubuntu.com/p/KkSd8PvZKW/
Timings: https://timings.aikar.co/?id=c5d11c94a35d4d78be92003639d18e28#timings

**Comment by mcmonkey4eva** [comment]
- 1.14.x minecraft is laggy and borked. If you want a stable server, use 1.13.2 or even 1.12.2. This isn't specific to Citizens, it's a Minecraft problem.
- We cannot give any helpful information based on timings reports in most cases. An actual Java Profiler would need to be used to find anything.

**Comment by mibby** [comment]
Citizens may not be the cause of any lag, but it's what's causing the most impact with lag spikes. My server is at the point where I can reach a stable 20.0 TPS on 1.14 without any issue. I'll run a warmroast profiler if you need more details.

**Comment by fullwall** [comment]
WarmRoast please.

**Comment by mibby** [comment]
@fullwall Here's the warmroast profile output. All threads monitored, 5 minute output. However it seems the upload paste browser is down.
https://paste.ubuntu.com/p/YGCqPJTvqT/

I see that lucko's spark supersedes WarmRoast as a replacement, so I'll download that and re-run the profiler.

**Comment by mibby** [comment]
I made some config changes and now EventListen does not have any noticeable impact. 

```
  skins:
    max-retries: 1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0
```

New Config: https://paste.ubuntu.com/p/BQNTMnW95H/

Perhaps with max-retries at -1, it was constantly spamming skin tasks for all npcs even if it didn't need to get the skin? My biggest impact now seems to be from ``Citizens::Task: net.citizensnpcs.Citizens$3 (Single)`` at a minuscule amount of performance hit.

https://timings.aikar.co/?id=1263e22174074cc6928099d88532cc52
Spark profile, 60 seconds, main thread only: https://sparkprofiler.github.io/#5ckCUbd2kU
Spark profile, 60 seconds, all threads: https://sparkprofiler.github.io/#fS2D6aPJZp
