### ISSUE TITLE
Invisible armorstand bug (update)

### ISSUE THREAD

**Issue by Raigna** [CitizensDev/Citizens2#1931]
Version : Spigot (MC-1.14.4-R0-1-SNAPSHOT)
Version Citizens : 2.0.25-SNAPSHOT (build 1744)
New Timings: https://timings.aikar.co/?id=1b9f49d5079346e6b7975bd1d767db97#plugins

I recently reported a issue to you guys here https://github.com/CitizensDev/Citizens2/issues/1926, and was told a plugin was conflicting with something other than citizens so I did a little investigating and removed every plugin except holographic displays, citizens, lagassist and multiverse (i temporarily removed multiverse and lagassist and still had the same problems, i was only using lagassist to monitor the entities in the chunks). The only time the armorstands as I mentioned in the other post stop spawning was when citizens was disabled from the server. the ones in spawn are fine but any outside of the spawn area cause this lag

I have left a copy of the test server i created within the post for you to test out, the affected areas was in and around spawnworld x 993 y 29 z 507, but I was also getting problems within other areas too. the only thing that seems to stop it is changing the spawn area....making me think the spawn being the only constantly loaded chunk prevents more to spawn

p.s I changed the paper spigot to spigot to make sure it wasnt that but the problem still persists

Here is the test server I was using https://mega.nz/#!PSRA1CRL!16tdYRV0fXx7io_U3blF2fJ02jWcqrhHoPvIhCcdgDg
I havent included lagassist with it being a premium plugin

**Comment by Raigna** [comment]
P.S it may take upto 10 mins before the problem begins to show, you cant notice the lag until hours later but as you can see in the timings i posted they begin to build slowly up

**Comment by mcmonkey4eva** [comment]
If this is part of an existing issue, reply to the original issue, don't open a new one.
