### ISSUE TITLE
Tablist flickering

### ISSUE THREAD

**Issue by GeneralBibi** [CitizensDev/Citizens2#1935]
So my Tablist is buging. The Name of the NPC is in timely random gaps in the tablist viewable.

Version -> paper version git-paper-172 (MC: 1.14.4)
Citizens version -> Citizens v2.0.25-SNAPSHOT (build 1745)

ive only used 1 NPC (named Bob) 

no other plugins while testing because ive thought maybe its because of any other plugin but it was not.

**Comment by JefpenShmirtz** [comment]
"that's an unavoidable problem due  to the way Minecraft handles player-like entities since MC1.7.6.
(well, you can avoid it by switching to villager or zombie or whatever NPCs of course)"
from mcmonkey (main denizen dev)
