### ISSUE TITLE
Citizens 1.14.3 There was an error

### ISSUE THREAD

**Issue by XiaoWen12** [CitizensDev/Citizens2#1936]
I don't have anything to do, sometimes this message will appear.
I went looking for the plugin file but couldn't find the file he said.
Citizens Version: 2.0.25（1.14.3 BUILD＃2）

`> [12:44:01 WARN]: java.lang.NullPointerException: Nodes must be provided.
> [12:44:01 WARN]: at org.yaml.snakeyaml.nodes.NodeTuple.<init>(NodeTuple.java:28)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:164)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315)
> [12:44:01 WARN]: at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315)
> [12:44:01 WARN]: at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315)
> [12:44:01 WARN]: at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315)
> [12:44:01 WARN]: at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:24)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:157)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:315)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:95)
> [12:44:01 WARN]: at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65)
> [12:44:01 WARN]: at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306)
> [12:44:01 WARN]: at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
> [12:44:01 WARN]: at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245)
> [12:44:01 WARN]: at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
> [12:44:01 WARN]: at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65)
> [12:44:01 WARN]: at net.citizensnpcs.api.util.YamlStorage.save(YamlStorage.java:106)
> [12:44:01 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore$1.run(SimpleNPCDataStore.java:73)
> [12:45:21 WARN]: java.util.ConcurrentModificationException
> [12:45:21 WARN]: at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
> [12:45:21 WARN]: at java.util.ArrayList$Itr.next(ArrayList.java:859)
> [12:45:21 WARN]: at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:191)
> [12:45:21 WARN]: at org.yaml.snakeyaml.serializer.Serializer.serializeNode(Serializer.java:195)
> [12:45:21 WARN]: at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:111)
> [12:45:21 WARN]: at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:307)
> [12:45:21 WARN]: at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
> [12:45:21 WARN]: at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245)
> [12:45:21 WARN]: at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:39)
> [12:45:21 WARN]: at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65)
> [12:45:21 WARN]: at net.citizensnpcs.api.util.YamlStorage.save(YamlStorage.java:106)
> [12:45:21 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore$1.run(SimpleNPCDataStore.java:73)`

**Comment by fullwall** [comment]
Something's up with your saves.yml. Can you pastebin it somewhere?

**Comment by fullwall** [comment]
What Minecraft version are you on? If 1.14.4 then please update your Citizens.

**Comment by XiaoWen12** [comment]
> What Minecraft version are you on? If 1.14.4 then please update your Citizens.

2.0.25（1.14.3 BUILD＃2）

**Comment by mcmonkey4eva** [comment]
Update to 1.14.4.

**Comment by XiaoWen12** [comment]
> 更新至1.14.4。

But my server is 1.14.3

**Comment by mcmonkey4eva** [comment]
Update your server to 1.14.4.
