### ISSUE TITLE
NPC's Getting Deleted.

### ISSUE THREAD

**Issue by Ankira** [CitizensDev/Citizens2#1938]
So, some of my citizens npc's keep getting removed by my server. I am wondering if this is a new glitch or if I need to update my citizens etc. Please get back to me ASAP

The output of command `/version` on my server is: Paper 1.14.4
The output of command `/version citizens` on my server is: 2.0.25 SNAPSHOT build 1741

**Comment by mcmonkey4eva** [comment]
... Those are not the outputs of the `/version` commands.

And: Look in your logs file for error messages. If your NPCs are actually getting deleted, there most likely is one during startup or shutdown.

If it's not true deletion but rather NPC entities disappearing, you're seeing https://github.com/CitizensDev/Citizens2/issues/1822

If you have an error message you can post, please reply below with it.
