### ISSUE TITLE
Spigot 1.7.10, Citizens Crashing Server

### ISSUE THREAD

**Issue by AshvaleStaff** [CitizensDev/Citizens2#194]
The only version of Citizens I could get to be recognized on startup was #1166, which is throwing these lines of error and crashing my server making it unable to startup again. 

http://www.pastebucket.com/74110

Are there any versions of Citizens that work with Spigot 1.7.10 Build #1637?

**Comment by mcmonkey4eva** [comment]
Are you sure you don't have a protocol hack version?
In which case http://wiki.citizensnpcs.co/Versions 1186 is needed. Worth trying if nothing else.

**Comment by AshvaleStaff** [comment]
Not sure what Protocol Hack is but version 1186 appears to be working perfectly. Thank you very much for the ultra speedy response.

**Comment by mcmonkey4eva** [comment]
Protocol hack means that 1.8 clients are able to connect in addition to the regular 1.7 clients
