### ISSUE TITLE
bug in version 1.14.3

### ISSUE THREAD

**Issue by aldsgts** [CitizensDev/Citizens2#1940]
good night, I made a donation to get the citizens plug for version 1.14.3, but. The following error is appearing in version 1.14.3, but I don't want to upgrade to version 1.14.4, can you fix it?

01.09 02:10:57 Thread do  servidor [servidor]  / WARN ... 34 mais 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em java.lang.ClassLoader.loadClass (ClassLoader.java:357) 
01.09 02:10 : 57  Thread do servidor [servidor]  / WARN em java.lang.ClassLoader.loadClass (ClassLoader.java:424) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em org.bukkit.plugin.java.PluginClassLoader.findClass ( PluginClassLoader.java:81) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em org.bukkit.plugin.java.PluginClassLoader.findClass (PluginClassLoader.java:86) 
01.09 02:10:57  [Servidor]  Thread do servidor / ADVERTIRCausado por: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em java.lang.Thread.run (Thread.java:745) 
01.09 02:10 : 57  Thread do servidor [servidor]  / WARN em net.minecraft.server.v1_14_R1.MinecraftServer.run (MinecraftServer.java:808) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.minecraft.server.v1_14_R1. MinecraftServer.sleepForTick (MinecraftServer.java:874) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll (SourceFile: 99) 
01.09 02:10:57  [Server]  Server thread / WARNem net.minecraft.server.v1_14_R1.MinecraftServer.executeNext (MinecraftServer.java:891) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.MinecraftServer.aW (MinecraftServer.java:898 ) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext (SourceFile: 114) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.minecraft.server .v1_14_R1.IAsyncTaskHandlerReentrant.executeTask (SourceFile: 23) 
01.09 02:10:57  [Servidor]  rosca Servidor / AVISO em net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask (SourceFile: 135) 
01.09 02:10:57  [Servidor] Thread do servidor / WARN em net.minecraft.server.v1_14_R1.TickTask.run (SourceFile: 18) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.PlayerConnectionUtils $$ Lambda $ 3374/1495539834 .run (fonte desconhecida) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda $ 0 (PlayerConnectionUtils.java:13) 
01.09 02:10:57  [Server]  Server thread / WARN em net.minecraft.server.v1_14_R1.PacketPlayInChat.a (PacketPlayInChat.java:1) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.PacketPlayInChat.a (PacketPlayInChat.java : 47) 
01.09 02:10:57 [Servidor]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.PlayerConnection.a (PlayerConnection.java:1516) 
01.09 02:10:57  [Server]  Thread do servidor / WARN em net.minecraft.server.v1_14_R1.PlayerConnection. handleCommand (PlayerConnection.java:1676) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand (CraftServer.java:710) 
01.09 02:10:57  [Server]  Server thread / WARN em org.bukkit.command.SimpleCommandMap.dispatch (SimpleCommandMap.java:149) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em org.bukkit.command.PluginCommand.execute (PluginCommand.java:45) 
01.09 02:10:57 [Servidor]  Thread do servidor / WARN em net.citizensnpcs.Citizens.onCommand (Citizens.java:263) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.citizensnpcs.api.command.CommandManager.executeSafe (CommandManager. java: 183) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.citizensnpcs.api.command.CommandManager.execute (CommandManager.java:87) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.citizensnpcs.api.command.CommandManager.executeMethod (CommandManager.java:155) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em java.lang.reflect.Method.invoke (Method.java:497) 
01.09 02 : 10: 57  [Servidor] Thread do servidor / WARN em sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java 
: 02): 01.09  02:10:57 10:57 Thread do servidor [servidor]  / WARN em sun.reflect.NativeMethodAccessorImpl.invoke0 (método nativo) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.citizensnpcs.commands.NPCCommands.create (NPCCommands.java: 426) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.citizensnpcs.npc.CitizensNPC.spawn (CitizensNPC.java:232) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARNem net.citizensnpcs.npc.AbstractEntityController.spawn (AbstractEntityController.java:41) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity: (HumanController.jpg ) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC. <init> (EntityHumanNPC.java:91) 
01.09 02:10:57 Thread do  servidor [servidor]  / WARN em net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise (EntityHumanNPC.java:292) 
01.09 02:10:57  [Servidor]  Thread do servidor / WARN em net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation. (PlayerNavigation.java:68) 
01.09 02:10:57 [Servidor]  Thread do servidor / WARN java.lang.NoClassDefFoundError: net / minecraft / server / v1_14_R1 / PathDestination 
01.09 02:10:57  [Server]  Thread do servidor / INFO aldsgts emitiu o comando do servidor: / npc create aldsgts

**Comment by mcmonkey4eva** [comment]
Update to 1.14.4.

**Comment by aldsgts** [comment]
if i upgrade i will lose the other plugins from version 1.14.3

**Comment by mcmonkey4eva** [comment]
No you will not. 99.9% of plugins are completely cross-compatible between 1.14.3 and 1.14.4... the few exceptions (like Citizens) have updated immediately.
