### ISSUE TITLE
no feedback

### ISSUE THREAD

**Issue by TechGL** [CitizensDev/Citizens2#1941]
when i write any tipe of command, nothing happened and nothing appear in chat, please fix this

**Comment by mcmonkey4eva** [comment]
- Please follow the issue template. This was displayed to you when you clicked 'new issue'. You can also view it again here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE
- Check your logs for error messages. Something probably has an error. If you find one, post it here.

Reply below with the info requested and we'll reopen the issue.

**Comment by TechGL** [comment]
What? 

Inviato da Posta per Windows 10

Da: mcmonkey4eva
Inviato: lunedì 2 settembre 2019 15:56
A: CitizensDev/Citizens2
Cc: TechGL; Author
Oggetto: Re: [CitizensDev/Citizens2] no feedback (#1941)

Closed #1941.

**Comment by TechGL** [comment]
no, nothing

**Comment by TechGL** [comment]
if you have discord joint to https://discord.gg/g39MBE so i show you

**Comment by mcmonkey4eva** [comment]
Follow the issue template.

If you want Discord support instead, our official Discord is at https://discord.gg/Q6pZGSR

**Comment by TechGL** [comment]
ok, see you in discord right?
