### ISSUE TITLE
Spamming Error in Console on 1.14.4

### ISSUE THREAD

**Issue by MysticCity** [CitizensDev/Citizens2#1942]
15:20:16 [INFO] [Citizens] Exception while updating 119: null.
15:20:16 [WARNING] java.lang.NullPointerException
15:20:16 [WARNING] 	at net.citizensnpcs.trait.LookClose.randomLook(LookClose.java:135)
15:20:17 [WARNING] 	at net.citizensnpcs.trait.LookClose.run(LookClose.java:149)
15:20:17 [WARNING] 	at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
15:20:17 [WARNING] 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:306)
15:20:17 [WARNING] 	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:584)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.World.a(World.java:936)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074)
15:20:17 [WARNING] 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918)
15:20:17 [WARNING] 	at java.lang.Thread.run(Unknown Source)

Just wiith Random Numbers. (7,119,118,6,5,9,183......)

I use Paper171 with Citizens  Citizens-2.0.25-b1745

**Comment by mcmonkey4eva** [comment]
Can you post the section of your `Citizens/saves.yml` for NPC `119`?

It looks like your LookClose settings for that NPC are corrupt (Random look enabled, but pitchRange is null?)

**Comment by MysticCity** [comment]
'119':
    name: Home-Welt-Infos
    uuid: 5a48d424-a389-40e0-a1ae-24673bbd3beb
    traits:
      type: PLAYER
      location:
        world: Home-Welt
        x: '2.5'
        y: '76.0'
        z: '1.5'
        yaw: '147.4628143310547'
        pitch: '0.0'
      spawned: true
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      gravity:
        enabled: false
      equipment:
        hand:
          type: CHEST
          amount: 1
          durability: 0
          mdata: 2
          type_namespace: minecraft
          type_key: chest
        helmet:
          type: LEATHER_HELMET
          amount: 1
          durability: 0
          mdata: 0
          type_namespace: minecraft
          type_key: leather_helmet
        chestplate:
          type: IRON_CHESTPLATE
          amount: 1
          durability: 0
          mdata: 0
          type_namespace: minecraft
          type_key: iron_chestplate
        leggings:
          type: CHAINMAIL_LEGGINGS
          amount: 1
          durability: 0
          mdata: 0
          type_namespace: minecraft
          type_key: chainmail_leggings
        boots:
          type: GOLD_BOOTS
          amount: 1
          durability: 0
          mdata: 0
          type_namespace: minecraft
          type_key: golden_boots
      inventory:
        '0':
          type_namespace: minecraft
          type_key: chest
          amount: 1
          durability: 0
          mdata: 2
        '36':
          type_namespace: minecraft
          type_key: golden_boots
          amount: 1
          durability: 0
          mdata: 0
        '37':
          type_namespace: minecraft
          type_key: chainmail_leggings
          amount: 1
          durability: 0
          mdata: 0
        '38':
          type_namespace: minecraft
          type_key: iron_chestplate
          amount: 1
          durability: 0
          mdata: 0
        '39':
          type_namespace: minecraft
          type_key: leather_helmet
          amount: 1
          durability: 0
          mdata: 0
      owner:
        owner: server
        uuid: ''
    traitnames: type,mounttrait,spawned,lookclose,owner,inventory,gravity,equipment,location
    navigator:
      speedmodifier: '1.0'
      avoidwater: false
      usedefaultstuckaction: true

**Comment by mcmonkey4eva** [comment]
I'm... confused how that error could possibly have come from that NPC. It doesn't look to have `randomLook` enabled. It doesn't even appear to have that section of trait data persisted at all (is that maybe an older copy of your saves.yml?)

**Comment by MysticCity** [comment]
My old server is on 1.13.2 and work
but now i update to 1.14.4

(just replace the old jar with the new one)

and get this error

**Comment by fullwall** [comment]
What are your settings?

**Comment by MysticCity** [comment]
https://pastebin.com/85LQPQRu

**Comment by mcmonkey4eva** [comment]
I again think that's an older copy, not a current one. That's missing relevant settings entirely, that shouldn't be missing if it was a current copy.

**Comment by MysticCity** [comment]
Yes this is from my 1.13.2 server that i use at this moment on the 1.13.2 server

but i try to update to 1.14.4

and on 1.14.4 i get this error now.... what must i do to prefent this spamming error

**Comment by mcmonkey4eva** [comment]
Post the config and saves.yml _from the 1.14.4 server that has the error_

**Comment by MysticCity** [comment]
saves: https://pastebin.com/w5cGSC3H
config: https://pastebin.com/NJnbjPvG

**Comment by mcmonkey4eva** [comment]
`       random-look-enabled: true`
why did you set that to `true` in the config? (It defaults to false)

**Comment by MysticCity** [comment]
because i think this is that npc dont look in 1 direction.... thay look random in all directions or not?

**Comment by mcmonkey4eva** [comment]
Sorta, yes... but... why did you enable that globally, as opposed to on a per-NPC basis? You probably don't want that on most NPCs.

**Comment by MysticCity** [comment]
why for all per command if i can use an option that the plugin have ^^

this is easy and apply for all npcs not only 1 thats why i use this option

**Comment by mcmonkey4eva** [comment]
This may be fixed by https://github.com/CitizensDev/CitizensAPI/commit/74f8394bd199ac96a3f2f173b7aa61c4607cfcce (in Citizens build 1746+).

You may or may not need to regenerate/fix all affected NPCs for the fix to apply (or reload from the original 1.13 saves file).

**Comment by MysticCity** [comment]
Okay i dl the last build and start the server and get the error... so what i need to do now?

place all npc`s new ?

**Comment by MysticCity** [comment]
any news?

**Comment by MysticCity** [comment]
any news ???

Becaus i need only this plugin to update my server to 1.14.4 ^^

**Comment by fullwall** [comment]
Can you post your saves.yml? Latest one

**Comment by MysticCity** [comment]
> 
> 
> saves: https://pastebin.com/w5cGSC3H
> config: https://pastebin.com/NJnbjPvG

**Comment by mcmonkey4eva** [comment]
That is not a current copy.

**Comment by MysticCity** [comment]
this is the last one i have

**Comment by mcmonkey4eva** [comment]
That is from september 6th, prior to the possible-fix commit.

**Comment by MysticCity** [comment]
nope not fixes

https://pastebin.com/pZRcfZXs

**Comment by MysticCity** [comment]
any news?

**Comment by fullwall** [comment]
Download the latest build

**Comment by MysticCity** [comment]
I use b1755 now and get the same errors

**Comment by fullwall** [comment]
What about 1756

**Comment by MysticCity** [comment]
nope same error

**Comment by fullwall** [comment]
Can you pastebin the error again?

**Comment by MysticCity** [comment]
https://pastebin.com/ANTdJ9ic

**Comment by fullwall** [comment]
I have pushed a new build

**Comment by MysticCity** [comment]
Okay i think now all work fine thx
