### ISSUE TITLE
Npc's despawn right away

### ISSUE THREAD

**Issue by GamemodeSurvival** [CitizensDev/Citizens2#1943]
The output of command `/version` on my server is: **Beer Spigot 1.2**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHPT**

**Comment by mcmonkey4eva** [comment]
- Post actual command output for the version commands, not bad retypings
- Describe your actual issue
- Run a sane server version like Spigot or Paper, not whatever that is

**Comment by GamemodeSurvival** [comment]
> * Post actual command output for the version commands, not bad retypings
> * Describe your actual issue
> * Run a sane server version like Spigot or Paper, not whatever that is

Wasnt a bad typing. Its 1.2. Thats the version when I do /ver i typed it exactly how it said. Also i fixed it.

**Comment by DelKatey** [comment]
He's referring to whatever the heck "Beer Spigot" is

**Comment by mcmonkey4eva** [comment]
You retyped it. That's wrong by default. Copy/paste or screenshot only. Aside from "beer spigot" (???), your Citizens version isn't a valid version, and the invalid version contains a typo too: `SNAPSHPT`

**Comment by Ph4i1ur3** [comment]
For context: BeerSpigot is a paper fork iirc, but it focuses on factions gameplay (tnt cannon optimization)
