### ISSUE TITLE
NPC not loading when teleporting it from far away using /npc tphere

### ISSUE THREAD

**Issue by Leonardo-Fiori** [CitizensDev/Citizens2#1944]
Description: when teleporting a citizen from a location far away using /npc tphere the npc will not be visible until i disconnect and reconnect to the server. If i teleport to the npc using /npc tp while he is not visible, it teleports me to his new correct location, the one after i did /npc here. So coords are updated but the npc does not get loaded.

The output of command `/version` on my server is: This server is running Paper version git-Paper-176 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is:  Citizens version 2.0.25-SNAPSHOT (build 1744)

Server log is not needed, there are no errors. The npc just does not appear when teleported from far away (more than the server's view distance).

I also tried to /forceload the chunks where the npc is standing in before doing /npc tphere, but the bug still persists..

I am teleporting the npc also using skript-npc, an additional module for skript. The same problem happens.

**Comment by Ph4i1ur3** [comment]
Likely related to #1822
