### ISSUE TITLE
[Bug] Npc doesn't sneak with the command /npc sneak

### ISSUE THREAD

**Issue by Tiplish** [CitizensDev/Citizens2#1946]
Hi !
I'm using :
- Spigot version 1.14.4-R0.1-SNAPSHOT
- Citizens v2.0.25-SNAPSHOT (build 1732)

When i use the command /npc sneak, the npc doesn't make the animation. I could switch between /npc stand and /npc sneak, the NPC stay up :( 

The commande /npc sit work correctly. 

Any clue ?

Thanks

**Comment by Ph4i1ur3** [comment]
This is actually a Denizen issue, as Denizen adds the relevent trait/command. Please open an issue here: https://github.com/DenizenScript/Denizen

**Comment by mcmonkey4eva** [comment]
The Denizen trait in turn just calls a Spigot method, which might be the broken part. But yeah, open at Denizen
