### ISSUE TITLE
Bug with NPC Armorstands head skins

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1948]
When placing playerheads that have skins onto an armorstand after **one** or can be up to **several** restarts the head texture reverts to a Steve/Alex skin. The conditions I have for the armorstand NPCs are visible false and small true

**config.yml**
https://pastebin.com/SidEhjFc

**saves.yml** (affected NPCs)
https://pastebin.com/edDvEvMi

![image](https://user-images.githubusercontent.com/37608633/64833918-efad8480-d61e-11e9-816c-423c49106e62.png)

The output of command `/version` on my server is: ** git-Paper-645 (MC: 1.13.2)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1746)**

**Comment by mcmonkey4eva** [comment]
The NPC's whose heads have lost their textures... still clearly have the texture in the `saves.yml` copy. That is: they're not lost from Citizens, just not being consistently loaded by your client. This is not likely to be a Citizens issue, much more likely a general minecraft player head issue (try some non-NPC armor stands).

**Comment by axemwa** [comment]
Hmm weird its true yeah the data is still in the yml folder but head textures dont show at all anymore no matter how many times I restart the server or which part of the body/armorstand the head is on. Non npc armor stands work fine every time guess ill just use them from now on
