### ISSUE TITLE
NPC Player glowing

### ISSUE THREAD

**Issue by ImWiiizaaard** [CitizensDev/Citizens2#1949]
Hello !

For months, I try to make a npc glowing with the command `/npc glowing --color aqua` (or other color), and no change appears... The glowing is true, he is white but he don't change to aqua color or an other...

Screenshot if you want : 
**https://imgur.com/smyRht9** (the message)
**https://imgur.com/G9y72xS** (the white color)

I think it's bug because a lot of peoples has the same problem.

Server: **1.14.4 Spigot**
Citizens: **2.0.25-SNAPSHOT (build 1751)**

(sorry for my bad english, im french)

**Comment by mcmonkey4eva** [comment]
Please follow the plugin conflict testing steps listed here: https://wiki.citizensnpcs.co/Plugin_Conflict

Sorry for not replying sooner, somehow missed this

**Comment by ImWiiizaaard** [comment]
Okay, i follow the testings steps.

I tried to take all plugins, make a local server and test 1 by 1 each plugins and i detucted it's Denizen.
I don't know why but without the plugin, the glowing color works perfectly.

**Comment by mcmonkey4eva** [comment]
Do you perhaps have some scoreboard-related scripts in use in Denizen?

**Comment by mcmonkey4eva** [comment]
I tested on a server running Spigot `git-Spigot-94af569-d6b3edd (MC: 1.14.4)`+Citizens `1762`+Denizen `1689-REL`, and `/npc glowing --color aqua` works exactly as expected.
So if the conflict is indeed Denizen-related, it's definitely from some form of script and not Denizen itself.

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply. Please perform testing for related scripts.
We can reopen if an issue with Citizens is found, or you can open a Denizen issue if you believe Denizen is at fault (though as noted... Denizen on its own is almost certainly not).

For more help related to Denizen, join the Discord https://discord.gg/Q6pZGSR
