### ISSUE TITLE
Citizens Traits not working

### ISSUE THREAD

**Issue by salvatraversone** [CitizensDev/Citizens2#195]
Whenever I try giving my citizens a trait I do /trait sentry but then there's a message saying Error Trait not found.

Please help.

**Comment by mcmonkey4eva** [comment]
Update Sentry then.

**Comment by salvatraversone** [comment]
I did that but now my console goes crazy when I try to add the sentry trait.

**Comment by mcmonkey4eva** [comment]
What does it say?!

**Comment by salvatraversone** [comment]
Please report this error: [see consol]
java.NoClassDefFoundError: net/minecraft/server/v1_8_R1/World

**Comment by mcmonkey4eva** [comment]
You downloaded the wrong version of Sentry. Find the correct one on the wiki.

**Comment by salvatraversone** [comment]
I dont really know where it is in the wiki

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Sentry#Updates

**Comment by salvatraversone** [comment]
Dies it afecta if i have a 1.7.9 server?

**Comment by salvatraversone** [comment]
*does it affect

**Comment by mcmonkey4eva** [comment]
Just get the appropriate Sentry version for 1.7.9

**Comment by salvatraversone** [comment]
Now when I do /trait sentry it says removed sentry successfully. But when I do it again the same error message appears. And when I do it again removed sentry successfully appears again. And so on and so on.

**Comment by mcmonkey4eva** [comment]
GET.
THE.
CORRECT.
SENTRY.
VERSION.

**Comment by salvatraversone** [comment]
I went to the wiki and got the 1.7.9 one and it still dosent work, could you possibly give me the link of the download?

**Comment by mcmonkey4eva** [comment]
http://ci.citizensnpcs.co/job/Sentry/12/artifact/target/sentry.jar

**Comment by mcmonkey4eva** [comment]
If that errors, try http://ci.citizensnpcs.co/job/Sentry/13/artifact/target/sentry.jar
