### ISSUE TITLE
Color-scheme config option isn't used in all outputs

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1952]
Please add configuration for console/log color scheme. Current red highlight does not read well on my dark blue console background.

The output of command `/version` on my server is:  **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
```
>version
[06:21:43] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[06:21:43] [Server thread/INFO]: You are running the latest version
>version citizens
[06:21:46] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1758)
[06:21:46] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[06:21:46] [Server thread/INFO]: Author: fullwall
[06:21:46] [Server thread/INFO]: CitizensCMD version 2.3.2
[06:21:46] [Server thread/INFO]: Author: Mateus Moreira
```

**Comment by mcmonkey4eva** [comment]
Citizens almost never outputs *anything* to console logs... the few times it does aren't colored. What are you referring to here?

EDIT: BTW, there's a native Citizens feature to add commands to NPCs now.

**Comment by SlimeDog** [comment]
At the console:
**citizens help
npc help ...**

**Comment by SlimeDog** [comment]
I tried resetting the color-scheme and **citizens reload**. Perhaps I have to reboot?

**Comment by mcmonkey4eva** [comment]
So that'd be command output, which is the config setting fullwall mentioned above.

**Comment by SlimeDog** [comment]
```
general:
  color-scheme:
    message-highlight: ''
    message: ''
```
![Screen Shot 2019-09-24 at 6 44 27 AM](https://user-images.githubusercontent.com/17748923/65516997-df0ad300-de96-11e9-8b4e-f648ab0886d1.png)

**Comment by SlimeDog** [comment]
Additional: It would be nice if **npc help** were sorted alphabetically, and at the console printed the complete list.

**Comment by fullwall** [comment]
I added some config to change the error colour (which is now used in the help commands). Do you want a specific format setting for the help commands or is that OK?

**Comment by SlimeDog** [comment]
My goal is that in-game and at the console, I have the option for all text produced by the plugin to be whatever color(s) I choose. In my case, that is white, across the board. Others may have different desires, like separating the "lead" text and the following text on each line, but I don't care about that personally.

**Comment by mcmonkey4eva** [comment]
In that case: the new config (committed at time of fullwall's last comment) suffices for you?

**Comment by SlimeDog** [comment]
Build 1759 works perfectly for me. Thank you.
