### ISSUE TITLE
TPS issues, floating items issue conflict with Ultimate Shops plugin ?

### ISSUE THREAD

**Issue by augstb** [CitizensDev/Citizens2#1953]
After a certain amount of time, my server gets to lag. I pasted a /timings and I found that two plugins could cause this issue :
- Citizens
- UtlimateShops (which is a plugin to make shops with floating items on top of slabs)

When I remove one of the two plugins, the problem is solved, and there is absolutely no lag at all. This is why I presmue the lag is due to the interaction of these two plugins. I contacted the developer of the UltimateShops plugin that anwsered me :

> Check for any plugins that may interfere with the display item spawning system. On my test server with no other plugins things work as intended.
(***ThirtyVirus***)

On the timings report, we can sort by plugins and here is the report, with citizens on top.
![Timings01](https://image.noelshack.com/fichiers/2019/39/7/1569759081-01.png)

On the other hand, in world entities, we can see that there is a lot of entities in a certain part of the map (exactly where I put floating shops and NPCs).
![Timings02](https://image.noelshack.com/fichiers/2019/39/7/1569759284-02.png)
We can also note that when I clean the floating entities, there is no lag anymore.

There is the link of my timings report so you can investigate by yourself :
[Timings Report Link](https://timings.aikar.co/?id=9a2dd9161e1149ff86f96d947748d182#plugins)

Can you help me to solve this problem please ? Thanks a lot !

The output of command `/version` on my server is: Paper(194) 1.14.4-R0.1-SNAPSHOT
The output of command `/version citizens` on my server is: Citizens v2.0.25-SNAPSHOT (build 1759)

**Comment by calico-kid** [comment]
Timings doesn’t give proper info please use warmroast to get more accurate info. Also dropped entities and entities in general are a huge issue on 1.14 we see a lot of ppl complaining about it.

**Comment by mcmonkey4eva** [comment]
If you want a server that doesn't lag, run 1.13.2 or 1.12.2
1.14.x can and will always lag due to being just fundamentally broken as a minecraft version.
