### ISSUE TITLE
Please add a /npc cat -L Option

### ISSUE THREAD

**Issue by Gh0stKitty** [CitizensDev/Citizens2#1954]
- Cats can now Lay down as of 1.14+ I'd love an option for it!

![Image example](https://media.discordapp.net/attachments/315625512753954816/629139736795283477/Z.png)

- 1.14+ versions

**Comment by mcmonkey4eva** [comment]
Added in build 1779+ by https://github.com/CitizensDev/Citizens2/commit/d0dcb235b3282f943e8079fc7eca551adcad1086 as `/npc cat -l`
