### ISSUE TITLE
Npc pitching / head movement error

### ISSUE THREAD

**Issue by ManO1234148** [CitizensDev/Citizens2#1955]
I am running version 1.12.2, spigot. Citizens and Sentinel are running. The bug is citizens with the sentinel trait that have crackshot weapons or other weapons are unable to pitch up / look up. For this reason they are unable to target enemies above them, very frustrating, please fix.

To replicate, you spawn an npc, give it trait sentinel, equip on it any weapon, make it target players, and the fly above it. Voila! You have reproduced the bug

![2019-10-05_18 43 30](https://user-images.githubusercontent.com/29739282/66263840-62d59100-e7ae-11e9-87cc-4d07222f6b18.png)
![2019-10-05_18 43 34](https://user-images.githubusercontent.com/29739282/66263843-679a4500-e7ae-11e9-820a-2dfce269bb58.png)
![2019-10-05_18 43 44](https://user-images.githubusercontent.com/29739282/66263845-6a953580-e7ae-11e9-87e6-8675026038df.png)

**Comment by mcmonkey4eva** [comment]
The underlying issue being that on 1.12.2 specifically, NPC heads don't pitch properly (This is also noticeable with things like lookclose, where it will jankily pitch a bit but then snap back down).
This issue is not present when testing on 1.14.4
