### ISSUE TITLE
1.14.4. Citizens 2 Performance Issues

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#1956]
Versions:
This server is running Paper version git-Paper-210 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Citzens: Citizens (2.0.25-SNAPSHOT (build 1762) (save file: https://pastebin.com/kZ4kKuTF )

After upgrading our paper spigot server to 1.14.4 we expect massive performance issue because of Citizens2. We tested this and it took us 1 day to find out that the issue is Citizens.

To see what happens you need to turn on debug (/debug start) on the server. Then you see something like this:
https://hastebin.com/mabezimuga.shell

The more NPCs you have the more debug messages are spammed into console and the higher the TPS drop is.

I hope this is enough information for you to get this issue fixed. If not, let me know, I can provide further information.

**Comment by mcmonkey4eva** [comment]
Minecraft 1.14.x itself has major issues, mainly related to performance but also some related to data stability / crashing / etc. Citizens is not the cause but rather a victim of these issues.

If you want a stable server, use 1.13.2 or 1.12.2.

To best track down performance issues, you need a Java Profiler like [Spark](https://www.spigotmc.org/resources/spark.57242/) to get a proper analysis.
