### ISSUE TITLE
PLEASE UPGRADE TO 1.14 PLEASE

### ISSUE THREAD

**Issue by Notpotat** [CitizensDev/Citizens2#1957]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by ImDatIllusion** [comment]
Drunk posting should not be allowed

**Comment by mergu** [comment]
1.14.4 has been supported basically since it came out. https://ci.citizensnpcs.co/job/Citizens2/
