### ISSUE TITLE
Citizens not working on 1.14.4 Spigot server

### ISSUE THREAD

**Issue by jancito81** [CitizensDev/Citizens2#1958]
SERVER LOG --> https://mclo.gs/F7PLepY

I am having issues with using Citizens (2) on my 1.14.4 server. Any command at all that runs through Citizens returns an "An internal error occurred while attempting to perform this command." message. Any advice? If this build of Citizens is not compatible with 1.14.4, I kindly request a version.
The output of command `/version` on my server is: 1.14.4-R10.1
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1605)

**Comment by SXRWahrheit** [comment]
You are approximately 100 builds of Citizens behind, please update: https://ci.citizensnpcs.co/job/Citizens2/

You also did not include the full output of the version command - it should say that Spigot is up to date or X version(s) behind.

**Comment by SXRWahrheit** [comment]
Also:

```
[17:55:49] [Server thread/INFO]: _j81 issued server command: /reload
[17:55:49] [Server thread/INFO]: _j81: Please note that this command is not supported and may cause issues when using some plugins.
[17:55:49] [Server thread/INFO]: _j81: If you encounter any issues please use the /stop command to restart your server.
```

Do not use the reload command to load plugins. Fully stop and start the server. You should *never* use that command.

**Comment by jancito81** [comment]
Sorry. The output said I am running the latest version. Also, I am using an Aternos server. That is the only version of Citizens available is that version. I will contact their support.
