### ISSUE TITLE
API despawning issues

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#1959]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
This server is running Paper version git-Paper-214 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
Citizens version 2.0.25-SNAPSHOT (build 1762)

I've recently gotten into the API of Citizens and have been actively talking with Matt (owner of CitizensCMD and TravelingCitizens) and I've found that firstly doing any despawning of NPCs on plugin startup after world load and Citizens load etc do not despawn the NPC. You can get the NPC it self but not actually despawn it.

And secondly, the biggest issue is that if you do
`npc.despawn();`
or with any DespawnReason the NPC will despawn but their state will NOT be saved in the saves.yml so on the next startup it'll respawn the NPC since in their traits it has "spawned: true" not false like it should be, along with this doing /npc select then /npc despawn works perfectly fine and it saves the state but not using the API.

**Comment by fullwall** [comment]
Is that player NPCs for the first point? 
Second point: yes, there's the Spawned trait for controlling that I guess maybe there should be some DespawnReason checking for this?

**Comment by mcmonkey4eva** [comment]
It sounds like the first is caused by the second? ie despawn isn't working at load time because it isn't even spawned in the first place (NPC's don't spawn until a player is nearby to cause chunk+entity loading).

As I said on Discord where you originally asked... when in doubt, check source code: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L511-L520

**Comment by HexedHero** [comment]
I already checked the source when I posted this and I did every single despawn reason but it was never saved.

**Comment by mcmonkey4eva** [comment]
The answer to your question is 3rd to last highlighted line in the link.

**Comment by HexedHero** [comment]
Oh, I didn't see that. Thanks.
