### ISSUE TITLE
Skins not loading

### ISSUE THREAD

**Issue by jsnbrown1989** [CitizensDev/Citizens2#196]
We are running Minecraft 1.7.9 with cauldron 1.1207.01.195 and Citizens 289 found here: http://cauldron.minecraftforge.net/threads/citizens-2-for-cauldron-1-7-10-released.289/

We have the name of the player set to a player on the server's ign with correct capitalization and such and no luck. 

When I originally mentioned this in a different ticket ( #185  )I was recommended to visit ticket #159 but it seems totally unrelated as this completely isn't loading from the start. 

There are no errors in the console. In fact, there is nothing at all in the console to take not of. 

We are hoping on opening up our server tomorrow. I would love it to have these skins working but due to how late in the game I am making this ticket, we may have to proceed with Steve skins. 

Is there any sort of miracle trick I can try to get this to work?

**Comment by calico-kid** [comment]
have you maybe attempted /citizens reload ? if not try it and see if that changes anything

**Comment by mcmonkey4eva** [comment]
There's only so much support we can provide for outdated and unofficial builds of our plugin...

**Comment by godleydemon** [comment]
I seem to be able to get skins to load by assigning the skin then walking far enough away that the NPC is out of rendering distance. Once I come back, the NPC has it's skin :p lol

**Comment by jsnbrown1989** [comment]
I have tried /citizens reload I have tried walking away, doing /spawn, logging off, restarting our server and manually adding the skin via the /citizens skin _____ (I believe) command. 

Mcmonkey4evs, if you do not mind me asking, why did you recommend me use that custom plugin if you wouldn't stand behind it? You said it was a custom plugin but I figured it was one a developer of this plugin made for cauldron. I appreciate the support before but it I feel that it didn't fully solve my problem.. Kinda like Microsoft giving me an unauthorized version of Windows that will expire without telling me as a solution. 

So, does citizens just not work for Cauldron? I know of a couple other servers that use cauldron and have it running on them with skins and the whole 9 yards.. I would contact them but I don't know the owners well.

**Comment by mcmonkey4eva** [comment]
Citizens does not work for cauldron. I directed towards an unofficial build that claimed support, as that is better than anything we can offer you here.

We try to offer support for unofficial builds but there's only so much we can do for code we don't have... you can contact bloodmc (the author of the unofficial build) if it's not functioning as expected for your best hope of support.

I'm not trying to turn you away, I'm just being honest about what we're capable of helping with here.

**Comment by jsnbrown1989** [comment]
Ehh, as you mentioned, it is outdated and it looks like he is helping with Sponge which is the priority. I doubt I will get any help from that ave. 

Well, seeing that google never yielded results I guess I shall have to put npc's on hold. 

Thank you anyhow!
