### ISSUE TITLE
Very laggy

### ISSUE THREAD

**Issue by Littledodger** [CitizensDev/Citizens2#1961]
First of all, apologies for my language, I'm not english !

Our server makes a lot of lags when citizens is on.
You can see the timmings report at the following link : 
https://timings.aikar.co/?id=257a0c1a49fd4d0eb57cb45f2d2e3c78

We have 12 pages of NPC's name when I ask /NPC list
saves.yml : 
https://pastebin.com/JJ0zfjNK
Timings :
https://timings.aikar.co/?id=257a0c1a49fd4d0eb57cb45f2d2e3c78

The output of command `/version` on my server is: 
This server is running Paper version git-Paper-207 'MC:1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Previous version: git-Paper-199 (MC: 1.14.4)
You are 7 version(s) behind

The output of command `/version citizens` on my server is: 
Citizens version 2.0.25-SNAPSHOT (build 1759)

Thanks in advance

**Comment by mcmonkey4eva** [comment]
Refer to #1956 or #1930 or #1927 or #1918 or #1881 or #1855 or #1848
