### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by LikeManTV** [CitizensDev/Citizens2#1962]
**Hello, I have a problem with loading the Citizens plugin. When I start the server, the error pops up in console saying:** _"[Citizens] v2.0.24-SNAPSHOT (build 1605) is not compatible with Minecraft v1_13_R1 - try upgrading or downgrading Citizens. Disabling."_

**Console:** https://pastebin.com/xvm0U1Yj - **Config:** https://pastebin.com/EiD22WN0

**The output of command `/version` on my server is:** _"This game is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPCHOT)"_

**The output of command `/version citizens` on my server is:** _"2.0.24-SNAPSCHOT (build 1605)"_

**Comment by mcmonkey4eva** [comment]
Update to latest Citizens: https://ci.citizensnpcs.co/job/Citizens2/
And update Spigot to latest 1.13.2 (you have 1.13 flat, which is unsupported)
