### ISSUE TITLE
NPC Despawn on Worldchange

### ISSUE THREAD

**Issue by DevJoey** [CitizensDev/Citizens2#1963]
Config: https://hasteb.in/obikenax.yaml
Spigot.yml: https://hasteb.in/uzotuxop.yaml
Bukkit.yml: https://hasteb.in/vibiboci.yaml
Saves.yml: https://hasteb.in/afufujid.yaml

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[15:48:40 INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
The error is also on 1.14.4 newest Spigot build.
The output of command `/version citizens` on my server is: [15:52:49 INFO]: Citizens version 2.0.22-SNAPSHOT (build 1547)
[15:52:49 INFO]: Website: http://www.citizensnpcs.co
[15:52:49 INFO]: Authors: aPunch and fullwall

And on the 1.14.4 Server: [15:53:43 INFO]: Citizens version 2.0.25-SNAPSHOT (build 1732)
[15:53:43 INFO]: Website: http://www.citizensnpcs.co
[15:53:43 INFO]: Author: fullwall

Description:
If i create a NPC and change the world. the npc is despawned. i can spawn him agian with /npc spawn. This is only on npc that are MOBS. Player npc are not affected.

**Comment by mcmonkey4eva** [comment]
You're running a pretty old build of Citizens, please update both of your servers to latest: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by DevJoey** [comment]
Yeah. But i need it for 1.12.2 and the newest 1.12.2 is on Spigot  2.0.22 (1.12.2 BETA #1)

**Comment by DevJoey** [comment]
And this version i already running. And the 1.14.4 builds not working on a 1.12.2 server.

**Comment by mcmonkey4eva** [comment]
The latest build of Citizens works for 1.12.2

The version of Citizens you have on your 1.14.4 server is not the latest.

**Comment by DevJoey** [comment]
Ok also i can use the newest 1.14.4 build on spigot for 1.12 2 is that correct?

**Comment by mcmonkey4eva** [comment]
the latest Citizens build, that I linked above, works on all minecraft versions

**Comment by DevJoey** [comment]
Thanks

**Comment by DevJoey** [comment]
#Fixed
