### ISSUE TITLE
1.14 Wither trait broken

### ISSUE THREAD

**Issue by orblazer** [CitizensDev/Citizens2#1965]
Hello,
I have try to make an charged wither boss with API but this have not correct behaviour.

The API code used :
```java
npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.WITHER, name);
npc.getTrait(WitherTrait.class).setCharged(true);
npc.spawn(config.location);
```

The output of command `/version` on my server is: **git-Paper-221 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1768)**

### The current behaviour
This use charge of trident instead of charge of wither.
![2019-10-24 19-01-43](https://user-images.githubusercontent.com/1344792/67508838-12a56c80-f692-11e9-951c-3356e835ec95.gif)

### The waiting behaviour
![2019-10-24_19 19 15](https://user-images.githubusercontent.com/1344792/67509472-619fd180-f693-11e9-9b4a-7cf703fc4613.png)

Thanks.

**Comment by mcmonkey4eva** [comment]
While this is indeed clearly broken, might I just mention that a trident-charged spinning wither is a far more intimidating boss than a blueish one.

**Comment by mcmonkey4eva** [comment]
Fixed in build 1779+ by https://github.com/CitizensDev/Citizens2/commit/d0dcb235b3282f943e8079fc7eca551adcad1086
