### ISSUE TITLE
Wither bossbar message blinking

### ISSUE THREAD

**Issue by Nety01** [CitizensDev/Citizens2#1967]
The output of command `/version` on my server is: **Paper 1.13.2 build 652**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1731)**

Issue:
When NPC type Wither has nametag visibility DISABLED then the bossbar message is blinking

Video: 
https://imgur.com/GwaaNyR

**Comment by fullwall** [comment]
So you want it to always be disabled right?

**Comment by Nety01** [comment]
I want to have nametag visibility disabled with bossbar message enabled. So the name above wither is not visible, but the message on top of the screen is VISIBLE. But my problem is that the bossbar message is blinking like it's on the video.

**Comment by mcmonkey4eva** [comment]
Issue refused due to being posted by a cracked user.
