### ISSUE TITLE
NPC sleep does not work

### ISSUE THREAD

**Issue by pgmann** [CitizensDev/Citizens2#1969]
The output of `/version` on my server is:
```
This server is running Paper version git-Paper-214 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

The output of `/version citizens` and `/version denizen` on my server is:
```
Denizen version 1.1.0-SNAPSHOT (build 1688-REL)
Citizens version 2.0.25-SNAPSHOT (build 1770)
```

The issue is:

Originally opened this in the Denien repo (DenizenScript/Denizen#2064), was told this is caused by an issue in Citizens.

Create an NPC on top of a bed. Run the `/npc sleep` command. The NPC remains standing. Note re-running the sleep command reports that the NPC is already sleeping although it is still shown standing in-game.

(Also, at least some of the location checking code works as running `/npc sleep` with no bed at the NPC's location will throw an exception as the bed direction cannot be determined. Ideally this should be handled rather than throwing an exception.)

**Comment by pgmann** [comment]
Further info on this I've discovered from testing: the `/npc sleep` command works the first time you run it after restarting the server. It does not work after this. So doing `/npc sleep`, `/npc wakeup`, `/npc sleep` would reproduce this.

**Comment by pgmann** [comment]
Also the head tracking (when I have `/npc look` turned on) tracks where it should look if it were still sleeping even after it wakes up.

**Comment by pgmann** [comment]
Sorry for the spam - after relogging the NPC is then shown in a sleeping state even though it is 'awake' according to `/npc wakeup`.

**Comment by mcmonkey4eva** [comment]
I submitted a PR to fix this issue (and basically any other sleeping issues): https://github.com/CitizensDev/Citizens2/pull/2029
