### ISSUE TITLE
the npc of my self made trait disappear after a while

### ISSUE THREAD

**Issue by Krglok** [CitizensDev/Citizens2#197]
citizens version 2.0.14-SNAPSHOT (build 1195)
1.8-R0.1-SNAPSHOT)

I make a trait that auto generate npc with my own trait.

i give them command like /waypoint provider wander  and all will done correct.
After a while the npc are not visible. There is no error message, no exception. i can move to them i can move them to me, but they are not visible.

I cant find any error :(

**Comment by Krglok** [comment]
Oh, aehh...  citizens version 2.0.14-SNAPSHOT (build 1195)
Server Spigot 1.8-R0.1-SNAPSHOT

**Comment by mcmonkey4eva** [comment]
Update to latest dev build.

**Comment by Krglok** [comment]
i followed the test system for 5 hours and the problem dont show again .
I think its solved. Unknown by what. I think it was i error in my trait.
Thx for your support.
