### ISSUE TITLE
Purchased the Citizens2 plugin but still displayed the purchase options

### ISSUE THREAD

**Issue by BigBigHugo** [CitizensDev/Citizens2#1970]
I bought Citizens2, but it also shows that I want to continue to buy it

**Comment by mcmonkey4eva** [comment]
Ask the Spigot staff or DM fullwall on the Spigot forums.
(That's not a Citizens issue, that's a Spigot forum issue)

Also if you for some reason didn't read the Citizens readme before buying, Citizens is free and you can download it here https://ci.citizensnpcs.co/job/Citizens2/
