### ISSUE TITLE
Feature Request: Tab Completion

### ISSUE THREAD

**Issue by VergilPrime** [CitizensDev/Citizens2#1971]
Feature Request:
Add tab completion for subcommands.

**Comment by mcmonkey4eva** [comment]
This would be a pretty nice feature to have.
Just completing the subcommands would be an excellent start, though ideally it would also extend to supporting the arguments to those as well (to whichever degree reasonably possible).

Relevant JavaDocs: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/command/TabCompleter.html

**Comment by mcmonkey4eva** [comment]
The basicmost form of this (the subcommand names) has been added to new dev builds (1771) by fullwall via
https://github.com/CitizensDev/CitizensAPI/commit/b5f2b51e67ba4e3f814177f327eebb477edef783 and https://github.com/CitizensDev/Citizens2/commit/727d1508e9f8597ab8f8b91e840fd862659cbf2f
:D 

That effectively resolves this issue, though I'm hopeful for a future implementation of additional completion for the options within each subcommand.
