### ISSUE TITLE
Rain Bug --type villager

### ISSUE THREAD

**Issue by dwa1275** [CitizensDev/Citizens2#1974]
after testing over and over again, removing all plugins but citizens I found that I had the same issue. try to reproduce. create an npc with this command. /npc create npc1 --type villager, after you do that just make it rain, fly up a little, and back up to make the npc disappear, then at running speed, I think /speed 2 move toward the npc villager. I notice that this does not happen to a player npc. yes, other player can see the issue as well

--type villager NPC's
out of box config.
NPC's jump into the air when it rains. that's about it. when raining, and you approach the NPC's they appear to jump real high, then fall from the sky. ONLY when it rains.

The output of command `/version` on my server is: **(git-Spigot-56f8471-7554e08 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **(Citizens v2.0.25-SNAPSHOT (build 1776))**

**Comment by mcmonkey4eva** [comment]
This is an incredibly odd and specific issue.

I've replicated it locally, and confirmed it's specific to the villager entity type (doesn't apply even to `pillagers` for example) and specific to rain (doesn't happen without rain).

**Comment by dwa1275** [comment]
types  that are effected by the rain.

GHAST
TRIDENT
SHULKER_BULLET
ENDER_DRAGON
ENDER_DRAGON
ENDER_DRAGON
VEX
PHANTOM
VILLAGER

**Comment by dwa1275** [comment]
i decided to really go threw the plugin and see if there was any other issue, some of the tyes like thrown experience, potion bottle, and types of minecarts dident appear to not work, the npc is created but no visual. theres a few things I dident create such as fireball, arrow, dragon fireball, fishing hook, llama spit, primed tnt, tnt.

I remember an issue like this from a long time ago relating an endless falling block when it rained. its been so long the old old, old post is not there anymore, otherwise id reference it as I remember it being a simple fix, but like I said, a long time ago, I can hardly remember all about it.

**Comment by mcmonkey4eva** [comment]
Reference GIF: https://i.alexgoodwin.media/i/misc/267669.gif

It seems to not be just from entering and spawning the villager.
It looks like, for as long as you are _near_ the villager NPC, in the rain, but past a certain distance, the NPC will just continually jump up and down until you either get far enough to despawn it or close enough that it stops.
