### ISSUE TITLE
Combat - Passive/follow -p

### ISSUE THREAD

**Issue by boredofnames** [CitizensDev/Citizens2#1975]
The output of command `/version` on my server is: **Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1776)**

Setting passive to false doesn't seem remove passive from the npc.
Using follow (user) -p returns unknown argument p

**Comment by mcmonkey4eva** [comment]
Looks like a simple case of the `flags` value wasn't listed in the command registration https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L554-L562

**Comment by mcmonkey4eva** [comment]
Should be fixed in the new build (1777+) at ci.citizensnpcs.co/job/Citizens2/
via https://github.com/CitizensDev/Citizens2/commit/94733ddb8198ed27cf6834f211daccb36d8781f0
