### ISSUE TITLE
Add command for Mushroom Brown

### ISSUE THREAD

**Issue by alexdragneel** [CitizensDev/Citizens2#1976]
Hello,

Juste a new idea that after researchs missing, could you please create a command to have a npc mushroom brown ?

Thank you for your work :)

**Comment by mcmonkey4eva** [comment]
That'd be for this MushroomCow Variant option: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/MushroomCow.Variant.html

**Comment by fullwall** [comment]
Which Minecraft version was this added in?

**Comment by mcmonkey4eva** [comment]
1.14

**Comment by mcmonkey4eva** [comment]
Added to build 1779+ by https://github.com/CitizensDev/Citizens2/commit/d0dcb235b3282f943e8079fc7eca551adcad1086 as `/npc mushroomcow --variant brown` (or red)
