### ISSUE TITLE
Combat - Ranged Mobs Ignored

### ISSUE THREAD

**Issue by boredofnames** [CitizensDev/Citizens2#1977]
The output of command `/version` on my server is: **Paper version git-Paper-226 (MC: 1.14.4)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.25-SNAPSHOT (build 1777)**

NPCs with passive set to false, or follow mode set to protect, will not aggro/attack ranged mobs (skeleton, pillager, etc).

**Comment by mcmonkey4eva** [comment]
You might want to consider Sentinel if you want combat-ready followers https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md

**Comment by boredofnames** [comment]
Okay, thanks for the link and support, I'll try that. 
I wasn't sure if this was intended or not, as it works for other mobs, so I figured I'd post my findings.

**Comment by mcmonkey4eva** [comment]
Follow protect mode should be fixed for projectiles in build 1779+ by https://github.com/CitizensDev/Citizens2/commit/d0dcb235b3282f943e8079fc7eca551adcad1086
