### ISSUE TITLE
/npc name not hiding the name even though in save.yml it says they are hidden

### ISSUE THREAD

**Issue by tigerboy985** [CitizensDev/Citizens2#1978]
Whenever I try to use /npc name the name doesn't hide at all, I've restarted, relogged and that hasn't fixed it at all.

Latest server log: https://pastebin.com/RYL1WV9k
Citizens Config: https://pastebin.com/i8mzwT0e

The output of command `/version` on my server is: This server is running Paper version git-Paper-153 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is:Citizens version 2.0.25-SNAPSHOT (build 1776)
INFO Website: http://www.citizensnpcs.co
INFO Author: fullwall

**Comment by Ph4i1ur3** [comment]
You likely have a plugin conflict
See: https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by tigerboy985** [comment]
It was scoreboard revisions, how would I go about fixing it and keeping the scoreboard?

**Comment by mcmonkey4eva** [comment]
Options:
- **A:** Contact the developer of the plugin, ask them about fixing it. Give them a link to the Plugin_Conflict page, which at the bottom has technical details to help devs fix this particular type of conflict.
- **B:** Remove the plugin.
- **C:** Replace the plugin with an equivalent. If you're just using the animated sidebar, we do provide a scripted version that works with Citizens, which you might want to consider: https://forum.denizenscript.com/viewtopic.php?f=13&t=147
- **D:** Just accept the nameplate toggling and long-names are broken.

Naturally, I suggest you try **A** first. If the developer is unresponsive or unhelpful, switch to option **C**.

If you need any more help with this, just reply below and we'll reopen the issue. Also feel free to join the Discord to talk with us directly https://discord.gg/Q6pZGSR
