### ISSUE TITLE
Npc Skins not staying with 1.8

### ISSUE THREAD

**Issue by tuckerandlexus** [CitizensDev/Citizens2#198]
Hi there, I have loaded the newest citizens build V2.014 build 1206, but the npc skins do not stay. I used to have a version for 1.7.9 and they skins remained all the time? It's strange, when I do a /reload and I am in front of that npc their skin will load, but when I go to the next house the skin on that npc is a regular steve guy. It either shows up as Steve or some girl, but they are always the same. I am using craftbukkit 1.8.R01 from spigot git bash. Here is a copy of my config http://pastebin.com/yLpPd6LK

No errors are popping up when this happens.
These are the plugins I am using: citizens 2, essentials, autorank, biometp, fancyportals, hungergames, multiverse core, sentry, server signs, ultra trader, vault, votifier, worldedit, worldguard.

Is there a way to fix it? Thank you :D
![picture1](https://cloud.githubusercontent.com/assets/5788878/5788129/0af46734-9deb-11e4-9961-499d5bc904e6.png)
![picture2](https://cloud.githubusercontent.com/assets/5788878/5788130/10f1c5b4-9deb-11e4-8830-df20a93c89e1.png)

**Comment by ELJESTER** [comment]
I have the same exact problem man! It is quite annoying!

**Comment by mcmonkey4eva** [comment]
Run Spigot, not CraftBukkit first of all...

**Comment by tuckerandlexus** [comment]
Shouldn't it work for both?

**Comment by tuckerandlexus** [comment]
I am asking because I got craftbukkit from git bash from spigot and I thiught citizens 2 was compatible with both?

**Comment by Oniromancie** [comment]
I have the same bug

**Comment by Vekseid** [comment]
The skin may also come back if you leave and go away.

Is there something about the plugin that's not properly emulating a player, perhaps? My NPCs also occasionally vanish with similar frequency.

**Comment by mcmonkey4eva** [comment]
The trouble is, we (The Citizens team) can't replicate NPCs vanishing or losing their skin. Everything's fine on our end. So we don't know what to do about this.

**Comment by Vekseid** [comment]
Haven't had NPCs vanish since moving to the latest dev build, knock on wood.

Since moving to that build, 99% of all resets come from spawning into the world, whether through a nether portal or logging in. It's at least much more consistent with this now.

**Comment by fullwall** [comment]
Duplicate: known issue.
