### ISSUE TITLE
Citizens NameTag or LeaderHeads Bug

### ISSUE THREAD

**Issue by FireQuacker** [CitizensDev/Citizens2#1983]
Server Version: 1.12.2
Plugin Version (Citizens): 2.0.25-b1781
Plugin Version (Leaderheads): 4.0.5

NameTags for the NPCs will only allow randomly between 10 - 12 characters, Im using leaderheads to edit the NPCs name and no matter what i try, the NPCs name will not display the full amount of info.

Am i doing something wrong?

[https://i.imgur.com/SAhl8Ti.png](https://i.imgur.com/SAhl8Ti.png)

Thank you,
Brandon

The output of command `/version` on my server is: git-paper-1617 (MC: 1.12.2)
The output of command `/version citizens` on my server is: 2-0-25 SNAPSHOT (Build 1781)

**Comment by mcmonkey4eva** [comment]
Common scoreboard-related plugin conflict, refer to https://wiki.citizensnpcs.co/Plugin_Conflict

There's a sidebar visible on your screenshot, so most likely the plugin conflicting will be whatever drives that one
