### ISSUE TITLE
Player Commands

### ISSUE THREAD

**Issue by DaDigDude** [CitizensDev/Citizens2#1984]
Hello. I recently purchased the plugin and was wondering if player commands upon interacting with an NPC are a thing? I know that you can set commands to NPCs and the commands will run from the console but I have found no source or information regarding to being able to have the player run those commands upon right or left clicking an NPC. Any help would be appreciated!

The output of command `/version` on my server is: 
**This server is running CraftBukkit version git-Spigot-56f8471-ccd47a5 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is:
 **Citizens version 2.0.25-SNAPSHOT (build 1781)
Website: http://www.citizensnpcs.co
Author: fullwall**

**Comment by fullwall** [comment]
Yes, using /npc command will allow this.

**Comment by DaDigDude** [comment]
Yes, but how? I've already tried. I have traveled to page 2 of Google. Nothing in the config file or Wiki display how to use the command feature as a player command.

**Comment by DaDigDude** [comment]
Yes, but how? I've already tried. I have traveled to page 2 of Google. Nothing in the config file or Wiki display how to use the command feature as a player command.

**Comment by mcmonkey4eva** [comment]
`/npc command -p add "some command here"` is available in the latest build at https://ci.citizensnpcs.co/job/Citizens2/
