### ISSUE TITLE
Villager NPCs not working

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#1987]
The output of command `/version` on my server is: **git-Spigot-f39a89e-73698cf (MC 1.15)**
The output of command `/version citizens` on my server is: **2.0.26 build 1789**

Hello,
After switching to Spigot 1.15, all my existing villagers NPCs have disappeared. I mean, they are still saved etc., but they don't have an entity. Creating a player NPC and doing _/npc type villager_ makes the NPC disappear as well.

**Comment by fullwall** [comment]
Which plugins are you using? Can see villagers here.

**Comment by SkytAsul** [comment]
WorldEdit, WorldGuard, Vault, LuckPerms, Citizens and a few of mine that I guarantee don't have anything to do with entity spawning.

**Comment by YourCoalAlt** [comment]
I am not sure if this is related, but when I try to grab the villager entity is throws an NPE and the NPCs do not spawn

`		NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.VILLAGER, displayName);
		npc.spawn(location);
		Entity ent = npc.getEntity();
		ent.setCustomNameVisible(true);
		ent.setCustomName(displayName);`

**Comment by mcmonkey4eva** [comment]
If entity was null, it would happen on the second-to-last line, not the last @YourCoalAlt

**Comment by YourCoalAlt** [comment]
Whoops I meant to put it there my bad, must've been tired when I wrote that

**Comment by YourCoalAlt** [comment]
yeah something funky is happening and I cannot figure out why.

Codewise, I made a plugin just to do the following:

> NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.VILLAGER, displayName);
npc.spawn(location);
Bukkit.getLogger().info("Checking existence for "+npc.getName());
Bukkit.getLogger().info(npc.getEntity() != null ? "Is real" : "Is null");

The NPC exists, however npc.getEntity() is always null. When it comes to just creating one with commands, that also fails for me as well. Hopefully this helps

**Comment by mcmonkey4eva** [comment]
In my local testing (in 1.15.1 now), `/npc create bob --type villager` works with no issues, a villager NPC appears.

**Comment by YourCoalAlt** [comment]
After updating to 1.15.1, the command now works. However, I am now coming to the conclusion that the .spawn method does not work in the code I provided above. After checking npc.isSpawned, it returns false.

**Comment by mcmonkey4eva** [comment]
@YourCoalAlt that's not a change, that's always been the case. An NPC cannot spawn into an unloaded area.

**Comment by YourCoalAlt** [comment]
I've never experienced this before, it used to work fine whether a player was on or not, and I always force load the chunk. Interesting this didn't effect me until now.

**Comment by mcmonkey4eva** [comment]
A forceloaded chunk without a player nearby is basically non-guaranteed. There's no definitive guarantee they will spawn and work, but there also isn't a guarantee that they won't. For the most part theoretically NPCs will automatically despawn when players are not nearby, even if the chunk isn't yet unloaded serverside - though exactly how and when varies based on implementation details. Mobs in vanilla minecraft work on a similar principle of despawning based on player distance, not chunk loading.

**Comment by mcmonkey4eva** [comment]
Do villagers still not work in 1.15.2?

**Comment by SkytAsul** [comment]
It's now working flawlessly for me!
