### ISSUE TITLE
Blacksmith trait Not working with Hyperconomy 0.975.3

### ISSUE THREAD

**Issue by Snakemansos** [CitizensDev/Citizens2#199]
(Spigot 1.8) Problems with Blacksmith trait on citizens-2.0.14-SNAPSHOT & hyperconomy v0.975.3 [Beta]. error-here: http://pastebin.com/MiqaFE36 Sorry about my language i speak spanish

**Comment by mcmonkey4eva** [comment]
Well... this is an error with Blacksmith or Hyperconomy, not with Citizens...?

**Comment by Snakemansos** [comment]
i was talking with developer of hyperconomy and say me: "Blacksmith just need to update to hyperconomy v0.975.3"
you can talk with developers of blacksmith to update that? i was trying to send the issue but i can't find the developer.

**Comment by mcmonkey4eva** [comment]
It's currently maintained by @Morphan1 - so, morph, what up with dis yo

**Comment by remremrem** [comment]
I forked Blacksmith repo from aufdemrand and my branch currently is compatible with HyperConomy 0.975.3

**Comment by Snakemansos** [comment]
i will tested and got a problem with repairing custom items, like diamond sword with custom name and lore, previous version working on that. This new version not recognize any item with custom name and lore.

**Comment by remremrem** [comment]
Okay I will check on that tonight. Was the custom item added to HyperConomy database with /additem command?

**Comment by Snakemansos** [comment]
Thanks man!!! :) the answer it's in the hyperconomy page!!!
