### ISSUE TITLE
Plugin conflict with QuickBoard

### ISSUE THREAD

**Issue by Nety01** [CitizensDev/Citizens2#1992]
The output of command `/version` on my server is: **Paper version git-Paper-652 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1790)**

The QuickBoard plugin (https://www.spigotmc.org/resources/quickboard-free-scoreboard-plugin-scroller-changeable-text-placeholderapi-anti-flicker.15057/) conflicts with Citizens and cuts the NPC's names to 16 characters only

**Comment by SXRWahrheit** [comment]
That's a problem with QuickBoard, not Citizens.

**Comment by mcmonkey4eva** [comment]
Also, you are a cracked user. We do not support cracked users.
