### ISSUE TITLE
NPCs are Pushable on 1.15

### ISSUE THREAD

**Issue by fjeddy** [CitizensDev/Citizens2#1993]
With the new 1.15 update, Citizens can be pushed around by players.

```
[Server thread/INFO]: Citizens version 2.0.26-SNAPSHOT (build 1790)
[Server thread/INFO]: Website: http://www.citizensnpcs.co
[Server thread/INFO]: Author: fullwall
[Server thread/INFO]: CitizensCMD version 2.4
[Server thread/INFO]: Author: Mateus Moreira
```

```
[Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f39a89e-4633e6c (MC: 1.15) (Implementing 
API version 1.15-R0.1-SNAPSHOT)
[Server thread/INFO]: Checking version, please wait...
```

**Comment by VanillaChan6571** [comment]
Can confirm this on 1.15-R0.1

**Comment by fjeddy** [comment]
I just encountered a weird bug.

In the spawn, I can push the citizens, but when I worked with NPCs in a different location, I can't push them. Havn't figured out what the difference is yet, or what's causing it. Still debugging, but the bug doesn't seem to be consistent.

**Comment by fjeddy** [comment]
![image](https://user-images.githubusercontent.com/43314498/70921525-bffa8800-2024-11ea-8acd-4264ce6eba1a.png)

These can't be pushed, if I move the NPC somewhere else, they still can't be pushed. Every other NPC can be pushed, old and new ones.

Any tips on how I can see if there is any difference between them?

![image](https://user-images.githubusercontent.com/43314498/70921594-e3253780-2024-11ea-8a3e-4db31dd29035.png)

This one can be pushed easily in the ground.

**Comment by fjeddy** [comment]
Opened up the saves.yml file and went through the difference manually. Whenever `gravity` is enabled, you can push the NPC, when it's disabled, you can't push it anymore! :/

**Comment by FuturePinger** [comment]
I seem to get an error about Denzien Pushable
https://pastebin.com/VBsYqWte

**Comment by mcmonkey4eva** [comment]
@FuturePinger the exception looks like a mishandling of an NPC despawning _the very same moment_ it's pushed.
I've fixed it in the new dev build of Denizen.

**Comment by ItsMeGriff** [comment]
> Opened up the saves.yml file and went through the difference manually. Whenever `gravity` is enabled, you can push the NPC, when it's disabled, you can't push it anymore! :/
> 
> Edit: Nvm, it seems like the above statement is true if the NPC is of the type `player`, but for all other mobs, friendly or hostile, then you can still push them no matter what.

Just to add a bit more onto this. You can set the flag /npc collidable to disable colliding but this only works for player models and when you try and it on it a villager, for example, it says "NPC cannot be the mob type villager". I'm not sure if the flag for setting collidable to any entity other than a player is a bug but that seems like the easiest fix to the issue would be allowing collidable to be set to any entity.

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/530e26c4f85cd15453f545779ad30446dc900a23 in build 1793+ on https://ci.citizensnpcs.co/job/Citizens2/
