### ISSUE TITLE
The plugin is red in the plugins list.

### ISSUE THREAD

**Issue by glub123** [CitizensDev/Citizens2#1996]
Hi,
I installed the citizens plugin on my Aternos server,  I reloaded the server and ran the command /pl. All my plugins were green exept for Citizens. If I run any citizens commands it says: An internal error occured while attempting to perform this command. Why does this happen? Please help me with this.

-glub123

PS: If you would like to see for yourself the server ip is glub1234.aternos.me

**Comment by mcmonkey4eva** [comment]
You have not followed the issue template (you can review it at https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE ), therefore this issue is invalid.
Please reply with the details requested in the issue template to have this issue reopened.

**Comment by glub123** [comment]
Well, Aternos does not have a feature to view the logs.

**Comment by mcmonkey4eva** [comment]
You're going to have get a server that gives you basic access to data for us to be able to give you any support.
You can potentially contact Aternos' support for help, if they provide it themselves.

**Comment by SXRWahrheit** [comment]
Alternatively: Buy a real server. OVH sells VPS shards for very little money and with great specs for the price: https://www.ovh.com/world/vps/vps-ssd.xml
