### ISSUE TITLE
NPE on WaypointProvider 

### ISSUE THREAD

**Issue by ImDatIllusion** [CitizensDev/Citizens2#1997]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
![image](https://user-images.githubusercontent.com/28360622/71217227-eafb0b00-22b4-11ea-9bde-7412c62d2341.png)

The output of command `/version citizens` on my server is: 
Citizens version 2.0.26-SNAPSHOT (build 1793)
Website: http://www.citizensnpcs.co
Author: fullwall

When I try to modify wander traits right after cloning an NPC, an NPE is thrown.
Code: https://pastebin.com/T5Mx1reJ
Exception: https://pastebin.com/XpRyt2cN

**Comment by fullwall** [comment]
Can you try using the copy() method I just added in the most recent build? I wonder if the JVM is interfering here because the error seems to be NPEing on an always non-null field.

**Comment by ImDatIllusion** [comment]
Similar exception
https://pastebin.com/mqKyt0Gx

**Comment by mcmonkey4eva** [comment]
That, hilariously, is on the same line, but a different variable is null now. gg

**Comment by ImDatIllusion** [comment]
Who am I supposed to thank for the issue? fullwall? myself?

**Comment by mcmonkey4eva** [comment]
Both you and fullwall and also me! You reported it, I traced it*, fullwall fixed it.

![trace](https://i.alexgoodwin.media/i/misc/04aeb1.png)

Anyway, try latest build (1799), fullwall made a new commit to theoretically fix the new NPE

**Comment by ImDatIllusion** [comment]
NPC cloning seems to spawn the NPC on the original location, pushing the original NPC

**Comment by ImDatIllusion** [comment]
NPE is fixed, the code seems to be using the registry to create a new NPC but Essentials still complains about the UUIDs (thinks it is the same entitiy)
