### ISSUE TITLE
There is a way to keep the NPC's names visible in F1?

### ISSUE THREAD

**Issue by ThatOverPowered** [CitizensDev/Citizens2#1998]
As it says in the title, is there any way to keep the names of the NPCs visible **while in F1**?

![image](https://user-images.githubusercontent.com/50776804/71225863-ded17680-22d1-11ea-8c8d-5480d1ed6e91.png)

A photo with an NPC with the **name** "&7(Click Dcho.)" And above it, a **hologram** of a plugin **external** to Citizens. As you can see, on the right of the screen I have a Scoreboard and below you can see the HUD perfectly, so **I am NOT in F1**

![image](https://user-images.githubusercontent.com/50776804/71225964-12140580-22d2-11ea-803e-1947e03f24a4.png)

Exactly **the same photo but in F1**, and as you can see, the hologram of the external plugin is still there, but **NOT the name of the NPC**

**There is something what can I do to make the name visible in F1?**

            ~ Thanks, ThatOverPowered

My server is running CraftBukkit version git-**Spigot-79a30d7-acbc348 (MC: 1.12.2)** (Implementing API version 1.12.2-R0.1-SNAPSHOT) **Last and final build for 1.12.2**

My Citiznes is: Version **2.0.26-SNAPSHOT (build 1793)**

**Comment by mcmonkey4eva** [comment]
Not sure exactly what's going on here, but uh...
You could workaround the problem by just adding two lines of hologram, and then using `/npc name` to disable the NPC's base name (ie, replace the NPC's nameplate with a hologram).

**Comment by ThatOverPowered** [comment]
Hi!

Thanks for the answer, but unfortunately that was my first idea... But `/npc name` does not work... The name still visible.
Should I **change** Citizens version to make the command work?

**Comment by mcmonkey4eva** [comment]
That's a known & common plugin conflict issue: https://wiki.citizensnpcs.co/Plugin_Conflict

Likely caused by whichever plugin is supplying the sidebar visible in your first screenshot.

**Comment by ThatOverPowered** [comment]
Okay, thanks for the link, i fix it. Ty for the help
