### ISSUE TITLE
ERROR WHEN I WANT TO CREATE A NPC

### ISSUE THREAD

**Issue by NoxTV** [CitizensDev/Citizens2#1999]
Hello, when I execute the command /npc create [name] it puts me a huge mistake. I downloaded the last build so I don't understand.

![Capture](https://user-images.githubusercontent.com/52321848/71263107-8934b280-2341-11ea-9af8-64429a2f180f.PNG)

The output of command `/version` on my server is: **CraftBukkit version git-Spigot-4d24e36-5193f76 (MC:1.14)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1793)**

**Comment by ImDatIllusion** [comment]
Update to 1.14.4

**Comment by mcmonkey4eva** [comment]
1.14 flat is unsupported and unsupportable. That version of Minecraft is fundamentally broken.
Use 1.14.4 (or 1.15.x, 1.13.2, 1.12.2, ...)
