### ISSUE TITLE
Player NPC's are added to world.getPlayers()

### ISSUE THREAD

**Issue by sanjay900** [CitizensDev/Citizens2#200]
As Player NPC's are added to world.getPlayers(), trying to send packets via protocolLib to every player in a world bug out, because protocollib can't send packets to NPC's which makes sense. I have a feeling this was caused by e4c5ed4906ac0ea858fd801a9ec99f3e9dabf8cc. Is there a way to fix this, or will i have to start checking if a player is an npc in all my loops?
``` Java
for (Player e : world.getPlayers()) {
ProtocolManager pm = ProtocolLibrary.getProtocolManager();
    PacketContainer armourStand =  pm.createPacket(PacketType.Play.Server.SPAWN_ENTITY_LIVING);
... add stuff to packet ...
    pm.sendServerPacket(e, armourStand); //Illegal argument exception
}
```
```
Caused by: java.lang.IllegalArgumentException: Unable to find a field null with the type io.netty.channel.Channel in net.citizensnpcs.npc.network.EmptyNetworkManager
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:367) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57) ~[?:?]
        at com.comphenix.protocol.reflect.FuzzyReflection.getFieldValue(FuzzyReflection.java:104) ~[?:?]
        at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:74) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolInjector$4.sendServerPacket(NettyProtocolInjector.java:351) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:836) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:790) ~[?:?]
```

**Comment by sanjay900** [comment]
Is this better solved by protocollib or by citizens? since this didn't happen a few versions ago.

**Comment by sanjay900** [comment]
Because this is caused by citizens, i haven't put an issue on ProtocolLibs github yet.

**Comment by mcmonkey4eva** [comment]
I suppose it would be fairly reasonable for Citizens to implement slightly more of the networking code (and still have it channel into nothing, of course). @fullwall what do you think?

**Comment by fullwall** [comment]
I think it's a ProtocolLib issue - it's checking for a field in the lowest subclass of NetworkManager and not the Minecraft NetworkManager.

**Comment by fullwall** [comment]
Reopening for the world.getPlayers() issue.

**Comment by mcmonkey4eva** [comment]
Aren't npcs only added to getPlayers if `/npc playerlist` is on?

**Comment by fullwall** [comment]
@mcmonkey4eva - to the Minecraft's player list yes, but not to the Bukkit playerlist.

**Comment by Xericore** [comment]
Is there any solution or workaround for this issue? I'm asking because of this: https://github.com/Phoenix616/BetterBeds/issues/2

**Comment by mcmonkey4eva** [comment]
@fullwall is it possible that players are in *`world.getPlayers()`*? That's what the guy on the issue says and I just noticed that Denizen's handling of the method has if checks to avoid NPCs... something that wouldn't be there if it wasn't an issue.

**Comment by sanjay900** [comment]
I mean, i always turned of the player list and the original issue was still a problem.

**Comment by Morphan1** [comment]
```
    public List<Player> getPlayers() {
        List<Player> list = new ArrayList<Player>();

        for (Object o : world.entityList) {
            if (o instanceof net.minecraft.server.Entity) {
                net.minecraft.server.Entity mcEnt = (net.minecraft.server.Entity) o;
                Entity bukkitEntity = mcEnt.getBukkitEntity();

                if ((bukkitEntity != null) && (bukkitEntity instanceof Player)) {
                    list.add((Player) bukkitEntity);
                }
            }
        }

        return list;
    }
```
Sorry, I should've replied to this earlier

**Comment by Morphan1** [comment]
How had would it be to remove the NPC from the entityList

**Comment by mcmonkey4eva** [comment]
That's terrifying inefficient code.

**Comment by fullwall** [comment]
@mcmonkey4eva - from memory world.getPlayers() actually scans the entire list of entities in the world. IIRC you kind of need to keep the players in that list.

**Comment by mcmonkey4eva** [comment]
Fixed on their end :)
