### ISSUE TITLE
Npc jump bug -rain-

### ISSUE THREAD

**Issue by dwa1275** [CitizensDev/Citizens2#2000]
CraftBukkit version git-Spigot-2ee05fe-90ef74e (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

Citizens-2.0.26-b1793

Same issue as before a month or 2 ago, NPC are jumping while it is raining

**Comment by mcmonkey4eva** [comment]
Specifically this one https://github.com/CitizensDev/Citizens2/issues/1974

I guess a matching problem re-emerged from the 1.15 update?

**Comment by dwa1275** [comment]
same as before, just can keep the villagers on the ground

**Comment by mcmonkey4eva** [comment]
Should be fixed in Citizens build 1796+ on https://ci.citizensnpcs.co/job/Citizens2/ via https://github.com/CitizensDev/Citizens2/commit/ba216c7587040a500c521589a38ca071f2002d9d + https://github.com/CitizensDev/Citizens2/commit/3e708f0d803142ffe540e8d9d7d5ac7ce17429b9
