### ISSUE TITLE
Npc dissapearing when i do /kill

### ISSUE THREAD

**Issue by VictorMajri** [CitizensDev/Citizens2#2001]
When I get killed or if i do /Kill the NPC's disseapear, if I do /rl or /citizens reload they come back. I also tried loopcommands but the skins look buggy when it reloads and if I use equip, the equipped items/gear dissapeares for a second.

**Comment by Ph4i1ur3** [comment]
Maybe follow the issue template?

**Comment by VictorMajri** [comment]
> Maybe follow the issue template?

What do you mean?

**Comment by VictorMajri** [comment]
Just looked into the template and it says respawning time. If this is what has to change than  what number do I need to give it to stop disappearing when I or someone else dies.

**Comment by Ph4i1ur3** [comment]
When you open an issue, all that text in the window isnt there to just be deleted. It's the issue template that you should follow for reporting a bug

**Comment by VictorMajri** [comment]
> When you open an issue, all that text in the window isnt there to just be deleted. It's the issue template that you should follow for reporting a bug

Oh okay, I will redo one then.

**Comment by mcmonkey4eva** [comment]
When you do `/kill` to get rid of entities, entities disappear. In what way exactly does this surprise you?

Also, you can review the issue template here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE
