### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by LeakMania-v6** [CitizensDev/Citizens2#2005]
`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:36 min
[INFO] Finished at: 2019-12-23T10:53:24+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project citizens-main: Could not resolve dependencies for project net.citizensnpcs:citizens-main:jar:2.0.26-SNAPSHOT: Could not find artifact org.bukkit:craftbukkit:jar:1.15.1-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :citizens-main
`

**Comment by mcmonkey4eva** [comment]
Builds can be found here: https://ci.citizensnpcs.co/job/Citizens2/
