### ISSUE TITLE
[1.15.1] exception occurred while the trait ocelotmodifiers was spawning for NPC

### ISSUE THREAD

**Issue by mrfloris** [CitizensDev/Citizens2#2006]
Got buildtools.jar, and made my own spigot-1.15.1.jar before replacing existing citizens jar with the latest from the jenkins server. Started the server, and got a bunch of errors, all the same. They're about ocelot and cats etc - Since 1.13.2 had just ocelots, and from 1.14.x onwards we have cats too, there's a mismatch when i start this 1.15.1. 

Full error; https://pastebin.com/mf6ruHdx

The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-05bb8bc-8073dbe (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **>ver Citizens
[10:29:09] [Server thread/INFO]: Citizens version 2.0.26-SNAPSHOT (build 1801)**

**Comment by mcmonkey4eva** [comment]
Amounts to a request for automatic trait updates between Minecraft versions. In this case ocelot -> cat. (I think the underlying change happened in 1.14 though, not 1.15)

**Comment by mrfloris** [comment]
We have 500+ id in the yml file, is it safe to just replace ocelot with the ocelot type it expects, manually? or would more than 'type:' editing be required?

**Comment by mcmonkey4eva** [comment]
This commit https://github.com/CitizensDev/Citizens2/commit/a0e3b23bc3054f11256c8f0fc315aa2bce58b025 in build 1806+ from https://ci.citizensnpcs.co/job/Citizens2/ should automatically migrate old ocelot data to modern cat data.
