### ISSUE TITLE
NPCs skin look weird / buggy

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#201]
Hi,

I have just upgraded my server to Spigot 1.8 (latest dev build) and Citizens2 v2.0.14 (latest dev build) and when creating new NPCs they look very weird / buggy. Screenshot:
![2015-01-19_12 52 01](https://cloud.githubusercontent.com/assets/6141938/5800062/60ad0a46-9fda-11e4-9fd3-8eed2ac8ac20.png)

How to fix?

**Comment by mcmonkey4eva** [comment]
What exactly is wrong with the skins here?
