### ISSUE TITLE
Player NPCs Crashing

### ISSUE THREAD

**Issue by nexlemav** [CitizensDev/Citizens2#2010]
I'm having an issue when NPCs are set to a player type that causes a server crash, doesn't happen when NPCs are set as a mob type. Seems to happen at random & regardless if players are on or not. Attached is my server's crash report.

Spigot 1.14.4 
Citizens-2.0.25-b1781

[latest.log](https://github.com/CitizensDev/Citizens2/files/4001776/latest.log)

https://pastebin.com/5iVDt8MA

https://pastebin.com/MBUquLU8

**Comment by mcmonkey4eva** [comment]
I've repastebin'd the latest log file since you oddly didn't pastebin it: https://pastebin.com/z3WPpMt9

You didn't include any crash report, and the latest.log doesn't seem to correspond to a server crash.
