### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by DodleGamer88** [CitizensDev/Citizens2#2011]
so im making a mmo rpg server and wanted to use npcs. so i downloaded citizens on my server.
i use alternos to creat my server btw.
but when the server started it wouldnt cooperate.. i went to my console and saw this:

[00:37:57] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1605)
--
255 | [00:37:57] [Server thread/INFO]: Creating file: config.yml
256 | [00:37:57] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1605) (Is it up to date?)
257 | java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
258 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
259 | at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_222]
260 | at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
261 | at net.citizensnpcs.Citizens.onEnable(Citizens.java:266) ~[?:?]
262 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
263 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
264 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
265 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
266 | at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
267 | at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
268 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
269 | at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
270 | at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
271 | at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
272 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
273 | Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
274 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
275 | at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
276 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
277 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
278 | ... 15 more

i dont kno how i can fix it. someone that can help me fix this problem ?

**Comment by mcmonkey4eva** [comment]
Run a real server host, or even just a local homehost. Aternos is basically unsupportable.
