### ISSUE TITLE
Citizens all disappear upon plugin reload.

### ISSUE THREAD

**Issue by Castiella** [CitizensDev/Citizens2#2012]
Citizens all disappear upon /citizens reload. 

Latest Log: https://pastebin.com/h8ewpTqv

The output of command `/version` on my server is: **[19:09:07 INFO]: This server is running Paper version git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **[19:09:39 INFO]: Citizens version 2.0.26-SNAPSHOT (build 1804)
[19:09:39 INFO]: Website: http://www.citizensnpcs.co
[19:09:39 INFO]: Author: fullwall**

I've also just been informed that the plugin isn't saving new NPC's created either. Upon restart they're deleted.

**Comment by Castiella** [comment]
and restart*

**Comment by mcmonkey4eva** [comment]
You have several basic error messages in that log, such as these two right at the top:
```
[18:19:59] [Server thread/ERROR]: Ambiguous plugin name `Multiverse-Core' for files `plugins/Multiverse-Core-4.1.0 (1).jar' and `plugins/Multiverse-Core-4.1.0.jar' in `plugins'
[18:19:59] [Server thread/ERROR]: Could not load 'plugins/extension-legacy-api-1.0.0.jar' in folder 'plugins'
```

Please fix all unrelated errors before continuing.

Also, post a `latest.log` (without those errors reoccurring) that includes either the server shutdown sequence or a usage of `/citizens save`.

If you're expecting NPCs to not disappear when you create them then immediately do `/citizens reload`... no you have to save first. Ideally you'd never reload at all.
