### ISSUE TITLE
server crash during npc tphere in another world

### ISSUE THREAD

**Issue by cicatrice74** [CitizensDev/Citizens2#2015]
I had a server crash during a npc tphere on another world than the original of the npc

- error log: https://pastebin.com/Jj1YEsk2
- citizen config: https://pastebin.com/H6KLSksY
- Spigot 1.15.1 server /version: This server is running CraftBukkit version git-Spigot-492a779-9820cd2 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
05.01 09:33:45 [Server] Server thread/INFO You are 2 version(s) behind
- citizens version:  =====[ Citizens v2.0.26-SNAPSHOT (build 1804) ]=====

**Comment by mcmonkey4eva** [comment]
Did you "npc tphere" directly into an ender portal?

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply / sufficient detail.

If you can replicate this issue still on recent builds and in 1.15.2, please reply below with more detail.
