### ISSUE TITLE
breakblock API does not propperly update the waypoint when the previous breakblock command is completed but the npc is still pathing

### ISSUE THREAD

**Issue by 1thebeast** [CitizensDev/Citizens2#2017]
the issue im having is related to the breakblock API
from denizen im using the break command which in turn calls the api
the problem i ran into is that when another break command is issued before the last one finishes the npc sometimes gets stuck
i think the cause is that the task is marked as finished when the block is broken but the npc might still be pathing towards the block (it pathes towards the block itself, not the location where it gets in range) so when the next break action is assigned its waiting for the target block to get in range but the waypoint doesnt get updated(my assumption is its added to the list but cleared when the npc arives at the first waypoint) so the npc is stuck waiting for the block to get in range until i reload citizens

The output of command `/version` on my server is:  
"This server is running CraftBukkit version git-Spigot-492a779-c727dc2 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)"
The output of command `/version citizens` on my server is: 
Citizens version 2.0.26-SNAPSHOT (build 1802)

**Comment by mcmonkey4eva** [comment]
The most literal solution to this would be to ensure `BlockBreakerConfiguration#callback` waits for pathing to complete, but the more proper solution would likely to be to make the NPC stop navigation immediately after breaking a block, right before the callback is called.

**Comment by fullwall** [comment]
I've refactored the block breaker a little bit; would you mind rechecking this is a problem? Going to close due to age but feel free to reopen
