### ISSUE TITLE
Respawn Delay Broken

### ISSUE THREAD

**Issue by Nutrition35** [CitizensDev/Citizens2#2021]
Im using the citizens plugin for my server to set up sentry bots to attack players, and players can attack them back. But, I dont want the NPC's to respawn right after they die, because it doesnt give the other players a chance to clear out the level. So, I issued the command: "/npc respawn 10000" in order to delay the respawn by 10000 ticks. BUT, the npcs ignore the command issued and always respawn in 10 seconds, no matter how high I put respawn value.
- [15:23:56 INFO]: Carsob issued server command: /npc respawn 100000 
-Pastebin link: https://pastebin.com/W45ZNDpf

The output of command `/version` on my server is: 1.8.8-R0.1-Snapshot
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1605)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8

Update to a more recent server version.
