### ISSUE TITLE
Citizens type player - keep chunks loaded

### ISSUE THREAD

**Issue by Zzheyd** [CitizensDev/Citizens2#2023]
Hi here, have a problem ...
I think all of my citizens type player  (300+) ... keep chunk loaded :s

With view distance in server.properties at 3, have arround 200 chunks load, ~400 entitie and 2K tiles - when i'm out of "world-X" (here, world-X is world of lot of npc type player are)

With view distance at 15 for exemple, have more than 1300 chunks load, +1500 entities and 7.8K tiles ...

Have you any idea why ?

Citizens 2.0.26 snapshot build 1808

Paper version git-Paper-50 (MC: 1.15.1)

and have : (config file : https://pastebin.com/ZDcXydGF)

  chunks:
    always-keep-loaded: false
    alwayskeeploaded: false

Citizens was perfectly loaded :/
https://pastebin.com/9s1Ue51b

Exemple in this pics :
https://cdn.discordapp.com/attachments/315625512753954816/667829940976091153/2020-01-17_21.36.15.png
https://cdn.discordapp.com/attachments/315625512753954816/667829951839600650/2020-01-17_21.36.22.png

Thx for your help !

**Comment by Zzheyd** [comment]
I was found a "problem"

I was set ma spawn radius protection to : 0
https://cdn.discordapp.com/attachments/285777124139466753/667835156513554442/Capture.PNG

But, if y create NPC on ocean for exemple, with NO build etc around npc, the spawn world ... and chunks arround keep loaded, if they have 1 npc or 500 npc, same chunks/tiles/entity keep loaded

0 NPC = 0/0/0
1 or more NPC = always same number of chunk/tiles/entiti ... chunk aournd the defaut spawn world :/

**Comment by mcmonkey4eva** [comment]
This appears to be a duplicate of https://github.com/CitizensDev/Citizens2/issues/1947


Also, spawn chunks being loaded is normal. Attempting to disable that is relatively pointless.

Also, if 200 chunks are loaded, I don't think _all 300 NPCs_ are forceloading chunks. As 300 is more than 200, y'know?

**Comment by Zzheyd** [comment]
/setworldspawn  lost in ocean

Problem fixed !
