### ISSUE TITLE
I made a simplified Chinese translation file for version 2.0.26

### ISSUE THREAD

**Issue by apachezy** [CitizensDev/Citizens2#2025]
I made a Simplified Chinese translation file for version 2.0.26. May I initiate an RP to submit this file?
Also, I cannot access Discord in China. . .

**Comment by mcmonkey4eva** [comment]
We just got the CLA set up now, so you should be able to make a PR.

**Comment by fullwall** [comment]
Is there another place to talk to you? Would be good to talk about how we can make citizens better for Chinese users.
