### ISSUE TITLE
The error "Could not pass event PlayerCreateNPCEvent" appears.

### ISSUE THREAD

**Issue by Louette** [CitizensDev/Citizens2#2026]
Entering the command **/npc create main** will cause an error as shown below.

![image](https://user-images.githubusercontent.com/49364637/72662529-aa192200-3a2b-11ea-803c-3967e7a352b2.png)

The output of command `/version` on my server is: **This server is running CatServer version git-CatServer-1.12.2-c4740bb (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1812)**

**Comment by mcmonkey4eva** [comment]
This is a problem with `ReserveEconomy`

Furthermore, you're running an entirely unsupported and unsupportable server version.
