### ISSUE TITLE
Skins do not stay

### ISSUE THREAD

**Issue by ELJESTER** [CitizensDev/Citizens2#203]
As the title states skins are no longer staying, What i mean by this is that when you leave an NPC for a while after a re log or a server restart, or even just randomly they turn into Steve skins and the standard girl skin, a temporary fix is to ether re log or to do /citizens reload in front of the NPC u want the skin to show on, this will not only fix the NPC in front of you but break all the other ones around you by setting their skins to Steve! This is quite annoying as our server highly depends on skins and would love to see this fixed so that my players get the 100% Experience!

It is not just me as this guy also has the same problem! https://github.com/CitizensDev/Citizens2/issues/198

**Comment by mcmonkey4eva** [comment]
What version of Citizens and Spigot are you using?

**Comment by mcmonkey4eva** [comment]
... You knowingly made a duplicate issue. Please don't do that, it makes issues much harder to manage.
