### ISSUE TITLE
Add a CONTRIBUTING.md File to help new devs

### ISSUE THREAD

**Issue by Turpster** [CitizensDev/Citizens2#2031]
### The Issue
- inconvenient and a stretch to compile.
- less accessible for new contributors.
### Solution
In interest of ease-of-development, It would be convenient to automatically install the CraftBukkit dependencies with an install script.

Therefore, I had commit a script used in the [EssentialsX repostory](https://github.com/EssentialsX/Essentials/blob/2e818ac7090626a6682b19f2b8ce6fe385dbc170/scripts/buildtools.sh) that
1. Creates the folder `.buildtools`.
2. Downloads `buildtools.jar` and places it in `.buildtools`.
3. Runs through all revisions needed (`1.8.8`, `1.10.2`, `1.11.2`, `1.12.2`, `1.13.2`, `1.14.4` and `1.15.1`), compiles and installs them into maven's local repository `~/.m2`.
#### Pull Request
I had made #2030 that has used and edited version of a  present in the EssentialsX repository. This PR  has been closed but it's worth creating an issue to grab opinions.

**Comment by mcmonkey4eva** [comment]
This really doesn't even need to be automated via script.
Anyone intending to work with Citizens source code should know how to operate BuildTools (for that matter, even most server owners should be able to figure it out)... there could maybe be a readme note adding clarifying that you must build the full list of historical back-supported versions, an autoinstall script is significantly too far and out-of-place.

**Comment by fullwall** [comment]
I can see a place for a contributing.md addition that tells you how to get started.

**Comment by mcmonkey4eva** [comment]
Yeah that sounds like the perfect route for this.
