### ISSUE TITLE
[Bug] Player NPCs Keep Chunks Loaded and Change Spawn Load Behavior on Paper

### ISSUE THREAD

**Issue by Kas-tle** [CitizensDev/Citizens2#2032]
Possibly related to #1947, but I was told to open a new issue on this. I am now using Paper-67 (1.15.2) and am still having the same issue with only Citizens, Denizens, and Essentials installed. I have done quite a lot of testing so I will try to divide this up as best I can. This is all done on a newly generated world, with doMobSpawn set to false to make what is happening as clear as possible.

Using `essentials:lag`, I have no chunks loaded in my world before a player joins as I have set `keep-spawn-loaded-range: 0` and `keep-spawn-loaded: false` in paper.yml. Firstly, it seems that the presence of player NPCs on the world completely negates these two settings. Spawn chunks remain loaded as soon as an NPC is spawned onto the world. So simply spawning any NPC away from the spawn chunks actually causes paper to immediately load  in the spawn chunks, causing my chunk count to double.  When using `view-distance=10` in server.properties, this means that loaded chunks increase from 529 with only a player on the world to 1058 when a player NPC is spawned. Removing the NPC brings the loaded chunks back to 529. If I leave the world with the NPC loaded, the loaded chunk count then decreases to 530. 
As Rabit points out, this issue seems to become amplified with view distance. 

On leaving the world with the NPC, it seems that at `view-distance=10`, only a single chunk is loaded for the NPC (The total is 530. We would expect 529 as spawn chunks are 23^2, which is equal to 529). If we bump this up to `view-distance=11`, however, the loaded chunk count jumps to 626. If we increase to `view-distance=12`, this jumps to 730. On first glance, this seems that more chunks are being loaded around the NPC. However, I do not believe that is what is happening. You will note that 530, 626, and 730 follow the format {[(2*viewdistance)+3]^2}+1. So what appears to be happening is the spawn chunk radius is somehow being increased to the view distance. This behavior does not occur when no NPCs are loaded. If we decrease to `view-distance=9`, this behavior continues with 442 chunks being loaded. Further confirming this, adding an extra NPC brings this total up to 443.

I have also tested setting the NPC to types other than player, and this issue does not occur in that case. Removing the npc via console brings the loaded chunk count to 0 as would be expected with these settings.

I can understand why this issue would be easy to miss, as at the standard view distance of 10, with only one NPC loaded, the number of chunks kept loaded is negligible. However, for those trying to achieve a performance boost by keeping unused worlds unloaded, this is an issue.

These results are also reproducible without Essentials, using `paper chunkinfo`, but you must subtract "Inactive" chunks from "Total" chunks to get the loaded chunk value. This is because Paper keeps track of how many chunks have been loaded since the server came online. "Total" chunks value also resets if loaded chunks reaches 0.

Also, this does not appear to be reproducible on normal Spigot, at least with the default configurations of Spigot in the 1.15 versions, as well as with the configurations I was using to produce it in 1.14.4, so it would seem something changed somewhere along the line with that.

Edit[3]:Reproduction Steps
1. Create a clean server with the latest build of Paper 1.15.2 (#67 at time of test)
2. Install EssentialsX for chunk counting (Paper alone may be used, but you must subtract "Inactive" chunks from "Total" chunks to get the loaded chunk value. If using this method, substitute `lag` for `paper chunkinfo` in later steps).
4. Start server and accept EULA to create configuration files.
5. Set `keep-spawn-loaded-range: 0` and `keep-spawn-loaded: false` in paper.yml.
6. Restart server, set `gamerule doMobSpawn false` in console, join, and `/tp 0 100 1000` to get far away from spawn chunks. If entities are present, remove with `/minecraft:kill @e[type=!player]`
7. Run `lag` in console and note the number of chunks loaded.
8. Run `/npc create foobar` to spawn an NPC
9. Run `lag` in console again. The number of chunks loaded should have roughly doubled due to the loading of spawn chunks.
10. Leave the server.
11. Run `lag` from console and note the number of chunks loaded.
12. Run `npc delete foobar` from console.
13. Run `lag` from console. There should now be 0 chunks loaded.

**Comment by mcmonkey4eva** [comment]
If this is only replicable with Paper, and not with Spigot, it's questionable whether this should be considered a Citizens issue at all, as that would imply a problem within Paper's codebase, not Citizens.

**Comment by Kev-1** [comment]
In paper, it appears that the NPC is never despawned, causing the chunks to stay loaded. Found out using the `debug: true` option in Citizen's config.

**Comment by Kas-tle** [comment]
I believe this Paper patch might explain what is happening. I did `paper debug chunks` to get chunk info and found there was an ticket placed on chunks with player NPCs or players. Looking into Paper's Spigot patch history, I think it may be the result of [this](https://github.com/PaperMC/Paper/blob/7329e19ce5c470c7daed375aaef39ddf180d5720/Spigot-Server-Patches/0395-Asynchronous-chunk-IO-and-loading.patch#L2475) patch as it was also present in 1.14. From my understanding, any chunk with an open ticket will not be unloaded... but obviously I don't know anything so sorry in advance if I sound like an idiot.

**Comment by mcmonkey4eva** [comment]
Please open an issue @ Paper's GitHub, they'll be able to see whether that's related - and if it is, or if they find a different cause - fix it :D

**Comment by Kas-tle** [comment]
Whelp... https://github.com/PaperMC/Paper/issues/2905 I tried but they seem to be convinced it isn't on their end. Not sure what to make of it.

**Comment by Kas-tle** [comment]
So as of Paper Build #80 this no longer occurs to an extent... spawn chunks being force loaded when a Player NPC is present still persists, so it would appear that has a separate cause. Something in [this commit](https://github.com/PaperMC/Paper/commit/d16a5d8813465b1b03c50adb756b9d324062f1f6) would have to have been the fix... not sure what to be honest, but they did make some modifications to what constitutes a player in the 0395 patch (responsible async chunk loading) so I would think it may be there, but I could be wrong.

**Comment by mcmonkey4eva** [comment]
That... sounds like Paper fixed the key part, and might eventually fix the other part. So... *close button*

**Comment by Drift91** [comment]
This seems to still be an issue on the latest builds of Paper for 1.17.1. Is there some way you can look into the issue further or prod at the devs of Paper on the [relevant ticket](https://github.com/PaperMC/Paper/issues/2905) and explain how the issue is on their end?

I feel like at this point more servers run Paper than Spigot and it's rather unfortunate that a lot of plugin authors insist on only maintaining support for Spigot or in some cases even Bukkit.

**Comment by Kas-tle** [comment]
@Drift91 
This isn't really the authors fault at all though. Paper is a fork of Spigot, so obviously it makes sense for developers to work with the Spigot API, as that is primarily what is available on paper as well. Given that, it is generally expected that Paper won't break things that work on normal Spigot. Paper itself does not add many things relevant to citizens in terms of API. Paper has basically said in the issue you reference they will not change their chunk loading system. This means that if there is a player entity, Paper will load the chunk, and they don't provide any system for unloading those chunks.
