### ISSUE TITLE
[1.15.2] One of the colours in a custom NPC name isn’t appearing

### ISSUE THREAD

**Issue by DeleteMetaInf** [CitizensDev/Citizens2#2034]
One of the colour codes in one of my NPCs’ name isn’t being applied.

Here’s the command I used: `/npc rename &6[&c&lÜber&e&lDonator&6] &rMaster`

![halp](https://user-images.githubusercontent.com/59761487/73310931-8cb33780-4225-11ea-9023-7b3abe64d2fe.png)

The “onator” part is supposed to be bold and yellow (`&e&l`) just like the “D,” but it’s just bold (`&l`). Even though there are no additional formatting codes after the “D,” it just cuts off the colouring, although it’s still bold.

In the chat, the name appears perfectly fine, just as I want it to, but above the NPC, it lacks one colour.
![halp4](https://user-images.githubusercontent.com/59761487/73311076-f03d6500-4225-11ea-8790-aa9260f80197.png)

Removing the `&rMaster` part of the name doesn’t change anything, nor does changing the “Ü” to a “U.” I’ve also tried using the command multiple times, deleting and recreating the NPC multiple times, and restarting my server, but to no avail.

However, removing the final bracket (`&6]`) does cause the colours to appear just fine. 
![halp3](https://user-images.githubusercontent.com/59761487/73311188-267ae480-4226-11ea-842f-73d1890ae6f5.png)

I can’t leave the bracket out of the name, though, so hopefully, a fix for this bug—or a workaround—will be found.

It seem as though there are simply too many colours in this name, which doesn’t happen with name tags on vanilla mobs, on signs, or on anything else I’ve tried. I didn’t hit the character limit as the name is just 34 characters long, and that’s including the formatting codes.

****

As you can see below, I am using the latest version of Minecraft (1.15.2), running a server using the latest version of [PaperMC](https://papermc.io/) (build #83), and using the latest version of Citizens (2.0.26-SNAPSHOT [build 1815]).

The output of command `/version` on my server is:
```
This server is running Paper version git-Paper-83 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

The output of command `/version citizens` on my server is:
```
Citizens version 2.0.26-SNAPSHOT (build 1815)
```

**Comment by mcmonkey4eva** [comment]
This is an issue with the name splitter, iirc I never made it compatible with multiple color codes (ie the `&e&l` would be treated like only `&l`).

The workaround until that's fixed is to just remove the bold.

**Comment by DeleteMetaInf** [comment]
Another workaround is to just add more colour codes. It eventually appears correctly. ☕️
