### ISSUE TITLE
[1.15.2] Citizens occasionally appearing in the player list

### ISSUE THREAD

**Issue by DeleteMetaInf** [CitizensDev/Citizens2#2035]
In the player list, my NPCs are periodically briefly appearing, and it’s quite annoying.

[Here’s a video I recorded of this happening.](https://i.imgur.com/PEJeBPC.gifv)

I’m using the plugin [Tab Reborn](https://www.spigotmc.org/threads/tab-1-5-x-1-15-1-reborn.324177/) for a custom player list on my server (which is not yet public), so I don’t know if this would happen in the vanilla player list. I’m assuming it would, though; I don’t think the Tab plugin is at fault here. I could be wrong, though. As you can see in the video, the citizens are still not counted as players as it doesn’t increase the number of players online in the player list.

[Here’s my Citizens config.yml.](https://pastebin.com/raw/eBF0dQg0) It’s unchanged from the default one. I also have [Denizen](https://www.spigotmc.org/resources/denizen.21039/) installed, whose config is also unchanged from the default one.

The output of the command `/version` on my server is:
```
This server is running Paper version git-Paper-86 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

The output of the command `/version citizens` on my server is:
```
Citizens version 2.0.26-SNAPSHOT (build 1815)
```

**Comment by SXRWahrheit** [comment]
Please attempt to replicate the issue without any plugins that affect the list; this sounds like an issue with Tab Reborn.

**Comment by DeleteMetaInf** [comment]
I disabled Tab Reborn, but as I expected, the issue still happens.

[**Video.**](https://i.imgur.com/ZdwkPTL.gifv)

**Comment by DeleteMetaInf** [comment]
I removed Tab Reborn, but as I expected, the issue still happens.

[**Video.**](https://i.imgur.com/ZdwkPTL.gifv)

**Comment by mergu** [comment]
This is an incredibly well-known thing very commonly brought up in the discord. To show people the npc, it has to be added to the tab list for a tick. This is unavoidable. You might not notice it on massive servers because they fill the tab list with players, but it's an issue everywhere.
