### ISSUE TITLE
Can someone help, please?

### ISSUE THREAD

**Issue by sagenthings** [CitizensDev/Citizens2#2036]
I am using the same save.yml file from my previous version of the plugin. I updated the .jar file and know am not seeing any npcs when I launch the server. can anyone please help me? the logs don't give any warning or error so i am very confused.

**Comment by Kas-tle** [comment]
Enable debug mode in the config and see if you get anything? Also if you could post the startup log w/ debug enabled.

**Comment by sagenthings** [comment]
Okay I will definitely try that. Thank you! I'll post in the Discord moving forward.

**Comment by mcmonkey4eva** [comment]
Yes, use the Discord. If you at any point post again on this GitHub issues page, please be sure to follow the issue template next time.
