### ISSUE TITLE
CITIZENS NPC NOT SPAWNING

### ISSUE THREAD

**Issue by felixgames097** [CitizensDev/Citizens2#2039]
Help me please!!!
When I run command '/npc create flsmdfr' say:
![Minecraft 1 12 2 2020-02-02 19 01 13](https://user-images.githubusercontent.com/60579848/73612726-6fe47e80-45ee-11ea-8446-07d19a5be391.png)
I don't know how to solve-it. Help. I also tried to create another world with multiverse but it dosen't worked.

The output of command `/version` on my server is: 
![Minecraft 1 12 2 2020-02-02 18 51 35](https://user-images.githubusercontent.com/60579848/73612593-5131b800-45ed-11ea-8e5e-50bfff766f4f.png)

The output of command `/version citizens` on my server is: 
![Minecraft 1 12 2 2020-02-02 18 52 49](https://user-images.githubusercontent.com/60579848/73612608-6c9cc300-45ed-11ea-970e-1261a38b67ab.png)

The log of my server is:
https://pastebin.com/Tq9iVwex

The console of  my server is:
https://pastebin.com/6T6hbdU0

**Comment by mergu** [comment]
You're running an unsupported server and you're running it in offline mode. Citizens is built for Spigot/Paper, and you must run a non-cracked server to receive support.

**Comment by felixgames097** [comment]
![Opcions _ Aternos _ Servidor gratuït de Minecraft y 6 páginas más ‎- Microsoft Edge 2020-02-02 20 38 42](https://user-images.githubusercontent.com/60579848/73614059-0a978a00-45fc-11ea-9b5a-5543f4463144.png)

**Comment by mergu** [comment]
```
[17:19:37] [User Authenticator #1/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player Felix_Kreeper is 6bcacd97-9f9e-37da-b162-95203c2be0b7
```
An offline uuid is one that looks like `xxxxxxxx-xxxx-3xxx-xxxx-xxxxxxxxxxxx`. The 3 there means it's being generated rather than authorized through mojang servers. Unless your server is behind an auth proxy and is just misconfigured, you are allowing non-authenticated accounts to join your server which is a massive security vulnerability. Someone can very easily join your server under an opped username and do anything they want, since the UUID maps to the opped account.

Also note, again, Citizens doesn't support whatever Magma is. If Magma is supposed to be compatible with Spigot/Paper plugins, you need to contact them.

**Comment by felixgames097** [comment]
![Magma Foundation y 1 página más ‎- Microsoft Edge 2020-02-03 13 26 01](https://user-images.githubusercontent.com/60579848/73653120-c1414c00-4688-11ea-8c21-a9ca4198ee88.png)

**Comment by felixgames097** [comment]
do i have  to activate the cracked mode?

**Comment by felixgames097** [comment]
> you are allowing non-authenticated accounts to join your server which is a massive security vulnerability.

i have crack mode disabled.

**Comment by SXRWahrheit** [comment]
Magma is not officially supported by Citizens. Again, your server is in offline-mode. If you want help using Citizens with Magma and with a server running in offline-mode, you'll have to seek it elsewhere.

Additionally, Aternos is an unreliable server host that does not give you full control over your server. You should also consider paying money for an actual host. It's typically recommended that you rent a VPS.

**Comment by mergu** [comment]
Yet your logs clearly indicate you are allowing non-authenticated accounts to join your server which is a massive security vulnerability. I'm not doing this silly back and forth where I repeat myself. Run Spigot or Paper, and figure out why your server has this vulnerability before it gets rekt.
