### ISSUE TITLE
Npc disapears disappears

### ISSUE THREAD

**Issue by Oniromancie** [CitizensDev/Citizens2#204]
Version: 1.8.1 Spigot lastest build
Citizen Build:  2.0.14
I've created a simple Npc with 3 sentence. Everything is going fine, but when I'm going out of the chunk for more than a minute the Npc isn't there anymore, but is still there at the same time. When I go close by I can see his text and when I do /reload I can't see him again. No erros in the console.
![image](https://cloud.githubusercontent.com/assets/10610585/5814061/f6aea9bc-a054-11e4-9b26-21f71d16da50.png)
![image](https://cloud.githubusercontent.com/assets/10610585/5814062/05d521fa-a055-11e4-83f8-6b1acbf2c80f.png)

**Comment by mcmonkey4eva** [comment]
Update Citizens to latest dev build.

**Comment by Oniromancie** [comment]
I'm using the latest dev build.

**Comment by goodsense** [comment]
i have same problem

**Comment by CKGAR** [comment]
Confirmed, NPCs lose skins and Citizens disguised as mobs disappear entirely. This is very frustrating, and seems like it's a problem with every build of Citizens I've ever had :/

**Comment by TagCraftMC** [comment]
Just experienced the issue as well when running Citizens #1206 and Spigot 1.8 (b1e6da1-17962f6).
We have 4 simple Horse NPC's in a stable, when entering the area I see only 2 are visible, the other two are still "there" just unable to be seen. I can still use the /npc select command to select it.
Running /npc tphere reload fixes the visibility on the selected NPC.
The Effected Horses save data: http://pastebin.com/bu884uku
Images of Invis Bug + TP "fix";
http://i.gyazo.com/fcfc98152543215186dea1a88b92c4d3.png
http://i.gyazo.com/eebd4185cee2e4d5f5e1d519f6b9bff4.png

Thanks.

**Comment by Vzdevek** [comment]
Same here... Any news?

**Comment by CKGAR** [comment]
I've been patiently waiting. This problem still persists, with citizens either disappearing/losing skins. There are no error logs. I'm pretty sure this should be looked into ASAP because, you know, SEEING the NPCs are kind of important :P

**Comment by fullwall** [comment]
Duplicate: this is a known issue however.
