### ISSUE TITLE
Names showing up even when set to false

### ISSUE THREAD

**Issue by Insprill** [CitizensDev/Citizens2#2040]
When i'm using a scoreboard plugin (linked at bottom) the NPC names appear even though they are set to no show. And on one of my other servers i dont have the scoreboard plugin but it still shows the names no matter what. No errors in console

The output of command `/version` on my server is: **git-paper-89 (MC: 1.15.2) (API Version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1812)**

Scoreboard plugin: https://www.spigotmc.org/resources/scoreboard.14754/

**Comment by mergu** [comment]
This is an issue with how their scoreboard system works, not with citizens. See https://wiki.citizensnpcs.co/Plugin_Conflict and open a ticket with them.

**Comment by Insprill** [comment]
Did u read the second part?

**Comment by Insprill** [comment]
on one of my other servers i dont have the scoreboard plugin but it still shows the names no matter what. No errors in console

**Comment by mergu** [comment]
For the other server, please post a full server log. I'm guessing you have something that messes with scoreboards there too.

**Comment by mcmonkey4eva** [comment]
Contact the developer of that scoreboard plugin (ideally send them the plugin_conflict wiki link) to request they resolve the issue.
