### ISSUE TITLE
Infinite loading of chunks

### ISSUE THREAD

**Issue by Dymeth** [CitizensDev/Citizens2#2041]
Some chunks are loaded due to Citizens and are unloaded the next tick. Thus, the same chunk is loaded 10 times per second. I have 3 similar chunks on my server.

Chunks loading stack: https://pastebin.com/raw/amTT8SK1
Chunks unloading stack: https://pastebin.com/raw/gkpdfrVL

> version
This server is running Paper version git-Paper-90 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-88 (MC: 1.15.2)
You are running the latest version

> version Citizens
Citizens version 2.0.26-SNAPSHOT (build 1815)
Website: http://www.citizensnpcs.co
Author: fullwall

**Comment by mcmonkey4eva** [comment]
This seems much more likely to be an issue with Paper than with Citizens. A chunk being unloaded the very tick after it's read from is... not proper behavior, and I don't think Minecraft's native chunk handler would do something so messy - or at least I hope it wouldn't. Paper has a fairly customized chunk handler.

Can you replicate this issue at all on Spigot?

**Comment by Dymeth** [comment]
The problem is not with Paper, since Spigot has a same situation.

Chunks loading stack: https://pastebin.com/raw/XNTASQZp
Chunks unloading stack: https://pastebin.com/raw/kVjYETwu

Of course, the chunk should not be unloaded to the next tick after loading.
But there is another problem - the chunk should not load by Citizens.

It will take me some time to provide the minimum necessary set of information to reproduce the problem.
Working with Citizens is fully done by my plugin - perhaps the problem is in it. But even so - Citizens should prevent such incorrect actions.
Also, I do not exclude that this situation is connected with some features of the world on the server.
In any case, I will let know when it becomes possible to provide more information.

>version
This server is running CraftBukkit version git-Spigot-c574e08-c985389 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

>version Citizens
Citizens version 2.0.26-SNAPSHOT (build 1815)
Website: http://www.citizensnpcs.co
Author: fullwall

**Comment by Dymeth** [comment]
I was able to find out that the problem occurs when try to apply the NPC skin, which is located on the block that adjoins the unloaded chunk.
I set skins using the SkinnableEntity.setSkinPersistent().
This code helped to avoid the original problem:
```
    private static boolean isSkinsAllowed(@Nonnull Location location) {
        int minBlockX = (location.getBlockX() >> 4) << 4;
        int minBlockZ = (location.getBlockZ() >> 4) << 4;
        int maxBlockX = minBlockX + 15;
        int maxBlockZ = minBlockZ + 15;
        World world = location.getWorld();
        if (isSkinsIgnored(location.getBlockX(), minBlockX, world, minBlockX - 1, location.getBlockZ())) return false;
        if (isSkinsIgnored(location.getBlockX(), maxBlockX, world, maxBlockX + 1, location.getBlockZ())) return false;
        if (isSkinsIgnored(location.getBlockZ(), minBlockZ, world, location.getBlockX(), minBlockZ - 1)) return false;
        if (isSkinsIgnored(location.getBlockZ(), maxBlockZ, world, location.getBlockX(), maxBlockZ + 1)) return false;
        return true;
    }

    private static boolean isSkinsIgnored(int currentBlockPos, int borderBlockPos, @Nonnull World world, int blockX, int blockZ) {
        return currentBlockPos == borderBlockPos && !world.isChunkLoaded(blockX >> 4, blockZ >> 4);
    }
```

**Comment by mcmonkey4eva** [comment]
Is this still a problem on latest builds of Citizens from https://ci.citizensnpcs.co/job/Citizens2/ ?
