### ISSUE TITLE
Npc's Won't Create or Nothing with /npc will happen and there 

### ISSUE THREAD

**Issue by clashyslime** [CitizensDev/Citizens2#2042]
The output of command `/version` on my server is: **(PLEASE FILL IN)** 1.13.2
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** 2.0.24-snapshot build 1591

I am working on an aternos server with the version of 1.13.2 and wanted to use the citizens plugin. I have the plugin, but when using the commands nothing happens in chat or in the game in general.I have also realised there is no config file for citizen when downloading. pls help
https://mclo.gs/21CzEbD and there is no config file only a a .jar
citizens: 2.0.24 (MC 1.10 - 1.13.2)      spigot: 1.13.2
how do i find specs, 0 npcs and idk the others srry im bad at things like this

pls help

**Comment by SXRWahrheit** [comment]
Your version of Citizens is over 200 builds out of date. You must update.

https://ci.citizensnpcs.co/job/Citizens2/

**Comment by clashyslime** [comment]
How do I do that

**Comment by SXRWahrheit** [comment]
Replace the jar file on your server with an updated copy from the link I provided.

**Comment by clashyslime** [comment]
I am using aternos

**Comment by SXRWahrheit** [comment]
The only way to get Citizens to work on your server is to update it. We can't do that for you. This is not a problem with Citizens.

**Comment by clashyslime** [comment]
Ok

**Comment by clashyslime** [comment]
The host says they won't update because the pluggin updates are now paid :/
thanks anyways.

**Comment by mcmonkey4eva** [comment]
I strongly recommend switching to a different server provider. Even just homehosting will be much, much better to deal with than janky freehosts like Aternos.

Also, Citizens is free.

**Comment by clashyslime** [comment]
Ok ty
