### ISSUE TITLE
recommend make panda sit and make it can eat food

### ISSUE THREAD

**Issue by nnnnssss7723** [CitizensDev/Citizens2#2043]

**Comment by fullwall** [comment]
It should eat if it has bamboo and is sitting.

**Comment by mcmonkey4eva** [comment]
Commit https://github.com/CitizensDev/Citizens2/commit/e52f616a4b0da3c70130de4778cab258f6225265 from fullwall
Adds `/npc panda -s` to make a panda sit
This new command is available in builds 1825+ from https://ci.citizensnpcs.co/job/Citizens2/
