### ISSUE TITLE
NPC Animation not saving.

### ISSUE THREAD

**Issue by Misio12320** [CitizensDev/Citizens2#2044]
The Citizen animation is saved but does not load in restart/rejoin server. I have set sleeping to true and it does not load. Everything works without it. And if I execute command /npc sleep it says NPC was arleady sleeping and is now standing..
Server log: https://pastebin.com/LfpDeBaf
Citizen config: https://pastebin.com/BA9tQ6NQ
Citizen's saves file: https://pastebin.com/n8qAAZ20
Server version: This server is running Paper version git-Paper-102 (MC: 1.15.2)
Citizens version: Citizens§f version §a2.0.26-SNAPSHOT (build 1815)
Image after player rejoin/restart server: 
![2020-02-11_16 58 29](https://user-images.githubusercontent.com/42146429/74253777-d1dc6c80-4cef-11ea-82fe-3aadaf777564.png)

**Comment by mcmonkey4eva** [comment]
Not a Citizens issue. This is a Denizen issue.
