### ISSUE TITLE
Commands on spawn/death

### ISSUE THREAD

**Issue by skerit** [CitizensDev/Citizens2#2045]
I've got a feature request. I hope this is detailed enough, it's quite easy to explain :)

I'd like to execute a certain command when an npc spawns or dies.
When it dies, I would need to know who killed it, so a `killer` placeholder would also be needed.

**Comment by mcmonkey4eva** [comment]
What you need is Denizen - https://www.spigotmc.org/resources/denizen.21039/

Denizen and Citizens are supported via the same shared Discord @ https://discord.gg/Q6pZGSR

**Comment by skerit** [comment]
Ok thanks, but that's quite a steep learning curve just to fire a command on npc death :/

**Comment by fullwall** [comment]
What kind of command do you want to run?

**Comment by skerit** [comment]
A console command registered by my custom plugin.

But I've now started implementing an event listener in my custom plugin that listens to the `NPCDeathEvent` there :)
