### ISSUE TITLE
NBT Usage

### ISSUE THREAD

**Issue by Dymeth** [CitizensDev/Citizens2#2046]
Hello!
It would be great to be able to set NPC NBT-tags via api (or even a command).
This is convenient, for example, when using various NBT tag generators. This is a universal format that allows you to do almost anything with the NPC with just one action. I think it would be convenient for many people

**Comment by mcmonkey4eva** [comment]
That's... not really relevant to Citizens? If you want NBT set on the entity via API... just do that? There's no reason for Citizens to be in the middle. To persist it, make your own trait.
