### ISSUE TITLE
Turtle > linear > path in open water thinks it's stuck at biome change

### ISSUE THREAD

**Issue by gmalone** [CitizensDev/Citizens2#2047]
Paper 1.14.4  latest Citizens (Feb 12, 2020)

Giving a turtle a path that starts in a beach biome, then moves through open water eventually reaching ocean biome, the turtle performs stuck action (teleports long distance across ocean) when hitting margin of ocean biome.  

I've tried with stuck action set to true and false.  Turning off the default stuck action results in turtle turning around and going back to start of path when it reaches ocean biome.  Stuck action = true results in turtle teleporting far across ocean biome.

Observation:  the 'problem' seems to occur at any biome change, not just beach -> ocean.  Have seen same issue when changing from ocean -> deep ocean, ocean -> beach, etc. 

Observation:  making turtle controllable shows similar biome change issue, except that instead it dumps its rider at the biome changeover point.

Waypoints are valid and unobstructed -- even routed them around all tall seaweed.

No triggers.

Have tested dozens of times, trying all variants of settings.

Here is turtle's config:  https://pastebin.com/gY77HyiC

Thanks.

**Comment by mcmonkey4eva** [comment]
Please follow the issue template and provide the information requested in the format requested (refer to template @ https://raw.githubusercontent.com/CitizensDev/Citizens2/master/ISSUE_TEMPLATE )

Also, please test and clarify:
- Is this specific to turtles, or will a similar issue happen with eg a player NPC?
- Is this truly a *biome* thing, or is it a deep water vs shallow water thing (ie does just digging the ground out change things)?

**Comment by fullwall** [comment]
Fixed
