### ISSUE TITLE
Unsafe enchanted armour being reset on restart.

### ISSUE THREAD

**Issue by trickman325** [CitizensDev/Citizens2#2048]
- When you give npc's unsafe enchanted items (e.g. prot 10 armour) they reset them to the highest safe value on restart (e.g. prot 4 armour). This is happening for both armour and weapons.
I also have these npc's set as sentinels that trigger on pvp trigger.

- Nothing in console on restart.

Server version: 
CMI 8.6.19.3 BungeeCord
Paper(107) 1.15.2-R0.1-SNAPSHOT
Vault version 1.7.3-b
Citizens version: 
Citizens v2.0.26-SNAPSHOT (build 1813)

**Comment by mcmonkey4eva** [comment]
That's... odd

The relevant code that handles that:
https://github.com/CitizensDev/CitizensAPI/blob/139b4c990d87b6b5ce7cdc0236cbe3686a13eadd/src/main/java/net/citizensnpcs/api/util/ItemStorage.java#L283-L286
```java
        if (root.keyExists("enchantments")) {
            Map<Enchantment, Integer> enchantments = deserialiseEnchantments(root.getRelative("enchantments"), res);
            res.addUnsafeEnchantments(enchantments);
        }
```
Very specifically uses unsafe enchantments.

-----

Side note, not likely to be related, but CMI is known to break things, as can be seen by your "server version" containing CMI (ie it's shoving itself in where it doesn't belong). Please remove CMI from your server. If you need any functionality within it, please find any other plugin that achieves the same things that you actually need from it (eg Essentials).

**Comment by trickman325** [comment]
Well CMI is what I’m actually using for enchanting.
It only happens for npcs which havevthe armour on and weapons in hand

**Comment by mcmonkey4eva** [comment]
I can replicate this issue in local testing, definitely broken somewhere / somehow. It's saving to file with the correct value, just loading back in wrong.

**Comment by trickman325** [comment]
hmm thats strange, any ideas of what could be causing it?

**Comment by mcmonkey4eva** [comment]
This should be resolved in builds 1824+ from https://ci.citizensnpcs.co/job/Citizens2/
by commit https://github.com/CitizensDev/CitizensAPI/commit/41941458834ea7aa9b356a2edac4eed4415953b4 from fullwall
