### ISSUE TITLE
NPCs sometimes spawn randomly and without their items

### ISSUE THREAD

**Issue by TheLastBlockbender** [CitizensDev/Citizens2#2049]
I'm using sentinel and have the respawn time set to 0. I have soldiers that spawn in automatically though with denizen spawning them in very specific instances. Once in a while, however, some NPCs spawn in randomly when they aren't supposed to and they spawn in without their held item. Even when they do spawn in when they are supposed to, they still sometimes spawn in without their held item. I can't pinpoint why some NPCs lose their items or "mis" spawn more often than others, but I do notice that it tends to be the NPCs that have positions a little farther from the "pack"
Server Log: https://pastebin.com/CePV8S62
Citizens Config: https://pastebin.com/Xs9pqXP3

The output of command `/version` on my server is: git-Paper-112 (MC: 1.15.2)
The output of command `/version citizens` on my server is: 2.0.22-SNAPSHOT (build 1822)

**Comment by mcmonkey4eva** [comment]
Could you try to narrow down whether it's a script causing that or not (ie see if NPCs ever randospawn without the script involve).
If you can't replicate without a script: it's not a Citizens issue, it's a script issue.
If you can replicate that way: we'll need details on as much of the setup as possible when replicating through Citizens alone

**Comment by TheLastBlockbender** [comment]
Well one thing I know for sure is that the scripts that spawn the NPCs only spawn them in groups of 10. I have groups of NPCs in server flags. None of my scripts spawn one off NPCs. And they definitely do not have anything to do with the items they are holding. I manually equipped each NPC with their items and haven't messed with them. Sometimes, their items disappear though. Also, I'm realizing that whenever an NPC spawns when it isn't supposed to, it loses its item 100% of the time.
