### ISSUE TITLE
Cant click NPC. Console error

### ISSUE THREAD

**Issue by Duqino** [CitizensDev/Citizens2#205]
Hello,

One of my members has a problem that he cant click a NPC. Everything was working 5 min before this happens.

http://pastebin.com/6xwhmyjN

King regards,

Dutchy.

**Comment by mcmonkey4eva** [comment]
I'd say that's a hypermerchant error, though you failed to post the entire error, just a small snippet of it.

**Comment by Duqino** [comment]
Hmm ill post it there to.

Even do -> http://pastebin.com/RcUgg7jt

**Comment by mcmonkey4eva** [comment]
Yup. Report this to the Hypermerchant team, it's an error on their end, not ours.

**Comment by Duqino** [comment]
Oke thanks for the info.
