### ISSUE TITLE
Error occurred while enabling Citizens

### ISSUE THREAD

**Issue by LFMJUN** [CitizensDev/Citizens2#2050]
The output of command `/version` on my server is: **( This server is running Akarin version git-Akarin-"9c4d9da" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[15:29:21 INFO]: Previous version: git-Paper-525 (MC: 1.13.2)
[15:29:21 INFO]: Error obtaining version information
)**
The output of command `/version citizens` on my server is: **( Citizens version 2.0.24-SNAPSHOT (build 1605)
[15:29:47 INFO]: Website: http://www.citizensnpcs.co
[15:29:47 INFO]: Authors: aPunch and fullwall
)**

Server log https://pastebin.com/ZSzf0kuJ

**Comment by LFMJUN** [comment]
citizens config https://pastebin.com/QvhgrSVS

**Comment by fullwall** [comment]
Update Citizens

**Comment by LFMJUN** [comment]
Thanks.
