### ISSUE TITLE
Console ERROR

### ISSUE THREAD

**Issue by WothRiss** [CitizensDev/Citizens2#2052]
[Citizens] Missing preferred location bundle.

**Comment by mcmonkey4eva** [comment]
Not an error.

That message just means there isn't a translation of Citizens into your system's default language, and so it will default to English.

Refer also to any of the many times people have posted this same issue: https://github.com/CitizensDev/Citizens2/issues?utf8=%E2%9C%93&q=is%3Aissue+preferred+location+is%3Aclosed+
