### ISSUE TITLE
Make flying NPCs ignore gravity by default

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2053]
The output of command `/version` on my server is: **git-Paper-120 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1812)**

When you create an NPC that is of an entity-type which can fly (e.g. Bat or Bee) then they still have gravity enabled by default which looks odd, when the entity suddenly falls down to the ground when summoned in the air.
This adds additional steps as you now have to first disable gravity through `/npc gravity` and then teleport it to its actual position (if you didn't prevent the NPC falling down that is).

My suggestion now is to allow those types of NPCs to have gravity disabled by default. Or alternatively have an additional argument (`--gravity <boolean>`) for the create command, to directly alter an NPCs gravity attribute.

**Comment by fullwall** [comment]
Done
