### ISSUE TITLE
I am unable to use the citizen command without it giving me a link to this website to report issues

### ISSUE THREAD

**Issue by Avagreystone** [CitizensDev/Citizens2#2058]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by mcmonkey4eva** [comment]
Please actually post an issue and follow the issue template... or just not post. Posting "I have a problem" will achieve nothing, we can't reach through the screen and fix everything for you.
