### ISSUE TITLE
Add ability to set NPCs skin from a png in plugin folder

### ISSUE THREAD

**Issue by Insprill** [CitizensDev/Citizens2#2059]
I would love for you guys to add a feature where there is a folder in the plugins main folder and in their you could put in a skin picture, and then set an NPCs skin from that.  Because changing your skin multiple times when setting NPCs skins and then having them all change even when they shouldn't is really annoying :P

The output of command `/version` on my server is: **Paperspigot 1.15.2 build 123**
The output of command `/version citizens` on my server is: **2.0.206 build 1812**

**Comment by mcmonkey4eva** [comment]
Check out https://wiki.citizensnpcs.co/Skins

At the bottom is a link to a Denizen script here -> https://forum.denizenscript.com/viewtopic.php?f=13&t=241 that lets you dynamically set an NPC's skin from any image URL (eg an image uploaded to imgur or Discord... or just anywhere that lets you use a direct link)
