### ISSUE TITLE
Problem with Waypoints

### ISSUE THREAD

**Issue by TakoMT** [CitizensDev/Citizens2#206]
If I create an NPC and set it's waypoints (either linear or wander)... as a Type Player it works fine. If the NPC is killed, on respawn it will resume the waypoints.

 But if the NPC is... say a wolf... if it is killed and respawns... he will spawn and not move. Waypoints are ignored.

Funilly enough he resumes when i log out and in again, or if I go far away then return to the NPC.

**Comment by mcmonkey4eva** [comment]
Is this still an issue on 1.8.3?
