### ISSUE TITLE
ScoreboardTrait issue (Glow color)

### ISSUE THREAD

**Issue by MrGraycat** [CitizensDev/Citizens2#2062]
Hello

General info:
Server version: git-Spigot-79a30d7-acbc348 (1.12.2 final build)
Citizens version: 2.0.26 SNAPSHOT (build1840)
Configuration: Default just created an npc on a frsh test server with only Citizens, PlaceholderAPI and Vault installed. Then used the glowing command on it.

Issue:
The issue is that /npc glowing --color color won't change the color.
I did some testing on my own and found out that when using 2.0.22 SNAPSHOT (build 1547) it does work. 
Perhaps due to the change in scoreboard values between 1.12.2 and higher versions?

Thanks
MrGraycat (Nick)

**Comment by MrGraycat** [comment]
I've looked at the source code and it seems inside ScoreboardTrait.class the SUPPORT_GLOWING_COLOR never gets set to false (since if it's false it will run the code that does work for 1.12.2) maybe add a check to see if the server itself is 1.12.2 or lower to set it to false?

**Comment by fullwall** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/ScoreboardTrait.java#L78

**Comment by MrGraycat** [comment]
I noticed that but it doesn't trigger?

**Comment by MrGraycat** [comment]
Found the issue read update above

**Comment by fullwall** [comment]
Does the latest build help?

**Comment by MrGraycat** [comment]
> 
> 
> Does the latest build help?

Yes this does solve this issue.

Thanks!
