### ISSUE TITLE
(1.15.x Only) Villager NPC's shaking their heads when right clicking.

### ISSUE THREAD

**Issue by 0fficerMike** [CitizensDev/Citizens2#2063]
So what happens is when I right-click on my villager NPC with the plugin Citizens CMD installed
The villager will shake his head, this happens in normal Minecraft too when a villager is saying like "No" if they can't trade. I only had this problem since I upgraded my server from 1.14.4 to 1.15.1, I never had that problem in 1.14.4. I asked in the discord of Citizens CMD and they said to me that I should report it here. No errors are given in the console.

Citizens config: **https://pastebin.com/5EcaXJ4q**
The output of command `/version` on my server is: **This server is running Paper version git-Paper-129 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-118 (MC: 1.15.2)
You are 2 version(s) behind**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1832)Website: http://www.citizensnpcs.coAuthor: fullwall**

**Comment by mcmonkey4eva** [comment]
Delete `Citizens CMD`. That is not a plugin you should ever be using. If you want to add click commands to NPCs, use `/npc command add [...]`, which is a feature of Citizens itself.

**Comment by Luis-Houston** [comment]
When trying to do /npc command add /warp spawn nothing happens. There seems to be no command added.

**Comment by fullwall** [comment]
@Luis-Houston /npc command add warp spawn

**Comment by mcmonkey4eva** [comment]
Probably actually `/npc command add -p warp spawn`

**Comment by Luis-Houston** [comment]
this worked thanks!

**Comment by 0fficerMike** [comment]
This problem is even there without CitizensCMD, it has nothing to do with it.

**Comment by mcmonkey4eva** [comment]
@0fficerMike Me saying to delete CitizensCMD has nothing to do with the issue either. You mentioned you are running a plugin that strongly should never have existed in the first place. Get rid of it.

**Comment by fullwall** [comment]
Fixed in latest build
