### ISSUE TITLE
Add nbt_attributes and script in NPC drops of save file

### ISSUE THREAD

**Issue by sentsuetrong** [CitizensDev/Citizens2#2064]
Hello, This is my first issue for feature request so
I am using Citizens2, Sentinel, Denizen and I found out that I can't make them drop an item with **nbt_attributes** and **script** (script tag is from denizen for events handler thing)
I would like to see this in the next feature of Citizens 2

Thanks
Suetrong.S (Zen)

The output of command `/version` on my server is: git-Paper-126 (MC: 1.15.2)
The output of command `/version citizens` on my server is: 2.0.26-SNAPSHOT (build 1844)

**Comment by fullwall** [comment]
So you're asking for serialising the NBT tag from the item?

**Comment by mcmonkey4eva** [comment]
Mainly asking about attributes: https://minecraft.gamepedia.com/Attribute
but seems to have thrown in a request for generic serialization support too

**Comment by fullwall** [comment]
I have implemented attribute serialisation

**Comment by sentsuetrong** [comment]
oh i see, the latest already have attribute serialisation,
then just only script tag from denizen that hasn't been done yet.
thanks for the hard working.
