### ISSUE TITLE
Citizens crash

### ISSUE THREAD

**Issue by Drc-DEV** [CitizensDev/Citizens2#2065]
https://pastebin.com/QMDjnr7f
Console is flodded and hangs.

Paper 1.15.2 (build 130)
Citizens-2.0.26-b1845

**Comment by mcmonkey4eva** [comment]
Looks to be an issue caused by malware that lists itself as `tech.panoply.leaderheads`.

If you believe this is not accurate, please post a full pastebin of your server log (`logs/latest.log`).

**Comment by Drc-DEV** [comment]
If you can define as malware a plugin which just calls a Citizens method..

Leaderheads is a plugin on Spigot https://www.spigotmc.org/resources/leaderheads.2079/

**Comment by mcmonkey4eva** [comment]
Look in the stack trace you posted:
```
[21:17:36] [Paper Watchdog Thread/ERROR]:       tech.panoply.leaderheads.e.a.d.a(d.java:12)
[21:17:36] [Paper Watchdog Thread/ERROR]:       tech.panoply.leaderheads.a.i.m(i.java:74)
[21:17:36] [Paper Watchdog Thread/ERROR]:       tech.panoply.leaderheads.a.i.b(i.java:45)
[21:17:36] [Paper Watchdog Thread/ERROR]:       tech.panoply.leaderheads.a.i.a(i.java:125)
[21:17:36] [Paper Watchdog Thread/ERROR]:       tech.panoply.leaderheads.a.e.run(e.java:5)
```
That `e.a.d.a`, `a.i.m`, etc. is hidden/secret code, which can be generally assumed to be malicious in intent. Legitimate software has no reason to disguise its codepaths that way.

**Comment by RobinDeBaets** [comment]
LeaderHeads is a non-malicious plugin of which I'm the developer.

The code I'm using looks something like this and is called for a **synchronous** thread:
```
if (CitizensAPI.getNPCRegistry() == null) return;
  for (NPC npc : CitizensAPI.getNPCRegistry()) {
    if (!npc.isSpawned()) continue;
       npc.setName(nametag);
       break;
    }
  }    
}
```

**Comment by mcmonkey4eva** [comment]
@RobinDeBaets if your plugin is not malicious in nature, please remove any and all obfuscation. There is no valid reason to obfuscate legitimate code.
