### ISSUE TITLE
Citizens not sitting or sleeping on server restart

### ISSUE THREAD

**Issue by Gamn69** [CitizensDev/Citizens2#2066]
SpigotMC Version = 1.15.2-RO1-Snapshot
Citizens Version = Citizens-2.0.26-b1845
All the citizens (NPCs) that were told to sit or sleep were not sitting or sleeping on server restart.

**Comment by mcmonkey4eva** [comment]
Not a Citizens issue. Possibly a Denizen issue. Probably ask on the Discord, or at least the Denizen issues page not Citizens.
