### ISSUE TITLE
When entering the portal ender

### ISSUE THREAD

**Issue by MrKlarki** [CitizensDev/Citizens2#2067]
Hi! Help me
- If the NPC touches the portal, the server will crash
- log https://pastebin.com/xeKkfdrK

/version
git-Spigot-6de3d4b-fc24934 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
/version citizens
Citizens version 2.0.26-SNAPSHOT (build 1845)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
