### ISSUE TITLE
NPC Invisible/Skin won't change

### ISSUE THREAD

**Issue by Zeuscp1** [CitizensDev/Citizens2#2069]
- When working with NPC Destinations, it has a feature to cache skin for each location, the skins change but they won't update for you unless you get out of visible range of NPC and get close again, or log out and log into the server again. Also, sometimes when the NPC needs to go to a location it becomes invisible and the fix is the same, get out of range or relog. 

Console log-https://pastebin.com/ZQtNEUmC
Citizens config-https://pastebin.com/xukYmmZE

The output of command `/version` on my server is: 
https://ibb.co/2nhsNws
The output of command `/version citizens` on my server is:
https://ibb.co/2W9sF8V

**Comment by mcmonkey4eva** [comment]
Both the described problem and the error in the log are problems caused by `NPC Destinations`, not Citizens. Please report to that plugin's developer.
