### ISSUE TITLE
Error on creation of an NPC

### ISSUE THREAD

**Issue by PintoInformatico** [CitizensDev/Citizens2#2070]
The output of command `/version` on my server is:[18:58:25] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-c8d4cef-1fee35b (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
[18:58:25] [Server thread/INFO]: You are 322 version(s) behind

The output of command `/version citizens` on my server is: [18:58:44] [Server thread/INFO]: Citizens version 2.0.26-SNAPSHOT (build 1845)
[18:58:44] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[18:58:44] [Server thread/INFO]: Author: fullwall

![unknown](https://user-images.githubusercontent.com/61939916/77104150-72226100-6a13-11ea-80a3-8932af7662ff.png)

Hello, i have a server and I can´t create an NPC, when I try it gives me an error, can you try to help me? I can give you the config. Tanks

**Comment by mcmonkey4eva** [comment]
You need 1.14.4, not 1.14.

(Or, better yet, update to 1.15.2)
