### ISSUE TITLE
Feature Request: Allow Mobs to have AI if they are not being instructed to target something

### ISSUE THREAD

**Issue by iarepandemonium** [CitizensDev/Citizens2#2071]
I have need of a citizen npc just doing normal mob things until I tell it to navigate, if it were possible for them to do that, that would be useful

**Comment by mcmonkey4eva** [comment]
Implemented by fullwall via https://github.com/CitizensDev/CitizensAPI/commit/e5fad8b43d903747727a538d11bda948f9730d67 & https://github.com/CitizensDev/Citizens2/commit/0531fe859e7a5aaf865ee7d1bf8b473f7dc14be3 as `npc#setUseMinecraftAI(boolean)`

**Comment by fullwall** [comment]
Bearing in mind that it's only for 1.15.2 at the moment.
