### ISSUE TITLE
Citizens not working and error in console

### ISSUE THREAD

**Issue by JohnsaUnderline2** [CitizensDev/Citizens2#2073]
The output of command `/version` on my server is: **CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)**
The output of command `/version citizens` on my server is: **Citizens v2.0.24-SNAPSHOT (build 1605)**

Citizens is not working and I keep getting an error in console!
https://github.com/CitizensDev/Citizens2/files/4371248/latest.log
config : https://pastebin.com/rgW1Yq1P

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
