### ISSUE TITLE
Missing file "Placeholders"

### ISSUE THREAD

**Issue by Rincewind34** [CitizensDev/Citizens2#2076]
Just a small note that you forgot to check in ...util.Placeholders ;)

**Comment by mcmonkey4eva** [comment]
What?

**Comment by mergu** [comment]
Is this what you mean? Seems to be checked in to me: https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/util/Placeholders.java
