### ISSUE TITLE
Add support for tpto, to have coordinates

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2077]
The output of command `/version` on my server is: **git-Paper-146 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1854)**

`/npc tpto` only supports a playername or NPC id and the alternatives only tp you to the npc (`/npc tp`) or the NPC to you (`/npc tphere`)
While those alternatives are somewhat ok, do they sometimes have issues like that the NPC is always facing the wrong direction (e.g. you face yaw 180 and pitch 0 (north) but the NPC faces 0, 0 (south) when using `/npc tphere`)
Having an option to provide the x, y and z coordinate (and optionally the yaw and pitch) may fix this long-standing issue with NPCs looking into the wrong direction.
It could perhaps be a new arg like `/npc tppos <x> <y> <z> [yaw] [pitch]` to not have too much rework on the TP command itself.

**Comment by Andre601** [comment]
Moved to #2074 as it probably is related to this.

**Comment by mcmonkey4eva** [comment]
The command is `/npc moveto`
