### ISSUE TITLE
/NPC Path not working, NPCs won't walk

### ISSUE THREAD

**Issue by CZ181** [CitizensDev/Citizens2#2079]
The output of command `/version` on my server is: 1.15.2
The output of command `/version citizens` on my server is: 2.0,26-SNAPSHOT

If it matters, I'm running the server on Minehut.

When I use the command /npc path on my NPCs, they don't start walking, they just stand there. This is the sequence of commands I used to make sure it's not clashing with another command, but  I doubt that.

/npc create aaa > /npc path

and then I set the points, the NPC still won't move.

Also tried using /npc create > /npc waypoint provider wander

the NPC still didn't move.

EDIT: It works on villagers, but not on player NPCs.

**Comment by mcmonkey4eva** [comment]
Minehut provides broken builds to users.

Please either get a real server provider (VPS/Dedi) or homehost (ie run the server on your home PC - legitimately a better option than "free" hosts like minehut).
