### ISSUE TITLE
Error Server Stop

### ISSUE THREAD

**Issue by JuuniorSantos** [CitizensDev/Citizens2#208]
Plugin citizens crashes the server, when I create a NPC
Log (Error): http://pastebin.com/08zUuka6
Lob (Complete): http://pastebin.com/ZfUt3pAL

**Comment by calico-kid** [comment]
have you tried updating to the latest everything?

**Comment by mcmonkey4eva** [comment]
Acquire the correct version of Citizens here: http://wiki.citizensnpcs.co/Versions
