### ISSUE TITLE
Problem with NPC skins / Citizens2

### ISSUE THREAD

**Issue by KuznetsMedia** [CitizensDev/Citizens2#2080]
Good afternoon.

I apologize for my English right away, I'm not a native speaker of this language.

Please help me! My problem is this: when I use command /npc skin -t and writing required data, skin on my npc is changes to the wrong skin whose data I entered. Understand correctly, I get the usual skin. But not the one I expected. For getting data about skin i use website "mineskin.org". 

I also tried using a Denizen script, which allows you to use url address skin images on some photostock by type imgur, but this way also not give me a result. 

P.S. When entering the same data into the command block with using command minecraft:give @p minecraft:player_head, skin on head is correctly.

Screenshot with my versions spigot and citizens:
![image](https://user-images.githubusercontent.com/62627555/77825401-dc7d8480-712a-11ea-928d-a54ad892bd31.png)

**Comment by fullwall** [comment]
Update Citizens to latest build and there is a new --url argument for /npc skin

**Comment by mcmonkey4eva** [comment]
If the URL to imgur didn't work, you likely entered the wrong URL (it needs to be one that ends with `.png`, not a gallery URL). Other image hosts, same concept, but a lot of them just don't allow direct URLs. Imgur or Discord are both easiest to get the direct URL with.
