### ISSUE TITLE
/npc pose -a  reset the axis looking when I reload the server.

### ISSUE THREAD

**Issue by HeyImKata** [CitizensDev/Citizens2#2081]
Well, when I create an npc, he looks towards the X axis.
I simply write the following commands : 
/npc create "..."
/npc skin "..." 
/npc rename "..." 
/npc pose -a 

Then I reload, and they are back, all looking towards the same axis.
Is there a way to fix this issue ? do I miss something ? Can we save the pose we set ?

**Comment by mergu** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE

**Comment by HeyImKata** [comment]
Oh sorry. Here is everything, I guess. 
Here is the citizens config and the logs. https://pastebin.com/uJqVqfju


![version](https://user-images.githubusercontent.com/52503728/77861687-a87f8d80-7216-11ea-9f38-31d1151e3ced.png).
Thx.

**Comment by fullwall** [comment]
Can you update to the latest version please?

**Comment by HeyImKata** [comment]
I just downloaded the 2.0.26-Snapshot (build 1857), still doesn't work.
Also, I'm hosting my server on omgserv if it is relevant.

**Comment by mcmonkey4eva** [comment]
Re-apply the pose while on the new build already. Posing from earlier builds won't be recalled in the new build (due to a bit of mixup with rotation logic in the recent few builds).

**Comment by HeyImKata** [comment]
Well I, tried several times. 
By changing the pose, even by creating a new npc. Nothing to do, when I restart they all look towards the same spot. (except the ones with the lookclose trait)
I noticed in the saves.yml that my NPC that have the lookclose trait have a different yaw. I guess it is obvious but the npc without lookclose all have : yaw : '0.0' (which seems also obvious)

Well I give you my saves.yml if you find it useful : https://pastebin.com/sPiKbbKf
Thanks for your answers, they are precious.

**Comment by mcmonkey4eva** [comment]
There's a lot of NPCs there. Which ones are working vs not? Is NPC 142 looking in the correct direction? (It's at the bottom of the list, has a valid yaw set, and doesn't have lookclose)

**Comment by HeyImKata** [comment]
In fact no one that hasn't got the lookclose trait is wrong because they are all aiming the same direction. This one too is aiming towards the same axis. pic 
![Sans titre](https://user-images.githubusercontent.com/52503728/77968559-ee585680-72e7-11ea-8a69-c856d5f761f2.png)

**Comment by HeyImKata** [comment]
Well I simply re-downloaded a second time and I found out that it worked
