### ISSUE TITLE
Cats running away

### ISSUE THREAD

**Issue by DSlyDog** [CitizensDev/Citizens2#2083]
The output of command `/version` on my server is: Paper-145 (git-Paper-145 (MC:1.15.2) Implementing API version 1.15.2-R0.1-SNAPSHOT))
The output of command `/version citizens` on my server is: 2.0.26-SNAPSHOT (build 1852)
Server logs: https://hasteb.in/wefediza.md
Citizens config: https://hasteb.in/wojalagi.yaml

Whenever I spawn in a cat, it seems to run away from its position after a few minutes to somewhere else. I've done some digging, and the location it runs to seems to be set as its position in the config. I've even changed the position in the config and restarted the server, but the cat runs away and a new position appears. This only seems to happen with cats too. I'm not really sure what is causing this to happen.

**Comment by mcmonkey4eva** [comment]
Log repasted to https://one.denizenscript.com/haste/66696 for persistent access (generic hastebin deletes pastes)

You use `/reload` in this log and therefore your issue is invalid.
Reload can and will break things and as such all problems on a server where it's been used will be assumed to be the fault of it. NEVER use `/reload`.

**Comment by DSlyDog** [comment]
> 
> 
> Log repasted to https://one.denizenscript.com/haste/66696 for persistent access (generic hastebin deletes pastes)
> 
> You use `/reload` in this log and therefore your issue is invalid.
> Reload can and will break things and as such all problems on a server where it's been used will be assumed to be the fault of it. NEVER use `/reload`.

Okay, here's a log without a reload. https://pastebin.com/KHyKy9H4 This one starts after the daily restart. The cats started moving around after the daily resets one day, and they move at random.

**Comment by DSlyDog** [comment]
First off, what I copied into pastebin was the entirety of the latest.log, but I'll attach it.
[
[latest.log](https://github.com/CitizensDev/Citizens2/files/4405497/latest.log)
](url)

**Comment by mcmonkey4eva** [comment]
It will be opened when you've provided enough detail for it to be reopened.
That involves a full proper log at a minimum... that log is just player's chatting. That is not a full server log. You may need to restart your server to get a proper log.

**Comment by DSlyDog** [comment]
It is just players chatting, and some sign placement information from GriefPrevention. It is a full log. That is all that has happened today.

**Comment by DSlyDog** [comment]
[2020-03-30-1.log.gz](https://github.com/CitizensDev/Citizens2/files/4405594/2020-03-30-1.log.gz)
[latest(1).log](https://github.com/CitizensDev/Citizens2/files/4405595/latest.1.log)

Okay, I ran a restart. That should be the first log from earlier plus the startup log. And the cat moved at some point between last night and now.

**Comment by mcmonkey4eva** [comment]
You're running a plugin named "MyPet" which is erroring on load. It's quite possible that plugin is messing with pet-mob handling. Try running without that to see if the problem happens without it. Refer also to https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by DSlyDog** [comment]
Huh. MyPet does have Citizens hooks. I'll look into it when I can tomorrow.
