### ISSUE TITLE
Cant access PlayerNPCCommand with modifiers "public"

### ISSUE THREAD

**Issue by DrakePork** [CitizensDev/Citizens2#2084]
On startup we're getting this warning after I tried out the new /npc command on some villagers.

Config - https://pastebin.com/giusjeRr
Warning - https://pastebin.com/WUDSznz7

The output of command `/version` on my server is: **(PLEASE FILL IN)** 1.15.2 | Paper-143
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** 2.0.26-SNAPSHOT (build 1857)

**Comment by fullwall** [comment]
Try latest build

**Comment by DrakePork** [comment]
Yeah is gone
