### ISSUE TITLE
Log repasted to https://one.denizenscript.com/haste/66696 for persistent access (generic hastebin deletes pastes)

### ISSUE THREAD

**Issue by DSlyDog** [CitizensDev/Citizens2#2085]
Log repasted to https://one.denizenscript.com/haste/66696 for persistent access (generic hastebin deletes pastes)

You use `/reload` in this log and therefore your issue is invalid.
Reload can and will break things and as such all problems on a server where it's been used will be assumed to be the fault of it. NEVER use `/reload`.

_Originally posted by @mcmonkey4eva in https://github.com/CitizensDev/Citizens2/issues/2083#issuecomment-606208312_

Reopening the cats issue. Here is a log without reloads: https://pastebin.com/KHyKy9H4

The cats started moving after one of the daily restarts, and when they move it seems to be at random. For example, I spawned in a cat, set it to sitting, added some text, set lookclose and close talker. When I walked away, out of its look zone, it ran off while still sitting.

**Comment by mcmonkey4eva** [comment]
Reply to the existing issue, don't open a new one... certainly not with this mess of a title.
