### ISSUE TITLE
[Suggestion] Improve displaying of Location

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2086]
The output of command `/version` on my server is: **git-Paper-155 (MC 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (Build 1859)**

When using a command that displays the location of a NPC like `/npc moveto` (which prints the location to which the NPC was teleported) does the location appear as `Location{world=CraftWorld{name=world_name},x=0,y=65,z=0,pitch=0.0,yaw=0.0}` which is kinda ugly.
I suggest to make this look more pretty in a way.
Maybe by adding a method to the [StringHelper](https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/util/StringHelper.java) which would take a location as param and then returns a Formatted String in the style of `world_name;x,y,z;yaw,pitch`?

I can PR such a implementation, if needed.

**Comment by fullwall** [comment]
I have just pushed an implementation. Any other places it should run?

**Comment by Andre601** [comment]
I don't know of any other place, where a message containing the location would be shown like that, so I think this is the only one..
