### ISSUE TITLE
Pathfinding Bug, triggers NavigationCompleteEvent to early

### ISSUE THREAD

**Issue by Likqez** [CitizensDev/Citizens2#2087]
- Description: I am using Citizens Pathfinding tool, and its NavigationCompleteEvent. I discovered an error, which triggers the NavigationCompleteEvent before the NPC has reached his target location. It happend after the NPC fell one block down. [Visual representation](https://i.imgur.com/FFrjZtF.jpg).

- Config: https://hasteb.in/yulovicu.yaml
- Code: https://hasteb.in/babasufa.java
- Error: https://hasteb.in/vowojate.md

- Versions: https://i.imgur.com/Xcf6qaA.png

**Comment by fullwall** [comment]
1. Update to the latest Citizens version
2. Run your removal code one tick later due to new Minecraft removal rules.

**Comment by Likqez** [comment]
The CompleteEvent still gets triggered when the npc jumps the given block (first post) down.
Do you have any ideas?
