### ISSUE TITLE
Npc Text Bug

### ISSUE THREAD

**Issue by Shirakamii** [CitizensDev/Citizens2#2092]
The latest version **Citizens 2.0.26 1.15.2 BETA #2** When adding **/npc text** to an Npc it says it applies the text but never actually does anything and doesn't even seem to update the save.yml. No matter how many times i've tried. This bug only recently occurred and does not effect npc text that was set prior to it. I think it broke when i was playing around with pre-set animations mainly 'Sit', Url-- skins and Coloured names e.g &a<name>. Now unable to use /npc text cmd for what ever reason.

command line: /npc text --> add <text> --> range <num> **no output!!!?**

[config.yml.txt](https://github.com/CitizensDev/Citizens2/files/4430433/config.yml.txt)
[saves.yml.txt](https://github.com/CitizensDev/Citizens2/files/4430439/saves.yml.txt)

![Screen Shot 2020-04-04 at 10 58 14 am](https://user-images.githubusercontent.com/63131017/78413515-6cf42180-7663-11ea-9c33-4ed220946c62.png)

![Screen Shot 2020-04-04 at 11 16 09 am](https://user-images.githubusercontent.com/63131017/78414029-ea209600-7665-11ea-9104-06de8f4c30a4.png)

**Comment by mcmonkey4eva** [comment]
Please post your server's `logs/latest.log` file.
