### ISSUE TITLE
Make NPC sneak (API)

### ISSUE THREAD

**Issue by realJongi** [CitizensDev/Citizens2#2093]
The output of command `/version` on my server is: **git-Spigot-cbd1a1b-009d8af (MC: 1.14.4 (Implementing API version 1.14.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1861)**

Hi,
I'm currently trying to create a NPC with the API.
The NPC is spawning correctly but I can't make it sneak.

I've tried using the following code line:

((Player)npc).setSneaking(true); (like in the Denizen SneakingTrait: https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/npc/traits/SneakingTrait.java )

but it isn't working...

How can I make my NPC sneak, without installing "complete" Denizen? Maybe with NMS?

Thanks!

**Comment by mcmonkey4eva** [comment]
Install Denizen, or copy the NMS source from Denizen.

----

`((Player)npc).setSneaking(true); (like in the Denizen SneakingTrait: `
^ Not sure where you got that from, but that's not the code in the link you posted.

**Comment by realJongi** [comment]
Thanks!!
I just recognized that I've used the 1.12 "sneak-code" instead of the 1.14 one.
