### ISSUE TITLE
Plugin attempted to register net.citizensnpcs.trait.Gravity@35582811 while not enabled

### ISSUE THREAD

**Issue by CyberSheppie** [CitizensDev/Citizens2#2094]
I'm filing this because I believe that the Citizens Plugin caused a pretty severe Server Crash for us. According to the Crashlog, this was caused by a Citizen NPC.
Hopefully filing this report can get us some information on what caused this, so we can take steps to resolve the problem.

Server Log: https://pastebin.com/fge8GExG
Crashlog: https://pastebin.com/YS7MkFLQ
Citizens Config: https://pastebin.com/3gD8dz4J
-->

The output of command `/version` on my server is: **CraftBukkit version git-Spigot-c574e08-807a677 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)** (Note. version has now been updated to the latest)
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1812)**

**Comment by mcmonkey4eva** [comment]
Please post your actual full log file, not just a snippet from the end of it.

**Comment by CyberSheppie** [comment]
Here's the full server logs, from start-up to crash
https://pastebin.com/R43M6TGj

**Comment by mcmonkey4eva** [comment]
Yeah that's not a Citizens issue there.

Your server locked up / froze for unrelated reasons. It looks like probably an overload of vanilla monsters.

Spigot has a weird way of improperly shutting down the server after a crash that produces very unrelated errors in the actual crash log.
