### ISSUE TITLE
NPC with 'avoidwater:true' does not avoid water when wandering

### ISSUE THREAD

**Issue by redshirt2** [CitizensDev/Citizens2#2095]
Latest Spigot, Citizens, Denizen

When NPC is set to avoidwater (/npc pathopt --avoidwater true) (and confirmed that NPC has property set, Plots a path that 'likes' water!

This is with NPC using waypoint provider wander, either old or new finder.

With Path debug, we watched as NPC did not avoid water.  We tried two new patches in citizen (1865) and no joy.

Thanks

**Comment by mcmonkey4eva** [comment]
Please follow the issue template.
