### ISSUE TITLE
NPC does not 'avoidwater' when pathing over slabs.

### ISSUE THREAD

**Issue by redshirt2** [CitizensDev/Citizens2#2096]
Previously thought a bug, where NPCs would not 'avoidwater' and create path to walk straight into ocean... discovered that the walking surface was slabs (lower).

NPC does not plot path to avoid water if on a path of lower slabs (like a dock).  Behaviour happens with old or new pathfinder.  Pathing over full blocks or things like carpet or trapdoors seems to be fine.

**REQUEST: please add support for 'avoidwater' while walking on slabs**

![2020-04-08_06 05 54](https://user-images.githubusercontent.com/13760466/78985739-c1295680-7ae6-11ea-8512-7083459e27e9.png)
![2020-04-08_09 39 22](https://user-images.githubusercontent.com/13760466/78985741-c1c1ed00-7ae6-11ea-9cb1-7bb1231861ff.png)

The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-a03b1fd-5838285 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT

The output of command `/version citizens` on my server is: Citizens version 2.0.26-SNAPSHOT (build 1865)

**Comment by fullwall** [comment]
I wasn't able to replicate this behaviour. Can you send a new screenshot with path debug turned on? Also please post your config and server log.

**Comment by mcmonkey4eva** [comment]
Is this problem actually related to avoidwater at all?
As was discussed on Discord, the likely problem is just that NPCs aren't willing to path over bottom-half-slabs

**Comment by fullwall** [comment]
Initially yes, because as you see in the screenshot the NPC is choosing to wander into water. However, I need an updated screenshot after I implemented avoid-water properly.

**Comment by redshirt2** [comment]
In these cases the npc was spawned on a slab:top upper deck.. and then climbed a lower slab rail and plunged in the water. Its like it didn't see water while on a bottom slab.

This might be good enough to show you, But I'm still going to try and replicate when NPC goes to end of dock and dives in.

![2020-04-10_16 02 13](https://user-images.githubusercontent.com/13760466/79026968-b3f08400-7b47-11ea-80bd-4f388ca77e4e.png)
![2020-04-10_16 01 22](https://user-images.githubusercontent.com/13760466/79026971-b521b100-7b47-11ea-951d-07832864021d.png)
![2020-04-10_16 12 48](https://user-images.githubusercontent.com/13760466/79026986-c7035400-7b47-11ea-85aa-46f1a3a362d3.png)




[latest.log](https://github.com/CitizensDev/Citizens2/files/4463546/latest.log)
[config.zip](https://github.com/CitizensDev/Citizens2/files/4463550/config.zip)

**Comment by redshirt2** [comment]
I'm very sorry.  It seems 1865 is working fine.  On my testing of 1865 I did not set the avoidwater.

I appreciate your patience.
