### ISSUE TITLE
Despawn NPC

### ISSUE THREAD

**Issue by Gorderok** [CitizensDev/Citizens2#2098]
With the latest version of PaperSpigot, my citizens disappear randomly
> PaperSpigot 1.15.2  build 167
> Citizens 2.0.26 build 1865

https://pastebin.com/An9bGbw6
https://pastebin.com/xnrcvbWV
https://pastebin.com/5QQ7N0Fg

**Comment by Zzheyd** [comment]
Have same error :s

**Comment by mcmonkey4eva** [comment]
Does this happen on Spigot?

**Comment by Zzheyd** [comment]
For me, i never used spigot, idk :/ only paper

**Comment by Gorderok** [comment]
I don't know, I only use paper too

**Comment by mcmonkey4eva** [comment]
Use Spigot.

If it happens on Spigot, reply below.
Otherwise, this will be assumed to be a Paper issue, and will have to be reported to them (please test & verify before doing so).
