### ISSUE TITLE
Strange 9 and Empty Shop Issue

### ISSUE THREAD

**Issue by TheMaddog** [CitizensDev/Citizens2#210]
I'm not sure if the DtlTrader Github is active so I've decided to post an issue with the DtlTrader module here, please see below. I hope this can be fixed.

Hi not sure if this is a Spigot bug or a DtlTrader bug or even the CitizensCore bug.

When opening a shop, all the items do not display until you click anywhere in the shop inventory.

I don't think I have to get anymore descriptive but basically, player opens shop, it's empty until that player clicks once inside the shop and then all the items that are up for sale display.

You will also notice that there is 9 being spammed in my console, that happens when adding an item to the shop.

Thanks!

https://dl.dropboxusercontent.com/u/16126341/dtltrader_log_ref.log

https://github.com/Dandielo/dtlTraders/issues/47

**Comment by mcmonkey4eva** [comment]
Definitely Dtl, sorry. Hope you get a solution!
