### ISSUE TITLE
The name of a npc AND player is hidden with the command "/npc name".

### ISSUE THREAD

**Issue by csBlackWolf** [CitizensDev/Citizens2#2101]
If the name of a npc is hidden with the command "/npc name", the name of a player with the same name is hidden too.

Config file:
https://pastebin.com/DAUi2caN

The output of command `/version` on my server is: 
This server is running CraftBukkit version git-Spigot-a03b1fd-bbe3d58 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is:
Citizens version 2.0.26-SNAPSHOT (build 1854)

**Comment by mcmonkey4eva** [comment]
Never give NPCs the same name as a player.
At the very minimum, attach a color code, like `/npc create csBlackWolf&f`
