### ISSUE TITLE
Display names in 1.8 not showing

### ISSUE THREAD

**Issue by Joshuak52** [CitizensDev/Citizens2#2102]
-  The server runs 1.8.X -) 1.15.2 but the display names on the NPCs do not show in 1.8
- Citizens Config; https://pastebin.com/2GDJ1R9Y

The output of command `/version` on my server is: **https://gyazo.com/d3d5680a77a2e15000870df2f4bfa5dc**

The output of command `/version citizens` on my server is: **https://gyazo.com/0bed50a218f2aee35ba29aafd3864e04**

**Comment by fullwall** [comment]
Can you update to latest Citizens please?

**Comment by Joshuak52** [comment]
> Can you update to latest Citizens please?

Hi, updated to the latest version: https://gyazo.com/8e40e6541fcef200948e00b0b65780d3
The issue not fixed but now I've run into another.

the NPCs keep wanting to face South and not the direction I'm looking when setting

**Comment by fullwall** [comment]
The latest version is 1866

**Comment by Joshuak52** [comment]
Hi, I'm now on latest version
 https://gyazo.com/7ce6ac663d0e0fcb51f983c5970141b1

but I still can only see the NPCs names when I hover over them:
 https://gyazo.com/30d8f8f9feaedf25ad8daf590c215386
----------

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by Joshuak52** [comment]
Hi, my server is already on the latest version of 1.15.2 running ViaVersion / ViaRewin etc
https://gyazo.com/7775863bca79dbea663984bfbbf23fda

**Comment by mcmonkey4eva** [comment]
Does the problem show up in a 1.15.2 client?

**Comment by Joshuak52** [comment]
No, issue stops after 1.9 and above all the way to 1.15.2
only in 1.8.X this issue occurs.

**Comment by mcmonkey4eva** [comment]
Then it's a ViaVersion problem.

**Comment by Joshuak52** [comment]
Hi, I've switched the ProtocolSupport plugin but I still get this issue ONLY on 1.8.X
am I just out of luck or anything else to try? Thank you!

**Comment by mcmonkey4eva** [comment]
Stop running such a mixed mess of versions. Run 1.15.2 clients on your 1.15.2 server. Problem solved!

**Comment by fullwall** [comment]
Wasn't custom name always visible only added in 1.9+?
