### ISSUE TITLE
NPE on Citizens Default

### ISSUE THREAD

**Issue by Driftay** [CitizensDev/Citizens2#2104]
The output of command `/version` on my server is: **1.8.8 Taco Spigot**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1868)**

Default config throws NPE when creating an NPC

[message (36).txt](https://github.com/CitizensDev/Citizens2/files/4476989/message.36.txt)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8
