### ISSUE TITLE
Can't modify npc speed with citizen api controllable trait.

### ISSUE THREAD

**Issue by SickUsernameBrah** [CitizensDev/Citizens2#2106]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-114 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1866)**

When creating a mount other then a horse, for example a pig, the pig's speed doesn't get modified with the `getNavigator().getDefaultParameters().speedModifier()` when you are using the controllalbe trait. 
I system printed the speed and that gets modified but the actual speed of the mount is the same with whatever number of speed modifier I use.
I also debugged the `updateHorizontalSpeed` function inside the controllable trait and speed mod gets updated in there correctly but the speed is always around 9-11 m/s no matter how high I set the speed modifier

**Comment by fullwall** [comment]
Try latest build

**Comment by SickUsernameDude** [comment]
Same issue on latest build. (new account since kinda got locked out of old account...)
