### ISSUE TITLE
Server crashes randomly

### ISSUE THREAD

**Issue by csBlackWolf** [CitizensDev/Citizens2#2107]
Server crashes randomly. No information at the server log.
But it looks like it has something todo with Citizens.

Crash report:
https://pastebin.com/Levg0J2y

Config:
https://pastebin.com/DAUi2caN

Saves:
https://pastebin.com/5CJNrLc9

CraftBukkit version git-Spigot-a03b1fd-bbe3d58 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Citizens v2.0.26-SNAPSHOT (build 1854)
Sentinel v2.0.1-SNAPSHOT (build 327)

**Comment by mcmonkey4eva** [comment]
That's unlikely to be related to Citizens.

If you believe it is, post your full `logs/latest.log` below. (Which is where the actual error message will be)

**Comment by csBlackWolf** [comment]
In the last log is no information about it. The server just crashed abruptly.

Log:
https://pastebin.com/3ZRUGutF

> That's unlikely to be related to Citizens.

If i look on the crash, it seems to me like there is at least a error what has something to do with Citizens.
I just can't say if it related with the crash.
But if it displayed in the crash log, i would think there could be a relation.

But i just noticed that my minecraft server memory is full. It could be responsible for the crash. I'll try again with more RAM.

**Comment by mcmonkey4eva** [comment]
Further support refused due to intentionally falsified log.
