### ISSUE TITLE
False accusation

### ISSUE THREAD

**Issue by csBlackWolf** [CitizensDev/Citizens2#2108]
Why is my ticket marked as spam and further support refused?
I only have remove information/user-data i am not allowed to make public by the data protection low from Germany and my policies. And for this the support got refused?

Nothing else from the log has been modified.
https://github.com/CitizensDev/Citizens2/issues/2107#issuecomment-614079201

**Comment by mcmonkey4eva** [comment]
"False accusation"
You intentionally falsified the contents of the log you posted. That is unarguably true.
No real logs generate nonsense like
```
[06:17:46] [User Authenticator #3/INFO]: UUID of player {PLAYERNAME} is {UUID OF PLAYER}
[06:17:47] [Server thread/INFO]: {PLAYERNAME}[/{IP:PORT}] logged in with entity id 44635 at ([world]118.43140762992367, 70.0, -2427.37640494241)
```
That's very clearly you falsifying the contents of the log.

We can and will refuse any and all support to users that intentionally falsify log contents regardless of why you chose to (or why you claim to have chosen to).
