### ISSUE TITLE
How do I make an npc msg you via console?

### ISSUE THREAD

**Issue by CodBucket** [CitizensDev/Citizens2#2111]
My issue: How do i make an npc msg you via console? I want to make it say "/msg (player) (text).
Please provide a  command for me if you can
Log: No log needed, please dont close this
MC Version: PaperSpigot 1.15.2
Citizens version: 2.0.26-SNAPSHOT
CommandNPC Version: 1.9.1

**Comment by mcmonkey4eva** [comment]
`/npc command add msg <p> hello there!`

Also, delete `CommandNPC`, that plugin shouldn't exist.
