### ISSUE TITLE
Could not pass event PlayerInteractEntityEvent to Citizens on NPC command

### ISSUE THREAD

**Issue by DrakePork** [CitizensDev/Citizens2#2112]
When adding a command to an npc with the /npc command and then clicking on the npc it now gives you a big error and it no longer works.

Error:
https://pastebin.com/8DQt7uZ3

The output of command `/version` on my server is: **(PLEASE FILL IN)** 1.15.2
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** 2.0.26-SNAPSHOT (build 1881)

**Comment by fullwall** [comment]
Download latest build
