### ISSUE TITLE
NPCs Invisible Minecraft 1.15.2 Paper-199

### ISSUE THREAD

**Issue by Insilvon** [CitizensDev/Citizens2#2113]
NPCs currently are not visible in the latest paper build-199. They are still in the world and can be interacted with, however they are not physically there. (No hitbox, no clicking, etc.) Denizen chat functions are still operational. Restarts, resetting saves, fresh installations on test servers - it appears to be broken on all platforms.

I found that backdating to paper-198 and disabling automatic paper updates (if your host offers that) fixes the issue. 
https://papermc.io/downloads

When I discovered the issue, I was running Paper-199 and Citizens-2.0.26-b1881.jar.

**Comment by TonyMontero** [comment]
Yeah im experiencing the same issue too.

**Comment by Sulack** [comment]
same here on bukkit. 

I think it has something to do with Tping people around. One person can see the NPC, but the TPed person cant. 

Need to disconnect and reconnect to fix.

**Comment by ESP4Ever** [comment]
Hi!
In my case only NPCs type PLAYER are invisible...
Spent few hours trying to figure out what's wrong(((

**Comment by mcmonkey4eva** [comment]
Bugs that are specific to Paper but don't replicate on Spigot are Paper bugs, not Citizens bugs.

In case of confusion, NPCs not appearing after you teleport the NPC is issue #2074

**Comment by Sulack** [comment]
It has nothing to do with me teleporting the NPC, I think it has to do with teleporting players around. 

I can see the NPC, but the player I tped close to the NPC cant.

**Comment by Ph4i1ur3** [comment]
Feel free to hop on the discord, and we can help you figure out your issue:
https://discord.gg/Q6pZGSR
