### ISSUE TITLE
NPC Command not working after restart and give errors

### ISSUE THREAD

**Issue by DevJoey** [CitizensDev/Citizens2#2114]
If i create a npc and add a command to him my command /wrtp <player> farmworld 7000 7000 the command is from my own plugin. and if i restart may server and click the npc it spams my console with the following error: https://one.denizenscript.com/haste/67734
I have reported it into Discord but your helpers says it is a critical bug and it must be reported to github. 

The output of command `/version` on my server is:  This server is running Paper version git-Paper-201 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: [17:42:14 INFO]: Citizens version 2.0.26-SNAPSHOT (build 1883)
[17:42:14 INFO]: Website: http://www.citizensnpcs.co
[17:42:14 INFO]: Author: fullwall

**Comment by fullwall** [comment]
What JVM are you using?

**Comment by DevJoey** [comment]
Java 8

**Comment by mcmonkey4eva** [comment]
I have a suspicion that it might be related to the persistence code -> https://github.com/CitizensDev/CitizensAPI/blob/d87a9e8fddf6bdbb26b93decd1ef21caa3df963b/src/main/java/net/citizensnpcs/api/persistence/PersistenceLoader.java#L182-L215
Specifically I think when trying to persist a long for the map -> https://github.com/CitizensDev/Citizens2/blob/dc72f7526c9b0ad53037e839bb188f656ccad9b3/main/src/main/java/net/citizensnpcs/trait/CommandTrait.java#L224-L225
it's loading `Integer` objects and not correcting the type (to `Long`), but perhaps needs to be.

**Comment by DevJoey** [comment]
I test it with removing the cooldown.

**Comment by DevJoey** [comment]
Normal commands are working, i have some npc's with a command without cooldown. Thy works fine. Only the villager in the farmworld with the /wrtp <player> farmworld 8000 8000 command print this issue.

**Comment by mcmonkey4eva** [comment]
Try the newer builds from https://ci.citizensnpcs.co/job/Citizens2/ , there was a commit that might fix the issue.

**Comment by DevJoey** [comment]
> 
> 
> Normal commands are working, i have some npc's with a command without cooldown. Thy works fine. Only the villager in the farmworld with the /wrtp farmworld 8000 8000 command print this issue.

I have tested it. With "2.0.26 build 1883" NPC Without cooldown it works well, but with cooldown <= 60 it will broke after restart. I will test the new Builds.

**Comment by DevJoey** [comment]
Fixed
