### ISSUE TITLE
Can't modify npc with controllable trait.

### ISSUE THREAD

**Issue by SickUsernameDude** [CitizensDev/Citizens2#2117]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-116 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1886)**

When creating a mount other then a horse, for example a pig, The controllable trait overwrites the speed if you are mounting it. I modify the speed with `getNavigator().getDefaultParameters().speedModifier()` and it **does** change the speed but the speed gets set to a specific speed while riding the npc with the controllable trait.

It also occurs when you just spawn a npc and give it the controllable trait with `/trait controlalble` the speed always avarages around 10m/s but when you dismount it goes back to its set speed, so only when mounted the speed changes.

**Comment by fullwall** [comment]
So the problem is when you dismount? Having a hard time following this.

**Comment by SickUsernameDude** [comment]
The problem is when you are on the mount, when nobody is on the mount the npc's speed works fine.
But as long if someone is on the mount it goes to the speed you cant modify. Maybe somewhere in the controllable trait its set to move with a certain speed? I did notice that there is a set speed modifier of 1.0F in the controllalbe class under the `PlayerInputAirController` class
Maybe that somehow messes with the speed?

**Comment by fullwall** [comment]
No, but there is a max speed.

**Comment by SickUsernameDude** [comment]
Whats the max speed, since I always get the same exact speed everytime. Can't make it slower or faster.

**Comment by fullwall** [comment]
I've just reduced the default speed. Reminder that you can test by using /npc speed while riding.

**Comment by SickUsernameDude** [comment]
Alright lowering speed works but max speed is reached at speed 4 already?
Is there a way to increase?

**Comment by fullwall** [comment]
Yes, there's a setting.

**Comment by SickUsernameDude** [comment]
Could you also tell me how to change that setting to have a higher max speed since I haven't found it yet.
