### ISSUE TITLE
#1887 Lag so hard

### ISSUE THREAD

**Issue by nagasiminecraft** [CitizensDev/Citizens2#2119]
Server got chunk await lag around 400% without any player online
Seems like its wrong coding on ticks management

**Comment by Tsoccerguy3** [comment]
Yes , just tested cauased tps 100 percent

**Comment by rudde0** [comment]
No issue on build 1886 but build 1889 consuming 40% of full server tick

**Comment by fullwall** [comment]
Try #1891

**Comment by Tsoccerguy3** [comment]
will try 1891 , But on 1890  really bad tps loss
https://timings.aikar.co/?id=581e43adc68e4f119429ee94017476be

**Comment by rudde0** [comment]
> will try 1891 , But on 1890 really bad tps loss
> https://timings.aikar.co/?id=581e43adc68e4f119429ee94017476be

is 1891 fine?

**Comment by Tsoccerguy3** [comment]
build 1891 was ok , tps stayed steady for the limited tests made .
