### ISSUE TITLE
Causes TPS lag.

### ISSUE THREAD

**Issue by FisherGee** [CitizensDev/Citizens2#2121]
Citizens v2.0.26 (build 1790)
Timings: https://prnt.sc/s4aw3g
Config: https://pastebin.com/Ht3uhu8N

**Comment by mcmonkey4eva** [comment]
- That's not a timings link that's a screenshot
- Timings are not a remotely useful way of tracking performance issues (a profiler is needed)
- https://wiki.citizensnpcs.co/Minecraft_1.8
