### ISSUE TITLE
Big consumption of perfomance by Citizens

### ISSUE THREAD

**Issue by MaxIsV** [CitizensDev/Citizens2#2122]
My problem is that Citizens is the most demanding plugin in performance, although I have also installed many other demanding plugins. In any timing report, Citizens is in first or sometimes second place among plugins. Usually its consumption is 5-11% of the total tick, but sometimes it can be 15%.

I have two plugins that are associated with citizens - this is Shop (it's called that) and CommandNPC.
Almost all% of Citizens consumption is this: "Citizens :: Task: net.citizensnpcs.util.PlayerUpdateTask (interval: 1)"

My server:
Shared hosting; Intel Xeon E5-1650v3; 13GB DDR4; SSD
82 citizens
Citizens config.yml: https://pastebin.com/NQVS85mE

Unfortunately on shared hosting I cannot install the profiler, but I have a timings report: https://timings.aikar.co/?id=35bdb7fede23466a99274c6cbf06573d

The output of command `/version` on my server is: **git-Paper-1618 (MC: 1.12.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1860)**

**Comment by mcmonkey4eva** [comment]
- That timings does not show a remotely high usage. It shows even "DailyRewards" using more.
- Timings are unreliable and unhelpful, get profiling done (eg via Spark, which installs as a plugin)
- Remove CommandNPC, there's no reason for that plugin to have ever existed, here's how to add commands to an NPC in modern Citizens: https://wiki.citizensnpcs.co/NPC_Commands
- PlayerUpdateTask is just the vanilla minecraft entity processing for player-type NPCs.

**Comment by fullwall** [comment]
You need to update Citizens, build 1860 had a performance bug in it.

**Comment by MaxIsV** [comment]
OK. I will remove CommandNPC soon. At your advice, I installed Spark and made a report: https://spark.lucko.me/#G6c6YlbRV4

Just like in Timings, it takes about 7.5 loads, I haven’t really figured it out in Spark yet, but everything points to Citizens, is such a load the norm?

You said that DailyRewards uses more, but DailyRewards is a problematic plugin that I will remove soon.

**Comment by mcmonkey4eva** [comment]
Citizens is using 7% of CPU time.
Vanilla mobs and hoppers are using 25% of CPU time.
Packets received from players are using another full 25% + 8%.
Running Paper timings at the same time as spark for some reason (?) used around 10% or so.

Of the 7.53% used by Citizens PlayerUpdateTask, 7.47 of that is the vanilla entity tick being applied to NPCs. Meaning, 0.06% of CPU time is used by Citizens itself within PlayerUpdatyTask.
As was said in my previous post: `PlayerUpdateTask is just the vanilla minecraft entity processing for player-type NPCs.`

**Comment by MaxIsV** [comment]
Can I somehow improve this PlayerUpdateTask or does nothing depend on me here?
