### ISSUE TITLE
NPC's are facing the wrong direction 

### ISSUE THREAD

**Issue by carddeal** [CitizensDev/Citizens2#2123]
The Issue I am currently having with Citizens is that when I create a Citizen it works perfectly fine facing the proper direction, but anytime I restart the server the plugin does not save and all my NPC's face south. I have tried changing the yaw in the saves but it never seems to work. No Changes are saved and it reverts back to facing south. Thanks for looking at my issue and hopefully it can be solved. 

The output of command `/version` on my server is: PaperSpigot 1.8.8
The output of command `/version citizens` on my server is: 2.0.26 snapshot

**Comment by fullwall** [comment]
Update Citizens

**Comment by Fonzee9** [comment]
Same issue here

**Comment by fullwall** [comment]
Try build 1896

**Comment by yambriz** [comment]
Same am having the same issue

**Comment by mcmonkey4eva** [comment]
@yambriz that's not a version.
Grab latest build from https://ci.citizensnpcs.co/job/Citizens2/

**Comment by yambriz** [comment]
oh theres a new build

**Comment by yambriz** [comment]
ok the new build fixed it
