### ISSUE TITLE
Error "An internal error occured while attempting to perform this command"

### ISSUE THREAD

**Issue by xmxaa** [CitizensDev/Citizens2#2125]
I have that error "An internal error occured while attempting to perform this command" using "/npc" command. 
I'm have 1.15.1 ver of minecraft and latest ver. of "citizens"

Error looks like: 

[03:54:16] [Server thread/ERROR]: null
--
766 | org.bukkit.command.CommandException: Cannot execute command 'npc' in plugin Citizens v2.0.24-SNAPSHOT (build 1605) - plugin is disabled.
767 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
768 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
769 | at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
770 | at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
771 | at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
772 | at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
773 | at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
774 | at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
775 | at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
776 | at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
777 | at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
778 | at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
779 | at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
780 | at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
781 | at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
782 | at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
783 | at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [minecraft_server.jar:git-Spigot-037559e-5c6b0dc]
784 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Is there any way to fix it?

**Comment by fullwall** [comment]
You must use 1.15.2 not 1.15.1

**Comment by Camotoy** [comment]
You need to use 1.16.5, not 1.16.3.
