### ISSUE TITLE
Issue With Receiving Product

### ISSUE THREAD

**Issue by HarryBrownie** [CitizensDev/Citizens2#2126]
Hello, I have purchased Citizens the newest version on SpigotMC, the payment has cleared and have waited 3+ hours and the product has not come through. Any ideas?

**Comment by SXRWahrheit** [comment]
Citizens is free.

https://i.alexgoodwin.media/i/real_use/6054b5.png

https://ci.citizensnpcs.co/job/Citizens2/

**Comment by HarryBrownie** [comment]
How do i get a refund? As spigot is charging 10 dollars

**Comment by SXRWahrheit** [comment]
Spigot isn't "charging" ten dollars, you have the *option* of donating through the "purchase" feature.

https://i.alexgoodwin.media/i/real_use/6054b5.png

Fullwall can process a refund if you DM him on Spigot.
