### ISSUE TITLE
Sentry moving problem

### ISSUE THREAD

**Issue by Snakemansos** [CitizensDev/Citizens2#213]
When i create a sentry, they moves if players push them by walking...Causing sentry falling on the top of my tower to the floor.
Spigot 1.8, citizens-2.0.14-SNAPSHOT and sentry 1.8.4
Sorry about my language i speak spanish!

**Comment by mcmonkey4eva** [comment]
`/npc pushable` I believe

**Comment by Snakemansos** [comment]
unknown command...
plugin suggest /npc leashable...but leashable or not, they will move anyways.
When i create an NPC with /npc create command, he not pushable, but when i add the sentry trait he moves.

**Comment by mcmonkey4eva** [comment]
Oop! That's a Denizen http://wiki.citizensnpcs.co/Denizen command. I'm not sure how to do it without Denizen :/

**Comment by Snakemansos** [comment]
i will try to use denizen plugin to see what happen...
Advice: On 1.7.2 citizens & sentry without Denizen works fine!

**Comment by Snakemansos** [comment]
i try denizen with command /npc pushable...and can be pushed anyways

**Comment by mcmonkey4eva** [comment]
You could try leaving a Sentry issue in case the original author comes back -> https://github.com/jrbudda/Sentry/issues -> (I maintain it, but I don't modify functionality ... I'm trying to replace it with something fully under my control, dSentry -> http://mcmonkey.org/denizen/repo/entry/0 )
