### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by KamThail** [CitizensDev/Citizens2#2131]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-037559e-5c6b0dc
(MC: 1.15.1) (Implementing API version 1.15.1-RO.1-SNAPSHOT),
Checking version, please wait...
The output of command `/version citizens` on my server is: Citizens version 2.0 26-SNAPSHOT (build 1854)
Author: fullwall
CitizensCMD version 2.4
Author: Mateus Moreira

Crash Report: https://hastebin.com/ahuwulucis.makefile

**Comment by mcmonkey4eva** [comment]
Support refused due to involvement in plugin piracy.
