### ISSUE TITLE
Path problem

### ISSUE THREAD

**Issue by XavierDare** [CitizensDev/Citizens2#2133]
NPC pathing doesnt work they dont go to it plus when i clear waypoints it makes eye of enders start flying and glitching out. 
Citizens Config: https://pastebin.com/dHcHqgSz
Server log: https://drive.google.com/open?id=1qxi_hxq_ZEzn2enNmSMCsy0zhH7yrkys

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
