### ISSUE TITLE
Controllable.java code improvement for 1.11 and above

### ISSUE THREAD

**Issue by Pirgosth** [CitizensDev/Citizens2#2134]
Hi,

Here: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/Controllable.java

I noticed that in your Controllable trait class, you are using a non regardless version function to check wether or not the mounted entity is an horse or not (Line 315).

I also noticed that in your net.citizensnpcs.util.Util package, you already have a nms function for this, so I suggest you to replace `(npc.getEntity() instanceof Horse)` with `Util.isHorse(npc.getEntity().getType())`

The issue with this is that in 1.11 and above, entities as Mule and Donkey do not extend from Horse, but AbstractHorse, and make the controllable trait not working with these.

Hope it will help.

**Comment by fullwall** [comment]
Sure
