### ISSUE TITLE
The bodies of some NPCs rotate incorrectly

### ISSUE THREAD

**Issue by MaxIsV** [CitizensDev/Citizens2#2137]
The problem is that some NPCs incorrectly rotate the body relative to the head. When I initially created the NPCs, they were fine, but after some kind of update this problem appeared. I tried to direct them in the right direction with the help of "/npc look" and "/npc lookclose", but after some time they again turned out incorrectly.

![2020-05-04_18 54 44](https://user-images.githubusercontent.com/58142896/81011633-f49a9f00-8e60-11ea-89e9-a490a301a0b3.png)

config.yml: https://pastebin.com/9iLhRk6j

The output of command `/version` on my server is: **git-Paper-1618 (MC: 1.12.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1899)**

**Comment by MaxIsV** [comment]
Hmm, was that fixed in build 1907?

**Comment by mergu** [comment]
Give an update a shot - always do this before opening an issue since you issue may have already been solved.
https://ci.citizensnpcs.co/job/Citizens2/
