### ISSUE TITLE
Npcs disappearing until citizens reload

### ISSUE THREAD

**Issue by tronman2020** [CitizensDev/Citizens2#214]
When leaving immediate area, on return, all npcs in a town will disappear completely. They are all still listed when /npc list is done. They will not come back untill /citizens reload is done.

**Comment by mcmonkey4eva** [comment]
Update citizens to latest dev build.

**Comment by tronman2020** [comment]
oh thank you, that solved it. I thought I had the most recent but I did not! ugh
