### ISSUE TITLE
NPC Skin randomly disapearing

### ISSUE THREAD

**Issue by hugo4715** [CitizensDev/Citizens2#2142]
The skins of my NPCs are not working properly and sometimes appear as steve/alex. When it happens I need to get far from the npc and come back for the skin to be reloaded properly. 
I am not using the Mojang API I am using a skin blob so it shouldn't be a Mojang related problem. The strange thing it that it does not happen everytime. Sometimes i have 1 or 2 npc workings and others that are 5 blocks away are just default steve. They should have the same skin.
I am attaching my skin in my plugin like this:
```
SkinnableEntity skinnableEntity = (SkinnableEntity) npc.getEntity();
skinnableEntity.setSkinPersistent("6b93094c-04ca-4b38-93bf-92af8262389c", "VKFLXG2CgEW02tmE20XE4cCPkMIV764Z9FeNA+I7uTzMB9pNJePkZIv5XBS7rx1d6eeWlYH/FnHwJeIjSsmMrSmGjWjE/o2A03hvpiYc7reKDCo1s+JAPSPfv6oWI42oGKvCXWaxFZarnaycMdecmE7qd21WlpnqwsVdMxp8GoR37xM7kXz1wyZ7CXBAvfcVwT3ju1vctIYGk/Ts1QPI2LGm1aSMJr94R9PG2aE2xlCr8j7XBb9JTrLZbXzKCttyJJnd8d3tuD4sLJk+lrQDgAAOMOMaqaOo2zIpvHSsx+wvLsN/ulYuFp0ymFCRxgKapVuctxNjczHeRHNLFwSCwu1du3tDtuNk3PIqUhpLtVsSJhGeM7HQy5rpNdR8WemJX6Z8UyEgtcNfLh4kme2ShoZynerHgoYliTqPjdCm/IABUyly36VpH4DxX2Ry38ox9dyod73zIfQl6e2dP+edL0cggH9Dmk5Yhfu0+RBsBZuMK0JFcVwkjtR9UAVipIp1RAN/mHeCtlkkj2BNBirXRAVpKwc+Is1em/fV98+XCR4ePyCNOu77Hd6HDjxcyzb2FSlHeVfcXJ/xz0Cmq27XwUAO8+BWNvlETjTGiNfXiJNvc8j/seVdGN4DpZjiRwdCSajRD7U4APKStysRD/tw9udnLhuEZv3JpBBKQqWhHvE=", "eyJ0aW1lc3RhbXAiOjE1ODcxMzA3MjM0MzAsInByb2ZpbGVJZCI6Ijc1MTQ0NDgxOTFlNjQ1NDY4Yzk3MzlhNmUzOTU3YmViIiwicHJvZmlsZU5hbWUiOiJUaGFua3NNb2phbmciLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIxYmEyYzRiMjAxNWFkNTk5ZWU4MTQ3YjZlMWIyZGIwN2I0Njc5MzA5MzAyZmYwZmZhYTIwYTcxMjE4ZWI4NzkifX19");
```

Additional informations:
Server version: [1.8 https://imgur.com/a/BsLc3RH](https://imgur.com/a/BsLc3RH)
Citizens version: 2.0.26-SNAPSHOT (build 1852)
I am running on a shared hosting service but not using the mojang api.
Online mode: true
No errors

**Comment by mcmonkey4eva** [comment]
A: Update Citizens, that's an old build.
B: use `SkinTrait`
C: update your server: https://wiki.citizensnpcs.co/Minecraft_1.8
