### ISSUE TITLE
That Belongs To an Administrator

### ISSUE THREAD

**Issue by TorrenStark** [CitizensDev/Citizens2#2143]
I have the latest version of Citizens
And my server version is 1.15.2

My members can not right click on the NPC and when they try to righty click it says “That belongs to an administrator”

Idk if this is a permission problem or a config problem. Plz help

**Comment by mcmonkey4eva** [comment]
That isn't a message that came from Citizens... you have some other plugin causing that. Refer to https://wiki.citizensnpcs.co/Plugin_Conflict for help with how to test & find the cause.

---

Please join the Discord for any further basic support questions or for further help with locating the cause of that message if needed: https://discord.gg/Q6pZGSR
