### ISSUE TITLE
Prevent mushroom cow from giving stew

### ISSUE THREAD

**Issue by AdrianR25** [CitizensDev/Citizens2#2144]
- A detailed description of your issue or feature request
  I'm trying to prevent a mushroom cow NPC from giving stew when right cliked with a bowl and it doesn't work. The protection works perfectly with milk, but not with stew.
- Link to server log & Citizens config (using e.g. pastebin.com) ESPECIALLY if it's a pathfinding issue
  I don't think this is necessary?
The output of command `/version` on my server is: **(PLEASE FILL IN)**
![image](https://user-images.githubusercontent.com/35237320/81484777-b5959080-9248-11ea-9d16-400a498378c6.png)
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
Citizens-2.0.26-b1945

**Comment by fullwall** [comment]
Fixed
