### ISSUE TITLE
NPC fly sometimes

### ISSUE THREAD

**Issue by Momonche** [CitizensDev/Citizens2#2147]
Sometimes NPC fly and never stop to 256 and respawn at their respawn location
But that create lag spike for 10~20 seconds and kill tps for little more time
Maybe related to this error : https://pastebin.com/Q241ufuU
Or this error : https://pastebin.com/Tpthb7wn

Video : https://www.youtube.com/watch?v=HfwttfQhzw0
Citizens config : https://pastebin.com/rSR6c5qY

The output of command `/version` on my server is: **git-Paper-273 (MC:1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1947)**

(I'm going to update Citizens and Paper when I can but I don't think it's going fix that)

**Comment by mcmonkey4eva** [comment]
Error from that log should be fixed via https://github.com/CitizensDev/CitizensAPI/commit/aae45b79f130b3f43be24651e8dd0b5f65992b88

**Comment by Momonche** [comment]
NPC still flying when they touch water visibly
