### ISSUE TITLE
Legacy material slowing down first npc selection

### ISSUE THREAD

**Issue by MrGraycat** [CitizensDev/Citizens2#2148]
Issue:
Using a stick on any NPC for the first time after a server boot causes it to initialize material support.
This takes a few seconds so slows down the first NPC selection.

Versions (Tested with Spigot and Paper both have the same issue.):
Spigot: git-Spigot-a03b1fd-95bd423 (MC: 1.15.2) implementing API version 1.15.2-R0.1-SNAPSHOT)
Paper: git-Paper-282 (MC:1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Citizens: 2.0.26-SNAPSHOT (build 1951)

Additional info:
Configuration: Default, unchanged.
Only one NPC which I'm selecting.

**Comment by fullwall** [comment]
Fixed
