### ISSUE TITLE
NPC fly when they encounter water

### ISSUE THREAD

**Issue by Momonche** [CitizensDev/Citizens2#2149]
When a NPC enter in water they start to fly
(Related to https://github.com/CitizensDev/Citizens2/issues/2147)
And when I try to apply a fire effect to him (with bow or sword), he doesn't burn (When is flying after enter water)

Maybe related to this error : https://pastebin.com/LYgGS3Q4
Video : https://www.youtube.com/watch?v=kkuIxH74ysU
Citizens config : https://pastebin.com/rSR6c5qY

The output of command `/version` on my server is: **git-Paper-282 (MC:1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1955)**

**Comment by mcmonkey4eva** [comment]
Cannot replicate.
