### ISSUE TITLE
NPC players not remaining in same location after server restart

### ISSUE THREAD

**Issue by PaisWillie** [CitizensDev/Citizens2#2150]
Issue:

When I restart my server, a couple of my NPCs will not be in their original place from before, but rather a few (5-10) blocks away from their original spot, even if I run `/citizens save` and `/save-all` before I restart. In my testing, one villager stays in the same spot, but the other two likes to change locations, even though for one of the two, I used `/npc tphere` before restarting, and I didn't do anything to the other NPC that changed location.

Commands I ran:

```
12.05 22:18:28 [Server] Server thread/INFO WisdomGamer issued server command: /npc select 3
12.05 22:18:30 [Server] Server thread/INFO WisdomGamer issued server command: /tp WisdomGamer
12.05 22:18:35 [Server] Server thread/INFO WisdomGamer issued server command: /npc tphere
12.05 22:24:37 [Server] Server thread/INFO WisdomGamer issued server command: /restart
```

[Server log](https://pastebin.com/Jv8RgHnd) (from when I ran the commands, to after server has restarted)

[Config file](https://pastebin.com/jDe5STDz)

The output of command `/version` on my server is:
```
[Wed, 13. May 2020 02:19:04 GMT INFO] This server is running CraftBukkit version git-Spigot-e7dc2f5-a8ec1d6 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[Wed, 13. May 2020 02:19:04 GMT INFO] You are 18 version(s) behind
```

The output of command `/version citizens` on my server is:
```
[Wed, 13. May 2020 02:19:23 GMT INFO] Citizens version 2.0.26-SNAPSHOT (build 1933)
[Wed, 13. May 2020 02:19:23 GMT INFO] Website: http://www.citizensnpcs.co/
[Wed, 13. May 2020 02:19:23 GMT INFO] Author: fullwall
[Wed, 13. May 2020 02:19:23 GMT INFO] CitizensCMD version 2.4
[Wed, 13. May 2020 02:19:23 GMT INFO] Author: Mateus Moreira
```

**Comment by PaisWillie** [comment]
Plugin List
```
AcceptTheRules v2.4
ActionAnnouncer v1.15.0
AdvancedFood v3.6.4
AdvancedLuckPermsGUI v6.0
AdvancedRegionMarket v3.1.1
AnimatedFrames v4.11.5-SNAPSHOT
AntiXrayHeuristics v1.2.0
ArmorStandTools v3.5.1
AsyncWorldEdit v3.6.20
BagOfGold v2.9.9
BankCheque v7.1.1
BannerBoard v1.10.3
BlockParticles v1.11.1-RELEASE
BuycraftX v12.0.6
Citizens v2.0.26-SNAPSHOT (build 1933)
CitizensCMD v2.4
ClearLag v3.1.6
CommandButtons v4.2.1
CommandPrompter v0.1.18
CommandSpy v2.0
CommandToItem v2.4.2
CoreProtect v2.18.2
DeathMessagesPrime v1.15.3
DeluxeChat v1.15.0
DeluxeJoin v2.8.0
DeluxeMentions v3.0.6
DeluxeMenus v1.13.2-Release
DeluxeTags v1.8.1
DiceFurniture v3.4.2
DiscordSRV v1.18.4
EpicRename v3.7.1
Essentials v2.17.2.0
EssentialsAntiBuild v2.17.2.0
EssentialsProtect v2.17.2.0
EssentialsSpawn v2.17.2.0
FabledSkyBlock v2.2.11
FeatherBoard v4.26.0
FogusCore v1.9.9
FurnitureLib v2.2.5
GrantX v1.5.1
GSit v[2.14.1.0]
GUIShop v7.3.8
HeadDatabase v4.12.2
HeapDump v1.4.0
HolographicDisplays v2.4.1
HolographicPlaceholders v2.0.3 Beta
InsaneShops v1.1.9
InteractionVisualizer v1.10.18
InteractiveChat v2.2.0
LeaderHeadsRevamped v4.0.5
LightAPI v3.4.3
LimitPillagers v2.12.0
LiteBans v2.5.2
LuckPerms v5.1.15
MapManager v1.7.8-SNAPSHOT
Matrix v4.8.1
mcMMO v2.1.127
MessageAnnouncer v1.11.0
MobFarmManager v1.5.5.1
MovingDevApi v1.1.6
Multiverse-Core v4.1.0-b775
Multiverse-Inventories v3.0.0-b459
Multiverse-NetherPortals v4.1.0-b763
Multiverse-Portals v4.1.0-b805
MVdWPlaceholderAPI v3.0.1
MyCommand v5.6.4
OnTime v4.1.4
OreoCore v14.9
PacketListenerApi v3.7.6-SNAPSHOT
PlaceholderAPI v2.10.6
PlayerReport v3.2.13
PlugMan v2.1.7
PremiumVanish v2.5.11
ProtectionLib v0.9.8
ProtocolLib v4.5.0
RestrictedCreative v2.3.6
RewardPRO v4.3.3
SelectionVisualizer v3.0.0.7
ServerTutorialPlus v1.21.3
SilkSpawners v6.0.1
Skript v2.4.1
TAB v2.7.4
TaskScheduler v1.0
TradeSystem v1.1.8
UltimateStacker v1.11.7
UltimateTimber v2.0.6
Vault v1.7.2-b107
ViaBackwards v3.0.0-SNAPSHOT
ViaVersion v3.0.0-SNAPSHOT
VillagerOptimiser v1.1.2
Votifier v2.6.0-SNAPSHOT
Voting v2.5.0
VotingPlugin v5.21.3
WorldBorder v1.9.10 (beta)
WorldEdit v7.1.0;8e55131
WorldGuard v7.0.2-SNAPSHOT;bf2593e
WorldGuardExtraFlags v4.1.4
XProtect v2.7.0
```

**Comment by mcmonkey4eva** [comment]
- Remove PlugMan. It breaks everything.
- remove CitizensCMD. That plugin has never had a valid reason to exist. To add click commands to an NPC use https://wiki.citizensnpcs.co/NPC_Commands
- Update to latest Citizens build https://ci.citizensnpcs.co/job/Citizens2/

**Comment by PaisWillie** [comment]
- I removed PlugMan
- I removed CitizensCMD
- I updated Citizens to the latest build
Bug is still occuring.

**Comment by mcmonkey4eva** [comment]
Can you please try the plugin-conflict testing steps @ https://wiki.citizensnpcs.co/Plugin_Conflict
In particular any plugin that might interact with villagers (`ClearLag`, `VillagerOptimiser`, ...) are likely to be related.

**Comment by PaisWillie** [comment]
Sorry, player NPCs, not villagers, my mistake. The villager I was referring to was a baby villager that is not affected by this, only the player NPCs are teleporting.

Things I tried:
- Removed VillagerOptimizer

Thing that worked:
- Removed FabledSkyblock (Reinstalled VillagerOptimizer)

It seems like FabledSkyblock is the culprit. I recall FabledSkyblock having some features built in where it will teleport players not allowed on the island (Although I have my visitors turned on). It only happens when the player NPC is on my island, but not in a world that is not handled by FabledSkyblock.

**Comment by mcmonkey4eva** [comment]
Yep, that's an issue to report to the `FabledSkyblock` team then.
