### ISSUE TITLE
Build 1958 make all NPC invisible

### ISSUE THREAD

**Issue by Momonche** [CitizensDev/Citizens2#2151]
Yesterday I updated to the latest version available and all my NPC became invisible so today I tested all previous build and I can say it's an issue with the build 1958 "Rework tablist for recent versions"

No error in console
Citizens config : https://pastebin.com/rSR6c5qY
The output of command `/version` on my server is: **git-Paper-282**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1662)**

**Comment by mcmonkey4eva** [comment]
Can't replicate any issues on current builds.

**Comment by Momonche** [comment]
@mcmonkey4eva I just find it's an issue with ProtocolSupport, can you do something to fix that ?

**Comment by mcmonkey4eva** [comment]
Nope, that'd be their problem to do something about.

**Comment by Ferocimo** [comment]
@mcmonkey4eva Why is this issue suddenly occuring ? It's obviously caused by something made in latest builds. Isn't there any workaround, anyway to make this build (and future ones) NOT cause this issue ?

Because clearly ProtocolSupport won't fix this.

**Comment by cicatrice74** [comment]
I do not understand the "it's a protocolsupport issue", or "it's a denizen's issue" question. If there is a problem and we send you informations about this, u shold look in to this, we do not say u must, but u shoul look in to it just to get your plugins better.
I also have the same disapperaing npc problems, i just reverted back to older version of denizen (not protocolsupport) and it is functioning again, it would be great to use latest versions of all plugins.

**Comment by fullwall** [comment]
I went back to the old method in the latest build.

**Comment by Momonche** [comment]
Works fine, thank you @fullwall
