### ISSUE TITLE
Issue With your Team

### ISSUE THREAD

**Issue by EpicRealms** [CitizensDev/Citizens2#2155]
Hello Dev. Team.

This will be our final attempt of contact since you deleted the previous post. We have been looking on all your rules terms and conditions wich are not a lot and stated this we will post this problem one last time. If your behavior keeps the same since no terms or conditions have been transgressed we will be forced to take legal mesures.

If you need for now any legal information to come in touch with us this is our info:
Company's Name: Epic Realms Unip. Lda.
For more info that we're not willing to make public contact us.
Contact: staff.epicrealms@outlook.com

As it was said previously: We have several problems that we would apreciate that you would take a look and full fill your work as Developing Team.

- Nametags on human type NPC's get cutted;
- NPC's ID change while using Denizen plugin breaking third party plugins

For now it is all.
Thanks for your attention. Any file or info we can provide to help you solving this quicker we will gladly provide.

Best regards,
Epic Realms INC

**Comment by mcmonkey4eva** [comment]
"forced to take legal measures"
Mate you got banned from a Discord for alting, fighting with staff, and running cracked servers.
I don't know what legal system you think exists, but it ain't one that lets you take Discord staff to court for banning a spammer.

And, by the way, cracked servers are illegal, and if you were a real company (you're not, you can't even seem to decide if you're `Epic Realms Unip. Lda.` or `Epic Realms INC` apparently), that would be sufficient to destroy your company and shove it into the ground.

We've banned 2 accounts that are unrepentantly you, 1 that has a different name but is obviously you, and 1 that is you pretending to be your own girlfriend for some reason. There are probably more bans on record that we don't even realize are also you.

Please don't post further. It ain't gonna work.
