### ISSUE TITLE
npcNav.setTarget(Location loc) will ALWAYS teleport unless .useNewPathfinder(true)

### ISSUE THREAD

**Issue by ROODAY** [CitizensDev/Citizens2#2158]
So I was stuck for a couple hours trying to get my NPC to spawn and walk somewhere, instead it kept spawning where I wanted it to end up (i.e. immediately teleporting). My code looked like this:
```
npc.getNavigator().setTarget(destination);
```
Changing the pathfinding range did nothing, and it continued not to work until I added this line:
```
npc.getNavigator().getLocalParameters().useNewPathfinder(true);
npc.getNavigator().setTarget(destination);
```
Can this be included in some docs somewhere?

**Comment by mcmonkey4eva** [comment]
That's not required at all. That likely indicates you have `use-new-finder` set `false` in your `config.yml` and you're trying to make the NPC navigate a path that the vanilla pathfinder can't handle.

Generally you actually shouldn't call that parameter method at all unless you have a very good reason to - instead, set the preferred pathfinder in your `config.yml` and/or on a per-NPC basis when configuring NPCs in-game via `/npc help pathopt`

**Comment by ROODAY** [comment]
Hmm I see you're right, the `use-new-finder` field was set to false. I never set that however, is it a default value? I ran into this while testing my plugin inside 14eredit megaserver, all I did was drop the Citizens jar inside the plugin folder and that `config.yml` is what I got.
