### ISSUE TITLE
Citizens 2 won't load on latest Paper build

### ISSUE THREAD

**Issue by Elric02** [CitizensDev/Citizens2#2159]
I just upgraded from Paper build 300 to Paper build 304 today, and Citizens 2 doesn't load anymore. My console keeps stuck : the usual message that appears at the point it freezes is `>.... [23:51:24 INFO]: [Citizens] Loaded 174 NPCs.` but nothing appears and I'm forced to kill the server or it won't shut down.
Retrograding to Paper build 300 fixed the issue.
Could you please have a look ? Thanks

The output of command `/version` on my server is: Paper 1.15.2 build 304
The output of command `/version citizens` on my server is: 2.0.26-SNAPSHOT (build 1968)

**Comment by mcmonkey4eva** [comment]
Please report this issue to the Paper team, as it's an issue from an update they did, not us.
