### ISSUE TITLE
Flying npc's fall

### ISSUE THREAD

**Issue by crolemol** [CitizensDev/Citizens2#216]
when i spawn any npc (flying)(tested with players and bats) the npc's fall down slowly. if they are walking to a location everything is fine but when they reached their target they fall down again. Also tried stacking entities both flying without result. please fix this

using v2.0.14 build 1206 and spigot 1.8

**Comment by mcmonkey4eva** [comment]
For some reason, Minecraft strongly enforces gravity. It's kinda difficult to make this work.

**Comment by crolemol** [comment]
is there any way of stopping it because my npc's have to hang in the air

**Comment by ryantheleach** [comment]
Can you make a NPC ride an armorstand that has no gravity?

**Comment by crolemol** [comment]
can armorstands have a velocity? I already tried setting a player(setFlying(true)) on a bat npc (setFlying(true)) without result. it still falls down

**Comment by ryantheleach** [comment]
I'm not sure, but armor stands specifically have the ability to be invisible, and have an option to not be effected by gravity.

**Comment by crolemol** [comment]
tried it and my armorstand npc doesn't spawn...

**Comment by Roos-Skywalker** [comment]
It's not a bug fix but you can place a barrier below the NPC and spawn it on that. It will look like as if the NPC flies.

**Comment by fullwall** [comment]
/npc gravity - if this doesn't work then it could be clientside predicted...
