### ISSUE TITLE
/npc is not working

### ISSUE THREAD

**Issue by Tse244** [CitizensDev/Citizens2#2161]
I'm trying to open a modded server and I was sure on using custom NPCs but they are unreliable. So I decided to use citizens. But when I write /npc nothing happens or writes at the chat. Can you guys help me?

The output of command `/version` on my server is: Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.57 (MC: 1.7.10)
The output of command `/version citizens` on my server is: 2.0.13

**Comment by Ph4i1ur3** [comment]
You can find an old link to Citizens for 1.7.10 for Cauldron (Not Thermos, although Thermos is ultimately a fork of Cauldron) on Citizen's spigot page. 

This is a unsupported version, and any bugs are unlikely to get fixed, and any issues will likely be up to you to solve.

The link: https://www.dropbox.com/s/cgtacg5qs1lvkby/citizens-2.0.13-1.7.10-Cauldron-B2.jar?dl=0
