### ISSUE TITLE
Illegal Reflective Access in Java 11

### ISSUE THREAD

**Issue by deanveloper** [CitizensDev/Citizens2#2162]
The output of command `/version` on my server is:
```
[11:53:28 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[11:53:28 INFO]: Checking version, please wait...
[11:53:28 INFO]: You are running the latest version
```
The output of command `/version citizens` on my server is:
```
[11:54:00 INFO]: Citizens version 2.0.26-SNAPSHOT (build 1952)
[11:54:00 INFO]: Website: http://www.citizensnpcs.co
[11:54:00 INFO]: Author: fullwall
```

Issue:
```
[19:41:23 INFO]: [Citizens] Enabling Citizens v2.0.26-SNAPSHOT (build 1952)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.citizensnpcs.util.NMS (file:/home/container/plugins/Citizens-2.0.26-b1952.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of net.citizensnpcs.util.NMS
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
This occurs on Java 11, although it may occur on anything higher than Java 9. It is only a warning so citizens still continues to work, however in future versions of Java it may stop working, as the warning states. It is likely a good idea to support Java 11 as Java 8 has hit its EOL and Java 11 is the current LTS release.

**Comment by mcmonkey4eva** [comment]
Run Java 8. Oracle Java is a meme, not actually viable for use.

If it helps, bStats report on all Spigot servers java versions:
![java](https://i.alexgoodwin.media/i/misc/04351b.png)

**Comment by Trqhxrd** [comment]
I have the same problem. However I use the corretto 11... It's not just the oracle distribution...

**Comment by Camotoy** [comment]
The warning is safe to ignore and does not actually cause issues on Java 11.

**Comment by deanveloper** [comment]
Correct however warnings typically indicate bad practices, and this warning in particular indicates that the features that Citizens is using will be removed in the future.

**Comment by mcmonkey4eva** [comment]
@Trqhxrd "Oracle Java" is referring to all versions of Java starting with Java 9.

Java versions up to 7 were developed by Sun Microsystems. Oracle, a corporation with purely negative intentions (notably their infamous lawsuit against google) purchased total control of Sun and their products, including Java.
Java 8 was later released based largely on Sun's incomplete projects at time of purchase... after that, Oracle completely redesigned the Java development lifecycle and began removing and breaking features for largely arbitrary reasons unrelated to the intentions of the original Java developers and unrelated to the public good of Java users.
This warning is an example of one such unreasonable and unnecessary feature removal.

If interested you can read more about Oracle's destruction of Sun's products on wikipedia @ <https://en.wikipedia.org/wiki/Sun_acquisition_by_Oracle>

**Comment by deanveloper** [comment]
Unbelievable that a package maintainer isn’t even going to properly support the language required by the library they are developing on top of.

**Comment by mcmonkey4eva** [comment]
We develop for Java 8. As does Spigot. As does Paper. As does the entire Minecraft community other than Paper.
