### ISSUE TITLE
plugin disabled

### ISSUE THREAD

**Issue by masterCode08** [CitizensDev/Citizens2#2164]
i need to use citizens on my server but every version i download shows up as disabled
The output of command `/version` on my server is: **
![image](https://user-images.githubusercontent.com/50266342/82757597-6703fc80-9dd9-11ea-9ae8-ef2e9a2fc46a.png)
**
The output of command `/version citizens` on my server is: **
![image](https://user-images.githubusercontent.com/50266342/82757613-784d0900-9dd9-11ea-8f76-0ddbf5a937e7.png)
**
i dont know what to do, as it just says internal error whenever i do any command citizens related

**Comment by Ph4i1ur3** [comment]
If you wanna hop on the discord, there's plenty of support to help you out: https://discord.gg/Q6pZGSR
