### ISSUE TITLE
Iron Golems Don't Respawn Properly

### ISSUE THREAD

**Issue by Yuval270** [CitizensDev/Citizens2#2165]
after i create an npc, i teleport to a different place, then teleport back and it disappears

**Comment by Yuval270** [comment]
i forgot to mention, it only happens iwith iron golem npc

**Comment by mcmonkey4eva** [comment]
Please edit your post to follow the issue template : https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE
