### ISSUE TITLE
Hide Nametag On the NPC

### ISSUE THREAD

**Issue by SharkblackFr** [CitizensDev/Citizens2#2167]
Hello,
I wish I could hide the names placed above the head of the NPC. Is it possible?
Thanks in advance for your help

**Comment by mcmonkey4eva** [comment]
`/npc name`

**Comment by SharkblackFr** [comment]
/npc name -h 
because it doesn’t hide the nametag

**Comment by SXRWahrheit** [comment]
Update Citizens. https://ci.citizensnpcs.co/job/Citizens2/

**Comment by SharkblackFr** [comment]
still not this is still visible I am in 1.14.4

**Comment by SXRWahrheit** [comment]
One of the most helpful tools to identifying the source of a problem is your server logs file! Logs contain all sorts of important information like server and plugin versions, any error messages, and a lot more important information.

Your log can be found in the logs folder within your server folder. The most recent log is a text file labeled latest.log. To get help using these logs, please open that file in a text editor and copy all of the text, then open https://pastebin.com/ and paste the text into the box on the page. Then click "Create New Paste" and copy the URL and paste that into a new comment.

**Comment by SharkblackFr** [comment]
https://pastebin.com/YUX2STYE

**Comment by mcmonkey4eva** [comment]
That's not your full latest.log

**Comment by SharkblackFr** [comment]
no srry https://pastebin.com/SmetaaL0

**Comment by mcmonkey4eva** [comment]
You're running unsupported and conflicting software.

For any further discussion, please use Discord https://discord.gg/Q6pZGSR
