### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by MetaIIum** [CitizensDev/Citizens2#2168]
The output of command `/version` on my server is: CraftBukkit 1.13.2
The output of command `/version citizens` on my server is: 2.0.24
https://pastebin.com/cTPBAqYB
![image](https://user-images.githubusercontent.com/66139418/83297165-0f420880-a1c0-11ea-8624-7c1c2bb458db.png)

**Comment by SXRWahrheit** [comment]
You are 503 versions behind.

**Comment by MetaIIum** [comment]
I do the commands and nothing happens

**Comment by MetaIIum** [comment]
How do I get a new version I just want to use 1.13.2

**Comment by SXRWahrheit** [comment]
You are 503 versions behind. You need to not be 503 versions behind, and ideally update to 1.15.2.

https://www.spigotmc.org/wiki/buildtools/

**Comment by MetaIIum** [comment]
I don't like really using the newest version is that the only way I can get citizens to work?

**Comment by SXRWahrheit** [comment]
You must use BuildTools to run the latest version of Spigot, whether it be the latest 1.13.2 build or the latest 1.15.2 build. You can alternatively use the latest builds of Paper. The server software you are currently using does not and will not support Citizens.

**Comment by MetaIIum** [comment]
Well ok then

**Comment by mcmonkey4eva** [comment]
Need to update Citizens as well, from https://ci.citizensnpcs.co/job/Citizens2/
