### ISSUE TITLE
NPC names only 16 chars long.

### ISSUE THREAD

**Issue by Tsumitsuki** [CitizensDev/Citizens2#2169]
- The NPC Names are only 16 charates long. A few days ago the names where longer. Now only the last 16 charaters are shown. Nothing has changed (afaik). no update nor config changes. 

Config: https://pastebin.com/jLn8gbib
log: https://pastebin.com/zD66YhSz

Citizens v2.0.26-SNAPSHOT (build 23)
git-Paper-194 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
`Citizens v2.0.26-SNAPSHOT (build 23)`
Where did you get that build from

**Comment by Tsumitsuki** [comment]
Side-Project from another Server that auto updates via jenkins.
If you'r not ok with that i buy another copy!

what about the shortend npc names?

**Comment by mcmonkey4eva** [comment]
Download the latest build of Citizens from https://ci.citizensnpcs.co/job/Citizens2/
Don't use any other builds of Citizens than the official builds.

Also update paper: https://papermc.io/downloads
