### ISSUE TITLE
NPC sometimes fly

### ISSUE THREAD

**Issue by Momonche** [CitizensDev/Citizens2#2171]
The output of command `/version` on my server is: **git-Paper-333 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1979)**

Hello !
I think this issue is related to Citizens :
When a NPC walk in water, the NPC start to fly in a right line to the top of the map and get rollback to the ground, and fly again to the top, ect
Video: https://www.youtube.com/watch?v=nQ74DCi1GTk
Seems to be ONLY when the NPC walk in water but not sure
Sometimes the NPC fly to the top of the map but sometimes he just fly like the video before he gets rollback
Not ALL NPC walking in water fly like this, so it can be hard to be replicate

**Comment by mcmonkey4eva** [comment]
I can actually replicate this pretty quickly and easily, via just `/npc create bob` then `/npc path` and marking a point underwater

**Comment by fullwall** [comment]
Try latest build

**Comment by Momonche** [comment]
The issue still occurs with build 1981

**Comment by fullwall** [comment]
Fixed in latest build
