### ISSUE TITLE
Citizens COMPARE NAMES

### ISSUE THREAD

**Issue by ArbyzikYA** [CitizensDev/Citizens2#2172]
@EventHandler
	public void NPC_RCM(NPCRightClickEvent e) {
		if(e.getNPC().getFullName() == (".")){ compare dont work (npc name now (.))
			e.getClicker().sendMessage("My name:");
		}
		e.getClicker().sendMessage("TEST"); - thats work 
	}

**Comment by mergu** [comment]
Strongly recommend looking up some Java tutorials. The `==` operation on Strings checks if the two Strings are the same Object, not whether the text matches. You'll have to use String.equals() or any other String methods to do text comparison.

That being said, if you are trying to check for a specific NPC we recommend tracking them by ID and not by name.

**Comment by ArbyzikYA** [comment]
Thank you very much, I am a beginner developer, and forgot this information, thank you very much for your help
