### ISSUE TITLE
NPC text not removing

### ISSUE THREAD

**Issue by ItsRodry98** [CitizensDev/Citizens2#2173]
The output of command `/version` on my server is: This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.26-SNAPSHOT (build 1979)

Recently i put text on two NPCs, but later i wanted to remove it. First a tried to use the /npc text command and i deleted the text. When i right click on NPC it doesn't talk anymore. In saves.yml file the part that contain text is removed.

Then I restart the server and this 2 NPC are saying "[NPC] -> You: Hi I'm <npc>!" The saves.yml has the text part. So i tried to delete this part in saves.yml and restart the server and it regenerate again.
I tried to use /npc text command, removed the text, used /citizens save command and restart the server too but they are saying it again.

**Comment by mcmonkey4eva** [comment]
To guarantee total removal of the text system, you can just do `/trait text` and it's gone.
