### ISSUE TITLE
Cannot set permission on server command

### ISSUE THREAD

**Issue by Volgeop** [CitizensDev/Citizens2#2175]
Hi, I have NPC, for ex. test and I add him command /npc command add -p server Build --permissions test.xxx, so it should send just players with this permission. BUT it doesn't! Permission doesn't work on server command probably.

The output of command `/version` on my server is: **git-Paper-334 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1979)**

**Comment by mcmonkey4eva** [comment]
I saw you join Discord, post that question, then delete it because you realized you were marked DoNotSupport. We have logs.
