### ISSUE TITLE
Disabled gravity not working on various NPC types

### ISSUE THREAD

**Issue by FrankSchepers24** [CitizensDev/Citizens2#2176]
_The output of command `/version` on my server is:_ **git-Paper-245**
_The output of command `/version citizens` on my server is:_ **2.0.26-SNAPSHOT (build 1979)**

**A detailed description of your issue:**
When I disable an NPC's gravity, it still falls. I use this on parrots and fishes (so they stay on a particular height in the water). It worked in previous versions on 1.13, but now that we've upgraded to 1.15.2, it stopped working. I duplicated the config, tried enabling and disabling. Tried enabling and disabling flyable. Tried tphere's. Tried to configure it through the config / saves.
Nothing seems to work.

**Link to server log & Citizens config:**
Config: https://pastebin.com/98EJpCGn
Saves: https://pastebin.com/gLbHiJJY
Server log: https://pastebin.com/vTVXPZtT

**Comment by BehrRiley** [comment]
per our conversation in the discord:
```
Server Version
Paper version git-Paper-245 (MC: 1.15.2)-- (Outdated build, behind by 89... Current build is 334)
```

Update paper, just verified on my localhost this is working with the following:

```
[18:33:50 INFO]: This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:33:50 INFO]: Previous version: git-Paper-129 (MC: 1.15.2)
[18:33:50 INFO]: You are running the latest version
> version citizens
[18:33:52 INFO]: Citizens version 2.0.26-SNAPSHOT (build 1979)
[18:33:52 INFO]: Website: http://www.citizensnpcs.co
[18:33:52 INFO]: Author: fullwall
```

Latest Paper builds are at https://papermc.io/downloads.

**Comment by BehrRiley** [comment]
an edit on the above: the gravity seems to work for most entities but I wasn't aware this was specific to Parrots, which is actually not functional in the server version above; tested with Spigot as well

**Comment by FrankSchepers24** [comment]
Tested some more, fishes (cod, salmon, tropical_fish) seems to work in the air. But when underwater they still sink to the ground.
Parrots also still don't work, (other flying animals like bats and phantoms do)

New log file after updating spigot & creating an armor_stand & parrot: https://pastebin.com/niYCfQgR

**Comment by fullwall** [comment]
This is probably because we switched to using Mojang's no gravity feature. I wonder if that just doesn't work for parrots/fish?
