### ISSUE TITLE
Shopkeepers be able to walk after adding Citizens to my server

### ISSUE THREAD

**Issue by SUICIDE01** [CitizensDev/Citizens2#2178]
The output of command `/version` on my server is: **(255)**
The output of command `/version citizens` on my server is: **(2.0.26 build 1854)**

Hi! After installing NPC along with the shopkeepers plugin, my shopkeepers spawned using /shopkeepers will be able to walk away but not like froze like before adding citizens. How can I solve this?

**Comment by Ph4i1ur3** [comment]
The version you posted in not the full output of that command. 

If you need live support you can always join the discord: https://discord.gg/Q6pZGSR

**Comment by SUICIDE01** [comment]
![image](https://user-images.githubusercontent.com/66518030/83944051-4dc86a80-a833-11ea-87f5-326385307323.png)
![image](https://user-images.githubusercontent.com/66518030/83944059-5b7df000-a833-11ea-9bfc-a586ac91b1dc.png)
