### ISSUE TITLE
'/npc command' Sequential Execution Option

### ISSUE THREAD

**Issue by lukaje** [CitizensDev/Citizens2#2179]
Hi! 
So basically what im trying to do, is to add commands to an NPC but i want them to go 1 by 1, which means people have to keep pressing right click to keep seeing messages.
If you ever played on hypixel skyblock i think you know what i mean. If you need more details please tell me, ill try to explain better.

**Comment by mcmonkey4eva** [comment]
Until a feature is added for this, you might consider using a Denizen script to achieve the same goal: https://guide.denizenscript.com/guides/background/what-is-denizen.html

**Comment by lukaje** [comment]
Thanks, i've never tried it b4, so yeah i guess its time to learn.
