### ISSUE TITLE
UltraTrader shop to buy playerheads?

### ISSUE THREAD

**Issue by tronman2020** [CitizensDev/Citizens2#218]
Can some one either recommend a better trader trait plugin or help me figure out how,if possible, to make a shop buy/sell named player heads? 

The keepers will only buy and sell player heads of the exact name they are configured for. I would like a shop to buy all player heads regardless of player name!

I submitted this question on ultra-trader as well but it is severely outdated.
Any help and recommendations please, I feel that this issue has been touched on before but I can not find.

**Comment by mcmonkey4eva** [comment]
uh... dtlTraders or calico-kid's Denizen shop script.
