### ISSUE TITLE
Boats Can "Steal" Mob-Type NPCs

### ISSUE THREAD

**Issue by FrozenBeard** [CitizensDev/Citizens2#2180]
The output of command `/version` on my server is: Paper 1.12.2
The output of command `/version citizens` on my server is: Citizens-2.0.26-b1982

Players are stealing my NPCs by pushing boats into claims and moving the NPCS, how can I stop this?

**Comment by FrozenBeard** [comment]
@mcmonkey4eva Added versions.

**Comment by mcmonkey4eva** [comment]
Tested & replicated on my own server - seems that the vanilla functionality of mobs auto-entering boats is applying to NPCs.

**Comment by mcmonkey4eva** [comment]
Should be fixed via https://github.com/CitizensDev/Citizens2/commit/310c1ce52fff78720b57084afd35d62872935651 in build 1992+ on https://ci.citizensnpcs.co/job/Citizens2/

**Comment by FrozenBeard** [comment]
Thanks, Ill give it a try!

**Comment by TomLewis** [comment]
So its a bit late, but Mobs can still be stolen with boats! Most of my NPC's are parrots if that helps.
