### ISSUE TITLE
Citizens and Sentinels not being able to reach relatively distant target

### ISSUE THREAD

**Issue by Ferocimo** [CitizensDev/Citizens2#2181]
The output of command /version on my server is: git-Paper-343 (MC: 1.15.2)
The output of command /version citizens on my server is: 2.0.26-SNAPSHOT (build 1982)

Hello,

Citizens that have a waypoint further away than 20 blocks won't be able to reach this location without teleporting to it, they won't be able to find a way to reach it. This has been an "issue" or a feature for a long time, but this was manageable as we just had to place more waypoints on the way so they follow the path...

Except for Sentinel where it has lately become a huge issue. Indeed, if a melee Sentinel (with a sword for instance) detects a target further away than 20 blocks, for instance 28 blocks, it will just stare blankly at it without being able to move at all. It's only when the target enters the "20 blocks" range limit that it will start moving towards the target, even though you set a range of, for example, 40 blocks. 

This is a very concerning issue as it means that because of this limitation, you'll NEVER be able to set a higher range than 20 blocks for a melee Sentinel, which is pretty low. This limitation should not be applied to Sentinels, or at least be configurable.

Thank you for looking into this.

**Comment by mcmonkey4eva** [comment]
This is the `/npc pathrange` value, which defaults to 25, that you need to set higher.
