### ISSUE TITLE
Set a skin 

### ISSUE THREAD

**Issue by uScoutzZ** [CitizensDev/Citizens2#2183]
The output of command `/version` on my server is: git-Paper-304 (1.15.2)
The output of command `/version citizens` on my server is: 2.0.26-SNAPSHOT (build 1968)

**- A detailed description of your issue or feature request**
I want to suggest a _npc.setSkin(Skin skin)_ method in your api. Because when I try to rename a NPC the skin gets changed to the name i entered but I want the skin the NPC had before. To get this skin you could use _Skin skin = ((SkinnableEntity) npc.getEntity()).getSkinTracker().getSkin();_ before renaming it. I hope a feature like this does not exist already and I'm to stupid to find it

**Comment by fullwall** [comment]
Use SkinTrait (preferably before spawning the NPC)
