### ISSUE TITLE
It doesn't do anything when players click on them.

### ISSUE THREAD

**Issue by TheNotTanMan** [CitizensDev/Citizens2#2184]
The output of command `/version` on my server is: **(
![image](https://user-images.githubusercontent.com/66755448/84700768-c7daac80-af21-11ea-9532-36a5d85f7bc3.png)
)
)**
The output of command `/version citizens` on my server is: **(
![image](https://user-images.githubusercontent.com/66755448/84700883-f9537800-af21-11ea-9014-43194585b29b.png)
)**

**Comment by BehrRiley** [comment]
You're 13 versions behind on Citizens, and very behind on spigot.

https://wiki.citizensnpcs.co/Minecraft_1.8

**Comment by TheNotTanMan** [comment]
Oh and I forgot to mention i'm using citizens-2.

**Comment by TheNotTanMan** [comment]
and I don't think it's the versions. It might be but when I turn build off in worldguard it spams a whole bunch of stuff in the chat. The npc's work for op's. Not for players. I'll still update my versions though.

**Comment by mcmonkey4eva** [comment]
If you encounter issues after updating, considering asking for help on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel
