### ISSUE TITLE
Setting Enderman To Use Provoked Animation

### ISSUE THREAD

**Issue by LordWaycrest** [CitizensDev/Citizens2#2186]
Hi,

I'm just making a request to see if it possible to have a feature that allows us to set Enderman to the animation when they are provoked (angry as some say).

I've tried playing around with some commands but couldn't seen to work it out and I have asked on the Discord and was told to open a feature request.

Cheers,
Lewis

The output of command `/version` on my server is: **git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SMAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1996)**

**Comment by mcmonkey4eva** [comment]
Added by https://github.com/CitizensDev/Citizens2/commit/59cefadedae3481a56d40177218f47acf2d5fbf9 and https://github.com/CitizensDev/Citizens2/commit/c9564c4be2f6c32f1aa2ab497ee5ba793ab8b5b8 under `/npc enderman` for build 2014+ from https://ci.citizensnpcs.co/job/Citizens2/
