### ISSUE TITLE
Players without op are supposed to use npcs but they cant still

### ISSUE THREAD

**Issue by mastrocat** [CitizensDev/Citizens2#2187]
I am very new to making servers and I have lots of trouble with permissions and I have discovered that players without op can't use NPCs, which is essential to having my server running. I am using LuckPerms to give permissions. I am using Citizens2 to make the NPCs and the plugin CitizensCMD to add commands to them. I have heard about the permissions citizens.npc.talk and citizens.npc.text for other players to use the NPCs. When I gave those permissions to the default rank, players were still not able to use the NPCs. I reseted my server aswell. **Please help**

The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
You are 1923 version(s) behind**
The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1605) Website: http://www.citizensnpcs.co Authors: aPunch and fullwall CitizensText version 1.18 Allows to make speak your NPCs from Citizens. Website: https://www.spigotmc.org/resources/citizenstext.40107/ Author: SkytAsul CitizensCMD version 2.4 Author: Mateus Moreira**

**Comment by mcmonkey4eva** [comment]
- Get rid of CitizensCMD, use https://wiki.citizensnpcs.co/NPC_Commands
- Get rid of CitizensText, use `/npc text` or Denizen
- Update Citizens https://ci.citizensnpcs.co/job/Citizens2/
- Update your server to MC 1.15.2 https://wiki.citizensnpcs.co/Minecraft_1.8
