### ISSUE TITLE
Using "item" in NPC text editor returns blank String

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2189]
The output of command `/version` on my server is: **git-Paper-334 (MC: 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.26-SNAPSHOT (build 1951)**

When you enter the text editor using `/npc text` and then select the option `item` without any additional arguments or similar will the plugin return an empty String (blank line).

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/Citizens2/commit/02e68de7c7ee13970b18a3166417485a6c0fa287 for build 1997+ from https://ci.citizensnpcs.co/job/Citizens2/
