### ISSUE TITLE
NPC of type DROPPED_ITEM with material PLAYER_HEAD can't have a skin applied

### ISSUE THREAD

**Issue by calico-kid** [CitizensDev/Citizens2#2190]
feature request
i think it would be neat if you could put a player skin on the head of a npc that is a player head item type.
ways i thought this could be done is possibly by equipping the item npc with the head or via command.

Thanks for looking into this fullwall

no issues to report since this is a feature request.

**Comment by mcmonkey4eva** [comment]
This ... doesn't make sense as a feature request.
There's nothing stopping you from doing this already. Just `/npc equip`, hold the head, and right click... and it goes on the NPC's head.

**Comment by mcmonkey4eva** [comment]
Oh, after reading Discord chat history, I see what you wanted (an NPC of type DROPPED_ITEM with custom item data), and have renamed the issue accordingly.
