### ISSUE TITLE
How do I setup a npc that has the appearence of a player, but has the brains of a villager?

### ISSUE THREAD

**Issue by antiGriefer** [CitizensDev/Citizens2#2191]
Im just a rookie at Citizens2 so I will need a little help, I hope the title explains it all, but I will explain in more detail;

I would like npc's of my top 3 donators (%craftingstore_donator_1%, %craftingstore_donator_2%, %craftingstore_donator_3%) to derp around at spawn, like a villager or something. How do I set this up?

**Comment by mcmonkey4eva** [comment]
If you want wandering, `/waypoints provider wander`.

If you want NPCs turning to look at nearby players, `/npc lookclose`

If you want a click interaction to open a trade GUI or whatever, refer to `/npc help command` (add a command for whatever should happen when clicked, like opening a trade gui in whatever given trading plugin)

If you want literally a villager that looks like a player, er... get a disguises plugin?

**Comment by antiGriefer** [comment]
ok, thanks, but how do I use a placeholder for the npc?

**Comment by mcmonkey4eva** [comment]
If you want to automatically alter NPC names, you might consider using Denizen.
You might also consider a Holograms plugin to search as dynamic names, and simply hide the NPC nameplate via `/npc name`

Also, consider joining the Discord @ https://discord.gg/Q6pZGSR

**Comment by antiGriefer** [comment]
Its more that the skin is important, and a hologram cant follow it

**Comment by mcmonkey4eva** [comment]
Join the Discord @ https://discord.gg/Q6pZGSR
