### ISSUE TITLE
LookClose Help

### ISSUE THREAD

**Issue by mangguoyo** [CitizensDev/Citizens2#2192]
Sorry,My English is not good and I am using a translation software to communicate with you.

When the NPC looks at the player, the player quits the game, and the NPC will stare at the offline location.After the player logs in again, the NPC will not look at the player again.

This problem seems to only exist on PaperClip.

Sorry, my statement may not be very clear.

Please see if you can fix it, thank you very much.

The output of command `/version` on my server is: PaperClip-1.12.2
The output of command `/version citizens` on my server is: Citizens version 2.0.26-SNAPSHOT (build 1997)

**Comment by mcmonkey4eva** [comment]
The Paper team has long since dropped support for 1.12.2
There's not much we can do about issues specific to an old version of paper other than suggest you either update your server to a recent version (like Paper 1.15.2) or switch to spigot.
