### ISSUE TITLE
API: getTrait Method Name Is Misleading

### ISSUE THREAD

**Issue by Rincewind34** [CitizensDev/Citizens2#2194]
I would like to suggest a very little change to the api with (in my opinion) big impact. I have a problem with the Citizens#getTrait(...) method.
What the name suggests is, that it returns the trait instance, and if the trait is not applied (using addTrait) it returns null. That is obviously not the case. Instead it adds the trait if it's missing. The real name should be "getOrAddTrait" for a good transparency.

My suggestion is to make "getTrait" deprecated and provide two new methods "getOrAddTrait" and "getTraitSafely" (or something similar).

If this change happens to be accepts by the developers and the community I would create pull request with this changes my self (including the refactoring of the current code).

~ Rincewind

**Comment by fullwall** [comment]
Yes, this was a design decision made a long time ago that is a bit confusing IMO. If you make a PR I'll look at it, preferably getOrAddTrait
