### ISSUE TITLE
NPC Texture from 1.8

### ISSUE THREAD

**Issue by OriginalPhizzle** [CitizensDev/Citizens2#2197]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

![image](https://user-images.githubusercontent.com/46453696/85714512-ee5bcd00-b703-11ea-9170-ae5bac19cfd7.png)

![image](https://user-images.githubusercontent.com/46453696/85714625-0b909b80-b704-11ea-8850-6fbc67752a2f.png)

**Comment by fullwall** [comment]
I don't understand the issue sorry.

**Comment by OriginalPhizzle** [comment]
> I don't understand the issue sorry.

this npcs has skin with 3D model, but it displayed as skins from 1.8 (with out 3D)

**Comment by OriginalPhizzle** [comment]
example: 
![image](https://user-images.githubusercontent.com/46453696/85736590-0ccbc380-b718-11ea-811a-e98186c5dafd.png)
![image](https://user-images.githubusercontent.com/46453696/85736635-17865880-b718-11ea-85f6-88c4a4d709bd.png)
![image](https://user-images.githubusercontent.com/46453696/85736646-19501c00-b718-11ea-896c-e4549fd9736e.png)

**Comment by fullwall** [comment]
Fixed
