### ISSUE TITLE
NPC Piglin turns into a real zombie pigling & The new mobs Hoglin, Zoglin cannot be created yet.

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#2198]
Spigot-Version: CraftBukkit version git-Spigot-758abbe-8dc1da1 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

Citizens-Version:2003

I create a new mob from 1.16.1 the Piglin. With the command: / npc create 'Piglin' --type Piglin

A pigling then appears, but it trembles all the time. After a short time, the Piglin NPC turns into a real zombie pigling because you can then kill.

![2020-06-25_13 51 27](https://user-images.githubusercontent.com/35557302/85714946-3b7f7500-b6eb-11ea-9f73-543e15dba71f.png)
![2020-06-25_13 52 21](https://user-images.githubusercontent.com/35557302/85714971-40442900-b6eb-11ea-9d0d-9383f42e2b9d.png)

The new mobs Hoglin, Zoglin cannot be created yet.

**Comment by fullwall** [comment]
Fixed
