### ISSUE TITLE
NPC's are killable and they shouldn't be

### ISSUE THREAD

**Issue by sketrick** [CitizensDev/Citizens2#2200]
1.16.1 - Spigot - Citizens-2.0.27-b2006.jar	
After update I can kill all the NPC's. When they are suppose to be invincible.

**Comment by BehrRiley** [comment]
Can you paste the rest of the information requested that you removed from your issue template?

> - Link to server log & Citizens config (using e.g. pastebin.com)
> - **Spigot and Citizens versions!** Use in-game commands "/version" and "/version citizens" and screenshot or copy/paste the EXACT output of BOTH commands:
> - The output of command `/version` on my server is: **(PLEASE FILL IN)**
> - The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by sketrick** [comment]
https://pastebin.com/Ata90vbP
https://pastebin.com/X5gwVnif
https://ibb.co/5BxK55W

**Comment by Ph4i1ur3** [comment]
Due to the piles out outdated plugins, and the obvious cracked status of the server, this issue can likely be closed.

**Comment by sketrick** [comment]
PvPManager - Caused this issue, contacted the dev will wait for response.
