### ISSUE TITLE
Events for when a player is responsible for the deletion of a trait

### ISSUE THREAD

**Issue by blablubbabc** [CitizensDev/Citizens2#2201]
Hello,

I want to perform certain setup and cleanup whenever a specific trait is added or removed from a NPC.
A second goal is to provide the player who is adding or removing the trait with feedback messages about these setup and cleanup tasks being performed. If no player is responsible for the adding or removing of the trait (or I am not able to figure out the player), then it's also possible for noone to receive these feedback messages. The setup and cleanup tasks are still supposed to take place though.

Currently the API seems to provide the following relevant events:
* Methods inside Trait for when a trait is added/removed, NPCAddTraitEvent, NPCRemoveTraitEvent and NPCRemoveEvent: These events don't provide the player responsible for adding/removing the trait.
* NPCTraitCommandAttachEvent: Called after a player added a trait via the `/trait ..` command.
* PlayerCreateNPCEvent: Called when a player created a NPC. The NPC creation command allows traits to be specified which get added to the newly created NPC. So this event is effectively called before these traits get added.
* Bukkit's PlayerCommandPreProcessEvent which might maybe be used to figure out the player responsible for the following adding or removing of traits.

My current attempt is to maybe (WIP) defer any handling of trait additions and removals and determine the player from the above two Citizens events (NPCTraitCommandAttachEvent and PlayerCreateNPCEvent). I still have to figure this out in detail, but this might principally be possible (even though it's rather clunky trying to connect these events during runtime).

However, there don't seem to be any events yet for when a player removes a trait or deletes a NPC (which also results in the removal of its traits then).

Would you mind adding events for when a player deletes a trait or NPC? And/Or do you have any suggestions regarding how I could more easily figure out the responsible player in the above cases?

**Comment by fullwall** [comment]
I've added NPCRemoveByCommandSenderEvent - I think the generic trait events are probably better off being done by yourself?

**Comment by blablubbabc** [comment]
> I've added NPCRemoveByCommandSenderEvent

Thanks!

> I think the generic trait events are probably better off being done by yourself?

I don't understand what you mean by 'generic trait events'. And with 'done by yourself' you refer to creating a PR or creating some kind of workaround inside my plugin using the Citizens API?

There is basically an equivalent to the existing NPCTraitCommandAttachEvent missing for when a player removes a trait via the 'trait' command (eg. "NPCTraitCommandDetachEvent", or a more generic sounding "CommandSenderTraitRemoveEvent").

The other thing I mentioned was that players can also specify a list of initial traits inside the npc create command. However, I am not too sure how to go about this with a possibly new event..

One possibility could be to add a new generic "CommandSenderAddTraitEvent" and call that there. To also have this called for the trait additions via the 'trait ' command (i.e. in place of the existing NPCTraitCommandAttachEvent) one possibility could _maybe_ be to make this new event a base class of the existing NPCTraitCommandAttachEvent and remove the separate HandlerList from the NPCTraitCommandAttachEvent (not completely sure if this works that way without testing this / looking into the event system implementation; the idea would be that an event handler for the new base CommandSenderAddTraitEvent would receive both the CommandSenderAddTraitEvent for when the trait is added during npc creation and the NPCTraitCommandAttachEvent for when a trait is added via the 'trait' command, without having to call an additional new event there; and any event handlers for the NPCTraitCommandAttachEvent should still only receive that specific event).

Another alternative could be to call an event specific for that situation (eg. "CommandSenderAddInitialTraitEvent", "CommandSenderAddTraitToNewNPCEvent", "CommandSenderCreateNPCWithTraitEvent", or similar). Or one could call the existing NPCTraitCommandAttachEvent in that place duing NPC creation (though the name of this event makes it sound like it is intended specifically for the traits added via the 'trait' command, so this might be confusing).

> Can you give me more context for the reason you want this change?

Currently I use the following heuristic approach to perform certain setup whenever a specific trait got added, and optionally figure out the player responsible for that:
* I listen to the NPCAddTraitEvent and defer any setup I need to perform for the added trait by 1 tick.
* If I receive a NPCTraitCommandAttachEvent for the same trait afterwards within this 1 tick, I use the player of this event.
* If I don't receive such an event, or if there is some other trait related event received in between, I perform my setup without any associated player.
* If I receive a PlayerCreateNPCEvent, I remember the player. If I receive a relevant NPCAddTraitEvent within the next tick for the same NPC I assume that the remembered player is responsible for that trait addition.

All of this is rather 'hacky' currently since other plugin could be doing arbitrary things in between these events, or even during the handling of these events (such as adding or removing traits or npcs). But for now (and the simple case) this seems to work fine. Currently the player is also not strictly required for the setup I perform, but is simply used to receive feedback messages about it (so that he knows that him adding the trait has successfully triggered this setup action). So even if this heuristic approach breaks, the 'damage' is not so severe currently.

**Comment by fullwall** [comment]
Which traits are you doing additional setup for? Why are you doing the extra setup? It's just that I'll have to check all the spots in the code where a trait could possibly be added and put an event in there somewhere.

**Comment by blablubbabc** [comment]
Okay, my concrete use case is with the Shopkeepers plugin: https://github.com/Shopkeepers/Shopkeepers/tree/master/src/main/java/com/nisovin/shopkeepers/shopobjects/citizens

Players are able to create a Citizens NPC and then attach the custom 'shopkeeper' trait. The Shopkeepers plugin then needs to setup a corresponding 'Shopkeeper' for this Citizens NPC (this is the 'setup' I referred to above). In order to send a 'Shopkeeper created.'-message I need to know the player who added the trait (maybe there are more uses for the player in the future). However, if some plugin programmatically adds the trait I still need to setup the corresponding shopkeeper (so only listening to the NPCTraitCommandAttachEvent is not enough).

Previously I listened to the NPCTraitCommandAttachEvent to perform the setup with the player from this event. And at the same time I had a delayed task started inside the trait's #onAttach method which would check after a short delay whether the corresponding shopkeeper has already been created and otherwise create it.
I now wanted to update this to also take the player into account who is adding the trait during NPC creation (https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L500).

And also forward the player responsible for the trait or NPC removal to any methods dealing with the removal of the corresponding shopkeeper. (This is missing currently)

**Comment by fullwall** [comment]
Do other plugins programmatically add the trait? Yes, the trait command exists but theoretically any .getTrait call will add the trait (and can be triggered by a player) so we generally recommend creating your own /shopkeepers command/API to add the trait which will then have access to your CommandSender.

**Comment by blablubbabc** [comment]
> Do other plugins programmatically add the trait?

I am not aware of that, but I definitively want to support it.

> Yes, the /trait command exists but theoretically any .getTrait API call will add the trait (and can be triggered by a player) so we generally recommend creating your own /shopkeepers command/API to add the trait which will then have access to your CommandSender.

There is a command built into the Shopkeepers plugin for spawning these Citizens NPCs. But I am aware of users using the trait directly with Citizens' trait commands and I see no reason why I wouldn't want to support that (especially since this already works quite well currently).

> So for instance in Citizens any /npc wolf or /npc ocelot command will add a trait and require an event to be sent.

Okay, I didn't think about these already built-in traits and how they are getting attached under various player triggered conditions to make things work.

Anyways, like I said, my current setup already works quite well and being able to send the player feedback messages isn't that important of an aspect. Especially since specifying traits directly with the NPC create command is probably a rather unusual special case anyways. So if you deem adding a generic event for that to not be worth the effort I am totally fine with that.

However, what do you think about adding a direct pendant to the currently existing NPCTraitCommandAttachEvent (maybe called "NPCTraitCommandDetachEvent") for the case that a player removes a trait via Citizens' trait command? Since its scope is rather narrow, this would probably simply need to be called at this single location: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/TraitCommands.java#L119
Similar to the simple implementation of the NPCTraitCommandAttachEvent (https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/TraitCommands.java#L63).

Together with the already added new NPCRemoveByCommandSenderEvent this should cover the most common cases of a player removing the trait.

**Comment by blablubbabc** [comment]
Thanks!
