### ISSUE TITLE
HorseTrait in Llama

### ISSUE THREAD

**Issue by Rincewind34** [CitizensDev/Citizens2#2203]
While looking through the code I noticed, that in the LLamaController the HorseModifiers trait is added. I think this is probably a copy paste mistake? The HorseModifiers trait does nothing for llamas as far as I can see.

**Comment by mcmonkey4eva** [comment]
Llamas are, as far as Spigot API cares, a type of horse. They contain several matching properties, such as chest carrying, saddle items, etc.
