### ISSUE TITLE
[1.16.1] Crash on right click to a Villager NPC

### ISSUE THREAD

**Issue by Lix3nn53** [CitizensDev/Citizens2#2204]
The output of command `/version` on my server is:  This server is running CraftBukkit version git-Spigot-758abbe-38de0b8 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2008)

Logs: [2020-06-26-17.log](https://github.com/CitizensDev/Citizens2/files/4835799/2020-06-26-17.log)
Crash report:
[crash-2020-06-26_10.51.22-server.txt](https://github.com/CitizensDev/Citizens2/files/4835756/crash-2020-06-26_10.51.22-server.txt)

Also I have a custom plugin that uses `NPCRightClickEvent` but I could not find anything related to this problem there. `NPCRightClickEvent` in the custom plugin is opening a GUI at the last line and it opened without error before server crashed so I dont think the problem is there. The only thing I do in `NPCRightClickEvent` is getting the NPC ID and doing some stuff according to it which is not related to citizens. https://github.com/Lix3nn53/GuardiansOfAdelia/blob/master/src/main/java/io/github/lix3nn53/guardiansofadelia/events/MyNPCRightClickEvent.java

**Comment by Lix3nn53** [comment]
Forgot to say that right clicking on Player NPCs works without problem.

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/Citizens2/commit/b62780a91e3d1c283ed583d40ae563a9493e0837 in build 2009+
