### ISSUE TITLE
GIve text to npc with a plugin

### ISSUE THREAD

**Issue by a-wernon** [CitizensDev/Citizens2#2205]
Is there a way to add text to npc w/o using gui?
I've found no method in API and even tried to emulate all gui actions like "/npc sel %id%; npc text; add; %text% ", but that requires me to be ingame.

**Comment by mcmonkey4eva** [comment]
When in doubt, check the source code: https://github.com/CitizensDev/Citizens2/tree/master/main/src/main/java/net/citizensnpcs/trait/text

**Comment by fullwall** [comment]
Yes, the Text trait has API methods.
