### ISSUE TITLE
Lookclose Default Angle

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2207]
The output of command `/version` on my server is: **2.0.26-SNAPSHOT (build 1951)**
The output of command `/version citizens` on my server is: **git-paper-334 (MC 1.15.2)**

When using lookclose on an NPC does it always remain in whatever rotation it was, when the player went out of its radius.
It would be a nice addition if we could define a default rotation that the NPC would return to when no player is within its lookclose range.

**Comment by fullwall** [comment]
I've added /npc pose default [name] (and /npc pose save [name] -d) to allow this in a trait-agnostic way.
