### ISSUE TITLE
People besides /op can't ride NPCs anymore.

### ISSUE THREAD

**Issue by Nues** [CitizensDev/Citizens2#221]
Noticed we've upgraded into a new server and downloaded the 2.0.13 version for CB 1.7.9, me as a co-owner can't make people ride the NPCs anymore, despite the fact that we used the same version on the same server version (Same CB 1.7.9 plugin with the same version on the server, 1.7.10).

Before, everyone, even the default group, could ride them, and we set up games that way.
Now we can't do this anymore.

And I've noticed that it's something to do with ownership.

So I want to remove ownership dominance, so that everyone can ride them.

How do I do that?

**Comment by mcmonkey4eva** [comment]
We're very limited in how much support we can provide for outdated versions.
It's likely you encountered a bug that exists in the specific version you downloaded only.
Please update.

**Comment by Nues** [comment]
Okay, but this is the second to latest version, which can't be that outdated.

Can you at least explain what would the problem be if it was in 1.8.1, the latest version?

**Comment by Nues** [comment]
So that I can fix it when I update.
