### ISSUE TITLE
[1.16.1] NPC spawn calls are rejected in one of the worlds, works fine on others.

### ISSUE THREAD

**Issue by Lix3nn53** [CitizensDev/Citizens2#2210]
The output of command `/version` on my server is:  This server is running CraftBukkit version git-Spigot-ad703da-d77f4d9 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2014)

logs: 
[latest.log](https://github.com/CitizensDev/Citizens2/files/4841887/latest.log)

Description: NPCs are working fine in every world but one. In my world named `tutorial` NPCs wont spawn even when I do `npc create`. I already run --forceUpgrade on the server and it was working fine on 1.15.2.

**Comment by mcmonkey4eva** [comment]
Relevant log lines:
```
[10:53:44] [Server thread/INFO]: Lix3nn issued server command: /npc tp
[10:53:44] [Server thread/INFO]: Retrying spawn of 9 later due to chunk being unloaded. Util.isLoaded true
[10:53:44] [Server thread/INFO]: Couldn't respawn id 9 during chunk event at [29,2]
[10:53:59] [Server thread/INFO]: Retrying spawn of 10 later due to chunk being unloaded. Util.isLoaded true
[10:53:59] [Server thread/INFO]: Couldn't respawn id 10 during chunk event at [18,7]
```

**Comment by fullwall** [comment]
So worldServer.addEntity is returning false (i.e. something in Minecraft is saying that you can't spawn the entity in that world). Could it be a plugin conflict? Or a world rules conflict?

**Comment by fullwall** [comment]
Can you get some debug output with the newest build please?

**Comment by Lix3nn53** [comment]
Multiverse Core prevents default spawns but it was always like that and does not cause problems in other worlds. Also `location.getWorld().spawnEntity(location, entitiyType);` works fine in the problematic world.

Plugins on the server: citizens, libs disguses, luckperms, multiverse core, protocol lib, world edit, world build
World rules: As long as I know it does not have any different rules than other maps.

new logs (couldnt see any extra log?):
[2020-06-28-16.log](https://github.com/CitizensDev/Citizens2/files/4842043/2020-06-28-16.log)

**Comment by fullwall** [comment]
Would it be possible to try without any plugins except Citizens? Having a hard time replicating this.

**Comment by Lix3nn53** [comment]
I tried with: 
- lastest spigot and citizens 
- `--forceUpgrade`
- plugins: citizens and multiverse core(so extra worlds load)
 but nothing changed. 

Created a new world with multiverse core command, have no problem there. I guess I will copy paste my buildings there when I have time. Thanks for the help!

**Comment by Lix3nn53** [comment]
I have no idea how but this worked:
- create backup for `tutorial` world folder
- remove `tutorial` from multiverse core
- create `tutorial2` via in game multiverse command
- set same settings from `tutorial` to `tutorial2` via ingame commands(copying config sections does not work)
- stop server, rename `tutorial2` to `tutorial` in multiverse core configuration
- rename `tutorial2` world folder to `tutorial` and copy paste `tutorial` backup to new `tutorial` world folder

Sorry for taking your time, it seems like a multiverse core configuration error? But I am absolutely sure I did not change multiverse core configuration while updating to 1.16.1 from 1.15.2. Anyways sorry for taking your time, thank you.
