### ISSUE TITLE
[1.16.1]  [Citizens] NPC type PIG_ZOMBIE was not recognized. Did you spell it correctly?

### ISSUE THREAD

**Issue by mrfloris** [CitizensDev/Citizens2#2212]
Started up 1.15.2 citizens/ folder and new 1.16.1 jenkins build of citizens and noticed this on startup on an existing world. I thought i'd report it.

i didn't see it listed in the yml files
```
floris@Floriss-iMac Citizens % cat *.yml |grep "pig_zombie"
floris@Floriss-iMac Citizens %
```

```
 [Citizens] NPC type PIG_ZOMBIE was not recognized. Did you spell it correctly?
```

The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version ` on my server is: **(PLEASE FILL IN)**

```
>
>ver
[15:15:44] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-ad703da-e2403a3 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[15:15:44] [Server thread/INFO]: Checking version, please wait...
[15:15:44] [Thread-53/INFO]: You are running the latest version
>ver citizens
[15:15:46] [Server thread/INFO]: Citizens version 2.0.27-SNAPSHOT (build 2018)
[15:15:46] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[15:15:46] [Server thread/INFO]: Author: fullwall
>
```

**Comment by mcmonkey4eva** [comment]
`grep` by default is case sensitive, you should check with `grep -i`

**Comment by fullwall** [comment]
It has been renamed to Zombified Piglin

**Comment by mrfloris** [comment]
> `grep` by default is case sensitive, you should check with `grep -i`

woops, yep. Found it. 


> It has been renamed to Zombified Piglin

Yes, I know, was hoping since the last time i reported an alike thing that the upgrade would have caught this and renamed it when found.

**Comment by mcmonkey4eva** [comment]
That auto-rename was added via https://github.com/CitizensDev/CitizensAPI/commit/47dd771efc15b0456ca739bd2e55c040c6292308 at the same time fullwall wrote that reply.
That fix is included in build 2020+ from https://ci.citizensnpcs.co/job/Citizens2/

**Comment by mrfloris** [comment]
Thank you for the help.
