### ISSUE TITLE
/npc lookclose doesn't work

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2213]
The output of command `/version` on my server is: **2.0.27-SNAPSHOT (build 2018)**
The output of command `/version citizens` on my server is: **git-Paper-371 (MC: 1.15.2)**

NPCs that have a pose set are no longer able to move using `/npc lookclose`
They will remain in the position you set.

1. Create a new pose using `/npc pose --save <name>`
2. Enable lookclose using `/npc lookclose`
3. Enter and leave the NPCs lookclose area.
4. The NPC won't rotate and look at you.

**Comment by mcmonkey4eva** [comment]
That's probably
https://github.com/CitizensDev/Citizens2/commit/0293ac17dfddb9f34425213dc095aed8b9369027#diff-0742b33e8556f8bd8686b87696a747dfR128
```java
                && (!npc.hasTrait(LookClose.class) || npc.getTrait(LookClose.class).canSeeTarget())) {
```
A missing `!` on the `canSeeTarget`

**Comment by Andre601** [comment]
Works with the latest release.
