### ISSUE TITLE
[Suggestion] Allow all entity types to have colored glow effect

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2215]
The output of command `/version` on my server is: **git-paper-371 (MC 1.15.2)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (Build 2019)**

Other entity-types seem to be able to have a glow color set to them proven by the fact that the plugin TrainCarts applies a glow color to an entity (armor stand for all I know) to highlight the block, item, ... in general.
So having the glow color restricted to player entities only seems like a bad thing now.

This seems to be the best I can find on how TrainCarts seems to assign a glow with color:
https://github.com/bergerhealer/TrainCarts/blob/d604abd014b17c5a3e597b24b75c3eacf9144a3c/src/main/java/com/bergerkiller/bukkit/tc/attachments/control/GlowColorTeamProvider.java#L118

It seems to just apply a team to the entity to then set the glowing color for it.

**Comment by mcmonkey4eva** [comment]
Did a quick test to validate that this is very possible:

![test](https://i.alexgoodwin.media/i/misc/fbbbc4.png)

**Comment by fullwall** [comment]
Preliminary stuff to add this was done, however even when creating a scoreboard for the mob NPC I couldn't get the color to change?

**Comment by fullwall** [comment]
Added
