### ISSUE TITLE
Bedwars Tester

### ISSUE THREAD

**Issue by bojaspie** [CitizensDev/Citizens2#2216]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by bojaspie** [comment]
i've tried to download the bedwars test and example thing and it hasnt been working when i've tried to download showing me errors is this a problem or something?

**Comment by mcmonkey4eva** [comment]
I don't know where you're trying to be, but this ain't it.
This is the Citizens NPCs github issues page. Nothing to do with bedwars here.
