### ISSUE TITLE
Invulnerable trait not working

### ISSUE THREAD

**Issue by Korinocho** [CitizensDev/Citizens2#2218]
The invulnerable trait isnt working
Even if you turn if off and on again they receive damage
If you need some video i can upload it but its simple:
1. Create npc
2. Hit him
3. He receive damage

The output of command `/version` on my server is: Paper gip-Paper-41 (MC 1.16.1)
The output of command `/version citizens` on my server is: 2.0.27 (Build 2026)

**Comment by mcmonkey4eva** [comment]
Can't replicate this. Have had one other user report a similar problem that turned out to be caused by a different plugin.

Can you please pastebin your `logs/latest.log` (as the issue template requests)

**Comment by Korinocho** [comment]
Of course
[latest.log](https://github.com/CitizensDev/Citizens2/files/4865829/latest.log)
There it is

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
