### ISSUE TITLE
Rabbits Sentry problem

### ISSUE THREAD

**Issue by elraro** [CitizensDev/Citizens2#222]
Cticizens2 #1206
Sentry #23 

All from jenkins.

Bug: Trait the rabbit like sentry and the rabbit doesnt move.

1) Create a NPC
2) /npc type rabbit
3) /trait sentry
4) /sentry target add entity:player

And the rabbit only attack if u are close, the rabbit never move :(

(sorry for my bad english, i hope u understand me :) )

**Comment by elraro** [comment]
/bump...

**Comment by mcmonkey4eva** [comment]
I'm dealing with issues with my dev environment ATM, but I'll check this out ~Friday if nobody else fixes it first.

**Comment by elraro** [comment]
something?

**Comment by mcmonkey4eva** [comment]
Oops, forgot this. I just checked and rabbits aren't responding to movement commands...

**Comment by elraro** [comment]
ok thanks :) Hope u get this solved soon!

**Comment by mcmonkey4eva** [comment]
Here's a temporary fix build: https://dl.dropboxusercontent.com/u/54130586/citizens-2.0.14-SNAPSHOT.jar
As a side effect, killer rabbit NPCs ... attack. Not sure how to patch this, as general movement and attacking share a function. Will work on it.

**Comment by elraro** [comment]
Can u guys update the jenkins with the last pull?

Thanks you.

**Comment by mcmonkey4eva** [comment]
Oh, woops. Building now.
