### ISSUE TITLE
Sometimes NPC doesn't start walking

### ISSUE THREAD

**Issue by Nick-kel** [CitizensDev/Citizens2#2221]
**A detailed description of your issue or feature request**
If I'm using the CitizensAPI and Navigations, sometimes a NPC doesn't start walking. So sometimes it starts walking and sometimes it starts walking only at the second/third/... try. I didn't change anything. 

Link to server log & Citizens config (using e.g. pastebin.com)
https://pastebin.com/FQu2kZWC

**Spigot and Citizens versions!** 
![image](https://user-images.githubusercontent.com/42046014/86538920-7195d380-bef9-11ea-91a5-6fa5adbf9b43.png)

**Comment by mcmonkey4eva** [comment]
This isn't an issue with Citizens. It's probably an issue with your own code.

Consider requesting help on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel.
