### ISSUE TITLE
NavigationCompleteEvent no call if target is an entity

### ISSUE THREAD

**Issue by Nick-kel** [CitizensDev/Citizens2#2223]
**A detailed description of your issue or feature request**
If I use navigations and the target is an entity (e.g. armor stand), the NavigationCompleteEvent is not called. If it isn't an entity, the event will be called.

Link to server log & Citizens config (using e.g. pastebin.com)
https://pastebin.com/FQu2kZWC

**Spigot and Citizens versions!** 
![image](https://user-images.githubusercontent.com/42046014/86538920-7195d380-bef9-11ea-91a5-6fa5adbf9b43.png)

**Comment by mcmonkey4eva** [comment]
Of course it's not called: the navigation never completes. It continues following the entity until navigation is cancelled.
