### ISSUE TITLE
Spam Console

### ISSUE THREAD

**Issue by thedarkcookieez** [CitizensDev/Citizens2#2224]
https://hastebin.com/fuwetehune.md

Can I disable the message in the console?

When NPCs move, the message appears

The output of command `/version` on my server is:Git Paper 1.16.1 75 MC
The output of command `/version citizens` on my server is: Citizens-2.0.27-b2036.jar

**Comment by mcmonkey4eva** [comment]
Update: https://ci.citizensnpcs.co/job/Citizens2/

If you're already on latest (as your message somewhat implies), please reply with the actual output of `/version` and `/version citizens`
