### ISSUE TITLE
Nametags get stuck after removing NPC

### ISSUE THREAD

**Issue by FreePvp** [CitizensDev/Citizens2#2227]
I remove the NPC and nametags stay

![image](https://user-images.githubusercontent.com/11426776/86800066-a496af00-c040-11ea-8137-de97f183b229.png)

**Comment by fullwall** [comment]
What Citizens version?

**Comment by FreePvp** [comment]
> What Citizens version?

2.0.27 (-b2036 if that helps any)

**Comment by Boy17000** [comment]
ive got the same problem, also version 2.0.27, as soon as I installed Sentinel plugin and created a npc. the npc left a extra holo gram of the name. despawning the npc did not work. Minecraft feature with "kill @e" and such didn't work either.

**Comment by mcmonkey4eva** [comment]
This can be consistently replicated, with Citizens as only plugin on server, by just doing `/npc create bob with the very long name` and then `/npc rem` (testing on build 2042)

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/CitizensDev/Citizens2/commit/ea20cdb21eee27d53302583a0a7d82cab87e97cb for build 2043+ from https://ci.citizensnpcs.co/job/Citizens2/
