### ISSUE TITLE
Npc's flying in minecarts.

### ISSUE THREAD

**Issue by Johnsonk2** [CitizensDev/Citizens2#2228]
So when trying to get my NPC (Jango) to mount into an NPC minecart, nothing happens. Only when you toggle **controllable** on the minecart does Jango mount it. And when that does happen the minecart flys away with Jango in it. Sidenote: the boat does seem to work when toggling **controllable** but the **lookclose** for Jango takes over the boat at the same time, moving both of them.  (Unsure if that works with minecarts due to the above bug, but I'd guess that to be true too.

EDIT: Seems to work for players mounting them also.

-No server logs sadly, I don't have access. (not the owner, just op)

![image](https://user-images.githubusercontent.com/25190838/86849840-308ff180-c0a8-11ea-8aaf-ede9d34c23ae.png)
![image](https://user-images.githubusercontent.com/25190838/86850007-6df47f00-c0a8-11ea-85d7-7f4fd539af61.png)

Hope that's all you need, I didn't include the command outputs as the versions are shown above.
Thanks.

**Comment by fullwall** [comment]
Fixed by defaulting controllable to ground controller for vehicles.
