### ISSUE TITLE
Citizens becomes a tps killer

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#2229]
Citizens: Citizens-2.0.27-b2037.jar
Paper: Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

Our server has problems with Citizens. As you can see from the timings, Citizens is already overloading the server with 1-3 players with almost 60% server performance.

https://timings.aikar.co/?id=afff379d73744bc1b4ec2afbdffa6f7a

**Comment by mcmonkey4eva** [comment]
Known paper specific issue: https://github.com/PaperMC/Paper/issues/3573

**Comment by Blueeyestar** [comment]
So if I take normal spigot again, should the problem be solved?

**Comment by mcmonkey4eva** [comment]
yep

**Comment by Blueeyestar** [comment]
Has this problem been reported directly to paper?

**Comment by mcmonkey4eva** [comment]
yes and I linked that report

**Comment by fullwall** [comment]
Can you try build 2041 please?

**Comment by Momonche** [comment]
@fullwall Build 2041 not solve this issue :/

**Comment by CapraGenus** [comment]
@Blueeyestar if you wish to stay with paper you can also enable always-keep-loaded setting within the citizens config which can help with the issue as it keeps the chunks loaded where NPCs are located, should drop the 60% usage down ALOT. But again yes its a paper issue.
