### ISSUE TITLE
ERROR IN THE NAMES

### ISSUE THREAD

**Issue by delocura** [CitizensDev/Citizens2#2232]
The names have a error of visibility.
I have updated the server today and citizens and i cant hide the names.

I have the latest version.

The log dont says nothing.

I have tested with other types of npcs and only happens with the /npc type player

Thanks.

**Comment by mcmonkey4eva** [comment]
Yep, looks like `/npc name` needs to be updated for the hologram nameplate change.

**Comment by delocura** [comment]
Ok, so need a new update no?

**Comment by mcmonkey4eva** [comment]
It's a confirmed bug, and the problem/solution are pretty clear, just need to do the codework&testing for it. There'll probably be a fix available within a day or two.

**Comment by delocura** [comment]
Ok, thank you very much, I'll wait. Much encouragement!

**Comment by fullwall** [comment]
Fixed
