### ISSUE TITLE
NPC Being removed in game on server restart (1.12.2 server)

### ISSUE THREAD

**Issue by ScrubZero** [CitizensDev/Citizens2#2234]
Whenever I conduct a server restart, all of the NPCs that I have created are removed from the game. I can not call them back with commands, and I can not selected them in any way, both in and out of the config, however, their data is still listed within the server's "saves" folder. I try to call them by both their NPC name, and their given NPC ID, but none wokr, and I get a message saying that "No NPC with the ID X exists." I'm wondering if this is specifically an issue with the Citizen's plugin, or if possibly there are other plugins that are stopping the respawning of my NPC's once the server is restarted. 

Below is the .ZIP file for all of the NPC's that should be loaded into the server upon restart, however, for some odd reason, the only NPC that loads in and stays for every restart is ID 8; Private Samuel, which is an NPC that I don't believe is in use, or even exists on a world folder anymore. Somehow, this is the only NPC that can withstand a full server reload / restart, while the other ones all get removed from the game. 

[plugins_Citizens_SavesFile.zip](https://github.com/CitizensDev/Citizens2/files/4899454/plugins_Citizens_SavesFile.zip)

Clearly, you can see that there are a ton of NPC's that naturally, should be working according to their state in the config, however I have no idea why they do not list once I am on the server. Anything that you can do to help would be greatly appreciated, thank you for your time, and thank you for providing such a wonderful plugin. 

Cheers, ScrubZero

The output of command `/version` on my server is: 
![Server Version](https://user-images.githubusercontent.com/68083446/87089086-dad05c00-c203-11ea-9ed3-7735b8e08c2d.png) 

The output of command `/version citizens` on my server is: 
![Citizen's Version](https://user-images.githubusercontent.com/68083446/87089100-df951000-c203-11ea-93e2-fef68956747c.png)

**Comment by mcmonkey4eva** [comment]
- Update to a recent Citizens build https://ci.citizensnpcs.co/job/Citizens2/
- Ideally update your server version to something more modern like 1.15.2 if you can
- If problems continue after updating, please reply with a pastebin of the contents of `logs/latest.log`

**Comment by ScrubZero** [comment]
One thing I forgot to mention, I am unable to update my server past 1.12.2, as there are many plugins that wouldn't function properly if I did. Is there anything that I am able to do with this current version?

**Comment by mcmonkey4eva** [comment]
As I said: Update to a recent Citizens build https://ci.citizensnpcs.co/job/Citizens2/
