### ISSUE TITLE
NPC's randomly showing that they are navigating but never move on MINECRAFT:Farmland

### ISSUE THREAD

**Issue by Nutty101** [CitizensDev/Citizens2#2238]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
`This server is running CraftBukkit version git-Spigot-ccb012a-4309566 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
`Citizens version 2.0.27-SNAPSHOT (build 2057) - Priors seem to suffer from this as well.`

This is when using the API to set the location to navigate. 
`net.citizensnpcs.api.ai.Navigator.setTarget(Location var1)`

They are marked as Navigating but never move no matter what targets i give to move. If i teleport them a block away, or even 1 above they will move again.
![image](https://user-images.githubusercontent.com/14265073/87235436-b1e5cd80-c3a1-11ea-9ddf-e7704c58f4a4.png)

This is what shows in the navigator.
![image](https://user-images.githubusercontent.com/14265073/87235424-9e3a6700-c3a1-11ea-92a3-d5525f302aa5.png)

I can fix it by debugging the steps and calling this.
`npc.teleport(npc.getEntity().getLocation().clone().add(1,2,1), PlayerTeleportEvent.TeleportCause.PLUGIN )`

**Comment by fullwall** [comment]
Can't reproduce this, but could be a MC pathfinder issue.

**Comment by mcmonkey4eva** [comment]
With new-finder false, NPCs will happily move over farmland but will walk entire circles around large areas to avoid doing so if they can. With new-finder true, NPCs will walk right over it without question.
Have not been able to replicate any amount of getting stuck either way.
I tested with both dry and wet farmland blocks.
On Spigot `git-Spigot-3a70bd9-bf3d720 (MC: 1.16.3)`
on Citizens `version 2.0.27-SNAPSHOT (build 2113)`

Will need a way to replicate the issue before being able to do anything about it.
