### ISSUE TITLE
plugin.yml missing in jar

### ISSUE THREAD

**Issue by kalleswe** [CitizensDev/Citizens2#2240]
Building git repo 1.16 proudces the jar file but the jar file is missing a plugin.yml file, so the plugin won't load.
Consider updating repo AND build script with plugin.yml.

The output of command `/version` on my server is: Not applicable since not even coming to that yet.
The output of command `/version citizens` on my server is: NONE since it does not load.

**Comment by mergu** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/resources/plugin.yml

You have to build the entire project. The versioned modules only include NMS-related code and as such should not be built alone.

**Comment by mcmonkey4eva** [comment]
Also, you can just download builds from https://ci.citizensnpcs.co/job/Citizens2/
