### ISSUE TITLE
Server crashed when pushing npc into end portal

### ISSUE THREAD

**Issue by matthewdm0816** [CitizensDev/Citizens2#2241]
The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-c3a49df-2f18108 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2038)**

When I'm pushing a npc into end portal the server crashed(it also crashes when interacting with back-portal in the end). I tried on a completely new world/save and the problem happened to this new world too(only one npc created for test, its configs are set default).

Server Log: https://paste.ubuntu.com/p/Rs4BdtPtbR/
Citizens Config: https://paste.ubuntu.com/p/m3bqYs8VNt/

**Comment by mcmonkey4eva** [comment]
I do believe this issue was recently reported and fixed already. Try with the latest build https://ci.citizensnpcs.co/job/Citizens2/

**Comment by fullwall** [comment]
No, seems like a separate issue (possibly related to playerlist again)

**Comment by fullwall** [comment]
Latest build has a fix for this.
