### ISSUE TITLE
Citizens NPC head rotation speed

### ISSUE THREAD

**Issue by colinnijhout** [CitizensDev/Citizens2#2247]
Hello,

mcmonkey told me to post a feature request for an idea that I had. Right now, NPC's can have a default facing direction, however, the NPC's can't turn their head back to the default position at a certain speed. Currently, it is very quick and it would be nice to have this is a smoother way.

**Comment by paulreob** [comment]
hey I would also like to see this function implemented, it would be very useful ^^

**Comment by witherStormXD** [comment]
is a very good idea should be added!
