### ISSUE TITLE
PlayerUpdateTask high Usage

### ISSUE THREAD

**Issue by LakeArcFox** [CitizensDev/Citizens2#2248]
Timings:
https://timings.aikar.co/?id=ecb3cd37b9724bb290dbf15054010c75
There are only two NPCs and one player in server.
PaperSpigot 1.12 Citizens 2.0.22
[saves.txt](https://github.com/CitizensDev/Citizens2/files/4943416/saves.txt)

The output of command `/version` on my server is: 
This server is running Paper version git-Paper-1574 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
You are 44 version(s) behind

The output of command `/version citizens` on my server is: 
Citizens version 2.0.22-SNAPSHOT (build 1487)
Website: http://www.citizensnpcs.co
Authors: aPunch and fullwall

**Comment by Ph4i1ur3** [comment]
Offline mode servers can not/will not be supported.
Refer to this link for more information:
https://wiki.citizensnpcs.co/Cracks

**Comment by fullwall** [comment]
To properly debug this issue you need to update Citizens to latest build (should work with 1.12) and get a spark profile.
