### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination

### ISSUE THREAD

**Issue by Reese14** [CitizensDev/Citizens2#2249]
- A detailed description of your issue or feature request:
When I try to do /npc create, it says in chat to 'Please report this error: [See console].' 

- Link to server log & Citizens config (using e.g. pastebin.com) ESPECIALLY if it's a pathfinding issue:
Server Log: https://pastebin.com/wxgMnv8P
Citizens Config: https://pastebin.com/isx56MRK

- FOR LAG RELATED ISSUES: please include server specs, number of NPCs, saves.yml and timings from WarmRoast or other profiler (NOT just Spigot timings, though that can be included as well)
3MB of RAM (Small server, and it's a hub server so not a lot of RAM needed)

The output of command `/version` on my server is: **This server is running CraftBukkit version git-Spigot-4d24e36-5193f76 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT))**
The output of command `/version citizens` on my server is: **Citizens v2.0.26-SNAPSHOT (build 1962)**

**Comment by mcmonkey4eva** [comment]
Update your server to a properly supportable minecraft version.

**Comment by Reese14** [comment]
How do I know what versions are suported?

**Comment by fullwall** [comment]
Use 1.14.4, not 1.14. Preferably use 1.16.1 if you can.

**Comment by mcmonkey4eva** [comment]
1.15.2 and 1.16.1 are ideal.
1.14.4 is acceptable if you specifically need that older version. 1.14(.0) is not.

**Comment by Reese14** [comment]
Okay, I appreciate the help.
