### ISSUE TITLE
How to execute a commands from the server not from the console with one npc? Please I need help!

### ISSUE THREAD

**Issue by Yan-Mihaylov** [CitizensDev/Citizens2#2250]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by Ph4i1ur3** [comment]
Use the `-p` argument in the command.

Please keep in mind GitHub is for issues, if you need help please join the support discord, as outlined in the readme:
https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
See also the wiki page here: https://wiki.citizensnpcs.co/NPC_Commands
