### ISSUE TITLE
when i create /npc hologram add test

### ISSUE THREAD

**Issue by Himo313** [CitizensDev/Citizens2#2251]
its create a new hologram but i get error
and if i try to remove hologram the hologram doesn't get removed
this is the error i get in the console https://pastebin.com/YjuGwWwV
server version paperspigot 1.8.8
plugin version 2.0.27 (1.16 ALPHA #3)

**Comment by Ph4i1ur3** [comment]
Try updating Citizens.

If you need further support, please join the support discord:
https://discord.gg/Q6pZGSR
