### ISSUE TITLE
Error when player joins

### ISSUE THREAD

**Issue by LoSCraft-Network** [CitizensDev/Citizens2#2254]
Good afternoon, I get this error when a player joins the server [https://hasteb.in/ocozaful.shell](url).
The output of command `/version` on my server is: **git-Tuinity-"7b639ea" (MC: 1.16.1)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2073)**

**Comment by Ph4i1ur3** [comment]
Report is from an offline mode server. Discord name: Dandan220
