### ISSUE TITLE
ID flickering in tab now

### ISSUE THREAD

**Issue by Merabi12** [CitizensDev/Citizens2#2255]
1.8.8 Server Version
2.0.27 (2073 build) Citizens

Now the ID of the npc is flickering in tab not whatever name i give it.

https://gyazo.com/2a0bc7fe815b05bf2d221332b4c11729 - replay of the issue
https://paste.helpch.at/zepesimode.md - log

**Comment by mcmonkey4eva** [comment]
This is normal and unavoidable. https://wiki.citizensnpcs.co/Frequently_Asked_Questions#Why_are_NPCs_showing_up_in_the_tablist.3F
