### ISSUE TITLE
Giving NPC a long name (using API and command) will result in random string as nametag and the name as hologram

### ISSUE THREAD

**Issue by kleinesNugget** [CitizensDev/Citizens2#2256]
We renamed an NPC and changed the Skin using the API and it resulted in what we expected, but a random nametag appeared which we obviously didn't want to have. After relogging the nametag disappears but everytime the plugin updates the name (or ourselves with the /npc rename command) the random nametag re-appears (See screenshots at the bottom)
When we /npc rename the npc to a short name it seems to work flawlessly (until it gets a long name again).
The string that appears to be random starts with 7 for all npcs that we had here, but continued with a random combination of numbers and letters.

Server Log: https://pastebin.com/i9EqP76H
Config: https://pastebin.com/Spu2EYnM

The output of command `/version` on my server is: 
**[14:55:38 INFO]: This server is running Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[14:55:38 INFO]: Checking version, please wait...
[14:55:38 INFO]: Previous version: git-Paper-49fdb182 (MC: 1.15.2)
[14:55:38 INFO]: You are 4 version(s) behind**

The output of command `/version citizens` on my server is: 
**[15:08:17 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2083)
[15:08:17 INFO]: Website: http://www.citizensnpcs.co/
[15:08:17 INFO]: Author: fullwall**

The reason that I'm sure that it's the actual nametag of the npc that shows the random string is because it disappears once I press F1 to hide my HUD and so on (See 2nd screenshot where the random string is gone)

![image](https://user-images.githubusercontent.com/44408413/88682570-19668180-d0f3-11ea-83ab-644c0d37cdd3.png)
![image](https://user-images.githubusercontent.com/44408413/88682583-1cfa0880-d0f3-11ea-9ced-d93ba2ab4286.png)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
