### ISSUE TITLE
i downloaded citizens and its appearing in my minecraft ingame command but when i do /npc create <name> the command doesnt works and my version is 1.13.2

### ISSUE THREAD

**Issue by jordans5566** [CitizensDev/Citizens2#2258]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by mcmonkey4eva** [comment]
Please either post the information requested in the issue template, or come ask for help on the Discord @ https://discord.gg/Q6pZGSR
