### ISSUE TITLE
[Flood] Error in Logs File

### ISSUE THREAD

**Issue by Rouchesta** [CitizensDev/Citizens2#2259]
- Dear Support, since i addded Denizen and Sentinel to my server my logs are flooded with an error. The log file become unusable because of the size of the file after w few minutes.

- Error : https://pastebin.com/LrMq6mZj

Paper 1.14.4
Citizens 2.0.27 (1.16 ALPHA #394)
Denizen 1.1.5-b4997-DEV
Sentinel 2.1.5

**Comment by mcmonkey4eva** [comment]
Please pastebin the full contents of `logs/latest.log`

**Comment by Rouchesta** [comment]
Here is the correct link with full logs : https://pastebin.com/mpxi7pag

**Comment by Rouchesta** [comment]
ProtocolLib has been updated but know the server stop responding with a Denizen Error.
https://pastebin.com/3bX01TA7
