### ISSUE TITLE
[Feature Req] /npc center and /npc tphere -center

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2261]
It would be nice to have a `/npc center` which centers the npc on the current block that it is standing on. In addition to this a `/npc tphere -center` would also be nice whereby it teleports to the center of the block that the sender is standing on.

**Comment by mcmonkey4eva** [comment]
Fullwall added this via https://github.com/CitizensDev/Citizens2/commit/d579fcbb53130c34a7c554e45af4d3b2a10ded91
by expanding tphere to `/npc tphere (cursor) (-c(enter))`

**Comment by LogGits** [comment]
Nice work, lookin good 👍
