### ISSUE TITLE
[Feature Req] /npc select -r 10 and /npc select x:{x} y:{y} z:{z}

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2262]
I was trying to edit a tonne of npc's in an area using /npc select and then using the npc subcommands when I thought there could be an easier method of bulkediting npc's. 

- `/npc select -r 10` - selects all npc's in a 10 block radius (sphere)
- `/npc select -r 10 -face-direction` - selects all npc's in a 10 block radius (semi-sphere) in the direction player is facing
- `/npc select x:5 y:10 z:5` - selects all npc's 5 blocks x & z and 10 blocks y up and down

Im not sure how in depth you'd could go but it would be nice to bulk edit.

**Comment by mcmonkey4eva** [comment]
Multi-selection is tracked @ https://github.com/CitizensDev/Citizens2/issues/1281

This is also a thing that can be achieved through Denizen.
