### ISSUE TITLE
[Feature Req] /npc face [direction]

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2263]
A command that allows us to essentially set the direction that the npc is facing. 

`/npc face [NORTH, SOUTH, EAST, WEST, UP, DOWN, ME]`
whereby if a face isn't specified it gets the npc to face the sender's eye height.

Side question with this, is it possible to make the npc's body face the same direction as the head with this?

**EDIT** could also include a `ME` argument whereby it makes the npc face the command senders eye height

**Comment by fullwall** [comment]
With your side question: there's an issue where Minecraft doesn't track body yaw exactly for players.

**Comment by mcmonkey4eva** [comment]
Body yaw issue is tracked @ https://github.com/CitizensDev/Citizens2/issues/1487

**Comment by LogGits** [comment]
Edited to include a `ME` argument

**Comment by mcmonkey4eva** [comment]
You can do:
`/npc moveto --yaw 0` (for south)
`/npc moveto --yaw 180` (for north)
etc.
`/npc moveto --pitch 90` (for up, -90 for down).
