### ISSUE TITLE
Floating Npcs

### ISSUE THREAD

**Issue by luizhtss** [CitizensDev/Citizens2#2264]
The output of command `/version` on my server is: **[01:53:33 INFO]: This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[01:53:33 INFO]: Checking version, please wait...
[01:53:34 INFO]: You are running the latest version**
The output of command `/version citizens` on my server is: **[01:53:50 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2084)
[01:53:50 INFO]: Website: http://www.citizensnpcs.co
[01:53:50 INFO]: Author: fullwall**

Server log: https://one.denizenscript.com/paste/73878.txt

NPC Floating: https://prnt.sc/tu8iif

**Comment by mcmonkey4eva** [comment]
I was able to pretty easily replicate this bug myself. NPCs seemingly just don't have gravity anymore. Create one in the air, it will stay floating there. Create one on the ground then push it over a cliff, it'll just float in the air above the cliff instead of falling.

**Comment by Plazmaz** [comment]
So something I noticed is when I programmatically set gravity to false (enabling gravity), npcs don't fall for almost exactly ten seconds in my use case. Not sure if that's just me or if it's relevant.
