### ISSUE TITLE
/npc lookclose doesn't see players who stand still

### ISSUE THREAD

**Issue by ThisIsOllie** [CitizensDev/Citizens2#2267]
When I have the lookclose option of an NPC enabled, it only starts to turn its head when a nearby player is moving. Otherwise, it won't rotate at all. See [this](https://youtu.be/7gLDFWnFTQM) video for more clarification.

The output of command `/version` on my server is: **This server is running Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2056)**

**Comment by mcmonkey4eva** [comment]
Confirmed and replicated locally. It's weird, I don't see any reason in source code this should happen. Theoretically an NPC should snapturn towards any player in range, but it's doing a slow rotate, almost as though perhaps somewhere internally a slowed rotation system was added, and only processes rotation when a new target is given (which does not appear to be within Citizens code).

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/CitizensDev/Citizens2/commit/8c1b51da98043ea745314b9953150268954b61fc for build 2119+ from https://ci.citizensnpcs.co/job/Citizens2/
