### ISSUE TITLE
/npc align

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2268]
Was thinking about the new /npc tphere args, it doesn't provide a way to align the npc to parts of the block that it's currently on. My idea would allow for a command that works such that:
`/npc align [LEFT, RIGHT, CENTER, BACK, FRONT]`
Whereby the location would be relative to the direction that the command sender is facing.

e.g. if I'm behind the npc facing it and type `/npc align left` the npc will be moved to the left of the block. If I'm in  front of the npc facing the npc and type `/npc align left` the npc will move to it's right (my left)

The level of detail that you'd like to go with this is 100% upto you. You could even make the part of the block that is associated with the arguments configurable by the end-user.

**Comment by fullwall** [comment]
I don't think this is helpful. I have been thinking about a different command that lets you preview the NPC position where you look and then place it there but this is just confusing IMO.
