### ISSUE TITLE
HOW Do You SUCCESSFULLY Run And Download It

### ISSUE THREAD

**Issue by Help-Me-Get-Citizen-NOW** [CitizensDev/Citizens2#227]
It says download complete but it never let me RUN it. AND it don't WORK IN MINECRAFT UGH HELP HELP HELP I AM GOING TO UGH

**Comment by mcmonkey4eva** [comment]
Install it in a Spigot server.

**Comment by AnthonyAMC** [comment]
You have to install the version that's correct for your version of spigot/craftbukkit http://wiki.citizensnpcs.co/Versions
