### ISSUE TITLE
[Suggestion] Support for faster NPC movement with pathfinding

### ISSUE THREAD

**Issue by Ice922** [CitizensDev/Citizens2#2272]
The way it seems right now is that if you set an NPC's speed to anything higher than the normal speed (1) the NPC will not move naturally. If I set the NPC speed to a 2, you would expect it to be able to catch up to me if I am running at normal speed but it just has really buggy movements in a sort of circle and can never catch up to me. I think there should at least be support for up to double speed for pathfinding.

**Comment by mcmonkey4eva** [comment]
... This seems to be a bug report, phrased into a suggestion.
The speed option exists. It's already there. If it's not working well, that's a bug report. Please fill out the issue template and describe in what way things aren't working.

**Comment by Ice922** [comment]
Ok. Here's /version:
[23:47:10] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[23:47:10] [Server thread/INFO]: Checking version, please wait...
[23:47:10] [Thread-278/INFO]: You are 238 version(s) behind
/version citizens:
[23:47:35] [Server thread/INFO]: Citizens version 2.0.27-SNAPSHOT (build 2084)
[23:47:35] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[23:47:35] [Server thread/INFO]: Author: fullwall

Example of the issue:
https://imgur.com/MEJU7Hg

**Comment by mcmonkey4eva** [comment]
That is WAY higher than 2x speed. That's like 5x or 10x. You've set it so high that it can't walk to the next block because if tries it will fly way past.

Also, update your Spigot build, or download Paper.

If you can replicate issues with a speed that isn't that so incredibly much beyond sanity, post your Citizens `config.yml` and `saves.yml` via pastebin.

**Comment by Ice922** [comment]
Am I missunderstanding how NPC speeds work? This is the method I am using to set the speed with the API
npc.getNavigator().getLocalParameters().baseSpeed(2);

**Comment by fullwall** [comment]
Yes, you shouldn't set baseSpeed like that.

**Comment by Ice922** [comment]
I'm not sure if this is what you mean: "npc.getNavigator().getLocalParameters().speedModifier(2);" but I am still having the same issue https://imgur.com/a/C6yBJph. It does still seem like it is more than 200% speed but I also had the problem when I just set it to 1.2 instead of 2 speed.
