### ISSUE TITLE
/npc tphere cursor and -c inconsistencies

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2273]
Was just testing the new cursor and -c arguments and I noticed some interesting inconsistencies. 

- there is no tabcomplete suggestions for "cursor"
- `-c` doesn't always teleport the player to the center of the block (e.g. if you stand on the border of two blocks it will put the npc in weird location)
- `cursor` argument doesn't seem to teleport the player onto the block your looking at. Seen in [this gif](https://gyazo.com/fd5969ab583f7086a071862ba21276c7).

The output of command `/version` on my server is: **(PLEASE FILL IN)** Paper 385 1.15.2
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** 2089

**Comment by fullwall** [comment]
The tabcomplete thing is a separate issue
