### ISSUE TITLE
help with CitizenAPI

### ISSUE THREAD

**Issue by YusufCool** [CitizensDev/Citizens2#2276]
how to disable health nametag from NPCs ?
i want it to shows for players only

```
`@EventHandler
    public void onPlayerJoin(PlayerJoinEvent e) {
        Player player = e.getPlayer();
        boolean isCitizensNPC = player.hasMetadata("NPC");
        ScoreboardManager manager = Bukkit.getScoreboardManager();
        Scoreboard board = manager.getNewScoreboard();
        Objective objective = board.registerNewObjective("showhealth", "health");
        objective.setDisplaySlot(DisplaySlot.BELOW_NAME);
        objective.setDisplayName(ChatColor.RED + ":heart:");

        if (!isCitizensNPC) {
            player.setScoreboard(board);
        }

    }`
```

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Frequently_Asked_Questions#There.27s_a_.220_health.22_line_below_my_NPC.27s_names

below_name scoreboard attaches to ALL player entities. You can't set it for some player-type entities and not others. You'd have to use a different approach to attaching data to players to avoid that, such as movement-synced holograms.
