### ISSUE TITLE
Plugin does not load in 1.16.2

### ISSUE THREAD

**Issue by kalleswe** [CitizensDev/Citizens2#2277]
Latest build (2.0.27-b2094) of Citizens will not load on a regular 1.16.2. You need to add support for 1.16.2 immediately since the world is now lacking NPCs. I can't be the only one bitching about this so get your asses on it and fix it ASAP and right now!

**Comment by mergu** [comment]
Citizens is always updated to the latest version quickly. But this is not even 24 hours after 1.16.2's release. Large plugins deeply hooked into nms don't update on the 0th day normally. Please wait patiently like everyone else. 

If you'd like the update to come out faster, feel free to update it yourself and open a PR.

**Comment by mcmonkey4eva** [comment]
build 2097+ on https://ci.citizensnpcs.co/job/Citizens2/ should work

**Comment by blablubbabc** [comment]
Does not yet work: http://prntscr.com/typ9bq

**Comment by mcmonkey4eva** [comment]
fixed via https://github.com/CitizensDev/Citizens2/commit/9e74257c2225cbc25dde792411594e1109eefc4f

Btw that reflect warning is because you're not on Java 8... you need Java 8 for minecraft servers.
