### ISSUE TITLE
Citizens2/Minecraft 1.13.2

### ISSUE THREAD

**Issue by lollox3001** [CitizensDev/Citizens2#2278]
Hi, lately I started a minecraft server with version 1.13.2 to have citizens 2 as plugin and also bossbars since in previous versions there weren`t. Unfortunately the plugin doesn't work correctly, it loads it but the command / npc create doesn't work ... I checked the logs folder and it says this:
Missing preferred location bundle.Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1605) (Is it up to date?). I`m 2.0.24 version of the plugin.With 1.12.2 everything worked but there were no bossbars.I tried to find tutorials on the internet explaining how to install the plugin correctly in minecraft 1.13.2 but unfortunately I didn't find the answer to my question. I am new in this site and I don't know if this is the right section, I'm sorry for my bad English.

**Comment by mcmonkey4eva** [comment]
That's a very old build. Current Citizens builds are @ https://ci.citizensnpcs.co/job/Citizens2/
