### ISSUE TITLE
Citizens-2.0.27-b2100 does not work in 1.16.1

### ISSUE THREAD

**Issue by kalleswe** [CitizensDev/Citizens2#2279]
The other day that build did not work on 1.16.2. Now you seem to have fixed that but the latest build Citizens-2.0.27-b2100 now does not work on 1.16.1.

**Comment by mcmonkey4eva** [comment]
1.16.1 is unsupported, just like 1.16 is unsupported, just like 1.15.1 is unsupported, just like 1.15 is unsupported, ...

Only latest sub-version is supported
