### ISSUE TITLE
ERROR: Unable to find Rhino classes - Spigot 1.8

### ISSUE THREAD

**Issue by Zippyduda** [CitizensDev/Citizens2#228]
Hi there.

Even on CraftBukkit and now on the latest Spigot 1.8 version I have always got the following error on server start-up:

ERROR]: [Citizens] Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes

Please can you advise?

Thanks and regards, Zippyduda

**Comment by mcmonkey4eva** [comment]
Ignorable error, it's meaningless.

**Comment by Zippyduda** [comment]
Thanks mcmonkey.

Just out of interest, what causes it?

**Comment by mcmonkey4eva** [comment]
The JavaScript engine Citizens has support for is not enabled/installed, and for some reason not being enabled qualifies as an error, despite almost nobody using it.

**Comment by Zippyduda** [comment]
I see. Thanks again! I'll look at a way to have it ignored in my server log.

**Comment by Zippyduda** [comment]
Huh, apparently Rhino classes were removed in Java 8. I use Java 7 anyway.

**Comment by mcmonkey4eva** [comment]
That makes no sense. We're referring to this -> https://en.wikipedia.org/wiki/Rhino_%28JavaScript_engine%29

**Comment by Zippyduda** [comment]
Ah I see.
