### ISSUE TITLE
Citizens-2.0.27-b2100 crash 1.16.2 server when player walks into nether portal

### ISSUE THREAD

**Issue by Wybranowsky** [CitizensDev/Citizens2#2280]
### Linkof stack trace
https://pastebin.com/agWGbgji

### Paper build number:
This server is running Paper version git-Paper-"1ba2f2145" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
What makes you think this is a Citizens error and not a Paper or Spigot error?

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
