### ISSUE TITLE
Citizens-2.0.27-b2100 crash 1.16.2 server when player walks into nether portal

### ISSUE THREAD

**Issue by Wybranowsky** [CitizensDev/Citizens2#2281]
### Link of crash
https://pastebin.com/24Tq3UUU

### Plugin list:
Plugins (1): Citizens

### Paper build number:
This server is running Paper version git-Paper-"1ba2f2145" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

I run test server with only Citizens plugin and online-mode=true.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
