### ISSUE TITLE
Paper1.16.1 cannot run 	Citizens-2.0.27-b2100

### ISSUE THREAD

**Issue by kaka2022** [CitizensDev/Citizens2#2282]
>.... [07:09:23 INFO]: [Citizens] Enabling Citizens v2.0.27-SNAPSHOT (build 2100)
>.... [07:09:23 ERROR]: [Citizens] v2.0.27-SNAPSHOT (build 2100) is not compatible with Minecraft v1_16_R1 - try upgrading or downgrading Citizens. Disabling.
>.... [07:09:23 INFO]: [Citizens] Disabling Citizens v2.0.27-SNAPSHOT (build 2100)

**Comment by mergu** [comment]
`try upgrading or downgrading Citizens`

Citizens only supports the latest sub-version (IE 1.16.2, not 1.16.1 or 1.16)

Check the dates here and use one from before 1.16.2: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by fjeddy** [comment]
"Check the dates"
"Not backwards compatible"

Just delete the plugin and start working at McDonalds where you belong.
