### ISSUE TITLE
An enternal error ocured while trying to preform this command (please help)

### ISSUE THREAD

**Issue by SkyLordxd** [CitizensDev/Citizens2#2283]
Hi so when i try to preform any command from this plugin it gives me the error: **An enternal error ocured while trying to preform this command..**
I tried deleting and reinstalling the plugin but nothing worked please help with my issue!
I realy need this plugin!
SkyLordxd.

**Comment by mcmonkey4eva** [comment]
Join the Discord for basic support: https://discord.gg/Q6pZGSR

But it's likely just a basic version issue, make sure you have the latest Citizens build on a fully up-to-date server
