### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by unlinked932** [CitizensDev/Citizens2#2284]
![Screenshot_20200815_102551](https://user-images.githubusercontent.com/65717911/90304476-957a0b00-dee2-11ea-8e01-add336f65426.JPG)

The output of command `/version` on my server is: **(CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **(2.0.27-SNAPSHOT (build 2100))**

**Comment by mcmonkey4eva** [comment]
No part of this post contains any form of error message...
