### ISSUE TITLE
Entering a nether portal on 1.16.2 Alpha 1 causes a server crash

### ISSUE THREAD

**Issue by 3xpl0itz** [CitizensDev/Citizens2#2286]
--
Description of my problem: when a user enters a nether portal from the overworld, there is a likely chance that the server will crash with the following log:
https://pastebin.com/1d4L2Bj1

The output of command `/version` on my server is: This server is running Paper version git-Paper-"1ba2f2145" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens-2.0.27-b2100
--

**Comment by Rodrogamby** [comment]
I have the exact same problem, the server crashes when someone tries to enter the nether using a portal, whether the portal is in the overworld or in the nether itself. My server version is `CraftBukkit version git-Spigot-379750e-f26d8e8 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)` I'm getting this error with every Citizens build compatible with 1.16.2.

I've tried removing Multiverse-Core, but the problem persisted.

The log fragment where the errors are located: https://pastebin.com/mkVZXLV0
The server initialization fragment: https://pastebin.com/kFFkiW7w

**Comment by mcmonkey4eva** [comment]
Can you please replicate this error on a server running *only* Citizens?

**Comment by Rodrogamby** [comment]
It's fixed for me, I just had to update Spigot to `git-Spigot-379750e-e850144 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)` (latest build). I'm using the same Citizens version and didn't remove any plugins :) @mcmonkey4eva @3xpl0itz
