### ISSUE TITLE
use nether portal and server crash when i put citizens plugins in my server

### ISSUE THREAD

**Issue by 5CHRYU** [CitizensDev/Citizens2#2287]
use nether portal and server crash when i put citizens plugins in my server
i try run server without citizens plugins it normal when i use/go another world like nether/the end
when i put citizens in my server this plugins works i can use/create npc but when i use nether portal or go another world my server crash and shutdown
idk what happen before 1.16.1 it normal now 1.16.2 it broke

server version : git-spigot-379750e-43c7ff9 (MC:1.16.2)(Implementing API version 1.16.2-R0.1-SNAPSHOT)
Citizens version : 2.0.27-SNAPSHOT (Build 2100) **free version**

[crash-2563-08-17_16.54.11-server.txt](https://github.com/CitizensDev/Citizens2/files/5083601/crash-2563-08-17_16.54.11-server.txt)

![image](https://user-images.githubusercontent.com/69794149/90385079-bf7f2900-e0ac-11ea-8d04-47e7cd1b0f33.png)

**Comment by mcmonkey4eva** [comment]
- There is no free vs paid version of Citizens, Citizens itself is free, always.
- Update Spigot. That Spigot build is outdated, and other users have reported that this problem is fixed on newer builds of Spigot.

**Comment by 5CHRYU** [comment]
i think i download newest version from https://getbukkit.org/download/spigot

maybe i miss something i will try re-download thanks

**Comment by mcmonkey4eva** [comment]
@5CHRYU you've mistakenly downloaded malware from a fake distribution platform. I strongly recommend performing a virus scan of your PC and/or server.
The legitimate way to acquire Spigot builds is via BuildTools, as documented on The spigot wiki @ https://www.spigotmc.org/wiki/buildtools/ and the relevant announcement post https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-8.36598/

**Comment by 5CHRYU** [comment]
oh idk about this site is fake ? okay i lerned thanks !

//now i got 1.16.2.jar form buildTools follow wiki 
![image](https://user-images.githubusercontent.com/69794149/90392705-96b16080-e0b9-11ea-8965-cf3920c32ef9.png)
