### ISSUE TITLE
Server crash when player entering nether portal in 1.16.2

### ISSUE THREAD

**Issue by YouHaveTrouble** [CitizensDev/Citizens2#2288]
Like the title.

https://pastebin.com/HnnNpE8G
this happens whenever any player steps into nether portal
I have default citizens config. Literally didn't touch it

The output of command `/version` on my server is: Tuinity-"0cd505d" (MC: 1.16.2)
The output of command `/version citizens` on my server is: Citizens-2.0.27-b2100

**Comment by mcmonkey4eva** [comment]
That server version is unsupportable. Grab a current Spigot build.
