### ISSUE TITLE
Keepalive timeout Issue V2. Bungee Setup 

### ISSUE THREAD

**Issue by ActuallyVieja** [CitizensDev/Citizens2#2291]
The problem is that players trying to join cant because of "Keepalive timeout". I´ve just removed the Citizens jar file and now everything works smoothly.
Server Log not relevant (Timeout on Entry to the server, solved when removed from it). Citizen config not touched, its default from stock.
-Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) // Citizens2.0.26 b1997 Free version
FOR LAG RELATED ISSUES: 5GB RAM - 25 NPC´s - https://timings.aikar.co/?id=880d0129dada4800a42c46ce2f84f05e#

Last issue was closed. Argued it was because there´s an incompatibility on Online mode (understandable). But what happens if theres a bungee network running? As suggested by Official Bungee server provider, spigot servers in network should be offline mode when in a BC setup. Any solutions there, or its just not made to work properly on Offline?

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
