### ISSUE TITLE
Just alittle Help optimizing The plugin, :/

### ISSUE THREAD

**Issue by Kqmu** [CitizensDev/Citizens2#2297]
I do not own the server, I am just an Admin with access to console, and currently we are facing some Ticks Per Second (TPS) Drops with has significant change to the server, it takes the server from an average of 20TPS to on average 5 TPS sometimes even lower. 
The Current server has 10GBs of Ram allocated to it, and the server relys on NPCs to lead players onto quests, and to just supply minor details to the towns of the server.
Current Number of NPCs = 146 plus (plus because there will be more NPCs created  as more towns gets created)
-->

The output of command `/version` on my server is: **paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2028)**
[timings.txt](https://github.com/CitizensDev/Citizens2/files/5117240/timings.txt)

Saves.YML \/\/\/

[citizensaves.txt](https://github.com/CitizensDev/Citizens2/files/5117276/citizensaves.txt)

**Comment by mcmonkey4eva** [comment]
Use a profiler/sampler like [Spark](https://www.spigotmc.org/resources/spark.57242/) to get performance data that can actually be used to improve things.

Also consider asking for help on Discord @ https://discord.gg/Q6pZGSR

After getting a sampler report from the server while lagging, either post it on Discord or as a reply below
