### ISSUE TITLE
NPC's fail to jump high enough when on soul sand

### ISSUE THREAD

**Issue by iron-59** [CitizensDev/Citizens2#2298]
The output of command `/version` on my server is: 18.8.-R0.1-SNAPSHOT
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2100)

I'm using the API to make "guards" which will attack when the player is a villain. When navigating, they often get stuck on soulsand when trying to attack. They will jump but never be able to get up. I used WorldEdit to replace the soulsand to another block and the guards were instantly able to come attack me.

**Comment by mcmonkey4eva** [comment]
Confirmed and replicated locally. Only happens with new-finder true, works fine with new-finder false.

The NPC seems to jump in advance, like it thinks the soul sand is a block higher (whereas it's actually 0.1 *lower*).

![gif](https://i.alexgoodwin.media/i/misc/fe8bd6.gif)

**Comment by iron-59** [comment]
Is there any specific way I could fix this in my own code?

**Comment by fullwall** [comment]
Try latest build
