### ISSUE TITLE
NPC´S DON'T KEEP THE COMMANDS FOR TOO LONG

### ISSUE THREAD

**Issue by chipamogli00** [CitizensDev/Citizens2#2299]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-2040c4c-893ad93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2075)

I left all the npc ready and after 1 or 2 hours the commands that I have with the CitizensCMD plugin were deleted, I have tried everything I can think of and I can not solve it. Is there any option I have so that it doesn't happen?

I attach my version of the plugin, my server is also 1.15.2

**Comment by mcmonkey4eva** [comment]
Don't use CitizensCMD. The proper way to add commands to an NPC is documented here: https://wiki.citizensnpcs.co/NPC_Commands
