### ISSUE TITLE
NameTag Issue

### ISSUE THREAD

**Issue by Davidp81** [CitizensDev/Citizens2#230]
If I name a NPC anything, I need to hover over it to be able to see the nametag, unlike back in 1.7. I have tried doing /npc name (to toggle off / on the tag) and it still doesn't work. If it is not possible now (which it should be since Holographic Displays uses it) then please fix the feature to remove the name, so I can create a hologram to put over it instead of the name tag.

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/issues/77
