### ISSUE TITLE
Spigot error when saving item meta

### ISSUE THREAD

**Issue by Castiella** [CitizensDev/Citizens2#2300]
The output of command `/version` on my server is: >....=>.... [18:46:02 INFO]: This server is running Tuinity version git-Tuinity-"598986c" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)**

The output of command `/version citizens` on my server is: **[18:46:28 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2085)**

Direct error: https://pastebin.com/NzpeLapD
latest log attached. 
[log.txt](https://github.com/CitizensDev/Citizens2/files/5138198/log.txt)

This error keeps randomly appearing within console. Not sure what to do but thought it would be wise to report it.

**Comment by mcmonkey4eva** [comment]
As the message itself says: it is a spigot error. Report it to spigot (or your spigot fork's team).
