### ISSUE TITLE
NPC Moveto with command blocks

### ISSUE THREAD

**Issue by RealBugless** [CitizensDev/Citizens2#2301]
Im currently running a 1.8 server and I need to be able to move npc's with command blocks, so the problem is the NPC Moveto command, I can't sepect a specific npc to move, meaning I can't use command blocks to move NPCs.

**Comment by mcmonkey4eva** [comment]
- Update your server: https://wiki.citizensnpcs.co/Minecraft_1.8
- Use the `--id ##` argument
