### ISSUE TITLE
Please Help - Download link to 2.0.27 (1.16.1 BUILD #1)

### ISSUE THREAD

**Issue by MonkeysUseCitizens** [CitizensDev/Citizens2#2303]
Hello, I am very new to github and plugins, and I can't find a link to the specific download to the 1.16.1 build, could anyone help me

2.0.27 (1.16.1 BUILD #1)

**Comment by mcmonkey4eva** [comment]
1.16.1 compatible build here: https://ci.citizensnpcs.co/job/Citizens2/2094/
As is explained on the Discord news channel @ https://discord.gg/Q6pZGSR
But ideally you should update your server to 1.16.2 and download the latest build.
