### ISSUE TITLE
1.16.2 nether portal crash

### ISSUE THREAD

**Issue by veltrium** [CitizensDev/Citizens2#2305]
Hi,
I'm new on all of this and it's really hard to understand about plugins, people isn't polite at all. I need to know why my server is crashing when I get into a nether portal. I paid for the plugin because I didn't know it was for free in other pages, so, im so frustrated bc i think it's a waste of money :( 
Everything was working fine, my server was Spigot 1.16.1, but 3 of my most needed plugins we not working, so I upgrade to 1.16.2, and it's okay, it works pretty fine, except for citizens. 

I saw some comments about "fake spigots" and something about BuildTools, idk anything about that, I just put Spigot 1.16.2 right on my multicraft panel. (theminecrafthosting)

![image](https://user-images.githubusercontent.com/70343689/91653555-ec015080-ea6f-11ea-8733-ddfb02aa0385.png)
This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
The plugin version was the 2.0.27 (1.16.2 ALPHA #2) (Downloaded from Spigot website) 

Can someone please help me?
Everybody tells me "go and look on google" dude, i did, and i don't get it xd. It is hard bc I don't speak English. 

Thanks.

AP.

**Comment by fullwall** [comment]
Can you post your logs please?

**Comment by veltrium** [comment]
@fullwall  hi

https://pastebin.com/5y93xJ9e

**Comment by mcmonkey4eva** [comment]
- remove SkinsRestorer from your server.
- Stop using that spigot jar. Get an up to date one using BuildTools: https://www.spigotmc.org/wiki/buildtools/ or download a Paper jar: https://papermc.io/downloads

**Comment by fullwall** [comment]
Download the latest build

**Comment by veltrium** [comment]
Thanks!
I'm using now the latest version of Paper.
Everything ok.
