### ISSUE TITLE
Disappear equip item

### ISSUE THREAD

**Issue by arts7493** [CitizensDev/Citizens2#2307]
As soon as the npc is created, the armor disappears when equipped.

The output of command `/version` on my server is: **This server is running Paper version git-Paper-387 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-384 (MC: 1.15.2)
You are running the latest version**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2103)
 Website: http://www.citizensnpcs.co
 Author: fullwall**

**Comment by mcmonkey4eva** [comment]
Need more information. How are you equipping armor? What do you mean "as soon as the npc is created"? What... anything?

I tested locally `/npc create bob`, `/npc equip`, add a chestplate, `/npc despawn`, `/npc spawn`, armor didn't disappear.

If you're still having an issue you haven't been able to resolve, please post replication steps akin to the way I described testing.
