### ISSUE TITLE
Citizens error (red) | doesn't work

### ISSUE THREAD

**Issue by Blueberry122** [CitizensDev/Citizens2#2308]
I am having trouble loading the citizens plugin because when I load it in the plugins folder. The plugin shows red and it is giving me an error also my server is supported by 1.8-1.16.2 plugins so I don't know why it is not working

**Comment by mcmonkey4eva** [comment]
Please either fill out all the information in the issue template, or just ask on Discord @ https://discord.gg/Q6pZGSR
