### ISSUE TITLE
Citizens2 [Feature Request]

### ISSUE THREAD

**Issue by knitro1** [CitizensDev/Citizens2#2309]
The output of command `/version` on my server is: **(1.16.1)**
The output of command `/version citizens` on my server is: **(1.13)**

Hello Citizens Devs!

First off amazing Plugin
Secondly So on my server They only use plugins from Spigot.mc and Bukkit So what this means for everyone using the same host i do we do not have access to Citizens For 3 reasons 1. Our Host Doesn't add paid Plugins 2. Our host Doesnt allow use to Drag and drop our own files that we downloaded into the Plugins File 3. Our Host provides the same files as Spigot
ThereFore we dont have access to The newest version of Citizens Because its free version is on a external website and on spigot it costs money  So with all of that Out of the way It would be Awesome if The free version of Citizens Had its own spigot page so us users Of our undisclosed host  Can have access To Citizens2

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Frequently_Asked_Questions#I_have_a_free_server_.28Aternos.2C_Minehut.2C_....29_but_there.27s_problems
