### ISSUE TITLE
ERROR Spigot error when saving item meta

### ISSUE THREAD

**Issue by Klawdek** [CitizensDev/Citizens2#2310]
The output of command `/version` on my server is: git-Paper-384 (MC: 1.15.2)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2105)

**Comment by Klawdek** [comment]
Most of the above comment is deleted by the server.  It only seems to allow two lines so I will break it up into multiple two line posts.

**Comment by Klawdek** [comment]
Server console log: https://pastebin.pl/view/8bdbfb2c
Citizens config: https://pastebin.com/FBksiHcm

**Comment by Klawdek** [comment]
The error occurs spontaneously.  No one needs be on the server or do anything.

**Comment by mcmonkey4eva** [comment]
Spigot error = Spigot error. Citizens is not Spigot. Report the error to Spigot.
