### ISSUE TITLE
Citizens bypasses bungeecord restricted mode.

### ISSUE THREAD

**Issue by SpicyChickenMcNuggets** [CitizensDev/Citizens2#2311]
Im not going to fill in all of that stuff to report a simple bug. 
Server version: Latest version of paper spigot 1.16.2
Plugin version: Citizens 2.0.27-Snapshot Build 2100

The problem: So basically when you set up an npc to use for bungeecord server teleportation. It completely bypasses bungeecord restricted mode for individual servers. It does not check to see if they have permission from the bungeecord config before sending them to the server.

**Comment by mcmonkey4eva** [comment]
That sounds more like a feature than a bug.

This also is not changeable, as it just calls the bungee Connect plugin channel as described at <https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/> which does not provide any options for altering handling based on bungee config.
You might instead tack on a permission requirement to the NPC's command via the `--permissions` flag when adding a command.
