### ISSUE TITLE
Citizens deleting after shut down

### ISSUE THREAD

**Issue by untfce** [CitizensDev/Citizens2#2313]
threadripper 2950x 10gb ram 2 npcs default timings

The output of command `/version` on my server is: 2.0.27-snapshot build 2085
The output of command `/version citizens` on my server is: spigot 1.16.1 r0.1 snapshot

Citizens delete after shutting down server, dont have this issue with another server of the exact same versions as this one.

**Comment by mcmonkey4eva** [comment]
Likely an error message in your server logs. If in doubt, [Pastebin](https://pastebin.com/) your `logs/latest.log` file after shutting down your server (the log of the startup and shutdown sequences are likely to be relevant).
