### ISSUE TITLE
Use Placeholders in NPC Skins

### ISSUE THREAD

**Issue by Jxliet** [CitizensDev/Citizens2#2314]
I asked for support for something that I wanted to do, and it wasn't in. So I came to suggest it here.

I wanted to make a top 3 donators board, and make it so the NPC names were **&4&kiii &c%top_donator_1% &4&kiii** but it was not possible yet, making it possible would be fantastic and would make the servers of players run a bit more smoothly.

**Comment by mcmonkey4eva** [comment]
The actual request on Discord was to make the *skin* update from a placeholder, not the name. Names already work.

**Comment by mcmonkey4eva** [comment]
This was added via https://github.com/CitizensDev/Citizens2/commit/21163e4ec478c759628bdff506df1a471c190b92 for build 2209+ from https://ci.citizensnpcs.co/job/Citizens2/
