### ISSUE TITLE
Option to change nameplate to hologram

### ISSUE THREAD

**Issue by Alejandro-Sosa** [CitizensDev/Citizens2#2315]
A suggestion for citizens.

Currently the nameplate and hologram use different values from entity-tracking-range. 

The option to hide the nameplate and replace it with a hologram would be useful so the entire thing only uses one value.

You could set the tracking range for the entity to the same value as for misc (armorstands) but then the entire npc dissapears aswell.

**Comment by fullwall** [comment]
Already a setting

**Comment by Alejandro-Sosa** [comment]
A how to comment would be helpful ^^

Wiki is blank about it.

**Comment by mcmonkey4eva** [comment]
Settings file is: `plugins/Citizens/config.yml`
Open it in any text editor
There is a line in there that says by default:
`  always-use-name-holograms: false`
Switch the `false` to `true`
