### ISSUE TITLE
NPC's resetting tablist formatting

### ISSUE THREAD

**Issue by patoscript** [CitizensDev/Citizens2#2316]
Hi,

There's this really weird bug that's been annoying me and the players. It's a little hard to explain as it only happens if certain circumstances are met, but I think it's when an NPC despawns (e.g. when its chunk unloads I think, but it doesn't happen if I switch worlds), it resets the tablist's formatting. This includes all of the player's prefixes, suffixes, and even fake nametags.

Server log (no errors show up on the console btw): https://pastebin.com/aVWMqi86
Citizens config (don't think I've ever changed it): https://pastebin.com/Cpiwa5ij

Spigot version:
![image](https://user-images.githubusercontent.com/20492365/92572862-ddd7df00-f27c-11ea-9b40-4a2c432c19b6.png)
Citizens version:
![image](https://user-images.githubusercontent.com/20492365/92572898-ec25fb00-f27c-11ea-863c-0d00e66769ad.png)

And here's an example:
When I'm near the NPC
![image](https://user-images.githubusercontent.com/20492365/92593769-8dbb4580-f299-11ea-9322-7c8eeee5a186.png)
When the chunk unloads
![image](https://user-images.githubusercontent.com/20492365/92593790-99a70780-f299-11ea-92dd-fecedb9c12be.png)
Note how it resets to the minecraft default.

Thanks.

**Comment by mcmonkey4eva** [comment]
We don't support piracy.
