### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chickiyeah** [CitizensDev/Citizens2#2317]
The output of command `/version` on my server is: git-Spigot-3a70bd9-bf3d720 (MC: 1.16.3)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOP (build 2110)

**Comment by chickiyeah** [comment]
https://pastebin.com/AtsveXnM

**Comment by mcmonkey4eva** [comment]
1.16.3 builds will be coming soon later today
