### ISSUE TITLE
Rightclick doesnt remove wandering points

### ISSUE THREAD

**Issue by blakedj012** [CitizensDev/Citizens2#2319]
If you use the provider "Wander" on a NPC you can set wanderpoints with "npc path > regions".

Unfortunately it does not work to remove them with a right click as described in the editor.

There are neither errors in the console nor logs. 

Latest Paper Version 1.16.3 (git-Paper-187 (MC: 1.16.2))

and 

Citizens-2.0.27-b2112

I hope its enough.

**Comment by fullwall** [comment]
Changed to use shulker bullets instead.

**Comment by blakedj012** [comment]
But rightclick to remove them dont work !!!

**Comment by blakedj012** [comment]
And they are disappear to fast i think is not good solution @fullwall

**Comment by blakedj012** [comment]
when will this work?

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/CitizensDev/Citizens2/commit/ba00c91a30432fa28271c3f56f8b66a84687c0c9 for build starting 2164+ from https://ci.citizensnpcs.co/job/Citizens2/
