### ISSUE TITLE
My citizens are deleting???

### ISSUE THREAD

**Issue by Medievalminecrafters** [CitizensDev/Citizens2#2321]
Citizens Version: Citizens-2.0.27-b2027
Minecraft Version: Spigot 1.16.1-R0.1

I am getting Zero errors in my console, and I cant find any Logs of them saying anything is wrong, but citizens keep deleting after i restart the server, and its weird because it is at random? I thought maybe there was a CAP on how many i could have but i couldnt find anything? Please help?

**Comment by Medievalminecrafters** [comment]
https://gyazo.com/f75daf1a240242c0770cb20f33b7c865

**Comment by mcmonkey4eva** [comment]
If you're stuck on MC 1.16.1, you need this older build of Citizens: https://ci.citizensnpcs.co/job/Citizens2/2094/

Latest builds are for 1.16.3, which you should be updating to ASAP.
