### ISSUE TITLE
npc create causes: java.lang.NoSuchFieldError: ORIGIN

### ISSUE THREAD

**Issue by TeklasJr7** [CitizensDev/Citizens2#2322]
When trying to do the command ingame (/npc create name)
this error comes up saying to look at console:

- java.lang.NoSuchFieldError: ORIGIN

This is the output:

12.09 02:40:34 [Server] Server thread/INFO TeklasJr7 issued server command: /npc create [TeklasJr7]
12.09 02:40:34 [Server] Server thread/WARN java.lang.NoSuchFieldError: ORIGIN
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_16_R2.util.PlayerNavigation.<init>(PlayerNavigation.java:43)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:318)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:97)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.nms.v1_16_R2.entity.HumanController.createEntity(HumanController.java:52)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:249)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:509)
12.09 02:40:34 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12.09 02:40:34 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12.09 02:40:34 [Server] Server thread/WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12.09 02:40:34 [Server] Server thread/WARN at java.lang.reflect.Method.invoke(Method.java:498)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
12.09 02:40:34 [Server] Server thread/WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
12.09 02:40:34 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
12.09 02:40:34 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
12.09 02:40:34 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
12.09 02:40:34 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)

- Citizens config: https://pastebin.com/KybbXvzJ

The output of command `/version` on my server is: 
This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are 54 version(s) behind

The output of command `/version citizens` on my server is:
Citizens version 2.0.27-SNAPSHOT (build 2113)
Website: http://www.citizensnpcs.co
Author: fullwall

Thanks for taking your time on helping!

**Comment by fullwall** [comment]
Update
