### ISSUE TITLE
Cannot create a NPC

### ISSUE THREAD

**Issue by Seniorendi** [CitizensDev/Citizens2#2324]
- If i create a NPC with /npc create SlixZero, nothing happens and a Exception Appears.
- Log: https://hasteb.in/oyukucik.md 
- Spigot/PaperMC Version: This server is running Paper version git-Paper-150 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
- Citizens Version: 2.0.27-Snapshot (Build 2113)

**Comment by mcmonkey4eva** [comment]
Either update your server to 1.16.3, or downdate your Citizens build to the 1.16.2 compatible one -> https://ci.citizensnpcs.co/job/Citizens2/2110/

**Comment by Seniorendi** [comment]
Thanks
