### ISSUE TITLE
Error Message "Plugin Disabled"

### ISSUE THREAD

**Issue by Netpex** [CitizensDev/Citizens2#2325]
Hello, I Recently Purchased The Plugin "Citizens2," 

![image](https://user-images.githubusercontent.com/71103756/93005050-09b7c680-f502-11ea-80af-3e9d048c0195.png)

And It's Giving me a Plugin Disabled Plugin,

![image](https://user-images.githubusercontent.com/71103756/93005086-69ae6d00-f502-11ea-9ff5-cfc9cb0057e8.png)
https://pastebin.pl/view/25edb984
(Config Unedited)

 I've seen this error on Here Before But That Help Didn't Quite Make Sense and Was Marked "Closed."

![image](https://user-images.githubusercontent.com/71103756/93005157-420bd480-f503-11ea-8afc-e1f0f73ea014.png)
![image](https://user-images.githubusercontent.com/71103756/93005159-4506c500-f503-11ea-92d8-8f4212c58bcb.png)

The output of command `/version` on my server is: 
![image](https://user-images.githubusercontent.com/71103756/93005191-99aa4000-f503-11ea-9143-84967240c1cd.png)

The output of command `/version citizens` on my server is: 
![image](https://user-images.githubusercontent.com/71103756/93005193-9fa02100-f503-11ea-8c50-35e1689e389b.png)

**Comment by mcmonkey4eva** [comment]
The last build that supported 1.16.1 was here: https://ci.citizensnpcs.co/job/Citizens2/2094/

But please update to 1.16.3 as soon as you can
