### ISSUE TITLE
NPCs set to follow a player 'break' when changing worlds

### ISSUE THREAD

**Issue by klinical** [CitizensDev/Citizens2#2327]
The output of command `/version` on my server is: git-Paper-192 (MC: 1.16.3)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2113)
Log: https://hastebin.com/bamowoxiro.md

When changing worlds, the NPC's pathfinding seems to break, and the NPC stands still. After moving out of their follow distance/pathfinding range, they simply teleport. Returning to the previous world either fixes their pathfinding, or makes the NPC disappear. 

https://imgur.com/a/BPRIEot

**Comment by Galajus** [comment]
I have a same problem on 1.15.2

**Comment by fullwall** [comment]
Still happening on the latest builds?
