### ISSUE TITLE
Can't create a npc

### ISSUE THREAD

**Issue by Mitchell3514** [CitizensDev/Citizens2#233]
Hello,

I downloaded citizens for minecraft 1.7.10 and i tried to make a npc whith /npc create <name> but i got a message that i had to report this fault. Please report this error: [See console] java.langNoClassDefFoundError: ft. Can someone tell me what i have to do? Console after doing the command (i deleted the console logg and did the command):
http://pastebin.com/nm9NZDdM

**Comment by mcmonkey4eva** [comment]
IS PASTEBIN SO FUCKING HARD TO USE

*edits post myself*

Now then.

Get the correct version of Citizens for your Bukkit version here: http://wiki.citizensnpcs.co/Versions

**Comment by Mitchell3514** [comment]
Hey,

Thanks for ur response. And sorry for the console log. I forgot how to do that.

**Comment by EclipseCoding7** [comment]
Please Tell Me How You Fixed this problem i am on 1.8 and i dont know what is the right version i am using please help me
