### ISSUE TITLE
Safe-guard against unexpected issues in version-specific code

### ISSUE THREAD

**Issue by blablubbabc** [CitizensDev/Citizens2#2330]
Hey,
would it be possible to wrap all version-specific code into try-catch blocks and react to any catched issue by shutting down the plugin or skip the NPC spawning?

I have the following situation: The Shopkeepers plugin stores additional data for Citizens NPCs. Since it is possible for Citizens NPCs to get deleted while the Shopkeepers plugin is not running, there is a check to automatically remove any associated data on startup if the Citizens plugin is enabled but the corresponding NPC no longer exists (identified by the NPC's unique id).

During the update from 1.16.2 to 1.16.3 some users attempted to simply update the server without updating all plugins first. Their updating process seems to be to update and then check for errors and then fix those one by one.

The Citizens plugin required an update and failed to spawn NPCs and consequently aborted the NPC loading process. However the plugin still kept listed as 'enabled'. https://prnt.sc/uhuqyo

The consequence was that the Shopkeepers plugin removed all associated data since it assumed that the NPCs no longer existed.

Would it be possible to guard against these kinds of unexpected issues within the version-specific code and then shutdown the plugin in reaction to a detected issue, or skip the operation (such as spawning the NPC) but keep the ramaining portions of the plugin working (such as loading all NPCs)?

**Comment by mcmonkey4eva** [comment]
I very very strongly recommend and encourage that you immediately remove the auto-deletion of user data. Please don't ever do that. Ever. In general, not just here, EVER. Users generally do not like their data disappearing. A lot of users also tend to be lazy with backups, which makes it worse (though, of course: always remind users to make regular backups of all server data).

Probably either store NPC-related data in an NPC trait, so it's saved alongside the NPC, or add an optional cleanup command to perform the autodelete, or just... tell people to not disable shopkeepers, then delete npcs, then re-enable shopkeepers with the original data file.

Most errors are non-fatal, so crashing the entire plugin at any error would be rather overzealous in itself.

**Comment by blablubbabc** [comment]
> Users generally do not like their data disappearing.

They certainly do if they intentionally deleted the NPC. I see no flaw in deleting associated data together with the NPC. The only issue is that apparently there are situations in which I cannot reliably check whether the NPC still exists.

Anyways, I will think about making this behavior configurable, or think about another alternative to deal with this inconsistent data in that specific case (eg. by spawning an entity myself if the NPC is no longer available).

> Probably either store NPC-related data in an NPC trait, so it's saved alongside the NPC

I thought about that, but this would complicate staying in sync with that additional data source. Also, this would make it even more complex to correctly handle situations in which not both plugins are currently enabled. Eg. if all shopkeepers of a player shall be deleted, but the Citizens plugin is not running currently (so the plugin would not know about the player's NPC shopkeepers in that case).

So I deemed this to not be worth the additional implementation effort, and the potentially new issues arising from this change.

> add an optional cleanup command to perform the autodelete

There is no need to add additional burden to admins for things which the plugin can handle automatically. One more thing admins do not have to deal with.

Especially since the shopkeepers plugins also prevents chest access and shopkeeper creation at places at which a shop already exists. So keeping shopkeeper data around for no longer existing NPCs would cause unexpected behavior with players not being able to access their previous shop chest or spawn a new shopkeeper at the previous location, until an admin has been made aware of the situation and has found the time to manually look into it.

> Most errors are non-fatal, so crashing the entire plugin at any error would be rather overzealous in itself.

Not being able to load or spawn NPCs sounds pretty fatal to me. I am not sure what purpose there is for the plugin to stay enabled in that circumstance. But like I said above, an alternative could be to only skip the NPC spawning, if there is an issue specific to that.

I still don't see the justification of not guarding against unexpected issues in this code portion which is known to be prone to break with every update.

**Comment by mcmonkey4eva** [comment]
`in this code portion which is known to be prone to break with every update.`
This^ is not accurate. This is the first time that code portion has ever broken. It is likely the only time it ever will.
`I still don't see the justification of not guarding against [update problems]`
Most updates problems are checked for and accounted for. Not *all* are, not all *can be*. This is an example of one that could not have been checked for, as it could not have been predicted.
The only way to have checked for this error in a way that would then crash the plugin would be to detect any Java exception and instacrash from that.

-----

`There is no need to add additional burden to admins for things which the plugin can handle automatically.`
The admins in your hypothetical world have created the burden themselves, by choosing to use link together multiple plugins and then remove one of the two for a while, edit data related to that linkage, and then re-add the plugin that was removed. Anybody who does that should very much expect that they'll have to clean up their own mess they just made.

There are two routes here:
A: Data gets deleted automatically, leading to a slight convenience after an admin really really f's up, but with a risk of deleting legitimate important data that may not be properly backed up.
B: Data gets deleted only via command, meaning data is safe but adding the tiniest possible inconvenience of being ideal to enter a single command after admins royally screw their setup.

A is both much more likely than B, and much much harsher of a consequence than B.
I cannot strongly enough recommend that you do not EVER auto-delete user data like that.

**Comment by blablubbabc** [comment]
> The admins in your hypothetical world have created the burden themselves, by choosing to use link together multiple plugins and then remove one of the two for a while, edit data related to that linkage, and then re-add the plugin that was removed. Anybody who does that should very much expect that they'll have to clean up their own mess they just made.

There are also situations which are not intentionally caused by an admin "f'ing up". For instance, both the Citizens and the Shopkeepers plugin disable themselves if they detect a severe issue during startup (such as running on an unsupported Minecraft version, or not being able to load their plugin data, etc.). So it might very well be that, without an admin's knowingly interaction, either of these plugin might not have been enabled for whatever reason.

And since not only admins can create and delete shops (and their associated NPCs), it might very well be possible for regular players to unknowingly delete/mess with one half of this linkage in this situation. And, depending on the concrete setup, the same applies to other plugins as well. Eg. there are region market plugins which automatically delete shops / NPCs within a region when the region's rent timer has run out.

I assess the likelyhood and the inconvenience for both admins and myself having to react to support requests to be far greater than the minimal risk of accidentially and unintentionally deleting user data. Especially since, like you said, this has been the first time that this has broken in such a way. So the risk of unintentionally deleting user data should therefore be pretty low compared to unintentinally running with only one plugin enabled and messing with one half of the linkage.

I created this ticket simply to suggest to further lower the risk of running into this unlikely worst-case by additionally guarding against these unexpected kinds of errors.

> This is an example of one that could not have been checked for, as it could not have been predicted. The only way to have checked for this error in a way that would then crash the plugin would be to detect any Java exception and instacrash from that.

The suggestion is to wrap the code spawning the entity into a try-catch-all block and then handle the catched issue in some way (whether that is to disable the plugin again, or to simply skip spawning the entity and logging an error would be up to you). This sounds reasonably to me, independently to how Shopkeepers handles inconsistent data, since the NMS code may change at any time. And this shouldn't be to difficulty to add either.

But if you consider the risk for this to break again in the future to not be worth this minimal effort to guard against it, then that is up to you of course..
