### ISSUE TITLE
Parrots are disappearing when they unmount from the player's shoulder

### ISSUE THREAD

**Issue by CharlieIsHere** [CitizensDev/Citizens2#2332]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
This server is running Tuinity version (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
Citizens version 2.0.27-SNAPSHOT (build 2108)

The issue:
If you set a parrot entity to be mounted onto a players shoulder and they unmount naturally (such as if the player starts flying or goes into water) the parrot will disappear instead of unmounting

**Comment by mcmonkey4eva** [comment]
You cannot mount NPC parrots on a player. Shoulder mounts are not actual entities in minecraft.
