### ISSUE TITLE
Citizens causing frequent server crashes on 1.16.3, multiple errors

### ISSUE THREAD

**Issue by TuckerAndrews3** [CitizensDev/Citizens2#2334]
My server is having multiple errors involving Citizens on 1.16.3, no lag issues or anything like that, but there's a ton of errors on startup/and stopping iirc, along with a bug that causes my server to stall and eventually crash.

This is the error that causes the crash right here, this dump: https://pastebin.com/v12XNHnM

This is the gigantic error on startup/stop that I believe is related to the crash error: https://pastebin.com/Td2CPicN

Citizens config: https://pastebin.com/7896WzrC

Server log: https://pastebin.com/gxbSL2ds

The output of command `/version` on my server is: This server is running Paper version git-Paper-197 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2117)
>.... [17:53:35 INFO]: Website: http://www.citizensnpcs.co
>.... [17:53:35 INFO]: Author: fullwall

**Comment by mcmonkey4eva** [comment]
- Get rid of that `citizensapi` jar.
- You have multiple plugins throwing errors, including Dynmap and Slimefun
- The `>.... [17:56:12 ERROR]: [Citizens] Spigot error when saving item meta` lines are, as stated in that message, Spigot errors, not Citizens ones. You have NPCs wearing Player_Head items, and Spigot's item serializer for those is broken. This error should be reported to Spigot, but can be workaround'd by removing the Player_Head items.
- The actual "error that causes the crash" is not an error nor a crash:
```
>.... [17:31:29 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-197 (MC: 1.16.3) ---
>.... [17:31:29 ERROR]: The server has not responded for 20 seconds! Creating thread dump
```
That is severe server lag. The precise cause of it cannot be readily identified by that piece of log alone... usually a Spark report helps track down lag sources.

**Comment by TuckerAndrews3** [comment]
What is a Spark report? Our timings reports haven't been working, I would have posted one but it wasn't possible.

**Comment by mcmonkey4eva** [comment]
https://www.spigotmc.org/resources/spark.57242/

**Comment by TuckerAndrews3** [comment]
After updating Dynmap and Slimefun their errors have disappeared, all that is left is the citizens/spigot one..
https://pastebin.com/L8CfTEyi

**Comment by mcmonkey4eva** [comment]
Please get a spark report.

**Comment by TuckerAndrews3** [comment]
What kind of report do you want? It seems there are multiple

**Comment by mcmonkey4eva** [comment]
Spark profiler (start it, let some lag happen, end it, get the report link)

**Comment by TuckerAndrews3** [comment]
Got it - going to let it run for a while to make sure I get the intended effect. It only lags during those server dump things, so it may be a while.

**Comment by TuckerAndrews3** [comment]
https://spark.lucko.me/#8cjuMVErIY Here's one I ran for a little bit, just to make sure I'm doing this right - I'm not sure if this will help.

**Comment by mcmonkey4eva** [comment]
Your server is clearly already struggling and lagging in that report, just from basic world processing (mobs and chunks). That recording shows less than half a percent of CPU time is spent idling, which is generally a safe bet that your TPS is under 20 (anything under 20 is problematic lag).

**Comment by TuckerAndrews3** [comment]
It averages out at about 17-20 but doesn't normally frequently crash like this, this is a new thing that's been happening.

**Comment by TuckerAndrews3** [comment]
Do you want a longer that report that's guaranteed to include the error from citizens/spigot?

**Comment by mcmonkey4eva** [comment]
Not a _longer_ one, just... one that includes a source of lag other than literally just chunks and entities. But if your server is usually running at the edge, you shouldn't be surprised when the moment something gets added, it pushes too far and times out

**Comment by TuckerAndrews3** [comment]
https://spark.lucko.me/#ZNFgh6gPTK

This one ran a bit longer and I was told a lagspike happened during it.. does this have anything of use?

**Comment by TuckerAndrews3** [comment]
https://spark.lucko.me/#hx6GvP218M 

This one ran through the error that I'm experiencing, etc

**Comment by TuckerAndrews3** [comment]
Is anyone going to reply to this?

**Comment by mcmonkey4eva** [comment]
Still waiting on a profiler report that _is not a very long recording_ but does include the relevant problem

Thus far you've only posted ones that are either
A: So long they don't even render on the webpage
or B: don't include the relevant issue

**Comment by TuckerAndrews3** [comment]
It's hard to catch the issue when it happens at random, and when it does happen the server crashes. There has to be a better way to do this..

**Comment by TuckerAndrews3** [comment]
oops - didn't mean to close

**Comment by enterih** [comment]
I also have the issue with crashes since using the newest build
I can get the following information:
- It happens when default players are online (not happens with admins/OP)
- Server is loosing TPS before crash
- No error in console unless server is overloading message

I tried to catch it with timings:
https://timings.aikar.co/?id=147a0b63aece4aee8255db9d30009c75#plugins 
Here i told other player to get online and then the issue was started

https://timings.aikar.co/?id=f6dad6419db7421b8531ce6013b47554#plugins
Here the i got the timings after restarting and also few seconds before crash

Maybe that helps you

**Comment by mcmonkey4eva** [comment]
It's been a long time with no reply here. Are you still having this problem in 1.16.4?
