### ISSUE TITLE
Armor stand nameplates don't get removed and are stacked.

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#2335]
When you do **/npc despawn** or **/npc remove** the nameplates don't get removed if it used an armor stand to display the name due to being too long.

It also seems that there is a few armor stands stacked on top of each other and produce a very dark nameplate.
https://i.imgur.com/MbPEJ4W.jpg
**_Edit: Maybe they are stacked due to the first bug of them not getting removed._**

[13:42:17 INFO]: This server is running Paper version git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[13:42:17 INFO]: Checking version, please wait...
[13:42:17 INFO]: Previous version: git-Paper-198 (MC: 1.16.3)
[13:42:17 INFO]: You are running the latest version

[13:42:18 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2113)
[13:42:18 INFO]: Website: http://www.citizensnpcs.co
[13:42:18 INFO]: Author: fullwall

**Comment by mcmonkey4eva** [comment]
Please post your full latest server log as the issue template specified to do.

**Comment by HexedHero** [comment]
Seems to be a weird issue, trying to repeat it with the code I was using to modify the entity is just causing issues. Obviously fresh 1.16.3 Paper B208 with just the below code and EssentialsX 2.18.1.13.

I managed to get the same issue just the other way around lol
https://cdn.hexedhero.com/u/5cS2VEdxwe.mp4

Code for this testing and the issue reason.
`    @Override
    public boolean execute(CommandSender sender, String commandLabel, String[] args) {
        if (!(sender instanceof Player)) { return false; }
        final Player player = (Player) sender;
        final NPC npc = getNPC(player.getLocation());
        if (npc != null && npc.isSpawned() && npc.getEntity().isValid()) {
            npc.setName(ChatColor.translateAlternateColorCodes('&', "&6&lNotchhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"));
            if (npc.getEntity().getType().equals(EntityType.PLAYER)) {
                npc.getTrait(SkinTrait.class).setSkinName("Notch");
            }
        }
        return true;
    }
`

`    public NPC getNPC(Location location) {
        for (final Entity entity : location.getWorld().getNearbyEntities(location, 5, 5, 5)) {
            if (entity.hasMetadata("NPC") && CitizensAPI.getNPCRegistry().isNPC(entity)) {
                final NPC npc = CitizensAPI.getNPCRegistry().getNPC(entity);
                return npc;
            }
        }
        return null;
    }`

When I spawn a new NPC and use the code the skin sometimes doesn't work until a server restart and then it starts to bug out.

Before restart: https://cdn.hexedhero.com/u/qUuh61xlCD.mp4
After restart: https://cdn.hexedhero.com/u/ysb8BJ52fF.mp4
