### ISSUE TITLE
Reload command removes player-made NPCs

### ISSUE THREAD

**Issue by SavagePanda116** [CitizensDev/Citizens2#2338]
Using the command '/citizens reload' removes any non-admin created NPCs. For example, if I create an NPC and a player creates an NPC and then I change something in the config and use '/citizens reload' to apply the change, the player-made NPC is removed.

Latest Log: https://pastebin.com/tKi6ahZ5 
Citizens Config: https://pastebin.com/GZTsePpX

The output of command `/version` on my server is: Paper version git-Paper-194 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2120)

**Comment by mcmonkey4eva** [comment]
Don't use `/citizens reload`... that's the command that deletes any changes you made in-game.
