### ISSUE TITLE
NPC respawn isn't working

### ISSUE THREAD

**Issue by SavagePanda116** [CitizensDev/Citizens2#2339]
After setting the respawn delay and killing an NPC, it does not respawn on it's own until someone uses the '/npc spawn' command.

Latest Log: https://pastebin.com/tKi6ahZ5 
Citizens Config: https://pastebin.com/GZTsePpX

The output of command `/version` on my server is: Paper version git-Paper-194 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2120)

**Comment by mcmonkey4eva** [comment]
Nowhere in that log do you use the Citizens base respawn command, the Denizen health trait respawn command, or the Sentinel respawn time command. Would need demonstration of the relevant problem happening to get anywhere.

(BTW, you should probably be using Sentinel if you're intending to have NPCs actually fighting with players... if you just want a target-dummy the built-in respawn+vulnerable will suffice though).
