### ISSUE TITLE
Villager Despawn

### ISSUE THREAD

**Issue by wd40bomber7** [CitizensDev/Citizens2#234]
Adult villagers spawned through spawn egg despawn like hostile mobs when player leaves the area.

Occurs when using:
Latest development build of citizens2
Latest spigot

Happens when all other plugins but citizens2 are removed.Remove citizens2 and its fixed.

No errors other than the missing rihno classes one.

**Comment by seema84** [comment]
its a old bug (he "was" fixed times) and it applies not only Villagers
i can confirm this problem on latest craftbukkit/spigot Builds 1.8

**Comment by SimbaZockt** [comment]
I have the same bug. But dont can say that the problem is from Citizens. Because if i only youse citizes nothing happens.

**Comment by SimbaZockt** [comment]
Found the bug! Citizens is the problem yes. But only you create a Npc with a mob type! Like Pig,cow

**Comment by wd40bomber7** [comment]
I've entirely tracked down this bug.

The problem happens like this:
When a mob type npc spawns, it registers its custom entity type using registerEntityClass(Class<?> clazz) in java.net.citizensnpcs.util.NMS.java

This function injects the type into the entity type table. One of the maps in the entity table is ID->Class
(NMS.ENTITY_INT_TO_CLASS) The registerEntityClass function overwrite the original entry for the vanilla type the NPC corresponds to, with the NPC controller for that type.
So say you were to spawn a villager npc, instead of the map saying
ID 120->VillagerEntity
It would now say:
ID 120->CitizensNPCController (I've abbreviated both of these class names for simplicity)
That means any time anyone uses a spawn egg, instead of spawning an EntityVillager, it spawns a Citizens.VillagerNPCController. This same issue exists for all mob types! Create a pig npc, and suddenly pigs spawned from spawn eggs are a Citizens.PigNPCController

Besides the obvious unnecessary overhead this creates for the server, this causes a bigger problem. When saving a chunk minecraft looks up a textual representation of entity types, if it can't find the textual representation for an entity, that entity isn't saved. It performs this lookup using the class name of the entity. Now spawned villagers (or whatever mob) will have a class name of Citizens.XXXNPCController instead of Minecraft.EntityXXXX. The citizens controller class name won't be in the lookup table, thus no textual representation of the entity will be found, thus the entity won't save. Ultimately this results in the entity ceasing to exist when the chunk is unloaded.

**Comment by mcmonkey4eva** [comment]
Does this fix the issue -> https://dl.dropboxusercontent.com/u/54130586/citizens-2.0.14-SNAPSHOT.jar ?

**Comment by wd40bomber7** [comment]
It certainly appears to!

I confirmed that placing a villager created a villager instead of a villager controller. I also confirmed that it correctly saved when the chunk unloaded/reloaded. I only gave the rest of citizens2 functionality a cursory sweep so I can't promise its regression free, but that bug is definitely patched!
