### ISSUE TITLE
[Bug] Just a repetitive error that is sent every once in a while.

### ISSUE THREAD

**Issue by AZFire1** [CitizensDev/Citizens2#2340]
**Description:**
This is just a repetitive error that has recently started to be set in console, it doesn't seem to effect anything though I thought I'd just report it just in case. https://pastebin.com/NMUtmSXJ

**Server log:**
https://mcpaste.io/bc047c44c148acf9
**Citizens config:**
https://pastebin.com/rEBsASB5

The output of command `/version` on my server is: **(PLEASE FILL IN)**
29.09 04:09:33 [Server] INFO This server is running Purpur version git-Purpur-770 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
29.09 04:09:58 [Server] INFO Citizens version 2.0.27-SNAPSHOT (build 2113)

**Comment by mcmonkey4eva** [comment]
That is a spigot error. Report it to the spigot bug tracker.
