### ISSUE TITLE
NPC Health issues 1.16.3

### ISSUE THREAD

**Issue by Thezul1** [CitizensDev/Citizens2#2341]
When creating a NPC it spawns with choosen name and a health bar beneth. And since i am also using Citizens Server Selector i use /css create NAME. When i than use /css setDesc DESCRIPTION it goes right over the health text. I tried disabling the health text by enabling the always-use-name-holograms: false to always-use-name-holograms: true. But now when i spawn a npc is just says Armor Stand. and is no longer useable by css only normal /npc command. No errors in log. Check example image for image of error

Log : https://pastebin.com/7prqQiTx
Version : http://prntscr.com/uq5brw
Citizens Version : http://prntscr.com/uq5bdy
Example : http://prntscr.com/uq5ae8

**Comment by mcmonkey4eva** [comment]
Get rid of "Citizens version selector"
Refer to https://wiki.citizensnpcs.co/NPC_Commands for how to do everything that plugin does, minus the random extra plugin

Regarding the health line, refer to this entry of the FAQ: https://wiki.citizensnpcs.co/Frequently_Asked_Questions#There.27s_a_.220_health.22_line_below_my_NPC.27s_names

**Comment by Thezul1** [comment]
Hey, I have removed the plugin "Citizens server selector" but this did not fix the issue
