### ISSUE TITLE
Hologram Returning With Invalid Line Number

### ISSUE THREAD

**Issue by BobbyMere** [CitizensDev/Citizens2#2342]
I can't figure out how to add holograms and multiple lines to npc's. If I do ```/npc hologram set 1 f``` it returns with invalid line number. I've tried multiple numbers and they return with the same.
<img width="191" alt="Screenshot 2020-09-29 205904" src="https://user-images.githubusercontent.com/25316276/94634886-ed07e680-0296-11eb-8311-ae165d3dd7cf.png">
<img width="190" alt="Screenshot 2020-09-29 205913" src="https://user-images.githubusercontent.com/25316276/94634892-eed1aa00-0296-11eb-9c9a-bf9223ebe6e0.png">

The wiki https://wiki.citizensnpcs.co/Commands says to use this command
 ```/npc hologram | set [line #] [text] \| remove [line #] \| clear \| lineheight [height]```

I can't figure out how to get this to work. 
<img width="455" alt="Screenshot 2020-09-29 210257" src="https://user-images.githubusercontent.com/25316276/94634986-2b050a80-0297-11eb-9ade-209c4d1b9ad2.png">

**Comment by BobbyMere** [comment]
So I discovered it's ```/npc hologram set 0 <textt>``` But the hologram doesn't show up 
<img width="490" alt="Screenshot 2020-09-29 211602" src="https://user-images.githubusercontent.com/25316276/94635748-feea8900-0298-11eb-87d9-38bdfa314ce7.png">
<img width="271" alt="Screenshot 2020-09-29 211626" src="https://user-images.githubusercontent.com/25316276/94635771-0c077800-0299-11eb-948d-8192c3f3d265.png">
No hologram to be seen.  How would I go about adding multiple lines for the name?

**Comment by mcmonkey4eva** [comment]
You want `add` not `set`

Also, if you post issues in the future, please fill out the issue template (or ask on Discord @ https://discord.gg/Q6pZGSR )

**Comment by BobbyMere** [comment]
This doesn't help with the broken holograms though.

**Comment by mcmonkey4eva** [comment]
It's likely the issues you encountered were a secondary effect of messing with `reload` and using the hologram command funkily (using `set` without having ever `add`ed anything)

And you can see the issue template here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE

**Comment by BobbyMere** [comment]
Why did you lock the other one? I tried using the proper template. I have to use ```citizens reload``` other wise the text won't show at all. Even if I use add or not. How else can I get it to work?

**Comment by mcmonkey4eva** [comment]
- The duplicate issue was locked because you already have an issue post for this issue... _this_ post. This one here.

- Holograms should instantly appear after using the `add` command... if not, something bugged, which requires you post your logs as the issue template says to do, to be able to even begin to diagnose.

- Do not ever use `/citizens reload`.

- You say there's something wrong with lineheight but have not specified whatsoever. When I test locally, it works fine other than not instantly applying (it applies whenever either the NPC hologram changes, or the NPC moves in the world)

**Comment by BobbyMere** [comment]
OH I'm sorry. I was adding it to the other ticket before you locked it. 

this is what it looks like with a lineheight of 0
<img width="146" alt="Screenshot 2020-09-29 222804" src="https://user-images.githubusercontent.com/25316276/94640552-ad47fb80-02a4-11eb-9208-2c162449b322.png">
<img width="98" alt="Screenshot 2020-09-29 224023" src="https://user-images.githubusercontent.com/25316276/94640592-c6e94300-02a4-11eb-95c5-d2ae1f4d7f36.png">

This is what it looks like with a lineheight of 1
<img width="147" alt="Screenshot 2020-09-29 222633" src="https://user-images.githubusercontent.com/25316276/94640522-9c978580-02a4-11eb-8edc-3a4466d3210b.png"

**Comment by mcmonkey4eva** [comment]
Command information can be found in-game via `/npc help`, eg `/npc help hologram`.
The wiki text was misformatted (and thus most info was missing by mistake) and has been fixed.

And, again: server logs are needed to diagnose bugs. Refer to https://wiki.citizensnpcs.co/Logs if you're unsure how to locate your server logs.

**Comment by BobbyMere** [comment]
The `add` seems to have fixed the the holograms from showing up problem and I thank you. But what about the odd height spacing? There's no error for it. 
Here's my log though https://pastebin.com/xGF1sK1e
Config:  https://pastebin.com/PbPk99we

**Comment by mcmonkey4eva** [comment]
I see now why you're not asking on the Discord... because you were banned from there.
