### ISSUE TITLE
Holograms Not Displaying Correctly

### ISSUE THREAD

**Issue by BobbyMere** [CitizensDev/Citizens2#2343]
Description: 
There seems to be a problem with the command ```/npc hologram set 0 <text>```. When I do this, no text shows up until I do ```/citizens reload```. If I do ```/npc hologram set 0 name``` and then do ```/citizens reload``` the original hologram stays in place and produces a new one. The old one can't be deleted unless I use a command to remove armorstand entity. 

- Link to server log & Citizens config (using e.g. pastebin.com) ESPECIALLY if it's a pathfinding issue:
https://pastebin.com/u0PnhBxg

<img width="455" alt="Screenshot 2020-09-29 210257" src="https://user-images.githubusercontent.com/25316276/94639643-47f30b00-02a2-11eb-9c83-8b58ac807307.png">

This isn't a lag issue. Timings not needed. 

The output of command `/version` on my server is: version
[03:13:12 INFO]: Checking version, please wait...
>> = [03:13:12 INFO]: This server is running Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[03:13:12 INFO]: You are 3 version(s) behind
[03:13:12 INFO]: Previous version: git-Paper-174 (MC: 1.16.2)

The output of command `/version citizens` on my server is: version citizens
[03:15:02 INFO]: Website: http://www.citizensnpcs.co
>> = [03:15:02 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2113)
[03:15:02 INFO]: Author: fullwall

**Comment by mcmonkey4eva** [comment]
Please do not spam issues.
