### ISSUE TITLE
NPC's missing

### ISSUE THREAD

**Issue by Cryper** [CitizensDev/Citizens2#2347]
We've updated our Server to 1.16.3 and running Paper on it. After the Update everything worked fine. But suddenly after one restart all, beside one, NPC's are gone. Only our Smith is still there. Cant see them in "/npc list" , but if i open the saves.yaml everbody is still there.

The output of command `/version` on my server is: **git-Paper-207**
The output of command `/version citizens` on my server is: **2.0.27-Snapshot (build 2103)**

**Comment by mcmonkey4eva** [comment]
That build is pretty far behind, update to latest: https://ci.citizensnpcs.co/job/Citizens2/
