### ISSUE TITLE
Sentry Itemdrops

### ISSUE THREAD

**Issue by habnef3** [CitizensDev/Citizens2#235]
I have a couple of sentries in my server, one of them I want to drop his items, the other I don't. The first one works and drops it like normal, but the second one, no matter what setting I put it on, still drops his items. I have tried /sentry drops, /sentry killdrops, tried copying the first one then changing it. Tried creating a whole new one. Please help, I don't want it to drop it's items.

**Comment by mcmonkey4eva** [comment]
This is Citizens support, not Sentry.
