### ISSUE TITLE
Plugin don't work :  java.lang.NoSuchFieldError: a   at java.lang.Thread.run(Thread.java:748)

### ISSUE THREAD

**Issue by BlackFox3000** [CitizensDev/Citizens2#2350]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-215 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Previous version: git-Paper-214 (MC: 1.16.3)
 You are running the latest version**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2103)**

Hi, the plugin just doesn't work anymore.
Since the passage in 1.16.3, we get this error.
We tried various things only there we dry.

**Logs:**  https://pastebin.com/s9crrqzP

**Comment by mcmonkey4eva** [comment]
Update: https://ci.citizensnpcs.co/job/Citizens2/
