### ISSUE TITLE
Can't seem to use AStarNavigationStrategy.

### ISSUE THREAD

**Issue by raghav17083** [CitizensDev/Citizens2#2351]
I am using the CitizensAPI. I can't seem to use the AStarNavigationStrategy class in my code, even though I can import AbstractPathStrategy. Also, AStarNavigationStrategy class has nms and util from Citizens imported and not the CitizensAPI. Can that have something to do with the issue?

**Comment by mcmonkey4eva** [comment]
Make sure you've linked Citizens properly through maven, as explained at https://wiki.citizensnpcs.co/API
