### ISSUE TITLE
npc.getNavigator().setTarget(Location) does not move the npc to the target location

### ISSUE THREAD

**Issue by raghav17083** [CitizensDev/Citizens2#2353]
The npc spawns properly. Also the coordinates of the destination location are perfect. But, the npc does not move towards the destination location and sometimes spins at the location it spawns and stops. Any idea how i can move the npc to the target location?

```
package org.mineacademy.orion.npctest;

//import com.sk89q.worldedit.WorldEdit;

import net.citizensnpcs.api.CitizensAPI;
import net.citizensnpcs.api.ai.PathStrategy;
import net.citizensnpcs.api.hpastar.Tile;
import net.citizensnpcs.api.npc.NPC;
import net.citizensnpcs.npc.ai.AStarNavigationStrategy;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.Player;
import org.mineacademy.fo.Common;
import org.mineacademy.fo.command.SimpleCommand;

public class BlockFinder extends SimpleCommand {
    private final static int RADIUS=20;

    public BlockFinder(){
        super("bfind"); //blockfind
    }

    public void onCommand() {
        checkConsole();

        NPC npc= CitizensAPI.getNPCRegistry().createNPC(EntityType.VILLAGER,"cutter");
        Player player=getPlayer();
        npc.spawn(player.getTargetBlock(null, 5).getLocation().add(3, 3, 0));

        //add location and setTarget to that location.

        Location finalLoc=newLocation(npc,player,RADIUS);
        npc.setProtected(false);
        npc.faceLocation(player.getLocation());
        Common.log("Location "+finalLoc);
        npc.getNavigator().setTarget(finalLoc);



    }

    public Location newLocation(NPC npc, Player player,int radius) {
//        int r=RADIUS;
        int x= (int) npc.getStoredLocation().getX();
        int y= (int) npc.getStoredLocation().getY();
        int z= (int)  npc.getStoredLocation().getZ();
        int minx=(x-radius);
        int miny=(y-radius);
        int minz=(z-radius);
        int maxx=(x+radius);
        int maxy=(y+radius);
        int maxz=(z+radius);
        Location nloc=new Location(npc.getEntity().getWorld(),x,y,z);
        for(int rx=minx;rx<=maxx;rx++) {
            for (int ry = miny; ry <= maxy; ry++) {
                for (int rz = minz; rz <= maxz; rz++) {
                    Block block = player.getWorld().getBlockAt(rx, ry, rz);
                    if (block.getType() == Material.JUNGLE_WOOD && (rx != 0 || ry != 0 || rz != 0)) {
                        nloc.setX(rx);
                        nloc.setY(ry);
                        nloc.setZ(rz);
                        return nloc;
                    }
                }
            }
        }
        return nloc;
    }

}

```

**Comment by mcmonkey4eva** [comment]
Generally you're going to have to delay a navigator instruction to at least a tick or two after the initial spawn. You should also make sure that the location you've selected is actually reachable (as in, there's air above it, not eg the middle of a tree/wall/whatever, and that there's an actual way you can walk from the NPC's position to the target without having to eg scale a wall or jump over a chasm or similar)

**Comment by raghav17083** [comment]
I mean there aren't any obstruction between the npc and the block location.
Also, is there a way I can use NavigationStrategy to find a path between the starting location and destination?
I am pretty new to using Citizens.
Thanks.

**Comment by mcmonkey4eva** [comment]
Yes, add a delay with the scheduler.

Do you mean you want to use Citizens to provide pathfinding for something other than NPCs, or do you mean you think there isn't already pathfinding happening and want to enable it? Cause if so: it does already find a path automatically.

**Comment by raghav17083** [comment]
Actually, what I am trying to make is an NPC that can go to the nearest tree and chop the wood. The first task I thought would be to make it go to some destination block. I was going through the documentation of citizensAPI and came across AStarNavigationStrategy, but I don't really know how to use it or any other NavigationStrategy.

**Comment by mcmonkey4eva** [comment]
Yeah that's ran automatically. When you give it a target location (on the ground, not in a tree) it will find a path there and move to that location (the location is where to stand, not where it wants to be close to)

**Comment by raghav17083** [comment]
Alright, so setTarget() implicitly calls the navigationStrategy? Right?

**Comment by mcmonkey4eva** [comment]
Yes
