### ISSUE TITLE
Performance issue with PlayerUpdateTask

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#2354]
PlayerUpdateTask is causing high tick times of 60-120ms very often. See the spark report.
https://spark.lucko.me/#Dd6acyfaLX

The output of command `/version` on my server is: **(PLEASE FILL IN)**
This server is running Paper version git-Paper-216 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
Citizens version 2.0.27-SNAPSHOT (build 2113)

**Comment by mcmonkey4eva** [comment]
That spark report has more server load from basic chunk ticking (in that recording it picked up soil ticks checking for nearby water) than from Citizens. The PlayerUpdateTask seems to be primarily spending its time within that report processing basic entity movement (ie, code running in NMS that we can't change much, and if you really wanted it gone you could just make the relevant NPCs stop moving).

Your Citizens jar is also significantly out of date so you should probably update before anything else https://ci.citizensnpcs.co/job/Citizens2/

**Comment by HexedHero** [comment]
Scary since not a single NPC is moving/have any waypoints nor look near and once I unloaded Citizens my max 80-120ms sometimes 200ms~ tick times completely vanished.
