### ISSUE TITLE
Improve performance of entity targeting with A* pathfinder 

### ISSUE THREAD

**Issue by TJPlaysNow** [CitizensDev/Citizens2#2355]
Issue: When NPCs start tracking a player and they are on a floor above the player the server starts to lag extremely hard. There is a valid path to get to the NPCs. They just choose to not take it most of the time.
Log: https://hastebin.com/uyefasaqur.yaml

Paper Version: 214
Citizens Version: 2.0.27-Snapshot 2127
Both updated a day or two ago, every time I have brought the error up I am asked to update my plugins and the error still persists after every update.

https://spark.lucko.me/#ZyV14gvemy

The output of command `/version` on my server is: **[22:57:36] [Server thread/INFO]: This server is running Paper version git-Paper-214 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[22:57:36] [Server thread/INFO]: Previous version: git-Paper-100 (MC: 1.16.1)
[22:57:36] [Server thread/INFO]: You are 5 version(s) behind**

The output of command `/version citizens` on my server is: **[22:57:39] [Server thread/INFO]: Citizens version 2.0.27-SNAPSHOT (build 2127)
[22:57:39] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[22:57:39] [Server thread/INFO]: Author: fullwall**

**Comment by mcmonkey4eva** [comment]
- The server in that report is not lagging. It's likely you recorded too large of a time period.
- You have new-finder enabled and an invalid path... this is a combination that does indeed cause lag. Either disable new-finder (in the config or via `/npc pathopt`) to use the more performant old finder, or tweak the relevant pathfinder settings (max-iterations, etc) to try to improve new-finder's performance.

**Comment by TJPlaysNow** [comment]
```The server in that report is not lagging. It's likely you recorded too large of a time period.```
It did lag at the end of that time report but it is likely I recorded to large of a window of the server. You can see in log that the server was having trouble keeping up at some points though. (I can try recording a smaller window during the lag)

```You have new-finder enabled and an invalid path... this is a combination that does indeed cause lag. Either disable new-finder (in the config or via /npc pathopt) to use the more performant old finder, or tweak the relevant pathfinder settings (max-iterations, etc) to try to improve new-finder's performance.``` The path is valid every time, I can give you an IP so you can join and see the path(s) and what happens.

**Comment by TJPlaysNow** [comment]
If you could re-open the issue that would be cool.

Just the lag recorded.
https://spark.lucko.me/#XFby4BDpMo

**Comment by TJPlaysNow** [comment]
Here is an image of the map.
https://imgur.com/pOzpKIl

After opening `Door1` and `Door2`, and sitting at spot `X1` when NPCs spawn from the green dots the NPCs on the blue floor get stuck around spot `X2` even though there is a valid path down the stairs.

If you do the opposite and sit at `X2` NPCs get stuck at `X1` and the lag is actually way worse (Probably because more come from  red than blue).

When sitting in stairs of `Door2` the NPCs track correctly again.

**Comment by fullwall** [comment]
Can you take screenshots of the path with path-debug enabled?

**Comment by TJPlaysNow** [comment]
Alright, I collected as much information as I could during this test run.

Citizens Debug File: https://hastebin.com/muzadizofu.yaml
Citizens Config File: https://hastebin.com/etitununin.yaml
Latest Log File: https://hastebin.com/wufiqugexu.yaml
Images During Play: https://imgur.com/a/6M2iBac
Sparky Report: https://spark.lucko.me/#oqkFM9GuXe

**Comment by fullwall** [comment]
Added new API for this, just need to add a way to auto-switch to this in the config.
