### ISSUE TITLE
Double name with Always use hologram name

### ISSUE THREAD

**Issue by Alejandro-Sosa** [CitizensDev/Citizens2#2356]
When setting the option Always-use-name-holograms to true it causes a double name.

Server log: https://pastebin.com/sHkDc12M
Citizens config: https://pastebin.com/WK65rG3s

/version: 

```
[INFO] ....>.... This server is running Paper version git-Paper-220 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

[INFO] .... Previous version: git-Purpur-786 (MC: 1.16.3)

[INFO] .... You are running the latest version
```

/version Citizens

```
[INFO] ....>.... Citizens version 2.0.27-SNAPSHOT (build 2130)

[INFO] .... Website: http://www.citizensnpcs.co

[INFO] .... Author: fullwall
```

Here is a image of it: https://imgur.com/a/zWBxOVP

In the image i created a villager with the name test. This issue is on all the npcs except for players.

**Comment by fullwall** [comment]
Fixed

**Comment by Alejandro-Sosa** [comment]
Issue is fixed for the most part, but now the issue happens on player npcs. Example: https://imgur.com/a/IabB5Zm
