### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by srnyx** [CitizensDev/Citizens2#2357]
Hi, I was just wondering if the latest version of Citizens supports 1.16.3.
I noticed it said it doesn't work with 1.16.1 and 1.16.2, but I didn't know if that was outdated (like copy/pasted from an earlier version when 1.16.3 didn't exist).

**Comment by SXRWahrheit** [comment]
https://tryitands.ee/

**Comment by srnyx** [comment]
> https://tryitands.ee/

Ok, thank you
