### ISSUE TITLE
java.lang.NoSuchFieldError: ORIGIN error when I try to make an npc

### ISSUE THREAD

**Issue by EliteAspect21** [CitizensDev/Citizens2#2358]
When I try to create an NPC, I get an error that tells me to check console. The exact error is

 "Please report this error: [See Console] 
java.lang.NoSuchFieldError: ORIGIN"

The output of command `/version` on my server is: Paper version git-Paper-189 (MC: 1.16.2)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2133)
PasteBin error: https://pastebin.com/ATsUsNRu
PasteBin config: https://pastebin.com/QukmtDBX

**Comment by fullwall** [comment]
Either use 1.16.3 or downgrade to the old Citizens build for 1.16.2
