### ISSUE TITLE
NPC is ignoring waypoint delays

### ISSUE THREAD

**Issue by lucasryw** [CitizensDev/Citizens2#2359]
so, I'm trying to make my npc walk around a building in circle (about 10 waypoints), stopping at some of it setting a delay. 
but is not working... the npc is ignoring the delay. causing some warns in loop on server console, and sometimes ignores the waypoint order... very difficult to configure, maybe because of some bug. I'm using the mouse scroll to change the points to edit.
one thing I changed in the config was the npc look options and pathfinding:

    look-close:
      enabled: true
      range: 3
      random-look-enabled: true
      random-look-delay: 500
      disable-while-navigating: true
    pathfinding:
      range: 50.0

complete Citizens config: https://pastebin.com/4ZhAAJpK

console warn loop:
[console-citizens.txt](https://github.com/CitizensDev/Citizens2/files/5363165/console-citizens.txt)

logs:
[latest.log](https://github.com/CitizensDev/Citizens2/files/5363155/latest.log)
[2020-10-12-3.log.gz](https://github.com/CitizensDev/Citizens2/files/5363156/2020-10-12-3.log.gz)

This server is running Paper version git-Paper-227 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Citizens version 2.0.27-SNAPSHOT (build 2134)

**Comment by fullwall** [comment]
Can you post your saves.yml please?

**Comment by lucasryw** [comment]
sure! thanks for the reply

[saves.yml.zip](https://github.com/CitizensDev/Citizens2/files/5363326/saves.yml.zip)

**Comment by lucasryw** [comment]
some other thing, when I create 2 waypoints, seems like the plugin is setting the second I make as the first. and the first as the second. so the the npc goes to the second ignoring the first. and when selecting the waypoint 0 and right clicking, its deleting the SECOND that I made, not the first.

**Comment by fullwall** [comment]
Your saves.yml doesn't appear to be updated? Can't see any triggers in there

**Comment by lucasryw** [comment]
I did multiple tests clearing the waypoints and trying again... but I just tested with a clean server, same version (paper-227), and with just the citizen plugin. same thing happened... ignored delays completely, wrong waypoint order... but no warns this time... I'm sending you the saves.yml of this clean server:
[saves.yml.zip](https://github.com/CitizensDev/Citizens2/files/5363665/saves.yml.zip)

and the entired test server (username: infinitytph):
http://www.mediafire.com/file/65qglc15sq0vgak/citizen-bug-test-server.zip/file

all new logs (clean server)
[2020-10-12-1.log.gz](https://github.com/CitizensDev/Citizens2/files/5363686/2020-10-12-1.log.gz)
[2020-10-12-2.log.gz](https://github.com/CitizensDev/Citizens2/files/5363687/2020-10-12-2.log.gz)
[2020-10-12-3.log.gz](https://github.com/CitizensDev/Citizens2/files/5363688/2020-10-12-3.log.gz)
[latest.log](https://github.com/CitizensDev/Citizens2/files/5363689/latest.log)

**Comment by fullwall** [comment]
I have made some fixes to /npc path in the latest build for you. I was not able to get the delay to not work however.

**Comment by lucasryw** [comment]
this build is better, but the issue persists... I'm sending you a video showing all the problems/issues and things that are now working. the ignoring delay issue persists.

https://www.youtube.com/watch?v=JeOhhsmA7Zc

the new save file (save file of the video)
[saves.yml.zip](https://github.com/CitizensDev/Citizens2/files/5368159/saves.yml.zip)

**Comment by fullwall** [comment]
I have just removed the editing slot thing because I always found it confusing.

**Comment by lucasryw** [comment]
thank you very much man! did you found the solution for the delay stop working?

**Comment by fullwall** [comment]
Still not able to reproduce it consistently...

**Comment by lucasryw** [comment]
how can I help you? I'm really hoping this will get fixed soon, because I'm working on my server for weeks trying to finish, so I can open for people on my discord, and this is the only thing missing, so I can add all npcs, including the shopkeepers, that I will use with citizens npcs. I've tested the new build... the sneaking and right click thing is not working, making me accidentaly deleting a waypoint when not crouching. the distance it shows between the previous waypoint is wrong (that msg about the limit is 25). about the delays, everytime I try they fail haha... :( have you tried lots of waypoint around an area?

I'm sending you a new save file (b2145), I've created 13 waypoints (0-12), and 4 delays (60 ticks), the delay in waypoint 10 is not working. I tried to remove the delay and add again, changing to 80 this time... didn't work... the test I made before this was putting 2 delays in 2 waypoints and none of them worked.

[saves.yml.zip](https://github.com/CitizensDev/Citizens2/files/5371360/saves.yml.zip)

**Comment by fullwall** [comment]
Still not reproducing this, but I just pushed a build which is more lenient with the distance calculation if you want to give it a try.

**Comment by lucasryw** [comment]
hey man, you said you can't reproduce the exactly cause of some waypoints/delays are being ignored, because is random, right? but have you experienced the problem?? (creating multiples waypoints and testing)... or the problem didn't even ocurred to you?? is just me?? because with me, like I said, everytime I try, I get in the problem, but is random, I don't know what are the actions that I'm doing that with some waypoints it works, some it don't... So if this is happening to you, means that the triggers system is not good, and is not working properly. maybe you should consider redesigning it. if not, then we could try finding why, but I don't think is just me, I tried to isolate the problem, sent you the server... anyway, I have a basic knowlage in programing, a LITTLE in java, but anything I could do to help, I will.

**Comment by fullwall** [comment]
The problem has not occurred for me yet. I tried your server, and I tried on my own test server.
