### ISSUE TITLE
Ghost Entity

### ISSUE THREAD

**Issue by farget92** [CitizensDev/Citizens2#236]
Hello community,

We had on our server wipe, but after it we add your plugin ( Citizens )
But today, we have quite confusing ... not error, but bug.

Our server with /list cmd: 
http://prntscr.com/633r00

Our server from proxy - BungeeCord /glist
http://prntscr.com/633t2m

We had on our server 2 times [Helper]BigShock ...
But he was on server only one time as all other player.

I think, this bug is caused by Citizens , or some collision with other plugin.
If you have some experience with this bug ... , please give me some sollution ;)

**Comment by mcmonkey4eva** [comment]
I... I don't... this can't be from Citizens, that's almost surely Bungee or something like that.

**Comment by farget92** [comment]
Hmm, perhaps ... But I think, that can not be from BungeeCord, we also using test server without Bungee, and we have same problem :(
Our main plugins: WorldGuard, WorldEdit, Essentials, Faction, MultiVers, Mobarena
