### ISSUE TITLE
Redo /npc path editor to be more intuitive 

### ISSUE THREAD

**Issue by fullwall** [CitizensDev/Citizens2#2361]
Looking at all waypoint editors and the trigger editor

**Comment by Misquoth** [comment]
This would be great.

maybe a gui menu to alter the waypoints? The main issues I've had is if you have a long list of waypoints and need to modify it in the middle it seems like there's hooks for inserting but you have to specify the index, and AFAIK there's no way to get the index of an existing waypoint. 

It might also be nice to have sets of way points that could be assigned via logic to different NPCs for different occasions.

**Comment by fullwall** [comment]
Yes, there used to be a way to insert in the middle but it was a bit complicated. It may be easier to allow you to insert after current selected waypoint. I agree on the sets of waypoints thing. Basically the waypoints system probably needs a partial rewrite to be more user friendly and clear and allow these extra features.
