### ISSUE TITLE
Npc's nametags bugged/ glitched

### ISSUE THREAD

**Issue by storm0chaser** [CitizensDev/Citizens2#2362]
The output of command `/version` on my server is: **1.8.8)**
The output of command `/version citizens` on my server is: **(Any latest version)**

Npc's nametags show as https://i.imgur.com/AkGg6Q7.png
When they are longer than 16 characters.
Also I believe they sometimes disappear completely.

**Comment by mcmonkey4eva** [comment]
Please fill out all required portions of the issue template exactly as the template requests.
