### ISSUE TITLE
NPC Становятся невидимыми 

### ISSUE THREAD

**Issue by StefTLT** [CitizensDev/Citizens2#2365]
Всем привет, столкнулся с проблемой. Расставил NPC на сервере и если отойти от них достаточно далеко и вернуться то они становятся невидимыми. взаимодействовать никак нельзя, при телепортации стоят где  положено но их все по прежнему не видно. как можно решить данную  проблему ? версия 1.15.2

**Comment by mcmonkey4eva** [comment]
English only please.
