### ISSUE TITLE
NPC is not respawning close to shopkeeper citizen npc player

### ISSUE THREAD

**Issue by lucasryw** [CitizensDev/Citizens2#2366]
NPC is not spawning after restarting the server when close to shopkeeper citizen npc player.
I could reproduce this in a clean server. Only occurs with citizens b2145 or later.

what I did:
/npc create bob
/npc path (make 2 points)
/shopkeeper npc (created close to bob)
/npc sel
/npc type player
restart server

bob won't spawn
I tested creating another 2 npcs away from each other, bob and the shopkeeper. same configuration as the first 2. Both spawned, bob still not.

On my main server, the npc who is not spawning is the shopkeeper! (npc/player-type)
I'm trying to put a shopkeeper close to other npcs (guards) and it only spawn if I set his postition away from the guards.

Paper version git-Paper-227 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Citizens version 2.0.27-SNAPSHOT (build 2149)
Shopkeepers v2.11.0
configs=default

clean test server
http://www.mediafire.com/file/eluls6s28r6dz5d/clean-test-server.zip/file

last log
https://pastebin.com/REAqBQ0g

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
