### ISSUE TITLE
After 2140 build it doesn't load some npc

### ISSUE THREAD

**Issue by andris155** [CitizensDev/Citizens2#2367]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-229 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2146)**

With 2140 build - load all npcs perfectly.
After build 2140 - no load some npc

![96100180-5e20de00-0ed4-11eb-9bea-dd3c1c50c6e1](https://user-images.githubusercontent.com/8324198/96108582-0a1af700-0ede-11eb-883d-2a559b4c3656.png)

**Comment by Fargus5** [comment]
Thanks to report this. I agree with you... and also in the latest build 2149 **the problem persist**.
I'm on Paper Build 231

**Comment by fullwall** [comment]
Should be fixed in build 2151.

**Comment by andris155** [comment]
Thanks!
