### ISSUE TITLE
Mouse Click

### ISSUE THREAD

**Issue by Benny0505** [CitizensDev/Citizens2#2368]
Hello,

I bought the plugin :)

now i have a question can you change that with the mouse? so left click?

Sorry for my english

Nice Plugin :)

**Comment by mcmonkey4eva** [comment]
I... think you forgot the question part of your question.

**Comment by Benny0505** [comment]
I would like to use this command
/npc command add -p server lobby

That you do not right click but left click

**Comment by fullwall** [comment]
/npc command add -p -r server lobby

**Comment by mcmonkey4eva** [comment]
`-r` for right, `-l` for left.
