### ISSUE TITLE
Citizens 1.16 don't work

### ISSUE THREAD

**Issue by LikeManTV** [CitizensDev/Citizens2#2370]
The output of command `/version` on my server is: **Paper version git-Paper-240 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build  2100)**

12:47:41[INFO] Likemantv issued server command: /npc create test
12:47:41[WARN] java.lang.NoSuchFieldError: a
12:47:41[WARN] at net.citizensnpcs.nms.v1_16_R2.util.PlayerNavigation.<init>(PlayerNavigation.java:43)
12:47:41[WARN] at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:318)
12:47:41[WARN] at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:97)
12:47:41[WARN] at net.citizensnpcs.nms.v1_16_R2.entity.HumanController.createEntity(HumanController.java:50)
12:47:41[WARN] at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
12:47:41[WARN] at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:249)
12:47:41[WARN]
at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:509)
12:47:41[WARN] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:47:41[WARN] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:47:41[WARN] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:47:41[WARN] at java.lang.reflect.Method.invoke(Method.java:498)
12:47:41[WARN] at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
12:47:41[WARN] at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
12:47:41[WARN]
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
12:47:41[WARN]
at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
12:47:41[WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
12:47:41[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
12:47:41[WARN] at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
12:47:41[WARN]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
12:47:41[WARN] at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
12:47:41[WARN] at java.lang.Thread.run(Thread.java:748)

**Comment by DoctorMacc** [comment]
You're using an outdated build of Citizens - download from the Spigot page or https://ci.citizensnpcs.co/job/Citizens2/ .

**Comment by LikeManTV** [comment]
It's the newest version from Spitgot page..

**Comment by mcmonkey4eva** [comment]
That is definitely not the newest version from the Spigot page, nor from the [dev builds](https://ci.citizensnpcs.co/job/Citizens2/) page that was linked. That is at time of writing 53 builds behind.
