### ISSUE TITLE
Citizen creates one armor stand per tick

### ISSUE THREAD

**Issue by Jessssuhh** [CitizensDev/Citizens2#2371]
I have one citizen animated to sit at spawn and do nothing. When the server restarts, the sitting npc glitches half a block down and creates thousands of armor stands in about two minutes. I'd guess perhaps one per tick. 

I am running MC 1.16.3, Paper 242 (which I've noticed is outdated and will update now) and Citizens build 2151.

I'm not kidding when I say the log is so long it crashes pastebin. But here's a small sample of what makes it so big:
<spoiler>[00:56:51] [Server thread/WARN]: [Citizens] Task #18193 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null
[00:56:51] [Server thread/WARN]: [Citizens] Task #18206 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null
[00:56:51] [Server thread/WARN]: [Citizens] Task #18232 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null
[00:56:51] [Server thread/WARN]: [Citizens] Task #18248 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null
[00:56:51] [Server thread/WARN]: [Citizens] Task #18283 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null
[00:56:51] [Server thread/WARN]: [Citizens] Task #18289 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null
[00:56:51] [Server thread/WARN]: [Citizens] Task #18293 for Citizens v2.0.27-SNAPSHOT (build 2151) generated an exception
java.lang.NullPointerException: null</spoiler>

**Comment by mcmonkey4eva** [comment]
Please [pastebin](https://pastebin.com/) a copy of all the information at the start up through until at least a few repeats of a full error message

**Comment by Jessssuhh** [comment]
[This](https://pastebin.com/ME13X3P7) is as far down as pastebin would let me get. The log is 18.5 million lines of code for about a ten minute period

**Comment by Jessssuhh** [comment]
Also just FYI its not the latest.log simply because I've since despawned that particular NPC and continued on.

**Comment by mcmonkey4eva** [comment]
`[00:54:46] [Server thread/INFO]: Jessssuhh issued server command: /minecraft:kill @e[type=armor_stand]`
^ that command deleted the armor stand that the NPC is trying to sit on, and created the errors that result (as the armor stand that was expected to be there is gone). The errors would automatically go away once either the NPC respawns for any reason or the server restarts.

As to why armor stands are being spammed into existence... well it probably depends on what you're doing to trigger the sit animation... that log doesn't contain Denizen, so you're not using the standard `/npc sit` command... (which is probably what you _should_ be using)

**Comment by Jessssuhh** [comment]
I'm using /npc path and then triggers animate sit. I issued the kill command because of the thousands of armour stands reported in timings.

**Comment by fullwall** [comment]
If you only have one waypoint it will "reach" the same place every tick and try to sit every tick, which is probably what you are experiencing. Maybe you should try a delay trigger or (more preferably) denizen?

**Comment by Jessssuhh** [comment]
I believe there was a delay, tho I couldn't tell you what with certainty. Most of my other animated NPCs have a default of speed 0.8 and delay of 200/10 seconds per waypoint on their path. I was planning on looking at denizen today anyway because I'd like a few shop NPCs to sort of mumble incoherently if players are near.

**Comment by Jessssuhh** [comment]
Well I've got them sat with denizen, I'll update this if the issue persists at any point.

**Comment by Jessssuhh** [comment]
Denizen seems to be working so far, probably good to close this now!
