### ISSUE TITLE
Controllable Mob conflict with Worldguard Regions

### ISSUE THREAD

**Issue by Maitlans** [CitizensDev/Citizens2#2373]
The output of command `/version` on my server is: **git-Paper-191 (MC: 1.16.3)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2120)**

When you create a controllable and ride him you're able to bypass worldguard region flags, such as denying leaving a region or entering one, as well as other features of Worldguard.

**Comment by SXRWahrheit** [comment]
This is a WorldGuard issue, not a Citizens one.

**Comment by Maitlans** [comment]
Hey @mcmonkey4eva I went on worldguard's discord explained the issue and I was told this, I'm not sure on what to do next.
![image](https://user-images.githubusercontent.com/51733032/97152802-d5156c80-1747-11eb-9948-bb909c0299eb.png)
