### ISSUE TITLE
Citizens left click not working (Bungeecord stuffs)

### ISSUE THREAD

**Issue by JaeHoKwak1** [CitizensDev/Citizens2#2374]
NPC left click commands do not run in any of the servers I made that are connected via bungeecord unless they are of type Villager. The ones in the main (hub) server run the commands just fine, it's just the ones in the sub servers that branch off from the main one.

I didn't include a server console output since nothing gets outputted since the commands aren't running at all.

https://pastebin.com/uQXr5mdf

This server is running Paper version git-Paper-206 (MC:1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

2.0.27-SNAPSHOT (build 2153)

**Comment by JaeHoKwak1** [comment]
Fixed it. Just had to go into configs and change the saves.yml in the saves directory

**Comment by JaeHoKwak1** [comment]
Turns out it didn't fix it. I was just being stupid...I clicked on a Villager type NPC...

**Comment by mcmonkey4eva** [comment]
Please pastebin an actually viewable latest.log ... the pastebin link you gave is private'd

**Comment by JaeHoKwak1** [comment]
That is very strange. I specifically remember making it public. Anyway I fixed it fixed it. https://pastebin.com/uQXr5mdf

**Comment by mcmonkey4eva** [comment]
Still need a full latest.log pastebin

**Comment by JaeHoKwak1** [comment]
Ah I'm so sorry.
https://pastebin.com/c1C2WSGn

**Comment by mcmonkey4eva** [comment]
That is not the full contents of the `latest.log` file

**Comment by JaeHoKwak1** [comment]
https://pastebin.com/PQwpPrxr

**Comment by mcmonkey4eva** [comment]
Do you have PvP disabled in your server settings or WorldGuard?
Player-type NPCs are often seen as basically just players (by plugins that don't explicitly integrate with Citizens), and "left clicking an NPC" is actually just attacking (punching) that NPC... so if PvP is disabled, that blocks "left clicking" on "player-type NPCs" (aka: it blocks punching other players!)

**Comment by JaeHoKwak1** [comment]
That fixed it. I'm not sure how I didn't realise sooner...

Thank you so much! Sorry for the screw ups with the logs and what not. I've never had to touch em before so I wasn't sure what I was doing xD
