### ISSUE TITLE
1.16.4 Build #1 does not work on 1.16.4

### ISSUE THREAD

**Issue by MisterSheeple** [CitizensDev/Citizens2#2377]
The output of command `/version` on my server is: **Paper build 259 (MC: 1.16.4)**
The output of command `/version citizens` on my server is: **v2.0.27-SNAPSHOT (build 2161)**

 "v2.0.27-SNAPSHOT is not compatible with Minecraft v1_16_R3" and it subsequently disables it.

My server is Paper build 259 (MC: 1.16.4)

Citizens is on v2.0.27-SNAPSHOT (build 2161) as mentioned above.

I suspect this issue is because of the latest commit, whereas V1_16_R3 was renamed to v1_16_R2, and 1.16.4 in actuality is R3 and not R2. So I suggest undoing commit 4542d70.

**Comment by SXRWahrheit** [comment]
Mojang reverted the new NMS version for some reason, yeah. This will be fixed soon.

**Comment by mcmonkey4eva** [comment]
https://ci.citizensnpcs.co/job/Citizens2/2160/ should work pending the re-fix for md_5 trying to piss off every plugin dev by renaming the module a 3rd time.
