### ISSUE TITLE
Saves.yml file not working (reset to blank when server starts)

### ISSUE THREAD

**Issue by Skyquior** [CitizensDev/Citizens2#2379]
Hello ! I submit this new issue for a particular problem : 
When I had my server on **1.15.2** I created a map with a lot of citizens and got the **Saves.yml** file too with all writen in it. Then I decided to update my server on **1.16.3** and bought the version "(1.16.3 BUILD #4)" of citizens to use it, the **1.15.2** version of the plugin being outdated and not working (plugin name in red).
-> The problem is that when I paste the **Save.yml** file in the Citizen folder and replace the (blank one) with the one from my 1.15.2 version, my server seems to reset it automatically when I reload / stop - restart  the server. So all the saving in my old Save.yml file disapear (reset to a blank one) and then no NPC appear on the map (wich is the same so the locations are the sames too).
Is there a way to bring the saves from the 1.15.2 version of citizens to the 1.16.3 version ? Or will it reset 24/7 whenever I try to launch the server ? 

Thank you !
Hope you can help me to resolve this problem ! 👍 Im a big fan of this plugin.

The output of command `/version` on my server is: **(1.16.3)**
The output of command `/version citizens` on my server is: **((1.16.3 BUILD #4))**

**Comment by BehrRiley** [comment]
> `The output of command /version on my server is: (1.16.3)
> The output of command /version citizens on my server is: ((1.16.3 BUILD #4))`

this is not the full output as neither of these outputs are valid, can you please either paste the entire full context, or a startup log instead please

**Comment by Skyquior** [comment]
/version : This server is running Paper version git-Paper-251 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
/version citizen : Citizens version 2.0.27-SNAPSHOT (build 2151)

**Comment by mcmonkey4eva** [comment]
Stop the server, THEN replace the file, THEN start the server. You generally can't manually edit the files of a live server.

**Comment by Skyquior** [comment]
Thank you it worked !
