### ISSUE TITLE
Horses not moving

### ISSUE THREAD

**Issue by JCThePants** [CitizensDev/Citizens2#238]
I noticed horses do not move anymore when a target is set nor do they move when setting waypoints. This seems to be the case for all builds for 1.8.

I did a little digging into the source and found that I could get them to follow their waypoints by invoking `super.doTick()` in `net.citizensnpcs.npc.entity.HorseController#doTick` method just after `npc.update()`.

I admit I have no clue what is going on in Minecrafts `EntityHorse#doTick` or what part of the code in it is needed and what is not.

**Comment by mcmonkey4eva** [comment]
Does this still affect 1.8.3?

**Comment by JCThePants** [comment]
Its working in latest build.
