### ISSUE TITLE
Default npc text keeps reappearing even after removing

### ISSUE THREAD

**Issue by JaeHoKwak1** [CitizensDev/Citizens2#2381]
I've tried removing the npc text from the config yml, in the saves yml and in game but whenever I restart the server the NPC says the default text line ("Hi! Im <npc>").

Config: https://pastebin.com/c8ewTFkL
Latest.log: https://pastebin.com/QpkjaFkD

The output of command `/version` on my server is: 
"This server is running Paper version git-Paper-206 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)"
The output of command `/version citizens` on my server is: 
"version 2.0.27-SNAPSHOT (build 2153)"

**Comment by mcmonkey4eva** [comment]
Use `/trait text` to remove the text entirely from an NPC
