### ISSUE TITLE
Cant run on 1.16.1

### ISSUE THREAD

**Issue by JeffsHer** [CitizensDev/Citizens2#2382]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2167)**
so i did the installation instructions on the wiki i restarted my server and when i run /citizens it says "an internal error occurred"
how do i fix this

**Comment by mcmonkey4eva** [comment]
You need 1.16.4, not .1
