### ISSUE TITLE
path marker 

### ISSUE THREAD

**Issue by seema84** [CitizensDev/Citizens2#2383]
Paper-253 (MC: 1.16.3)
Citizens-2.0.27-b2158

The path marker do not disappear when leaving the editor or deleting the npc, toggle path does not work
only a server restart helps

**Comment by mcmonkey4eva** [comment]
Update, this was already fixed in newer versions

**Comment by seema84** [comment]
i think b2158 was the latest build for 1.16.3
spigot/paper 1.16.4 its not a recommended version
