### ISSUE TITLE
NPC Path> Door closing request

### ISSUE THREAD

**Issue by RepublicanSensei** [CitizensDev/Citizens2#2385]
With new pathfinders, citizens are able to open doors but after they pass the door, they won't close the doors.
My requests are: 
* Citizens should close the doors after they pass.
* Sounds for door opening and closing. (If its possible)
* Add fence gate support for doors. Citizens should be able to open/close fence gates too.

Thanks <3

**Comment by fullwall** [comment]
Should be addressed in the new build, although closing might be funny.
