### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by dinobossytnew** [CitizensDev/Citizens2#2387]
but before I get this, the kangaroo bosses dev told me to talk to you.
https://pastebin.com/VCFwMuFR

The command that they ask me to execute on my server does give an error, it says that the plugin is disabled.

**Comment by mcmonkey4eva** [comment]
Please fill out the issue template properly. You can find a copy of the template you ignored here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE
Alternately, feel free to ask for help on the Discord channel instead: https://discord.gg/Q6pZGSR

**Comment by dinobossytnew** [comment]
.........

**Comment by dinobossytnew** [comment]
**### _ok thanks i guess .._**
