### ISSUE TITLE
In 1.8.8 /npc name doesnt toggle name visiblity

### ISSUE THREAD

**Issue by JHarris12345** [CitizensDev/Citizens2#2389]
The output of command `/version` on my server is: **https://gyazo.com/f4abccc5bfd0095157c3fb9a7bcf77e5**
The output of command `/version citizens` on my server is: **(.0.26-SNAPSHOT (build 1996)**

- Server version 1.8.8 the /npc name command is not hiding the name 
- Server log: https://pastebin.com/9TrNHEbq
- Citizens config: https://pastebin.com/pnGw15CA

**Comment by mcmonkey4eva** [comment]
Every part of that server setup is completely unsupported.
- Software breaking plugins (plugman, etc)
- Nonsense server jar (only Spigot and Paper are supported)
- Ancient server version (1.8 is 6 years old... https://wiki.citizensnpcs.co/Minecraft_1.8 )
- Very old Citizens version ( https://ci.citizensnpcs.co/job/Citizens2/ )

If anything you're lucky to have only the one minor thing going noticeably wrong with such an arcane setup
