### ISSUE TITLE
Can't setup Citizens on my server

### ISSUE THREAD

**Issue by vffa34** [CitizensDev/Citizens2#2391]
Hello,i can't setup Citizens on my server. I tried to but it only showed the message "An internal error occoer while attempting to perform this command"
My log is empty. The config is in https://pastebin.com/aR179jhB
Lower is the image of both commands.

![image](https://user-images.githubusercontent.com/62444045/99976797-2b57e880-2da4-11eb-86d5-0a411eb7f6a3.png)

**Comment by vffa34** [comment]
Well,i just realised that i wrote everything in the wrong box. Taking this down

**Comment by mcmonkey4eva** [comment]
You downloaded a 2 year old file from the page with this on top of it:
![img](https://i.alexgoodwin.media/i/misc/1bc52c.png)

Please download the current Citizens build from https://ci.citizensnpcs.co/job/Citizens2/
