### ISSUE TITLE
NPC with waypoints defined are not working

### ISSUE THREAD

**Issue by Chronoken** [CitizensDev/Citizens2#2392]
Intended outcome: `The server is launched and all npc with waypoints are moving.`
Actual outcome: `All npcs with their waypoints set, show an error in the console and stop moving at all.`
What troubleshooting have you done: `I've tried clearing all of their waypoints and defining new ones, but the same thing is happening after i restart or reload citizens.`
Have you looked at console for any errors?: `Yes, this error shows up for each npc with a waypoint defined: `https://pastebin.com/7WaWRRAZ

Steps to reproduce:
  - Create an npc
  - Set its waypoints with `/npc path`
  - Save the npc
  - reload the plugin or restart the server

The output of command `/version` on my server is: `This server is running Purpur version git-Purpur-845 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`

The output of command `/version citizens` on my server is: `Citizens version 2.0.27-SNAPSHOT (build 2187)`

**Comment by mcmonkey4eva** [comment]
That pastebin link doesn't work.
