### ISSUE TITLE
hasMetadata("NPC") not working in CreatureSpawnEvent

### ISSUE THREAD

**Issue by TheNety** [CitizensDev/Citizens2#2394]
The output of command `/version` on my server is: **This server is running Paper version git-Paper-294 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**

Hey, firstly, sorry for deleting part of template, but online mode was already verified on your discord and the current version or anything another is not needed as the research is as follows:

In my plugin, I check if entity `hasMetadata("NPC")`. It's working fine to the Citizens build 2180 (included). It's not working properly in build 2181 and newer. So the issue must be in this commit - https://github.com/CitizensDev/Citizens2/commit/3c2d0625b476c25b0768133ac73bbb4f8ccd033f.

**Comment by mcmonkey4eva** [comment]
That commit moves the metadata set to *after* the spawn event, when it used to be before. So the basic solution here would be to just move the metadata set back to where it was.

**Comment by mcmonkey4eva** [comment]
Should be fixed via https://github.com/CitizensDev/Citizens2/commit/0b79c392b0ccfb4f942a2463b3a04c2c3c353187 for build 2190+ from https://ci.citizensnpcs.co/job/Citizens2/
