### ISSUE TITLE
price is not listed on the website

### ISSUE THREAD

**Issue by JasonTable** [CitizensDev/Citizens2#2395]
the issue is that the plugin's price to buy it is not listed on the website anywhere. i know it became a paid plugin because spigot wants a login so that it can first bait me into making an account before telling me that i gotta pay for the mod. i would not mind buying the mod but not from spigot because they are dishonest. but i would at least like to know the price before making the spigot account.

**Comment by fullwall** [comment]
Read the description on Spigot.
http://ci.citizensnpcs.co
