### ISSUE TITLE
Error when i try to execute "/npc" command

### ISSUE THREAD

**Issue by Monaldcry7788** [CitizensDev/Citizens2#2396]
Server version and citizen version:
![immagine](https://user-images.githubusercontent.com/63928518/100498693-535c9880-3164-11eb-9cae-0acc1270a56d.png)

Citizen config: https://pastebin.com/3qFdCnAN
Server Log: https://pastebin.com/FK6AwZwz
Spark: https://spark.lucko.me/#bgBRrndwFp

Hi, when i try to create a NPC or execute command "/npc" give me this error: https://pastebin.com/nzMqdsHJ

**Comment by BehrRiley** [comment]
Your previous version shows that you actually downgraded your sub-version which isn't good to do, you'll want to update to the latest sub-version for your server's version (1.16.4) for the citizens build you're using. You are behind 43 versions now
you may also consider removing these problematic plugins:
`PluginManager v1.6` - PlugMan is dangerous and will cause unpredictable issues. Remove it.
`CitizensCMD v2.5.1` - NPC Command plugin was abandoned in favor of the built-in Citizens command. The modern way is https://wiki.citizensnpcs.co/NPC_Commands.
Regarding your spark report, `MinecraftServer.sleepForTick()96.58%` indicates your server is not lagging, or you did not catch any reasonable measure of lag here.
Lastly, you have other plugins throwing errors you'll want to resolve to eliminate any unexpected problems, this may be resolved by updating your server version and the relevant plugins as well

**Comment by Monaldcry7788** [comment]
Thanks, now i test it

**Comment by Monaldcry7788** [comment]
Work, thanks so much
