### ISSUE TITLE
Provider change locks /npc path from closing

### ISSUE THREAD

**Issue by Jimjamss** [CitizensDev/Citizens2#2398]
When using /npc path editor it is possible to change the provider causing the /npc path command to be locked from closing giving message "You're already in an editor!" as it is reading the old provider editor being opened. 

The only fix besides reloading the plugin was changing the provider back to the original provider from when the command was issued. 

The output of command `/version` on my server is: **This server is running Craftbukkit version git-spigot-a19903d-009f0ba (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Checking version, please wait...
you are 8 version(s) behind**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2190)**

**Comment by mcmonkey4eva** [comment]
I've tested and confirmed this does happen as reported on current builds (2210 in my testing).
Replication steps:
- `/npc path` (path editor opens and works)
- `/wp provider wander` (provider switches)
- `/npc path` (now says "You're already in an editor!", can continue to place path points)

**Comment by mcmonkey4eva** [comment]
This was fixed by https://github.com/CitizensDev/Citizens2/commit/1ae074278e4899cd3e3dd8af3f5c188ad982760f for build 2212+ on https://ci.citizensnpcs.co/job/Citizens2/
