### ISSUE TITLE
/builder load error

### ISSUE THREAD

**Issue by caxdepth** [CitizensDev/Citizens2#2399]
npc:
  always-use-name-holograms: false
  pathfinding:
    new-finder:
      iterations-per-tick: 5000
      check-bounding-boxes: false
      open-doors: false
    default-distance-margin: 2
    default-path-distance-margin: 1
    update-path-rate: 20
    straight-line-targeting-distance: 5
    disable-mc-fallback-navigation: true
    maximum-new-pathfinder-iterations: 10000
    minecraft:
      max-fall-distance: 3
    attack-range: 3.0625
    use-new-finder: false
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  controllable:
    ground-direction-modifier: 1.0
    max-ground-speed: 0.5
    use-boat-controls: true
  default:
    waypoints:
      cache-paths: false
    look-close:
      enabled: false
      range: 5
      random-look-enabled: false
      random-look-delay: 60
      disable-while-navigating: true
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  hologram:
    default-line-height: 0.4
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
    remove-packet-delay: 1
  follow:
    teleport-across-worlds: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0
  commands:
    error-messages:
      maximum-times-used: You have reached the maximum number of uses ({0}).
      no-permission: You don't have permission to do that.
      not-enough-money: You need at least ${0}.
      on-cooldown: Please wait {0} more seconds.
  packets:
    update-delay: 30
  player:
    remove-from-list: true
  selection:
    item: stick
    message: Selected [[<npc>]] (ID <id>).
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '*'
  teleport-delay: -1
  player-scoreboard-teams:
    enable: true
general:
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-error: <c>
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins

![2020-12-02_16 38 54](https://user-images.githubusercontent.com/75395297/100934574-ee36d900-34bc-11eb-966c-b7f89837ede6.png)

![2020-12-02_16 33 01](https://user-images.githubusercontent.com/75395297/100934280-85e7f780-34bc-11eb-9dce-14ee72fca67f.png) # Citizens Configuration
So I'm on 1.16.4 and I have the version 2.0.27

I created a builder and when I use the load command it gives me the error message  "An internal error has occurred while attempting to preform this command"  Does anybody know how to fix this

**Comment by BehrRiley** [comment]
Please fill out the issue template properly. You can find a copy of the template you ignored here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE
Alternately, feel free to ask for help on the Discord channel instead: https://discord.gg/Q6pZGSR

**Comment by caxdepth** [comment]
@BehrRiley I have updated my post 
does it fill the requirements in the template?

**Comment by caxdepth** [comment]
I have updated my post to fulfill the template

**Comment by BehrRiley** [comment]
Bukkit development was discontinued 6 years ago. You should be either using Spigot or Paper. 
Paper is a higher-performance alternative to Spigot that is 100% compatible with the equivalent Spigot version. 
It's much easier to update than Spigot itself, and carries a lot of performance and quality-of-life benefits.
Latest Paper builds are at https://papermc.io/downloads.

Builder is maintained by someone that isn't actively connected to this community, you can find it here: https://www.spigotmc.org/resources/builder-reloaded-1-8-1-16.55326/
