### ISSUE TITLE
I can't control npc in 1.8.1 server

### ISSUE THREAD

**Issue by natural7530** [CitizensDev/Citizens2#240]
I used 2.0.14 version of citizen plugin.

**Comment by mcmonkey4eva** [comment]
...?

**Comment by DarkCrimsonFury** [comment]
I believe what he's saying is, "I'm unable to use the "Citizens2" plugin due to a slight malfunctions with the commands."
xD.

**Comment by BlackCoyote** [comment]
If you're having trouble controlling your NPC's, please consider calling this guy; http://i.gyazo.com/2aa4c9cd16941e780944d770a018a7ba.png
