### ISSUE TITLE
empty variable when editing paths with /npc path 

### ISSUE THREAD

**Issue by Tyloon1e** [CitizensDev/Citizens2#2400]
The output of command `/version` on my server is: **This server is running Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2190)**

![image](https://user-images.githubusercontent.com/52511724/101063746-78ea0780-3593-11eb-93b8-7ad892147f1b.png)

**Comment by fullwall** [comment]
Delete the lang/ folder in plugins/Citizens
