### ISSUE TITLE
Paper 1.16.3 paper support

### ISSUE THREAD

**Issue by Ando022** [CitizensDev/Citizens2#2402]
Hello i need to know if there is a version that supports 1.16.3 on paper or if i will not ever be able to use this plugin after purchasing despite the fact it says working on 1.16

**Comment by DoctorMacc** [comment]
It is highly recommended that you update to 1.16.4.

That being said, if you absolutely cannot update, https://ci.citizensnpcs.co/job/Citizens2/2158/ is the last 1.16.3 build. Do not expect support for it.

**Comment by mcmonkey4eva** [comment]
You MUST update to 1.16.4.

.3 is entirely unsupported.

Also, Citizens is free, as it says on the top of the spigot readme:
![img](https://i.alexgoodwin.media/i/real_use/6054b5.png)

You can download latest builds from https://ci.citizensnpcs.co/job/Citizens2/
