### ISSUE TITLE
Citizens was detected, but is not enabled! Fix Citizens to allow linkage.

### ISSUE THREAD

**Issue by raygungames** [CitizensDev/Citizens2#2403]
The output of command `/version` on my server is: 1.16.3
The output of command `/version citizens` on my server is: (unkown command)

**Comment by BehrRiley** [comment]
Update your server to the latest sub-version, 1.16.4, and the latest Citizens build

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.

Latest Paper builds are at https://papermc.io/downloads.
