### ISSUE TITLE
Server hang: "java.io.IOException: Cannot allocate memory"

### ISSUE THREAD

**Issue by MaxIsV** [CitizensDev/Citizens2#2405]
Hello, recently my server has crashed several times due to one bug that mentions the Citizens plugin. That is, the server does not stop and does not reboot, but hangs and stops responding to commands. And I have to forcibly "kill" him.
I have no idea what this is connected with.

Server log (error): https://pastebin.com/wqFA2PZp
Config.yml: https://pastebin.com/xCEhZcbS

The output of command `/version` on my server is: **git-Paper-1618 (MC: 1.12.2)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2176)**

**Comment by mcmonkey4eva** [comment]
Your server's data drive is either out of space or in some way inoperable.
That's not caused directly by Citizens itself, that's caused by the IO operation of trying to save the Citizens saves file (which, I note, is rarely more than a single megabyte even for heavy users).

**Comment by MaxIsV** [comment]
> Your server's data drive is either out of space or in some way inoperable.
> That's not caused directly by Citizens itself, that's caused by the IO operation of trying to save the Citizens saves file (which, I note, is rarely more than a single megabyte even for heavy users).

@mcmonkey4eva My hosting support replied that at the moment there are no problems with the disk, and if there were any, this would affect other plugins too, but the error only occurs with Citizens. Maybe you can try to investigate this, please?

**Comment by mcmonkey4eva** [comment]
This is not anything on Citizens' end, I guarantee. That is some form of drive or filesystem error. Your hosting support are not the ones that would know about that. YOU, or whoever the server owner is, should know that. And if you don't, contact a Linux support team somewhere.
