### ISSUE TITLE
Npc's keep resetting

### ISSUE THREAD

**Issue by Joeythemlgprogamer11** [CitizensDev/Citizens2#2407]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

Our issue on our server is that sometimes the npc's where you right click to get guides and such keep resetting, we fixed this a few days ago then the bug came back 

Version citizens: 2.0.27 snapshot build 2170

Version: paper spigot  1.16.4 A0.1 snapsho

We havent changed the config at all so we dont know why its doing this

**Comment by BehrRiley** [comment]
You are 21 Citizens versions behind and you did not specify your server version.

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.

Latest Paper builds are at https://papermc.io/downloads. 

If the problem persists after updating, please instead paste a startup log.

**Comment by Joeythemlgprogamer11** [comment]
Heya so we updated to the most recent update and this sadly is still happening, if needed il give you the config, could it be an issue with having too many at one point?

**Comment by mcmonkey4eva** [comment]
- Please pastebin your full latest server log (`logs/latest.log`)
- Please explain better what exactly you mean by "resetting"
- Consider also asking for help on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel

**Comment by Joeythemlgprogamer11** [comment]
Alrighto il ask the admins to give me the lastest server log, when i say reset what i mean is that npcs will have working command when right clicking but then after a while the right click doesent work for anyone
