### ISSUE TITLE
Server crash Navigator while in cave

### ISSUE THREAD

**Issue by Dreamtrailtv** [CitizensDev/Citizens2#2410]
I spawned a parrot while I was in a cave.
Then I gave the parrot a location with the navigator. 
After that this bug occurred.

The output of command `/version` on my server is: This server is running Paper version git-Paper-262 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2197)

https://paste.timo.cloud/nihobarowo.sql Log and config

**Comment by BehrRiley** [comment]
You're 74 paper versions behind, you'll want to update.

Additionally, you did not post a log, you instead posted output from paper that indicates at the bottom:
`DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH`

Latest Paper builds are at https://papermc.io/downloads.

**Comment by Dreamtrailtv** [comment]
Now is my Version is: This server is running Paper version git-Paper-336 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

And the Log: https://paste.timo.cloud/faqonefapo.sql

**Comment by mcmonkey4eva** [comment]
That's not a bug, that's overload, which inevitably happens when you gave too-complex or impossible pathfinding tasks. You might be able to improve things by turning `/npc pathopt --use-new-finder` to false or true... but also you should probably just keep flying paths to a minimum regardless
