### ISSUE TITLE
NPCRegistry#getById() returns null

### ISSUE THREAD

**Issue by zManuu** [CitizensDev/Citizens2#2411]
So I have a npc with the id 49 on the server, but when using `NPCRegistry#getById(49)`, the method returns null. I tried to loop through all the NPCRegistrys, but it still returns null. Does anyone know what I did wrong?

**Comment by mcmonkey4eva** [comment]
Need a lot more information, including... the rest of the relevant code, saves file, etc.
Though, you should probably just ask for help on the Discord @ https://discord.gg/Q6pZGSR in the Citizens channel.
