### ISSUE TITLE
lagging when click on a npc with cmd

### ISSUE THREAD

**Issue by bighead0901** [CitizensDev/Citizens2#2413]
Please include:
- A detailed description of your issue or feature request
when user clicks on a npc with cmd(opening deluxemenu), the whole server lagged with no console error

- Link to server log & Citizens config (using e.g. pastebin.com)
https://pastebin.com/qgaXtByg

- **Spigot and Citizens versions!** Use in-game commands "/version" and "/version citizens" and screenshot or copy/paste the EXACT output of BOTH commands!
![image](https://user-images.githubusercontent.com/11792574/102749298-bd9cdd80-439e-11eb-87c0-8fd133cdd4da.png)

- FOR LAG RELATED ISSUES: please include server specs, number of NPCs, saves.yml and the output of a profiler like Spark (NOT just Spigot timings, though that can be included as well)
Using amd 3700x, 16GB ram, SSD and 4 GB ram is allocated to this test server 
Saves.yml: https://pastebin.com/6cU8TTFr
number of npc: 40
https://spark.lucko.me/#2xgwglV8J3
https://timings.spigotmc.org/?url=ezumitibuv

**Comment by fullwall** [comment]
Not sure why but maybe your permissions plugin is lagging you? The server is slowing down when setting operator on the player.

**Comment by mcmonkey4eva** [comment]
Ideally don't use the `-o` option, and instead execute as-server with the player name in the command, as explained at https://wiki.citizensnpcs.co/NPC_Commands
That will avoid the permissions-manipulation issues that tend to arise
