### ISSUE TITLE
[IDEA] NPC drops ?

### ISSUE THREAD

**Issue by ZukiLTU** [CitizensDev/Citizens2#2414]
The output of command `/version` on my server is: **(1.16.4)**
The output of command `/version citizens` on my server is: **(2.0.27)**

Hello, I have a suggestion : allow NPCS to drop items when they are killed from their inventory.
They could be configured using commands for example:

Example : /npc addloot minecraft:log 10 (10 equals 10%)
/npc viewloots
/npc delloot 
/npc delallloots

Thanks, Zuki

**Comment by mcmonkey4eva** [comment]
This is already a feature of Sentinel https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md which you should be using if you have NPC combat on your server, via `/sentinel drops`
