### ISSUE TITLE
I can not add text on my server bungee cord spigot bukki paper and the npc text editor will not add text i type add and it just type add in main chat not the editor please help i run a server with peple on it every day

### ISSUE THREAD

**Issue by jackel3812** [CitizensDev/Citizens2#2415]
The output of command `/version` on my server is: **1.16.4**
The output of command `/version citizens` on my server is: **(2027=2184**

**Comment by jackel3812** [comment]
Can u please help me fix this sir  Sent from Mail for Windows 10 From: mcmonkey4evaSent: Tuesday, December 22, 2020 10:32 AMTo: CitizensDev/Citizens2Cc: jackel3812; AuthorSubject: Re: [CitizensDev/Citizens2] I can not add text on my server bungee cord spigot bukki paper and the npc text editor will not add text i type add and it just type add in main chat not the editor please help i run a server with peple on it every day (#2415) Closed #2415.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mcmonkey4eva** [comment]
Please use Discord
