### ISSUE TITLE
NPCs dissapear.. general trouble

### ISSUE THREAD

**Issue by rkclayton** [CitizensDev/Citizens2#2417]
NPCs will randomly vanish. When they vanish they are not there (not even invisible) even though the /npc spawn command thinks they are. I have to use /npc tptohere it will tell me they have successfully teleported, and they will talk but not be visible until i use /npc rename.     This is the only way i can get them to reappear. 
On top of that.. all of my NPCs are incredibly slow while following... seems when i first installed the plugin it was OK but now if i tell them to /follow they dont really show the walking graphic and they are just sloooooow.  They wander ok with /npc path it seems.  

 Citizens Config:  https://pastebin.com/WG7zyhCM

 Server log: https://pastebin.com/CxYCDTR4

/version output:
This server is running Paper version git-Paper-341 (MC:
1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-330 (MC: 1.16.4)
You are 1 version(s) behind

/version citizens output: 
Citizens version 2.0.27-SNAPSHOT (build2170)

**Comment by mcmonkey4eva** [comment]
![check](https://i.alexgoodwin.media/i/misc/81f13e.png)

You need an update https://ci.citizensnpcs.co/job/Citizens2/ 

Also to look through and fix the errors in that log
