### ISSUE TITLE
Send tablist three or four times per npcs waste network traffic

### ISSUE THREAD

**Issue by caoli5288** [CitizensDev/Citizens2#2418]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-unknown-unknown (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2203)

When a player meet an NPC, he will receive 3 tablist packets(3 add and 3 remove).
That's a lot of overhead, because it includes skin textures. 
Another problem is that citizens send a tablist when player quit, which is unnecessary.

**Comment by mcmonkey4eva** [comment]
This isn't an issue post of any form, that version is broken nonsense, the network usage of spawn packets is very minor on the scale of minecraft (ever seen how big a chunk packet is?) and there's not really going to be changes to how spawn packets work regardless.
