### ISSUE TITLE
Citizens causing lots of lag

### ISSUE THREAD

**Issue by KickSquareMC** [CitizensDev/Citizens2#2419]
Hi. I did a timings report. Out of 80+ plugins, citizens is taking `total(24.48% 13.381s, 1.12% of tick)`. I do have lots of NPC's, and I understand how NPC's can be laggy. Are there any optimizations I can do though? For example, does it help to turn off the "look at player" option?

**Comment by paryl** [comment]
I have quite a few as well, and yes, it helped to turn off look. It seems when you reach a certain threshold, the plugin is constantly cycling through every NPC and searching their surroundings for something to look at. I disabled look on most of mine (I have a custom NPC market with dozens of vendors) and that seemed to solve things.

**Comment by KickSquareMC** [comment]
I have one of those too haha. Thanks for the tip
