### ISSUE TITLE
Restarting server or running /npc reload breaks npc skins

### ISSUE THREAD

**Issue by Zoon20X** [CitizensDev/Citizens2#2420]
running latest version on jenkins and when i use a command like create or /npc skin the skin will appear, (i havent tested leaving and rejoining) but when i restart the server or run a /citizens reload it will completely break the skins, i downgraded to a earlier version for 1.16.4 and the issue is completely fixed which imo it has nothing to do with the config then, the config is generated from the latest and run on the older version (version tested and it worked Citizens-2.0.27-b2208)

npc saves: https://hastebin.com/ukuquliqel.yaml 

![image](https://user-images.githubusercontent.com/47308184/103259772-8a81cc00-49e6-11eb-94cd-86fe6c6c19ec.png)

**Comment by mcmonkey4eva** [comment]
Please use [Pastebin](https://pastebin.com/) not hastebin

And: please pastebin a server log (`logs/latest.log`)

**Comment by Zoon20X** [comment]
> Please use [Pastebin](https://pastebin.com/) not hastebin
> 
> And: please pastebin a server log (`logs/latest.log`)

Saves file: https://pastebin.com/a79PXd73
Server log: https://pastebin.com/GgxvZbBZ

**Comment by mcmonkey4eva** [comment]
Get rid CitizensCMD, use https://wiki.citizensnpcs.co/NPC_Commands

**Comment by mcmonkey4eva** [comment]
Might be fixed by https://github.com/CitizensDev/Citizens2/commit/0b1a8cc369e548384b958263b705338ef490ef0c in build 2213

**Comment by Zoon20X** [comment]
> Might be fixed by [0b1a8cc](https://github.com/CitizensDev/Citizens2/commit/0b1a8cc369e548384b958263b705338ef490ef0c) in build 2213

works perfectly now thanks
