### ISSUE TITLE
[API HELP] NPC Meta

### ISSUE THREAD

**Issue by TrueMB** [CitizensDev/Citizens2#2423]
Hello!

I would like to save meta data on different NPCs, to ask later, if they are for my Plugin.

What i found so far is npc.data().set(String, boolean); It does work, but after the server restarts, the value gets deleted.
Is there also a way to save it? Or do I have to set it on a different way?

Of course I could just set the meta, after the spawn of the npc again. But it would be awesome, to know the way, if there is one.

Thanks in advance!

**Comment by mcmonkey4eva** [comment]
Make a Trait. You can persist any data with your trait, and also of course use hasTrait to differentiate relevant NPCs.
See also the API wiki page which explains this and gives example code: https://wiki.citizensnpcs.co/API
