### ISSUE TITLE
Player crash when relaod

### ISSUE THREAD

**Issue by zelytra** [CitizensDev/Citizens2#2424]
I'm using Bungeecord & Citizens plugin. After creating a new NPC and then reload all player connected are kicked with this error :
IllegalArgumentException : Team CIT-d464cb8bb6f4 already exists in this scoreboard @com.googls.common.base.Precondition:191

With some research i see that bungee don't clear the scoreboard on reload i don't know if it help but just saying.

Config yml : https://paste.md-5.net/aducimapet.coffeescript
Spigot version : git-Spigot-ff439d1-24c79a1 (MC:1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Citizens version : 2.0.27-SNAPSHOT (build 2214)

**Comment by mcmonkey4eva** [comment]
Never reload. If you change plugins on your server, do a full restart. If you're just doing in-game commands, you don't need any form of reloading anyway.

If you can replicate any issues WITHOUT reloading, please pastebin your server log (`logs/latest.log`)
