### ISSUE TITLE
-r and -l tags not working

### ISSUE THREAD

**Issue by Teric7** [CitizensDev/Citizens2#2426]
when I type "/npc cmdadd -r cc preview vote"

It runs the command with both click and when I add

"/npc cmdadd -l cc open vote"

Sometimes it runs that, sometimes it does nothing and sometimes it runs the right click command

server IP: play.minesmash.net

Citizens Version: 2.0.27-SNAPSHOT (build 2176)
Spigot Version: Paper Version git-Paper-355 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
"Cmdadd" isn't a valid command.
Refer to the documentation at https://wiki.citizensnpcs.co/NPC_Commands
If you're running any Citizens-related plugins that claim to add their own click-command system, remove them.

Also update your Citizens build, that's a fair bit behind https://ci.citizensnpcs.co/job/Citizens2/

Also be aware that left-clicking an NPC is effectively combat, you're punching the NPC in the face, so all combat-related topics (such as PvP-blocking plugins or settings) can get in the way.
