### ISSUE TITLE
Right-Clicking on NPCs causes player crash.

### ISSUE THREAD

**Issue by Nuvolotto** [CitizensDev/Citizens2#2427]
**The output of command `/version` on my server is:** _This server is running CraftBukkit version 1.8.8_R0.1-SNAPSHOT (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
Unknown version, custom build?_
**The output of command `/version citizens` on my server is:** _Citizens version 2.0.27-SNAPSHOT (build 2218)
Website: http://www.citizensnpcs.co
Author: fullwall_

**yml files:**

[config.yml](https://pastebin.com/cmd950Ei)
[saves.yml](https://pastebin.com/ARUscGHQ)

Hello, I have recently been experiencing an issue in which, if you right click any NPC, it will kick you from the server with the following error.
Here's a picture.
[Crash Error](https://gyazo.com/dca3281304b649bc5b901fdb45fb87c9)
Here's the Pastebin link.
[Crash Error Pastebin](https://pastebin.com/6PqTKFwM)

All of the plugins [here](https://gyazo.com/e6dc7c334a59bff05bb5be8305c7c232).

**Useful Informations:**

- I allocated 512 MB of ram to the server since it is supposed to be only a Lobby.
- The server is part of a BungeeCord.
- I am hosting the Bungee, Lobby, and Main server on my old PC (I turned it into a server). 
It never gave any sort of problem and I find it very unlikely it is the computer's fault since everything apart from this works as intended.
- I allocated 256 MB of ram to the bungee.
- The last error linked only pops up in the Bungee terminal.

I have tried re-installing the plugin removing any previous folder but nothing worked.
I never did /reload.
I honestly don't know what might cause this issue and, I am fully aware that 1.8 is no longer supported, but I really need some help...
(I have attached a video of the issue as well. Sorry for the music in the background.)

https://user-images.githubusercontent.com/69163624/103873736-8b92b780-50d0-11eb-9da9-de83c467a0ea.mp4

**Comment by mcmonkey4eva** [comment]
- This error is almost certainly an external problem
- Your server logs that the issue template asks for are suspiciously missing
- We can't really support 1.8 either way https://wiki.citizensnpcs.co/Minecraft_1.8
