### ISSUE TITLE
Shared cooldown for all commands on NPC

### ISSUE THREAD

**Issue by christaylor201** [CitizensDev/Citizens2#2428]
Currently, we have several NPCs with commands in linear mode set up as follows:
* summon a boss,
* send a message to the player,
* play a sound.

Each of these commands has the same 24-hour cooldown. This works perfectly fine, however it has one little issue – the cooldown message is sent 3 times.

That's why I propose something like a shared cooldown. Basically, all commands would share the same cooldown, so it would send only 1 cooldown message, not multiple.

I think this would be useful for our case but also for other people, who might want to achieve something similar.

**Comment by mcmonkey4eva** [comment]
I think this is technically best listed as a bug report, of multiple cooldown messages showing at once with that setup.

Though the idea of a shared cooldown might also be a feature to add.

Either way, definitely worth noting here that if you want more advanced scripted actions attached to an NPC, you should... well, use a script lol. [Denizen](https://guide.denizenscript.com/index.html) is available as a scripting engine that directly integrates with Citizens.

**Comment by christaylor201** [comment]
You're right – I wasn't sure if I should label it as a bug or not, I considered it more as a feature.

Anyway, thank you for the tip on Denizen, we might try it!

**Comment by fullwall** [comment]
Fixed (although it won't work perfectly in the case of long delay commands)

**Comment by christaylor201** [comment]
Nevertheless, the issue was fixed in our case, thank you very much!
