### ISSUE TITLE
Unknown Issue With all NPC Commands

### ISSUE THREAD

**Issue by DarkCrimsonFury** [CitizensDev/Citizens2#243]
I'm unable to use any commands in Citizens2 or Sentries, and I use 2.0.14 Alpha 1, and 1.8.4 Build 2. Typing the command does nothing, and I don't believe there are any error logs and nothing was said in the console.

If you need some more information, like a pastebin with my Citizens2 files, or if the Console ends up responding, I'd be happy to help!

I really need these NPC's, they're like the whole point of my server. People join and ask "What do I do?"

Good work on this plugin guys, and hope you can tell me what I'm doing wrong (I mess up A LOT!) so I can get my server back up and running!

**Comment by mcmonkey4eva** [comment]
Post a full startup log (to pastebin).

**Comment by DarkCrimsonFury** [comment]
http://pastebin.com/J9Y3yPYb

Included main INFO at the top  of the Pastebin.

**Comment by mcmonkey4eva** [comment]
You are running the wrong version of Citizens.

Acquire the correct version here: http://wiki.citizensnpcs.co/Versions

**Comment by DarkCrimsonFury** [comment]
Thank you, I thought I had the wrong version but didn't want to mess anything up. :P

**Comment by DarkCrimsonFury** [comment]
That's weird... I put the right plugin in, and now my server won't start up.

Sorry about all the other junk, my server is really messed up right now. xD.

http://pastebin.com/D6ZBRzVT

If you know what's wrong, I would be super happy if you could help!

Thanks!

**Comment by mcmonkey4eva** [comment]
You downloaded the wrong version again. Look more closely at the version list.

**Comment by DarkCrimsonFury** [comment]
Should I download the one for 1.7.9, or 1.7.10?

I'm so sorry I've been taking so much of your time!

If you don't want to respond to this, I'll figure it out eventually. :P

Thanks for your help!

**Comment by mcmonkey4eva** [comment]
You, earlier: "`I use a build of Spigot that is primarily 1.7.10, but supports 1.8 Clients.`"
Get the build for that version.

**Comment by DarkCrimsonFury** [comment]
When I got the version for 1.7.10, it didn't work, and then when I got the version for 1.7.9, it also didn't work.

I'm not that sure what to do anymore. D:

Should I try to get a new version of Spigot?

17.02 08:00:21 [Server] INFO Disabling Citizens v2.0.13-SNAPSHOT (build 1142)
17.02 08:00:21 [Server] ERROR v2.0.13-SNAPSHOT (build 1142) is not compatible with Minecraft v1.7.10 - try upgrading or downgrading Citizens. Disabling.
17.02 08:00:21 [Server] INFO Enabling Citizens v2.0.13-SNAPSHOT (build 1142)

17.02 08:00:22 [Server] INFO v1.8.2 disabled.
17.02 08:00:22 [Server] INFO Disabling Sentry v1.8.2
17.02 08:00:22 [Server] ERROR Citizens 2.0 not found or not enabled
17.02 08:00:22 [Server] INFO Enabling Sentry v1.8.2

**Comment by GoldenSpencer** [comment]
Same I Have The 1.7.10 Snapshot And It Just Keeps Crashing My Server :/

**Comment by calico-kid** [comment]
"I use a build of Spigot that is primarily 1.7.10, but supports 1.8 Clients." <--- that is called a 1.8 protocall hack... so you need the 1.8 protocall hack citizens... not the 1.7.10..

**Comment by DarkCrimsonFury** [comment]
Okay I got the protocol, but it still isn't working. Does this mean I have to use a different build for sentries, or convert my files?

Sorry, I'm really not sure why it's still not working. :P

**Comment by DarkCrimsonFury** [comment]
Protocall Hack*

**Comment by calico-kid** [comment]
check your version of sentry make sure it matches

**Comment by DarkCrimsonFury** [comment]
I got the 1.8 Version of Sentry since there is no Protocall Hack, and it still refuses to work, including all commands relating to this plugin.

**Comment by mcmonkey4eva** [comment]
Omf.

1.8 protocol hack version of Citizens, 1.7.10 version of Sentry. If it doesn't work in that configuration, post a fresh startup log.

**Comment by DarkCrimsonFury** [comment]
http://pastebin.com/j2XiDEHR

Here ya go.

**Comment by mcmonkey4eva** [comment]
That's the 1.7.9 version of Citizens, not the 1.8 protocol hack version.
