### ISSUE TITLE
Crash report & errors

### ISSUE THREAD

**Issue by LuluxClient** [CitizensDev/Citizens2#2430]
- Server keeps crashing because of a citizen error spamming my console while I'm claiming land with SaberFaction.
Error : https://pastebin.com/ZFkqSecw
crash report : https://pastebin.com/DPybv3pY

The output of command `/version` on my server is: **https://gyazo.com/05ce60987e618a09f2e0dbd603b70aca**
The output of command `/version citizens` on my server is: **https://gyazo.com/a56f79df06505a5ab94150c7570214fb**

**Comment by mcmonkey4eva** [comment]
This is entirely a 1.8 problem https://wiki.citizensnpcs.co/Minecraft_1.8
