### ISSUE TITLE
Hoglin to Zoglin Problem

### ISSUE THREAD

**Issue by oneboyreal** [CitizensDev/Citizens2#2431]
![image](https://user-images.githubusercontent.com/63717382/104036997-6a1af400-51d4-11eb-9002-b2331917632b.png)
I create a Hoglin NPC with the command / npc create Hoglin --type hoglin

As soon as I make it vulnerable, he starts the transformation into a Zoglin. Can I fix this problem?

**Comment by mcmonkey4eva** [comment]
I've replicated this myself, it's as easy as `/npc create bob --type hoglin` + `/npc vulnerable` + wait a few seconds, it'll start shaking and then "transform" (despawn the NPC and spawn a zoglin mob). As it's a new mob type doing a new thing, this is likely just a simple matter of finding and disabling the relevant NMS methods.

**Comment by fullwall** [comment]
This is currently explicitly tied to protected much like other mobs.

**Comment by oneboyreal** [comment]
> This is currently explicitly tied to protected much like other mobs.

Will there be a solution?

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/CitizensDev/Citizens2/commit/7023ac4c54dac1a0e2d62b071130e9b9cc2fcade for Citizens build 2219+ from https://ci.citizensnpcs.co/job/Citizens2/
