### ISSUE TITLE
Plugin is disable

### ISSUE THREAD

**Issue by lobiQ** [CitizensDev/Citizens2#2433]
I need help. Plugin is disable i dont know why.
![version](https://user-images.githubusercontent.com/77249278/104186354-91f99a00-5416-11eb-9494-64441bb2a89f.jpg)
![version citizens](https://user-images.githubusercontent.com/77249278/104186743-29f78380-5417-11eb-92d9-f9240d84bc47.jpg)

**Comment by mcmonkey4eva** [comment]
You need Spigot or Paper, not Bukkit.
And 1.16.4, not .3
