### ISSUE TITLE
/npc create name --at doest seem to work 

### ISSUE THREAD

**Issue by Rasmusbb** [CitizensDev/Citizens2#2435]
- the problem is the commnad /npc create name --at 58 20 200 it will never pass no matter what cords it gets its always the same message over and over agian "Spawn location could not be parsed or was not found" im not sure if its me doing the command wrong or what there is wrong but couldt find anywere to check and the command just doest seem to work at all 

The output of command `/version` on my server is: this server is running Paper version git-paper-406 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT) Your are running the latest version
The output of command `/version citizens` on my server is:  Citizens version 2.0.27-snapshot (build 2217)

**Comment by mcmonkey4eva** [comment]
`58,20,200,world`

**Comment by Rasmusbb** [comment]
;)
