### ISSUE TITLE
Dont have permissions for any "/npc" commands even tho i am OP and have *

### ISSUE THREAD

**Issue by Playge** [CitizensDev/Citizens2#2436]
The output of command `/npc` on my server is: the basic "you dont have permission, contact an admin" and so on
The output of command `/version citizens` on my server is:  2.027-SNAPSHOT (build 2217)

**Comment by mcmonkey4eva** [comment]
That's most likely an issue with whatever permission or protection plugin you have.

If you can't figure out the source of the problem on your own, please pastebin your `logs/latest.log` or ask on Discord https://discord.gg/Q6pZGSR

**Comment by Playge** [comment]
[latest.log](https://github.com/CitizensDev/Citizens2/files/5811095/latest.log)

**Comment by mcmonkey4eva** [comment]
That log is filled to the brim with error messages.

NEVER use `/reload`. It WILL break things.
Remove PluginManager. It WILL break things.
ALWAYS do a FULL server restart when you change plugins around.

Additionally, after safely restarting your server, I'd strongly recommend looking through your own logs for any error messages and getting them resolved.

**Comment by Playge** [comment]
okay thanks i will do that now
