### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by tptuaasn** [CitizensDev/Citizens2#2438]
![image](https://user-images.githubusercontent.com/74866833/104722484-75d06280-5760-11eb-81b8-7a54826c202e.png)

The output of command `/version` on my server is: **(1.12.2)**
The output of command `/version citizens` on my server is: **(2.0.27-b2221)**

**Comment by mcmonkey4eva** [comment]
There is no issue in this issue.
Just a screenshot of a console running Java 11 as it does Java 11 things. (Use Java 8 to avoid Java 11 dumbness)
