### ISSUE TITLE
Won't let me use Citizens on MY server.

### ISSUE THREAD

**Issue by TheRealAudio** [CitizensDev/Citizens2#2439]
I just purchased the new citizens plugin and while trying to use it on my server it states. "I do not have authorization to use that command please contact the server administrators if you believe this to be false." 
With that being said I am opped and the server owner have access to console and everything 
The output of command `/version` on my server is: **(git-spigot-1.16.4-snapshot)**
The output of command `/version citizens` on my server is: **(2.0.27-snapshot)**

**Comment by TheRealAudio** [comment]
I did something wrong I apologize

**Comment by mcmonkey4eva** [comment]
Neither of those versions are the actual output of those version commands.

This seems like a basic permissions configuration issue, which... refer to the documentation of your preferred permissions plugin.

If you can't resolve it on your own, please pastebin your full `logs/latest.log` file and/or ask for help on Discord https://discord.gg/Q6pZGSR

**Comment by theCarso** [comment]
To the original poster, I found that a temporary fix to this issue was removing '*' permission from my user. I don't know why this fixed it, but it did.

Citizens 2.0.25 didn't have this issue but 2.0.27 did, and I'm currently running LuckPerms v5.2.76.

**Comment by mcmonkey4eva** [comment]
That sounds a lot more likely to be related to luckperms changes than to anything in Citizens
