### ISSUE TITLE
Lots of issues with dead NPC

### ISSUE THREAD

**Issue by GomaTerzu** [CitizensDev/Citizens2#244]
Hey fullwall,

first of all I am using the latest Citizens2 build and the latest Denizen and sentry build. Debug doesn't say anthing.

My Denizen config is

Traits:
  Health:
    Enabled: false
    Respawn:
      Enabled: true
      Delay: 1s
    Animated death:
      Enabled: false

My Citizens Config is:

  player:
    remove-from-list: true

Now i have several problems atm

- Sometime I create NPC that are vulnerable, kill them and they become invisible on respawn. This is not something i can reproduce, but it seems to happen a lot.

- Then i have another problerm. To reproduce my problem you need to create a NPC and make it vulnerable. Make it respawn very fast (1s). No need to give it the sentry trait. Now kill the NPC lots of times. Then I fly away like 10 chunks and come back. Now you see every single version of that NPC you killed again, see screenshot: I have the feeling it affects gameplay, because the more dead bodys are lying around, the less i can hit the living version. It becomes almost invincible at some point. 

http://puu.sh/g16Nc/ef6dab3534.png
http://oi57.tinypic.com/2latvyr.jpg

Even other players can see all the dead bodies again.

- The third problem is not good too. Once i delete every single npc, save citizens and denizen, reload citizens, player are still able to select the removed npc at their last position:

http://puu.sh/g16CI/e4d2f15c47.png
http://puu.sh/g16y0/ec3133c95d.png

**Comment by GomaTerzu** [comment]
Oh btw i figured out i have these problems only with Player-Type NPC, so when i change the type to like --type Zombie  nothing of the problems seems to happen

**Comment by mcmonkey4eva** [comment]
Sorry about largely ignoring this - what of this is still an issue?

**Comment by GomaTerzu** [comment]
Sorry, was away a while. I think most of this was already fixxed somehow. Never encountered it again in the latest builds.
