### ISSUE TITLE
Inconsistent validity checking for players in trait `lookclose`

### ISSUE THREAD

**Issue by elgbar** [CitizensDev/Citizens2#2441]
When using the trait `lookclose` what factors determine if a player is valid is not consistent between finding and invalidating players. See the table below to see the differences. An `X` marks it as checked.

| Test                              | findNewTarget | hasInvalidTarget | Note                                                                                            |
| :-------------------------------- | :-----------: | :--------------: | :---------------------------------------------------------------------------------------------- |
| If entity is a NPC                |       X       |                  | This should not be checked in invalidate, included for completeness                             |
| Same world                        |       X       |        X         |                                                                                                 |
| Players gamemode is not spectator |       X       |                  |                                                                                                 |
| Player has INVISIBILITY potion    |       X       |                  |                                                                                                 |
| Player is vanished via plugin     |       X       |                  |                                                                                                 |
| Distance between player and NPC   |       ~       |        ~         | See #2440                                                                                       |
| Player is online                  |               |        X         | Player will be online when retrieved via an AABB call, so no real need when finding new targets |
| Player is valid                   |               |                  | Should be done in `hasInvalidTarget` to prevent npc not looking at a stale player object        |

As can be seen the npc will turn to look at a vanished/spectator/invisible player if they become so while being the target the NPC.

The output of command `/version` on my server is: `Paper version git-Paper-436 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
The output of command `/version citizens` on my server is: `Citizens version 2.0.27-SNAPSHOT (build 2226)`

**Comment by mcmonkey4eva** [comment]
Please only create one issue post per issue
