### ISSUE TITLE
Add event for player look close target change

### ISSUE THREAD

**Issue by elgbar** [CitizensDev/Citizens2#2444]
Okay so this is what all my issues have been building towards. I want an event fired when the target of `lookclose` changes. 

Here is an example event 
```java
import net.citizensnpcs.api.event.NPCTraitEvent;
import net.citizensnpcs.api.npc.NPC;
import org.bukkit.entity.Player;
import org.bukkit.event.HandlerList;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * @author Elg
 */
public class NPCLookCloseChangeEvent extends NPCTraitEvent {

  public NPCLookCloseChangeEvent(@NotNull NPC npc, @NotNull LookClose trait, @Nullable Player newTarget, @Nullable Player oldTarget) {
    super(npc, trait);
    this.newTarget = newTarget;
    this.oldTarget = oldTarget;
  }

  @Nullable
  private final Player newTarget;
  @Nullable
  private final Player oldTarget;

  @NotNull
  private static final HandlerList handlerList = new HandlerList();

  @Nullable
  public final Player getNewTarget() {
    return newTarget;
  }

  @Nullable
  public final Player getOldTarget() {
    return oldTarget;
  }

  @NotNull
   public LookClose getTrait() {
     return (LookClose) super.getTrait();
   }

  @Override
  @NotNull
  public HandlerList getHandlers() {
    return handlerList;
  }
  @NotNull
  public static HandlerList getHandlerList() {
    return handlerList;
  }
}
```

This event should be called 

* in `onDespawn()` as `new NPCLookCloseChangeEvent (npc, this, null, lookingAt).callEvent();`
* in `hasInvalidTarget()` as `new NPCLookCloseChangeEvent (npc, this, null, lookingAt).callEvent();`
* in `findNewTarget()` (see [issue #2442 comment](https://github.com/CitizensDev/Citizens2/issues/2442#issuecomment-763569535))
  ```java
    Player closest = null;
    for (Entity entity : ...) {
      //replace the current `lookingAt` with `closest`
    }

    if (closest != lookingAt) {
      new NPCLookCloseChangeTarget(npc, this, closest, lookingAt).callEvent();
      lookingAt = closest;
    }
  ```

The output of command /version on my server is: This server is running Paper version git-Paper-436 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
The output of command /version citizens on my server is: Citizens version 2.0.27-SNAPSHOT (build 2229)

**Comment by elgbar** [comment]
@fullwall In your implementation you can change who is next, but when invalidating `lookingAt` in `onDespawn()` and `hasInvalidTarget()` probably shouldn't honor `NPCLookCloseChangeTargetEvent#getNewTarget()`. As it invalidates the checks done prior. In my opinion it should be read-only.

**Comment by mcmonkey4eva** [comment]
The above comment was fixed by https://github.com/CitizensDev/Citizens2/commit/80187501d012acbf8fd6b3a5f117b0c32ffdeb7a which simply ignores any new target set in the event that isn't valid.
