### ISSUE TITLE
/npc is not working

### ISSUE THREAD

**Issue by DaRealLevenGamer** [CitizensDev/Citizens2#2448]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
![npcerror](https://user-images.githubusercontent.com/43507866/105224439-2fe21880-5b2b-11eb-80b3-c907effb63e2.jpg)

The version of my server is 1.16.4 and when I got the new version of citizens and installed it it gave me all this errors that I dont understand

**Comment by elgbar** [comment]
You have an old version `v2.0.24-snapshot` the newest is `v2.0.27-snapshot`. Download it here https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/
