### ISSUE TITLE
Can't get C2 working with spigot/bukkit 1.7.10 and 1.8

### ISSUE THREAD

**Issue by Golicraft** [CitizensDev/Citizens2#245]
If thw owner of this plugin seen this the plugin dont work for spigot/bukkit 1.7.10 and 1.8 with the newest build. 

Can you pleas fix it and send a link to the newest download.

Thank You

**Comment by mcmonkey4eva** [comment]
It works fine, the download links are all here: http://wiki.citizensnpcs.co/Versions

**Comment by Golicraft** [comment]
ok thank you. but i have a problem. When i create ncp i can se them in the tab and i try to disable it in the config?

**Comment by mcmonkey4eva** [comment]
They only appear in the tab list for a second before disappearing. This is due to a Mojang bug that we have no control over.

**Comment by Golicraft** [comment]
o... so i can't fix

**Comment by Golicraft** [comment]
but if i use just 1.7.10?

**Comment by mcmonkey4eva** [comment]
I think 1.7.10 didn't have much trouble at all with the tablist... but neither does 1.8. Just... ignore it, it's not an issue and it doesn't last more than a second.

**Comment by Golicraft** [comment]
so you think that if I wait a few days it will go over and not displayed in the tab more?

**Comment by mcmonkey4eva** [comment]
wait LITERALLY LESS THAN ONE SECOND and it's gone.

**Comment by Golicraft** [comment]
not for me....

**Comment by Golicraft** [comment]
can you go on my server and see it?

**Comment by mcmonkey4eva** [comment]
Then update to latest 1.8 Spigot/Citizens2.

**Comment by mcmonkey4eva** [comment]
And I mean full 1.8, not the protocol hack.

**Comment by Golicraft** [comment]
when i type /pl citizenz is red...

**Comment by mcmonkey4eva** [comment]
Update, then if it still does not work, post a startup log.

**Comment by Golicraft** [comment]
ok
thank you

**Comment by Golicraft** [comment]
here is the biiiiiiiig console:


19.02 00:02:59 [Server] INFO MOD: MOD : ImZozed_ »
19.02 00:02:51 [Multicraft] ImZozed_ ran command Message of the Day
19.02 00:02:51 [Connect] User ImZozed_, IP 85.166.174.193
19.02 00:02:51 [Server] INFO Teleporting...
19.02 00:02:51 [Server] INFO 29 regions loaded for 'hub'
19.02 00:02:51 [Server] INFO Unknown command. Type "/help" for help.
19.02 00:02:51 [Server] INFO UUID of player ImZozed_ is 5921af63-9852-479b-a961-443422b0c527
19.02 00:02:41 [Server] INFO 0 regions loaded for 'sg2'
19.02 00:02:25 [Server] WARN Update at: http://dev.bukkit.org/server-mods/vault
19.02 00:02:25 [Server] WARN Stable Version: 1.5.2 is out! You are still running version: 1.5.0
19.02 00:02:25 [Server] INFO *********************************
19.02 00:02:25 [Server] INFO No new version available
19.02 00:02:25 [Server] INFO Current Build: #211
19.02 00:02:25 [Server] INFO Stable Build: #211
19.02 00:02:25 [Server] INFO ***** 1vs1 Version Checker ***** 
19.02 00:02:25 [Server] INFO A newer version of survivalgames is available. ( SurvivalGames - Version Beta 1.9.4) You can download it here: http://dev.bukkit.org/bukkit-plugins/ultimatesurvivalgames/ You're using SurvivalGames - Version Beta dev1.9.4b
19.02 00:02:25 [Server] INFO Checking for Updates ... 
19.02 00:02:25 [Server] INFO GroupManager - INFO - Bukkit Permissions Updated!
19.02 00:02:25 [Server] INFO dev.bukkit.org/bukkit-plugins/holographic-displays
19.02 00:02:25 [Server] INFO Download it on Bukkit Dev:
19.02 00:02:25 [Server] INFO Found a new version available: v2.1.4
19.02 00:02:25 [Server] Startup Done (32.149s)! For help, type "help" or "?"
19.02 00:02:24 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
19.02 00:02:24 [Server] INFO Enabling MultiWorldMoney v1.8
19.02 00:02:24 [Server] INFO enabled.
19.02 00:02:24 [Server] INFO Enabling Multiverse-Inventories v2.5-b335
19.02 00:02:24 [Server] INFO 17 - Portals(s) loaded
19.02 00:02:23 [Server] INFO - Version 2.5-b699 Enabled - By Rigby and fernferret
19.02 00:02:23 [Server] INFO Enabling Multiverse-Portals v2.5-b699
19.02 00:02:23 [Server] INFO [KitController] Registered 1 kits ...
19.02 00:02:23 [Server] INFO [ChestController] Registered 36 chest items ...
19.02 00:02:23 [Server] INFO Loaded configuration for world 'island-0'
19.02 00:02:23 [Server] INFO (island-0) Fire spread is UNRESTRICTED.
19.02 00:02:23 [Server] INFO (island-0) Lava fire is blocked.
19.02 00:02:23 [Server] INFO (island-0) Lighters are PERMITTED.
19.02 00:02:23 [Server] INFO (island-0) TNT ignition is PERMITTED.
19.02 00:02:23 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/island-0/blacklist.txt
19.02 00:02:23 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/island-0/config.yml
19.02 00:02:23 [Server] INFO Preparing spawn area for island-0, 93%
19.02 00:02:23 [Multicraft] Skipped 6 lines due to rate limit (30/s)
19.02 00:02:22 [Server] INFO Experience Merge Radius: 3.0
19.02 00:02:22 [Server] INFO Clear tick list: false
19.02 00:02:22 [Server] INFO Chunks to Grow per Tick: 650
19.02 00:02:22 [Server] INFO View Distance: 10
19.02 00:02:22 [Server] INFO Max TNT Explosions: 100
19.02 00:02:22 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
19.02 00:02:22 [Server] INFO Max Entity Collisions: 8
19.02 00:02:22 [Server] INFO Sending up to 5 chunks per packet
19.02 00:02:22 [Server] INFO Structure Info Saving: true
19.02 00:02:22 [Server] INFO Random Lighting Updates: false
19.02 00:02:22 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
19.02 00:02:22 [Server] INFO Alternative Hopper Ticking: false
19.02 00:02:22 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
19.02 00:02:22 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
19.02 00:02:22 [Server] INFO Replace Blocks: [1, 5]
19.02 00:02:22 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
19.02 00:02:22 [Server] INFO Engine Mode: 1
19.02 00:02:22 [Server] INFO Anti X-Ray: true
19.02 00:02:22 [Server] INFO Wheat Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Sapling Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Pumpkin Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Mushroom Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Melon Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Cane Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Cactus Growth Modifier: 100%
19.02 00:02:22 [Server] INFO Nerfing mobs spawned from spawners: false
19.02 00:02:22 [Server] INFO Mob Spawn Range: 4
19.02 00:02:22 [Server] INFO -------- World Settings For [island-0] --------
19.02 00:02:22 [Server] INFO Loading World & Settings - 'island-0' - Env: NORMAL - Type: NORMAL & generator: WickedSkyWars
19.02 00:02:22 [Server] INFO [SchematicController] Registered 6 schematics ...
19.02 00:02:20 [Server] INFO Enabling WickedSkyWars v1.3.1-SNAPSHOT
19.02 00:02:20 [Server] INFO Enabling HolographicDisplays v2.0.1
19.02 00:02:19 [Server] INFO Plugin enabled. WorldEdit found!
19.02 00:02:19 [Server] INFO 31 signs loaded!
19.02 00:02:19 [Server] INFO 4 lobbys loaded!
19.02 00:02:19 [Multicraft] Skipped 4 lines due to rate limit (30/s)
19.02 00:02:16 [Server] INFO 98 messages loaded!
19.02 00:02:16 [Server] INFO Successfully connected to database! Using database type SQLite!
19.02 00:02:16 [Server] INFO Enabling SurvivalGames vBeta dev1.9.4b
19.02 00:02:16 [Server] INFO MineResetLite version 0.3.6 enabled!
19.02 00:02:16 [Server] INFO Loading mine from file 'G.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'H.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'e.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'A.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'N.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'I.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'F.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'J.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'B.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'M.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'D.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'K.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'L.mine.yml'...
19.02 00:02:16 [Server] INFO Loading mine from file 'C.mine.yml'...
19.02 00:02:16 [Server] INFO Enabling MineResetLite v0.3.6
19.02 00:02:16 [Server] INFO Version 2.5-b691 (API v18) Enabled - By Rigby, fernferret, lithium3141 and main--
19.02 00:02:15 [Server] INFO 14 - World(s) loaded.
19.02 00:02:15 [Server] WARN Use '/mv remove' to remove it from the config!
19.02 00:02:15 [Server] WARN WorldManager: Can't load this world because the folder was deleted/moved: Bygge
19.02 00:02:15 [Server] WARN Use '/mv remove' to remove it from the config!

**Comment by mcmonkey4eva** [comment]
That /is/ not a complete startup log, and it doesn't look like it's even a /startup/ log. Also, for the love of space, use pastebin for big posts.

**Comment by Golicraft** [comment]
ok thank you and srry

**Comment by Golicraft** [comment]
a problem: I cough on a website and there it is such that after a certain number of words is full delete Console automatically the bottom the words and it makes it difficult and copy

**Comment by mcmonkey4eva** [comment]
Use your file access to open latest.log and copy from that

**Comment by Golicraft** [comment]
ok ty

**Comment by Golicraft** [comment]
do you mean the log file?

**Comment by mcmonkey4eva** [comment]
I said `logs/latest.log`. I don't think it could be any clearer.

**Comment by Golicraft** [comment]
whre can i found it?

**Comment by Golicraft** [comment]
found it here is my pastebin:

http://pastebin.com/uxwTzEPA

**Comment by mcmonkey4eva** [comment]
You're running a 1.7.10 server with 1.8 Citizens on it. Either upgrade your server or downgrade Citizens.

**Comment by Golicraft** [comment]
oh... but i try to use the 1.7.9 version but it doesn't work 2

**Comment by mcmonkey4eva** [comment]
YOU'RE ON A 1.7.10 SERVER, USE THE 1.7.10 VERSION.

**Comment by Golicraft** [comment]
but i use 1.7.10/1.8 spigot patch

**Comment by mcmonkey4eva** [comment]
Then use the 1.8 protocol hack version.

**Comment by Golicraft** [comment]
ok god

**Comment by Golicraft** [comment]
ok i try

**Comment by Talamar1** [comment]
You stuck a cows butt on an elephants head, it doesn't work that way.  Pick a version and use the same build for each.

**Comment by Golicraft** [comment]
ok i use the 1.7.10 for craftbukkit

**Comment by Golicraft** [comment]
i use 1.7.10 Cb but don't work 

The log: http://pastebin.com/stfE98PV

**Comment by mcmonkey4eva** [comment]
You're still using the 1.8 version of Citizens.

**Comment by Golicraft** [comment]
no?

**Comment by mcmonkey4eva** [comment]
Yes.

**Comment by Golicraft** [comment]
ok i try again...

**Comment by mcmonkey4eva** [comment]
Do remember to shut the server down while editing your plugins folder @.@

**Comment by Golicraft** [comment]
yes i do that <3

**Comment by Talamar1** [comment]
You should be using this version:
http://ci.citizensnpcs.co/job/Citizens2/1166/
You are using:
[00:08:15] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.14-SNAPSHOT (build 1195)

**Comment by Golicraft** [comment]
Hm... Here is the new log: http://pastebin.com/0tQzNpbh

**Comment by mcmonkey4eva** [comment]
You still did not change your Citizens version.

**Comment by Golicraft** [comment]
yes i do!

**Comment by Golicraft** [comment]
i download this 2.0.13 (alpha 1 for MC1.7.9)

**Comment by mcmonkey4eva** [comment]
That is the wrong flipping version once again.
And you either didn't edit the Citizens jar or didn't redownload the logs properly, cause those logs clearly show you using the 1.8 version of Citizens on a 1.7.10 server.

**Comment by Golicraft** [comment]
ok i give up!

**Comment by mcmonkey4eva** [comment]
K.

**Comment by Golicraft** [comment]
NO its not ok i have used 5 times of my life to doing this!!!!!!!!!!!!!!1

**Comment by mbax** [comment]
Then follow his instructions. :)

**Comment by Golicraft** [comment]
but i do that... but it still not work

**Comment by mcmonkey4eva** [comment]
I told you to download the version labeled `1.8 Protocol Hack.`
Your response?
`i  download this 2.0.13 (alpha 1 for MC1.7.9)`
I ... can't even...

**Comment by Golicraft** [comment]
so i must use: citizens-2.0.13-SNAPSHOT.jar

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions
On this page it says
`- 1186 1.8 Protocol Hack[2]`
with a link to
http://ci.citizensnpcs.co/job/Citizens2/1186/
use THAT build.

**Comment by Golicraft** [comment]
yes... thats work fine

**Comment by Golicraft** [comment]
but the ncp on tab is showing i think you fixing the bug in the newest 1.8 build

**Comment by korikisulda** [comment]
@Golicraft At the risk of assuming.. Is English not your first language?

**Comment by Golicraft** [comment]
yes im norwegian

**Comment by Golicraft** [comment]
i suck to talk english

**Comment by mcmonkey4eva** [comment]
We fixed that bug in the version for latest 1.8 /release/. It might exist within the 1.7.10/1.8 combo version. If you can't update your server, you're stuck with it.

**Comment by Golicraft** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO why do you don't editing it in a new version of Citienz?

**Comment by Golicraft** [comment]
with 1.7.10 and 1.8 support

**Comment by Golicraft** [comment]
can you pleas fix the bug in the 1.7.10 version 2 :( i love this plugin and can't update

**Comment by korikisulda** [comment]
Ah, ville preferanse bli skriv i Norsk? Jeg er ikke den beste men...

**Comment by mcmonkey4eva** [comment]
We can't fix it, it was due in part to a bug with Spigot.

**Comment by Golicraft** [comment]
du er også norsk?

**Comment by Golicraft** [comment]
fack spigot!

**Comment by Golicraft** [comment]
ok... then i come to delete my Citizens and cry  ;(

**Comment by korikisulda** [comment]
Mig? Nei :s Jeg kan snakke en litt, så jeg trodde det ville hjelpe en litt?

**Comment by Golicraft** [comment]
you used google oversetter haha <3

**Comment by Golicraft** [comment]
baibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibaibai

**Comment by korikisulda** [comment]
I actually didn't but whatever. I'm just bad at Norwegian.

**Comment by korikisulda** [comment]
グーグル翻訳したいですならこれを読め!御前は馬鹿な幼い子と御前の母はトカゲだ！
