### ISSUE TITLE
Inventory not updating

### ISSUE THREAD

**Issue by Nolifs** [CitizensDev/Citizens2#2451]
Hello! We are currently working on a replay plugin based on Citizens. Everything seems to work normal. Besides one issue: 
If we set equipment for a player it never updates.

Even though the response of entity.getitem says it changed. 

We can set horse armor we can give a skeleton something in his hands but a player not.... No console issue nothing we update their inventory and still the same item is visible. 

Example of the code that get's called on the right time is:
entity.getEquipment().setItemInMainHand(item);

and we do entity.updateInventory();

Am I missing something? My own inventory updates if I change it to my equipment so it should work I assume? 

Kind regards

Version of the server is : 1.16.4-R0.1-SNAPSHOT Paper
Citizens version: 2.0.27-SNAPSHOT Build 2232

**Comment by mcmonkey4eva** [comment]
Already responded to you on Discord, going to close this issue for now so we're not doubling everything.
