### ISSUE TITLE
Not Compatible With Up-to-date Minecraft/Bukkit Versions

### ISSUE THREAD

**Issue by Datcraz3gamer** [CitizensDev/Citizens2#2457]
I am making a server on 1.16 and the plugin just comes up with the issue "An Internal error occurred while trying to preform this command" whenever I try to create an npc. The server logs say the plugin is not compatible with the current version of minecraft.

Pastebin.com link: https://pastebin.com/n8nNLjb6

The output of command `/version` on my server is: **1.16.5**
The output of command `/version citizens` on my server is: **2.0.24**

**Comment by Camotoy** [comment]
You're on a rather outdated build! Download the latest from here: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
Also, the Bukkit project shut down in 2014. Don't download any plugins from their dead website, and use Spigot or Paper as a server jar, not any fake downloads of a "Bukkit" 1.16.x version. (The last real "Bukkit" jar was made for MC 1.7.10)
