### ISSUE TITLE
stuttering when using citizens 2 when passing some sort of trigger radius

### ISSUE THREAD

**Issue by Ultrajungleboy** [CitizensDev/Citizens2#2458]
when i pass a certain radius around an npc the client hangs, this is extremely annoying considering that im using a city map where interactions with citizen npcs is normal and essential :)

This can easily be reproduced by setting up an npc and finding where the client hangs around the npc, however it happens to only be when leaving the radius and not when entering?

--ive tested this on a server with no plugins and it still has the same result

--ive tried removing an npc while the server is on and it doesnt remove the radius????

--if i remove the entire citizens data folder in the plugins folder then this isnt an issue because there arent any npcs registered

--same issue on build on spigot and for latest dev build

Specs- 10gb Ram
 intel i7-8700k

Doesnt matter the amount of NPCS its per npc ive tested on other npcs in different locations

THIS is VIDEO evidence of it happening on an npc with just a simple lookclose enabled and text prompt
https://streamable.com/9p55k6

And this is the EXACT same server except ive removed the citizens plugin to prove that it is in fact citizens
https://streamable.com/xkftao

heres the spark
https://spark.lucko.me/#y6Am9bPpWs
heres the timings event -- citizens listener is huge and is definitely what is causing the stutters
--Also do not blame Easylamps for the lag I've made that plugin myself and the reason for the long tick time is because it changes Redstone lamps every time it goes from night to day, I haven't yet implemented it to where the blocks arent all set at one time which is why it appears on the timings as though it is lagging the server.
https://timings.aikar.co/?id=0c5b18e5e95b45aaa0bf37d39ff9df39

The output of command `/version` on my server is: paper 444 1.16.5
The output of command `/version citizens` on my server is: build 2247

**Comment by mcmonkey4eva** [comment]
- That is a client stutter not a server stutter, server timings aren't overly relevant
- Paper Timings is almost always somewhere between wrong and useless
- According to that spark report, your server is running EXTREMELY well. During the 109 seconds you had it running, only 9 seconds were spent calculating on the CPU, and the remaining 100 seconds were free - aka, only 8% CPU usage. This means you have a massive amount of room to expand before your server will start struggling.
- I cannot replicate this problem at all.
- You are running a modded client in that video, I'd recommend testing on a vanilla client (or non-forge optifine).
- If it doesn't happen without an NPC in the area, the problem isn't an NPC
- You have multiple plugins on your server that are known to cause client glitching, including Spartan, ClearLag, and ProtocolLib.
- Several of the plugins you are running are very likely to conflict with Citizens in problematic ways, again including Spartan. Please test on a server running ONLY Citizens.
- Being a client stutter issue, you should also test what happens around real players for comparison. For clientside effects, NPCs and players are usually mostly equivalent.

**Comment by Ultrajungleboy** [comment]
I believe I've narrowed it down to being an optifine/citizens bug
when crossing chunks on the x plane

this is the video of me in vanilla with citizens:
https://streamable.com/7fryb6

this is the video of me in optifine with citizens:
https://streamable.com/7m7ucp

this is the video of me in optifine without citizens:
https://streamable.com/f592a5

I'm going to assume that a player would act the same as you said they are mostly equivalent, but I will update you using an actual player later

**Comment by Ultrajungleboy** [comment]
The issues only persist on my computer with optifine my friend tried it out and there was no stuttering for him, ALSO there was no stuttering for my version of optifine when i didnt have citizens -- weird bug
