### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [CitizensDev/Citizens2#2460]
Details:
	This server is running Mohist version 1.12.2-185 (MC: 1.12.2)
	Citizens v2.0.27-SNAPSHOT (build 2217)
[crash-2021-01-29_18.39.13-server.txt](https://github.com/CitizensDev/Citizens2/files/5893397/crash-2021-01-29_18.39.13-server.txt)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
