### ISSUE TITLE
Npc move and console "0" spam issue

### ISSUE THREAD

**Issue by Lorias-Aegorin** [CitizensDev/Citizens2#2462]
The output of command /version on my server is:` git-Paper-391 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`
The output of command /version citizens on my server is: `v2.0.27-SNAPSHOT (build2217)`

I have several problems at once. 
First problem: When I slecte the npc with the ID 184 ingame and ask it for the ID with the "/npc id" command, I get "2" as a response. In addition, I cannot move it. Only the name of the Npc is moved. With the /citizens save and then /citizens reload command, the name tag is visible several times. Once at the actual NPC and once at the newly teleported location.

Second problem: When I look in the console, I have an intermittent "[22:06:26 INFO]: 0" spam that lasts for several minutes. The whole thing is triggered by Citizens. At least this error no longer occurs when we remove the plugin.

I have attached three pictures to illustrate the one problem and also the Config and Save file from Citizens.
![Screenshot_1](https://user-images.githubusercontent.com/62625225/106518535-4fd5ec80-64da-11eb-81ee-30c272086948.png)
![Screenshot_2](https://user-images.githubusercontent.com/62625225/106518538-51071980-64da-11eb-8f7d-aafa2796e7f4.png)
![Screenshot_3](https://user-images.githubusercontent.com/62625225/106518539-52384680-64da-11eb-9e5b-fa323e486c33.png)
[save and config yml.zip](https://github.com/CitizensDev/Citizens2/files/5906807/save.and.config.yml.zip)

**Comment by mcmonkey4eva** [comment]
- Update. You're quite far behind... including an entire minecraft patch, and 30+ Citizens builds.
- Never use the reload command.
