### ISSUE TITLE
NPC's types like pillagers & enderman keep moving away from their original location, keep having to teleport them back to original pos.

### ISSUE THREAD

**Issue by cloakfox** [CitizensDev/Citizens2#2470]
NPC's types like pillagers & enderman keep moving away from their original location. This has been an issue in citizens for a while now and is still not fixed. I'd figure ill just report it.

The NPC's get agitated by something and then move around.

I've checked all 13 pages of commands and none of them helped me fix this issue, I have tried a few like toggling if they can target other mobs, and setup an anchor? But yeah, nothing helps.

Using Paper 1.16.5
Using Citizens 2.0.27 build 2225

![Capture](https://user-images.githubusercontent.com/3696645/107381078-c7b1a180-6aee-11eb-939a-6bc33f3aa7b7.PNG)

**Comment by cloakfox** [comment]
![Capture](https://user-images.githubusercontent.com/3696645/107381866-92f21a00-6aef-11eb-9104-6ca0141375ba.PNG)

**Comment by mcmonkey4eva** [comment]
This type of issue is almost always a plugin conflict -> https://wiki.citizensnpcs.co/Plugin_Conflict

**Comment by cloakfox** [comment]
Seems more like an issue with Citizens itself. The location of the NPC changes and reloading citizens will not put the NPC's back in their place.

Also like I mentioned originally it's only happening to certain types of NPCs like endermands and pillagers.

All the villager type NPC's in our spawn never wander of.

**Comment by cloakfox** [comment]
You closed it?

**Comment by mcmonkey4eva** [comment]
You closed it by verbally refusing to follow basic testing steps, I just pressed the button that applies your choice there.

I'm quite happy to press the reopen button after you perform a basic plugin conflict test.

**Comment by cloakfox** [comment]
Basic testing steps? The method you described is only viable for Timmy's 10 plugin server.
![image](https://user-images.githubusercontent.com/3696645/107387719-650fd400-6af5-11eb-8db2-d05d41d45815.png)

It's pretty obvious from my description that it's not plugin related issue either. This issue only happens to a few TYPES of NPCS.

I will not be wasting my time testing 115 plugins for such a dumb issue like this.

**Comment by SXRWahrheit** [comment]
Create a local test server like every other server admin. Zip your server files, download them to your computer, and attempt to replicate the issue with only Citizens installed. It's not hard. In fact, it's a crucial part of server administration - whether for this plugin or another.

**Comment by cloakfox** [comment]
> Create a local test server like every other server admin. Zip your server files, download them to your computer, and attempt to replicate the issue with only Citizens installed. It's not hard. In fact, it's a crucial part of server administration - whether for this plugin or another.

The issue happens randomly and not consistent. Pretty sure every other server admin would realize it's pointless to waste time on an issue like this.

**Comment by SXRWahrheit** [comment]
Most of them are not only willing to cooperate, they actually isolate the issue before reporting it so that it can be fixed quickly!

**Comment by cloakfox** [comment]
> Most of them are not only willing to cooperate, they actually isolate the issue before reporting it so that it can be fixed quickly!

And most devs blame other plugins before even considering their own, what a world we live in.

**Comment by SXRWahrheit** [comment]
You seem to misunderstand. If it's a Citizens issue, replicating it with only Citizens installed will make it easy and fast to resolve the issue. Introducing additional variables makes it difficult - if not impossible - to identify the source of the problem.

**Comment by cloakfox** [comment]
> You seem to misunderstand. If it's a Citizens issue, replicating it with only Citizens installed will make it easy and fast to resolve the issue. Introducing additional variables makes it difficult - if not impossible - to identify the source of the problem.

Well let me help your thought process. How is it possible that an enderman NPC get's agitated as if you looked it straight in the eye an it starts teleporting around on it's own Is it possible that the enderman NPC can still receive damage somehow?

My question is, why is it even possible in the first place that this can happen? the NPC should have no AI at all right? Does it get overridden somehow?

**Comment by SXRWahrheit** [comment]
![2021-02-09_10 03 24](https://user-images.githubusercontent.com/774463/107391340-375b6880-6abe-11eb-865f-4c9c9f4a71d7.png)
![2021-02-09_10 03 32](https://user-images.githubusercontent.com/774463/107391343-37f3ff00-6abe-11eb-959c-61f272706665.png)

I tried to replicate your issue and could not. Please replicate the issue with only Citizens installed.

**Comment by SXRWahrheit** [comment]
![2021-02-09_10 05 31](https://user-images.githubusercontent.com/774463/107391507-5fe36280-6abe-11eb-8f6d-f97f62158e0b.png)

Same with the enderman. Please replicate the issue with only Citizens installed.

**Comment by cloakfox** [comment]
https://gyazo.com/a4ed529477487794f3872d4ec92e2633

**Comment by cloakfox** [comment]
Does citizens prevent mobs like enderman from getting into that state?

**Comment by SXRWahrheit** [comment]
Unless and until you replicate the issue with only Citizens installed, we can't help you.
