### ISSUE TITLE
swim, but not really

### ISSUE THREAD

**Issue by Beubeux74** [CitizensDev/Citizens2#2471]
**Suggestion/bug**

Hi, i have a probleme a probleme like this https://github.com/CitizensDev/Citizens2/issues/1878
Fish and npc of all kinds do not swim, either they float or they sink, it is impossible to give them "paths" in the water because they are either on the surface or at the bottom.
The gravity or not of activated
Here is the chosen route 
![image](https://user-images.githubusercontent.com/74351200/107557236-a1b4fb80-6bd9-11eb-8677-6c38763bf050.png)

The output of command `/version` on my server is: **Purpur 1.16.5-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **Citizens v2.0.27-SNAPSHOT (build 2247)**
![image](https://user-images.githubusercontent.com/74351200/107556541-d4122900-6bd8-11eb-9981-228cf61bfe06.png)

**Comment by mcmonkey4eva** [comment]
Please don't open duplicate issues, just reply to the previous one if you have any new information to add
