### ISSUE TITLE
Error when creating an NPC

### ISSUE THREAD

**Issue by MultiGod** [CitizensDev/Citizens2#2474]
Whenever I try to create a new npc I get this error not sure if this is just an issue with the version I am using or not.
https://pastebin.com/GfzswGpp

The output of command `/version` on my server is: This server is running Mohist version 1.16.5-360 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.0.22)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2263)
Website: http://www.citizensnpcs.co
Author: fullwall

**Comment by mcmonkey4eva** [comment]
Forge is unsupported. Only Spigot/Paper are supported.
