### ISSUE TITLE
citizens.commands.npc.select.already-selected does not output properly.

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#2476]
Paper dev 467 (Spigot 1.16.5)
Citizens dev 2264

When you look at an npc and type ``/npc select`` twice, it outputs ``citizens.commands.npc.select.already-selected`` in red instead of the actual message string. The line does exist in my messages_en.properties lang file.

```
citizens.commands.npc.select.already-selected=You already have that NPC selected.
```

**Comment by mcmonkey4eva** [comment]
Delete your messages_en file, it will regenerate at next server startup and then have the missing line automatically.

**Comment by mibby** [comment]
The line is not missing...

**Comment by mcmonkey4eva** [comment]
Oo, I see, the select command uses the translatable message string:
https://github.com/CitizensDev/Citizens2/blob/34398f09d5c0012d955d3fd2dc6fa4895155da6f/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L1789

But the error handler doesn't pass that string to the translate method:
https://github.com/CitizensDev/Citizens2/blob/34398f09d5c0012d955d3fd2dc6fa4895155da6f/main/src/main/java/net/citizensnpcs/commands/NPCCommandSelector.java#L66

**Comment by mcmonkey4eva** [comment]
This should be fixed via https://github.com/CitizensDev/Citizens2/commit/d99109d0b2f36ef51ee03344f7291ca5a138ad88 in Citizens build 2265+ from https://ci.citizensnpcs.co/job/Citizens2/

**Comment by mibby** [comment]
Thanks.
