### ISSUE TITLE
7 Npc's Lagging server tps drops so bad players cant join on the latest update 1.16.5

### ISSUE THREAD

**Issue by ac1dv1p3r** [CitizensDev/Citizens2#2478]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by mcmonkey4eva** [comment]
Please actually fill out all the information the issue template asks for, OR ask on Discord: https://discord.gg/Q6pZGSR
