### ISSUE TITLE
Error on log

### ISSUE THREAD

**Issue by Lunatik934** [CitizensDev/Citizens2#2479]
The output of command `/version` on my server is: 1.8.8-R3
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2263)

Hi, i have this error after updating to 2.0.27 version.
https://pastebin.com/d8JP4L6s

**Comment by mcmonkey4eva** [comment]
This is a duplicate of #2472 which was already fixed for build 2269+ from https://ci.citizensnpcs.co/job/Citizens2/
