### ISSUE TITLE
Ingame Player-GUI

### ISSUE THREAD

**Issue by ErythroCraft** [CitizensDev/Citizens2#2480]
In-game GUI to create and set up custom entities for users without command.

The problem I have is that players need a lot of commands to set up their own entities.
A player gui should help that citizens of a city get help from self-created entities with building, farming or similar.

I've also tried to create my own GUI with the help of various plagins. Unfortunately, this was unsuccessful because further permissens are missing.

What should the Player-Gui be able to do?

- simple authorization to open the GUI
- a site for creating / deleting entity types
- a right click event for owners of the entities to open the setting.

- additional rights for server owners to extend permissions (e.g. sitizens.owned. * or sitizens.use.player or ....)

What do I want to do with a player gui for sitizens?
I want to mix Towny, TownyWars, Plotsquared, Jobs and other plugins to get the first server in the world
that the player can create big cities, play wars and much more. For example, the user should be able to create and set entity types on a server in order to change the course of the game and thus bring a new freedom to play in minecraft.

I hope you can understand my english.

/version` on my server is: **(1.16.5dev)**
/version citizens` on my server is: **(latest)**

**Comment by fullwall** [comment]
Yes, this was the plan with the new GUI stuff (e.g. /npc equip)

**Comment by ErythroCraft** [comment]
Do you need help in structures?
I can not programming, but I can create structures by "Paradigm"

**Comment by ErythroCraft** [comment]
sorry. was sick. 
it woked for versions wothout 1.18.x

THX
