### ISSUE TITLE
Citizens Issue

### ISSUE THREAD

**Issue by Attila144** [CitizensDev/Citizens2#2481]
Cannot access Citizens, no commands appearing, the citizens I made in 1.15.2 are not there (Im on 1.16 now)

https://pastebin.com/dPM14VhV - Server Logs

https://pastebin.com/FQ3tJV0E - Config

Server
This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Previous version: git-Paper-300 (MC: 1.15.2)

Citizens
Citizens version 2.0.27-SNAPSHOT (build 2268)
Website: http://www.citizensnpcs.co
Author: fullwall

2 GB of RAM
No Info of CPU From Apex Hostings

17 NPCS

https://pastebin.com/hcfmKKdR - Save.yml

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
