### ISSUE TITLE
/npc equip duplication

### ISSUE THREAD

**Issue by ZwingGX** [CitizensDev/Citizens2#2482]
The output of command `/version` on my server is: Paper version git-Paper-470 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2270)

bug report:
Insert the item into the left-handed equipment and enter the /npc equip command again to copy the item.

![Zwing_2021-02-20_00-34-15](https://user-images.githubusercontent.com/1742441/108525665-af722b80-7313-11eb-828d-568de0df8eb8.gif)

**Comment by fullwall** [comment]
Try latest build
