### ISSUE TITLE
illegal reflective access

### ISSUE THREAD

**Issue by seema84** [CitizensDev/Citizens2#2483]
this warning occurs at server startup ->

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.citizensnpcs.util.NMS (file:/mnt/minecraftbukkit/plugins/Citizens-2.0.27-b2270.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of net.citizensnpcs.util.NMS
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Paper version git-Paper-470 (MC: 1.16.5)
Citizens v2.0.27-SNAPSHOT (build 2270)

**Comment by mcmonkey4eva** [comment]
You can pretty much just ignore that message, it's a result of Paper pushing Java 11 on people despite, y'know, not being a supported Java version. Everything works, just weird messages like that appear.

**Comment by seema84** [comment]
that means it will stay that way until the vanilla version supports java 11?

**Comment by mcmonkey4eva** [comment]
It will stay that way until paper stops pushing java 11

**Comment by seema84** [comment]
then it will probably always remain
