### ISSUE TITLE
Tracking System for Showing/Hiding to specific players

### ISSUE THREAD

**Issue by Cryptite** [CitizensDev/Citizens2#2486]
An oft-requested feature, it'd be nice for Citizens to have a means by which NPCs could be white/blacklisted to players so that they could see specific NPCs and not others. In my specific use-case, Questing where players at certain stages of quest progress could see or not see certain NPCs is one example.

I mention the White/Blacklist system mostly in reference to [this ProtocolLib Utility ](https://gist.github.com/aadnk/5871793)in which you can create groupings to manage entity tracking. That util is a bit old; there're some forked versions elsewhere that include more modern packets, etc.

fullwall asked that I put this here for tracking purposes.

**Comment by mcmonkey4eva** [comment]
You're a Java dev right? There's literally a Bukkit API for this you can call and use for freely - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#hidePlayer(org.bukkit.entity.Player)

**Comment by Cryptite** [comment]
fullwall specifically asked that I make this issue as he mentioned it was something he wanted to add to Citizens, presumably also not requiring Denizen.

I'm also implementing this my own way for my plugin currently as well.

**Comment by fullwall** [comment]
Added in new build
