### ISSUE TITLE
Add the ability to create a Named Registry at /npc create time

### ISSUE THREAD

**Issue by Cryptite** [CitizensDev/Citizens2#2487]
There is already the ability to do `/npc list` and provide a named registry. It'd be great to be able to provide one at `/npc create` time as npc creation via API is not always preferred to do this.

**Comment by Cryptite** [comment]
Is it possible for this to also _create_ the given Registry if it doesn't exist? Or if not, a command to add/remove registries? These seem like something that people would probably wanna use without using the API to do it.

**Comment by mcmonkey4eva** [comment]
This was resolved via https://github.com/CitizensDev/Citizens2/commit/8afaf23c1d9810e82adc5d0a60b701a6a472e5d3
