### ISSUE TITLE
Need help with placeholders

### ISSUE THREAD

**Issue by ShinyPlasm** [CitizensDev/Citizens2#2489]
I want to send a/the user who clicks a npc sent to a different minecraft server (using bungeecord), so I'm trying to sudo them into running the /server command. Everything works until I have to enter the placeholder for the user clicking the npc, how do I do this?

The output of command `/version` on my server is: FINAL BUILD FOR 1.14.4
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2269)

**Comment by fullwall** [comment]
<p>

**Comment by mcmonkey4eva** [comment]
Refer to the bungee information on https://wiki.citizensnpcs.co/NPC_Commands
