### ISSUE TITLE
HEX Color codes

### ISSUE THREAD

**Issue by mooshlandia** [CitizensDev/Citizens2#2490]
Hi, I am wondering if Citizens supports HEX color codes in the NPC name holograms. If so, how do I correctly format it?

If this is not a feature currently in the plugin is it something that is being added in the future?

**Comment by mcmonkey4eva** [comment]
`&#FF00FF`, same as most plugins, or `&x&f&f&0&0&f&f` as Spigot itself uses

**Comment by mooshlandia** [comment]
Thank you!
