### ISSUE TITLE
Questions about how the API works

### ISSUE THREAD

**Issue by JAPGamer** [CitizensDev/Citizens2#2497]
Hey there,
I'm currently working on a Spigot plugin including the Citizens2-API. I just want to create an npc called "Dealer". 
This NPC should turns his head in direction of closest player. 
In addition, a method should be executed when you click at the NPC.

I also would like to apply a custom uploaded skin from mineskin.org (With TextureData, TextureSignature) to my npc.

I have already tried a few methods, but have not yet come to any result.

That's my code:

    public void create() {
       npc = registry.createNPC(EntityType.PLAYER, name);
       npc.setProtected(true);
       npc.addTrait(LookClose.class);
       npc.spawn(loc);
    }

Thanks in advance
JAPGamer

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Skins
