### ISSUE TITLE
Show/Hide NPC names if player is looking

### ISSUE THREAD

**Issue by DevJorgeMCS** [CitizensDev/Citizens2#2498]
This is a suggestion/feature request.

A way to only show the NPC names if i'm looking them (in a certain range and direction (if possible)) and hide the name if i don't look them.

Server version: 1.16.5   Citizens version: Lastest

**Comment by mcmonkey4eva** [comment]
For non-player type NPCs, you can use `/npc name -h`
For player types, you might consider using Denizen with these packet-based fake-sneak sample scripts @ https://forum.denizenscript.com/viewtopic.php?f=13&t=354

**Comment by fullwall** [comment]
Duplicate issue of #1676
