### ISSUE TITLE
Cannot create NPC

### ISSUE THREAD

**Issue by Rmarmorstein** [CitizensDev/Citizens2#250]
I've been trying to find the answer, but cannot seem to find it.

I'm running Spigot 1.8 and Citizens 2.0.14 from the jenkins site.

Citizens will load fine, and i can execute the commands fine, however, no NPC seems to spawn. It says that it spawned, and I can /npc select - but there is no npc there.

I'm hoping someone can help me get an answer. Thanks

**Comment by mcmonkey4eva** [comment]
Post a startup log please (including logs of when you spawned an NPC)
... to pastebin.

**Comment by Rmarmorstein** [comment]
Startup:

[20:24:29] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.14-SNAPSHOT (build 1211)
[20:24:29] [Server thread/ERROR]: [Citizens] Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes
[20:24:29] [Server thread/INFO]: [Citizens] Loaded 3 NPCs.

When executing the command, nothing is logged other than the player has executed the command message.

**Comment by mcmonkey4eva** [comment]
According to the full logs
 `[20:35:37] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.14-SNAPSHOT (build Unknown)`
You're running an unofficial and thus unsupported build, not 1211.

**Comment by Rmarmorstein** [comment]
My apologies. That was attempt to use the build that was listed in another ticket. I've now updated to the 1211. The issue is still persistent. 

New startup log: http://pastebin.com/Q2BAH7Fy

**Comment by mcmonkey4eva** [comment]
Is this still an issue in 1.8.3?

**Comment by MrBUTTER1399** [comment]
Yes

**Comment by MrBUTTER1399** [comment]
I am currently trying to get it to work but cant seem to get any of the mobs to spawn.

**Comment by MrBUTTER1399** [comment]
Actually, if you use it for JUST 1.8/1.8.1 it works, but 1.8.3 Seems to have some missing codes for the entities themselves.

**Comment by mcmonkey4eva** [comment]
All I can tell you is it works fine for everyone else. Perhaps it might be worth trying to remove plugins one by one, to see if it suddenly starts working (and thus you would be able to identify the last plugin removed as the cause of the trouble)?
