### ISSUE TITLE
NPC new pathfinder fails when approaching ladders from the side

### ISSUE THREAD

**Issue by 1thebeast** [CitizensDev/Citizens2#2500]
when an npc approaches a ladder from the side they just jump up against the block and then path below where they were supposed to go. when they approach the ladder from the front they path up it as intended.

paper version paper-469
citizens version 2.0.27 snapshot build 2274

**Comment by mcmonkey4eva** [comment]
Not able to replicate this on current builds.

If you're able to replicate it still, please post a screenshot or video of the path the NPC is meant to take / is taking.
