### ISSUE TITLE
MEssage

### ISSUE THREAD

**Issue by Zuixik** [CitizensDev/Citizens2#2503]
![image](https://user-images.githubusercontent.com/61326124/110881576-da331c80-82e0-11eb-85da-03b969445613.png)

**Comment by mcmonkey4eva** [comment]
There's a reason the issue template (which you deleted instead of filling out) asks for versions... this issue, like many, is one that was already resolved - in this case an entire week ago. Update to the current version from https://ci.citizensnpcs.co/job/Citizens2/
