### ISSUE TITLE
Disapearing npc

### ISSUE THREAD

**Issue by Trewur** [CitizensDev/Citizens2#2505]
When i'm online i can't place an npc with my nickname. I'm using newest citizens.
[33;1m[00:08:38 WARN]: Trying to add entity with duplicated UUID b37998d2-5f98-35e0-b8c5-0602b7ab9652. Existing minecraft:player#361, new: minecraft:player#1949

**Comment by BehrRiley** [comment]
Please fill out the issue template properly. You can find a copy of the template you ignored here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE
Alternately, feel free to ask for help on the Discord channel instead: https://discord.gg/Q6pZGSR

However, it appears that your server may be cracked. if so, please refer to this wiki to correct this before seeking support, as we don't provide any support to cracked or improperly configured servers: https://wiki.citizensnpcs.co/Cracks

**Comment by Trewur** [comment]
Oh sorry, didn't know plugin was only for premium servers 😃
