### ISSUE TITLE
Feature Request - Tags under the NPC name

### ISSUE THREAD

**Issue by CoreTechMC** [CitizensDev/Citizens2#2508]
Hello i would like to sumbit a request to have stuff to add under the npc's name such as Click or online or anything like that

The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by mcmonkey4eva** [comment]
This isn't a feature request, this is a basic support question.

Use `/npc hologram`
