### ISSUE TITLE
[Feature request] Text below player name

### ISSUE THREAD

**Issue by franga2000** [CitizensDev/Citizens2#251]
Hi, I'm trying to make NPCs for the staff on my server and I'd like to show their username and rank, but I can't fit both on a single line.

In Minecraft 1.7 (not 100% sure), mojang added a way to display scoreboard scores under a player's name ([wiki](http://minecraft.gamepedia.com/Scoreboard#Display_slots)). 

Could you use that to add a second line to the player NPCs so something like this would be possible?

Another thing you can do with scoreboards is increase the max name tag length using team prefixes and suffixes. That would also be an awesome feature.

**Comment by mcmonkey4eva** [comment]
Nope, scoreboards don't allow custom text, only a single global text variable and a number for each player :/
You could use a hologram though (separate plugin).

**Comment by franga2000** [comment]
Too bad. I was almost certain I saw it used on another server. I guess they were using holograms too.
