### ISSUE TITLE
Skins resetting in the nether

### ISSUE THREAD

**Issue by Kayndashians** [CitizensDev/Citizens2#2510]
so whenever i set a skin for an npc in the nether it works fine, but when I leave and enter the nether again, the skin resets back to default

![2021-03-20_17 35 56](https://user-images.githubusercontent.com/80624420/111871371-0450a280-89a3-11eb-8fac-f1c667017701.png)
![2021-03-20_17 36 07](https://user-images.githubusercontent.com/80624420/111871373-061a6600-89a3-11eb-85a8-1658b9cc3768.png)

**Comment by Kayndashians** [comment]
oh also, when im in the nether and the skin is resets back to default i can leave and join the game and the skin will be whatever i picked earlier

**Comment by mcmonkey4eva** [comment]
It's been a while, but I can't replicate this in testing on Paper 1.18.1.
Please reply below if this is still a current issue and we can investigate further
