### ISSUE TITLE
Ticking entity?

### ISSUE THREAD

**Issue by YodaLightsabr** [CitizensDev/Citizens2#2512]
The output of command `/version` on my server is: I can't access this because my server has a ticking entity
The output of command `/version citizens` on my server is: I can't access this because my server has a ticking entity

# The issue I have
My server has a ticking entity and crashes right after it starts.

# Steps to reproduce
Run `/npc create Minecart --type minecart`
Run `/npc minecart --item command_block`
Watch your server die

I'm still trying to resolve the issue of the ticking entity and I will provide more information as it becomes available.

**Comment by mcmonkey4eva** [comment]
Please post your full `logs/latest.log` file and any applicable crash report files.

Consider also asking for support on Discord @ https://discord.gg/Q6pZGSR
