### ISSUE TITLE
NPCs cause a lot of lag

### ISSUE THREAD

**Issue by CodeLey33** [CitizensDev/Citizens2#2513]
Hello Citizens! My problem is that citizens is causing me a lot of lag, the server does not drop below 20tps but the players jerk all the time and the scoreboard text animations are constantly jamming. So I activate the debug mode in the citizens config and when I enter the lobby, which is the area where the npc are, the console starts sending these errors (https://pastebin.com/hSgRQskq).

I have noticed that using / npc respawn 10 on all npcs most of the lag goes away but I keep getting the same error on the console.
If I delete the configuration files and leave citizens by default without npc or anything the problem continues to appear, although only if I activate debug mode, if I do not activate it the plugin says nothing and everything works correctly but the lag is still there.
Here is the error that it gives me when the config is completely new 
(https://pastebin.com/pA6S976c). 
Although it is the same error I will send it to you just in case

The strange thing is that it took a few days in which I did not notice any type of lag, everything worked perfectly and smoothly, until today and when I began to diagnose my server I realized that citizens was the problem and as I have already said the plugin works perfectly despite the lag and the errors that I send you that only appear when activating debug mode

I have tried updating the server to Papermc but it did not solve anything
I have tried to copy the spawn (which is where I have the npc) and paste it in another new map but it did not solve anything
I have tried using an older version (1.13) and it seems to work without any problem, but the current version also worked without problems at first and has features that interest me.

Server Specs:
CPU: Intel I7-4790k CPU @4.00GHz
Hard drive: SSD
Ram: 8Gb DDR3

Spark test: https://spark.lucko.me/zzxcy8p2uj
Number of NPCs on the server:   7
error with my npc´s:                                  https://pastebin.com/hSgRQskq
error with the default config:                     https://pastebin.com/pA6S976c 
Citizens config:                                          https://pastebin.com/uXT8RHWC
Saves file:                                                  https://pastebin.com/duHS9zi6
Spigot Version: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Citizens Version: Citizens version 2.0.27-SNAPSHOT (build 2269)

English is not my native language, I hope I have explained myself well. thanks for your help and have a nice day

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
