### ISSUE TITLE
Name with more 16 caracters on player type npc

### ISSUE THREAD

**Issue by DevilishDante** [CitizensDev/Citizens2#2514]
Hello, i am experiencing some issue about naming my player's npc with custom name out of 16 caracters
none peticular about some error or anything like that in logs or console, i have tried /npc hologram without success ❌ 
as you can see :

![image](https://user-images.githubusercontent.com/13486924/112728596-602da500-8f28-11eb-99a6-5dd76e5a60db.png)

**server specs**
OS: Debian 9
Java : 1.8.0_151

**config**
https://pastebin.com/sNG003ud

**saves**
https://pastebin.com/h5qgzjyg

**Server version**
![image](https://user-images.githubusercontent.com/13486924/112728653-9a974200-8f28-11eb-9ce7-e0f72c94e557.png)

**Citizen version**
![image](https://user-images.githubusercontent.com/13486924/112728629-7e93a080-8f28-11eb-89ae-7242bd13e6be.png)

It's pretty anoying, how can i resolve this please?

Thanks to read me, have a good day.

**Comment by SXRWahrheit** [comment]
Only 1.16.5 is supported, and you have another plugin interfering with scoreboards.

**Comment by DevilishDante** [comment]
Wich version can i take for 1.16.3? 
And this plugin add health feature : https://www.spigotmc.org/resources/tab-1-7-x-1-16-5-free-version.57806/
But i have always this kind of fearture on my server and there're never make any issues :x

**Comment by SXRWahrheit** [comment]
Update your server to 1.16.5 if you'd like support. Support is not provided for outdated versions of Minecraft.

**Comment by DevilishDante** [comment]
mh updating my server version isn't possible due to some other plugins not follow in version 1.16.5 for now

**Comment by SXRWahrheit** [comment]
Any plugin that hasn't updated to 1.16.5 yet should be considered abandoned. It's been months. You should find a replacement.

**Comment by DevilishDante** [comment]
it's easier said than done x) but ok i find myself how to bypass this problem in other way
