### ISSUE TITLE
A big TPS drop problem

### ISSUE THREAD

**Issue by ItsHofer** [CitizensDev/Citizens2#2515]
One day, the server TPS dropped to around 2, and after removing the Citizens plugin, it was fixed and never happened again.
our server heavily relies on this plugin for shops, immersive environments, quests and transport, we are currently having an event with over 10 youtubers that would require this not to be a problem, we'd really apricate if we could get this issue fixed. 

server log：https://pastebin.com/cuM99Ugi
config：   https://pastebin.com/mWFTwsk6

"FOR LAG RELATED ISSUES"
number of npcs when the issue occurred：780~800
server specs：cpu e5 2660 v2  ram 12GB
saves.yml：https://drive.google.com/file/d/1fYnA48d7jJqtChFRLPD8R3E8zD7_7eqW/view?usp=sharing
"profiler like Spark"：I am sorry about this, I don't know what this is thus I don't possess this entity.

The output of command /version on my server is: 
Paper version get-Paper-138 (MC:1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

The output of command /version citizens on my server is: 
2.0.27-SNAPSHOT (build 2087)

**Comment by fullwall** [comment]
Seems to be a luckoperms thing? That zip file closed exception doesn't seem Citizens-related.

**Comment by mcmonkey4eva** [comment]
And severely outdated versions - you need to update to Paper 1.16.5 ASAP, and current versions of all relevant plugins

**Comment by ItsHofer** [comment]
> Seems to be a luckoperms thing? That zip file closed exception doesn't seem Citizens-related.

sorry? which zip file is not related? there are no zip files, and certainly nothing related to lucky perms.

**Comment by mcmonkey4eva** [comment]
You need to update.
