### ISSUE TITLE
Question about spawning and despawing citizens

### ISSUE THREAD

**Issue by ltei01** [CitizensDev/Citizens2#2516]
I got a question about how I can spawn citizens and despawn citizens. Is it possible that a citizens despawns if a player is further away then 20 blocks as an example. And the citizens spawns if a player is in the range of 20 blocks.

The output of command `/version` on my server is: **Git Paper 565**
The output of command `/version citizens` on my server is: **2.0.27**

**Comment by mcmonkey4eva** [comment]
You can also try messing with entity-tracking-range options in the spigot configs if you just want to change the ranges that things visually load/unload at.
