### ISSUE TITLE
Unable to perform click action on dropped_item type.

### ISSUE THREAD

**Issue by janiiik** [CitizensDev/Citizens2#2518]
The output of command `/version` on my server is: [08:24:16 INFO]: This server is running Paper version git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: [08:25:40 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2269)

Issue: when entity type is of type dropped_item it is not possible to do click action. When same npc is changed to for example type shulker, click action is working fine.

**Comment by BehrRiley** [comment]
You're 107 paper versions and 12 Citizens builds behind, you may want to update those first and verify the issue persists. 

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.

Latest Paper builds are at https://papermc.io/downloads.

If the issue does persist, you can provide a startup log from your `latest.log` file found in the `logs` folder within your server folder.

**Comment by mcmonkey4eva** [comment]
I think it's not possible to click a dropped item - they have no bounding box, the client will just try to click the ground beneath them.

You could spawn an invisible clickable thing in the same spot - eg a simple player NPC, but use `/npc invisible` (with Denizen), and then give the click command to that player.
