### ISSUE TITLE
[Denizen] Citizens does not seem to be activated! Denizen will have greatly reduced functionality!

### ISSUE THREAD

**Issue by anthony114669** [CitizensDev/Citizens2#2519]
issue: compatibility: denizen

[Denizen] Citizens does not seem to be activated! Denizen will have greatly reduced functionality!

citizen version: Bugfix for /npc command
denizen version: b 1733
paper version: 570

to reproduce:
just install it

**Comment by mcmonkey4eva** [comment]
This is likely a plugin conflict related to plugins that break load order, like FAWE.

If that's not enough for you to fix it on your own,
Please ask on Discord @ https://discord.gg/Q6pZGSR in the `#denizen` channel.
