### ISSUE TITLE
Error in logs with Citizens after setting a pose

### ISSUE THREAD

**Issue by Th3BlxckCxt** [CitizensDev/Citizens2#2520]
it's not flooding anymore but I will post the issue anyways. When setting a pose for an NPC my console log was flooding and spamming with this:
[INFO] [Citizens] Exception while updating 26: null.

[WARNING] java.lang.NullPointerException

[WARNING] at org.bukkit.craftbukkit.v1_16_R3.entity.CraftLivingEntity.hasLineOfSight(CraftLivingEntity.java:489)

[WARNING] at net.citizensnpcs.trait.LookClose.canSee(LookClose.java:58)

[WARNING] at net.citizensnpcs.trait.LookClose.canSeeTarget(LookClose.java:67)

[WARNING] at net.citizensnpcs.trait.Poses.run(Poses.java:133)

[WARNING] at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:480)

[WARNING] at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:350)

[WARNING] at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.tick(EntityHumanNPC.java:463)

[WARNING] at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:772)

[WARNING] at net.minecraft.server.v1_16_R3.World.a(World.java:769)

[WARNING] at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:507)

[WARNING] at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1214)

[WARNING] at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394)

[WARNING] at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1117)

[WARNING] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:956)

[WARNING] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)

I dont have a server log link since its been a day. But here is a link to my citizens config:
https://paste.helpch.at/udidevovar.coffeescript
Server version is CraftBukkit version 3029-Spigot-79d53c2-e9ad7ob 9MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Citizens version is 2.0.27-SNAPSHOT 9build 22690

**Comment by mcmonkey4eva** [comment]
This appears to be:

This line was called:
https://github.com/CitizensDev/Citizens2/blob/48a2763a1b68d9c76f576265b07a1c8df748d52f/main/src/main/java/net/citizensnpcs/trait/Poses.java#L133

Which translates to this method:
https://github.com/CitizensDev/Citizens2/blob/48a2763a1b68d9c76f576265b07a1c8df748d52f/main/src/main/java/net/citizensnpcs/trait/LookClose.java#L67

Which uses the `lookingAt` field, which can be null:
https://github.com/CitizensDev/Citizens2/blob/48a2763a1b68d9c76f576265b07a1c8df748d52f/main/src/main/java/net/citizensnpcs/trait/LookClose.java#L40

so when this is reached:
https://github.com/CitizensDev/Citizens2/blob/48a2763a1b68d9c76f576265b07a1c8df748d52f/main/src/main/java/net/citizensnpcs/trait/LookClose.java#L58

It's passing that null value along, and thus throwing an NPE.

The solution should be as simple as: add a null check to `canSeeTarget`

**Comment by Th3BlxckCxt** [comment]
Sorry Im not the brightest. Im not sure what that means

**Comment by mcmonkey4eva** [comment]
That was a quick technical analysis of why the error happened. You don't need to understand it, it's mainly for fullwall's reference so he can very quickly and easily fix it when he sees this post.

**Comment by Th3BlxckCxt** [comment]
oh haha alright

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/74839e9843ed7a222f46e5db027ae3e57e2307ee in build 2282+ from https://ci.citizensnpcs.co/job/Citizens2/
