### ISSUE TITLE
NPC equipment keeps disappearing.  this new equipment editor is dysfunctional. /npc equip

### ISSUE THREAD

**Issue by IAmAirman** [CitizensDev/Citizens2#2521]
The new equipment editor is dysfunctional, does not always work(BIG ISSUE) and makes many of the items I give the npc disappear. Its a bug that has been mentioned on your spigot reviews too. I dont have a server log for this since i dont know much about how to use server logs
- Link to server log & Citizens config (using e.g. pastebin.com)
- **Spigot and Citizens versions!** Use in-game commands "/version" and "/version citizens" and screenshot or copy/paste the EXACT output of BOTH commands!
/npc equip
This is what it was like on a previous update as shown in this demo by MineHut(WHICH ACTUALLY WORKS AND HAS NO BUGS)
![Image 4-5-21 at 1 32 AM](https://user-images.githubusercontent.com/68290331/113540831-f9a32980-95ae-11eb-91a4-53bcab6b30dd.jpg)
<img width="1003" alt="Screen Shot 2021-04-05 at 1 31 41 AM" src="https://user-images.githubusercontent.com/68290331/113540861-03c52800-95af-11eb-81e9-dab03a6570b4.png">

Except this is what I get. It works almost half of the time, but for the rest of it, my stuff completely vanishes as if the npc just takes it. if you look closely at the npc in this photo during my playtest, its not working. the way the developers did this is so much better than this new crap. If only this system will fully work and if only you revert it back to the way you first used the /npc equip, that would brighten my day.
<img width="1440" alt="Screen Shot 2021-04-05 at 1 38 31 AM" src="https://user-images.githubusercontent.com/68290331/113541165-b0070e80-95af-11eb-8187-38a473d8b4ea.png">

The output of command `/npc equip` on my server is: **The picture from above**
The output of command `important bugfix for /npc command` on my server is: **same picture. its only just this part of the plugin that needs to be fixed or reverted**

**Comment by IAmAirman** [comment]
<img width="1440" alt="Screen Shot 2021-04-05 at 1 38 31 AM" src="https://user-images.githubusercontent.com/68290331/113541503-610da900-95b0-11eb-83c5-a40205afad2c.png">
<img width="1003" alt="Screen Shot 2021-04-05 at 1 31 41 AM" src="https://user-images.githubusercontent.com/68290331/113541519-64a13000-95b0-11eb-923c-278eede5e17d.png">

**Comment by IAmAirman** [comment]
The new equipment editor is dysfunctional, does not always work(BIG ISSUE) and makes many of the items I give the npc disappear. Its a bug that has been mentioned on your spigot reviews too. I dont have a server log for this since i dont know much about how to use server logs
- Link to server log & Citizens config (using e.g. pastebin.com)
- **Spigot and Citizens versions!** Use in-game commands "/version" and "/version citizens" and screenshot or copy/paste the EXACT output of BOTH commands!
/npc equip
This is what it was like on a previous update as shown in this demo by MineHut(WHICH ACTUALLY WORKS AND HAS NO BUGS)
![Image 4-5-21 at 1 32 AM](https://user-images.githubusercontent.com/68290331/113540831-f9a32980-95ae-11eb-91a4-53bcab6b30dd.jpg)
<img width="1003" alt="Screen Shot 2021-04-05 at 1 31 41 AM" src="https://user-images.githubusercontent.com/68290331/113540861-03c52800-95af-11eb-81e9-dab03a6570b4.png">

Except this is what I get. It works almost half of the time, but for the rest of it, my stuff completely vanishes as if the npc just takes it. if you look closely at the npc in this photo during my playtest, its not working. the way the developers did this is so much better than this new crap. If only this system will fully work and if only you revert it back to the way you first used the /npc equip, that would brighten my day.
<img width="1440" alt="Screen Shot 2021-04-05 at 1 38 31 AM" src="https://user-images.githubusercontent.com/68290331/113541165-b0070e80-95af-11eb-8187-38a473d8b4ea.png">



The output of command `/npc equip` on my server is: **The picture from above**
The output of command `important bugfix for /npc command` on my server is: **same picture. its only just this part of the plugin that needs to be fixed or reverted**

**Comment by mcmonkey4eva** [comment]
Please
- Fill out the issue template in full
- Describe the actual issue you have so it can be fixed, rather than just saying you hate entire features
- Be kind to the developer who worked hard to make a proper GUI for NPC equipment by popular request

Consider also asking for support on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel
