### ISSUE TITLE
guided waypoint mode issue

### ISSUE THREAD

**Issue by saintblair11** [CitizensDev/Citizens2#2522]
this has taken me roughly 6 hours.... i got 1 npc walking.

i setup guided waypoints sofar working till i tried to use toggle path... it just says "type <toggle path> to toggle showing entities which in everyway ive tried will not work.

even typing "trigger" in chat only goes to the broadcast instead of a command, even after it gave me a clickable link to insert "trigger" into the chat.

tried to use markers/cycle but there is no documentation on how to use and no command help and ive tried many ways to enter it useing either /waypoint <arg> or /npc path <arg> just gives "too many arguments" in chat for /npc path <arg>.

shift+right click will not select way points or remove, i have to change providers to force it to remove the set waypoints. (guided mode)

last thing i can think of, i cant find any info on how to make an npc stay inside a worldguard region for wandering... no syntax, text or videos to show how but it is mentioned.

The output of command `/version` on my server is: **(This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 19 version(s) behind)**
The output of command `/version citizens` on my server is: **(2.0.27-snapshot (build 2283)**

**Comment by mcmonkey4eva** [comment]
`even typing "trigger" in chat only goes to the broadcast instead of a command, even after it gave me a clickable link to insert "trigger" into the chat.`

Does this happen with other chat inputs in Citizens? If so, it's likely you have an external chat plugin that is blocking the normal chat events.

**Comment by saintblair11** [comment]
> `even typing "trigger" in chat only goes to the broadcast instead of a command, even after it gave me a clickable link to insert "trigger" into the chat.`
> 
> Does this happen with other chat inputs in Citizens? If so, it's likely you have an external chat plugin that is blocking the normal chat events.

here is a pic of the plugins im useing just easier then explaining as its quite a bit...
![2021-04-06 09_41_20-plugins](https://user-images.githubusercontent.com/26775782/113747451-3f99e380-96bc-11eb-8734-78bbe4994c29.png)

**Comment by saintblair11** [comment]
i was looking through the commands page... do you require denziens for waypoint triggers? bc it looks that way to me.

**Comment by saintblair11** [comment]
![2021-04-06 13_49_38-Minecraft_ 1 16 5 - Multiplayer (3rd-party Server)](https://user-images.githubusercontent.com/26775782/113776560-e8f1d100-96de-11eb-8acc-32702ecd2376.png)

maby 2 mins later i did nothing at all except walk away a bit and come back and now they are how they looked when i created them with /npc create banker.
![2021-04-06 13_50_18-Minecraft_ 1 16 5 - Multiplayer (3rd-party Server)](https://user-images.githubusercontent.com/26775782/113776778-1d658d00-96df-11eb-84b3-ea94f575bfb8.png)

**Comment by saintblair11** [comment]
/npc text
i am able to type "add" and it is working there ok sofar

**Comment by mcmonkey4eva** [comment]
Is there any particular reason you're trying to use guided waypoints at all?

ngl I genuinely don't know of any use cases for that, other than maybe theoretically using it as a tool for another plugin to add onto. Its current impl is just a more-complicated less-capable version of the `wander` provider.

**Comment by fullwall** [comment]
I have fixed the major complaints in this issue.
