### ISSUE TITLE
Error with Citizens when using shopkeeper

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#2523]
Citizens-Version : Citizens-2.0.27_Build2284.jar

Paper:Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

i wanted to create an npc with shopkeeper. Unfortunately, this error always comes.

`>.... [18:16:12 INFO]: Blueeyestar issued server command: /npc type player
>.... [18:16:12 WARN]: java.lang.NullPointerException
>.... [18:16:12 WARN]: at java.util.Properties$LineReader.readLine(Properties.java:434)
>.... [18:16:12 WARN]: at java.util.Properties.load0(Properties.java:353)
>.... [18:16:12 WARN]: at java.util.Properties.load(Properties.java:341)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.getDefaultBundleProperties(Translator.java:230)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.populateDefaults(Translator.java:284)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.getDefaultResourceBundle(Translator.java:251)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.getDefaultBundle(Translator.java:65)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.translate(Translator.java:84)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.format(Translator.java:49)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.translate(Translator.java:312)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Translator.translate(Translator.java:316)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.util.Messaging.sendTr(Messaging.java:139)
>.... [18:16:12 WARN]: at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:2383)
>.... [18:16:12 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>.... [18:16:12 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>.... [18:16:12 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [18:16:12 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
>.... [18:16:12 WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
>.... [18:16:12 WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
>.... [18:16:12 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [18:16:12 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [18:16:12 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
>.... [18:16:12 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
>.... [18:16:12 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [18:16:17 INFO]: Blueeyestar issued server command: /npc skin _wr3
>.... [18:16:17 WARN]: java.lang.NullPointerException
>.... [18:16:17 WARN]: at java.util.Properties$LineReader.readLine(Properties.java:434)
>.... [18:16:17 WARN]: at java.util.Properties.load0(Properties.java:353)
>.... [18:16:17 WARN]: at java.util.Properties.load(Properties.java:341)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.populateDefaults(Translator.java:284)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.getDefaultResourceBundle(Translator.java:251)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.getDefaultBundle(Translator.java:65)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.translate(Translator.java:84)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.format(Translator.java:49)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.translate(Translator.java:312)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Translator.translate(Translator.java:316)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.util.Messaging.sendTr(Messaging.java:139)
>.... [18:16:17 WARN]: at net.citizensnpcs.commands.NPCCommands.skin(NPCCommands.java:1986)
>.... [18:16:17 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>.... [18:16:17 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>.... [18:16:17 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [18:16:17 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
>.... [18:16:17 WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
>.... [18:16:17 WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
>.... [18:16:17 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [18:16:17 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [18:16:17 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
>.... [18:16:17 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
>.... [18:16:17 WARN]: at java.lang.Thread.run(Thread.java:748) `

**Comment by mcmonkey4eva** [comment]
That looks more likely that Citizens failed to load or similar
Please post your full `logs/latest.log`

Consider also asking on the Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel

**Comment by Blueeyestar** [comment]
> Consider also asking on the Discord

https://pastebin.com/TzJdSG9z

**Comment by mcmonkey4eva** [comment]
- That log has many errors in it, which you should look into ASAP.
- You're running PlugMan, GadgetsMenu, HeadDatabase, and CMI, each of which are known to cause issues. You may have a plugin conflict - check https://wiki.citizensnpcs.co/Plugin_Conflict
- You're using the `de` locale, and the quoted error relates to translation logic - that locale file has not been edited much in literally 9 not years, it's quite likely outdated or broken. You might be best off simply changing your locale in the Citizens config to `en`.
