### ISSUE TITLE
npcs stop walking/go missing entirely

### ISSUE THREAD

**Issue by saintblair11** [CitizensDev/Citizens2#2525]
i tried to teleport id 0 (THE DECIMATOR) to me which wanders around randomly. it however teleported id 8 to me which is (max),  at one point it said cant find source file or something like that when i did teleport to me command.

also the walking npc's useing waypoints stop walking and attacking monsters.

![2021-04-06 18_49_08-2021-03-31 20_18_46-Minecraft Color Codes — Minecraft Color Codes png - Windows ](https://user-images.githubusercontent.com/26775782/113798816-bfe63600-9708-11eb-9dc2-049035800091.png)
![2021-04-06 18_47_25-2021-03-31 20_18_46-Minecraft Color Codes — Minecraft Color Codes png - Windows ](https://user-images.githubusercontent.com/26775782/113798819-c2489000-9708-11eb-8095-93f8096d1b32.png)

The output of command `/version` on my server is: **(This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 20 version(s) behind)**
The output of command `/version citizens` on my server is: **(2.0.27-snapshot (build 2283))**

**Comment by mcmonkey4eva** [comment]
You have to select the NPC you want to do commands on, eg via `/npc select 0`
