### ISSUE TITLE
Server crashes instantly when I set a waypoint

### ISSUE THREAD

**Issue by ghoodsite** [CitizensDev/Citizens2#2527]
- When I set a /path or /waypoint the server crashes. NPC create ticking problem.
-
- CRASH REPORT (https://pastebin.com/26g9aa8L)
- CITIZEN CONFIG (https://pastebin.com/1gfbBwat)

Mohist version 1.16.5-449 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.4)

Citizens-2.0.27-b2286

**Comment by mcmonkey4eva** [comment]
Citizens only works on Spigot and forks thereof like Paper.
Forge is entirely unsupported.

**Comment by ghoodsite** [comment]
ah ok that makes sense thank you
