### ISSUE TITLE
Npc Dont Look at Players ??? 

### ISSUE THREAD

**Issue by DeTrey5648** [CitizensDev/Citizens2#2528]
I have this Plugin installed , it's start fine  but  /npc look have no Function that NPC dont Look / Rotate to Players 

i have i Correctly installed ;/ 

The output of command `/version` on my server is: **This server is running Paper version git-Paper-549 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2283)
**

**Comment by mcmonkey4eva** [comment]
This bug was already fixed, update: https://ci.citizensnpcs.co/job/Citizens2/
