### ISSUE TITLE
Client side lag after updating citizens

### ISSUE THREAD

**Issue by FlamerAwesome** [CitizensDev/Citizens2#2531]
Updated citizens through 80 or so versions and after restarting servers I would find random chunks that drop my frames to 0 for a couple of seconds. I was told to kill all armor stands after loading all these chunks in and did so multiple times over 3 hours, this fixed the issues temporarily and the lag chunks started coming back. I suspect they started coming back around the time I re used the commands like npc name, npc sit, and any npc commands involving armor stands.
- https://paste.denizenscript.com/View/83291   (Citizens Config)
- https://paste.denizenscript.com/View/83293 (Server Logs)
- https://i.imgur.com/E91AwCJ.png (Versions of server and citizens)
- https://paste.denizenscript.com/View/83295 (Saves yml)
- 160 npcs
- SPECS: AMD Ryzen 5 2600 Six-Core Processor
16 Gb ram
2tb storage (1tb free)

**Comment by mcmonkey4eva** [comment]
We already discussed this on Discord days ago.
- This continues to be unlikely to be related to Citizens
- Your server continues to be significantly outdated
- Your logs continue to be full of errors

Update your server, and fix the errors. Only once those are done can you even consider less-significant topics like client lag
