### ISSUE TITLE
Right-Clicking Entity 

### ISSUE THREAD

**Issue by natalciu** [CitizensDev/Citizens2#2533]
Server Version: Paper git-paper-284 (MC: 1.16.4)
Citizens Version: 2.0.27-SNAPSHOT (build 2269)
https://pastebin.com/8X3TV2G1 <-- My config, I haven't changed anything.

The only sort of error or anything I get from the console is a line saying I disconnected. 
`13.04 22:32:43 [Disconnect] User natalciu has disconnected, reason: Internal Exception: java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/PacketPlayInUseEntity$EnumEntityUseAction`

This happens every time I try to click on the npc, Even if I have a command on it or not. To repeat if possible, I created an NPC and didn't do anything to it, I clicked it and get kicked. After getting kicked I get the NoClassDefFoundErrror, this is probably an issue with my server version, but I am not completely sure.

**Comment by mcmonkey4eva** [comment]
That error is related to MC 1.11 - if the version of Paper and Citizens you gave are correct, that error came from a different plugin.

If in doubt, post your full `logs/latest.log` file, or ask for help on our Discord @ https://discord.gg/Q6pZGSR
