### ISSUE TITLE
Initializing

### ISSUE THREAD

**Issue by ZappySK** [CitizensDev/Citizens2#2534]
I am getting this error when I click to NPC which have commands:
![image](https://user-images.githubusercontent.com/76651966/115162095-c5953180-a0a1-11eb-8cdf-ab064735d67b.png)

**Comment by BehrRiley** [comment]
Please fill out the issue template properly. You can find a copy of the template you ignored here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE

Alternately, feel free to ask for help on the Discord channel instead: https://discord.gg/Q6pZGSR

**Comment by ZappySK** [comment]
[00:11:54 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2297)
[00:11:54 INFO]: Website: http://www.citizensnpcs.co
[00:11:54 INFO]: Author: fullwall

**Comment by BehrRiley** [comment]
**please fill out the entire template**

**Comment by ZappySK** [comment]
Server log: https://paste.denizenscript.com/View/83583
Server version: https://ctrlv.sk/shots/2021/04/19/tQDt.png
Citizens version: https://ctrlv.sk/shots/2021/04/19/OJ41.png
Citizens config: https://paste.denizenscript.com/View/83584
Citizens saves: https://paste.denizenscript.com/View/83585

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
