### ISSUE TITLE
Lag spike with NPC's

### ISSUE THREAD

**Issue by Typheonn** [CitizensDev/Citizens2#2535]
Hi, we get a huge lag spike, apparently caused by citizens.

You can find here all details about versions, ...

The output of command `/version` on my server is: **git-paper-472 (MC: 1.16.5)**
The output of command `/version citizens` on my server is: **2.0.27-SNAPSHOT (build 2165)**

saves.yml : <https://hatebin.com/ihbmrscgmu>
config.yml : https://pastebin.com/raw/JPdAGvn5
Spark sampler : <https://spark.lucko.me/2isWI6uqLt>

**Comment by mcmonkey4eva** [comment]
This was a past bug that was already fixed months ago. Update: https://ci.citizensnpcs.co/job/Citizens2/
