### ISSUE TITLE
Hex color code not working if name <= 16 characters

### ISSUE THREAD

**Issue by Pugabyte** [CitizensDev/Citizens2#2537]
`/npc rename &#4cc9f0J` -> black text
`/npc rename &#4cc9f0JJ` -> black text
`/npc rename &#4cc9f0JJJ` -> blue text

![image](https://user-images.githubusercontent.com/12417961/115724238-c4d4f780-a34e-11eb-9fff-3463823282f8.png)

**Comment by mcmonkey4eva** [comment]
This I think happens because:
https://github.com/CitizensDev/CitizensAPI/blob/6959b80be2b17d01fdab4b2b0d814bc1004e97cd/src/main/java/net/citizensnpcs/api/npc/AbstractNPC.java#L353-L358
This code checks for `&x` but the actual name contains `§x` (aka `ChatColor.COLOR_CHAR` instead of `&`)

**Comment by mcmonkey4eva** [comment]
Likely fixed by https://github.com/CitizensDev/CitizensAPI/commit/a1a8d152671a8e34e8c0237fb0129d2d0f0d12bc for Citizens build 2298+ from https://ci.citizensnpcs.co/job/Citizens2/
