### ISSUE TITLE
Horse Type Not Leashable

### ISSUE THREAD

**Issue by connorgillespie** [CitizensDev/Citizens2#2538]
Description:
When setting a horse type citizen to leashable, the leash will not connect to the entity and will result in the horse standing on it's hind legs and the leash event being cancelled.

Citizen:
I created a citizen using the following command. /npc create horse --type horse

Server Version:
git-Paper-582 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Citizens Version:
Citizens version 2.0.27-SNAPSHOT (build 2296)

**Comment by fullwall** [comment]
Is the horse vulnerable too?

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply

**Comment by KingsSack** [comment]
I had this same problem

**Comment by mcmonkey4eva** [comment]
@KingsSack please post a new issue or ask on Discord @ https://discord.gg/Q6pZGSR in the Citizens channel
