### ISSUE TITLE
Npc nameplate cant be disabled for non-living entity types

### ISSUE THREAD

**Issue by zozer** [CitizensDev/Citizens2#2541]
Non-living entities cant have their nameplate disabled with /npc name, the command returns a message saying the entity must be a living entity

steps to replicate:
/npc create myitem --type dropped_item
/npc name

The output of command `/version` on my server is: git-Paper-529 (1.16.5)
The output of command `/version citizens` on my server is: 2.0.27 (build 2296)

**Comment by mcmonkey4eva** [comment]
Simple case of
https://github.com/CitizensDev/Citizens2/blob/c9d8bad4f857e2075dc68af84f9dfb62ddcd3401/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L1318-L1319

`livingEntity = true` should be removed.

Already confirmed through Denizen that everything works as expected for dropped_item entities and thus the livingEntity requirement is purely redundant.
