### ISSUE TITLE
Question/Help with npcs pathing

### ISSUE THREAD

**Issue by Whxtealex** [CitizensDev/Citizens2#2542]
The output of command `/version` on my server is: **1.16.4 git Paper**
The output of command `/version citizens` on my server is: **2.0.27-Snapshop**

Hey so when you do /npc path it will make an path for the npc but my question issue is how can i stop him for like 5 seconds do an task (Like fishing with denizens) and than he goes his way again.

**Comment by mcmonkey4eva** [comment]
To stop *and do a custom task* that'd be the domain of a Denizen script.

To just stop and that's about it, or some very basic motions, you can look through `triggers` inside of `/npc path`
