### ISSUE TITLE
It show a error why 

### ISSUE THREAD

**Issue by Aditya471777** [CitizensDev/Citizens2#2545]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

**Comment by Aditya471777** [comment]
Why

**Comment by BehrRiley** [comment]
Please fill out the issue template properly. You can find a copy of the template you ignored here: https://github.com/CitizensDev/Citizens2/blob/master/ISSUE_TEMPLATE

Alternately, feel free to ask for help on the Discord channel instead: https://discord.gg/Q6pZGSR
