### ISSUE TITLE
Command no reaction 

### ISSUE THREAD

**Issue by AirantoStinks** [CitizensDev/Citizens2#2546]
Hello, I have a server on 1.16.5 I downloaded citzens but when I write the command there is no reaction, no message, nothing
I have tried to install other versions and the same all the time, can you help me as I need your plugin very much.
my log:
[latest.log](https://github.com/CitizensDev/Citizens2/files/6445694/latest.log)
![image](https://user-images.githubusercontent.com/83864341/117536202-fe1d9080-aff9-11eb-8c93-785b0766f2f5.png)
![image](https://user-images.githubusercontent.com/83864341/117536454-602ac580-affb-11eb-9d8d-e2c040dcb33e.png)

My citizens version is 2.0.27-SNAPSHOT (bulid 2307)
In my config is only :# Citizens Configuration
Please help

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
