### ISSUE TITLE
Prevent NPCs From Speaking To Other NPCs With "/NPC Text"

### ISSUE THREAD

**Issue by FelDragon15** [CitizensDev/Citizens2#2553]
Citizens currently speak to other npc's that either are close to them or run past them, and I would like to be able to have an option to them that allows you to make it so they will only say their texts to players. Currently I have guards that patrol and the npc's say all of their conversations to the guards when they are only meant to be said to the players.

**Comment by mcmonkey4eva** [comment]
Added via https://github.com/CitizensDev/Citizens2/commit/22fd1da0c833b925d806b18b30cd79b953a16f0a for build 2315+ on https://ci.citizensnpcs.co/job/Citizens2/
