### ISSUE TITLE
[Citizen API] Why occur this error?

### ISSUE THREAD

**Issue by gayakps** [CitizensDev/Citizens2#2554]
The output of command /version on my server is: (1.16.5-R0-1-SHAPSHOT / git-paper-557 )
The output of command /version citizens on my server is: (Citizen version (build 2310) - 2.0.27)

[crash-2021-05-19_15.11.38-server.txt](https://github.com/CitizensDev/Citizens2/files/6506268/crash-2021-05-19_15.11.38-server.txt)

Situation : In server npcs are 3, they are use two trait ( following, custom trait( attack another entity ) ) but two npcs are following me but another one npc isn't follow to me so I'm teleport to another npc ( no following ) after 1 seconds server has crashed and then close server

**Comment by mcmonkey4eva** [comment]
That is not a relevant server log. The actual error is in your server log, not the crash report file.

**Comment by gayakps** [comment]
Nothing errors, after occur errors, server was closed

**Comment by mcmonkey4eva** [comment]
It is not possible for a crash report to generate without an error in the actual server log.
