### ISSUE TITLE
Error Console + Problem with plugin Citizens CMD

### ISSUE THREAD

**Issue by SNokerYT** [CitizensDev/Citizens2#2556]
- I'm using CitizensCmd plugin When I Relode plugin Citizens, all the saves command file on Citizenscmd has been deleted after reload Citizens plugin
- Link to server log | https://pastebin.com/z7yNgeiA
- **Spigot and Citizens versions 2.0.27-snapshot (build 2269) | I also tried the last version Citizens-2.0.27-b2315 but it's the same problem

- FOR LAG RELATED ISSUES: please include server specs, number of NPCs -> 30
-->

The output of command `/version` on my server is: **This server is running Paper version git-Paper-662 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 52 version(s) behind
Previous version: git-Paper-655 (MC: 1.16.5)**
The output of command `/version citizens` on my server is: **Citizens Version 2.0.27-SNAPSHOT (build 2269)**

**Comment by mcmonkey4eva** [comment]
- Update Citizens https://ci.citizensnpcs.co/job/Citizens2/
- Update Paper
- Remove `CitizensCMD` https://wiki.citizensnpcs.co/NPC_Commands

**Comment by SNokerYT** [comment]
i have been updated Citizens | I have been updated Paper | I removed plugin citizensCMD
but there still another weird problem after 3 hours or 7 hours this problem comes some NPC changed names to codes like this give 
and to fix this issue i use command | /citizens Reload 
![bug3dwadwdwيص](https://user-images.githubusercontent.com/68678154/119252895-e8d66380-bbae-11eb-88aa-1ab25d00bf83.gif)

**Comment by mcmonkey4eva** [comment]
- Don't use `/citizens reload`
- That gif you showed clearly indicates you have errors in your server log... so, post your new server log with those errors in it, that's probably related to the origin of the problem.
- That name you're seeing is the internally generated name with the NPC's uuid in it, which is used to make a unique entry for the NPC in minecraft's scoreboard teams. The scoreboard team is then used to do things like hiding the nameplate. If you have other plugins or systems messing with scoreboards, scoreboard teams, or especially packet-based things, those might be disrupting something.
