### ISSUE TITLE
My tab is keep flashing after i set some npcs

### ISSUE THREAD

**Issue by Nibaalxd** [CitizensDev/Citizens2#2557]
- issue: after i set some of nps, my tab is keep flashing every 3 sec or something and it's annoying
- https://pastebin.com/EgyUDRW4
-->

The output of command `/version` on my server is: **This server is running Paper version git-Paper-391 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-1618 (MC: 1.12.2)
You are running the latest version**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2217)
Website: http://www.citizensnpcs.co
Author: fullwall**

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Frequently_Asked_Questions#Why_are_NPCs_showing_up_in_the_tablist.3F
