### ISSUE TITLE
Just a small question.

### ISSUE THREAD

**Issue by LewisRad** [CitizensDev/Citizens2#2558]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

I have read the above, but this is not an issue or anything, just a small question regarding the plugin.

Is it possible to add custom sounds to the NPCs? Im trying to link them with quests using custom characters and would like the player to hear a custom sound if they click on them! Could be fun!

Thanks, hope this didn't waste any time, I was just curious!

**Comment by mcmonkey4eva** [comment]
Use https://wiki.citizensnpcs.co/NPC_Commands to add a playsound command when clicked
