### ISSUE TITLE
NPC navigator lookat is broken

### ISSUE THREAD

**Issue by Mwthorn** [CitizensDev/Citizens2#2559]
When using Denizen command to navigate the NPC:
`/ex walk auto_range lookat:<player.cursor_on> <player.location>`
The NPC does not look at the direction specified. The NPC only looks in the direction it is walking (default).

The output of command `/version` on my server is: Paper version git-Paper-670 (MC: 1.16.5)
The output of command `/version citizens` on my server is: 2.0.27-SNAPSHOT (build 2315)
Logs: https://paste.denizenscript.com/View/85058

The issue is related to:
npc.getNavigator().getLocalParameters().lookAtFunction(nav -> lookat);
https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/scripts/commands/entity/WalkCommand.java#L199

object.getNavigator().getLocalParameters().lookAtFunction().apply(object.getNavigator());
https://github.com/DenizenScript/Denizen/blob/dev/plugin/src/main/java/com/denizenscript/denizen/objects/NPCTag.java#L1148

**Comment by mcmonkey4eva** [comment]
When I tested myself, the NPC indeed looks in its walking direction, and then when it stops moving it snaps to face the lookAt target.

**Comment by fullwall** [comment]
This is tricky because navigation is tied to yaw now.

**Comment by Aseeef** [comment]
I just spent the last 3 hours investigating this stumbling on this issue myself. Do we have any updates on this?

**Comment by Aseeef** [comment]
Was there a version when this was working?

**Comment by mcmonkey4eva** [comment]
Closing this in favor of the more modern copy of it https://github.com/CitizensDev/Citizens2/issues/2814
