### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JannikCrafter09** [CitizensDev/Citizens2#2560]
Error
![Bild_2021-05-29_191421](https://user-images.githubusercontent.com/82037628/120078940-11c88e00-c0b2-11eb-95e3-a4e0c370df57.png)

The output of command `/version` on my server is: This server is running CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT
The output of command `/version citizens` on my server is:
 [19:13:20] [Server thread/INFO]: Citizens version 2.0.24-SNAPSHOT (build 1605)
[19:13:20] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[19:13:20] [Server thread/INFO]: Authors: aPunch and fullwall
>

**Comment by mcmonkey4eva** [comment]
Current Citizens builds are at https://ci.citizensnpcs.co/job/Citizens2/ or https://www.spigotmc.org/resources/citizens.13811/ 

The build you downloaded is from years ago. The Bukkit project shut down in 2014, no links related to Bukkit or on Bukkit's old website are going to be remotely recent.
