### ISSUE TITLE
Error with WildStacker

### ISSUE THREAD

**Issue by WarnDangerous** [CitizensDev/Citizens2#2561]
The output of command `/version` on my server is: **c2me-port-31 of yatopia (it's based on paper 1.16.5-760)**
The output of command `/version citizens` on my server is: **Citizen version 2.0.27- build 2310**

Hello,

Since some weeks (maybe month), I got an error on server stop with WildStacker.
I contacted the dev of WildStacker and he told me the error was from Citizen, and it's you who have to fix the error.
I searched if the error has been reported before (by searching "wildstacker" in ticket list, also on closed one) and I didn't find any ticket on it, so I decide to report the error :

Link of the error :
https://pastebin.com/fzx69pv3
(I took it from logs, and even in logs there is the  "... 15 more")

I got this error ALSO on paper 1.16.5 , so it's not an issue related to yatopia.

**Comment by mcmonkey4eva** [comment]
- Need full `logs/latest.log` file, not a snippet.
- Test on Spigot or Paper, not a fork.
- Consider asking for support on Discord @ https://discord.gg/Q6pZGSR

**Comment by WarnDangerous** [comment]
Here is my latest log :
https://hastebin.com/ipoquvijoj.sql

Note : I'm on ONLINE_MODE, but as I use velocity, I need to set online_mode to false, as it's velocity that manage the online_mode part.

Note 2 : I tried on paper, and it's the same, WildStacker's dev can confirm it's not related to yatopia (in the logs it's on yatopia because I don't want to switch to paper, but I tried it some weeks ago, and the error also appeared on paper)

**Comment by mcmonkey4eva** [comment]
This appears to be a WildStacker issue. It's trying to make calls to the CitizensAPI after the server has already shut down.

There are two primary issues in WildStacker here, which I'll tag the WildStacker dev @OmerBenGera to see:

----

First:

You have this code: https://github.com/BG-Software-LLC/WildStacker/blob/132ad074d355cfaeacfb7c3a1264a661ae76989d/src/main/java/com/bgsoftware/wildstacker/hooks/CitizensHook.java

```java
        if(!CitizensAPI.hasImplementation())
            CitizensAPI.setImplementation(JavaPlugin.getPlugin(Citizens.class));
```

This is actively breaking code. You cannot do that.

You should probably replace it with just:
```java

        if(!CitizensAPI.hasImplementation())
            return false;
```

-----

Second:

The actual reason this is breaking, and the actual solution, is that WildStacker does not `softdepend` on Citizens, and therefore is loading before and unloading after. If a `softdepend` on `Citizens` is added to the `plugin.yml`, it should fix the error that was reported here.

**Comment by OmerBenGera** [comment]
Sorry for not responding for a long time
I pushed a new version that should fix the issues, let me know if it works now

**Comment by WarnDangerous** [comment]
It works. 

Thanks
