### ISSUE TITLE
Phantoms are slowly moving over time

### ISSUE THREAD

**Issue by Xemorr** [CitizensDev/Citizens2#2562]
Phantom NPCs are slowly moving over time, you can't see them moving with the human eye, but you just notice later that they've moved forward.

The output of command `/version` on my server is: **- This server is running Tuinity version git-Tuinity-"2683c77" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind**
The output of command `/version citizens` on my server is: **- Citizens version 2.0.27-SNAPSHOT (build 2314)**

**Comment by fullwall** [comment]
Does the latest build help? (try on 1.16.5 for now as 1.17 will be buggy)

**Comment by Xemorr** [comment]
I'll give it a test, thanks fullwall!

**Comment by Xemorr** [comment]
Left it 21 hours, and I don't _think_ it has moved, it's hard to tell honestly.

**Comment by fullwall** [comment]
Well, I'll close this for now then. If it moves again then reopen this issue.
