### ISSUE TITLE
FATAL]: Error executing task on Server

### ISSUE THREAD

**Issue by archroot** [CitizensDev/Citizens2#2563]
![изображение](https://user-images.githubusercontent.com/41123605/121504311-9688a580-c9ea-11eb-8521-472077ad734e.png)

Paper version git-Paper-775 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Citizens version 2.0.27-SNAPSHOT (build 2317)

**Comment by mcmonkey4eva** [comment]
This looks like something related to whatever that "bot" plugin is moreso than Citizens.
