### ISSUE TITLE
NPC name supporing placeholders. So the skin can change along with leaderboard placements

### ISSUE THREAD

**Issue by CrispyDairy** [CitizensDev/Citizens2#2564]
A feature, where for example: I give an npc the name %playtime_top_1_name%, their name becomes the output of that placeholder. Currently, when I do that, their name becomes "Armor Stand".

The output of command `/version` on my server is: **(2.0.27- SNAPSHOT**
The output of command `/version citizens` on my server is: **(Purpur - 1163 1.16.5)**

**Comment by mcmonkey4eva** [comment]
Placeholders are supported.

There's a bunch of `top` style placeholders people have been trying to use that hit https://wiki.citizensnpcs.co/Frequently_Asked_Questions#My_PlaceholderAPI_Placeholder_Works_In_Chat.2C_But_Not_On_An_NPC for some reason.
