### ISSUE TITLE
Following NPC becoming invisible

### ISSUE THREAD

**Issue by Simblizok** [CitizensDev/Citizens2#2565]
Hello,

I have a small issue  with my following NPCs. When a player disconnect all the NPCs that are following someone become invisible (But they are still here). Sometimes it happens with teleportation but not all the time : The NPC became invisible to me (he was following me) but not to other people. The only way to make it appear is to despawn and spawn again.

Here is my logs : https://pastebin.com/nQBCL6i3
And here is my config :https://pastebin.com/9fsW9NV9

My version of spigot :
This server is running Paper version git-Paper-768 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 8 version(s) behind
Previous version: git-Paper-186 (MC: 1.16.2)

And my version of Citizens
![image](https://user-images.githubusercontent.com/85732225/121656503-d65d9480-ca9f-11eb-90ff-d9f79b636017.png)

Thanks in advance!

**Comment by mcmonkey4eva** [comment]
Closing as invalid, pastebin links lead nowhere.
