### ISSUE TITLE
Lookclose Issue on 1.17

### ISSUE THREAD

**Issue by lilingxi01** [CitizensDev/Citizens2#2567]
The output of command `/version` on my server is: **CraftBukkit 3117-Spigot (MC: 1.17) 1.17-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **2.0.28-SNAPSHOT build 2321**

Problem:
The `lookclose` feature works improperly on this build.

When I walk around the NPC (just newly created with `lookclose` on, no any other setting) clockwise, his head will go 360 degrees (following me) without turning his body (which he should do).

When I walk around him counterclockwise, his head and body cannot turn correctly and will be stuck at about 30 degrees left and shaking his head until I go back to an angle that he can turn to.

There is no log generated on the server console.

Screen record: https://streamable.com/4yinxs

**Comment by mcmonkey4eva** [comment]
Replicated this myself on `Citizens version 2.0.28-SNAPSHOT (build 2325)` + `CraftBukkit version 3133-Spigot-66f9d3c-3fa79d3 (MC: 1.17)`
https://gfycat.com/gargantuansourhylaeosaurus
https://gfycat.com/tartgiddydeer

The internals for how head/body yaw work in minecraft seem to have significantly changed in 1.17.

**Comment by fullwall** [comment]
Should be back to 1.16 behaviour as of latest build.
