### ISSUE TITLE
Can't remove text from npc

### ISSUE THREAD

**Issue by Nononitas** [CitizensDev/Citizens2#2568]
The output of command `/version` on my server is: Paper 1.16.5-777
The output of command `/version citizens` on my server is: Citizens-2.0.28-b2325

Problem:
You can't acutally remove the speaking text from npcs:
For example if you do
/npc sel
/npc text
remove 
0
exit
/citizens save
/citizens reload /citizens reload or restart the server

the text will be regenerated. So there is no possibility to remove the npc text.

**Comment by mcmonkey4eva** [comment]
`/trait text` to remove the text trait entirely if you don't want it at all

**Comment by Nononitas** [comment]
Thank you didn't find that anywhere
