### ISSUE TITLE
Problems with NPCs

### ISSUE THREAD

**Issue by FraazT0** [CitizensDev/Citizens2#257]
There are some problems with my NPCs:
1. If I walk away from an NPC, when I return he hasn't the skin or it disappears. I avoided the problem with the command /citizens reload. But now I can't do this.
2. Some days ago, I could create NPC adlso with the first problem. Now, when I create a new NPC, whenever Citizens reload (for server restart or /citizens reload) it disappears. No, it's not a lag problem, the NPC isn't show on /npc list.
I use Spigot 1.8.1 (BuildTools build #27) and Citizens version 2.0.14 (alpha 1 for MC 1.8.1).
I have also some Citizens traits: Alchemist, Builder, Bloacksmith, Denizen and Sentry.

**Comment by SjamonDaal** [comment]
i got the same problem i use spigot 1.8

**Comment by SjamonDaal** [comment]
I have the perfect fix!
Just found it by myself,
Download the newest SNAPSHOT version from Citizens2
WARNING! COPY YOUR ORIGINAL SERVER DATA!
Dev Page: http://ci.citizensnpcs.co/job/Citizens2/
Newest Snaphot: http://ci.citizensnpcs.co/job/Citizens2/1212/

**Comment by mcmonkey4eva** [comment]
Yeah need to update to fix 90% of bugs.
