### ISSUE TITLE
1.17 - NPC Pathing Glitches Out With new-finder false

### ISSUE THREAD

**Issue by LeftBoob1949** [CitizensDev/Citizens2#2572]
When using the /NPC path command don't walk in a straight line and go left to right instead and sometimes even stand in a certain spot and spiral 

![2021-06-19_17 21 35](https://user-images.githubusercontent.com/86170352/122655753-f259d980-d122-11eb-9a2b-8b4932ce8c7c.png)
![2021-06-19_17 21 19](https://user-images.githubusercontent.com/86170352/122655755-f2f27000-d122-11eb-9181-7805a107e2c5.png)

Server log: https://pastebin.com/EfsX1Ymm 
Citizens config: https://pastebin.com/j4xr2JS3

Video Proof: https://www.youtube.com/watch?v=JIb_bdQJXr4

**Comment by mcmonkey4eva** [comment]
Did my own testing, verified this happens with `/npc pathopt --use-new-finder false`
works fine with `true`

**Comment by fullwall** [comment]
Bit better now. Still seems to be moving left and right too much - yaw change?
