### ISSUE TITLE
NPC's with pathing don't load

### ISSUE THREAD

**Issue by salt55** [CitizensDev/Citizens2#2573]
After updating from 1.16.5 and downloading the latest build of citizens for 1.17, NPC's that have a path just don't load. Every other NPC loads perfectly fine.
Also when I try to create a new NPC and give it a path, the moment I place a waypoint the NPC just disappears.

Server logs: https://paste.gg/p/anonymous/3a569cee218142789de71bd564c76249
Citizens config.yml: https://paste.gg/p/anonymous/311a4b832e9d4c29bb6728624e7bfdad
Citizens saves.yml: https://paste.gg/p/anonymous/c90f6712dae0427489bdb08061d8e619

The output of command `/version` on my server is: **Paper-1.17-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **2.0.28-SNAPSHOT (build 2328)**

**Comment by mcmonkey4eva** [comment]
Please test with Spigot for the time being. That's more likely to be a bug from Paper's initial 1.17 update work rather than something wrong in Citizens.
