### ISSUE TITLE
hologram default-line-height bug

### ISSUE THREAD

**Issue by p82183645** [CitizensDev/Citizens2#2576]
"hologram default-line-height"   This feature modification did not work
npc name will not change
![image](https://user-images.githubusercontent.com/5382252/123015103-39352100-d3fa-11eb-9c71-faa3afd79109.png)

![image](https://user-images.githubusercontent.com/5382252/123015021-07bc5580-d3fa-11eb-8884-070d5220a1ee.png)
![image](https://user-images.githubusercontent.com/5382252/123015031-0db23680-d3fa-11eb-9822-c365c0d6ca04.png)

**Comment by mcmonkey4eva** [comment]
That's the *default*. That is not how to alter existing NPCs.

Use `/npc hologram lineheight 0.8` (or whichever number) to edit the lineheight on an NPC.

**Comment by p82183645** [comment]
@mcmonkey4eva  can add change default?

**Comment by mcmonkey4eva** [comment]
The default is the value in the config.
The one applied to any given NPC is configured via command.
Newly created NPCs receive the default value. Pre-existing NPCs do not.

**Comment by p82183645** [comment]
> The default is the value in the config.
> The one applied to any given NPC is configured via command.
> Newly created NPCs receive the default value. Pre-existing NPCs do not.

I mean to change the holo of the default NPC name
