### ISSUE TITLE
Problem with BetonQuest

### ISSUE THREAD

**Issue by p82183645** [CitizensDev/Citizens2#2577]
Use BetonQuest conversation to happen

error:  https://pastebin.com/bGU6Gqfq

![image](https://user-images.githubusercontent.com/5382252/123016064-62ef4780-d3fc-11eb-9e18-1f5fb483c3ae.png)
![image](https://user-images.githubusercontent.com/5382252/123016071-65ea3800-d3fc-11eb-9c66-5876c5bf7cdd.png)

**Comment by mcmonkey4eva** [comment]
That is a BetonQuest problem, report to them not us

**Comment by p82183645** [comment]
This happened when I updated the citizen plugin
