### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by kalebchoi** [CitizensDev/Citizens2#2579]
This is a suggestion/feature request.

I would like to see special velocity proxy support in the future. Equivalent to the bungee support

**Comment by fullwall** [comment]
I understand velocity supports plugin messaging now same as bungee? Please reopen if you wanted anything else

**Comment by kalebchoi** [comment]
I forgot if i got this working or not. I no longer use this plugin. I may of given up and just used a serverselector plugin. Idk, i don't remember. Though, a bit of testing wouldn't hurt
