### ISSUE TITLE
Bought but doesnt allow me to download

### ISSUE THREAD

**Issue by Yuzi1221** [CitizensDev/Citizens2#2582]
- I bought Citizens 2.0.28 on Spligot and it did go through but its asking me to pay again
![image](https://user-images.githubusercontent.com/57733446/123501922-b93bd080-d61e-11eb-9c30-eab81e0b96a3.png)
![image](https://user-images.githubusercontent.com/57733446/123501951-ebe5c900-d61e-11eb-91cb-95251d515db3.png)
My username is: SkyNixeee
- https://pastebin.com/blah
- NONE DONT OWN CITIZEN but 2.0.28

The output of command `/version` on my server is: NONE DONT OWN CITIZENS 1.16.5
The output of command `/version citizens` on my server is: NONE DONT OWN CITIZEN 2.0.28

**Comment by mcmonkey4eva** [comment]
You can download Citizens for free from https://ci.citizensnpcs.co/job/Citizens2/
The spigot page is just for donations, as the readme explains
