### ISSUE TITLE
Villager NPC glitch when change biome

### ISSUE THREAD

**Issue by chochoco4777** [CitizensDev/Citizens2#2583]
The output of command `/version` on my server is: 1.8.8
The output of command `/version citizens` on my server is: 2.0.28-SNAPSHOT (build 2330)

https://www.youtube.com/watch?v=nmRhtF4wQMk

Changing the biome and right-clicking on the Villager NPC does not automatically do this.

**Comment by mcmonkey4eva** [comment]
A: Whatever is going on has nothing to do with Citizens
B: https://wiki.citizensnpcs.co/Minecraft_1.8
