### ISSUE TITLE
Cannot hide player type NPC name

### ISSUE THREAD

**Issue by thanhthanhthanhthanh** [CitizensDev/Citizens2#2584]
Version:
```
Citizens version 2.8.28-SNAPSHOT (build 2330)
```
How can I hide player type NPC name with ``/npc name -h``? Is it impossible to hide it? 
I encounter an odd bug that I accidentally able to hide NPC nametag by messing around with ``/npc rename``. Sadly, I cannot reproduce it now.

**Comment by thanhthanhthanhthanh** [comment]
I think I figure it out.
I'm able to hide NPC name after renaming and hiding NPC name repeatedly until it decided to work.
Any ideas why this is happening? 

Thank you.

**Comment by mcmonkey4eva** [comment]
it's `/npc name` without the `-h`
