### ISSUE TITLE
Citizen taking up 50% tick

### ISSUE THREAD

**Issue by NightLife-SG** [CitizensDev/Citizens2#2588]
- Link to server log & Citizens config (using e.g. pastebin.com)
config https://pastebin.com/RbnZJVnx
saves https://pastebin.com/dUgBiifY
- FOR LAG RELATED ISSUES: https://timings.aikar.co/?id=513d59fa196b43b99405006cde4d085a#plugins
-->

The output of command `/version` on my server is: **paper 1.17 build 70**
The output of command `/version citizens` on my server is: **v2.0.28-SNAPSHOT (build 2330)**

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
