### ISSUE TITLE
Is it possible to make player npc names hide when not looking at them?

### ISSUE THREAD

**Issue by intangir** [CitizensDev/Citizens2#259]
mob and villager npc names seem to disappear when they are too far away or your not looking at them

is it possible to do this with player npc names also?

**Comment by calico-kid** [comment]
i do believe this can be done with /npc name or /npc invisible not sure which one tho.

**Comment by intangir** [comment]
hrm i tried /npc name, it says toggled nameplate visibility, but i can't tell what it actually did

the behavior of it seems unchanged

think it has to be restarted afterward?

**Comment by calico-kid** [comment]
the nameplate toggle is to turn off the nameplate unless you are looking at the npc

**Comment by intangir** [comment]
thats what im looking for. doesn't seem to work though

not on villager npcs, nor player npcs. no change seems to occur

does it work for  you?

if so what version of spigot are you using? wonder if there is a difference

**Comment by calico-kid** [comment]
there have been some issues with citizens as of late... thats not a widly used feature as far as i know. so it might have been overlooked... i will test on the latest spigot build soon tho to see also try a citizens reload after doing a citizens save once you toggle the nameplate. it may be that the npc needs to reload for it to take effect

**Comment by intangir** [comment]
i tried reloading

it looks like toggling it toggles it ON, the extra data saved with the npc is nameplate-visible: true, where i guess default is not

there is no change to the behavior of it though

maybe its not an option in the newer versions of spigot/bukkit

**Comment by mcmonkey4eva** [comment]
This is not directly possible. You can, however, mount an invisible entity on top of the player NPC and use that to hide the nameplate, and unmount / remount as needed to show/hide it... far from an ideal solution, but ... Mojang's doings, not ours, sorry.

**Comment by Hkliese** [comment]
invisible armor stand with the name

**Comment by Platinteufel** [comment]
Any news here? Is there any feature that the player can see NPC names only if he's near to them? (lets say in an area of 10 blocks)
Thanks in advance!

**Comment by madtomic** [comment]
This will certainly make the role playing experience better. As of now, player can see npc nameplate through solid blocks. It kinda of defeat the reason of having names in the first place.
