### ISSUE TITLE
1.17 - Axolotl Variant Command & Trait

### ISSUE THREAD

**Issue by LegendSpard4** [CitizensDev/Citizens2#2592]
Hello, could you add a command to generate a blue-type axolotl NPC?

**Comment by mcmonkey4eva** [comment]
Specifically a 1.17 trait + command for https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Axolotl.Variant.html

**Comment by mcmonkey4eva** [comment]
Was added via https://github.com/CitizensDev/Citizens2/commit/3a50ad5d85a37fc2515ed62d7ce260701fb43b1d as `/npc axolotl --variant blue` available in build 2345+ from https://ci.citizensnpcs.co/job/Citizens2/
