### ISSUE TITLE
/npc playerlist not creating vanilla mobspawns in 1.16.x, 1.17.x, and previous versions

### ISSUE THREAD

**Issue by CoderStone** [CitizensDev/Citizens2#2601]
I am currently using citizens for the goal of fully afkable mob farms, whether that be the NPC actively killing the mobs, or the NPC being used to afk mob farms.
I located the command /npc playerlist which is supposed to add the npc as a player.
This should in theory trigger mob spawning behavior, but it does not.
The only thing /npc playerlist changes in mob spawning seems to be NPC interaction with mob spawners, where NPCs afking by mob spawners will actually spawn mobs, and will attack them with Sentinel.
There are no errors in the logs, and my citizens config is default.
![image](https://user-images.githubusercontent.com/34324909/125027609-715a8600-e0c1-11eb-95e0-09c39bb20ebd.png)
![image](https://user-images.githubusercontent.com/34324909/125027630-7c151b00-e0c1-11eb-9e81-9ef4387655db.png)
Issue is reproducible on paper, tuinity, spigot, and purpur.

The output of command `/version` on my server is: **This server is running Purpur version git-Purpur-1260 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 444413b on HEAD)
You are running the latest version
Previous version: git-Purpur-1258 (MC: 1.17.1)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.28-SNAPSHOT (build 2346)**

**Comment by CoderStone** [comment]
What works: 
![image](https://user-images.githubusercontent.com/34324909/125029605-e4193080-e0c4-11eb-9b70-85b85a49942b.png)
NPCs added to the playerlist and left by mob spawners will trigger the mob spawner.
What doesn't work:
![image](https://user-images.githubusercontent.com/34324909/125029657-f8f5c400-e0c4-11eb-8f07-195ad3c5cf9d.png)
Mobs will not spawn surrounding the NPC like it would for a player. Thus, an NPC cannot afk a farm like this, while a console client alt can.

**Comment by CoderStone** [comment]
15 days and no reply to a question. Come on...

**Comment by fullwall** [comment]
Appears to be an issue with the new chunk tracking system. Need to make sure that the player's chunk has a ticket.

**Comment by mcmonkey4eva** [comment]
Probably fixed in https://github.com/CitizensDev/Citizens2/commit/19ee0e2c19714e6348e52c00d88c40c23495f72c in build 2434+ from https://ci.citizensnpcs.co/job/Citizens2/
