### ISSUE TITLE
NPC don't load

### ISSUE THREAD

**Issue by Togglerine** [CitizensDev/Citizens2#2602]
Hello,

Most of NPCs on my serwer didn't load after update server to 1.17.1. 
Error in console pointed only one npc, but after remove it, in console appear other one (this "Chlopiec")
I tried to remove Citizens folder in plugins and put copy instead of new one.

Error log:
https://pastebin.com/adYYGz9w

The output of command `/version` on my server is:  This server is running Paper version git-Paper-95 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0aa0a1d)
You are running the latest version
Previous version: git-Purpur-1260 (MC: 1.17.1)

The output of command `/version citizens` on my server is: Citizens version 2.0.28-SNAPSHOT (build 2346)

What kind of problem may is it?

**Comment by fullwall** [comment]
Update to the latest build
