### ISSUE TITLE
Axolotl NPC can be picked up using a empty bucket (even with worldguard region protecting it)

### ISSUE THREAD

**Issue by cloakfox** [CitizensDev/Citizens2#2604]
As title says can be reproduced on paper 1.17.1 and Citizens v2.0.28-SNAPSHOT (build 2346)

**Comment by cloakfox** [comment]
Is this fixed in latest build?

**Comment by cloakfox** [comment]
> Is this fixed in latest build?

Just saw latest build, thanks!

**Comment by mcmonkey4eva** [comment]
Initial report was resolved by https://github.com/CitizensDev/Citizens2/commit/d515c6b44916e2600cb8e273062e775ed13d87dc
Secondary report was resolved by https://github.com/CitizensDev/Citizens2/commit/65f5d870db1a679fc1a909342df02cbe0de3267b

If you find additional holes in the protection of Axolotl's from Buckets in MC 1.17.x, please comment on this issue, don't make a new one.
