### ISSUE TITLE
NPC Skin Isn't Displaying

### ISSUE THREAD

**Issue by Sparxez** [CitizensDev/Citizens2#2607]
Whenever I create a NPC the skin doesn't seem to load, and /npc skin [name] doesn't show any skins. Previous NPC's have there skin but now it doesn't work. 

config.yml:
https://pastebin.com/HijsmhPY

saves.yml:
https://pastebin.com/qyHqxjGP

The output of command `/version` on my server is: git-PaperSpigot-"4c7641d" (Paper 1.8.8)
The output of command `/version citizens` on my server is: 2.0.28-SNAPSHOT (build 2347)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8 & https://wiki.citizensnpcs.co/Skins

**Comment by Sparxez** [comment]
Understandable I guess but its not like 1.8 is completely unused, its what people need for PvP servers or low usage servers such as lobbies.

**Comment by Sparxez** [comment]
> https://wiki.citizensnpcs.co/Minecraft_1.8 & https://wiki.citizensnpcs.co/Skins

Updating to 1.12.2 paper did not fix this either.
