### ISSUE TITLE
Console Spam on shutdown [1.17.1]

### ISSUE THREAD

**Issue by Ty0ne** [CitizensDev/Citizens2#2610]
When shutting down a Paper 1.17.1 Server it throws this error into Console: https://hatebin.com/nldtqhyncq there does not seem to be any real issues alongside this but it's just Console spam which is always annoying.

Using a Paper Spigot fork called AirPlane (https://airplane.gg/) and the Citizens version is 2.0.28-SNAPSHOT
Config: https://hastebin.com/hukeperuqo.yaml (It's just the default one but here you go I guess)

`/version` Command: https://gyazo.com/030eaaa092063320b57ce789cd5371c4
`/version Citizens` Command: https://gyazo.com/05c3b0aa030496d0851c43379cc777fa

**Comment by mcmonkey4eva** [comment]
Refer to https://github.com/CitizensDev/Citizens2/issues/2609
