### ISSUE TITLE
/NPC Command: Cost Per Command

### ISSUE THREAD

**Issue by GGTEC** [CitizensDev/Citizens2#2611]
add a '--cost' argument to the ' /npc add cmd ' command, to add a cost to run the command, to not get the player's vault if the command is coldown. 

So that if the command is in coldown, don't run the command and don't take the player's vault.

Because it doesn't make sense to charge for the click on the NPC if the command is still in coldown for example

**Comment by fullwall** [comment]
How is this different to /npc command cost ?

**Comment by mcmonkey4eva** [comment]
The request (per Discord) was for when adding multiple commands in `/npc command`, to have different costs per each.

I think stemming from an earlier bug report that if a command is added as eg `-r` (right click only), the costs still applies when the player left clicks, but no command is executed.
