### ISSUE TITLE
Holograms are not colored

### ISSUE THREAD

**Issue by LacoDev** [CitizensDev/Citizens2#2616]
The output of command `/version` on my server is: **![image](https://user-images.githubusercontent.com/41340572/126084193-97fe3700-b266-471a-a62f-b7ac0933ad0f.png)**
The output of command `/version citizens` on my server is: **![image](https://user-images.githubusercontent.com/41340572/126084181-66191acd-83dd-4418-98a3-d928e78c3095.png)**

Holograms are not colored eventough I use the correct color codes.
Serverlog: https://pastebin.com/N3qSRJwD
Citizens Config: https://pastebin.com/Zw5iDfP6

**Comment by mcmonkey4eva** [comment]
Need a full server log, not just a snippet.

Also ideally a screenshot of the NPC you're testing with

**Comment by LacoDev** [comment]
![image](https://user-images.githubusercontent.com/41340572/126151658-6ababf66-25fb-49fa-8885-85090ac84295.png)
Full Serverlog from start to Holgram creation: https://pastebin.com/9u2m17e4

**Comment by LacoDev** [comment]
Same with the Name of the NPC... If the Name contains two or more colorcodes the name turns white.

**Comment by mcmonkey4eva** [comment]
I just, cannot replicate this at all.

Per your log and screenshot, I tested on Spigot 1.16.5 with Optifine 1.16.5
I copy/pasted your exact command `/npc hologram add &cLevel 1 &aFriedlich`

And it works how it should:
![img](https://i.alexgoodwin.media/i/misc/97f565.png)

I don't know what to tell you, I have genuinely no idea how that would have happened. I've never seen anything like this reported before either.

**Comment by LacoDev** [comment]
Could it be possible that it is a client side error? I used Badlion Client for MC 1.16.5

**Comment by mcmonkey4eva** [comment]
Quite possible, yes. Test with vanilla or optifine.

**Comment by LacoDev** [comment]
It actually was a client  sided problem with Badlion Client... I switched to Optifine 1.16.5 and it worked fine. Sorry for bothering you with this issue...
I really enjoy your plugin keep up the great work!
