### ISSUE TITLE
Error message in console

### ISSUE THREAD

**Issue by Titigre** [CitizensDev/Citizens2#2617]
Hi, I got a lot of error message in my console. In particulary those :
[Tue, 20. Jul 2021 14:17:52 UTC ERROR] Could not pass event EntityPotionEffectEvent to Shopkeepers v2.12.0
[Tue, 20. Jul 2021 14:17:52 UTC ERROR] Could not pass event EntityTargetLivingEntityEvent to Shopkeepers v2.12.0
[Tue, 20. Jul 2021 14:17:52 UTC ERROR] Could not pass event EntityDamageEvent to Shopkeepers v2.12.0
[Tue, 20. Jul 2021 14:17:37 UTC ERROR] [Citizens] The trait npcdestinations failed to load for NPC ID: 175.
Do you know How can i fix it ? My server is in 1.16.5. And there is my save.yml if needed Thanks for your help :
[save.yml.txt](https://github.com/CitizensDev/Citizens2/files/6849057/save.yml.txt)

**Comment by mcmonkey4eva** [comment]
Need your full `logs/latest.log`, not just random single lines
