### ISSUE TITLE
Problems with BetonQues

### ISSUE THREAD

**Issue by p82183645** [CitizensDev/Citizens2#2619]
Problems with BetonQuest  , happen on click npc conversations
Please check for this error. **This is a problem caused after the citizens update**
after testing

![image](https://user-images.githubusercontent.com/5382252/126722906-7880fea6-4995-4daf-8b65-275d7dc5665f.png)
![image](https://user-images.githubusercontent.com/5382252/126723084-113a760f-56a7-4484-a5b9-b65e010cb457.png)

The output of command `/version` on my server is: **(PLEASE FILL IN)**
![image](https://user-images.githubusercontent.com/5382252/126722919-3ce02259-22e8-4b11-80cb-5f12a922734e.png)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
![image](https://user-images.githubusercontent.com/5382252/126722929-bebe90bc-af96-4301-9e65-46d40ca311a7.png)

**Comment by mcmonkey4eva** [comment]
report betonquest errors to betonquest

**Comment by p82183645** [comment]
> report betonquest errors to betonquest

Can you see the details? This is caused by updating the citizen
Not caused by BQ

**Comment by fullwall** [comment]
It's caused by betonquest giving invalid location to Citizens.
