### ISSUE TITLE
Fix the Sleeping Animation

### ISSUE THREAD

**Issue by Jannik8500** [CitizensDev/Citizens2#262]
If i making a NPC sleeping in 1.8, the Animation doesn't work. 
The NPC nametag changes to the ground, but the NPC isn't sleeping. 

See here:
![ju648bb](https://cloud.githubusercontent.com/assets/5825853/6428083/d0a98454-bf93-11e4-9d95-f09eec6142bd.png)

**Comment by Morphan1** [comment]
How are you making it sleep?
If it's with /npc sleep, this is a Denizen issue
https://github.com/DenizenScript/Denizen-For-Bukkit/issues

**Comment by Jannik8500** [comment]
Nope, i use the API.

SLEEP {
@Override
protected void playAnimation(EntityPlayer player, int radius) {
PacketPlayOutBed packet = new PacketPlayOutBed(player, new BlockPosition((int) player.locX,
(int) player.locY, (int) player.locZ));
sendPacketNearby(packet, player, radius);
}
}

But in 1.8 does the PacketPlayOutBed not work without a bed at this location. 
I have discussed it with Thinkofdeath in the IRC, and he said that this not work in 1.8.

Watch the following thread, it's the same:
http://www.spigotmc.org/threads/packetplayoutbed.35321/

**Comment by Morphan1** [comment]
This is actually an issue with 1.8... It requires a bed below the NPC. But the bed can simply be removed after having them sleep on it, and they'll continue to sleep

**Comment by mcmonkey4eva** [comment]
As this is a 1.8 MC issue, not our code, I'll close this. Please do comment below if you ideas that could help though!
