### ISSUE TITLE
Hiding NPC Names Also Deletes The Internal Custom_Name Value

### ISSUE THREAD

**Issue by Inxity** [CitizensDev/Citizens2#2620]
To Reproduce:

Create a NPC 
Use /npc name command to set nametag visibility of NPC
It is not making nametag invisible, it DELETES the tag

What do i expect?
It should make the nametag invisible, NOT DELETE the tag

The output of command `/version` on my server is: **![image](https://user-images.githubusercontent.com/61350916/126801535-b21b6573-8cd8-4279-8aa8-d4e4719e1cf5.png)**
The output of command `/version citizens` on my server is: **![image](https://user-images.githubusercontent.com/61350916/126801535-b21b6573-8cd8-4279-8aa8-d4e4719e1cf5.png)**

**Comment by fullwall** [comment]
What do you mean "deletes the tag"

**Comment by Inxity** [comment]
It does not make
CustomNameVisible: false
It makes
CustomName: none -> DELETED

**Comment by mcmonkey4eva** [comment]
are you referring to a mob-typed NPC?

**Comment by Inxity** [comment]
Yes,the NPC is a Wandering Trader. I am using OptiFine Random Entity system, Like when I rename a Wandering Trader to "Mysterious Trader" OptiFine changes Wandering Trader's texture to different texture. Thats why i need names not to be deleted
