### ISSUE TITLE
After npc being used again, the command is not getting executed

### ISSUE THREAD

**Issue by Ramzie55** [CitizensDev/Citizens2#2621]
### **Issue:**
When the player executes a command using the npc, it generates a console error, which is recorded in the server log below; this is a minor issue because the command is not executed again.

### **Server Log:**
https://pastebin.com/yyA0zZb7
### **Citizens Config:**
https://pastebin.com/mg3fCWKs

The output of command `/version` on my server is:
<img width="556" alt="ad54983b84be6e601576e23fc6965b50" src="https://user-images.githubusercontent.com/54107659/126826637-e9e3ec7c-7e0c-4de5-87c5-552de1a01998.png">

I'm using this jar, since it says "custom": https://www.mc-market.org/resources/19660/, which is a fork for 1.8.8 PaperSpigot.

The output of command `/version citizens` on my server is:
<img width="467" alt="c69add4dbb87f0934bafb2024fa12b69" src="https://user-images.githubusercontent.com/54107659/126826654-d2f85e27-c7c2-4464-a1ac-7ffa2fb95224.png">

**Comment by mcmonkey4eva** [comment]
You probably just need to delete and regenerate your config and it'll be fine after.

Ideally also update your server, you're running hacked up versions of 7 year old software https://wiki.citizensnpcs.co/Minecraft_1.8
