### ISSUE TITLE
Make the shields work

### ISSUE THREAD

**Issue by nicoandthe9rs** [CitizensDev/Citizens2#2622]

**Comment by nicoandthe9rs** [comment]
Is it possible to make shields work, because at the moment they dont protect at all

https://pastebin.com/D0Tb9GWv

**Comment by mcmonkey4eva** [comment]
Use Sentinel for NPC Combat - https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md

**Comment by nicoandthe9rs** [comment]
i did but the shields dont work

mcmonkey4eva ***@***.***> escreveu em ter., 27/07/2021 às
03:14 :

**Comment by mcmonkey4eva** [comment]
If something with Sentinel isn't working, ask for support on https://discord.gg/Q6pZGSR in the `#sentinel` channel
