### ISSUE TITLE
Message d'erreur "An internal error occurred while trying to execute this command"

### ISSUE THREAD

**Issue by Bulgui553** [CitizensDev/Citizens2#2624]
Hello, I just installed Citizens on my server and then started it. But when, in game, I execute the command "/citizens" this error massage appears : "an internal error occurred while trying to execute this command"

Le message d'erreur :
![image](https://user-images.githubusercontent.com/88266443/127866930-e3a63a6d-cce5-4f08-9c67-c421d802ba2f.png)

La version du serveur et du plugin :
![image](https://user-images.githubusercontent.com/88266443/127866758-07e2ace9-1d2d-4233-9fe3-250a351d857b.png)

**Comment by mcmonkey4eva** [comment]
You downloaded an ancient copy of Citizens, probably from the log-dead bukkit site (Bukkit shut down in 2014).
Grab a current dev build https://ci.citizensnpcs.co/job/Citizens2/ or the Spigot release build https://www.spigotmc.org/resources/citizens.13811/
