### ISSUE TITLE
NPC needs execute /citizens reload to make trait invisible take effect

### ISSUE THREAD

**Issue by Caishangqi** [CitizensDev/Citizens2#2627]
NPC needs execute `/citizens reload` to make trait invisible take effect
After start the server
![T_56F14S_)GS1@H(W`5V@OO](https://user-images.githubusercontent.com/39553613/128226859-5e039521-f2fd-47dc-a5f9-b077321cf05d.png)

Using `/citizens reload`
![4 (7DD09GVQAIG0I$MSF%ED](https://user-images.githubusercontent.com/39553613/128227063-f5f2a791-95ae-4ee1-ad76-1057ce8d52e3.png)
The NPC had already written the --trait invisible in saves.yml. However, I need to use reload command to let the trait take effect when I restart the server.

The output of command `/version` on my server is: **git-Paper-157 (MC: 1.17.1)**
The output of command `/version citizens` on my server is: **2.0.28-SNAPSHOT (build 2359)**
Java version: **16.0.2 Windows**
Denizen version : **1.2.1-b1744**

**Comment by mcmonkey4eva** [comment]
`The NPC had already written the --trait invisible in saves.yml. ` no part of this is valid.
You can add invisible via `/npc invisible`. Trying to manually add the trait will break it.

Also, Invisible is a trait added by Denizen, so for any future questions or issues related to it, please ask on Discord @ https://discord.gg/Q6pZGSR  in the `#denizen` channel
