### ISSUE TITLE
Issue with the cost function when running a command that has limited uses

### ISSUE THREAD

**Issue by Psykrot** [CitizensDev/Citizens2#2628]
- There seems to be an issue with the cost function when running a command that has limited uses. For example, I set it up so that an NPC gives you a permission when you give them 12 x Eye of Ender, and use the "--n 1" argument to limit it to one use. The problem is after you use the command once and try clicking again, the NPC still takes 12 Eye of Ender from you before telling you that you've reached the maximum number of uses. So you pay for nothing.

- Link to server log: https://pastebin.com/vvGbV5vL
- Citizens config: https://pastebin.com/1Epxf0TD

- The output of command `/version` on my server is: This server is running Purpur version git-Purpur-1311 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d3a45fc on ver/1.17.1)
You are running the latest version
Previous version: git-Purpur-1296 (MC: 1.17.1)
- The output of command `/version citizens` on my server is: 2.0.28-SNAPSHOT (build 2337)

**Comment by mcmonkey4eva** [comment]
Your Citizens version is over a month old, and there were some changes to that command recently - please update from https://ci.citizensnpcs.co/job/Citizens2/ and reply to let us know whether the issue still occurs on the newer build.
