### ISSUE TITLE
NPC Spawning/Despawning

### ISSUE THREAD

**Issue by PlagueisTheWise21** [CitizensDev/Citizens2#2629]
So ive recently been implementing Citizens usage into my plugin I am coding, and it involves the NPC spawning and de-spawning at time intervals. I am able to select the npc but when I try to use either `npc.spawn(location);` or `npc.despawn();` nothing happens and the npc just remains in the spawn it was originally in. Am I just stupid and missing something really simple or is there someone not working behind the scenes.

The output of command `/version` on my server is: 1.16.5-RO.1-SNAPSHOT
The output of command `/version citizens` on my server is: 2.0.28-SNAPSHOT (build 2328)

**Comment by mcmonkey4eva** [comment]
The `Spawned` trait tracks whether an NPC *should* be spawned - ie when a player loads the area, should the NPC spawn in (NPCs automatically despawn and spawn based on whether players are around, to avoid lagging the server).

So a despawn should look like:
```java
npc.getOrAddTrait(Spawned.class).setSpawned(false);
if (npc.isSpawned()) {
    npc.despawn(DespawnReason.PLUGIN);
}
```
Similar for spawning back in
