### ISSUE TITLE
NPCs are teleporting instead of moving to targett location

### ISSUE THREAD

**Issue by ItzMace** [CitizensDev/Citizens2#263]
Hello!
I just tried to create a plugin with the "citizens-2.0.13-SNAPSHOT.jar" in which npc needs to walk to specific locations. 
At first I started with spawning a Zombie and setting its targett location about 80 blocks away. 
The problem was, that the Zombie isn't walking to this position, it is just teleporting there.
Is it possible to make Zombies walk to a location, no matter how far the targett is away?

Code used:
npc.getNavigator().setTarget(player.getLocation());

Thanks for answers!

Best wishes,
ItzMace ;)

**Comment by mcmonkey4eva** [comment]
Gotta set the pathrange too.

**Comment by ItzMace** [comment]
Hey! Thanks for your answer! 
But how do I set the Pathrange? :)

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L939

**Comment by ItzMace** [comment]
Great! Thank you very much, it works! :)
But now one last question: 
If the target location is inside a construct like a cube. How do I handle it that the NPCs doesn't teleport inside this construct and just stand in front of it/ walk against it?

Best wishes,
ItzMace ;)

**Comment by mcmonkey4eva** [comment]
Go into your C2 config and change the pathfinder mode, I think I recall that one of them works correctly and the other doesn't in this situation, I forget which is which... opposite of whatever you currently have oughtta work.

**Comment by ItzMace** [comment]
Hey! Thanks for your answer!
Hm.. which of them is the correct?:
1. default: pathfinding: range: 25.0
2. general: debug-pathfinding: false
3. pathfinding: new-finder-open-doors: false
3. pathfinding: new-finder-open-doors: false

**Comment by Morphan1** [comment]
@ItzMace I'm fairly certain he means `use-new-finder`.. try changing that to true

**Comment by ItzMace** [comment]
Hey @Morphan1 , Thanks for your answer!
Hm.. with setting use-new-finder to true, the NPCs are teleporting to the location and not walking.
Setting this to false again, they walk to the specific location, but still teleporting into cubes :(
Thank you anyways!!

Best wishes,
ItzMace ;)

**Comment by mcmonkey4eva** [comment]
OH you want them to NOT teleport. Okay. You need to use either the API or Denizen for that. The Denizen mechanism for it is http://mcmonkey.org/denizen/mecs/teleport_on_stuck
