### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by nivcoo** [CitizensDev/Citizens2#2638]
Hello, sometimes i've this error : https://hastebin.com/zoxomuqoxu.sql and all citizens dispawn
I use the version 2.0.28 #6 in 1.12.2 kspigot (fork of paper spigot)

**Comment by mcmonkey4eva** [comment]
1: Update https://ci.citizensnpcs.co/job/Citizens2/
2: Test with Spigot or Paper - forks sometimes break things in weird ways
3: Please [Pastebin](https://paste.denizenscript.com/new/Log) your **full** server [logs](https://wiki.citizensnpcs.co/Logs), not just a small snippet.
