### ISSUE TITLE
Citizens not working on 1.16.3

### ISSUE THREAD

**Issue by TemaisgameNoobas** [CitizensDev/Citizens2#2639]
Hello , i downloaded citizens for my minecraft server, and this happened : 

v2.0.28-SNAPSHOT (build 2362) is not compatible with Minecraft v1_16_R2 - try upgrading or downgrading Citizens. Disabling.

Where i can get a working citizens version?

I just started citizens, and it's alerady started not working.

Console Log: `https://pastebin.com/r96tjzKJ`
The output of command `/version` on my server is: ![image](https://user-images.githubusercontent.com/60001674/129941553-60f3ebf1-6d06-4113-a645-6b81a00d1f9e.png)
The output of command `/version citizens` on my server is:  v2.0.28-SNAPSHOT (build 2362)

**Comment by mcmonkey4eva** [comment]
You need 1.16.5

**Comment by TemaisgameNoobas** [comment]
What 1.16.5?

**Comment by mcmonkey4eva** [comment]
Spigot or Paper 1.16.5? For Minecraft 1.16.5?

You're running an outdated build of 1.16.3, which is in turn an outdated build of MC 1.16.x

**Comment by TemaisgameNoobas** [comment]
I got spigot, and i can't upgrade my server.

**Comment by TemaisgameNoobas** [comment]
Where i can get working build?

**Comment by SXRWahrheit** [comment]
https://papermc.io/downloads

**Comment by TemaisgameNoobas** [comment]
What is that?

**Comment by mcmonkey4eva** [comment]
If you need help with Citizens, you can ask on Discord @ https://discord.gg/Q6pZGSR
However what you need is help with basic server operation, which is entirely outside the scope of anything specific to Citizens. Consider googling for support platforms related to Minecraft servers in general or spigot in particular.
