### ISSUE TITLE
java.lang.NoSuchFieldError: field_75515_a What does this mean?

### ISSUE THREAD

**Issue by Thurrunn** [CitizensDev/Citizens2#264]
Hello i am using Citizens on my attack of the b team server, and whenever i try to /npc create name i get this error, i have no idea what is wrong here. I am using Cauldron for bukkit plugins.

**Comment by mcmonkey4eva** [comment]
You are using a non-Cauldron plugin on a Cauldron server.

Luckily, there are Cauldron versions available, such as this one: http://cauldron.minecraftforge.net/threads/citizens-2-1-7-10-b2-update.427/
