### ISSUE TITLE
Citizens Text Issue

### ISSUE THREAD

**Issue by Drevya** [CitizensDev/Citizens2#2640]
Citizens version: 2.0.24

After adding text to NPC and setting range, NPC repeats this text forever. How can I turn this off. When I add delay, it is added between both texts.

https://media.discordapp.net/attachments/315625512753954816/878076509666050139/2021-08-20_03.png?width=722&height=406

**Comment by mcmonkey4eva** [comment]
That version is horrendously outdated. Update: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by Drevya** [comment]
i updated. But i don't want to add with click command. When the player comes near the NPC I want it to write.
