### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by MrKatrioPL** [CitizensDev/Citizens2#2641]
Hi! I have a problem. Citizens alltime spam my console with this java error: https://pastebin.com/srmY6Q7y 
otherwise, plugin works fine.

(Sorry for my english ;p)

The output of command `/version` on my server is: **This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD) (Spigot's fork)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.28-SNAPSHOT (build 2357)**

**Comment by mcmonkey4eva** [comment]
You need 1.17.1, not 1.17 flat.
