### ISSUE TITLE
Citizens Error + New-Finder Bug Report

### ISSUE THREAD

**Issue by xMiamix** [CitizensDev/Citizens2#2643]
- Requests -

1.) Basically while using the new-finder, if you're fighting a "npc" and jump it will freeze the NPC and cause the server to drop in tps. This also happens when the "npc" hits you off a 1 block and it'd be considered jumping and it'll also freeze the npc and lag the server.

2.) Also while using the new-finder, if you run away from the said hostile "npc", it will take forever to locate or track you.

- Bug Report -

Raw link of Pastebin of Error: https://pastebin.com/eVSZsus6

<script src="https://pastebin.com/embed_js/eVSZsus6"></script>

_______________________________________________________

The server is on a forked Taco Spigot, however has been tested with regular spigot and paperspigot and it still has the same problems.

The version of citizens I'm using is Citizens2 Build #2363

The configuration is

Raw link of Pastebin of Configuration: https://pastebin.com/ciuqBdrB

<script src="https://pastebin.com/embed_js/ciuqBdrB"></script>

<img width="641" alt="Screen Shot 2021-08-24 at 7 43 43 PM" src="https://user-images.githubusercontent.com/89057481/130717815-4f4d9b2e-d216-4176-9eb0-1e6087cf84ff.png">

**Comment by BehrRiley** [comment]
There's not much more support you can receive running 1.8 beyond recommending you update to the latest build, which you appear to be on. Would highly recommend updating to a Minecraft version from this decade as you're on a version that we cannot reliably support. You can and should update your server. There are plugins for clientversion support and older-style PvP available if those are what hold you back presently.

For more information, refer to https://wiki.citizensnpcs.co/Minecraft_1.8.

Additionally, Citizens are immune and do not seek targets by default, this would be a Sentinel issue if you're referring to combat NPCs when using Sentinel. But the above still apply and you would need to update first for support

**Comment by BehrRiley** [comment]
Fullwall believes there may be a cross version issue also, he's looking into a fix he believes may be helpful. He'll help when he's available next

**Comment by fullwall** [comment]
Tracking this in #2730
