### ISSUE TITLE
Fish will not stay in the water

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#2648]
When you place fish NPCs such as cod into the water they will forever float up and down in and out of the water even with gravity turned on/off.

The output of command `/version` on my server is: **(PLEASE FILL IN)**
[12:30:14 INFO]: This server is running Paper version git-Paper-787 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
[12:30:35 INFO]: Citizens version 2.0.28-SNAPSHOT (build 2357)
[12:30:35 INFO]: Website: http://www.citizensnpcs.co
[12:30:35 INFO]: Author: fullwall

**Comment by mcmonkey4eva** [comment]
Might be related to the `/npc swimming` command

Might also be related to https://github.com/CitizensDev/Citizens2/issues/1878

**Comment by HexedHero** [comment]
Doing /npc swim helps but it makes the fish fall down in the water slowly even when disabling gravity.

**Comment by Boothin** [comment]
This also happens with squid and glowsquid, and pathfinding seems to be broken as well because they can't properly stabilize themselves in the water

**Comment by fullwall** [comment]
Latest build fixes this somewhat, I'll track the pathfinding issue in #1878
