### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by Togglerine** [CitizensDev/Citizens2#2649]
Hello
I have error spam in console and guess it appears randomly and doesn't causes any functionality problems, but create tons of logs.
Link to server log & Citizens config: https://pastebin.com/Kvb8f1aW / https://pastebin.com/kmpYq4wL

The output of command `/version` on my server is: - This server is running Purpur version git-Purpur-1370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cdbf59d on ver/1.17.1)
You are running the latest version
The output of command `/version citizens` on my server is: Citizens version 2.0.28-SNAPSHOT (build 2366)

I have this problem for a long time
Is exist possibility to stop this error showing?

**Comment by mcmonkey4eva** [comment]
This was a Sentinel error, not Citizens.

It's fixed in build 429+ of Sentinel from https://ci.citizensnpcs.co/job/Sentinel/
