### ISSUE TITLE
An internal error has occurred

### ISSUE THREAD

**Issue by AlexNotFounnd** [CitizensDev/Citizens2#2650]
Hi,
So I have an error, my citizens says "`An internal error has occurred while trying to run this command`" when I try to make an npc is there a fix? (My mc server version is 1.17.1 using the latest citizens version)

My server host is aternos for further more information.

-AlexNotFounnd (Alex)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Frequently_Asked_Questions#I_have_a_free_server_.28Aternos.2C_Minehut.2C_....29_but_there.27s_problems
