### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by joaopinto14** [CitizensDev/Citizens2#2651]
When the server is started in the log the information below appears.
At the same time the plugin is disabled

![image](https://user-images.githubusercontent.com/61939916/132211973-5e527fa6-69c3-4b74-aa58-cc51fb55984d.png)

![image](https://user-images.githubusercontent.com/61939916/132211843-5b36975c-6a90-4f81-a69d-7b5338ce9d77.png)

**Comment by mcmonkey4eva** [comment]
If you want to use Minecraft 1.16.x, you need 1.16.5, not 1.16.1.
