### ISSUE TITLE
UUID Error

### ISSUE THREAD

**Issue by Lonewolfi** [CitizensDev/Citizens2#2656]
(My English is not very well,so the following is from Google Translate)
When the first character of the string character in the middle of the UUID is 2, the debugging output in the Citizens plug-in is 4
(Please see UUID below, Google Translate may not be accurate).
I have tried many versions, all of which are re-created NPCs, but as long as the first character of the string in the middle of the UUID is 2, the plug-in will output 4.

public static void NPCRightClick(NPCRightClickEvent event) {
String UUID = event.getNPC().getUniqueId().toString();
}
Citizens2 UUID: e0f064cf-c441-4571-81c2-b45f0d0bb053
Bukkit UUID: e0f064cf-c441-2571-81c2-b45f0d0bb053
error：2571 →→→ 4571

Citizens2 UUID: cb16b17f-2e2a-402b-b52c-22165aaaeaba
Bukkit UUID: cb16b17f-2e2a-202b-b52c-22165aaaeaba
error：202b →→→ 402b

version:
Server: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Plugin: ( I have tried 2.0.24-2.0.28, but all have errors )
Citizens version 2.0.28-SNAPSHOT (build 2372)
Website: http://www.citizensnpcs.co
Author: fullwall

**Comment by mcmonkey4eva** [comment]
This isn't an error.
