### ISSUE TITLE
Use the first hologram or choose a hologram to be displayed as a name while the npc talks, in an npc (Npc Text)

### ISSUE THREAD

**Issue by EdgarGDE** [CitizensDev/Citizens2#2658]
I just wonder if there is a way to display a name other than the real name of the NPC when using the NPC text feature.
What i would like
Example:
If my NPC is called "CLICK HERE" and there is a hologram in my NPC that says "Alexander" I wish that when the NPC speaks (With /npc text) the hologram "0" or the one I choose appears, instead of "CLICK HERE"
Example:
[NPC] CLICK HERE: Hello! Is a test. (×) NO!
[NPC] Alexander: Hello! Is a test. (✓) YES!
All this without using "/npc name" to hide the name and use two or more holograms.
It is something that many would like and it would come in handy.
I want to know if this is already possible today or if it could be possible, greetings!

**Comment by mcmonkey4eva** [comment]
`All this without using "/npc name" to hide the name and use two or more holograms.` this is literally the answer to your question.
Just make two holograms and hide the nameplate.
