### ISSUE TITLE
Top TPS load with 45 plugins on the server

### ISSUE THREAD

**Issue by Sitmobedaf** [CitizensDev/Citizens2#2659]
https://timings.pl3x.net/?id=9755007648264934924e79335562d964#plugins
StrikeTurrets does heavy chunk calculations and does get Nearby every tick for every turret.
I have not looked at the Citizens code, but I think it is possible to optimize in https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/util/PlayerUpdateTask.java

First of all, by trying to do it in a separate thread, that is, asynchronously.
If this does not work, then try to cache frequently used data or use a different approach to reduce the load from the main thread. I think this problem is the main one in Citizens at the moment, it makes no sense to make any other changes in the plugin. Get to work guys!

**Comment by fullwall** [comment]
Please obtain Spark timings and re-open this issue when you have done so. Appreciate you looking at the code, however PlayerUpdateTask is ultimately 99% Minecraft (i.e. single threaded) code that is not possible to make async. I am of course aware of alternative approaches.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
