### ISSUE TITLE
NPC's on Player List

### ISSUE THREAD

**Issue by IvIercenary** [CitizensDev/Citizens2#266]
Alright, im seeing where everyone is saying its fixed.....however on my server it is not, im using current builds of both spigot and citizens and it shows all the npcs on the list, so when a player enters an area with a high npc count, all they see is npc names....

http://screencloud.net/v/lzf0

**Comment by mcmonkey4eva** [comment]
Great job reading!
It's not fixed, it's a known bug with no current known workaround.

It's also not a major issue, as the NPC names go off the list after a few seconds.

**Comment by tjbruce17594** [comment]
I am also having the same problem.

But It doesn't happen when I enter an area, it occurs as I join the server.

The Player NPC's appear in the tablist as well as the prefix (Using rankprefixplus)

Thanks for trying to fix this bug.

**Comment by IvIercenary** [comment]
Matmorcat commented on Dec 11, 2014
As far as I can tell, that fixed it. I can't even get them to show up by moving far away. :smile:
Just as a reference, I'm running git-Spigot-b023457-9d43c91 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT).

**Comment by tjbruce17594** [comment]
Is this fixed in #1218 ?

**Comment by mcmonkey4eva** [comment]
... is this still an issue?

**Comment by StillSwingin** [comment]
Well, names still appear but disappear almost instantly

**Comment by mcmonkey4eva** [comment]
Yeah that's known, nothing we can do about it, Mojang's fault
