### ISSUE TITLE
Knockback is not consistent with normal entities

### ISSUE THREAD

**Issue by NateKomodo** [CitizensDev/Citizens2#2665]
The output of command `/version` on my server is: **git-Purpur-965 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **version 2.0.28-SNAPSHOT (build 2381)**

Title. I have created an NPC and set it to be vulnerable and tested the knockback. Vanilla mobs appear to have a falloff tied to how many hits they have taken in one sprint whereas NPCs appear to not have this drop off and follow a linear path. Please note i am not referring to the first hit of a sprint doing more knockback, i am referring to subsequent hits in the same sprint.

I feel this is easy to show using an image:
![image](https://user-images.githubusercontent.com/31631620/134456467-3ee65bcb-f8a1-47e3-a2e2-ef7e84d667f3.png)
You can see the zombie having a curve as the knockback falls off, whereas the NPC does not

**Comment by NateKomodo** [comment]
An easy way to see an implication of this in game is to try spam punching an npc while sprinting vs spam punching a zombie while sprinting. The NPC will always remain at more or less the same distance to you, however the zombie will get closer over time.

**Comment by fullwall** [comment]
Try latest build

**Comment by NateKomodo** [comment]
Can confirm fixed in 2382
