### ISSUE TITLE
Npc are not invincible and can be killed by other players

### ISSUE THREAD

**Issue by Kissadere** [CitizensDev/Citizens2#2667]
After installing the plugin i noticed every player can damage and kill my npcs, i'm not sure if it's a plugin compatibility issue or some other issue, plus i noticed i can't see the saves.yml file, since there's empty, but i can spawn and list my npcs in-game.

The output of command `/version` on my server is: Paper(263) **1.17.1-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **Citizens v2.0.28-SNAPSHOT (build 2362)**
Server Fresh Start Log: https://mcpaste.io/8a8aa6cf707f2755
Citizens Config File: https://pastebin.com/aAx2LjcL
Edit: Fixed plugin versions on server logs not showing off correctly

Plugin List: AggressiveAnimals*, AuthMe, AzLink, BloodInMinecraft, BottledExp, Citizens, CitizensGUI, CMI, CMILib, CoreProtect, CreativeManager, DiscordSRV, EcoPower, ExcellentEnchants, ExtraGear, FastAsyncWorldEdit (WorldEdit), GUIPlus, Jobs, LibsDisguises, Liquid, LuckPerms, LumberJack, LWC, LWCTrust, M0-OnlinePlayersGUI, MarketPlace, MarriageMaster, MarriageMasterGUI, MidensFoods, MobCapturer, Multiverse-Core, MusicBox, NexEngine, NoteBlockAPI, NotQuests, OreMarket, PCGF_PluginLib, PlaceholderAPI, PlugMan, ProtocolLib, ServerTours, Shopkeepers, SkinsRestorer, Slimefun, SlimefunOreChunks, Towny, TownyGUI, TradeSystem, TranscEndence, Vault, ViewDistanceTweaks, VoidGen, WorldBorder, WorldGuard

Starting process: /usr/bin/java -Xmx10240M -Dterminal.jline=false -Dterminal.ansi=true -Djline.terminal=jline.UnsupportedTerminal -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dpaper.playerconnection.keepalive=128 -jar paper.jar

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
