### ISSUE TITLE
NPCs keep Disappearing

### ISSUE THREAD

**Issue by sunnydive** [CitizensDev/Citizens2#2669]
The output of command `/version` on my server is: **Airplane 1.17.1-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **Citizens-2.0.28-b2383**

** DETAILED DESCRIPTION **
Basically the NPC gone whenever there's no player close to them. I need to do /citizens reload to bring them back but then when i leave that chunk, they disappear. It's been like that since i update it to 1.17,1 & update the Citizens Plugins. What I can think of is probably Citizens's own plugin problem or one of my plugin problem. "Mob Farm Manager" this plugin, but I've also tested disabling it the NPC still disappear when we go out of chunk, there's no other plugin that i can find that is related to the NPCs in any way. Please reply me asap if you found any Solution. Thank you so much for your time!

Please help asap yeah I'm a bit troubled right now.

**Comment by mcmonkey4eva** [comment]
Update: https://ci.citizensnpcs.co/job/Citizens2/

You downloaded a broken dev build that was fixed the day after in the next build
