### ISSUE TITLE
Issue with Citizens UUID 

### ISSUE THREAD

**Issue by DebuffPvP** [CitizensDev/Citizens2#2675]
ISSUE: So when i log in to my server one of my plugins gives me an error and i found out it has to do with citizens.

LOG: https://pastebin.com/69MDTdnL
SPIGOT: This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
CITIZENS: Citizens version 2.0.28-SNAPSHOT (build 2357)
SAVES: https://pastebin.com/Y5MRdU9F
CONFIG: https://pastebin.com/nJR0D6wQ

Conclusion: There is a problem with the uuids when entering, it changes them and there are plugins that cause citizens error in my case my HSkyWars plugin and i did the whole removing plugins and stuff spent like 2 hours and it appears to only happen with citizens the premium one of course.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8
