### ISSUE TITLE
Citizens NPC's disappear and not getting loaded properly

### ISSUE THREAD

**Issue by OwnedGG** [CitizensDev/Citizens2#268]
On the one hand the new builds fix that NPC's will be shown in the Playerlist when you use the TAB-key. On the other hand my NPC's sometime just disappear (mostly npcs who stand still) and their skins wont get loaded. So actually im useing the 1190 Build because it prevent the disappearing of my NPC's and also the default Skin ( which is caused by no skin loading ). Will this get fixed that NPC's dont disappear and skins get loaded as well without having them in TAB?

**Comment by mcmonkey4eva** [comment]
We're working on it.

**Comment by tjbruce17594** [comment]
Thanks very much!

**Comment by ssamjh** [comment]
Oh nice. I'd like to confirm this problems. But it only happens when ClearLagg is installed.

**Comment by Legendaryx** [comment]
I have the same bug and i dont have clearlagg installed.

**Comment by fullwall** [comment]
Duplicate
