### ISSUE TITLE
npc trigger teleport not functioning properly?

### ISSUE THREAD

**Issue by sargeow** [CitizensDev/Citizens2#2680]
issue: when using the triggers teleport for some odd reason the nps has to return the previous destination before he can go to the next teleport location. the video better explains it - https://www.dropbox.com/s/iwb73eth5y3qmul/2021-10-19%2006-54-00.mp4?dl=0
Log: https://pastebin.pl/view/ebcaac19
Config: https://pastebin.pl/view/4c4d53b1
- ![paper version](https://user-images.githubusercontent.com/89289084/138028115-c6f53b67-a1ba-40fe-87d1-749934d420a2.png)
- ![citizen version](https://user-images.githubusercontent.com/89289084/138028117-513696df-c1e3-4520-9643-b5a5b094fae9.png)

thanks for helping :D

**Comment by fullwall** [comment]
I cannot access your config.

**Comment by mcmonkey4eva** [comment]
Please use https://paste.denizenscript.com/New/Log to pastebin your server log and config (instead of the obscure polish paste service that appears to have gone down)
