### ISSUE TITLE
Citizens NPCs not being cleared

### ISSUE THREAD

**Issue by razorrider7** [CitizensDev/Citizens2#2682]
One of the networks I run has had servers repeatedly crashing. The memory usage starts at around 2-2.5GB but slowly works it's way up to 8GB (what I have allocated) and then eventually crashes.

I ran a memory dump by running `/heapdump dump` using the [HeapDump](https://www.spigotmc.org/resources/heapdump.1433/) spigot plugin. I analyzed the dump in Eclipse Memory Analyzer and it found `88,648 instances of “net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC$PlayerNPC”, loaded by “org.bukkit.plugin.java.PluginClassLoader @ 0x60d042cb8” occupy 3,820,310,120 (62.77%) bytes.` Are NPCs not getting unloaded when they should be?

Also, the log is not showing any errors, but the server is still crashing, and citizens is loading correctly otherwise. I do not know which log is from a crash, as I have restarted the server many times since for debugging, so if a full log is needed, I will need to wait for the server to crash again... otherwise, I have attached a startup log showing everything starting correctly.

Server is running on a Ryzen 9 3950X and 8GB RAM, with a few other servers that are all having the same issue. Each server has access to 1/8 processing time. There are 73 NPCs, most of which are not loaded in, as they are in an inaccessible world to players.

[saves.yml](https://pastebin.com/2vBNAfCg)
[config.yml](https://pastebin.com/7VYetty6)
[latest.log](https://pastebin.com/vbbbfKBe)

The output of command `/version` on my server is: **This server is running Airplane version git-Airplane-99 (MC: 1.17.1 (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e68f5c2 on HEAD) You are on the latest version!**
The output of command `/version citizens` on my server is: **Citizens version 2.0.28-SNAPSHOT (build 2393)**

![image](https://user-images.githubusercontent.com/19194919/139444330-3cb2df65-47d9-4f88-99f3-bb0830734788.png)

**Comment by mcmonkey4eva** [comment]
Can you replicate the issue on Spigot or Paper?
If not, it's likely to be an issue with the janky server fork you're running.

**Comment by fullwall** [comment]
The other thing to consider is seeing what is referencing the PlayerNPC instances (presumably the update task?)

**Comment by razorrider7** [comment]
How would I check what is referencing the PlayerNPC instances?

**Comment by razorrider7** [comment]
Still happens on latest paper build...

**Comment by razorrider7** [comment]
com.fastasyncworldedit.bukkit.BukkitPermissionAttachmentManager seems to be referencing the instances... I take it I should bring this up with them.

**Comment by razorrider7** [comment]
Alright, issue is still ongoing on latest 1.17.1 paper: `This server is running Paper version git-Paper-391 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3e73355)`

Please let me know what other information you need.

**Comment by mcmonkey4eva** [comment]
In your previous comment you discovered it was a FAWE issue and were going to bring it up with them
