### ISSUE TITLE
Errors on Spigot 1.8.3

### ISSUE THREAD

**Issue by KeithSt0ne** [CitizensDev/Citizens2#269]
Testing on our test server with spigot for 1.8.3 and getting these errors on startup

http://pastebin.com/98PCEXJy

**Comment by Xericore** [comment]
According to your paste, you are using an old version of citizens. The new version apparently has some 1.8.3 support (see: http://ci.citizensnpcs.co/job/Citizens2/changes). I suggest you try that version.

**Comment by mcmonkey4eva** [comment]
^
