### ISSUE TITLE
/npc endercrystal -b

### ISSUE THREAD

**Issue by BehrRiley** [CitizensDev/Citizens2#2690]
### `/version` output

```txt
This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)
You are running the latest version
Previous version: git-Paper-377 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.28-SNAPSHOT (build 2401)
Website: http://www.citizensnpcs.co
Author: Fullwall
```

### Log file

https://paste.denizenscript.com/View/89978

### config.yml

https://paste.denizenscript.com/View/89980

### saves.yml

https://paste.denizenscript.com/View/89979

### Description

`/npc endercrystal -b` does nothing, it just prints "unknown flag: b" - `/npc help endercrystal` prints `/npc endercrystal -b - edit endercrystal modifiers` - but im not sure what `-b` would do other than making the bedrock at the bottom maybe?

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/blob/968f3fd68b4def8d919543ae99465c93b0116080/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L667-L677
`flags = "b"` is missing from the command registration

Also for the record it's short for 'bottom' so yes

**Comment by mcmonkey4eva** [comment]
fixed by https://github.com/CitizensDev/Citizens2/commit/3d1d2ef222bd9412781709d6ba1dce846fe2ac1b
