### ISSUE TITLE
NPCs not able to execute commands

### ISSUE THREAD

**Issue by AlphineGhost** [CitizensDev/Citizens2#2693]
### `/version` output

```txt
This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version
```

### `/version Citizens` output

```txt
[18:12:29 INFO]: Citizens version 2.0.28-SNAPSHOT (build 2398)
[18:12:29 INFO]: Website: http://www.citizensnpcs.co
[18:12:29 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/90321

### config.yml

https://paste.denizenscript.com/View/90322

### saves.yml

https://paste.denizenscript.com/View/90323

### Description

When trying to right click and left click a npc with a command, the command doesn't run.

**Comment by mcmonkey4eva** [comment]
I don't see any usage of `/npc command` in that log

**Comment by AlphineGhost** [comment]
I already have the npcs made and they where working. But when I tried to right click or left click it doesn't work at all. So no `/npc` command was evoked

**Comment by AlphineGhost** [comment]
Found the issue, It was due to a plugin called RotatingHeads.
