### ISSUE TITLE
1.17/18 for citizens

### ISSUE THREAD

**Issue by JimmyBinoculars** [CitizensDev/Citizens2#2698]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

I would like citizens 2 to be able to support 1.17/18 Minecraft servers

**Comment by mcmonkey4eva** [comment]
... what?
Citizens works on latest versions already.
If you're lost, consider asking for help on Discord https://discord.gg/Q6pZGSR in the citizens channel
