### ISSUE TITLE
java.lang.NoSuchMethodError: void net.minecraft.world.entity.ai.navigation.NavigationAbstract.o

### ISSUE THREAD

**Issue by mozai** [CitizensDev/Citizens2#2700]
### `/version` output

```txt
version
[19:01:00] [Server thread/INFO]: §f§oChecking version, please wait...
[19:01:00] [Thread-134/INFO]: §fThis server is running Paper version git-Paper-68 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c779c2)§r
§aYou are running the latest version§r
§7§oPrevious version: git-Paper-60 (MC: 1.18)
```

### `/version Citizens` output

```txt
version Citizens
[19:01:13] [Server thread/INFO]: §aCitizens§f version §a2.0.29-SNAPSHOT (build 2419)
[19:01:13] [Server thread/INFO]: Website: §ahttp://www.citizensnpcs.co
[19:01:13] [Server thread/INFO]: Author: §afullwall
```

### Log file

https://paste.denizenscript.com/View/90800

### config.yml

https://paste.denizenscript.com/View/90801

### saves.yml

https://paste.denizenscript.com/View/90802

### Description

Set the NPC to "wander" around spawn.  It walks through doors despite `pathfinder-open-doors: false` so it can go pretty far afield.  I tried to tp it back to spawn but it didn't appear.   when I tp to it I am in a pond and the NPC isn't visible.  I tp the NPC to me and its still not visible.  I do /citizens reload and it's stlil not visible.  Check the server logs and I see the NoSuchMethodError.

I rewrite the saves.yml to give it a traits.location that is sane, /citizens reload, and the NPC is visible... until it wanders for a few seconds then vanishes, and the "NoSuchMethodError" is in the server logs again.

**Comment by mcmonkey4eva** [comment]
1.18.1 is brand new, we'll update it soon, please don't spam issues about it.
Use 1.18 until .1 is supported.

**Comment by mozai** [comment]
How is it "spam" when I've only spoken once?  C'mon.

Unfortunately can't roll-back because minecraft refuses to load chunks that changed while the server was v1.18.1 -- world-state  is ratcheted forward.  This is fine, I've learned to use an explicit server version instead of letting Bukkit/Spigot/Paper default to "latest".

Here's my workaround, for the next person who searches for the error message:  
Did a `/citizens save` , edited the NPC's location in saves.yml and changed the NPC's properties by hand.  Changed "traits.location" so the x, y and z are a known safe place to stand.  Changed traints.waypoints.provider to "linear" instead of "wander".  This means the NPC will stand still but better than disappearing, and I can go in-game to set waypoints if I need.  After editing, `/citizens reload` then `/citizens reload` again to confirm, and fly to the NPC's usual place for a `/npc select 0` then `/npc tphere`

**Comment by mcmonkey4eva** [comment]
This is why you should
A: always have backups of every file that matters. Automated daily or weekly backups is a good thing.
B: as you realized yourself, never have automatic updates enabled. Updates should only ever happen while a server admin is at the ready to fix anything that goes wrong.

`How is it "spam" when I've only spoken once? C'mon.` you're not the only person that posted, and it's a common occurrence for every plugin to receive endless messages about every Minecraft version update. The answer is always the same for every plugin for every update. It's a new version, we'll update to it eventually, don't run brand new Minecraft versions the day they're out if you need anything to function.
