### ISSUE TITLE
Console Spamming

### ISSUE THREAD

**Issue by RocketManKian** [CitizensDev/Citizens2#2701]
### `/version` output

```txt
"You are running the latest version
Previous version: git-Paper-59 (MC: 1.18)"
```

### `/version Citizens` output

```txt
"Citizens version 2.0.29-SNAPSHOT (build 2420)
Website: http://www.citizensnpcs.co
Author: fullwall"
```

### Log file

https://paste.denizenscript.com/View/90810

### config.yml

https://paste.denizenscript.com/View/90811

### saves.yml

https://paste.denizenscript.com/View/90812

### Description

When updating to version 2.0.29 my console is being constantly spammed with messages about "Task #82 for Citizens v2.0.29-SNAPSHOT (build 2420) generated an exception"

**Comment by mcmonkey4eva** [comment]
You're on Citizens for 1.18.1, and Paper 1.18
Either update Paper, or downdate Citizens
