### ISSUE TITLE
NPC Lookclose doesnt work

### ISSUE THREAD

**Issue by lucaswave69** [CitizensDev/Citizens2#2706]
So I recently installed Citizens on my Server after buying it. I thought I knew what I was doing because ive been using it on my older servers. Everything seems to work fine, but the only command not working is the /npc lookclose on NPC's like if I spawn myself.

Please help me 👍

**Comment by mergu** [comment]
Help is on discord: https://discord.gg/Q6pZGSR 

You also did not follow the required issue template

**Comment by lucaswave69** [comment]
sorry for not following the issue template I'm new to this 
I will look for help on the discord thanks !!
