### ISSUE TITLE
Invalid entity rotation: NaN, discarding.

### ISSUE THREAD

**Issue by PikaMug** [CitizensDev/Citizens2#2707]
### `/version` output

```txt
This server is running Paper version git-Paper-"95d881f" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 95d881f)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2428)
```

### Log file

Server owner does not authorize release

### config.yml

https://paste.denizenscript.com/View/90965

### saves.yml

https://paste.denizenscript.com/View/90966

### Description

Created a rideable horse NPC named Pedro. Mounting and moving the horse results in the following console errors:

`[Server] ERROR Invalid entity rotation: NaN, discarding.`

This issue has been present since at least Citizens-2.0.28-b2333 and happens on both MC 1.17 and 1.18 servers.

**Comment by mcmonkey4eva** [comment]
`Server owner does not authorize release`

issue responder does not authorize answer

**Comment by PikaMug** [comment]
Unfortunately, I can't provide what I don't have. Considering you awarded an answer to #2705 and others despite the same fault, I hope you find time to look into this. All the best.
