### ISSUE TITLE
/npc command --cooldown 84400 doesnt work

### ISSUE THREAD

**Issue by AngerminecraftYT** [CitizensDev/Citizens2#2708]
/npc command --cooldown 84400 doesnt work

I created a daily npc it will give ppl armor but the thing is if i do: /npc command --cooldown 84400 it says the help command, the seconds: 84400 is 1 day because its "daily"

**Comment by mcmonkey4eva** [comment]
you have to ... add a command

Consider asking for help on Discord @ https://discord.gg/Q6pZGSR
