### ISSUE TITLE
Unable to Sponsor monthly for more than $1 and less than $20.

### ISSUE THREAD

**Issue by LlmDl** [CitizensDev/Citizens2#2709]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Please enable custom monthly sponsor options or add more tiers.

**Comment by mcmonkey4eva** [comment]
It's a thing now! Yay :D

![](https://i.alexgoodwin.media/i/misc/b9af14.png)

**Comment by LlmDl** [comment]
@fullwall do you think you could change the minimum monthly to $5? It's currently at $10.

**Comment by fullwall** [comment]
Sure, no worries. Thanks for the support.
