### ISSUE TITLE
npc lookclose pitch/yaw = 0/0

### ISSUE THREAD

**Issue by Xericore** [CitizensDev/Citizens2#271]
NPCs keep looking at pitch/yaw = 0/0. If the player moves, the NPC looks at the player for a brief moment and then looks at 0/0 again.

The following is enough to reproduce:
/npc create looky
/npc lookclose

Using citizens-2.0.15-SNAPSHOT.jar build 1219 with latest spigot-1.8.3.
Update: Issue still present in build 1220.

**Comment by SullyTheUnusual** [comment]
I am also seeing this phenomena.

**Comment by Sketaful** [comment]
Same here.

**Comment by fullwall** [comment]
Fixed, pushing today.
