### ISSUE TITLE
Ticking Entity error crashing server

### ISSUE THREAD

**Issue by Xeryxes** [CitizensDev/Citizens2#2712]
### `/version` output

```txt
This server is running Arclight version arclight-1.17.1-1.0.2-a79a6a5 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2428)
```

### Log file

https://paste.denizenscript.com/View/91393

### config.yml

https://paste.denizenscript.com/View/91394

### saves.yml

https://paste.denizenscript.com/View/91395

### Description

When creating a new npc, the server loads the npc for a second and then everything crashes and I can only restart the server after deleting the config.yml and saves.yml from the Citizens plugin folder.

How to recreate:
Step 1. Load up a server
Step 2. type /npc (or npc2) create steve (or other name)
Step 3. Watch npc load up
Step 4. Crash

Here is a copy of the crash report file as well: https://paste.denizenscript.com/View/91396

**Comment by mcmonkey4eva** [comment]
We do not support anyone involved in plugin piracy here.
