### ISSUE TITLE
Not Able To Select NPC's With Space In Names

### ISSUE THREAD

**Issue by 0bviouslee** [CitizensDev/Citizens2#2714]
### `/version` output

```txt
git-Paper-64 (MC: 1.18)
```

### `/version Citizens` output

```txt
2.0.29_SNAPSHOT (build 2430)
```

### Log file

https://paste.denizenscript.com/View/91429

### config.yml

https://paste.denizenscript.com/View/91427

### saves.yml

https://paste.denizenscript.com/View/91428

### Description

I have tried to select an NPC via its name with spaces though it doesn't seem to work whether I do "/npc sel &8[NPC] Citizen1", "/npc sel [NPC] Citizen1", or anything similar.

**Comment by BehrRiley** [comment]
Some of the information you provided does not match the hastes you've submit.

> /version output
> ```git-Paper-64 (MC: 1.18)```

This is does not reflect what your log file provided shows, your server version is actually: `Paper version git-Paper-"95d881f" (MC: 1.18.1)`. You'll want to make sure you're using the latest version. Latest Paper builds are at https://papermc.io/downloads. 


While updating your server version, it's recommended you update the rest of your plugins as well - you're on an ancient old Denizen version and your Citizens and Sentinel could both be updated.

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.
Spigot releases of Citizens are available at https://www.spigotmc.org/resources/citizens.13811/.
Latest Sentinel dev builds are at https://ci.citizensnpcs.co/job/Sentinel/.
Spigot releases of Sentinel are at https://www.spigotmc.org/resources/sentinel.22017/.


When using Denizen, generally your main public/live server should use only the release builds. Your test/dev servers can use dev builds, but are often better off running release builds. If you choose to use a dev build on your test server, you are expected to update the build every few days at most - if you ask for help on our support channels while running a dev build from more than a few days ago, the first thing we'll tell you is to stop running dev builds as they're clearly not for you.

Latest Denizen stable release builds are at https://ci.citizensnpcs.co/job/Denizen/. Most users should download the stable release build.
Latest Denizen dev builds are at https://ci.citizensnpcs.co/job/Denizen_Developmental/. Dev builds are for usually for test servers only.

Lastly, you have some potentially relevant plugins that may be causing issues as well:
`TAB v3.0.0` - This plugin adds Below_Name scoreboards to NPCs.
`ViaVersion v4.1.1` - Mixed client vs server versions can sometimes cause packet-related issues
ViaVersion specifically has some errors in your logs currently, as well as 100+ other errors being output, it's highly recommended you attempt clearing those as much as possible to eliminate potentially related conflicts with the issue you're having.

For further help, we provide faster support on the discord: https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
You can select an NPC:
- by ID #
- By standing near them and typing `/npc sel`
- By right-clicking them with a stick

Names are never guaranteed reliable for a multitude of reasons, and are supported just as an extra convenience option for when it is able to work
