### ISSUE TITLE
Console Error Spam

### ISSUE THREAD

**Issue by topthat177** [CitizensDev/Citizens2#2715]
Hi,

Getting the following error spamming console, plugin seems to be operating correctly. 

https://pastebin.com/QEa4SizH

Server Version: Paper version git-Paper-10 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: c728c78)
Plugin Version: 2.0.29 SNAPSHOT (Build 2420)

**Comment by mcmonkey4eva** [comment]
Update to 1.18.1
