### ISSUE TITLE
Selecting NPC with name $3 produces error

### ISSUE THREAD

**Issue by GriffinCodes** [CitizensDev/Citizens2#2719]
### `/version` output

```txt
git-Parchment-684ee05 1.17.1-R0.1-SNAPSHOT
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2431)
```

### Log file

https://paste.projecteden.gg/raw/citizens2719latest

### config.yml

https://paste.projecteden.gg/raw/citizens2719config

### saves.yml

https://paste.projecteden.gg/raw/citizens2719saves

### Description

Looking at an NPC named `$3` and typing `/npc sel` produces the following error
![image](https://user-images.githubusercontent.com/12417961/147715425-68fc0c4d-1a1a-44a9-871f-ae1fde5e0f83.png)

**Comment by mcmonkey4eva** [comment]
Was fixed by https://github.com/CitizensDev/CitizensAPI/commit/7eb7494d91cead7844c8e1c86ef594e0edb9e965 for Citizens build 2439+ from https://ci.citizensnpcs.co/job/Citizens2/
