### ISSUE TITLE
Broken compatibility with 1.12

### ISSUE THREAD

**Issue by RedGuys** [CitizensDev/Citizens2#2722]
### `/version` output

```txt
This server is running Paper version git-Paper-"77cce8236" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Previous version: git-Paper-1618 (MC: 1.12.2)
Checking version, please wait...
You are 1 version(s) behind
```

### `/version Citizens` output

```txt
Citizens version 2.0.28-SNAPSHOT (build 2354)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/91650

### config.yml

https://paste.denizenscript.com/View/91651

### saves.yml

https://paste.denizenscript.com/View/91652

### Description

While trying to construct a path through the door, this error occurs.
Judging by the javadoc org.bukkit.block.data.Openable was added only in 1.13, and just extends org.bukkit.block.data.BlockData.
https://papermc.io/javadocs/paper/1.12/org/bukkit/block/data/Openable.html - 1.12 javadoc - the class does not exist
https://papermc.io/javadocs/paper/1.13/org/bukkit/block/data/Openable.html - 1.13 javadoc - the class has been added

This error was added with this commit:
https://github.com/CitizensDev/CitizensAPI/commit/e0507a7aed31d6b263e88cbbe04578e8314a32d3

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
