### ISSUE TITLE
NPC not saved in saves.yml

### ISSUE THREAD

**Issue by Robster1973** [CitizensDev/Citizens2#2723]
### `/version` output

```txt
git-Paper-134 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 55a1756)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2420)
```

### Log file

https://paste.denizenscript.com/View/91901

### config.yml

https://paste.denizenscript.com/View/91900

### saves.yml

EMPTY

### Description

If have just installed the plugin on my Paper 1.18.1 server 
Created an npc and issues /citizens2 save and /citizens2 save

The saves file stays empty. If I delete the file it is created but still empty.

**Comment by Robster1973** [comment]
Just an additional note - even if i create a saves.yml manually and issue /citizens save the file is emptied

**Comment by mcmonkey4eva** [comment]
... You haven't, uh, described any actual issue here?
Don't mess with saves files manually, they're for the plugin to access not for you.

**Comment by Robster1973** [comment]
Not an issue? The NPC disappear after a server restart because they are not saved to saves,yml - for me that sounds like an issue...

**Comment by mcmonkey4eva** [comment]
`The NPC disappear after a server restart` 
Now *that* is describing an actual issue.

- Update Citizens: https://ci.citizensnpcs.co/job/Citizens2/
- `/citizens reload` don't use that command
- `--registry Auktionator` don't input a registry when creating NPCs, that, yknow, prevents saving entirely

**Comment by Robster1973** [comment]
That helped a lot - Thank you
