### ISSUE TITLE
https://wiki.citizensnpcs.co/Cracks

### ISSUE THREAD

**Issue by samuelovski1** [CitizensDev/Citizens2#2729]
https://wiki.citizensnpcs.co/Cracks

_Originally posted by @mcmonkey4eva in https://github.com/CitizensDev/Citizens2/issues/2728#issuecomment-1008427343_
----
What do you mean by that? My server is on on-line mode.

**Comment by mcmonkey4eva** [comment]
https://discord.gg/Q6pZGSR
