### ISSUE TITLE
Group Target Lag

### ISSUE THREAD

**Issue by dylandwsn** [CitizensDev/Citizens2#273]
Been having an issue with extreme lag issues in certain situations. This has been ongoing for a while and I've been researching the problem a bit to no avail. Currently on Dev build #1219, however this has been occurring on numerous previous dev builds. Whenever I add a group target to a Sentry NPC the server begins to lag out almost immediately afterwards. On the server box CPU usage stays normal, block-placing and world generation cease all together until the Sentry's are removed. I have had this exact same lag problem occur a couple months back with NPCs who dropped items, and only dropped items. I think it is some sort of conflict with WorldGuard regions, as I have only tested these NPCs within WorldGuard regions. We have plenty of other Sentry NPCs that do not have any of these issues.

Spigot Version: 1.8.3 (Issue persistent on numerous builds)
Citizens Version: Dev Build #1219
Plugins: MinecraftMarket, AsyncWorldEditInjector, dynmap, WorldEdit, Essentials, Logblock, NametagEdit, Lockette, ProtocolLib, WorldGuard, AsyncWorldEdit, ArmorSaddles, PermissionsEx, mcMMO, PlayerCountMessage, Vault, EssentialsSpawn, Landlord, Herochat, CitIzens, Shopkeepers, PhatLoots, Blacksmith, Sentry, BetonQuest

Any help would be greatly appreciated :)

**Comment by mcmonkey4eva** [comment]
Sentry issue, not Citizens.
