### ISSUE TITLE
NPCs aren't closing doors after opening them

### ISSUE THREAD

**Issue by akusoff** [CitizensDev/Citizens2#2732]
### `/version` output

```txt
This server is running Paper version git-Paper-155 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 99cf01f)
You are running the latest version
Previous version: git-Paper-110 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2453)
```

### Log file

https://paste.denizenscript.com/View/92308

### config.yml

https://paste.denizenscript.com/View/92310

### saves.yml

https://paste.denizenscript.com/View/92311

### Description

NPCs aren't closing doors after they open them

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
