### ISSUE TITLE
no implementation set error

### ISSUE THREAD

**Issue by Lairon1** [CitizensDev/Citizens2#2734]
### `/version` output

```txt
1.16.5 R0.1
```

### `/version Citizens` output

```txt
maven version 2.0.20-SNAPSHOT
```

### Log file

https://pastebin.com/HcwNLXEb

### config.yml

https://pastebin.com/rc1B5xWV

### saves.yml

Empty

### Description

When I try to create an NPC from my new plugin, I get an error no implementation set.
But at the same time, my other plugins have no problems with this.
`npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, "§ctest");`
I can not understand what it could be connected with.

**Comment by Lairon1** [comment]
UPD: I also have a dependency in pludin.yml and in general I create the NPC much later than the plugin starts.

**Comment by mcmonkey4eva** [comment]
A: Consider asking for help on Discord @ https://discord.gg/Q6pZGSR
B: Update Citizens that's way outdated
B: that log link isn't what the information you ignored asked for. We need your *full* latest.log posted via https://paste.denizenscript.com/New/Log

**Comment by Lairon1** [comment]
https://paste.denizenscript.com/View/92398
full log file.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
