### ISSUE TITLE
[bug]NPC with knockback sword can knockback knockback resistance 100% mobs

### ISSUE THREAD

**Issue by hkkongou** [CitizensDev/Citizens2#2735]
### `/version` output

```txt
[11:40:41 INFO]: This server is running Paper version git-Paper-152 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 78999b5)
You are 15 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Purpur-1506 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
[11:40:31 INFO]: Citizens version 2.0.29-SNAPSHOT (build 2448)
[11:40:31 INFO]: Website: http://www.citizensnpcs.co
[11:40:31 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/92434

### config.yml

https://paste.denizenscript.com/View/92433

### saves.yml

https://paste.denizenscript.com/View/92432

### Description

NPC can knockback mobs with 100% knockback resistance.
i am using mythicmobs to make mobs, i made a mob with 100% knockback resistance as mob setting, which can prevent player knockback using any kind of knockback method(such as enchant), the mob can resist any player knockback, but it cannot resist NPC with a simple knockback enchantment.

i also checked by adding a normal knockback resistance boot to my mob, i also tested the boot myself, wearing the boot can resist all knockback from player and mob, but still, cannot resist NPC attack's knockback

video provided: 
https://youtu.be/rXGCwP3phbE

**Comment by mcmonkey4eva** [comment]
That sounds like an issue with either mythicmobs or Sentinel - either way, not Citizens.

**Comment by hkkongou** [comment]
> That sounds like an issue with either mythicmobs or Sentinel - either way, not Citizens.

so do i need to copy all of the things about to sentinel github?
is your projects 🤔
