### ISSUE TITLE
Player NPCs crawling

### ISSUE THREAD

**Issue by VladMoore** [CitizensDev/Citizens2#2737]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

1.As of 1.14 (I believe) players have been able to get into a crawling position in 1 block vertical gap. It just seems like something an NPC should be able to do.
2. A lot of cool builds could be achieved by having NPCs crawl or lay; like crime scenes, etc.
3. I have not found an alternative, unfortunately.

**Comment by fullwall** [comment]
Is this for pathfinding? I thought this was a visual thing when in small gaps

**Comment by mcmonkey4eva** [comment]
*Theoretically* you can just call `LivingEntity#setSwimming(true)` and it should apply the visual effect (crawling and swimming are the same stance internally). In practice, this doesn't currently work on NPCs, so there's likely something in the NMS that would need to be changed for it to be possible to apply.

For real players, it works (excluding self-view) with a combination of `setSwimming(true)` and cancelling `EntityToggleSwimEvent` when `event.isSwimming()` is `false`. (For a player to see it on their own client, there's a much more complicated solution, but that can be ignored for NPC usage)

**Comment by HowardZHY** [comment]
is there a way to let player type NPCs sitting(riding on a arrow) ?

**Comment by mcmonkey4eva** [comment]
@HowardZHY  ask on Discord @ https://discord.gg/Q6pZGSR , don't hijack unrelated github issues please

**Comment by HowardZHY** [comment]
my discord is unavailable now.
sorry about that.



At 2022-05-02 06:47:32, "mcmonkey4eva" ***@***.***> wrote:

@HowardZHY ask on Discord @ https://discord.gg/Q6pZGSR , don't hijack unrelated github issues please

**Comment by fullwall** [comment]
Track here https://github.com/CitizensDev/Citizens2/issues/2993
