### ISSUE TITLE
 Task #510 for Citizens v2.0.29-SNAPSHOT (build 2448) generated an exception

### ISSUE THREAD

**Issue by TheGamingFireman** [CitizensDev/Citizens2#2739]
Consol spamming on any server I put the plugin on. This is spammed to my consol once a second. The plugin works fine and the config is default. 
waterfall-1.18-466
purpur 1.18-64

**Comment by mcmonkey4eva** [comment]
either post an issue that follows the bug report template, or ask for help on Discord @ https://discord.gg/Q6pZGSR
