### ISSUE TITLE
Netherite Repair Blacksmith

### ISSUE THREAD

**Issue by Drizzt11** [CitizensDev/Citizens2#2742]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

The repair shop is a great plugin and works great with what it is compatible with. It doesnt work with Netherite. I wish it would so the gear that my players worked hard for pays off with money repairs.

**Comment by Drizzt11** [comment]
Blacksmith plugin I mean

**Comment by mcmonkey4eva** [comment]
Blacksmith is a separate plugin from Citizens, maintained by other people. I don't know whether anybody currently maintains it tbh. Usually that functionally gets replaced by a Denizen script.
