### ISSUE TITLE
ClassCastException when trying to use Pathfinding

### ISSUE THREAD

**Issue by byquanton** [CitizensDev/Citizens2#2746]
### `/version` output

```txt
This server is running Paper version git-Paper-204 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7b8e0c3)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2480)
```

### Log file

https://paste.denizenscript.com/View/93583

### config.yml

https://paste.denizenscript.com/View/93584

### saves.yml

https://pastebin.com/JSW1Ghy7

### Description

Fresh installation of Citizens. 
Created an NPC and used `/npc pathto x y z` Command

**Comment by fullwall** [comment]
Fixed
