### ISSUE TITLE
NPC problem

### ISSUE THREAD

**Issue by KreWw** [CitizensDev/Citizens2#275]
So whenever I create an npc it is all ok but I dont like his type so when I change it his name dissapears and only appears when you look at him whilst when I dont change his type to villager his name is always there above his head even if I dont look at him. The other thing is that sometimes the npcs are not there so I have to relog to see them. Thank you for reading!

**Comment by mcmonkey4eva** [comment]
What.

**Comment by KreWw** [comment]
The name above the npc I create dissapears when I change his /type villager . It does not dissapear completely but it only appears when I cursor over him. And sometimes the npc will dissapear and to see him again I have to either walk away and come back or relog.

**Comment by mcmonkey4eva** [comment]
Nametag issue is here: https://github.com/CitizensDev/Citizens2/issues/77
I've never heard of mob-type NPCs disappearing though. Only player type NPCs have ever had disappearing issues. Perhaps you have some external plugin (EG, clearlagg) deleting the entities?

**Comment by KreWw** [comment]
Nope clearlagg does not clear villagers or npcs. But Im not 100% sure if it does tell me how to stop it.

**Comment by mcmonkey4eva** [comment]
I have no idea what to do with this - nobody else is reporting this issue.
