### ISSUE TITLE
Path Command throws errors

### ISSUE THREAD

**Issue by Popcwrn** [CitizensDev/Citizens2#2750]
### `/version` output

```txt
[08:11:00 INFO]: This server is running Paper version git-Paper-207 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b757019)
You are running the latest version
Previous version: git-Paper-204 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
[08:11:11 INFO]: Citizens version 2.0.29-SNAPSHOT (build 2478)
[08:11:11 INFO]: Website: http://www.citizensnpcs.co
[08:11:11 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/93652

### config.yml

https://paste.denizenscript.com/View/93651

### saves.yml

https://paste.denizenscript.com/View/93650

### Profiler report

https://spark.lucko.me/Z7VSYaZtBK

### Description

Im fairly new to Citizens2 and utilizing its commands. However, I just tried to create an NPC. Creating the NPC and everything seems to work perfectly fine. However, when it comes to pathing the NPC using the `/npc path` command. This is when the errors occur. 

I would like it to be understood that directly typing that command itself doesn't actually throw the error. Instead, its actually as soon as I try to set a waypoint that the errors occur (As you can see it being spammed in my latest.log). Not too sure what's causing this but any and all assistance is appreciated!

**Comment by mcmonkey4eva** [comment]
You had the bad luck of downloading a temporarily broken build - that bug was introduced and then fixed both within the past few days. Update: https://ci.citizensnpcs.co/job/Citizens2/
