### ISSUE TITLE
package net.citizensnpcs.api.event does not exist

### ISSUE THREAD

**Issue by Andrei0016** [CitizensDev/Citizens2#2751]
I was using the API to make a NPC and made a Click event for it and when I compiled I got this error. **package net.citizensnpcs.api.event does not exist**. I get no errors in the editor.
This is the code:
`public class npc_click_event implements Listener {
    @EventHandler
    public void getNPC(NPCClickEvent event) {
        NPC npc = event.getNPC();
        Player player = event.getClicker();
        if (npc.getName() == "Worker NPC") {

            Inventory gui = Bukkit.createInventory(player, 18, ChatColor.AQUA + "NPC Inventory");
            ItemStack menu_blank = new ItemStack(Material.GRAY_STAINED_GLASS_PANE, 1);
            ItemMeta menu_blank_meta = menu_blank.getItemMeta();
            menu_blank_meta.setDisplayName(ChatColor.GRAY + " ");
            menu_blank.setItemMeta(menu_blank_meta);
            gui.setItem(5, menu_blank);
            gui.setItem(7, menu_blank);
            gui.setItem(9, menu_blank);
            gui.setItem(10, menu_blank);
            gui.setItem(11, menu_blank);
            gui.setItem(12, menu_blank);
            gui.setItem(13, menu_blank);
            gui.setItem(14, menu_blank);
            gui.setItem(15, menu_blank);
            gui.setItem(16, menu_blank);
            gui.setItem(17, menu_blank);
            player.openInventory(gui);
        }
    }
}`
API version: 2.0.29-SNAPSHOT

**Comment by mcmonkey4eva** [comment]
This is an issue with your editor, compiler, or pom file. It's not an issue related to Citizens itself.

Check the linking properly section of https://wiki.citizensnpcs.co/API
Consider also asking for help on Discord @ https://discord.gg/Q6pZGSR

Also you need NPCRightClickEvent not the base class
