### ISSUE TITLE
Illegal State Exception

### ISSUE THREAD

**Issue by GamerMedic** [CitizensDev/Citizens2#2753]
### `/version` output

```txt
26.02 16:17:16 [Server] INFO Checking version, please wait...
26.02 16:17:16 [Server] INFO This server is running Purpur version git-Purpur-1489 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: ed169a3 on HEAD)
26.02 16:17:16 [Server] INFO You are 76 version(s) behind
26.02 16:17:16 [Server] INFO Download the new version at: https://purpurmc.org/downloads
26.02 16:17:16 [Server] INFO Previous version: git-Paper-101 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
26.02 16:17:37 [Server] INFO Citizens version 2.0.29-SNAPSHOT (build 2462)
26.02 16:17:37 [Server] INFO Website: http://www.citizensnpcs.co
26.02 16:17:37 [Server] INFO Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/93838

### config.yml

https://paste.denizenscript.com/View/93839

### saves.yml

https://paste.denizenscript.com/View/93840

### Description

This error regularly appears in the log without any input required. The server simply needs to be on with Citizens enabled. Just in the (unlikely) case of plugin conflict, I have pasted my plugin list below.

26.02 16:25:31 [Server] INFO Plugins (46): AdvancedBan, ajLeaderboards, AngelChest, ArmorStandTools, AuctionHouse, BetonQuest, BetterChair, BetterEconomy, BetterRTP, Bookshelf, Brewery, Citizens, CMI, CMILib, CoordinatesHud, CoreProtect, CrateReloaded, Denizen, dynmap, Elevator, EzChestShop, FastAsyncWorldEdit (WorldEdit), FeatherBoard, GrapplingHook, HeadDatabase, ImprovedFactions, InvSeePlusPlus, LuckPerms, Multiverse-Core, Multiverse-Portals, MVdWPlaceholderAPI*, NBTAPI, PlaceholderAPI, PlayerNightVision, PlayerVaults, ProtocolLib, RanksReloaded, SafeTrade, Shopkeepers, TreasureChest, UndeadPandemic, Vault, Vehicles, Votifier, WorldEditSUI, WorldGuard

**Comment by mcmonkey4eva** [comment]
Please test swapping from Purpur to either Paper or Spigot, as it's possible the error originates in changes made by Purpur.
