### ISSUE TITLE
Add Clickable links to NPC Text Page List

### ISSUE THREAD

**Issue by PalmTamino** [CitizensDev/Citizens2#2755]
Add Clickable links to npc's like [<<] 3/8 [>>] and when you click it shows a new text with at the end [<<] 4/8 [>>]

**Comment by mcmonkey4eva** [comment]
Is your request for `/npc text` to have clickable links in the list of pages to scroll through the pages automatically?

**Comment by PalmTamino** [comment]
> Is your request for `/npc text` to have clickable links in the list of pages to scroll through the pages with?

Yes
