### ISSUE TITLE
Plugin doesnt support 1.18.2 yet

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#2756]
### `/version` output

```txt
spigot 1.18.2
```

### `/version Citizens` output

```txt
2.0.29 Build 2488
```

### Log file

https://paste.denizenscript.com/View/93919

### config.yml

https://paste.denizenscript.com/View/93919

### saves.yml

https://paste.denizenscript.com/View/93919

### Description

plugn deies loading for now on spigot

**Comment by mcmonkey4eva** [comment]
It does in fact support 1.18.2 https://ci.citizensnpcs.co/job/Citizens2/
