### ISSUE TITLE
select doesnt work

### ISSUE THREAD

**Issue by FireStrider12S** [CitizensDev/Citizens2#2757]
### `/version` output

```txt
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-400 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
2.0.28-SNAPSHOT (build 2359)
```

### Log file

https://paste.denizenscript.com/View/93952

### config.yml

https://paste.denizenscript.com/View/93953

### saves.yml

# Citizens NPC Storage

### Description

Whenever I look at a villager and I type '/npc select' it does nothing...

**Comment by mcmonkey4eva** [comment]
First of all, please review the output of the automated log check:
![](https://i.alexgoodwin.media/i/misc/3ad647.png)

Second... do you think vanilla villagers are NPCs? They're not. Citizens is used to create its own NPCs. Do a google or youtube search for tutorials on how to use Citizens and/or look through the wiki https://wiki.citizensnpcs.co/Citizens_Wiki
also for further basic  help questions consider asking on Discord https://discord.gg/Q6pZGSR
