### ISSUE TITLE
free version is not 1.18

### ISSUE THREAD

**Issue by Justwasbeer** [CitizensDev/Citizens2#2758]
### `/version` output

```txt
its not 1.18 so i cant use on my server it says its nog enabled and the commands dont work
```

### `/version Citizens` output

```txt
ss
```

### Log file

 dont have

### config.yml

 dont have

### saves.yml

 dont have

### Profiler report

 s 

### Description

 ssss

**Comment by BehrRiley** [comment]
Please don't troll the issues page.

Actually read, follow, and update your issue post to actually provide the requested information per the template you ignored, fix it yourself, or request faster support on Discord at https://discord.gg/Q6pZGSR. Per the warning:
![image](https://user-images.githubusercontent.com/46008563/156688573-35edbe80-033d-4259-9695-1ab4eb912fba.png)

By not doing so you're wasting everyone's time by pasting an issue that will likely never receive any helpful support.

If by chance you mean you're running Spigot or Paper version 1.18, update to 1.18.1 and use the last build of Citizens for 1.18.1 located at https://ci.citizensnpcs.co/job/Citizens2/2490/, or update to 1.18.2 and use the the latest version. Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.
