### ISSUE TITLE
Pass customHolderProvider to entity registry

### ISSUE THREAD

**Issue by datatags** [CitizensDev/Citizens2#2759]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Couldn't decide if this was a bug or feature request, but here you go. This is in reference to 1.18.2 with Mojang mappings specifically.

Citizens seems to replace the NMS entity registry with its [own wrapped version](https://github.com/CitizensDev/Citizens2/blob/master/v1_18_R2/src/main/java/net/citizensnpcs/nms/v1_18_R2/util/CustomEntityRegistry.java), but doesn't construct it in the same way the NMS version is constructed. When the NMS entity registry is constructed (through DefaultedRegistry), it's passed 4 arguments, while the Citizens registry only passes 3 arguments to the DefaultedRegistry constructor (leaving off one that is stored in MappedRegistry under the name `customHolderProvider`.

I'm working on a plugin that registers its own entities in the NMS entity registry using `Registry.register(...)` which calls `MappedRegistry#createIntrusiveHolder(...)` somewhere down the line. In 1.18.2, the entity registry was changed so that it no longer accepts new entries in this way at the time plugins are loaded, due to being "frozen." I've worked around this by resetting `frozen` and the other field that's cleared when the registry is frozen, but there's another check for `customHolderProvider` that is set in the normal NMS registry but is not set in the Citizens registry.

I imagine my plugin is not the only one that registers entities this way, so this may help other plugins that also depend on this vanilla behavior.

There's probably another way I could register entities, but I don't know what it is (I didn't write the entity registration code for this plugin to begin with). If you have suggestions, let me know.

Thanks

### Code Example

```java
// current code: from https://github.com/CitizensDev/Citizens2/blob/0a9176836987a8ca7ff059a47b1bebfe4fe71fcf/v1_18_R2/src/main/java/net/citizensnpcs/nms/v1_18_R2/util/CustomEntityRegistry.java#L144-L146
super(original.getDefaultKey().getNamespace(),
                (ResourceKey<Registry<EntityType<?>>>) IREGISTRY_RESOURCE_KEY.invoke(original),
                (Lifecycle) IREGISTRY_LIFECYCLE.invoke(original), null); // <- note null arg
// don't really know how Citizens does things, but NMS uses something like this:
(Registry<T> var0) -> EntityType.PIG
```

**Comment by mcmonkey4eva** [comment]
Fullwall fixed this in https://github.com/CitizensDev/Citizens2/commit/ae36f4bd9f74e75e48090096aa4deca3947f2659 (build 2492+)
