### ISSUE TITLE
Why Isnt It Active, Why Doesnt It Work???

### ISSUE THREAD

**Issue by coolguy87653** [CitizensDev/Citizens2#276]
Hello Im Asking why my citizen plugin doesn't work? I Have Spigot And I Have The Plugins To Run It But Still It Doesn't Work, Why Can you please him me. thank you

by: coolgyt: bosscraft networks owner.

**Comment by Morphan1** [comment]
What is this

**Comment by AnthonyAMC** [comment]
Why didn't you provide any relevant info?

**Comment by Morphan1** [comment]
Um... Well now that you've edited the information in, choose the correct link for your Spigot version from this page http://wiki.citizensnpcs.co/Versions

**Comment by coolguy87653** [comment]
Never mine, now when I get the plugin it crashes my server do you have any solutions...?

**Comment by coolguy87653** [comment]
I Have the version 1.7.9

**Comment by mcmonkey4eva** [comment]
Post the error message maybe?

**Comment by ELJESTER** [comment]
I as having the same problem, Citizens plugins works fine even though the skins were still not fixed :(, If you downloaded the newest dev build its only for Minecraft 1.8.3 according to "Morphan1" perhaps update your Minecraft server to 1.8.3 or downgrade citizens...
