### ISSUE TITLE
Placeholder skin

### ISSUE THREAD

**Issue by Trinchezito** [CitizensDev/Citizens2#2760]
### `/version` output

```txt
paper 1.18.2
```

### `/version Citizens` output

```txt
2493
```

### Log file

.

### config.yml

.

### saves.yml

.

### Description

I do /npc name %ajlb_lb_superior_island_total_level_1_alltime_name% - It works.

When i do /npc skin %ajlb_lb_superior_island_total_level_2_alltime_name% it does not work. It doesn't update the skin. I'm on 1.18.1 and running Build #2493

**Comment by fullwall** [comment]
Please ask the placeholder provider

**Comment by mcmonkey4eva** [comment]
If you get lost and/or can't find anything wrong with the placeholders themselves, consider starting a thread within the Citizens channel on Discord @ https://discord.gg/Q6pZGSR and we might be able to help you through it
