### ISSUE TITLE
Not compatible with Minecraft v1_18_R1

### ISSUE THREAD

**Issue by tuckerandlexus** [CitizensDev/Citizens2#2762]
### `/version` output

```txt
This server is running CraftBukkit version 3443-Spigot-699290c-2c1e499 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
[20:40:10] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1605)
[20:40:10] [Server thread/INFO]: [Citizens] Could not fetch NMS field modifiers: [[modifiers.
[20:40:10] [Server thread/ERROR]: [Citizens] v2.0.24-SNAPSHOT (build 1605) is not compatible with Minecraft v1_18_R1 - try upgrading or downgrading Citizens. Disabling.
[20:40:10] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1605)
```

### Log file

https://paste.denizenscript.com/View/94153

### config.yml

https://paste.denizenscript.com/View/94154

### saves.yml

https://paste.denizenscript.com/View/94154

### Description

Hi there. I am not sure if this is an actual bug, so please pardon my lack of knowledge on this issue. I just started a new server and for some reason I can not get the Citizens plugin to work. It just keeps disabling and telling me I have the wrong version. I tried running it with only vault and citizens as my plugins and I have tried versions 2.0.24, 2.0.17, 2.0.16, 2.0.14, and even 2.0.29, but none of them work. I believe my Minecraft spigot version is 1.18.1 and I have the most recent vault version 1.7.3. I could not attach a saves.yml since it keeps disabling. I was really hoping to use the Sentinel plugin with Citizens. Please let me know if there is anything else I can provide or if you could please provide direction on how I can resolve this issue. Thank you kindly. Cindy

**Comment by mcmonkey4eva** [comment]
Update to 1.18.2

**Comment by mcmonkey4eva** [comment]
Also download Citizens from an official current source - dev builds https://ci.citizensnpcs.co/job/Citizens2/ or spigot https://www.spigotmc.org/resources/citizens.13811/

**Comment by tuckerandlexus** [comment]
> Also download Citizens from an official current source - dev builds https://ci.citizensnpcs.co/job/Citizens2/ or spigot https://www.spigotmc.org/resources/citizens.13811/

Thank you
