### ISSUE TITLE
ADD AN OPTION TO : Automatically comes back the NPCs look in the direction they were spawned in after the player moves away.

### ISSUE THREAD

**Issue by CarraGrive** [CitizensDev/Citizens2#2763]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

That's clearly the feature that everyone needs.
Add a command or option to Citizens that allows the NPC to look in the direction they were spawned in after the player moves away.
This would avoid having NPCs looking at the ground, the sky or behind them.

**Comment by fullwall** [comment]
Already exists - set the default pose using /npc pose

**Comment by CarraGrive** [comment]
Can you give more explanation on how that works cause the command isn't actually doing what i suggested.

**Comment by fullwall** [comment]
/npc pose --save [name] -d will make it the default pose

**Comment by CarraGrive** [comment]
The command is a bit complex for something that basic but ok.
There is any possibility to reduce the speed rotation of the head or make it more natural?

**Comment by fullwall** [comment]
Sure, that's fair.
The speed rotation question is tricky for players but there is an open issue for that.

**Comment by CarraGrive** [comment]
Yeah, right now the head is moving too fast and not naturally + the body is not following the head properly, it looks like a bot.
https://gyazo.com/e5045a68a755d6068db0b2bd4e4053bb

**Comment by mcmonkey4eva** [comment]
It *is* a bot.
