### ISSUE TITLE
[Feature Request] Add support for skin restorer skins

### ISSUE THREAD

**Issue by DeathGOD7** [CitizensDev/Citizens2#2764]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [x] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

1. To add support for skins created from Skin Restorer and have support for same skin for multi-server under proxy.
2. Well they can use the same skin for different NPC in the whole servers under proxy
3. Nope

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Skins
