### ISSUE TITLE
IllegalArgumentException: yaw not finite (on HologramTrait Entity)

### ISSUE THREAD

**Issue by Koboo** [CitizensDev/Citizens2#2766]
### `/version` output

```txt
This server is running Tuinity version git-Tuinity-"ac3aee1" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2498)
```

### Log file

https://paste.denizenscript.com/View/94180

### config.yml

https://paste.denizenscript.com/View/94179

### saves.yml

https://paste.denizenscript.com/View/94181

### Description

Hello,

I have some wolf NPCs which I spawn (through Java-Code). I also have a trait that is responsible for attacks and navigation. Unfortunately I always get the `IllegalArgumentException: yaw not finite`. As can be seen in the logs, the problem seems to be that the value `yaw` of the location is `NaN`. 

After searching in my source code I couldn't find the error. Therefore I looked at the source code details of the StackTrace in Citizens.

There I asked myself why the values `yaw` and `pitch` of the NPC are sent with a teleport of the hologram entities and if this is needed at all, because the ArmorStand is invisible and the NameTag is rotated client-side. (related Source code: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/HologramTrait.java#L226)

Would it be possible on your part to explicitly set the `yaw` and `pitch` to 0 before teleporting the hologram entity? If not, would you have an idea why such an error occurs?

Otherwise, thank you in advance for your answer and your great work on Citizens!

With kind regards 
Koboo

**Comment by mcmonkey4eva** [comment]
Your suggested fix wouldn't *fix* much it would just move the error to a different location. The root of the issue is whatever created the infinite yaw.

That said, prior #1 should be updating your server to a stable version like Paper 1.18.2 (or 1.17.1).

Tuinity is a project that shut down a while ago now.

There's a decent chance that just moving to a stabler version will avoid issues like that.

**Comment by einfachBlu** [comment]
But upgrading to newer minecraft versions is not always the best solution. This could fix the issue, but in case the server has already lots of things that need to run on 1.16?

Do you have any ideas except upgrading to 1.17 or 1.18?

**Comment by mcmonkey4eva** [comment]
Updating is -essential-. Your server version is vulnerable to the Log4Shell attack.

**Comment by einfachBlu** [comment]
Do you know any other active spigot/paper fork for 1.16 that works fine with citizens2?

**Comment by fullwall** [comment]
What created the infinite yaw in the first place?

**Comment by einfachBlu** [comment]
We try to find that but we havent found anything yet. Its not from our systems. it must be either from citizens2 or tuinity

**Comment by mergu** [comment]
To be clear, someone can take over your minecraft server by posting a simple message in chat until you update. This is a very critical thing to fix, and if you can't update, this is a "stop your server until you do" sort of thing
