### ISSUE TITLE
Allow Non-Player Type NPCs to have customizable persitent pitch

### ISSUE THREAD

**Issue by ComradeVist** [CitizensDev/Citizens2#2767]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Currently, when a non-player type NPC is out of `/npc look`, it cannot have a pitch different from 0, and its pitch is not preserved. I would like to request the ability to customize this to allow non-player type NPCs to have different pitch that is persistent. This would allow for non-player NPCs to be able to look in specific directions, just as a player type already could, allowing for more immersive NPCs as well as ways of subtly guiding a player towards something of interest.

Some examples of this in use:
A Cat looking up at a fish tank
An Iron Golem solemnly looking down
A group of passive animals looking down at a suspicious object

The only alternatives to this currently are to either use a player type, which might break immersion, or to enable `/npc look`, which would change the NPC's pitch when any player approaches it.

**Comment by fullwall** [comment]
Added
