### ISSUE TITLE
Ondisable error

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2768]
### `/version` output

```txt
Paper 1.18.2 build 249
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT build 2508
```

### Log file

https://paste.denizenscript.com/View/94333

### config.yml

N/A

### saves.yml

N/A

### Description

Throws an error after using `/restart`.

**Comment by mcmonkey4eva** [comment]
Would need your full log file, not just a random snippet.
Consider also asking for support on Discord @ https://discord.gg/Q6pZGSR
