### ISSUE TITLE
1.18.2 slowdown

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [CitizensDev/Citizens2#2769]
### `/version` output

```txt
17.03 17:44:09 [Server] INFO Current: git-Purpur-1596 (MC: 1.18.2)*
17.03 17:44:09 [Server] INFO Previous: git-Paper-225 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
17.03 17:44:02 [Server] INFO Citizens version 2.0.29-SNAPSHOT (build 2503)
17.03 17:44:02 [Server] INFO Website: http://www.citizensnpcs.co
17.03 17:44:02 [Server] INFO Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/94408

### config.yml

https://paste.denizenscript.com/View/94410

### saves.yml

https://paste.denizenscript.com/View/94411

### Description

Once in a time server freezes due to error at the end of included log file. Then after every restart server freezes. The only possibility is to remove all npcs from saves.yml and then add it one by one to see, which one is bugged and then remove it and place again. After a few days it happens again, and again and again.

**Comment by fullwall** [comment]
Please provide a spark timing; this is not a crash

**Comment by mcmonkey4eva** [comment]
You have multiple NPCs stuck below Y:0 - `946, 905, 609`, if your min-world-height for world 'spawn' is below 0, this might be fine, but if you have a min-world-height of 0, this might be the source of the problem - NPCs below the bottom of the world can in some cases bug out.

**Comment by mcmonkey4eva** [comment]
Oh, oof. https://wiki.citizensnpcs.co/Cracks
