### ISSUE TITLE
Plugin not loading :\

### ISSUE THREAD

**Issue by ELJESTER** [CitizensDev/Citizens2#277]
17.03 01:59:40 [Server] INFO Enabling Bankcraft v2.4.2
17.03 01:59:40 [Server] INFO Disabling Citizens v2.0.15-SNAPSHOT (build 1220)
17.03 01:59:40 [Server] ERROR v2.0.15-SNAPSHOT (build 1220) is not compatible with Minecraft v1.8 - try upgrading or downgrading Citizens. Disabling.
17.03 01:59:40 [Server] INFO Enabling Citizens v2.0.15-SNAPSHOT (build 1220)
17.03 01:59:40 [Server] INFO 6 Destinations loaded!

I receive this error when loading the newest dev build of citizens, any theories?

**Comment by Morphan1** [comment]
The latest builds of Citizens2 are for 1.8.3
Consider upgrading your server
