### ISSUE TITLE
NPC Body Rotation doesn't persist properly

### ISSUE THREAD

**Issue by Garfieldwxg55** [CitizensDev/Citizens2#2770]
### `/version` output

```txt
This server is running Paper version git-Paper-260 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: bc68ee0)
You are running the latest version
Previous version: git-Paper-252 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2509)
```

### Log file

https://paste.denizenscript.com/View/94426

### config.yml

https://paste.denizenscript.com/View/94425

### saves.yml

https://paste.denizenscript.com/View/94424

### Description

I've noticed that NPC's saving their rotation when a player leaves and rejoins a server is really inconsistant. Some NPCs from older versions of the plugin seem to have saved their rotation correctly, but my newer ones don't seem to do that and instead face their heads in the right direction but their bodies will be awkwardly rotated. I've tried setting their rotation with /lookclose, but they go back to their old rotation after I leave the server and rejoin.

**Comment by mcmonkey4eva** [comment]
Update from testing and discussion in the dev channels:

Body rotation on older versions was synchronized to the head rotation by displaying an arm-swing animation, as this would force the body to match the head clientside. The NPC's head was then rotated from there to match the saved rotation.

In 1.18.2, this appears to no longer work:
![](https://i.alexgoodwin.media/i/misc/52e486.gif)

Meaning, a new solution to the issue will have to be found to correctly sync body&head yaw in modern minecraft versions.

**Comment by fullwall** [comment]
Just updating here from a few weeks ago; the arm swing code hasn't changed, unfortunately nothing else has been added to sync / set body yaw for players.

**Comment by PersonalDom** [comment]
You are a piece of shit. told by one dev to create a feature request.. the other bans me for disputing doing what Fuliwali requested. 

Get your shit together. Great teamwork.

**Comment by mcmonkey4eva** [comment]
It has been requested by another user\* to have a command to link head/body rotation to the same value automatically.

Relatedly it'd also be nice to have something like a `/npc moveto --body [yaw]`

(\* who unfortunately had to be blocked from this repo and Discord due to the inappropriate argumentative way they about it)

**Comment by NotifiedGaming** [comment]
Look, all i want is some help using your plugin. I did what fullwali told me to do, you're the one who is blowing this whole situation out of propertion. There is NO NEED to warn me for "causing an argument" When i'm literally just defending myself and confused on what the hell you want me to do.

Ban me again on this github, it just shows how Terrible your customer support is.

Unreal. behaviour. From both of us.

and banning me for 1 year when i try and defend myself again in the incident channel?

If i can't defend myself and argue the warning. why have the channel in the first place?

@fullwall Can I get that fix please.

All due respect, your friend doesn't have a clue what he's doing.

**Comment by JellyTale** [comment]
This issue has changed(?). Body rotation now persists, but head rotation for player NPCs always defaults to south for some reason. If you leave an NPC's active area and then load it back in, its head will face south by default.
