### ISSUE TITLE
Lag spike when player join server

### ISSUE THREAD

**Issue by hkkongou** [CitizensDev/Citizens2#2771]
### `/version` output

```txt
This server is running Paper version git-Paper-215 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7f65b0b)\nYou are 1 version(s) behind\nDownload the new version at: https://papermc.io/downloads\nPrevious version: git-Paper-198 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2488)
```

### Log file

https://paste.denizenscript.com/View/94472

### config.yml

https://paste.denizenscript.com/View/94474

### saves.yml

https://paste.denizenscript.com/View/94473

### Profiler report

https://spark.lucko.me/Ju515fQolO

### Description

I am finding some lag spikes which cause my server unstable, after recording spark profiler with 100ms+ spikes, the profiler show citizen is the first one in the list

**Comment by fullwall** [comment]
Seems to be due to chunk loads, some citizens debug would be helpful.

**Comment by mcmonkey4eva** [comment]
You should probably update to 1.18.2, the latest build of Citizens, and latest builds of any other outdated plugins before going further.

**Comment by hkkongou** [comment]
> Seems to be due to chunk loads, some citizens debug would be helpful.

excuse me, how to do citizen debug?

**Comment by mcmonkey4eva** [comment]
Open your `plugins/Citizens/config.yml` file and swap `debug-mode` to `true`
