### ISSUE TITLE
NullPointerException with EnderdragonNPC

### ISSUE THREAD

**Issue by DopiGFX** [CitizensDev/Citizens2#2772]
### `/version` output

```txt
git-Purpur-1597 (MC: 1.18.2)

// Purpur is built ontop of paper
// Paper version in this build is git-Paper-260
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2506)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/94547

### config.yml

https://paste.denizenscript.com/View/94548

### saves.yml

https://paste.denizenscript.com/View/94549

### Description

I spawned an Enderdragon-NPC in my world and the console got spammed with endless nullpointer exceptions...
/npc despawn -> no Nullpointers
/npc spawn -> starts again

You can find its configuration in my provided saves.yml starting at line 65

If you need any more information, just let me know

**Comment by mcmonkey4eva** [comment]
Please test on Paper

**Comment by mcmonkey4eva** [comment]
Need the logs from the paper test

**Comment by DopiGFX** [comment]
https://paste.denizenscript.com/View/94550

**Comment by mcmonkey4eva** [comment]
Did some testing, couldn't replicate at first but realized you missed a step: `/npc bossbar`. The error is related to the NMS implementation of the bossbar trait.

**Comment by DopiGFX** [comment]
Ohh yea I see... I removed the Bossbar-Options in the config, now the error is gone :) Thanks for your quick help

**Comment by mcmonkey4eva** [comment]
fullwall pushed https://github.com/CitizensDev/Citizens2/commit/2c8b1864d840feb902d8c267dd9eb40518642100 to fix the error properly
