### ISSUE TITLE
Npc's not spawning with Prorpgitems

### ISSUE THREAD

**Issue by Alphavin** [CitizensDev/Citizens2#2773]
### `/version` output

```txt
1.18.2
```

### `/version Citizens` output

```txt
Citizens2.0.29 #5
```

### Log file

https://paste.denizenscript.com/View/94562

### config.yml

https://paste.denizenscript.com/View/94560

### saves.yml

https://paste.denizenscript.com/View/94561

### Description

Wean i join my server some npc's dont load like the ones with ProRPGItems traits do not load and the ones with dtlTradersPlus traits do load oo and wean i logoff and back on agen i have to reload agen

**Comment by Alphavin** [comment]
now it not loading right with dtlTradersPlus traits as well

**Comment by mcmonkey4eva** [comment]
A: that log is flooded with errors from "ActionZones"
B: remove CitizensCMD and use the built-in command system  https://wiki.citizensnpcs.co/NPC_Commands
C: Consider switching to Paper
D: Any issues relating to third party traits are issues that should be reported to the developers of those traits, not us
