### ISSUE TITLE
Plugin Not Working On Minecraft server (MINEHUT)

### ISSUE THREAD

**Issue by Johnnyhesih** [CitizensDev/Citizens2#2776]
Problem:Whenever i typed the command , this pop up 
![2022-03-27_19 13 00](https://user-images.githubusercontent.com/102461807/160278887-82b93708-e1a2-45c1-85a8-1e8da5cd4ea0.png)

Here is the log of the server:
![Capture](https://user-images.githubusercontent.com/102461807/160278969-fe7f3206-56dc-4173-bd38-f37d575b571c.PNG)
![Capture3](https://user-images.githubusercontent.com/102461807/160278974-16ee73f7-ffab-48f8-8494-40ad94ebd224.PNG)

I just started the server.Version 1.18.1
Sorry, i don't really know how to use github
Label:Help

Best Regerds

**Comment by mcmonkey4eva** [comment]
Download Paper 1.18.2, not .1
