### ISSUE TITLE
NPC gets stuck trying to navigate down scaffolding

### ISSUE THREAD

**Issue by andrew121410** [CitizensDev/Citizens2#2778]
### `/version` output

```txt
This server is running Paper version git-Paper-268 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e2f743d)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-384 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2511)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/94930

### config.yml

https://paste.denizenscript.com/View/94932

### saves.yml

https://paste.denizenscript.com/View/94933

### Description

When the NPC is trying to navigate down scaffolding it gets stuck. 

![image](https://user-images.githubusercontent.com/12376951/160920024-989259b0-8af5-4925-8ba6-dd7eceeefb90.png)

**Comment by andrew121410** [comment]
Seems like it sneaks too early

**Comment by fullwall** [comment]
Thanks, I have made it sneak a bit later in the latest dev builds.

**Comment by mcmonkey4eva** [comment]
Commit reference: https://github.com/CitizensDev/CitizensAPI/commit/cafd1b0bd2e77674f4ab90837f1f3b0bd7eabe12
Fix is included in build 2516+ from https://ci.citizensnpcs.co/job/Citizens2/
