### ISSUE TITLE
Add 1.1.8.1 Support

### ISSUE THREAD

**Issue by Schnozbanger** [CitizensDev/Citizens2#2779]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

You Should Add 1.1.8.1 Support

**Comment by andrew121410** [comment]
Citizens only supports the latest patch versions of Minecraft. So for 1.18 only 1.18.2 is supported.

**Comment by BehrRiley** [comment]
We support only the latest patch-version of Minecraft for any recent main version (and Mojang, Spigot, Paper, etc. all generally also follow the same rule).

"Patch version" means the last number in a version label, for example in `1.16.5`, the main version is `1.16`, and the patch version is `.5`.
So if `1.16.5` is the latest patch version, then `1.16.4`, `1.16.3`, `1.16.2`, `1.16.1`, and `1.16(.0)` are all outdated patch versions, and therefore are permanently unsupported.

Note that we do still support recent older main versions (such as `1.17` and `1.16`) so long as you are on the latest patch-version of those main versions (like `1.17.1` and `1.16.5`).

You should never consider usage of an outdated patch version for security,performance, and many other reasons.
