### ISSUE TITLE
NPC (Excluding Type Player) Loose Mainhand items on Reload, of Server, Plugin or Chunks.

### ISSUE THREAD

**Issue by ZachRodgers** [CitizensDev/Citizens2#2780]
### `/version` output

```txt
This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-187 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2506)
```

### Log file

https://paste.denizenscript.com/View/95104

### config.yml

https://paste.denizenscript.com/View/95102

### saves.yml

https://paste.denizenscript.com/View/95103

### Description

Ever since updating the server and plugin to 1.18.2,
Pre-Exisiting and new NPC's have there main hand items deleted.
Use /npc equip
Offhand and armour stays on the NPC
Although Main Hand Items are Delete when the Chunks, Server or Plugin is Resetarted.

**Comment by mcmonkey4eva** [comment]
Try updating to the current dev build https://ci.citizensnpcs.co/job/Citizens2/

**Comment by ZachRodgers** [comment]
Thankyou, that solved the issue.
