### ISSUE TITLE
[BUG] Citizen nametag bug

### ISSUE THREAD

**Issue by kedavlar** [CitizensDev/Citizens2#2783]
### `/version` output

```txt
1.16.5 tuinity
```

### `/version Citizens` output

```txt
2.0.29 build 2511
```

### Log file

https://paste.denizenscript.com/View/95319

### config.yml

https://paste.denizenscript.com/View/95320

### saves.yml

https://paste.denizenscript.com/View/95321

### Description

![2022-04-10_20 44 37](https://user-images.githubusercontent.com/85011614/162634770-0b6ec147-01b4-403c-9f16-cac9f59e7cf2.png)

As you can see there 2 holo on the npc, the bug disappar when player quit and re-join. The second holo i think is the nametag with like: CIT-6fd6ff5

**Comment by mcmonkey4eva** [comment]
Very likely related to your obscure fork (Tuinity) of an outdated minecraft version (1.16.5).
It's important to note here that unless you have a special specific sub-fork of tuinity that's been updated very recently, your server is likely vulnerable to the Log4Shell attack (ie malicious players could crash or even take control of your server).
If you're on Discord, a post explaining that is in the `#news` channel @ https://discord.com/channels/315163488085475337/485397838923038730/918978685934137344

---

LogCheck also reports an unsupported Java version and some plugins known to often be related to issues, so you might also try testing whether the issue occurs on Java 8 or 16/17, or without those plugins

![](https://i.alexgoodwin.media/i/misc/176f25.png)

If you need more general help with Citizens or with tracking down which specific incompatibility is the source of the issue, consider asking for support on Discord @ https://discord.gg/Q6pZGSR

If you don't switch over to Discord, and you're able to replicate this issue on a supported server configuration (primarily Spigot/Paper as opposed to the fork), feel free also to reply below with a demonstration of replication on a supported server version.

**Comment by kedavlar** [comment]
i have a special version of tuinity, its not vulnerable. I also try with java 8 and paper 1.16.5 and almost have no other plugin on the server
