### ISSUE TITLE
NPCs Going Missing In 1.18+ Until Reload

### ISSUE THREAD

**Issue by UltraFaceguy** [CitizensDev/Citizens2#2784]
### `/version` output

```txt
git-Paper-283 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2513)
```

### Log file

https://pastebin.com/raw/9ZRtuasp

### config.yml

https://pastebin.com/raw/9ZRtuasp

### saves.yml

https://pastebin.com/raw/9ZRtuasp

### Description

Upon updating from 1.17 to 1.18, NPCs on the fringe seem to be vanishing and not returning until everyone leaves the area. The NPC remains fine in the saves.yml, and re-appears when /citizens reload is run. This is presumably because chunks can now be loaded for only block data via the breaking of view-distance into simulation-distance and view-distance. Simulation handles the entity ticking and spawning chunk range, while view handles the block data. I believe citizens are being placed then removed in the area where only block data is kept.

To reproduce more easily:
- Place NPCs around a world
- set "simulation-distance" in server.properties to a low number (3)
- set "view-distance" to a high value (14)
- run around and load the chunks containing the NPCs

Issue doesn't occur if:
- NPC is close to a player when a player loads in a chunk, usually via teleportation into it
- Chunk containing the NPC remains loaded and in player range, such as being near the world's spawn protection

**Comment by BehrRiley** [comment]
Please don't troll in our issues forms; either properly fill out the forms or stick to submitting your information and requesting support on Discord. The entire bee movie script is not your server's log file, or your Citizens configuration file and saves file.

**Comment by UltraFaceguy** [comment]
I decline. If you don't want to solve the issue as is, don't.
