### ISSUE TITLE
When the NPC looks at the player, the rotation range of the head and body is inconsistent

### ISSUE THREAD

**Issue by luoxiawuchen** [CitizensDev/Citizens2#2789]
### `/version` output

```txt
This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2520)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/95552

### config.yml

https://paste.denizenscript.com/View/95553

### saves.yml

https://paste.denizenscript.com/View/95554

### Description

When the /NPC lookclose command is used to make the NPC look at the player, the rotation range of the body and the head is inconsistent. When the NPC head deflects 90 degrees, a strange situation will occur (as shown in the figure below)
![43{13I9D1 8N`D6@%F`@QQQ](https://user-images.githubusercontent.com/64759847/163805210-4c36e6fd-cf83-458b-8f1e-d8af3e208b6b.png)

**Comment by mcmonkey4eva** [comment]
This is odd, I can replicate this in 1.18.2
The odd thing is... we don't even really control the behavior at all serverside, it's theoretically processed clientside to my knowledge, so this is very confusing.

**Comment by fullwall** [comment]
This is controllable actually, I'll explain on discord.

**Comment by fullwall** [comment]
I think we'll track this one elsewhere
