### ISSUE TITLE
spawn command - 'unknown target reason'

### ISSUE THREAD

**Issue by uledrith** [CitizensDev/Citizens2#279]
'''/ex spawn e@blaze target:<player>'''

I have found that putting pretty much anything after "target:" causes this error.  However, when you use the denizen debug -r and denizen submit it fails to capture this error message so I'm including a screenshot.

![capture](https://cloud.githubusercontent.com/assets/4096231/6680843/cfb8ab4e-cc2a-11e4-9437-4914eb41c507.JPG)

**Comment by Morphan1** [comment]
This is a Denizen issue.

**Comment by mcmonkey4eva** [comment]
Rather, it's a Spigot issue caused in Denizen code by coincidence.
