### ISSUE TITLE
More hologram NPCs than lines

### ISSUE THREAD

**Issue by DoubleNico** [CitizensDev/Citizens2#2793]
### `/version` output

```txt
git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2511)
```

### Log file

https://pastebin.com/BS7zjgxj

### config.yml

https://paste.denizenscript.com/View/95644

### saves.yml

the custom npc get deleted when server is closed

### Description

I want to implement holograms to a custom npc using the HologramTrait,
My code
`    public void addHologram(NPC npc, String text) {
        HologramTrait hologram = npc.getOrAddTrait(HologramTrait.class);
        hologram.addLine(text);
    }`
https://github.com/CitizensDev/Citizens2/blob/96ba80edd8bbd2146b1ab230485d349893c381d2/main/src/main/java/net/citizensnpcs/trait/HologramTrait.java#L59

https://github.com/CitizensDev/Citizens2/blob/96ba80edd8bbd2146b1ab230485d349893c381d2/main/src/main/java/net/citizensnpcs/trait/HologramTrait.java#L233

**Comment by mcmonkey4eva** [comment]
A: update to latest build https://ci.citizensnpcs.co/job/Citizens2/
B: if the issue continues, please post your FULL `logs/latest.log`, specifically to https://paste.denizenscript.com/New/Log and also all your Citizens-relevant java code (at the very least, the full function path from initial input to where it adds the hologram, including any new NPC creations or anything else you do in the same code)
C: consider also asking for help on Discord @ https://discord.gg/Q6pZGSR
