### ISSUE TITLE
Equipment packets spamming is messing up my script that raises a shield

### ISSUE THREAD

**Issue by DrewBeeDoo48** [CitizensDev/Citizens2#2794]
### `/version` output

```txt
This server is running Paper version git-Paper-295 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: c642d25)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
```

### `/version Citizens` output

```txt
Citizens version 2.0.29-SNAPSHOT (build 2520)
Website: http://www/citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/95783

### config.yml

https://paste.denizenscript.com/View/95785

### saves.yml

https://paste.denizenscript.com/View/95786

### Description

Basically, I was helped by making a thread to figure out how to make my NPC use its offhand item, which in this case is a shield. It works fine. However, there is a constant flicker as the npc is holding it, which I was told was because citizens spams the equipment packets constantly. Hopefully there is a fix to this.

**Comment by mcmonkey4eva** [comment]
Relevant technical info on this issue:
- `PlayerAnimation.start_use_offhand_item` is used to raise the shield, but it visibly flickers down and back up.
- This flicker appears to synchronize with the sending of an equipment packet from Citizens - it can even be modified via the `packets.update-delay` config setting
- The NPC's equipment isn't actually changing in this time, meaning the equipment packet is redundant
- Ideally, the code that sends out equipment packets should be checking whether there's been any change, and not sending the packet if so. This would allow the shield to remain raised continually as one would expect, and *possibly* alleviate other bugs this packet flood might cause as well (not sure if any exists, but it feels like this general state reset the equipment packet causes might have other visual oddities that we just haven't paid attention to previously)

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/Citizens2/commit/3685d339803494fa17b4844015bf85f117cb8b8e# in build 2533+
