### ISSUE TITLE
citizens is causing lag after some time

### ISSUE THREAD

**Issue by DEADLYDEVIL-SPIGOT** [CitizensDev/Citizens2#2795]
### `/version` output

```txt
Airplane version git-Airplane-"d9154a1" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d9154a1 on purpur/1.17)
```

### `/version Citizens` output

```txt
2.0.29-SNAPSHOT (build 2534)
```

### Log file

https://paste.denizenscript.com/View/95915

### config.yml

https://paste.denizenscript.com/View/95916

### saves.yml

https://paste.denizenscript.com/View/95917

### Profiler report

https://spark.lucko.me/VGPEIPLfJU

### Description

when server runs it's fine for like 1 or 2 hour after that it will get laggy and tps will drop under 13

**Comment by BehrRiley** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> https://wiki.citizensnpcs.co/Cracks

it was working fine after I changed from 1.16.4 to 1.17.1

**Comment by BehrRiley** [comment]
please read the information provided; we don't provide support for cracked servers

**Comment by DEADLYDEVIL-SPIGOT** [comment]
> 

what if I change my server to online-mode rightnow?

**Comment by mcmonkey4eva** [comment]
We generally prefer basic support start on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel.
In your case if you join there we can go through the steps of getting your server configured legally first on discord and then continue either with support on Discord or reopening the GitHub issue.
