### ISSUE TITLE
Render distance per NPC

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#2796]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Add the ability to see a "render distance" for each NPC so a player has to be X radius away for the NPC to be visible.

**Comment by mcmonkey4eva** [comment]
This miiiight be possible to implement via mucking with `ChunkMap.TrackedEntity#range`? (The entity-tracker-range)

**Comment by OceaniaCraft** [comment]
Would really love to see this!

**Comment by fullwall** [comment]
> This miiiight be possible to implement via mucking with `ChunkMap.TrackedEntity#range`? (The entity-tracker-range)

This is the tracking range from spigot.yml and is settable per entity (although I believe at present only set for Players).

**Comment by mcmonkey4eva** [comment]
This was added by fullwall via https://github.com/CitizensDev/CitizensAPI/commit/fb2563fbf2eadeb0397c6dc098237666751ffdcc and https://github.com/CitizensDev/Citizens2/commit/8d202aa988d913159e49fdafa9e17b381f704572
As: `/npc trackingrange [range]` and `/npc activationrange [range]`
