### ISSUE TITLE
not working on 1.18 :(

### ISSUE THREAD

**Issue by Szybkimp3** [CitizensDev/Citizens2#2797]
### `/version` output

```txt
This server is running Paper version git-Paper-66 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: dce79f3)
You are running the latest version
Previous version: git-Paper-398 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
citizens version 2.0.29-SNAPSHOT (build 2542)
```

### Log file

https://paste.denizenscript.com/View/96306

### config.yml

https://paste.denizenscript.com/View/96305

### saves.yml

none

### Description

not working :c
i tried with every version of citizens

**Comment by fullwall** [comment]
Upgrade to 1.18.2

**Comment by Szybkimp3** [comment]
ok
