### ISSUE TITLE
Add NPC Entity Types: Arrow & Fishing Hook

### ISSUE THREAD

**Issue by xxcodianxx** [CitizensDev/Citizens2#2798]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Citizens should allow you to create an NPC of entity type ARROW and FISHING_HOOK. Currently, an internal error is thrown whenever you try to use these  types.

- Allows using the existing pathfinding code to create things like a following flying arrow.
- Coverage for more entity typea in the Minecraft server, which is always good!

**Comment by mcmonkey4eva** [comment]
All entity types are spawnable. If there's a bug with any, report it as a bug.
Fishing hook NPCs being broken is already a tracked bug: https://github.com/CitizensDev/Citizens2/issues/1702
