### ISSUE TITLE
Problems with NPCs and Chunks

### ISSUE THREAD

**Issue by uledrith** [CitizensDev/Citizens2#280]
```
ChunkLoad:
  type: task
  debug: false
  script:
  - foreach <cu@msborder.list_partial_chunks.as_list> {
    - chunkload add location:<def[value]> }
```

```
General:
  type: world
  debug: true
  events:
    on server start:
    - run s@ChunkLoad
```
When using the above script in an 'on server start:', I have many problems with NPCs.  For starters, skins do not seem to work at all.  Even doing things that normally work, don't fix it (i.e. /ex adjust npc skin").  Also, commands like /npc despawn do not work.

However, if I start server without loading chunks, I get the following error in console.  It's like the NPCs are triggering the "on player enters:" event.  I thought mcmonkey had fixed this already, but maybe this is different somehow?

```
PlayerEnterExit:
  type: world
  debug: false
  events:
    on player enters msborder:
    - ^if <player.location.is_within[cu@mslowercrypt]> || <player.location.is_within[cu@mschurchcrypt]>  {
      - queue clear }
    - ^if !<player.has_flag[mstitle]> {
      - title "title:<green>Misty Shores" targets:<player>
      - flag <player> mstitle duration:600 }
```

![capture](https://cloud.githubusercontent.com/assets/4096231/6680991/5ee0a3ba-cc2d-11e4-94c3-6a3633c85a13.JPG)

**Comment by Morphan1** [comment]
Again, this is a Denizen issue.

**Comment by uledrith** [comment]
so I should open this ticket on the Denezin github?
