### ISSUE TITLE
NPC disappears after server restart

### ISSUE THREAD

**Issue by Klaimstorm** [CitizensDev/Citizens2#2801]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

After I set up and created the NPC, everything works, but as soon as I restart the server, all the NPCs immediately disappear and do not respawn again, what should I do with this? how to make it so that they did not disappear or recovered themselves, I used 3 plugins to create the NPC - citizens-2_0_29-b2548, CitizensCMD, deluxemenus-1_13_3-release.

### Code Example

```java
menu_title: '&e» &8Выбрать Рассу'
open_command: demon
size: 9
open_requirement:
  requirements:
    permission:
      type: has permission
      permission: menu.open
      deny_commands:
        - "[message] &cУ вас нет прав."
items:
  'accept':
    material: LIME_STAINED_GLASS_PANE
    slots:
      - 0-3
    display_name: '           &a&lПодтвердить    '
    lore:
      - '  &7Нажмите, чтобы подтвердить  '
    left_click_requirement:
      requirements:
        balance_check:
          type: has money
          amount: 0
          deny_commands:
          - '[message]'
          - '[message]'
          - '[sound] ENTITY_VILLAGER_NO'
          - '[close]'
    left_click_commands:
      - '[takemoney] 0'
      - '[console] lp user %player_name% parent set demon'
      - '[message]'
      - '[message]&e Вы Демон &e:)'
      - '[message]'
      - '[sound] ENTITY_PLAYER_LEVELUP'
      - '[close]'
  'decline':
    material: RED_STAINED_GLASS_PANE
    slots:
      - 5-8
    display_name: '           &c&lОтклонить    '
    lore:
      - '  &7Нажмите, чтобы отклонить  '
    left_click_commands:
      - '[close]'
  'info':
    material: paper
    slot: 4
    display_name: ' &a&l<<<<<  &c&l>>>>>'
```

**Comment by fullwall** [comment]
Please post a log file with citizens debug enabled.

**Comment by mcmonkey4eva** [comment]
- Don't use "CitizensCMD", there's a built in feature for this: https://wiki.citizensnpcs.co/NPC_Commands
- Please post a *Bug report* not a feature request, and fill out all required fields of the bug report form -or- ask on Discord by making a thread in the citizens channel @ https://discord.gg/Q6pZGSR
