### ISSUE TITLE
Citizens only able to player

### ISSUE THREAD

**Issue by babylululu** [CitizensDev/Citizens2#2805]
### `/version` output

```txt
This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
```

### `/version Citizens` output

```txt
Citizens version 2.0.22-SNAPSHOT (build 1487)

 Website: http://www.citizensnpcs.co

 Authors: aPunch and fullwall
```

### Log file

https://paste.denizenscript.com/View/97052

### config.yml

https://paste.denizenscript.com/View/97054

### saves.yml

sorry for this it said my content are too little and become spammer.The save.yml is only: # Citizens NPC Storage

### Profiler report

https://spark.lucko.me/YTXQUwiKvw

### Description

im making a /shopkeeper npc on an other server and its not working,so i use a test server that i think the problem is 
[Citizens] Could not fetch NMS field modifiers: [[modifiers.
[Citizens] Could not fetch entity id mapping fields: Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "modifiersField" is null.
[Citizens] Unable to use economy handling. Has Vault been enabled?
i dont know whats this and a search in the network and dont have any way.
my friend also download the same citizens plugin but it can work but i cant :(
the main problem is its only work on /npc type player and other such as pig cow sheep and balabala just disapear >:(

**Comment by BehrRiley** [comment]
You're extremely outdated and need to update your Citizens build. You're over one thousand builds behind having used the builds incorrectly from the Bukkit site; Please note the plugin descriptions when installing them, we have a huge header on the ancient old Bukkit page saying "don't download this" basically. We also would heavily recommend that you consider upgrading your server version.

Paper is a higher-performance alternative to Spigot that is 100% compatible with the equivalent Spigot version. It's much easier to update than Spigot itself, and carries a lot of performance and quality-of-life benefits.

Latest Paper builds are at https://papermc.io/downloads.

(If you would prefer to use a Spigot build, refer to building spigot)

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.
Spigot releases of Citizens are available at https://www.spigotmc.org/resources/citizens.13811/.

> [Citizens] Unable to use economy handling. Has Vault been enabled?
You may need to verify your vault plugin as well.

**Comment by babylululu** [comment]
Thanks for the reply!!!!!!i'll try it out now ty!!!!!!!:)

**Comment by BehrRiley** [comment]
No prob bob - If you'd like faster support also, we're more active on Discord @ https://discord.gg/Q6pZGSR

**Comment by babylululu** [comment]
im sorry fo my stupidity:(. i've upgraded it but this is in the console
[12:24:17 ERROR]: [Citizens] Missing preferred location bundle.
[12:24:17 INFO]: [Citizens] Could not fetch NMS field modifiers: [[modifiers.
[12:24:17 INFO]: [Citizens] Could not fetch NMS field bY: [[Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "net.citizensnpcs.util.NMS.MODIFIERS_FIELD" is null.
[12:24:17 INFO]: [Citizens] Could not fetch NMS field b: [[Cannot invoke "java.lang.reflect.Field.setInt(Object, int)" because "net.citizensnpcs.util.NMS.MODIFIERS_FIELD" is null.
[12:24:17 INFO]: [Citizens] Could not fetch entity id mapping fields: Cannot invoke "java.lang.reflect.Field.get(Object)" because "field" is null.
i can't change citizens to any mobs :(
what is NMS field modifiers ☹

**Comment by BehrRiley** [comment]
Again, we're a lot more active on Discord if you're able to continue there - however, can you provide another startup log from having updated? if by any chance you are, make sure you're not reloading with the built-in `/reload` command, or using any plugins implying they can "reload" plugins (eg: plugman, plugmanx, etc)
