### ISSUE TITLE
Won't Create Citizen

### ISSUE THREAD

**Issue by MDMeaux** [CitizensDev/Citizens2#281]
I type '/npc create Bob' and it says:
Please report this error: [See console]
java.lang.NoClassDefFoundError:
net/minecraft/server/v1_8_R1/Packet

Using: craftbukkit_latest_development_build_1.8.3.jar
            Version 2.0.14-SNAPSHOT (build 1195) by fullwall (latest)
            MC 1.8.3
Console:
18.03 07:53:15 [Multicraft] Skipped 6 lines due to rate limit (30/s)
18.03 07:52:59 [Server] WARN at java.lang.Thread.run(Thread.java:745)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:670)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
18.03 07:52:59 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:262)
18.03 07:52:59 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(SourceFile:9)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(SourceFile:37)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:937)
18.03 07:52:59 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1077)
18.03 07:52:59 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:625)
18.03 07:52:59 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
18.03 07:52:59 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
18.03 07:52:59 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:606)
18.03 07:52:59 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18.03 07:52:59 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
18.03 07:52:59 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
18.03 07:52:59 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
18.03 07:52:59 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
18.03 07:52:54 [Multicraft] Baeoeu ran command Message of the Day
18.03 07:52:54 [Connect] User Baeoeu, IP 86.183.29.109
18.03 07:52:53 [Server] INFO UUID of player Baeoeu is 321a0da6-7e7b-4af8-9644-bf7ccff4b09d
18.03 07:52:35 [Server] INFO Loaded 0 NPCs.
18.03 07:52:35 [Server] Startup Done (1.511s)! For help, type "help" or "?"
18.03 07:52:35 [Multicraft] Skipped 11 lines due to rate limit (30/s)
18.03 07:52:35 [Server] INFO WEPIF: Using the Bukkit Permissions API.
18.03 07:52:34 [Server] INFO Enabling WorldEdit v6.0;3342-78f975b9
18.03 07:52:34 [Server] INFO ... 12 more
18.03 07:52:34 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_65]
18.03 07:52:34 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_65]
18.03 07:52:34 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
18.03 07:52:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
18.03 07:52:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:236) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:329) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:374) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:408) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit_latest_development_build_1.8.3.jar:git-Bukkit-6fe6b38]
18.03 07:52:34 [Server] INFO at me.stopbox123.npc.Main.onEnable(Main.java:13) ~[?:?]
18.03 07:52:34 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/World
18.03 07:52:34 [Server] ERROR Error occurred while enabling BukkitNPC v0.1 (Is it up to date?)
18.03 07:52:34 [Server] INFO Enabling BukkitNPC v0.1
18.03 07:52:34 [Server] INFO Unable to use economy handling. Has Vault been enabled?
18.03 07:52:34 [Server] ERROR Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes
18.03 07:52:34 [Server] INFO Creating file: config.yml
18.03 07:52:34 [Server] INFO Enabling Citizens v2.0.14-SNAPSHOT (build 1195)
18.03 07:52:34 [Server] INFO Preparing start region for level 2 (Seed: 27594263)
18.03 07:52:34 [Server] INFO Preparing start region for level 1 (Seed: 27594263)
18.03 07:52:33 [Server] INFO Preparing start region for level 0 (Seed: 27594263)
18.03 07:52:33 [Server] INFO Preparing level "world"
18.03 07:52:33 [Server] INFO Loading WorldEdit v6.0;3342-78f975b9
18.03 07:52:33 [Server] INFO Loading BukkitNPC v0.1
18.03 07:52:33 [Server] INFO Loading Citizens v2.0.14-SNAPSHOT (build 1195)
18.03 07:52:33 [Server] INFO This server is running CraftBukkit version git-Bukkit-6fe6b38 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
18.03 07:52:33 [Server] INFO Using epoll channel type
18.03 07:52:33 [Server] INFO Starting Minecraft server on 94.23.121.150:25587
18.03 07:52:33 [Server] INFO Generating keypair
18.03 07:52:33 [Server] INFO Default game type: CREATIVE
18.03 07:52:33 [Server] INFO Loading properties
18.03 07:52:33 [Server] INFO Starting minecraft server version 1.8.3
18.03 07:52:27 [Server] INFO Loading libraries, please wait...
18.03 07:52:27 [Multicraft] Loaded config for "Mod: CraftBukkit Latest Development Build 1.8.3"
18.03

**Comment by Morphan1** [comment]
Update the plugin before posting error reports, please.
http://ci.citizensnpcs.co/job/Citizens2/

**Comment by NicoFilippo** [comment]
I still have the issue on 1.8.3 (I am using 1.8.1 vesion, since there is no 1.8.3). What ca I do? My server is 1.8.3!!!

**Comment by mcmonkey4eva** [comment]
@NicoFilippo http://wiki.citizensnpcs.co/Versions

**Comment by CCYB3R** [comment]
i have the same error, i downloaded all the possible files for 1.8!
Plugins installed: Citizens (red), WorldEdit, CommandNPC (red), Shopkeepers, Quests, Essentials, EssentialsSpawn, EssentialsChat, GroupManager, WorldGuard

**Comment by mcmonkey4eva** [comment]
@CCYB3R check the versions link, make sure you have the one that /exactly matches/ your ACTUAL server version.

**Comment by CCYB3R** [comment]
@mcmonkey4eva i tried but it still does not work
