### ISSUE TITLE
All mob's became pigs

### ISSUE THREAD

**Issue by EvilMask587** [CitizensDev/Citizens2#2811]
### `/version` output

```txt
This server is running Magma version 1.16.5-36.2.35-7a9a29aa (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge Version 36.2.35-7a9a29aa)
```

### `/version Citizens` output

```txt
Citizens-2.0.30-b2565
```

### Log file

https://paste.denizenscript.com/View/97414

### config.yml

https://paste.denizenscript.com/View/97415

### saves.yml

# Citizens NPC Storage

### Description

![image](https://user-images.githubusercontent.com/94621300/172894490-5ede63ca-da06-435b-8ef4-c68140431897.png)

All mobs, default, modded, from plugins. ALL of them become pigs!

P.S. in image must be squids

**Comment by mcmonkey4eva** [comment]
- We don't support cracks: https://wiki.citizensnpcs.co/Cracks
- We don't support Forge
- That issue definitely has nothing to do with Citizens anyway
