### ISSUE TITLE
Error when trying to spawn a villager

### ISSUE THREAD

**Issue by baailey** [CitizensDev/Citizens2#2812]
### `/version` output

```txt
This server is running Paper version git-Paper-12 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 3d37b42)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2565)
```

### Log file

https://paste.denizenscript.com/View/97537

### config.yml

https://paste.denizenscript.com/View/97538

### saves.yml

https://paste.denizenscript.com/View/97539

### Description

when I ran `/npc create t --type villager` it generated an error and didn't spawn the entity.

**Comment by Thin-Troll** [comment]
https://github.com/CitizensDev/Citizens2/issues/1822

the situation repeats, VIllager just disappears when reloading the plugin on 1.17.1 PURPUR, using Citizens v2.0.30-SNAPSHOT (build 2577),
just write /npc reload and NPCs will appear.

**Comment by fullwall** [comment]
Fixed
