### ISSUE TITLE
Player can give and take Allay holding item

### ISSUE THREAD

**Issue by Antal1609** [CitizensDev/Citizens2#2813]
### `/version` output

```txt
This server is running Paper version git-Paper-14 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 48f7a1a)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2568)
```

### Log file

Irrelevant

### config.yml

Irrelevant

### saves.yml

Irrelevant

### Description

1. /npc create allay
2. /npc type allay
3. give item
4. take item

Unexpected:
Default players can give and take items from allay.

Relevant wiki: https://minecraft.fandom.com/wiki/Allay#Behavior

**Comment by mcmonkey4eva** [comment]
Closing due to refusal to provide required information.
