### ISSUE TITLE
Pixelmon bug involving Citizens plugin

### ISSUE THREAD

**Issue by Rikardinhoboss** [CitizensDev/Citizens2#2815]
### `/version` output

```txt
Minecraft Version: 1.16.5
Software Server: Magma Foundation 1.16.5 - dde3ce7e
Forge: 1.16.5 - 36.2.35
Mod Version involving: Pixelmon 9.0.2
```

### `/version Citizens` output

```txt
Vercion Citizens: Citizens-2.0.30-b2577
```

### Log file

https://paste.denizenscript.com/View/97770

### config.yml

https://paste.denizenscript.com/View/97771

### saves.yml

https://paste.denizenscript.com/View/97772

### Description

I am creating a pixelmon modpack server and a few more mods and all the mods are working perfectly in armonia, when i went to put the plugins, they all worked, including the server software is magma foundation for 1.16.5 latest to date date (19/06/2022), however, when putting citizens it simply bugs the pokemons and turns them into pigs, and it's the plugin that is doing this because after removing the plugin, the pokemons go back to being pokemons, and it's not just the pokemons, the pokeballs, where they are mounted that involves the mod, everything that generates an entity, it turns into a pig with the plugin, I reported it to the mod support, they also didn't know about the bug, and they also suggested informing the support from citizens, and I think you should take a look at it, I'll leave a link to the lightshot of the image to show!

[https://prnt.sc/nQdhLmxUNF8b](url)

**Comment by Rikardinhoboss** [comment]
Link worked: https://prnt.sc/nQdhLmxUNF8b

**Comment by fullwall** [comment]
Currently magma foundation is not supported by Citizens.
