### ISSUE TITLE
Consider your options before closing an issue

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [CitizensDev/Citizens2#2817]
https://wiki.citizensnpcs.co/Cracks

_Originally posted by @mcmonkey4eva in https://github.com/CitizensDev/Citizens2/issues/2816#issuecomment-1159759619_

I have a hybrid authentication system and am using Velocity

**Comment by SPAWNRYS-ban** [comment]
and lol it's "Premium" serve
![Screenshot_5428](https://user-images.githubusercontent.com/68144848/174489617-7e2811d1-76aa-4365-b688-a43c19a448f8.png)
r

**Comment by mcmonkey4eva** [comment]
Post on Discord if you'd like to discuss our policy about cracked servers or dispute your support refusal @ https://discord.gg/Q6pZGSR
