### ISSUE TITLE
/npc drops impossible to use

### ISSUE THREAD

**Issue by soshimee** [CitizensDev/Citizens2#2819]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

/npc drops should be usable. Currently, it's view-only, it should be also be editable.

**Comment by fullwall** [comment]
Fixed
