### ISSUE TITLE
Problemen with blacksmit trait.

### ISSUE THREAD

**Issue by Duqino** [CitizensDev/Citizens2#282]
Hello,

I think it got something to do with the 1.8.3 update of spigot. But the blacksmith trait just stopped working. I had some problems with that enchants where removed of items. So i thought lets do a clean install, and now i got this problem. I had 3 NPC's and i removed one of them and placed it back. That one stopped working but the other 2 are doing fine for now.

http://pastebin.com/K4HajJQS

Also another thing. Not sure yet if this problem is solved now but ill post it anyway.

I got a special enchant plugin called EnchantsPlus http://www.spigotmc.org/resources/1-8-enchantsplus.3396/
running on my survival server with the blacksmith plugin.
But somehow it demotes enchants. Like sharpness 4 to sharpness 1. 
This kinda sucks and i dont want that.

Kind regards,

Dutchy

**Comment by mcmonkey4eva** [comment]
You should contact the owners/maintainers of Blacksmith and/or EnchantsPlus... sorry, but neither is maintained by the Citizens team at the moment.
