### ISSUE TITLE
Error on removing or getting npc metadata

### ISSUE THREAD

**Issue by DevJoey** [CitizensDev/Citizens2#2829]
### `/version` output

```txt
version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens v2.0.30-SNAPSHOT (build 2596)
```

### Log file

https://paste.denizenscript.com/View/98985

### config.yml

https://paste.denizenscript.com/View/98984

### saves.yml

https://paste.denizenscript.com/View/98983

### Description

I get this error if i want to get or remove metadata of an npc

https://paste.denizenscript.com/View/98986

**Comment by fullwall** [comment]
Can't reproduce this.

**Comment by DevJoey** [comment]
It is reproduceable! I have currently tested it with newest dev build!

If i use /npc metadata remove <key> it gives me an exception!

Pls look at this gif: https://workupload.com/file/B68j3MeRhq6

The error: https://paste.denizenscript.com/View/99269

**Comment by fullwall** [comment]
Try in new build.

**Comment by DevJoey** [comment]
> Try in new build.

Still the same error ;(
https://paste.denizenscript.com/View/99277

Build: 
![image](https://user-images.githubusercontent.com/38475631/180501164-cf034656-f360-435a-9a3a-5051821074b9.png)

**Comment by DevJoey** [comment]
I have reset the lang file and now it works!

Only if i type /npc metadata set and then nothing as argument, the error is still there. But removing works now

**Comment by fullwall** [comment]
Remember to delete the lang folder in the citizens folder
