### ISSUE TITLE
API: PlayerDeathEvent crashing on NPC

### ISSUE THREAD

**Issue by Abdalion** [CitizensDev/Citizens2#283]
Heres the crash log:
 http://pastebin.com/4ZjQRcbX

**Comment by mcmonkey4eva** [comment]
Can't provide support for outdated versions, if you can replicate this on the latest builds then and only then can we investigate.

**Comment by Abdalion** [comment]
Will test tomorrow on 2.0.15.

**Comment by fullwall** [comment]
You have set /npc respawn to a non-integer value.
