### ISSUE TITLE
Minecraft bedrock can't click on npc error

### ISSUE THREAD

**Issue by vudz2310** [CitizensDev/Citizens2#2830]
### `/version` output

```txt
version: 2.0,30
```

### `/version Citizens` output

```txt
version: 2.0,30
```

### Log file

https://paste.denizenscript.com/New/log

### config.yml

https://paste.denizenscript.com/New/Log

### saves.yml

https://paste.denizenscript.com/New/Log

### Profiler report

https://www.spigotmc.org/resources/57242/

### Description

for minecraft pc everything is normal
but with minecraft platform when clicking on npc, it won't be clickable
error tool:
When I click on minecraft bedrock to go to the npc, it will appear
First it will be not be the same and will not open more
That's my description, if I'm missing anything, please forgive me

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
