### ISSUE TITLE
Error on console 

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [CitizensDev/Citizens2#2833]
### `/version` output

```txt
[Sat 19:30:25 INFO ] This server is running Paper version git-Paper-64 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 90836d0)
You are 13 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-52 (MC: 1.19)
```

### `/version Citizens` output

```txt
[Sat 19:30:34 INFO ] Citizens version 2.0.30-SNAPSHOT (build 2617)
[Sat 19:30:34 INFO ] Website: http://www.citizensnpcs.co
[Sat 19:30:34 INFO ] Author: fullwall
```

### Log file

https://paste.walshy.dev/dV61rECjnrts

### config.yml

https://paste.denizenscript.com/View/99306

### saves.yml

https://paste.denizenscript.com/View/99307

### Profiler report

N/A

### Description

While left clicking , or right clicking an NPC , with a command , it gives that error

**Comment by mcmonkey4eva** [comment]
Post your FULL logs/latest.log to https://paste.denizenscript.com/New/Log and paste the link here
