### ISSUE TITLE
1.12 lag

### ISSUE THREAD

**Issue by CodedRedGIT** [CitizensDev/Citizens2#2837]
### `/version` output

```txt
This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2638)
```

### Log file

https://paste.denizenscript.com/View/99512

### config.yml

https://paste.denizenscript.com/View/99513

### saves.yml

https://paste.denizenscript.com/View/99514

### Profiler report

https://timings.aikar.co/?id=543600f487f5462cb1a6cdead1215fba#plugins

### Description

Kind of random. Sometimes these lag spikes are 30mins apart or 8hrs apart. Seems to be coming from when the chunk unloads. We have placed alts by the npcs to see if the error still raises and it still does. Any help is appreciated. Thank you.

**Comment by fullwall** [comment]
It would be helpful to get a full log file please and a spark timings report. Assuming this is a chunk unloading problem, enabling citizens debug to get the problem NPCs then if you can debugging chunk loads (slow) would be the next steps.

**Comment by CodedRedGIT** [comment]
Idk if this will help: https://paste.denizenscript.com/View/99536
https://spark.lucko.me/IcdwBW91g4 (need to update spark)

**Comment by fullwall** [comment]
The spark report shows creepermc itemspawnlistener causing the majority of the lag. As I say, aikars timing doesn’t really help me at all.
