### ISSUE TITLE
JAVA.LANG.NULLPOINTER

### ISSUE THREAD

**Issue by GuruSea** [CitizensDev/Citizens2#2838]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

I want to create a npc in aternos  spigot version 1.19 and when i put de code in the console npc create name and  push enter the console crash 
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null

**Comment by mcmonkey4eva** [comment]
- https://wiki.citizensnpcs.co/Frequently_Asked_Questions#I_have_a_free_server_.28Aternos.2C_Minehut.2C_....29_but_there.27s_problems
- You're trying to run a 1.19.1 targeted build on a 1.19(.0) server
- This is not a feature request

**Comment by GuruSea** [comment]
my server is on aternos and I'm using the plugin from there, and I only
have these two versions
[image: image.png]
[image: image.png]
