### ISSUE TITLE
I can't create any kind of npc

### ISSUE THREAD

**Issue by joooom** [CitizensDev/Citizens2#2839]
### `/version` output

```txt
This server is running Paper version git-Paper-65 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 384d639)
You are 16 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-387 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2657)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/99612

### config.yml

https://paste.denizenscript.com/View/99613

### saves.yml

not created

### Description

I can't create any kind of npc I've tested with a villager, player and A BAT. and always reproduces the same error in chat:
Please report this error [See console]
java.lang.NoSuchMetodError: 'boolean
net.minecraft.world.entity.Entity.bo()'

**Comment by mcmonkey4eva** [comment]
Either update Paper to 1.19.1 or downdate Citizens to https://ci.citizensnpcs.co/job/Citizens2/2640/ (the last build for 1.19.0)

**Comment by joooom** [comment]
thanks
