### ISSUE TITLE
./butcher removes Mob NPCs

### ISSUE THREAD

**Issue by Apotheosis1337** [CitizensDev/Citizens2#284]
What title says..
/butcher removes all Mob NPCs.

**Comment by Morphan1** [comment]
And this is a Citizens problem how? Report this to the plugin that provides your command. Or don't use the command, as there's plenty of better options.

**Comment by Apotheosis1337** [comment]
Ehm, /butcher as every other command like /killall, which are both essential commands, and pretty sure every server has them. And NPC mob types get removed when killing every monster in the area, I believe this bug should be towards Citizens than Essentials. And can I know 1 of those better options?

**Comment by Morphan1** [comment]
We can't control whether another plugin's commands recognize the fact that a mob is created by Citizens. They must check the entity's metadata that Citizens provides. Again, take this up with the other plugin's team.
