### ISSUE TITLE
Citizens NPC error

### ISSUE THREAD

**Issue by MrStreeet** [CitizensDev/Citizens2#2842]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2657)
```

### Log file

https://paste.denizenscript.com/View/99697

### config.yml

https://paste.denizenscript.com/View/99698

### saves.yml

Submission Refused

### Description

When I try to create an NPC, it doesn't works and displays a big error on the console, it says that I have to report it

**Comment by fullwall** [comment]
Use the correct version for your server (build 2640 is the last build that supports 1.19.0)
