### ISSUE TITLE
Velocity, Snap, & Paper all not working.

### ISSUE THREAD

**Issue by AceSardonyx** [CitizensDev/Citizens2#2846]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Citizens is not working for:
The latest version of Velocity
PaperMC 1.19-81
The Snap Plugin for Bungee Compatibility (I assume this gets no support anyways)

If needed, I can post the error for each in the comments.

**Comment by AceSardonyx** [comment]
Any recommended build to fix it? I did not try them all nor can I find most of them on the Jenkins page.
(But I'm also dumb so...)

**Comment by mcmonkey4eva** [comment]
I don't know what your issue is, and either why you're reporting an issue but you used the Feature Request button and falsely checkmarked the boxes.
Either file a Bug Report and fill it out properly, or ask on Discord: https://discord.gg/Q6pZGSR
