### ISSUE TITLE
Error when /npc create name

### ISSUE THREAD

**Issue by yoanndelord** [CitizensDev/Citizens2#2849]
### `/version` output

```txt
This server is running CraftBukkit version 3506-Spigot-ee73712-c3f219e (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2663)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://webftp.verygames.net/?dl=%2Fminecraft_spigot%20-%20Spigot119%2Flogs%2Flatest.log

### config.yml

https://webftp.verygames.net/?dl=%2Fminecraft_spigot%20-%20Spigot119%2Fplugins%2FCitizens%2Fconfig.yml

### saves.yml

https://webftp.verygames.net/?dl=%2Fminecraft_spigot%20-%20Spigot119%2Fplugins%2FCitizens%2Fsaves.yml

### Description

Hello , i just typed the command : /npc create Henry (whatever the name the error is still the same) , and it write me the error next : 
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null

sometimes it write me because local 4 is null , but idk why it write me thoses errors. Thanks for your help

**Comment by mcmonkey4eva** [comment]
- Please use https://paste.denizenscript.com/New/Log as the template you ignored told you to
- Update your server to 1.19.2
