### ISSUE TITLE
Denizen doesn't work

### ISSUE THREAD

**Issue by MDMeaux** [CitizensDev/Citizens2#285]
I try to install the latest version of Denizen, but it says this in the console:

19.03 21:25:13 [Server] INFO Could not register with Denizen
19.03 21:25:13 [Server] INFO Enabling Sentry v1.8.5
19.03 21:25:13 [Server] INFO Disabling Denizen v0.9.6-SNAPSHOT (build 1551)
19.03 21:25:13 [Server] WARN -------------------------------------
19.03 21:25:13 [Server] WARN This Denizen version is not compatible with this CraftBukkit version! Deactivating Denizen!
19.03 21:25:13 [Server] WARN -------------------------------------
19.03 21:25:13 [Server] INFO Enabling Denizen v0.9.6-SNAPSHOT (build 1551)

Using: craftbukkit_latest_development_build_1.8.3.jar
           MC 1.8.3
           Citizens 2.0.15 SNAPSHOT
           Denizen 0.9.6 SNAPSHOT

**Comment by mcmonkey4eva** [comment]
For 1.8.3 you must install a `developmental` build. Those are available here: http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
The release builds work too now.
