### ISSUE TITLE
Can't create, spawn, teleport npc Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Pogo1000** [CitizensDev/Citizens2#2852]
### `/version` output

```txt
1.19
```

### `/version Citizens` output

```txt
2.0.30- Snapshot (build 2664)
```

### Log file

https://paste.denizenscript.com/View/100048

### config.yml

https://paste.denizenscript.com/View/100046

### saves.yml

https://paste.denizenscript.com/View/100047

### Description

I want  create an NPC and when i write /citizens:npc2 (or only /citizens:npc) then shows this error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifable.a(double)" beacuse "range" is null

**Comment by Pogo1000** [comment]
*
/citizens:npc2 (or only) with commands like create, spawn or any

**Comment by RealMCSamuel** [comment]
You’ll have to update to 1.19.2 in order to use the latest version of Citizens. If you don’t want to, the last update that is 1.19.0 compatible is build 2640.

**Comment by Pogo1000** [comment]
Ok i'il try

**Comment by Pogo1000** [comment]
Thank you very much :)
