### ISSUE TITLE
1.8.8 - citizens save dont work i have an error

### ISSUE THREAD

**Issue by MLBLEBG** [CitizensDev/Citizens2#2855]
### `/version` output

```txt
This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) Error obtaining version information
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2665)
```

### Log file

https://paste.denizenscript.com/View/100253

### config.yml

https://paste.denizenscript.com/View/100254

### saves.yml

https://paste.denizenscript.com/View/100255

### Description

i do "/citizens save" but its not work i have this error https://paste.denizenscript.com/View/100264

**Comment by MLBLEBG** [comment]
Please help

**Comment by fullwall** [comment]
Fixed; update to latest build

**Comment by MLBLEBG** [comment]
thanks ^^
