### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by Foxxfire1** [CitizensDev/Citizens2#2856]
### `/version` output

```txt
1.19 spigot
```

### `/version Citizens` output

```txt
Last version
```

### Log file

https://paste.denizenscript.com/View/100270

### config.yml

https://paste.denizenscript.com/View/100272

### saves.yml

https://paste.denizenscript.com/View/100271

### Description

I try creating a npc and nothing work, everythink worked before doing the citizen update. Can I have help please

**Comment by Foxxfire1** [comment]
I had a lot of npc and they all disapeared

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2, or downdate to 1.18.2 - 1.19(.0) is not a supportable version.
