### ISSUE TITLE
/npc mirror 

### ISSUE THREAD

**Issue by haroldrc** [CitizensDev/Citizens2#2857]
### `/version` output

```txt
This server is running WindSpigot Release v2.1.2 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
```

### `/version Citizens` output

```txt
[10:44:36 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2654)
[10:44:36 INFO]: Website: http://www.citizensnpcs.co
[10:44:36 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/100292

### config.yml

https://paste.denizenscript.com/View/100293

### saves.yml

https://paste.denizenscript.com/View/100294

### Description

i can't get the / npc mirror command to work, i would like the dell npc skin to change according to the player watching the npc

**Comment by mcmonkey4eva** [comment]
Mirror command wasn't created until 1.13. Update your server to a more modern version, ideally 1.18.2 or 1.19.2
https://wiki.citizensnpcs.co/Minecraft_1.8
