### ISSUE TITLE
Error on boot and on npc creation.

### ISSUE THREAD

**Issue by renuwuwu** [CitizensDev/Citizens2#2858]
### `/version` output

```txt
git-Purpur-1735 (MC: 1.19)
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2666)
```

### Log file

https://paste.denizenscript.com/View/100314

### config.yml

https://paste.denizenscript.com/View/100315

### saves.yml

https://paste.denizenscript.com/View/100317

### Description

On startup, I get the error https://pastebin.com/Diy95Eck and when trying to create an NPC, it gives this error https://pastebin.com/zT0S3UGB and tells me to report it. It does create an NPC in the saves.yml file but nothing is actually where the NPC should be.  Everything worked fine prior to updating the server to 1.19. I didn't touch to plugin upon switching so I'm not sure what changed.

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2, not 1.19.0
