### ISSUE TITLE
NPC nametags stacked and unremovable

### ISSUE THREAD

**Issue by SignorPollito** [CitizensDev/Citizens2#2859]
### `/version` output

```txt
git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2569)
```

### Log file

Can't post log for privacy reasons, but there are no exceptions, the plugin is working as expected

### config.yml

https://paste.denizenscript.com/View/100321

### saves.yml

https://paste.denizenscript.com/View/100322

### Description

When using Citizens API and despawning/removing NPCs, sometimes the nametags gets bugged and remains in the air.
There is no wait to remove those armorstands, I tried everything, but I think they are packet, so they are not server-side.

Maybe the problem could also be caused by despawning the NPC, changing its name and then respawning it.

Is there a way to destroy all those nametags got stuck in the air?
Some players are having FPS issues cause of this.

![2022-08-18_12 16 27](https://user-images.githubusercontent.com/63754986/185373634-1066fd33-1f02-40cb-81ff-fac765008b06.png)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
