### ISSUE TITLE
Citizens timings report lag

### ISSUE THREAD

**Issue by Gregoryxnmasd** [CitizensDev/Citizens2#2864]
### `/version` output

```txt
1.19.2
```

### `/version Citizens` output

```txt
v2.0.30 SNAPSHOT (build 2665)
```

### Log file

isnt necessary cause havnt any message of citizens errors in the logs

### config.yml

https://pastebin.com/R0qxi7QX

### saves.yml

https://pastebin.com/XkvhnDta

### Profiler report

https://timings.aikar.co/dev/?id=a07c53ccfc164fc9a9533bbeff199941

### Description

some citizens process is causing lag on my server: Citizens::Task: net.citizensnpcs.Citizens.CitizensSaveTask (interval:72000) (SELF)

**Comment by mcmonkey4eva** [comment]
Closing due to refusal to provide required information.

Consider also asking for help on Discord in the `#citizens` channel https://discord.gg/Q6pZGSR
