### ISSUE TITLE
Empty lines bug

### ISSUE THREAD

**Issue by inithook** [CitizensDev/Citizens2#2865]
### `/version` output

```txt
git-Paper-1618 1.12.2
```

### `/version Citizens` output

```txt
2.0.28 build 2359
```

### Log file

https://paste.denizenscript.com/View/100728

### config.yml

https://paste.denizenscript.com/View/100729

### saves.yml

https://paste.denizenscript.com/View/100730

### Description

![image](https://user-images.githubusercontent.com/112404880/187217829-0f703460-ac62-4052-b6bd-0c0082e1392c.png)
there's black lines in tab
happens everywhere

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
