### ISSUE TITLE
Allow alternate encodings (e.g. SHIFT-JIS/unicode) for translations

### ISSUE THREAD

**Issue by fullwall** [CitizensDev/Citizens2#2866]

**Comment by mcmonkey4eva** [comment]
Should probably just take and properly parse UTF-8. The limitation isn't so much allowing any particular encodings, as allowing *encoding in the first place* as right now it seems to be parsing as ASCII and requiring `\u1234` style encodings for Unicode which is painful to work with.

**Comment by fullwall** [comment]
Yes but I know that for Japanese translations the user would specifically like SHIFT-JIS which is very much not Unicode.
