### ISSUE TITLE
Npc create

### ISSUE THREAD

**Issue by yjj71044** [CitizensDev/Citizens2#2867]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-135 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2673)
```

### Log file

https://paste.denizenscript.com/View/100818

### config.yml

https://paste.denizenscript.com/View/100819

### saves.yml

https://paste.denizenscript.com/View/100820

### Description

Checked for problems when using /npc create <name>.

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2
