### ISSUE TITLE
npcs don't spawn

### ISSUE THREAD

**Issue by Ceddix** [CitizensDev/Citizens2#2868]
### `/version` output

```txt
Current: git-Purpur-1735 (MC: 1.19)*
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2672)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://pastebin.com/82fEL5RJ

### config.yml

https://pastebin.com/u4Mcazau

### saves.yml

https://pastebin.com/AL33Jbf4

### Description

Not a single NPC appears. As soon as I try to spawn an NPC, an error appears in the console *(see log file)*.

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2, and use Paper not Purpur
