### ISSUE TITLE
/npc lookclose

### ISSUE THREAD

**Issue by Mick43** [CitizensDev/Citizens2#287]
Hello,
With the command /npc lookclose the NPC does not concern us, it works sometimes with the head in the back...

**Comment by mcmonkey4eva** [comment]
... What?

**Comment by Mick43** [comment]
Since the citizens-2.0.15 release the command: "/npc lookclose" is buggy.
Please watch this short video, the head of the NPC bug.
(Citizens-2.0.14, works fine)
https://youtu.be/9-rg4XtItwc

**Comment by mcmonkey4eva** [comment]
Update to latest dev build, this was fixed already.

**Comment by Mick43** [comment]
I have the latest version and the problem continues:
version citizens-2.0.15-SNAPSHOT.jar / #1​22​1 16 mars 2015 23:17
version sentry / #2​7 8 mars 2015 17:40
