### ISSUE TITLE
NPC refresh is heavier than before

### ISSUE THREAD

**Issue by WarnDa** [CitizensDev/Citizens2#2872]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Since latest  versions, `HologramTrait.run()` and `updateCustomNameVisibility()` are way heavier than before.
I changed nothing on my side, I just updated citizens always on latest dev build.

I'm using 
- Citizens dev build b2674
- pufferfish 1.19.2
- Java 18
- online_mode (it's my test server, so only 2 players, server is still in development)
Here is my config.yml my save.yml and my logs :
https://pastebin.com/Dq3jgM6a
https://pastebin.com/NC99G0EL
https://pastebin.com/9tdnWgaG

All my NPC are statics, then don't move/look arround/speak/change name, NOTHING.
It's just npc that are static for player to click on them for quests.
That's why I don't understand why it needs to refresh the name so often, or maybe there is a settings to reduce this task, idk.
On older version it was using 0.3-0.6%, now it's 1.8%, that's why I made a ticket !

The spark : https://spark.lucko.me/QigRxL5iH5

Tell me if I forgot things, and please don't close it and just telling "your server isn't lagging" or "1.8% is nothing" etc. :)

**Comment by WarnDa** [comment]
Here is a spark on DEFAULT config, if needed ! https://spark.lucko.me/xO5ERtQw78

**Comment by fullwall** [comment]
Hm, I think the answer is still your server isn't lagging. setName looks to have slowed down slightly due to spigot's text component changes.

**Comment by WarnDa** [comment]
> Hm, I think the answer is still your server isn't lagging

Yes but it makes servers "losing" ressources for a plugin, and new versions are heavier to run, so if I can save 1-2% server ressources that's big, if 3-4 plugins consumes the same, then it kills server performances

> setName looks to have slowed down slightly due to spigot's text component changes. I'm not sure if this is worth changing.

And you can't add a settings which change the delay of names' refresh (or npc update), for players like me who uses npc just for basic things ?

**Comment by fullwall** [comment]
But you don't have any evidence that this is a problem?

**Comment by WarnDa** [comment]
On a spark, it shouldn't take that much percent, the spark show that the task is heavier than it was before (at least 3x more), so anything that could help optimising this task would be appreciated

**Comment by fullwall** [comment]
The correct way to fix this is to ask Spigot to make their entity names not try to parse hyperlinks.

**Comment by emmanuelvlad** [comment]
> The correct way to fix this is to ask Spigot to make their entity names not try to parse hyperlinks.

That's it? :(

Couldn't we have a way to reduce the update rate or even not update at all?

**Comment by galacticwarrior9** [comment]
Would also be interested if there could be an option to change the update rate.. we only have 7 NPCs on our server, yet they take up 1-2% of the tick (according to spark) precisely because of this issue.
