### ISSUE TITLE
Sheep NPC do not always update for players when changing dye colour and name

### ISSUE THREAD

**Issue by coolnickname** [CitizensDev/Citizens2#2873]
### `/version` output

```txt
This server is running Paper version git-Paper-792 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 2 version(s) behind
Previous version: git-Paper-778 (MC: 1.16.5)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2673)
Website: http://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/100904

### config.yml

https://paste.denizenscript.com/View/100905

### saves.yml

last-created-npc-id: 723 npc: {}

### Description

When I change the dye colour and name of my sheep NPC it sometimes doesn't update for players that are already in the world. Players that teleport into the world afterwards see the updated colour and name, but players that were there before the update don't.

I use an anonymous NPC registry and the change the colour and name as follows:
`npcRegistry.getNPC(sheep).setName(text);`
`((Sheep) sheep).setColor(color)`
where `sheep` is an instance of LivingEntity.

Would it be possible to send some packet to the client to update the entity?

**Comment by BehrRiley** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by coolnickname** [comment]
@BehrRiley the server is normally run behind a proxy so it has to be in offline mode

**Comment by BehrRiley** [comment]
> @BehrRiley the server is normally run behind a proxy so it has to be in offline mode

please refer to the link provided; the note you specified is outlined here: https://wiki.citizensnpcs.co/Cracks#Bungee
your backend servers should be offline to allow your proxy to firewall it in an online-mode - you should correct that as players can join your server without authenticating properly, making it a cracked server. we do not support cracked servers

**Comment by coolnickname** [comment]
@BehrRiley This is not the production server, but a copy I downloaded to my PC to test my plugins on. I just haven't bothered to change the online mode setting because the server is only running when I am testing something and is not exposed to the internet.

Maybe I should have mentioned that from the beginning, but I didn't figure it would be such a big deal. For the record: the accounts I used are both authenticated, and I would be more than happy to recreate the issue in an online mode environment if that would help.

**Comment by coolnickname** [comment]
This issue has not been resolved yet. Please reopen.

**Comment by mcmonkey4eva** [comment]
Need replication logs on an up-to-date online-mode server

**Comment by coolnickname** [comment]
New log:
[https://paste.denizenscript.com/View/108387](https://paste.denizenscript.com/View/108387)

**Comment by fullwall** [comment]
I still can't reproduce this.
