### ISSUE TITLE
Could not pass event NPCRightClickEvent for new players

### ISSUE THREAD

**Issue by TheCashFire** [CitizensDev/Citizens2#2874]
### `/version` output

```txt
Paper 1.19.2-R0.1-SNAPSHOT b134
```

### `/version Citizens` output

```txt
Citizens version 2.0.30 b8
```

### Log file

No logs available

### config.yml

https://paste.denizenscript.com/View/100914

### saves.yml

https://paste.denizenscript.com/View/100915

### Description

Able to reproduce this when a new player interacts with Ornn, NPC#8. Not sure why, probably because of an old text option that I've since removed, but it continues to come back for some odd reason. Only seems to effect this NPC.

**Comment by mcmonkey4eva** [comment]
Can't look into a bug report if you refuse to provide logs.

Consider asking for help on Discord https://discord.gg/Q6pZGSR

**Comment by TheCashFire** [comment]
Would just regular server logs do? I don't have any Citizens only logs.

**Comment by TheCashFire** [comment]
Just realized I forgot to actually include the issue. Whoops.

Here are the last few logs from startup to error. There is also a text doc with the error inside it in case it isn't in one of these for some reason.

[2022-09-03-3.log.gz](https://github.com/CitizensDev/Citizens2/files/9485127/2022-09-03-3.log.gz)
[2022-09-03-2.log.gz](https://github.com/CitizensDev/Citizens2/files/9485128/2022-09-03-2.log.gz)
[2022-09-03-1.log.gz](https://github.com/CitizensDev/Citizens2/files/9485129/2022-09-03-1.log.gz)
[Citizens Click Event Issue.txt](https://github.com/CitizensDev/Citizens2/files/9485130/Citizens.Click.Event.Issue.txt)
