### ISSUE TITLE
Players get randomly disconnected with errors "Team CIT-4afcdd7c79b8 already exists in this scoreboard"

### ISSUE THREAD

**Issue by Akiranya** [CitizensDev/Citizens2#2875]
### `/version` output

```txt
Current: git-Purpur-1774 (MC: 1.19.2)*
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2673)
```

### Log file

https://mclo.gs/Amqk2Re

### config.yml

https://paste.denizenscript.com/View/101110

### saves.yml

https://paste.denizenscript.com/View/101111

### Description

**From the Bukkit console:**

There is really no errors on the Bukkit console (tho I pasted the `latest.log` of Bukkit console as requested). What I see on the Bukkit console is the players simply get disconnected normally. My players report to me that they can get disconnected randomly anytime, like when they AFK fishing at home and there were no NPCs around them...

**From the Bungeecord console:**

The actual errors happen in the Bungeecord (specifically Waterfall fork) console, here is the logs: https://mclo.gs/LGSBDMP

I searched the previous issues (#2835, #2600) and it looks like they were basically the same issues (same errors). The solutions presented in those issues were mostly updating Citizens, but unfortunately I already updated the Citizens to the latest on the Spigot and the issue still happened ...

If you need more information I'm happy to provide them

**Comment by mcmonkey4eva** [comment]
- Please use https://paste.denizenscript.com/New/Log for log pastes
- Test on Paper, not Purpur

**Comment by Akiranya** [comment]
Logs: [I use mclog.gs for hiding IP address of my paper and the content ](https://paste.denizenscript.com/View/101112)

I also tested on Paper on my friend's server and we got the exactly the same CIT-blabla errors.

**Comment by mcmonkey4eva** [comment]
Your server has not been restarted since midnight and thus has had its logs rolled over.

Also that bungee logs link is not from a bungee server.

**Comment by Akiranya** [comment]
Sorry for the wrong logs, I probably mixed up the links.

The Bukkit logs since server startup:

https://paste.denizenscript.com/View/101114 (2022-09-08) _(log A)_
https://paste.denizenscript.com/View/101115 (latest.log) _(log B)_

The Waterfall logs:

https://paste.denizenscript.com/View/101117 (2022-08-31, this is the startup logs)
https://paste.denizenscript.com/View/101119 (2022-09-08) _(log C)_
https://paste.denizenscript.com/View/101118 (latest.log) _(log D)_

The log A and B of Bukkit are aligned with log C and D of Bungeecord (they are in the same time frame). So searching for the timestamp should be quick to locate the errors.

----

A side question: I was just wondering, if I have a plugin that intercepts the Team packets from server to client (https://wiki.vg/Protocol#Update_Teams) while the player is AFK, and we send the Team packets normally when the player is back (not AFK anymore), would it cause this disconnecting issue?

The packet interception plugin is made by myself and are running in my and my friend's servers.

**Comment by Akiranya** [comment]
I think I probably solved this issue. I don't intercept the Team packets and this issue does not happen anymore (for the last 12 hours)

**Comment by mcmonkey4eva** [comment]
Oh, yeah that edited message above explains a lot - issue had nothing to do with Citizens.
You can't just block out team packets, they do things and Bungee gets upset if they're mucked with.
