### ISSUE TITLE
Can't Create NPC

### ISSUE THREAD

**Issue by AbeAzka** [CitizensDev/Citizens2#2876]
### `/version` output

```txt
1.19
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT
```

### Log file

https://pastebin.com/RFyFhHud

### config.yml

https://pastebin.com/e7ZRMvrz

### saves.yml

https://pastebin.com/3eX1mAt7

### Description

I Can't Create Npc and my plugin for support command Citizens is command npc

**Comment by BehrRiley** [comment]
If you can't fill out the issue template form, please consider creating a thread on our Discord: https://discord.gg/Q6pZGSR

**Comment by AbeAzka** [comment]
ok
