### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by alexaraven** [CitizensDev/Citizens2#2878]
### `/version` output

```txt
Hello, citizen does not work and gives me an error, citizen please report this error. [see console] java.land.nullpointerexception: cannot invoke "net.minecraft.world.entity.ai.attribute.attribute`modifiable.a{double}" because "range" is null
```

### `/version Citizens` output

```txt
Citizens-2.0.30-b2662
```

### Log file

https://haste.flaxeneel2.net/7EdFFnKHMxagu8djwPDSBSyg3PUQDsWZexfzR73tooNk6LM9ao

### config.yml

https://dev-panel.falixnodes.net/server/bbcd52f9/files/edit#/plugins/Citizens/config.yml

### saves.yml

https://dev-panel.falixnodes.net/server/bbcd52f9/files/edit#/plugins/Citizens/saves.yml

### Description

![2022-09-10_22 26 29](https://user-images.githubusercontent.com/113259382/189496860-f9d98337-c150-4b04-8d4d-a582818b22e3.png)

**Comment by BehrRiley** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by alexaraven** [comment]
> https://wiki.citizensnpcs.co/Cracks
what
