### ISSUE TITLE
Skins dissapearing on moving NPCs

### ISSUE THREAD

**Issue by Boosik** [CitizensDev/Citizens2#288]
If NPC is static (does not move around) skins are working correctly.
But if I set path for my NPC and set a skin for it, it sets the skin, but if I fly away and then back skin disappears and reverts to classic steve/alex skin. If I fly away and back few times (1-3 times) skin comes back eventually, but after another fly away and back, it disappears again.

(My moving NPCs have Sentry trait, if it maters, but are using standard "/npc path" move path)
I'm using build #1221.

**Comment by mcmonkey4eva** [comment]
Direct skin disappearance discussion here: https://github.com/CitizensDev/Citizens2/issues/223
