### ISSUE TITLE
not working on 1.18.1

### ISSUE THREAD

**Issue by XVisior** [CitizensDev/Citizens2#2880]
### `/version` output

```txt
paper 1.18.1
```

### `/version Citizens` output

```txt
Citizens-2.0.30-b2700
```

### Log file

https://paste.denizenscript.com/View/101180

### config.yml

https://paste.denizenscript.com/View/101178

### saves.yml

https://paste.denizenscript.com/View/101179

### Description

hello, citizens plugin not working on 1.18.1, please help me

**Comment by fullwall** [comment]
You need to use 1.18.2.
