### ISSUE TITLE
Can't create npc

### ISSUE THREAD

**Issue by tugadevil** [CitizensDev/Citizens2#2883]
### `/version` output

```txt
1.19.2
```

### `/version Citizens` output

```txt
2.0.30
```

### Log file

https://paste.denizenscript.com/View/101209

### config.yml

https://paste.denizenscript.com/View/101210

### saves.yml

https://paste.denizenscript.com/View/101211

### Description

When trying to create a new npc, it shows an error and says to view it in the console.
Tried deleting the old folder, but nothing happened.

![imagem_2022-09-13_123905408](https://user-images.githubusercontent.com/113437947/189891634-6473e728-727e-4939-942f-1b05990428c8.png)

**Comment by BehrRiley** [comment]
Please actually fill out the issue template - The log is incomplete, and you did not correctly fill out the `/version` or `/version Citizens` output requests. Before correcting your request, you could either try updating your Paper version and Citizens build to see if it resolves your issue, or consider asking for help on our discord: https://discord.gg/Q6pZGSR


Latest Paper builds are at https://papermc.io/downloads.

Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.
Spigot releases of Citizens are available at https://www.spigotmc.org/resources/citizens.13811/.
