### ISSUE TITLE
Add option to change update rate for NPCs

### ISSUE THREAD

**Issue by alexey-va** [CitizensDev/Citizens2#2886]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Currently Citizens updates some stuff every tick (e.g. npc name). It can take a noticable part of server's tps while sometimes there is no need for that. I have 40 npcs with static names and due to updates taking place every tick Citizens is by far the most heavy plugin on my server.

**Comment by emmanuelvlad** [comment]
I have the same issue, static npcs without the need to be updated take a lot of server performance. I wish there would be a response to this issue or #2872

**Comment by galacticwarrior9** [comment]
In case empirical evidence of a performance problem is needed: 

![spark](https://i.gyazo.com/95abb56272a47b428026df87ea2dbe2a.png)

spark report is [here](https://spark.lucko.me/3WITgoayAT).

These are from the 6 NPCs we have on our server, which use the hologram trait:

![npcs](https://i.gyazo.com/5524caa5890015855600ada7f3c3bc0b.png)

**Comment by matipoirierg** [comment]
can confirm this performance issue

**Comment by alexey-va** [comment]
Dear devs, pls help. This will increase performance for many servers

**Comment by fullwall** [comment]
I have just pushed a micro optimisation for this issue.

**Comment by fullwall** [comment]
Going to close this for now, if required in a different context open another issue.
