### ISSUE TITLE
NPCs teleport on targeting players

### ISSUE THREAD

**Issue by kangarko** [CitizensDev/Citizens2#2887]
### `/version` output

```txt
This server is running Paper version git-Paper-142 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ef0e5a6)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2705)
```

### Log file

https://pastebin.com/QG0NCt2T

### config.yml

https://pastebin.com/4aGYWCb5

### saves.yml

empty file

### Description

Following up on issue https://github.com/kangarko/Boss/issues/1103

In a nutshell, NPCs are targeting players and teleporting themselves to players when players are too far away. I'd like to disable this feature of Citizens. Tried setting npc.follow.teleport-across-worlds to false to no avail.

Here is my code: https://pastebin.com/rwBQyKqy

Thank you!

**Comment by kangarko** [comment]
> You can either use straight line targeting or remove the stuck action.

Thank you, may I please ask you to point me out to the specific API call for this? I am not so familiar with the Citizens API at the moment.

**Comment by mcmonkey4eva** [comment]
When in doubt, API version of commands can be found by just finding the source of that command: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/WaypointCommands.java#L70

in this case `npc.getNavigator().getDefaultParameters().stuckAction(null);`

**Comment by kangarko** [comment]
Thank you so much that will help a ton <3
