### ISSUE TITLE
Shitty developers.

### ISSUE THREAD

**Issue by ShiftyRP** [CitizensDev/Citizens2#2890]
### `/version` output

```txt
Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.
```

### `/version Citizens` output

```txt
Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.
```

### Log file

Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.

### config.yml

Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.

### saves.yml

Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.

### Profiler report

Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.

### Description

Shitty developers. Can't get their shit together. Expect you to pay for their plugin and then ban you when you do what they say in support.

**Comment by BehrRiley** [comment]
https://denizenscript.com/discimg/citizens_is_free.png

Citizens is free, as explained on Spigot's `readme`, and as demonstrated by being completely open source.

Please also be aware that your behavior is against Github's usage and is considered both spam and harassment and will be reported.

**Comment by ShiftyRP** [comment]
REport me. :)

**Comment by ShiftyRP** [comment]
I'll be reporting them for their terrible support and behaviour
