### ISSUE TITLE
Citizens Hologram Bug

### ISSUE THREAD

**Issue by DebuffPvP** [CitizensDev/Citizens2#2892]
### `/version` output

```txt
This server is running ReliableSpigot version 2.4.4 (MC: 1.8.8) (Implementing API version 1.8.8-R0.3
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2673)
```

### Log file

N/A

### config.yml

https://paste.denizenscript.com/View/101315

### saves.yml

https://paste.denizenscript.com/View/101314

### Description

https://gyazo.com/65beac0602cb299c422d7310fbd35139 Hey how do i move this hologram close the the npc head instead of it being on top?

I already tried /npc hologram lineheight 0.25 and it didn't work so is this a bug or is there another command i must use?

**Comment by mcmonkey4eva** [comment]
Closing due to refusal to provide logs.
