### ISSUE TITLE
Everytime I try to create an npc this error pops up

### ISSUE THREAD

**Issue by Florixa** [CitizensDev/Citizens2#2897]
### `/version` output

```txt
Paper version git-paper-81 (MC:1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git:86f87ba)
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2702) Website: https://citizensnpcs.co/ Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/101495

### config.yml

https://paste.denizenscript.com/View/101496

### saves.yml

https://paste.denizenscript.com/View/101497

### Description

When doing (/npc create "username") in chat, Response: Please report this error: [See console] java.lang.NullPointerException: Canno't invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null.

![error](https://user-images.githubusercontent.com/114229578/191957990-893987c1-d0a8-473b-9055-1918ea459336.png)

**Comment by mcmonkey4eva** [comment]
update to 1.19.2
