### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NetroX283** [CitizensDev/Citizens2#2899]
### `/version` output

```txt
This server is running Pufferfish version git-Pufferfish-72 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8f05a00 on HEAD)
You are on the latest version!
Previous version: git-Paper-387 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2705)
```

### Log file

https://pastebin.com/zffC7R83

### config.yml

https://pastebin.com/0NGnZ1FU

### saves.yml

https://pastebin.com/Nx6nSseU

### Profiler report

https://spark.lucko.me/vj2b8Da91z

### Description

Hello, Citizens causes crashes on my server but I can't identify the problem

**Comment by RealMCSamuel** [comment]
1. Your latest.log file is not complete, it’s just the error.
2. You didn’t upload anything to the correct link in the box description.

**Comment by NetroX283** [comment]
https://pastebin.com/kQ4XtfCT
I did not understand your second question

**Comment by NetroX283** [comment]
https://paste.denizenscript.com/View/101607
https://paste.denizenscript.com/View/101608
https://paste.denizenscript.com/View/101609
https://paste.denizenscript.com/View/101610

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
