### ISSUE TITLE
NPC Skins not loading & reverting to default on world change.

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#290]
I am using the very latest Citizens 2 build (2.0.15 #1222) and not all of the NPC skins load on player join and when you change the world and come back, the skins revert back to Alex and Steve skins.

I am using Spigot 1.8.3. Version - CraftBukkit version git-Spigot-c136710-350cb99 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Protocol LIB version #91 for Spigot 1.8.3.

**Comment by mcmonkey4eva** [comment]
We have like 5 other issues for this.

**Comment by whoshenry** [comment]
Yes I realise but I was giving an update on the versions used. Is there going to be a fix for this?

**Comment by mcmonkey4eva** [comment]
We're still looking for the cause of it. All our attempted fixes seem to fail. Any help on that end would be greatly appreciated.
If you want to update that it's relevant to the latest versions, post on the existing issues themselves.
