### ISSUE TITLE
Unable to create NPC

### ISSUE THREAD

**Issue by Zanarak** [CitizensDev/Citizens2#2900]
### `/version` output

```txt
The server is in 1.19 version
```

### `/version Citizens` output

```txt
Citizens version is 2.0.30-SNAPSHOT
```

### Log file

https://paste.denizenscript.com/View/101617  

### config.yml

https://paste.denizenscript.com/View/101619

### saves.yml

https://paste.denizenscript.com/View/101618

### Description

Hello,

When I want create a NPC, an error message appeared is :
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null

It is possible to help me please ?

**Comment by RealMCSamuel** [comment]
Citizens doesn’t support 1.19.0. Update to 1.19.2
