### ISSUE TITLE
Cannot create Angry Wolves.

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#291]
When typing the command /npc wolf -a for a split second you can see the Angry Wolf but it then reverts back to the passive version.

Running latest Citizens2 2.0.15 and the latest ProtocolLIB and Spigot 1.8.3.

**Comment by mcmonkey4eva** [comment]
If this doesn't work, it's a Bukkit/Spigot issue. The code for this literally just calls the Bukkit method to set wolf's angry.

I recommend posting on the Spigot page and seeing what they say.

**Comment by whoshenry** [comment]
I've created an issue post there.

**Comment by whoshenry** [comment]
See here - https://hub.spigotmc.org/jira/browse/SPIGOT-735
