### ISSUE TITLE
Can't seem to get it to work, "/npc create Shop"

### ISSUE THREAD

**Issue by FalZz03** [CitizensDev/Citizens2#2910]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-411 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2673)
```

### Log file

https://paste.denizenscript.com/View/101965

### config.yml

https://paste.denizenscript.com/View/101967

### saves.yml

nothing generated

### Description

never used the citizens and newly bought it from spigot. just watched a quick tutorial on how to use it and when i tried doing the first thing "/npc create shop" i get a error

and i am unsure what this really is.
![Skjermbilde 2022-10-04 201839](https://user-images.githubusercontent.com/109356598/193895457-378f3712-db0e-4002-b4fe-ff16f65687fa.png)

**Comment by BehrRiley** [comment]
Your Log file is not a log file, it's an incomplete snippet of your server's output that you thought was relevant. Please provide the entirety of the log, optimally including a startup sequence; this means to include the entirety of the file, never copy anything less but everything. If the startup sequence is not evident, restart your server and replicate the issue before uploading it to our pastebin: https://paste.denizenscript.com/New/Log

additionally, That version is an outdated Citizens build.
The current Citizens build is 2710.
You are behind by 37 builds. 
Latest Citizens dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.
Spigot releases of Citizens are available at https://www.spigotmc.org/resources/citizens.13811/.

**Comment by FalZz03** [comment]
So i guess spigot is outdated. Now i downloaded the newest build got the error under.
![image](https://user-images.githubusercontent.com/109356598/193906499-82607671-3bb8-4d2e-bec3-9025c1782511.png)

this is the log when restarting the server: https://paste.denizenscript.com/View/101968

**Comment by BehrRiley** [comment]
Again, this is not a log you've provided. You pasted both an image that refers you to your console and a paste of what you thought what was relevant, neither are complete logs for your server.

Please post your full latest log file.

**Background Info**: One of the most helpful tools to identifying the source of a problem is your server logs file! Logs contain all sorts of important information like server and plugin versions, any error messages, and a lot more important information ([More Info](https://wiki.citizensnpcs.co/Logs)).

**How To**: Your log can be found in the logs folder within your server folder. The most recent log is a text file labeled latest.log. To get help using these logs, please open that file in a text editor and copy all of the text, then open https://paste.denizenscript.com/New/Log and paste the text into the box on the page. Then click "Submit" and copy the URL and paste that back into this channel.

**Comment by FalZz03** [comment]
here is the whole log on startup: https://paste.denizenscript.com/View/101969

**Comment by mcmonkey4eva** [comment]
You need 1.19.2, not 1.19(.0)

**Comment by FalZz03** [comment]
Why do i need 1.19.2 to run citizens? what version of citizens do i need to run a 1.19 server?
