### ISSUE TITLE
Can't seem to get the plugin to work with command "/npc create shop". 

### ISSUE THREAD

**Issue by FalZz03** [CitizensDev/Citizens2#2911]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-411 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
Version 2.0.30-SNAPSHOT (build 2712)
```

### Log file

https://paste.denizenscript.com/View/101998

### config.yml

https://paste.denizenscript.com/View/101999

### saves.yml

https://paste.denizenscript.com/View/102000

### Description

I made a post earlier but got closed without being 100% resolved (https://github.com/CitizensDev/Citizens2/issues/2910#issue-1396668695)

When i try to make a npc i get the following error
![image](https://user-images.githubusercontent.com/109356598/194080125-d891fca6-42b5-47d4-81eb-f4faf20d9b09.png)

**Comment by fullwall** [comment]
As before, the solution is to update to 1.19.2.

**Comment by FalZz03** [comment]
why cant i use citizens on older versions on mc?

**Comment by fullwall** [comment]
Citizens only targets the most recent patch version so you can get the most Minecraft bugfixes/features for a given update version.
