### ISSUE TITLE
my npc is invisible and have a bug

### ISSUE THREAD

**Issue by PowerOFGaming** [CitizensDev/Citizens2#2913]
### `/version` output

```txt
1.19.2
```

### `/version Citizens` output

```txt
Citizens-2.0.30-b2716.jar
```

### Log file

https://paste.denizenscript.com/View/102082.txt

### config.yml

https://paste.denizenscript.com/View/102082.txt

### saves.yml

https://paste.denizenscript.com/View/102083.txt

### Description

my server is created from aternos.
when i creates it didnt show the npc but the npc works like the same.
then when i go to the console i see that, that says,
Can't keep up! Is the server overloaded? Running 6106ms or 122 ticks behind
and
[STDERR]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
please fix this issue

**Comment by PowerOFGaming** [comment]
and i was using sentinel plugin
https://www.spigotmc.org/resources/sentinel.22017/

**Comment by mcmonkey4eva** [comment]
If you have a real issue, consider opening a thread on Discord @ https://discord.gg/Q6pZGSR
if you're just here to troll with fake paste links, find something better to do.
