### ISSUE TITLE
Colorcode of npc textes dont get parsed

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#2914]
### `/version` output

```txt
[13:00:52 INFO]: Checking version, please wait...
[13:00:53 INFO]: This server is running Paper version git-Paper-199 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 77a50b9)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-196 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
[13:00:29 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2708)
[13:00:29 INFO]: Website: https://www.citizensnpcs.co
[13:00:29 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/102158

### config.yml

https://paste.denizenscript.com/View/102159

### saves.yml

https://paste.denizenscript.com/View/102160

### Description

The issue apears in newer versions. We have a lot of citicents that paste textes to the chat when you get near them.
we tried the latest build and saw that the colorcodes of this chat doent get parsed anymore.

Here an example:
![image](https://user-images.githubusercontent.com/12080017/195074104-e5654bbd-6b0a-449b-9be9-bcf63a06e63d.png)

If you look into the config you see that this is the format that was defined in the config.
```
      to-target: '&b<npc>&e: &f<text>'
```
we switched back to Build Version 2708. Here this issue does not appear.and the text is defined like in config (so white text here) and the npc name in this "lightcyanblue" and the dot in its colors.

So we aspect that on of the Builds after 2708 to the latest broke the config colors definition...

**Comment by ScuroK** [comment]
I can confirm

**Comment by RealMCSamuel** [comment]
Your Paper version is 3 versions behind, and your Citizens version is 9 behind the latest. 
Grab the build from this link: https://ci.citizensnpcs.co/job/Citizens2/ , and see if that works.

**Comment by CloudeLecaw** [comment]
you didnt understood right? it doesnt matter the we are 3 version behind. paper aometimes makes 3 Updates a day.

i said we DOWNGRADED citicenz to the version you see in logs, because it issue exist only starts with the newer versions.

so if we Upgrade the issue is back..dont look at the version we use now. we downgraded to fix the issue.
with the current used version of citicenz it works fine.

i hope can fix it soon so we can upgrade aggain.

**Comment by RealMCSamuel** [comment]
Looking back, the major changes to the texts were in 2714 and 2717. Couple you try in these two, as well as the versions right before them (2713 & 2716)?

**Comment by ScuroK** [comment]
I had the issue yesterday on yesterdays latest paper version.

**Comment by CloudeLecaw** [comment]
> Looking back, the major changes to the texts were in 2714 and 2717. Couple you try in these two, as well as the versions right before them (2713 & 2716)?

like i said we used 2708 abd updated to 2717 but i will try the others today too.

**Comment by CloudeLecaw** [comment]
Its me Aggain: 

```
[18:52:13 INFO]: This server is running Paper version git-Paper-207 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 7fe34e9)
You are running the latest version
Previous version: git-Paper-206 (MC: 1.19.2)
```` 

config part: ```      to-target: '&b<npc>&e: &f<text>'```` 
text from save ```        text:
          '0': Willkommen auf Mirai, hier kannst du wundervolle Gebäude und Zonen
            anschauen aus einer alten Minecraft Vergangenheit. Du kannst &4/fly &fmachen
            und dabei alles erkunden.Wenn du Lust hast Besuche uns auf &4mc.lululand.de
            &fda geht der Spass weiter. Bis dann :)```


Build 2717 verion sowed this:
![Snag_fca6b](https://user-images.githubusercontent.com/12080017/195401525-1a8af19b-cb1e-4ed7-83fc-a012d997895b.png)


Build 2713, 2714, 2715, 2716 shows this
![Snag_136257](https://user-images.githubusercontent.com/12080017/195402248-a4b5ed4a-171e-4876-ad30-cc16d1d67a9d.png)

Build 2712 shows the correct format
![Snag_1a8c24](https://user-images.githubusercontent.com/12080017/195403809-6bff38b4-1fd1-41d5-9eae-7052a2f2a31d.png)

So we could update now own server from 2708 to 2712

So all build after 2713 have the effect (and it changed with 2717 but is still wrong)

**Comment by RealMCSamuel** [comment]
Ah, I see the issue. @fullwall I think you accident removed " import org.bukkit.ChatColor" in "main/src/main/java/net/citizensnpcs/util/StringHelper.java" during build 2713

**Comment by mcmonkey4eva** [comment]
Should be fixed in new dev build https://github.com/CitizensDev/CitizensAPI/commit/ac33673df56aae831f80a62802310c0c3ff16996

**Comment by CloudeLecaw** [comment]
Issues got fixed with Build 2719 =)
![Snag_57d2f8](https://user-images.githubusercontent.com/12080017/195665372-a4794ff1-a570-488f-b6d3-f26bf929a951.png)
