### ISSUE TITLE
NPCs can't find path after server restarts

### ISSUE THREAD

**Issue by James0699** [CitizensDev/Citizens2#2915]
### `/version` output

```txt
This server is running Paper version git-Paper-200 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: c389b1c)
```

### `/version Citizens` output

```txt
aCitizensf version a2.0.30-SNAPSHOT (build 2717)
```

### Log file

https://paste.denizenscript.com/View/102173

### config.yml

https://paste.denizenscript.com/View/102174

### saves.yml

https://paste.denizenscript.com/View/102175

### Description

Hello. So I ran into this issue, that after server restarts CITIZENS NPCs can't find path on  **/npc pathto x y z command**. When the same command i**s run the second time it works**. **After server restart the same issue occurs** and an NPC can find path only after **the command is run the second time** while server is online.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
