### ISSUE TITLE
Npc disappear after chunk unload with paper

### ISSUE THREAD

**Issue by Bibithom** [CitizensDev/Citizens2#2918]
### `/version` output

```txt
Paper version git-Paper-211 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
Citizens v2.0.30-SNAPSHOT (build 2719)
```

### Log file

https://paste.denizenscript.com/View/102248

### config.yml

https://paste.denizenscript.com/View/102277

### saves.yml

https://paste.denizenscript.com/View/102278

### Description

What i would like to be able to do : use mob npc in non spawn chunk.
What's my issue : Mobs npcs despawn during chunk unload and **never respawn**.

Description :
Mobs npcs are invisible/not there after chunk unload/reload.
I've created a simple npc with /npc create test --type VILLAGER, when moving far way and going back, npcs aren't there anymore. I can select them with /npc sel, modify them, but they don't show up.

To test it, i've used a barebones server, using only paper and no plugins. So paper + citizen create that issue. It only works outside spawn chunk (yes they're permanently loaded, i know).

I've tried to reproduce with a spigot server, and this issue doesn't occur, so it related to paper.
I've tried with player npc, and it works.
I've tried in spawn chunks, it works

Step to reproduce :
1. Start server (no plugin just papermc)
2. Move away from spawn (/tp 500 120 500)
3. create a test mob npc (/npc create test --type COW)
4. unlog, then relog
5. Npc has disappeared.

Thank you in avance for your help, have a nice day. Feel free to ask me any questions.

**Comment by ScuroK** [comment]
Could you report this to paper aswell please? Your server setup is much cleaner than mine and im not 100% sure if we have the same issue. 

If you report it to paper we can see if they are willing to fix it or if  citizens would need to find a way to patch it.

**Comment by ChrissW-R1** [comment]
Same issue here

**Comment by fullwall** [comment]
Fixed
