### ISSUE TITLE
Pathing waypoint marker issue

### ISSUE THREAD

**Issue by Sycholic** [CitizensDev/Citizens2#292]
Seems that now when you use the highlighting feature to mark out what pathing markers for npcs like sentries.  It is using Eye of Ender. Now they fly off into the sunset making it impossible to use them effectively.

**Comment by mcmonkey4eva** [comment]
*tests*
Oh. Oh that is ... fantastic... guess there must've been a typo during an update or somethin', switching the two ender entities around... hm...

**Comment by mcmonkey4eva** [comment]
This build should fix it: https://dl.dropboxusercontent.com/u/54130586/citizens-2.0.15-SNAPSHOT.jar

**Comment by Sycholic** [comment]
looks good..... tested not more flying off into the sunset...
