### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ProtoGhost** [CitizensDev/Citizens2#2920]
### `/version` output

```txt
This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Previous version: git-Paper-1618 (MC: 1.12.2)
```

### `/version Citizens` output

```txt
Citizens v2.0.30-SNAPSHOT (build 2719)
```

### Log file

https://pastebin.com/q36GrCgj

### config.yml

https://pastebin.com/WKSrLB60

### saves.yml

https://pastebin.com/W8WJn8VB

### Description

throwing error in the startup

**Comment by ProtoGhost** [comment]
![image](https://user-images.githubusercontent.com/67905221/196171901-4c63993c-78dd-4755-ba9e-fc77cdad0756.png)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by ProtoGhost** [comment]
im not using cracked server
wtf
