### ISSUE TITLE
NPC Nameplates "fall off" and duplicate

### ISSUE THREAD

**Issue by SykoUSS** [CitizensDev/Citizens2#2922]
### `/version` output

```txt
This server is running Paper version git-Paper-220 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3dcfec4)
You are running the latest version
Previous version: git-Paper-219 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2666)
```

### Log file

https://paste.denizenscript.com/View/102460

### config.yml

https://paste.denizenscript.com/View/102461

### saves.yml

https://paste.denizenscript.com/View/102462

### Description

After some time, NPCs in a certain area began to "drop" their nameplate armor-stands and duplicate, either leaving a trail of nameplates along their path or a massive pile of nameplates where they were standing.

I am unsure how to replicate this bug.

Removing the NPC and creating a new one did fix the issue for some, but the bug still persists for most unless I disable nameplate visibility

**Comment by mcmonkey4eva** [comment]
Update, already been fixed.
