### ISSUE TITLE
Citizens shows up under /plugins, but any citizens commands yield "Unknown/Incomplete Command"

### ISSUE THREAD

**Issue by lunachuu** [CitizensDev/Citizens2#2923]
### `/version` output

```txt
This server is running Paper version git-Paper-"3dcfec4" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3dcfec4)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2731)
```

### Log file

https://paste.denizenscript.com/View/102478

### config.yml

https://paste.denizenscript.com/View/102479

### saves.yml

https://paste.denizenscript.com/View/102479

### Description

I have the latest version of Citizens and now Paper rather than Spigot, but my server despite listing Citizens in my plugins yields "Unknown or incomplete command" when using any Citizens command. No errors are in my log as far as I know, but /help Citizens works. Could not upload saves.yml because paste denizenscript says it's too small since there are no saves in there.
![image](https://user-images.githubusercontent.com/116419318/197321920-3f5153b9-acc7-420c-98e5-a029311a069e.png)

**Comment by mcmonkey4eva** [comment]
Favoring your Discord thread that already exists over this.
