### ISSUE TITLE
possibility to duplicate items with an allay npc

### ISSUE THREAD

**Issue by Ceddix** [CitizensDev/Citizens2#2925]
### `/version` output

```txt
Current: git-Purpur-1825 (MC: 1.19.2)*
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2731)
```

### Log file

https://pastebin.com/zzbX9Add (only citizens logs - if something else should be relevant, I could provide it)

### config.yml

https://pastebin.com/FaT71aPD (but shouldn't be relevant)

### saves.yml

https://pastebin.com/twY07twU (but shouldn't be relevant)

### Description

Players _without special permissions_ can give and remove items from allays, this bug also allows them to **duplicate** items.
For better understanding, we've recorded a video: https://youtu.be/WnOlMdnIFo0

Hopefully this bug can be fixed quickly, as it is quite critical.

Greetings, Ceddix 😄

**Comment by mcmonkey4eva** [comment]
Closing due to refusal to provide required information.

Consider also posting on Discord @ https://discord.gg/Q6pZGSR in the Citizens channel
