### ISSUE TITLE
 the bungeecord server command does not work for npc

### ISSUE THREAD

**Issue by kol0na** [CitizensDev/Citizens2#2926]
### `/version` output

```txt
spigot 1.8.8
```

### `/version Citizens` output

```txt
citizens 2.0.30
```

### Log file

https://paste.denizenscript.com/View/102714

### config.yml

https://paste.denizenscript.com/View/102713

### saves.yml

https://paste.denizenscript.com/View/102712

### Description

when I try to add a command on nps to switch to another buneecord server, it does not appear, there is not even an error in the chat of the console, although everything is fine with all other commands

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
