### ISSUE TITLE
no implementation set

### ISSUE THREAD

**Issue by RedCarl** [CitizensDev/Citizens2#2928]
### `/version` output

```txt
This server is running Mirai version git-Mirai-24 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: e0a26d7 on HEAD)
You are on the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2742)
```

### Log file

null

### config.yml

null

### saves.yml

null

### Description

![image](https://user-images.githubusercontent.com/71010647/200043220-189982cb-a141-47ab-b364-d6783ef1d269.png)
![image](https://user-images.githubusercontent.com/71010647/200043294-3ab20ec9-f69f-42c5-b6ca-66615f79e810.png)

**Comment by mcmonkey4eva** [comment]
Closing due to refusal to provide required information.

Consider also making a thread on https://discord.gg/Q6pZGSR in the `#citizens` channel
