### ISSUE TITLE
PlayerUpdateTask performance issue

### ISSUE THREAD

**Issue by SwartZCoding** [CitizensDev/Citizens2#2929]
### `/version` output

```txt
Current: git-Purpur-1834 (MC: 1.19.2)*
Previous: git-Purpur-1749 (MC: 1.19.1)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### `/version Citizens` output

```txt
[11:47:49 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2742)
[11:47:49 INFO]: Website: https://www.citizensnpcs.co
[11:47:49 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/103003

### config.yml

https://paste.denizenscript.com/View/103004

### saves.yml

https://paste.denizenscript.com/View/103005

### Profiler report

https://spark.lucko.me/eX0T0OJWDE

### Description

I have no info about that, i just make a spark and see that ^^.

**Comment by mcmonkey4eva** [comment]
Of the 5% used by PlayerUpdateTask, 4.75% is literally just vanilla entity ticking on player-type NPCs. You probably just have a bunch of NPCs spawned and/or moving around.

**Comment by SwartZCoding** [comment]
> Of the 5% used by PlayerUpdateTask, 4.75% is literally just vanilla entity ticking on player-type NPCs. You probably just have a bunch of NPCs spawned and/or moving around.

I just literally have less than 35 NPC on my all server ... Like 10 of them doesn't have lookup enabled. And no one move.
