### ISSUE TITLE
Why Isnt It Working For 1.8.3?

### ISSUE THREAD

**Issue by coolguy87653** [CitizensDev/Citizens2#293]
Hello, I Just Got 1.8.3 And Got Some Cool Plugin Finally Enabled But The Bad Part IS That Citizens 2 isn't I got the latest version 1.8.1 but it doesn't work, why please respond back staff, mod, Or Even better the owner, thanks a lot for helping me and the compunity

Thanks and hope you can solve my problem

**Comment by mcmonkey4eva** [comment]
You'll need the latest dev build, available here: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by coolguy87653** [comment]
TY
