### ISSUE TITLE
creating npc bug

### ISSUE THREAD

**Issue by PowerOFGaming** [CitizensDev/Citizens2#2930]
### `/version` output

```txt
minecraft 1.19
```

### `/version Citizens` output

```txt
Citizens-2.0.30-b2742.jar
```

### Log file

https://paste.denizenscript.com/View/103040

### config.yml

https://paste.denizenscript.com/View/103041

### saves.yml

https://paste.denizenscript.com/View/103042

### Description

Please fix this i will be so much happy

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2
