### ISSUE TITLE
Error on startup when dispatching /npc skin

### ISSUE THREAD

**Issue by nicholasveronico** [CitizensDev/Citizens2#2931]
### `/version` output

```txt
[02:46:02 INFO]: This server is running Paper version git-Paper-263 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3ac1a8d)
```

### `/version Citizens` output

```txt
[02:46:23 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2748)
[02:46:23 INFO]: Website: https://www.citizensnpcs.co
[02:46:23 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/103116

### config.yml

https://paste.denizenscript.com/View/103117

### saves.yml

https://paste.denizenscript.com/View/103118

### Profiler report

https://spark.lucko.me/7Y26pPnOPq

### Description

With one of our plugins, it creates three NPCs from the plugin's config using the following:
`NPCRegistry.createNPC(EntityType.PLAYER, name);` and
`NPCRegistry registry = CitizensAPI.createNamedNPCRegistry  ("civilizations",new MemoryNPCDataStore());`

It then sets a skin for each NPC using the following:
`Bukkit.getServer().dispatchCommand(Bukkit.getConsoleSender(),"npc skin --url "+url);`

We are getting this error upon the server starting (and I am assuming when the NPCs are created), which is preventing the NPCs from spawning. We were about 50 builds behind prior to this issue happening.

https://paste.denizenscript.com/View/103119

If you require any additional information, please let me know.

**Comment by mcmonkey4eva** [comment]
Refer to: https://wiki.citizensnpcs.co/Skins

You should not try to set skins from url directly via code. That's a convenience tool for in-game usage, that just downloads the *actual* data the code needs from a third-party service.
Your code should be applying the *actual* data directly.
