### ISSUE TITLE
1.19.2 load failed

### ISSUE THREAD

**Issue by Tptuaazn** [CitizensDev/Citizens2#2932]
### `/version` output

```txt
This server is running Purpur version git-Purpur-1838 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
Citizens v2.0.30-SNAPSHOT (build 2755)
```

### Log file

https://paste.denizenscript.com/View/103156

### config.yml

Not generated

### saves.yml

Not generated

### Description

Got error at first time loading plugin.

**Comment by fullwall** [comment]
Fixed
