### ISSUE TITLE
Citizens implementation changed

### ISSUE THREAD

**Issue by cameronnarrel** [CitizensDev/Citizens2#2933]
Server version 1.19.2
whenever i try to enable Citizens it shows this 

[Citizens] Citizens implementation changed, disabling plugin.
13.11 17:42:39 [Server] [INFO] [Citizens] Disabling Citizens v2.0.29-SNAPSHOT (build 2520)
13.11 17:42:39 [Server] [ERROR] Error occurred while enabling Citizens v2.0.29-SNAPSHOT (build 2520) (Is it up to date?)
13.11 17:42:39 [Server] [INFO] java.lang.NullPointerException: inStream parameter is null

**Comment by mcmonkey4eva** [comment]
Either A: follow the issue template and post full details with logs and all
or B: join the Discord @ https://discord.gg/Q6pZGSR and post in the `#citizens` channel
