### ISSUE TITLE
Cannot spawn NPC

### ISSUE THREAD

**Issue by AKACZ208** [CitizensDev/Citizens2#2935]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2769)
```

### Log file

https://paste.denizenscript.com/View/103456

### config.yml

https://paste.denizenscript.com/View/103457

### saves.yml

https://paste.denizenscript.com/View/103458

### Description

When I was trying to **create** the NPC, it was just giving some kind of an error in the console.

**Comment by mcmonkey4eva** [comment]
You need 1.19.2, not 1.19(.0)
