### ISSUE TITLE
NPC Name Hex Colors Broken

### ISSUE THREAD

**Issue by TroyFarmer** [CitizensDev/Citizens2#2936]
### `/version` output

```txt
[2022-11-29 19:23:49] [INFO]: This server is running Paper version git-Paper-290 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: d98c370)
```

### `/version Citizens` output

```txt
[2022-11-29 19:25:24] [INFO]: Citizens version 2.0.30-SNAPSHOT (build 2759)
```

### Log file

https://paste.denizenscript.com/View/103555

### config.yml

https://paste.denizenscript.com/View/103554

### saves.yml

https://paste.denizenscript.com/View/103553

### Profiler report

N/A

### Description

Since updating our server to the latest version (from 1.19 to 1.19.2) and Citizens to the latest build, my custom NPCs have no longer been able to use custom hex colors. The colors worked as intended for at least the last four months, the latest version it worked on being when we updated to 1.19 with build 2.0.30 ALPHA #2 (I think). Nothing in the save file was changed during the update, and no alternative color hex code formats (modern, legacy, §s, non-§s, etc.) have worked for me.

This problem is apparent when my citizens use gradients in their name, as displayed here:

**Old, working colors**
![Hex1](https://user-images.githubusercontent.com/101306033/204702332-8f6b2c0d-b571-4c34-8dd7-16d10c2fb687.PNG)

**Current, broken colors**
![Hex2](https://user-images.githubusercontent.com/101306033/204702419-789d3f97-d0e3-443b-b029-6cc200356ef5.PNG)

To reproduce this error, use **/npc rename &#8efbfb&lO&#82f4fbp&#76ecfba&#6be5fcq&#5fddfcu&#53d6fce &#47cffc&lO&#3bc7fcp&#2fc0fch&#24b8fde&#18b1fdl&#0ca9fdi&#00a2fda** on an NPC.

I assume the reason for the broken colors in the second image is due to Citizens being unable to recognize custom hex codes, and thus registering them as their closest default counterparts. Other plug-ins that we use have been able to render custom color codes just fine.

If there is a proven method to side-step this issue, please let me know. Thank you.

**Comment by mcmonkey4eva** [comment]
That's... odd.

Several recent commits touch related code, so try updating to the latest dev build to see if that happens: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by TroyFarmer** [comment]
Updating to the latest version seems to have fixed the color rendering issue. Thanks!

However, the fix seems to have created another, minor problem. Now, for whatever reason, the text seems to encounter some formatting issues. Usually, whenever a new color is specified, the format (e.g. bold, italics, underline) resets, making way for another format. The issue is displayed here:

**Old, working format**
![Hex1](https://user-images.githubusercontent.com/101306033/204957906-af3bfda1-857a-4923-9338-c44b1a8a3d6e.PNG)

**New, broken format**
![hex3](https://user-images.githubusercontent.com/101306033/204957956-d6c9167d-84ae-4313-93e6-63b6bd58d741.PNG)

Now, using a single bold (&l) specifier turns the entire name bold, without any way to isolate it.

Albeit this issue isn't nearly as severe, and I'm satisfied the greater problem has been corrected. However I still cannot seem to return the names to their former state. The command used is the same as earlier and, again, nothing had changed in the actual save file to produce this error. Using &r (the color/format reset string) doesn't seem to work either.

Could be my fault, but I don't see a way around it. Please continue to keep me posted on this issue. Thanks again.

**Comment by fullwall** [comment]
Can you try with the new build?

**Comment by mcmonkey4eva** [comment]
issue still present on Citizens-2775.

**Comment by fullwall** [comment]
Tested on latest build working.

**Comment by TroyFarmer** [comment]
I can confirm that, after updating to the latest Citizens build, the issue has been fixed. Thank you!

**Comment by MoeXIV** [comment]
Currently experiencing this same issue on build 2838.

**Comment by fullwall** [comment]
> Currently experiencing this same issue on build 2838.

Please open a new issue
