### ISSUE TITLE
Invalid player data

### ISSUE THREAD

**Issue by MehdiPG** [CitizensDev/Citizens2#2939]
### `/version` output

```txt
This server is running Arclight version arclight-1.18.2-1.0.7-40114eb5 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2777)
```

### Log file

https://paste.denizenscript.com/View/103646

### config.yml

https://paste.denizenscript.com/View/103647

### saves.yml

https://paste.denizenscript.com/View/103648

### Description

When I installed the citizens plugin, when joining the server, it kicks me out of the server with this error: Invalid player data, but when I remove the plugin, everything works fine

**Comment by fullwall** [comment]
There's a lot going in your log, but it's not related to Citizens. (Forge, Oh The Biomes You'll Go, https://wiki.citizensnpcs.co/Cracks).
