### ISSUE TITLE
bugs in the /NPC shop

### ISSUE THREAD

**Issue by glueglue12** [CitizensDev/Citizens2#2941]
### `/version` output

```txt
Spigot-1.19.2.jar
```

### `/version Citizens` output

```txt
https://youtu.be/jduVKpIQ9Fo
Citizens: 2.0.30-Snapshot (build 2783)

https://youtu.be/FNmvfb10QXQ
Citizens: 2.0.30-Snapshot (build 2782)
```

### Log file

https://paste.denizenscript.com/View/103693

### config.yml

https://paste.denizenscript.com/View/103691

### saves.yml

https://paste.denizenscript.com/View/103692

### Description

Version: 1.19.2
Hello!
I made npc shop using citizen plugin on Minecraft server. However, the shop command does not work from 2.0.30-Snapshot (build 2783).
[Youtube Link](https://youtu.be/jduVKpIQ9Fo)

And I also found a bug when exchanging items with items.
When a player has 60 items, if you buy 10 items, 64 items are defined as one set and 6 items are left. At this time, there is a bug where the result of the item changes to six items.
[Youtube Link](https://youtu.be/FNmvfb10QXQ)

PS. Could you include the function to display the price of the item?

example.
[Item Name]
[type] Sell/Buy
[Price] Item Name X 5

[Silver coins]
[type] Sell
[Price] Copper Coin x 10

I am Korean and I used a translator.

**Comment by mcmonkey4eva** [comment]
Try updating to the dev build, the bug may have already been fixed - https://ci.citizensnpcs.co/job/Citizens2/

**Comment by glueglue12** [comment]
Thank you!
The problem with the /npc shop command not working is resolved. But the second problem has not been solved.

**Comment by fullwall** [comment]
Is it working in build 2793 or above?

**Comment by glueglue12** [comment]
It's fixed! Thank you!
