### ISSUE TITLE
CustomEntityRegistry not working as expected (with "solution")

### ISSUE THREAD

**Issue by Jakllp** [CitizensDev/Citizens2#2947]
### `/version` output

```txt
This server is running Paper version git-Paper-334 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 20503be)
You are running the latest versionr
Previous version: git-Paper-323 (MC: 1.19.3)
```

### `/version Citizens` output

```txt
Citizensversion 2.0.30-SNAPSHOT (build 2813)
```

### Log file

https://paste.denizenscript.com/View/104019

### config.yml

https://paste.denizenscript.com/View/104020

### saves.yml

https://pastebin.com/RVrfjdRR

### Description

Hi, I'm the maintainer of MyPet and users have reported some fun behavior when using Citizens and MyPet on 1.19.3 (see https://github.com/MyPetORG/MyPet/issues/1587)

I've hunted down the root of this problem:
In your [CustomEntityRegistry](https://github.com/CitizensDev/Citizens2/blob/master/v1_19_R2/src/main/java/net/citizensnpcs/nms/v1_19_R2/util/CustomEntityRegistry.java#L155) you check if the `intrusiveHolderCache` of the original EntityRegistry is null to determine if you should put true or false in the constructor.
This however will always return false as Minecraft will use the `freeze()` method before enabling plugins, setting the intrusiveHolderCache to null.

This will in turn result in the `CustomEntityRegistry` not being able to create intrusive holders.

I tried just forcing this to `true` which resulted in a more different error:
https://paste.denizenscript.com/View/104021

This could then be resolved by changing the type of the `wrapped` field in `CustomEntityRegistry` to be `DefaultedMappedRegistry`.

This results in the class looking like this:
https://github.com/Jakllp/Citizens2/blob/15669d5c55b4309413a4528a91737c80a4840ee9/v1_19_R2/src/main/java/net/citizensnpcs/nms/v1_19_R2/util/CustomEntityRegistry.java

I did not want to create a pull request as I don't know if you just want this "hacked" `true` value there.

**Comment by fullwall** [comment]
Thanks, I have implemented your solution.
