### ISSUE TITLE
CAMEL OPTIONS!

### ISSUE THREAD

**Issue by moda84** [CitizensDev/Citizens2#2949]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Add lying camel and camel with saddle!
/npc camel position stand/lay

**Comment by mcmonkey4eva** [comment]
Fullwall added `camel (--pose pose) (--strength strength)` for the new dev build via https://github.com/CitizensDev/Citizens2/commit/c6e7ce65f5001b6eacccb7b09252d028e6df8532
