### ISSUE TITLE
Rabbit Sentry Waypoint not working

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#295]
I am trying to create a Boss Mob in conjunction with the Quests plugin, it requires the player to kill a rabbit.

With this rabbit, it has Sentry as a trait and I put the waypoint in a simple straight line, but the rabbit does not follow the waypoint at all. I've tried removing/creating a new one with the same info and the problem persists.

This is the config entry for the NPC - http://pastebin.com/BfWiYV4Z

**Comment by fullwall** [comment]
Working on it.
