### ISSUE TITLE
Npc at tablist...

### ISSUE THREAD

**Issue by zPeppo05** [CitizensDev/Citizens2#2950]
### `/version` output

```txt
Current: git-Purpur-1862 (MC: 1.19.3)*
Previous: git-Purpur-1857 (MC: 1.19.2)
* You are 11 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### `/version Citizens` output

```txt
[18:16:13 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2816)
[18:16:13 INFO]: Website: https://www.citizensnpcs.co
[18:16:13 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104127

### config.yml

https://paste.denizenscript.com/View/104130

### saves.yml

https://paste.denizenscript.com/View/104128

### Description

Hi, citizens appear in the tablist..

![image](https://user-images.githubusercontent.com/70705179/208255874-a58beed1-c4f7-4a77-8133-36eebd5e8212.png)

**Comment by mcmonkey4eva** [comment]
No you cannot use github issues to get past the DNS restriction on Discord.
