### ISSUE TITLE
NO TYPE FOR CAMEL

### ISSUE THREAD

**Issue by moda84** [CitizensDev/Citizens2#2952]
### `/version` output

```txt
Current: git-Purpur-1873 (MC: 1.19.3)*
Previous: git-Purpur-1870 (MC: 1.19.3)
* You are running the latest version
```

### `/version Citizens` output

```txt
Citizens 2.0.30-SNAPSHOT (Build 2822)
```

### Log file

read.info

### config.yml

read.info

### saves.yml

read.info

### Description

![image](https://user-images.githubusercontent.com/44532692/208291133-3c6cbfaa-5fb9-4e79-8e36-670c8801e87a.png)
Cant set sitting camels, because {0} not camel

**Comment by mcmonkey4eva** [comment]
Closing for not providing required information.

Consider also asking for support on Discord @ https://discord.gg/Q6pZGSR  in the citizens channel

**Comment by moda84** [comment]
> Closing for not providing required information.

ok...
![image](https://user-images.githubusercontent.com/44532692/208293690-6331da8d-ad5b-47a2-a57e-dd0555f29d0c.png)
