### ISSUE TITLE
CustomEntityRegistry AssertionError (The saga continues. sorry)

### ISSUE THREAD

**Issue by Jakllp** [CitizensDev/Citizens2#2953]
### `/version` output

```txt
This server is running Paper version git-Paper-334 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 20503be)
You are running the latest version
Previous version: git-Paper-323 (MC: 1.19.3)
```

### `/version Citizens` output

```txt
Citizens�version 2.0.30-SNAPSHOT (build 2822)
```

### Log file

https://paste.denizenscript.com/View/104160

### config.yml

https://paste.denizenscript.com/View/104020

### saves.yml

https://pastebin.com/RVrfjdRR

### Description

Good old CustomEntityRegistry.

So the 2815 build fixed the MyPet issues, causing UltraCosmetics-Issues (https://github.com/CitizensDev/Citizens2/issues/2951).
Now with those taken care of, MyPet is getting an AssertionError.

There's some fun behavior using both MyPet and UltraCosmetics as UC doesn't unfreeze the registry in that case - but that's besides the point.
Switching between just UC and just MyPet I whipped up a fix that works for both and will make a PR request for it.
Just wanted to document everything properly.

I hated Mojang's changes to the registry (aka freezing) and will continue to do so.

**Comment by Jakllp** [comment]
https://github.com/CitizensDev/Citizens2/pull/2954

**Comment by fullwall** [comment]
I don't see how the change to the field type would change this?

**Comment by Jakllp** [comment]
I don't know why, I don't know how but it does
