### ISSUE TITLE
Having trouble getting the plugin to show up green and/or work.

### ISSUE THREAD

**Issue by alienspy007** [CitizensDev/Citizens2#2959]
### `/version` output

```txt
[20:21:27 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-201 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
> version Citizens
[20:22:41 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2793)
[20:22:41 INFO]: Website: https://www.citizensnpcs.co
[20:22:41 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104391

### config.yml

https://paste.denizenscript.com/View/104392

### saves.yml

# Citizens NPC Storage  {}

### Description

I've tried using several versions of citizens, including the latest version and one that I believe to be made for 1.19.2, and when I do the /plugins command, it shows as red. When trying to use citizens commands in-game, I get internal errors.

**Comment by mcmonkey4eva** [comment]
ProtocolLib is failing to load on your server, and Citizens failing is just a side effect of that. Remove ProtocolLib or replace it with a version that works for 1.19.2

**Comment by alienspy007** [comment]
Thanks! I'll give that a try, didn't realize it used protocolib
