### ISSUE TITLE
1 Command

### ISSUE THREAD

**Issue by jakovkacan** [CitizensDev/Citizens2#296]
I can use only one command: /npc create <name>  
/npc type /npc remove /npc rename doesn't work!
Plese fix that!!!

**Comment by mcmonkey4eva** [comment]
What version(s) are you running? (Spigot version? Citizens version?)

**Comment by jakovkacan** [comment]
I have 1.7.10 Bukkit server.

2015-03-27 22:49 GMT+01:00 mcmonkey <notifications@github.com>:

**Comment by mcmonkey4eva** [comment]
That does not answer my question in full.

**Comment by jakovkacan** [comment]
I have 2.0.13 Citizens version.



2015-03-28 23:03 GMT+01:00 mcmonkey <notifications@github.com>:

**Comment by mcmonkey4eva** [comment]
... you know what, just grab the right version off http://wiki.citizensnpcs.co/Versions
I don't know if you have the right version based on your inability to answer questions fully, but I'm going to start making assumptions
