### ISSUE TITLE
Hex color codes not working on (most) NPC nametags

### ISSUE THREAD

**Issue by MoeXIV** [CitizensDev/Citizens2#2960]
### `/version` output

```txt
This server is running Paper version git-Paper-358 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f26e9cc)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.18.1)
```

### `/version Citizens` output

```txt
[18:21:28 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2836)
[18:21:28 INFO]: Website: https://www.citizensnpcs.co
[18:21:28 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104452

### config.yml

https://paste.denizenscript.com/View/104453

### saves.yml

https://paste.denizenscript.com/View/104454

### Description

After updating our server from 1.18 to 1.19.3, and the accompanying plugins (like Citizens), the nametags NPCs have no longer support hex color codes. I have tried downgrading to the 3 builds below this one and the issue persists.

This applies to both formatting options
- `&#ffff81`
- `§x§f§f§f§f§8§1`

It seems to take the last color from the color code (ie: 1 in this example).

NOTE that holograms work fine still, so will be moving my approach to holograms but felt like I needed to share.

![download (18)](https://user-images.githubusercontent.com/10734348/209447817-1839ec59-1de7-47b8-a1cd-813d7edb832a.png)

**Comment by fullwall** [comment]
Is this better on the new version?

**Comment by MoeXIV** [comment]
Hey, sorry for the delay. Still not working over here on build 2846

**Comment by MoeXIV** [comment]
Confirmed also not working on build 2858

**Comment by fullwall** [comment]
@MoeXIV it is working for me. Perhaps you could post a fresh log and saves.yml?

**Comment by mcmonkey4eva** [comment]
Can you try: `/npc sel` (select the NPC) then `/npc rename &#ff8282[NPC] Nethren` - ie, reapply the name?

**Comment by fullwall** [comment]
Looks like names weren't being parsed on load - should be fixed in the new build.
