### ISSUE TITLE
Name Npc BUG

### ISSUE THREAD

**Issue by BadSr92** [CitizensDev/Citizens2#2961]
### `/version` output

```txt
git-purpur-1876 MC 1.19.3
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT
Build 2845
```

### Log file

https://paste.denizenscript.com/New/Log/I HAVE NOT

### config.yml

https://paste.denizenscript.com/View/104520

### saves.yml

https://paste.denizenscript.com/View/104518

### Description

1: when hiding the name of the npc with /npc name it is hidden but when you enter again it is a bug since the name appears in the normal position if there were no holograms
![Screenshot_20221226-015630](https://user-images.githubusercontent.com/121424617/209525700-fb8f4cc2-354e-4585-8393-46f3acc12b7e.jpg)

2: Any npc's in the world that the player encounters appear in the player's list.
![Screenshot_20221226-020315](https://user-images.githubusercontent.com/121424617/209525723-2cdef57a-767e-4817-80af-98f2d50650a3.jpg)

**Comment by tal5** [comment]
You need to provide all the information requested, consider also asking for support on Discord @ https://discord.gg/Q6pZGSR

**Comment by BadSr92** [comment]
@tal5 I can't ask for support on discord because I don't have it and I won't download it for this only.

**Comment by fullwall** [comment]
@BadSr92 need a server log please

**Comment by BadSr92** [comment]
@fullwall https://mclo.gs/BDH1LhR

**Comment by BadSr92** [comment]
do you need the list of plugins too?

**Comment by mcmonkey4eva** [comment]
You have a forked server (purpur vs paper), your issue relates to bedrock (that's a geyser issue not a citizens issue), and you're using ViaVersion - if you're testing on anything other than Java Minecraft 1.19.3, _that's your problem_

**Comment by BadSr92** [comment]
ok thanks, I'll report it to them then and thank you very much

**Comment by BadSr92** [comment]
One question while we're here, is it also Geyser's mistake that I don't know how to execute the npcs commands with right click?

**Comment by mcmonkey4eva** [comment]
if it only relates to bedrock players then it is a geyser issue
