### ISSUE TITLE
Tablist Disable - Still Adds

### ISSUE THREAD

**Issue by BrandonT80** [CitizensDev/Citizens2#2964]
### `/version` output

```txt
This server is running Paper version git-Paper-362 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 52718db)
You are running the latest version
Previous version: git-Paper-"476ef25" (MC: 1.19.2)
```

### `/version Citizens` output

```txt
Citizens version: 2.0.30-SNAPSHOT (build 2843)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104557

### config.yml

https://paste.denizenscript.com/View/104558

### saves.yml

https://paste.denizenscript.com/View/104559

### Description

Hello!

I have found a bug where even with disabled tablist config setting, citizens still show up in the tablist. Upon checking I have found the issue started on 2.0.30 (BUILD 14 1.19.3) or 2.0.30 (BUILD 13 1.19.3). Below are the commits assiciated with the changes on that date (Dec 18th).

commit 2e3ba07
commit 8d202aa

**Comment by BrandonT80** [comment]
Proper format for #2963

**Comment by fullwall** [comment]
Is this only on geyser clients?

**Comment by BrandonT80** [comment]
> Is this only on geyser clients or ViaVersion clients?

I am on Java, so I was seeing it on java when I made this issue, not sure about bedrock at this time.

**Comment by fullwall** [comment]
I can't reproduce this, can you double check your client version and everything? Easier to troubleshoot on discord too.

**Comment by mercurialmusic** [comment]
FWIW, I'm getting the same tablist thing. All of the NPC faces show in tablist, but not the names. Only seems to happen when traveling to chunks that contain NPCs. Unloading those chunks sometimes removes them from tablist but kinda mixed behavior there. 

[18:45:54 INFO]: =====[ Citizens v2.0.30-SNAPSHOT (build 2856) ]=====
[18:45:54 INFO]:      -- Author: fullwall
[18:45:54 INFO]:      -- Website Support

On git-Paper-365 (MC: 1.19.3) behind git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510

No ViaVersion or anything like that. Clients are unmodified Java Edition 1.19.3. Floodgate is present and Bedrock clients see the same behavior.

**Comment by mcmonkey4eva** [comment]
could potentially be an issue with Waterfall, or floodgate has broken it in such a way that even non-bedrock users get glitched?
Or some other plugin you haven't thought to mention is at fault.
(For reference, the first user we followed up on reports of this with forgot to mention they were ViaVersioning from 1.19.2 clients for quite a while into the debugging process, so I'm sus of anything other than a full log file / plugin list)

**Comment by mercurialmusic** [comment]
I just noticed that fullwall mentioned LibsDisguises in a [discussion](https://discord.com/channels/315163488085475337/1057606913858224199) on Discord, so following up with them. OP also has LIbsDisguises installed so it looks like that might be the common thread.

**Comment by BrandonT80** [comment]
> I just noticed that fullwall mentioned LibsDisguises in a [discussion](https://discord.com/channels/315163488085475337/1057606913858224199) on Discord, so following up with them. OP also has LIbsDisguises installed so it looks like that might be the common thread.

Hello,

I've disabled that plugin already since this issue was created. LibsD is broken to the point where it kicks players for chat. Issue still persists.

**Comment by mercurialmusic** [comment]
Not sure what's happening with OP at least, but for me at least LibsDisguises just pushed an updated (b1152) that fixed the issue for me.

**Comment by BrandonT80** [comment]
> Not sure what's happening with OP at least, but for me at least LibsDisguises just pushed an updated (b1152) that fixed the issue for me.

Can also confirm the issue was fixed for me as well now!

I guess I still had it installed when I last checked the tablist break! Sorry about that.
