### ISSUE TITLE
Add the option for LookClose to work on NPCs not just Players

### ISSUE THREAD

**Issue by Awesome-Sauces** [CitizensDev/Citizens2#2965]
### I confirm that I have ...

- [x] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

I wanted to make a plugin that the NPC targets the Player/NPC it is looking at with the LookClose trait but I can't seem to get it to make an NPC look at an NPC. I even tried editing it to make it allow NPC's LookClose on other NPCs but I couldn't get it to work for 1.8.9.

### Code Example

```java
NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, "Bob");

LookClose lookClose = npc.getTrait(LookClose.class);
lookClose.setTargetNPC(true);

npc.spawn(new Location("world", 0, 0, 0);
```

**Comment by fullwall** [comment]
Added
