### ISSUE TITLE
[1.19.3]NPC disappears if the type is: WANDERING_TRADER once in a while. 

### ISSUE THREAD

**Issue by arturek1666** [CitizensDev/Citizens2#2966]
### `/version` output

```txt
[Tue 19:22:01 INFO] Checking version, please wait...
[Tue 19:22:01 INFO] This server is running Light Spigot.
Unknown version
Previous version: git-Paper-356 (MC: 1.19.3)
```

### `/version Citizens` output

```txt
[Tue 19:21:36 INFO] Citizens version 2.0.30-SNAPSHOT (build 2843)
[Tue 19:21:36 INFO] Website: https://www.citizensnpcs.co/
[Tue 19:21:36 INFO] Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104586

### config.yml

https://gist.github.com/arturek1666/6b6cd720d7d3f56d83354c4f2a8c08b7

### saves.yml

https://gist.github.com/arturek1666/6b6cd720d7d3f56d83354c4f2a8c08b7

### Description

Every time I had try to use the mob type /npc type WANDERING_TRADER, it disappears a lot of times and to fix it I need to do /citizens save and /citizens reload x2 to fix it all the times, the amount of disappearing it's crazy.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
