### ISSUE TITLE
NPC Gamemode change Spectator->Survival = pass through walls and floor

### ISSUE THREAD

**Issue by boiscljo** [CitizensDev/Citizens2#2967]
### `/version` output

```txt
[13:04:04 INFO]: Current: git-Purpur-1876 (MC: 1.19.3)*
Previous: git-Purpur-1762 (MC: 1.19.2)
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### `/version Citizens` output

```txt
[13:04:15 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2855)
[13:04:15 INFO]: Website: https://www.citizensnpcs.co
[13:04:15 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104636

### config.yml

https://paste.denizenscript.com/View/104637

### saves.yml

https://paste.denizenscript.com/View/104638

### Profiler report

https://spark.lucko.me/EVwXzrU1mn

### Description

NPC ignores all blocks after being in spectator mode. Change to spectator mode then return to anything (Survival,Creative, Adventure) and it will just ignore all blocks and just fall through everything.

/npc create B
/npc gamemode spectator
/npc gamemode survival

-> NPC ignores all blocks and just falls infinitely

The bug also happens if the game mode is set via the API(How I found the bug, then tested with the commands and it also happens).

**Comment by fullwall** [comment]
Fixed in new build
