### ISSUE TITLE
[1.19.3 Paper] WANDERING_TRADER disappearing after some time.

### ISSUE THREAD

**Issue by arturek1666** [CitizensDev/Citizens2#2969]
### `/version` output

```txt
> version
[16:16:12 INFO]: Checking version, please wait...
[16:16:13 INFO]: This server is running Paper version git-Paper-358 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f26e9cc)
You are 7 version(s) behind
Download the new version at: https://papermc.io/downloads
```

### `/version Citizens` output

```txt
> version citizens
[16:16:28 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2843)
[16:16:28 INFO]: Website: https://www.citizensnpcs.co
[16:16:28 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104644

### config.yml

https://paste.denizenscript.com/View/104645

### saves.yml

https://paste.denizenscript.com/View/104646

### Description

**INFO:**
Every time I set an NPC as Wandering Trader the NPC will disappear, the only thing I have to do is make an NPC with type is Wandering Trader and just wait after running server for good 2-3 hours the npc will disappear, and the only fix is to do /citizens save and /citizens reload to fix that issue. 

### DISCLAIMER
All this tests were done with server settings:
online-mode=true
Thanks.

**Comment by mcmonkey4eva** [comment]
Account blocked for spamming.

You may appeal this on Discord @ https://discord.gg/Q6pZGSR
