### ISSUE TITLE
Can't use the plugin

### ISSUE THREAD

**Issue by axel37** [CitizensDev/Citizens2#297]
Hi, i'm axel.

I recently bought a serv... bla bla bla.

The plugin look correctly installed : there is a /help and a /plugins menu...

But when i do a command (like /npc create JoeBob), it do... nothing. No error text, no thing, nothing.

So help. Thank you ;-D

**Comment by mcmonkey4eva** [comment]
What does it show in the server console?

**Comment by axel37** [comment]
H--HUH ? wow... errr
This morning i had a big surprise : i said me 'what does it show in the console? Ok, i  will reboot the server, connect and enter a /npc create bobby in the chat for see what does the console say.' 
AND a magic thing appear : IT works.

So, thank you for your help tentative :) but now it works.... sorry, and good bye!
