### ISSUE TITLE
Huge Performance Loss

### ISSUE THREAD

**Issue by daniel-skopek** [CitizensDev/Citizens2#2970]
### `/version` output

```txt
This server is running Pufferfish version git-Pufferfish-47 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 9b8cdc7 on HEAD)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2793)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104760

### config.yml

https://paste.denizenscript.com/View/104761

### saves.yml

https://paste.denizenscript.com/View/104762

### Profiler report

https://spark.lucko.me/ZfYWYeZsT7

### Description

Since the first day of using Citizens, I have encountered problems regarding performance.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
