### ISSUE TITLE
ChatControlRed and Confiscate cant hook into Citizen

### ISSUE THREAD

**Issue by 500gHackfleisch** [CitizensDev/Citizens2#2971]
### `/version` output

```txt
This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2870)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/104883

### config.yml

https://paste.denizenscript.com/View/104884

### saves.yml

there is no

### Description

Hey, I used to run into this issue a few days ago with an older build aswell.
I am just starting to create my server and trying to first install citizen.

First I just saw that ChatControlRed and Confiscate cant hook into Citizen but after reading the latest log, it seems like my minecraft version isnt supported. It should be the latest Paperspigot 1.19.2 version.

I am using bungeecord, so dont worry why the server is in offline mode, my proxy is in online mode as it should.

If you have anything else for me or need more information, just hit me up, I am trying to build a server network which 100% EULA conform.

btw I censored the ip adress, port and some other stuff in the latest log which should not influence the troubleshooting for privacy reasons cause I am not familiar with github and your pastebin site and dont know who might read it aswell...

**Comment by mcmonkey4eva** [comment]
You need to update update to 1.19.3, or use a 1.19.2 compatible version of Citizens (  https://ci.citizensnpcs.co/job/Citizens2/2793/ )

note that the above link was copied out of the `#news` channel on Discord @ <https://discord.gg/Q6pZGSR>
