### ISSUE TITLE
Right-clicking on a command does not trigger when executing a [text] command to npc.

### ISSUE THREAD

**Issue by ookami0104** [CitizensDev/Citizens2#2972]
### `/version` output

```txt
This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT
```

### Log file

https://paste.denizenscript.com/View/104946

### config.yml

https://paste.denizenscript.com/View/104943

### saves.yml

https://paste.denizenscript.com/View/104944

### Description

After executing the [text] command to npc and setting npc to talk, the command that was set to npc does not fire.

I am Japanese and use a translator.
Sorry if my writing is not correct.

**Comment by fullwall** [comment]
Update to the latest version of Citizens. You did not post what version of Citizens you are using.

**Comment by ookami0104** [comment]
> Citizens の最新バージョンに更新します。使用している Citizens のバージョンを投稿していません。

Thank you very much.
It worked fine when I brought it up to date successfully.
