### ISSUE TITLE
Citizens don't work

### ISSUE THREAD

**Issue by pawelkuwa** [CitizensDev/Citizens2#2975]
### `/version` output

```txt
This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-123 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2890)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/105164

### config.yml

https://paste.denizenscript.com/View/105165

### saves.yml

https://paste.denizenscript.com/View/105165

### Description

![image](https://user-images.githubusercontent.com/83598982/211350545-1026ed30-ce03-452a-b0c8-db0867420ce1.png)

and https://paste.denizenscript.com/View/105164

**Comment by mcmonkey4eva** [comment]
You need 1.19.3
