### ISSUE TITLE
Collision problem, delay update impact server

### ISSUE THREAD

**Issue by wryel2000** [CitizensDev/Citizens2#2977]
### `/version` output

```txt
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT build 2673
```

### Log file

https://paste.denizenscript.com/View/105457

### config.yml

https://paste.denizenscript.com/View/105456

### saves.yml

https://paste.denizenscript.com/View/105455

### Profiler report

https://spark.lucko.me/Y6lajq7g7q

### Description

Hello everyone, I'm here again for the efficiency of the basic opinions and suggestions that you always give me

now, i have a littl problem to Thread do Plugin (Citizens2)

About problem:
 
Player NPC and NPC Armorstands generate delay on CollisionsForBlocksOrWorldBorder lines or moveWithFallDamage ( FrictionAndCalculateMovement and more :// 
![Captura de tela 2023-01-17 084215](https://user-images.githubusercontent.com/101683845/212920955-322e9616-6ba7-44f2-80ad-0338b53095a6.png)
![Captura de tela 2023-01-17 084437](https://user-images.githubusercontent.com/101683845/212920963-5e04a523-3f49-4f71-a89f-954b0fa2fd03.png)

**Comment by RealMCSamuel** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by wryel2000** [comment]
> https://wiki.citizensnpcs.co/Cracks

ok, I'm going to use a maximum of 20 npcs instead of using different mechanics in 1000 different npcs, I believe I can help, right?

Currently I use some mechanics like cooldown, kit, missions. I'm switching to plugins like Mycommand or similar to perform the functions instead of Citizens.

**Comment by RealMCSamuel** [comment]
Update your server's uuid version, remove the LoginSecurity and SkinsRestorer plugins, and join the discord for further support.

**Comment by mcmonkey4eva** [comment]
You are refused support currently due to running a cracked server, as is explained in the link.
Join the Discord @ https://discord.gg/Q6pZGSR if you'd like to dispute this.
