### ISSUE TITLE
Bypass God Mode - Sentries

### ISSUE THREAD

**Issue by mcMMO** [CitizensDev/Citizens2#298]
Normal sentries can bypass god mode supplied by essentials or other plugins.

Version: Latest release to date.

**Comment by mcmonkey4eva** [comment]
Option 1: Don't use normal Sentry, use dSentry or something else instead.
Option 2: Report this to the nonexistent Sentry team: https://github.com/jrbudda/Sentry/issues

**Comment by mcMMO** [comment]
@mcmonkey4eva Should I replace the trait Sentry to dSentry? Is this a Denizen Sentry? Where can all traits be found?

**Comment by AnthonyAMC** [comment]
dSentry is a denizen script to replace Sentry. It isn't a Citizens trait as such.

**Comment by mcMMO** [comment]
I can't find anything under Denizen Sentries on http://wiki.citizensnpcs.co/Sentry/Sentry_and_Denizen#Criminal_System

**Comment by mcmonkey4eva** [comment]
You should be looking on the Denizen pages, not Sentry.
http://mcmonkey.org/denizen/repo/entry/0

**Comment by mcmonkey4eva** [comment]
Oh and be aware that it's not 100% functional, it's a work in progress. However, more people using it = more people pushing for certain features to be added = more progress getting done!
