### ISSUE TITLE
TAB LIST BUG

### ISSUE THREAD

**Issue by wlm1455925277** [CitizensDev/Citizens2#2982]
### `/version` output

```txt
> version
[14:44:41 INFO]: Checking version, please wait...
[14:44:42 INFO]: Current: git-Purpur-1894 (MC: 1.19.3)*
Previous: git-KeYi-main/1.19.3-22a9d75 (MC: 1.19.3)
* You are 11 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### `/version Citizens` output

```txt
> version Citizens
[14:45:43 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2895)
[14:45:43 INFO]: Website: https://www.citizensnpcs.co
[14:45:43 INFO]: Author: fullwall
```

### Log file

https://mclo.gs/si864na

### config.yml

https://mclo.gs/CqtwNQc

### saves.yml

https://mclo.gs/Xki3tUy

### Description

The npc will always stay on the tablist in version 1.19.3, and it will not disappear immediately!
My game version is 1.19.2. If I use version 1.19.3, it won't appear! The server is version 1.19.3! Use 1.19.2 and it will always appear!
![$RRZ3COO](https://user-images.githubusercontent.com/87473483/214774648-e0f76700-8aec-41d9-bcf9-44aebce5fa8d.png)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
