### ISSUE TITLE
NPCs in boats can only pathfind in 1-block-deep water

### ISSUE THREAD

**Issue by repeater64** [CitizensDev/Citizens2#2984]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Currently, an NPC riding a controllable NPC boat can pathfind very nicely, but only through 1-block-deep water.

If it tries to pathfind to a location in deeper water, it instantly fails.
If it tries to pathfind to a location in 1-block-deep water but it itself is in deeper water, it just sort of spins in circles.

Ideally the behavior that is seen in 1-block-deep water would be seen in deeper water too.

**Comment by fullwall** [comment]
Tracking here https://github.com/CitizensDev/Citizens2/issues/2993
