### ISSUE TITLE
Citizens2 latest isn't 1.19.2 compatible?

### ISSUE THREAD

**Issue by Mentrixx** [CitizensDev/Citizens2#2985]
01.02 09:50:14 [Server] [ERROR] [Citizens] v2.0.30-SNAPSHOT (build 2898) is not compatible with Minecraft v1_19_R1 - try upgrading Minecraft or Citizens. Disabling...

Not sure what exactly is happening?

01.02 09:50:14 [Server] [ERROR] [Citizens] v2.0.30-SNAPSHOT (build 2898) is not compatible with Minecraft v1_19_R1 - try upgrading Minecraft or Citizens. Disabling...
01.02 09:50:14 [Server] [INFO] [Citizens] Disabling Citizens v2.0.30-SNAPSHOT (build 2898)
01.02 09:50:14 [Server] [ERROR] Could not pass event PluginEnableEvent to ItemsAdder v3.2.3i
01.02 09:50:14 [Server] [INFO] java.lang.NoClassDefFoundError: net/citizensnpcs/api/trait/Trait
01.02 09:50:14 [Server] [INFO] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
01.02 09:50:14 [Server] [INFO] at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
01.02 09:50:14 [Server] [INFO] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:223) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
01.02 09:50:14 [Server] [INFO] at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CitizensHook.register(SourceFile:36) ~[ItemsAdder_3.2.3i.jar:?]
01.02 09:50:14 [Server] [INFO] at dev.lone.itemsadder.Main.b(SourceFile:705) ~[ItemsAdder_3.2.3i.jar:?]
01.02 09:50:14 [Server] [INFO] at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX.jar:?]
01.02 09:50:14 [Server] [INFO] at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX.jar:?]
01.02 09:50:14 [Server] [INFO] at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
01.02 09:50:14 [Server] [INFO] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
01.02 09:50:14 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]
01.02 09:50:14 [Server] [INFO] Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.trait.Trait
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
01.02 09:50:14 [Server] [INFO] at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
01.02 09:50:14 [Server] [INFO] ... 43 more

**Comment by mcmonkey4eva** [comment]
Update to 1.19.3
