### ISSUE TITLE
was told to report this after attempting /npc panimate EAT_FOOD

### ISSUE THREAD

**Issue by Joeychuwu** [CitizensDev/Citizens2#2990]
### `/version` output

```txt
This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-376 (MC: 1.19.3)
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2888)
```

### Log file

https://paste.denizenscript.com/View/106103

### config.yml

https://paste.denizenscript.com/View/106104

### saves.yml

https://paste.denizenscript.com/View/106105

### Description

npc is sitting and when i tried to run/npc panimate EAT_FOOD it said 
please report this error [see console]
java.lang.UnsupportedOperationException: null
so im doing that now x3

10.02 03:50:50 [Server] INFO Joeychu issued server command: /npc panimate EAT_FOOD
10.02 03:50:51 [Server] WARN java.lang.UnsupportedOperationException
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R2.util.PlayerAnimationImpl.play(PlayerAnimationImpl.java:52)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.nms.v1_19_R2.util.NMSImpl.playAnimation(NMSImpl.java:1237)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.util.NMS.playAnimation(NMS.java:497)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.util.PlayerAnimation.play(PlayerAnimation.java:96)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.commands.NPCCommands.playerAnimate(NPCCommands.java:1934)
10.02 03:50:51 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.02 03:50:51 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10.02 03:50:51 [Server] WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.02 03:50:51 [Server] WARN at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
10.02 03:50:51 [Server] WARN at Citizens.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:366)
10.02 03:50:51 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
10.02 03:50:51 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
10.02 03:50:51 [Server] WARN at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929)
10.02 03:50:51 [Server] WARN at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
10.02 03:50:51 [Server] WARN at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
10.02 03:50:51 [Server] WARN at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:313)
10.02 03:50:51 [Server] WARN at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:297)
10.02 03:50:51 [Server] WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
10.02 03:50:51 [Server] WARN at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
10.02 03:50:51 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
10.02 03:50:51 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
10.02 03:50:51 [Server] WARN at net.minecraft.server.TickTask.run(TickTask.java:18)
10.02 03:50:51 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
10.02 03:50:51 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
10.02 03:50:51 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
10.02 03:50:51 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
10.02 03:50:51 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
10.02 03:50:51 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by fullwall** [comment]
I think it's START_USING_MAINHAND_ITEM now
