### ISSUE TITLE
ability to use any command without having to select an NPC

### ISSUE THREAD

**Issue by NickyTheCat** [CitizensDev/Citizens2#2998]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

some commands you can run without selecting an NPC, others you cant which is really annoying. Please add a parameter for ID like some of the commands have

**Comment by mcmonkey4eva** [comment]
`--id #` is available in all commands

**Comment by NickyTheCat** [comment]
Understood. Sorry to be a bother but thank  you for your reply.
