### ISSUE TITLE
Error Entity 

### ISSUE THREAD

**Issue by Comandante99** [CitizensDev/Citizens2#300]
When i try to create a player npc the server crash with this error
Logs:
http://pastebin.com/8kSQCMfz

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens. http://wiki.citizensnpcs.co/Versions

**Comment by Comandante99** [comment]
Which one should i use? I'm running spigot on 1.7.10 to 1.8

**Comment by mcmonkey4eva** [comment]
The one that says it's for the 1.8 protocol hack.
