### ISSUE TITLE
NPC Shop setname and setdescription not working

### ISSUE THREAD

**Issue by StepGaming** [CitizensDev/Citizens2#3000]
### `/version` output

```txt
This server is running Paper version git-Paper-442 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 5cc78f2)
You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-409 (MC: 1.19.3)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2888)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/107355

### config.yml

https://paste.denizenscript.com/View/107356

### saves.yml

https://paste.denizenscript.com/View/107357

### Description

Unfortunately, I am unable to add new items to the integrated store GUI. After clicking "Save", the item does not appear in the store, and even after restarting the server, the issue persists.

**Comment by fullwall** [comment]
Unable to reproduce
