### ISSUE TITLE
Can't find TEXT_DISPLAY entity type on 1.16.5

### ISSUE THREAD

**Issue by exzolink** [CitizensDev/Citizens2#3002]
### `/version` output

```txt
Airplane version git-Airplane-11 (MC: 1.16.5) §bKibble 1.7.1* (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
build 2976
```

### Log file

fresh start

### config.yml

default

### saves.yml

default

### Description

https://paste.denizenscript.com/View/107406
Even if NPCs doesnt have holograms

**Comment by fullwall** [comment]
Fixed
