### ISSUE TITLE
Can't create NPC's "That is not a valid number"

### ISSUE THREAD

**Issue by TheCommander64** [CitizensDev/Citizens2#3005]
### `/version` output

```txt
This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2888)
```

### Log file

https://paste.denizenscript.com/View/107838

### config.yml

https://paste.denizenscript.com/View/107839

### saves.yml

Empty File

### Description

When attempting to use /npc2 spawn <Name> it gives the error "That is not a valid number"
![image](https://user-images.githubusercontent.com/84328331/227727579-42ba9de4-62df-4d1c-aa36-efbfcef66594.png)

**Comment by mcmonkey4eva** [comment]
- You should google for tutorials on how to get started using Citizens
- `/npc create bob` is the most basic creating an NPC command

**Comment by TheCommander64** [comment]
I've tried the basic create command, it does not work
It only ever shows  "That is not a valid number"

**Comment by TheCommander64** [comment]
I've used Citizens several times over the past couple years, I know how to use the commands. The problem is that the plugin clearly has a bug because nowhere in the command am I using a number

**Comment by TheCommander64** [comment]
@mcmonkey4eva So if you could actually help me with my issue, that would be appreciated, otherwise I'd like this issue to be reopened as I am still having the bug

**Comment by mcmonkey4eva** [comment]
- `npc2` is not meant to be used
- `spawn` is not how you create an NPC.
- Join https://discord.gg/Q6pZGSR  for support
