### ISSUE TITLE
Error with latest ProtocolLib build (#621)

### ISSUE THREAD

**Issue by NoltoxGit** [CitizensDev/Citizens2#3006]
### `/version` output

```txt
Current: git-Purpur-1947 (MC: 1.19.4)*
Previous: git-Purpur-1946 (MC: 1.19.4)
* You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNAPSHOT (build 2994)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/107879

### config.yml

https://paste.denizenscript.com/View/107877

### saves.yml

https://paste.denizenscript.com/View/107878

### Description

With the latest version of Citizens & ProtcolLib, citizens have an issue for enable support with ProtocolLib here : https://paste.denizenscript.com/View/107879#487.

**Comment by NoltoxGit** [comment]
- The previous build ([#620](https://ci.dmulloy2.net/job/ProtocolLib/620/)) it works properly though!

**Comment by mcmonkey4eva** [comment]
This looks to be a ProtocolLib issue
