### ISSUE TITLE
[10:43:19 ERROR] [Minecraft]: [Citizens] v2.0.31-SNAPSHOT (build 3013) is not compatible with Minecraft v1_19_R1 - try upgrading Minecraft or Citizens. Disabling...

### ISSUE THREAD

**Issue by ysefwakil** [CitizensDev/Citizens2#3007]
### `/version` output

```txt
arclight-1.19.2-1.01-0550c6cd (MC1.19.2)
```

### `/version Citizens` output

```txt
2.0.31-snapshot(build 3013)
```

### Log file

https://paste.denizenscript.com/View/108185

### config.yml

null

### saves.yml

null

### Description

Is citizens compatible with arclight 1.19.2

**Comment by mcmonkey4eva** [comment]
latest citizens is compatible with Spigot and Paper 1.19.4. Older patchversions are not supported, forge-integrating forks aren't either.
