### ISSUE TITLE
Server overload

### ISSUE THREAD

**Issue by Vitoldik** [CitizensDev/Citizens2#3008]
### `/version` output

```txt
This server is running Paper version git-Paper-657 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Previous version: git-Paper-656 (MC: 1.13.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNNAPSHOT (build 2989)
```

### Log file

Can't provide

### config.yml

https://paste.denizenscript.com/View/108223

### saves.yml

Can't provide

### Profiler report

https://spark.lucko.me/UOgWWmWeIQ

### Description

After upgrading from the old version, there was a high load

**Comment by mcmonkey4eva** [comment]
Ask on Discord @  https://discord.gg/Q6pZGSR  in the #citizens channel
