### ISSUE TITLE
NPC Entity Collision Error

### ISSUE THREAD

**Issue by KhrysAK47** [CitizensDev/Citizens2#3009]
### `/version` output

```txt
This server is running Paper version git-Paper-431 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e574412)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2897)
```

### Log file

https://paste.denizenscript.com/View/108253

### config.yml

https://paste.denizenscript.com/View/108251

### saves.yml

https://paste.denizenscript.com/View/108252

### Description

When an NPC is unprotected (made vulnerable), the collision gets overwritten and players can push them. Even if tweaking the collision externally from paper.yml, and other plugins.

**Comment by fullwall** [comment]
Why is this a bug? Use /npc collidable or metadata you should be able to prevent collision again.

**Comment by KhrysAK47** [comment]
> Why is this a bug? Use /npc collidable or metadata you should be able to prevent collision again.
Hey. That's the thing, after doing that it is still a collidable entity.

**Comment by fullwall** [comment]
I can't reproduce this on the latest build. I need more info or logs or video or something.
