### ISSUE TITLE
Cannot create a sentry.

### ISSUE THREAD

**Issue by axel37** [CitizensDev/Citizens2#301]
Here is the error log : 

>
> [11:55:20 WARN]: ... 28 more
> [11:55:20 WARN]: at java.lang.ClassLoader.loadClass(Unknown Source)
> [11:55:20 WARN]: at java.lang.ClassLoader.loadClass(Unknown Source)
> [11:55:20 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
> [11:55:20 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
> [11:55:20 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R2.Packet
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:817)
> [11:55:20 WARN]: at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:955)
> [11:55:20 WARN]: at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:703)
> [11:55:20 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
> [11:55:20 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [11:55:20 WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
> [11:55:20 WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
> [11:55:20 WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
> [11:55:20 WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
> [11:55:20 WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
> [11:55:20 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [11:55:20 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> [11:55:20 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [11:55:20 WARN]: at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
> [11:55:20 WARN]: at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
> [11:55:20 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:90)
> [11:55:20 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:111)
> [11:55:20 WARN]: at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
> [11:55:20 WARN]: at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
> [11:55:20 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R2/Packet
> [11:55:20 INFO]: Axel3_7 issued server command: /trait sentry

**Comment by mcmonkey4eva** [comment]
Wrong version of Sentry. Get the correct one here: http://wiki.citizensnpcs.co/Sentry#Updates

**Comment by axel37** [comment]
Now it works ! thx
