### ISSUE TITLE
[BUG] NPC#destroy API bug

### ISSUE THREAD

**Issue by Kr1S-D** [CitizensDev/Citizens2#3011]
### `/version` output

```txt
1.12.2 paperspigot
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT (build 2888)
```

### Log file

//

### config.yml

https://paste.denizenscript.com/View/108805

### saves.yml

https://paste.denizenscript.com/View/108806

### Profiler report

https://spark.lucko.me/VxuV6MiDMd

### Description

Ok, I found two bugs, the first one, npc with /npc teleport randomly bug and I have to restart the server.
The second, working with the npc plugin I have a plugin called RubyAutominer, this plugin takes care of creating npc that dig inside a mine, however when a player does /am despawn all the autominers in use are despawned, when this happens , the npc entity is removed while in the /npc list it remains due to lag with a task called PlayerUpdateTask, I used the NPC#destroy method to remove the npc

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
