### ISSUE TITLE
problem when the server starts with citizens

### ISSUE THREAD

**Issue by lechatdeschat** [CitizensDev/Citizens2#3012]
### `/version` output

```txt
This server is running Pufferfish version git-Pufferfish-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 42ef3dc on HEAD)
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNAPSHOT (build 3031)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/108824

### config.yml

https://paste.denizenscript.com/View/108825

### saves.yml

https://paste.denizenscript.com/View/108826

### Profiler report

https://spark.lucko.me/zmxBIoeQbu

### Description

problem when the server starts with citizens. I can't place npc and when I want to do /pl the plugins and in red and when I do /npc create test, the server gives me a critical error.

sorry i am french and i use google translate

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
