### ISSUE TITLE
Packet Trait does not work with non-player entities

### ISSUE THREAD

**Issue by fan87** [CitizensDev/Citizens2#3014]
### `/version` output

```txt
[13:22:36 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:22:36 INFO]: You are 52 version(s) behind
```

### `/version Citizens` output

```txt
[13:22:52 INFO]: Citizens version 2.0.31-SNAPSHOT (build 3030)
[13:22:52 INFO]: Website: https://www.citizensnpcs.co
[13:22:52 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/108985

### config.yml

https://paste.denizenscript.com/View/108986

### saves.yml

https://paste.denizenscript.com/View/108987

### Description

Packet trait not working with non-player entities.
(in this case, Armour Stand)

I've did some debugging with MCP (Minecraft Client-side),

```
Armor stand spawned!
Armor stand spawned!
Armor stand spawned!
Entity Remvoed: EntityArmorStand['OkOk'/17853, l='MpServer', x=6.47, y=1.00, z=10.44]
```

(I've tried `/npc move` and it doesn't log `S14PacketEntity` or `S18PacketEntityTeleport`)

Not sure if it's work as intended, it works on Player NPC tho, sorta, only one player Packet NPC can be spawned at the time, if I try to spawn another Player Packet NPC it just doesn't work.

**Comment by fan87** [comment]
Just tested it with the latest build (`b3037`), doesn't work as well

**Comment by fullwall** [comment]
Unfortunately, we aren't able to support cracked minecraft servers.

**Comment by fan87** [comment]
Uh just turned online mode on, the issue is still there
