### ISSUE TITLE
Add option to hide NPC nameplates behind walls

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#3017]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Like you can see in the pictures its possible for Shopkeepers
but for NPC citicenz it seems not possile to do this. their names are view able milesaway

![Snag_b3b89b](https://user-images.githubusercontent.com/12080017/235193632-d8bf1b7a-230f-4a18-9163-30c6c676851c.png)

In Secound Picture i removed the Block between the Shopkeeper an me to show is shown when the is no block btween you and him
![Snag_b48a43](https://user-images.githubusercontent.com/12080017/235193811-cab5475a-ed8e-4438-9706-d5fc57706a05.png)

![Snag_b56b0d](https://user-images.githubusercontent.com/12080017/235194003-a6f34a4b-42f7-4eb0-87af-db0bb3912cff.png)
An in the last picture you see what might most of us felt into.. the names apear over walls and you can view them from far far away throu blocks too

i saw many things on good where player talked about sneaks and co when the player is not viewing the npc
well this seem to not work with citicenz itself

So please add something maybe a command option for the /npc nameplate command so that we can
hide npcs name throu walls if wanted..

**Comment by CloudeLecaw** [comment]
Today i learned that his is callaed - Dynamic Nametag Detection

![image](https://user-images.githubusercontent.com/12080017/235288547-d4501ef9-4214-4383-9cdb-b27dd62a5df7.png)

**Comment by fullwall** [comment]
Duplicate request.
This is possible within Denizen scripts however - I recommend joining the discord and getting started with that.

**Comment by CloudeLecaw** [comment]
but i want it for Citizens not for an other plugin or a Script or anything....
