### ISSUE TITLE
Please fix this!

### ISSUE THREAD

**Issue by hipn0z** [CitizensDev/Citizens2#302]
When I try to create an npc it says,
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/packet
What do I do?

**Comment by XxCoolGamesxX** [comment]
What version(s) are you running? (Spigot version? Citizens version?)

**Comment by mcmonkey4eva** [comment]
He's definitely running the /wrong/ version. Get the correct one(s) here: http://wiki.citizensnpcs.co/Versions
