### ISSUE TITLE
NPC Shop doesn't working on 1.12.2&below

### ISSUE THREAD

**Issue by HowardZHY** [CitizensDev/Citizens2#3021]
### `/version` output

```txt
This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNAPSHOT (build 3096)
```

### Log file

https://paste.denizenscript.com/View/110199

### config.yml

https://paste.denizenscript.com/View/110200

### saves.yml

https://paste.denizenscript.com/View/110201

### Description

<img width="205" alt="image" src="https://github.com/CitizensDev/Citizens2/assets/96782166/5644e849-ffcc-407a-a6cd-668f89d337ff">
1.12.2 and below's shop are broken because serveral 1.13+ stuffs 're used. 

https://github.com/CitizensDev/Citizens2/blob/ee77512185fcc7f4e1d14229a356f7304135a839/main/src/main/java/net/citizensnpcs/trait/shop/ItemAction.java#L62
as I know, org.bukkit.inventory.meta.Damageable doesn't exist in paper 1.12.2

**Comment by mcmonkey4eva** [comment]
Why not... just update?

**Comment by fullwall** [comment]
Fixed
