### ISSUE TITLE
PLAYER npc do not spawn mobs

### ISSUE THREAD

**Issue by sebseb7** [CitizensDev/Citizens2#3022]
### `/version` output

```txt
This server is running Paper version git-Paper-540 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f9f9079)
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNAPSHOT (build 3097)
```

### Log file

https://paste.denizenscript.com/View/110311

### config.yml

https://paste.denizenscript.com/View/110312

### saves.yml

https://paste.denizenscript.com/View/110313

### Description

NPC is set to "playerlist" and "chunkload". 

I placed the npc in the afk spot of a common mob farm (creepers, spiders, skeletons,zombies) but no mobs do spawn soon the real player is switched to spectator mode

**Comment by fullwall** [comment]
Tracking on discord
