### ISSUE TITLE
command feom console 

### ISSUE THREAD

**Issue by TymekSL** [CitizensDev/Citizens2#3023]
### `/version` output

```txt
1.19.2 paperspigot
```

### `/version Citizens` output

```txt
2.0.31
```

### Log file

https://paste.denizenscript.com/View/110318

### config.yml

https://paste.denizenscript.com/View/110318

### saves.yml

https://paste.denizenscript.com/View/110318

### Profiler report

?

### Description

when trying to write /npc trough conso,e

**Comment by mcmonkey4eva** [comment]
Update to 1.19.4

If you need help ask on Discord @ https://discord.gg/Q6pZGSR

**Comment by TymekSL** [comment]
> Update to 1.19.4
> 
> If you need help ask on Discord @ https://discord.gg/Q6pZGSR
wtf using latest version lmao
