### ISSUE TITLE
API NPC Data return null

### ISSUE THREAD

**Issue by thelipe7** [CitizensDev/Citizens2#3024]
### `/version` output

```txt
Paper-538 (MC: 1.19.4)
```

### `/version Citizens` output

```txt
2.0.31-SNAPSHOT
```

### Log file

Unnecessary

### config.yml

Unnecessary

### saves.yml

Unnecessary

### Profiler report

Unnecessary

### Description

I am using the citizens API to create an NPC and I am defining a metadata called "server" where I store some information, however when I try to retrieve this value by the API and identify that I am clicking on the correct NPC, the returned value is empty, I thought it could be some error of mine however this was working perfectly before, I entered the server, selected the NPC and typed /npc metadata get server and the value that I define is returned correctly, this is a bug that happens only when I try specifically by the API.

My code:
![image](https://github.com/CitizensDev/Citizens2/assets/101154133/0be203c6-5fe7-4832-96b8-b8915576b48f)
![image](https://github.com/CitizensDev/Citizens2/assets/101154133/43bccc10-408c-4d7a-b8eb-51167490310b)

I ran some debugs and the code doesn't go past npc.data().has("server"), I tried to use the method get("server") != null and the same happened, as I said in-game when I check by the citizens command it returns everything correctly.

**Comment by mcmonkey4eva** [comment]
use `setPersistent` rather than `set`, but also don't use metadata for your own data, use traits - https://wiki.citizensnpcs.co/API
