### ISSUE TITLE
Citizens cause lag

### ISSUE THREAD

**Issue by lucaro2708** [CitizensDev/Citizens2#303]
I'm experiencing massive lag on my hub because of citizens, i tried to remove every single plugin and the problem was npcs. Any suggestion to fix this problem?

**Comment by mcmonkey4eva** [comment]
Are you sure it was Citizens NPCs, not a sub plugin (such as Sentry NPCs)?

**Comment by Talamar1** [comment]
What version of bukkit/spigot?  What version of Citizens?  Have you run /timings on and /timings paste and what are the results?

**Comment by lucaro2708** [comment]
I have spigot that works from 1.7 to 1.8 and the protocol hack version of Citizen and i have only "vanilla" Citizen no sub plugins. http://goo.gl/W7RGcw This is with citizen (4 Npcs on the map).

**Comment by mcmonkey4eva** [comment]
Citizens is not even on that timings.

**Comment by lucaro2708** [comment]
When i unload the plugin it doesn't lag, i don't know what to say, look at the entities.
