### ISSUE TITLE
ModelEngine + Citizens when npc got model from modelengine this is dont work currectly

### ISSUE THREAD

**Issue by YOKKUU** [CitizensDev/Citizens2#3032]
### `/version` output

```txt
3498-Spigot-b081915-10ba1be (MC1.18.2) (Api version R0.1 Snapshot)
```

### `/version Citizens` output

```txt
2.0.30
```

### Log file

https://paste.denizenscript.com/View/111417

### config.yml

https://paste.denizenscript.com/View/111418

### saves.yml

https://paste.denizenscript.com/View/111419

### Description

Hello!
When im trying create NPC and add trait model thats got clonned by original type entity,
Video: 
`https://youtu.be/yeCV_tP7lLw`

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
