### ISSUE TITLE
The "/npc path" command caused the server to crash.

### ISSUE THREAD

**Issue by 615303619** [CitizensDev/Citizens2#3036]
### `/version` output

```txt
This server is running CatServer version 1.16.5-1d8d6313 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
```

### `/version Citizens` output

```txt
Citizens version 2.0.32-SNAPSHOT (build 3163)
```

### Log file

https://paste.denizenscript.com/View/112197

### config.yml

https://paste.denizenscript.com/View/112198

### saves.yml

https://paste.denizenscript.com/View/112199

### Description

After creating the NPC, I attempted to use the "/npc path" command to set the NPC's position. However, the server crashed when the NPC started pathfinding.

Steps to reproduce:

Use the command "/npc create [name]" to create an NPC.
Use the "/npc path" command to set the NPC's position to a specific location.
If the NPC is not pathfinding, use "/npc tphere" to move the NPC to another location.
Subsequently, the server crashes.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
