### ISSUE TITLE
Citizens have all been lost

### ISSUE THREAD

**Issue by aml2023529** [CitizensDev/Citizens2#3038]
### `/version` output

```txt
> version
[12:38:45 INFO]: Checking version, please wait...
[12:38:47 INFO]: This server is running Paper version git-Paper-97 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 1837f6c)
You are running the latest version
Previous version: git-Paper-96 (MC: 1.20.1)
>
```

### `/version Citizens` output

```txt
> version Citizens
[12:38:29 INFO]: Citizens version 2.0.32-SNAPSHOT (build 3171)
[12:38:29 INFO]: Website: https://www.citizensnpcs.co
[12:38:29 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/112841

### config.yml

https://paste.denizenscript.com/View/112840

### saves.yml

https://paste.denizenscript.com/View/112842

### Description

Updated Citizen all my citizens are missing.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by aml2023529** [comment]
> https://wiki.citizensnpcs.co/Cracks

I'm not sure what that means do you mean I don't have a legitimate account to access the server? But I'm using a legit account to access the server when my server doesn't have authentication turned on is that why you're saying that I'm messing up the translation I can only make out the general meaning of what you're posting!
