### ISSUE TITLE
[Server thread/ERROR]: [Citizens] Unhandled exception occurred in onPacketSending(PacketEvent) for Citizens

### ISSUE THREAD

**Issue by YodaZen** [CitizensDev/Citizens2#3039]
### `/version` output

```txt
CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Impementing API version 1.8.8-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens Version: 2.0.32-SNAPSHOT (build 3156)
ProtocolLib: 5.0.0
```

### Log file

https://paste.denizenscript.com/View/113075

### config.yml

https://paste.denizenscript.com/View/113076

### saves.yml

https://paste.denizenscript.com/View/113077

### Description

Restarting the server, it throws a lot of these errors, and i suspect the problem is with protocolLib.

**Comment by fullwall** [comment]
Fixed in newer build
