### ISSUE TITLE
RGB Color Name 

### ISSUE THREAD

**Issue by Leviih01** [CitizensDev/Citizens2#3040]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [x] ...checked other existing issues for my feature request.

### Description

Welcome to the developer(s).
I would like to request that the NPC name be synced with RGB HAX code as shown below

### Code Example

```java
&#4f811fG&#587e21u&#617b23n &#737627M&#7c7329a&#85712bs&#8e6e2dt&#976b2fe&#9f6930r
```

**Comment by mcmonkey4eva** [comment]
RGB Hex codes already work in NPC names.

**Comment by Leviih01** [comment]
really? 1.20 is not display the name with HEX code.

**Comment by mcmonkey4eva** [comment]
I loaded up latest Citizens dev build on Paper 1.20.1 and created an NPC with the name you gave:

![image](https://github.com/CitizensDev/Citizens2/assets/4000772/76193815-6354-4fa8-a6c1-79773ff6c690)


Works fine.
