### ISSUE TITLE
citizens throws a bunch of errors in console when a player gets close because of lookclose

### ISSUE THREAD

**Issue by Zoometryfr** [CitizensDev/Citizens2#3041]
### `/version` output

```txt
[01:26:00 INFO]: This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
```

### `/version Citizens` output

```txt
[01:26:19 INFO]: Citizens version 2.0.32-SNAPSHOT (build 3167)
[01:26:19 INFO]: Website: https://www.citizensnpcs.co
[01:26:19 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/113411

### config.yml

https://paste.denizenscript.com/View/113412

### saves.yml

https://paste.denizenscript.com/View/113413

### Description

server console throws errors when someone is close to an npc with lookclose enabled;

[Citizens] OVERWRITTEN ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=104] net.minecraft.network.protocol.game.PacketPlayOutEntityTeleport@69361cb4

**Comment by mcmonkey4eva** [comment]
Looks like accidentally left in debug https://github.com/CitizensDev/Citizens2/blob/6fd768992acb8b3ce7ff12d48cd40beec607b95b/main/src/main/java/net/citizensnpcs/ProtocolLibListener.java#L219

**Comment by Zoometryfr** [comment]
i shall try that

**Comment by Zoometryfr** [comment]
where can i find that file?

**Comment by mcmonkey4eva** [comment]
Oops, my mistake, I have been informed that is in fact a proper `.debug` and not an always-on debugging message - just disable debugging messages in your `Citizens/config.yml` to hide that

```yml
  # Enable Citizens debugging
  debug-mode: false
```

**Comment by Zoometryfr** [comment]
alright thank you, will try

**Comment by Zoometryfr** [comment]
in my config file debug mode is already set to false

**Comment by mcmonkey4eva** [comment]
Make sure to update to latest build https://ci.citizensnpcs.co/job/Citizens2/
