### ISSUE TITLE
Packet NPC BUG

### ISSUE THREAD

**Issue by SladeHazard** [CitizensDev/Citizens2#3042]
### `/version` output

```txt
[05:30:11 INFO]: This server is running Paper version git-Paper-2116373 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
[05:29:37 INFO]: Citizens version 2.0.32-SNAPSHOT (build b3188)
```

### Log file

https://paste.denizenscript.com/View/114012

### config.yml

https://paste.denizenscript.com/View/114016

### saves.yml

https://paste.denizenscript.com/View/114015

### Description

on 1.12.2 server the packet npcs never work, I've tried with fresh configs, fresh server with no other plugins other than dependencies. Once you make an npc packet, it just becomes invisible completely and never shows up again even if you restart.

Also this is the latest build compiled for 1.12.2, i've also tested the old builds the packet command never works for 1.12.2.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by SladeHazard** [comment]
I'm not using a cracked version of minecraft??? it's connected to a velocity proxy hence why it's in offline mode. and the test server that I tested it on was completely online

**Comment by SladeHazard** [comment]
@mcmonkey4eva ^
