### ISSUE TITLE
The /npc2 name command does not work

### ISSUE THREAD

**Issue by f1ttJK** [CitizensDev/Citizens2#3043]
### `/version` output

```txt
PurPur-1985 (MC: 1.19.4)
```

### `/version Citizens` output

```txt
2.0.32-SNAPSHOT (build 3135)
```

### Log file

-

### config.yml

-

### saves.yml

https://paste.denizenscript.com/View/114019

### Description

The /npc2 name command does not work

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
