### ISSUE TITLE
NPC Animation question

### ISSUE THREAD

**Issue by GithubErwan** [CitizensDev/Citizens2#3045]
### `/version` output

```txt
Current: git-Purpur-2035 (MC: 1.20.1)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### `/version Citizens` output

```txt
2.0.32-SNAPSHOT (build 3156)
```

### Log file

https://nothing.com

### config.yml

https://nothing.com

### saves.yml

https://nothing.com

### Description

Hello, I would like to know how to make my NPC an animation, for example by lying down.

**Comment by mcmonkey4eva** [comment]
consider asking on Discord instead of misfiling github bug reports https://discord.gg/Q6pZGSR
