### ISSUE TITLE
API Question: Nearest follow distance

### ISSUE THREAD

**Issue by kangarko** [CitizensDev/Citizens2#3046]
### `/version` output

```txt
[17:39:31 INFO]: This server is running Paper version git-Paper-160 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b8a0049)
```

### `/version Citizens` output

```txt
Citizens-2.0.32-b3188.jar
```

### Log file

.

### config.yml

.

### saves.yml

.

### Description

I apology, I am developer against Citizens API and struggling to find the options described in this customer ticket below - max hit distance and nearest follow distance.

https://github.com/kangarko/Boss/issues/1195

Can you please advise me where to adjust these options and what values do you recommend to avoid the issue that the customer shows in the 13second clip?

Thanks much,
Matej

**Comment by fullwall** [comment]
You can decrease the distance margin (https://jd.citizensnpcs.co/net/citizensnpcs/api/ai/NavigatorParameters.html). If using Sentinel API, ask in the Sentinel github.

**Comment by kangarko** [comment]
Thank you so much)
