### ISSUE TITLE
Lost TPS when chunk are loaded

### ISSUE THREAD

**Issue by normanfeltz** [CitizensDev/Citizens2#3047]
### `/version` output

```txt
This server is running Paper version git-Paper-108 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: d6d2b6f)
You are 55 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-521 (MC: 1.19.4)
```

### `/version Citizens` output

```txt
Citizens version 2.0.32-SNAPSHOT (build 3156)
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/114306

### config.yml

https://paste.denizenscript.com/View/114304

### saves.yml

https://paste.denizenscript.com/View/114305

### Profiler report

https://spark.lucko.me/nCzWVn9DA2

### Description

Hi,

Server lost TPS after loading chunk in a certain part of the map, below 10 TPS for 1-5 minutes, after check the spark we have see that the problem may be Citizens

Cordialy

Norman

**Comment by fullwall** [comment]
Looks like you have a chunk reloading issue (Paper bug, I am working on a workaround).
To work around yourself:
1. Enable citizens debug-mode in config.yaml
2. Find the NPC in the reloading chunk
3. Move the NPC off the chunk border (use F3+G to see chunk borders)
