### ISSUE TITLE
Circular plugin loading crash

### ISSUE THREAD

**Issue by Verzante** [CitizensDev/Citizens2#3048]
### `/version` output

```txt
Current: git-Purpur-2042 (MC: 1.20.1)*
```

### `/version Citizens` output

```txt
Citizens version 2.0.32-SNAPSHOT (build-3188)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/114384

### config.yml

https://paste.denizenscript.com/View/114385

### saves.yml

https://paste.denizenscript.com/View/114382

### Description

Unfortunately, I don't know how to reproduce it. I am reporting this crash since it says "Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help." 

Of course, in this case, I am reporting this because of these loops:
[08:34:13 ERROR]: [SimpleProviderStorage] Citizens -> CMI -> AdvancedMobArena -> BossMania -> Citizens
[08:34:13 ERROR]: [SimpleProviderStorage] Citizens -> CMI -> AdvancedMobArena -> BossMania -> ModelEngine -> Citizens

I did report this first to PaperMC and Purpur support but they gave no help.

**Comment by mcmonkey4eva** [comment]
Citizens is not at fault here, it's likely CMI adding a reverse dependency (loadbefore) which are pretty infamous for causing failures like this
