### ISSUE TITLE
Help me my server  won't work with citizens2

### ISSUE THREAD

**Issue by JLjoe** [CitizensDev/Citizens2#305]
everytime i try to do /npc create JLjoe it says

java.lang.NoSuchFieldError:field_75515_a
The error is below i screen shoted it
as far as i know the other commands are working
also im running a tekkit server and tekkit is in 1.6.4 so i downloaded the sentry and citizens 1.6.4 versions
thankyou

![2015-03-30_16 28 11](https://cloud.githubusercontent.com/assets/11722311/6899655/db58470a-d6f9-11e4-878c-26121676dbf4.png)

**Comment by Talamar1** [comment]
We would need server logs, server version and citizen version(build number)

**Comment by JLjoe** [comment]
what about now???

**Comment by Talamar1** [comment]
We would want to see the server log showing the error (console log).
We need to know what version of bukkit/spigot you are using.
We need to know what version/build of Citizen you are using.

**Comment by JLjoe** [comment]
uh how do i find them? i know how to find the version of citizen
i shall get that now

**Comment by JLjoe** [comment]
http://www.curse.com/bukkit-plugins/minecraft/citizens/740217



the link to it

**Comment by Talamar1** [comment]
Okay, that's a way old version of Citizen for version 1.6.4
I would suggest getting the version that matches your version of bukkit/spigot from:
http://wiki.citizensnpcs.co/Versions

**Comment by Talamar1** [comment]
spigot/bukkit version you get from typing:  /version

**Comment by JLjoe** [comment]
okay how do i find my spigot version??

**Comment by JLjoe** [comment]
thanks
i screen shotted it one second please

**Comment by Talamar1** [comment]
You could just copy and paste

**Comment by JLjoe** [comment]
![2015-03-30_16 39 12](https://cloud.githubusercontent.com/assets/11722311/6899955/8689c5c6-d6fb-11e4-990f-4e5d89b9041d.png)

**Comment by JLjoe** [comment]
can you see the photo?

**Comment by Talamar1** [comment]
Wow, yeah, you are using really old server code.  This is the last build for that version:
http://ci.citizensnpcs.co/job/Citizens2/1076/artifact/target/citizens-2.0.10-SNAPSHOT.jar

**Comment by JLjoe** [comment]
thankyou and sentry?

**Comment by Talamar1** [comment]
Might want to try:
http://ci.citizensnpcs.co/job/Sentry/5/artifact/target/sentry.jar
But not sure, build 6 failed and build 7 was for the next release of MC core.

**Comment by Talamar1** [comment]
Sentry is not really supported much anymore.  Most people are using Denizen and using dSentry script.

**Comment by JLjoe** [comment]
the one you  sent 4 mins ago i installed the same error ill try the other one you sent

**Comment by JLjoe** [comment]
yes um the one you sent me that was citizens i got the same error?

**Comment by Talamar1** [comment]
Then we would need to see your console logs.

**Comment by JLjoe** [comment]
where are they located?

**Comment by JLjoe** [comment]
btw i deleted the citizens after i got the same error

**Comment by JLjoe** [comment]
because i have 3 different server logs

**Comment by JLjoe** [comment]
Hello??

**Comment by Talamar1** [comment]
usually latest.log is the one

**Comment by Talamar1** [comment]
You should see a huge string of java errors.
That being said, I doubt fullwall will go back and fix it if it is an error in Citizens2, the version of MC you are running is very old.  I would suggest upgrading to 1.7.10 or 1.8.3

**Comment by JLjoe** [comment]
what how but tekkit is 1.6.4 minecraft version

**Comment by Talamar1** [comment]
Again, without seeing the java error in the log which shows what part of Cit is causing the issue, there is no hope of getting this fixed.

**Comment by JLjoe** [comment]
how do i send the log to you??

**Comment by Talamar1** [comment]
paste it to http://mcmonkey.org/paste (make sure you click the Server Log radio button) and paste the link here after you save it

**Comment by JLjoe** [comment]
server log radion button? and i have 3 server logs whch one?

**Comment by JLjoe** [comment]
also i just installed citizens again and its told me even though im op i can't use tp
this has happend before i had to delete the server and reload a backup

**Comment by JLjoe** [comment]
i cant acces anything like /fly tp

**Comment by JLjoe** [comment]
this is really messed up now???

**Comment by Talamar1** [comment]
Those commands are all protected by essentials or something like that.  Not related to Citizens.  What are the names of your 3 server logs?

**Comment by JLjoe** [comment]
well how comes citizens after being installed has  made it do it?

**Comment by JLjoe** [comment]
server.log
server.log.1
server.log.1.lck
server.log.lck

**Comment by JLjoe** [comment]
also citizens caused this problem with essentials last time i tried

**Comment by Talamar1** [comment]
server.log

the .1 is the old log and the .lck are lock files

**Comment by JLjoe** [comment]
if you see why essentials has suddenly stopped working please tell me ive clicked to view it and the page is just blank btw

**Comment by JLjoe** [comment]
okay ive pasted it what now?

**Comment by JLjoe** [comment]
okay im going to thankyou for your efforts but im just gunna use a new plugin thankyou im sorry for wasteing your time
