### ISSUE TITLE
Changing price colors in shops

### ISSUE THREAD

**Issue by Zinnorov** [CitizensDev/Citizens2#3051]
### I confirm that I have ...

- [x] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

It would be nice to have an option to change the price color, so it doesn't blend in with the rest of the lore. I tried to make changes in shops.yml or directly in the shop editor by adding &f or `<white>` but with no success. This one resulted in the price being displayed as $0.00:
```
cost:
  '0':
    money: <white>150.0</white>
```

**Comment by fullwall** [comment]
Added
