### ISSUE TITLE
Client console spams "Server attempted to add player prior to sending player info "

### ISSUE THREAD

**Issue by HC-Emro** [CitizensDev/Citizens2#3053]
### `/version` output

```txt
This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
```

### `/version Citizens` output

```txt
Citizens version 2.0.32-SNAPSHOT (build 3156)
```

### Log file

https://paste.denizenscript.com/View/115247 (client)

### config.yml

https://paste.denizenscript.com/View/115246

### saves.yml

https://paste.denizenscript.com/View/115245

### Profiler report

only client side / no problem on server side tps 20/20

### Description

When the player joins the server, occasionally the console spams "Server attempted to add player prior to sending player info (Player id uuid)". After checking, it is indeed the citizens plugin which is causing this spam and the uuids correspond to the uuids of the NPCs. The players are running Fabric 1.19.4 and even without mods, the result is the same. My server is under velocity and paper.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by normanfeltz** [comment]
Hey,

We have the same problem on our server, but we are a premium server with a waterfall proxy and paper servers.

Cordialy

Norman
