### ISSUE TITLE
Textdisplay & Itemdisplay support  npc name and holograms

### ISSUE THREAD

**Issue by abola2** [CitizensDev/Citizens2#3056]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Citizens should add this because textdisplay and itemdisplay allow create modern and more lightweight holograms / names

### Code Example

```java
-
```

**Comment by fullwall** [comment]
This is already supported. However, the entities don't look as good as armor stands.

**Comment by fullwall** [comment]
@UltraFaceguy this user received support on Discord, so my response was naturally brief. You were marked as "Do Not Support" for being inflammatory in our community in the past, and it does not appear to have changed much. I am happy to work on this feature in the future but I have already spent significant time on it a few months ago.
