### ISSUE TITLE
Display entities doesn't obey to default-line-height

### ISSUE THREAD

**Issue by rudde0** [CitizensDev/Citizens2#3060]
### `/version` output

```txt
Current: git-Purpur-2076 (MC: 1.20.2)*
Previous: git-Purpur-2074 (MC: 1.20.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.33-SNAPSHOT (build 3219)
```

### Log file

No error

### config.yml

https://paste.denizenscript.com/View/116258

### saves.yml

I create temporary NPCs using CitizensAPI

### Description

I able to change height of nameplate holograms of NPCs with using `default-line-height` but when I set `use-display-entities` to true, changing the value isn't changing height of hologram. I also tried change height of hologram with `HologramTrait.setLineHeight` but it doesn't change height either.

**Comment by mcmonkey4eva** [comment]
Please either properly fill all required fields of the issue template, or ask on Discord instead  https://discord.gg/Q6pZGSR
