### ISSUE TITLE
Non-ops can no longer use their NPCs

### ISSUE THREAD

**Issue by aurel85** [CitizensDev/Citizens2#3061]
### `/version` output

```txt
10.10 21:19:00 [Server] INFO This server is running Paper version git-Paper-226 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a2ba452)
10.10 21:19:00 [Server] INFO You are 1 version(s) behind
10.10 21:19:00 [Server] INFO Download the new version at: https://papermc.io/downloads/paper
10.10 21:19:00 [Server] INFO Previous version: git-Paper-223 (MC: 1.20.2)
```

### `/version Citizens` output

```txt
10.10 21:21:16 [Server] INFO Citizens version 2.0.33-SNAPSHOT (build 3219)
10.10 21:21:16 [Server] INFO Website: https://www.citizensnpcs.co
10.10 21:21:16 [Server] INFO Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/116287

### config.yml

https://paste.denizenscript.com/View/116288

### saves.yml

https://paste.denizenscript.com/View/116289

### Description

Hi,

On this version my players who can use NPCs can no longer do anything at all. The commands do not react and when they try to modify their NPC the plugin tells them that they are not owners, even though they are in the save.yml.

They can still create a new NPC but once it is done they can no longer modify it. It's as if they lost ownership upon creation.

There are no errors in the console.

Thanks in advance.

**Comment by fullwall** [comment]
Try the newest build. (Only supports **1.20.2** not *1.20.1**)

**Comment by aurel85** [comment]
Everything is ok, thanks !
