### ISSUE TITLE
Internal error has occurred - Plugin is disabled

### ISSUE THREAD

**Issue by BruhNeedsScripts** [CitizensDev/Citizens2#3062]
### `/version` output

```txt
This server is running Paper version git-Paper-36 (MC: 1.80.1) (Implementing API version 1.20.1-9.1-SNAPSHOT) (Git: faf9a65)
```

### `/version Citizens` output

```txt
Citizens version 2.0.33-SNAPSHOT (build 3226) Website: https://www.citizensnpos.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/116465

### config.yml

https://paste.denizenscript.com/View/116466

### saves.yml

no saves.yml file

### Description

This happened to me when i first just downloaded the plugin, i havent used it before and havent created no npcs no none of that. When i was trying to create a npcs the command didnt pop up but i saw the /citizens:citizens command so i executed that but then it gave me a internal error occured message, i checked the versions and everything and to me they seem up to date, but this is my first time using this plugin so i decided to come here to double check. Here are some images of the problems
![image](https://github.com/CitizensDev/Citizens2/assets/127696417/1c4e6774-6988-4a5e-9cfc-603d78ac4fce)
![image](https://github.com/CitizensDev/Citizens2/assets/127696417/4fb39f6d-0209-4d9b-85e0-0a09817d8c4e)
I also read some forum posts about the almost same problem but they came from older versions such as 1.16 and 1.15,
if anyone has a fix to this, please reply, so i can get this server update out, thanks!

**Comment by mcmonkey4eva** [comment]
Latest builds target MC 1.20.2, not .1

**Comment by BruhNeedsScripts** [comment]
Wait but can i download a 1.20.1 version of citizens?
