### ISSUE TITLE
Unprivate ItemDrop class and drops list field

### ISSUE THREAD

**Issue by Fusezion** [CitizensDev/Citizens2#3064]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

These two parts of the DropsTrait class are the biggest limitation for people using the api. As the only other way to do this themselves is to make their own trait and override yours. 

The ItemDrop class is the only supported class to add/set drops 
and the `drops` list field can't even be accessed outside of the class.

**Comment by fullwall** [comment]
Why can't you make your own trait? I'm confused.

**Comment by Fusezion** [comment]
It's not that you can't, it's more so why would I want to reinvent the wheel when changing two privates to public makes more sense. This just seems like a very weird decision to private these two core components but leave gui stuff public. 

I don't know the code base that well or at all as this is just my 4th day using the api this still is a weird decision made when created.

**Comment by fullwall** [comment]
It's a trivial wrapper around listening for NPCDeathEvent. The methods are private since the drops API is not stable. This is a very easy method to implement.
