### ISSUE TITLE
Summoning NPCs with --registry leaves me unable to modify them

### ISSUE THREAD

**Issue by TheFriendlyBudgie** [CitizensDev/Citizens2#3065]
### `/version` output

```txt
This server is running Paper version git-Paper-260 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1865625)
You are running the latest version
Previous version: git-Paper-241 (MC: 1.20.2)
```

### `/version Citizens` output

```txt
2.0.33-SNAPSHOT (build 3230)
```

### Log file

https://paste.denizenscript.com/View/117020

### config.yml

https://paste.denizenscript.com/View/117021

### saves.yml

# Citizens NPC Storage  {}

### Description

When running 
`/npc create "Parkour Spiral 1" --registry "parkourspiral"`
and then attempting to list all NPCs no NPCs are listed even though the npc is visible

**Comment by fullwall** [comment]
There are some documented limitations with custom NPC registries. You can use /npc list --registry [registry]
