### ISSUE TITLE
Ability to add broken blocks directly to a NPCs Inventory instead of them appearing as a drop.

### ISSUE THREAD

**Issue by NightSling** [CitizensDev/Citizens2#3066]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

If a NPC were to break a block, and if a flag like `addToInv` is true, It should automatically add the broken block to the NPCs inventory instead of dropping the block.

**Comment by fullwall** [comment]
This should be on discord not github issues
