### ISSUE TITLE
Very low TPS

### ISSUE THREAD

**Issue by DefensiveWarden** [CitizensDev/Citizens2#3068]
### `/version` output

```txt
This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
You are running the latest version
Previous version: git-Paper-246 (MC: 1.20.2)
```

### `/version Citizens` output

```txt
2.0.33-SNAPSHOT (build 3229)
```

### Log file

https://paste.denizenscript.com/View/117421

### config.yml

https://paste.denizenscript.com/View/117422

### saves.yml

https://paste.denizenscript.com/View/117423

### Profiler report

https://spark.lucko.me/gDOq3QyYI5

### Description

The TPS is low. I don't really have that much complicated paths, the only paths i use is to get them back to their spots after combat, so just one pathpoint per npc. To be honest, i know nearly nothing about coding. But i think the real problem is about unloading npcs. TPS seems to get low AFTER i get far from a loaded group of npcs. This problem started after i created 2 npcs far away from my main group of npcs that are relatively closer to each other.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by DefensiveWarden** [comment]
Ok fair, changed it to online mode and nothing changed performance wise, should i open a seperate issue with new reports, or should i post the new reports here?
