### ISSUE TITLE
Waypoint provider wander issue

### ISSUE THREAD

**Issue by angrybirds85** [CitizensDev/Citizens2#307]
Recently found out about the ability to make NPC's wander with the command /waypoint provider wander. I wanted to make a city and have citizens walking around the city. So I created an NPC and went to build a house then went back to look for the NPC and I saw it was gone. So I tp'd to it and it was underground, even though it couldn't access any caves. So I trapped it in a box and it was teleporting on top of the box, then onto the floor under the box. So yeah, can you fix this please? Not sure if the story was needed but meh :P

**Comment by angrybirds85** [comment]
Hello? Are you going to look into this bug or not?

**Comment by mcmonkey4eva** [comment]
Give it time, our lead dev is very busy lately, and I (secondary dev) have no idea about any of that.

**Comment by angrybirds85** [comment]
Oh, ok then. I saw that other tickets had replies too and I thought this was being ignored. Thanks for clearing that up and hope it gets fixed soon :P

**Comment by fullwall** [comment]
Ok, I understand the issue. The problem is he picks a location to wander to that he can't make it to so he teleports there instead. To disable that behaviour type /waypoint disableteleport

**Comment by angrybirds85** [comment]
Will this disable it for the NPC selected or all NPC's?

**Comment by mcmonkey4eva** [comment]
That's selected NPC I believe.

**Comment by angrybirds85** [comment]
Aww, ok.
