### ISSUE TITLE
Command to make NPC fluid pushable/unpushable

### ISSUE THREAD

**Issue by blablubbabc** [CitizensDev/Citizens2#3070]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

There was a similar request in the past: https://github.com/CitizensDev/Citizens2/issues/2832
And there is a "FLUID_PUSHABLE" Metadata value already that can be used to make NPC's unpushable via the API.
But I don't think there is a command yet to allow toggling this behavior on and off in-game for individual NPCs.

Also, related to that: Are the NPCs meant to be pushable by fluids by default? Or would it make sense to make them unpushable by default, similar to how they are invulnerable and non-collidable by default.

**Comment by fullwall** [comment]
Tracking this on Discord
