### ISSUE TITLE
Please update to version 1.20.4

### ISSUE THREAD

**Issue by CCjun6** [CitizensDev/Citizens2#3071]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

1.20.4 has been out for a while, but the latest version does not support it. Please update it. Thank you.

**Comment by fullwall** [comment]
Yes, it does.
