### ISSUE TITLE
Citizens2 won't work 1.20.2 Spigot

### ISSUE THREAD

**Issue by SicuramenteDave** [CitizensDev/Citizens2#3072]
### `/version` output

```txt
This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-Paper-297 (MC: 1.20.2)
```

### `/version Citizens` output

```txt
2.0.33-SNAPSHOT (build 3287)
```

### Log file

https://paste.denizenscript.com/View/118570

### config.yml

https://paste.denizenscript.com/View/118573

### saves.yml

no file

### Description

When i try to run the plugin (after start the server) the plugin is disabled.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by 07SPARSH07** [comment]
So what is the solution for this ?

**Comment by SicuramenteDave** [comment]
That's new Log file

[https://paste.denizenscript.com/View/118574](https://paste.denizenscript.com/View/118574)

I'm using the offline mode just for testing with two user.

I've a paid minecraft account
