### ISSUE TITLE
Color codes not working?

### ISSUE THREAD

**Issue by Rator123** [CitizensDev/Citizens2#3074]
### `/version` output

```txt
/version: This server is running Paper version git-Paper-331 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ff26d54)
You are running the latest version
```

### `/version Citizens` output

```txt
/version Citizens:
Citizens
 version 
2.0.33-SNAPSHOT (build 3287)
```

### Log file

https://paste.denizenscript.com/View/118689

### config.yml

https://paste.denizenscript.com/View/118690

### saves.yml

https://paste.denizenscript.com/View/118691

### Description

There is a bug that color codes doesn't show in a right/proper way, it shows in a weird way as an NPC name when using color codes or even in commands just like provided in the picture below:
![image](https://github.com/CitizensDev/Citizens2/assets/154095180/b9a2318f-a2ae-4b09-abe4-0d28b2c61ae5)
![image](https://github.com/CitizensDev/Citizens2/assets/154095180/068114d1-74e8-4bba-acc0-4a279d9b0604)
![image_2023-12-17_234204993](https://github.com/CitizensDev/Citizens2/assets/154095180/7189eef4-1574-4aed-a41a-50ca6b691031)

**Comment by rayanbzd** [comment]
Adventure API has not been updated yet in Citizens for 1.20.3 
Adventure 4.15.0 (support 1.20.3) has been updated just 10hours ago, so devs of Citizens should update the dependency soon i guess

**Comment by fullwall** [comment]
> Adventure API has not been updated yet in Citizens for 1.20.3 Adventure 4.15.0 (support 1.20.3) has been updated just 10hours ago, so devs of Citizens should update the dependency soon i guess

Waiting for adventure-platform actually (still not updated). Watch https://github.com/KyoriPowered/adventure-platform/pull/144
