### ISSUE TITLE
Shearing an NPC Snow Golem doesn't enable derp mode which means it does not save the derp mode

### ISSUE THREAD

**Issue by mrjasonn** [CitizensDev/Citizens2#3076]
### `/version` output

```txt
This server is running CraftBukkit version 3976-Spigot-06d602e-b3b43a6 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)
Checking version, please wait...
You are 2 version(s) behind
```

### `/version Citizens` output

```txt
Citizens version 2.0.33-SNAPSHOT (build 3287)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/118771

### config.yml

https://paste.denizenscript.com/View/118769

### saves.yml

https://paste.denizenscript.com/View/118768

### Description

If you shear an NPC Snow Golem, it won't activate derp mode in the settings which means it won't save that properly. I don't even know if you are supposed to be able to shear them if they are NPC.

**Comment by fullwall** [comment]
Fixed in new build
