### ISSUE TITLE
Problem while trying to rotate, especially npcs with --type, they just face a 1 direction which is south

### ISSUE THREAD

**Issue by Rator123** [CitizensDev/Citizens2#3077]
### `/version` output

```txt
This server is running Paper version git-Paper-338 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d11a588)
You are running the latest version
Previous version: git-Paper-336 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
=[21:20:27 INFO]: 
Citizens
 version 
2.0.33-SNAPSHOT (build 3288)
[21:20:27 INFO]: Website: 
https://www.citizensnpcs.co
[21:20:27 INFO]: Author: 
fullwall
```

### Log file

https://paste.denizenscript.com/View/118817

### config.yml

https://paste.denizenscript.com/View/118819

### saves.yml

https://paste.denizenscript.com/View/118820

### Description

First thank you for your effort in fixing the plugin color codes, but now there is another issue which is the NPCS not rotating, especially those with --type, they are all facing the South direction for some reason, I tried removing and re-creating them to face an exact direction as well, they would just rotate by their own to the South direction, waiting for it to be fixed!

**Comment by fullwall** [comment]
https://wiki.citizensnpcs.co/Cracks
