### ISSUE TITLE
How to bind commands on NPC's

### ISSUE THREAD

**Issue by gHc280** [CitizensDev/Citizens2#308]
Is there any way you can bind a command on the citizens?
For example: if you rightklick it  "/gamemode" 1 will be activated for the player who klicked him
Citizens Plugin Version: 1.7.9

**Comment by Talamar1** [comment]
You would need to use the Denizen plugin attached to the Citizen npc.

**Comment by gHc280** [comment]
Oh ok, thanks for the quick response :smile:
