### ISSUE TITLE
Towny support for towns

### ISSUE THREAD

**Issue by Thebanremover** [CitizensDev/Citizens2#3080]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

It would be nice if you could add citizens npcs to towns using towny, this would be good because it would make citizens more immersive, or use towny's resident list as like a npc list for quests
I tried using the plugin reallyfakeplayers but its discontinued

**Comment by fullwall** [comment]
This is something to ask Towny.
