### ISSUE TITLE
PlayerNPC won't fly up or down when moved programically

### ISSUE THREAD

**Issue by ffd000** [CitizensDev/Citizens2#3082]
### `/version` output

```txt
This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
```

### `/version Citizens` output

```txt
Citizens version 2.0.31-SNAPSHOT (build 3100)
```

### Log file

https://paste.denizenscript.com/View/119357

### config.yml

https://paste.denizenscript.com/View/119358

### saves.yml

https://paste.denizenscript.com/View/119359

### Description

I have a task running every .5 seconds to move the NPC around using `navigator.setTarget(targetLocation)` where the coordinates in `targetLocation` are updated dynamically. The NPC only moves across the X and Z axes but not up or down. I want it to reach the target location regardless of its Y level as it moves step by step in the air.
I toggle the NPC's Gravity trait and set its speed modifier before spawning it. I tried to setFlyable but it doesn't work.

**Comment by fullwall** [comment]
Ask on discord please with your code.
