### ISSUE TITLE
Enhancement: Improve Hologram Management - Remove Shadows

### ISSUE THREAD

**Issue by Jeremylo1** [CitizensDev/Citizens2#3083]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Citizens should have the ability to manage holograms more effectively, especially in the context of modern Minecraft versions. This feature request proposes the addition of an option to remove shadows from holograms, which can significantly enhance the visual experience for players.

**Why should it be added?**
Adding the option to remove shadows from holograms within the Citizens plugin is essential for several reasons:
1. **Visual Enhancement:** Shadows on holograms can sometimes obscure the text or content displayed, making it less visually appealing.
2. **Flexibility:** This feature would provide server owners and administrators with greater control over the appearance of holograms, allowing for a more tailored and immersive experience.
3. **Compatibility:** As Minecraft updates continue to improve rendering, having the option to remove shadows ensures compatibility with the latest visual enhancements.

**What are the benefits for others?**
The benefits of adding this feature to Citizens would extend to server owners, administrators, and players:
1. **Server Owners:** Greater customization options for holograms enhance the overall quality and uniqueness of their servers.
2. **Administrators:** Easier management of holographic content without the interference of shadows.
3. **Players:** Improved readability and immersion when interacting with holograms in the game.

**Are there existing alternatives you considered?**
One alternative that users may consider is using the default Minecraft display_text feature overlaid on Citizens holograms. However, this approach lacks the fine-grained control and flexibility that would be provided by the proposed feature. Using the default Minecraft text may not be as manageable, especially when dealing with complex holographic content or custom styling. Therefore, having a built-in option within Citizens to remove shadows from holograms would offer a more user-friendly.

**Comment by fullwall** [comment]
I agree. This is planned for a future release of citizens, and is being tracked on discord.
