### ISSUE TITLE
Color error in the hologram

### ISSUE THREAD

**Issue by Barpadzik** [CitizensDev/Citizens2#3084]
### `/version` output

```txt
ImanitySpigot3 Premium 1.8.8
```

### `/version Citizens` output

```txt
Dev Build 3305
```

### Log file

https://paste.denizenscript.com/View/119620

### config.yml

https://paste.denizenscript.com/View/119621

### saves.yml

https://paste.denizenscript.com/View/119623

### Description

After the update I saw this: (Colors) (Only when placeholder in line)
![obraz_2024-01-21_220615984](https://github.com/CitizensDev/Citizens2/assets/132010826/95cc677d-4213-4dc4-ad49-0c97eb4dc464)

This is Citizens Holograms

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks  & https://wiki.citizensnpcs.co/Minecraft_1.8

wiki is temporarily down so archive links too: http://web.archive.org/web/20240121085616/https://wiki.citizensnpcs.co/Cracks  http://web.archive.org/web/20220630135254/https://wiki.citizensnpcs.co/Minecraft_1.8
