### ISSUE TITLE
Support meg4

### ISSUE THREAD

**Issue by CCjun6** [CitizensDev/Citizens2#3085]
### `/version` output

```txt
Checking version, please wait...
Current: git-Purpur-2128 (MC: 1.20.4)*
Previous: git-Purpur-2112 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
Citizens version 2.0.33-SNAPSHOT (build 3311)
 Website: https://www.citizensnpcs.co
 Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/119771

### config.yml

https://paste.denizenscript.com/View/119769

### saves.yml

https://paste.denizenscript.com/View/119770

### Description

I am currently using the latest version of ModelEngine4
But after I add a model to the npc
and then logging back in to the server I get an error

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
