### ISSUE TITLE
Append version number to the downloaded artifact on Spigot

### ISSUE THREAD

**Issue by YanisBft** [CitizensDev/Citizens2#3086]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

When downloading Citizens' artifacts from Spigot, the JARs are always named "Citizens.jar". I suggest adding the version number to it, to help server owners not getting confused. Thanks!

**Comment by fullwall** [comment]
I'll take this into consideration.
