### ISSUE TITLE
The plugin is overload server, and tps drops show up.

### ISSUE THREAD

**Issue by DraimCiDo** [CitizensDev/Citizens2#3087]
### `/version` output

```txt
> version
[17:21:14 INFO]: Checking version, please wait...
[17:21:14 INFO]: Current: git-Purpur-2130 (MC: 1.20.4)*
Previous: git-Paper-394 (MC: 1.20.4)
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### `/version Citizens` output

```txt
> version Citizens
[17:21:03 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3311)
[17:21:03 INFO]: Website: https://www.citizensnpcs.co
[17:21:03 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/119826

### config.yml

https://paste.denizenscript.com/View/119827

### saves.yml

https://paste.denizenscript.com/View/119828

### Profiler report

https://spark.lucko.me/czLztHORQh

### Description

The server starts and after a while the plugin starts to accumulate and consume more resources.
When the server has been running for more than an hour - the server starts to lag.

**Comment by fullwall** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by DraimCiDo** [comment]
![image](https://github.com/CitizensDev/Citizens2/assets/53317146/2f408e2c-9e9a-467b-aa36-bc31adcaeea5)
