### ISSUE TITLE
Does citizens plugin work on spigot 1.8?

### ISSUE THREAD

**Issue by RealSkyWolf** [CitizensDev/Citizens2#309]
Hello people,
I recently add a plugin which called "citizens" to my little server to make commandnpc but it doesn't work! I have vault installed also and the cizitens plugin still in red format when I do /plugins. I have reinstall everything multiple times but nothing changes. Please help and don't say something like: "update your server to the lastest spigot version" cyz I already did that.

I have checked the consolle also billion times and it doesn't say something about an error.

**Comment by Talamar1** [comment]
Use this link:
http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

**Comment by RealSkyWolf** [comment]
doesn't work :(

**Comment by Talamar1** [comment]
Can you upload your server logs to http://mcmonkey.org/paste

**Comment by RealSkyWolf** [comment]
Here you go: http://mcmonkey.org/paste/14839
Page 2 is coming..

**Comment by RealSkyWolf** [comment]
Latest log: http://mcmonkey.org/paste/14841

**Comment by mcmonkey4eva** [comment]
Please select the appropriate build from http://wiki.citizensnpcs.co/Versions

**Comment by Talamar1** [comment]
spigot.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95
You are using 1.7.9, not 1.8
