### ISSUE TITLE
Compatibility with weapon mechanics 

### ISSUE THREAD

**Issue by tana-to** [CitizensDev/Citizens2#3091]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Hello, I propose enhancing Citizen plugin compatibility to seamlessly integrate with weapon mechanics plugin. On my server, initially using Quality Armory and Citizen, I created NPCs equipped with Quality Armory guns. Transitioning to WM, I faced challenges assigning weapons to NPCs. Collaborating to establish compatibility would greatly enhance the overall experience.

**Comment by mcmonkey4eva** [comment]
That would be done through Sentinel https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md not base Citizens, and it's already been planned on the WM side: https://github.com/WeaponMechanics/MechanicsMain/issues/255 so voice your support there
