### ISSUE TITLE
Could not pass event NPCRightClickEvent to Citizens

### ISSUE THREAD

**Issue by brnxx** [CitizensDev/Citizens2#3093]
### `/version` output

```txt
git-Paper-407 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
Citizens version 2.0.33-SNAPSHOT (build 3314)
```

### Log file

https://paste.denizenscript.com/View/120069

### config.yml

https://paste.denizenscript.com/View/120070

### saves.yml

https://paste.denizenscript.com/View/120071

### Description

I'm using the CitizensText plugin to better add texts to NPCs. But when integrated, it generates this error that is in the log.

[16:40:39 ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.33-SNAPSHOT (build 3314)

**Comment by mcmonkey4eva** [comment]
Use the Citizens built-in `/npc text` system, it's pretty capable these days. If you choose to use the external plugin, you'll have to ask their support for help with it not us.
