### ISSUE TITLE
Citizens shown in Tablist in latest jenkins version

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#3095]
### `/version` output

```txt
[02:06:23 INFO]: This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)
You are running the latest version
Previous version: git-Paper-434 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
[02:07:29 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3319)
[02:07:29 INFO]: Website: https://www.citizensnpcs.co
[02:07:29 INFO]: Author: fullwall

Error arrouted with
Build 3320 up tp 3327
```

### Log file

https://paste.denizenscript.com/View/120526

### config.yml

https://paste.denizenscript.com/View/120527

### saves.yml

https://paste.denizenscript.com/View/120528

### Description

Citicenz are shown to the Tablist
For our Tablist we are using CMI-Tablist
This issue can be seen by using Build 3320 up to 3327
With build 3319 all is fine.

![Snag_3d732ca](https://github.com/CitizensDev/Citizens2/assets/12080017/8b9df9b4-aab0-4c57-bf60-dd788a66d9ee)

**Comment by fullwall** [comment]
Easier to track this on discord.
