### ISSUE TITLE
ProtocolLib listener optimization

### ISSUE THREAD

**Issue by IAISI** [CitizensDev/Citizens2#3097]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

https://github.com/CitizensDev/Citizens2/blob/3c8429aa6d69ae44ff1aeb694b24463c6efa6e23/main/src/main/java/net/citizensnpcs/ProtocolLibListener.java#L229

ProtocolLibListener#getNPCFromPacket would show up in Spark profile from time to time. I'm trying to figure out a way to optimize this. When testing testing our packet based PlayerHider we had similar issues but after some testing we've noticed packet.getEntityModifier is faster. I'm wondering if the following change to getNPCFromPacket would help with this issue (pasted updated getNPCFromPacket below).

### Code Example

```java
private NPC getNPCFromPacket(PacketEvent event) {
        PacketContainer packet = event.getPacket();
        Entity entity;
        try
        {
            Object entityInPacket = packet.getEntityModifier(event).getTarget();
            if(!(entityInPacket instanceof Entity))
                return null;

            entity = (Entity) entityInPacket;
        } catch (FieldAccessException | IllegalArgumentException ex) {
            if (!LOGGED_ERROR) {
                Messaging.severe(
                        "Error retrieving entity from ID: ProtocolLib error? Suppressing further exceptions unless debugging.");
                ex.printStackTrace();
                LOGGED_ERROR = true;
            } else if (Messaging.isDebugging()) {
                ex.printStackTrace();
            }
            return null;
        }
        return entity instanceof NPCHolder ? ((NPCHolder) entity).getNPC() : null;
    }
```

**Comment by fullwall** [comment]
Give it a go in new build
