### ISSUE TITLE
PlayerDeadEvent console error

### ISSUE THREAD

**Issue by homerek111** [CitizensDev/Citizens2#3099]
### `/version` output

```txt
This server is running Paper version git-Paper-398 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b700460)
You are 38 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-318 (MC: 1.20.2)
```

### `/version Citizens` output

```txt
2.0.33-SNAPSHOT (build 3332)
```

### Log file

https://paste.denizenscript.com/View/120687

### config.yml

https://paste.denizenscript.com/View/120688

### saves.yml

https://paste.denizenscript.com/View/120689

### Description

error pops out after killing bot in bot-fight in StrikePractice plugin

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
