### ISSUE TITLE
Citizens makes my server automatically Shutdown

### ISSUE THREAD

**Issue by KidzViciouz** [CitizensDev/Citizens2#310]
When I type / npc create [example: Steve] then I immediately shutdown the server or the server closed, why? Can you help me to fix it, I use the server version: Spigot_1.7.10 R 1 and Citizen 2.0.14-SNAPSHOT

**Comment by mcmonkey4eva** [comment]
Make sure you have the correct version of Citizens -> http://wiki.citizensnpcs.co/Versions
