### ISSUE TITLE
NPCs don't regenerate health when hurt

### ISSUE THREAD

**Issue by WilliamWCYoung** [CitizensDev/Citizens2#3101]
### `/version` output

```txt
> version
[20:46:20 INFO]: Checking version, please wait...
[20:46:20 INFO]: This server is running Paper version git-Paper-436 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 850b736)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
```

### `/version Citizens` output

```txt
> version Citizens
[20:46:40 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3349)
[20:46:40 INFO]: Website: https://www.citizensnpcs.co
[20:46:40 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/120781

### config.yml

https://paste.denizenscript.com/View/120783

### saves.yml

https://paste.denizenscript.com/View/120784

### Description

I've created some npcs, made them non-protected, and then attacked them. I noticed they don't get hungry (no events) so started printing out their health/food level/saturation/exhaustion and noticed even though their health and exhaustion go down as expected, it's not replenished with their food level and saturation. I've looked through the documentation and can't see anything that I need to add?

**Comment by fullwall** [comment]
Ok in the new build /npc ai will enable this.

**Comment by WilliamWCYoung** [comment]
Thank you so much!
