### ISSUE TITLE
Looking south using ViaBackwards

### ISSUE THREAD

**Issue by MiguVT** [CitizensDev/Citizens2#3104]
### `/version` output

```txt
This server is running Pufferfish version git-Pufferfish-46 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: fb16f9c on HEAD)
You are on the latest version!
```

### `/version Citizens` output

```txt
Citizens version 2.0.33-SNAPSHOT (build 3365)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

No interesting logs about this error :c

### config.yml

https://paste.denizenscript.com/View/120982

### saves.yml

https://paste.denizenscript.com/View/120983

### Description

I use the latest ViaVersion and ViaBackwards snapshot
![image](https://github.com/CitizensDev/Citizens2/assets/71216796/7f70bd50-ad64-4013-9f0d-81470cf58357)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
