### ISSUE TITLE
Cannot read field "h" because "server" is null Error

### ISSUE THREAD

**Issue by witcharon** [CitizensDev/Citizens2#3105]
### `/version` output

```txt
Previous version: git-MultiPaper-"7e90ee5" (MC: 1.20.1)
```

### `/version Citizens` output

```txt
Citizens-2.0.32-b3147.jar
```

### Log file

https://paste.denizenscript.com/View/121060

### config.yml

https://paste.denizenscript.com/View/121061

### saves.yml

https://paste.denizenscript.com/View/121062

### Description

I'm failing when opening and trying to create an NPC with '/create Test' and I get this error.

**Comment by mcmonkey4eva** [comment]
Need 1.20.4, not .1

**Comment by witcharon** [comment]
I'm using MultiPaper and I have to use version 1.20.1, I can use the same Citizens on another server with Paper 1.20.1. Based on this information, can you help me resolve this issue? Is it a problem related to Proxy configuration by Citizens?
