### ISSUE TITLE
NPC to be deleted/despawned when it dies.

### ISSUE THREAD

**Issue by Veggiboi** [CitizensDev/Citizens2#3107]
### I confirm that I have ...

- [x] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

NPC to be deleted/despawned when it dies.

**Comment by mcmonkey4eva** [comment]
...?
