### ISSUE TITLE
[Placeholder] Placeholders are no longer hologrammetric

### ISSUE THREAD

**Issue by NoHere32** [CitizensDev/Citizens2#3110]
### `/version` output

```txt
This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-44 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
2.0.33-SNAPSHOT (build 3385)
```

### Log file

https://paste.denizenscript.com/View/121988

### config.yml

https://paste.denizenscript.com/View/121987

### saves.yml

https://paste.denizenscript.com/View/121986

### Description

upload the new build for testing
![image](https://github.com/CitizensDev/Citizens2/assets/123643370/d7d9c5be-0a79-4664-8f22-aaa66ccb4494)

**Comment by fullwall** [comment]
I don't know what you mean

**Comment by fullwall** [comment]
Try new build
