### ISSUE TITLE
[customentity] Custom entities become invisible 

### ISSUE THREAD

**Issue by NoHere32** [CitizensDev/Citizens2#3111]
### `/version` output

```txt
This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-44 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
2.0.33-SNAPSHOT (build 3385)
```

### Log file

https://paste.denizenscript.com/View/121989

### config.yml

https://paste.denizenscript.com/View/121987

### saves.yml

https://paste.denizenscript.com/View/121986

### Description

L'orsqu'un citizens possède une entité custom (itemsadder / modelengine) et que l'on s'eloigne de ce dernier il se peut qu'il deviennt invisible et qu'il ne rest que son hologramme tout en restant fonctionnel.
![image](https://github.com/CitizensDev/Citizens2/assets/123643370/d3baed85-5f5a-4a5d-8e47-ff6748383953)
![image](https://github.com/CitizensDev/Citizens2/assets/123643370/34787b2f-c459-4afb-a026-98611abf9039)

**Comment by NoHere32** [comment]
The problem has been present ever since the 1.20.4 build was released. 
To reproduce it, you just need to move away from it by about thirty blocks, sometimes even less, and then return to it.

**Comment by mcmonkey4eva** [comment]
ModelEngine issues are modelengine issues, can't solve them from Citizens side

**Comment by NoHere32** [comment]
It's not a matter of modelengine or itemsadder but of citizens, because a modelengine or itemsadder model doesn't despawn.

**Comment by NoHere32** [comment]
the problem is not present in the next version of citizens

This server is running Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)
You are running 22 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-26 (MC: 1.20.1)



2.0.32-SNAPSHOT (build 3188)

**Comment by mcmonkey4eva** [comment]
The ModelEngine-Citizens integration exists in ModelEngine code, not Citizens. We can do nothing about it. It's a ModelEngine issue.

**Comment by NoHere32** [comment]
/

> The ModelEngine-Citizens integration exists in ModelEngine code, not Citizens. We can do nothing about it. It's a ModelEngine issue.

so you're not the one proposing customentity in your code?

**Comment by fullwall** [comment]
Sounds like a tracking range problem. Citizens offers /npc trackingrange which you can try but as @mcmonkey4eva said this is probably an issue with ModelEngine.
