### ISSUE TITLE
Error Moving An Item Display

### ISSUE THREAD

**Issue by DefinitlyEvil** [CitizensDev/Citizens2#3115]
### `/version` output

```txt
This server is running Paper version git-Paper-466 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a203544)
```

### `/version Citizens` output

```txt
[19:24:05 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3382)
[19:24:05 INFO]: Website: https://www.citizensnpcs.co
[19:24:05 INFO]: Author: fullwal
```

### Log file

https://paste.denizenscript.com/View/122141

### config.yml

https://paste.denizenscript.com/View/122142

### saves.yml

n/a

### Description

```java
    public boolean move(Location location, double margin) {
        if (visual.getMainEntity() == null || visual.getNpc() == null) throw new IllegalStateException("unable to move");
        if (visual.getNpc().getNavigator().isNavigating()) return false;
        if (!visual.getNpc().getNavigator().canNavigateTo(location)) return false; // <-- exception line no. 33
        final Navigator nav = visual.getNpc().getNavigator();
        nav.getDefaultParameters().distanceMargin(margin);
        nav.setTarget(location);
        return true;
    }
```

**Comment by mcmonkey4eva** [comment]
You can't using the living-entity navigator on an ItemDisplay NPC entity. Use a teleport if you need to move that, or use a living-entity typed NPC.

**Comment by fullwall** [comment]
You need to use the new finder for non-living entities. I have fixed an inconsistency here in canNavigate in the new build.

**Comment by DefinitlyEvil** [comment]
> You can't using the living-entity navigator on an ItemDisplay NPC entity. Use a teleport if you need to move that, or use a living-entity typed NPC.

Thank you for the note, however I want it to walk like a regular mob... xD 



> You need to use the new finder for non-living entities. I have fixed an inconsistency here in canNavigate in the new build.

Thanks for the reply! I didn't quite catch that, what did you mean?

**Comment by fullwall** [comment]
You need to set use new finder to true.
