### ISSUE TITLE
NPC hologram cause extreme lag on bedrock clients

### ISSUE THREAD

**Issue by Logikoz** [CitizensDev/Citizens2#3116]
### `/version` output

```txt
This server is running Paper version git-Paper-462 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 00fd87a)
```

### `/version Citizens` output

```txt
[15:12:42 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3396)
[15:12:42 INFO]: Website: https://www.citizensnpcs.co
[15:12:42 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/122168

### config.yml

https://paste.denizenscript.com/View/122169

### saves.yml

https://paste.denizenscript.com/View/122170

### Description

im using geysermc to use my server in java and bedrock clients.

citizens work good, but, to the any hologram on npc, cause fucking extreme lag on bedrock clients.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by adalmo** [comment]
I am getting same issue and report it on citizens dc

**Comment by Logikoz** [comment]
> I am getting same issue and report it on citizens dc

apparently, because it has online-mode: false, citizens does not support these bugs...

but if you activate online-mode: true, I believe the problem will be resolved.

But in my case, even though I try everything original, other players can't afford it!

**Comment by CayanNet** [comment]
well i am running on online-mode: true with velocity uh

**Comment by CayanNet** [comment]
Citizens-2.0.33-b3382 can u try with this build to test? i was fine with this build

**Comment by jakey1995abc** [comment]
> https://wiki.citizensnpcs.co/Cracks

I have online mode set to true and am having the exact same issue as originally described. Can I get help with the issue please?

**Comment by fullwall** [comment]
Please join on discord

**Comment by Logikoz** [comment]
@mcmonkey4eva reopen issue pls

**Comment by fullwall** [comment]
@jakey1995abc join on discord to get support with this issue.
I am locking this issue now as it was opened by a cracked user.
