### ISSUE TITLE
Server says that the plugin is disabled

### ISSUE THREAD

**Issue by Sissari77** [CitizensDev/Citizens2#3119]
### `/version` output

```txt
Paper-1.20.4-496
```

### `/version Citizens` output

```txt
2.0.34-SNAPSHOT (build 3416)
```

### Log file

https://paste.denizenscript.com/View/122668

### config.yml

https://paste.denizenscript.com/View/122670

### saves.yml

https://paste.denizenscript.com/View/122669

### Description

Hi! When I type /npc, it says in the chat 
**"An iternal error occurred while attempting to perform this command"**.
And in the log it says that the plugin is disabled.
![Näyttökuva 2024-05-13 171158](https://github.com/CitizensDev/Citizens2/assets/116287118/bf8a816a-68f7-44c7-84a7-32575fc5f600)
It worked fine until i updated my paper version _(1.20.4 paper 344 → 1.20.4 paper 496)_.
Please help me thanks!

**Comment by mcmonkey4eva** [comment]
General support is on Discord - https://discord.gg/Q6pZGSR 

Latest dev builds are for MC 1.20.6, you need to either grab an old 1.20.4 build of the plugin, or update your server (probably the downdate option as .6 isn't very stable yet)

**Comment by Sissari77** [comment]
Bro it didn't help
![image](https://github.com/CitizensDev/Citizens2/assets/116287118/45677ff9-f352-4600-a334-07269c93d5ef)
Now the server doesn't even find the plugin💀

**Comment by fullwall** [comment]
Post your logs again (or join discord)

**Comment by Sissari77** [comment]
there u go: https://paste.denizenscript.com/View/122692

**Comment by fullwall** [comment]
This is an error with parkour, not citizens
