### ISSUE TITLE
Error downloading library on server start

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [CitizensDev/Citizens2#3121]
### `/version` output

```txt
[13:52:29 INFO]: Checking version, please wait...
[13:52:32 INFO]: This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-550 (MC: 1.19.4)
```

### `/version Citizens` output

```txt
[13:52:51 INFO]: Citizens version 2.0.35-SNAPSHOT (build 3437)
[13:52:51 INFO]: Website: https://www.citizensnpcs.co
[13:52:51 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/123945#246

### config.yml

https://paste.denizenscript.com/View/123946

### saves.yml

https://paste.denizenscript.com/View/123947

### Description

I am updating my server from 1.19.4 to 1.20.6. I have gotten most of the plugins updated, but one of the ones causing some issues is Citizens. I saw that someone in the discord had this problem last year and tried following the same steps they used to solve it (run the plugin on another server, then manually copy the library to the folder), but that still did not work. I put file at `/plugins/Citizens/lib/ch/ethz/globis/phtree/phtree/phtree-2.8.0.jar`.

**Comment by fullwall** [comment]
Does your server not allow connections to maven central?

**Comment by MinecraftMan1013number2** [comment]
I'm not sure. Is there some way for me to check?

**Comment by fullwall** [comment]
Yes, see if maven.apache.org/repository is reachable

**Comment by fullwall** [comment]
You could ask your server host support

**Comment by MinecraftMan1013number2** [comment]
They have confirmed that it is an issue with their servers.
