### ISSUE TITLE
Doesn't work on Paper 1.21

### ISSUE THREAD

**Issue by andrew121410** [CitizensDev/Citizens2#3125]
### `/version` output

```txt
This server is running Paper version 1.21-38-master@1f5db50 (2024-06-27T20:15:58Z) (Implementing API version 1.21-R0.1-SNAPSHO>
```

### `/version Citizens` output

```txt
Citizens v2.0.34-SNAPSHOT (build 3429)
```

### Log file

https://paste.denizenscript.com/View/124156

### config.yml

Not needed.

### saves.yml

Not needed.

### Description

Fix is here https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

Probably doesn't work on Paper 1.20.6 either, because of that change above.

**Comment by fullwall** [comment]
You are using an outdated build

**Comment by andrew121410** [comment]
Oh I thought I updated the jar before making this issue, but I accidentally uploaded the new .jar to my other Minecraft server. I apologize
