### ISSUE TITLE
NPC vanish, but they exist

### ISSUE THREAD

**Issue by Corpse710** [CitizensDev/Citizens2#3127]
### `/version` output

```txt
This server is running Paper version 1.21-60-master@70ff1ec (2024-07-12T07:54:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-57-0e02aa5 (MC: 1.21)
```

### `/version Citizens` output

```txt
2.0.35-SNAPSHOT (build 3445)
```

### Log file

https://paste.denizenscript.com/View/124543

### config.yml

https://paste.denizenscript.com/View/124544

### saves.yml

https://paste.denizenscript.com/View/124545

### Profiler report

N/A

### Description

I can no longer see the NPC, but they exist. I make them shops; everything was right like two days ago, now they vanish :(((
![2024-07-12_11 01 04](https://github.com/user-attachments/assets/7d813c5a-3509-4038-8cd3-ca4a65fec189)

**Comment by ShadowMX93** [comment]
downgrade your papermc 1.21 to build #54 till a fix for citizens is released as paper changed a few things

**Comment by Corpse710** [comment]
> downgrade your papermc 1.21 to build 54 till a fix for citizens is released as paper changed a few things

ty

**Comment by mcmonkey4eva** [comment]
a patch was pushed earlier today
