### ISSUE TITLE
Can't remove/spawn/despawn NPCs, effects take place only by rejoining the server

### ISSUE THREAD

**Issue by NickDomanti** [CitizensDev/Citizens2#3129]
### `/version` output

```txt
This server is running Paper version 1.21-81-master@ceeb8c1 (2024-07-17T00:39:18Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-79-a6ceda1 (MC: 1.21)
```

### `/version Citizens` output

```txt
2.0.35-SNAPSHOT (build 3451)
```

### Log file

https://paste.denizenscript.com/View/124692

### config.yml

https://paste.denizenscript.com/View/124691

### saves.yml

https://paste.denizenscript.com/View/124690

### Description

I've created a couple of NPCs some time ago, one type villager with merchant features and all and one type warden for testing purposes, now, after some time has passed, I've noticed I can't do almost nothing with them.
Specifically, I've noticed that /npc remove doesn't remove the actual entity from the server, nor does /npc despawn, unless I LEAVE AND REJOIN THE SERVER, then the changes take place.
It looks like I have this issue for most commands, this doesn't seem to be limited to removing and despawning.
This is blocking all further tests with this plugin, since I have to restart the server for anything to happen...
While writing this, I tested if the commands worked properly with a newly created NPC, and they don't.
/npc create doesn't display the new NPC (although I can hear it), but it appears when rejoining the server.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
