### ISSUE TITLE
Trigger waypoints?

### ISSUE THREAD

**Issue by MDMeaux** [CitizensDev/Citizens2#313]
Is there a way to get an NPC to remain idle and then on a trigger / after an amount of time begin to follow a series of waypoints?
Is this possible with just the plugin, with Denizen or would I need to use the API?

**Comment by mcmonkey4eva** [comment]
Definitely possible through Denizen, via the pause/resume waypoints commands.

I believe base Citizens has an option to pause at certain waypoints, but I've never used it. (I prefer to just make things in Denizen). Hopefully someone else will see this and be able to explain how to do that if you don't want to use Denizen. (If you do want to use it, I can help you set that up).

**Comment by fullwall** [comment]
In Citizens to do this you need to follow these steps:

Enter the NPC path editor with /npc path
Select the waypoint you want to add a trigger to (using the item bar)
Type 'triggers' into chat
Type 'add' into chat
Type 'delay' into chat
Type the number of ticks to pause for
Type 'exit' to exit the editor
