### ISSUE TITLE
Showing Bedrock Players Skins on NPCs

### ISSUE THREAD

**Issue by Joshuak52** [CitizensDev/Citizens2#3133]
### `/version` output

```txt
This server is running Paper version 1.21-78-master@ef96a69 (2024-07-16T08:23:03Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3477)
```

### Log file

https://paste.denizenscript.com/View/124728

### config.yml

https://paste.denizenscript.com/View/124729

### saves.yml

https://paste.denizenscript.com/View/124730

### Description

So I don't know if this is more of a bug or just not knowing hw how to setup this up.
As you can see from my NPCs that MIRRROR with /npc mirror they show the bedrock skin correctly

![image](https://github.com/user-attachments/assets/90228b63-92ee-44fb-a11b-8048896f6f69)

But, when I go over to my statistics area where I set the top player for that statistic the players name through a place holder (works fine for java players) it just shows random Steve type skins.
![image](https://github.com/user-attachments/assets/5df6f2d7-40a3-4ed0-a4da-78929c20194a)

when I do /npc skin on one of these they do show the bedrock players name correctly but with a "." in front of the name.

Is there any way I can fix this? Thanks

**Comment by fullwall** [comment]
I have fixed this in new build
