### ISSUE TITLE
ConcurrentModificationException in Citizens Plugin During NPC Update

### ISSUE THREAD

**Issue by var1nthon** [CitizensDev/Citizens2#3134]
### `/version` output

```txt
This server is running Paper version 1.21-54-master@f250ec0 (2024-07-11T16:05:17Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 45 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-55-7bd22b1 (MC: 1.21)
```

### `/version Citizens` output

```txt
2.0.35-SNAPSHOT (build 3445)
```

### Log file

https://paste.denizenscript.com/View/124789

### config.yml

https://paste.denizenscript.com/View/124790

### saves.yml

https://paste.denizenscript.com/View/124791

### Profiler report

https://spark.lucko.me/8v2s3nc5se

### Description

**Plugin**: Citizens

**Error Type**: java.util.ConcurrentModificationException

**Log Details**:
The exception occurs during the update of an NPC with the ID 1.
The error is traced back to ArrayList$Itr.checkForComodification and ArrayList$Itr.next.
The update method in AbstractNPC at line 536 is attempting to iterate over a collection while it is being modified.
The stack trace shows the error propagating through several classes related to NPC updates and Minecraft server ticking mechanisms.

**Steps to Reproduce**:
Start a Minecraft server with the Citizens plugin installed.
Create and interact with NPCs.
The error may occur during the server's NPC update cycle, particularly if there are multiple threads interacting with NPCs simultaneously.

**Expected Behavior**:
NPCs should update without causing exceptions or errors in the server log.

**Actual Behavior**:
The server log shows a ConcurrentModificationException when updating an NPC, indicating that the collection of NPCs or related data is being modified concurrently.

**Possible Cause**:
The issue is likely due to the Citizens plugin attempting to modify a collection (e.g., a list of NPCs or related entities) while it is being iterated over in the update method of AbstractNPC.

**Potential Solutions**:
Ensure that collections are not modified during iteration. Use appropriate synchronization mechanisms or data structures that support concurrent modifications.
Review the update logic in AbstractNPC to identify and fix areas where concurrent modifications may occur.

**Relevant Code Sections**:
AbstractNPC.update(AbstractNPC.java:536)
CitizensNPC.update(CitizensNPC.java:477)
TextDisplayController$EntityTextDisplayNPC.tick(TextDisplayController.java:105)

**Notes**:
This bug may affect server stability and performance, as exceptions during the tick process can lead to broader issues.
Updating to the latest version of the Citizens plugin or reporting this issue to the plugin developers may provide a fix or workaround.

**Comment by fullwall** [comment]
https://wiki.citizensnpcs.co/Cracks
