### ISSUE TITLE
Citizens Plugin Fails to Enable with 'java.lang.VerifyError'

### ISSUE THREAD

**Issue by var1nthon** [CitizensDev/Citizens2#3135]
### `/version` output

```txt
This server is running Paper version 1.21-103-master@aa3b356 (2024-07-20T17:56:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-54-f250ec0 (MC: 1.21)
```

### `/version Citizens` output

```txt
2.0.35-SNAPSHOT (build 3445)
```

### Log file

https://paste.denizenscript.com/View/124821

### config.yml

https://paste.denizenscript.com/View/124822

### saves.yml

https://paste.denizenscript.com/View/124823

### Profiler report

https://spark.lucko.me/x1SWHEM0OI

### Description

When enabling the Citizens plugin (version 2.0.35-SNAPSHOT, build 3445) on a Minecraft server, the plugin fails to initialize and throws a **java.lang.VerifyError** This error occurs in the **NPCCommands.profession** method, indicating a type mismatch on the operand stack.

**Steps to Reproduce**
1. Install the Citizens plugin version 2.0.35-SNAPSHOT (build 3445) on a Minecraft server.
2. Start the server and observe the server log for errors during the plugin enable phase.

**Expected Behavior**
The Citizens plugin should enable without errors and function as expected.

**Actual Behavior**
The Citizens plugin fails to enable and throws a **java.lang.VerifyError**

**Comment by fullwall** [comment]
https://wiki.citizensnpcs.co/Cracks
