### ISSUE TITLE
Skins not loading due to using wrong session server.

### ISSUE THREAD

**Issue by sphynxgames** [CitizensDev/Citizens2#3137]
### `/version` output

```txt
This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)
```

### `/version Citizens` output

```txt
[15:25:46 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3382)
[15:25:46 INFO]: Website: https://www.citizensnpcs.co
[15:25:46 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/124987

### config.yml

https://paste.denizenscript.com/View/124989

### saves.yml

https://paste.denizenscript.com/View/124990

### Description

My server is hosted on an external server hoster, that is connected to minehut thru minehuts proxy.

This proxy is achieved by setting up the servers IP in minehut, then adding the commands to my startup to make it work as shown :
`Dminecraft.api.auth.host=https://authserver.mojang.com/ -Dminecraft.api.account.host=https://api.mojang.com/ -Dminecraft.api.services.host=https://api.minecraftservices.com/ -Dminecraft.api.session.host=https://api.minehut.com/mitm/proxy -jar server.jar`

Due to this, the citizens skin function to have custom skins on citizens does not work due to the session server being changed to **https://api.minehut.com/mitm/proxy**. 

This means instead of going to  https://sessionserver.mojang.com/session/minecraft/profile/5892b73415cf4d489e5c02b99dc89484 to retrieve a player skin, it is trying to goto https://api.minehut.com/mitm/proxy/session/minecraft/profile/5892b73415cf4d489e5c02b99dc89484 which will not return a skin.

There is an option in config.yml to use where the skins come from as seen on line 202 under Authlib
`
general:
  authlib:
    # Search for gameprofiles using this URL
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
`

Though, this seems to do nothing about the issue. I can not remove this startup command due to it breaking the proxy. Is there anyway that this could be fixed or there is something im not seeing? I do not wish to remove my proxy just to fix the plugin.

**Comment by fullwall** [comment]
Seems like a minehut issue.
