### ISSUE TITLE
Possible Memory Leak with Citizens and Sentinel

### ISSUE THREAD

**Issue by xEcho1337** [CitizensDev/Citizens2#3138]
### `/version` output

```txt
This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3439)
```

### Log file

https://paste.denizenscript.com/View/125083

### config.yml

https://paste.denizenscript.com/View/125081

### saves.yml

https://paste.denizenscript.com/View/125082

### Description

I'm making a 1.20 KitPvP server with NPCs and the server randomly crashes after some hours, I had this same issue a year ago but while making a 1.8 server instead with Citizens and Sentinel. The memory increases until for some reason it crashed, but not for a OutOfMemoryException, also I will provide spark logs in the next few days

**Comment by xEcho1337** [comment]
I just got a spark log here: https://spark.lucko.me/RBUKM6YNvH

**Comment by mcmonkey4eva** [comment]
that spark link doesn't load

**Comment by xEcho1337** [comment]
Probably because I made it with /spark profiler open, lol my bad

**Comment by fullwall** [comment]
Please post on discord with a working link and heapdump
