### ISSUE TITLE
my npc skins are turning into steves and alexs 

### ISSUE THREAD

**Issue by smach28** [CitizensDev/Citizens2#314]
this is ealy wierd i have citizens on splegit 1.8 and i ahve 16 npcs and wen i add more a npc's skin turns into a ale xor a steve whats funny is that teh boy skins turn into a alex and girl skins turn into steve pls help me whats going on with citizens

**Comment by smach28** [comment]
and now sighns are blank pls help me!!!!!!!!!!!!

**Comment by mcmonkey4eva** [comment]
- Learn basic English
- Signs have nothing to do with Citizens
- Skins defaulting is a known issue, use the existing issue pages.
