### ISSUE TITLE
Folia Support

### ISSUE THREAD

**Issue by SharkPika** [CitizensDev/Citizens2#3144]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

could u plz support folia? my survival server need it!

**Comment by mcmonkey4eva** [comment]
duplicate of https://github.com/CitizensDev/Citizens2/issues/3013
