### ISSUE TITLE
[Bug] [1.18.2-Paper] tried load plugin is failed

### ISSUE THREAD

**Issue by 8MiYile** [CitizensDev/Citizens2#3145]
### `/version` output

```txt
This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3526)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/125950

### config.yml

nope

### saves.yml

nope

### Description

i tried load this plugin 
get this error

**Comment by mcmonkey4eva** [comment]
PlugMan is unsupportable, and 1.18.2 is no longer supported, please update your server.
