### ISSUE TITLE
players hide

### ISSUE THREAD

**Issue by goncalodelima** [CitizensDev/Citizens2#3147]
### `/version` output

```txt
latest
```

### `/version Citizens` output

```txt
latest
```

### Log file

.

### config.yml

.

### saves.yml

.

### Profiler report

.

### Description

i just can see player if he quit, (my sleeping plugin create a citizens npc) and i kill him and i execute npc.destroy()) 
if i kill him player is invisible yet

**Comment by LegacyValken** [comment]
User is flagged as DNS on discord.
Discord id: 800441336310399046

**Comment by goncalodelima** [comment]
This server isn't even mine, I'm just trying to help. What do I do then? Do I tell him to come here and ask for help?
