### ISSUE TITLE
Skins do not work

### ISSUE THREAD

**Issue by FortuneMidnight** [CitizensDev/Citizens2#3148]
### `/version` output

```txt
Current Purpur Version: 1.21.1-DEV-b5a40ee (MC: 1.21.1)*
* Unknown version
Previous: 1.21.1-DEV-61a813c (MC: 1.21.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3537)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/126384

### config.yml

https://paste.denizenscript.com/View/126385

### saves.yml

https://paste.denizenscript.com/View/126386

### Description

Simply put, the skins do not work. NPCs that still had skins still have the skin. But as soon as I create a new one and set a skin there, it simply remains a default skin. I don't know exactly when the error started, but most probably since the update to 1.21.

**Comment by fullwall** [comment]
https://wiki.citizensnpcs.co/Cracks
