### ISSUE TITLE
NPCs hologram name may causing MSPT rise

### ISSUE THREAD

**Issue by EyE-ball** [CitizensDev/Citizens2#3149]
### `/version` output

```txt
This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
Error obtaining version information
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2886)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/126438

### config.yml

https://paste.denizenscript.com/View/126440

### saves.yml

https://paste.denizenscript.com/View/126441

### Profiler report

https://spark.lucko.me/uNZuiOp4zO

### Description

Our server has been experiencing a significant MSPT rise, and after reviewing the spark report, I identified that the primary cause is the Citizens, maybe related to hologramtrait, and I want to further optimize Citizens as Citizens occupy server thread's 33.43%. 
Additionally, when renaming NPCs with formatting codes (e.g., &e&l), their hologram names become bugged, shifting to the next line and overlapping with "[0 Health]." However, once the Citizens plugin was removed, the lag was resolved.

**Comment by fullwall** [comment]
Your server is running on 1.17.1 on a citizens build that is 20 months old. This issue likely doesn't exist on recent builds. Please update to 1.21.1 and should be resolved then.
