### ISSUE TITLE
Break tag broken, instead of newline it gives a "LF in box" character

### ISSUE THREAD

**Issue by andr3i1010** [CitizensDev/Citizens2#3150]
### `/version` output

```txt
[08:13:58 INFO]: Current Purpur Version: 1.21.1-2305-fdfc12e (MC: 1.21.1)*
* You are running the latest version
```

### `/version Citizens` output

```txt
[08:14:21 INFO]: Citizens version 2.0.35-SNAPSHOT (build 3559)
[08:14:21 INFO]: Website: https://www.citizensnpcs.co
[08:14:21 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/126510

### config.yml

https://paste.denizenscript.com/View/126508

### saves.yml

https://paste.denizenscript.com/View/126509

### Description

When adding a `<br>` tag in an NPC's name, instead of a new line i get a "LF in a box" character. 

![image](https://github.com/user-attachments/assets/49ab06af-d608-481d-ade5-a2d3a20cfc4a)

**Comment by mcmonkey4eva** [comment]
https://discord.gg/Q6pZGSR
