### ISSUE TITLE
CANNOT CREATE PLAYER NPC

### ISSUE THREAD

**Issue by MeoNguOfficial** [CitizensDev/Citizens2#3151]
### `/version` output

```txt
Leaf 1.21.1 (Build September 17th 2024)
```

### `/version Citizens` output

```txt
Citizens-2.0.35-b3566.jar
```

### Log file

https://paste.denizenscript.com/View/126620

### config.yml

https://paste.denizenscript.com/View/126621

### saves.yml

https://paste.denizenscript.com/View/126622

### Description

I can't create playerNPC on my server, i tried many server on same version but still not created
Video: https://streamable.com/j4i93y

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by MeoNguOfficial** [comment]
No, i mean player npc isn't show although my account is premium
