### ISSUE TITLE
Unable to create a player NPC on Leaf

### ISSUE THREAD

**Issue by miguotw** [CitizensDev/Citizens2#3152]
### `/version` output

```txt
This server is running Leaf version 1.21.1-DEV-ver/1.21.1@e62b6fc (2024-09-22T10:46:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Previous: 1.21.1-DEV-5cb2cb6 (MC: 1.21.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3558)
```

### Log file

https://paste.denizenscript.com/View/126738

### config.yml

https://paste.denizenscript.com/View/126740

### saves.yml

https://paste.denizenscript.com/View/126741

### Description

Unable to create an NPC of `--type minecraft:player` on Leaf. 
Reference video: https://youtu.be/EqlB2wo-W90

**Comment by mcmonkey4eva** [comment]
If you can replicate issues on Spigot/Paper, we can replicate them and fix them. Issues that only affect the Leaf fork are necessarily compatibility issues with Leaf and therefore should be reported to the Leaf team first, who could then report back to us if they believe it's on our side.

**Comment by fullwall** [comment]
There's a compat-mode setting in leaf config for this situation - async entity tracking related. Leaf never communicates with us. Very happy to work with leaf to fix this in Discord.
