### ISSUE TITLE
latest version doesn't work on 1.21

### ISSUE THREAD

**Issue by Kyles1201** [CitizensDev/Citizens2#3157]
### `/version` output

```txt
paper 1.21-130 master
```

### `/version Citizens` output

```txt
2.0.35-snapshot build 3433
```

### Log file

https://paste.denizenscript.com/View/127076

### config.yml

default config

### saves.yml

literally none

### Description

just doesn't load. Makes no sense there are like 5 versions on the spigot page that claim to work on 1.21, but none work so i guess citizens hasn't updated yet?

**Comment by mcmonkey4eva** [comment]
Use 1.21.1, not 1.21(.0), and latest dev build https://ci.citizensnpcs.co/job/Citizens2/
