### ISSUE TITLE
/npc mount

### ISSUE THREAD

**Issue by Thewest123** [CitizensDev/Citizens2#316]
When I type /npc mount, plugin say to me:

Please report this error: [See console]
java.lang.NoSuchMethodError:
net.minecraft.server.v1_8_r1.entityplayer.setpassengerof(Lnet/minecraft/server/v1_8_R/Entity;)V

latest.log : http://dl.vycraftito.eu/docs/latest.log (Line 325)

**Comment by mcmonkey4eva** [comment]
Update your server, that's an outdatedness bug.

**Comment by Thewest123** [comment]
I have latest Spigot (BuildTools.jar #35 from 1.3.2015)
/version = git-Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Should I downgrade the server?

**Comment by Morphan1** [comment]
That's not the latest spigot. The latest spigot is MC 1.8.3
maybe try redownloading the build tools if it says otherwise
