### ISSUE TITLE
NPC Shop exception when editing names

### ISSUE THREAD

**Issue by benaldo** [CitizensDev/Citizens2#3165]
### `/version` output

```txt
This server is running Paper version 1.21.1-128-master@d348cb8 (2024-10-21T16:23:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Previous version: 1.21.1-85-c5a1066 (MC: 1.21.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3583)
```

### Log file

https://paste.denizenscript.com/View/127548

### config.yml

https://paste.denizenscript.com/View/127549

### saves.yml

https://paste.denizenscript.com/View/127550

### Description

When I select an NPC to edit the shop, and I go to edit a text label on one of the shop objects (Or anything that calls up the anvil interface, it seems...)

It throws the exception you'll see towards the bottom of the log and I get kicked out of the shop edit UI. 

The shops work, it's just the editing functionality.

**Comment by benaldo** [comment]
Just to add: for funsies I rolled back our paper server jar and that fixed it. They broke something lol.

**Comment by SNWCreations** [comment]
1.21.1 is no longer supported. Use last prior build for it: build 3598
For further support, please follow Paper update when available.

**Comment by benaldo** [comment]
Ah, I grabbed my update from the Spigot page and it still said 1.21.1 was OK. 

Just loaded up the latest stable paper with the build# you suggest and it's working well, thank you!
