### ISSUE TITLE
The shop object type citizen is not enabled

### ISSUE THREAD

**Issue by Cinofi** [CitizensDev/Citizens2#3170]
I cant create new shopkeeper I am using "/shopkeepers npc" code but game writing "the shop object type 'citizen' is not enabled" and in the shopkeepers file and in config.yml "enable-citizens-shop: true" is opened but not working its the last log https://mclo.gs/Vp73vLK

**Comment by SNWCreations** [comment]
1.21.1 is no longer supported, pls use last build for it and try again: build 3598

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
