### ISSUE TITLE
citizens error on startup, paper 1.21.1

### ISSUE THREAD

**Issue by DEAMJAVA** [CitizensDev/Citizens2#3176]
### `/version` output

```txt
This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-130-b1b5d4c (MC: 1.21)
```

### `/version Citizens` output

```txt
[15:15:01 INFO]: Citizens version 2.0.36-SNAPSHOT (build 3608)
[15:15:01 INFO]: Website: https://www.citizensnpcs.co
[15:15:01 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/127707

### config.yml

https://paste.denizenscript.com/View/127708

### saves.yml

none

### Description

this is a newly created 1.21.1 server the configs has not been touched and it is failing to load

**Comment by SNWCreations** [comment]
https://wiki.citizensnpcs.co/Cracks

**Comment by SNWCreations** [comment]
Sorry for missing careful check on log. 1.21.1 no longer supported. use last prior build for it: 3598.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
