### ISSUE TITLE
When I do the command: /npc create...

### ISSUE THREAD

**Issue by yuuuup** [CitizensDev/Citizens2#318]
When I do the basic command /npc create I get this error:

jang.lang.NoClassDefFoundError: net/minecraft/server/v1_8R1/Packet

Please fix. I need this plugin as an essential part of my server. Thanks.

**Comment by mcmonkey4eva** [comment]
I don't get why people act like it's /our/ fault they don't know how to update a plugin.
http://wiki.citizensnpcs.co/Versions
