### ISSUE TITLE
Npc shop doesn't work

### ISSUE THREAD

**Issue by DamianNL1** [CitizensDev/Citizens2#3181]
### `/version` output

```txt
This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-130-4d2672e (MC: 1.21.1)
```

### `/version Citizens` output

```txt
This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-130-4d2672e (MC: 1.21.1)
```

### Log file

https://paste.denizenscript.com/View/127830

### config.yml

https://paste.denizenscript.com/View/127832

### saves.yml

https://paste.denizenscript.com/View/127833

### Description

I created a new npc, because i wanted to test the shop function. in the beginning it works fine but after when i try to click on "Edit shop title" the console gives me a warning, this also happens for me when i try to set the money cost and xp cost, it also gives me a error when i click on "Edit permission required to view shop"

**Comment by SNWCreations** [comment]
pls use last build for 1.21.1: [build 3598](https://ci.citizensnpcs.co/job/Citizens2/3598)

I remember that this is an issue which is already solved in a later build.

**Comment by DamianNL1** [comment]
i'm using the latest build i could download on spigot

**Comment by SNWCreations** [comment]
> i'm using the latest build i could download on spigot

Builds uploaded to Spigot is not reliable as they are rarely updates just to keep the resource page alive.

**Comment by DamianNL1** [comment]
Thank you for the help, the shop works fine now.
