### ISSUE TITLE
 NPC Names Disappear

### ISSUE THREAD

**Issue by CCjun6** [CitizensDev/Citizens2#3182]
### `/version` output

```txt
Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)*
* You are running the latest version
Previous: 1.21.1-2324-e12a4de (MC: 1.21.1)
```

### `/version Citizens` output

```txt
2.0.35-SNAPSHOT (build 3566)
```

### Log file

https://paste.denizenscript.com/View/127874

### config.yml

https://paste.denizenscript.com/View/127876

### saves.yml

https://paste.denizenscript.com/View/127878

### Description

NPC names sometimes mysteriously disappear and become completely invisible. I have to reload for them to appear again. This has happened many times. What could be causing this?
![image](https://github.com/user-attachments/assets/d37ce58c-b343-488b-b5cc-9024d607c20e)

**Comment by fullwall** [comment]
https://wiki.citizensnpcs.co/Cracks
