### ISSUE TITLE
Error on Startup: Could not fetch NMS field...

### ISSUE THREAD

**Issue by BigJoys** [CitizensDev/Citizens2#3183]
### `/version` output

```txt
[01:21:08 INFO]: Checking version, please wait...
[01:21:08 INFO]: This server is running Paper version 1.21.1-131-ver/1.21.1@84281ce (2024-10-31T17:43:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-14-fcb6c72 (MC: 1.21.3)
```

### `/version Citizens` output

```txt
[01:22:10 INFO]: Citizens version 2.0.36-SNAPSHOT (build 3633)
[01:22:10 INFO]: Website: https://www.citizensnpcs.co
[01:22:10 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/128079

### config.yml

https://paste.denizenscript.com/View/128080

### saves.yml

# Citizens NPC Storage  {}

### Description

When the server starts, the error appears in the log. Tested with the official version of Spigot (purchased) and the current dev version from today. After that Citizens is disabled.

> [01:24:00] [Server thread/ERROR]: [Citizens] Could not fetch NMS field ck: [[static final field has no write access: net.minecraft.world.entity.animal.armadillo.Armadillo.SCARE_DISTANCE_VERTICAL/double/putStatic, from class net.citizensnpcs.util.NMS (unnamed module @5d5c8c94).
> [01:24:00] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.36-SNAPSHOT (build 3633) (Is it up to date?)
> java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R2/boss/CraftBossBar
> 	at Citizens-2.0.36-b3633.jar/net.citizensnpcs.nms.v1_21_R2.util.NMSImpl.<clinit>(NMSImpl.java:2717) ~[Citizens-2.0.36-b3633.jar:?]
> 	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
> 	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
> 	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
> 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
> 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at Citizens-2.0.36-b3633.jar/net.citizensnpcs.api.util.SpigotUtil.lambda$getMinecraftPackage$1(SpigotUtil.java:171) ~[Citizens-2.0.36-b3633.jar:?]
> 	at Citizens-2.0.36-b3633.jar/net.citizensnpcs.api.util.SpigotUtil.getMinecraftPackage(SpigotUtil.java:176) ~[Citizens-2.0.36-b3633.jar:?]
> 	at Citizens-2.0.36-b3633.jar/net.citizensnpcs.Citizens.onEnable(Citizens.java:322) ~[Citizens-2.0.36-b3633.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
> 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
> Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R2.boss.CraftBossBar
> 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
> 	... 21 more

See more Detailed in Log.

**Comment by SNWCreations** [comment]
1.21.1 is no longer supported by latest builds and it seems that you have a downgrade from 1.21.3?
please use 1.21.3 to receive support, and this seems to be invaild.

**Comment by SNWCreations** [comment]
duplicate #3164 #3168 #3176
