### ISSUE TITLE
An error appears when starting the server

### ISSUE THREAD

**Issue by ZizionarD** [CitizensDev/Citizens2#3184]
### `/version` output

```txt
This server is running Pufferfish version 1.21.1-21-HEAD@cfa3c61 (2024-10-22T23:08:19Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.36-SNAPSHOT (build 3632)
```

### Log file

https://paste.denizenscript.com/View/128092

### config.yml

https://paste.denizenscript.com/View/128093

### saves.yml

-

### Description

The server is new and it doesn't want to run on it

**Comment by SNWCreations** [comment]
duplicate #3164 #3168 #3176 #3183
