### ISSUE TITLE
Citizens won't enable

### ISSUE THREAD

**Issue by OwlSeries** [CitizensDev/Citizens2#3186]
### `/version` output

```txt
1.21 papermc on minehut.com free server plan
```

### `/version Citizens` output

```txt
2.0356-SNAPSHOT (build 3637)
```

### Log file

https://mclo.gs/aWJV7Gq

### config.yml

Same here don't have that

### saves.yml

Doesn't have on server files for some reason

### Profiler report

https://spark.lucko.me/ljDyA71D2K

### Description

Citizens refuses to enable due to ```<html>
<body>

[12:54:58] [Server thread/ERROR]: [Citizens] Could not fetch NMS field ck: [[static final field has no write access: net.minecraft.world.entity.animal.armadillo.Armadillo.SCARE_DISTANCE_VERTICAL/double/putStatic, from class net.citizensnpcs.util.NMS (unnamed module @7a8ac76e).
--
350 | [12:54:58] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.36-SNAPSHOT (build 3637) (Is it up to date?)
351 | java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R2/boss/CraftBossBar
352 | at citizens-2.0.36-SNAPSHOT (4).jar/net.citizensnpcs.nms.v1_21_R2.util.NMSImpl.<clinit>(NMSImpl.java:2720) ~[citizens-2.0.36-SNAPSHOT (4).jar:?]
353 | at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
354 | at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
355 | at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
356 | at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
357 | at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
358 | at citizens-2.0.36-SNAPSHOT (4).jar/net.citizensnpcs.api.util.SpigotUtil.lambda$getMinecraftPackage$1(SpigotUtil.java:171) ~[citizens-2.0.36-SNAPSHOT (4).jar:?]
359 | at citizens-2.0.36-SNAPSHOT (4).jar/net.citizensnpcs.api.util.SpigotUtil.getMinecraftPackage(SpigotUtil.java:176) ~[citizens-2.0.36-SNAPSHOT (4).jar:?]
360 | at citizens-2.0.36-SNAPSHOT (4).jar/net.citizensnpcs.Citizens.onEnable(Citizens.java:322) ~[citizens-2.0.36-SNAPSHOT (4).jar:?]
361 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
362 | at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
363 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
364 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
365 | at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
366 | at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
367 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
368 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
369 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
370 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
371 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
372 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
373 | Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R2.boss.CraftBossBar
374 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
375 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
376 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
377 | ... 21 more

</body>
</html>  seems like error with armdillo I need to use citizens so can someone tell me why this is happening i have attemped other citizens2 versions

**Comment by SNWCreations** [comment]
1.21.1 is no longer supported. Use last build supporting it: [3598](https://ci.citizensnpcs.co/job/Citizens2/3598/). If it does not work then we had no idea as free servers are highly limited and we can't give full support for it. See more there: https://wiki.citizensnpcs.co/Frequently_Asked_Questions#I_have_a_free_server_(Aternos,_Minehut,_...)_but_there's_problems

**Comment by OwlSeries** [comment]
Ty for telling me but bro  wtf 1.21.1 just came out you already dropping support?

**Comment by SNWCreations** [comment]
> Ty for telling me but bro wtf 1.21.1 just came out you already dropping support?

_"We support only the latest patch-version of Minecraft for any recent main version (and Mojang, Spigot, Paper, etc. all generally also follow the same rule).
"Patch version" means the last number in a version label, for example in 1.20.6, the main version is 1.20, and the patch version is .6.
So if 1.20.6 is the latest patch version, then 1.20.3, and 1.20(.0) are all outdated patch versions, and therefore are unsupported.
Note that we do still support recent older main versions (such as 1.19 and 1.18) so long as you are on the latest patch-version of those main versions (like 1.19.4 and 1.18.2)."_ -- DenizenMetaBot on discord

**Comment by OwlSeries** [comment]
Also ty for sending me last version it worked

**Comment by SNWCreations** [comment]
> Fair but to be also fair 1.21.3 isnt' exactly stable enough for a big server personally

yeah, so you can stay on older ver but pls keep in mind upgrade when possible. Ending this discussion.
