### ISSUE TITLE
Strange and hard-to-explain behavior of the plugin: disappearing models from ModelEngine.

### ISSUE THREAD

**Issue by Ksewedo5** [CitizensDev/Citizens2#3187]
### `/version` output

```txt
[14:59:31 INFO]: Checking version, please wait...
[14:59:31 INFO]: Current Purpur Version: 1.21.1-2324-e12a4de (MC: 1.21.1)*
* You are 5 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: git-PufferfishPlus-46 (MC: 1.20.4)
```

### `/version Citizens` output

```txt
[14:59:54 INFO]: Citizens version 2.0.35-SNAPSHOT (build 3598)
[14:59:54 INFO]: Website: https://www.citizensnpcs.co
[14:59:54 INFO]: Author: fullwall
```

### Log file

No erros in console 

### config.yml

https://paste.denizenscript.com/View/128304

### saves.yml

https://paste.denizenscript.com/View/128305

### Description

Models from ModelEngine disappear from some NPCs. Citizens does not save the "meg_model" section in the configuration file. After manually adding this parameter to the configuration file and executing the command ./citizens reload, the models reappear. However, after some undefined period of time, both the models and the entries in the configuration file disappear again.

To reproduce the bug, follow the standard procedure:

./npc create
trait add meg_model
meg npc model CITIZENS add XYZ
Then simply wait for a certain amount of time, restart the server, or leave the world where these NPCs are located.

I would like to add that the specific models I want to use have already been utilized on another world, and the NPCs there behave normally. At the moment, this issue only affects one world. On other worlds, the issue occurred in the past but resolved itself spontaneously.

I also tried changing the permissions of the saves.yml file to 444. It seems to have helped a bit, as the models survived two server restarts... but could this just be a coincidence?

translated by ChatGPT

**Comment by fullwall** [comment]
This is a bug in modelengine, I am happy to help fix it but it seems that the modelengine team does not want to.
