### ISSUE TITLE
Cannot Edit My NPCs anymore

### ISSUE THREAD

**Issue by Raidmax24** [CitizensDev/Citizens2#3188]
### `/version` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3595)
```

### `/version Citizens` output

```txt
Citizens-2.0.35-b3595.jar
```

### Log file

https://paste.denizenscript.com/View/128364

### config.yml

https://paste.denizenscript.com/View/128365

### saves.yml

https://paste.denizenscript.com/View/128366

### Description

I suddenly can't edit or add or even remove an npc. 
I have over 400 NPCs on my server and this issue just began when i switched accounts.
NB: Op-ing others to dod it doesnt also work.
My server is running 1.21.1 and i have never had this issue before.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
