### ISSUE TITLE
Error when creating NPC

### ISSUE THREAD

**Issue by KingBsdp** [CitizensDev/Citizens2#319]
I have Citizens and DtlTraders installed, but whenever I try to use /trader create <Name> nothing happens, and when I try to use /npc create <Name> I get this:

Please report this error: [See console]
java.lang.NoClassDefFoundError:
net/minecraft/server/v1_8_R1

Unfortunately the plugin is spamming so much into the console I cannot single out what the error was, so I cannot help you there.

**Comment by mcmonkey4eva** [comment]
You've downloaded the wrong version of Citizens and/or dtl and/or any other plugin.
http://wiki.citizensnpcs.co/Versions assuming it's Citizens.

**Comment by KingBsdp** [comment]
Yup, it was Citizens. I was using the download from the bukkit page rather than using the dev downloads from Jenkins. I've updated to 2.0.15 snapshot and everything is working smoothly
