### ISSUE TITLE
Hologram-Placeholders that requires a player do not update automatically

### ISSUE THREAD

**Issue by DevJoey** [CitizensDev/Citizens2#3191]
### `/version` output

```txt
Current Purpur Version: 1.21.3-2345-55d4309 (MC: 1.21.3)*
```

### `/version Citizens` output

```txt
2.0.36-SNAPSHOT (build 3641)
```

### Log file

https://paste.denizenscript.com/View/128599

### config.yml

https://paste.denizenscript.com/View/128598

### saves.yml

https://paste.denizenscript.com/View/128597

### Description

If i use placeholder-api placeholders which are requesting player-based data, they will not update automatically in holograms or names. They stay static on the value the placeholder had when the placeholder was added. Thats not nice because cooldowns do not counting down and so on... Discord-report is ignored for days

**Comment by SNWCreations** [comment]
_Ref_: https://discord.com/channels/315163488085475337/1309949379372912750
Sorry if you feel your post was ignored, but actually we've seen it, fullwall may just have no spare time on it.
Please be patient. Thanks for understanding. :)
Maybe I'll look into this when I'm available. It depends.

**Comment by fullwall** [comment]
Your discord report wasn't ignored, I have been overseas for a few weeks. Remember that this is not my full time job and please be patient next time.
