### ISSUE TITLE
NPC attribute issues

### ISSUE THREAD

**Issue by Ovara** [CitizensDev/Citizens2#3192]
### `/version` output

```txt
This server is running Paper version 1.21.3-77-master@1e035f3 (2024-12-01T15:52:35Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are 2 version(s) behind
```

### `/version Citizens` output

```txt
Citizens version 2.0.36-SNAPSHOT (build 3642)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/128674

### config.yml

https://paste.denizenscript.com/View/128675

### saves.yml

https://paste.denizenscript.com/View/128676

### Description

When setting invalid attributes (as in attributes with invalid keys) on NPCs using /npc attribute, it returns an error, but still gets APPLIED and SAVED as "null". These "null"-key attributes cause errors on startup and load/reload, as well as prevent the adding of new attributes, even if they're valid.

**Comment by SNWCreations** [comment]
Can confirm. Writing a patch for that.
