### ISSUE TITLE
Helmet Replaced with Paper

### ISSUE THREAD

**Issue by groovyloopylou** [CitizensDev/Citizens2#3197]
### `/version` output

```txt
UniverseSpigot version 1.21.1-DEV-ver/1.21.1@c4c13f7 (2024-11-30T21:55:13Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Universe-1.21.1-DEV-c4c13f7 (MC: 1.21.1)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3583)
```

### Log file

https://paste.denizenscript.com/View/128762

### config.yml

https://paste.denizenscript.com/View/128763

### saves.yml

https://paste.denizenscript.com/View/128764

### Description

We apply a helmet to an NPC (successfully)
On server restart it turns to to a piece of paper

the uploaded saves file above is from after restart (when broken)

Here is the saves.yml file after it has been fixed on the server if you wish to compare them
https://paste.denizenscript.com/View/128765

We still have Citizens version 2.0.35-SNAPSHOT (build 3545) on our test server and it does not occur on that version, only on the main server with the versions at the top of this report.

**Comment by MC-Samuel** [comment]
Update to 1.21.3 and use a more recent build.
