### ISSUE TITLE
Class CraftBossBar won't allow plugin on Purpur 1.21.3

### ISSUE THREAD

**Issue by darkdex52** [CitizensDev/Citizens2#3198]
### `/version` output

```txt
Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version
```

### `/version Citizens` output

```txt
DNF (Citizens won't load, using plugin version 3646.
```

### Log file

https://paste.denizenscript.com/View/128798.txt

### config.yml

https://paste.denizenscript.com/View/128799.txt

### saves.yml

https://paste.denizenscript.com/View/128800.txt

### Description

Server won't start plugin, error here:

![image](https://github.com/user-attachments/assets/186b540f-21e1-4054-904a-cefad1c007c0)

**Comment by mcmonkey4eva** [comment]
latest builds are for 1.21.4, not .3 anymore. Last build for .3 was https://ci.citizensnpcs.co/job/Citizens2/3644/
