### ISSUE TITLE
[Error] Player registered twice with different NPC instances

### ISSUE THREAD

**Issue by VentureStudios** [CitizensDev/Citizens2#3199]
### `/version` output

```txt
This server is running Pufferfish version 1.21.3-27-HEAD@04bc249 (2024-12-04T01:51:20Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are on the latest version!
```

### `/version Citizens` output

```txt
Citizens version 2.0.36-SNAPSHOT (build 3644)
```

### Log file

https://paste.denizenscript.com/View/128811

### config.yml

https://paste.denizenscript.com/View/128809

### saves.yml

https://paste.denizenscript.com/View/128810

### Description

![image](https://github.com/user-attachments/assets/30023384-cf88-4091-9d90-d79b979e78e4)

Hi, I always get these errors in the console and I don't know how to resolve them.

**Comment by SNWCreations** [comment]
Known issue but still processing. See previous discussion on this there: https://discord.com/channels/315163488085475337/1308624182241660948
