### ISSUE TITLE
Update 1.21.4

### ISSUE THREAD

**Issue by yeying-xingchen** [CitizensDev/Citizens2#3201]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

Mojang has released the 1.21.4 update, which is very much new, and many servers will be updated.

**Comment by fullwall** [comment]
It is already updated.
