### ISSUE TITLE
Respect custom names

### ISSUE THREAD

**Issue by NonSwag** [CitizensDev/Citizens2#3203]
### I confirm that I have ...

- [X] ...tried the latest [Development Build](https://ci.citizensnpcs.co/job/Citizens2/) to make sure my feature doesn't exist already.
- [X] ...checked the Wiki for any possible information about my feature.
- [X] ...checked other existing issues for my feature request.

### Description

It would be a huge plus if the NPC name would only be used as display name if the custom name of the entity is not set
This would make it possible to define really complex names for entities without having to set it as the name
This would have the downside that it would only work from an API perspective, but it could also be added as a trait to be persisted
_or easier, just add a direct display name method to the NPC interface_

I would like to hear your thoughts on this and could also PR it myself if this is a feature that is actually wanted

### Code Example

```java
npc.getEntity().customName(MiniMessage.miniMessage().deserialize("<rainbow>this is my test entity"));
```

**Comment by SNWCreations** [comment]
As a workaround of this issue, the following code will: disable nametag visibility, create a hologram and make it act as custom name
```java
npc.setName("any name you want");
npc.data().set(NPC.Metadata.NAMEPLATE_VISIBLE, false);
npc().getOrAddTrait(HologramTrait.class).addLine("custom name here"); // we assume the NPC does not have any hologram yet
```

But yeah, maybe we should respect the API? leaving this to fullwall for further discussion.

**Comment by fullwall** [comment]
I need a bit more clarity here. Do you mean that you want the NPC name to be different in chat compared to on the NPC? @SNWCreations does show a way you can do that with the current API.

**Comment by NonSwag** [comment]
No I want a way to have a _friendly_ name and a display name
The friendly name is the unformatted name of the npc
The display name is what is actually shown

**Comment by SNWCreations** [comment]
Unformatted names are just only raw components, not so user-friendly. I also think we need a bit more clarity. how will you use the unformatted names?

**Comment by NonSwag** [comment]
The entire name implementation seems flawed to me
I would suggest using the name as how the npc is stored without color and formatting.
Custom names/display names would be what is displayed as the tag
If none is specified it will fallback to the name
This would make the list of NPCs way less cluttered when using components or even legacy colors in name tags

**Comment by SNWCreations** [comment]
> The entire name implementation seems flawed to me I would suggest using the name as how the npc is stored without color and formatting. Custom names/display names would be what is displayed as the tag If none is specified it will fallback to the name This would make the list of NPCs way less cluttered when using components or even legacy colors in name tags

Did you mean display the internal name in NPC list but display name for players for better display in `/npc list` output?

**Comment by NonSwag** [comment]
Exactly

**Comment by SNWCreations** [comment]
> Exactly

Fair. I agree about improving the display of `/npc list` but... this isn't an important feature we'll have to work first, I think I'll look into this but could have this progressed slowly. feel free to make a PR on your own if you wish to solve this and contribute your solution for everyone. :)

**Comment by NonSwag** [comment]
I will get to it if I got some free time

**Comment by fullwall** [comment]
I'm still confused, but if you want a way to make /npc list have a different name, that's not going to happen without a pull request since it's very low priority.
