### ISSUE TITLE
Citizens 2 Bug Console Spam

### ISSUE THREAD

**Issue by TSNCM** [CitizensDev/Citizens2#3205]
### `/version` output

```txt
[09:55:38 INFO]: This server is running Paper version 1.21.4-32-main@b8a0541 (2024-12-24T10:07:40Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.4-31-d0d0efe (MC: 1.21.4)
```

### `/version Citizens` output

```txt
[09:55:53 INFO]: Citizens version 2.0.37-SNAPSHOT (build 3659)
[09:55:53 INFO]: Website: https://www.citizensnpcs.co
[09:55:53 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/129363

### config.yml

https://paste.denizenscript.com/View/129362

### saves.yml

https://paste.denizenscript.com/View/129360

### Description

Hello, when I start my server, I get this error in the console.
You can see the error in the log file.

`[20:02:43] [Craft Scheduler Thread - 3 - Citizens/ERROR]: Got an error with a html body connecting to https://api.minecraftservices.com/minecraft/profile/lookup/bulk/byname: `

**Comment by SNWCreations** [comment]
Need full log to do analysis.

**Comment by TSNCM** [comment]
https://paste.denizenscript.com/View/129368

**Comment by SNWCreations** [comment]
Do you have many NPCs in your server? It seems to be rate-limited.

**Comment by TSNCM** [comment]
I have one NPC, and my friend has the same problem.

**Comment by SNWCreations** [comment]
HeadDatabase is found on your server. It has been known to cause issues with skins. Would you mind disabling it and try again?

**Comment by TSNCM** [comment]
I have deleted the Citizens folder and restarted, and the problem seems to be gone.
How can this be?

**Comment by SNWCreations** [comment]
> I have deleted the Citizens folder and restarted, and the problem seems to be gone. How can this be?

Might not be related to Citizens. Maybe HeadDatabase requested too many skins at once so your IP was temporary banned by Mojang's skin server at Microsoft Azure. Citizens may also cause this type of issue if you have many NPCs which have skins that only a name is known.

**Comment by TSNCM** [comment]
Ok, then I'll keep an eye on it to see if it comes back. Thank you very much for the help.

**Comment by mcmonkey4eva** [comment]
Judging by the nonstandard port `25592` you are potentially on a "cheap minecraft host" (ie: one of those services that sells you a minecraft install, not an actual server, and so the actual server has like 50 minecraft instances running on it) in which case Mojang has likely blocked the whole IP for too much constant activity, and you'd need to move to a server platform that isn't overprovisioned to avoid getting blocked.

**Comment by bobhenl** [comment]
I have similar issue too:
```yml
[06:42:02] [Craft Scheduler Thread - 8 - Citizens/ERROR]: Got an error with a html body connecting to https://api.minecraftservices.com/minecraft/profile/lookup/bulk/byname: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
```

But I don't understand why there's profile/lookup/bulk address
any idea, please? @mcmonkey4eva

**Comment by bobhenl** [comment]
maybe reopen it @TSNCM

**Comment by TSNCM** [comment]
> maybe reopen it @TSNCM

How can I do this?

**Comment by mcmonkey4eva** [comment]
There's not much we can do to help with Mojang's servers giving you a Forbidden response, other than suggest you don't spam their servers too much one way or another, and/or set your skins persistently not by name. See https://wiki.citizensnpcs.co/Skins for info

**Comment by TSNCM** [comment]
Yes, I am using /npc skin --url for custom skins, and it is working.

**Comment by bobhenl** [comment]
https://www.spigotmc.org/threads/403-forbidden-when-trying-to-whitelist-people.679754/
