### ISSUE TITLE
Citizens messing with commandblocks

### ISSUE THREAD

**Issue by Spartankiin** [CitizensDev/Citizens2#322]
I updated citizens recently, and have come to realize that the new version causes errors in a few commandblock commands, notably the ability to detect specific entities. For example, /testfor @e[type=Skeleton] no longer works, although it did on the previous version of Citizens. To make things strange, I have noticed that the command works fine with an empty save file, but under no other circumstance have i been able to get the command to work.

Thanks for reading, if you have any questions or need any clarifications, just let me know.

**Comment by fullwall** [comment]
@mcmonkey4eva - could this be related to the recent NMS map change?

**Comment by mcmonkey4eva** [comment]
@Spartankiin - Update again, we literally just fixed this in the latest dev build.

**Comment by Spartankiin** [comment]
Now i'm getting this in console "java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI"

**Comment by mcmonkey4eva** [comment]
... Wot.
