### ISSUE TITLE
Sentry Issue - Mounted NPC Waypoints Error

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#323]
Using latest versions of both Citizens 2 and Sentry on Spigot 1.8.3.

I create an NPC, add the Sentry trait, then mount that sentry. I then set a waypoint path however, the mounted sentry moves to the first one then just spins uncontrollably on that spot and doesn't move to the second waypoint.

No errors in the console, the only way to get it to move is to remove the mounted sentry.

**Comment by mcmonkey4eva** [comment]
Can you replicate this without Sentry?

**Comment by whoshenry** [comment]
Sorry, I'm on my phone at the moment. 

But the whole thing with the Mounting is that it is Sentry, so you can't do that without it right?

**Comment by mcmonkey4eva** [comment]
You can mount with a Denizen script

**Comment by whoshenry** [comment]
I don't have Denizen at the moment and have no need for it. So if it could be fixed for Sentry it would be very useful.

**Comment by mcmonkey4eva** [comment]
Sentry issues get reported on the Sentry page.
