### ISSUE TITLE
I have a problem, A BIG PROBLEM!!!!!

### ISSUE THREAD

**Issue by SonicBoom123** [CitizensDev/Citizens2#325]
Every time I try to create a Citizen I get an error code. Please report this error: [See Console] java.lang,NoClassDefDefFoundError:net/minecraft/server/v1_8_R1/Packet. I have no idea what this means but it is annoying the heck out of me. Someone please help me it would be greatly appreciated!

**Comment by mcmonkey4eva** [comment]
It means you downloaded the wrong version of Citizens for your minecraft version. Get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by FraazT0** [comment]
I have the same problem on Spigot 1.8.3, but there isn't a version for that Spigot!

**Comment by mcmonkey4eva** [comment]
Yes there is.
