### ISSUE TITLE
NPC skin command is not working.

### ISSUE THREAD

**Issue by Midgetking15** [CitizensDev/Citizens2#329]
Version build 1227 2.0.15
Spigot build 1.8.3 r0.1 snapshot
Version citzens api 448
Small gif of creating it an nothing happening: http://gyazo.com/ccb927b790912e61d301b0f4dfc0f50d
Gif of trying to name the npc different skins and nothing happening: http://gyazo.com/5c14ff1106954dbc5eaf81ab46b7c1ab
No error logs, or startup errors

**Comment by mcmonkey4eva** [comment]
Those gif's do not show what commands you're inputting, if any.

**Comment by Midgetking15** [comment]
First gif was just ./npc create Notch
Second gif I did /npc skin midgetking15, and /npc skin _jeb
also side error: http://gyazo.com/323f737b6993802c781d422325369103
all hats for a skin do not appear in one world

**Comment by mcmonkey4eva** [comment]
Well his name is `jeb_` not `_jeb` so... but yeah no it looks like it's working for you, just not in certain circumstances? Can you narrow down when exactly it doesn't work?

**Comment by Midgetking15** [comment]
Any single skin doesn't work, have tried countless, I've also tried 2 different servers 3 different spigot builds and 6 different citizens build, just any skin or creation of an npc with a player name does not show the skin, while previous skins that I already changed on npc's work fine

**Comment by mcmonkey4eva** [comment]
I don't know what to say. Maybe the skin server's down?

**Comment by Midgetking15** [comment]
ah actually just found a recent error in start up, might be related, might not be

**Comment by Midgetking15** [comment]
[23:16:29] [Server thread/ERROR]: Could not load 'plugins/citizensapi-2.0.15-SNAPSHOT (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-2f787bd-1a1bc08]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by mcmonkey4eva** [comment]
... You're not supposed to download CitizensAPI. 0.o

**Comment by Midgetking15** [comment]
Another staff member must've slipped it in there while updating, ill remove it and see if it was causing anything

**Comment by Midgetking15** [comment]
Yep, changed nothing

**Comment by Midgetking15** [comment]
anyone else able to test if they have the same error? Might be linux perms, bungee or something else on my side

**Comment by RyLogic** [comment]
Hey,

I have the same issue. I've tried different builds, but it still doesn't work. 
There are no error logs or something similar.

**Comment by Midgetking15** [comment]
I found out that the skins are just from to many request to mojang, but i havent been able to figure out why the hat skins don't appear,,,

**Comment by Midgetking15** [comment]
Tested it, the hat skin just wont appear for some worlds. I have deleted the player data for that world, disabled every plugin except citizens, what else could it be? something within the spigot or bungee config?

**Comment by Midgetking15** [comment]
Capes also appear to not be loading

**Comment by mcmonkey4eva** [comment]
Things working in latest (1.8.6)?
