### ISSUE TITLE
VERSION ERROR.

### ISSUE THREAD

**Issue by RealSkyWolf** [CitizensDev/Citizens2#330]
I recently downloaded cizitens plugin but I found out that it doesn't work for my server's version could you give me the link to download it for my servers spigot version (I think it is spigot 1.7.9). 

Thanks for spending the time to read my thread.

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by RealSkyWolf** [comment]
Pls send me the link to the specific version that I need. I have downloaded almost all the versions and nothing of them worked.

**Comment by mcmonkey4eva** [comment]
Be less lazy and follow the link I gave.
