### ISSUE TITLE
Custom inventory drop

### ISSUE THREAD

**Issue by MPPrison** [CitizensDev/Citizens2#332]
Hello, is there a way to drop a custom inventory when a NPC dies? so for example if I kill a Guard can I make it drop a beacon ? 

If this is not possible could you possibly make a feature? I would love this.

**Comment by mcmonkey4eva** [comment]
Use a short Denizen script for this -> http://wiki.citizensnpcs.co/Denizen

**Comment by MPPrison** [comment]
Ive been trying this but I can't get it to work. I want the npc called ''Guard'' to drop an item at his death location and give a death message how do I do this?

**Comment by MPPrison** [comment]
Never mind I got it thanks.
