### ISSUE TITLE
NPC Skins Not Showing Up For Anyone But Me

### ISSUE THREAD

**Issue by Blaze590** [CitizensDev/Citizens2#333]
So basically when I set an npc's skin through /npc skin <name> it doesnt show up as that skin for anyone else. I even did /citizens save.

Spigot 1.8.3

**Comment by mcmonkey4eva** [comment]
What Citizens build #?

**Comment by Blaze590** [comment]
2.0.14 SNAPSHOT

**Comment by mcmonkey4eva** [comment]
That is neither a build number, nor is it a version you could possibly be running.
only 2.0.15 is compatible with 1.8.3, 2.0.14 is for 1.8

**Comment by mcmonkey4eva** [comment]
So... update your server :)
