### ISSUE TITLE
NPC Passive/Non-Passive Mode Bugged

### ISSUE THREAD

**Issue by Killstreak42069** [CitizensDev/Citizens2#336]
Hello, I'm just reporting that the passive mode for NPCs is bugged. On my server I set an NPC to non-passive mode, meaning it should attack entities. Unfortunately, the NPC will not attack hostile mobs, passive mobs, or players, even if they attack the NPC. I've tried several different NPCs and I've tried several different things to make the NPC attack, but none of them have worked. If anyone could help, I'd surely appreciate it.
Thanks in advance,
~Killstreak42069

**Comment by mcmonkey4eva** [comment]
Where are you seeing a `passive` setting?

**Comment by Morphan1** [comment]
@mcmonkey4eva there is a command: `/npc passive`
However, I don't think there's any code in Citizens itself that makes NPCs attack. I think it just disables other plugins from damaging an entity with the NPC. 
I could be wrong, but that's as far as I'm aware

**Comment by mcmonkey4eva** [comment]
Oh.

Well, either way.

You have 4 main choices here:
- Use normal entities if you want normal entity AI
- Use a plugin like Sentry -> http://wiki.citizensnpcs.co/Sentry
- Use a script like dSentry -> http://mcmonkey.org/denizen/repo/entry/0
- Make your own plugin/script to handle combat AI

The whole point of a Citizens NPC is that they /don't/ attack things by default.
