### ISSUE TITLE
Some animations not working

### ISSUE THREAD

**Issue by uledrith** [CitizensDev/Citizens2#337]
I've done thorough testing with the 'animate' command. The following animations have issues:

To replicate, simply do the following:
 /npc create BoB 
 /ex equip <npc> hand:i@apple 
 /ex animate <npc> animation:eat_food  (does nothing - tried multiple types of food in hand)
 /ex animate <npc> animation:start_use_item  (does nothing - tried equipping multiple items in npc's hand)
 /ex animate <npc> sleep  (npc's nameplate appears around the npc's knees, but npc stays standing)
 I tried putting the npc on top of a bed with the sleep command, but still does exact same thing.

I'm on latest dev build (2.015-snapshot (build 1228).

Thanks!
 Uledrith

**Comment by fullwall** [comment]
You're right... seems like the eat food animation packet has been removed.
