### ISSUE TITLE
Sentry Bug 1.8 or Citizens2 1.8

### ISSUE THREAD

**Issue by MCNaruto** [CitizensDev/Citizens2#338]
Hi we are hosting a new Naruto Server that's trying to add a Clone jutsu. The clone works fine ,but it's supposed to follow me and attack it works in 1.7.9 ,but not in 1.8. Like the sentry plugin dosent work together with citizens or denizen

**Comment by mcmonkey4eva** [comment]
Report Sentry bugs on the Sentry page, not here.
