### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by tara81** [CitizensDev/Citizens2#339]
Tried multiple citizen versions and still getting crashes , I think maybe one of my citizens is corrupted? How can I tell ?

Here are the crash logs:
http://pastebin.com/TMGL6u8r
http://pastebin.com/PRqCY0cS

**Comment by mcmonkey4eva** [comment]
That's quite possible. Can you narrow down which NPC it is and post the saves.yml entry for this NPC?

**Comment by tara81** [comment]
Not sure how to tell i have 6 pagers of npcs. I will teleport to each later tonight and see if it crashes.

**Comment by mcmonkey4eva** [comment]
Based on the lack of response, I'm assuming this is solved.

**Comment by tara81** [comment]
Sorry I have so many citizens, and after the 3 times it crashed within 2
days, it suddenly stopped.  Very odd.

**Comment by tara81** [comment]
But since it stopped , I cannot troubleshoot and am glad the problem
disapeared =)
