### ISSUE TITLE
Heads on NPC Equip not staying

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#340]
When I try and equip an NPC with a head, it works perfectly fine, then I save the citizens plugin then reload it and the head disappears.

**Comment by mcmonkey4eva** [comment]
Is this still an issue in the 1.8.6 builds?

**Comment by whoshenry** [comment]
Haven't tested yet as 1.8.6 means upgrading other plugins, is Citizens 1.8.6 version backwards compatible to 1.8.x?

**Comment by whoshenry** [comment]
Just tested it on the Spigot 1.8.3 build as that's the version that all plugins I have are compatible with, and it didn't work. I will just have to wait for other plugins to update to 1.8.6 unless you guys can offer backwards compatibility? It can't be just me waiting for other plugins to update to the latest Spigot.

**Comment by mcmonkey4eva** [comment]
Either I'm misunderstanding this issue, or I failed to recreate your issue.

I equipped a skeleton skull on one NPC, and a human skull with my own skin on a second NPC.
I then restarted the server.
When I got back, both skulls were exactly as I made them.

**Comment by whoshenry** [comment]
I am using Build 1227. I think I see the issue, I just tried it with my own skin head and it worked correctly, however, I tried it using a head from this website - http://heads.freshcoal.com/heads.php that basically gives custom heads via a commandblock in-game. When I equip an NPC with one of those heads, it works correctly, I do /citizens save then /citizens reload and when it loads back up, the head disappears.

**Comment by mcmonkey4eva** [comment]
Can you give me a sample of a head thingy from there (IE, the command I spawn it or whatever), as that website doesn't function properly for me.

**Comment by whoshenry** [comment]
Sure, paste this into a Command Block and then equip the NPC with the head - http://pastebin.com/kDcFWZCj

**Comment by mcmonkey4eva** [comment]
It dooesss indeed break. That's very weird. @fullwall ?

**Comment by fullwall** [comment]
Fixed.
