### ISSUE TITLE
Skins and MobType still not working in #1228

### ISSUE THREAD

**Issue by Echen-kraul** [CitizensDev/Citizens2#341]
I am still having issues with skins as some show up but others dont, doing /citizens reload will refresh the citizens int eh immediate area but farther away.... like 16 blocks or so.... citizens that had skins will revert back to steves, also at this time i am still unable to create mobtype citizens.

/npc create [somename] --type [WITHER]

WITHER ins not a valid mob type.

this is true for any mob with any id formating... ie; WITHER, Wither, wither, WITHERBOSS, WitherBoss, witherboss, WITHER_BOSS, and on and on

ive tried SKELETON, ZOMBIE, WITHER, BLAZE, all return not valid mob type.

**Comment by mcmonkey4eva** [comment]
Don't put [] on the word `wither`

**Comment by Echen-kraul** [comment]
awesome its been a minute since we've set up npc's thanks man that was quick

**Comment by Echen-kraul** [comment]
another odd thing. if i log out and back in np's in the area where i logged out that didnt have the right skins will now have their skins while others farther away... again it seems around 16 blocks or more no longer have their skins and are alexs and steves. not sure if this helps any but it seems that the plugin is skinning them it just isnt sending the packet information to the client properly.

**Comment by mcmonkey4eva** [comment]
Skin trouble goes here -> https://github.com/CitizensDev/Citizens2/issues/223
