### ISSUE TITLE
Issues with Guided Waypoints

### ISSUE THREAD

**Issue by Zombie-Droid** [CitizensDev/Citizens2#342]
I've set up some guided waypoints and have found some buggy behaviors. The biggest issue I'm running into is clearing the existing waypoints. Ideally I'd like to be able to remove individual guide/destination waypoints but also the clear command doesn't appear to function either. These issues were discovered after encountering an issue with the toggle path command which the editor help indicates would toggle showing the entities at the waypoints. When using the toggle path command I receive the messages indicating it's being turned on or off but the eyes remain. Also all of the above commands including removing individual waypoints and clearing the waypoints list work as expected in Linear mode. The only "buggy" behavior I'm getting from linear is that typing exit doesn't close out the editor you have to type the /npc path command to exit.

**Comment by mcmonkey4eva** [comment]
Where does it say to type `exit` to leave the editor? That's not the proper exiting method 0.o

**Comment by Zombie-Droid** [comment]
I'll have to double check but I believe I received that in the prompt when
you enter the editor. This was on an older build so it may not be the case
currently. I will email you back this afternoon to confirm if it's still
the case and where I saw this specifically.

**Comment by fullwall** [comment]
Sometimes you need to relog to actually hide the entities that you have removed.
