### ISSUE TITLE
Still can't make wolves angry

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#343]
I am doing the correct command and I have posted it as an error on Spigot, referenced here - https://hub.spigotmc.org/jira/browse/SPIGOT-735

Any idea if there's a fix?

**Comment by mcmonkey4eva** [comment]
It was determined to be a minecraft limitation - you can't make wolves angry without supplying a target now.

**Comment by whoshenry** [comment]
But I am using it with Sentry and using players as targets and they are aggressive. Will this still not work? How can a plugin like EchoPet work with angry wolves then?

**Comment by mcmonkey4eva** [comment]
It's a question of who we make the target really... we don't know who the target should be for creating an angry wolf... it has to be angry at /someone/, but who

**Comment by whoshenry** [comment]
I see, could you make it target the creator of the NPC and every other player nearby within their range? Or maybe when a player enters their range set by sentry they turn into angry wolves?

**Comment by mcmonkey4eva** [comment]
Muahahaha... I've gone mad with power, and located an... alternate solution >:D

**Comment by whoshenry** [comment]
Haha great.
