### ISSUE TITLE
can not run citizens

### ISSUE THREAD

**Issue by Elioz** [CitizensDev/Citizens2#346]
Hi there,

I'm trying to run versions of citizens from jenkins to try to fix the skins reset issue but when I run the server, the plugin is loaded but i'm unable to write citizens commands.
Tried to run version 2.0.15

I'm using spitgot 1.8.3

Thanks!

**Comment by mcmonkey4eva** [comment]
Log?

**Comment by Elioz** [comment]
@mcmonkey4eva 
http://pastebin.com/dK8u94X3

**Comment by mcmonkey4eva** [comment]
[13:40:21] [Server thread/ERROR]: [Citizens] v2.0.15-SNAPSHOT (build 1228) is not compatible with Minecraft v1.8 - try upgrading or downgrading Citizens. Disabling.

You're on 1.8, not 1.8.3

**Comment by Elioz** [comment]
@mcmonkey4eva 
Thanks! after upgrading to 1.8.3 it's working,
I have a question, there is a solution for the npc skins? if I leave the chunks the npc skin reset to steve
only after perform citizens reload it's working.?

Thanks

**Comment by mcmonkey4eva** [comment]
That issue discussion goes here -> https://github.com/CitizensDev/Citizens2/issues/223
