### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by shaggy2922** [CitizensDev/Citizens2#347]
When I tried to create a citizen this happened

19.04 09:46:48 [Server] WARN ... 28 more
19.04 09:46:48 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
19.04 09:46:48 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
19.04 09:46:48 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
19.04 09:46:48 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
19.04 09:46:48 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
19.04 09:46:48 [Server] WARN at java.lang.Thread.run(Unknown Source)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
19.04 09:46:48 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
19.04 09:46:48 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
19.04 09:46:48 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
19.04 09:46:48 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
19.04 09:46:48 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
19.04 09:46:48 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
19.04 09:46:48 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
19.04 09:46:48 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19.04 09:46:48 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
19.04 09:46:48 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
19.04 09:46:48 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
19.04 09:46:48 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions wrong version of Citizens.
