### ISSUE TITLE
Help! I can't Create a Npc!

### ISSUE THREAD

**Issue by xXAndreaaXx** [CitizensDev/Citizens2#348]
Hello,In my server when I do /npc or /citizens it wont work I do first /npc create and it get to like

The plugin is generating exception errors. 
20.04 20:02:00 [Server] ERROR Could not pass event EntityCombustEvent to Citizens v2.0.14-SNAPSHOT (build 1195)

And My server is 1.8.3 Server Ip: 69.175.55.51 and when I do /citizens, no /citizens create command pelase help I LOVE This Plugin! D=

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens, get the correct one at http://wiki.citizensnpcs.co/Versions

**Comment by xXAndreaaXx** [comment]
Thanks!

**Comment by xXAndreaaXx** [comment]
But idk how to download it like the 1.8.3 version and download it please!

**Comment by mcmonkey4eva** [comment]
... what?

**Comment by xXAndreaaXx** [comment]
like I dont find the 1.8.3 version for citizens,I cant find the link

**Comment by goodbyebluemonday89** [comment]
http://i.imgur.com/y2TWecE.png

^ Do this.

And then do this:
http://i.imgur.com/ZucKhNk.png
