### ISSUE TITLE
Citizens won't load

### ISSUE THREAD

**Issue by silentspectr** [CitizensDev/Citizens2#349]
Hi 
i'm on a 1.7.10 Cauldron server and when i try to install citizens, it won't activate 
and sentry neither because he don't find a version of citizens 
i tried with versions 2.0.12, 2.0.13 and 2.0.14 and i always got the same message:

"[16:24:52] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.12-SNAPSHOT (build 1114)
[16:24:52] [Server thread/ERROR]: [Citizens] v2.0.12-SNAPSHOT (build 1114)not compatible with Minecraft v{1}. Désactivation.
[16:24:52] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.12-SNAPSHOT (build 1114)"

i know that it's really obvious that the citizens version is incorrect but i tried with the last three versions  and they does not work 
is this a bug or something else ?

**Comment by mcmonkey4eva** [comment]
http://cauldron.minecraftforge.net/threads/citizens-2-1-7-10-b2-update.427/

**Comment by silentspectr** [comment]
thanks 
but it doesn't work 
i copied the zip file to my plugins folder 
i suppose this wasn't the way
so how do i install it on the server ? 

thanks

**Comment by mcmonkey4eva** [comment]
There's no .zip involved, only a .jar

**Comment by silentspectr** [comment]
oh 
i need some sleep :p 
i clicked the wrong link and went to the github page :p 
thanks
