### ISSUE TITLE
Citizens Not Working

### ISSUE THREAD

**Issue by Escudos** [CitizensDev/Citizens2#350]
Ok so im staff on a server that has citizens added and you can create npcs no problems about that but when you do a real persons username when you create it it will show them as steve or alex skins. I might be able to tell you the version if you ask but i need help with this. All the help i can get is appreaciated. :palm_tree: :smile:

**Comment by mcmonkey4eva** [comment]
Yeah the version would be helpful information here.

**Comment by mcmonkey4eva** [comment]
We'll reopen when you provide more information.
