### ISSUE TITLE
Citizens/Citizens2 won't Work.

### ISSUE THREAD

**Issue by Kenflame** [CitizensDev/Citizens2#351]
You See, I get a error when i run this plugin on Spigot 1.8.3, and this is the error: Please report this error: [See console] java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet. Please explain how/and why this error occurs, and how to fix it. Thanks.

**Comment by mcmonkey4eva** [comment]
Version mismatch, get the correct version here: http://wiki.citizensnpcs.co/Versions

**Comment by Kenflame** [comment]
Thanks, I was kinda stumped.
