### ISSUE TITLE
Creating new npc keeps disconnecting me

### ISSUE THREAD

**Issue by OneEyedKakuja** [CitizensDev/Citizens2#352]
Hi. Whenever i make a new npc with /npc create (name) it will kick me out with 'Disconnected From the server'. I tried to log back in but it wont let me and keep kicking me with that message. I looked at the console for my kick reason it said

[11:43:31] [Server thread/INFO]: OneEyedKakuja lost connection: Internal Exception: java.lang.NullPointerException
[11:43:31] [Server thread/INFO]: 

and the way i get back in is by removing all the npc.I'm wondering if it's the plugins that are not supported or either the version. My list of plugins> http://prntscr.com/6x3vep. Hope you can resolve this. Thanks :+1:

**Comment by mcmonkey4eva** [comment]
What version of Citizens? Of CraftBukkit?

**Comment by OneEyedKakuja** [comment]
Citizens: 2.0.13-Snapshot (for me other versions just don't work) Spigot: CraftBukkit version git-Spigot-1571 (MC:1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
Are you perhaps on the 1.8 protocol hack? We have a version for that: http://wiki.citizensnpcs.co/Versions

**Comment by OneEyedKakuja** [comment]
Um no. I checked and i was using 1.7.10 version. I also tried to use 1.7.4 but it didn't work out.

**Comment by mcmonkey4eva** [comment]
1.8 Protocol hack IS 1.7.10. Try the protocol hack version, just for giggles.

**Comment by OneEyedKakuja** [comment]
Still a nope

**Comment by mcmonkey4eva** [comment]
ER... apparently lost track of this issue. Have you gotten it working yet, or...?
