### ISSUE TITLE
Error message on citizen creation

### ISSUE THREAD

**Issue by DarthUtopia** [CitizensDev/Citizens2#353]
http://pastebin.com/1bVEtTvc
I am opped, I try to create a Citizen, and this
Other plugins:
Multiworld, Orebfuscator, NoCheatPlus, WorldEdit, PermissionsEx, WorldGuard, Essentials, WarpPortals, ProtectionStones, Essentialsspawn, EssentialsChat, BetonQuest
All at latest versions

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens2 -> get the correct one at http://wiki.citizensnpcs.co/Versions
