### ISSUE TITLE
Create --type player npc dissappears

### ISSUE THREAD

**Issue by KeithSt0ne** [CitizensDev/Citizens2#355]
1. When I create a new npc with the type player it disappears, I've also tried changing a mob type npc to a player type and it still disappears.

2. I see in the config options where it has this option, "removefromlist", does this allow the npc to show in the tab list? I would like for the player npc's to show in our tab list.

I'm using the latest version from here: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
`I would like for the player npc's to show in our tab list.` Banned by Mojang. Fake players online = bad.
`When I create a new npc with the type player it disappears` Interfering plugin most likely.
