### ISSUE TITLE
Guardian Waypoints

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#356]
I created a Guardian NPC and tried to set a waypoint but the guardian just stood still, even in mid air. Didn't move at all.

**Comment by ELJESTER** [comment]
I can second this, Guardians don't seem to move at all, even when setting them to controllable i cant move them.

**Comment by mcmonkey4eva** [comment]
Can confirm this - @fullwall ?

**Comment by fullwall** [comment]
Just fixed them updating.
