### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by Spartankiin** [CitizensDev/Citizens2#357]
Is it possible to give Citizens status effects?
And i'm not sure if this is just my config, but i can hear citizens talking to others and vice versa, and was wondering if its possible to disable that through config.

**Comment by mcmonkey4eva** [comment]
There is indeed a config option to change how far away NPC voices can be heard.

Assuming `status effects` means potion effects... no, you'd need a separate plugin for that, as Citizens does not natively track that.

**Comment by Spartankiin** [comment]
oh wow, awesome response time.
Is there a way to make citizen conversations totally private?

**Comment by mcmonkey4eva** [comment]
Set the view distance to 0. Nobody can be below 0 blocks away from an NPC, so it's effectively private.
Alternately, use a sub-plugin like Denizen -> http://wiki.citizensnpcs.co/Denizen -> which allows greater control of NPC interaction via scripting.

**Comment by Spartankiin** [comment]
ohh thanks!

**Comment by Spartankiin** [comment]
lol i also just found the line bystanders-hear-targeted-chat: true‏
