### ISSUE TITLE
NPC creation error

### ISSUE THREAD

**Issue by Rumba1313** [CitizensDev/Citizens2#358]
Server 1.8
Citizens c2.0.14-Snapshot (build 1195)

type: /npc create Rumba1313
receive the error " Please report this error java.lang.NoclassDefFoundError:net/minecraft/server/v1_8_R1/Packet"

Any advice on how to fix this so I can summon an NPC?

**Comment by mcmonkey4eva** [comment]
You're not running 1.8
Figure out what version you're really running, the get the correct version of Citizens from http://wiki.citizensnpcs.co/Versions

**Comment by Rumba1313** [comment]
Woo! That seemed to be the problem.
Thank you so much for a timely response!
