### ISSUE TITLE
Remove this unuse classes

### ISSUE THREAD

**Issue by madtomic** [CitizensDev/Citizens2#360]
[13:22:51 INFO]: [Citizens] Enabling Citizens v2.0.13-SNAPSHOT (build 1186)
[13:22:51 ERROR]: [Citizens] Unable to find Rhino classes - javascript scripts w
on't see non-CraftBukkit classes

Where can I edit to remove this error from build? I know it is not game breaking but I just don't like error messages. Any help would be great to get ride of this error.

Regards,
madtomic

**Comment by mcmonkey4eva** [comment]
Oh wow, this issue slipped right past me. Sorry.

Just ignore the message... or pull request to Citizens2 to fix the damn thing showing. It's only there because everyone's too lazy to patch it.

**Comment by fullwall** [comment]
Removed.

**Comment by madtomic** [comment]
Is this fix now?

**Comment by mcmonkey4eva** [comment]
Yes.

**Comment by madtomic** [comment]
What commit is this? I have an older version of mcmmo. I just need the part to remove it or can you please change it on my fork?

April 5 - https://github.com/madtomic/mcMMO

**Comment by mcmonkey4eva** [comment]
... this is Citizens, not mcMMO.

**Comment by madtomic** [comment]
Sorry, I link the wrong GitHub. What commit was the fix for Citizens ?
