### ISSUE TITLE
npc skin permissions

### ISSUE THREAD

**Issue by silentspectr** [CitizensDev/Citizens2#361]
Hi 
i just updated to 1.7.9 with citizens 2.0.13 and when i input the "/npc skin" command, it says that i don't have permissions.
what is the permission required to use this command ? 

thanks

**Comment by silentspectr** [comment]
Up

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/src/main/resources/plugin.yml#L648

**Comment by silentspectr** [comment]
Thank you 
it's an amazing feature :p
