### ISSUE TITLE
Commands not working....

### ISSUE THREAD

**Issue by AgentBeatzPH** [CitizensDev/Citizens2#363]
Look at this Picture:
http://bit.ly/1IzaCNg

Commands aren't working .-.

Citizens version:
2.0.11 (for MC 1.7.x)

Server version:
Spigot 1.7.5 Build #1387

Pls reply!

**Comment by Scorpionvssub** [comment]
same for me /citizen and /npc both dont work and im using spigot 1.8.3 which is latest build by spigot as far as recommended and options go.

**Comment by mcmonkey4eva** [comment]
The only times this happens is when you have the wrong version of Citizens2. Get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by JeromSar** [comment]
@mcmonkey4eva Wouldn't it be more logical if a descriptive error message was displayed instead? Commands failing to load is probably the last thing that should be happening if there is a version mismatch.

**Comment by mcmonkey4eva** [comment]
@JeromSar There /is/ one. In the console, at load time, then it blocks the plugin from loading to avoid further errors.

**Comment by JeromSar** [comment]
@mcmonkey4eva I see, perhaps there isn't a cleaner solution.
