### ISSUE TITLE
Citizens (2.0.14-SNAPSHOT) vanish upon death.

### ISSUE THREAD

**Issue by Zariem** [CitizensDev/Citizens2#364]
Hey, I encountered that my Citizens 'disappear' if I die. I also logged in with two accounts and let one account die. The one who got killed didn't see any of the citizens anymore, but he could push one of them around (without noticing). The one who didn't get killed saw the citizens all the time.

Do you already know how to fix this problem?
If so, I'd be really glad about a solution.

**Comment by mcmonkey4eva** [comment]
I sent in a patch, should only be a few days max before our lead dev sees it and pulls it in.
For now, the simplest patch is to teleport away and back, which will recalculate the NPC visibility.

**Comment by Zariem** [comment]
Oh okay thanks a lot :) I hope your patch will be added soon!

**Comment by Zariem** [comment]
Using snapshot 2.0.15 and the bug is gone :D yay!

**Comment by mcmonkey4eva** [comment]
@Zariem are you sure? We didn't pull the patch. unless a previous patch that you forgot to download unknowingly encompassed it?

**Comment by Zariem** [comment]
Yes, but i did not just change from Snapshot 2.0.14 to 2.0.15, but also from spigot 1.8.0 to spigot 1.8.3 (due to issues with a questing plugin)
I don't know why the bug is fixed there, but I tried it with and without op, killed my avatar and after the respawning the NPCs didn't vanish.
So... yes, I am pretty sure.
I still don't get why it works now and did not work before...
