### ISSUE TITLE
Works Fine But Creating NPC's Doesnt Work

### ISSUE THREAD

**Issue by MortalWombat44** [CitizensDev/Citizens2#367]
The plugin itself loads up and is great.

Then when you run the npc create command it breaks and doesnt work.

We have no prior Citizens files.

Version: 1.8.3

**Comment by mcmonkey4eva** [comment]
Download the proper version of Citizens here: http://wiki.citizensnpcs.co/Versions
(Most common issue, I'm taking a guess)

**Comment by MortalWombat44** [comment]
Thank you very much :o!

:D
