### ISSUE TITLE
npc spawning doesn´t work

### ISSUE THREAD

**Issue by freakys** [CitizensDev/Citizens2#368]
there is the error 
http://java.lang.NoClassDefFoundError:
net/minecraft/server/v1_8_R1/Packet

whats the problem?

what can i do?

**Comment by JeromSar** [comment]
@freakys You're using the wrong version of Citizens/Spigot (their versions are incompatible), check your versions and try again. :)

**Comment by mcmonkey4eva** [comment]
Can acquire the correct version here -> http://wiki.citizensnpcs.co/Versions
