### ISSUE TITLE
Traits

### ISSUE THREAD

**Issue by JeromSar** [CitizensDev/Citizens2#369]
Is there any reason why so many traits are defined in the plugin and not in the API? It seems rather counter intuitive since plugins hooking into the Citizens API wouldn't be able to access these traits cleanly.

**Comment by mcmonkey4eva** [comment]
Just hook into C2, it doesn't matter.

The specific reason they're define in C2 is C2 is the one with NMS access, which is needed for a lot of things. The C2 API is essentially just a list of version-independent C2 functions, where everything else is version-locked.

**Comment by JeromSar** [comment]
@mcmonkey4eva Aha I see, thanks for the quick reply. If I find a way to get some of the traits into the API without any side effects, would you accept a PR for that?

**Comment by mcmonkey4eva** [comment]
If you really want to, should be fine. I don't see why, though.
