### ISSUE TITLE
Crash on NPC create

### ISSUE THREAD

**Issue by finesthops** [CitizensDev/Citizens2#370]
Fresh install using snapshot for 1.7.10 works fine. NO NPCs created at this time.

Create an NPC and the server starts shutting everything down. After that it boots, shuts down over and over. 

From Server Log
http://pastebin.com/urnjBCK5

included there is the error in spigot i get. When I remove citizens entirely, this does not happen. It is only with citizens and at least 1 NPC created that this happens. 

Server Crash Log
http://pastebin.com/sX64sRBe

States right in it that it was caused by citizens.

**Comment by Talamar1** [comment]
Try using the latest build for 1.7.10
http://ci.citizensnpcs.co/job/Citizens2/1166/

**Comment by finesthops** [comment]
i did before, BUT installing that exact one from the link you provided just to say it was done.

**Comment by mcmonkey4eva** [comment]
Wrong version. http://wiki.citizensnpcs.co/Versions I think you're probably using the 1.8 Protocol Hack.

**Comment by finesthops** [comment]
I have not installed a protocol hack that I am aware of. Unless the fragnet version of spigot utilizes it.

**Comment by finesthops** [comment]
i will also try the protocol hack version as well since i have not tried it as the thought never occurred to me.

**Comment by finesthops** [comment]
1166, same results.... installing 1186 now

**Comment by finesthops** [comment]
so, 1186 is working.... but i have seriously looked everywhere i can find. i do not believe i have a 1.8 protocol hack installed. Primarily because i do not have any of the 1.8 blocks on the server. BUT... all is well that ends well.

**Comment by mcmonkey4eva** [comment]
1.8 hack means 1.8 clients can connect, it does not mean you get 1.8 blocks
