### ISSUE TITLE
More than 16 characters?

### ISSUE THREAD

**Issue by LavaGaming** [CitizensDev/Citizens2#372]
Hi,

I've not got any problems with NPCs, apart from this - is it possible to add more than 16 characters? I need to fit in '&2&lPLAY&r TNT Run' but it only takes '&2&lPLAY&r TNT R'.

Please help! D:

**Comment by ELJESTER** [comment]
Quote from mcmonkey4eva: 
"no, this is not possible. Why would we have added our own random character limit? A bit of logical analysis would reveal that this is an inherent limitation of Minecraft... because unlike Mojang, we are smart enough to not limit things that don't require limits."

So basically no, its a Minecraft limitation not Citizens :'|

**Comment by mcmonkey4eva** [comment]
It may be closer to being possible now than before - we're researching using scoreboard stuff to add prefixes/suffixes to player names, which would allow slightly longer nameplates. May be a while before we have it functional, if ever.

**Comment by LavaGaming** [comment]
Then how come servers like Mineplex and The Nexus have NPCs with more than 16 chars?

**Comment by ultiferrago** [comment]
It is possible to assign them to a team and utilize the teams prefix/suffix to achieve a name longer than 16 chars

**Comment by LavaGaming** [comment]
How do you add prefixes then?

**Comment by ultiferrago** [comment]
you would need another plugin to achieve these results. There maybe a vanilla way of achieving the result but I am unsure. Essentially create a team, then create a prefix for that team then assign the npc to the team

**Comment by LavaGaming** [comment]
So how am I supposed to add an NPC to a team? That's the thing I'm confused about o_O

**Comment by ultiferrago** [comment]
I don't know how to do it via minecraft only programmatically.



On May 21, 2015, at 3:43 PM, LavaGaming <notifications@github.com<mailto:notifications@github.com>> wrote:


So how am I supposed to add an NPC to a team? That's the thing I'm confused about o_O

-

**Comment by ryantheleach** [comment]
You would need to know the NPC's uuid and add that to a team.

**Comment by LavaGaming** [comment]
Can't find a plugin to add NPC prefixes, any help?

**Comment by LavaGaming** [comment]
Anyone?

**Comment by sanjay900** [comment]
I think some servers just put holograms above npcs.
