### ISSUE TITLE
NPC doesn't pathfind upon respawn after death

### ISSUE THREAD

**Issue by Gavster4** [CitizensDev/Citizens2#376]
NPC appears to lose its path if it was set to vulnerable and then killed with a respawn time. The NPC will respawn but will remain where it died. If a path node is deleted or added it will start back on its path again.

**Comment by Gavster4** [comment]
Nothing? Or do I need to restate the issue better?

**Comment by mcmonkey4eva** [comment]
Can you make a video / .gif of this behavior?

**Comment by Gavster4** [comment]
https://db.tt/XWkQd8kM is a video of my issue. NPC will teleport back to start properly when it reaches the end of the path away from the start point, but it is set to vulnerable and when killed it will respawn on the timer but it never returns to the path it was on even though path nodes are within reach. Removing a node, or adding a new node will trigger something that returns the npc to its path again.

**Comment by mcmonkey4eva** [comment]
Hm... I can confirm the issue, but I can't see any possible reason in the code this should be happening. Any ideas @fullwall ?

**Comment by fullwall** [comment]
Looking into it, thanks for the video.

**Comment by fullwall** [comment]
Hm, I can't confirm the issue.

**Comment by Gavster4** [comment]
You cant confirm, meaning does work for you but not for mcmonkey or myself? Can you confirm the versions you are using and I'll try to replicate on my end.

**Comment by Gavster4** [comment]
Anything else I can do to help on this,  or anything I can try?

**Comment by mcmonkey4eva** [comment]
I tried again on a clean install.
https://www.youtube.com/watch?v=nJ38AhIanm0&feature=youtu.be
Doesn't glitch.
@Gavster4 Try ... resetting your config maybe?
