### ISSUE TITLE
Red color but right version?

### ISSUE THREAD

**Issue by Jadhex** [CitizensDev/Citizens2#377]
So I am trying to get the plugin citizens for my gta server but whenever I download it it turns red I am using a spigot protocol hack could that be it?
I tried all the 1.7 versions so 2.0.11 - 2.0.13
I also get no errors is my console.
Does anyone know the problem? and the sollution?

Yours faithfully
Jadhex

**Comment by Morphan1** [comment]
http://wiki.citizensnpcs.co/Versions
