### ISSUE TITLE
NPE with Citizens upon Right Click also using HyperMerchant Trait

### ISSUE THREAD

**Issue by Cmoor** [CitizensDev/Citizens2#378]
Hey there, Im having a small issue with a certain npc who doesn't want to open the GUI for HyperMerchant. I am also using HyperConomy of course. Like I have done with other NPC's I have created one with:
/npc create SpawnEggs --type villager --trait hypermerchant
It does create the villager and i have setup the area around the villager marking what shop he belongs to. I removed all other items from him by using /ss ban all. I have added the correct category to him which is /ss addcategory mobeggs. It confirms that that it has been added. But as i go to right click him, first time I did I was in creative so I gms myself and then right click him for no output. Check the logs to see an error and here it is:
http://hastebin.com/lozobovaxe.avrasm

**Comment by mcmonkey4eva** [comment]
Hypermerchant error, not Citizens.

**Comment by Cmoor** [comment]
errr nevermind, i feel stupid. it was because i didnt setshop with the npc. oops xD
