### ISSUE TITLE
Error when creating npc

### ISSUE THREAD

**Issue by A4Papers** [CitizensDev/Citizens2#379]
Hi getting this error in console - http://pastebin.com/vKMp0fq1 when attempting to create a npc....With this error ingame - http://prntscr.com/75wmel

Server running 1.8.3 with citizens 2.0.14
Thanks, Sorry if something stupid aha

**Comment by mcmonkey4eva** [comment]
Wrong C2 version -> http://wiki.citizensnpcs.co/Versions

**Comment by A4Papers** [comment]
Ah... Thanks haha
