### ISSUE TITLE
1.8.4 Compatibility 

### ISSUE THREAD

**Issue by angrybirds85** [CitizensDev/Citizens2#382]
Plugin is appearing as red instead of green in the /plugins list, using latest Spigot build

**Comment by Morphan1** [comment]
It's in the process. #381
Please give it time when there is a new version, Citizens2 is extremely version-dependent, and we need to make sure it works.

**Comment by 100chilly** [comment]
Spigot is on version 1.8.5 now. Oh the joys of updates. Looking forward to see a release for this version hopefully. :D

**Comment by mcmonkey4eva** [comment]
Updated to 1.8.6 in the dev builds
