### ISSUE TITLE
HELP PLESE!

### ISSUE THREAD

**Issue by jakovkacan** [CitizensDev/Citizens2#383]
![2015-05-21_10 37 16](https://cloud.githubusercontent.com/assets/11645793/7744776/5530fbce-ffa6-11e4-9f0a-9e4dd52a61eb.png)

![2015-05-21_10 37 20](https://cloud.githubusercontent.com/assets/11645793/7744751/39b55b10-ffa6-11e4-8f52-d604d7e484a1.png)
HELP PLESE!

**Comment by mcmonkey4eva** [comment]
You're running Citizens 1.8 on a non-1.8 server - assuming you're not on 1.8.4, acquire the correct version here: http://wiki.citizensnpcs.co/Versions

**Comment by jakovkacan** [comment]
I have 1.8.4 server!

jakovkacan
Dana 21. 5. 2015. 10:45 osoba "mcmonkey" <notifications@github.com>
napisala je:

**Comment by mcmonkey4eva** [comment]
Then you have to wait for 1.8.4 Citizens to be ready

**Comment by mcmonkey4eva** [comment]
1.8.6 Citizens is ready for your usage.

**Comment by jakovkacan** [comment]
Thanks

jakovkacan
Dana 26. 5. 2015. 06:55 osoba "mcmonkey" <notifications@github.com>
napisala je:
