### ISSUE TITLE
getNPCRegistry() returning null

### ISSUE THREAD

**Issue by srfoster** [CitizensDev/Citizens2#385]
Looking at the source code, it looks this this should not be null after Citizens has been enabled.  But it is when I call it from my plugin.  Any ideas?

    Bukkit.getServer().getPluginManager().getPlugin("Citizens").getNPCRegistry()

I'm using the 2.0.15 snapshot from here: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
A: why not use `CitizensAPI.getNPCRegistry()`?
B: Where are you calling it from? an onEnable perhaps?

**Comment by Morphan1** [comment]
Also, shouldn't that be
```
((Citizens) Bukkit.getServer().getPluginManager().getPlugin("Citizens")).getNPCRegistry()
```

**Comment by srfoster** [comment]
Well, I was calling it at runtime from inside Scriptcraft (javascript engine), so it didn't require a cast.  

I also did a test from inside a normal Java plugin, though, and it was also null.

I was going to try CitizensAPI next, but I looked at the code and realized that it should be the same thing.

**Comment by mcmonkey4eva** [comment]
Citizens doesn't load at onEnable, it loads a tick late.

**Comment by srfoster** [comment]
Okay, so it turned out that I was just being dumb.  I was on an older version of Bukkit and hadn't noticed the error message from Citizens on startup.  So it just wasn't enabled.

Thanks for the help!  Citizens is really, really cool.  I'm excited to be learning more about how it works.
