### ISSUE TITLE
1.8.4

### ISSUE THREAD

**Issue by ke4zzy** [CitizensDev/Citizens2#386]
Just wanted to say Thank yo for the hard work. And good luck, we are all waiting on the new build.
We are checking back every hour or so.
Also just curious? Have you considered a Citizens Lite?
For people like our group that is only looking for...
Spawn toon and path? Would that be easier to keep up to date?

**Comment by mcmonkey4eva** [comment]
`1.8.4` https://github.com/CitizensDev/Citizens2/issues/382
If you need it /now/, compile it off the pull request.

`Have you considered a Citizens Lite?` Entirely pointless, we're more than capable of maintaining the full Citizens engine. The only thing slowing us down is the lead developer being less and less active... worst case scenario is he disappears... at which point, I will take over and ensure everything continues as normal, so no need to fear.
