### ISSUE TITLE
won't let me create an NPC, and I don't know wich version I DO need

### ISSUE THREAD

**Issue by nimbas1103** [CitizensDev/Citizens2#388]
i've used multiple versions, and I always get this as response: http://pastebin.com/intJ0rJE , what do I have to do? I use bukkit for 1.8.3, so wich version of citizens do I have to use?

**Comment by Morphan1** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by nimbas1103** [comment]
yeah, wich one do I have to choose from that link?

**Comment by mcmonkey4eva** [comment]
You're not allowed to use Citizens if you're not competent enough to read the versions lists and figure out which one is needed.

**Comment by nimbas1103** [comment]
I mean... if version 1.8.3 doesn't work on bukkit 1.8.3 (I am not THAT kind of a noob) then there must be something wrong here... blaming it all on me isn't very nice too.

**Comment by mcmonkey4eva** [comment]
It says, on that page,
`- 1230 1.8.3[2] `
Click the associated link. If that doesn't work, then post an error message received from that particular build.

**Comment by nimbas1103** [comment]
I found out the problem, after trying another version, I forgot to remove the other one (guess I AM that kind of a noob), so they were fighting wich one to do

**Comment by mcmonkey4eva** [comment]
Glad to see you got it working.
