### ISSUE TITLE
navigation of a ridden saddled horse

### ISSUE THREAD

**Issue by Tursiops1** [CitizensDev/Citizens2#389]
I can set the navigation of a unsaddled horse and code in a location to go. I can also do this with a saddled horse when it's not being ridden. However, a ridden saddled horse does not travel to the location given and only moves on keyboard inputs for directions. Is there a way to get the navigation to work with code for a ridden saddled horse?

**Comment by mcmonkey4eva** [comment]
This is a larger issue - NPC horses with saddles should not be mountable at all, unless `/npc controllable` is set.

**Comment by mcmonkey4eva** [comment]
And I can't seem to find a way to prevent that properly - @fullwall ?

**Comment by fullwall** [comment]
@mcmonkey4eva - yeah, VehicleEnterEvent should be covering this, not sure...

**Comment by mcmonkey4eva** [comment]
@Tursiops1 Is this still a problem in the latest build? If so, could you clarify the issue?
