### ISSUE TITLE
The trait sentry failed to load for NPC ID: x

### ISSUE THREAD

**Issue by cuddylier** [CitizensDev/Citizens2#392]
HI

I'm getting the following errors on citizens build 1232:

On startup and spamming while the server is running: http://pastie.org/pastes/10207272/text?key=kuan9u7lxfqp3mhvxtiwea

Using Spigot 1.8.6.

**Comment by mcmonkey4eva** [comment]
Update Sentry @.@

**Comment by cuddylier** [comment]
Would this be related to Sentry too? http://pastie.org/pastes/10207303/text?key=yif4setvvgfphnfch1ufsa

**Comment by mcmonkey4eva** [comment]
That'd be `Traders`
