### ISSUE TITLE
Creating NPC not working on server.

### ISSUE THREAD

**Issue by IceRaider** [CitizensDev/Citizens2#393]
When I type /npc create it doesn't work.. The NPC does not show in-game but it says the NPC was successfully created, I have tried disabling all my plugins except Citizens and Vault!
http://i.gyazo.com/c0b064027d80ea651d716bc0f7d9585f.png

**Comment by mcmonkey4eva** [comment]
Any console errors?
What version?

**Comment by IceRaider** [comment]
Thanks for the fast response, satest version released today, and latest Vault version.. And there are no console errors ): This is the only thing that shows 26.05 02:24:16 [Server] INFO [02:24:16 INFO]: [Citizens] Using cached skin texture for NPC Human UUID 8764589a-eea3-408c-9fc6-de3b4722624e

**Comment by fullwall** [comment]
Seems like a 1.8.5 issue.

**Comment by IceRaider** [comment]
I've had this issue in 1.8.3

**Comment by mcmonkey4eva** [comment]
I have no idea what to do with this issue.

**Comment by IceRaider** [comment]
It's fixed.
