### ISSUE TITLE
Spigot 1.8.6 - Npcs only on One World

### ISSUE THREAD

**Issue by Dennis000903** [CitizensDev/Citizens2#395]
When I join my Server after restart, no npcs are there. But when I type /citizens reload, all npcs spawning in the world i am, but not in the other worlds. When i go to another world an do the same, all npc on other worlds are go away and only the mobs in the world i typed are spawned. Please fix this. No error is created, it just seems to be a bug.

**Comment by Dennis000903** [comment]
And please excuse my bad grammar :D

**Comment by mcmonkey4eva** [comment]
What version of Citizens and Minecraft are you running?

**Comment by Dennis000903** [comment]
I am using the latest Spigot 1.8.6 and citizens2.0.16-Snapshot

**Comment by Dennis000903** [comment]
Okay on latest jenkins build, #1238, it works finally. Thanks.
