### ISSUE TITLE
Player model NPC's bugging

### ISSUE THREAD

**Issue by Fortifier42** [CitizensDev/Citizens2#396]
https://dl.dropboxusercontent.com/u/4208005/Bug%20Citizens2.mp4

- Do not face the right direction and steve is kinda bugged.

**Comment by mcmonkey4eva** [comment]
Link is a 404.

**Comment by Fortifier42** [comment]
Updated - sorry

**Comment by mcmonkey4eva** [comment]
That's a really old bug, it was fixed a while back. What version are you on?

**Comment by Fortifier42** [comment]
"citizens-2.0.15-SNAPSHOT.jar"

**Comment by mcmonkey4eva** [comment]
Update to MC 1.8.6 and Citizens 2.0.16 and see if you can still replicate it - if so, ... well we'll have a problem to deal with

**Comment by Fortifier42** [comment]
On it boss

**Comment by Fortifier42** [comment]
That seems to have done the trick - now to wait on the addons (trader, blacksmith etc to update...)

**Comment by Fortifier42** [comment]
New Video - Real skins attempted to be used - no skinning at all then.
https://dl.dropboxusercontent.com/u/4208005/Java%202015-05-27%2014-38-51-98-1.mp4

**Comment by mcmonkey4eva** [comment]
@Fortifier42 Once it starts bugging, it's bugged... doesn't really count as a replication video unless you do it on a *new* NPC.

**Comment by Fortifier42** [comment]
New NPC's not skinned at all. Couldn't immediately replicate the spasm
https://dl.dropboxusercontent.com/u/4208005/Java%202015-05-27%2014-43-42-59-1.mp4

**Comment by mcmonkey4eva** [comment]
Well now that's a whole different bug you got going on.

**Comment by Fortifier42** [comment]
Restarted server - replication of original bug.
https://dl.dropboxusercontent.com/u/4208005/Java%202015-05-27%2014-54-04-34-1.mp4

**Comment by mcmonkey4eva** [comment]
`<Morphan1> mcmonkey: looks like it occurs when you give them a valid name, and then change their skin to an invalid name`

**Comment by Fortifier42** [comment]
Just tested with /npc skin -p 0 and the bug didn't occur. Then tried /npc skin 0 and it happened again.

**Comment by fullwall** [comment]
Links are broken
