### ISSUE TITLE
Npc Toggle Path Bugged

### ISSUE THREAD

**Issue by Patthebadger** [CitizensDev/Citizens2#399]
Whenever I remove an npc's path with toggle path enabled it sometimes leaves behind eyes of ender (the marker). This is unintended and if possible is there a way to remove them?

**Comment by mcmonkey4eva** [comment]
You might just have to restart your server to clear them *for sure* >.>
Or just disable the markers entirely

**Comment by fullwall** [comment]
It's a client-side bug most likely. If you relog they will go away.
