### ISSUE TITLE
Bukkit 1.8.4

### ISSUE THREAD

**Issue by slingchilders** [CitizensDev/Citizens2#401]
What build of citizens2 should I use with Bukkit 1.8.4-R0.1?

**Comment by Morphan1** [comment]
There was no official C2 build for 1.8.4, as 1.8.5 and 1.8.6 came out pretty quickly afterwards.
Why not just update your server?

**Comment by mcmonkey4eva** [comment]
Either way, the latest dev builds should be compat with 1.8.4 since there was no NMS version bump.
