### ISSUE TITLE
Nametags

### ISSUE THREAD

**Issue by NDruce** [CitizensDev/Citizens2#402]
Nametags on mob-like NPCs displays only on mob target hovering. I suggest to add sub-command to disable rendering nametag on it (I will set nametag via HolographicDisplays plugin), or else render nametag above mob head all the time

**Comment by mcmonkey4eva** [comment]
You can set the name to `&r` or something and be mostly good.

**Comment by fullwall** [comment]
Minecraft disabled the flag which let you switch between the two different modes.

**Comment by OldTownMC** [comment]
And there is no work around for it @fullwall (just curious)?

**Comment by iBars** [comment]
But I say about you can allow FULLY disable mob name. You think, all default mobs has any nameplate above head? Nope.

**Comment by mcmonkey4eva** [comment]
@fullwall there's definitely a way /hide/ nametags, which is all they're requesting here.

**Comment by FusionDeck** [comment]
^ High priority feature.

**Comment by Fortifier42** [comment]
With 1.9 coming soon, this will become NBT data and this should fix the problem.
Rather than wasting resources coming to a fix now, shouldn't we wait till 1.9 when it is readily available?
>CustomNameVisible:true will make the name tag on mobs show in the same way as on players.
>http://minecraft.gamepedia.com/1.9#Command_format_2

**Comment by fullwall** [comment]
Fixed for not being able to hide nametags. Apologies, thought I had fixed it but there was another bug hiding it.
