### ISSUE TITLE
Sponge API Support!

### ISSUE THREAD

**Issue by nikosgram13** [CitizensDev/Citizens2#404]
Will there be a case to running this plugin from the Sponge?

https://github.com/SpongePowered/SpongeAPI

**Comment by Morphan1** [comment]
Most likely Citizens2 will wait until 1.9 to start development for Sponge, but it's too much of an incomplete API at the moment to do it now. They seem to have just fully implemented human entities though, so that's gonna be amazing for making C2 one step closer to not being able version-dependent.

**Comment by mcmonkey4eva** [comment]
In theory, if Sponge fulfills its plans, Citizens will be 100% version independent.

**Comment by nikosgram13** [comment]
Yeah true, but we can start working with the Sponge and now. :smile:

**Comment by mcmonkey4eva** [comment]
Sponge is not yet complete enough to develop large-scale plugins like Citizens for it.

**Comment by MrMaleficus** [comment]
Any updates ? :)

**Comment by Rubbertjuh** [comment]
Would love to see this being added ^^

**Comment by mcmonkey4eva** [comment]
Citizens for Sponge is being slowly worked on, but it may be a while as our lead developer wishes to do it entirely himself (at least initially) and is rather busy most of the time.

**Comment by GalacticLion7** [comment]
It's been almost 6 years. Any update for the now-premium version?

**Comment by mcmonkey4eva** [comment]
Unfortunately Sponge as a project has essentially died off years ago. It's still technically going but they never gathered the community support needed to get fully going, and they don't maintain the project in a way that would ever entice Spigot users over anymore (notably very slow MC version updates).
