### ISSUE TITLE
Rabbit NPC Sentries Not Spawning

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#405]
This is a weird issue, I have a few Rabbit NPCs and their trait is a sentry. They have a set path.

When I go into the area, the rabbits don't appear at all but when I do /citizens reload they appear fine and they have the correct paths etc. They don't seem to appear when I go into the area at all. This only happens with a few Rabbits, others in other areas seem to appear ok.

I have only found this issue to be with rabbits also. Is it possible also to have the rabbits jump like they do in Vanilla or is that not possible for them as NPCS?

**Comment by mcmonkey4eva** [comment]
Rabbits *do* hop. Not very high, but they hop.

And I can't replicate your issue (I don't have Sentry though - see if you can replicate without that)
