### ISSUE TITLE
Can't create npcs

### ISSUE THREAD

**Issue by Parker8231** [CitizensDev/Citizens2#406]
When I try to create a NPC it gives me a java.lang.NoClassDefFoundError
I have tryed this on both Bukkit 1.8 and Spigot 1.8 and It still gives me error.

**Comment by nikosgram13** [comment]
Citizens build?

**Comment by mcmonkey4eva** [comment]
^ You have the wrong one either way. Get the correct one here: http://wiki.citizensnpcs.co/Versions
