### ISSUE TITLE
Unexpected crash 1.7.10 #1166 

### ISSUE THREAD

**Issue by JHXSMatthew** [CitizensDev/Citizens2#408]
Server crash when I try to spawn a human NPC
1.7.10 using version #1166 
No problem for other types of mobs. 

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 6/3/15 2:40 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
	at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277)
	at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150)
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620)
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595)
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460)
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516)
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277)
	at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150)
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620)
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595)

-- Entity being ticked --
Details:
	Entity Type: null (net.citizensnpcs.npc.entity.EntityHumanNPC)
	Entity ID: 6843
	Entity Name: 阿法利亚佣兵团
	Entity's Exact location: -141.40, 3.50, -82.10
	Entity's Block location: World: (-142,3,-83), Chunk: (at 2,0,13 in -9,-6; contains blocks -144,0,-96 to -129,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460)
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516)

-- Affected level --
Details:
	Level name: world_the_end
	All players: 2 total; [EntityHumanNPC['阿法利亚佣兵团'/649, l='world_the_end', x=-141.96, y=3.50, z=-82.11](阿法利亚佣兵团 at -141.95551874409978,3.5,-82.11278697855509), EntityPlayer['jhxs'/6421, l='world_the_end', x=-141.40, y=3.50, z=-82.10](jhxs at -141.40089837946664,3.5,-82.10325867779441)]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 5670759388919075704
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,66,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 36045600 game time, 36045600 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706)
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-431.23.3.el6.x86_64
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4061814600 bytes (3873 MB) / 5297930240 bytes (5052 MB) up to 5297930240 bytes (5052 MB)
	JVM Flags: 2 total; -Xms5G -Xmx5G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	CraftBukkit Information: 
   Running: CraftBukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) false
   Plugins: { GroupManager v2.0 (2.12.1) (Phoenix) org.anjocaido.groupmanager.GroupManager [AnjoCaido, Gabriel Couto, ElgarL], Stp v0.0.3 stp.Stp [], NeverLag v1.2.1 jiongjionger.NeverLag [jiongjionger], RpgitemAddition v1.0 rpgitemaddition.RpgitemAddition [], ShowOffS v2.0 me.crafter.mc.showoffs.ShowOffS [], RandomPlacer v2.0 com.nasonfish.randomplacer.RandomPlacer [], Teleports v0.50b-22 com.minecraftdimensions.bungeesuiteteleports.BungeeSuiteTeleports [Bloodsplat], BanItem v2.8 com.abcalvin.BanItem.main [abcalvin], RideMe v1.1 me.crafter.mc.rideme.RideMe [], CoreProtect v2.10.0 net.coreprotect.CoreProtect [Intelli], WorldEdit v5.6.1 com.sk89q.worldedit.bukkit.WorldEditPlugin [], Essentials vPre2.13.1.2 com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally], Restart v1.0 com.rb2750.restart.Main [], ClearLag v2.7.7 me.minebuilders.clearlag.Clearlag [bob7l], Intensify v2.5 Intensify.Intensify [], WorldBorder v1.7.7 com.wimbli.WorldBorder.WorldBorder [Brettflan], Chat v0.5b-56 com.minecraftdimensions.bungeesuitechat.BungeeSuiteChat [Bloodsplat], ProtocolLib v3.4.0 com.comphenix.protocol.ProtocolLibrary [Comphenix], CustomServerMessages v5.2 Bammerbom.CustomServerMessages.Main [[Bammerbom]], BreedingLimiter v1.3 emikodo.breedinglimiter.BreedingLimiter [], iConomy v7.0 com.iCo6.iConomy [Nijikokun, SpaceManiac], easyCommand v1.0 com.me.davidsss.easyCommand [davidsss], CommandCode v1.0 com.github.a810587921.CommandCode [a810587921], SafeNetherDoor v1.0 SafeNetherDoor [], SQLibrary v7.1 lib.PatPeter.SQLibrary.SQLibrary [PatPeter], AntiCheat v2.0.2 net.gravitydevelopment.anticheat.AntiCheat [Gravity], EffectLib v3.2 de.slikey.effectlib.EffectLib [Slikey], AutoSave v0.2.6 com.mengcraft.server.AutoSave [min梦梦], mcMMO v1.5.00-b3547 com.gmail.nossr50.mcMMO [nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking], Bans v0.50b-8 com.minecraftdimensions.bungeesuitebans.BungeeSuiteBans [Bloodsplat], Vault v1.2.31-b411 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], ScriptBlock v0.8.72CN scriptblock.ScriptBlock [Shereis], LWC v4.5.0-SNAPSHOT com.griefcraft.lwc.LWCPlugin [Hidendra], QuickShop v4.5 org.maxgamer.QuickShop.QuickShop [Netherfoam], Marriage v1.2.5 com.lenis0012.bukkit.marriage.Marriage [lenis0012], WorldGuard v6.0.0-beta-05.1569- com.sk89q.worldguard.bukkit.WorldGuardPlugin [], ChestCommands v3.1 com.gmail.filoghost.chestcommands.ChestCommands [], EssentialsProtect vPre2.13.1.2 com.earth2me.essentials.protect.EssentialsProtect [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], EssentialsAntiBuild vPre2.13.1.2 com.earth2me.essentials.antibuild.EssentialsAntiBuild [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, Iaccidentally], Gifts v1.0 qq330679663.Gifts [syx330679663], EssentialsSpawn vPre2.13.1.2 com.earth2me.essentials.spawn.EssentialsSpawn [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits], Simple_Suffix v1.7.1 me.staartvin.simplesuffix.SimpleSuffix [Staartvin], PlotMe v0.13f com.worldcretornica.plotme.PlotMe [ZachBora], RPG_Items v3.0.4 think.rpgitems.Plugin [], Credit v1.0.1 io.github.sjj118.credit.Credit [sjj118], Multiverse-Core v2.5-b678 com.onarandombox.MultiverseCore.MultiverseCore [Rigby, fernferret, lithium3141, main--], Citizens v2.0.13-SNAPSHOT (build 1166) net.citizensnpcs.Citizens [aPunch, fullwall], McCombatLevel v1.4 com.gmail.mrphpfan.McCombatLevel [], Residence v2.6.6.6 com.bekvon.bukkit.residence.ResidenceCommandListener [bekvon, nate302, t00thpick1], GlobalMarket v1.3.0-11 com.survivorserver.GlobalMarket.Market [], AncientGates v1.8.0 org.mcteam.ancientgates.Plugin [peewi96], Lottery v1.0.1 io.github.sjj118.lottery.Lottery [sjj118], VIP v1.0.0 io.github.sjj118.vip.VIP [sjj118], CreditShop v1.0 com.github.SHENDong.CreditShop [syx330679663], QuickSee v1.0 com.github.a810587921.QuickSee.QuickSee [a810587921], HolographicDisplays v2.1.1 com.gmail.filoghost.holographicdisplays.HolographicDisplays [], Sentry v1.8.5 net.aufdemrand.sentry.Sentry [aufdemrand, jrbudda], ItemLoreStats v5.11 com.github.supavitax.itemlorestats.ItemLoreStats [Supavitax], MythicMobs v2.0.3 net.elseland.xikage.MythicMobs.MythicMobs [Xikage AKA Ashijin], TouchscreenHolograms v1.3 com.gmail.filoghost.touchscreen.TouchscreenHolograms [],}
   Warnings: DEFAULT
   Threads: { TIMED_WAITING Async Chat Thread - #1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], WAITING Chunk I/O Executor Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING File IO Thread: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.FileIOThread.b(SourceFile:44), net.minecraft.server.v1_7_R4.FileIOThread.run(SourceFile:23), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING pool-28-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522), java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)], RUNNABLE Netty IO #1: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], RUNNABLE Netty IO #3: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Craft Scheduler Thread - 22: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Thread-17: [java.lang.Thread.sleep(Native Method), net.coreprotect.consumer.Consumer.run(Consumer.java:47), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_7_R4.ThreadSleepForever.run(SourceFile:63)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING EbeanBackgroundThread: [java.lang.Thread.sleep(Native Method), com.avaje.ebeaninternal.server.lib.BackgroundThread$Runner.run(BackgroundThread.java:168), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING pool-19-thread-2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522), java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Thread-13: [java.lang.Thread.sleep(Native Method), com.griefcraft.modules.credits.CreditsModule$CreditsTask.run(CreditsModule.java:110), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Thread-16: [java.lang.Thread.sleep(Native Method), net.coreprotect.thread.CacheCleanUp.run(CacheCleanUp.java:14), java.lang.Thread.run(Thread.java:745)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), net.minecraft.util.com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:73), org.bukkit.craftbukkit.v1_7_R4.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Thread-12: [java.lang.Thread.sleep(Native Method), com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:181), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Craft Scheduler Thread - 25: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)], TIMED_WAITING pool-13-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522), java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1603), org.bukkit.craftbukkit.v1_7_R4.CraftCrashReport.call(CraftCrashReport.java:28), net.minecraft.server.v1_7_R4.CrashReportSystemDetails.a(SourceFile:74), net.minecraft.server.v1_7_R4.CrashReport.h(CrashReport.java:45), net.minecraft.server.v1_7_R4.CrashReport.<init>(CrashReport.java:33), net.minecraft.server.v1_7_R4.CrashReport.a(CrashReport.java:230), net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1463), net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516), net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706), net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289), net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584), net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490), net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:255), java.io.BufferedInputStream.fill(BufferedInputStream.java:246), java.io.BufferedInputStream.read(BufferedInputStream.java:265), java.io.FilterInputStream.read(FilterInputStream.java:83), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader$1.read(ConsoleReader.java:167), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:267), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:204), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:1167), net.minecraft.server.v1_7_R4.ThreadCommandReader.run(ThreadCommandReader.java:32)], TIMED_WAITING pool-7-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], WAITING ProtocolLib-StructureCompiler 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Spigot Metrics Thread: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:92)], WAITING pool-8-thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], WAITING Ebean-Simple_Suffix.0: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:75), java.lang.Thread.run(Thread.java:745)], RUNNABLE Netty IO #0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:745)], RUNNABLE Netty IO #2: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97), net.minecraft.util.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:591), net.minecraft.util.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:301), net.minecraft.util.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101), java.lang.Thread.run(Thread.java:745)], RUNNABLE Craft Scheduler Thread - 29: [java.net.SocketInputStream.socketRead0(Native Method), java.net.SocketInputStream.socketRead(SocketInputStream.java:116), java.net.SocketInputStream.read(SocketInputStream.java:170), java.net.SocketInputStream.read(SocketInputStream.java:141), sun.security.ssl.InputRecord.readFully(InputRecord.java:465), sun.security.ssl.InputRecord.read(InputRecord.java:503), sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961), sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363), sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391), sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375), sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563), sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185), sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282), sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257), sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250), net.minecraft.util.com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:73), net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:54), net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:50), net.citizensnpcs.npc.entity.HumanController$UUIDFetcher.call(HumanController.java:251), net.citizensnpcs.npc.entity.HumanController$UUIDFetcher.call(HumanController.java:231), net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:146), net.citizensnpcs.npc.entity.HumanController$SkinThread.run(HumanController.java:226), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71), org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Thread-14: [java.lang.Thread.sleep(Native Method), jiongjionger.listener.BetterChunkManager$3.run(BetterChunkManager.java:79), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Timer-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)],}
   Recent tasks from 6480-6510{Citizens:net.citizensnpcs.npc.entity.HumanController$SkinThread@6511,GlobalMarket:com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1@6511,Citizens:net.citizensnpcs.npc.entity.HumanController$SkinThread@6521,Citizens:net.citizensnpcs.npc.entity.HumanController$SkinThread@6531,GlobalMarket:com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1@6531,}
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 5 / 60; [EntityPlayer['weisuodashu'/651, l='world', x=-409.76, y=72.00, z=392.28](weisuodashu at -409.76433240096424,72.0,392.28433667292614), EntityPlayer['Guard'/840, l='world', x=-75.34, y=69.00, z=-631.28](Guard at -75.34362067559562,69.0,-631.2841399332428), EntityPlayer['15KG'/1155, l='plotworld', x=225.87, y=90.98, z=-458.82](15KG at 225.87377843331848,90.98034331661972,-458.8161295308548), EntityPlayer['14kg'/976, l='plotworld', x=195.40, y=65.00, z=-442.39](14kg at 195.3996439063639,65.0,-442.3909394439516), EntityPlayer['jhxs'/6421, l='world_the_end', x=-141.40, y=3.50, z=-82.10](jhxs at -141.40089837946664,3.5,-82.10325867779441)]
	Is Modded: Definitely; Server brand changed to 'Spigot'
	Type: Dedicated Server (map_server.txt)

**Comment by mcmonkey4eva** [comment]
Is pastebin so hard?!

Anyway, wrong C2 version. http://wiki.citizensnpcs.co/Versions
