### ISSUE TITLE
Items not appearing in the Dtltraders inventory

### ISSUE THREAD

**Issue by BLAKOUT13** [CitizensDev/Citizens2#409]
I am running a cauldron server 1.7.10 and i have the right citizens plugin (the one meant for cauldron) and i added the dtlTraders plugin. When ever i try to put items in his inventory i press unlock stock and then i add the items. I click exit and save and it brings me back to the regular screen and the items are no there. If i click the square where i added the items into it says buying <that item>. so it gives me the items but they are invisible in his inventory. if you could help i would be very happy.
Thanks - BLAKOUT13

**Comment by mcmonkey4eva** [comment]
This is not DTL support, this is Citizens.
