### ISSUE TITLE
/npc he creates error on despawned NPC

### ISSUE THREAD

**Issue by Fortifier42** [CitizensDev/Citizens2#410]
Step 1: /npc sel
Step 2: /npc despawn
Step 3: /npc he
Step 4: ???
Step 5: Profit

http://pastebin.com/npK6nnVF

Spigot: [20:29:59 INFO]: This server is running CraftBukkit version git-Spigot-044d928-e8c6403 (MC: 1.8.6) (Implementing API version 1.8.6-R0.1-SNAPSHOT)
Citizens: [20:30:17 INFO]: Citizens version 2.0.16-SNAPSHOT (build 1236)
Denizen: [20:30:30 INFO]: Denizen version 0.9.6-SNAPSHOT (build 227)

**Comment by nikosgram13** [comment]
Citizens build? And Spigot Version?

**Comment by Fortifier42** [comment]
Added to Post.

**Comment by nikosgram13** [comment]
You can report this error here: https://github.com/DenizenScript/Denizen-For-Bukkit/issues

**Comment by mcmonkey4eva** [comment]
Yes that's a Denizen error. Or, rather, it's a you error. Don't do entity-related commands on despawned NPCs :(

**Comment by mcmonkey4eva** [comment]
I mean we could add code that posts warnings if you do that but... just don't do it man.

**Comment by Fortifier42** [comment]
Yes boss.
