### ISSUE TITLE
citizens not working with spigot 1.8.4...

### ISSUE THREAD

**Issue by slothencounters** [CitizensDev/Citizens2#411]
citizens appears red while doing the /pl command. is it compiled for that version? i see that there is one for 1.8.3 and 1.8.6. is it possible to get this plugin working for 1.8.4?

**Comment by Talamar1** [comment]
What build are you using?    I would suggest starting at 1230 and see if that works.

**Comment by slothencounters** [comment]
i'm using the latest. i just tried that version and i'm still getting:

[14:01:57 ERROR]: [Citizens] v2.0.15-SNAPSHOT (build 1230) is not compatible wit
h Minecraft v1.8.4 - try upgrading or downgrading Citizens. Disabling.
[14:01:57 INFO]: [Citizens] Disabling Citizens v2.0.15-SNAPSHOT (build 1230)

**Comment by Talamar1** [comment]
Looks like 1231 has the 1.8.4 in it from what I can tell walking backward through the history.

**Comment by slothencounters** [comment]
is it safe running an unstable version like that? i tried 1232 and still no luck...

**Comment by Talamar1** [comment]
Not sure why it would be considered unstable, especially if you are running 1.8.6.

**Comment by slothencounters** [comment]
i'm running on spigot 1.8.4, not 1.8.6. i've tried almost every version of citizens 2 and they all give me the same error. not sure what else to do. i don't want to upgrade my spigot version because a lot of my core plugins are only updated to that version.

**Comment by Talamar1** [comment]
1232 was updated for 1.8.5, the only build that has 1.8.4 in it (possibly, depends on time of compile) would be 1231.

**Comment by Talamar1** [comment]
Nevermind, looks like 1231 failed to build and mcmonkey broke it on 1232, so nothing was built for 1.8.4.  You will have to wait and see if mcmonkey has an answer for you.

**Comment by slothencounters** [comment]
i hope so... i wonder if he can compile if for me. it would be much appreciated.

**Comment by mcmonkey4eva** [comment]
Latest builds work on 1.8.4, though we highly recommend updating to 1.8.6 to avoid trouble

**Comment by slothencounters** [comment]
i've tried the latest. it keeps giving me that same error. :/ in the /pl directory, it appears red and the commands don't work.

**Comment by mcmonkey4eva** [comment]
With /what error/?

**Comment by slothencounters** [comment]
the one i posted above: 
[14:01:57 ERROR]: [Citizens] v2.0.15-SNAPSHOT (build 1230) is not compatible wit
h Minecraft v1.8.4 - try upgrading or downgrading Citizens. Disabling.
[14:01:57 INFO]: [Citizens] Disabling Citizens v2.0.15-SNAPSHOT (build 1230)

**Comment by slothencounters** [comment]
keep in mind, i KNOW i'm not using the latest in the error. i already used the latest and got the same error, so i tried that one.

**Comment by slothencounters** [comment]
any help? D:

**Comment by mcmonkey4eva** [comment]
Oh, you can edit your config to fix that.

**Comment by fullwall** [comment]
Set check-minecraft-version to false in the settings.
