### ISSUE TITLE
NPC Skin Flags

### ISSUE THREAD

**Issue by crolemol** [CitizensDev/Citizens2#412]
hey,

i'm having some trouble with the skins of all my npc's, they have a skin but it's a bit messed up, it looks like all the skin flags have been disabled (1.8 layers). I looked in the code of citizens to see if this is normal and in the EntityHumanNPC at line 304 i found the method updatePackets() which tells me that it should be enabled. any fix? /version = git-Spigot-044d928-e8c6403 = latest , citizens build 1239
![2015-06-04_19 15 21](https://cloud.githubusercontent.com/assets/7345077/7990121/08c51f96-0aef-11e5-989c-767c510cbaff.png)

**Comment by mcmonkey4eva** [comment]
A few people have encountered issues similar to this, and at those times it was determined to be a setting unrelated to Citizens2 - things like changing what world they were in (via multiverse / similar) would suffice to restore full skin functionality.

**Comment by seedie** [comment]
Mine don't even have skins at times! :D so consider yourself lucky :8ball: (running latest of everything, dont have multiverse or similar)

**Comment by crolemol** [comment]
indeed, it seems to be a world issue and it only appears in the world which is generated by my plugin so is there any specific setting which could cause this bug?

**Comment by crolemol** [comment]
?

**Comment by crolemol** [comment]
still not idea?

**Comment by mcmonkey4eva** [comment]
All I know is this issue happens in rare circumstances and is linked to the world.

**Comment by mcmonkey4eva** [comment]
Can you replicate this on latest builds @crolemol ?
