### ISSUE TITLE
Npc Creation

### ISSUE THREAD

**Issue by AlTheCal** [CitizensDev/Citizens2#413]
I dont know why but i cant create an npc. I am using the latest version of craftbukkit and i even tried spigot. This error report keeps showing "java.lang.NoClassDefFoundError:net/minecraft/server/v1_8_R1/Packet". Please I need help it would be appreciated.

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens for your minecraft version: http://wiki.citizensnpcs.co/Versions
