### ISSUE TITLE
[1.8.6] Npc's are shown only after a reload

### ISSUE THREAD

**Issue by Dennis000903** [CitizensDev/Citizens2#417]
Using Spigot 1.8.6
And latest CitizensDevBuild

When the server starts, no npcs are shown, only after typing /citizens reload  they appear

**Comment by Dennis000903** [comment]
The Same Issue on Spigot 1.8.7 with latest #1244

**Comment by Fortifier42** [comment]
I do not have this issue:
- `Spigot version: This server is running CraftBukkit version git-Spigot-f928e7a-994b2aa (MC: 1.8.7)`
- `Citizens version: Citizens version 2.0.16-SNAPSHOT (build 1244)'

All NPC's spawn on server start - maybe you have a conflicting plugin?

**Comment by Dennis000903** [comment]
I really dont know what plugin that could be. But its good to know I try to figure out what plugin is causing that conflict

**Comment by Fortifier42** [comment]
What plugins do you have on your server?

**Comment by Talamar1** [comment]
Check your console for any error messages when Cit loads.

**Comment by Dennis000903** [comment]
1. No errors
2. I found the problem! LaggRemover blocked the npcs
