### ISSUE TITLE
Cant interact with NPCs

### ISSUE THREAD

**Issue by mjcrafter100** [CitizensDev/Citizens2#420]
I have created a region, and one of the flags is pvp: deny
I know that is the problem, but I need pvp off, how do I fix this?

**Comment by mcmonkey4eva** [comment]
Talk to the creators of your region plugin, not us.

**Comment by mjcrafter100** [comment]
I am the owner of the sever

**Comment by mjcrafter100** [comment]
I have fixed the problem, turned out to be a world guard issue.
You may close this now.
