### ISSUE TITLE
Entity Collisions

### ISSUE THREAD

**Issue by Tursiops1** [CitizensDev/Citizens2#422]
When I create multiple entities and set their navigation to the same location they collide and occupy the same spot. Is there a way to avoid this? I would like for them to try to go to the same place, but not overlap.

**Comment by Tursiops1** [comment]
Is this expected behavior?
https://www.youtube.com/watch?v=STGxFmFQKSU&feature=youtu.be

**Comment by mcmonkey4eva** [comment]
Use the Flocker. https://github.com/DenizenScript/Denizen-For-Bukkit/blob/master/src/main/java/net/aufdemrand/denizen/scripts/commands/entity/WalkCommand.java#L142

**Comment by Tursiops1** [comment]
Thank you!
