### ISSUE TITLE
Sitting Problem.

### ISSUE THREAD

**Issue by BillTheMaster** [CitizensDev/Citizens2#423]
If i write "/npc sit" is the npc sitting. But after 1 minute despawn the arrow from the NPC, and he stand again. I dont wrote "/npc stand" or something else.

Before,

![2015-06-14_23 41 39](https://cloud.githubusercontent.com/assets/12886529/8150577/467308dc-12ef-11e5-9dcd-af291d0bba5c.png)

After 1 Minute,

![2015-06-14_23 42 03](https://cloud.githubusercontent.com/assets/12886529/8150579/508ed9a4-12ef-11e5-917e-db67bffd4ba9.png)

.

**Comment by mcmonkey4eva** [comment]
`/npc sit` does not exist within Citizens. Are you perhaps using the Denizen command?

**Comment by BillTheMaster** [comment]
Yes. i use Denizen

**Comment by mcmonkey4eva** [comment]
Well then, report the issue there :)

**Comment by BillTheMaster** [comment]
[09:02:14 INFO]: BillTheMaster issued server command: /npc sit

Not more, he sit for 1 minute, and then he stand again. but in the Script is he sitting.
