### ISSUE TITLE
NPC Creeper type randomly exploding

### ISSUE THREAD

**Issue by iversenMC** [CitizensDev/Citizens2#424]
I have a problem with an npc that has the type creeper (/npc type creeper), randomly exploding...
I have tried all commands, and I am clueless on how to fix this. I dont know if the reason is that is is close (4 blocks from all sides) to other mobs (also hostile though).

I don't know if this is a bug, or if I just missed how to fix it... I'd really appriciate a fix though, thanks in advance :)

**Comment by mcmonkey4eva** [comment]
Cannot replicate.
Please provide a replication video.

**Comment by iversenMC** [comment]
Will try to catch it on video tomorrow. Though it doesnt often happen while I look.

**Comment by BillTheMaster** [comment]
Dit you use Sentry plugin ?

**Comment by iversenMC** [comment]
No, I am not

**Comment by iversenMC** [comment]
It happened again. While I didnt capture it... http://puu.sh/iqXJA/d792c5086f.jpg

**Comment by mcmonkey4eva** [comment]
Probably a part of https://github.com/CitizensDev/Citizens2/issues/455 which is far easier to replicate.
