### ISSUE TITLE
NPC's dissapearing

### ISSUE THREAD

**Issue by Legendaryx** [CitizensDev/Citizens2#426]
My npcs suddenly begin to dissapear (despawn).

When I do /citizens reload.
They come back untill the chunk is unloaded.

Im using build 1230.

My npcs are villagers.

**Comment by ServCraftTech** [comment]
I am the same problem with my server

**Comment by Standfford** [comment]
Yes, I have the same problem with last dev build 1244 and 1241 for 1.8.7

**Comment by xikage** [comment]
Same thing happening on my server. NPC type does not appear to matter. NPCs will not come back until I do a reload or select them and do /npc spawn. No errors in console, happening on 2.0.16 beta 2 and Spigot 1.8.7.

**Comment by Standfford** [comment]
The problem is for clearlag and citizens run good now.

You need disable clear mobs and put whitelist on /lagg killmobs

**Comment by blablubbabc** [comment]
I just noticed on my test server that '/citizens save' seems to be required now, in order for freshly created npc's to survive a '/citizens reload'. Has this always been this way?
Maybe this is related to this ticket.

Maybe the unsaved data could be saved during a reload, similar to how it seems to get saved during plugin disable.
Alternatively (or additionally): is there a way to trigger a save via the api?

**Comment by RFSMassacre** [comment]
I'm having the same issue. NPCs despawn after 30 seconds of being spawned in. Have to constantly run /citizens reload to even get my town fully functional.

http://pastebin.com/e3Z4mgsN

**Comment by mcmonkey4eva** [comment]
This is 99.99% of the time from external plugins. (EG the above trouble was from clearlagg)

`Alternatively (or additionally): is there a way to trigger a save via the api?` Source code answers 90% of questions like this -> just find where the relevant command or action is in the codebase, and copy over some code...

**Comment by blablubbabc** [comment]
Any comment on:
'I just noticed on my test server that '/citizens save' seems to be required now, in order for freshly created npc's to survive a '/citizens reload'. Has this always been this way?

Maybe the unsaved data could be saved during a reload, similar to how it seems to get saved during plugin disable.'

This is with only citizens running, no other plugins interfering.

**Comment by mcmonkey4eva** [comment]
I believe that's fairly standard - reload is generally if you want to reload the data from disk, not overwrite it...

**Comment by blablubbabc** [comment]
My guess would have been that the purpose of the reload command would be to reload configuration (and things which the user might have manually changed outside of minecraft). The save data for npc's however shouldn't be something the user should mess with outside of minecraft..
Anyways, if that's intended then I guess I simply have to be more cautious that I don't reload citizens right after I have created and setup a new npc.
