### ISSUE TITLE
Can't type commands!

### ISSUE THREAD

**Issue by Andreaskal** [CitizensDev/Citizens2#432]
Hi, i have just installed citizens 2.0.13 snapshot (build 1130) but when i try writing /npc nothing happens! it should be right installed.

**Comment by mcmonkey4eva** [comment]
Install the correct version for your minecraft version: http://wiki.citizensnpcs.co/Versions

**Comment by Andreaskal** [comment]
i have 1.8.7 and it don't support this update

**Comment by Andreaskal** [comment]
uhmm... sorry :P

**Comment by Fortifier42** [comment]
@Andreaskal on the page http://wiki.citizensnpcs.co/Versions It says 
`Latest Citizens builds [1.8.6, 1.8.7] are always available here[1]`

Look here: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by Andreaskal** [comment]
yeah sorry :I

**Comment by Fortifier42** [comment]
@Andreaskal close the issue if it is fixed.

**Comment by Andreaskal** [comment]
thx guys please help here also :smile: 
https://github.com/Ktar5/Info-Board/issues/30
