### ISSUE TITLE
Ender Dragon mount cannot fly down.

### ISSUE THREAD

**Issue by Stuperfied** [CitizensDev/Citizens2#434]
created npc as ender dragon type and mounted. Pressed space and flew however when pushing shift did not fly down as expected. Pressing shift dismounts the npc. Could not find anywhere this could be configured. Recommend default be fly down and only if on ground dismount. That way you could implement this now and worry about config for it later.

**Comment by mcmonkey4eva** [comment]
This is a limitation imposed by Mojang's control scheme, the only alternative is to implement entirely our/your own via something like point-n-click-to-fly
