### ISSUE TITLE
Skins Mechanics Question

### ISSUE THREAD

**Issue by Gavster4** [CitizensDev/Citizens2#435]
Does the skins -p command make the skin persistent beyond skin changes, or just more difficult to accidentally change? I understand spout is the only way to do certain skin changes but I'm hoping to avoid client mod requirements.

Thanks!

**Comment by mcmonkey4eva** [comment]
The skins are (Temporarily? Up to Mojang) able to be fully persistent with complete disregard for skin changes.

So if you set your skin to a zombie, then skin -p an NPC to that, then change back to a normal skin... that NPC will have a zombie skin for as long as you don't do the skin command again.

**Comment by intangir** [comment]
another skin question, i have the same mod on two servers

but on one it shows 2 layers of the skin, on the other it shows only the base layer

whats going on there..

how can i force it to show both layers of a players skin, could they have been cached somewhere or something?

**Comment by intangir** [comment]
the only difference between their configs is the npc uuid , which i am guessing is supposed to be unique anyway

**Comment by mcmonkey4eva** [comment]
Again, we have no idea why that happens on specific worlds.

**Comment by Formula350** [comment]
Regarding the skin persistence does that mean that I can use 1 alternate MC account and change the skin multiple times, each time assigning it to one NPC with the `-p` flag, and have them all be uniquely skinned?

Or will using the same Minecraft account, across multiple NPCs, eventually cause skin derpage?

**Comment by mcmonkey4eva** [comment]
Who knows if it will ever derp out, aside from Mojang. For now, at least, it works.

**Comment by Gavster4** [comment]
Thanks for the clarification. If there is no other use for this thread you
can close it.
