### ISSUE TITLE
A question about /npc create

### ISSUE THREAD

**Issue by Andre424971** [CitizensDev/Citizens2#437]
This is only a question.

with /npc create test --type Item I can create a Item. But this item is only stone.
Is it possible to change it? And if yes: how?

Thanks for answering
Andre424971

**Comment by mcmonkey4eva** [comment]
`/npc item <type>` I think

**Comment by Andre424971** [comment]
it dont work.

For example. I type /npc create test --ty

**Comment by Andre424971** [comment]
Tahnks!
It works!
