### ISSUE TITLE
Installed, when using commands nothing shows up

### ISSUE THREAD

**Issue by Velsurag** [CitizensDev/Citizens2#438]
When using the latest build (and turning off the check versions in the config file) I try to use the command. When I type /citizen to see if it does work as a test nothing comes up. No "you do not have perms for that", no error, nothing. But, when I use PrimeShop is says I don't have citizens installed, when I do. The folder created and when I use /citizen it doesn't give me the "Unknown command" error either. Please help.

**Comment by mcmonkey4eva** [comment]
`(and turning off the check versions in the config file)` ... why?! Download the correct version: http://wiki.citizensnpcs.co/Versions

**Comment by qwertyfat** [comment]
thats didn't help

**Comment by Fortifier42** [comment]
@qwertyfat use the version that corresponds to your version of spigot.

**Comment by qwertyfat** [comment]
thanks I know
