### ISSUE TITLE
http://citizensnpcs.co/

### ISSUE THREAD

**Issue by Jackiedk100** [CitizensDev/Citizens2#440]
Down the buttom

Sponsored by CreeperHost
Copyright 2012 © CitizensNPCs.com

We are in 2015

**Comment by Talamar1** [comment]
What URL?

**Comment by Jackiedk100** [comment]
http://citizensnpcs.co/

**Comment by mcmonkey4eva** [comment]
That page hasn't been touched in forever, lol.

@fullwall might be worth updating

**Comment by mcmonkey4eva** [comment]
Found out where that page's file hides and update myself :)
