### ISSUE TITLE
[Spigot 1.8.7] [Citizens b1247] /npc playerlist don't work properly

### ISSUE THREAD

**Issue by KsenMih** [CitizensDev/Citizens2#441]
Hi,

>  /npc playerlist :
> Toggles an NPC as a 'real' player, so that it will be more recognised by other plugins, will keep chunks loaded and crops ticking. 

I've tried to make a «real player» NPC with the command `/npc playerlist`. Once executed, the message «_Added CmdPermTest to the player list._» is displayed, but the NPC don't appear in the tablist. I've tried to `/citizens save` then `/npc reload` but nothing change =c

I'm using **CraftBukkit version git-Spigot-f928e7a-d432434 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)** and **Citizens version 2.0.16-SNAPSHOT (build 1247)**.

Tell me if you need more informations.

**Comment by mcmonkey4eva** [comment]
We will NEVER intentionally add NPCs to the tab list, nor the ping list user count.

Stop trying to cheat and get real players. if you want to look popular - BE popular. There's no easy way around that.

**Comment by KsenMih** [comment]
I don't try to cheat and get real players. I've just wanted to create Fake OP Players who can execute `summon` in each world, because `summon`, if executed by console, only works in the primary world. With fake players, I can 'sudo` them to use `summon` in others worlds.

**Comment by mcmonkey4eva** [comment]
Use Denizen, Denizen can execute commands as NPC OPs.

`- execute as_npc "summon potato"`
ANd, for that matter, it can summon entities in arbitrary worlds pretty easily.
`- spawn zombie l@0,100,0,world`

**Comment by KsenMih** [comment]
Thanks ! I will take a look to Denizens :)
