### ISSUE TITLE
Tablist problem

### ISSUE THREAD

**Issue by ufastars** [CitizensDev/Citizens2#442]
Hi, the problem is that all displayed by npc/buggy in Tablist. Can I fix it?
Citizens 2.0.16 alpha 2
Spigot 1.8.7

**Comment by mcmonkey4eva** [comment]
... what?

**Comment by Fortifier42** [comment]
they mean occassionally the tablist (playerlist) bugs and shows npc's when they are in range, but only for a tick usually.

**Comment by mcmonkey4eva** [comment]
That's not even an issue that's a known side effect that causes zero problems ever.

**Comment by Fortifier42** [comment]
Well you are creating fake players, there are bound to be some issues on the tablist

**Comment by sh4444dow** [comment]
Are you joking ? This issue is the worst bug ever... The tab list which always blinks is annoying for players and admin, especially if you have a plugin like BungeeTabListPlus which is completely bugged because this issue. Let's create 10 or 20 NPCs, download BungeeTabListPlus, and see if this "side effect" isn't a real issue...

**Comment by Fortifier42** [comment]
@Sh4444dw
It is a mine craft issue. We can't do anything.

**Comment by sh4444dow** [comment]
Obviously, there is 1 tick between the player entering in the list and the player removing from the list ? Isn't there a way to catch the TabListPacket and cancel/rewrite it instantly ?

**Comment by Fortifier42** [comment]
@sh4444dow If it could be done, do you not think it already would be implemented?

**Comment by sh4444dow** [comment]
How would I have been able to know that this issue was already known by developers ?

**Comment by Fortifier42** [comment]
It's been an "issue" in citizens since pretty much the beginning.

**Comment by sh4444dow** [comment]
Well, I have just discovered the Citizens Github and I didn't know anything about this issue, sorry. This Issue may be closed so.
