### ISSUE TITLE
NPC hiding nameplates.

### ISSUE THREAD

**Issue by Terryjomjarry** [CitizensDev/Citizens2#443]
I know in an earlier report (#186), it was said that you must make an NPC invisible, then mount it on top of the NPC you want to hide the nameplate on. How exactly do I make the NPC invisible, and then mount it to another NPC?

Please help, I really love your plugin, but its bugging me that my NPCs nameplates only appear when I look straight at them. 

My goal is to hide the nameplates then use holographic display to display to text I want!

-Thanks for the help
    -Keep up the good work
        -Terryjomjarry

**Comment by mcmonkey4eva** [comment]
Generally we vote 'Do it with a Denizen script or command'

`/ex mount <FIRST NPC>|<SECOND NPC> <player.location>` where capitals need to be filled in.

We're planning on making a better way to do this automatically through Citizens, but for now... Denizen is the best option.

**Comment by Terryjomjarry** [comment]
Wow, thanks for the quick feedback!

The only sad thing is, is that some reason Denizen doesn't load on my server. It will just stay as a .jar file and create no other files or anything. I don't know if the console even recognizes it!

I am currently running 1.8.6 on Mcprohosting services.

**Comment by mcmonkey4eva** [comment]
Check your logs, if you have a .jar file in the plugins folder, it will create /some/ form of output in th elogs.

**Comment by Terryjomjarry** [comment]
kk ill try it now!

**Comment by Terryjomjarry** [comment]
okay, my log is very very stuffed with errors and such, do you know any commands for denizen I could try. 

Or is '/ex' one of them because when I type /ex, it runs a WorldEdit command

**Comment by Terryjomjarry** [comment]
Okay, so I actually got it to show up in the '/plugins' command buy un-installing it, rebooting server, shutting down server, installing it, then rebooting!

I shall search my logs now brb!

**Comment by Terryjomjarry** [comment]
Well, could not find any error enabling the plugin, hope someone can help me from here :/

**Comment by Terryjomjarry** [comment]
Hope you find the time to get back to me, turns out Denizen started working on 1.8.0, time for an update?

**Comment by mcmonkey4eva** [comment]
Are you sure you downloaded the right version off of http://wiki.citizensnpcs.co/Versions ?

**Comment by Terryjomjarry** [comment]
Yes, im not sure how this would effect Denizen?

**Comment by mcmonkey4eva** [comment]
... The right version of Denizen from that link is what I meant

**Comment by Terryjomjarry** [comment]
ah I see what you meant now, so would Denizen 1.8.3 work?

**Comment by mcmonkey4eva** [comment]
If you're on Spigot 1.8.3, yes.

**Comment by Terryjomjarry** [comment]
Alright ill try it out! Thanks for all the help man!

**Comment by Terryjomjarry** [comment]
Okay got it running on Spigot 1.8.1 fine.

So I create 2 npcs Test1 and Test2, now I want to mount Test2 on to Test1, an have Test2 be invisible in order to hide nameplate.

So I typed 
/ex mount Test1|Test2 

Then I received this...
Running dCommand... Check you console for Debug output.

Could you give me the command to mount these 2 npcs so I could just copy and paste it?

-Thank you
-Terryjomjarry

**Comment by Terryjomjarry** [comment]
Okay It may be because now citizens doesn't have the '/npc mount' command because I downgraded to 1.8.1, some help would be appreciated :+1:

**Comment by mcmonkey4eva** [comment]
We can't provide reasonable support on old versions.
