### ISSUE TITLE
Maven repo is too slow...

### ISSUE THREAD

**Issue by sgdc3** [CitizensDev/Citizens2#444]

**Comment by mcmonkey4eva** [comment]
Boo-hoo.

**Comment by Talamar1** [comment]
Check your interwebs or use -o to offline compile.

**Comment by Talamar1** [comment]
At least it works, Vault's repo has been broken for ages...  feel free to donate to the project so that they can purchase better hosting.

**Comment by Talamar1** [comment]
Oh, and if you don't follow the interweb news, hacker groups have been beating the hell out of web lately, PSN has been up and down multiple times the last 2 weeks, Xbox Live has been taken down repeatedly, Nintendo Live barely keeps its head above water, Steam resets connections daily... so... yeah.. it might be a little slow with all the DDOS going on.
