### ISSUE TITLE
Text editor not recognizing input

### ISSUE THREAD

**Issue by mogulus** [CitizensDev/Citizens2#445]
Hello. I'm able to create npcs, edit their paths, equip them and everything else. I'm having an issue with the text editor however. I type /npc text and the text editor opens fine, but when I type any commands ( add, edit, etc ) it simply comes up in the chat like i'm trying to talk to people.

everyone on my server keeps asking why i'm saying "add" over and over. lol
help please :)

**Comment by mcmonkey4eva** [comment]
LOL you expect Citizens text system to work properly... funny ^^

We generally recommend Denizen if you want your NPCs to talk -> http://wiki.citizensnpcs.co/Denizen
