### ISSUE TITLE
How to use /ex mount (Denizen)

### ISSUE THREAD

**Issue by Terryjomjarry** [CitizensDev/Citizens2#446]
So I have my first NPC 'bob'

My second NPC 'jeff'

I want jeff to be on top of bob, what would be the Denizen command to do so?

**Comment by Terryjomjarry** [comment]
Is this command run in-game them?

**Comment by Pigman168** [comment]
You can run it from a script or in-game. Wherever you like :3

**Comment by Terryjomjarry** [comment]
Okay, so the version of Citizens 2 I am using does not support /npc mount, will this affect that?

**Comment by Pigman168** [comment]
Shouldn't but I would update everything if possible. If not you are still free to use /ex mount as a substitute.

**Comment by Terryjomjarry** [comment]
Well that is the thing, Denizen only works on 1.8.3, so I cant update Citizens 2 or it'll mess that up too.

**Comment by Pigman168** [comment]
Ah ok.

**Comment by mcmonkey4eva** [comment]
Denizen works on all versions. http://wiki.citizensnpcs.co/Versions
