### ISSUE TITLE
Commands wont show up or work

### ISSUE THREAD

**Issue by Eboss34** [CitizensDev/Citizens2#447]
Whenever I type any of the commands in the chat bar or in a command block, nothing with show up, its as if i didnt type anything. I didn't mess with anything in the config, but I am using it on a 1.7.10 server of mine and there appeared not to be any 1.7.10 download, so I just downloaded the 1.7.9 download but it didn't work at all. So after that I tried and used the latest version (which is currently 1.8.7) and that didn't work either. I have watched previews on this plugin and I really want to use it but none of the videos said I had to do anything special like in the config or anything so I had to resort to asking you.
Please answer. Im sure many other people have this problem so please come up with a solution or tell me where I might find the 1.7.10 version that might work.

Thanks,
Eboss34

**Comment by Morphan1** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by Eboss34** [comment]
Thank you!
