### ISSUE TITLE
How i fix that

### ISSUE THREAD

**Issue by hsndmrts** [CitizensDev/Citizens2#448]
http://snag.gy/mUqxf.jpg

i want more Word limit but how i do that?

**Comment by mcmonkey4eva** [comment]
You update to the latest version :)

**Comment by hsndmrts** [comment]
i use 1.8.3version

**Comment by Fortifier42** [comment]
He said update not downgrade

**Comment by mcmonkey4eva** [comment]
Use the 1.8.7 version :)

**Comment by hsndmrts** [comment]
but i need 1.8.3v please add 1.8.3?

**Comment by mcmonkey4eva** [comment]
No.

**Comment by Fortifier42** [comment]
You don't need 1.8.3. 90% of useful plugins support 1.8.7.
