### ISSUE TITLE
Add in 1.8.3v Please :(

### ISSUE THREAD

**Issue by hsndmrts** [CitizensDev/Citizens2#449]
please add max name lenght options in 1.8.3v please i need only in 1.8.3 please ;(

**Comment by mcmonkey4eva** [comment]
Fuck right off good sir.

**Comment by Fortifier42** [comment]
We can't. It is done. Finished.

**Comment by mcmonkey4eva** [comment]
(Which is to say, we don't support old versions and DO NOT APPRECIATE YOU REPOSTING ISSUES AFTER WE CLOSE THEM)
