### ISSUE TITLE
Nothing shows up after doing commands

### ISSUE THREAD

**Issue by qwertyfat** [CitizensDev/Citizens2#451]
When I write any commands like /npc nothing shows up. My server is running Spigot 1.8.7. please help.

**Comment by mcmonkey4eva** [comment]
Are you definitely running the correct version of Citizens? http://wiki.citizensnpcs.co/Versions

**Comment by qwertyfat** [comment]
Yes it's the correct build. Is Citizens incompatible with any plugins because I have alot

**Comment by mcmonkey4eva** [comment]
Check your startup logs for errors... if something went wrong there's just about guaranteed to be an error message somewhere.

**Comment by ROLND** [comment]
I'm having the same issue, just wondering what you did or what you can suggest me doing.

I've downloaded the latest build, yet still gives me the error:
[Server] ERROR Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1251) (Is it up to date?)

Server is running Spigot 1.8.7, everything else besides the installation of the plugin seems to be fine.

**Comment by Talamar1** [comment]
can you pastebin your boot log?

**Comment by ROLND** [comment]
http://pastebin.com/rbZ5tsx9

**Comment by mcmonkey4eva** [comment]
You are running 1.8`(.0)` not 1.8.7
