### ISSUE TITLE
Denizen Mount

### ISSUE THREAD

**Issue by Terryjomjarry** [CitizensDev/Citizens2#452]
The exact word for word command to mount 
1. 'Bob'
2. 'John'

Bob on John, Thankyou

**Comment by mcmonkey4eva** [comment]
`- mount li@<server.get_players_named[Bob].get[1]>|<server.get_players_named[John].get[1]> <player.location>` or something like that.

**Comment by Fortifier42** [comment]
@mcmonkey4eva Wouldn't they be after the Citizens method?

**Comment by mcmonkey4eva** [comment]
@Fortifier42 the title says 'Denizen' sooooo

**Comment by Fortifier42** [comment]
Then whats this shit in the Citizens issues for

**Comment by mcmonkey4eva** [comment]
@Fortifier42 Oh woops, typo. Nice catch! Thanks. *Edited*

And I have no idea why it's in C2 issues page, only the OP would know

**Comment by Terryjomjarry** [comment]
Thankyou now how would I make Bob, invisible?

**Comment by mcmonkey4eva** [comment]
```
[18:40:20] <monkeybot> [entity command] invisible: Makes an NPC or entity go invisible (Note: use '/npc playerlist' to make it work on NPCs!)
[18:40:20] <monkeybot> Syntax: - invisible [<entity>] (state:true/false/toggle)
```

**Comment by Terryjomjarry** [comment]
So /ex invisible bob true

**Comment by mcmonkey4eva** [comment]
`<npc>` not `bob`, particularly while the NPC is selected.
