### ISSUE TITLE
Trait.onRemove() during disable and reload

### ISSUE THREAD

**Issue by blablubbabc** [CitizensDev/Citizens2#453]
Refering to this code: https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/Citizens.java#L108

Is it intended that Trait.onRemove() is called when Citizens disables or gets reloaded (and Trait.onAttach() after the reload)? Would it make more sense maybe to call Trait.onDespawn()?

Until now I thought that Trait.onRemove() is only called when a player permanently removes the trait from the NPC or the NPC altogether.
So I put all my cleanup code into that method of my custom trait. However this caused that on every reload of citizens, all the data related to the trait got removed and freshly recreated again after the reload (on fresh attach).

Is there any way for me to find out if onRemove() is called because the npc/the trait gets permanently removed (which I need to react to)?
Preferably without having to listen to NPCRemoveEvent and NPCRemoveTraitEvent, as this doesn't seem to be very future proof in case there is a new situation added in which the trait gets permanently removed.

**Comment by mcmonkey4eva** [comment]
That's ... a solid question. @fullwall ?

**Comment by fullwall** [comment]
Good catch, fixed.

**Comment by blablubbabc** [comment]
@fullwall As you are already on it: is there something inside Trait which is called only when the trait is freshly added to a npc? As already mentioned, onAttach is called everytime the traits get freshly load/created and linked to the npc, but that's probably intentionally (to inform the freshly constructed trait that the npc is now available/linked).

Currently I am starting a delayed task, let citizens fully load the trait, and then check if I already have backing data for this trait (which is not directly stored together with the trait).
I was already thinking about maybe listening to the NPCAddedTraitEvent and comparing the Trait there with my custom one and then reacting to that instead.
Would it make sense to add some method for this directly to Trait?

**Comment by mcmonkey4eva** [comment]
You could always dump a boolean on the trait's storage for lazy handling...

**Comment by blablubbabc** [comment]
That would of course be possible as well. I am just curious what the cleanest/prefered solution would be.
