### ISSUE TITLE
Add Crackshot Support

### ISSUE THREAD

**Issue by Colton1070** [CitizensDev/Citizens2#456]
I would like citizens to have a config node that says crackshot=false by default and when changed to true this would have citizens treat items as crackshot weapons, and use them if hostile. Pm me on bukkit:
colton1070
Thanks, alot of players would enjoy compatibility with crackshot.

**Comment by mcmonkey4eva** [comment]
Citizens do not do combat of any form, regardless of item.

**Comment by Colton1070** [comment]
with sentries, sorry

**Comment by Colton1070** [comment]
i should bring this to sentries then,

**Comment by mcmonkey4eva** [comment]
Yes. Though Sentry is no longer in active developmental so... probably you'd be better off begging the crackshot team to add support for things.
