### ISSUE TITLE
Nothing happens after command.

### ISSUE THREAD

**Issue by Nixee** [CitizensDev/Citizens2#458]
I am running the Citizens plugin on my MCProHosting server. I tried to do a command, but nothing happened after it. No message. No NPC. No nothing. I need to figure out why it's not working, or my server role play is in big trouble.

**Comment by Talamar1** [comment]
Probably the wrong version.  Look at the console for an error message.  What version of minecraft server are you running and which Cit did you install?

**Comment by Nixee** [comment]
I have 1.7.10 minecraft. The citizens thing is 1.8.... oh. Well there's my problem...

**Comment by Nixee** [comment]
Thank you! XD
