### ISSUE TITLE
Cant make a baby zombie!!!

### ISSUE THREAD

**Issue by Eboss34** [CitizensDev/Citizens2#459]
Please help!!!! I have tried to use the command to get a zombie to turn into a baby zombie and its not working! I found the command on the citizens wiki and whenever I type this "/npc zombiemod -b(aby)" it does nothing but come up with this "npc zombiemod (-b(aby), -v(illager)). Please Help!!

**Comment by mcmonkey4eva** [comment]
it's uh... `/npc zombiemod -b`

**Comment by Eboss34** [comment]
Thanks
