### ISSUE TITLE
Citizens 1.7.10 support?

### ISSUE THREAD

**Issue by madtomic** [CitizensDev/Citizens2#462]
Does the latest builds of citizens support 1.7.10 or only 1.8.x?

**Comment by mcmonkey4eva** [comment]
Latest builds are for 1.8.7, to get a 1.7.10 build (who knows why you would ever want that) you can grab it off BukkitDev or http://wiki.citizensnpcs.co/Versions

**Comment by madtomic** [comment]
Because Mojang changed how the npc names are shown and meta data aren't supported in 1.8

Thank you for the link.
