### ISSUE TITLE
Error on enabling

### ISSUE THREAD

**Issue by Likton** [CitizensDev/Citizens2#464]
Hi! I would to play on my server with your wonderfull plugin, but it seems that I get an error each time I'm trying to launch my server.
I've pasted the error(s) on the console. In fact, the plugin is green in the plugins list, but no commands can be done.
http://pastebin.com/2UbzqBt4

If you have an idea to help, I'll congratulate u and kiss your feet! :)

**Comment by Talamar1** [comment]
You are using a build for 1.8 on a 1.7 server.  Try this one:
http://ci.citizensnpcs.co/job/Citizens2/1166/

**Comment by Likton** [comment]
Thanks for fast answering! :p I'll try this! I'll send you back statement!

**Comment by Likton** [comment]
Effectivly! It's working well now! thanks a lot!
