### ISSUE TITLE
unknown issue

### ISSUE THREAD

**Issue by Likton** [CitizensDev/Citizens2#465]
Sorry, but it's me again. The plugin is installed, but, when i'm trying to create an npc with the command /npc create <name> , it returns an error.

http://puu.sh/jeTOv/d7581219ce.png

http://puu.sh/jeTNh/9ecf0fe522.png 

Do you have any idea about this error ? thanks to help me :)

**Comment by mcmonkey4eva** [comment]
Are you running MCPC? If so, cauldron.minecraftforge.net/threads/citizens-2-for-cauldron-1-7-10-released.289/

**Comment by Likton** [comment]
ho! Yes, it's exactly what I'm running. Sorry for the inconvence. And thanks to fast reply. :) I'll try this, and send you back statement.
