### ISSUE TITLE
Citizens Not Working

### ISSUE THREAD

**Issue by ritolika** [CitizensDev/Citizens2#466]
Basically i have a server with these plugins:
ActionBar API
Areashop
Armor effects
armor stand tools
ChestShop
CommandNpcs
essentials
factions
HealthBar
HologramDisplays
iconomy
ItemCommand
Kitadder
Mcore
MMarket
MobHealth
Multiworld
MyCommand
MythicMobs
Oreobfuscator
permissionEx
PlayerHeads
ShopKeepers
Skins
Vault
Worldedit Worldguard
And citizens 1.8.7
But citizens doesn't work i did /pl and it's green
So it should work but when i do a command nothing happens
 ERROR Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1251) (Is it up to date?)

**Comment by mcmonkey4eva** [comment]
Can you please **pastebin** a full startup log?
