### ISSUE TITLE
Skins Refusing to Load

### ISSUE THREAD

**Issue by logicalPolaris** [CitizensDev/Citizens2#468]
Running newest 1.8.7 Spigot and Citizens build #1251.

This bug takes place 9/10 of the time. The other 1/10 the skin loads. It's a bug I believe occurs when loading multiple NPC skins at one time. It might time out or something.

**Comment by Yooly** [comment]
I also encountered this bug,

**Comment by qwertyfat** [comment]
I have this bug as well.

**Comment by seedie** [comment]
This bug seems more common than anyone realises, its been in every recent build. I believe it has been fully fixed in an older version, however that version had the tablist bug where all the names were constantly on it (now those names only flash now and then if you are close to NPCS) Its been reported many times but nothing is ever done, or if it is...it's not tested properly.  Plugin would be perfect if these issues were fixed, its the only thing stopping me from donating.

**Comment by qwertyfat** [comment]
This has been up for 15 days and nobody knows how to fix it?

**Comment by Fortifier42** [comment]
@seedie 
>  Its been reported many times but nothing is ever done, or if it is...it's not tested properly.

This isn't something easily fixable as you/we are creating fake players. They're going to show up at some point. Go bug Mojang if you want fixes.

**Comment by JCThePants** [comment]
I started working on this issue using the latest respository as of Sunday. It's not 100% perfect, but so far it seems far more stable in terms of getting skins loaded. 
https://www.dropbox.com/s/9lvd9p8gw8gdozh/CitizensTest1.8.8.jar?dl=0

**Comment by mcmonkey4eva** [comment]
@JCThePants Anything worthwhile you fix, please do PR.

**Comment by JCThePants** [comment]
PR'd. Just needed some time to clean up my mess.

**Comment by qwertyfat** [comment]
The commands don't show up when I do /npc.

**Comment by JCThePants** [comment]
The jar I provided is for Bukkit/Spigot 1.8.8.

**Comment by qwertyfat** [comment]
Temporary Fix found(works with multiverse): 
1. Install the latest dev build(citizens-2.0.16-SNAPSHOT) 
2. Enable command blocks on your server.
3. Make some npcs with skins.
4. Save your npcs with /citizens save.
5. Place a command block with the command /citizens reload.
6. Place a button in front and click it a couple times.
This should now make your npc's skins work about 2 seconds after entering that world.

**Comment by seedie** [comment]
@JCThePants Thank you for trying! it seems noticeably better so far, but as you say it is not 100%. From what i have seen is it a great improvement.

@qwertyfat Won't you keep having to press that button quite often though?

**Comment by JCThePants** [comment]
@qwertyfat I updated the test jar. It didn't include some language resource files in the jar and was causing the commands to not work.

**Comment by JCThePants** [comment]
More commits. Much improved. Updated drop box link above.

**Comment by logicalPolaris** [comment]
This build has fixed 99% of all skin bugs. I've only seen the bug like once, and I've been using this build for a week. Thank you so much for this pull request.

**Comment by qwertyfat** [comment]
Still can't see the commands with CitizensTest1.8.8 but they show up with /help citizens. Please help, I really want to use citizens on my server.

**Comment by qwertyfat** [comment]
@seedie No, once you press it they reload when you get in the chunk.

**Comment by JCThePants** [comment]
@qwertyfat I don't know what to tell you. It's working for me. Maybe your still using the old file?

@logicalPolaris Your welcome. 

I was having issues as well and figured the Citizens team has their hands full with maintaining this project and whatever other projects they are working on. Maintaining NMS code has to be a huge pain and I appreciate the work they do here.

**Comment by qwertyfat** [comment]
Ok, switched to paper spigot 1.8.8 and it works great. Thanks so much!

**Comment by GeForcez** [comment]
same problem here but sometimes the skin loads but the 3d kinda skin (layer above the skin new in 1.8) doesnt load

**Comment by mcmonkey4eva** [comment]
@GeForcez there's a separate issue for that.
