### ISSUE TITLE
Config Not Saving

### ISSUE THREAD

**Issue by Mythanh123** [CitizensDev/Citizens2#469]
The config for the Citizens 2 plugin doesn't save the config. I've tried /citizens save before /citizens reload and it still doesn't work. It keeps resetting after reload to the original one. I can't seem to solve the problem. I know I'm not doing the config wrong because I changed one thing (True or false) and it still resets. I hope you can resolve this issue asap! Thanks!

**Comment by mcmonkey4eva** [comment]
You can only edit the Citizens config while the server is offline.

**Comment by Mythanh123** [comment]
I did what you said but I still would not work. My steps: I turned off Server, went to config, changed what I needed. Saved File. Turned on server. Still config the same as default.

**Comment by Mythanh123** [comment]
@mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
I... have no idea what that's about. It's not a Citizens issue, it's something lower level...

**Comment by smallboy12153** [comment]
Having the same issue

**Comment by mcmonkey4eva** [comment]
Do either of you have any more useful information than what's already been provided? Perhaps an error in the console that may be related?
