### ISSUE TITLE
Update to 1.8.8

### ISSUE THREAD

**Issue by CKGAR** [CitizensDev/Citizens2#470]
Citizens breaks on the latest Spigot build (1.8.8)

28.07 20:20:35 [Server] INFO Disabling Citizens v2.0.16-SNAPSHOT (build 1242)
28.07 20:20:35 [Server] ERROR v2.0.16-SNAPSHOT (build 1242) is not compatible with Minecraft v1.8.8 - try upgrading or downgrading Citizens. Disabling.
28.07 20:20:35 [Server] INFO Enabling Citizens v2.0.16-SNAPSHOT (build 1242)

**Comment by mcmonkey4eva** [comment]
You can try disabling version check in your config - haven't checked if that'll work with 1.8.8 yet though.

**Comment by CKGAR** [comment]
That worked. Sorry if that solution was posted in previous update tickets, I'm a lazy bastard xD
