### ISSUE TITLE
Sentry error

### ISSUE THREAD

**Issue by SilverDark6** [CitizensDev/Citizens2#472]
I am trying to run sentry with citizens version 2.0.14 and every time I try the /trait sentry command on an NPC it shows an error message that looks like this in the console:

02.08 15:44:25 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
02.08 15:44:25 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
02.08 15:44:25 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
02.08 15:44:25 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
02.08 15:44:25 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.Packet
02.08 15:44:25 [Server] WARN at java.lang.Thread.run(Thread.java:745)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:645)
02.08 15:44:25 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:262)
02.08 15:44:25 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919)
02.08 15:44:25 [Server] WARN at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058)
02.08 15:44:25 [Server] WARN at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625)
02.08 15:44:25 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
02.08 15:44:25 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
02.08 15:44:25 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:606)
02.08 15:44:25 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.08 15:44:25 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02.08 15:44:25 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:88)
02.08 15:44:25 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:109)
02.08 15:44:25 [Server] WARN at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
02.08 15:44:25 [Server] WARN at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
02.08 15:44:25 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Packet

This prevents the plugin from working and I have no Idea what the problem is

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Sentry#Updates wrong version of Sentry.
