### ISSUE TITLE
Citizens not working

### ISSUE THREAD

**Issue by strc0pier** [CitizensDev/Citizens2#475]
I have citizens green on plugins list, but I am not able to spawn an npc. The command doesnt even show anything /npc command doesnt work either.

**Comment by zombieninja546** [comment]
same here

**Comment by mcmonkey4eva** [comment]
Make sure you downloaded the correction version ~ http://wiki.citizensnpcs.co/Versions

**Comment by strc0pier** [comment]
The links wont work there. Could you give me an external download for 1.8.3 versioon please.

**Comment by mcmonkey4eva** [comment]
Sorry, our network is currently down, so you'll have to wait a few days while we get things back online...

**Comment by mcmonkey4eva** [comment]
Is everything good now? (The network has been up for a few days, sorry, forgot to ping back sooner)
