### ISSUE TITLE
Citizens crashing the server

### ISSUE THREAD

**Issue by TheKosciany** [CitizensDev/Citizens2#478]
Hey. I have severe problem with Citizens. Since I moved my server to 1.8 strange thing happens. On my server I use TownyChat. When i try to use command to forward the message through command to specific chat channel (Like this: "/admin Hey guys!"), server crashes. Normal chatting works flawless. I was surprised to found that this issue happens ONLY when Citizens is installed, after you use certain Citizens commands - eg. enter and exit from "/npc path" editor or when your server has NPC with waypoints.
You can clearly see the issue in this fragment of log: http://pastebin.com/W8Jy8Et3
I checked this on 3 servers: my live server and two test servers. Everytime the server hangs, then crashes. I totally believe this is a Citizens issue as it wasn't present in previous versions (1.7.10) and TownyChat didn't change anything at all from that time and on previous version everything worked fine.
Sorry, if my report is a bit chaotic.... I spent whole night debugging this stuff :D Thank you for answering and any help in this stuff. I really want this fixed, because... Just any player is able to crash the server using one command.

EDIT: I forgot to mention: My Spigot version is 1.8.6, I am using TownyChat v45 but it happens on all versions. My Citizens version doesn't matter, because I tried reproducing it on all versions from Jenkins that are labelled 2.0.16 and everytime it crashed. Let's just assume I have latest Jenkins version of Citizens #1251.

**Comment by mcmonkey4eva** [comment]
... That makes... no sense at all... that crash /is/ from Citizens, but ... space knows how the `/a s` command is causing Citizens to misbehave..

Can you replicate this with **latest versions of everything** - Spigot, Towny/TChat/Citizens/etc.?

**Comment by TheKosciany** [comment]
I edited my post. I did tests on latest versions too. I really don't know what the hell is happening there :D

**Comment by Morphan1** [comment]
Can you post the entire error log and inform us of any other plugins you have?

**Comment by TheKosciany** [comment]
Sure: http://pastebin.com/f6UZyAic
http://imgur.com/ANjGbLc

Problem persists even on test server with Citizens, Towny, TownyChat, PEX and Vault.

**Comment by Morphan1** [comment]
Uhhh... The crash log isn't in there

**Comment by TheKosciany** [comment]
Sorry, I'm absent minded. http://pastebin.com/1HeLgqzf

**Comment by TheKosciany** [comment]
It doesn't crash instantly. Server hangs for 10-15 seconds after command and then it crashes.

**Comment by mcmonkey4eva** [comment]
How about a log from the `test server with only Citizens, Towny, TownyChat, PEX and Vault.`?

Also, there's a suspicious lack of Citizens references in that new error log.

**Comment by TheKosciany** [comment]
God... This time i tested clean server "with only Citizens, Towny, TownyChat, PEX and Vault" it worked flawlessly. And then I added Denizen and it crashed. Sorry for whole fuss out there, I bet it's denizen. The crash log got me confused as if it was Citizens fault.

**Comment by mcmonkey4eva** [comment]
Can you replicate it on /latest/ Denizen http://ci.citizensnpcs.co/job/Denizen/lastSuccessfulBuild/ ?

**Comment by TheKosciany** [comment]
Which version of Spigot should I have? On Spigot 1.8.6-R0.1-SNAPSHOT this Denizen crashes http://pastebin.com/gCLBqWVF

**Comment by TheKosciany** [comment]
But...  @mcmonkey4eva Nope. New version fixes the crash... For now. I'll try to use it and will update you if something happens again. Thanks for prompt responses and help :)
