### ISSUE TITLE
Sentry wont work

### ISSUE THREAD

**Issue by Eboss34** [CitizensDev/Citizens2#479]
I have the latest versions of both Citizens plugin and Sentry plugin and whenever I type /trait sentry, it does nothing and brings this up "please report this error: [see console] java.lang.noclassdeffounderror:net/minecraft/server/v1_7r1/packet"
I don't know what is wrong, no other arguments help and I cant find any Youtube videos to help either.
Please help!!!

**Comment by mcmonkey4eva** [comment]
Wrong version of Sentry -> http://wiki.citizensnpcs.co/Sentry#Updates

**Comment by Eboss34** [comment]
ok
