### ISSUE TITLE
If an NPC is destroyed on death, null pointers will happen

### ISSUE THREAD

**Issue by onbjerg** [CitizensDev/Citizens2#480]
Hello!

I am making a plugin where I only need NPCs until they die. I thought the best way (after poking around) to do this was to destroy the NPC on death. This resulted in null pointers in the onEntityDeath event of Citizens.

I also tried doing it on despawn (checking the despawn reason), but it doesn't work either.

I was thinking that maybe we should check if the NPC is destroyed after we call these events in the EventListen class?

**Comment by onbjerg** [comment]
This should be checked both when the NPCDeathEvent is called, and when the despawn of the NPC occurs.

Any other suggestions on how to do it?

**Comment by mcmonkey4eva** [comment]
You should delete the NPC 1 tick later using bukkit's scheduler to avoid trouble ideally.

**Comment by onbjerg** [comment]
This is what I am doing now, but ideally I shouldn't have to do it, unless you have some voodoo magic to perform when they die. If possible, could you call the event later, when it is safe to delete them?

**Comment by mcmonkey4eva** [comment]
It makes no sense to do that - what you're trying to do makes no sense.
You're taking an event - volatile active data that things are using... and /deleting some of that data/ from existence. It's the same as force-despawning an entity in an interactentity or death event - it'll get you in a lot of trouble with other plugins.

**Comment by fullwall** [comment]
The problem is the NPCDeathEvent is called before the NPC is despawned to allow you to check things like entity type etc. I have just pushed a change that may fix your problem however.

**Comment by mcmonkey4eva** [comment]
Assuming this is fixed.
