### ISSUE TITLE
Sentry is the only trait working

### ISSUE THREAD

**Issue by Eboss34** [CitizensDev/Citizens2#481]
Whenever I try a trait besides sentry like "Quests" it says it can be found. I don't know whats wrong with it. I'm wondering if I have to download a whole bunch of plugins to use those or what? Here is what it looks like. Please Help. You guys are greatly appreciated and have a lot of patients for all my probably stupid questions.

https://cloud.githubusercontent.com/assets/13354236/9151661/d18ea1a8-3dc7-11e5-8f02-1c8c15a00dcf.png

**Comment by Morphan1** [comment]
...Yeah, you need the plugins that add those traits to use those traits.

**Comment by mcmonkey4eva** [comment]
You can find relevant trait downloads on the sub pages of http://wiki.citizensnpcs.co/Citizens_Wiki
