### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by buttercreeper6** [CitizensDev/Citizens2#483]
When i go and try to do a command it doesn't work. but when i go and see if the plugin is ok it says its fine

**Comment by mcmonkey4eva** [comment]
Please post a full startup log.

**Comment by Mijeman** [comment]
I'm getting the same issue.  These are the only relevant logs that occur in the startup.

13.08 08:40:46 [Server] ERROR Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1247) (Is it up to date?)
13.08 08:40:46 [Server] INFO Creating file: config.yml
13.08 08:40:46 [Server] INFO Enabling Citizens v2.0.16-SNAPSHOT (build 1247)13.08 08:40:46 [Server] ERROR Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1247) (Is it up to date?)
13.08 08:40:46 [Server] INFO Creating file: config.yml
13.08 08:40:46 [Server] INFO Enabling Citizens v2.0.16-SNAPSHOT (build 1247)

**Comment by mcmonkey4eva** [comment]
That is not a full startup log, that is one in which you casually admitted there was an error but failed to post it.

**Comment by Mijeman** [comment]
I was just using the wrong Spigot version.  My mistake.

**Comment by mcmonkey4eva** [comment]
As the OP is dead, closing until they awaken.
