### ISSUE TITLE
Custom Skull/Base64 CitizensDeserialiseMetaEvent

### ISSUE THREAD

**Issue by TagCraftMC** [CitizensDev/Citizens2#484]
Just wanted to post this error on start up. It does not stop anything from loading and or working how it should (heads displaying the skin).
Pretty sure the issue stems from giving an NPC a custom skull that uses the Base64 encoding method discussed here: https://www.reddit.com/r/MinecraftHeads/comments/24rz62/important_changes/ or a head taken from this database: heads.freshcoal.com/maincollection.php and not having anything in the owner field of the skulls metadata.

Error: http://pastebin.com/9H197vqS
NPC: http://pastebin.com/X4irMv2p

**Comment by fullwall** [comment]
Fixed.
