### ISSUE TITLE
I have problem whit installing.

### ISSUE THREAD

**Issue by kungfalco** [CitizensDev/Citizens2#485]
When I'm trying to download it.

I can download it and install it.

But in game it dosen't work. In my plugin list it's red and I can't use the commands.

**Comment by mcmonkey4eva** [comment]
...???

**Comment by Fortifier42** [comment]
Use the version which corresponds to your spigot installation.

**Comment by kungfalco** [comment]
Okey..

Do you have 1.8.8?

**Comment by mcmonkey4eva** [comment]
And now with that edit, still barely any information.

I'm going to guess at random that you downloaded the wrong version.

Get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by Fortifier42** [comment]
For spigot 1.8.8 use the build found here:
http://ci.citizensnpcs.co/job/Citizens2/1251/

**Comment by kungfalco** [comment]
Do you need the API?

**Comment by mcmonkey4eva** [comment]
No.

**Comment by kungfalco** [comment]
Okey

**Comment by kungfalco** [comment]
But when I install it my multivers stops..

**Comment by mcmonkey4eva** [comment]
???

**Comment by kungfalco** [comment]
citizens-2.0.16-SNAPSSHOT.jar

Yes my multiverse-core and portal stop working

**Comment by Fortifier42** [comment]
Then... update your Multiverse? I have them running along-side fine.

**Comment by kungfalco** [comment]
okey..

**Comment by Fortifier42** [comment]
@kungfalco 
You done something wrong :sweat_smile: 
http://puu.sh/jB3uk/26549592ee.png

**Comment by kungfalco** [comment]
LOVE YOU GUYS! I DIDEN'T KNOW HOW TO ASK BEFORE!

I had this problem for like 4 moths! LOVE YOU<3
