### ISSUE TITLE
Lookclose gives error: java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by StratDigital** [CitizensDev/Citizens2#486]
Says please report this error, whenever I have an npc selected and type /npc lookclose this error pops up(In title).

Said see console, so I looked and this is what it said

16.08 00:48:05 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
16.08 00:48:05 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
16.08 00:48:05 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
16.08 00:48:05 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
16.08 00:48:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
16.08 00:48:05 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
16.08 00:48:05 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
16.08 00:48:05 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
16.08 00:48:05 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
16.08 00:48:05 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
16.08 00:48:05 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.commands.NPCCommands.lookClose(NPCCommands.java:728)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:224)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.getTraitFor(AbstractNPC.java:231)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.npc.CitizensTraitFactory.getTrait(CitizensTraitFactory.java:119)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.npc.CitizensTraitFactory.create(CitizensTraitFactory.java:112)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.api.trait.TraitInfo.tryCreateInstance(TraitInfo.java:41)
16.08 00:48:05 [Server] WARN at java.lang.Class.newInstance(Unknown Source)
16.08 00:48:05 [Server] WARN at java.lang.reflect.Constructor.newInstance(Unknown Source)
16.08 00:48:05 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
16.08 00:48:05 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
16.08 00:48:05 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.trait.LookClose.<init>(LookClose.java:23)
16.08 00:48:05 [Server] WARN at net.citizensnpcs.Settings$Setting.asBoolean(Settings.java:124)
16.08 00:48:05 [Server] WARN java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean

**Comment by mcmonkey4eva** [comment]
Please post your Citizens config.yml

**Comment by StratDigital** [comment]
# Citizens Configuration

npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  default:
    look-close:
      enabled: enable
      range: 5
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-speed: 100
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
  pathfinding:
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  controllable:
    use-boat-controls: true
  tablist:
    disable: true
advanced:
  check-minecraft-version: false
general:
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
economy:
  npc:
    cost: 0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins

**Comment by mcmonkey4eva** [comment]
`       enabled: enable`

.... that... you ... what. That is definitely not how configuration files work.

Fix that line in your config to fix the error :)

**Comment by StratDigital** [comment]
Brain. Fart.
