### ISSUE TITLE
Bandwidth usage issue...

### ISSUE THREAD

**Issue by Blackyvk** [CitizensDev/Citizens2#488]
So... I installed Citizens

and for somereason everytime i add an NPC bandwidth usage raises, each npc sums more, the more npc i add the more bandwidth it takes.

Its a weird problem, i have used citizens in other of my server and bandwidth doesnt go over 30kbps.

if i remove the citizens.jar the problem is gone... Also I tried once to recreate the world (not the region) files and the problem was gone but later the problem came back. And also tried to create an npc in s different world in the same server and no problem, i have this problem right now in 2 of my world and the multiverse settings are almost the same, there is no difference in the world settings.

Citizens version: 2.0.16-SNAPSHOT (build 1251)
Multiverse-Core 2.5 build 697
Spigot 1.8.8

**Comment by hsmallbone** [comment]
How are you measuring bandwidth?

**Comment by Blackyvk** [comment]
the level.dat file is the one causing it.... and i have 2 samples

http://www.filedropper.com/leveldat

rename levelbad.dat to level.dat  and try it, if you have npc in that world ( i think they need to be near you) the bandwidth raises more than it should, if you use the levelgood.dat it wont.... why is happening ?

**Comment by fullwall** [comment]
The only difference between those two level.dats is one has daylightcycle set to true (levelgood.dat) and the other false (levelbad.dat). There is no reason that this should cause a difference and I couldn't reproduce this.

**Comment by Blackyvk** [comment]
did you try my files ? i thought it was the gamerule  but for it isnt or maybe it is but only happens after sometime with the world running....

is it normal for DayTime rainTime  and Time to be that high ?

**Comment by fullwall** [comment]
Yes it is normal.

**Comment by Blackyvk** [comment]
not cpu, bandwidth...  the server cpu and ram is fine, is just the bandwidth increase.

when i change the gamerule doDaylightCycle to true of the bad file, the bandwidth goes back to normal...

see 
![2015-08-23_13-14-38](https://cloud.githubusercontent.com/assets/9063912/9429418/2141ec0a-4999-11e5-9d6e-e3fc2e4d9b77.png)

**Comment by fullwall** [comment]
I just looked into the code for doDaylightCycle, I can't see how it's connected to NPCs at all.

**Comment by Blackyvk** [comment]
well the thing is that only affect when npcs are on that world with that gamerule after sometime... the only fix i find is to remove the rule use wg to change the time... hopefully it will work that way.

**Comment by fullwall** [comment]
Do you have keep-chunks-loaded: true in your config? Maybe your server can't handle the bandwidth of keeping those chunks alive.

**Comment by Blackyvk** [comment]
no, the problem only happens when the user is on that world, the chunk isnt loaded until you go there... and actually, that bandwidth usage is client side, red is download (near 600kbps) yellow upload, this server can handle it the problem is user with slow connection suffer when they are near an npc, and they are just standing there, the client is clean no mods or anything.... i thought it was the MV devbuild  but I tried the old one and still happens....

**Comment by mcmonkey4eva** [comment]
Any updates on this issue?

**Comment by Blackyvk** [comment]
no, I just stopped changing the gamerule and used a different plugin to control the time, thats the only way I can make it work without problems... If you cant reproduce this you can close this issue, I stopped trying.
