### ISSUE TITLE
NPC name not showing all the time

### ISSUE THREAD

**Issue by GlitchDoesMC** [CitizensDev/Citizens2#489]
Hello,

I'm using Spigot 1.8 and I have just joined my server. One thing I noticed is that the NPC names were not showing. They were shown when I hover my cursor over them, but I want it to show all the time. They were shown all the time in 1.7, though. Even when I do /npc name it still doesn't show permanently.
I'm using Citizens 2.0.13 SNAPSHOT and Spigot 1.7.10-R0-1.

Thanks in advance, 
GlitchDoesMC

**Comment by mcmonkey4eva** [comment]
Recent restriction imposed by mojang - we're still looking for solid workarounds (EG holograms)...

**Comment by fullwall** [comment]
Fixed...?
