### ISSUE TITLE
Click Event Not Being Called

### ISSUE THREAD

**Issue by PaulBGD** [CitizensDev/Citizens2#49]
Added a custom trait, but when I go to click on the NPC no event is fired. I tried PlayerInteractEntity as well, still no event. Everything in the plugin that has to do with clicking (such as clicking to ride) works however. I'm running the latest dev build off the server.

**Comment by superpeanut911** [comment]
I'm having the same issue here, we may be doing something wrong but


 on the onEnable:
CitizensAPI.getTraitFactory().registerTrait(net.citizensnpcs.api.trait.TraitInfo.create(LobbyTrait.class).withName("Lobby"));


In the trait class:
@EventHandler
    public void onClick(NPCClickEvent event) {
        System.out.println("click");

NPC does have the trait, (Confirmed with onAttach) the click event does not get called. I have also tried registering the class normally with no luck either.
