### ISSUE TITLE
when mounting controllable NPC, ASD doesn't work

### ISSUE THREAD

**Issue by cjunekim** [CitizensDev/Citizens2#492]
I am running the citizens-2.0.16-SNAPSHOT.jar with CraftBukkit-1.8.8. When the player mounts a controllable NPC, you can only move forward with W key. A, S, and D keys do not work.

Is it expected?

**Comment by mcmonkey4eva** [comment]
What type of NPC?

**Comment by cjunekim** [comment]
Pig, horse, and villager. I haven't tried other types. Only W key works -- directing with mouse works though.

**Comment by mcmonkey4eva** [comment]
@cjunekim Can you confirm this was fixed properly in latest dev builds?

**Comment by cjunekim** [comment]
I tested it with the latest build from http://ci.citizensnpcs.co/job/Citizens2/ .

It does not work, either.

**Comment by mcmonkey4eva** [comment]
cannot replicate on current builds, controllable fully works in my testing
