### ISSUE TITLE
Domain expired!

### ISSUE THREAD

**Issue by Zetaphor** [CitizensDev/Citizens2#493]
http://citizensnpcs.co/ is no longer online. Looks like the domain has expired!

**Comment by fullwall** [comment]
Yes, known issue. In contact with domain registrar about it... someone forgot to renew the domain.

**Comment by mcmonkey4eva** [comment]
Oh god not this again

**Comment by KaidaSeren** [comment]
I keep getting an error ....java.lang.NoClassDefFoundError:.... is this why?

**Comment by drew5494** [comment]
Is there another way of getting a dev build at the moment?

**Comment by mcmonkey4eva** [comment]
http://citizens.playat.ch:8080/job/Citizens2/

**Comment by drew5494** [comment]
Thanks a lot man!

**Comment by KarmaPanda** [comment]
Thanks for the link @mcmonkey4eva

**Comment by CorporalBruno** [comment]
@mcmonkey4eva im new around here but very in love with the work. I'll mirror your domain info on my network for free. So if this ever happens again you have a backup place to send ppl. Let me know.

**Comment by mcmonkey4eva** [comment]
Thanks but no need - We have several alternate domains available, it's just our primary one got messed up. It should in theory be fixed in the next few days.

**Comment by fullwall** [comment]
Domain should be up, and I will be renewing it from now on.
