### ISSUE TITLE
Latest Dev build issues

### ISSUE THREAD

**Issue by Foreme** [CitizensDev/Citizens2#497]
In my hub I have multiple rabbit npc's all set to be facing the middle of the spawn. In this hub I also have 1 wither skeleton and 1 donkey.

The issue with the rabbits is that after a few restarts they no longer keep their original direction. They are all facing random directions now.

The wither skeleton, every restart he slowly drifts further and further away from his set location. After about 7 restarts or so he is almost 2 blocks away.

The donkey, well.. He doesn't have a saddle but people can ride him~

**Comment by CorporalBruno** [comment]
My npc's are also drifting after time / restarts haha. I only have a couple, thought it was just me, but one wasn't pushable after checking. spigot 1.8.8 latest build of cit2 w/ denizens

**Comment by Talamar1** [comment]
Lastest build as of 1 hour ago?

**Comment by CorporalBruno** [comment]
Im installing now to test. <3

**Comment by Foreme** [comment]
Latest version~

Can still ride the donkey
Rabbits now cannot have their direction changed when doing /npc tphere
Not sure if the wither is gonna slide away, will have to do a few restarts

**Comment by Foreme** [comment]
I think there is an issue saving pitch
in saves.yml pitch for all is 0.0

**Comment by Foreme** [comment]
Alright yeah I think the slidey thing is fixed, just the other two issues~

**Comment by Foreme** [comment]
Yeah no, the skele still moves away

**Comment by fullwall** [comment]
Fixed

**Comment by Foreme** [comment]
Donkey bug is fixed, only thing left if the wither skeleton
"The wither skeleton, every restart he slowly drifts further and further away from his set location. After about 7 restarts or so he is almost 2 blocks away."

**Comment by fullwall** [comment]
Is that just a skeleton with WITHER type?

**Comment by Foreme** [comment]
Yeah

**Comment by fullwall** [comment]
Can a reload trigger it?

**Comment by Foreme** [comment]
I'm not sure

**Comment by Foreme** [comment]
I'm not sure if its just restarts either, i've never seen it move with my own eyes.. just came on and its been moved (I'm the only one who can edit npc's)

**Comment by KeangDavid** [comment]
Couple ideas for the wither skeleton that might make it an odd case. It is ~3 blocks tall so its surroundings may affect it. Also is there anyway AI would be active temporarily making it want to move when it first loads? What direction is it drifting, what towards?

**Comment by fullwall** [comment]
I think I have figured out the cause, just need some reproduction steps to make sure.

**Comment by Foreme** [comment]
You can always just upload it and ill throw it in my server and if it ever happens again ill let you know

**Comment by fullwall** [comment]
Try the next build, should be better.

**Comment by Foreme** [comment]
Alright thanks

**Comment by fullwall** [comment]
1282

**Comment by Foreme** [comment]
/npc type wither
(Was already a normal skeleton) and it just disappeared

**Comment by fullwall** [comment]
Don't you mean /npc skeletontype wither

**Comment by Foreme** [comment]
Oh..... for some reason I had to delete the npc and remake it to get it a wither after doing that. But yeah oops wrong command. I have a wither now so i'll let you know if it drifts away again
