### ISSUE TITLE
2.0.14 /npc create not working

### ISSUE THREAD

**Issue by GRRRillaNinja** [CitizensDev/Citizens2#499]
Console error said to report this so here I am :)

I tried using the latest 2.0.16 dev build also, but commands wouldn't work at all so I switched back to 2.0.14

29.08 20:22:15 [Server] WARN at java.lang.Thread.run(Thread.java:745) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) 29.08 20:22:15 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266) 29.08 20:22:15 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) 29.08 20:22:15 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) 29.08 20:22:15 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) 29.08 20:22:15 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 29.08 20:22:15 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154) 29.08 20:22:15 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497) 29.08 20:22:15 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 29.08 20:22:15 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 29.08 20:22:15 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47) 29.08 20:22:15 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92) 29.08 20:22:15 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

**Comment by mcmonkey4eva** [comment]
Wrong version ~ http://wiki.citizensnpcs.co/Versions

**Comment by GRRRillaNinja** [comment]
Ah thanks! I thought I was using Spigot 1.8.1 but it's actually 1.8.3 but it's working now. :)
