### ISSUE TITLE
Naming extension - Sub Title

### ISSUE THREAD

**Issue by madtomic** [CitizensDev/Citizens2#500]
I was wondering if this is achievable? Maybe using ProtocolLib or Scoreboard?

Maybe add a way to add sub title names to Citizens?

/npc subtitle npcsubtitle

As well supporting colors/formats. /npc subtitle &3[&6Sub Title&3]

So it would appear

Soanso - npc name
[Sub Title] - another name appear below the npc name

**Comment by mcmonkey4eva** [comment]
Minecraft doesn't support 'subtitles' on NPC names natively.
(You can a score subtitle: a single global message that appears for everyone but has a unique number per person... but that's probably not what you want)

You'd probably have to use a hologram plugin to achieve that...

**Comment by madtomic** [comment]
@mcmonkey4eva
Which hologram would you recommend to use for this effect?

**Comment by mcmonkey4eva** [comment]
Any given hologram / holographic display plugin will do.
