### ISSUE TITLE
Formatting codes use character space in player nametags

### ISSUE THREAD

**Issue by ssamjh** [CitizensDev/Citizens2#506]
See the title.

For example when I name a npc CaptainDemonDean it will show the whole name. But if I make it blue (&1CaptainDemonDean) it only says CaptainDemonDe.

**Comment by mcmonkey4eva** [comment]
Yes. That happens.

Either way, we've fixed the limit being so small via scoreboards in more recent versions, so you can fit such a long name now.
Update your server :)

**Comment by ssamjh** [comment]
Is that fixed in Build #1257?

http://ci.citizensnpcs.co/job/Citizens2/1257/

**Comment by mcmonkey4eva** [comment]
That's latest dev build so yes.
