### ISSUE TITLE
"/questadmin purge" blacklisted everyone

### ISSUE THREAD

**Issue by bdr498** [CitizensDev/Citizens2#509]
I wanted to clear someone's quest data so I used /questadmin purge [name], which worked, however it also appears to have blacklisted everyone.  No normal players or even ops are able to use and /quest commands and are greeted by the message that they are blacklisted and should contact a server admin if it is in error.  How can I un-blacklist everyone from this "blacklist" and prevent this from happening in the future?

**Comment by Fortifier42** [comment]
That.. is not a Citizens error, that is a quest plugin error
