### ISSUE TITLE
Crashing when tping near a npc

### ISSUE THREAD

**Issue by Markusi13** [CitizensDev/Citizens2#510]
If you tp near a npc it crashes your game and gives you this message: http://i.imgur.com/v35zcfS.png
We use the build: 2.0.16-SNAPSHOT (build 1255)
Thank you for your time.

**Comment by JCThePants** [comment]
This is fixed in the latest build (1257)

http://ci.citizensnpcs.co/job/Citizens2/

**Comment by Markusi13** [comment]
Ah ok thank you for your quick answer.
