### ISSUE TITLE
Color Options

### ISSUE THREAD

**Issue by KreatorB** [CitizensDev/Citizens2#511]
It would be nice if you could use the Minecraft color codes to change the set ups of the NPC Name and message sent out! 
Example §8BOB: §7Hello I am BoB!
And also set the color a-top his head also. ;-)
If it could set via a program like chatex or pex permissions that would also be great.

What is the purpose of connecting citzens2 into iconomy and vault. How do you do it?

**Comment by mcmonkey4eva** [comment]
You can do the colors - `&5` or whatever. It translates correctly.

**Comment by KreatorB** [comment]
Thank You I was not using the using this & I was using §... I have one more question. Can the Name above the NPC head be changed as I can not find it anywhere. It is white and I would like to make it Green. Is that possible? Thank you for your time it works really good in MC 1.8.7

As for the Vault I found that info. ;-)

**Comment by fullwall** [comment]
Yes, use the color code for green &2 in the NPC name.

**Comment by KreatorB** [comment]
I am sorry that does not work. In the Save file for NPC Name: MyName I tried &a and '&a' the first one removed the NPC and the second removed them all.

**Comment by mcmonkey4eva** [comment]
... wut. What did you enter exactly?
