### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChickenNuggetNG** [CitizensDev/Citizens2#512]
So every time i load the plugin it never works i do /npc /citizens and npc never has it worked i tried diferent verison but never seems to work

**Comment by mcmonkey4eva** [comment]
Are you sure you tried the /correct/ version http://wiki.citizensnpcs.co/Versions - that's the problem 99% of the time. Trying way wrong versions.

**Comment by ChickenNuggetNG** [comment]
Yea I've tried multiple version none worked

**Comment by mcmonkey4eva** [comment]
... which versions? What version is your server? Do you have any error logs of the /correct/ version not working?

**Comment by ChickenNuggetNG** [comment]
1.8.8 and ive used like 5 versison for this then i downgraded the server and still did not work

**Comment by mcmonkey4eva** [comment]
Have you tried the **latest dev release** while on a 1.8.8 server?
