### ISSUE TITLE
Config setting not working!

### ISSUE THREAD

**Issue by KreatorB** [CitizensDev/Citizens2#513]
The following configs not working, I have tried them and set them multi times restarted server and even tried left click, right and different items... Both do not react... Any ideas.. If you want to test those to options are on and running in config. Just visit iplay.mc-srv.com thanks once again

default:
    look-close:
      enabled: true
      range: 5
and
  talk-item: '388'

**Comment by mcmonkey4eva** [comment]
Sorry, I appear to have missed this issue. We recommend using Denizen -> http://wiki.citizensnpcs.co/Denizen -> for handling NPC interaction, as the builtin NPC interaction is rather limited and underdeveloped at the moment.
