### ISSUE TITLE
[Suggestion] UnregisterTrait Method

### ISSUE THREAD

**Issue by redcreep76** [CitizensDev/Citizens2#515]
Hello all, i am working on a plugin who use CitizensTrait API to add new trait, and i noticed that when we reload our plugin with custom Trait Citizens throw an IllegalArgumentException because the trait name is already registered, so my suggestion is to create a method to unregister traits when our plugin is disabled. Here an example of what i mean : 

Class CitizensTraitFactory : (in package net.citizensnpcs.npc)

    public void unregisterTrait(String name) {
         if (!this.registered.containsKey(name)) {
	     throw new IllegalArgumentException("trait name not registered");
	 }
        TraitInfo info = this.registered.remove(name);
        if (info.isDefaultTrait()) {
            this.defaultTraits.remove(info);
        }
    }

Class TraitFactory : (in package net.citizensnpcs.api.trait)

     public abstract void unregisterTrait(String paramString);

And here an example of a CustomPlugin :

    public void onEnable() {
 CitizensAPI.getTraitFactory().registerTrait(TraitInfo.create("TraitClass").withName("TraitName"));
 }

   public void onDisable() {
        CitizensAPI.getTraitFactory().unregisterTrait("TraitName");
   }

I hope this suggestion can help you and you will find an utility of this method, its a little thing but usefull for server who dont want to restart when they modify plugin with custom trait but reload the plugin with plugin like 'PluginReloader'.

Thanks for your attention.
Best regards, Redcreep76.

**Comment by mcmonkey4eva** [comment]
While this is a reasonable suggestion...

We **very strongly** recommend **never** reloading Citizens or related plugins through any means external to the plugin itself. IE, `/citizens reload` is fine but `/reload citizens` is not.

**Comment by mcmonkey4eva** [comment]
@fullwall not sure why you closed this?

**Comment by mcmonkey4eva** [comment]
Apparently this was implemented. : D
