### ISSUE TITLE
Builder for 1.8.7 not loading at all

### ISSUE THREAD

**Issue by ScratchVinyl** [CitizensDev/Citizens2#519]
I updated my server today, including citizen, sentry and builder.
Sentry works just fine, but Builder won't even load!

Line 11: [13:55:37] [Server thread/ERROR]: Could not load 'plugins/Builder.jar' in folder 'plugins'

**Comment by Talamar1** [comment]
if you updated your server, it should be running 1.8.8, 1.8.7 was a few weeks ago.

**Comment by ScratchVinyl** [comment]
Nitrado still offers only the 1.8.7

**Comment by Talamar1** [comment]
Where did you download it from?
http://ci.citizensnpcs.co/job/Builder/lastSuccessfulBuild/artifact/target/Builder.jar

**Comment by ScratchVinyl** [comment]
I downloaded the matching version from there, yes

**Comment by Talamar1** [comment]
Which build of Citizen are you running?
http://wiki.citizensnpcs.co/Versions

**Comment by mcmonkey4eva** [comment]
Closing on the assumption this is either resolved or the poster is missing (lack of response); please reply below if you wish for the issue to be reopened.

**Comment by fireboyev** [comment]
I would like to reopen this

My builder plugin isn't loading either? and I have the latest version and i run spigot

**Comment by mcmonkey4eva** [comment]
@fireboyev are you running the version Talamar linked?

**Comment by Fortifier42** [comment]
It loads and works for me - Spigot 1.8.8
