### ISSUE TITLE
Citizens appearing in [TAB] menu for seconds and then disappears.

### ISSUE THREAD

**Issue by captainploo** [CitizensDev/Citizens2#524]
I have a Citizen that has my skin. I enabled the Citizen to appear in the [TAB] Menu. Though, when I go look in it the player name doesn't appear. I reloaded the server and the name appeared for a millisecond and then disappeared. What is going on?
![2015-10-02_18 49 32](https://cloud.githubusercontent.com/assets/14896548/10259456/680db5da-6936-11e5-9900-060c9dff9c79.png)

**Comment by mcmonkey4eva** [comment]
Expected; that's a limitation Mojang arbitrarily forced upon us in 1.8 and some 1.7 versions of minecraft. Just ignore it.
