### ISSUE TITLE
npcs clone them selves.

### ISSUE THREAD

**Issue by ravenfallls** [CitizensDev/Citizens2#525]
npc's for some reason are cloning them selves, there is only 1 id for the pair and if one is deleted the other remains with no info on them in the configs, which leads to the server logs becoming filled with errors.

**Comment by Fortifier42** [comment]
Recommend updating your stuffs (spigot, citizens)

**Comment by ravenfallls** [comment]
have the latest version of all plugins.
and as annoying as this is, though the cmd screen will fill with errors and lag the server, none of it has been recorded in my logs.

**Comment by Fortifier42** [comment]
Can't actually find out what's wrong without a log generally :)

**Comment by mcmonkey4eva** [comment]
Please reply below with a log (even just a screenshot of console errors) or other helpful information, and we will reopen the issue.
