### ISSUE TITLE
Server keeps randomly crashing with citizens npc's at spawn

### ISSUE THREAD

**Issue by Elvi81** [CitizensDev/Citizens2#526]
Here's the crash log, i can't make much sence out of it but maybe you guys can.
http://pastebin.com/Jwzw4unj

**Comment by mcmonkey4eva** [comment]
What build of Citizens are you running?

**Comment by Elvi81** [comment]
1262

**Comment by mcmonkey4eva** [comment]
That is latest, and you have a recent Spigot... gonna have to ping @fullwall here, no idea why this would occur 0.o

**Comment by Elvi81** [comment]
It's not the first time it's happend, even older builds have caused it but no clue why, other than it seems to sometimes happen when players use the /back command of spigot essentials or maybe /spawn, happend once when i just flew closer to spawn.

**Comment by Fortifier42** [comment]
Do you have an insane number of NPC's around or doing stuff around spawn?

**Comment by Elvi81** [comment]
No about 5 around spawn, 1 of them talking, then another 2 combined with betershops near there and that's it, there's tons elsewhere but that's just around spawn.

**Comment by mcmonkey4eva** [comment]
So uh... I've not seen this before, and have no idea why it would happen >.> any additional info you can gather for us?
Perhaps up to potentially creating a small-scale test server, zipping it up and letting us run it so we can see the error in real time?

**Comment by fullwall** [comment]
I better put my current investigations in this issue I guess - basically what I think is happening is the player list is changing somehow while a player NPC is spawning and while a packet is being sent - it points to some kind of async issue which may or may not be citizens related. I pushed a small change recently which may have fixed the problem (basically delaying when the NPC is removed from the player list).

**Comment by Elvi81** [comment]
It hasn't happend for a while now but i will continue to monitor the server as it's not always activly used either.

**Comment by Elvi81** [comment]
Okay it happend and this time with the beta 1 build you had on the bukkit pages, this time i had to force shutdown the server too as it wouldn't go down on it's own.
Here's the error report.
http://pastebin.com/LAFMV7pk

**Comment by Elvi81** [comment]
Just wondering, what java do you guys run usualy? atm i'm running the old 8u31, i remember when u4x came out and it screwed up a lot of plugins so i went back to u31.

**Comment by mcmonkey4eva** [comment]
We build for and generally run the latest version of Java 7, not 8.

**Comment by Elvi81** [comment]
And again http://pastebin.com/gfAwt36b
This time with citizens build 1274 and spigot git-Spigot-5f38d38-18fbb24
Oddly enough it didn't crach the server just flooded it with those errors then came back after some minutes.

**Comment by fullwall** [comment]
Seems like the thread gets locked forever waiting on the callEvent to return. Not sure why that would be a problem though
