### ISSUE TITLE
NPC Respawns

### ISSUE THREAD

**Issue by Monsterwaffle** [CitizensDev/Citizens2#528]
Whenever I kill an NPC, it respawns where it was killed. Is there any way to set a spawn point for an NPC?

**Comment by mcmonkey4eva** [comment]
What plugin are you using to make it respawn?

**Comment by Monsterwaffle** [comment]
Citizens2 with the /npc respawn command.

**Comment by mcmonkey4eva** [comment]
I always forget that exists. Most people manage respawning externally, EG through the Health trait in Denizen. I don't believe the built in system has anything more than a timer at the moment.

**Comment by Monsterwaffle** [comment]
Alright, thanks. If you could explain to me what anchors do, that'd be great as well. The wiki doesn't exactly cover it very well.

**Comment by mcmonkey4eva** [comment]
If you want to learn about Denizen stuff like anchors, start with learning the general stuff via my tutorial videos: http://mcmonkey.org/denizen/vids - though you don't need any of that for this issue...
But if you do want to get into advanced Denizen usage, that's the way to start. Somewhere in the video list is one on where to learn more.

**Comment by Monsterwaffle** [comment]
Alright, thank you so much
