### ISSUE TITLE
NPC Skins are not loading for new NPCs

### ISSUE THREAD

**Issue by Fortifier42** [CitizensDev/Citizens2#529]
Old npc skins load fine, however new ones don't load, rather simply stay as Alex or Steve. 

I am getting occasional timeout messages in console (17.10 07:39:27 [Server] INFO Connection timed out) which *could* be related?

**Comment by JCThePants** [comment]
I'm guessing that you're not making the connection to Mojang skin servers for whatever reason. The old skins work fine because they are cached on the server.

**Comment by Fortifier42** [comment]
I didn't think we were able to cache skins, as Mojang prohibited the ability to use local skin files, but alas...

I haven't any reason why we should be able to connect to mojang's skin server..

**Comment by JCThePants** [comment]
Make sure you're using the latest build. http://ci.citizensnpcs.co/job/Citizens2/

If so, turn Citizens debugging on and post the console output. With debugging on, it should output what's going on with skin downloads.

**Comment by Fortifier42** [comment]
I did that earlier and received an error along the lines of "Failed to fetch profile 'username', null". 

I've tested it on other servers and it works fine. Hoped there may have been something going wrong elsewhere but alas.

I'll keep it under my belt for now @JCThePants 

thanks.
