### ISSUE TITLE
function for NPC's to be only visible to single players

### ISSUE THREAD

**Issue by Dudeplayz** [CitizensDev/Citizens2#530]
Hi,
i am working with Denizen and i got a critical issue. I want that one npc is duplicated for everyone, so that every player has his personal NPC, but the NPC is the 'Same'. I mean that the NPC is saved as one NPC and is managed as one NPC, but every player can see his own. This is usefull if u have a quest where the NPC is showing u a way from point 1 to point 2. But when player 1 activates this NPC and the NPC is moving, then the NPC for player 2 is no longer there. And so player 2 isnt able to start the mission again until the npc returns.
And so is my wish that the NPC is 'copied' from a blueprint maybe for every player and despawns if the mission is completet. 
It would be also awesome if it is possible to hide and unhide specific NPC's for single players. This function would be enough because I can than easily copy one NPC and hide him, while the 'original' NPC is moving and is hide to everyone else than the specific player.

I hope u can understand what i mean. My english isnt the best ^^

**Comment by Talamar1** [comment]
We do this all the time, mcmonkey has a video on how to do it
http://mcmonkey.org/denizen/vids/Putting%20It%20Together:%20NPC%20Guides
