### ISSUE TITLE
In spigot does not work Citizens 2

### ISSUE THREAD

**Issue by Franco200700** [CitizensDev/Citizens2#531]
In spigot not want to run and install the plugin plugin sometimes given as active but not executan commands. Bone effects commands do. And sometimes not activated. The plugin comes in red

**Comment by mcmonkey4eva** [comment]
Make sure you have the right version of C2 for your spigot version -> http://wiki.citizensnpcs.co/Versions

**Comment by Franco200700** [comment]
use of the latest version. That version use?

**Comment by mcmonkey4eva** [comment]
If you have latest Spigot, then use the latest C2...

**Comment by Franco200700** [comment]
I Spita 1.7 - 1.8

**Comment by mcmonkey4eva** [comment]
Then get the C2 version that corresponds to that from the link above.

**Comment by Franco200700** [comment]
Good thank you. I'll try

**Comment by Franco200700** [comment]
Thank you. Solve my problem for years.
