### ISSUE TITLE
Errors with Vault

### ISSUE THREAD

**Issue by DavidStyler10** [CitizensDev/Citizens2#532]
Hey,
I am using Citizens and Sentry. When a Player kills a npc or a player he gets money. But when a npc kills a player there is the following error

at net.milkbowl.vault.economy.plugins.Economy_Essentials.withdrawPlayer(Economy_Essentials.java:111) ~[?:?]

He tries to give the npc money.This makes the whole server lag. How may i fix that? Or do i have to contact the Essentials Devs?

Best Regards,
David

**Comment by mcmonkey4eva** [comment]
That's an error in Vault or Ess. Probably you don't have versions of the two plugins that align correctly. If I were you, I'd update everything on the server to latest versions. (Plugins + main server jar).

If that doesn't fix it, I'd go to the Vault team for further help, as that error is within their code.

**Comment by DavidStyler10** [comment]
Thank you! I will have a look on it
