### ISSUE TITLE
Lag, crash..

### ISSUE THREAD

**Issue by ThunderWave** [CitizensDev/Citizens2#534]
Using server version 1.8.8, and the alpha version for 1.8.7, I am getting very bad lag on the server, and so are other players.
The server crashed too, and after removing Citizens, everything works fine now.
I've pasted the crash log below, as I don't know to do with it.
I remember having the option to have chunks loaded whilst NPC were there enabled, if that means anything.

http://pastebin.com/Km3wFtgi

**Comment by mcmonkey4eva** [comment]
Not a single line of that error report mentions Citizens.

**Comment by ThunderWave** [comment]
Hm, weird. Everything is fine now that I've removed citizens.
Crash was probably unrelated then, might be an admin doing something stupid.
