### ISSUE TITLE
Sentry wont walk up to target to kill it.

### ISSUE THREAD

**Issue by GeForcez** [CitizensDev/Citizens2#535]
hey guys i post it here because nobody commented on my request @sentry so hey.

i have a problem none of my sentries want to go to a target to kill it but are aggroed to the target ?
is there a fix 
love G_4s

**Comment by mcmonkey4eva** [comment]
We don't maintain Sentry anymore, only dSentry -> http://mcmonkey.org/denizen/repo/entry/0

**Comment by GeForcez** [comment]
what is the difference ?

**Comment by GeForcez** [comment]
i see thx guys :D

**Comment by GeForcez** [comment]
@mcmonkey4eva hey but there is a few yml errors in the script its about comments with # on some lines just wanna tell you that :D

**Comment by mcmonkey4eva** [comment]
@GeForcez Denizen is not valid YAML. Don't run dScripts through a YAML parser. Use the bots at http://mcmonkey.org/ircchat_denizen

**Comment by GeForcez** [comment]
thats cool and all but it it won't load untill i deleted all errors tho :D

**Comment by mcmonkey4eva** [comment]
What?! Come on the webchat and ping me about this (not appropriate to discuss it on the C2 issues page), we need to figure out what went wrong and blocked it from loading for you, as it should work out-of-the-box!

**Comment by mcmonkey4eva** [comment]
Oh, or, post on the Denizen issues page if you dislike webchats for some weird reason.

**Comment by GeForcez** [comment]
what is easiest for you and how can i join your webchat
?

**Comment by mcmonkey4eva** [comment]
(see link a few posts up)
