### ISSUE TITLE
npc sleeps 1 block aside the bed

### ISSUE THREAD

**Issue by GeForcez** [CitizensDev/Citizens2#537]
i tried to test some new features of citizens and is came accross sleep i saw that he bugs one block farther if you do that and after a little he wont sleep anymore oh and also if you let an npc sits  the arrow despawns and the npc stands again :D

**Comment by mcmonkey4eva** [comment]
This are, actually, Denizen issues. Denizen is what adds these commands, for some reason they're not included in base Citizens. Please report the issue here: https://github.com/DenizenScript/Denizen-For-Bukkit/issues
