### ISSUE TITLE
Weird lag for npc owners

### ISSUE THREAD

**Issue by OkumuraRin** [CitizensDev/Citizens2#538]
Hello , Well my problem is sometimes when an npc owner connects he gets huge lag plus npc names start showing on player lists , the console doesn't output any errors , and it always happens when my internet connection is slow !
![NPC](http://i.imgur.com/mVh02dT.png)

**Comment by mcmonkey4eva** [comment]
Do the NPC names go away after a short time?

**Comment by OkumuraRin** [comment]
Yes they do !

**Comment by mcmonkey4eva** [comment]
Well... that's normal then. They temporarily appear on the tab list to workaround a bug, they go away so quickly that if you're not lagging you won't even see it generally. That's normal.
Lag, however, is unusual and there shouldn't be any lag an NPC owner receives that other players don't. Can you get any additional information on that? Just 'it lags' is not much to go by.

**Comment by OkumuraRin** [comment]
thank for the quick awnser :D , I'm not sure if only the owner or the other players aswell getting lags , as mush as i know i'm the only one whose getting the lag ( as the npc owner ) none reported it , however the type of lag i get is like getting stuck in a block or something invisible when trying to move i go back right away on that spot ! also when i press T to open the chat box it automaticly closes !

**Comment by mcmonkey4eva** [comment]
This sounds like it needs a lot more investigation on your part. It's likely not a Citizens issue... it could easily be just a bad network link on your end.

Please comment below with additional information if you wish for this issue to be reopened.
