### ISSUE TITLE
Ocelot sitting issue

### ISSUE THREAD

**Issue by Sonic5317** [CitizensDev/Citizens2#539]
Using the latest build I'm unable to get Ocelot NPCs to sit using the /npc ocelot -s command. It does however work for wolves.

**Comment by fullwall** [comment]
Fixed.

**Comment by Jnxd1** [comment]
Hey guys idk if u fixed it or no but it does not work now....
Citizens  v2.0.16-SNAPSHOP (build 1267)

**Comment by mcmonkey4eva** [comment]
@Jnxd1 update your server.

**Comment by Jnxd1** [comment]
My server was updated like a week or two now.Do i have to reupdate it?
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Thanks

**Comment by mcmonkey4eva** [comment]
Update to **Minecraft 1.10.2** to fix the issue.

**Comment by Jnxd1** [comment]
Oh i see!
Few more weeks to 1.11 :package:  :P 
Thanks for the help!
Cheers!
