### ISSUE TITLE
npc create causes: java.lang.NoSuchFieldError: field_75515_a

### ISSUE THREAD

**Issue by nzzane** [CitizensDev/Citizens2#541]
When trying to do the command ingame (/npc create name --type player)
this error comes up saying to look at console
This is the output:
[SEVERE] java.lang.NoSuchFieldError: field_75515_a
[SEVERE] 	at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:35)
[SEVERE] 	at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:154)
[SEVERE] 	at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:66)
[SEVERE] 	at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:22)
[SEVERE] 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:28)
2015-10-30 08:03:24 [SEVERE] 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:150)
[SEVERE] 	at net.citizensnpcs.commands.NPCCommands.spawn(NPCCommands.java:1087)
[SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[SEVERE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[SEVERE] 	at java.lang.reflect.Method.invoke(Unknown Source)
[SEVERE] 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
[SEVERE] 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[SEVERE] 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
2015-10-30 08:03:24 [SEVERE] 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
[SEVERE] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
[SEVERE] 	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:534)

Where if the exact command above is done in console (npc create nzzane --at 45007 69 32024 --type player) This is the error that comes up: 
[INFO] Spawn location could not be parsed or was not found.

Running: Citizens v2.0.10-SNAPSHOT (build 979)
this is on a TekkitMain server, so mc version 1.6.4

Thanks for your time.

**Comment by mcmonkey4eva** [comment]
You need a custom build, available here: http://cauldron.minecraftforge.net/threads/citizens-2-for-cauldron-1-7-10-released.289/

**Comment by nzzane** [comment]
Is it compatible with 1.6.4?

**Comment by mcmonkey4eva** [comment]
That's what it's built for, yes.

**Comment by nzzane** [comment]
Awesome, thanks for your help

**Comment by mcmonkey4eva** [comment]
Woops, wrong link.

**Comment by mcmonkey4eva** [comment]
https://dl.dropboxusercontent.com/u/54130586/citizens-2.0.10-MCPC-R1.jar
This should be it.

**Comment by nzzane** [comment]
Sweet, thanks heaps :)
