### ISSUE TITLE
No skins loading for 1.7.10 Cauldron

### ISSUE THREAD

**Issue by ColinBPlays** [CitizensDev/Citizens2#542]
So I have spent days setting paths and such for 80 npcs in a world planned for a roleplay series. I started with a 1.8 bukkit server and recently changed to a 1.7.10 cauldron server. I was able to get the npcs transfered and working and everything... just there are NO skins! They are all Steve skins. After days of work with this plugin and I'm stuck at this point. I really love your plugin and don't want to use the CustomNpcs plugin as I don't really like the dialog boxes and such. Is there ANYWAY possible to make it so skins are available in the 1.7.10 cauldron version?! Maybe even so I can upload my own png skins to certain npcs myself?

Also, I've had a terrible time trying to use the "triggers." I wonder if I'm just not using them correctly or not. Is there any link you could give to a correct way to use such things as the "Delay" or "Sit" triggers? Thanks so much for making this plugin! It's really been fun to toy with! :)

**Comment by mcmonkey4eva** [comment]
Are you using this version: http://cauldron.minecraftforge.net/threads/citizens-2-for-cauldron-1-7-10-released.289/ ?

As for triggers/etc, we generally use Denizen -> http://wiki.citizensnpcs.co/Denizen -> for complexifying NPC actions, though it's not tested on Cauldron.

**Comment by ColinBPlays** [comment]
Yes that is the one. I've tried relogging and despawning/respawning them and everything. Just no skins..

**Comment by mcmonkey4eva** [comment]
We're limited in what support we can give for a build someone else created for an outdated and non-standard version :/
I don't really know what to tell you... I doubt Bloodmc is still likely to maintain that.

**Comment by ColinBPlays** [comment]
Aw okay. That sucks for me then! The plugin works.. just wish they weren't all Steves! Oh well.. back to the drawing board then. Thanks for the responses!

**Comment by mcmonkey4eva** [comment]
Just a note here...

Spigot is alive for the forseeable future, and pretty solid.

Cauldron is dead.

Sponge is inbound, and offers similar functionality to Cauldron (Forge mods + serverside plugins) and will soon have things like Citizens available.

If I were you, I'd use Spigot for now and upgrade to Sponge when it's ready.
