### ISSUE TITLE
NPC following

### ISSUE THREAD

**Issue by cricketcricketcricket** [CitizensDev/Citizens2#544]
Hio,

Not sure if this is a Sentry issue. After upgrading to latest Citizens the sentry guarding the other sentry walking behind him it used too. No the one that was following(walking) just waits for a bit then jumps the other sentry it used to follow. it keeps doing that as the sentry walks its path.

**Comment by Fortifier42** [comment]
Not a citizens issue.

**Comment by fullwall** [comment]
How long does it wait for each time?

**Comment by cricketcricketcricket** [comment]
Approx 3 seconds then the following guard pops up to the guard its following

**Comment by cricketcricketcricket** [comment]
@ Fortifier|42| - I will try that script out on this bodyguard...I reviewed your script, I like it. The only reason I still use sentry is for the spell casting they do, like if I equip 1 with a blazerod, I have merlin 8)

**Comment by fullwall** [comment]
@cricketcricketcricket - try the latest build of Citizens, it should follow quicker. I may make this a setting if needed. Basically to avoid frequent path calculation Citizens only calculates it every second.
