### ISSUE TITLE
My citizens is experiencing alot of lag it seems.

### ISSUE THREAD

**Issue by Legendaryx** [CitizensDev/Citizens2#548]
It also shows a weird line with EntitySlimNPC.
Is that caused by citizens? 
And how can I fix it.

https://dl.dropboxusercontent.com/u/103908786/Naamloos.jpg

**Comment by fullwall** [comment]
That task (Citizens$2) is only called when Citizens saves all its data every so often (depends on your config) so it is not lagging your server in that case. Do you have a lot of slime NPCs?

**Comment by Legendaryx** [comment]
I had 1 npc and deleted it so i will be testing it later again.
