### ISSUE TITLE
Wither-Shoot-Bug

### ISSUE THREAD

**Issue by Andre424971** [CitizensDev/Citizens2#550]
I have a problem.

When I create a NPC with the Type Wither, the NPC will shoot at all Players, that are in Gamemode 0 or 2
When I use the command **/npc passive --set true** the NPC still shoots at the Players, but no longer give Damage to them.

Can you fix that?

**Comment by mcmonkey4eva** [comment]
What version of Citizens (build #) and spigot are you on?

**Comment by Andre424971** [comment]
we are using Citizens v2.0.14-SNAPSHOT (Build 1190) on Spigot 1.8 R0.1 (20141203)

**Comment by mcmonkey4eva** [comment]
Those are ancient, please update to Spigot 1.8.7 or 1.8.8 alongside Citizens 2.0.16 to fix your issue.

**Comment by Andre424971** [comment]
I can't uopdate the version, because when I do this, the server has relly Big problems!

**Comment by Morphan1** [comment]
Sorry, can't exactly support old versions (that would require us downgrading the code to fix something most likely fixed in the latest versions!)

**Comment by Andre424971** [comment]
The problem is now fixed.
I updatet my Server and the plugins, that make problems.

The fix, that the NPC's will no longer shown in the TabList is a little buggy. (Shows the NPC's for a short moment)

**Comment by Morphan1** [comment]
That's something that can't really be fixed, it's a problem with how Mojang decided to handle skins in 1.8
The good part is that most people generally won't even notice it
