### ISSUE TITLE
Npc types not showing

### ISSUE THREAD

**Issue by roxxstar2000** [CitizensDev/Citizens2#551]
Only villager types are appearing. No witch, enderman, or skeletons, ect

**Comment by mcmonkey4eva** [comment]
Do you perhaps have aggressive mobs disabled (by plugin, game difficulty, etc.)?

**Comment by vashts6583** [comment]
If you're on Peaceful, that might also be a problem.

**Comment by roxxstar2000** [comment]
Here is my server-properties file: http://hastebin.com/kahuhoguwe.hs
Also every time I type /npc create name --type witch the npc pop ups for a split second and disappears.

**Comment by roxxstar2000** [comment]
Never mind fixed it. It was because of the game mode. Sorry about this. Thanks!
