### ISSUE TITLE
/npc select not working

### ISSUE THREAD

**Issue by TaintedScales** [CitizensDev/Citizens2#552]
All of the citizens commands are working just fine, I can create npcs, except I cant /npc select a npc that isn't spawned so I can spawn them, it says nothing in chat. I have tried restarting my server if it is just lag but it still doesn't work.
I am using build 1267 and I am using the latest version of minecraft.

**Comment by vashts6583** [comment]
Even using /npc select [npc-id] doesn't work?  Does the npc show up when you use /npc list ?

**Comment by TaintedScales** [comment]
When I do /npc select with the id it says no npc could be found, while the other times I did /npc select nothing happened. I can see the npc's using /npc list

**Comment by Talamar1** [comment]
are you despawning them or deleting them?

**Comment by TaintedScales** [comment]
Nope

**Comment by mcmonkey4eva** [comment]
npc sel is quiet about. You have to `/npc sel ID`. I don't know why it doesn't say anything when there's nothing to select, that's probably a bug @fullwall

**Comment by fullwall** [comment]
Fixed.
