### ISSUE TITLE
Plugin error, How can I fix it?

### ISSUE THREAD

**Issue by VicZk** [CitizensDev/Citizens2#553]
This is the only error in my server that bothers me, I just want to know how to fix it. Plugin is running how it should, but with this error...
[21:19:41 ERROR]: [Citizens] Missing preferred location bundle.
And yes I am using the latest version of Spigot and Citizens both 1.8.8
Just want to know how to fix it (If possible)

**Comment by mcmonkey4eva** [comment]
That means Citizens detected or is configured to load some non-English translations, and cannot find the relevant translations.

**Comment by VicZk** [comment]
Hmmmm... So any way I can fix that?? I already tried setting the language to en_US, but had no success.
If the server log is needed just tell me.
Reply ASAP thank you!

**Comment by VicZk** [comment]
Bunp, please answer me the last qustion I asked ASAP. Thank You!

**Comment by mcmonkey4eva** [comment]
I really have no idea. You can probably just ignore it.

**Comment by VicZk** [comment]
Soooo... Is there any way I can block the plugin from logging??

**Comment by mcmonkey4eva** [comment]
Why does it matter?

**Comment by VicZk** [comment]
Ehhh... I'm perfectonist as hell, I just wished I could run a server with no error even thought they are infensive...

**Comment by mcmonkey4eva** [comment]
Well you can fix your system settings to identify a more common language, you can add your own language to the Citizens files, you can edit Citizens to not include that error, you can get a special program or plugin that deletes lines you don't like from console output...

**Comment by VicZk** [comment]
Btw, MIGHT be a bug, does nor metter if I run a completly new server with citizens as the only plugin, the error still there.
