### ISSUE TITLE
restore npc's

### ISSUE THREAD

**Issue by silentspectr** [CitizensDev/Citizens2#554]
Hi, i upgraded my serveur and the sentry and citizens plugins too but i cannot restore my npc'c from the save i have 
when i put the save and reload citizens, the citizens save resets to 0 
is there a command or something to restore the npc's ? 

thank you

**Comment by mcmonkey4eva** [comment]
You must fully shut down the server, insert the saves file, THEN start up the server.

**Comment by silentspectr** [comment]
Thank you 
worked perfectly
