### ISSUE TITLE
 Could not pass event NPCSpawnEvent to Citizens v2.0.16-SNAPSHOT (build 1267)

### ISSUE THREAD

**Issue by JohOply** [CitizensDev/Citizens2#555]
I use beta 1 (build 1267) and sometimes, its error happens, but i don't know why :
http://pastebin.com/43mC4SX4

**Comment by mcmonkey4eva** [comment]
Can you replicate this bug on latest builds?

**Comment by JohOply** [comment]
I will try.

**Comment by JohOply** [comment]
I don't see any new error yet, i will open a new ticket if i see it something :)
