### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by roxxstar2000** [CitizensDev/Citizens2#556]
I am using Spigot 1.8.8 and they are not showing up. It is not because the game is on peaceful. When i do /plugins Citizens shows up but when I do a command like /citizens reload nothing comes up!

**Comment by Fortifier42** [comment]
What version of Citizens are you using? Sounds like you're not using the correct version for your spigot.

Get the latest version from here: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

**Comment by Talamar1** [comment]
Paste server logs with the load sequence for Citizens.

**Comment by Fortifier42** [comment]
@Talamar1 
this is the same issue as https://github.com/CitizensDev/Citizens2/issues/540 no?

**Comment by mcmonkey4eva** [comment]
@Fortifier42 not the same issue but your help response is correct. Update fixes it 90% of the time.

**Comment by Fortifier42** [comment]
@mcmonkey4eva says its registered by no commands work? Sounds the same to meeeee :)

**Comment by mcmonkey4eva** [comment]
@Fortifier42 it's not. Just stop flooding this convo please.
