### ISSUE TITLE
cauldron

### ISSUE THREAD

**Issue by bonesaws** [CitizensDev/Citizens2#559]
is there any way to get this plugin to work with cauldron currently? i am running a 1.7.10 server, and none of the builds, including one i found for cauldron, work.

**Comment by mcmonkey4eva** [comment]
The correct build is available at http://cauldron.minecraftforge.net/threads/citizens-2-for-cauldron-1-7-10-released.289/ - or would be, if the website was online >.> might have to wait a while for it to load back up.

**Comment by bonesaws** [comment]
i managed to get it to work, that site is offline though, (found it from a different source, but the same file) but now my skins wont change.

**Comment by mcmonkey4eva** [comment]
Skins are working in versions prior to 1.7.6 and also 1.8.8 and higher.

Not in any version in between, as we had a variety of issues dealing with Mojanglogic back then. So... update or downdate if you need skins.

**Comment by bonesaws** [comment]
cannot do that at this time, but thanks for you help, was worth a try.
