### ISSUE TITLE
waypoints.. how?

### ISSUE THREAD

**Issue by VaiN474** [CitizensDev/Citizens2#56]
Having trouble setting up waypoints. I attempted first using the guided provider. The NPC seems to ignore all guided waypoints and get stuck trying to go directly to a destination waypoint causing it to just teleport back to it's spawn. Rinse and repeat.

Also when trying to right-click to remove a waypoint (as it says in the description) it just creates another one on top of the current one. There's no 'clear' command, and so I'm stuck with non-functioning waypoints that can't be removed.

`toggle path` command does nothing. I now have a bunch of `eye of ender` effects in my path that I can't get rid of.

Any help would be appreciated

**Comment by jeannen** [comment]
Same problem here (2.0.25 1768)

**Comment by mcmonkey4eva** [comment]
@jeannen please open a new issue instead of replying to an issue from 2014...

**Comment by MaximusMcfly** [comment]
Wow, this is sure old!
