### ISSUE TITLE
air/flying-based mobs not tracking waypoints correctly

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#562]
Citizens version 2.0.16-SNAPSHOT (build 1274)

This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (54): ClearChat, GroupManager, MobEggSpawnerBlocker, ScheduledAnnouncer2, SimpleTicketManager, ChestRegen, Ping, Titlebar, AsyncWorldEditInjector, CoreProtect, PlayerHeads, dynmap, WorldEdit, VoteRoulette, OpenInv, Essentials, Chairs, Votifier, ActionBarAPI, ProtocolLib, Multiverse-Core, Stables, EssentialsChat, BlocksHub, TrollCommands, mcMMO, Vault, BlocksHub-CoreProtect, EnjinMinecraftPlugin, DisguiseCraft, Dynmap-Essentials, HolographicDisplays, LWC, WorldGuard, Brewery, BlocksHub-WorldGuard, MythicMobs, AncientGatesReloaded, EssentialsProtect, EssentialsGeoIP, ServerSigns, Multiverse-NetherPortals, EssentialsSpawn, Commandspy, CustomEnchantments, Dynmap-WorldGuard, Citizens, AsyncWorldEdit, AsyncWorldEdit-ActionBarAPI, Signs, ColoredTablist, SuperVanish, Sentry, BetonQuest

---------------------

Ender_Dragon:
1. when reached a way point it does flips around the waypoint. -it should just smoothly transition it's flight path to the next waypoint.   ---i set temp blocks in the air(waypoints) to make a realistic 'flight path'. blocks will be removed later, but it doesn't matter if the blocks are there or not.
—poaabe fix: whan dragon reaches 1 block from next waypoint, skip waypoint and move to the next one
2. /npc controllable doesn't allow me to controll/ride it (as seen in youtube video on a regular npc/biped)
-not waypoint related:
3. enderdragon static positioning  faces the mob backwards from where i am faceing [ie: /npc tphere] 
4. IF this is fixable, i've heard it's something mojang needs to fix. slow down the wing flapping when not moveing.
5. Boss bar doesn't always say the npc's name. randomly will just say "Ender Dragon" instead of the name i gave it.
-improvements?:
6. add sitting position?

Ghast:
7. doesn't rotate to face the direction of travel with waypoints
8. if waypoints are set on a block, and there's a solid block in it's path it will get 'stuck' on the block

Wither(Boss):
9. wither boss completely ignores waypoints and sits still

unrelated: improvement?:
+be able to set the speed of the npc between each waypoint.
+be able to have the npc pause at a waypoint for a given duration.

-found all this a few days ago when i was trying to figure out some of the basics from a youtube vid. :)

**Comment by fullwall** [comment]
1. yes, would need some kind of yaw smoothing.
2. /npc controllable will let you ride the dragon, but because the hitbox for the dragon is quite hard to right click you will need to use something like /npc mount
3. yes, Minecraft has coded it so that ender dragons are backwards by default. I could fix this for individual commands?
4. will look into it.
5. will look into it.
6. sitting position for what?

7. will look into it.
8. ^
9. ^

10. you mean speed between certain waypoints?
11. this is possible using waypoint triggers.

**Comment by leasoncre** [comment]
3. whyyyyyyyyyy......... mojang... that's just dumb...[ignore that] individual commands? huh? or you already fixed it?
5. it's kind of wierd. it displays the name, but then after a few moments it might decide to say ender dragon or the npc's name. Note: i had 2 enderdragon NPC's 1 stationary, and 1 with an approx 10x6 chunk flight pattern, might be related to that. (dragon goes in and out of player's bossbar range while another is present)
6. could use mine-cart seated position or crouching position for npcs (like the dragon for example, though i don't think it has this position period)
8. leeway? (i use useing the same path/npc to test the ghast as i did the ender dragon)

10,11 i'll have to research triggers, i have no idea what they are atm....

**Comment by fullwall** [comment]
2. The actual hitbox of the main dragon to right click is small (dragons are broken up into body parts).
3. well essentially dragons need a special case for each command to have a correct yaw so if you list the commands you want to change I could do that.
5. ok, will investigate
6. you mean for players?
8. at the moment you can't set this but I could add a command/setting that lets you set the default distance from the end point of a path the entity can be.

**Comment by leasoncre** [comment]
-2. body parts? [i'm used to the F3+B shows hitboxes] i assume the pasts that make up the dragon's character. (assumeing head, neck, 2 wings, body and tail) can the 'ride npc' be bound to that hitbox?
-3. any command that positions/spawns an enderdragon npc should auto-correct the faceing direction. (until mojang can get their ---- together.) as well as 'uncorrect' the facing direction if the npc is changed to a different mob.
-6. player, zombie,pigmen, (bipeds) npc's i'd assume can all have a sitting position the same way a player does when they sit in a minecart. (a chairs plugin has them assume this pose too). i'm not sure if it's possable for other shaped npcs (cows, dragons, withers, etc...) would be awesome if it were possable to have the ender dragon 'sit' still though with wings folded, or even lay down. (if i know how to script that, i would do it myself o.O )
-8. i think you're thinging what i was thinking. a setting or command: though i think a command set per-npc wound be wiser in the long run: /npc min-dist-to-waypoint <decimal value between 0(default) and 5(max configureable in congif.yml)> -would allow npc to 'curve' their path smoother by skipping the way-point they are approaching and head to the next one. if it works right it should also fix all the wierd flying circles around every waypoint problem too.

**Comment by fullwall** [comment]
2. I will look into it. Yes they are broken into wings, legs and arms
3. There's some API compatibility concerns - I may make it into a setting disabled by default.
6. No, all rendering is client side so only biped models can do this
8. OK

**Comment by fullwall** [comment]
4, added (/npc pathopt --distance-margin [value])

**Comment by leasoncre** [comment]
problems: https://gyazo.com/209437b522d2c11b90a7874196733510

PS. when i went to set this on the enderdragon i have flying around my cave it was some 50+ clocks away stuck in the ground, acting like it was path following though the ground as well, ignoring the hitbox entirely. (not sure if intended) seems to have sorted itself out, might have been a client glitch or something.

**Comment by fullwall** [comment]
The dragon actually by default is allowed to pass through blocks. That command should work, I can test it tonight.

**Comment by mcmonkey4eva** [comment]
Any luck, @leasoncre ?

**Comment by leasoncre** [comment]
it lets me set the variable. but the message only says i set the distance to "1" even though i specified 4 as the [value]

doesn't appear to have fixed the problem [the intent of the fix] the dragon still does circles around the waypoints
(i'd try a restart, but it's pretty busy atm.)

**Comment by fullwall** [comment]
I'll investigate this tonight.

**Comment by fullwall** [comment]
@leasoncre try #1293 - the block distance was being set in blocks squared so 4 likely wasn't far enough. I have changed it to be in blocks in that build. To fix the incorrect message issue then delete the plugins/Citizens2/lang folder.

**Comment by leasoncre** [comment]
wow.. i thought the distance margin was a radius. had to set it to 50 to get 'em to stop flippn on the waypoints. still not as smooth as i'd like to see, but it's a start. he still looks like he's tripping on the waypoints though. (just momentarilly stopping in front of the point before moving on.) testing the setting between 50-100 seems to be working the best.
Is there another setting i should try in addition to distance-margin to make things smoother? (as if mojang made the path :) )

-message not fixed, deleted messages.yml &/or folder. i don't think the [[{1}]] is being parsed before output. (best guess)

**Comment by fullwall** [comment]
@leasoncre - should be deleting messages_en.properties. If it's still not working can you please upload your messages_en.properties and I'll take a look. Did you update your build?
Looking into the 'tripping' issue.

**Comment by leasoncre** [comment]
updated the jar file and re-deleted lang file/folder. i must have had the build prior to that fix. :/ derp.. [message works properly now]
