### ISSUE TITLE
Problem initializing Citizens2 build #1277

### ISSUE THREAD

**Issue by Mathiaskruse** [CitizensDev/Citizens2#564]
So whenever i try to launch my server running latest SPIGOT, for MC 1.8.8, i get this error:

26.11 13:04:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R3.CraftServer
26.11 13:04:02 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
26.11 13:04:02 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Bukkit-33d5de3]
26.11 13:04:02 [Server] INFO at net.citizensnpcs.Citizens.onEnable(Citizens.java:262) ~[?:?]
26.11 13:04:02 [Server] INFO at net.citizensnpcs.util.Util.getMinecraftRevision(Util.java:78) ~[?:?]
26.11 13:04:02 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R3/CraftServer
26.11 13:04:02 [Server] ERROR Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1275) (Is it up to date?)
26.11 13:04:02 [Server] INFO Creating file: config.yml
26.11 13:04:02 [Server] INFO Enabling Citizens v2.0.16-SNAPSHOT (build 1275)

I use latest build #1277 of Citizens2 aswell. Ingame it seems like citizens is loaded, but no commands work, and they dont even send an error message to the console either.

**Comment by Fortifier42** [comment]
`26.11 13:04:02 [Server] INFO Enabling Citizens v2.0.16-SNAPSHOT (build 1275)` You sure you're running the latest build? :)

**Comment by mcmonkey4eva** [comment]
`running latest SPIGOT, for MC 1.8.8`
Lying won't get you anywhere :(
You're running Spigot 1.8, not 1.8.8...

**Comment by Mathiaskruse** [comment]
Well now. My bad. But, when i try to run with the very last version i get continous errors, and server doesn't work at all: 

http://pastebin.com/9Z2sXxuE 

It seems like my Quests plugin is being f***** by the newest version of Citizens ?

**Comment by mcmonkey4eva** [comment]
Paying attention score: negative three.

YOU.
ARE.
NOT.
RUNNING.
LATEST.
SPIGOT.

Fix that if you want to run latest Citizens, mkay?

**Comment by Mathiaskruse** [comment]
My bad. But anyways, take a chill pill dude. 

http://i.imgur.com/Rs3bp0e.png - The 1.8.8 one is called "Craftbukkit" and not spigot build? anyway to choose another, or should  i just upload my own jar?

**Comment by Fortifier42** [comment]
@Mathiaskruse see close to the end of the list there is Mod: Spigot 1.8.8

Please. use it.

**Comment by mcmonkey4eva** [comment]
It is illegal to use any build other than a self-produced one via http://www.spigotmc.org/wiki/buildtools/

**Comment by Fortifier42** [comment]
@mcmonkey4eva not distributed, it's via multicraft and shared hosting.

**Comment by mcmonkey4eva** [comment]
@Fortifier42 Local-range distribution is still distribution.

**Comment by Fortifier42** [comment]
@mcmonkey4eva it's not distribution, they do not have access to the jar file.

**Comment by Mathiaskruse** [comment]
@Fortifier42 - Lol i'm so stupid, Thanks alot for your help :) ! Greatly appreciated. I hope this will work :+1:

**Comment by Fortifier42** [comment]
@Mathiaskruse  if this is fixed, please close  the issue :)
