### ISSUE TITLE
Citizens Wont work

### ISSUE THREAD

**Issue by Active-Owner** [CitizensDev/Citizens2#565]
when i do /citizens it never works and when i do /plugins citizens comes up red ... are there any other plugins i need with citizens
if you could reply to this with a solution pls
Active_Owner

**Comment by mcmonkey4eva** [comment]
Make sure you have the correct version: http://wiki.citizensnpcs.co/Versions

**Comment by Active-Owner** [comment]
which one would be best for a spigot 1.8 server

**Comment by mcmonkey4eva** [comment]
The one labeled Spigot 1.8

**Comment by Active-Owner** [comment]
k

**Comment by Active-Owner** [comment]
I just tried it but the command are not doing anything and citizens is the only cloning plugin i have ... i dont get that ????

**Comment by mcmonkey4eva** [comment]
Please type this command in your server:
`/version`
What does it output to you?

**Comment by Active-Owner** [comment]
This Server is running Craftbukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API Version 1.7.10-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
You're running either 1.7.10 or the 1.8/1.7 protocol hack. Download the relevant build off http://wiki.citizensnpcs.co/Versions for functionality.

**Comment by Active-Owner** [comment]
ok

**Comment by Active-Owner** [comment]
The plugin works but not /npc ... What happend

**Comment by mcmonkey4eva** [comment]
Grab the correct version and it'll work.

**Comment by Triliton** [comment]
Hello, ive had Fakemobs installed, but they really dont do anything.
Now ive tried many times to install Citizens, but none of the commands work.
Do i even have the right version? I cant see the 1.8 version, there is a snapshot of it.
Am i missing the link somewhere? 
I run this server: Craftbukkit version Spigot (MC: 1.8) Implementing API   version 1.8-R0.1-snapshot

Please help

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by Triliton** [comment]
this one?

- 1186 1.8 Protocol Hack[4]

I tried that.

**Comment by mcmonkey4eva** [comment]
No. Read closer.

**Comment by Triliton** [comment]
I still dont understand what you mean. Read where? what?

**Comment by mcmonkey4eva** [comment]
The versions link. Read your options. Click the **extremely obvious** one. I have no idea why you chose to click a different one.

**Comment by Triliton** [comment]
These are my options not????

Latest Citizens builds [1.8.6, 1.8.7] are always available here[1]

- 1230 1.8.3[2]

- BukkitDev 1.8[3]

- 1186 1.8 Protocol Hack[4]

**Comment by Triliton** [comment]
am i missing something??

**Comment by mcmonkey4eva** [comment]
Yes, those are your options. Now which of those has a version matching your own version?

**Comment by Triliton** [comment]
This one since its 1.8

1186 1.8 Protocol Hack[4]

**Comment by mcmonkey4eva** [comment]
**NO**. The **PROTOCOL HACK** is **NOT THE SAME** as **1.8**.
Try again.

**Comment by Triliton** [comment]
Grab the latest perhaps?

**Comment by mcmonkey4eva** [comment]
**NO**. The **latest 1.8.8** are **NOT** builds for standard **1.8**

You get one last try.

**Comment by Triliton** [comment]
oooooohhhh, ok ok, i might be abit blind :)

- BukkitDev 1.8[3] ?

**Comment by mcmonkey4eva** [comment]
What do you mean A BIT?

Yes that one!

**Comment by Triliton** [comment]
I mean alot but that (3) confused me, so it looked like 1.8.3. So i might be alot blind.
But thank you for your time and advice helping this poor soul out :)
