### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Kita075** [CitizensDev/Citizens2#567]
My NPC will not allow me to apply a skin to it whatsoever. I have the correct version, but when I create an NPC with a username, it shows up as Steve. When I do /NPC skin the same thing happens.

**Comment by HillustratedMike36** [comment]
Try either relogging into your client or removing the NPC and creating it again.

If it still happens, you either have a skin for a MC account that is not real. or you have low available server memory, assuming this is on multiplayer.

**Comment by mcmonkey4eva** [comment]
^
