### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by controlorCZ** [CitizensDev/Citizens2#569]
When i move around NPCs it shows them in Tab, for very short time, but still.

**Comment by vashts6583** [comment]
Pretty sure this is how the plugin tells the client to load any skins for those NPCs.

**Comment by controlorCZ** [comment]
Yes sure, but idk if this si good for players, because TAB will be like.., you know, in 1.7.x it was not.

**Comment by mcmonkey4eva** [comment]
Vasht explained it. Mojang changed how skins where handled in 1.7.6; we can no longer silently send skins in the background, it's now required that they flash on the tab list unfortunately.

**Comment by spaceemotion** [comment]
I don't know if you're currently doing this already, but wouldn't it be feasible to only update the skin if necessary and not on every move (if thats even possible)?

**Comment by vashts6583** [comment]
Pretty sure it only flashes the NPC in the tablist when the player loads a chunk client-side that has an NPC in it.

**Comment by controlorCZ** [comment]
Yes, but after rejoin, it will do again, and em Mojang do really magic items..
