### ISSUE TITLE
PersitenceLoader & Persister

### ISSUE THREAD

**Issue by MaTaMoR** [CitizensDev/Citizens2#572]
Im starting using this API but im having some problems when i try to register a Persister also when i try to set it in the argument @DelegatePersistence 

This is my Persister class : http://pastebin.com/jiPDwSsM

The problem is when i try to register the Class, i checked the API and it should be something like this : 

PersistenceLoader.registerPersistDelegate(ImplicitComplexTypePersister.class);

But there isn't that method, just :

PersistenceLoader.registerPersistDelegate(Class<?> class, Class<? extends Persister<?>> persister);

I have two problems with this, what i should put at "Class<?> class" ? And i can't my class HologramLoader on Class<? extends Persister<?>>... I think it is because of <?> at Persister<?> i think it should be Class<? extends Persister>, anyways i just wanna know how to fix this, and if you guys can update the API would be amazing.

API Version : 2.0.16-SNAPSHOT

**Comment by fullwall** [comment]
Sure, sorry there isn't more documentation here.  DelegatePersistence is for manual Persister specification. registerPersistDelegate registers the Persister for all classes automatically so DelegatePersistence isn't required anymore. To do that it requires the class that the Persister will be managing persistence for. In this case it looks like the call should be registerPersistDelegate(CustomHologram.class, HologramLoader.class)
