### ISSUE TITLE
Skins are not rendered

### ISSUE THREAD

**Issue by WardsParadox** [CitizensDev/Citizens2#573]
References issue #567, skins do not work on my server. The server has plenty of memory (8G), it is on latest version of the Citizens build and spigot build. It is offline mode and I have re-logged into the MC client multiple times. Anything else I can try to get skins working?

**Comment by Fortifier42** [comment]
Offline mode = no skins.

**Comment by WardsParadox** [comment]
I meant isn't. Sorry it's been a long day trying to fix this.

**Comment by Fortifier42** [comment]
If you are on shared minecraft hosting, like CreeperHost or BeastNode, chances are their node's have been blocked my mojang for making too many skin requests.
```
There is a limit on the number of times an IP can request a skin from Mojang, if you exceed this limit they blacklist your IP (normally temporarily, however can last a long time).
```

**Comment by WardsParadox** [comment]
Ah that might be it. Crap. Is there a way to check this?

**Comment by Fortifier42** [comment]
You can enable debug in the citizens config, and see if it is actually requesting skins. It may (not entirely sure here) tell you if there was an error retrieving the skin.

**Comment by WardsParadox** [comment]
Alright. Let me go try that.

**Comment by Fortifier42** [comment]
You need to turn off your server, edit the config and then start it up again.

**Comment by WardsParadox** [comment]
Ya. I know. will this show up in console or in a logfile in the citizens dir?

**Comment by Fortifier42** [comment]
Console.

**Comment by WardsParadox** [comment]
I see this:
06.12 23:14:53 [Server] INFO Profile lookup for player 'wardsparadox' failed: null

**Comment by Fortifier42** [comment]
Looks like mojang aren't accepting your requests. (I've experienced this before).

**Comment by WardsParadox** [comment]
Shoot. Anything I can do or just hope that one day they will display.

**Comment by Fortifier42** [comment]
You can't do anything unless you change hosts. Since shared hosts run sometimes up to 24 servers on each node, you can have 10-20 servers sending requests quite frequently, and mojang will block it very fast.

**Comment by WardsParadox** [comment]
Crap. Didn't used to happen but oh well. Thanks for the help.
