### ISSUE TITLE
Npcs float 

### ISSUE THREAD

**Issue by Triliton** [CitizensDev/Citizens2#574]
Hello,

Any reason why an npc floats?
I havent made a long pathway, just 5 points but the npc walks fine abit, then suddenly
there is no gravity and the npc floats.

**Comment by BlackCoyote** [comment]
DID YOU DIVIDE BY 0

**Comment by Triliton** [comment]
Erm, what do you mean by divide by 0 ?

**Comment by mcmonkey4eva** [comment]
Eh. What. Can you... record this happening?

**Comment by Triliton** [comment]
yes i cab record it

**Comment by Triliton** [comment]
Here it is

https://www.youtube.com/watch?v=BX_IpoD7Dkc&feature=youtu.be

**Comment by mcmonkey4eva** [comment]
That is rather odd. It looks like a clientside glitch - does this still happen after reconnecting?

**Comment by Triliton** [comment]
Ive tried a new npc, this one acts fine. If i do get this problem again il give you notice
