### ISSUE TITLE
Armor Stands have Bugs within Citizens

### ISSUE THREAD

**Issue by Devotedworker** [CitizensDev/Citizens2#578]
I've noticed this odd Behavior within Citizens ( I Updated and it did not fix the issue either )

- NPC Armor Stands do not properly recieve Right Click Interactions ( Including the NPC Wand, Denizen Right Click Scripts, also the EQUIP feature )
[https://github.com/CitizensDev/Citizens2/issues/563] <-- ( Another Bug report about the Equip Bug )

- NPC Armor Stands lose their "Arm" and "Base_plate" and "armor_pose" NPC tags on Player Relog, Citizen Reload. Using Citizen Save does not solve the issue. If I had to guess the NPCs are not saving this data properly.

**Comment by Devotedworker** [comment]
I've noted the following issue with Armor Stands

They can not be selected with the NPC selection wand ( Stick )
They can not be right clicked, as in any right click will not register
They can only be selected by using their ID
They can not be equiped using the Equip menu
They can not be "removed" without despawning them first, and they give this error http://puu.sh/mf7f3/3551bb7e13.png
They can not be turned invisible, through any method or command

**Comment by fullwall** [comment]
I'm still working on the right click issue but I have added saving and a command for visibility in the latest build. I could not reproduce your error.

**Comment by fullwall** [comment]
Fixed

**Comment by joex92** [comment]
There might be an issue with EssentialsX Anti-Build... 
if a player tries to right click an armor stand on a world that has no permission to build with Anti-Build, it won't work, it will only show this: 
![image](https://user-images.githubusercontent.com/645579/171983232-8c598c13-a941-41b9-87d4-e1a7d9a14117.png)
but the left click works.

idk if this is an EssentialsX issue or a Citizens issue.

**Comment by fullwall** [comment]
EssentialsX.
