### ISSUE TITLE
Citizens spam error in console

### ISSUE THREAD

**Issue by Aquinios** [CitizensDev/Citizens2#581]
https://gyazo.com/d3e73b3ac7b9f8841677d752b2911eb6

here's a screenshot, if i write "/pl" in game, it signs Citizens on red, that's because it doesn't work.
i've tested a lot of different version of this plugin, and anyone works with Quests (or in general works).

Thanks.

**Comment by mcmonkey4eva** [comment]
Grab the correct version of Citizens here -> http://wiki.citizensnpcs.co/Versions

**Comment by Aquinios** [comment]
yes, but which of those? i have: craftbukkit 1.8.3 and anyone works

**Comment by Fortifier42** [comment]
there is a link specifically for 1.8.3.. labeled that way too -> [here](http://ci.citizensnpcs.co/job/Citizens2/1230/)

![](http://puu.sh/m6Zva.png)

**Comment by Aquinios** [comment]
it doesn't work, i told that i've tested a lot of them, but anyone works

**Comment by Fortifier42** [comment]
well you did say a lie, you're not using 1.8 at all, you're using 1.7 spigot.

Update, or use the correct version.
