### ISSUE TITLE
Sentry >> Sentries not dealing damage to players

### ISSUE THREAD

**Issue by Concordev** [CitizensDev/Citizens2#583]
Greetings,
I have been trying to use the fantastic addition to Citizens of Sentries, but have had one large issue. The sentries do not deal damage to player targets. The sentries attack, but do not actually damage players. The sentries do deliver damage to mobs and other targets, just not real players. I've tried it with all different equips and still haven't gotten it to work. There are no errors in the console, and besides this the plugin runs perfectly. What am I doing wrong here?

**Comment by mcmonkey4eva** [comment]
Probably an unrelated plugin is cancelling the damage.

You might be able to locate the plugin doing this and ... deal with it somehow.

Alternately, you might try dSentry: http://mcmonkey.org/denizen/repo/entry/0 which uses Denizen as a basis: http://wiki.citizensnpcs.co/Denizen
