### ISSUE TITLE
Server crashes (Possibly caused by Citizens beta 2.0.16) (Thread dump included)

### ISSUE THREAD

**Issue by SmilingTrickster** [CitizensDev/Citizens2#585]
Link to the thread dump: http://pastebin.com/J0B4M8cL
I have no idea what is causing this issue, but Citizens is the only plugin on the server that has something to do with fake players and their movement.

**Comment by mcmonkey4eva** [comment]
No code related to citizens appears in any trace there. That looks like /legit/ player movement throwing an error. Kinda looks like a corrupted entity or something.

**Comment by SmilingTrickster** [comment]
Thanks for the quick reply. I've reported it to the official Spigot JIRA. Hopefully they will have some idea.
