### ISSUE TITLE
NPC's Velocity mid-air is wierd...

### ISSUE THREAD

**Issue by ronfarkash** [CitizensDev/Citizens2#586]
After messing around with Citizens NPCs, I've faced an issue where if I spawn the NPC mid-air through a command or through a plugin, they'll slowly fall down.

Regardless to what method I use, when that NPC is in the air it'll just fall down at the same speed, not accelerate like a player.

 I found half solution:

 If you spawn an NPC mid-air --> set an NPC to vulnerable --> Damage him one time --> NPC will get the gravity/acceleration of a normal player.

I've been looking in the source code of Citizens and found nothing helpful.

 I'd like to be able to apply that NPC a the gravity/falling acceleration of a normal player without having to damage him. If anyone could help with that I'd be grateful.

I am well known to the existence of this command:
/npc gravity
But it doesn't seem to affect it.

**Comment by ronfarkash** [comment]
Any updates on fixing it? or do I just wait?

**Comment by mcmonkey4eva** [comment]
I myself have no idea about this, so I've labeled it for attention from our lead dev. Now, we wait.

**Comment by fullwall** [comment]
Try latest build.

**Comment by fullwall** [comment]
Any updates on this? @ronfarkash

**Comment by bublif** [comment]
Still doesn´t work
