### ISSUE TITLE
Citizens 2 issues with attack of the b team

### ISSUE THREAD

**Issue by KumariAshamaki** [CitizensDev/Citizens2#587]
we had to use an older version due to b team using mc 1.6.4 and it works fine but we can not have npcs use waypoints they only tp so we turned off the tp and turned on debug and it spamed that the npc was stuck it odly seems npcs can not move at all on a bteam server it just acts as if they are stuck even if the blocks are vanilla minecraft.

**Comment by Fortifier42** [comment]
Can't really give support for a version so old.

**Comment by fullwall** [comment]
Unfortunately the code has changed a lot since 1.6.4 so you have probably run into a bug. The message saying they are stuck means they were unable to continue pathfinding for some time so they teleport to the end. Are you sure you are on the most up to date version for 1.6.4?

**Comment by KumariAshamaki** [comment]
Yes i believe so i was hoping i could make it more compatible with bteam because i dont know if its mc or a mod conflict

**Comment by mcmonkey4eva** [comment]
Well... sorry, but there's very little we can do here. Citizens is incompatible with an awful lot of Forge mods purely by virtue of it being made for Bukkit, not Forge.
