### ISSUE TITLE
API Tutorials ?

### ISSUE THREAD

**Issue by Rotockter** [CitizensDev/Citizens2#590]
Are there Tutorials how to work with the api? The javadocs are not very helpfull to know how the classes work together.

The only thing i found was to spawn npcs with CitizensAPI.getNPCRegistry()

And how can i spawn correct a NPC with the Sentry Extension ?

**Comment by fullwall** [comment]
There is a little bit of info here: http://wiki.citizensnpcs.co/API

**Comment by fullwall** [comment]
Will work a bit on Javadocs.
