### ISSUE TITLE
Gives me error when I create a npc

### ISSUE THREAD

**Issue by kingdeathmore** [CitizensDev/Citizens2#591]
So before I got a different version of citzens it would just crash my server but now it just gives a error and doesent crash, ingame it says 
Please report this error: [See Console]
java.lang.noclassdeffounderror:
net/minecraft/server/v1_8_R1/packet

heres my log:

15.01 09:51:54 [Server] WARN at java.lang.Thread.run(Thread.java:745)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
15.01 09:51:54 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15.01 09:51:54 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
15.01 09:51:54 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
15.01 09:51:54 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
15.01 09:51:54 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
15.01 09:51:54 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
15.01 09:51:54 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
15.01 09:51:54 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15.01 09:51:54 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15.01 09:51:54 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
15.01 09:51:54 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
15.01 09:51:54 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
15.01 09:51:54 [Server] INFO kingdeathmore issued server command: /npc create bob

**Comment by mcmonkey4eva** [comment]
wrong version - http://wiki.citizensnpcs.co/Versions

**Comment by kingdeathmore** [comment]
what version should i use?

**Comment by Talamar1** [comment]
What version is your server?

**Comment by kingdeathmore** [comment]
craftbukkit version git-spigot-fdc1440-53fac9f (mc: 1.8.8) (implementing api version 1.8.8-r0.1-snapshot)

says when i do /version

**Comment by Talamar1** [comment]
Then you should probably be using the latest build on the ci server:
http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/artifact/target/citizens-2.0.16-SNAPSHOT.jar

**Comment by kingdeathmore** [comment]
just says the same thing:

Please report this error: [See Console]
java.lang.noclassdeffounderror:
net/minecraft/server/v1_8_R1/packet

**Comment by kingdeathmore** [comment]
just crashed and log says

23.01 11:19:35 [Server] WARN at java.lang.Thread.run(Thread.java:745)
23.01 11:19:35 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:592)
23.01 11:19:35 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
23.01 11:19:35 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
23.01 11:19:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
23.01 11:19:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
23.01 11:19:35 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
23.01 11:19:35 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.Citizens.onDisable(Citizens.java:245)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.Citizens.despawnNPCs(Citizens.java:107)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:93)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.remove(HumanController.java:136)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.npc.skin.SkinPacketTracker.onRemoveNPC(SkinPacketTracker.java:138)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.npc.skin.TabListRemover.sendPacket(TabListRemover.java:100)
23.01 11:19:35 [Server] WARN at net.citizensnpcs.npc.skin.TabListRemover.getEntry(TabListRemover.java:82)
23.01 11:19:35 [Server] WARN at java.util.HashMap.put(HashMap.java:611)
23.01 11:19:35 [Server] WARN at java.util.HashMap.putVal(HashMap.java:628)
23.01 11:19:35 [Server] WARN at java.util.HashMap.resize(HashMap.java:703)
23.01 11:19:35 [Server] WARN java.lang.OutOfMemoryError: Java heap space
23.01 11:19:35 [Multicraft] Skipped 38 lines due to rate limit (30/s)
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.t_(EntityPlayer.java:262) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTracker.a(EntityTracker.java:249) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.citizensnpcs.util.nms.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:43) ~[?:?]
23.01 11:19:34 [Server] INFO at net.citizensnpcs.npc.skin.SkinPacketTracker.updateViewer(SkinPacketTracker.java:217) ~[?:?]
23.01 11:19:34 [Server] INFO at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_60]
23.01 11:19:34 [Server] INFO at java.util.HashMap.putVal(HashMap.java:628) ~[?:1.8.0_60]
23.01 11:19:34 [Server] INFO at java.util.HashMap.resize(HashMap.java:703) ~[?:1.8.0_60]
23.01 11:19:34 [Server] INFO java.lang.OutOfMemoryError: Java heap space
23.01 11:19:34 [Server] ERROR Cause of unexpected exception was
23.01 11:19:34 [Server] INFO ... 4 more
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.EntityPlayer.t_(EntityPlayer.java:262) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTracker.a(EntityTracker.java:249) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.citizensnpcs.util.nms.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:43) ~[?:?]
23.01 11:19:34 [Server] INFO at net.citizensnpcs.npc.skin.SkinPacketTracker.updateViewer(SkinPacketTracker.java:217) ~[?:?]
23.01 11:19:34 [Server] INFO at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_60]
23.01 11:19:34 [Server] INFO at java.util.HashMap.putVal(HashMap.java:628) ~[?:1.8.0_60]
23.01 11:19:34 [Server] INFO at java.util.HashMap.resize(HashMap.java:703) ~[?:1.8.0_60]
23.01 11:19:34 [Server] INFO Caused by: java.lang.OutOfMemoryError: Java heap space
23.01 11:19:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:796) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:34 [Server] INFO net.minecraft.server.v1_8_R3.ReportedException: Ticking entity
23.01 11:19:34 [Server] ERROR Encountered an unexpected exception
23.01 11:19:32 [Multicraft] kingdeathmore ran command Message of the Day
23.01 11:19:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
23.01 11:19:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:32 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:32 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-BT42-1.8.8.jar:git-Spigot-fdc1440-53fac9f]
23.01 11:19:32 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:35) ~[?:?]
23.01 11:19:32 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:123) ~[?:?]
23.01 11:19:32 [Server] INFO java.lang.NoClassDefFoundError: com/earth2me/essentials/xmpp/XMPPManager
23.01 11:19:32 [Server] WARN Task #148 for Essentials vTeamCity generated an exception
23.01 11:19:32 [Connect] User kingdeathmore, IP 74.88.90.67
23.01 11:19:32 [Server] INFO kingdeathmore is now registered.
23.01 11:19:32 [Multicraft] Skipped 25 lines due to rate limit (30/s)
23.01 11:19:31 [Server] WARN * MISSING 191(DARK_OAK_FENCE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 190(JUNGLE_FENCE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 189(BIRCH_FENCE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 188(SPRUCE_FENCE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 187(ACACIA_FENCE_GATE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 186(DARK_OAK_FENCE_GATE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 185(JUNGLE_FENCE_GATE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 184(BIRCH_FENCE_GATE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT) 
23.01 11:19:31 [Server] WARN * MISSING 183(SPRUCE_FENCE_GATE / SOLID+IGN_PASSABLE+GROUND+GROUND_HEIGHT)

**Comment by Talamar1** [comment]
Your server is running out of memory for one thing.  The oldest error in the stack is from Multicraft, Cit is just crashing because the server is tanking.

**Comment by kingdeathmore** [comment]
so i should delete some stuff?

**Comment by kingdeathmore** [comment]
so i deleted stuff and when i do /npc create bob it still crashes and
log says:

3.01 16:31:07 [Server] INFO Saving chunks for level 'plotmeworld'/Overworld
23.01 16:31:07 [Server] INFO Saving chunks for level 'plotme'/Overworld
23.01 16:31:07 [Server] INFO Saving chunks for level 'plotworld'/Overworld
23.01 16:31:07 [Server] INFO Saving chunks for level 'Survival'/Overworld
23.01 16:31:07 [Server] INFO Saving chunks for level 'skyblock2_nether'/Nether
23.01 16:31:07 [Server] INFO Saving chunks for level 'skyblock2'/Overworld
23.01 16:31:07 [Server] INFO Saving chunks for level 'KINGLANDIA_the_end'/The End
23.01 16:31:07 [Server] INFO Saving chunks for level 'KINGLANDIA_nether'/Nether
23.01 16:31:07 [Multicraft] Skipped 26 lines due to rate limit (30/s)
23.01 16:31:01 [Server] INFO Shutting down executor and waiting for any pending tasks...
23.01 16:31:01 [Server] INFO Disabling WorldGuard v6.1
23.01 16:31:01 [Server] INFO Disabling MyItems v1.7
23.01 16:31:01 [Server] INFO [Punishmental]: COMMANDS DISABLED
23.01 16:31:01 [Server] INFO Disabling Punishmental v5.1
23.01 16:31:01 [Server] INFO Disabling EssentialsXMPP vTeamCity
23.01 16:31:01 [Server] INFO Disabling EssentialsProtect vTeamCity
23.01 16:31:01 [Server] INFO Stopping ImageOnMap
23.01 16:31:01 [Server] INFO Disabling ImageOnMap v2.7
23.01 16:31:01 [Server] INFO Disabling EssentialsGeoIP vTeamCity
23.01 16:31:01 [Server] INFO Disabling EssentialsChat vTeamCity
23.01 16:31:01 [Server] INFO Disabling PermissionFinder v1.2.2
23.01 16:31:01 [Server] INFO MinEmojis: [MinEmojis v1.3 disabled.]
23.01 16:31:01 [Server] INFO MinEmojis: [Player file for disabled players saved!]
23.01 16:31:01 [Server] INFO Permissions listed in as player-commands will be given to all users.
23.01 16:31:01 [Server] INFO Essentials: Using config file enhanced permissions.
23.01 16:31:01 [Server] INFO Disabling MinEmojis v1.3
23.01 16:31:01 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
23.01 16:31:01 [Server] INFO Disabling PermissionsEx v1.23.3
23.01 16:31:01 [Server] INFO version 1.1 has been unloaded.
23.01 16:31:01 [Server] INFO kits.yml has been successfully saved with 15 kits.
23.01 16:31:01 [Server] INFO Disabling CobraKits v1.1
23.01 16:31:01 [Server] INFO Disabling AntiSwear v1.0
23.01 16:31:01 [Server] INFO Disabling SuperCubeBros v4.1
23.01 16:31:01 [Server] INFO Disabling Vault v1.5.6-b49
23.01 16:31:01 [Server] INFO Disabling EssentialsSpawn vTeamCity
23.01 16:31:01 [Server] INFO Disabled
23.01 16:31:01 [Server] INFO Disabling MassiveCore v2.8.2
23.01 16:31:01 [Server] INFO Disabling PlotMe v0.16.3
23.01 16:31:01 [Server] WARN java.lang.OutOfMemoryError: Java heap space
23.01 16:31:00 [Server] INFO Disabling Citizens v2.0.16-SNAPSHOT (build 1298)
23.01 16:31:00 [Server] INFO Disabled
23.01 16:31:00 [Server] INFO Disabling Factions v2.8.2
23.01 16:31:00 [Server] INFO Saved name database
23.01 16:31:00 [Server] INFO Saved top ten list
23.01 16:31:00 [Server] INFO Saving top ten list
23.01 16:31:00 [Server] INFO Saving offline messages...
23.01 16:31:00 [Server] INFO Disabling ASkyBlock v2.9.8.1
23.01 16:31:00 [Server] INFO Disabling ChestCommands v3.1.2
23.01 16:31:00 [Server] INFO Disabling AmpleChatBot v2.0.1
23.01 16:31:00 [Server] INFO Disabling PlotMe-DefaultGenerator v0.16.1
23.01 16:31:00 [Server] INFO - Disabled
23.01 16:31:00 [Server] INFO Disabling Multiverse-Core v2.4-b527
23.01 16:31:00 [Server] INFO Disabling ColorShuffle v1.5
23.01 16:31:00 [Server] INFO Disabling Multiverse-Inventories v2.5-b335
23.01 16:31:00 [Server] INFO GriefPrevention: GriefPrevention disabled.
23.01 16:31:00 [Server] INFO Disabling GriefPrevention v13.5.1
23.01 16:31:00 [Server] INFO Disabled!
23.01 16:31:00 [Server] INFO Disabling Paintball v1.3.4
23.01 16:31:00 [Server] INFO Disabling HolographicDisplays v2.1.10
23.01 16:31:00 [Server] INFO Stopping server
23.01 16:31:00 [Server] ERROR This crash report has been saved to: ./crash-reports/crash-2016-01-23_16.31.00-server.txt
23.01 16:31:00 [Server] INFO java.lang.OutOfMemoryError: Java heap space
23.01 16:31:00 [Server] ERROR Encountered an unexpected exception
23.01 16:30:59 [Server] INFO kingdeathmore issued server command: /npc create bob
23.01 16:30:53 [Server] INFO kingdeathmore issued server command: /npc help 6
23.01 16:30:49 [Server] INFO kingdeathmore issued server command: /npc help 5
23.01 16:30:47 [Server] INFO admins: [Owner]~kKingDeathMorek
23.01 16:30:47 [Server] INFO CONSOLE issued server command: /list 
23.01 16:30:40 [Server] INFO kingdeathmore issued server command: /npc help 4
23.01 16:30:29 [Server] INFO kingdeathmore issued server command: /npc help 3
23.01 16:30:26 [Server] INFO kingdeathmore issued server command: /npc help 2
23.01 16:30:19 [Server] INFO kingdeathmore issued server command: /npc help
23.01 16:30:16 [Server] INFO kingdeathmore issued server command: /npc
23.01 16:30:13 [Server] INFO kingdeathmore issued server command: /help npc
23.01 16:30:11 [Server] INFO admins: [Owner]~kKingDeathMorek
23.01 16:30:11 [Server] INFO CONSOLE issued server command: /list 
23.01 16:30:09 [Server] INFO kingdeathmore issued server command: /npc
23.01 16:30:09 [Multicraft] Skipped 178 lines due to rate limit (30/s)
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #675 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #677 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #647 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #669 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #665 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #659 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #667 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #663 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #657 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #671 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #653 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #651 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #655 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #649 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:58 [Server] WARN Task #661 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:58 [Multicraft] Skipped 16 lines due to rate limit (30/s)
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #619 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #631 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #617 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #625 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #621 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #627 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #629 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #615 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #613 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception
23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit
23.01 16:29:57 [Server] WARN Task #607 for Citizens v2.0.16-SNAPSHOT (build 1298) generated an exception

**Comment by mcmonkey4eva** [comment]
You don't have enough memory to run the plugins you have.

**Comment by kingdeathmore** [comment]
ok, thank you for helping me mcmonkey and talamar

**Comment by kingdeathmore** [comment]
![2016-01-23_16 44 42](https://cloud.githubusercontent.com/assets/16721116/12533010/c1d5c77a-c1f0-11e5-8730-95c625adb234.png) it says i have like 500 mb left

**Comment by mcmonkey4eva** [comment]
Well.
`23.01 16:29:57 [Server] INFO java.lang.OutOfMemoryError: Requested array size exceeds VM limit`
says you don't.

**Comment by Talamar1** [comment]
You are using the latest build of Citizens with a MC core that is 25 versions behind..

**Comment by kingdeathmore** [comment]
how do i update that?

**Comment by kingdeathmore** [comment]
how do I update my core?

**Comment by Talamar1** [comment]
http://bit.ly/15RZsn6
