### ISSUE TITLE
Not ignoring cancelled EntityDamageEvents

### ISSUE THREAD

**Issue by MisterErwin** [CitizensDev/Citizens2#594]
Citizens does not ignore cancelled EntityDamageByEntityEvent, in fact: It de-cancels them.

[Link to the EventListener - EventListen.java:188 following](https://github.com/CitizensDev/Citizens2/blob/8f565a589be3d48d488a48721a123680d2f4b585/src/main/java/net/citizensnpcs/EventListen.java#L188)

I suggest either ignoring cancelled events or not setting the cancel-state to false, if its already cancelled. 

(If you are too busy, I can make a pull request. Just tell me)

**Comment by fullwall** [comment]
Yes, there were some compatibility issues with other plugins/server settings IIRC that made us stop respecting cancelled since they didn't. Can add back but will likely cause compatibility issues... tricky.

**Comment by fullwall** [comment]
Added it back as a test.

**Comment by Fortifier42** [comment]
Maybe 
```Java
if (event.isCancelled()) {
    return; 
} 
```
to respect the current event state?
