### ISSUE TITLE
/npc create error out on 1.7.0 ussing cauldron

### ISSUE THREAD

**Issue by Anora** [CitizensDev/Citizens2#597]
so i am not new to citizen I have used it in the past and recently wanted to get into it again. but when i try to make an npc i get this in the logs of my server

http://pastebin.com/w1rmEcHQ

I have a feeling its got to do whit cauldron and I need forge for this project.

**Comment by fullwall** [comment]
https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by Anora** [comment]
thank you
