### ISSUE TITLE
behaviour command gone?

### ISSUE THREAD

**Issue by cjunekim** [CitizensDev/Citizens2#599]
There used to be /npc behaviour command.

http://wiki.citizensnpcs.co/Scripting

It seems to be gone now. Also, there seems to have been /npc create --b (behaviours) command, and it seems to be gone as well -- the NPCCommands.java file shows "--b" is not handled at all.

What is the supposed way of scripting NPCs now? (BTW, I don't like Denizen's own language -- I'd prefer if it were a javascript or jython)

**Comment by fullwall** [comment]
Ah, apologies for this. Yes, there used to be a hook into Java's inbuilt scripting runtime for Citizens. Due to lack of usage and because Rhino (the old implementation of javascript scripting) was quite slow (especially when behaviours were running every tick), the feature was removed. Because of Nashorn there is the possibility to have a fast scripting runtime so it could potentially be brought back.

**Comment by mcmonkey4eva** [comment]
Generally we either go the "efficient" route of using Java trait programming, or the "easy" route of using Denizen. You don't like dScript; but what's wrong with Java?

**Comment by cjunekim** [comment]
I see a huge potential of using Citizen4 scripting for educational purposes. (see http://education.minecraft.net/ ) And Java isn't a particularly good language for young people to start learning programming.

I would love to use Citizen4 for teaching programming and computation thinking. Denizen's script language isn't generic and isn't transferable to other domains.

**Comment by fullwall** [comment]
I agree, that would be pretty cool to see. What kind of helpers would you like to see to make it easier to understand for kids?

**Comment by cjunekim** [comment]
Once the base level APIs are exposed and if they are easy to be used from dynamic programming languages, it will be much easier to build an environment from there thanks to the language's dynamic nature.

**Comment by fullwall** [comment]
Most of these languages have bindings to java code but the idioms aren't always as clean when you put them in e.g. a python context. Also, there's the question of whether you expose the script as running on every update or running at some other time.

**Comment by cjunekim** [comment]
There could be four entry points generally:

1 initial load
2 when the user/admin starts it via command
3 through register_event function
4 via add_task function; scheduler runs it

**Comment by fullwall** [comment]
I have added a simple first pass at this in the latest build. Script files go into plugins/Citizens/scripts, and are added via (e.g.) /npc script --add test.js. The scripts can define global 'onLoad' and 'run' functions.
