### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.World

### ISSUE THREAD

**Issue by greensanoob** [CitizensDev/Citizens2#600]
i get his error Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.World i never seen it be for been trying to fix it but idk how i am lost lol

**Comment by Fortifier42** [comment]
wrong verson http://wiki.citizensnpcs.co/Versions

**Comment by greensanoob** [comment]
ok will try updating thanks

**Comment by Fortifier42** [comment]
Downgrading. You aren't running 1.8+

**Comment by greensanoob** [comment]
the server is 1.8.3 and i got the new verson but its still giving that error

**Comment by greensanoob** [comment]
the server is 1.8.3 and i got the new verson but its still giving that error

**Comment by fullwall** [comment]
You should upgrade your spigot.
