### ISSUE TITLE
duplicated npcs

### ISSUE THREAD

**Issue by silentspectr** [CitizensDev/Citizens2#605]
Hi 
My NPC's duplicate some times for no reason
it's really anoying and uses more ressource than it should

a "citizens reload" command won't change anything and sometimes it gets worse
i use spigot 1.8.8 and the 2.0.16 snapshot (build 1267) of citizens
is this a known bug ? 
what should i do to resolve it?
thank you

**Comment by fullwall** [comment]
Can you try using #1299? There was a fix recently for /citizens reload which may help.

**Comment by silentspectr** [comment]
well i just realised that the only npc's that duplicate are the one who have the trait sentry on them 
the build 1299 didn't correct that 
i suppose the bug comes from the sentry plugin 
Do you manage this plugin too?
the author "jrbudda" don't answer in the bukkit page.
do you know if there is a github page for sentry where he can help me ? 
thank you

**Comment by mcmonkey4eva** [comment]
@silentspectr jrbudda is MIA, I'm the only maintainer, and I've got no idea what to do about that.

A while ago I half-converted Sentry to a Denizen script, you can always try that instead - http://mcmonkey.org/denizen/repo/entry/0

**Comment by silentspectr** [comment]
a guy on the denizen IRC gave me this link a while ago 

i tried it but cannot manage to hit the npc or have it attack a specified group.
is he invincible or something ? 
and he don't follow when he is guarding someone

**Comment by silentspectr** [comment]
About citizens, my npc bug when i tell them to sit or sleep 
i suppose it's a bug but when will it be corrected ? 

thanks
