### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by Neotras** [CitizensDev/Citizens2#607]
Hey what is with http://citizensnpcs.co/??? is offline?

**Comment by Fortifier42** [comment]
It has been down for a time. The host has been notified. 

We are aware of this issue.

**Comment by Neotras** [comment]
thx

**Comment by Neotras** [comment]
when the website online than i buy Citizens

**Comment by Fortifier42** [comment]
@Neotras Citizens is free and open source? You don't buy it..
