### ISSUE TITLE
Maven repository is down?

### ISSUE THREAD

**Issue by games647** [CitizensDev/Citizens2#608]
I tried to access: http://repo.citizensnpcs.co/

but it fails with the message: ERR_CONNECTION_REFUSED.

**Comment by games647** [comment]
Duplicate of #607

**Comment by Fortifier42** [comment]
All services related to citizensnpcs.co is offline as the host has been under attack.

**Comment by games647** [comment]
>as the host has been under attack.

Thanks for this info.

**Comment by Fortifier42** [comment]
Feel free to keep up to date. https://twitter.com/CreeperHost/

**Comment by games647** [comment]
It's back online, but the api version is missing.

**Comment by fullwall** [comment]
API was rebuilt.
