### ISSUE TITLE
NPCs despawning

### ISSUE THREAD

**Issue by silentspectr** [CitizensDev/Citizens2#609]
My npc's despawn sometime with no reason and i have to "citizens reload" to spawn them again 
i'm with version 2.0.16 build 1299
spigot 1.8.8
urgent to correct this 

thanks

**Comment by fullwall** [comment]
Can you please put your config on pastie.org or something?

**Comment by silentspectr** [comment]
here you go 
http://pastie.org/10705613

**Comment by fullwall** [comment]
Try setting 'always-keep-loaded: false' to 'always-keep-loaded: true'

**Comment by silentspectr** [comment]
i did that and i think it worked 
one day without problems 
thank you
