### ISSUE TITLE
NPC EnderDragon waypoints glitchy

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens2#61]
So.. I'm trying to make an enderdragon fly through my Spawn, but it's to glitchy. I've createad a //hcyl on world edit at defined some waypoints on top of that. If I set all of them, he just flying something like 100m/s if not more, if I only set some of them he completely bugs out.
Help?

**Comment by Offerel** [comment]
could you please reopen that issue? i would like to let a EnderDragon fly other the Fortress from my Son.

**Comment by mcmonkey4eva** [comment]
@Offerel will reopen if you can provide the screenshot requested above

**Comment by Offerel** [comment]
Could you please give me some advice, how i can enable your debug? In the meatime i try to find a good Screenshot Program

**Comment by mcmonkey4eva** [comment]
Citizens config.
