### ISSUE TITLE
Wiki Down?

### ISSUE THREAD

**Issue by Armystich** [CitizensDev/Citizens2#610]
Hello im trying to learn how to use your plugin correctly, but it seems that your website is all 404 erroe... something u all may need to look into if you dont know its down.

**Comment by Fortifier42** [comment]
Most of our services are down, with only our download repository available.. Host had a lot of issues.

**Comment by SimSonic** [comment]
:(

**Comment by Fortifier42** [comment]
We've done everything we can on our end. It is up to the host to recover the service until we are able to use it :cry:

**Comment by fullwall** [comment]
The current site is partially restored from a backup, but the wiki is quite large and I may have to upload it on a faster connection.

**Comment by marcosbotaro** [comment]
Hi, you have any perspective to up the wiki?

**Comment by fullwall** [comment]
I will have access to a faster internet connection tomorrow.

**Comment by marcosbotaro** [comment]
Thanks
Wiki is extremely helpful for me
sorry for my english
I'm from Brazil

**Comment by fullwall** [comment]
Update: need to migrate database tonight.

**Comment by Badutski** [comment]
Fullwall, if you need a free host, I can host it for you?
My specs are a bit over qualified to host a website, but I'm only hosting 1 Minecraft Server at the moment.

I run a Dedicated server Linux Debian based 
Intel  Xeon E5
2 x E5-2690v3	48t 3,4 GHz
512 GB of RAM DDR4 ECC 1866 MHz	
2 x4TB of SAS  SOFT	
vRack 10 Gbps Uplink

**Comment by fullwall** [comment]
@Badutski no worries, bought a droplet for the month.

**Comment by Badutski** [comment]
@fullwall Sorry for the late response, was working :-1:
But cool ;) aslong as I can see the damn Wiki soon

**Comment by mcmonkey4eva** [comment]
@Badutski Feel free to join us on IRC -> http://webchat.esper.net/?channels=citizens -> and ask any questions you have until we get the wiki functional

**Comment by fullwall** [comment]
The wiki database wasn't pulled down in my backup... may need to wait for the original VM and worst case rewrite the wiki.

**Comment by Fortifier42** [comment]
One of the users of the `#citizens` IRC channel has put up a wiki to mirror the old one. http://167.114.41.233/Citizens_Wiki/

However it maintains no styling :)

**Comment by fullwall** [comment]
@Fortifier42 - is that from google cache...?

**Comment by mcmonkey4eva** [comment]
@fullwall Web Archive (WayBackMachine)
