### ISSUE TITLE
/NPC not loading

### ISSUE THREAD

**Issue by BowWhalley** [CitizensDev/Citizens2#611]
None of the npc commands are working. I downloaded the latest snapshot of the plugin incase it was that, but it didnt fix it. I am running Spigot 1.8.0

Any help is appreciated.

**Comment by BowWhalley** [comment]
I believe this is a plugin conflict, I got Citizens and CMDNPC and it works in empty new server.
Here is a list of my plugins, please let me know what plugins conflict.

ChestShop
CoreProtect
EnjinMinecraftPlugin
Essentials
EssentialsChat
EssentialsSpawn
Factions
GAListener
GroupManager
Holograms
MassiveCore
McMMO
ModReq
Multiverse-Core
Multiverse-Inventories
Multiverse-Portals
PlotMe
PlotMe-DefaultGenerator
Plugman
Vault
Votifier
SignEdit
SilkSpawners
WarpPortalCommands
WorldEdit
WorldGuard

**Comment by Fortifier42** [comment]
You'll need to wait until our website is fully functional. You have the wrong version of the plugin.

When our website is back up please go to http://wiki.citizensnpcs.co/Versions and download the correct version for your spigot.

**Comment by mcmonkey4eva** [comment]
Grab 2.0.14 off http://dev.bukkit.org/bukkit-plugins/citizens/files/ for functionality in 1.8(.0), latest builds are for 1.8.8

**Comment by BowWhalley** [comment]
Thx, I tried that mcmonkey4eva but unfortunetly it now wont show up in /pl.
Even when changing the spigot jar?

**Comment by Fortifier42** [comment]
You could just update to 1.8.8 and use the latest?

**Comment by BowWhalley** [comment]
I did.

**Comment by mcmonkey4eva** [comment]
@BowWhalley please post a full startup log (via pastebin!) of latest spigot with latest citizens?

**Comment by BowWhalley** [comment]
http://pastebin.com/KYzHHzxP

**Comment by mcmonkey4eva** [comment]
@BowWhalley 
Few problems...
A: You are NOT running latest Spigot. Latest is 1.8.8, that's 1.8.6
B: You are NOT running a legitimate copy of Citizens. The file may be corrupted, or someone may have attempted to edit your file. Either way, redownload it from http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/

**Comment by BowWhalley** [comment]
Works now, THX :)
