### ISSUE TITLE
How do I use custom skins for npcs?

### ISSUE THREAD

**Issue by BowWhalley** [CitizensDev/Citizens2#614]
I want a custom skin for the NPCs, one that isn't on a registered minecraft player. How can I do this?

**Comment by mcmonkey4eva** [comment]
You put it on a minecraft player.
You can set it persistently on the nPC and then change the skin back afterwards.

**Comment by BowWhalley** [comment]
I am in the skin I want to set it as, I set it to my name and it goes to my old skin and not my current skin?

**Comment by fullwall** [comment]
Use /npc skin -p

**Comment by Grundy1133** [comment]
has this feature been removed? -p flag throws an error

**Comment by mcmonkey4eva** [comment]
the `-p` option was removed. Its functionality is now the default. `-l` is required to use the old non-persistent logic.
