### ISSUE TITLE
There is a problem 1.8.4 !!!! HELP!!!!!

### ISSUE THREAD

**Issue by cp123907444** [CitizensDev/Citizens2#615]
>[03:46:45 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Pa                                                                                        cket
>[03:46:45 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTr                                                                                        ait.java:134)
>[03:46:45 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait                                                                                        .java:116)
>[03:46:45 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac                                                                                        tNPC.java:109)
>[03:46:45 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac                                                                                        tNPC.java:88)
>[03:46:45 WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(Trai                                                                                        tCommands.java:64)
>[03:46:45 WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitC                                                                                        ommands.java:157)
>[03:46:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M                                                                                        ethod)
>[03:46:45 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S                                                                                        ource)
>[03:46:45 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno                                                                                        wn Source)
>[03:46:45 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
>[03:46:45 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe                                                                                        thod(CommandManager.java:152)
>[03:46:45 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C                                                                                        ommandManager.java:87)
>[03:46:45 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa                                                                                        fe(CommandManager.java:175)

**Comment by Talamar1** [comment]
Looks like you need to update Sentry.

**Comment by BlackCoyote** [comment]
As far as i'm aware, sentry is no longer being updated. There's a dScript version of sentry available right here: http://mcmonkey.org/denizen/repo/entry/0  You will need to have Denizen running on your server.

**Comment by SgtLegoTown** [comment]
is that the same case with the builder trait ?

**Comment by fullwall** [comment]
Update Sentry.

**Comment by cp123907444** [comment]
Thank

**Comment by cp123907444** [comment]
Thank

**Comment by cp123907444** [comment]
Thank
