### ISSUE TITLE
wiki doesnt work

### ISSUE THREAD

**Issue by gwgw99** [CitizensDev/Citizens2#617]
when going to http://wiki.citizensnpcs.co/, all you get is: A database query error has occurred. This may indicate a bug in the software.

**Comment by barnie995** [comment]
From what I understand, the host has suffered an attack over last weekend.  Fullwall has done all he can and is now just waiting on the host to finish stuff up

**Comment by mcmonkey4eva** [comment]
Host was attacked - https://twitter.com/CreeperHost/ 
Currently working off of an old backup

**Comment by fullwall** [comment]
Duplicate.
