### ISSUE TITLE
Citizens not working.

### ISSUE THREAD

**Issue by ProMiner10000** [CitizensDev/Citizens2#619]
I might have a reason why this is not working but when I download Citizens, I downloaded the 5 recent files and tried them all individually. Although, my server is a Spigot server. I am also using the 1.7 and 1.8 protocol hack which basically means that users connecting to my server can use 1.7 or 1.8 to connect to my server. Although Citizens would be a big improvement to my server. Citizens can open up a lot of more possibilites. There's no errors at all. When I load up the server there's no errors. When I go into my server and do /npc it will not do anything, no errors in the console either. When I do /pl Citizens is colored red and not green. But I get no errors.

Please help?

**Comment by mcmonkey4eva** [comment]
@ProMiner10000 A special file is required to run on that version... unfortunately, our web services were attacked and are temporarily offline. It could be a while before we're able to get the special download available again.

In the meantime, I'd highly recommend updating your server to latest 1.8.8 and using that instead.
