### ISSUE TITLE
NPC Disappears

### ISSUE THREAD

**Issue by mrequinox3** [CitizensDev/Citizens2#620]
As title says, all of my NPCes keep disappearing after a random amount of time :\
There is no error log.
Plugins I use:
MinecraftMarket, TopLite, WorldEdit, SpawnTP, DrawMyThing, Essentials, BarAPI, GroupManager, BountifulAPI, ClearLag, AutoMessage, ChatControl, Block-That-Command, ProtocolLib, WorldGuard, NoCheatPlus, BungeePortals, IPWhitelist, EssentialsChat, Vault, EssentialsSpawn, TitleManager, Citizens, ChestCommands, CommandNPC

Plugin version: last version

**Comment by mcmonkey4eva** [comment]
That is rather odd.
A recent similar issue was posted, and the solution was via this post:
`Try setting 'always-keep-loaded: false' to 'always-keep-loaded: true'`

**Comment by mrequinox3** [comment]
Already tried. :( Not working...

**Comment by mrequinox3** [comment]
I made a mistake... it is not the latest version but the last version for 1.7.x servers. Sorry...

**Comment by mcmonkey4eva** [comment]
Update to 1.8.8 to receive support.
