### ISSUE TITLE
Equipping Custom Armour on NPCs (Armour in Mods)

### ISSUE THREAD

**Issue by mascals** [CitizensDev/Citizens2#622]
I have flans mod and such installed and i try /npc equip the npc and add the mod armour and it goes straight to his hand? if anyone can find out how to make it so he doesn't wield it in his hand that would be fantastic!

**Comment by fullwall** [comment]
Will add a chat command to forcibly set the equipment tonight.

**Comment by mascals** [comment]
Im also on Kcauldron running 1.7.10

**Comment by Fortifier42** [comment]
@fullwall that poses an issue :stuck_out_tongue:

**Comment by fullwall** [comment]
@Fortifier42 - no, you can just allow the current itemstack to be set directly via chat and it will work. His problem is that Citizens' editor checks the held item's Material against whitelists to determine whether they are chestplates for example. See https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/editor/GenericEquipper.java

**Comment by mascals** [comment]
@fullwall Wait i dont get it, so i have to do something to be able to make them wear certain mod armour such as flans juggernaught or team gear?

**Comment by Fortifier42** [comment]
@fullwall I was refering to the 1.7.10 build, you'll need to work off old code, and he wants it so that you can equip custom mod based armor onto the NPC :)

**Comment by fullwall** [comment]
@Fortifier42 - yes, I believe I have the old source for that. Custom mod based armor is no problem if you set it directly without checking the Materials.

**Comment by Fortifier42** [comment]
Ah okay, just wasn't sure of the custom armour :) all good!

**Comment by mascals** [comment]
@fullwall Ok how whats the thing i type to put in the custom armour which is mod based

**Comment by mascals** [comment]
@fullwall bump

**Comment by mascals** [comment]
bump pls

**Comment by fullwall** [comment]
@mascals - I looked into this and it's a bit tricky due to using the modded version. When I get a chance I'll implement it but may take a bit longer.

**Comment by mascals** [comment]
hey when is it fixed?
