### ISSUE TITLE
Named Firework Stars glitch with chest shops

### ISSUE THREAD

**Issue by Kynrasian** [CitizensDev/Citizens2#623]
I couldn't find a ticket for this issue, but it seems that named firework stars allow players to interact with chest shops without performing the transaction. Even a firework star names at an anvil will suffice. I'm at wits end, and I apologise if I've missed something.

- Buy shops can be bought from without paying.
- Sell shops can be sold to without being paid.
- Trade shops can be bought from and sold to but only items already in the chest can be sold to it. No money is exchanged.

Reproduction steps:

1. Have someone else create a chest shop
2. Name a firework star
3. Attempt to remove or add items according to what kind of chest it is.
4. Profit, literally.

I hope this has been helpful of me.

**Comment by mcmonkey4eva** [comment]
...
This is the Citizens NPCs support page, not ChestShop.

**Comment by Kynrasian** [comment]
How'd I even make that mistake? Sorry >_<
