### ISSUE TITLE
NPC guardian does not works

### ISSUE THREAD

**Issue by KittyCat7** [CitizensDev/Citizens2#624]
Hi, i just have Spigot 1.8 and Citizen2, when I crete an NPC and use command /npc guardian i have the message : "The NPC cannot be the mob type PLAYER for that command" but i have testing all type and no one works...

Pleaaaaaase just say me how to do that :(

(And, i don't use Sentry because it don't work on Minecraft 1.8, I just use CITIZENS 2)

**Comment by mcmonkey4eva** [comment]
It needs... to be of guardian type... for the guardian command to work. Guardian controls guardian entities.

**Comment by mcmonkey4eva** [comment]
Also both Sentry and dSentry are compatible with 1.8.8

**Comment by KittyCat7** [comment]
"It needs... to be of guardian type... for the guardian command to work"

Yes but i have search on the config.yml and not here.. Do you know where can I config that please ?

And for Sentry, i have search but today, it have no working version ... :(

**Comment by KittyCat7** [comment]
http://dev.bukkit.org/bukkit-plugins/sentry-citizens2/

Last version is for 1.7.9

**Comment by mcmonkey4eva** [comment]
Sentry is available here: http://ci.citizensnpcs.co/job/Sentry/lastSuccessfulBuild/

Guardian is a type of mob, just as cow and skeleton are mob types. It's not in the config, it's an entity type.

**Comment by KittyCat7** [comment]
No, i don't speak about the mob "Guardian" but the TYPE Guard ^^

On citizen version 1 the command was /toggle guard

**Comment by KittyCat7** [comment]
And thanks for Sentry, I go test that and i say you if it work :)

**Comment by mcmonkey4eva** [comment]
Citizens does not have that kind of thing anymore, instead of it has Traits. Sentry is an example of a trait, which more or less replaces the functionality you were looking for.

**Comment by KittyCat7** [comment]
SENTRY WORKS !!!!!

I love you guuuuy :)


( http://dev.bukkit.org/bukkit-plugins/sentry-citizens2/ is not the last version at this page )
