### ISSUE TITLE
Two questions about Citizens / Sentry

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#627]
I have two questions.

Why sentry isn't updated anymore ?
Why did remove Sentry's updates from : http://167.114.41.233/Sentry/
(I have the 1.8.5 version)

I need an update for bug fixes, cause I have more than 1000 Citizens.
The denizen's creator sent me dSentry script, but I can't migrate all my Sentries ...

**Comment by mcmonkey4eva** [comment]
See https://github.com/CitizensDev/Citizens2/issues/610
