### ISSUE TITLE
Getting exceptions on player join

### ISSUE THREAD

**Issue by i9hdkill** [CitizensDev/Citizens2#628]
Getting these exceptions on (new?!)-player join
http://pastebin.com/NsBK6mxX
We don't use any Player Npcs. Just 1 Villager NPC.

Two questions:
Some devs told me, that this error is citizens related. But I am not quite sure about it, as we are don't using player npcs so there is no reason for citizens for reqeusting a skin.

Citizens config:
`skins:
    max-retries: 0
    retry-delay: 10000
    rotation-update-degrees: 90.0
    use-latest: false
    view-distance: 100.0`

If this is citizens, is there a way to block this behaviour completely? Citizens shouldn't contact mojang in any way for our setup.
Even when citizens is not the root cause of getting blocked from mojang, I don't want any connection attempts.

spigot built on 13.02.
Citizens 1262

**Comment by mcmonkey4eva** [comment]
@i9hdkill Whoever told you this is Citizens related isn't too smart.

This is from placed `human skull` tile entities on the ground. You seem to have too many loading at once. Mojang will block requests when it receives too many, this can be from either loading too many or just being on a shared host (Where several servers are all rapidly requesting this data!)

**Comment by i9hdkill** [comment]
Ok, thanks for the answer. I was bit confused too, because there wasn't a pluginname between those error lines.
No, we are running many gamelobby servers on a dedicated machine, Every lobby contains just 4 custom head placed on armor stands

Anyways, glad that this is not citizens:) This issue can be closed^^
