### ISSUE TITLE
NPC's are sleeping

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#629]
After a reload or a restart of the server, all my Citizens with the Sentry trait are globally "asleep" : when a player enters an area for the first time since the last reload/restart, Citizens don't react at all for 5-10 minutes. They don't attack the player even if they are supposed to. If attacked, they may however retaliate, but will forget the player as soon as he is no longer in sight. After 5-10 minutes, all the Citizens in the said area suddenly "wake up" and start behaving normally.

[20:48:10] [Server thread/INFO]: [Citizens] Loaded 1,240 NPCs.
CPU and RAM are ok (TPS > 19).

Can  you help me ?

**Comment by mcmonkey4eva** [comment]
Citizens don't "behave" their job is to just sit there and look pretty. Any extensions to this are just that: extensions. Not part of Citizens itself.

**Comment by Blamo27** [comment]
The previous versions of Citizens had the same problem but it was shorter than 5 - 10 minutes.

**Comment by Fortifier42** [comment]
@Blamo27 is this evident with `/npc path` ?

**Comment by Blamo27** [comment]
As for the path, they are actually behaving normally : they just don't react with players even if they are supposed to attack them.

**Comment by Fortifier42** [comment]
@Blamo27 that means it is not a Citizens issue :)

**Comment by Blamo27** [comment]
Okey ...
