### ISSUE TITLE
Allow commands from console

### ISSUE THREAD

**Issue by seanth** [CitizensDev/Citizens2#630]
It would be nice to allow NPC to be selected from the console for out-of-game automation.

Right now you can't list or select NPCs from console, so there's no way to then give a builder commands.

**Comment by mcmonkey4eva** [comment]
Except you can...?
`/npc list -a`
`/npc sel 52`

**Comment by seanth** [comment]
Ohhh. If I just said 'npc list' I got nothing on the out-of-game-commandline.

thx.
