### ISSUE TITLE
Citizens Disabling itself

### ISSUE THREAD

**Issue by WolvePlay** [CitizensDev/Citizens2#631]
So, i tried every Citizens Version in the Range of the CraftBukkit Version, which is 1.7.X-1.8.X.
I read somewhere that i would need a special Version for that or something like that.

I really don't wanna miss out on this one, as i know how awesome it is.

P.S. I don't wanna upgrade. That's why i'm asking.

**Comment by mcmonkey4eva** [comment]
Due to errors with our hosting provider, we currently don't have the files for old versions, sorry. We'll hopefully regain them soon.

I would strongly recommend upgrading your server either way.

**Comment by WolvePlay** [comment]
Thanks for the quick response!

Well i'm going to wait and hope then...

**Comment by fullwall** [comment]
Back now.
