### ISSUE TITLE
Ignore players in spectator mode

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#632]
Can you add a feature that will allow npcs to completely ignore players in gamemode 3 please?

dead giveaway when the npc looks at you or talks to you....

**Comment by fullwall** [comment]
Done.

**Comment by leasoncre** [comment]
latest build: npc's don't talk to anyone. reguardless of gamemode.

**Comment by fullwall** [comment]
Text should be fine, maybe another build broke it for you? Try build 1303 and see if you still have this problem.

**Comment by leasoncre** [comment]
1308 same issue, 1303 same issue, 1298 same issue, 1292 same issue, 1286 same issue,1274 same issue, 1262, same issue. I'm thinking there's some other issue causing this. citizens.npc.talk permission is added to users. i'm assuming at this point that it may be related to my test server being locally hosted: same machine running the client as the server.

my live server is running build 1262 and no prob there.

uploaded 1308 to the live server, and this issue does not exist. i'm going to conclude that something in related to localhosting (client and server) (even if i delete citizens config file) is causing this issue. problem only seems to occur on locally hosted machines & clients, possibly only to that user(s). I can't test if the problem exists to users not on the local machine at this time.

Feature does work as expected on live server.

-CLOSE TICKET-
