### ISSUE TITLE
BUG new npcs paths move at super speed

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#633]
[22:30:33] [Client thread/INFO]: [CHAT] This server is running CraftBukkit version git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[22:30:33] [Client thread/INFO]: [CHAT] Checking version, please wait...
[22:30:34] [Client thread/INFO]: [CHAT] You are 2 version(s) behind 
(w/e, blame the hosting company)

[22:30:35] [Client thread/INFO]: [CHAT] Citizens version 2.0.16-SNAPSHOT (build 1262)
[22:30:35] [Client thread/INFO]: [CHAT] Website: http://www.citizensnpcs.co
[22:30:35] [Client thread/INFO]: [CHAT] Authors: aPunch and fullwall

there's some kind of bug where any npc not previously having a defined path will tarck waypoints at speed 10 or so. without having changed anything (just adding new path waypoints to a new npc)

changing the speed of the npc does not fix it. tried other things like pathopt distance margin and pathrange, nothing appeared to improve the problem

old npcs (like the enderdragon i have with a path already existing before we worked on the pathopt --distance-margin feature) are still working as expected o.O

**Comment by fullwall** [comment]
Looking into this.

**Comment by leasoncre** [comment]
'new' pathfinding? i only know of the /npc path command

**Comment by fullwall** [comment]
You don't have use-new-finder set to true in your settings?

**Comment by fullwall** [comment]
Also, what NPC entity type are you using?

**Comment by leasoncre** [comment]
will do that now. reloading the plugin doesn't seem to have made a difference, will have to try on my test server.

NPC type is ghast atm, but i have tried with a new npc as a ghast or enderdragon, wither, tried a zombie too.. i'm thinking it thinks flying type mobs can't fly so it's trying to place them on the marker blocks as if ground-path-finding.

**Comment by leasoncre** [comment]
just downloaded the latest build from a few min ago.
no change with the 'use new pathfinder' config option set to true

that bug with --distance-margin is back again (message always says "...set to {1}")
same thing with stationary ticks message

**Comment by fullwall** [comment]
Having trouble reproducing the speed increase. The message bugs are caused by having an outdated messages_en.properties so delete the locale/ folder inside your Citizens.

**Comment by leasoncre** [comment]
i have this issue on my live server and test server. live server is play.legendsandkings.net if you'd like to observer/troubleshoot the issue there let me know and i'll whitelist you. (as we're currently still in alpha and not open to the public yet)
we also have a teamspeak @ legendsandkings.typefrag.com if you can use voice chat for quicker conversation.

i'm not sure how to reproduce the isse on your end. as i can reproduce it 100% of the time on my end(s).

en file deletion fixed it, thanks.

**Comment by leasoncre** [comment]
@ #677 did some more testing thinking sentry is related to pathing
with sentry installed, if sentry is not added as a trait, npc's won't pathfind.

**Comment by mcmonkey4eva** [comment]
Sentry doesn't exist anymore, so any issues caused by that are gone now!
