### ISSUE TITLE
I can't remove the nametag.

### ISSUE THREAD

**Issue by GWoldendorp** [CitizensDev/Citizens2#634]
Hi,

At some servers, the nametag above the npc isn't shown, like on the Hypixel server.
How can I do that. If I try /npc name, the nametag is still shown.
Please help.

Kind regards,
Gerard Woldendorp
Team GamesCubeNL

**Comment by BlackCoyote** [comment]
What is the entity type of these NPCs?

**Comment by GWoldendorp** [comment]
The entity is set to player

**Comment by BlackCoyote** [comment]
I don't believe minecraft is capable of rendering player models without a nametag with the single exception of when another entity is mounted on top of that player model. (such as an invisible armour stand perhaps.)

Your best bet is to name your npc with a colour code such as &7, it will not show any text however you will be stuck with a small grey box above the model

**Comment by GWoldendorp** [comment]
All right, I'll try it
Thanks

**Comment by GWoldendorp** [comment]
With colercodes, I can still see the names
How do you think Hypixel does it?

**Comment by DNx5** [comment]
could you provide us a screenshot?

**Comment by Morphan1** [comment]
I think this is possible by placing some kind of invisible entity on the NPC's head, similar to "holograms".

**Comment by Xenmai** [comment]
As far as I know, NoNameTags is the only plugin doing that, although it's outdated. What Morphan1 suggested might work too.

**Comment by BlackCoyote** [comment]
yeah like i said in my previous post, the only way to actually get rid of the nametag is by mounting an entity on top of it

**Comment by Morphan1** [comment]
It's probably also possible with scoreboard teams, if you care to figure out how that works.

**Comment by GWoldendorp** [comment]
![naamloos2](https://cloud.githubusercontent.com/assets/17410192/13222818/02c44b28-d982-11e5-99d9-f047f4c0f3c6.jpg)
![naamloos](https://cloud.githubusercontent.com/assets/17410192/13222817/02c1b75a-d982-11e5-8a3e-20290c425fd3.jpg)

**Comment by GWoldendorp** [comment]
2 screenshosts

**Comment by BlackCoyote** [comment]
we were talking about actually mounting an entity on top of the NPC, not placing a block above it

**Comment by GWoldendorp** [comment]
What should I place above it?

**Comment by BlackCoyote** [comment]
mount an entity on top of it, as in a second entity riding it, like when you get on a horse

If you're running denizen, you could probably do `/ex mount e@armor_stand[visible=false]|<pl.target> <pl.target.location>`

**Comment by GWoldendorp** [comment]
Is this the denizen you're talking about?
http://dev.bukkit.org/bukkit-plugins/denizen/

**Comment by BlackCoyote** [comment]
yeah, i recommend using this download link: http://ci.citizensnpcs.co/job/Denizen/lastSuccessfulBuild/

**Comment by GWoldendorp** [comment]
It worked. Thanks

**Comment by BlackCoyote** [comment]
The armour stands on top of the NPCS should be relatively safe, no players should be able to break it. however when an NPC goes under water, their mounted entities will dismount, so keep that in mind

**Comment by GWoldendorp** [comment]
All right, I haven't planned placing npc's underwater, so it should be fine.
Thanks to all of you!

**Comment by GWoldendorp** [comment]
One more thing, /ex mount e@armor_stand[visible=false]|<pl.target> <pl.target.location
What should I enter al <pl.target> and <pl.target.location

**Comment by BlackCoyote** [comment]
You should copy paste the command exactly like how I provided it, but you'll have to make sure you're looking directly at your NPC

**Comment by GWoldendorp** [comment]
all right

**Comment by GWoldendorp** [comment]
Should I stand at the point were the NPC stands?

**Comment by BlackCoyote** [comment]
Normally no but if it seems like you're moving the npc by doing so, then yeah

**Comment by GWoldendorp** [comment]
okay

**Comment by GWoldendorp** [comment]
when I add a skin to a NPC, the nametag returns, even when I type the command in again.

**Comment by BlackCoyote** [comment]
I'm going to assume that changing the NPC skin dismounted the armour stand, and now 'player.target' is getting the invisible armour stand, resulting in you mounting the new one on the old one.

Try `/ex remove <player.location.find.entities[armor_stand].within[5]>` and then do the other thing again

**Comment by GWoldendorp** [comment]
It worked. Thanks

**Comment by GWoldendorp** [comment]
Hi, when I relog on my server, the nametags a visible again sometimes.

**Comment by Morphan1** [comment]
There should probably be some kind of MountTrait (if there isn't already) to keep things there...

**Comment by BlackCoyote** [comment]
or atleast a little dScript

**Comment by GWoldendorp** [comment]
and what should that be?

**Comment by fullwall** [comment]
@Morphan1 to track what entity an NPC is mounted on? Seems kind of tricky unless it's mounted on an NPC.

**Comment by fullwall** [comment]
Seems to be removed by default now

**Comment by FirstLadyAnna** [comment]
I found this about citizens2 npc name invisibility problem : https://youtu.be/5HKM2MujZIM

**Comment by Kelaphi** [comment]
heres a fix that worked for me `/znpcs lines <id> set`
