### ISSUE TITLE
NPC show in tab when players first join

### ISSUE THREAD

**Issue by SioWolf** [CitizensDev/Citizens2#635]
When a player joins the server the NPC's will flicker in TAB for a bit. After they have been on for a while it does not do it anymore. It happens again if the player disconnects and reconnects. 

Running Citizens 2.0.16 (beta 1 for MC 1.8.8)
Running latest PaperSpigot build. Running /version says:

This server is running CraftBukkit version git-PaperSpigot-"3ebeccc" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Checking version, please wait...
Error obtaining version information

**Comment by mcmonkey4eva** [comment]
That's expected. It's a limitation imposed by Mojang, not much we can do about it :/
