### ISSUE TITLE
Player counter above NPC.

### ISSUE THREAD

**Issue by GWoldendorp** [CitizensDev/Citizens2#636]
Hello,

Is it possible to get a player counter above the npc, like in Hypixel?

**Comment by mcmonkey4eva** [comment]
... huh?

**Comment by GWoldendorp** [comment]
What huh?

**Comment by mcmonkey4eva** [comment]
Will reopen when readable, clear, sense-making post is added.

**Comment by BlackCoyote** [comment]
If you're having too much trouble expressing your question in english, feel free to ask it in dutch

**Comment by GWoldendorp** [comment]
Is het mogelijk om een boven het hoofd van een NPC een spelerteller te weergeven, die dan het aantal spelers in die wereld telt en weergeeft, net zoals in de Hypixel server?

**Comment by BlackCoyote** [comment]
Voor zo'n gelijkaardige dingen zul je je eigen denizen script moeten schrijven. https://www.youtube.com/watch?v=I71eMkUZmDY

Eenmaal dat je die video gevolgd hebt en je begrijpt hoe je een script op de server zet, kunnen we wel verder praten over hoe we ee nspelerteller kunnen maken

**Comment by Morphan1** [comment]
@BlackCoyote ...can you translate a bit?

**Comment by BlackCoyote** [comment]
yeah yeah sorry, he wants to put the amount of online players inside the name of the NPC, i told him he'll have to learn some basic denizen for that, have him the link to set him up, told him that once he knows how to get a script running we can talk about how to do his idea

**Comment by Morphan1** [comment]
Okay cool. You got this then
