### ISSUE TITLE
DireWolf20 mod crashes on NPC spawn

### ISSUE THREAD

**Issue by nzzane** [CitizensDev/Citizens2#638]
Like the title says, everytime i do /npc create name   it will crash nearby clients, no npc's were created though.  Disabling citizens allows people to join again, enabling it kicks players.

 CONSOLE: [INFO] nzzane issued server command: /npc create nzzane
 CONSOLE: nzzane has left.
 CONSOLE: [INFO] nzzane lost connection: Internal Exception: java.lang.NullPointerException
 CONSOLE: [INFO] nzzane left the game.
 CONSOLE: [INFO] =====[ NPCs 1/1 ]=====
 CONSOLE: [INFO] Key: ID Name

I am running FTB DireWolf20, Thermos (custom build of cauldron) 1.7.10,
Citizens version: 2.0.13-1.7.10-Cauldron-B2

**Comment by fullwall** [comment]
Do you have a modded client?

**Comment by nzzane** [comment]
What mods may / commonly cause issues with citizens?

**Comment by fullwall** [comment]
@nzzane - unsure, it would help if you could narrow down the problematic mod but may not be possible with modpacks.

**Comment by nzzane** [comment]
Doesn't appear to be a mod, i have disabled a few which could cause errors, but the problem still occurs.

**Comment by fullwall** [comment]
@nzzane - I think to track down this error I would need both your minecraft jar and the exception log.

**Comment by nzzane** [comment]
Down the bottom of the log, sorry its messy but owell.
[https://mega.nz/#F!ld4mRI5L!5ttWzM7jj6c1DBufErrHGg]

**Comment by fullwall** [comment]
Sorry, your minecraft client jar

**Comment by nzzane** [comment]
http://ftb.cursecdn.com/FTB2/launcher/FTB_Launcher.jar
I am using the latest version of DireWolf20 (you will probably need to scroll up)
I can't get the actual jar since its built into the launcher

**Comment by fullwall** [comment]
@nzzane - and the logs?

**Comment by nzzane** [comment]
Hang on my server decided it would suddenly die, shouldn't be too long

**Comment by nzzane** [comment]
@fullwall sorry, but what logs are you looking for?
client logs don't contain any information about players being d/c'd by the npc's

**Comment by fullwall** [comment]
@nzzane - sorry, missed your response here. The server logs indicate what type of exception the client had 'Internal Exception: java.lang.NullPointerException' - this is logged somewhere by your client.
