### ISSUE TITLE
Reloading from modified saves.

### ISSUE THREAD

**Issue by Jerethkhan** [CitizensDev/Citizens2#639]
Citizens: v2.0.16 b1262
Spigot: 1.8.8

Whenever an edit is done and saved directly to the save.yml a "/citizens reload" doesn't seem to take the changes made. The next time citizens saves it overwrites any changes previously made even though those changes should have be loaded with the reload. 
The only way around this is to make the changes, stop the server, save the changes, then restart the server.

To note, the reason I'm doing it this way is to used cached skins.

**Comment by fullwall** [comment]
Fixed in latest build.
