### ISSUE TITLE
Help Citizens Plugin

### ISSUE THREAD

**Issue by Lucatortuga9** [CitizensDev/Citizens2#641]
i have a cauldron server 1.7.10 i tried to install various builds for 1.7.10 but they are not working , the plugin installs but when i do /npc create name it says : Java.lang.illegalaccesserror: tried to access field
.netminecraft.pathfinding.pathnavigate.field_75521_i from class net.citizensnpcs.until.nms.playernavigation

im using citizens snapshot v 2.0.13 build 1143

**Comment by mcmonkey4eva** [comment]
https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar use the special cauldron build
