### ISSUE TITLE
Citizens for Spigot 1.7.9

### ISSUE THREAD

**Issue by TheKox25** [CitizensDev/Citizens2#643]
Hi, I have Spigot 1.7.9 r0.3 and I can't get Citizens to work. I tried a bunch of builds, none of them works. I have succesfully lauched them on Bukkit, but I don't like that engine, it makes the server laggy (in my case). Also I don't want to upgrade to Spigot 1.8, because I use many of plugins, that aren't compatible with 1.8. Please help me with Citizens.

**Comment by fullwall** [comment]
Only 1.7.10 is supported using https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by TheKox25** [comment]
No, I'm not using MCPC

**Comment by fullwall** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by fullwall** [comment]
Can you please post your log?

**Comment by TheKox25** [comment]
From whole server, or only citizens?

**Comment by TheKox25** [comment]
I accidentally did something and they work.
It was build 1142, if someone needs that.
