### ISSUE TITLE
Citizens for Spigot 1.7.9

### ISSUE THREAD

**Issue by TheKox25** [CitizensDev/Citizens2#644]
In reply to this post: https://github.com/CitizensDev/Citizens2/issues/643#event-570472418

I used build 1142, which is for 1.7.9 but it doesn't work. And next time, please wait for my reply, and don't close the topic.

**Comment by fullwall** [comment]
It's fine, you can reopen an issue at any time. Please put this comment back on the other issue as this is a duplicate.
