### ISSUE TITLE
1.9 Incompatibility

### ISSUE THREAD

**Issue by SioWolf** [CitizensDev/Citizens2#645]
Just updated to spigot 1.9

Citizens v2.0.16-SNAPSHOT (build 1267

http://pastebin.com/JHK4EqAb

**Comment by mcmonkey4eva** [comment]
Yeah, we haven't update yet. Patience is needed here. Will be max a few days in theory.

**Comment by fullwall** [comment]
The basic compatibility stuff is done. Please open individual issues for things you find during testing.
