### ISSUE TITLE
Shulker pathfinding not working

### ISSUE THREAD

**Issue by fullwall** [CitizensDev/Citizens2#649]

**Comment by redshirt2** [comment]
Same experience.
citizens 2.0.17. 1312
sentry 1.9.0.30

wiped out my old citizens save file.. Created new NPC, assigned latest Sentry.  created a five point path.  


won't follow path

**Comment by CorporalBruno** [comment]
shulker dont walk. they teleport from one block to another. they must have a solid block to be attached to. (vanilla)

**Comment by fullwall** [comment]
Looks like the client doesn't allow non-block based teleportation, so not sure if pathfinding is possible here.
