### ISSUE TITLE
/npc lookclose not working?

### ISSUE THREAD

**Issue by fullwall** [CitizensDev/Citizens2#650]
Player lookclose not working.

**Comment by Sikatsu** [comment]
Awesome. If I find more bugs I'll make an issue on github next time. :)

**Comment by fullwall** [comment]
It is working for me... Recently look close was disabled for spectators if that makes a difference?

**Comment by Sikatsu** [comment]
./npc lookclose is working when I set the type to an Villager for example. But when I use a player NPC lookclose doesn't work. If you want you can come to my test server and see/test it?

**Comment by Nutty101** [comment]
Didn't want to open a new issue, but just adding a comment that the PLAYER, Shulker, and  entity all around seems dead.  The rest work :)

**Comment by fullwall** [comment]
Can you please pastie your configs?

**Comment by fullwall** [comment]
Also please try with the latest build

**Comment by Sikatsu** [comment]
Config is default. I'll try latest build in a moment.

**Comment by fullwall** [comment]
Should be working as of build #1316

**Comment by Sikatsu** [comment]
Alright, going to try it now.

**Comment by Sikatsu** [comment]
Yes, working same for /tphere :) Good work!
