### ISSUE TITLE
Villagers opes trade shop on right click

### ISSUE THREAD

**Issue by andrewchi12345** [CitizensDev/Citizens2#652]
I cant cancel the event since I'm listening for the NPCRightClickEvent, which will not be called if the entity interact event is canceled. However, since it opens a trade menu, the target GUI its supposed to open is closed and replaced with a trade shop

**Comment by fullwall** [comment]
Fixed in the latest build?

**Comment by fullwall** [comment]
Reopen if this is still an issue.

**Comment by andrewchi12345** [comment]
Thanks.
