### ISSUE TITLE
/npc create not working in 1.9

### ISSUE THREAD

**Issue by xGalDev** [CitizensDev/Citizens2#655]
I cant see npc's
/npc create & /npc tphere are both not working

**Comment by CorporalBruno** [comment]
npc create works for me. npc tphere works 1 time and then quits.

**Comment by fullwall** [comment]
You will need to check your logs and see if there is an error there.

**Comment by xGalDev** [comment]
@fullwall checked, theirs nothing. When the server starts up there are no errors and it says the npc's loaded so...

**Comment by fullwall** [comment]
Can you try with the latest build please?

**Comment by xGalDev** [comment]
@fullwall Yep :) ill try it as soon as i get home.

**Comment by SgtLegoTown** [comment]
I can make NpC also do trait only tab completion did not work on latest

**Comment by xGalDev** [comment]
@fullwall Working :D Thanks!
