### ISSUE TITLE
/npc look not functional

### ISSUE THREAD

**Issue by woodfin15** [CitizensDev/Citizens2#656]
I am able to create a npc, but pretty much every other command regarding the npc does not work, will not tp, will not look and follow player. I understand brand new update so take your time. Just letting you know

**Comment by CorporalBruno** [comment]
note: lookclose works fine for me.

tphere works 1 time. then quits until the NPC is respawned.

manual path selection using /npc path works. delay works one time.

paths from scripts ( i havent tested, but chat has indicated they do not work )

**Comment by woodfin15** [comment]
tphere would not work at all, and the npcs will not look where players go. I also was unable to use /npc path i could set the path but the npc was stuck frozen.

**Comment by fullwall** [comment]
Duplicate - also, can you please pastie your server logs?

**Comment by fullwall** [comment]
Can you try with the latest build as well?

**Comment by woodfin15** [comment]
latest build same thing. I could not find any output of it in the server console i did the commands and watched console no error msgs or anything. https://www.dropbox.com/s/effl7i449ozb2yi/2016-03-01_23.51.10.png?dl=0
https://www.dropbox.com/s/bulrya77gz7o9id/2016-03-01_23.51.18.png?dl=0

**Comment by fullwall** [comment]
@woodfin15 please pastie your config

**Comment by woodfin15** [comment]
its the default but ok give me a min

**Comment by woodfin15** [comment]
https://www.dropbox.com/s/t7iurl9rhttcz9a/config.yml?dl=0

**Comment by fullwall** [comment]
Sorry, just trying to reproduce since I am having trouble. Can you also post your plugin list?

**Comment by woodfin15** [comment]
yep. one sec.

**Comment by woodfin15** [comment]
https://www.dropbox.com/s/gun3ff9ujidsrzi/Capture.PNG?dl=0

**Comment by fullwall** [comment]
Still can't reproduce... let me just check the basics: you are on build 1314 and within 5 blocks of the NPCs you are trying to look close with, correct?

**Comment by woodfin15** [comment]
yes, ive made sure that i was in survival not in vanish. using the latest build you told me to use. just double checked it redownloaded it again and everything.

**Comment by woodfin15** [comment]
https://www.dropbox.com/s/r66jri7qzvvrv5x/citizens-2.0.17-SNAPSHOT%20%282%29.jar?dl=0

**Comment by woodfin15** [comment]
there is the jar im using. None of my other plugins would be causing any conflicts with this one.

**Comment by fullwall** [comment]
Latest build fixes this.
