### ISSUE TITLE
Citizens + PremiumVanish + ProtocolLib Issue.

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#659]
Hey,

I had several errors in my console using PremiumVanish. i reported the errors to the PremiumVanish developer and he said it's an issue with Citizens and Protocollib.

`Because PremiumVanish uses ProtocolLib's getEntityFromID method whose 1.9 fix has been broken by Citizens.`

Error log: https://www.dropbox.com/s/kwwo1b42pqnlhes/2016-03-03-7.log?dl=0

**Comment by leasoncre** [comment]
have you updated your protocallib to 1.9 yet?

**Comment by Sikatsu** [comment]
Ofcourse I did :)

**Comment by fullwall** [comment]
Fixed
