### ISSUE TITLE
Unknown "talk" command?

### ISSUE THREAD

**Issue by Bluelade** [CitizensDev/Citizens2#661]
So I wanted my character to greet my players at my spawn's spawn point, and I wanted him to say something like "Hello there" or something, but I can't figure out how to make him do that. I've looked a variety of different tutorial videos and every single one of them say to use to **/npc talk** command, but when I put it in, it says "Unknown command. Did you mean: **_/npc name_**?". I even saw that command on the Citizen's Wiki page. I am not sure why this is happening. I don't know if I am doing something wrong or if this is a legit bug issue. Either way, it is VERY annoying and I would appreciate any help I can get. 

Thanks in advanced to everyone! :)

**Comment by mcmonkey4eva** [comment]
Not quite sure what's up there, but I'd like to point out there's a better option for NPC interaction available here -> http://wiki.citizensnpcs.co/Denizen -> though be warned it's a bit more of a learning curve. Worthwhile if you're willing to try it though.

**Comment by vashts6583** [comment]
Could also use /npc text (instead of talk) to make this happen.  The wiki has info on the Text editor here: http://wiki.citizensnpcs.co/Editors#Text_Editor

**Comment by fullwall** [comment]
You may be looking at Citizens1 information.
