### ISSUE TITLE
Citizens2 - Latest Dev Build // Skins not rendering

### ISSUE THREAD

**Issue by Pr0totype2** [CitizensDev/Citizens2#662]
Heey,

Let's keep it short and simple;
Using /npc skin is useless for me, skins simply won't render.
I can only use /npc skin Pr0totype2, which will use my skin.
That's the only skin which works, as I'm online.
When I go offline, players tell me my skin gets reverted to either Steve or Alex.

Using Spigot 1.9 latest build, aswell as Citizens2 latest dev build;
(2.0.17-SNAPSHOT (build 1316)

Plugins (22): TimTheEnchanter, LoreAttributesRecoded, PlugMan, ChestRegen, WorldEdit, VoxelSniper, CoreProtect, Vault, ProtocolLib, EffectLib, HolographicDisplays, Votifier, GAListener, WorldGuard, Shopkeepers, CrateReloaded, MythicMobs, CS-CoreLib, QuestWorld, LegacyPvE, Citizens, Lores

Thanks in advance,,
Pr0totype2

**Comment by fullwall** [comment]
Are you running an offline mode server?

**Comment by Pr0totype2** [comment]
Nope, VPS hosted by OVH

**Comment by fullwall** [comment]
Can you turn debug mode on and let me know if you see anything about skins in the log?

**Comment by Pr0totype2** [comment]
Lmao wtf turned on debug-mode, now everything works perfectly fine.
