### ISSUE TITLE
Mob NPCs name plate always showing

### ISSUE THREAD

**Issue by Sonic5317** [CitizensDev/Citizens2#663]
Since 1.9 update npc mobs have their names always shown as opposed to showing when looking at the mob. The name can be turned off with /npc name but I can't get it to display how it was prior to the update

**Comment by fullwall** [comment]
/npc name will toggle this though? Do you mean the default behaviour?

**Comment by Sonic5317** [comment]
Yeah, the /NPC name command toggles it on or completely off. What I mean is the name plate showing only when the NPC is being looked at instead of showing all the time. It used to be like that before 1.9. Currently name tags used on regular mobs give the effect I'm talking about

**Comment by fullwall** [comment]
OK, looking into this.

**Comment by Masterductape** [comment]
Same issue, not yet resolved. Running 'citizens-2.0.17-SNAPSHOT.jar' on 'spigot-1.9.2.jar'.

**Comment by Sonic5317** [comment]
No it isnt, although I do like that player type nameplates can now be toggled on/off as that feature didn't work before

**Comment by Masterductape** [comment]
Issue persists with  'citizens-2.0.18-SNAPSHOT.jar' on 'spigot-1.9.4.jar'. One of the side effects of this issue, in my case, are that NPCs are killed by Essentials's butcher command when they do not constantly have a nameplate showing. Another issue is that players must either be able to see the nametag of hidden NPCs (from great distances/ through walls/ etc), or be unable to see a name for the NPC at all.

**Comment by mcmonkey4eva** [comment]
`/npc name -h` is a thing for the original issue. For through walls stuff, sneaking option is relevant (with Denizen enabled, use `/npc sneak`)
