### ISSUE TITLE
Mobs hop when using the new pathfinding on slabs

### ISSUE THREAD

**Issue by PaulBGD** [CitizensDev/Citizens2#664]
Citizens v2.0.16-SNAPSHOT (build 1267)

If you create a large field of slabs and have an NPC walk from one side to the next with the new pathfinding, they will hop the ENTIRE way there.

**Comment by fullwall** [comment]
New build should be better (1.9 only though)

**Comment by PaulBGD** [comment]
Thanks for the fixes, I'll manually merge them back to a later version :)
