### ISSUE TITLE
Citizens enable issue

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#665]
I'm trying to reload / disable / enable the plugin with Plugman (always worked before) but it seems not to work right now. Tested with other plugins and it worked fine.

`06.03 10:30:53 [Server] ERROR Error occurred while enabling Citizens v2.0.17-SNAPSHOT (build 1319) (Is it up to date?)
06.03 10:30:53 [Server] INFO java.lang.LinkageError: loader constraint violation: when resolving method "net.citizensnpcs.api.CitizensAPI.setImplementation(Lnet/citizensnpcs/api/CitizensPlugin;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/Citizens, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, net/citizensnpcs/api/CitizensAPI, have different Class objects for the type net/citizensnpcs/api/CitizensPlugin used in the signature
06.03 10:30:53 [Server] INFO at net.citizensnpcs.Citizens.onEnable(Citizens.java:257) ~[?:?]
06.03 10:30:53 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285) [PlugMan.jar:?]
06.03 10:30:53 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:238) [PlugMan.jar:?]
06.03 10:30:53 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:299) [PlugMan.jar:?]
06.03 10:30:53 [Server] INFO at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
06.03 10:30:53 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
06.03 10:30:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1314) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1149) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
06.03 10:30:53 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-bc01c3a-55b0def]
06.03 10:30:53 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]`

**Comment by fullwall** [comment]
Plugin list?

**Comment by Sikatsu** [comment]
My list: http://prntscr.com/abv9qj
As far as I know.. no one uses the API?

**Comment by Fortifier42** [comment]
Are.. you trying to load citizens from PlugMan?

**Comment by Sikatsu** [comment]
Reload. Then I tried disable and enable, it worked on 1.8.

**Comment by Fortifier42** [comment]
NEVER /reload.

**Always** stop the server, put files on, and start server up again. Plugman is terrible too.

**Comment by Sikatsu** [comment]
I meant Plugman, not the normal /reload. And it worked before actually..

**Comment by fullwall** [comment]
@Sikatsu - something within Plugman is keeping a bad reference to the old classes. I'll try to track it down but this is a class leak and probably related to how Plugman is reloading plugins. I would recommend using /citizens save and /citizens reload if you can.

**Comment by Sikatsu** [comment]
@fullwall Hmm I see, it would be great if it works. Tested all my plugins and only 2 (one of them Citizens) have this issue. If i throw a new jar in my FTP and use /citizens save and /citizens reload will that work aswell ?

**Comment by Fortifier42** [comment]
@Sikatsu `/citizens save` and `/citizens reload` are used to save and reload citizens data, always restart your server is you add or change plugins
