### ISSUE TITLE
Glow feature request and message issue.

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#666]
Feature request:
It would be nice if you can add an option /npc glowing <color>

You are able to change the color of the glow on yourself using the scoreboard, so I guess it should be possible on an NPC aswell?

Bug:
It says "{0} is now glowing." instead of "<name> is now glowing."

**Comment by fullwall** [comment]
What do you mean by 'option'? The second bug is fixed by deleting the plugins/Citizens/lang folder

**Comment by Sikatsu** [comment]
Sorry, it seems the < tag didn't get added.

/npc glowing (color)

**Comment by fullwall** [comment]
Seems to be decided by scoreboards somewhat randomly.

**Comment by Sikatsu** [comment]
Use scoreboards commands to give glow color to an NPC?

**Comment by fullwall** [comment]
I can do it automatically using a fake scoreboard if you want? Not sure if that would conflict with anything.

**Comment by Sikatsu** [comment]
Not sure either, I don't know much about /scoreboard. But someone showed me lately that he was able to change the glow color using /scoreboard and it would be nice if it was possible for NPCs too. :)
