### ISSUE TITLE
Double right-click

### ISSUE THREAD

**Issue by wasder** [CitizensDev/Citizens2#667]
Seems to be a Minecraft 1.9 bug, but still. When I try to talk with NPC with bare hand with right-click it fires two events at once - he talks to me 2 lines at once.

**Comment by Morphan1** [comment]
I'd suggest updating spigot. There was a bug causing both hands to fire an event.

**Comment by wasder** [comment]
This server is running CraftBukkit version git-Spigot-3104eb1-bf43ca6 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

**Comment by Morphan1** [comment]
Uh.. Update citizens, bugs bugs everywhere
