### ISSUE TITLE
NPC with PLAYER type is non existent (Invisible)

### ISSUE THREAD

**Issue by Zangoran** [CitizensDev/Citizens2#669]
When I create a npc with /npc create , and I give it the PLAYER type it works fine. But then I spawn it in using /npc spawn and it says that it is already spawned. I used /npc tphere and it tps to me but the npc is invisible, but when I change the type to a PIG for example it shows up and works fine.
I am running the the latest spigot and I have the citizens-2.0.12-SNAPSHOT.jar. My plugins list is : BetterAlias.jar , Chairs-1.4.jar , ChatEx.jar , citizens-2.0.17-SNAPSHOT.jar , CommandNPC_v1.0.9.jar , Essentials.jar , OpenInv.jar , PermissionsEx-1.23.4.jar , RoyalShops.jar , SimpleBackup.jar , SimpleHelpTickets.jar , Vault.jar , worldedit-bukkkit-6.1.jar.

Help would be much appreciated as this is causing development of my server to halt. Thanks for your time!

**Comment by fullwall** [comment]
Server log?

**Comment by Zangoran** [comment]
@fullwall The thing is there is no errors from Citizens. Do you want the start up log?

**Comment by Movinggun** [comment]
I have narrowed this issue down. The reason the plugin is not erroring is because the plugin is fine. Bungee is the reason the NPCS are not showing. Try it yourself. Connect to your server without using the bungee proxy and then try and make a NPC. It should work then if you go and connect to the server using the proxy the NPC will be vanished.

**Comment by Zangoran** [comment]
@fullwall @Movinggun Will this be fixed soon? Or is this a bug that cannot be fixed? Thanks for the help guys!

**Comment by Zangoran** [comment]
@fullwall @Movinggun Is there a fix for this? Or is there a workaround? Or do I just have to live with it?

**Comment by mcmonkey4eva** [comment]
We're still investigating at the moment. Please be patient.

**Comment by Zangoran** [comment]
@mcmonkey4eva Thanks for the update!

**Comment by Zangoran** [comment]
@mcmonkey4eva What's the status of this bug?

**Comment by Morphan1** [comment]
> We're still investigating at the moment. **_Please be patient._**

**Comment by fullwall** [comment]
I have investigated and still unable to reproduce even using bungee - also, other people have reported this without bungee. Can you please post your bungee config?

**Comment by Zangoran** [comment]
@fullwall 

`
ip_forward: false
network_compression_threshold: 256
stats: 5da1e220-6f89-4326-a9b6-fbf8039afd90
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  zangoran:
  - admin
servers:
  hub:
    address: localhost:25566
    restricted: false
    motd: "                    &8&lKobalt &6&lOrange                    \n     &2Survival\
      \ &8| &6MiniGames &8| &9SkyBlock &8| &eCreative       "
timeout: 30000
listeners:
- query_port: 25577
  motd: '&8&lKobalt &6&lOrange'
  priorities:
  - hub
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    play.kobalt-orange.com: hub
  max_players: 1000
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
player_limit: 500
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
`

**Comment by fullwall** [comment]
Not convinced this is a Bungee issue.

**Comment by Zangoran** [comment]
@fullwall What do yo put thin kit is caused by?

**Comment by fullwall** [comment]
@Zangoran - if you set npc.tablist.disable to false in the settings does it work?

**Comment by Zangoran** [comment]
@fullwall I am unable to do that right now at the moment. I will try it later. Will update you when I give it a shoot. Thanks for the idea and the help. It is greatly appreciated.

**Comment by Zangoran** [comment]
@fullwall Turns out I just needed to update BungeeCord. Well, I made a dumb mistake on not problem solving enough. Thanks for your help! It has been greatly appreciated!
