### ISSUE TITLE
Vanishing Npc's / Help request

### ISSUE THREAD

**Issue by VicZk** [CitizensDev/Citizens2#670]
Hello there!
I would like some help on the issue I'm currently having. So what's happening is when I join another server or close Minecraft, than join my server again all NPCS are vanished, so I have to do /citizens reload, and then they come back, I'm not the only one in my server experiencing this issue, that's really annoying since some of them execute certain commands when clicked.

**Comment by mcmonkey4eva** [comment]
What version(s) are you on?

**Comment by VicZk** [comment]
I already tried to switch to every single version of citizens and bukkit/spigot, In my web host and in my computer. They usually disappear when I join another server and come back to mine, it's not an issue with any other plugin too, because I already tested citizens completely free from any other plugin in the server, and this still happens.
But my server is currently running spigot 1.8.8 R0.1-SNAPSHOT, but I can ensure it's not an issue with the jar server.

**Comment by fullwall** [comment]
Duplicate

**Comment by VicZk** [comment]
What ha been duplicated there?

**Comment by fullwall** [comment]
Multiple reports on other issues of disappearing NPCs. Could you please list your plugins?

**Comment by fullwall** [comment]
If you are using BungeeCord, make sure you have a build newer than 1126.

**Comment by VicZk** [comment]
Citizens, Essentials, Worldguard, WorldEdit, ClearLagg, Lagg remover,  KingKits, KingKitsSpecial, FeatherBoard, CratesReloaded, CustomEnchantments, NPCcommands,
PermissionsEx, HolographicDisplays, CoreProtect, ConsoleScheduler, ChestCommands, Vault, CustomJoinItems, PvPMangaer And ProtocolLib
But I think It's not an issue with the plugins, since I've tested Citizens without any other plugin, and it did the same thing

**Comment by VicZk** [comment]
I'm running spigot 1.8.8 R0.1-SNAPSHOT,

**Comment by VicZk** [comment]
But that happens with any 1.8.x version

**Comment by fullwall** [comment]
If you try setting npc.tablist.disable to false in the settings what happens?

**Comment by VicZk** [comment]
Nope, nothing happened.

**Comment by mcmonkey4eva** [comment]
@VicZk why not update to 1.9?

**Comment by VicZk** [comment]
Oh well, I guess I could do so :p.
Thanks for everybody who tried to help ^
