### ISSUE TITLE
NPC's are movable

### ISSUE THREAD

**Issue by AshourAziz** [CitizensDev/Citizens2#671]
Bug description/feature request

N/A

V2.0.17-Snapchat build 1325

#668 was closed, but it seems people are still able to move NPC's.

Before it was able to hook and once you pulled it would unhook and move the NPC.
Now if you hook, you can just keep trying to swing and the NPC will not unhook and it keeps pulling the NPC closer to you.

Not sure how I can explain this better sadly.

Although I think the solution /may\ need to unhook the rod and the NPC.

**Comment by fullwall** [comment]
Fixed, sorry for the delay.
