### ISSUE TITLE
500 error at citizensnpcs.co/converter/

### ISSUE THREAD

**Issue by woeterman94** [CitizensDev/Citizens2#672]
Bug: when visiting http://citizensnpcs.co/converter/

NPC converter: http://citizensnpcs.co/converter/

Server returns 500 error

**Comment by mcmonkey4eva** [comment]
Why in space would you possibly need the converter? We haven't supported Citizens 1.0 in years 0.o

**Comment by woeterman94** [comment]
Because my 1.7.xx citizens don't work on 1.8. 
How can I convert them?

**Comment by mcmonkey4eva** [comment]
Were you using Citizens 1.x or Citizens 2.x?

**Comment by woeterman94** [comment]
2.x

**Comment by fullwall** [comment]
The converter isn't for Citizens 2.x.

**Comment by mcmonkey4eva** [comment]
@woeterman94 your NPCs should work fine from 1.7 to 1.8 -> there's no need for any form of converter.

**Comment by woeterman94** [comment]
Ok...
