### ISSUE TITLE
Non-player NPCs are randomly dissapearing.

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#674]
On minecraft 1.9 using the latest #1325 devbuild, my villagers from my mall are randomly dissapearing frequently. The player npc's are never dissapearing. /citizens reload spawns them back.

This might occur on a server restart or when no one is in the mall, I think.

Also when I delete a villager, it comes back after a restart.

**Comment by fullwall** [comment]
Plugin list? Are you using BungeeCord?

**Comment by Sikatsu** [comment]
Spigot 1 version behind. I shared the plugin list on an closed issue
earlier I believe, otherwise I can send it later.

Op vr 11 mrt. 2016 17:06 schreef fullwall <notifications@github.com>:

**Comment by leasoncre** [comment]
might be related to #660

**Comment by Sikatsu** [comment]
Not really, when I use /citizens reload all my npc's are back. But the villagers from my mall keep vanishing :s 

Plugin list: http://prntscr.com/ae807y

**Comment by fullwall** [comment]
If you set keep-chunks-loaded to true in the config, do they still disappear?

**Comment by Sikatsu** [comment]
They still dissappear. Only the non-player NPCs tho, for me I only use ''Villagers'' which are vanishing.

**Comment by fullwall** [comment]
OK, looking into it.

**Comment by Sikatsu** [comment]
@fullwall It happens atleast 3 times a day that I need to use /citizens reload because my villagers disappear.

**Comment by mcmonkey4eva** [comment]
Can you test with clearlag removed?

**Comment by Sikatsu** [comment]
Even without clearlag it is still dissapearing, it seems to happen when a chunk gets unloaded.

**Comment by fullwall** [comment]
Closed as duplicate of https://github.com/CitizensDev/Citizens2/issues/803
