### ISSUE TITLE
Remove NPC bugged

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#680]
When I want to remove an NPC, and lets say 5minutes later I restart the server, the NPC's are back.

**Comment by fullwall** [comment]
How are you restarting the server?

**Comment by Sikatsu** [comment]
I use ''restart'' within my multicraft panel or ''Stop''.

**Comment by fullwall** [comment]
Definitely quite an odd issue... at some point Citizens must not be saving properly.

**Comment by Sikatsu** [comment]
Yup, it's really weird. However, this never came to be notice on 1.8, or it's a new issue.

**Comment by mcmonkey4eva** [comment]
Check log files for errors if this is happening - likely an error message would be in the logs somewhere
