### ISSUE TITLE
Citizens Sentry NPE

### ISSUE THREAD

**Issue by oloflarsson** [CitizensDev/Citizens2#681]
@mcmonkey4eva

**Console Error:** https://gyazo.com/3f4e189a1f76e381f1da3e808153e284
**Citizens Version:** http://ci.citizensnpcs.co/job/Citizens2/1330/
**Sentry Version:** http://ci.citizensnpcs.co/job/Sentry/33/
**Server Version:**
>version
[16:54:55 INFO]: This server is running CraftBukkit version git-Spigot-104c8c8-e43b278 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
[16:54:55 INFO]: Checking version, please wait...
[16:54:55 INFO]: You are running the latest version

**Comment by mcmonkey4eva** [comment]
Fixed in Sentry build 34

**Comment by slkjoy** [comment]
@mcmonkey4eva 

trigger command: 
     /trait sentry
response: 
    Please report this error: (See console)
    java.lang.NoClassDefFoundError:
     net/minecraft/server/v1_8_R3/World

Console error (in reverse order, newest at top): http://pastebin.com/TMUZqJmi
Sentry build 34
Citizen build 1330
Server:
16.03 02:54:45 [Server] INFO This server is running CraftBukkit version git-Spigot-604e046-69e196f (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
@slkjoy you are definitely _NOT_ running Sentry build 34. Please correct that.
