### ISSUE TITLE
Player/Normal NPC Types Are Invisible

### ISSUE THREAD

**Issue by CosmicCakeMC** [CitizensDev/Citizens2#682]
All Normal or Player type NPC's are invisible. They have no nameplate and cannot be interacted with. All other mob types work and have visible nameplates. I have tried running the plugin with NO other plugins running on the server and the same bug still occurred.

Server Log:
http://pastebin.com/sTqHFZp3

Citizens Config:
http://pastebin.com/Q0TsNLQ5

Minecraft Version/Spigot Version: 1.8.8-R0.1-SNAPSHOT

Citizens Version: 2.0.16-SNAPSHOP (build 1308)

Any help would be appreciated.

**Comment by mcmonkey4eva** [comment]
How about on a fresh restart, without using /reload?

**Comment by fullwall** [comment]
Can you post your config please? Try setting remove-from-tablist to false.

**Comment by CosmicCakeMC** [comment]
@mcmonkey4eva I have already tried that many times and still the same result.

@fullwall If your meaning my Citizens config, i did post it. I set remove-from-list to false and still the same thing.

**Comment by fullwall** [comment]
@CosmicCakeMC - I mean set tablist.disable: false

**Comment by CosmicCakeMC** [comment]
@fullwall in what config is that setting in?

**Comment by fullwall** [comment]
@CosmicCakeMC - Citizens' config.yml, should look like

tablist:
    disable: false

**Comment by CosmicCakeMC** [comment]
Still not working.

**Comment by mcmonkey4eva** [comment]
@CosmicCakeMC Can you replicate this in Spigot 1.9?

**Comment by Olif666** [comment]
Hi, have you solved this problem, I'm still having it today
