### ISSUE TITLE
Does not work with Spigot 1.7.9-R0.2-207-g03373bb

### ISSUE THREAD

**Issue by Sparks5** [CitizensDev/Citizens2#688]
Straight up does not work. It does not create a plugin folder, the plugin literally does not load onto the server at all. It just sits there as a .jar file.
Citizens version: 2.0.13 (alpha 1 for MC1.7.9)
Spigot version: 1.7.9-R0.2-207-g03373bb
Client version: Tested on both 1.7.x and 1.8.x

Also, yes, I am running BungeeCord.

UPDATE: Tested with citizens-2.0.13-SNAPSHOT from jenkins, the only commands that work are:
/citizens
/trait
/traitc

**Comment by mcmonkey4eva** [comment]
That is the 1.8 protocol hack, I assume?

Use this: http://ci.citizensnpcs.co/job/Citizens2/1186/

**Comment by Sparks5** [comment]
Indeed, it is. I will try that version and hope it works.
