### ISSUE TITLE
Citizens error with Spigot newest version

### ISSUE THREAD

**Issue by semirotta** [CitizensDev/Citizens2#689]
Error on launch:
http://pastebin.com/pgX8nxpw

I have not had the chance to test if things still are working or not.

This version of spigot was made about 9 hours ago.

**Comment by Subtleoliver** [comment]
I also have that error.

**Comment by Jalau11** [comment]
Same here :/

**Comment by Morphan1** [comment]
It seems this is caused by a recent Spigot-specific update. 
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/04266858e3436dafcb20eba5ae3c9f6d63a7c5a9#CraftBukkit-Patches/0150-Optimize-Navigation-Listener.patch

**Comment by fullwall** [comment]
Fixed.
