### ISSUE TITLE
feature: disable push/hitbox-collisions for npcs (1.9's new 'push')

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#693]
can you add a feature to disable entity collisions with npcs?

purpose: in 1.9 players can push players, back in 1.8 you could walk through other players, but with the new pushing of player, it would be a problem (or really annoying) to try to push past/through npcs

`/npc push [true|false] (toggle npc pushing/collision, default is push=true)`

**Comment by leasoncre** [comment]
old ticket `/npc pushable -t' does not work (says it changed things, but doesn't work

**Comment by fullwall** [comment]
That's because /npc pushable is for other entities pushing the entity. I have just added /npc collidable for the NPC pushing other entities.

**Comment by leasoncre** [comment]
figure out #689 yet? (sooo spammy with alot of npcs)
