### ISSUE TITLE
NPC flickering / disappearing 

### ISSUE THREAD

**Issue by Vessan** [CitizensDev/Citizens2#694]
The Npc are flickering as in the are disappearing and reappearing, doesnt happen with player npcs
only mob ones. but when I come close to them they return to normal untill i walk like 5-10 blocks away

**Comment by mcmonkey4eva** [comment]
What version(s) are you on?

**Comment by Sikatsu** [comment]
Are you using the preview of Optifine? Because that makes them flickering too. As for dissappearing, mine seems to dissapear when the chunk unloads. (Setting it to chunk always loaded doesn't fix it)
