### ISSUE TITLE
NPC Shield Blocking (feature request)

### ISSUE THREAD

**Issue by uledrith** [CitizensDev/Citizens2#696]
Pretty much what title says.  I would like the ability to make the NPC actually block (not just animate) and use his shield to parry blows.  Not sure if this would be possible to add, but would be insanely awesome. :)

Thanks, Uledrith

**Comment by fullwall** [comment]
Via API or automatically?

**Comment by uledrith** [comment]
Honestly, I think either would be great, but automatically would be my preference if I had to choose. :)

How would that work though?  If I issue an '- attack' command on an NPC that has a sword in hand and shield in offhand, would he automatically use both sword and shield while fighting?

Would be really cool to have an associated event in denizen (i.e. on NPC blocks with shield:) that would allow to determine block amount, etc.

**Comment by fullwall** [comment]
I think doing it automatically would be too overpowered for NPCs? I will expose it via API

**Comment by fullwall** [comment]
@mcmonkey4eva - PlayerAnimation#START_USE_XXX_ITEM will do shield blocking...
