### ISSUE TITLE
/npc glowing --color

### ISSUE THREAD

**Issue by Nickshelton80** [CitizensDev/Citizens2#698]
What is the correct string after --color?

I seem to be getting "null" when I do /npc color --color &c, I tried putting "red" "RED" "DARK_RED" "&c" "\u00a7c", everything I could think of.

**Comment by Pr0totype2** [comment]
Hmm, try /npc color [Whatever]
Just try it without the --color

**Comment by Nickshelton80** [comment]
Doesn't seem to work still D:

**Comment by fullwall** [comment]
How long is your NPC name

**Comment by Nickshelton80** [comment]
It's name is "__" So two characters

**Comment by adnurmal** [comment]
Local testing on my computer yields the same results as Nick mentioned (null). Character name is &7Pet &dKeeper so including color tags and space, 14 characters long.

**Comment by Sikatsu** [comment]
Same issue here. The NPC name is &aInformatie but when trying to use a color I also recieve ''null'' everytime.

**Comment by fullwall** [comment]
Should work a bit better in the latest build.

**Comment by Sikatsu** [comment]
@fullwall For me it still says ''Null'' when trying to give a color.

**Comment by fullwall** [comment]
@Sikatsu - what color?

**Comment by Boosik** [comment]
I have the same problem. Tried RED, GOLD, gold, red, DARK_RED and &6. Nothing worked.
Tried it with /npc glowing <color> and also /npc glowing --color <color>

**Comment by fullwall** [comment]
https://dl.dropboxusercontent.com/u/6701575/2016-03-26_01.35.35.png

**Comment by Boosik** [comment]
Can you tell me exact command you used?

**Comment by Sikatsu** [comment]
Well it's not working for me lol

**Comment by Morphan1** [comment]
@Boosik @Sikatsu do you have any plugin(s) that mess with the scoreboard?

**Comment by Boosik** [comment]
Yes, NameTagEdit and McMMO.

**Comment by Sikatsu** [comment]
McMMO

**Comment by GravityX** [comment]
Works for me and I have mcMMO. Make sure you've first enabled glowing with /npc glowing before you add a color.

**Comment by Boosik** [comment]
I did /npc glowing and then /npc glowing - - color DARK_REDand npc is it I'll glowing white and also got red null in the chat.

**Comment by mcmonkey4eva** [comment]
I tried
`/npc glowing --color DARK_RED`
followed by
`/npc glowing`
and it glows the correct color.

**Comment by Sikatsu** [comment]
I'm sorry but it doesn't work at all.. it's either white or nothing.

**Comment by mcmonkey4eva** [comment]
It works fine for us, so something's going wrong that we didn't think to account for, as it doesn't apply to our own testing environments. We're going to need more information to work with... Can you set up a local test server and replicate it there (no extra plugins, latest official versions of Citizens and Spigot, ...)?

**Comment by mcmonkey4eva** [comment]
Random update: Looks like NPCs occasionally need a manual respawn for the coloring to take effect.

**Comment by Sikatsu** [comment]
It indeed seems to be a conflict with a plugin. It works on my test server but doesn't on my main server. Manually respawning doesn't work.

**Comment by Kainzo** [comment]
I know this is a mega bump.. but the colorization on the glow doesnt seem to work.

**Comment by mcmonkey4eva** [comment]
See https://wiki.citizensnpcs.co/Plugin_Conflict for information on diagnosing plugin conflicts.
