### ISSUE TITLE
[BUG] Offhand items not rendering after restart

### ISSUE THREAD

**Issue by PsychoLynx** [CitizensDev/Citizens2#699]
Running latest Spigot 1.9 built today (52c7fc0) and latest dev builds of Citizens, Denizen and Sentry. After using /npc equip to give NPCs items and using /citizens save and then restarting the server, the offhand seem to have disappeared from their hands. No errors are printed in the server console upon startup or shutdown.

Here's an example of one of the NPCs whose shield is not loading: 
http://pastebin.com/JRmFsmJi

**Comment by PsychoLynx** [comment]
Tested in a clean server with only Citizens (the one with the Elytra fix). Problem persists.

**Comment by fullwall** [comment]
Fixed
