### ISSUE TITLE
[REQUEST] Make NPCs able to wear Elytra

### ISSUE THREAD

**Issue by PsychoLynx** [CitizensDev/Citizens2#700]
(Could also be a bug related to #699 )

I tried modifying the Citizens save-file to make NPCs wear the Elytra on their backs, as the in-game /npc equip editor only allowed the Elytra be placed on their hands. This would be a rather useful aesthetic addition, I think!

**Comment by fullwall** [comment]
Fixed.

**Comment by Wuemeli** [comment]
Whats the Command?

**Comment by mcmonkey4eva** [comment]
... `/npc equip`?
