### ISSUE TITLE
NPCs Locking up

### ISSUE THREAD

**Issue by djlawrence4** [CitizensDev/Citizens2#703]
In this issue, please include:
- whether this is a bug description or a feature request

Bug

- Link to server log & Citizens config if relevant (using e.g. pastie.org) 

http://pastebin.com/0wvcc8V5 - Config
No Console Error

- Minecraft & Citizens version if relevant

Spigot 1.9 Latest 3/21/16
Citizens 1339

-Note- I tried changing in the config as requested by FullWall

player:
   remove-from-list: (from _true_ to _false_)

After doing so I had a huge amount of mobs/animals on the server... based on amount of players mobs were spawning huge amounts. I did not notice any issues with locking up afterwards but I had to revert it back to true.

**Comment by mcmonkey4eva** [comment]
What exactly do you mean by `locking up`?

**Comment by djlawrence4** [comment]
During their patrol the npcs with freeze into place until I restart the server and then the issue repeats itself. I did notice that when an NPC freezes mobs/animals in a radius of the npc will also freeze.

**Comment by djlawrence4** [comment]
I don't have a complete confirmation but I think it may have been fixed. Usually after a couple hours of uptime the NPCs will begin to lock up. But My server has been up for 6 hours and no locking up. So to continue the investigation of this issue I will let my server run for a total of 24 hours to confirm. Just thought I should give you an update for putting a lot of effort into something that is free. Like I said in the IRC chat you may remember * * * * * stars! ^.^

**Comment by djlawrence4** [comment]
Ran 27 Hours Latest 1.9.2 Spigot Build and Citizens 2 build 1356. 

NPCs no longer locking up. Confirmed fixed! Thank You!
