### ISSUE TITLE
Loan not permitted? 

### ISSUE THREAD

**Issue by donnie8986** [CitizensDev/Citizens2#704]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

Hello, 

One of my players keeps encountering this error: couldn't create npc reason: loan was not permitted. I checked logs and there are no errors. I'm on MC 1.9 and the most recent Citizens.

**Comment by mcmonkey4eva** [comment]
What command exactly did they enter?

**Comment by BlackCoyote** [comment]
it's simple, you start with a small loan of a million dollars

**Comment by fullwall** [comment]
Hello, it looks like you have defined a cost to create an NPC, but for whatever reason your economy plugin is requesting a loan when it tries to withdraw the money for the NPC. Seems to be an issue with your config.
