### ISSUE TITLE
Bug Report - Scoreboard Intereference

### ISSUE THREAD

**Issue by mrCookieSlime** [CitizensDev/Citizens2#705]
Good day, for the past few days I have been encountering a rather annoying Error pop up every few ticks. I included the full Stacktrace of that Error down below.

Using Minecraft 1.9 (latest Spigot Build right now.)
Using Citizens Build #1340 (latest Build at the moment)
Stacktrace: http://pastebin.com/cS1GJbp9

I looked at the Source Code and discovered it is caused by a Scoreboard Team being null, I made a Plugin which messes with Scoreboard Teams and could imagine there may be an Intereference with that, however I am depending on my Scoreboard Team Plugin as it functions as my Group Prefix Plugin.
Since I am not using the colored "Glow" for any NPC, Id be satisfied with a simple null-check or a config option to disable it.

**Comment by mcmonkey4eva** [comment]
Should be fixed in latest builds.

**Comment by mrCookieSlime** [comment]
Yep, can confirm the Error is gone.
