### ISSUE TITLE
Some errors on my server.

### ISSUE THREAD

**Issue by morsay** [CitizensDev/Citizens2#706]
Hi, i got the last version of spigot 1.9 and laste version of citizen.

I have no problem in game but when i restart my server i have this : (sry for my bad english)

http://pastebin.com/hWACQiev

I just want to be sure it will have no impact on my serv in the futur.

Thanks.

**Comment by mcmonkey4eva** [comment]
You do not in fact have the latest version of Citizens. Please update from http://ci.citizensnpcs.co/job/Citizens2/

**Comment by morsay** [comment]
Thanks u
