### ISSUE TITLE
Player kick when npc spawned

### ISSUE THREAD

**Issue by diecode** [CitizensDev/Citizens2#707]
Hi,

I am using latest spigot and citizens build. When I spawn NPC I get this: https://gyazo.com/f1066f8b1162759f24671c6837808478

The last row in the console before kick the player: "java.lang.ClassCastException: net.minecraft.server.v1_9_R1.BlockPosition cannot be cast to com.google.common.base.Optional"

Is this Citizens or Spigot bug?

**Comment by Morphan1** [comment]
Please paste the FULL console error to a site such as pastebin.com and link it back here

**Comment by diecode** [comment]
There isn't any error message: http://pastebin.com/faWhTFkW

**Comment by fullwall** [comment]
I don't think we use Optional in Citizens, so doesn't seem to be Citizens related

**Comment by diecode** [comment]
I investigated a lot. This is not citizens issue. Sorry for this.

Thank you your help.
