### ISSUE TITLE
EntityControllers stacktrace

### ISSUE THREAD

**Issue by Pr0totype2** [CitizensDev/Citizens2#708]
Getting this error, hehe ;P
http://hastebin.com/ehijamabeg.avrasm

**Comment by mcmonkey4eva** [comment]
What version(s) are you on?

**Comment by Pr0totype2** [comment]
Citizens2: Latest dev build
Spigot: 109 versions behind

Might be a good time to update

**Comment by fullwall** [comment]
Update spigot
