### ISSUE TITLE
Nothing Happens When I Do /Npc (any Npc command)

### ISSUE THREAD

**Issue by MinerMadness** [CitizensDev/Citizens2#709]
I don't know why/how it's doing this I need help, fast!

**Comment by mcmonkey4eva** [comment]
make sure you have the right version: http://wiki.citizensnpcs.co/Versions

**Comment by MinerMadness** [comment]
I do when I do /pl and look over Citizens It's in green but when I do a Npc command it just acts like nothing happened

**Comment by mcmonkey4eva** [comment]
Double check your version ( **Seriously** ) and if you can't find a flaw in the version choice, post a full startup log.

**Comment by MinerMadness** [comment]
Ok I'l Retry

**Comment by MinerMadness** [comment]
Still Doesn't Work

**Comment by MinerMadness** [comment]
Wait Never Mind!Thanks
