### ISSUE TITLE
Error in console. Server crash not sure if this plugin is causing it.

### ISSUE THREAD

**Issue by Duqino** [CitizensDev/Citizens2#710]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

Spigot 1.9 right now 10 updates behind but updating doenst work. Had this before i did the last update.

http://pastebin.com/Wk83VA3i

Full log if needed -> http://pastebin.com/UgHVsPts

**Comment by mcmonkey4eva** [comment]
Update to latest Citizens2 -> http://ci.citizensnpcs.co/job/Citizens2/

**Comment by Duqino** [comment]
Lol you really pushed out a update when i didnt check for one :)

Thanks!
