### ISSUE TITLE
[BUG] NPCs taking knockback from sweep attacks

### ISSUE THREAD

**Issue by PsychoLynx** [CitizensDev/Citizens2#711]
On the latest available version of Spigot 1.9 and Citizens build. Created a villager type NPC (although the same goes for humans, and I suspect other NPCs as well) - a zombie came close to the NPC and I attacked it using a diamond sword - the ensuing sweep attack caused both the NPC and the Zombie to fly back. 

The only way I managed the NPCs to take no knockback was to do ALL of the following (on a separate server): Giving the NPC a single waypoint (/npc path), giving them the Sentry trait and (/sentry incinvicible) and finally giving them a Denizen assignment. A bit cumbersome, so a fix would be highly appreciated!

**Comment by fullwall** [comment]
Having difficulty finding the handling code for this part of combat... @mcmonkey4eva ?

**Comment by mcmonkey4eva** [comment]
@fullwall it seems to fire the standard `EntityDamageByEntityEvent` but cancelling that even doesn't stop knockback -- that makes this a Spigot level issue, I think. We should bug them to patch it. Though a placeholder in C2 workaround until that's fixed may be useful.

**Comment by mcmonkey4eva** [comment]
A functioning workaround example in Denizen:
```
        on entity damaged by entity:
          - determine passively cancelled
          - adjust <context.entity> velocity:0,0,0
          - wait 1t
          - adjust <context.entity> velocity:0,0,0
```
Basically: Cancel the event, set velocity to a zero-vector, (and then to be safe, set it again 1 tick later)

**Comment by fullwall** [comment]
@mcmonkey4eva - yeah, the NMS code for this is fairly well hidden.

**Comment by mcmonkey4eva** [comment]
EntityLiving.java -> `public void a(Entity entity, float f, double d0, double d1) {`
looks like a knockback method? Something along the lines of `DoKnockback(Entity attacker, float force, float vecX, float vecZ)`...

As far as potential candidates on Entity, it's possible that it's actually something calling `public void g(double d0, double d1, double d2) {` would be the real cause - in which case outputting a stacktrace in an override of that method ought to show you the function you need to block.

**Comment by fullwall** [comment]
Should be fixed.
