### ISSUE TITLE
Dual wielding / Dutch translation

### ISSUE THREAD

**Issue by CraftaPanda** [CitizensDev/Citizens2#714]
Hi, I am having the newest citizens version and I was wondering if there is a way to dual wield a citizen?
Also if you need Dutch translation for the website/ plugin I could help you!

Sammie

`<removed>`

**Comment by mcmonkey4eva** [comment]
Just type 'offhand' into chat while using the equipment editor.

**Comment by fullwall** [comment]
It would be useful for a Dutch translation of https://github.com/CitizensDev/Citizens2/blob/master/src/main/resources/messages_en.properties

**Comment by mcmonkey4eva** [comment]
Here's proof it works + demonstration how to do it.

![Offhand](http://i.imgur.com/Uc5GU79.gif)

If that doesn't work, make sure you have:
- Latest Citizens and Spigot versions
- no "overpowering" chat plugins (Chat plugins that block the standard chat event)

**Comment by CraftaPanda** [comment]
It doesnt work. How can I create such a GIF so I can show you myself?

**Comment by mcmonkey4eva** [comment]
I used [GifCam](http://blog.bahraniapps.com/gifcam/) to make that, there's a lot of similar tools available if you don't like that one. I then uploaded to Imgur ( http://imgur.com/ ) and linked in back in my post.

If you do that, please include the output of:
`/version`
followed by
`/version citizens`

**Comment by CraftaPanda** [comment]
![gif](https://cloud.githubusercontent.com/assets/16403370/14217356/c1dfff9a-f84d-11e5-96ec-64abe2fe039e.gif)
Here you see, nothing

**Comment by mcmonkey4eva** [comment]
You are about 30 versions behind.
Please update to the latest version:
http://ci.citizensnpcs.co/job/Citizens2/

**Comment by CraftaPanda** [comment]
Really thanks!!!
