### ISSUE TITLE
Scoreboard teams bug

### ISSUE THREAD

**Issue by LXGaming** [CitizensDev/Citizens2#715]
Citizens/Spigot Bug:
NPCs are ending up in there own teams in scoreboard.

http://i.imgur.com/5JvS9So.png

Minecraft version: CraftBukkit version git-spigot-129f87a-6bf25cd (MC: 1.9)
Citizens version: 2.0.17-SNAPSHOT (build 1343)

**Comment by mcmonkey4eva** [comment]
This is somewhat intended, it's used for longer NPC names and glowing color.

**Comment by LXGaming** [comment]
Is there anyway to prevent this from happening, it prevents us from adding staff to scoreboard as they get pulled from there teams if they have an NPC.

This only occurred after updating Spigot.

**Comment by fullwall** [comment]
Adding a setting for this in the next build.
