### ISSUE TITLE
NPC Mount Command

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#719]
A default trait to keep track of when an NPC is mounted on another NPC, alongside a simple `/npc` command to mount them. For example:
`/npc sel Bob`
`/npc mount Steve`
Bob will now be permanently mounted on Steve.

This has been done by Sentry, but would be useful as a core Citizens feature!

**Comment by fullwall** [comment]
Only when mounted on another NPC? I think that's fine

**Comment by mcmonkey4eva** [comment]
@fullwall Yes, just another NPC is all that's needed realistically. Anything that requires mounting on a random entity will get too funky too fast and is better off just converting the entity to an NPC.

**Comment by mcmonkey4eva** [comment]
Still need a way to forcibly mount one NPC onto another.

**Comment by Eufranio** [comment]
?
