### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by tara81** [CitizensDev/Citizens2#720]
Just a lot of errors suddenly.
Spigot 1.9 Last updated on the 26th.
Citizens Last updated on the 26th.
http://pastebin.com/w8RWiLBA

**Comment by mcmonkey4eva** [comment]
Please post your `config.yml` and `saves.yml` via pastebin as well.

**Comment by tara81** [comment]
More errors: http://pastebin.com/Jsvry9z4
Config: http://pastebin.com/AGbct7tB
Saves: http://pastebin.com/VgTqejR7

**Comment by fullwall** [comment]
Should be fixed in latest builds.
