### ISSUE TITLE
PlayerUpdateTask using 12% CPU

### ISSUE THREAD

**Issue by oloflarsson** [CitizensDev/Citizens2#724]
**Citizens Version:** [http://ci.citizensnpcs.co/job/Citizens2/1343/](http://ci.citizensnpcs.co/job/Citizens2/1343/)
**Profiler Screenshot:** [https://i.gyazo.com/c637fd5fc7850cf25f92de9bdfc3fa75.png](https://i.gyazo.com/c637fd5fc7850cf25f92de9bdfc3fa75.png)

**Comment by mcmonkey4eva** [comment]
How does this compare to the default entity tick?
How many NPCs do you have spawned, and what are they doing?

**Comment by fullwall** [comment]
I like seeing some profiling data, but it would be nice to get inherent timings.
