### ISSUE TITLE
Mounted NPCs should enforce the controller's path

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#727]
When using the navigator API or `/npc path` command, for an NPC that is mounted on another NPC... the pile of NPCs should navigate to follow the orders of the topmost NPC. Currently they just sit around doing nothing.

**Comment by mcmonkey4eva** [comment]
@fullwall Perhaps there can be an option to choose between top-controller and bottom-controller?

ATM I'm trying to replicate Sentry's old mount functionality, which had it so that the top NPC would force its ride to go wherever was needed for the top NPC to do the attacking.

**Comment by fullwall** [comment]
@mcmonkey4eva not sure if this should be handled by Citizens

**Comment by mcmonkey4eva** [comment]
It's either Citizens does it, or myself and every other developer using the API has to make special checks for if an NPC is mounted and if so redirect the navigation instruction to the "vehicle" NPC, which seems like it would get rapidly annoying, whereas a single automated redirect in the internal path method could take care of it nicely.
