### ISSUE TITLE
Modify the inventory produced by /npc inventory doesn't take effect

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#728]
Steps to reproduce:
`/npc create bob`
`/npc inventory`
Put an item in the NPC's inventory
Restart server
Item is not there.

ALTERNATELY:
`/npc create bob`
`/npc inventory`
Put an item in the NPC's inventory
echo to console the full list of items in `npc.getTrait(Inventory.class).getContents()`

The first few slots will be the NPC's equipment, after that is an entirely empty array!

**Comment by mcmonkey4eva** [comment]
Not fixed in build 1347.

**Comment by fullwall** [comment]
May be an issue with which slot is getting saved...
