### ISSUE TITLE
Offhand unechanted

### ISSUE THREAD

**Issue by CraftaPanda** [CitizensDev/Citizens2#731]
Hi, I discovered that when I put an enchanted item in the offhand it becomes unenchanted

**Comment by CraftaPanda** [comment]
[img]http://i.imgur.com/akwMbBn.gif[/img]
Here is the proof

**Comment by mcmonkey4eva** [comment]
```
                npc.getTrait(Equipment.class).set(finalSlot,
                        new ItemStack(event.getPlayer().getInventory().getItemInMainHand().getType(), 1));
```
@fullwall ^ the relevant code literally just sets the Material, disregarding the item stack D:

**Comment by fullwall** [comment]
Fixed in newest build
