### ISSUE TITLE
Skins not rendering (help request)

### ISSUE THREAD

**Issue by TalonPhoenix** [CitizensDev/Citizens2#733]
None of my citizens have their proper skins. I even tried my own and it didn't appear, so it's not a problem with them being offline or having changed their name. I turned on debug mode and see a bunch of this spammed in the console with all of the playernames I'm using:

03.04 19:06:46 [Server] INFO Profile lookup for player 'zillie' failed: null

Versions:
Minecraft 1.9
citizens-2.0.17-SNAPSHOT.jar	

It seems no one else is having this problem except a guy who it was fixed for after turning on debug mode, so I'm not sure what's going wrong. I have more plugins in now, but even when I had just essentials and multiverse it was still a problem. It has been a problem since I updated to 1.9.

**Comment by mcmonkey4eva** [comment]
- Are you on ONLINE or OFFLINE mode server?
- Are you a SHARED HOST (IE, do you own the machine you're hosting from, or just a single server on a service that runs many servers?)

**Comment by TalonPhoenix** [comment]
Online mode and I'm a single server on a service that runs many.

**Comment by mcmonkey4eva** [comment]
That's likely the issue then.

Mojang/Minecraft restricts how rapidly a single machine can lookup textures ATM.
This is a problem with shared hosting, as too many servers are constantly looking up NPC skins and Skull item skins, making Mojang's servers block the entire machine.

We don't currently have any idea how to solve this other than to tell users they need to host off their own machine :/

**Comment by TalonPhoenix** [comment]
I went to the room where I use command blocks to spawn in heads. Sure enough, the heads on display still appeared but when I spawned in a new one it was a steve head :/ thanks for the reply, I've been thinking of getting a dedicated machine for awhile and I guess it's time.
