### ISSUE TITLE
Offhand custom shields

### ISSUE THREAD

**Issue by Sonic5317** [CitizensDev/Citizens2#735]
Offhand customized shields revert to normal shields on server restart.

**Comment by fullwall** [comment]
Fixed

**Comment by Sonic5317** [comment]
Tested with latest build, still an issue

**Comment by FlashLight34** [comment]
yep the custom shield is not serialized with citizens

**Comment by fullwall** [comment]
You are talking about shield patterns?

**Comment by Sonic5317** [comment]
Yeah customs designs, they don't save on sever restart

**Comment by FlashLight34** [comment]
any ETA about this pls? Its possible or not to add this?

**Comment by mcmonkey4eva** [comment]
It's certainly possible :) , just takes a bit of time and effort

**Comment by fullwall** [comment]
Try latest build, looks like Spigot implemented an API then forgot to use it.

**Comment by FlashLight34** [comment]
already got the latest build and tested with them :)

**Comment by mcmonkey4eva** [comment]
Woops, looks like that build didn't go through. Try now, with build 1357.

**Comment by FlashLight34** [comment]
nice
i see that in the save.yml now but maybe as a little bug with the loading see the picture below:
![shieldbug1](https://cloud.githubusercontent.com/assets/9997676/14576176/0cd121b8-0335-11e6-9943-b0493ef085e4.jpg)

i saved with /citizens save and reloaded with /citizens reload and the shield go dark see the config:
`hand:
          type: SHIELD

          amount: 1

          durability: 0

          mdata: 0

          meta:

            repaircost: 0

            blockstate:

              banner:

                basecolor: WHITE

                patterns:

                  '0':

                    color: BLUE

                    type: ts

                  '1':

                    color: RED

                    type: bs

`

**Comment by FlashLight34** [comment]
about this mcmonkey you know what is the problem?

**Comment by Sonic5317** [comment]
Also tried this and having the same issue as FlashLight with sheilds just showing as black on restart.

**Comment by fullwall** [comment]
Are you using patterns with these shields? Do the non-patterned shields save/load?

**Comment by FlashLight34** [comment]
@fullwall humm see the config i has after the reload :| in my post https://github.com/CitizensDev/Citizens2/issues/735#issuecomment-210665423

**Comment by fullwall** [comment]
@FlashLight34 - for me white blue red with no pattern is loading so I guess this is to do with patterns identifiers.

**Comment by FlashLight34** [comment]
@fullwall this is the pattern of the banner in the shield you know?

**Comment by fullwall** [comment]
Try latest build

**Comment by FlashLight34** [comment]
@fullwall Yeah that work now nice job guys continue your fantastic work :dancer:

**Comment by FlashLight34** [comment]
@fullwall just a little question: Have npc type to be filtered in blocks commands? Example 
testfor @a[type=!Npc]

**Comment by FlashLight34** [comment]
@fullwall anyway to filter npc type player with @a from command bloc?

**Comment by Sonic5317** [comment]
Seems to be working perfectly on latest build! Problem solved!
