### ISSUE TITLE
A lot of WARN in console

### ISSUE THREAD

**Issue by mellowism** [CitizensDev/Citizens2#736]
Everything seems to work fine but the console is spammed with errors and warnings. Starts with 
"An exception occurred while the trait inventory was spawning for NPC ID... " and then random id number, followed by a lot of warnings. 

Spigot and Citizens updated today.

http://pastebin.com/VreNCrMC 

http://pastebin.com/fhk2Q2A9

**Comment by mcmonkey4eva** [comment]
Please post the actual error message(s).

**Comment by mellowism** [comment]
http://pastebin.com/S5pWJCVA

**Comment by fullwall** [comment]
Fixed

**Comment by mellowism** [comment]
I'm having the same errors after updating to the latest citizens version. Should I change something in the config file on the npc inventory perhaps to make the error disappear? Remove the {}?

**Comment by fullwall** [comment]
Can you try with the next build?

**Comment by PsychoLynx** [comment]
Happens in the newest build to

**Comment by fullwall** [comment]
@PsychoLynx - having trouble reproducing, can you please paste the error and NPC type?

**Comment by PsychoLynx** [comment]
@fullwall 
Error log: http://pastebin.com/0sAna68m
saves.yml: http://pastebin.com/AzYkFvtf (Luke = Human, hepo = Horse)

**Comment by fullwall** [comment]
fixed

**Comment by mellowism** [comment]
Latest build seems to have fixed my issue.
Thanks and keep up the great job!
