### ISSUE TITLE
Players unable to path on latest version

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#737]
Player-type NPCs (possible others?) are entirely unable to move/path on Citizens 1351, Spigot 13 versions behind at time of posting.
Worth noting is that it works fine on: Citizens 1347, Spigot 13 versions behind.

**Comment by dniym** [comment]
I'd like to confirm this but with a small addition:
								npc.getNavigator().setTarget(loc);
								npc.getNavigator().setPaused(false);
as time goes by the npc appears to move like by inches each time the navigator executes, mind you the movement is so small it would take an hour for the npc to move 5 blocks.

**Comment by dniym** [comment]
was this resolved?

@fullwall fullwall closed this an hour ago

**Comment by mcmonkey4eva** [comment]
A commit was sent in for the latest build that supposedly fixes it

**Comment by fullwall** [comment]
Sorry, forgot to comment. Yes, made a new build to fix the issue.
