### ISSUE TITLE
[BUG] Citizens + Modifyworld = Unable to mount NPCs on horses

### ISSUE THREAD

**Issue by PsychoLynx** [CitizensDev/Citizens2#739]
On a clean server with PEX 1.23.4, Modifyworld and newest Citizens 2:

/npc mount --onnpc 1 (A human NPC on a horse NPC) results in the human just warping closer to the horse, as if dismounted immediately. Removing Modifyworld stops this behavior. Some sort of workaround would be nice!

**Comment by mcmonkey4eva** [comment]
```
On a clean server with PEX 1.23.4, Modifyworld and newest Citizens 2:

/npc mount --onnpc 1 (A human NPC on a horse NPC) results in the human just warping closer to the horse, as if dismounted immediately. Removing Modifyworld stops this behavior. Some sort of workaround would be nice!
```

Are you sure you didn't do something that might cause this behavior, such as removing a permission needed to mount horses from the default player group?

**Comment by PsychoLynx** [comment]
Here's my config from the test server:

http://pastebin.com/A92sxiXW

**Comment by PsychoLynx** [comment]
Okay, so update here. I added the NPC to playerlist and used PEX's debug to give it the permissions it was after (worldguard.region.bypass.*), but no luck. I also gave the NPC every single permission I myself required to mount (according to the debug) the NPC, but still no luck.

**Comment by PsychoLynx** [comment]
Another update: Managed to fix the problem by adding the NPC to my ops.json manually, but it still fels like a bit of an overkill. Oh well, I take what I can get.
