### ISSUE TITLE
Error while creating a Citizens trait

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#741]
Hello,
I'm trying to create a Citizens trait but after Citizens load NPCs I have an error :
http://pastebin.com/PvifwE7t

I'm tried with 2.0.16 & 2.0.17 API
Can you help me ?

**Comment by Blamo27** [comment]
I just removed this :
plugin.getServer().getLogger().info(npc.getName() + "has been assigned MyTrait!");

**Comment by mcmonkey4eva** [comment]
... what's your trait code?

**Comment by Blamo27** [comment]
It works now, I just removed :
> plugin.getServer().getLogger().info(npc.getName() + "has been assigned MyTrait!");

I just copy / paste the "Code Example registration and simple trait" for test

**Comment by mcmonkey4eva** [comment]
... 'kay.

**Comment by Blamo27** [comment]
Sorry
