### ISSUE TITLE
Citizens dissapear & do not move anymore

### ISSUE THREAD

**Issue by HollishKid** [CitizensDev/Citizens2#744]
Bug Description
Citizens v.2.0.17 Build 1350
CraftBukkit version git-Bukkit-cac90f6 (MC: 1.9)

Hello,

For some reason, my citizens dissapear randomly.
They do reappear after using the /citizens reload command.

Moreover, they have ALL stopped moving. Their waypoints are still defined properly in config.

Any ideas on this?
Thanks!

**Comment by mcmonkey4eva** [comment]
Old bug, update to latest versions please.
http://ci.citizensnpcs.co/job/Citizens2/

**Comment by HollishKid** [comment]
Hello,

I take the liberty to open this issue again, since I just installed the latest Citizens 2 build #1357, but I still have this issue with citizens not appearing correctly. This happens every time upon login (with authme) and sometimes randomly when walking around.

Any ideas on this? 
Thanks!

**Comment by mcmonkey4eva** [comment]
We do not support "cracked/offline" servers. Please legally acquire the game.

(Note: aside from legal issues, we also don't support it because Citizens literally can't function fully with offline mode, as offline mode messes with some important player-related data)
