### ISSUE TITLE
Add a configurable warmup for teleporting npcs

### ISSUE THREAD

**Issue by ThemInspectors** [CitizensDev/Citizens2#745]

**Comment by fullwall** [comment]
I'm assuming you mean a delay before a teleport occurs. When does this occur? On a specific command or for all teleports?

**Comment by mcmonkey4eva** [comment]
@fullwall Any player-command-induced teleport most likely.

**Comment by fullwall** [comment]
@mcmonkey4eva I guess any TeleportCause.PLUGIN?

**Comment by fullwall** [comment]
Added under npc.teleport-delay
