### ISSUE TITLE
Zero response

### ISSUE THREAD

**Issue by xXxIKLUtCH** [CitizensDev/Citizens2#746]
I'm not sure if this is a bug or if i am just plain dumb, however, when I install citizens 1 or 2 into my plugins folder everything loads up just fine. I didn't change anything in the config except for the money required to create an npc. I tried it without config changes as well. No matter what I tried, citizen versions, config changes, etc... When I logged into the world the only command that worked was /help citizens. Every other command was unresponsive. The commands showed up in the console and I did not get and error or was told that it was an invalid command, nothing happened. If anyone knows why this is happening please let me know. Thanks
-xXxIKLUtCH

**Comment by mcmonkey4eva** [comment]
Make sure you have the correct version of Citizens2 for your minecraft version: http://wiki.citizensnpcs.co/Versions

**Comment by xXxIKLUtCH** [comment]
@mcmonkey4eva Thanks so much, after trying almost all of the versions i finally found one that worked, curiously though it was not the same version of spigot that i am running, but i won't complain, thanks again,
-xXxIKLUtCH
