### ISSUE TITLE
onTeleport Trait Request

### ISSUE THREAD

**Issue by CharlieIsHere** [CitizensDev/Citizens2#747]
This is a feature request.

Currently there is no way to tell with Bukkit's API when a entity has been teleported using Entity.teleport(Location loc) which is what is used to move the NPC with /npc tphere.

So I would like to request onTeleport to be added to custom traits so we can EFFICIENTLY tell when someone moves the NPC with /npc tphere.

Thanks :+1:

**Comment by mcmonkey4eva** [comment]
Why not an event?

**Comment by CharlieIsHere** [comment]
I feel like whatever would work, but the fact is you don't have events for onSpawn, onAttach, onDespawn in the trait class you use method calls. Its a per-trait per-npc basis, so I would think it would be inside the trait class not an event. But you guys know your own software more than I do and I trust your judgment over mind.

**Comment by fullwall** [comment]
This can be added fairly easily for when you use Citizens' npc.teleport method, but doing it more generally may affect performance. Why do you need this feature?

**Comment by CharlieIsHere** [comment]
I do not see any way to tell when the NPC has been moved with /npc tphere, if I am wrong let me know. The reason I need to know is so I can move the hologram above its head when its teleported. I highly doubt this will effect performance as when do you really ever move the NPC with /npc tphere other than to adjust the position initially.

**Comment by fullwall** [comment]
@CharlieIsHere - sure, there's just a difference between an event for Citizens' npc.teleport and for Spigot's entity.teleport since the latter is called much more often

**Comment by CharlieIsHere** [comment]
So there is already a NPCTeleportEvent?

**Comment by fullwall** [comment]
@CharlieIsHere There's two methods that are both known as 'teleport' - NPC#teleport, which teleports the NPC and the mounts but is Citizens-specific (it won't catch teleports from other plugins) and Entity#teleport, which is a Spigot method called by every plugin. NPCTeleportEvent could be both of these or just for NPC#teleport.

**Comment by CharlieIsHere** [comment]
It should just be for NPCs in my opinion, anyone working with the API only needs to know when the Citizens NPC moves, not the others.

**Comment by fullwall** [comment]
I created NPCTeleportEvent.
