### ISSUE TITLE
NPC's don't load

### ISSUE THREAD

**Issue by iamV12** [CitizensDev/Citizens2#748]
Minecraft Version: 1.9.2
Citizens Build: #1356 (latest)
Logs: http://hastebin.com/buvahizami.coffee

**Comment by mcmonkey4eva** [comment]
```
Citizens Build: #1356 (latest)
```
Lying won't help you get support.

From the logs:
```
[Citizens] Loading Citizens v2.0.17-SNAPSHOT (build 1312)
```

Update Citizens.
