### ISSUE TITLE
Wither tries to fly up before following a path

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#751]
Every time the path is updated, the wither flies up, waits a few seconds, THEN moves forward.

This makes it impossible to function when the pathfinder is updated too rapidly.

**Comment by fullwall** [comment]
Can you get a screenshot of the path debug output?

**Comment by mcmonkey4eva** [comment]
Here's a quick recording of it happening (default minecraft pathfinder): http://i.imgur.com/ZiZpW0t.gifv
Looks roughly the same with `use-new-finder` enabled.

**Comment by fullwall** [comment]
@mcmonkey4eva I think this is caused by the tall grass in the way not being marked as passable. Can you try removing the grass?

**Comment by mcmonkey4eva** [comment]
the NPC is actually in a clearing in that recording - there's tallgrass around it but not where the NPC is actually moving through.

**Comment by fullwall** [comment]
Fixed
