### ISSUE TITLE
NPCLeftClickEvent

### ISSUE THREAD

**Issue by Scratch741** [CitizensDev/Citizens2#752]
Hello. I'm using Quester "http://dev.bukkit.org/bukkit-plugins/quester/" and since Citizens 2.0.17, Quester can't recognize NPCLeftClickEvent. Because of that I can't hit a NPC and see which Quest should I do. I was asking Quester developer and he told me you removed this method. I'm asking for adding back this method or explain how could possibly Quester recognize left click on NPC in PvP area off. Thanks!

**Comment by fullwall** [comment]
The only thing that has changed is the ignoring of already-cancelled damage events by Citizens. What plugins are you using that might conflict with Citizens by preventing damage events from happening?

**Comment by raGan262** [comment]
He mentioned it happens in areas where pvp is prevented. He also mentioned that WorldGuard has been used to protect them.

**Comment by Scratch741** [comment]
As Ragan stated, it is in areas with prevented pvp. I prevent pvp with WorldGuard (6.1).

**Comment by fullwall** [comment]
Yes, this is because of cancelled pvp. There's compatibility issues with both approaches so not sure how to proceed.

**Comment by raGan262** [comment]
It used to send cancelled events if I remember correctly. I think that approach was working well enough. If you want plugins to really know what's going on, you could instead extend event to include whether or not origin was cancelled. 

Plugins would be able to decide what to do even if damage is cancelled, while still being able to know if something cancelled npc click directly. 

I guess anything is better than using damage events or worse to detect clicks manually in user code.

**Comment by fullwall** [comment]
@raGan262 - yeah there's actually a packet specifically for left click and I wish Spigot had an event for it :(

**Comment by raGan262** [comment]
Does that mean it will stay unresolved for now?

**Comment by fullwall** [comment]
@raGan262 - I will revert the change

**Comment by fullwall** [comment]
Reverted
