### ISSUE TITLE
Metric is old

### ISSUE THREAD

**Issue by FlashLight34** [CitizensDev/Citizens2#753]
the metric version is old :P

**Comment by mcmonkey4eva** [comment]
... so?

**Comment by FlashLight34** [comment]
so has a change with the getonlineplayers() no?

**Comment by mcmonkey4eva** [comment]
Metrics still works fine, and is reporting accurately. What's the problem?

**Comment by FlashLight34** [comment]
int playersOnline = Bukkit.getServer().getOnlinePlayers().size();
to
int playersOnline = this.getOnlinePlayers();

private int getOnlinePlayers() {
        try {
            Method onlinePlayerMethod = Server.class.getMethod("getOnlinePlayers");
            if(onlinePlayerMethod.getReturnType().equals(Collection.class)) {
                return ((Collection<?>)onlinePlayerMethod.invoke(Bukkit.getServer())).size();
            } else {
                return ((Player[])onlinePlayerMethod.invoke(Bukkit.getServer())).length;
            }
        } catch (Exception ex) {
            if (debug) {
                Bukkit.getLogger().log(Level.INFO, "[Metrics] " + ex.getMessage());
            }
        }
        
        return 0;
    }

**Comment by mcmonkey4eva** [comment]
That's an irrelevant change though.

I'll say it in big bold letters just for you...

**WHAT IS THE PROBLEM HERE?**

**Comment by FlashLight34** [comment]
hum i think its a important change no? because with Mobhunting i got an error with metric bukkit get onlineplayers but he already update the metric so he think that come frome another plugin with old metric

**Comment by mcmonkey4eva** [comment]
It's not Citizens causing any Metrics errors. Our version of the code is fully up-to-date... more-so than the code you posted above, in fact. That code is outdated compared to our current code.
