### ISSUE TITLE
Disable auto-save/center mobs

### ISSUE THREAD

**Issue by FlaggedBrad** [CitizensDev/Citizens2#755]
- This is a feature request

Please have a way of disable auto saving or have an option to replace every .54021606445312 for the x and z coordinates .5
This would be a great solution to the problem of some mobs drifting, as seen in a [bug report of mine](https://github.com/CitizensDev/Citizens2/issues/754)

**Comment by fullwall** [comment]
You can already disable autosaving in the config

**Comment by FlaggedBrad** [comment]
How can i disable it?

**Comment by fullwall** [comment]
Set the save task delay to a large number

**Comment by FlaggedBrad** [comment]
thank you :D

**Comment by fullwall** [comment]
Try with latest build
