### ISSUE TITLE
NPC won't spawn on worldload with denizen

### ISSUE THREAD

**Issue by GomaTerzu** [CitizensDev/Citizens2#756]
Hey fullwall, so I have the following issue:

I try to replace multiverse with a denizen script. In order to load a world on server start I use

- createworld worldname

and then the world with the name gets loaded. The problem is that NPCs won't automatically load in these worlds until I make /citizens reload or select them and make /npc spawn

When I look into the citizens save file all NPCs are listed as 

spawned:true

so I probably should not be able to actually spawn them with the spawn command again. When I make /citizens reload it only spawns npcs in loaded chunks. If I enter a chunk with an npc the npc won't be automatically loaded, too.

I also have the setting 

  chunks:
    always-keep-loaded: true

I was told citizens should try to load NPC automaticaly here so maybe I found an issue. Can you help me here?

**Comment by fullwall** [comment]
Can you try setting debug to true in the config and pasting the server output?

**Comment by GomaTerzu** [comment]
Sorry I could not reproduce it because I gave up the worldcreate setting soon after. Once I try it again, I'll report it
