### ISSUE TITLE
NPC CREATE COST NOT WORKING

### ISSUE THREAD

**Issue by crypticturtle** [CitizensDev/Citizens2#757]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant
i dont know about the issues atop this but my cost system dose not work i can make npc's but it dosn't cost any thing i set up the config but it still dosnt work please help me

**Comment by ThemInspectors** [comment]
maybe you have a bypass permission? also follow the format of the issue

**Comment by crypticturtle** [comment]
what format?

**Comment by ThemInspectors** [comment]
Server log, citizens version (on pastebin or similar) 
Spigot version and minecraft version,
use "/about Citizens" in-game to get the version or in console "about Cititzens"
for the spigot/bukkit version use "/version" or "version" in-console

**Comment by fullwall** [comment]
What economy plugin are you using? Citizens uses Vault so it must be compatible with Vault.
