### ISSUE TITLE
Spigot1.9.2 Citizens/Sentinel errors

### ISSUE THREAD

**Issue by sammyt291** [CitizensDev/Citizens2#758]
Hello,
Im running:
- Spigot 1.9.2 r0.1 
- Java 1.8.0 u45 
- Linux Ubuntu 15.04.
- Citizens ver: 2.0.17
- Sentinel ver: 0.4 

When creating an NPC I have this error show in console:
http://pastebin.com/HqyHWvY6
(Exact same error for a few other commands such as /npc skin <name>)

After giving the NPC a Single node path and then applying the sentinel trait, The console gets spammed with this error:
http://pastebin.com/crw5ezr6
(This error does not occur if I add the sentinel trait without giving the NPC a path.)

Both Citizens & Sentinel configs are default as generated.

Edit:
The first error happens if I have Sentinels loaded or not.
The second error only occurs when Sentinels is loaded.

**Comment by mcmonkey4eva** [comment]
Update Citizens and possibly Spigot, you're outdated - http://wiki.citizensnpcs.co/Versions

**Comment by sammyt291** [comment]
Perfect!, the newer version of Citizens fixes this issue, I didn't realize mine was out of date because I was only paying attention to the release version and not the build version, Thank you very much!
