### ISSUE TITLE
Skins not working.

### ISSUE THREAD

**Issue by GirlGlitch** [CitizensDev/Citizens2#759]
Bug Description.

Version 1.7.10 MC // Citizens Version https://gyazo.com/23ac5c6b5bfdb0914cb72758730b8e94
https://dl.dropboxusercontent.com/content_link/0skJUOQxcGpkpv2ZzA1pHozulT99jiPndw4ZVmmKZr4ZVvDz7hJF1eb63Uz9aMUh/file?dl=1
Citizens download of version I have right now. ^

This version of citizens was made for Cauldron servers (Modded servers)

For some reason when the command /npc skin is executed it types out in chat &cnull (not literally the &c part that's just the color code of the lettering) 
when an Npc is selected and the command [/npc skin Glitch] (Glitch is my IGN) The npc refreshes but it does not load the skin. It is still a Steve, and when the command is executed there is no log about it in the console, the only log that occurs is the log showing I executed the command /npc skin Glitch.

I have found this warning in my console though. I do not know if it is relevant.
24.04 23:40:27 [Server] ERROR [Citizens] Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes

Please help me with this issue, I desperately would like to use the Citizens Skin Feature!

**Comment by mcmonkey4eva** [comment]
I think skins never were made to work with old Cauldron servers :/

For that matter, we didn't even make any Cauldron-compatible versions - someone else did (bloodmc iirc)
