### ISSUE TITLE
Main Thread IO at startup

### ISSUE THREAD

**Issue by Techcable** [CitizensDev/Citizens2#761]
You [load saves on the main thread](https://github.com/CitizensDev/Citizens2/blob/3c9e82ea1d0310d9a05e23213e944c068b6dd989/src/main/java/net/citizensnpcs/Citizens.java#L296-L301) on startup.
I saw this take over 1000 milliseconds on someone's timings.
You should be running this async ;)

**Comment by mcmonkey4eva** [comment]
... what exactly do you think that code does, and why do you think it's a problem to do that on the main thread?

**Comment by Techcable** [comment]
Its mainly 'saves.loadInto(npcRegistry)' that i'm worried about.
I perfectly understand, wanting to update your data structure on the main thread.
However, i'd prefer that you do the loading from a file async, then proceed to update the data structure on the main thread.

**Comment by mcmonkey4eva** [comment]
That creates a delay / fault risk.

Its important to note that that is *one-time startup code*, not continually running things.

If that gets allowed to delay off-thread, it could potentially be as bad as players joining before the NPCs show up... which could potentially be problematic, particularly if NPC Traits are used for any form of player control. It could also be problematic for plugins that rely on Citizens loading within the first tick, that break if their NPCs are not able to load quickly.

The real question, though, is *why*. What is the advantage of doing a one-time loading task off thread? Who benefits from the startup sequence being off the main thread?

**Comment by fullwall** [comment]
Config is loaded on the main thread too... it's done this way since it's at server startup. Unless you have a specific use case I don't see the benefits of complicating this part of the code.
