### ISSUE TITLE
NPCs do not spawn

### ISSUE THREAD

**Issue by Sparta0** [CitizensDev/Citizens2#762]
Hello, I installed Citizens, but when I start the command /npc create Example , the NPC does not spawn. In the chat is a message:
Please Report this Error: [See Console]
java.lang.NoClassDefFoundError:
net/minecraft/server/v1_8_R1/Packet
And when I look in the Console, there is the following message:

24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) 24.04 16:25:11 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:166) 24.04 16:25:11 [Server] WARN at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) 24.04 16:25:11 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) 24.04 16:25:11 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) 24.04 16:25:11 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) 24.04 16:25:11 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) 24.04 16:25:11 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154) 24.04 16:25:11 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:601) 24.04 16:25:11 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 24.04 16:25:11 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 24.04 16:25:11 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47) 24.04 16:25:11 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92) 24.04 16:25:11 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

The Link to the server log:
javascript:submitBrowseForm('/logs','','browse','main');
[net2ftp-1461659770.zip](https://github.com/CitizensDev/Citizens2/files/236191/net2ftp-1461659770.zip)

Minecraft version: Craftbukkit 1.8.8 (Java 7), Citizens version: 2.0.14 (alpha 1 for MC 1.8.1)

**Comment by mcmonkey4eva** [comment]
You got the wrong version of Citizens. Download the correct 1.8.8 version from here: http://wiki.citizensnpcs.co/Versions

**Comment by Sparta0** [comment]
thanks

**Comment by Sparta0** [comment]
When I enter /citizens there is no message. But I already installed Citizens for 1.8.8

**Comment by mcmonkey4eva** [comment]
**Pastebin** a startup log?

**Comment by Sparta0** [comment]
Now its working. Thanks.
