### ISSUE TITLE
Large Scoreboard.dat resulting in memory leaks and long logins

### ISSUE THREAD

**Issue by BlackBeltPanda** [CitizensDev/Citizens2#763]
Using Citizens 2.0.17

After a few days, the scoreboard.dat file reaches about 3MB and causes long "Download Terrain" screens when players try to login.

In Bungee/Waterfall setups, it also causes memory leaks with the proxy server.

The scoreboard.dat file fills up with thousands of teams like this one: https://i.gyazo.com/4b01bacc7d5cf748337083f85390c28f.png

Example scoreboard.dat file: https://www.dropbox.com/s/afnde0mzuu0cvc6/scoreboard.dat?dl=1

I know Waterfall has just received a patch that interns strings to avoid the memory leak, but it would still be a problem in Bungee setups.

**Comment by fullwall** [comment]
Changed to only use one scoreboard per NPC, thanks for the report.
