### ISSUE TITLE
/npc skin <name> -p not working correctly.

### ISSUE THREAD

**Issue by elliswin** [CitizensDev/Citizens2#766]
I have had a problem with the above command today.

Earlier today I successfully managed to create 3 NPC using this method with all 3 wearing Police Officer Skins.

I have attempted several times now to repeat the process, I change my skin to the next one I want then do /npc create <name> the do npc skin EllisWin -p, However  no matter how often I change my skin or how many times I log in or out, when ever I try to issue the /npc skin EllisWin -p it always shows the police officer I did this morning.

I get the following error in the console, any ideas you have that what it might be hen let me know.

30.04 13:44:45 [Multicraft] Skipped 3 lines due to rate limit (30/s)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
30.04 13:44:41 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
30.04 13:44:41 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
30.04 13:44:41 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
30.04 13:44:41 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
30.04 13:44:41 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
30.04 13:44:41 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
30.04 13:44:41 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
30.04 13:44:41 [Server] WARN at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:407)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
30.04 13:44:41 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
30.04 13:44:41 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
30.04 13:44:41 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add
30.04 13:44:41 [Server] INFO EllisWin issued server command: /npc create OldMan_Haggerty
30.04 13:44:10 [Server] INFO Admins: EllisWin
30.04 13:44:10 [Server] INFO CONSOLE issued server command: /list

**Comment by mcmonkey4eva** [comment]
That error comes from having the wrong version - update from http://wiki.citizensnpcs.co/Versions
