### ISSUE TITLE
errors in logs

### ISSUE THREAD

**Issue by tryolivier** [CitizensDev/Citizens2#767]
Hello,

I use the last version of citizens for spigot 1.9.2

I have a lot of errors in logs 

I show you : http://hastebin.com/xuqodemimo.avrasm

thanks !

**Comment by mcmonkey4eva** [comment]
You're on an old version, update from here: http://wiki.citizensnpcs.co/Versions

**Comment by tryolivier** [comment]
oh yes sorry :( :p 

thanks to reply
