### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by Qinak** [CitizensDev/Citizens2#768]
Got this error spamming every 4/5 minutes since minecraft 1.9.

Using latest version of Spigot as of yesterday _(2016-05-02)_:
CraftBukkit version git-Spigot-e6f93f4-ed60c01

[**Console**](http://pastebin.com/fevSBfjX)
[**Config.yml**](http://pastebin.com/X5zxVUNB)
[**Saves.yml**](http://pastebin.com/3asd6fdV)

**Comment by mcmonkey4eva** [comment]
Update your Citizens2: http://ci.citizensnpcs.co/job/Citizens2/
