### ISSUE TITLE
Citizens pathfinding slow speed

### ISSUE THREAD

**Issue by mawej1** [CitizensDev/Citizens2#769]
I'm not quite sure if this issue is more Denizen or Citizens regarded, but I believe it has to do something with the Citizens' path-finding. 

When I try '`/ex walk <npc> <player.location>`'  the NPC just moves slowly when it is close to the player (never reaching him), and stops when it hits an obstacle when further away from the player (as seen on the gif). It also sometimes occurs that the NPC just teleports to the destination.

The config for Citizens - http://mcmonkey.org/paste/33296 
I did try it first with use-new-finder: false, but the NPC would just stop as soon as it hit an obstacle, not completing the path.

I'm using Denizen build 1615 and Citizens build 1362, along with newest 1.9.2-R0.1 snapshot

The video - http://i.imgur.com/UOWInrt.gifv

Thanks for any suggestions/replies.

**Comment by mawej1** [comment]
Another proof http://i.imgur.com/zbx1Vdx.gifv

**Comment by fullwall** [comment]
Can you please make a video with debug-pathfinding set to true in your config?
