### ISSUE TITLE
NPC Name tag not appearing

### ISSUE THREAD

**Issue by Elements-** [CitizensDev/Citizens2#77]
NPC nametag doesnt appear in 1.8

**Comment by fullwall** [comment]
Sorry, this got lost. I'll look into it again...

**Comment by fullwall** [comment]
I'll have to use a hologram, but I'm not sure about whether to do that.

**Comment by Elements-** [comment]
Like how to do it? Its an invisible mob

- Elements

**Comment by Legendaryx** [comment]
I saw on wynncraft that npcs had nameplates. And even nameplates below their nameplate.

Any way to get these things implemented? :P

**Comment by Elements-** [comment]
@Legendaryx Sounds like scoreboard stuff.

**Comment by Davidp81** [comment]
@fullwall Possibly add in a soft dependency for Holographic Displays?

**Comment by madtomic** [comment]
If you added hologram. Wouldn't it be two names ?

**Comment by mcmonkey4eva** [comment]
@madtomic not if you mounted the hologram onto the NPC

**Comment by madtomic** [comment]
I will try that. Thanks

**Comment by madtomic** [comment]
How to mount the hologram onto the NPC?

**Comment by mcmonkey4eva** [comment]
Assssskkkk the developers of the hologram plugin

**Comment by madtomic** [comment]
Going back to 1.7.10

 1.8.x sucks.

**Comment by Morphan1** [comment]
@madtomic please remember that we will not provide any support for old versions. I hope you don't run into any problems

**Comment by Legendaryx** [comment]
It is possible nowadays with a certain thing. Its also on wynncraft that they have npcs with nametags.
