### ISSUE TITLE
NPC Events not registering

### ISSUE THREAD

**Issue by MythicFX** [CitizensDev/Citizens2#772]
This is a bug, and i tried to do NPC events but they are not registering, i think this is a bug
Code:
```
 @EventHandler
	public void NPCDamageByEntityEvent(NPCDamageByEntityEvent event){
                  NPC np = event.getNPC(); 
		  Player player = (Player)event.getDamager();
		  if(np.getName().equalsIgnoreCase(npc.getFullName())){
                      // Code ( Yes i put something here, just to keep my code secured )
			  }
			  if(config.getBoolean(player.getName() + ".ka1") == true){
                      // Code ( Yes i put something here, just to keep my code secured )
			  }
		  }
	  }
```
Version: 1.8.8

**Comment by Morphan1** [comment]
Your code has no context. Is this inside a trait? If not, are you registering the event properly yourself? Have you tried putting debug output in the event to make sure your code isn't just failing?

**Comment by MythicFX** [comment]
Nevermind, i was using Citizens 2 instead of CitizensAPI, Sorry. Closed
