### ISSUE TITLE
Citizens 2 Plugin showing up as disabled

### ISSUE THREAD

**Issue by Mineguy** [CitizensDev/Citizens2#773]
I'm not sure if it's a bug.
Minecraft Server Version - 1.8.3 USING CraftBukkit.
If I type in** /npc **then hit SHIFT+TAB, two options come up--/npc AND /npc2???
Please help me with this issue. I am look forward into using this Plugin.
If you need anything else from me to understand what is going on, please reply : )

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions <-- grab the correct version of the plugin.

**Comment by Mineguy** [comment]
Ok, nevermind. It shows up as an enabled plugin - 
![2016-05-05_18 59 05](https://cloud.githubusercontent.com/assets/19213962/15060784/c3a1c046-12f3-11e6-8052-17b3f0402161.png)

Just, whenever I execute /citizens OR /npc OR ANYTHING part of the plugin, nothing happens. Literally, i doesn't even say "You don't have perms" or "unknown command, run /help".
All I do is execute ANY CITIZENS command in game and NOTHING happens.

Thank you for replying! It would be greatly appreciated if you could help me on this one.
Do I need full operator perms? I am not sure. Thank you, again!

**Comment by mcmonkey4eva** [comment]
I'll say again:" http://wiki.citizensnpcs.co/Versions <-- grab the correct version of the plugin."
99% of problems like this are due to the wrong version being installed.
And yes you generally need permissions to operate a plugin.

**Comment by BenPlayzz** [comment]
Hello. I am experiencing this problem too. The plugin is appearing red in my plugins list. I'll add a picture. I have the correct version of the plugin. I am using bungee and the servers are in offline mode (does this effect the plugin?).

Thanks
![image](https://cloud.githubusercontent.com/assets/19263136/15108382/3b79c854-1608-11e6-9abe-7ae8c8a3ad8d.png)

**Comment by mcmonkey4eva** [comment]
@BenPlayzz offline mode can cause bugs, but it's generally safe with bungee.

Please share the output of:
`/version`
as well as:
`/version citizens`

**Comment by BenPlayzz** [comment]
Server Version:
![image](https://cloud.githubusercontent.com/assets/19263136/15135244/9b28554c-16a6-11e6-8a71-130105ae23f9.png)

Citizens version:

![image](https://cloud.githubusercontent.com/assets/19263136/15135258/b3ebb498-16a6-11e6-918b-54ff7d226e6a.png)

**Comment by mcmonkey4eva** [comment]
See this is the problem: Users keep lying to me on the support page :(
You have the wrong version. http://wiki.citizensnpcs.co/Versions

**Comment by BenPlayzz** [comment]
which version do I need?

**Comment by mcmonkey4eva** [comment]
the one labeled  1.8.8

**Comment by BenPlayzz** [comment]
aha, thank you. I had downloaded this already but realised that I hadn't removed the other version i had downloaded
