### ISSUE TITLE
Endermen do not hold items

### ISSUE THREAD

**Issue by Sonic5317** [CitizensDev/Citizens2#775]
In this issue, please include:

Using latest build on 1.9.2, when using /npc equip Endermen do not hold blocks that are given to them and just drop to the floor instead.

**Comment by mcmonkey4eva** [comment]
Have you tried `/npc item STONE`?

**Comment by Sonic5317** [comment]
just tried it, doesn't seem to like the command.
![2016-05-07_00 23 48](https://cloud.githubusercontent.com/assets/13396169/15088346/3926570e-13ea-11e6-89c0-40d89b414f38.png)

**Comment by fullwall** [comment]
Fixed
