### ISSUE TITLE
NPC's nametags appear when in F1 mode

### ISSUE THREAD

**Issue by svensonic1** [CitizensDev/Citizens2#776]
Hello, on the latest dev build of Citizens all NPC's have nametags above them when you are in F1 mode in other versions it didn't and I think its a bug.

**Comment by fullwall** [comment]
You mean NPCs with invisible nametags have their nametags displayed? Isn't this expected behaviour for that mode?

**Comment by svensonic1** [comment]
No, I mean like this normally when you are in F1 mode (no gui and hud of minecraft) players dont show names with the latest version of 2.0.18 it shows names above players heads:https://gyazo.com/cf0c1609169fb68de1fd5b37f7c69523
Date: Mon, 9 May 2016 01:39:04 -0700

**Comment by svensonic1** [comment]
Hmm, is there a fix available for this already?

**Comment by mcmonkey4eva** [comment]
I don't know what this would be other than a client issue really
