### ISSUE TITLE
NPC Skins Vanishing

### ISSUE THREAD

**Issue by CKGAR** [CitizensDev/Citizens2#777]
NPC skins are vanishing with the same exact symptoms as in the referenced issue. I am running the latest version of Citizens and latest Spigot version. #359

**Comment by mcmonkey4eva** [comment]
Then... use that issue?

**Comment by CKGAR** [comment]
It is closed, old, and no one responded to me. There was no reason to close this issue.

**Comment by Morphan1** [comment]
That issue is, in fact, not closed. So yes, there was a reason to close this: `duplication`.

**Comment by CKGAR** [comment]
Um, yes. It was closed. Of course it is open now, because I commented on it, but no one responded. They were responding to other issues so I figured they didn't see it.
![e471ef8f88d4c78091f80f90454c98d3](https://cloud.githubusercontent.com/assets/8227387/15101340/55128164-155b-11e6-973a-31f6e4c87ed9.png)

**Comment by mcmonkey4eva** [comment]
No it was literally never closed, that screenshot you posted just indicates that the closed issue #637 links back to that issue.

**Comment by CKGAR** [comment]
Ok, well is it going to be addressed?

**Comment by BlackCoyote** [comment]
yes but on https://github.com/CitizensDev/Citizens2/issues/359 :)
