### ISSUE TITLE
Bug? Dunno. pretty urgent D:

### ISSUE THREAD

**Issue by craftinFeathers** [CitizensDev/Citizens2#778]
Hello! I have been having a problem with the citizens plugin. I know you guys aren't the plugin developers but maybe you can help me. I have had an issue with citizens, as it is installed, the commands are there, but when i do theme there is not a error message nor anything that happens.

Basically, When i do /npc there is no error message that states "you need to have a npc selected" etc etc.
it says the plugin is active but apparently It is not? D: 
thanks for all your help in advance!

**Comment by mcmonkey4eva** [comment]
Make sure you have the right version: http://wiki.citizensnpcs.co/Versions

**Comment by craftinFeathers** [comment]
I have made sure I am using the correct version D: mcmonket4eva

**Comment by mcmonkey4eva** [comment]
How sure?
99% of problems like this are from a minor versioning error. Citizens is extremely sensitive to this.

**Comment by craftinFeathers** [comment]
i am on 1.8.3 i believe, and i believe i also have the correct version, as i saw your answer on other forms
 mcmonkey4eva

**Comment by mcmonkey4eva** [comment]
Perhaps there was an error at startup then?

Please pastebin a startup log. (Start your server and pastebin the contents of `logs/latest`)

**Comment by craftinFeathers** [comment]
Do you mean copy the message that is in console when my server is started up? if so:
09.05 19:21:57 [Server] INFO CoreProtect version 2.10.0 is enabled!
09.05 19:21:57 [Server] INFO Using SQLite for data storage.
09.05 19:21:57 [Server] INFO Enabling MyMOTD v0.2.5
09.05 19:21:57 [Server] INFO Enabling WhatIsIt v1.3.8
09.05 19:21:57 [Server] INFO has been enabled.
09.05 19:21:57 [Server] INFO Enabling BukkitNPC v0.1
09.05 19:21:57 [Server] ERROR Error occurred while enabling BukkitNPC v0.1 (Is it up to date?)
09.05 19:21:57 [Server] INFO java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/World
09.05 19:21:57 [Server] INFO at me.stopbox123.npc.Main.onEnable(Main.java:13) ~[?:?]
09.05 19:21:57 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_51]
09.05 19:21:57 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
09.05 19:21:57 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[factions.jar:git-Spigot-dbe012b-61ef214]
09.05 19:21:57 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
09.05 19:21:57 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_51]
09.05 19:21:57 [Server] INFO ... 12 more
09.05 19:21:57 [Server] INFO Enabling ClearLag v2.9.1
09.05 19:21:57 [Server] INFO Loading modules...
09.05 19:21:57 [Server] INFO Modules enabed, loading config values
09.05 19:21:59 [Multicraft] Skipped 28 lines due to rate limit (30/s)
09.05 19:21:59 [Server] INFO Enabling EssentialsChat vTeamCity
09.05 19:21:59 [Server] INFO Enabling Factions v2.7.5
09.05 19:21:59 [Server] INFO === ENABLE START ===
09.05 19:21:59 [Server] INFO === ENABLE COMPLETE (Took 131ms) ===
09.05 19:21:59 [Server] INFO Enabling CombatLog v1.8.11
09.05 19:21:59 [Server] INFO Loading messages.properties.
09.05 19:21:59 [Server] INFO Loading config.yml.
09.05 19:21:59 [Server] INFO DisguiseCraft plugin not found! Disguise removal will not work.
09.05 19:21:59 [Server] INFO CombatLog v1.8.11 Enabled.
09.05 19:21:59 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
09.05 19:21:59 [Server] Startup Done (8.480s)! For help, type "help" or "?"
09.05 19:22:00 [Server] INFO Loading Cachefile datas...
09.05 19:22:00 [Server] INFO Loading Onlineplayer datas...
09.05 19:22:00 [Server] INFO Loading Registry datas...
09.05 19:22:00 [Server] INFO Loading Dbmojangapi datas...
09.05 19:22:00 [Server] INFO Player Strings Found: 0
09.05 19:22:00 [Server] INFO Player Strings Cached: 0
09.05 19:22:00 [Server] INFO Player Strings Remaining: 0
09.05 19:22:00 [Server] INFO Now fetching the remaining players from Mojang API ...
09.05 19:22:00 [Server] INFO ... done!
09.05 19:22:00 [Server] INFO Saving Cachefile...
09.05 19:22:00 [Server] INFO Upgrading from player name to player uuid...
09.05 19:22:00 [Server] INFO Pre update factions_mplayer.
09.05 19:22:00 [Server] INFO Post update factions_mplayer. Took 1ms. 0/15 changed.
09.05 19:22:00 [Server] INFO ... done!
09.05 19:22:00 [Server] INFO (database saving will now commence which might lock the server for a while)
09.05 19:22:00 [Server] INFO ** Vaults have already been converted to UUIDs. If this is incorrect, shutdown your server and rename the plugins/PlayerVaults/uuidvaults directory.
09.05 19:22:00 [Server] WARN The block breaking data is incomplete, default to allow instant breaking:
09.05 19:22:00 [Server] WARN --- Missing entries -------------------------------
09.05 19:22:00 [Server] WARN * MISSING 165(SLIME_BLOCK / SOLID+GROUND)



**just in case i did make a mistake with the version, i am running spigot 1.8.3**

**Comment by craftinFeathers** [comment]
I copied my message from console, hopefully that is fine:

09.05 19:32:12 [Server] INFO Initializing file backend
09.05 19:32:12 [Server] INFO Permissions file successfully reloaded
09.05 19:32:12 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
09.05 19:32:12 [Server] INFO [Vault][Permission] PermissionsEx hooked.
09.05 19:32:12 [Server] INFO [Vault][Chat] PermissionsEx_Chat hooked.
09.05 19:32:12 [Server] INFO Enabling WorldGuard v5.8
09.05 19:32:12 [Server] INFO (world) TNT ignition is PERMITTED.
09.05 19:32:12 [Server] INFO (world) Lighters are PERMITTED.
09.05 19:32:12 [Server] INFO (world) Lava fire is blocked.
09.05 19:32:12 [Server] INFO (world) Fire spread is UNRESTRICTED.
09.05 19:32:12 [Server] INFO Loaded configuration for world 'world'
09.05 19:32:12 [Server] INFO (world_nether) TNT ignition is PERMITTED.
09.05 19:32:12 [Server] INFO (world_nether) Lighters are PERMITTED.
09.05 19:32:12 [Server] INFO (world_nether) Lava fire is blocked.
09.05 19:32:12 [Server] INFO (world_nether) Fire spread is UNRESTRICTED.
09.05 19:32:12 [Server] INFO Loaded configuration for world 'world_nether'
09.05 19:32:12 [Server] INFO (world_the_end) TNT ignition is PERMITTED.
09.05 19:32:12 [Server] INFO (world_the_end) Lighters are PERMITTED.
09.05 19:32:12 [Server] INFO (world_the_end) Lava fire is blocked.
09.05 19:32:12 [Server] INFO (world_the_end) Fire spread is UNRESTRICTED.
09.05 19:32:12 [Server] INFO Loaded configuration for world 'world_the_end'
09.05 19:32:12 [Server] INFO (Flowers) TNT ignition is PERMITTED.
09.05 19:32:12 [Server] INFO (Flowers) Lighters are PERMITTED.
09.05 19:32:12 [Server] INFO (Flowers) Lava fire is blocked.
09.05 19:32:12 [Server] INFO (Flowers) Fire spread is UNRESTRICTED.
09.05 19:32:12 [Server] INFO Loaded configuration for world 'Flowers'
09.05 19:32:12 [Server] INFO (staff) TNT ignition is PERMITTED.
09.05 19:32:12 [Server] INFO (staff) Lighters are PERMITTED.
09.05 19:32:13 [Multicraft] Skipped 103 lines due to rate limit (30/s)
09.05 19:32:13 [Server] INFO [WARNING] Could not create a PluginDependencyProvider for: WorldGuard! (Are you sure the type is valid?) - Only WorldGuard 6.0 and after are supported
09.05 19:32:14 [Server] INFO Enabling EssentialsChat vTeamCity
09.05 19:32:14 [Server] INFO Enabling Factions v2.7.5
09.05 19:32:14 [Server] INFO === ENABLE START ===
09.05 19:32:15 [Server] INFO === ENABLE COMPLETE (Took 133ms) ===
09.05 19:32:15 [Server] INFO Enabling CombatLog v1.8.11
09.05 19:32:15 [Server] INFO Loading messages.properties.
09.05 19:32:15 [Server] INFO Loading config.yml.
09.05 19:32:15 [Server] INFO DisguiseCraft plugin not found! Disguise removal will not work.
09.05 19:32:15 [Server] INFO CombatLog v1.8.11 Enabled.
09.05 19:32:15 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
09.05 19:32:15 [Server] Startup Done (9.020s)! For help, type "help" or "?"
09.05 19:32:15 [Server] INFO Loading Cachefile datas...
09.05 19:32:15 [Server] INFO Loading Onlineplayer datas...
09.05 19:32:15 [Server] INFO Loading Registry datas...
09.05 19:32:15 [Server] INFO Loading Dbmojangapi datas...
09.05 19:32:15 [Server] INFO Player Strings Found: 0
09.05 19:32:15 [Server] INFO Player Strings Cached: 0
09.05 19:32:15 [Server] INFO Player Strings Remaining: 0
09.05 19:32:15 [Server] INFO Now fetching the remaining players from Mojang API ...
09.05 19:32:15 [Server] INFO ... done!
09.05 19:32:15 [Server] INFO Saving Cachefile...
09.05 19:32:15 [Server] INFO Upgrading from player name to player uuid...
09.05 19:32:15 [Server] INFO Pre update factions_mplayer.
09.05 19:32:15 [Server] INFO Post update factions_mplayer. Took 1ms. 0/15 changed.
09.05 19:32:15 [Server] INFO ... done!
09.05 19:32:15 [Server] INFO (database saving will now commence which might lock the server for a while)
09.05 19:32:15 [Server] INFO ** Vaults have already been converted to UUIDs. If this is incorrect, shutdown your server and rename the plugins/PlayerVaults/uuidvaults directory.
09.05 19:32:15 [Server] WARN The block breaking data is incomplete, default to allow instant breaking:
09.05 19:32:15 [Server] WARN --- Missing entries -------------------------------
09.05 19:32:15 [Server] WARN * MISSING 165(SLIME_BLOCK / SOLID+GROUND) 
	

Thank you in advance, also when i do /plugins, it says citizens is active yet nothing happens when i run the commands

**Comment by craftinFeathers** [comment]
well, I fixed it.. I had another plugin interfering with it which was an NPC plugin, so sorry for the wasted time, it was just disabled and i could not see it D;
thank you so much for the help.
