### ISSUE TITLE
Converter page Error 500

### ISSUE THREAD

**Issue by SentryTheDefiant** [CitizensDev/Citizens2#779]
Less of a problem with the plugin itself, and more-so a problem with deployment of the upgrade, due to the converter's unavailability.  This is also the only place I found to return feedback on issues of any kind. My apologies if this is not the best channel, but needed to bring this to someone's attention.

**Comment by fullwall** [comment]
Are you trying to convert Citizens1 to Citizens2?

**Comment by SentryTheDefiant** [comment]
Are you saying the converter is not necessary when moving your server from spigot 1.8 to 1.9? 
I suppose if that's the case, then I was confused, 

On the other hand, the converter page DOES return a 500 error regardless of what device/network I'm on, so for those who do need it, it is still a problem.

**Comment by mcmonkey4eva** [comment]
@SentryTheDefiant if you were running 1.8, you don't need the converter. Citizens 1.0 last updated to like minecraft 1.6 or so.

**Comment by fullwall** [comment]
The converter page is specifically for Citizens 1.0 and will error if it doesn't get things in a specific format.
