### ISSUE TITLE
NPC controllable hunts the player

### ISSUE THREAD

**Issue by Faksba** [CitizensDev/Citizens2#780]
Hey CitizensDev
I have a server which have used citizens for more than 3 years and have always been happy about it! i really love the pluing and i use the NPC's as transport for the players, they can buy a bat and then fly around.
But my problem is that i updateded my server for 1.9 and got the newest update for citizens, but when i use /npc control it kinda fucks up the npc and it starts flying after the player and keeps pushing to the player without and control, and the only way to stop it is to remove the NPC. I can create the npc as i want, but i cant make them controllable anymore.
Hope you can help me out with my problem :)
- Faksba

**Comment by fullwall** [comment]
Can't reproduce this. What build of Citizens?
