### ISSUE TITLE
NPCs have the player spawn algorithm applied to them

### ISSUE THREAD

**Issue by ghost** [CitizensDev/Citizens2#783]
It seems to occur that on server restarts or other random events, that some npcs that are close to a ceiling teleport on top of it/the highest solid block available above them. This is really annoying because the players aren't able to see and interact with them if they stand on the roofs of buildings or trees.

**Comment by mcmonkey4eva** [comment]
I've never seen this occur. That's... really odd...

**Comment by fullwall** [comment]
@mcmonkey4eva I think bukkit added an algorithm for this.

**Comment by Jalau11** [comment]
Sadly still a thing. Can it be fixed?

**Comment by fullwall** [comment]
Looking into this tomorrow.

**Comment by Jalau11** [comment]
Has the bug been fixed or found?

**Comment by fullwall** [comment]
@Jalau11 I looked into it... haven't found the cause yet beyond checks if a player is overlapping a block it may be pushed out of it.

**Comment by Jalau11** [comment]
Can it be reproduced on your end?

**Comment by Jalau11** [comment]
Just found more about the issue, seems like when the chunk is not loaded yet, I select the npc and tp to them, the npc will spawn like 500 blocks above ground and fall with me. This seems to be the cause for them to be on the upper block at their location all the time.

**Comment by fullwall** [comment]
@Jalau11 haven't been able to reproduce that behaviour... any plugins that may be causing the issue?

**Comment by Jalau11** [comment]
@fullwall Almost the whole server is running of a custom plugin. Anything that could cause this behaviour? Killing npcs? Despawning? I don't know where to look for in my plugin.

**Comment by mcmonkey4eva** [comment]
The github user who reported this was deleted, so... going to assume not a live issue
