### ISSUE TITLE
My server crash

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#784]
> Citizens : EventListen::onChunkUnload(ChunkUnloadEvent) => TPS 0.1

See thread for more infos:
https://www.spigotmc.org/threads/instant-crash-no-logs-timings.146589/

Can you help me ?
Thanks in advance

**Comment by mcmonkey4eva** [comment]
It looks like a player quit, which unloaded chunks, which had corrupt data, which borked your server.

Not likely to be related to Citizens.

**Comment by Blamo27** [comment]
Yes but, my server can crash in loop :/

**Comment by mcmonkey4eva** [comment]
...?

**Comment by Blamo27** [comment]
There are no errors in the logs, do you have an idea to fix that ?

**Comment by mcmonkey4eva** [comment]
`Not likely to be related to Citizens.`

**Comment by Blamo27** [comment]
Thanks anyway
