### ISSUE TITLE
1.9.4 from build server

### ISSUE THREAD

**Issue by AshourAziz** [CitizensDev/Citizens2#785]
I am receiving this error running spigot 1.9.4 with the latest citizens dev build.
http://pastebin.com/QycqQU16

The server then proceeds to crash.

**Comment by DoudouPike** [comment]
Same error on 1.9.2.

PS: If you've download spigot 1.9.4 on getspigot, it's not the 1.9.4 version. That's the same download's link of the 1.9.2 version. (sorry for my english)

**Comment by mcmonkey4eva** [comment]
@DoudouPike Please acquire spigot legally through the BuildTools system.

**Comment by fullwall** [comment]
Fixed
