### ISSUE TITLE
I'm getting this error message, I don't know why

### ISSUE THREAD

**Issue by NadeSwiiv** [CitizensDev/Citizens2#788]
12.05 18:48:57 [Server] INFO [CE] Checking for updates...
12.05 18:48:57 [Multicraft] Skipped 50 lines due to rate limit (30/s)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
12.05 18:48:47 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
12.05 18:48:47 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add
12.05 18:48:47 [Server] WARN at java.lang.Thread.run(Unknown Source)
12.05 18:48:47 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
12.05 18:48:47 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
12.05 18:48:47 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
12.05 18:48:47 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
12.05 18:48:47 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
12.05 18:48:47 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:118)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:222)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
12.05 18:48:47 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
12.05 18:48:47 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
12.05 18:48:47 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add
12.05 18:48:47 [Multicraft] Skipped 70 lines due to rate limit (30/s)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
12.05 18:48:46 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
12.05 18:48:46 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add
12.05 18:48:46 [Server] WARN at java.lang.Thread.run(Unknown Source)
12.05 18:48:46 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
12.05 18:48:46 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
12.05 18:48:46 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
12.05 18:48:46 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
12.05 18:48:46 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
12.05 18:48:46 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:118)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:222)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
12.05 18:48:46 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
12.05 18:48:46 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
12.05 18:48:46 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add
12.05 18:48:46 [Multicraft] Skipped 30 lines due to rate limit (30/s)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
12.05 18:48:45 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
12.05 18:48:45 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add
12.05 18:48:45 [Server] WARN at java.lang.Thread.run(Unknown Source)
12.05 18:48:45 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
12.05 18:48:45 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
12.05 18:48:45 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
12.05 18:48:45 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
12.05 18:48:45 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
12.05 18:48:45 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:118)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:222)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
12.05 18:48:45 [Server] WARN at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
12.05 18:48:45 [Server] WARN at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
12.05 18:48:45 [Server] WARN java.lang.Throwable: Unexpected NavigationListener add

**Comment by mcmonkey4eva** [comment]
Update http://wiki.citizensnpcs.co/Versions
