### ISSUE TITLE
Anyway to use two hands for npc?

### ISSUE THREAD

**Issue by FlashLight34** [CitizensDev/Citizens2#793]
trying to equip sword in left hand and shield in other hand bug i thing its impossible or i dont know how to do that i tryed /npc inventory et npc equip.

**Comment by mcmonkey4eva** [comment]
`/npc equip`
hold the item you want
`offhand` (just say it, in chat)

**Comment by FlashLight34** [comment]
ooooooh nice :)

**Comment by FlashLight34** [comment]
thx so much for your answer :)

**Comment by ScuroK** [comment]
@mcmonkey4eva how could we know things like this? are they in the wiki??
they dont appear on /npc help

**Comment by ScuroK** [comment]
could you add a message on /npc equip telling the users about this option?

**Comment by Silverstar** [comment]
Sorry for digging this out, but I searched this for a while now. I would also vote to insert that into the help text as well as in the wiki.
Thank you.

**Comment by HaterKevinKush** [comment]
does this not work anymore?

**Comment by mcmonkey4eva** [comment]
@HaterKevinKush still works.
