### ISSUE TITLE
Citizens isn't loading skins in spigot 1.8.8

### ISSUE THREAD

**Issue by Jaiiiii** [CitizensDev/Citizens2#794]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

This is a bug or something that i'm missing out.

There is no server issues on the console, so idk..
Current Plugins: http://prntscr.com/b4gojd
Running on the latest build for Citizens2

**Comment by mcmonkey4eva** [comment]
Latest version of Citizens doesn't work with old version of Spigot. Downdate your Citizens: http://wiki.citizensnpcs.co/Versions

**Comment by Jaiiiii** [comment]
to what version exactly?

**Comment by mcmonkey4eva** [comment]
The Citizens build on that link labeled '1.8.8'

**Comment by fullwall** [comment]
@mcmonkey seems more of a duplicate issue...

**Comment by ESFS** [comment]
[14:49:00] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1267)
[14:49:00] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.
kernel version 1.8.8 Spigot

**Comment by fullwall** [comment]
@ESFS what system language is your server set to?

**Comment by ESFS** [comment]
[15:06:07] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1308)
[15:06:07] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.
kernel version 1.8.8 Spigot

**Comment by ESFS** [comment]
How to understand the language? In general, Russian

**Comment by ESFS** [comment]
What then swing version that there were no errors and citizens created

**Comment by ESFS** [comment]
What to write here ?
```
 translation:
    locale: '?'
```
en?

**Comment by ESFS** [comment]
After komnady / npc create ... Drops an error related to Sky Wars O_o ???
Log https://yadi.sk/i/GO_GITyhrokzh

**Comment by fullwall** [comment]
locale: 'en'

**Comment by ESFS** [comment]
[16:01:22] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1267)
[16:01:22] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.

**Comment by fullwall** [comment]
Can you list the contents of the plugins/Citizens/lang folder?

**Comment by ESFS** [comment]
https://yadi.sk/d/qTnKFRlsrtQYH

**Comment by fullwall** [comment]
This 'error' shouldn't cause any issues.

**Comment by ESFS** [comment]
No problem. But there is an error and it excites .
