### ISSUE TITLE
NPC's disappearing after restart.

### ISSUE THREAD

**Issue by LoXR** [CitizensDev/Citizens2#795]
Basically after my server is restarted all the NPC's at spawn disappear. And by fixing this I would need to simply reload the plugin for them to reappear again.

**Comment by fullwall** [comment]
Payer NPCs? Citizens version? Spigot version?

**Comment by LoXR** [comment]
Yeah the npcs you create with the command, Citizens Version: 2.0.16, spigot version: 1.8.8

**Comment by fullwall** [comment]
Plugin list?

**Comment by LoXR** [comment]
Plugins (83): AdvancedList, FactionsFly, GroupManager, PerWorldPlugins, PlugMan, CloudChest, Pl3xMOTD, BetterChairs, NoPl, NametagEdit, AdvancedLogger, SkinsRestorer, BossBarAPI, DeathMessages, ViaVersion, ShutdownNotice, LiveTweak, CoreProtect, TTA, AsyncWorldEditInjector, AntiBotDeluxe, Installer, AntiAdvertiser, ItemKills, RoboticStaff, BringBackTheEnd, EntityWatch, Interactables, Votifier, ActionHealth, ActionBarAPI, LaggRemover, ProtocolLib, AntiWDL, LibsDisguises, BanVote, AsyncWorldEdit, RealChop, mcMMO, GAListener, Vault, ObsidianAuctions, LWC, QuickShop, ChestCommands, ArchonCrates, EZRanksPro, InfernalMobs, WorldEdit, PortalCommands, Essentials, mcMMOAction, CTSNC, Citizens, React, EssentialsChat, EnjinMinecraftPlugin, PlotSquared, CarlTheCreeper, WorldGuard, CrateKeys, EssentialsProtect, CommandNPC, EssentialsSpawn, CompatNoCheatPlus, Multiverse-Core, NoCheatPlus, AuthMe, HolographicDisplays, Factions, Multiverse-Inventories, FactionUUIDLogout, AreaShop, MultiWorldMoney, FBasics, FactionScoreboard, RandomTP, LiteBans, CommandSigns, SilkSpawners, RPGHealthPlus, CombatTagPlus, FactionWars-FactionsUUID

**Comment by fullwall** [comment]
Can you try disabling AuthMe?

**Comment by LoXR** [comment]
Well it seems to be the problem. Would AuthMe have to fix this?

**Comment by fullwall** [comment]
Yes, please report it to them. Someone else has reported setting this HideTablistBeforeLogin: false in the settings can fix this issue.
