### ISSUE TITLE
[Bug] Changing player skin and setting skin on NPC uses player's old skin

### ISSUE THREAD

**Issue by SundialMC** [CitizensDev/Citizens2#797]
<BUG REPORT>

- Minecraft 1.9.0 / Citizens Build 1362

Let's say my player name is "Bob." Bob has a **pigman** skin. Bob makes a new **"NPC A"**, and uses the command _"/npc skin Bob -p"_ to set **NPC A**'s skin to a **pigman**, making sure it will stay a **pigman** even if Bob changes his own skin later on. Bob makes a new **"NPC B"** and wants it to have a **dragon** skin. Bob changes his own skin to a **dragon**, and uses _"/npc skin Bob -p"_ again to set NPC B's skin to a **dragon**. But - no matter how many times he tries, **NPC B** keeps getting the **pigman** skin.

Bob tries to create new npcs using _"/npc create Bob"_, but they all have the **pigman** skin, even if he himself has a **dragon** skin.

I'd like to create multiple NPCs with different skins, but this doesn't allow me to.

**Comment by mcmonkey4eva** [comment]
@fullwall perhaps a command flag to ignore the skin cache (redownload the skin from Mojang for the current NPC's new skin) could be of use here... or something like that...

**Comment by fullwall** [comment]
Try latest build

**Comment by SundialMC** [comment]
Seems like it's fixed, but I've first got to change the NPC's skin to something else using another player's skin i.e. /npc skin randomname -p

then change it back to what I want (/npc skin bob -p)

but it's all good now, thanks for the fix.
