### ISSUE TITLE
Plotsquared error with citizens

### ISSUE THREAD

**Issue by Ac3dUd3** [CitizensDev/Citizens2#798]
Bug
 Im on 22.05 01:12:09 [Server] INFO This server is running CraftBukkit version git-Spigot-1480adb-6247aa0 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)
citizens ver 22.05 01:12:52 [Server] INFO Citizens version 2.0.17-SNAPSHOT (build 1316)
my error 
http://hastebin.com/akemazihid.avrasm
http://hastebin.com/ovahovenox.avrasm

**Comment by mcmonkey4eva** [comment]
update Citizens to the final 1.9.2 release http://wiki.citizensnpcs.co/Versions

**Comment by Ac3dUd3** [comment]
thank you :)
