### ISSUE TITLE
Very high Pct Tick 3,563.72%: Task: Citizens$2(Single)

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#80]
Latest Citizens2 dev build is causing lag:

3,563.72%     1.78 s     1,781.86 ms     0.0           0.0k     Task: Citizens$2(Single)

See my timings here:
http://timings.aikar.co/?url=8460111

**Comment by bambole** [comment]
ive got the same problem with latest citizens dev, latest spigot 1.8, latest sentry and quester 0.6.x.
15,092.21%
http://timings.aikar.co/?url=9672575

**Comment by mcmonkey4eva** [comment]
That's probably just an autosave. Pct Total is what matters, not Pct Tick.
