### ISSUE TITLE
Crash with ocelot sounds

### ISSUE THREAD

**Issue by FlyingPikachu** [CitizensDev/Citizens2#800]
[19:54:55] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-4af49dc-4e19de1 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

[19:54:58] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.18-SNAPSHOT (build 1367)

http://pastie.org/private/56nx19byleyfbpa8siiwa

**Comment by fullwall** [comment]
Have you ever used the /npc sound command on your ocelots?

**Comment by FlyingPikachu** [comment]
@fullwall Yes, here's the one and only ocelot from saves.yml - http://pastebin.com/XsHYB2MJ

**Comment by fullwall** [comment]
You should delete that sound - I will also fix the code later.

**Comment by FlyingPikachu** [comment]
I have disabled the plugin for now. Not sure if this is related, but "type: Ozelot" is misspelled. Is that intentional? Happy to trying editing that line and re-running the plugin if not.

**Comment by fullwall** [comment]
no, it is misspelled in Mojang's code

**Comment by FlyingPikachu** [comment]
@fullwall Updated to build 1371. There is now a new issue, which I assume is related because it occurred right as I loaded the chunk containing the Ocelot NPC. There are no Magma Cube NPCs present and it is not a Nether world. Loading the same chunks without the plugin does not cause a crash.

Error - http://pastebin.com/360913FH

**Comment by fullwall** [comment]
@FlyingPikachu - working on this for 1.10

**Comment by fullwall** [comment]
@FlyingPikachu done.

**Comment by FlyingPikachu** [comment]
@fullwall Is build 1375 supposed to break compatibility with older versions? I'll be upgrading soon regardless.

[10:45:13] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.19-SNAPSHOT (build 1375)
[10:45:13] [Server thread/ERROR]: [Citizens] v2.0.19-SNAPSHOT (build 1375) is not compatible with Minecraft v1_9_R2 - try upgrading or downgrading Citizens. Disabling.
[10:45:13] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.19-SNAPSHOT (build 1375)

**Comment by fullwall** [comment]
Yes - all minecraft updates break compatibility with previous builds currently. It is possible to circumvent this but it has not been done as yet.

**Comment by FlyingPikachu** [comment]
Alright, I'll report back once we've updated. Thanks!

**Comment by FlyingPikachu** [comment]
@fullwall Cannot test, guess Sentry needs updating? http://pastebin.com/vrn3sm2k

**Comment by mcmonkey4eva** [comment]
@FlyingPikachu Sentry will not be updated to 1.10/higher. Instead, use Sentinel: https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md
It includes an importer for Sentry data on its 1.9.4 release if you wish to recover data from 1.9.4 Sentry.

**Comment by FlyingPikachu** [comment]
@mcmonkey4eva Thank you! Just to clarify, I would need to run Sentinel on a 1.9.4 server for it to convert? Can't be done on 1.10?

**Comment by mcmonkey4eva** [comment]
@FlyingPikachu You can't open Sentry on 1.10, so you can't run the import. You have to run 1.9.4 during the import (Which should, in theory, be as easy as just not updating or restoring to backup from before the incomplete update) and only then doing the full update.

**Comment by FlyingPikachu** [comment]
@mcmonkey4eva Understood. I went ahead and ran the appropriate Citizens, Sentry and Sentinel builds on a 1.9.4 server with the same configuration, and ran into a dilemna.

As I mentioned to @fullwall a few comments back (right after the Close), there is a Magma Cube bug on 1.9.4 which crashes the server. Running everything correctly on 1.9.4 results in the server closing _immediately_ after startup due to this bug. http://pastebin.com/sGDm0aeC

So, it appears impossible for me update. 1.9.4 crashes because of that bug and 1.10 is incompatible with Sentry :(

**Comment by mcmonkey4eva** [comment]
eh... delete the magma cube temporarily from your saves.yml?

**Comment by FlyingPikachu** [comment]
@mcmonkey4eva Genius. Done, working on this error at the moment http://pastebin.com/5LtfnKpS

**Comment by mcmonkey4eva** [comment]
@FlyingPikachu download an older (1.9.4) build of Sentinel to fix that. You have the 1.10 version which expects polar bears to be a valid entity.

**Comment by FlyingPikachu** [comment]
@mcmonkey4eva Duh, my bad. With that, the conversion worked perfectly. Added the cube back and everything's going great. Thanks a million!
