### ISSUE TITLE
Citizens2 not loading

### ISSUE THREAD

**Issue by Pr0totype2** [CitizensDev/Citizens2#802]
Ehm, Citizens2 simply doesn't want to load:
http://hastebin.com/yulubijihe.vbs

**Comment by Pr0totype2** [comment]
Counts for Shopkeepers aswell:
http://hastebin.com/ahiyodagoq.avrasm

The 2 are messing around with each other, I noticed.

**Comment by mcmonkey4eva** [comment]
```
23.05 11:40:34 [Server] ERROR [Citizens] v2.0.18-SNAPSHOT (build 1369) is not compatible with Minecraft v1_9_R1 - try upgrading or downgrading Citizens. Disabling.
```
It's not /that/ hard to read that error message is it? You have Citizens for 1.9.4 on your 1.9 or 1.9.2 server. Downdate Citizens. http://wiki.citizensnpcs.co/Versions

**Comment by Pr0totype2** [comment]
I've tried 4 different versions fyi ;P
But thanks, this helped me ^-^
