### ISSUE TITLE
Armorstands / NPC's dissapearing until /citizens reload

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#803]
Sometimes the armorstands and NPC's, both from Citizens2. are vanishing.

For a referance: http://prntscr.com/b7haw9

These npc's were vanished until I used /citizens reload

Plugins:

23.05 17:45:42 [Server] INFO Plugins (49): BlockParticles, PlaceholderAPI, PlugMan, SuperTrails, FlashLight, DeathMessages, CratesPlus, CoreProtect, AsyncWorldEditInjector, dynmap, VoteRoulette, AnimatedNames, ChatControl, WorldBorder, Votifier, ProtocolLib, AdvancedPortals, AsyncWorldEdit, PermissionsEx, mcMMO, MoneyMobs, HolographicDisplays, WorldEdit, React, MobArena, LWC, WorldGuard, ArmorStandEditor, PetBlocks, ScratchCards, CustomNoteBlock, Vault, BattlePets, ZHorse, AuctionHouse, BuyHead, MyCommand, Essentials, Stickers, LiteBans, Citizens, CustomGUI, EnjinMinecraftPlugin, EssentialsGeoIP, CommandNPC, EssentialsSpawn, PremiumVanish, CompatNoCheatPlus, NoCheatPlus

Spigot version:

1.9.4

Citizens version:

2.0.18-SNAPSHOT build 1367

**Comment by Sikatsu** [comment]
Any news regarding this issue? @mcmonkey4eva 

I know /citizens reload is simple to do, but it's quite annoying if theres no staff online.

**Comment by LoXR** [comment]
Yes! I have this problem so much aswell. I'm using the addon plugin CarlTheCreeper for player rewards, and I'm having to do /citizens reload everytime after a certain time to get him back.

**Comment by fullwall** [comment]
Working on it

**Comment by Sikatsu** [comment]
I can't imagine which it might be, I don't have any special plugins or so. I removed PetBlocks and NoCheatPlus is replaced with AAC in the meanwhile.

**Comment by fullwall** [comment]
Can you try and get some debug-mode: true output when this happens?

**Comment by Sikatsu** [comment]
That's very hard to do so.

Will that spam me or the console?

Most of the times I get a discord message saying ''the shops are gone again..''

**Comment by fullwall** [comment]
It will give a little bit of spam to the console... I can add a setting to write it to a file or something.

**Comment by Sikatsu** [comment]
That would be awesome. Then I can just turn it on, and as soon as I see that the npc's are gone I sent you the file. However, even then, I'm not sure if I can give you a close time.

**Comment by fullwall** [comment]
I added a new setting in the latest build.

**Comment by Sikatsu** [comment]
Perfect, as soon as they dissapear I'll send you the file!

**Comment by LoXR** [comment]
Hmmm for me personally, i'm running Spigot 1.8.8. So I dont think I can run this for myself.

**Comment by Sikatsu** [comment]
When I have debug-mode: true it spams the console, how to get it so it will write to the log?

**Comment by mcmonkey4eva** [comment]
Set the new config option `general.debug-file` to a valid file name to send debug logs to.

**Comment by Sikatsu** [comment]
I tried this: http://prntscr.com/bdcy7c with and without the "

And also log.txt, but that doesn't seem to work.

**Comment by Sikatsu** [comment]
They still keep dissapearing but I don't get the debug to work..

**Comment by fullwall** [comment]
Try setting it to plugins/Citizens/log.txt

**Comment by Sikatsu** [comment]
Thanks, works now. When it dissapears again I'll send you the file.

**Comment by Sikatsu** [comment]
It's really hard because they always dissapear when i'm not online. However, a player just messaged me on skype that the shop villagers are gone again. So heres the file, the villagers for sure dissapeared within this log file. but it might be very large. Hope it helps :/

I noticed I forgot to mention which NPC's I actually mean.
So far, I noticed it occurs on ''Armorstands'' and ''Villagers''. When those dissapear, the normal player NPC's are always still there. Worth mentioning, I don't have any plugin removing entities like armorstands or villagers.

No npc's: http://prntscr.com/beni49

No villagers: http://prntscr.com/bengvc

There are, however, the player npc's: http://prntscr.com/beni8z

Log.txt: https://www.dropbox.com/s/j0h78kjzaj6gy8j/log.txt?dl=0

@fullwall

**Comment by mcmonkey4eva** [comment]
It looks like at timestamp `2016-06-10 05:00:00 ` everything got reloaded. Could be related?

**Comment by Sikatsu** [comment]
Thats because the server gets restarted at midnight. However, the npc's dissapear during the day.

**Comment by fullwall** [comment]
What IDs are the NPCs who disappeared?

**Comment by Sikatsu** [comment]
When using /npc select <ID> and teleporting to that ID, it teleports me to the NPC"s which are dissapeared. So it seems, most, if not all ID's from the log are dissapearing.

I only restart my server at midnight, and I use /citizens reload everytime the NPC's are dissapeared.

**Comment by fullwall** [comment]
The log is cut off a bit that's all. Are any of the NPCs in that log disappearing?

**Comment by Sikatsu** [comment]
Cut off? It's the full llog I downloaded from the folder o.O

As said earlier, yes those npc's are dissapearing. (Well 666 is not)

As far as I know, these are the dissapearing ID's:

401
445
510
511
512
514
516
525
627
634
638
639
640
641
642
643
660

**Comment by fullwall** [comment]
I have made an update based on that info: can you please test the latest build? Also it'd be nice to get a fresh log as well.

**Comment by Sikatsu** [comment]
I will test the latest build. It works on both 1.9 and 1.10?

**Comment by fullwall** [comment]
No... just 1.10 unfortunately

**Comment by Sikatsu** [comment]
In that case I can't test until i'm running 1.10 (Monday or Tuesday)

Will mention you here when tested then. ^^

**Comment by Sikatsu** [comment]
@fullwall 

Alright, just tested it.

It seems to work with villager npc's, but not with armorstand npc's.

ID's:
638
639
640
641
642
643

If for some reason the villager npc's also start dissapearing again, I'll inform you.

Clean log on 1.10:
https://www.dropbox.com/s/zyf1osavmq09h92/log.txt?dl=0

**Comment by Sikatsu** [comment]
Turns out the villagers are gone now too.

**Comment by fullwall** [comment]
@Sikatsu ok

**Comment by Sikatsu** [comment]
@fullwall 

I really wonder what is causing this problem.

I also have a plugin which spawns an villager NPC, without the use of Citizens. This villager never dissapears.

**Comment by fullwall** [comment]
@Sikatsu - all I can do is try to get more debug log to narrow it down. https://dl.dropboxusercontent.com/u/6701575/citizens.jar this adds some more finegrained debugging info

**Comment by Sikatsu** [comment]
@fullwall Will test and give you a clean log.

**Comment by Sikatsu** [comment]
Is it normal that the file now recalls himself to log.txt.1 and log.txt.2?

**Comment by fullwall** [comment]
@Sikatsu yes I noticed that myself... haven't changed anything so it must be the way it works.

**Comment by Sikatsu** [comment]
@fullwall 

Alright, 2 new fresh logs. I attach them both to be sure you have the logs where they did dissapear.

https://www.dropbox.com/s/wqllqi2m1m6dcuc/Citizens.rar?dl=0

**Comment by fullwall** [comment]
@Sikatsu sorry, still no luck... try this https://dl.dropboxusercontent.com/u/6701575/citizens.jar

**Comment by Sikatsu** [comment]
@fullwall I will :)

**Comment by Sikatsu** [comment]
Sorry for the delay, 2 new fresh logs: https://www.dropbox.com/s/wqllqi2m1m6dcuc/Citizens.rar?dl=0

**Comment by fullwall** [comment]
@Sikatsu https://dl.dropboxusercontent.com/u/6701575/citizens.jar this one should give us some answers... sorry for the number of builds

**Comment by Sikatsu** [comment]
I guess plugman isn't supported so I have to wait till tonight before I can add that jar, will give you some fresh logs later tonight or tomorrow

**Comment by Sikatsu** [comment]
Didn't had much time yesterday.

New logs: https://www.dropbox.com/s/wqllqi2m1m6dcuc/Citizens.rar?dl=0

**Comment by fullwall** [comment]
Another build sorry... seems to be related to keep-chunks-loaded at this stage https://dl.dropboxusercontent.com/u/6701575/citizens.jar

**Comment by Sikatsu** [comment]
It's really hard as I can't restart in the middle of the day, to many players. Will do tonight and get you a freshlog around that time.

**Comment by fullwall** [comment]
No worries on timing

**Comment by Sikatsu** [comment]
Yesterday around 23:00 I restarted the server to update the Citizens jar, so between then and now they did dissapear.

https://www.dropbox.com/s/grcsxyjuyggspmx/log.rar?dl=0

**Comment by fullwall** [comment]
All the problematic NPCs are in the same chunk as 646 yes?

**Comment by Sikatsu** [comment]
No not really, 646 doesn't dissapear because it's a player NPC.

Around the same chunk with ID 643 and the chunk with ID 525.

**Comment by fullwall** [comment]
The NPC types disappearing are villager and armorstand?

**Comment by Sikatsu** [comment]
Yes

**Comment by vizv** [comment]
For those who use spigot, could you try setting `entity-tracking-range.players` to a higher value (e.g. `64`) in `spigot.yml`? It might help to fix the issue.

**Comment by Sikatsu** [comment]
Seems the issue is fixed, it indeed was a plugin conflict. Didn't see them dissapear in the last couple of days.

**Comment by fullwall** [comment]
@Sikatsu - which plugin?

**Comment by Sikatsu** [comment]
@fullwall React made a Citizens compatibility update, since then it seems stable.

**Comment by fullwall** [comment]
OK, marking this as closed.
