### ISSUE TITLE
NPCRightClickEvent firing twice

### ISSUE THREAD

**Issue by razorrider7** [CitizensDev/Citizens2#804]
I am using the latest citizens snapshot (2.0.18) and have even tried the 2.0.17 version, but the event NPCRightClickEvent fires twice. I believe this to have something to do with the ability to use both hands (right hand makes the event trigger once, then the left hand).

http://pastie.org/private/m3viu4pct4m4n64n2bcyw#

Note: It happens even with an item only in one hand.

EDIT: nevermind... seems that has already been fixed... I don't know what's wrong...

**Comment by fullwall** [comment]
Looks like you are listening for left, right and also NPCClickEvent - you should just not listen for NPCClickEvent as that will fire it twice

**Comment by razorrider7** [comment]
That isn't it... The NPCClickEvent only fires if the click type is both, however the NPCRightClickEvent is fired if it is set to right. Because it is set to right, only the NPCRightClickEvent will be used. The full source is available at https://github.com/razorrider7/CommandNPC as I have been updating the plugin

**Comment by razorrider7** [comment]
Ok, so I have updated spigot and Citizens2 to 1.9.4 and now only the right click is firing...
