### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Bodyash** [CitizensDev/Citizens2#805]
Spigot 194 + latest Jenkins build of citizens
[crash-2016-05-04_03.41.47-server.txt](https://github.com/CitizensDev/Citizens2/files/286537/crash-2016-05-04_03.41.47-server.txt)

**Comment by razorrider7** [comment]
Could you include the server log too?

PS: Double check your spigot version... your crash report says 1.9.2 and I'm not sure if that is different than the 1.9.4 spigot build:
`Running: CraftBukkit version git-Spigot-e6f93f4-ed60c01 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT) false`

**Comment by fullwall** [comment]
Citizens v2.0.17-SNAPSHOT (build 1360) - you are using the wrong version of Citizens

**Comment by Bodyash** [comment]
i`m using 1.9.4
Its looks like bug is fixed, but i didnt changed anythig o_O Only updated NoCheatPlus
