### ISSUE TITLE
No 1.7 versions are working for me

### ISSUE THREAD

**Issue by Shane1199** [CitizensDev/Citizens2#808]
I have Minecraft 1.7.10 with Cauldron running Pixelmon 3.5.1. We can't get any of the released versions for 1.7 to work on the server. Previously we used to have another 1.7.10 and we used a Snapshot version, but I am not aware which Snapshot that was. Can you please help? Thanks!

**Comment by mcmonkey4eva** [comment]
https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar
