### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

### ISSUE THREAD

**Issue by DevIPv2** [CitizensDev/Citizens2#810]
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet when i type /npc create Test it says java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet see in console heres logs.
05.06 14:23:17 [Server] INFO IPv2 issued server command: /npc create t
05.06 14:23:17 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
05.06 14:23:17 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
05.06 14:23:17 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.06 14:23:17 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05.06 14:23:17 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05.06 14:23:17 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
05.06 14:23:17 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
05.06 14:23:17 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
05.06 14:23:17 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
05.06 14:23:17 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
05.06 14:23:17 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
05.06 14:23:17 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:672)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628)
05.06 14:23:17 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536)
05.06 14:23:17 [Server] WARN at java.lang.Thread.run(Thread.java:745)
05.06 14:23:17 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
05.06 14:23:17 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
05.06 14:23:17 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
05.06 14:23:17 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
05.06 14:23:17 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
05.06 14:23:17 [Server] WARN ... 28 more
05.06 14:23:25 [Server] INFO CONSOLE issued server command: /list 
05.06 14:23:25 [Server] INFO Developer: [Developer]IPv2
05.06 14:23:26 [Server] ERROR Could not pass event EntityCombustEvent to Citizens v2.0.14-SNAPSHOT (build 1195)
05.06 14:23:26 [Server] INFO org.bukkit.event.EventException

**Comment by mcmonkey4eva** [comment]
You're running 1.8.8 but have the 1.8(.0) version of Citizens.
You can update from http://wiki.citizensnpcs.co/Versions
