### ISSUE TITLE
NPC doesnt speak

### ISSUE THREAD

**Issue by magnus505** [CitizensDev/Citizens2#811]
Hello I'm trying to make a npc to speak with players. but i can't make it work help please
Minecraft Verison 1.9.

plugins verison unknowned

**Comment by mcmonkey4eva** [comment]
... huh?

**Comment by fullwall** [comment]
Are you using /npc speak or denizen? Can you post a server log please?

**Comment by ElementalRealm** [comment]
If you are using "/npc text" when you get on the text editor type "close" to start talking
