### ISSUE TITLE
1​37​0 - massive lag issues

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#813]
Updated Citizens to latest dev build and now it is lagging like hell. See timings:
https://timings.spigotmc.org/?url=17068369

Spigot 1.9.4
Citizens dev build:` #1​37​0`

**Comment by fullwall** [comment]
How many player NPCs do you have? What are they doing?

**Comment by bloggy** [comment]
318 NPCs. Most of  them doing nothing. about 5 wandering around.

**Comment by fullwall** [comment]
Any chance you could use https://github.com/sk89q/WarmRoast and get a screenshot of the output?

**Comment by fullwall** [comment]
Should be a little better in the latest build - the potion effects were being sent too often.

**Comment by fullwall** [comment]
Merging this into #801
