### ISSUE TITLE
[BUG] Moving NPC's

### ISSUE THREAD

**Issue by ToXiCHaZe541** [CitizensDev/Citizens2#814]
So I have just discovered that NPC's can be pulled around spawn by fishing rods. Could you possibly fix this?

**Comment by mcmonkey4eva** [comment]
What version are you running?

**Comment by TagCraftMC** [comment]
I am able to replicate the issue on build 1369 running 1.9.4 Spigot.

https://www.youtube.com/watch?v=8frrYDL1D4w&feature=youtu.be

**Comment by fullwall** [comment]
Fixed in 1.10.
