### ISSUE TITLE
Dissapearing

### ISSUE THREAD

**Issue by Liturkey** [CitizensDev/Citizens2#816]
Hello! I have a problem on server. Whenever connects to server, he doesn't see NPCs. It's happening in new 1.9 version.

Server Log: http://pastebin.com/d1ftapfq
Citizens Config: http://pastebin.com/BGtcxqM2

Minecraft 1.9, Citizens 2.0.17

**Comment by mcmonkey4eva** [comment]
Grab the relevant Citizens version at http://wiki.citizensnpcs.co/Versions

**Comment by Liturkey** [comment]
Not working still same... :)

**Comment by DNx5** [comment]
#803

**Comment by mcmonkey4eva** [comment]
@Liturkey updated error log?

The error log you gave is from having the wrong version Citizens (or a way old Spigot build)

**Comment by Liturkey** [comment]
I actually figured it out. I completly reinstalled Citizens and it worked! Thank you guys :)
