### ISSUE TITLE
[BUG] /citizens save leads to NullPointerException

### ISSUE THREAD

**Issue by PsychoLynx** [CitizensDev/Citizens2#818]
Using Citizens B1371 on Spigot 1.9.4. I noticed my NPC changes are not being saved anymore:

http://pastebin.com/E4bMXwYi

**Comment by mcmonkey4eva** [comment]
Do you perhaps have a strange / invalid item in the inventory of one of your NPCs?

particularly a banner.

That exception appears to be on this line:
```
            root.setString("basecolor", banner.getBaseColor().name());
```

**Comment by PsychoLynx** [comment]
Well, what do you know! That's what it was. I changed the banner one of the bannermen was wearing to a new one I summoned via command block, namely this:

/give @p minecraft:banner 1 0 {BlockEntityTag:{Base:1,Patterns:[{Pattern:flo,Color:0},{Pattern:mr,Color:0},{Pattern:mc,Color:1},{Pattern:sc,Color:0},{Pattern:bs,Color:1},{Pattern:ts,Color:1},{Pattern:flo,Color:0},{Pattern:tts,Color:0},{Pattern:gra,Color:0}]}}

I dunno why it shouldn't work, but I guess I'll stick to more vanilla banners for now.

**Comment by fullwall** [comment]
Seems like the base color should be included somewhere? I thought it was mandatory.

**Comment by mcmonkey4eva** [comment]
I recall this being fixed at some point  but I'm not at all sure offhand

**Comment by mcmonkey4eva** [comment]
Yes it was (CitizensAPI -> ItemStorage -> serializeBanner)
