### ISSUE TITLE
Wither Lifebar Colour

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#819]
**Infos:**
Serverversion: Spigot 1.9.4
Citizens-version: 2.0.18 SNAPSHOT

What happens:
I createt a Wither-NPC with a colored Name. But the Name in the Lifebar on top of the Screen is still "Wither" without any Colors.

And I maybe have a suggestion:
Is it possible to add a command, with that you can change the Color of the Lifebar of the NPC, if its a Enderdragon or Wither (For example: **/npc colorlifebar (color)**)

**Comment by fullwall** [comment]
I will look into whether this is possible.

**Comment by fullwall** [comment]
It is possible... looking into developing it tomorrow.

**Comment by fullwall** [comment]
Added this for 1.10 version - /npc bossbar --color red for example.
