### ISSUE TITLE
BungeeTabListPlus(+)Citizens2 - Still not possible.

### ISSUE THREAD

**Issue by Funreal** [CitizensDev/Citizens2#821]
Donated 10 USD for this plugin but there has only been problems...

Here's a screenshot of the error:
https://i.gyazo.com/66ba208591569051347c3f324bf9e16b.png
- Paperspigot version 1.9.4. Latest version of Citizens.

**Comment by GomaTerzu** [comment]
Latest Version of Citizens is for Minecraft 1.10 already. This is the last build for Minecraft 1.9.4

http://ci.citizensnpcs.co/job/Citizens2/1371/

**Comment by Funreal** [comment]
That version worked for me.
But now there's a problem with my BungeeTablistPlus.

Screenshot: https://i.gyazo.com/e5acf2b81823c585779952beeadc5b16.png

**Comment by fullwall** [comment]
Disable player-scoreboard-teams

**Comment by Funreal** [comment]
That did not fix my issue at all.

**Comment by fullwall** [comment]
Can you please pastie your config?

**Comment by Funreal** [comment]
`# Citizens Configuration

npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  default:
    look-close:
      enabled: false
      range: 5
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  teleport-delay: -1
  controllable:
    use-boat-controls: true
  player-scoreboard-teams:
    enable: false
advanced:
  check-minecraft-version: true
general:
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
`

**Comment by Funreal** [comment]
Sometimes when someone joins it gets fixed for some seconds.

**Comment by Funreal** [comment]
There doesn't seem to be any fix to this... moving on to the text plugin..

**Comment by mcmonkey4eva** [comment]
@Funreal have some patience yo, it sometimes takes a few days to get issues sorted, not so many minutes.

**Comment by Funreal** [comment]
Well as the next man I would appreciate a response. Should I begin looking for a new plugin or should I bother waiting a few days for a fix?

**Comment by mcmonkey4eva** [comment]
I can guarantee you, you will not find an NPC plugin that doesn't have tablist oddities anywhere.
If you stick around, a way will be found to make it all work out as soon as reasonably possible.

**Comment by Funreal** [comment]
Well, if I look at another server they have no issues at all with tablist using a NPC plugin.
Why's that?

**Comment by mcmonkey4eva** [comment]
Because the problem you're encountering is an issue with your specific setup, not a definitive flaw in the plugin itself.

**Comment by Funreal** [comment]
Actually it is. My tablist would be fine without the plugin itself.

**Comment by mcmonkey4eva** [comment]
@Funreal Childish misinterpretations will not get you closer to a fix that allows you to use NPCs non-disruptively on your server under your current setup. Please simply remain patient for further investigation.

**Comment by fullwall** [comment]
Try newest build

**Comment by Funreal** [comment]
That last build of Citizens2 doesn't work at all alongside Paperspigot build 773 (MC: 1.9.4)
Commands will not respond & I get exact same error in console. (See post 1)

**Comment by fullwall** [comment]
@Funreal it's for 1.10 only

**Comment by Funreal** [comment]
Okay. But I would like a fix for the current Citizens2 build I am using. http://ci.citizensnpcs.co/job/Citizens2/1371/

**Comment by Funreal** [comment]
We'll update to 1.10 on Friday. Don't bother fixing it, if not anyone else have the same issue but not very likely I guess.

**Comment by Funreal** [comment]
Still not working alongside BungeeTabListPlus in 1.10.

**Comment by mcmonkey4eva** [comment]
I think the eventual determination on this problem (via other discussions) is that `BungeeTabListPlus` is at fault for damaging the tablist and we don't have any way to fix it on our end here
