### ISSUE TITLE
NPC setTarget causes Server Crash

### ISSUE THREAD

**Issue by ItzMace** [CitizensDev/Citizens2#823]
**[] ISSUE []**
**Server Info:**
Minecraft Version: Minecraft 1.9.4
Spigot Version: "This server is running CraftBukkit version git-Spigot-4af49dc-23da8b0 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)"
Citizens Version (/citizens): Citizens v2.0.18-SNAPSHOT (build 1371)

Hello guys!
I've a problem with citizens.
I use this code to spawn a NPC and let it walk to a specific location;
http://pastie.org/private/4yol2txvmukr4gjqwswdma

In ~9/10 times I execute this code, all players are kicked from my server with text: "timed out".
In the other time, I got this crash report: http://pastie.org/private/sesk3vvski4s6fahfs8w

The last line in chat I could see is executed by this:
Bukkit.broadcastMessage("TARGET: " + target.getLocation());
So I guess that the error is caused by this line: **npc.getNavigator().setTarget(target.getLocation());**

**Comment by degobyan** [comment]
Did you spawn the NPC?  Creating only registers the entity on the backend.  Doesn't spawn unless you do npc.spawn(location).  I believe you have to spawn it before getting it's navigator.

**Comment by ItzMace** [comment]
Thank you for your answer!
I tested it out but I still get the same problem :(
Here is the current state of my plugin: http://pastie.org/private/xjgpun852mc9shexlokog
I splitted the whole code into two methods  as you can see.

**Comment by degobyan** [comment]
Hmm.. not sure then, though the things that still stand out to me are that an NPC can probably immediately despawn if in the right conditions.  A check if(npc.isSpawned) before getting the navigator would say for sure.

Also your variable "target" is a location... but then you get a location from the location (target.getLocation()).  I don't see that method in the spigot docs but i guess it works for you?  Best of luck if it's neither of those things!

**Comment by fullwall** [comment]
From your crash report it looks like you have a bad chunk that is causing Minecraft to freeze when loaded by the navigation.

**Comment by ItzMace** [comment]
Hm.. well. Now I don't get any error or something else, I just get kicked from the server with reason: "Timed out".
I now tested this plugin: http://pastie.org/private/q6e7kbdtwxgbfan1bql9xq
And still the same result.. Here are all server information required+updated:
**Spigot Server**: This server is running CraftBukkit version git-Spigot-4af49dc-23da8b0 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
**Citizens**: Citizens v2.0.18-SNAPSHOT (build 1371)
-> Original Filename: **citizens-2.0.18-SNAPSHOT.jar** (NOT citizensapi-2.0.18-SNAPSHOT.jar!!)
**Server Information**:
 **Start Script**: java -Xmx10G -Xms7G -jar spigot.jar nogui
 **Citizens Config**: http://pastie.org/private/tioyelejodte8arastv8fa
 **List of Plugins on TestServer**: Citizens, TestPlugin
Any ideas how to solve this or is there another way to achieve the same result?

**Comment by fullwall** [comment]
It also seems like your pathfinding range is quite high (5000) - you could try a shorter range to avoid pathfinding taking too long. I noticed that you have -Xms7G as well, how much RAM do you have on your server?

**Comment by ItzMace** [comment]
Oh well.. There goes the problem..
Thank you very much! **The pathfinding range should be 500 and not 5000**
With changing it to 500, everything worked perfectly fine!
Have a nice day :+1:
