### ISSUE TITLE
[Citizens] v2.0.19-SNAPSHOT (build 1379) is not compatible with Minecraft v1_9_R2

### ISSUE THREAD

**Issue by Jouke200** [CitizensDev/Citizens2#824]
In this issue, please include:
- [Citizens] v2.0.19-SNAPSHOT (build 1374) is not compatible with Minecraft v1_9_R2
- ConcoleLog: http://pastebin.com/JTJ9pkBw  Config: http://pastebin.com/hnemhhd2
- Minecraft 1.9.4 & [Citizens] v2.0.19-SNAPSHOT (build 1379)

**Comment by DNx5** [comment]
Latest dev build is only for Bukkit 1.10
Get the correct version here:
http://wiki.citizensnpcs.co/Versions
