### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by superpara93** [CitizensDev/Citizens2#826]
This is a ERROR pls help me

> [[16:06:07 ERROR]: Error occurred while enabling Citizens v2.0.9-SNAPSHOT (build 877) (Is it up to date?)
> java.lang.LinkageError: loader constraint violation: when resolving method "net.citizensnpcs.api.CitizensAPI.setImplementation(Lnet/citizensnpcs/api/CitizensPlugin;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/Citizens, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for resolved class, net/citizensnpcs/api/CitizensAPI, have different Class objects for the type npcs/api/CitizensPlugin;)V used in the signature
> >       at net.citizensnpcs.Citizens.onEnable(Citizens.java:235) ~[?:?]
> >       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at autosaveworld.modules.pluginmanager.InternalUtils.loadPlugin(InternalUtils.java:113) [AutoSaveWorld.jar:?]
> >       at autosaveworld.modules.pluginmanager.PluginManager.loadPlugin(PluginManager.java:94) [AutoSaveWorld.jar:?]
> >       at autosaveworld.modules.pluginmanager.PluginManager.handlePluginManagerCommand(PluginManager.java:43) [AutoSaveWorld.jar:?]
> >       at autosaveworld.commands.subcommands.PluginManagerSubCommand.handle(PluginManagerSubCommand.java:39) [AutoSaveWorld.jar:?]
> >       at autosaveworld.commands.NoTabCompleteCommandsHandler.onCommand(NoTabCompleteCommandsHandler.java:123) [AutoSaveWorld.jar:?]
> >       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_101]
> >       at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_101]
> >       at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit.jar:git-Spigot-550ebac-7019900]
> >       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_101]]

**Comment by fullwall** [comment]
Are you using the API? I think the plugin 'autosaveworld' is the problem.
