### ISSUE TITLE
Too many NPC's [/npc text]

### ISSUE THREAD

**Issue by ElementalRealm** [CitizensDev/Citizens2#827]
Im having this issue. When I have too many NPC's at the same area (more then 4) they don't talk. I define the speaking lines and they just don't say them. I did not forgot to use the "close" key when im on the "/npc text" editor. What can I do?

**Comment by mcmonkey4eva** [comment]
One option is to use Denizen for NPC speech instead of the built in text system

http://wiki.citizensnpcs.co/Denizen

Beyond that, there might be a fixable bug, if @fullwall can find one

**Comment by ElementalRealm** [comment]
Is it compatible with 1.8.3 spigot?  If it is please tell me how can I use it. Thanks.  Is there any way to create a kind of a shop with citizens?

**Comment by mcmonkey4eva** [comment]
Yup to the 1.8.3 bit -> http://wiki.citizensnpcs.co/Versions 
There's a full Denizen tutorial series here: http://mcmonkey.org/denizen/vids though that covers more advanced usage than what you need.
YOu just need the basics (setup/install, npc configuration) + something like this:
```
my_npc:
    type: assignment
    actions:
        on assignment:
        - trigger name:proximity state:true
        on enter proximity:
        - random {
          - chat "hi there person!"
          - chat "Nice day!"
          - chat "weee"
          }
```

As for shops: yes, there are a variety of NPC-driven shop plugins and scripts available.

**Comment by ElementalRealm** [comment]
Can you tell me for what i need to look to find those plugins?

**Comment by mcmonkey4eva** [comment]
I googled "bukkit npc shops"
here's a few samples: http://dev.bukkit.org/bukkit-plugins/dtltraders/ http://dev.bukkit.org/bukkit-plugins/hypermerchant/ http://dev.bukkit.org/bukkit-plugins/shopkeepers/ http://dev.bukkit.org/bukkit-plugins/better-shops/ http://dev.bukkit.org/bukkit-plugins/ultratrader/

and of course random sample scripts like this http://mcmonkey.org/denizen/repo/entry/62

**Comment by ElementalRealm** [comment]
Does they work with 1.8.3 spigot?

**Comment by ElementalRealm** [comment]
The UltraTrader is the only one that works with Citizens 2. dtlTrader is not working well...

**Comment by ElementalRealm** [comment]
But UltraTrader is just to 1.7
I don't know how to work with scripts...
