### ISSUE TITLE
It just does not work! It doesn't!

### ISSUE THREAD

**Issue by Arbiciter** [CitizensDev/Citizens2#829]
So I own a Spigot 1.9 Server and I used the most actual Citizens Dev Build from 06.15..

My Problem is, that it just doesn't work. Under /pluins it is marked red and when I type /npc commands it happens nothing. I already tried everything possible and I'm desperate. This is the List of my plugins:

WorldEdit, BasicHomes, RemoteToolkitPlugin, iConomy_Recreation, PermissionsEx, Vault, Multiverse-Core, WorldGuard, MythicMobs, Quests, ArmorStandTools, Jobs, ChatEx, LWC, Holograms, ChestShop

Maybe one of the PlugIns is conflicting with Citizens? Or maybe I need another plugin? I just need help!

**Comment by mcmonkey4eva** [comment]
1.9 is an old version http://wiki.citizensnpcs.co/Versions

**Comment by Arbiciter** [comment]
It's actually on 1.9.4 but I thought 1.9, 1.9.2 and 1.9.4 are the same...

**Comment by Arbiciter** [comment]
Oh my gosh, thank you SO MUCH! I JUST INSTALLED THE LATEST POSTET ON THE SITE AND IT WORKS!!!! IT WORKS!!!! I LOVE YOU!!!
