### ISSUE TITLE
Unbreakable tag lost when server reloads

### ISSUE THREAD

**Issue by Kungkong1** [CitizensDev/Citizens2#832]
An npc is equiped with an item that has the Unbreakable tag attatched to it.
When the server restarts the item looses the tag.

**Comment by HeadlessJoey** [comment]
I would like to add that when an npc has an item with a specific durability and unbreaking in their hand then the item will always have a durability of 0. But when you take the item back it has the right durability as before.
I use this for special textures in my resource pack, an iron sword with a durability of 34 and unbreaking would have a special texture but sadly citizens2 changes the durability of the item in the npcs hand to 0 thus the texture won't show up. 
Also after server restart the unbreaking tag dissapears, I think these two issues are related. If not I can make this into a seperate issue?

**Comment by fullwall** [comment]
@HeadlessJoey it's fine, I will look into this as well.

**Comment by fullwall** [comment]
Not able to reproduce this? What do you mean by 'Unbreakable tag'?

**Comment by mcmonkey4eva** [comment]
@fullwall NBT Tag "unbreakable". If it helps, you can use Denizen to replicate this via `/ex give i@diamond_sword[unbreakable=true]`
You can then at any time test whether it's still there by holding the item and typing `/ex narrate <player.item_in_hand.unbreakable>`.

**Comment by fullwall** [comment]
@mcmonkey4eva hm... there's no bukkit api for unbreakable is there?

**Comment by mcmonkey4eva** [comment]
Noooooooopppe don't think so, NMS is fun tho

**Comment by HeadlessJoey** [comment]
Btw I have a small solution for those who really need it:
Make a small script that upon server restart equips the npcs with their specific unbreakable item.
I only did it for a select few because I needed those to have unbreakable items but you could make a list of npcs and have a flag on each npc with their unbreakable item specified.

**Comment by ABUDoctor** [comment]
You can cast the ItemStack into ItemMeta and check if unbreakable using:

meta.spigot().isUnbreakable();

and set the item using 

meta.spigot().setUnbreakable(true);

**Comment by NathanWolf** [comment]
As of 1.11 there is an unbreakable API on ItemMeta in Bukkit, no need for spigot().

I'd really love to see this preserved as well, it prevents us from being able to use custom item models (via unbreakable items and durability trick) in NPC hands.

**Comment by fullwall** [comment]
Fixed

**Comment by NathanWolf** [comment]
Wow, awesome, thank you very much!
