### ISSUE TITLE
Bug - NPC type Player is Invisible

### ISSUE THREAD

**Issue by ChiaroscurosMC** [CitizensDev/Citizens2#833]
Using Citizens v.2.0.18-SNAPSHOT (build 1371) 
Server is running CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (version 1.9.4-R0.1-SNAPSHOT) 

No errors are showing up in the server log. Citizens config file is at its default settings as the server just installed the plugin this morning. 

From what we have noticed, all other mob types seem to be working with the exception of the player type. The PlayerNPC is invisble. We have tried name the NPC the same as they player's name as well as different than the player's name and have set the skin to that player. 

I've seen previous issues similar to this one which mentioned bungee, though our server is not using bungee. 

If needed, other plugins which we have installed are:
BarAPI, ClearLag, CompatNoCheatPlus, CrateKeys, EnjinMinecraftPlugin, EssentialsX-2.0.1, HolographicDisplays, iDisguise, Lockette, MobHunting, Multiverse-Core-2.5-b717, NoCheatPlus, OnTime, PermissionsEx-1.23.4, ProtocolLib, PvPManager, Questioner, SilkSpawners, Towny, TownyChat, TuxTwoLib, Vault, Votifier, WorldEdit, WorldGuard

**Comment by fullwall** [comment]
Can you try disabling ClearLag?

**Comment by ChiaroscurosMC** [comment]
I will take a shot at disabling it, though we actually added ClearLag after Citizens. But I will give it a shot if there is a chance to make it work.

**Comment by ChiaroscurosMC** [comment]
Removed the ClearLag jar, restarted the server, Current player-type NPCs still weren't visible. Tried to create a new one, still not visible. Doesn't look like it is ClearLag. :(

**Comment by ChiaroscurosMC** [comment]
Just logged in for the first time in close to a year apparently. I believe this issue was the reason I created an account. Not sure what did it, but at some point between 1.9.4 and updating to 1.11.2 the issue fixed. 

Thanks for all your work on the plugin and keeping it updated!
