### ISSUE TITLE
SUGGESTION - Skins

### ISSUE THREAD

**Issue by exZerry** [CitizensDev/Citizens2#834]
Hey, it would be better if we can use skin files from the folders.
Like custom *.png's

**Comment by mcmonkey4eva** [comment]
Can't - Mojang doesn't allow it within their skin system, sorry.
You can put a skin on a player, attach it to the NPC with `/npc skin <name> -p`, and then safely change your skin back. It's a longer process, but it works well enough.

**Comment by exZerry** [comment]
But technically it is possible, right?

**Comment by mcmonkey4eva** [comment]
No. It's literally impossible. Mojang's system does not allow it.

**Comment by exZerry** [comment]
Well I found a way :)

**Comment by mcmonkey4eva** [comment]
What's your way?

**Comment by exZerry** [comment]
simple, you create a custom uuid libriary with profiles, and "Voi la")
