### ISSUE TITLE
Show NPC's only specific players

### ISSUE THREAD

**Issue by Rincewind34** [CitizensDev/Citizens2#837]
Hey,

i just would like to know, if it is possible to show a npc only to permitted player. I already searched in your source code and your api, but aren't able to find anything looking like this feature.
~ Rincewind

**Comment by mcmonkey4eva** [comment]
The Bukkit API features a basic system to do this with player-type entities.

Beyond that, it'll require NMS packet work - you can find examples of that in the Denizen source code https://github.com/DenizenScript/Denizen-For-Bukkit/
