### ISSUE TITLE
PlayerUpdateTask Loss

### ISSUE THREAD

**Issue by TheMikeAmbrose** [CitizensDev/Citizens2#839]
Hello,

Any suggestions for optimization on larger (50-100 players) servers with many NPCs? With PaperSpigot 1.10 and latest Citizens build as of today 1379 the percent per tick for "net.citizensnpcs.util.PlayerUpdateTask" is around 45%.

**Comment by fullwall** [comment]
I need profiling data from something like https://github.com/sk89q/WarmRoast

**Comment by fullwall** [comment]
Should be a little better in the latest build - the potion effects were being sent too often.

**Comment by fullwall** [comment]
Merging this into #801
