### ISSUE TITLE
[BUG] I cant spawn in the NPCs - 1.9.4 spigot

### ISSUE THREAD

**Issue by UDOgaming** [CitizensDev/Citizens2#841]
So whenever I type: /npc create [name]     it comes up with this in the console.

http://pastebin.com/8AWgMvbu

**Comment by mcmonkey4eva** [comment]
You somehow managed to download entirely the wrong thing.

You can download the correct thing from http://wiki.citizensnpcs.co/Versions

**Comment by UDOgaming** [comment]
It still wont spawn them in. I downloaded the one on the site that said 1.9.4. The name of the .jar is citizens-2.0.18-SNAPSHOT.jar is that correct?

**Comment by mcmonkey4eva** [comment]
... yes, that's the correct jar I think. Do you have an updated error message?

**Comment by Fortifier42** [comment]
@mcmonkey4eva Duplicate jar file most likely

**Comment by UDOgaming** [comment]
got it to work. I had the original citizens.jar in the folder and it was messing it up.
