### ISSUE TITLE
java.lang.NoClassDeffFoundError: net/minecraft/server/v1_8_R1/Packet

### ISSUE THREAD

**Issue by IntoTheGame** [CitizensDev/Citizens2#843]
I tested many Versions of Citizens and Down/upgrade the Version of my Server, and whether the Plugin shows up in red with the command /plugin or it is green and a error appears: "java.lang.NoClassDeffFoundError: net/minecraft/server/v1_8_R1/Packet"
Here the log of the Console:
02.07 16:40:20 [Server] INFO a=873
02.07 16:40:20 [Server] INFO net.minecraft.server.v1_8_R3.PacketPlayOutEntityMetadata@3b9a7951[
02.07 16:40:20 [Server] ERROR Parameters: 
02.07 16:40:20 [Server] INFO at java.lang.Thread.run(Thread.java:722) [?:1.7.0_04]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:191) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:332) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot-1.8.8-java-7.jar:git-Spigot-db6de12-d3e0b6f]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:151) ~[HolographicDisplays.jar:?]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.wrappers.WrappedWatchableObject.getIndex(WrappedWatchableObject.java:80) ~[ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO at com.comphenix.protocol.wrappers.WrappedWatchableObject.getWatcherObject(WrappedWatchableObject.java:72) ~[ProtocolLib.jar:4.0.1-b291]
02.07 16:40:20 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedDataWatcher$WrappedDataWatcherObject
02.07 16:40:20 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
02.07 16:40:20 [Multicraft] Skipped 7 lines due to rate limit (30/s)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
02.07 16:40:10 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:166)
02.07 16:40:10 [Server] WARN at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
02.07 16:40:10 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
02.07 16:40:10 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
02.07 16:40:10 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
02.07 16:40:10 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
02.07 16:40:10 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
02.07 16:40:10 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:601)
02.07 16:40:10 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 16:40:10 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
02.07 16:40:10 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
02.07 16:40:10 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
02.07 16:40:10 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

**Comment by fullwall** [comment]
http://wiki.citizensnpcs.co/Versions
