### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EnderW01f** [CitizensDev/Citizens2#845]
Minecraft server Version 1.8.8
And i donwload Citizens for 1.8.8 (2.0.16 ) and dont work.. say up to date...
And i download new version and again dont work...
Say Enabling Citizens and for 3second Disabling Citizens
Sry for bad English :)

**Comment by fullwall** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by EnderW01f** [comment]
this is for 1.8.8: http://ci.citizensnpcs.co/job/Citizens2/1308/
And dont work
![help](https://cloud.githubusercontent.com/assets/20269120/16546847/10dc3886-4158-11e6-8044-1dca3942974c.PNG)

**Comment by EnderW01f** [comment]
ok work :)
tnx
