### ISSUE TITLE
BUG - Npc does not stop moving at target

### ISSUE THREAD

**Issue by GhotiMayo** [CitizensDev/Citizens2#847]
I am using spigot for Minecraft 1.10 and am using the latest build of Citizens (2.0.19 Build #1381).

Something changed between 1.9 and now that causes NPCs to not stop when they have reached their targets.

The NPC is doing this instead of stopping near the player like it did before the update.
https://i.gyazo.com/b172253d05b2f96b273f2945873a277c.gif

**Comment by fullwall** [comment]
Change the distance margin on your NPC

**Comment by GhotiMayo** [comment]
Nothing I change it to seems to make a difference. The NPC just keeps pacing back and forth.

**Comment by fullwall** [comment]
Fixed
