### ISSUE TITLE
Npc not showing up

### ISSUE THREAD

**Issue by swedsesn** [CitizensDev/Citizens2#848]
Hello, So all mob type npc works fine but PlayerNPC don't show up at all, we don't get any error messages or nothing.

plugins used on the server are: PlaceholderAPI, PorteCoulissante, FastCraftPlus, ChaosTowny, BlockedBlocks, ChatReaction, Tablist, CoreProtect, AsyncWorldEditInjector, Action, Essentials_WarpGUI, OpenInv, Essentials, PlayerJoinCounter, PacketListenerApi, WorldBorder, KitGUI, ProtocolLib, Multiverse-Core, NightVision, AsyncWorldEdit, SyncDoors, iDisguise, pStaffList, PermissionsEx, TreeAssist, mcMMO, Vault, ElytraWings, HolographicDisplays, LWC, Holograms, EssentialsSpawn, CratesPlus, WorldEdit, Jobs, Auctions, LiteBans, PlayerVaultsGUI, Citizens, MineResetLite, WorldGuard, Brewery, RandomTeleport, AreaShop, Autorank, Towny, SilkSpawners, TownyChat, SonarPet, CraftBook, ChestShop, BlueShop, TownyNameUpdater

**Comment by mcmonkey4eva** [comment]
Er... sorry for this never getting a reply. Issues page has been a mess. I hope this isn't an issue anymore?
If it is please open a new issue.
