### ISSUE TITLE
[Feature request] /npc speak --id npcid

### ISSUE THREAD

**Issue by Augustin37** [CitizensDev/Citizens2#849]
Hello! I would like to use the /npc speak feature with commandblocks, but a npc must be selected to perform the command. And we can't really select a npc with the console.

So can you add the flag "id" to the /npc speak ?
Command should look like :

> /npc speak message to speak --id npcid

Thank you :D

**Comment by mcmonkey4eva** [comment]
Few things.
`And we can't really select a npc with the console.` Yes, you can actually. `/npc select ID`

NPC Speaking is a bit of an old system and you might be better off firing a Denizen script to accomplish controlled chatting - http://wiki.citizensnpcs.co/Denizen

**Comment by Augustin37** [comment]
> Yes, you can actually. /npc select ID. When you do /npc speak after select it, it says I have to select an NPC :/

I did not tought about Denizen, you are right, this is the solution for this problem :) Thank you very much!
