### ISSUE TITLE
PolarBear moving - Version 2.0.19-SNAPSHOT - Build 1381 

### ISSUE THREAD

**Issue by Lemrigue** [CitizensDev/Citizens2#850]
Hello there, I made an NPC PolarBear (size baby) and sometimes the NPC move a bit to the north-west. After a day he would have move from 1 or 2 blocks and I have to movehere him.
I noticed the NPC is moving after the server restart.
[Before restarting](http://puu.sh/q0lEQ/48cabf6d4e.png)
[After restarting](http://puu.sh/q0lFv/64766b93b0.png)

**Comment by fullwall** [comment]
I have a fix for this but it will not work with Denizen yet.
