### ISSUE TITLE
Error For 2.0.14

### ISSUE THREAD

**Issue by konapuppy** [CitizensDev/Citizens2#851]
Ok, so I downloaded everything, reloaded the sever, did /plugins, Citizens was good and green, but then when I try and do "/npc create KonaTheBaconator" it says, "Please report this error: [See console] java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet"

I've tried reinstalling, etc.

Thanks, Kona
![screenshotcitizens](https://cloud.githubusercontent.com/assets/20464171/16851526/e17c72ea-49b8-11e6-8d11-77362d2e3cf6.png)
![untitled](https://cloud.githubusercontent.com/assets/20464171/16851527/e185cd7c-49b8-11e6-9223-f0650daf2929.png)

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions

**Comment by konapuppy** [comment]
I run a CraftBukkit 1.8.8 server. I any other versions don't work with my server.

**Comment by mcmonkey4eva** [comment]
Then download the appropriate version from the link I just posted.

**Comment by konapuppy** [comment]
OH my god! Thanks so much! I'm so stupid!
