### ISSUE TITLE
Gravity disable option not working

### ISSUE THREAD

**Issue by malonnnn** [CitizensDev/Citizens2#853]
Started in Build #1384
Still exists in Build #1387

This server is running CraftBukkit version git-Spigot-078e2f8-7f9fbe5 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[15:00:22 INFO]: Checking version, please wait...
[15:00:23 INFO]: You are running the latest version

**Comment by fullwall** [comment]
Which NPC type?

**Comment by malonnnn** [comment]
type player

**Comment by fullwall** [comment]
Try latest build
