### ISSUE TITLE
Citizens showing up as a Disabled Plugin

### ISSUE THREAD

**Issue by LegendzOFF** [CitizensDev/Citizens2#855]
Citizens not working:
This is a Bug.
Server Config for Citizens: http://pastebin.com/KPR74WH4
Latest server of Citizens - Spigot Version 1.8.3

Proof: https://www.youtube.com/watch?v=-npYXCvskYw&feature=youtu.be

Please, I need this answered as soon as possible. I purchased this Plugin for $10.00 on the Spigot Website. My Server Owners are waiting for the plugin and the server to be launched. Thank you for reading. Please reply asap.

**Comment by LegendzOFF** [comment]
Wait. I think I just bought a fake Plugin... Is Citizens suppose to be for $10.00? Should I charge-back?

**Comment by mcmonkey4eva** [comment]
The $10 is a non-required donation. Please do not charge back, as that causes issues with the system.
You can download an older (1.8.3) version of Citizens from http://wiki.citizensnpcs.co/Versions

**Comment by fullwall** [comment]
The $10 is a donation, if you want I can refund it. Treating this as closed otherwise.
