### ISSUE TITLE
version 1.8.8 doesnt work

### ISSUE THREAD

**Issue by zorvi** [CitizensDev/Citizens2#856]
Hello if i do /npc create creeper I dont see him i use
- Minecraft 1.8.8 and citizens-2.0.16-SNAPSHOT.jar
cosole dont give errors

**Comment by mcmonkey4eva** [comment]
Make sure you have the correct version off of http://wiki.citizensnpcs.co/Versions

Additionally, make sure you have no interfering plugins.

**Comment by zorvi** [comment]
I have The correct version...

**Comment by mcmonkey4eva** [comment]
Can you please post a full startup log (using pastebin)?
