### ISSUE TITLE
Hero NPCs issues

### ISSUE THREAD

**Issue by ladiciuss** [CitizensDev/Citizens2#860]
Unsure if Bug or I'm ignorant of some functionality.

Using spigot 1.10 and Citizens 2.0.19 Snapshot build 1379

At first my issue was that Player NPCs couldn't seem to keep their armor on. I traced the problem to it being a Heroes NPC, and the default Hero couldn't wear the armor I needed on the NPC. So that lead me to finding the command to change the NPC's hero. This works, but once I restart my server the NPC's hero gets reset to the default. Wondering if there's anyway to disable automatically making a Player NPC with the HeroesNPC trait or if there's a way to make the NPC keep the class I set it to.

**Comment by mcmonkey4eva** [comment]
That's a question for the Heroes team, isn't it?

**Comment by fullwall** [comment]
You can remove the HeroesNPC trait with the /trait remove command but yes should ask the Heroes team about this.

**Comment by ladiciuss** [comment]
Removing the trait just reapplies it on server restart, but I've found a workaround.
