### ISSUE TITLE
Blaze NPC still makes burning noise even when sounds are null

### ISSUE THREAD

**Issue by MiniCraft12** [CitizensDev/Citizens2#861]
Minecraft Version: 0.10.2
Citizens Version: 2.0.19

Bug description:
When I try to set all of the sounds on a Blaze NPC to null with the command: /npc sound -n, the crackling fire noise is still audible.

**Comment by fullwall** [comment]
Try latest build.

**Comment by MiniCraft12** [comment]
Isn't 2.0.19 the latest build?

**Comment by mcmonkey4eva** [comment]
http://ci.citizensnpcs.co/job/Citizens2/

**Comment by MiniCraft12** [comment]
Ok I upgraded to  2.0.20 and the fire sound persists.

**Comment by mcmonkey4eva** [comment]
@MiniCraft12 did you reapply `/npc sound -n` on a latest build?

**Comment by MiniCraft12** [comment]
Yes, I selected the Blaze NPC and reapplied /npc sound -n, but the I still makes the ambient fire crackling noise. Also I'd like to thank you for your continued support, your a helpful developer!

**Comment by Serializator** [comment]
I suspect that the fire crackling sound (`entity.blaze.burn` according to `EntityBlaze#n()` and its invocation of `World#a(double, double, double, SoundEffect, SoundCategory, float, float, boolean)` in 1.12.2) is client-side and only controllable by the `Silent` tag which also keeps the blaze from creating any other type of sound, not only the fire crackling sound.

I know this is an old issue and what I just said may be already known after almost two years but if not, I don't think this issue can be solved without the ambient sound attribute of the blaze NPC affecting the hurt and death sound attributes.
