### ISSUE TITLE
Citizens teleported out of Entry Deny Region from Worldguard

### ISSUE THREAD

**Issue by crazydred** [CitizensDev/Citizens2#862]
Since last dev build:
citizens-2.0.20 #1390
**all citizens placed in a entry deny region from Worldguard will be teleported out after server restart, and they can't be teleported back in.**

Can you explain why this happens?

**Comment by mcmonkey4eva** [comment]
Entry deny means Citizens NPCs are denied entry as well - WorldGuard's doing, not ours.

**Comment by crazydred** [comment]
Yes I understand. But how do I allow Citizens group in the area?

**Comment by mcmonkey4eva** [comment]
That's a question for the WorldGuard team.

**Comment by crazydred** [comment]
Ok, I will post their answer

**Comment by crazydred** [comment]
Reported to worldguard team
[http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3736](url)
