### ISSUE TITLE
internal error occuring with Builder trait

### ISSUE THREAD

**Issue by itos01** [CitizensDev/Citizens2#864]
hello, i want to use the rait Builder on my server, but every time i try to use /builder build, it say that an internal error occured while attempting to perform this command. Attaching the trait, loading the schematic (house.schematic from the download file) works and it shows the amount of blocks in it.
can someone help me with it? link to the error from console is below.
p.s. i did not edit the config files
Minecraft: 1.8.7 Citizens: 2.0.16
[Error.txt](https://github.com/CitizensDev/Citizens2/files/378038/Error.txt)

**Comment by mcmonkey4eva** [comment]
http://ci.citizensnpcs.co/job/Builder/9/

**Comment by itos01** [comment]
so i now can see a bunch of changes in the code but eh installing the shown Jar file of Builder does not work either. soo a bit more than just a link to a compiler would be nice ^^ for example with a guide how to use it. i am not really experienced with Java at all. Thankks anyways :D

**Comment by mcmonkey4eva** [comment]
... Download the `Builder.jar` link and use that in your plugins folder, after deleting the original copy.

If that doesn't post, post the current error.

**Comment by itos01** [comment]
i have tried to install that builder.jar but now the trait is not found/registered and can not be attached to an NPC as if it was not existing

**Comment by mcmonkey4eva** [comment]
Post a startup log?

**Comment by itos01** [comment]
[Error.txt](https://github.com/CitizensDev/Citizens2/files/381636/Error.txt)
thats the entire log of a reload. the Builder.jar is located in the plugins directory and does not load

**Comment by itos01** [comment]
whoops did not mean to close~

**Comment by fullwall** [comment]
Looks like a Builder issue

**Comment by itos01** [comment]
i could already install the trait earlier just as said above but when i wanted the builder to start it put out the error i posted

**Comment by mcmonkey4eva** [comment]
@itos01 that old version of builder has a dependency for Denizen. You can pick that up from http://wiki.citizensnpcs.co/Versions then it should all work :)

**Comment by itos01** [comment]
soo after all i could install the Builder Trait itself, citizens as well, but still i can not let them build schematics. that is when the error occurs which is shown at my first post on here. what cases that error, how can i fix it or can any of you?

**Comment by mcmonkey4eva** [comment]
@itos01 read my previous post above ^ just download Denizen to your plugins and it oughtta work.

**Comment by itos01** [comment]
ah i just clicked the wrong thing and downloaded a Citizens jar xD okay i am downloading Denizen for 1.8.8

**Comment by itos01** [comment]
still putting out the error from above

**Comment by itos01** [comment]
no matter about which version of Denizen or Builder i use

**Comment by mcmonkey4eva** [comment]
Please post an updated error message

**Comment by itos01** [comment]
[Error.txt](https://github.com/CitizensDev/Citizens2/files/384265/Error.txt)

**Comment by mcmonkey4eva** [comment]
@itos01 and what happens when you actually run the 1.8.7 versions of Builder and Denizen, as opposed to what you're running now, which is very much /not/ those version?

**Comment by itos01** [comment]
i tried to run the 1.8.7 versions already, i tried the last one as well.

**Comment by mcmonkey4eva** [comment]
@itos01 Please post any error message you get **while running 1.8.7 versions of both Builder and Denizen**.
