### ISSUE TITLE
Server lag when NPC activates redstone

### ISSUE THREAD

**Issue by ladiciuss** [CitizensDev/Citizens2#867]
(BUG) Nothing's being printed in console when it happens, but whenever you observe an NPC walking over a pressure plate or tripwire, the server stops for a second and then unfreezes. Happens every time. Any idea as to why this is?

**Comment by fullwall** [comment]
Player NPC?

**Comment by ladiciuss** [comment]
Yeah it's a player NPC. It doesn't lag when it's a villager though.

**Comment by fullwall** [comment]
Are they on the playerlist? What's your config?

**Comment by ladiciuss** [comment]
http://pastie.org/10919805

**Comment by ladiciuss** [comment]
And no, they're not on the playerlist.

**Comment by mcmonkey4eva** [comment]
Doesn't seem to be an issue on current versions.
