### ISSUE TITLE
Citzens2 cant work 

### ISSUE THREAD

**Issue by VincentVVV2016** [CitizensDev/Citizens2#869]
Oh My god！I find my title is wrong ！**Citizens2**
![_ e9xe2j7e n k7 2jpf 2](https://cloud.githubusercontent.com/assets/20635875/17092180/53466580-5273-11e6-9e81-c48d7a3bbaee.png)

I search the mcbbs http://www.mcbbs.net for a long time and I cant find how to work out it
Please help me！
There is a likely problem happened to 
①https://github.com/CitizensDev/Citizens2/issues/68
②https://bukkit.org/threads/i-cant-dowload-plugins-like-citizens.139526/

**Comment by mcmonkey4eva** [comment]
If you are having trouble finding the correct version, http://wiki.citizensnpcs.co/Versions
If you are having trouble installing: contact someone about general plugin setup.
If you are having trouble with usage: http://wiki.citizensnpcs.co/Citizens_Wiki
