### ISSUE TITLE
Console Spammed with "SET DATA"

### ISSUE THREAD

**Issue by HollishKid** [CitizensDev/Citizens2#871]
Bug Description
My console is constantly spammed with "SET DATA".

Log: http://pastebin.com/2hnMkiXC
Citizens config: http://pastebin.com/MHwUGQDP

Minecraft version: server is running CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
Citizens version: Citizens v2.0.18-SNAPSHOT (build 1369)

Thanks for your help!

**Comment by fullwall** [comment]
Seems like a version specific debug issue... you can try http://ci.citizensnpcs.co/job/Citizens2/1371/ this build otherwise might have been fixed in 1.10. Let me know as I am working on cross compatibility.

**Comment by HollishKid** [comment]
Thanks, this seems to work fine for now.
I'll test it a bit more and reopen this issue if necessary!

Thank you very much!
