### ISSUE TITLE
Fix launcher skins

### ISSUE THREAD

**Issue by mikassio** [CitizensDev/Citizens2#873]
Hello.
Skins on the server, with its own launcher skins and the system displays only standard. (Steve and Alex girl).
How to fix it?
P. s. sorry for my English, because I'm Russian.

**Comment by mcmonkey4eva** [comment]
... huh?

**Comment by mikassio** [comment]
I am Russian. :-(
I have a launcher for the project. The server is citizens2, but attempts to put some skin with the nickname of the license minecraft - the skin is not put. The same situation with the launcher, NPC names have a standard skins.

**Comment by mcmonkey4eva** [comment]
By `launcher` do you mean a modded server (EG Forge, Cauldron, ...)? Or...?

**Comment by mikassio** [comment]
No, it is the launcher. In Russia do not license server. You create projects with your launcher. (Example -Russian launcher for http://rubukkit.org/threads/sashok724-launcher.42883/ projects). They should own system skins. The skin can be changed on site. So, Citizens does not take the skins are not from my website, or with Mojang.
But I understand there hardly will help, because you are not familiar with the "launcher". : D

**Comment by mcmonkey4eva** [comment]
Unfortunately, at this time Citizens is only compatible with the legal official Mojang servers, and will not function with alternate setups that do not use the official system.

**Comment by mikassio** [comment]
Is it possible to rewrite the skins system?
And is there a source snapshot 2.0.18?

**Comment by mcmonkey4eva** [comment]
Rewrite it for your weird case? No.

Source? Somewhere in there.

Possibly this link: https://github.com/CitizensDev/Citizens2/tree/28d23c31c2f453666047bc4e5df8d685c4ced186

**Comment by mikassio** [comment]
No, you do not understand me. I asked whether it is possible, and I will seek to rewrite any of the Russian people.
And it's kind of snapshot 2.0.17.

**Comment by mcmonkey4eva** [comment]
2.0.17 is here: https://github.com/CitizensDev/Citizens2/tree/02312848aa4bf54e0468db623f68d0ce3afe13bd

**Comment by mikassio** [comment]
Okey. Thanks.
