### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by mikassio** [CitizensDev/Citizens2#874]
Hey. And where api?
http://rgho.st/7cFmKJBDt/image.png

**Comment by fullwall** [comment]
Have you imported the right thing into your pom.xml?

**Comment by mcmonkey4eva** [comment]
Generally you need a built file, not source code.
You can pick up whichever C2 prebuilt file you require from http://wiki.citizensnpcs.co/Versions

**Comment by fullwall** [comment]
You should use maven and include the pom.xml as it shows here: https://github.com/CitizensDev/CitizensAPI 

Copy and pasting java files is generally a bad idea since Spigot's classloader will get confused

**Comment by mikassio** [comment]
Can you give a link directly to a file 1. 9. 4?

**Comment by mcmonkey4eva** [comment]
release: http://ci.citizensnpcs.co/job/Citizens2/1371/artifact/target/citizens-2.0.18-SNAPSHOT.jar api: http://ci.citizensnpcs.co/job/CitizensAPI/net.citizensnpcs$citizensapi/505/artifact/net.citizensnpcs/citizensapi/2.0.18-SNAPSHOT/citizensapi-2.0.18-SNAPSHOT.jar

**Comment by mikassio** [comment]
Thanks

**Comment by mikassio** [comment]
Hello again. I have a problem again why lib folder does not appear in the plugin after the assembly? Because of this plugin is not working.

**Comment by mikassio** [comment]
Hello again. I have a problem again why lib folder does not appear in the plugin after the assembly? Because of this plugin is not working.

**Comment by fullwall** [comment]
The Citizens plugin should not be included into your plugin JAR - instead the Citizens plugin is installed separately and you include a depend: [Citizens] in your plugin.yml
