### ISSUE TITLE
Citizens Is showing up red in my plugins 

### ISSUE THREAD

**Issue by CubedOnline** [CitizensDev/Citizens2#875]
Citizens Is showing up red in my plugins 
-Yes my server is running CraftBukkit (1.8.8)
If someone knows the problem please tell me!

**Comment by mcmonkey4eva** [comment]
Download the /ancient/ 1.8.8 builds off of http://wiki.citizensnpcs.co/Versions

**Comment by CubedOnline** [comment]
What? does that do

**Comment by CubedOnline** [comment]
THANKS IT WORKED THUMBS UP THXX SO MUCH
