### ISSUE TITLE
NPCs in TabList & Can't remove NPCs

### ISSUE THREAD

**Issue by Poweringg** [CitizensDev/Citizens2#878]
Hi, i created some NPCs but, NPCs is blinking in tablist and NPCs breaking up player nameTags. 

(ExtigradGuard is NPC.)
![2016-08-03_11 51 23](https://cloud.githubusercontent.com/assets/15527318/17361517/2d319acc-5971-11e6-8e5a-6a763782606d.png)

next problem is, i can't remove NPCs with custom nameTag eg. "&a&lExtigrad &aGuard&r"
i typed "npc remove" yep is deleted, but when i reloads/restarts server NPC is back.

spigot - 1.9.4-R0.1
citizens v2.0.18-snapshot (build 1366)

how to fix this problem? thanks.

**Comment by fullwall** [comment]
Config?

**Comment by Poweringg** [comment]
`
# Citizens Configuration

npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  default:
    look-close:
      enabled: false
      range: 5
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  controllable:
    use-boat-controls: true
  player-scoreboard-teams:
    enable: true
  teleport-delay: -1
advanced:
  check-minecraft-version: true
general:
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
  debug-file: ''
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
`

here it is

**Comment by mcmonkey4eva** [comment]
Shouldn't be happening on current builds.
(Unless you have some external tablist screwery plugin)
