### ISSUE TITLE
Npc's not turning correctly

### ISSUE THREAD

**Issue by Elvi81** [CitizensDev/Citizens2#880]
With build 1407 npc's don't turn when you have them controllable, been like this for several builds and i think you know that already and i've seen fixes but none have worked on my end.

Running git-Spigot-90f61bc-83a9dbd (MC: 1.10.2)

**Comment by fullwall** [comment]
What NPC type?

**Comment by Elvi81** [comment]
I made a polarbear ridable but it's with any npc/mob and yes it's set to true.

**Comment by Elvi81** [comment]
It's still doing on build 1420 but i found out that if you ride the ender dragon with /npc mount it turns as it should strangly enough.
