### ISSUE TITLE
Citizens spawning in WG regions

### ISSUE THREAD

**Issue by mawej1** [CitizensDev/Citizens2#881]
Hey,

after updating to the newest Citizens and Denizen versions, I can no longer use the Denizen create command to spawn an npc that is included in the deny-spawn flag of a region. To be exact, I am creating a copy of a skeleton npc.

I posted this issue on the Denizen issues page, and I was told that no code change regarding this was made, hence I am posting it here.

I understand that this maybe isn't an issue, but it didn't occur before updating from a version few weeks old. 

With that said, is there a way to make this work with the current configuration, or should I rather report this to the WorldGuard issues page?

Thanks

**Comment by fullwall** [comment]
It may be an event priority issue, it might be worth asking WorldGuard about it.
