### ISSUE TITLE
Citizens that do not save to the config

### ISSUE THREAD

**Issue by iarepandemonium** [CitizensDev/Citizens2#882]
Make it possible that an npc can have something that can be turned on that prevents the npc from being saved into the config in the case of temporary npcs that by default is off.  That way if a plugin has a temporary npc it will not bug out if citizens crashes or their server crashes.

**Comment by mcmonkey4eva** [comment]
That was added at some point I'm pretty sure. (MemoryNPCDataStore stuff)
