### ISSUE TITLE
Player nametag longer than 16 characters

### ISSUE THREAD

**Issue by RobiRami** [CitizensDev/Citizens2#883]
This is a feature request. I would like to be able to set the nametag of player NPC's to a nametag longer than 16 characters. I don't know if it's possible.

NickNamer may be doing this, but I'm not sure: https://www.spigotmc.org/resources/1-8-1-9-1-10-nicknamer-integrated-api.5341/

**Comment by mcmonkey4eva** [comment]
This is already doable within Citizens though...

Just set it to a long name, there's no issue.

**Comment by RobiRami** [comment]
playername.setName("&bAristocratically"); causes issues and only shows 'ly'

**Comment by mcmonkey4eva** [comment]
You might have something on your server (EG potentially even the plugin you linked above, NickNamer) interfering with usernames or NPC player teams. Also check your Citizens config for related settings.

**Comment by RobiRami** [comment]
I tested this with a server with only Citizens and a default Citizens config.

**Comment by mcmonkey4eva** [comment]
Well.
![image](http://puu.sh/qxwLG.png)
http://puu.sh/qxwLG.png

I don't know what to tell you.

**Comment by RobiRami** [comment]
:/

![2016-08-11_19 29 02](https://cloud.githubusercontent.com/assets/10091332/17598278/03dbb506-5ffa-11e6-878f-b7792a190d37.png)

**Comment by RobiRami** [comment]
![2016-08-11_19 29 02](https://cloud.githubusercontent.com/assets/10091332/17598393/9344f9aa-5ffa-11e6-8e21-56d8bb0346d6.png)

**Comment by MnMaxon** [comment]
I took a look at the code. The prefix/suffix thing that lets you make long names is only in HumanController.createEntiy()
It's not on AbstractNPC.setName(String name)
So, currently this only works if you create a player npc with a long name. It won't work if you rename it to a long name.


PS: It also works if you spawn an entity with a short name, rename it to a long name, then create a new NPC with the same long name (then you can delete the new NPC).
https://gyazo.com/a12ed163f6a526a6fd61c8f5fdd2d439

**Comment by RobiRami** [comment]
Any idea how I can do this clean code-wise ?

**Comment by mcmonkey4eva** [comment]
- Create the NPC with the right name in the first place
or
- Respawn the NPC after renaming it
?

**Comment by RobiRami** [comment]
Could this be added to AbstractNPC.setName() for EntityType.PLAYER ?

I have to change the name of my NPC's a lot so if I have to create a new one all the time, my index id of the NPC's would quickly rise to a high number.

**Comment by mcmonkey4eva** [comment]
Hm... if that doesn't work, it's likely a bug for @fullwall to patch

**Comment by RobiRami** [comment]
I might be able to bypass the rising index number by spawning a new NPC with the id parameter. I'll do some more tests.

**Comment by RobiRami** [comment]
I got it working, but the issue now is that color codes break after character 16. Is this on purpose? Can I add my own thing to bypass this (e.g. add the last color code after character 16) ?

**Comment by RobiRami** [comment]
Looks like that is bypassable, you might want to make it that way by default.

**Comment by RobiRami** [comment]
Finally fixed it :+1: 

```
    private final Pattern pattern = Pattern.compile("(&.)");	
    private String fixNameTag(String tag) {
		Matcher matcher = pattern.matcher(tag.substring(0, 16));
		List<String> chars = new ArrayList<String>();
		while(matcher.find()) {
			chars.add(matcher.group(1).substring(1));
		}
		Collections.reverse(chars);
		for(String character: chars) {
			ChatColor c = ChatColor.getByChar(character);
			if(c != null) {
				return (tag + "&" + character);
			}
		}
		return tag;
	}
```

![](http://i.robindebaets.be/22-56-56.png)

**Comment by fullwall** [comment]
Yeah there's some problems with the scoreboards that I found out about recently so not sure whether to fix this feature or not.

**Comment by sigmaroot** [comment]
Any news?

**Comment by RobiRami** [comment]
Bump.

**Comment by Namnodorel** [comment]
I am running into the same thing atm, and it is really annoying... I found out too, that https://github.com/CitizensDev/Citizens2/blob/14cd243d6a1e97f8d87d33fa009d8e66fd2b9363/v1_10_R1/src/main/java/net/citizensnpcs/nms/v1_10_R1/entity/HumanController.java#L38 is responsible for this behavior, that code also resets any color codes after 16 characters. 

Does anybody now why that code is actually there? I wouldn't know why I want  my nametags to be messed around with like that. If it has no particular purpose, why don't we just remove it?

**Comment by mcmonkey4eva** [comment]
@Namnodorel the nametag can only be 16 characters. If it's longer than that, it needs to be split into the scoreboard system to display correctly at all

**Comment by mcmonkey4eva** [comment]
Renaming is patched in latest build.

Also re-reading that last question @Namnodorel I'm not actually sure why the reset color code is there offhand, but I don't think it's problematic particularly (Possibly was to prevent name conflicts?)

**Comment by RobinDeBaets** [comment]
I will update my plugin and revert it to the old renaming. Thanks for fixing.

**Comment by LikeManTV** [comment]
![image](https://user-images.githubusercontent.com/56754106/87879004-2cd56680-c9e8-11ea-8e00-d422d3ede301.png)
For me it's not working either by creating the NPC with long name or renaming it (probably beacouse version 1.8)
Is there a way of fixing the bug on this version or installing newer version on this one?

**Comment by LikeManTV** [comment]
And the "Nameplate visibility" isn't working too on this version, so I can't make the name by HD.
(btw I need this version)

**Comment by fullwall** [comment]
This is the wrong place to ask your question but the answer is most likely updating to the latest build of Citizens.

**Comment by LikeManTV** [comment]
The question is to this post..

**Comment by fullwall** [comment]
Create a new issue, don't necro one from 2016.
