### ISSUE TITLE
Skeleton NPCs navigation

### ISSUE THREAD

**Issue by mawej1** [CitizensDev/Citizens2#884]
Bug screen: http://imgur.com/oWcLxz4

Save: http://mcmonkey.org/paste/35292

**Comment by fullwall** [comment]
@mcmonkey4eva does the range stat in sentinel mean anything here?

**Comment by mcmonkey4eva** [comment]
@fullwall that's how far they'll spot an enemy from, nothing more.

**Comment by mcmonkey4eva** [comment]
Is this still an issue?
