### ISSUE TITLE
HI This is more of an Idea/wondering if it can be done???

### ISSUE THREAD

**Issue by TheSodaPopPanda** [CitizensDev/Citizens2#885]
I'm making a GUI menu in chest commands and I use a plugin to add the command to the NPC now I made a really cool menu Think using armour stands and I set the NPC at the same spot as a slime for a large hitbox to open the menu and I need to make the NPC invisible I thought there was a command for this but now I can find one please help

**Comment by mcmonkey4eva** [comment]
The Denizen side-plugin http://wiki.citizensnpcs.co/Denizen adds `/npc invisible` to Citizens.

**Comment by TheSodaPopPanda** [comment]
Awesome Thank you so much also you response time is just WOW :O

**Comment by TheSodaPopPanda** [comment]
Please Help /npc invisible is not working did denizens remove it?

**Comment by mcmonkey4eva** [comment]
If that doesn't work you can also do a more internal-ish Denizen command: `/ex invisible <npc>` (note: literal text, don't replace or change anything in that) and it should work.

Fair note that this requires `/npc playerlist` be enabled if it's a player.

Also that it bugs in a thousand an one different setups for unknown reasons :/

**Comment by TheSodaPopPanda** [comment]
OK sorry about the other thread I didn't know to reopen this one

and that worked thank you very much
