### ISSUE TITLE
Please Help /npc invisible is not working did denizens remove it?

### ISSUE THREAD

**Issue by TheSodaPopPanda** [CitizensDev/Citizens2#887]
Please Help /NPC invisible is not working did denizens remove it?
I installed it and-and it works but the command does not 
you said Denizens had this 
here's the link to the thread 
https://github.com/CitizensDev/Citizens2/issues/885#issuecomment-239353082

**Comment by mcmonkey4eva** [comment]
Please don't open multiple issues for the same question from the same person... you can reopen the old issue if needed.
