### ISSUE TITLE
cant left-click npc because of worldgaurd  

### ISSUE THREAD

**Issue by woolfxx** [CitizensDev/Citizens2#888]
hello i cant left the npc on my server bc i have pvp  deny with worldgaurd and i have quicksell set up with npc, players cant see the price bc they cant left it and when i allow pvp players could see the prices and pvp too
 is there any way i could have pvp deny and allow players to left click the npcs

**Comment by mcmonkey4eva** [comment]
That's a question for the WorldGuard team, isn't it?

**Comment by woolfxx** [comment]
i check everything with worldguard still nothing idk what to do

**Comment by mcmonkey4eva** [comment]
... ask this question to the WorldGuard team, maybe? They have support pages too.

**Comment by AnthonyAMC** [comment]
I swore up and down that i wasn't going to answer this question because it's been answered many times and because the info is on the [WG wiki](http://docs.enginehub.org/manual/worldguard/latest/regions/flags/). It's the interact flag. In [dRegions](https://www.spigotmc.org/resources/denizen-dregions.26864/), however, there's a separate flag for it to control NPCs specifically.

**Comment by woolfxx** [comment]
anthony is there any u could help me fix i look every were. if u fix my problem ill pay u 5-10 paypal?

**Comment by AnthonyAMC** [comment]
`/rg flag [regionID] interact -g all allow`
`/rg flag [regionID] use -g nonmembers deny`
You can send a contribution to [here](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=NPXKHCNMTGSUG) if you are actually serious.

**Comment by woolfxx** [comment]
bro do u have skype or can u get on my server and yes im serious about the paypal i tryed so much if u fix my problem ill send u the money ty

**Comment by mcmonkey4eva** [comment]
Just do the commands he showed?

**Comment by woolfxx** [comment]
im still confused can either 1 of u get on my server please and send me ur paypal email my server ip is : Kyrosity.mygs.co

**Comment by mcmonkey4eva** [comment]
No, just follow the instructions provided and ask any questions you have.

If you can't handle that, you can't handle server ownership tbh :/

**Comment by BlackCoyote** [comment]
if you pay me $500 i'll come fix it for you

**Comment by woolfxx** [comment]
blackcoyote come on 5-10$ please

**Comment by BlackCoyote** [comment]
400, no lower , I have a family to feed

**Comment by woolfxx** [comment]
blackcoyote can u get on my server we talk there Kyrosity.mygs.co

**Comment by BlackCoyote** [comment]
What's the new question? as far as I can see you've had your previous one answered already

**Comment by mcmonkey4eva** [comment]
This is going nowhere, and the trolls are starting to get in... contact WorldGuard support for further assistance.
