### ISSUE TITLE
BUG: Error when players load chunks with NPC's in them

### ISSUE THREAD

**Issue by Ronan77** [CitizensDev/Citizens2#889]
I'm using the latest dev version of citizens and in this im getting an error in console every time players load the chunks they are in, not sure why this happens, please find what is causing this, i haven't edited the config what so ever, so yeah, config has nothing to do with this, and I am running it on 1.10. Error: http://pastebin.com/fmYsvxWt

**Comment by fullwall** [comment]
Fixed
