### ISSUE TITLE
Villager Type NPCs can not be right clicked

### ISSUE THREAD

**Issue by doitliketyler** [CitizensDev/Citizens2#890]
The title says it all. If I want to have a quest NPC I have to use other NPC types. Any fix for this so I can use Villagers instead?

**Comment by mcmonkey4eva** [comment]
what versions are you on?

**Comment by doitliketyler** [comment]
Citizens v2.0.20-SNAPSHOT (build 1390)

**Comment by fullwall** [comment]
Fixed in the latest build?
