### ISSUE TITLE
NPC's not spawning at their specified location after a server restart

### ISSUE THREAD

**Issue by dannybisby** [CitizensDev/Citizens2#892]
After a server restart NPC's are not visible at their specified location, this does not apply to all NPC's it appears to be only newly added NPC's since updating to 1.10

Teleporting to the NPC using /npc tp will teleport me to the location is meant to be at
Using /npc tph will teleport the NPC to my location

It appears as though the NPC's are spawning in the wrong location somewhere?

Rrunning CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Citizens v2.0.20-SNAPSHOT (build 1409)

There are no startup or stop errors

**Comment by BiGUNMAN** [comment]
They may just not be appearing, try /npc spawn.
