### ISSUE TITLE
Hostile NPCs Not Spawning

### ISSUE THREAD

**Issue by BiGUNMAN** [CitizensDev/Citizens2#893]
Hostile mob citizens do not spawn.
My gamerule allows mob spawning, my multiverse world allows mob spawning, my server properties does to. A worldguard **global** flag is set to disable mob spawning, but I put the hostile mobs with higher priority regions in allow mob spawning regions (this shouldn't be an issue though, since WorldGuard never had allow-mob-spawning and Citizens compatibility issues.

If I do /npc select and then /npc spawn they do appear, but after a server restart they disappear.

Their are no server log errors.

Plugin Version:
http://i.imgur.com/Vz1R9Bo.png (I bought the plugin on Spigot and used that version, then tried the dev build, makes no difference).

PaperSpigot Version:
http://i.imgur.com/I5wCqWa.png

**Comment by fullwall** [comment]
If you enable debug: true in the config what do you get on startup?

**Comment by BiGUNMAN** [comment]
Here's the debug: http://pastebin.com/N4K2WbFF - 17 and 24 are the npc's that are hostile (zombie and skeleton respectively), and they do not spawn. If I type /npc select (17/24) and then /npc spawn they appear, but otherwise they do not.

**Comment by fullwall** [comment]
I guess from that it seems like a worldguard compatibility issue

**Comment by BiGUNMAN** [comment]
Stopped server, disabled worldguard, started server, npcs still don't spawn.

**Comment by BiGUNMAN** [comment]
The other thing is this is almost random. Sometimes they appear, I'll try to find some pattern, currently it seems like there's an issue with the order in which players join the server when it first starts up.

**Comment by mcmonkey4eva** [comment]
I imagine if it's player joining order related, it's related to #1332 (and can be discussed there if so. if not, please reply below and I'll reopen this issue)
