### ISSUE TITLE
Server crash with CommandNPC plugin

### ISSUE THREAD

**Issue by Bodyash** [CitizensDev/Citizens2#894]
Someone find a great way to crash server.

http://pastebin.com/2WniHtWZ

Can u create own method to add command to execute when NPC right clicked

**Comment by Bodyash** [comment]
Oh wait, Denizen can do it?

**Comment by mcmonkey4eva** [comment]
`Can u create own method to add command to execute when NPC right clicked`
Use Denizen ( http://wiki.citizensnpcs.co/Denizen ) for that.
