### ISSUE TITLE
It told me to report this error

### ISSUE THREAD

**Issue by teamaonn** [CitizensDev/Citizens2#895]
In this issue, please include:
- Error
- Is the default setup
- 1.10.2 version

5:14:02 AM
 CONSOLE:
[INFO] Zyuoh_The_World issued server command: /npc
5:14:02 AM
 CONSOLE:
WARN]: java.lang.NullPointerException
5:14:02 AM
 CONSOLE:
WARN]: at net.citizensnpcs.commands.NPCCommands.npc(NPCCommands.java:982)
5:14:02 AM
 CONSOLE:
WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
5:14:02 AM
 CONSOLE:
WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
5:14:02 AM
 CONSOLE:
WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
5:14:02 AM
 CONSOLE:
WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
5:14:02 AM
 CONSOLE:
WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
5:14:02 AM
 CONSOLE:
WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
5:14:02 AM
 CONSOLE:
WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
5:14:02 AM
 CONSOLE:
WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
5:14:02 AM
 CONSOLE:
WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
5:14:02 AM
 CONSOLE:
WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
5:14:02 AM
 CONSOLE:
WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
5:14:02 AM
 CONSOLE:
WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
5:14:02 AM
 CONSOLE:
WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673)
5:14:02 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572)
5:14:02 AM
 CONSOLE:
WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by fullwall** [comment]
Try latest build?
