### ISSUE TITLE
[1.10.2] NPC Movement and Deletion Bug

### ISSUE THREAD

**Issue by Xerviscious** [CitizensDev/Citizens2#898]
Spigot Version: 1.10.2
Citizens 2 Version: 2.0.20 Snapshot

Problem: Upon placing an NPC by using the command /npc create <name> the NPC is created. However, there is another blank skinned NPC inside of the NPC that is created.

The NPC also moves from a slight left and right axis rapidly fast until the command /npc rem is given.

When the NPC is removed it is still there however the plugin does not recognize it is still on the world; it thinks that the NPC has been removed.

**Comment by Jocke155** [comment]
This happens to me too... But when you remove it, try relogging and it's gone.

**Comment by Xerviscious** [comment]
That's exactly what I am experiencing... is there a fix for this?

**Comment by mcmonkey4eva** [comment]
What build # of Citizens are you on?
Also, what plugins do you have installed?

**Comment by BruurTycho** [comment]
http://img.suppixel.xyz/img/2016-08-21_15-39-31.mp4

Newest build

**Comment by BruurTycho** [comment]
Mobs are not affected as it seems:
http://i.imgur.com/IL92c1P.png

**Comment by fullwall** [comment]
Fixed, sorry.

**Comment by Jocke155** [comment]
Xerviscious: I use Shadowplay, that comes with nvidia cards

**Comment by BruurTycho** [comment]
Yes, the problem has been fixed!

**Comment by Jocke155** [comment]
Where can I grab the fixed build?

**Comment by Xerviscious** [comment]
Thanks!
