### ISSUE TITLE
NoSuchMethodError guava10

### ISSUE THREAD

**Issue by Edisoni** [CitizensDev/Citizens2#899]
PluginVersion: 2.0.20
Server: Thermos 1.7.10
http://pastebin.com/mzvDgLsn

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions for the standard versions, or if `Thermos` is Cauldron, https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar
