### ISSUE TITLE
PlayerUpdateTask CPU Usage

### ISSUE THREAD

**Issue by oloflarsson** [CitizensDev/Citizens2#900]
# Introduction

Hello @fullwall! Thank you for developing Citizens. We have been using it for over two years on MassiveCraft at this point. It's a great plugin :+1:. Due to a bug or missconfiguration on my end the plugin makes use of quite a bit of CPU though.

I have tried reporting this issue twice before but it seems my issue tickets did not contain enough information and were closed:
- https://github.com/CitizensDev/Citizens2/issues/724
- https://github.com/CitizensDev/Citizens2/issues/801

This time I aim to provide much more information.
# Environment

**PaperSpigot:** https://ci.destroystokyo.com/job/PaperSpigot/842/
**Hardware and System:** https://gyazo.com/9dc320590a2b1b9ca885ec40dbd69281
**Many other plugins:** https://gyazo.com/bf0dd9610436d80f0dc18eae7b5d5599
**Citizens2:** http://ci.citizensnpcs.co/job/Citizens2/1409/
**Citizens config.yml:** http://pastebin.com/8fg5yCHY
**Citizens saves.yml:** Too big to pastebin. Is 806KB.
**Citizen Quantity:** We have 299 NPCs
# Performance Details

**VisualVM Sample Screenshot:** https://gyazo.com/273dfadaa2ac3c3e194bec7816b9e12c
**VisualVM Sample File:** http://files.massivecraft.com/tmp/citizens-issue.nps
**MassiveLag Timing List:** https://gyazo.com/479f8e0c75bbc0e804815e175879b057
**MassiveLag Timing Show:**
1. https://gyazo.com/193c9dce8b58ba238d2580a2a02fe6c5
2. https://gyazo.com/03738ca15aa0c8d7d538e9828344b533
3. https://gyazo.com/b57c193e8b734c6c0bd7983f2a05fadc
4. https://gyazo.com/e11d217be299f0354810d37aa8961ea1
5. https://gyazo.com/3a88ab329d7dbe581c28a3d797aef01a
6. https://gyazo.com/6c99ac6d9d3c63867e0c6754e6f075b8
7. https://gyazo.com/eab7927733d3c6a573acb89e07373567
8. https://gyazo.com/3749e4ee82eecf40ce5a161bc5eae2bf
9. https://gyazo.com/d86a13da5dbee2b5b4667ff1727851d7
10. https://gyazo.com/82c8f4d50df1c3f6bf89f9cff876cec9
# MassiveLag Explanations

The information from my plugin MassiveLag is a CPU sample for what is within the PlayerUpdateTask only. It is in this cased based on 362680 samples and should thus be really accurate. MassiveLag samples all the time the server is running and had in this case been running for 13 hours.

What comes before the execution of the actual task in the stacktrace is cut away. This is why the stack trace tree starts with the PlayerUpdateTask directly and not with how the server decided to run that task.

Recursion is removed from the stack trace. This is done by adding each StackTraceElement to a set and trashing what is already in the set from the StackTrace.

The sample tree is expanded down to a maximum depth of 30 or when the children use below 5%.
# Your Previous Questions

**Q:** How does this compare to the default entity tick?
**A:** Looking at the VisualVM sample we can see that Citizens PlayerUpdateTask uses 8.5% and the default entity tick uses 6.1%.

**Q:** How many NPCs do you have spawned, and what are they doing?
**A:** We have 299 NPCs. They mostly wait to be clicked or killed. Some stand still and some walk around a bit. We use Sentinel. We also have our own plugin MassiveQuest where you click NPCs to talk to them, though the MassiveQuest integration is really lightweight. It just checks the PNC name upon clicking it and does not do any pathfinding stuff.
# Theories and Questions

Maybe something could be optimizied in Citizens, maybe not. I'll leave that to you as developers. A\* Pathfinding can be very taxing so maybe what is required is simply configuration changes?

What config options could we change to reduce the CPU use for pathfinding? What values do you recommend we try for these and what side effects would there be?:
- `npc.default.pathfinding.range`
- `npc.pathfinding.new-finder-open-doors`
- `npc.pathfinding.attack-range`
- `npc.pathfinding.use-new-finder`
- `npc.pathfinding.update-path-rate`
- `npc.pathfinding.default-distance-margin`
- `npc.player.remove-from-list`
- `general.debug-pathfinding`

Please note that I did check http://wiki.citizensnpcs.co/Configuration but that page is not yet updated to include all new configuration options you added.

I would really appreciate some help with suggestions for config changes.

**Comment by mcmonkey4eva** [comment]
Thank you for the detailed and clear report!

It looks like a noticeable amount of pathfinding is being done (at an admittedly very short glance) indicating that may be slowing it down, as you theorized. While we wait for fullwall to address this properly, I would recommend taking a bit of time to try setting `use-new-finder` to the opposite of whatever it currently is.
(IE, if it's false, switch to true and try that, or vice versa).
When it's false, Citizens will use Minecraft's built in pathfinding code for NPCs.
When it's true, Citizens uses its own custom pathfinding code.
It's possible one of the two underperforms in your environment, and the other may work better.

Fair warning: this has the potential to change what routes an NPC will take in a given circumstance.

**Comment by fullwall** [comment]
Thanks for the detailed report - looking at your snapshot, seems like you're getting bitten a lot by having too many event listeners registered (HandlerList.unregisterAll taking up a significant amount of time). I will work on a change to call unregister less.

**Comment by fullwall** [comment]
@oloflarsson I have just pushed a build which should reduce the HandlerList lag which was skewing the snapshot. Redoing the profiling now would probably help if possible.

**Comment by oloflarsson** [comment]
I have now tested the first configuration change. I reduced `npc.default.pathfinding.range` from 25 to 16. For some reason the CPU Usage actually went up from 9% to 22%: https://gyazo.com/e26f455f2c3bfa5c239d45a05ea43e88

I'm still using the default path finder. Meaning that `npc.pathfinding.use-new-finder` is still `false`. I did update citizens to include the "small optimizations" commit, though I doubt that would increase CPU use. It's probably an effect from the changed pathfinding range.

Any ideas why this would happen? Would the A* continue searching the full set of options resulting in more CPU use if the pathfinding range reduction results in a failure? Any ideas?

Next I'll try setting the `npc.pathfinding.use-new-finder` to `true`.

**Comment by fullwall** [comment]
@oloflarsson if the path is outside the range it will check all possible paths before deciding that it cannot path to the destination. Your screenshot shows this happening (PlayerPathfinder is Minecraft pathfinding code).

**Comment by oloflarsson** [comment]
@fullwall
* Does that happen with `npc.pathfinding-use-new-finder`?
* Would it be possible to just do a distance check to realize the pathfind is impossible before even starting?
* What will happen on a failure? Is the NPC teleported to the waypoint or does it stand still?
* Is there a way to output error messages when this happens so we can find the NPCs wich waypoints we need to rework?

**Comment by Venlious** [comment]
I'm also experiencing the same lag - and my MassiveLag timings report is almost identical to the one reported by @oloflarsson 

There's none, to little, TPS drops when all Civlians are alive (100+) - however, once players enter the world and slaughter them things start to change. I believe that as soon as the NPCs respawn the lag really starts kicking in and the server sometimes ends up freezing entirely for a short while.

I'm not sure how helpful this really is - but thought it'd be worth mentioning as I've been struggling with this issue for a while now. Thinking it was just me doing a poor configuration job at first.

**Comment by fullwall** [comment]
@oloflarsson Sorry for the delay. I have just pushed an update to force stuck when outside of pathfinding range. On failure it depends on your stuck action (configurable in code but default in config is to teleport to the destination).
@Venlious Please post your timings report

**Comment by Venlious** [comment]
@fullwall Here's the timings report you requested:
**Massivelag timings report:** https://i.gyazo.com/f7581d455fd3226a92b8245d37c66383.png

_And the more specific ones, six total in my case:_
1. https://i.gyazo.com/5671833f4e0ba56d4fba1d0664261f1e.png
2. https://i.gyazo.com/3bf15e18f7253e025aa0b5cbbe5c7258.png
3. https://i.gyazo.com/91d726df738ec435ce9d07bbca0ce534.png
4. https://i.gyazo.com/1d867cc0a588ca8e08e03b62452f476a.png
5. https://i.gyazo.com/7fd5684711556d19d0c8ce8c501949be.png
6. https://i.gyazo.com/7418fa6b4b20f3ff3ce42f2360234905.png

I've also updated to the latest version and made sure all my NPCs were set to the default unstuck functionality as described by you. This didn't seem to have fixed the issue, with both the Minecraft pathfinding the system and the custom one.

**Comment by fullwall** [comment]
@Venlious hmm... for comparison would it be possible to get the timings report for use-new-finder disabled? Most of the time in pathfinding seems to be spent loading chunks which may be different in the minecraft pathfinder. Also worth noting that sentinel takes up 26% of the time.

**Comment by Venlious** [comment]
@fullwall most certainly. Apologies for the delays between every answer, I try to wait for the lag to kick in before making the timings report. TPS; https://i.gyazo.com/82f7642ea62a9417ef3a71b06e9efa62.png - the server had been running for **6** hours - this was the player count between said hours; https://i.gyazo.com/f50931a03f19537bc60a2c98a9f138f2.png

**Massivelag Timings:** https://i.gyazo.com/03d4759be1462c1e597d270467b22351.png

_And the more specific ones, six again:_
1. https://i.gyazo.com/e20ad0f2bbc365f855bee6080236286b.png
2. https://i.gyazo.com/43716e2d202ae0b72cc221f09a311332.png
3. https://i.gyazo.com/00599772ac63616402786d4a5890bcb8.png
4. https://i.gyazo.com/7f4f8c481acad2545c8de25f9f7ef636.png
5. https://i.gyazo.com/13861d1aed58c925c45328994c766787.png
6. https://i.gyazo.com/5a33bb5cd8ca0cabd35af5cbe179b1e5.png

This timings report was done with changing the pathfinding system to `use-new-finder` on `disabled`. Apart from that, I've also changed Sentinel around so it no longer uses Regex to detect the items. This seems to have worked as Sentinel now uses 6% instead of the earlier 26%.

**Comment by fullwall** [comment]
@Venlious hmm... Minecraft pathfinding took most of the time so not much Citizens can do there except do less of it. I wonder if you could maybe increase the npc.pathfinding.update-path-rate from the default of 20 if you have a lot of Sentinel pathfinding.

**Comment by Venlious** [comment]
Apparently the changes done with setting `usedefaultstuckaction` to `true` weren't saved correctly when I had updated them. I've also reduced the amount of NPCs that walk around with pathfinding and will let you know how it goes.

**Comment by fullwall** [comment]
@Venlious I think changing the stuck action won't do much... increasing the update rate might though.

**Comment by mcmonkey4eva** [comment]
Would be great to get updates on this situation - if you think there's more to improve with the current version of Citizens, please do post a new issue with updated profiling data!
