### ISSUE TITLE
"/npc path" does not "toggle"

### ISSUE THREAD

**Issue by MarkehMe** [CitizensDev/Citizens2#901]
I'm unsure if this is a bug, feature request, or a miss-understanding. 😃 

However - in help it says that ```/npc path``` will toggle the editor.. but when you execute ```/npc path``` while in the path editor it just says you're already in the editor

--
<s>Citizens v2.1.19 b1374</s> _2.0.19-SNAPSHOT (build 1374)_ - PaperSpigot b832

**Comment by mcmonkey4eva** [comment]
Neither of those are correct version IDs :(

**Comment by MarkehMe** [comment]
Oops, this was a miss-copy.

I took this from the /version command (```/verison, /version citizens```):

```
[12:01:37 INFO]: Citizens version 2.0.19-SNAPSHOT (build 1374)
[12:03:05 INFO]: This server is running Paper version git-Paper-832 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
```

I just realised I also have WanderingNPC installed ([github](https://github.com/Nutty101/TheWanderingNPC), [spigotmc](https://www.spigotmc.org/resources/the-wandering-npc.10024/)), alongside Sentinel so perhaps that is conflicting?

**Comment by mcmonkey4eva** [comment]
First, update Citizens: http://ci.citizensnpcs.co/job/Citizens2/
If that doesn't help, check your console/logs for errors.
If there is any error, post it here.
If not, try removing wanderingnpc and take another try at everything.

**Comment by mcmonkey4eva** [comment]
@MarkehMe I looked at the code for wanderingnpc, it's an absolute wreck and very very likely to cause this and other problems, definitely delete that and search for an alternate solution :(

**Comment by MarkehMe** [comment]
Looks like WanderingNPC is causing the issue. I'll take it off on your advice, perhaps there is a better solution (or time for me to start using denizen)
