### ISSUE TITLE
My Citizens dont work? Help Request

### ISSUE THREAD

**Issue by Zigziig** [CitizensDev/Citizens2#902]
My Citizens dont work and i cant find a way to fix this
Info:
- This is a Help Request
- My console says this when starting the server: http://pastebin.com/ceChnq0w
- Minecraft Version: 1.8.8
- Citizens Version: 2.0.20
- My plugins on the server: https://gyazo.com/f2429a0f29c7e5bdafed93ff3e40d503

**Comment by mcmonkey4eva** [comment]
Get rid of citizensAPI, that's not needed for you.
Download the version of Citizens2 to match your server version here: http://wiki.citizensnpcs.co/Versions
