### ISSUE TITLE
Traits with upper-case letters fail to load

### ISSUE THREAD

**Issue by Darkyenus** [CitizensDev/Citizens2#903]
### Bug report

Citizens tries to have trait names case-agnostic ([judging by the .toLowerCase() call here](https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/CitizensTraitFactory.java#L154)), but it fails to include lower-case conversions everywhere (no conversions [here](https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/CitizensTraitFactory.java#L166) or [here](https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/trait/TraitInfo.java#L31), but it is [here](https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/trait/TraitInfo.java#L58)). Due to this bug, traits with upper case names fail to load with unhelpful error message.

*Version: latest*

**Comment by fullwall** [comment]
Fixed.
