### ISSUE TITLE
Citizens Skin not always loaded

### ISSUE THREAD

**Issue by Frenchtirox** [CitizensDev/Citizens2#904]
Hi, my server is on spigot 1.8 and i use the citizens 2.0.14 versions. 

When i go far and come back my skin on a npc didn't work. It's just a steve skin. How can i do to see the skins on the npc all the times please ?

Thank's if you help me and sorry for my very bad english.

**Comment by mcmonkey4eva** [comment]
Update your server.

**Comment by MarkehMe** [comment]
I have this issue myself.. it had worked previously. 

* PaperSpigot 1.10.2 build 832
* Citizens 2.0.19 build build 1374

![](https://www.dropbox.com/s/yqbgwkqm740vsfo/Screenshot%202016-09-02%2013.58.47.png?dl=1)

http://minecraft-skin-viewer.com/player/dadralord505

Heres what I tested with:

```
[13:58:13 INFO]: MarkehMe issued server command: /npc create test
[13:58:17 INFO]: MarkehMe issued server command: /npc lookclose
[13:58:24 INFO]: MarkehMe issued server command: /npc skin dadralord505
[13:58:39 INFO]: MarkehMe issued server command: /npc rename dadralord505
```

**Comment by Frenchtirox** [comment]
I can't update my servers :/ No issues for 1.8 ?

**Comment by Ugikie** [comment]
can we get a bump? also having this problem and now when I go too far out of range (warping somewhere) the npcs just despawn and I have to use /citizens reload

I am on Spigot version 1.10.2 and using Citizens v2.0.19 build 1374

Really need to figure this one out, please help if you can!

**Comment by mcmonkey4eva** [comment]
ALways update before posting. 2.0.20 Citizens is available.

That said, skins are an active issue - Mojang mucked up the systems it works by. @fullwall doesn't know what to do beyond the improvements and workarounds 2.0.20 contains.

**Comment by mcmonkey4eva** [comment]
With all the changes to the skin system that have happened, this issue is too outdated to remain relevant. Feel free to open a new issue if you have trouble with current builds
