### ISSUE TITLE
Guardian teleporting?

### ISSUE THREAD

**Issue by AlexServers** [CitizensDev/Citizens2#906]
I have a bug that I would like to report. I create an npc with the name "Guardian". It works and all that, but I want to make it move around. So I use the waypoint editor, and then create my waypoints. Then all of a sudden, it starts TELEPORTING to that waypoint. I would like it to move (like walk) to the waypoint and back.

Thank you,

AlexServers

Citizens version 2.0.16-SNAPSHOT (build 1267)
MC version 1.8.8

**Comment by mcmonkey4eva** [comment]
Fair warning, if a fix is made for this (assuming it hasn't been already), it will only be available for 1.10+ not 1.8.8

**Comment by AlexServers** [comment]
all right, anyways

**Comment by pseigo** [comment]
Same thing for me with guided waypoints on 2.0.27-b2277 (1.16). Can't get an NPC to move between distant destination nodes w/o teleporting.

**Comment by fullwall** [comment]
Vague report?
