### ISSUE TITLE
Citizens plugin isnt working.

### ISSUE THREAD

**Issue by VortexHDPlays** [CitizensDev/Citizens2#907]
I have a minecraft server and its 1.8.8 and I had 1.8.8 and I had Citizens automaticly i reset my server ages ago and Citizens didnt work anymore.. I have the host: MCPH, and im confused why it doesnt work anymore. Because I want CommandNPCS, and CommandNPCS is depencity of Citizens I enjoyed Citizens in the past, and i know its avaible for 1.8.9, because Mineplex has CommandNPCS and the serveri s 1.8.9/1.9/possibly 1.10. and my server is 1.8.9/1.9. im confused please help me!

**Comment by mcmonkey4eva** [comment]
Check your versions at https://wiki.citizensnpcs.co/Versions
Also, use Denizen not CommandNPC.
