### ISSUE TITLE
Citizens not working...

### ISSUE THREAD

**Issue by dragonstalker28** [CitizensDev/Citizens2#908]
I recently downloaded Citizens trying to find a good plugin for our staff room on our new server. Our server version is 1.7.10 and we downloaded the 1.7.10 version but for what ever reason when we start up the server with the newly downloaded plug in it shows red on the plugin list. What are we doing wrong? Is there a plugin that needs to go with it? We are totally confused and any help you can give us would be much appreciated. Thank you all :)

**Comment by mcmonkey4eva** [comment]
You're using an incredibly old version.
You can see old version here: https://wiki.citizensnpcs.co/Versions
If you're on cauldron, use this one: https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar
