### ISSUE TITLE
Real player teleported to NPC

### ISSUE THREAD

**Issue by sigmaroot** [CitizensDev/Citizens2#910]
A player is teleported to a NPC which has the same name, when the npc is loaded, spawned or the plugin is reloaded (/citizens reload).

This server is running Paper version git-Paper-842 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Citizens version 2.0.20-SNAPSHOT (build 1416)

Any suggestions?

**Comment by fullwall** [comment]
What config are you using?

**Comment by sigmaroot** [comment]
http://pastebin.com/aQRNsbtA

**Comment by fullwall** [comment]
@sigmaroot - I wonder if it's because they have used /npc playerlist on that NPC?

**Comment by sigmaroot** [comment]
No, this player don't know about this command :cry:

**Comment by sigmaroot** [comment]
Okay, it seems to work now. Removing the npc, restarting the server and recreating the npc seems to solve this issue. I dunno what was causing that to happen, maybe a wrong npc configuration.

I'll reopen this, if this happens again.

**Comment by sigmaroot** [comment]
Okay, this was not the solution. Players are teleported to NPC when using /citizens reload.

Please verify.

**Comment by fullwall** [comment]
What plugin do you use to make the player's name more than 16 chars?

**Comment by sigmaroot** [comment]
I don't use a plugin to make it longer than 16 chars. JessicaLamaertzx is exactly 16 chars.

BTW: It is not only JessicaLamaertzx, it's every player...

Can this be caused by CompatNoCheatPlus?

**Comment by fullwall** [comment]
> BTW: The name of that player is longer than 16 chars: JessicaLamaertzx

Oh, I wondered if you had a problem specifically with long NPC names.

**Comment by sigmaroot** [comment]
Oh, I'm sorry. No, it is exactly 16 chars.

But I'm having the same issue like #883 
Playernames longer than 16 chars (including color codes) are split / skipped and only the last chars are displayed on the name tag. But that has nothing to do with this issue.

**Comment by mkcoldwolf** [comment]
Yo i got the same problem at it, And i am lucky bcs i just add a plugin and that make this problem so i found out this easily. sorry about for bring back that old foums, i use Citizen API and NoCheatPlus, the NoCheatPlus make this problem, ill report to NocheatPlus this bug, u should check ur anticheat Plugins
, and it should  be fix

**Comment by sigmaroot** [comment]
Thanks, yea this is still a problem. It was also my idea that it has something to do with NoCheatPlus but I dunno how to fix this.

Thanks for your help and reporting to NCP!

**Comment by M450NC** [comment]
I'm also still having this issue. VERY frustrating. Any ideas on a fix?

**Comment by mcmonkey4eva** [comment]
if NCP is at fault, it'd reasonably be down to NCP developers to fix...

**Comment by mcmonkey4eva** [comment]
far as I can tell, it wasn't ever actually reported at https://github.com/NoCheatPlus/Issues/issues
