### ISSUE TITLE
Can't Change NPC skins

### ISSUE THREAD

**Issue by seeker17** [CitizensDev/Citizens2#913]
First let me start by saying that I am new to running a server and that I sorry if I ask any dumb questions.

I am having an issue which changing the skin on my npc's. I do /npc skin -p (name) and it tells me
 "(npc name)'s skin name set to (player name)" but the skin does not update, I have tried leaving the chunk, reloging, and restarting the server. It seems that nothing will cause the skin to change.

I am on Citizens v2.0.19-SNAPSHOT (build 1374)

**Comment by mcmonkey4eva** [comment]
First: update, http://ci.citizensnpcs.co/job/Citizens2/
As for the issue:
- Try removing `-p` to see if that makes a difference.
- Make sure you're on a properly configured online-mode server.
- Make doubly sure the player name you chose is definitively exactly correct, and has a custom skin.

If none of that helps, please post the playername you're trying and also pastebin your config file so we can see if it's related to the name or your installation.

**Comment by seeker17** [comment]
Thanks for the speedy reply!
I am still having this issue sadly.

- I updated to the latest version (citizens v2.0.20-SNAPSHOT (build1418)) 

- The server that I am using is in online mode (according to the server.properties)

- I am trying to change a npc to my own skin, My minecraft name (case sensitive) is seeker17(I have tried other names with no success). I am typing it correctly. Screenshot to shot provided here: https://gyazo.com/5ec9cb3e95c81d284c949887930ab109

- The paste bin to my config: http://pastebin.com/JdaBYuCn

Are there any plugins that could be causing this to happen?

**Comment by mcmonkey4eva** [comment]
Generally a plugin shouldn't mess with it.

Another potential risk is if you're on a shared host (IE, a generic minecraft server where other servers might be using the same IP to save space for a hosting company) in which case it's possible a different server on the address has a lot of skin loads (from NPCs or skull items) and got the system blacklisted by Mojang.

To test this, try to spawn a custom skull item with a skin of a random player valid player name.

**Comment by seeker17** [comment]
I try to give myself my own player head (command below)

/give @p minecraft:skull 1 3 {SkullOwner:"seeker17"}

and I given an error "Error: Player not found"

**Comment by mcmonkey4eva** [comment]
You might have to put it in a command block for that to function, Bukkit/Spigot is weird with that.

**Comment by seeker17** [comment]
It gives me a normal no skin'ed player head, but it does say that it is my head. If it place it down it is still steve

**Comment by mcmonkey4eva** [comment]
then yeah, you're probably on an IP that mojang has forbidden from using skull/NPC skins :/

**Comment by seeker17** [comment]
If this is the case what do you suggest that I do?

If I contact the host would they be able to do something so that skins would work for us again?

Is there away to have a  npc get a skin form a .png file from the ftp?

What do you think would be the best course of action?

**Comment by mcmonkey4eva** [comment]
It's not really the host's fault. They just oversell too much, they're not going to change that for your NPC skins.

You have a few options still though!

The first is the best: Get your own server guaranteed personal IP address - no reselling of the same IP. If your present host offers this service it's usually like a buck or two extra per month. If not, you'd have to change hosts - which I'd strongly recommend if your present host is so restrictive they don't allow you your own IP.

The other option is awkward but works too: Set up a local private server on your home PC, use `/npc skin -p <name>` on that server to get an NPC wearing the correct skin, then copy its data from the `saves.yml` file to your other server's `saves.yml` - it **might** just casually work if you do that, no guarantees.
