### ISSUE TITLE
Citizens Breaking Scoreboard

### ISSUE THREAD

**Issue by Curtis73** [CitizensDev/Citizens2#915]
Bug Report.

Hello there. I have recently updated my Minecraft version to 1.10.2, and citizens to v2.0.20 (Build 1419), and I am getting a weird bug where it is messing up the scoreboard. lets say that I make a team called "Owner", and set the team color to purple, I would join that team for about 30 seconds, but then I would be added to a random group, belonging to Citizens. [http://prntscr.com/cg3qzc]. I have searched through the configs, and have tried with tablist: disable on true and false, same with   player-scoreboard-teams: true and false.

Configs:

[http://pastebin.com/XZiJCYsc]

Thanks!

**Comment by Jocke155** [comment]
Happens for me too, it breaks the default scoreboard, and when I use tab I can sometimes see the NPCs' as an online player in the tab list. (For a few ticks)

**Comment by Curtis73** [comment]
Can anything be done about this?

**Comment by mcmonkey4eva** [comment]
I believe there's a config option somewhere that will disable this action in the newer version.

**Comment by Curtis73** [comment]
Is it:
`  player-scoreboard-teams:
    enable: true`

Is that meant to be false? I keep trying to change it but it jumps back to true..?

**Comment by mcmonkey4eva** [comment]
That's the right one I think.

You have to shut down your server to edit that config file for some reason atm.

**Comment by Curtis73** [comment]
Just did it - didn't work.

**Comment by Curtis73** [comment]
Does anyone have any suggestions?
It's causing quite a bit of a problem on my server.

**Comment by mcmonkey4eva** [comment]
Edit the config setting - if it self-resets as you mentioned, you likely have a file handling error, or are not editing it while the server is offline
