### ISSUE TITLE
Kcauldron + Citizens

### ISSUE THREAD

**Issue by petitecolier** [CitizensDev/Citizens2#919]
Hello,

I am running a server on kcauldron 1.7.10. We added citizens version 1.7.10 and it was not working. Is there a specific version we must add for kcauldron? Or is it just an error on our part?

**Comment by mcmonkey4eva** [comment]
Need the special MCPC/Cauldron build: https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by petitecolier** [comment]
It works! Thank you so much for your help. You really saved our server
