### ISSUE TITLE
Bug: Equipping does not work / Inventory bug

### ISSUE THREAD

**Issue by iFalcon720** [CitizensDev/Citizens2#920]
Unable to equip NPC's mainhand and offhand; Right clicking npc removes mainhand item and creates skeleton and villager sounds (Sounds may not be caused by Citizens)
Citizens Version: 2.0.20-SNAPSHOT
Minecraft Version: 1.10.2 (Spigot)
Citizens Config: http://pastebin.com/YCG2ALGp
Citizens save example: http://pastebin.com/6DTjgfZU

Seems that when rightclicking (Empty hand) an npc who has items in both hands, the mainhand item is pushed to the inventory.

**Comment by mcmonkey4eva** [comment]
Sorry for never replying to this issue.
The issue is very likely resolved by equipment changes done in the time since.
If you're still having issues, please open a new issue.
