### ISSUE TITLE
Owner Trait  (getOwnerId() & isOwnedBy(UUID)) return null's.  

### ISSUE THREAD

**Issue by Nutty101** [CitizensDev/Citizens2#921]
Tested with 1419 and it's returning NULL's on that as well.

Owner ownerTrait = npc.getTrait(Owner.class);
Boolean a = ownerTrait.isOwnedBy(sender));  //java.lang.NullPointerException
UUID b = ownerTrait.getOwnerId(); //returns a null

Name based is working fine.

**Comment by fullwall** [comment]
Is sender null? UUID is expected to return null sometimes if you look at the javadoc.

**Comment by fullwall** [comment]
Looking here: https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/trait/trait/Owner.java#L50 I can't see any case where an NPE would occur under normal conditions.

**Comment by Volkenstein666** [comment]
The only time an NPC has returned null on owner for my server is when the original creator of the NPC has had their files completely wiped. In that case I set NPC owner as 'server' or myself

**Comment by Nutty101** [comment]
Man how did I miss the earlier response's to this. Sorry about that.  It would make sense as if I recall I was getting this on my devserver in testing. That gets restored all the time due to random stuff etc, so I can see this happening that way. Closing this out, again sorry for not catching your response on this one @fullwall.  Also thanks Volkenstein for the note on this, makes sense.
