### ISSUE TITLE
Waypoint Provider Guided dont work

### ISSUE THREAD

**Issue by xXMrGXx** [CitizensDev/Citizens2#922]
Waypoint Provider Guided dont work.
NPC can use destination points, if they are in pathfindrange range.
If a destinationpoint is more than the pathfindrange away, but connected with guide points, the npc teleports to the destination point instead walking there by using the guide points.
Option "use-new-finder: true" doesnt help.
Version: Spigot 1.1.0

**Comment by fullwall** [comment]
OK, will look into this

**Comment by fullwall** [comment]
Can't reproduce.
