### ISSUE TITLE
text editor issue

### ISSUE THREAD

**Issue by TheaPMC** [CitizensDev/Citizens2#924]
bug:
I have citizens 2.0.19 (alpha 1 for MC 1.10) installed on a spigot 1.10.2 server, it's loading fine, am able to spawn the npcs etc, type in /npc text it brings up the list of options just fine, type add and ... nothing. I just say add in chat.  It's a bungeecord server, not sure if that has something to do with it?

I've gone through the congif and made sure talk-close: is set to true

I have the perms added including citizens.npc.edit.text and citizens.npc.talk (we use bungeeperms).

the npcs do their "Hi, I'm <npc> line just fine,

I've also tried edit and the other commands same result, it just returns posts the word edit in chat.

**Comment by mcmonkey4eva** [comment]
Generally we'd advise using Denizen - http://wiki.citizensnpcs.co/Denizen - for text chatting NPCs.

**Comment by TheaPMC** [comment]
hi, thanks for the reply.... however, that looks pretty complicated. :/

Am I to assume then that there's no fix? :(

**Comment by mcmonkey4eva** [comment]
Tbh I don't know what the problem is, because like most people I Don't use that at all... Denizen is nice, and has great setup tutorial videos - http://one.denizenscript.com/denizen/vids it's not hard to do basic things.

**Comment by TheaPMC** [comment]
ok well I'll look at it closer, thanks!
