### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by IndyLukes** [CitizensDev/Citizens2#926]
When we try to install citizens for 1.10 on my friends server, it doesn't work. it says in the console that the plugin has installed but it just doesn't show up in game

**Comment by mcmonkey4eva** [comment]
Are you sure you have the correct version?
https://wiki.citizensnpcs.co/Versions

**Comment by IndyLukes** [comment]
@mcmonkey4eva when I look at that list I see nothing for 1.10. We tried using 2.0.19, but we really are having no luck. Nothing comes up in game

**Comment by calico-kid** [comment]
sounds like you need 2.0.20

**Comment by mcmonkey4eva** [comment]
@IndyLukes it says: `Latest Citizens builds [1.10] are always available here[1] ` which links to: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by IndyLukes** [comment]
@mcmonkey4eva ok I will try 2.0.20

**Comment by IndyLukes** [comment]
@mcmonkey4eva  the plugin didn't work. Nothing shows up in game. no plugin, no commands, anything

**Comment by mcmonkey4eva** [comment]
@IndyLukes please pastebin a startup log

**Comment by IndyLukes** [comment]
@mcmonkey4eva http://pastebin.com/8uWPCAb9

**Comment by Morphan1** [comment]
That doesn't look like a full startup log. Or if it is, then you don't have Citizens properly installed.

**Comment by mcmonkey4eva** [comment]
It's a backwards log for some reason.

But yeah, there's no mention of Citizens in there at all.

Make sure you have the Citizens2 jar file in your plugins folder.

**Comment by IndyLukes** [comment]
@mcmonkey4eva can you link me to that?

**Comment by mcmonkey4eva** [comment]
Once again, it is at http://ci.citizensnpcs.co/job/Citizens2/
