### ISSUE TITLE
Error Message {Spigot 1.8.8 Build #45} {Citizens: 2.0.14}

### ISSUE THREAD

**Issue by FastSex** [CitizensDev/Citizens2#928]
I just installed Citizens, to make NPCs of all of the staff members, and this error message came up. I dont know whats wrong with it, maybe its an incorrect version?

29.09 20:36:54 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
29.09 20:36:54 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
29.09 20:36:54 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
29.09 20:36:54 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
29.09 20:36:54 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.09 20:36:54 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
29.09 20:36:54 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
29.09 20:36:54 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
29.09 20:36:54 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
29.09 20:36:54 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
29.09 20:36:54 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
29.09 20:36:54 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
29.09 20:36:54 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
29.09 20:36:54 [Server] WARN at java.lang.Thread.run(Thread.java:745)
29.09 20:36:54 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
29.09 20:36:54 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
29.09 20:36:54 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
29.09 20:36:54 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
29.09 20:36:54 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
29.09 20:36:54 [Server] WARN ... 28 more

**Comment by mcmonkey4eva** [comment]
You downloaded the wrong version of Citizens, grab the correct one at http://wiki.citizensnpcs.co/Versions
