### ISSUE TITLE
Citizens Flickering

### ISSUE THREAD

**Issue by MandiKro** [CitizensDev/Citizens2#929]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

This is a bug description, so I have bought the leaderboard heads plugin for $12.50, and it has citizens as a hook plugin. Whenver I click TAB, the players are always flickering, please add me on Skype: `<removed>` for more information regarding it, it's more easier to understand if you join the server, thanks.

**Comment by mcmonkey4eva** [comment]
We're not going to add you on skype or join your server.

Are you moving around when thinks are flickering? or even rotating in place?

**Comment by RobiRami** [comment]
Just to add this: LeaderHeads respawns the NPC every 30 seconds to change its nametag and avoid the 16 character limit. (see issue [883](https://github.com/CitizensDev/Citizens2/issues/883))
