### ISSUE TITLE
Yaml errors with template usage

### ISSUE THREAD

**Issue by Azfaloth** [CitizensDev/Citizens2#930]
in Citizens version 2.0.20-SNAPSHOT (build 1415)

When I try to make an NPC template, I get several errors when I make templates from NPCs that have text, or skins applied or items equipped.

The logs are something like this:
[errors.txt](https://github.com/CitizensDev/Citizens2/files/504423/errors.txt)

**Comment by BlackCoyote** [comment]
Could you show us your template configuration?

**Comment by Azfaloth** [comment]
Various errors occur, some while creating an NPC with the template. Some while creating the template itself and some while making an NPC with a template. And the skins never carry on to the NPCs creating using the template.

This is my template file. the bandit2 template works in all ways but the others all give various errors.

I hope this is helpful
[templates.txt](https://github.com/CitizensDev/Citizens2/files/504464/templates.txt)

**Comment by fullwall** [comment]
Thanks, will investigate
