### ISSUE TITLE
Creating NPC failing

### ISSUE THREAD

**Issue by AliumCraft** [CitizensDev/Citizens2#931]
This is a bug report because whenever I try to create an NPC in my plugin or in game it will put this error out:

https://gyazo.com/3b05f595a4eade74109aebb1f2fd2ab1

My minecraft version is 1.9 and my citizens version is 2.0.17

This is also the code I was using:
```
@Override
	public void createNpc(EntityType type, String name, Location spawnLocation, UUID uuid, int id) {
		NPCRegistry registry = CitizensAPI.getNPCRegistry();
		NPC npc = registry.createNPC(type, uuid, id, ChatColor.translateAlternateColorCodes('&', name));
		npc.spawn(spawnLocation);
	}
```
Also while I have this ticket open I was wondering how I can change the skin of the NPC?

**Comment by mcmonkey4eva** [comment]
Update Citizens: http://wiki.citizensnpcs.co/Versions
and `/npc skin <name>`

**Comment by AliumCraft** [comment]
I want to change the skin from my code :P and thanks

**Comment by mcmonkey4eva** [comment]
You can check the source code of any command as a reference: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/commands/NPCCommands.java#L1500

**Comment by AliumCraft** [comment]
Thanks!

I seem to be having trouble removing the npc though, I've tryed to use npc.despawn(DespawnReason.REMOVAL); and npc.destroy(); and whenever someone joins the server it crashes and then it's gone when the server starts up.

Also is there a way to set the NPC's skin to that of a player from a UUID?

**Comment by mcmonkey4eva** [comment]
For some reason that code still uses names, so *shrug*. And what's the server crash error message?

**Comment by AliumCraft** [comment]
https://gyazo.com/3c7e1bd2cc283397a12f12787301ddaa

**Comment by mcmonkey4eva** [comment]
it looks like Citizens is not loaded or otherwise in an errored state by the time that message shows - is there perhaps an error earlier on?

**Comment by AliumCraft** [comment]
Oh I think I know why, when I did it I spawned a npc without despawning the old one, all with the same id, let me try removing the previous one before setting the new one

**Comment by AliumCraft** [comment]
Ok yeh that was the problem. So now I have another problem, when I set the SkinName to my skin it set's it to something else

**Comment by mcmonkey4eva** [comment]
... what?

**Comment by AliumCraft** [comment]
My code: http://pastebin.com/XLBqdXsN
https://gyazo.com/4e0cae859806be9b0d0d083e622594c8

(My name is Sorry4WreckingU) and that's my skin in the middle, but that's the skin it's setting to on the sides.

**Comment by mcmonkey4eva** [comment]
That would be the skin of Wiseman: http://mcskinsearch.com/skin/Wiseman

npc.getEntity is only available while the NPC is spawned.

**Comment by AliumCraft** [comment]
Oh lol, but even when I had npc.spawn before the checking if npc.getEntity() is a SkinnableEntity it would do the same thing

**Comment by AliumCraft** [comment]
Never mind!! It worked haah

**Comment by AliumCraft** [comment]
One problem tho, on initial server startup the NPC isn't a SkinnableEntity but after that it is?

**Comment by mcmonkey4eva** [comment]
NPCs are not spawned at startup - they are spawned at earliest after a full tick after server start - and even then, you have to wait for their chunk to be loaded.

**Comment by AliumCraft** [comment]
ok thanks
