### ISSUE TITLE
Setting NPC skin uses previously cached player skin

### ISSUE THREAD

**Issue by MrStickmanPro1** [CitizensDev/Citizens2#933]
I have noticed that setting the skin of an NPC with `/npc skin <name> -p` (without the `-p` option as well) does not use the most recent skin of the specified player but rather uses a previous one they played with (probably the one they had when citizens updated its cache the last time).

This makes it extremely complicated to give NPCs a custom skin without restarting the server every time I want to apply a new skin.

It would be better to update the cache when the `/npc skin` command is executed.

**Comment by fullwall** [comment]
Try latest build?
