### ISSUE TITLE
Citizens API get selected NPC

### ISSUE THREAD

**Issue by ipsk** [CitizensDev/Citizens2#936]
This is a help request with the API.

Hello, I've been trying to use the API to make a command on right click plugin, but I've encountered a problem, how do I get the NPC ID of the selected NPC?

Cheers.

**Comment by mcmonkey4eva** [comment]
`CitizensAPI.getDefaultNPCSelector(),getSelected( ... )`

**Comment by ipsk** [comment]
Omg it was this simple.
I'm really sorry, it's my first time working with it and I'm also new to making plugins.
But thank you, it worked perfectly.
