### ISSUE TITLE
NPC can be attacked with fishing rod

### ISSUE THREAD

**Issue by netlangthien** [CitizensDev/Citizens2#937]
As in the title, npc can be hit with fishing rod even in gamemode 1 and inside WG region which disable pvp. WG still send msg to player that they cant attack but the NPC still get hit and pushed away. And it seem like the fishing rod can only hit npc when target on the npc's leg. Because of that, the npc will be pushed away the location I want. So I have to teleport them again and again.
Currently I'm using Spigot 1.10.2 with the default config.

**Comment by fullwall** [comment]
Believe this is fixed
