### ISSUE TITLE
Problem....

### ISSUE THREAD

**Issue by JHost-iso** [CitizensDev/Citizens2#938]
In this issue, please include:
- whether this is a bug description or a feature request
  The problem is that it disappears NPC. As soon as he walked away from the NPC disappears and is no longer is presented until Reload plugin
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
  http://pastie.org/private/3hjcxgbdfmbkqdju6dgfxq
- Minecraft & Citizens version if relevant
  MC 1.8.1, Citizens 1295, value 1.5.6

**Comment by mcmonkey4eva** [comment]
... `MC 1.8.1`? What? `value 1.5.6`? Again, what?

**Comment by JHost-iso** [comment]
Minecraft 1.8.1, plug Vault version 1.5.6

**Comment by mcmonkey4eva** [comment]
Minecraft 1.8.1 isn't a valid Spigot version.
Only 1.8, 1.8.3, 1.8.6->1.8.8

Either way, it's an ancient version and at the moment we're focused on the latest version (1.10)

**Comment by JHost-iso** [comment]
2.0.14
Updated for Minecraft 1.8.1
https://dev.bukkit.org/bukkit-plugins/citizens/files/52-2-0-16-beta-1-for-mc-1-8-8/

so that you advise me? how to solve this problem?

**Comment by mcmonkey4eva** [comment]
That was a typo on fullwall's part.

And yeah I'd advise an update, as that's the resolution to the best I can make out of what you're even saying here.

**Comment by JHost-iso** [comment]
but the other plug-ins to higher versions are not obnovlyayutsya, Mauger even tell what area the problem

**Comment by mcmonkey4eva** [comment]
If you can't find an update or functional version past 1.8 for a plugin, drop or replace the plugin, it's not worth leaving your minecraft server weak and outdated just cause a few plugins are no longer maintained :(
