### ISSUE TITLE
[Skin] NPC

### ISSUE THREAD

**Issue by zZeroPlays** [CitizensDev/Citizens2#939]
- My error is: No have skin in the NPC, if execute command /npc skin <Skin_Name> no change, is Steve or Alex!
  - No Have bug in Console
  - My Minecraft version is: Spigot 1.8.8 (1.8.*)
  - My Citizens version is: 1.0.16

**Comment by mcmonkey4eva** [comment]
Please update your server to 1.10


Also, ensure you own your full IP address range - Minecraft servers are not able to retrieve skin data on a shared host. (Mojang blocks them)

**Comment by zZeroPlays** [comment]
No have possibility update my server to 1.10.

And, My server is Hosting by LandHosting, IP public!

**Comment by mcmonkey4eva** [comment]
If your IP is shared and you can't update, there's nothing we can do to fix skins on your server :( sorry :/

**Comment by zZeroPlays** [comment]
If I change my IP and NOT updater my version to 1.10 is resolved?

**Comment by mcmonkey4eva** [comment]
So long as you fully own the IP address, not shared, then probably it should work, with some bugs.

**Comment by zZeroPlays** [comment]
Finish!


Thank You!
