### ISSUE TITLE
saves.yml empty?

### ISSUE THREAD

**Issue by gerardvanschip** [CitizensDev/Citizens2#940]
**bug description**
The saves.yml file remains empty. I ran the save command, restarted the plugin, restarted the server yet the file stays empty but created 3 NPC's and they showed up after restart so they have to be saved somewhere.

**Software**
Spigot 1.10.2
Citizens 2.0.19 (alpha 1 for MC 1.10)

**Comment by mcmonkey4eva** [comment]
... You've gotta be looking in the wrong location then. 0.o

**Comment by gerardvanschip** [comment]
Right and wrong. Discovered that the config has 98 blank lines. I thought that was maybe a screwup on my part so deleted the config, restarted the server but again, the config starts at line 99. So not a bug as rather an annoyance.

**Comment by mcmonkey4eva** [comment]
Well. That's... odd. But, it's fine, as that file's not meant to be messed with by humans.

**Comment by axemwa** [comment]
@mcmonkey4eva 
Wish I knew this earlier haha me such fool
