### ISSUE TITLE
Can't remove NPC

### ISSUE THREAD

**Issue by gerardvanschip** [CitizensDev/Citizens2#941]
**bug description**
Can't remove NPC. I used the /npc select command, then the /npc remove followed by /citizens save to force save to disk, when I reload the NPC is back.

**Software**
Spigot 1.10.2
Citizens 2.0.19 (alpha 1 for MC 1.10)

**Comment by mcmonkey4eva** [comment]
First, update to 2.0.20: http://ci.citizensnpcs.co/job/Citizens2/

If it persists after the update, check your console for any odd messages.

**Comment by Luky584** [comment]
I have the same problem, no other console messages.
