### ISSUE TITLE
[Minecraft 1.9 Viaversion | compatible with 1.10] Wont work

### ISSUE THREAD

**Issue by ProCakeMan** [CitizensDev/Citizens2#942]
Ive downloaded Citizens and CitizensAPI and i also have vault but when i do /pl
Citizensn is not green but red?! And wont work please help!

**Comment by mcmonkey4eva** [comment]
Don't download the API.
Download the version of Citizens that matches your actual server version exactly (do `/version` to check) from here: https://wiki.citizensnpcs.co/Versions

**Comment by LimitedGames** [comment]
Is this ''Open'' or forgoten to close? Becouse in my server (1.8.7) Citizens Does work, and i have the newest version of ViaVersion..
Maby you have the wrong Citizens version? Or maby the issue is at the CitizensAPI.
