### ISSUE TITLE
Citizens and cratekeys issue

### ISSUE THREAD

**Issue by DarkPklord3** [CitizensDev/Citizens2#943]
Bug Report with CrateKeys

Multiple users have reported it to him and it seems this is more an issue with citizens and not cratekeys, despite cratekeys not loading and citizens loading

we're getting this error on startup:
http://pastebin.com/A1hEc8Zf

And this error on disable:
http://pastebin.com/9DFxekf7

After I take citizens out of the equation, though, it works fine.
I know for me, personally, I'm using the latest version of cratekeys & I've tried the latest dev builds of citizens and I've bought the plugin on spigot and used the most current download provided there. The issue happens with both.

I'm using minecraft 1.10.2

**Comment by mcmonkey4eva** [comment]
It looks like `cratekeys` forgot to list `Citizens` on the `plugin.yml` depends list, and thus is borking out when it tries to load a Citizens-related section of code before Citizens itself loads.

**Comment by DarkPklord3** [comment]
Is Citizens being loaded after CrateKeys? The plugin would not be throwing that error if it was not loading after Citizens. Definitely not on my side.

Is from picknchew (cratekeys author) in response to the above

**Comment by Morphan1** [comment]
CrateKeys loading before Citizens is the only way that error could occur.
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/Citizens.java#L258
I'm not sure what's making him or her think it should be properly loaded, and as far as I can tell there's no source code we could look at to help out. This is definitely a CrateKeys issue.

**Comment by DarkPklord3** [comment]
This is my full startup log, im providing this same pastebin with cratekeys. Maybe it will clear up some confusion. Not really sure who to get support from at this point as cratekeys thinks its citizens and vice versa

 http://pastebin.com/utw1T0mc

**Comment by Morphan1** [comment]
You can clearly see that CrateKeys is being enabled at line 658, while Citizens is being enabled at 749. In fact, you seem to have 2 other plugins *properly* hooking into Citizens below that. There's not a whole lot we can do to help from our side.
