### ISSUE TITLE
NPC's have invisible armor. (Bug)

### ISSUE THREAD

**Issue by KeiwaM** [CitizensDev/Citizens2#944]
Whenever I equip an NPC with armor and weapons, the armor dissappears on reload or restart even if I do /citizens save. They keep the weapon, text, everything I've done with them except the armor.

When I go to /npc equip and Shift+RMB they drop all the items including the armor that wasn't visible. I Can equip it again then and it's fine until the next reload or restart.

Minecraft 1.9.2

**Comment by mcmonkey4eva** [comment]
Old bug, update your server.
