### ISSUE TITLE
Server crashing...

### ISSUE THREAD

**Issue by skulltraill** [CitizensDev/Citizens2#945]
MC: This server is running CraftBukkit version git-Spigot-570526c-75a8885 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Citizens: =====[ Citizens v2.0.20-SNAPSHOT (build 1419) ]=====

Log of crash: http://pastebin.com/YAqjBGvv

Now I'm not too sure if it actually is a citizens issue, but someone who knows more about MC than me said it might be, so I thought of reporting it.

If you could take a look, I'd really appreciate it.

**Comment by fullwall** [comment]
Pastebin your saves.yml
