### ISSUE TITLE
SkinChange skin dont appair

### ISSUE THREAD

**Issue by LimitedGames** [CitizensDev/Citizens2#947]
Minecraft Version: 1.8.7
Citizens version: 2.0.16
If i set a npc withe the name of a player, and the player will change his skin the npc wont update, after restart is also doesnt update. But if you set a new npc and give him the playername-skin it will be the new skin of the player, but it still doesnt update the first npc.

**Comment by mcmonkey4eva** [comment]
Update your server; MC 1.10 and Citizens 2.0.20 are available.
