### ISSUE TITLE
Citizens UpdateTask Lag

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#948]
The UpdateTask causes lag:
https://timings.spigotmc.org/?url=hekadupigu

What exactly is it doing? How can I reduce lag?

**Comment by mcmonkey4eva** [comment]
What's your Citizens2 config? How many human-type NPCs do you have?

**Comment by bloggy** [comment]
Here is my config:
http://hastebin.com/naxuwodari.swift

The saves.yml has 18000 lines, but I dont know how many NPCs of type human.

**Comment by mcmonkey4eva** [comment]
`The saves.yml has 18000 lines, but I dont know how many NPCs of type human.`
You might just have ridiculously way too many NPCs 0.0

**Comment by bloggy** [comment]
Shouldn't matter at all? Because they are only loaded when someone is near, and they are placed everywhere in the world. Or am I wrong?
