### ISSUE TITLE
BUG / ERROR

### ISSUE THREAD

**Issue by Gardiac** [CitizensDev/Citizens2#952]
[21:37:36 INFO]: Wayfare issued server command: /npc create KURAC

> [21:37:36 WARN]: java.lang.NoClassDefFoundError: ft
> 
> [21:37:36 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:319)
> 
> [21:37:36 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> [21:37:36 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
> [21:37:36 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> [21:37:36 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
> 
> [21:37:36 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
> 
> [21:37:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> 
> [21:37:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
> 
> [21:37:36 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
> 
> [21:37:36 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
> 
> [21:37:36 WARN]: Caused by: java.lang.ClassNotFoundException: ft
> 
> [21:37:36 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 
> [21:37:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
> 
> [21:37:36 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
> 
> [21:37:36 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 
> [21:37:36 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 
> [21:37:36 WARN]:        ... 26 more

i'm using 1.7.10spigot and 1.7.10 compatibility of citizens

**Comment by mcmonkey4eva** [comment]
You should be using this: http://ci.citizensnpcs.co/job/Citizens2/1166/

**Comment by Gardiac** [comment]
Not working bruh...

**Comment by mcmonkey4eva** [comment]
With what error?
