### ISSUE TITLE
Question sorry no issue.

### ISSUE THREAD

**Issue by nolifer123** [CitizensDev/Citizens2#954]
Hello Citizens dev's,

i got 2 questions:

1. can i let a npc jump.
2. can i let a npc use his right hand in the air? :)

Sorry for asking this in the issue page.
But i tried multiple times in the chat and i found out that or there is a time difference or i'm not that patient to wait that long in a chat room :).

**Comment by fullwall** [comment]
1) Yes, use the bukkit setVelocity APIs or NMS.jump
2) Yes, use the PlayerAnimation class )will have to depend on a specific Citizens NMS version) or bukkit's APIs (animate()) to do this.
