### ISSUE TITLE
Human NPCs vs. Villager NPC - performance?

### ISSUE THREAD

**Issue by bloggy** [CitizensDev/Citizens2#955]
tickEntity - EntityHumanNPC is minimum at 5% in my timings.

I wonder if it would help to eleminate citizens lag when switching from human NPCs to villager npcs (they have no skin). Would this reduce lag?

**Comment by fullwall** [comment]
Perhaps - would need more detailed timings than Aikar's plugin though. Try something like WarmRoast or MassiveLag to see what the problem is.

**Comment by bloggy** [comment]
There is this task:
Citizens::Task: net.citizensnpcs.util.PlayerUpdateTask (interval:1)
It constantly uses 6 - 10% of the overall server performance. Could you guys improve this? What is this for?

**Comment by fullwall** [comment]
I think this has been discussed on other issues.
