### ISSUE TITLE
Must have a NPC to execute the command?

### ISSUE THREAD

**Issue by UnspeicalSoul** [CitizensDev/Citizens2#956]
Every time I do /npc skin (Unspecialsoul as an example) It only says "You must have an NPC selected to execute that command." I tried every command, I don't understand what it means.

**Comment by mcmonkey4eva** [comment]
... Select an NPC to do the command on.
Or create one.
`/npc create Bob` to create one named Bob.
or
`/npc sel` whilst standing near an NPC...
