### ISSUE TITLE
Pathfinding ?

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#959]
Hello,

Please read this Sentinel issue to understand the problem : https://github.com/mcmonkey4eva/Sentinel/issues/93

Is the pathfinding buggy ? 
Can you help me ? Thanks.

**Comment by mcmonkey4eva** [comment]
Did you ever look in your Citizens config and fiddle the settings?
If so, what was the results of that? particular new-finder vs. old

**Comment by Blamo27** [comment]
Yes, I tried to change some configuration, but nothing change.

**Comment by Blamo27** [comment]
See this thread : https://github.com/CitizensDev/Citizens2/issues/962
