### ISSUE TITLE
[Suggested feature] improved NPC look?

### ISSUE THREAD

**Issue by MusicScore** [CitizensDev/Citizens2#960]
I'm currently using the latest Citizens2 plugin (version 2.0.20, build 1420) with Spigot 1.10.2 (Craftbukkit version git-Spigot-de459a2-51263e9), and I noticed that using the "lookclose" feature makes player NPCs look at you, but not necessarily mob-type NPCs. Let's say I use a Zombie NPC and give it the lookclose trait. It'll look at me when I move around it, but when I fly up or down it doesn't track me the same way a player NPC would. As a small test, I used the latest version of Denizen in an attempt to force the Zombie to look upwards. My attempts were not successful.

I would like to have the mobs be able to look up and down as well. I can work around it, but it's just something I'd like to have (by work around it, I mean finding player skins online...which I don't want to do often).

**Comment by mcmonkey4eva** [comment]
Denizen mobprox trait + the Denizen look command + cleverness = victory!

**Comment by MusicScore** [comment]
Yea, I don't think I have the cleverness required to make a mob's head rotation look convincing lol

I'll probably just stick with player NPCs with various skins. I did try out the mobprox trait and the Denizen look command, but I failed to figure out how exactly could I make the mob look up without it banging its head like it was in a metal concert.

**Comment by mcmonkey4eva** [comment]
You know what? I entirely misread you. I'm sorry. I thought you wanted an NPC to look at mobs. You actually want a mob NPC to look at things... I see now. That actually sounds like a bug! Which means its our (The Citizens team) job to look into and hopefully fix that!

**Comment by fullwall** [comment]
Fixed.
