### ISSUE TITLE
Still the same - Tablist

### ISSUE THREAD

**Issue by Dolzur** [CitizensDev/Citizens2#961]
Hello, i'm not sure if I missed the resolution of this problem, but still i'm having names of my npc's in the tablist. 
They blink there for a second and then dissapear. I've read, that somehow mojang made you to do it, but as far as I remember, that was and old post on a spigot forum. 

Haven't you managed this issue? Because for my PRG-server there's a need to make guardians on a spawn, and I dont want my tablist to be messed up with names of every single guardian.

Hope you to answer me asap!
Ty!

**Comment by Brokkonaut** [comment]
If they are player npcs there is no other option, because adding them to the tablist is the only way to send skins.

**Comment by mcmonkey4eva** [comment]
Yup ^ unfortunate limitation of the current Minecraft versions :/
Sorry for not responding sooner, somehow didn't see this post!
