### ISSUE TITLE
Pathfinding is buggy

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#962]
Hello,

There is a big issue with pathfinding in the latest versions of Citizens. 
Please watch this video : https://streamable.com/ky2a

This is with Citizens 2.0.16 (build 1308), on a 1.8 Minecraft server. At the beggining, the player puts a waypoint on the ground (where he hits) : we can see that the NPC goes correctly to that waypoint, even if it does not chose the best course to do so. In other words, here, it's fine.

Now, watch this video with Citizens 2.0.20 (build 1420), on a 1.10 Minecraft server :
https://streamable.com/q22i

As you can see the NPC simply does not recognize a correct path to go to the location and heads straight to a wall, where it stays blocked virtually forever. Note that in both videos, the NPC is just a NPC, without any trait in particular. This issue however has major consequences with Sentinel, since it makes NPCs go completely nuts when trying to reach an attacker, as you can see on these videos :
https://streamable.com/5m83
https://streamable.com/xgir

**Comment by mcmonkey4eva** [comment]
What difference does use-new-finder true and false make? (As in, a literal question: What do you notice when switching between the two?)

**Comment by Blamo27** [comment]
With the use-new-finder setting to true instead of false :
https://streamable.com/ceg1
https://streamable.com/4djp
._.

**Comment by Blamo27** [comment]
@mcmonkey4eva So...? Is this going to be fixed ? Is there even a way to do so ? Can someone from Citizens tell us, also...?

**Comment by mcmonkey4eva** [comment]
Personally, I have absolutely no idea why anyone of that would happen.
@fullwall might have some clue.

**Comment by Blamo27** [comment]
@mcmonkey4eva Can this be counted as a bug ?

**Comment by fullwall** [comment]
What does debug-pathfinding: true do? This seems like a bug to me but since 1.11 is coming out soon it may be worth holding off to see if it's fixed in 1.11.

**Comment by Blamo27** [comment]
Pastebin of the debug file (debug-pathfinding enabled) :
http://pastebin.com/Sd8Q9Qb9

**Comment by mcmonkey4eva** [comment]
debug-pathfinding should render things in-game as well (Specifically, a pathway of flowers to indicate what path it's found)

**Comment by Blamo27** [comment]
I see nothing like this.

**Comment by Blamo27** [comment]
Yep, just checked and double checked : there's absolutely no in-game effect with the debug set to true. Nothing in particular.

**Comment by Blamo27** [comment]
Timings paste : 
https://timings.spigotmc.org/?url=foqukujala

**Comment by Blamo27** [comment]
@fullwall @mcmonkey4eva 
We're still having this issue, which litterally makes the whole pathfinding un-usable, and therefore the plugin itself un-usable, preventing us from finally updating our server to 1.10 or higher. Here you can see another example of the bug, with a little comparison :

--> This is with Citizens [version] on 1.8 server : https://streamable.com/ambx
--> This is the same NPC, but with Citizens [version] on 1.10 server : https://streamable.com/hwys

We desperately need a fix for this. Thank you.

**Comment by Nutty101** [comment]
Just to add to this issue, having a ton of wacky path following problems as well.  This one is from sentinel on a server I am trying to get my own plugin working cleanly with the new citizens.

Video of the issue:
https://youtu.be/5bYrAwNOxrU

**Comment by Nutty101** [comment]
Also another video on issues with the path finder. The slabs are causing NPCs to get stuck.

` pathfinding:
    default-distance-margin: 0.5
    update-path-rate: 20
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: true`

ttps://www.youtube.com/watch?v=pv7mJFXakcg

**Comment by Nutty101** [comment]
Same issue happens on soil as well.  1.10 and 1.11 with citizens 1460.

https://www.youtube.com/watch?v=HE8KbFoC0hI    video of the issue with this one.

>citizens
[18:27:25 INFO]:           =====[ Citizens v2.0.21-SNAPSHOT (build 1460) ]=====
[18:27:25 INFO]:      -- Written by fullwall and aPunch
[18:27:25 INFO]:      -- Source Code: http://github.com/CitizensDev
[18:27:25 INFO]:      -- Website: http://www.citizensnpcs.co


[18:27:34 INFO]: This server is running CraftBukkit version git-Spigot-de459a2-5
1263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

[18:28:01 INFO]: This server is running CraftBukkit version git-Spigot-f950f8e-6
55d840 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[18:28:01 INFO]: Checking version, please wait...
[18:28:02 INFO]: You are 7 version(s) behind

**Comment by Nutty101** [comment]
If the waypoints are on soil, this happens, if i replace the soil with grass, the issue goes away.
