### ISSUE TITLE
NPC directly affecting playerdata

### ISSUE THREAD

**Issue by MusicScore** [CitizensDev/Citizens2#963]
I'm currently using the latest Citizens2 plugin (version 2.0.20, build 1420) with Spigot 1.10.2, and on a server I was working on something strange happened. I tried out the **/npc glowing --color aqua** command, and my tablist name and my nameplate became aqua. No matter what I did, I could not restore my tablist name and nameplate to a white color. I tried this out with someone else and simply changed the NPC's name to the other player's name. That player was also affected by the NPC. I'm unsure whether or not the **/npc glowing** command was the direct cause of the issue, but I'm willing to bet that it is.

Update: Upon reinstalling Citizens, I found out that the problem persists even with a clean reinstall (Citizens files deleted and everything). I could only resolve the issue by creating another NPC, renaming it to my username and the other player's username, then setting it to a mob-type NPC. Once it was a mob-type NPC, it could not affect our nameplates' visibility, nor did it affect the color of our nameplate and tablist name. No other solution worked other than that.

Update 2: I found out that naming an NPC after a player (without any format codes) will make it affect the player's data. I have now wasted 2 NPCs testing this out lol

**Comment by mcmonkey4eva** [comment]
Yup. For some drunk reason, Mojang made scoreboards use names, not UUIDs. So anything with the same name as you shares a scoreboard with you. Adding a color code to the end usually fixes that issue.

**Comment by Darlelet** [comment]
Why not forcing this by default as a temporary fix then? (Ending NPCs' names with color code)

**Comment by fullwall** [comment]
@Darlelet it would cut down on maximum name length but I suppose it's a kind of workaround.
