### ISSUE TITLE
Java load crashing

### ISSUE THREAD

**Issue by EternalUF** [CitizensDev/Citizens2#964]
Hello, I am currently having an issue with Citizens or Quicksell plugins. When the server is online and 2 or more users is playing the server crashes from Java load when a player interacts with a NPC. I am currently running 1.8, and the issue doesn't seem to bring up an Error in the logs. Thank you.

**Comment by fullwall** [comment]
If the java process is crashing there will be a dump somewhere of why it crashed. Please send us that since it is difficult to reproduce this.

**Comment by EternalUF** [comment]
Sorry for the late response, this is what I have. 
http://pastebin.com/QNwgp678

**Comment by mcmonkey4eva** [comment]
So CommandNPC triggered a command to QuickSell, which froze while calculating permissions via PEX.

... Which part of this is the fault of Citizens exactly?

**Comment by fullwall** [comment]
Yes, this is an issue with PEX and/or Quicksell/PermissionBoosters.
