### ISSUE TITLE
1.11 update

### ISSUE THREAD

**Issue by seema84** [CitizensDev/Citizens2#965]
Bukkit/Spigot 1.11 ->
[Citizens] v2.0.20-SNAPSHOT (build 1420) dont load - please update

**Comment by mcmonkey4eva** [comment]
Literally in testing right now, please be patient!

**Comment by seema84** [comment]
ok thanks :D

**Comment by mcmonkey4eva** [comment]
Initial builds are becoming available now! http://ci.citizensnpcs.co/job/Citizens2/

**Comment by fullwall** [comment]
Please report any issues you find in separate issues
