### ISSUE TITLE
NPCs want to sleep, too!

### ISSUE THREAD

**Issue by Namnodorel** [CitizensDev/Citizens2#966]
Hey, I just noticed that a feature for (player) NPCs is missing: They are unable to sleep! I'd suggest to add the (API and command) ability to make them sleep in a bed.

And secondly and way more exciting I want to suggest that you can make them sleep - without bed! Have a look at CorpseReborn to see how this can be accomplished. Again, both a command and a method for this in the API would be nice.

Stay awesome!

**Comment by mcmonkey4eva** [comment]
Denizen - https://wiki.citizensnpcs.co/Denizen - adds several more 'out there' features to Citizens, including easy sitting and sleeping commands.

Be warned, sleeping tends to bug out fairly often when there's no bed present, due to Mojang screwing with how that functions in recent versions!

**Comment by Namnodorel** [comment]
As far as I can tell, it has only the animate-command with a SLEEP animation. But that is insufficient. What CorpseReborn does, can basically be reduced to this (NMS) method: https://github.com/egold555/CorpseReborn/blob/master/src/org/golde/bukkit/corpsereborn/nms/nmsclasses/NMSCorpses_v1_10_R1.java#L122

**Comment by mcmonkey4eva** [comment]
Open an issue on the Denizen page and we'll see about getting that added there, as it's outside the scope of Citizens itself.
