### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Leon2Crafty** [CitizensDev/Citizens2#968]
Hello, today got this plugin for 10$, but it is not working. I have tried multiple versions, but none of them work (when I type /npc it does nothing). I have a 1.8.8 spigot server. I have not configurated the plugin. Here is what it says in the console though:

17.11 18:31:21 [Server] ERROR v2.0.20-SNAPSHOT (build 1420) is not compatible with Minecraft v1_8_R3 - try upgrading or downgrading Citizens. Disabling.

As said, I tried to upgrade/downgrade, and neither work. Please help me,
thanks
Also... I recently saw that I could have gotten the plugin for free. Is there a difference between the 10$ version and the free version?

**Comment by mcmonkey4eva** [comment]
You can grab the correct version from https://wiki.citizensnpcs.co/Versions
Find the one that matches your minecraft server version (1.8.8)

The $10 version on Spigot is a donation option.

**Comment by fullwall** [comment]
As mcmonkey said, you have a version mismatch. The $10 is a donation option - more info is posted in the spigot plugin description.
