### ISSUE TITLE
NPC Breaking Custom Entity Spawning 1.11

### ISSUE THREAD

**Issue by ABUDoctor** [CitizensDev/Citizens2#969]
If you are running a server that has Citizens (2.0.21-SNAPSHOT (build 1425)) for 1.11 and you also have a custom plugin that spawns custom entities on startup citizens takes what is needed for the NPC and not allows anything else to use it causing the custom plugin to throw this error on startup.

Custom Plugin Download: http://www.mediafire.com/file/w30061hc5t60ij3/CustomSpawn_1.11-R0.1_1.0.1.jar

Stack Trace Error: http://pastebin.com/GPJ9r8L1

**Comment by fullwall** [comment]
This doesn't seem Citizens related? Unless Citizens using the same java.lang.reflect.Field is overriding your final modifiers.

**Comment by ABUDoctor** [comment]
That is what I am saying citizens hook into the field and will not release it or allow anything else to access it. Thus locking it out and not allowing to use custom entities.

net.minecraft.server.v1_11_R1.EntityTypes.b

This object is required to create a custom entity for 1.11 as it seems.

**Comment by mcmonkey4eva** [comment]
That... doesn't sound anything close to how Java works?

**Comment by ABUDoctor** [comment]
Unless you reflection to hook into the object, Then load in your own class that uses the final object that is required to spawn the custom entities thus making the object look for a Custom citizen class. Then making it so you can not hook into it using a different plugin that has its own custom class. Giving the error:
Can not set static final net.minecraft.server.v1_11_R1.RegistryMaterials field net.minecraft.server.v1_11_R1.EntityTypes.b to net.doc.managers.CustomEntityRegistry

Also once I disable Citizen the error message goes away and everything works as it should with the custom spawning.

**Comment by mcmonkey4eva** [comment]
Can you show us the relevant code from the plugin generating the error?

**Comment by fullwall** [comment]
I think this is related to setting a final Field. Citizens grabs the value of the Field before you so it may be interfering with your plugin. I would recommend not setting a final Field and instead changing the values directly.

**Comment by ABUDoctor** [comment]
Custom Entity Code: http://pastebin.com/RFVUHs4j

You call: CustomEntityRegistry.addCustomEntity() on startup to register the custom entity and this is where it stack traces.

**Comment by fullwall** [comment]
Why are you wrapping the original RegistryMaterials?

**Comment by ABUDoctor** [comment]
How do you think i should do it?

**Comment by mcmonkey4eva** [comment]
Just add/remove entries from the existing map as needed.

**Comment by ABUDoctor** [comment]
how would i add to the map, i thought this is what allows you to add to the map

**Comment by fullwall** [comment]
You can just reflect and get the Registry Materials map and call a(int code, MinecraftKey key, Class<? extends Entity> class); 

I think it's better than trying to set a final field which isn't supposed to be modified.

**Comment by ABUDoctor** [comment]
cool thx all you need it this

MinecraftKey minecraftKey = new MinecraftKey(entityName);
EntityTypes.b.a(entityId, minecraftKey, entityClass);

That fixes my issue.
