### ISSUE TITLE
1.11 --type VILLAGER not working

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#974]
When I use --type VILLAGER, the npc vanishes.

Edit: Seems --type isn't working at all, only player npcs.

**Comment by fullwall** [comment]
Server log?

**Comment by Sikatsu** [comment]
What exactly do you want? Theres no error.

This doesn't happen for you?

**Comment by fullwall** [comment]
No, it works fine for me. I need some info on plugins/environment/server log.

**Comment by Sikatsu** [comment]
Environment? Is it weird if I do not have that folder?

**Comment by fullwall** [comment]
Sorry, that's not a folder, just a list of things I need to track down the issue. Maybe try disabling CommandNPC while you're at it.

**Comment by Sikatsu** [comment]
It's not CommandNPC it seems, as when I used /npc create test --type VILLAGER without adding a command, it still dissapeared.

Do you want /plugins/citizens/log?

**Comment by fullwall** [comment]
I want a list of plugins, the server log and the server environment (paperspigot or spigot basically)

**Comment by Sikatsu** [comment]
Give me a moment, my server is removing the nether and end and restarting. Will give all you need within 5 minutes.

**Comment by Sikatsu** [comment]
`21.11 17:03:17 [Server] INFO This server is running CraftBukkit version git-Spigot-16c940b-691628a (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
21.11 17:03:17 [Server] INFO Checking version, please wait...
21.11 17:03:18 [Server] INFO You are running the latest version`

Plugins: http://prntscr.com/da12yn

Server log: http://pastebin.com/2gFPF0aM

**Comment by fullwall** [comment]
Can you please try disabling PremiumVanish, MyPet and MobHunting?

**Comment by Sikatsu** [comment]
I disabled all of them, and used /npc create test --type VILLAGER, no luck. Still vanished.

**Comment by fullwall** [comment]
Can you try with the latest build?

**Comment by Sikatsu** [comment]
Build failed?

**Comment by fullwall** [comment]
Yeah, hold on.

**Comment by Sikatsu** [comment]
The build likes to spam minecraft:villager

**Comment by Sikatsu** [comment]
It works besides that :)

**Comment by fullwall** [comment]
Whoops, fixed.
