### ISSUE TITLE
1.11 right clicking NPCs creates an Inventory popup

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#975]
When I right click npc's an empty GUI comes up.

Left clicking works fine with CommandNPC.

**Comment by fullwall** [comment]
Which plugin is listening for the right click event?

**Comment by Sikatsu** [comment]
CommandNPC.

However, even when I do not link an command to the npc, it still opens an empty GUI on right click.

**Comment by Sikatsu** [comment]
It seems to happen when I'm in vanish. WIthout vanish it works.

Shift + Right click works in vanish.

**Comment by fullwall** [comment]
Still a problem?

**Comment by Sikatsu** [comment]
Yes, still a problem.

When in Vanish, the citizens open an empty GUI.

**Comment by Sikatsu** [comment]
http://prntscr.com/da26ov

**Comment by fullwall** [comment]
Is that PremiumVanish?

**Comment by Sikatsu** [comment]
Correct.

**Comment by Sikatsu** [comment]
If you need an API, SuperVanish is the free version of PremiumVanish.

**Comment by fullwall** [comment]
Can't reproduce with SuperVanish - tried with /sv on and off.

**Comment by mcmonkey4eva** [comment]
Is it possible your plugin is putting you in spectator gamemode?
Spectator mode enables 'peaking' into some inventories: in the case of Citizens, it would generally show an empty one!

**Comment by Sikatsu** [comment]
It puts me in spectator mode for opening chests, not I didn't see it for
NPC's. SuperVanish doesn't have that feature fullfall, with PremiumVanish
you can right click a player to open his inventory, but it glitches with
NPC's.

Op di 22 nov. 2016 07:49 schreef mcmonkey <notifications@github.com>:

**Comment by mcmonkey4eva** [comment]
So... everything is working exactly as expected across multiple plugins. What's the problem?

**Comment by Sikatsu** [comment]
It didn't do this for NPC's in 1.10?

Op di 22 nov. 2016 08:42 schreef mcmonkey <notifications@github.com>:

**Comment by mcmonkey4eva** [comment]
That sounds like a feature change in an update to PremiumVanish.

**Comment by Sikatsu** [comment]
PremiumVanish didn't receive an update since, but maybe it's a bug from
premiumvanish then

Op di 22 nov. 2016 08:46 schreef mcmonkey <notifications@github.com>:

**Comment by Sikatsu** [comment]
Solved by PremiumVanish dev, sorry.
