### ISSUE TITLE
Villager NPC bug

### ISSUE THREAD

**Issue by Sikatsu** [CitizensDev/Citizens2#977]
While the villager shows up now, he somehow get's stuck.. It doesn't happen immediatly but after some time he gets ''frozen'' even while /npc lookclose is on.

One works, one is frozen: http://prntscr.com/da4z7j

**Comment by Sikatsu** [comment]
One works, one is frozen: http://prntscr.com/da4z7j

**Comment by Sikatsu** [comment]
It seems to get worser by the day.. you can see it on my server if needed.

**Comment by fullwall** [comment]
Could it be related to chunk un/reloading?

**Comment by Sikatsu** [comment]
I don't know, what I do know is that it all worked fine on 1.10.. also they are located in the spawn.

Theres one villager moving a bit with his head, tho it doesn't move towards me and all villagers are frozen. Same probably for other mobtypes, you can see it on my server.. i'm not sure what else I can say to make it more clear

**Comment by fullwall** [comment]
Can you pastebin your config please?

**Comment by Sikatsu** [comment]
http://pastebin.com/zmRwxtsq

**Comment by Sikatsu** [comment]
This doesn't seem to be a villager only bug. It seems to be with all NPC"s including players.

Player NPC's not rotating to me but instead get frozen. http://prntscr.com/dakf7q

**Comment by Sikatsu** [comment]
Any news about this issue?

**Comment by mcmonkey4eva** [comment]
This was fixed (#983)
