### ISSUE TITLE
NPC won't use proper skin

### ISSUE THREAD

**Issue by Redfordshadow** [CitizensDev/Citizens2#978]
When I do /npc skin (username), it won't change to my skin. It changes to a different skin
Some backstory, I needed to skin some NPC's so I changed my skin to the desired skin, then did /npc skin (my username) -p to change it to the skin I wanted. It worked the first time, but whenever I do the same command but with a different skin, it changes to the skin I had first. Am I doing something wrong?

**Comment by fullwall** [comment]
What version of Citizens are you using?

**Comment by Redfordshadow** [comment]
Version 2.0.19

**Comment by fullwall** [comment]
This should be fixed in newer versions.

**Comment by Murreey** [comment]
This seems to still be happening in 2.0.21 build 1451 (latest).

However I can make it work by constantly restarting the server. If I do /npc skin [player] -p it gets the player's skin, then if I change the skin and run the command on another NPC it gets the first skin again. If I then restart the server and do it again for the second NPC, it updates to the right skin.

**Comment by mcmonkey4eva** [comment]
This issue is very old, but might still be present - caching problems with persistent skins.

**Comment by mcmonkey4eva** [comment]
Skin handling has been upgraded even further at some point semi-recently.
See https://wiki.citizensnpcs.co/Skins for notes

If there's still trouble, please open a new issue
