### ISSUE TITLE
NPC Animations are lost

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#987]
It seems like NPC animations are being lost in the middle of them happening.
As though the NPC is being reset every half second or so, which disables any animation playing.

Possibly related to an update packet that isn't aware of any currently playing animations?

**Comment by fullwall** [comment]
Can't reproduce... ARM_SWING?

**Comment by mcmonkey4eva** [comment]
@fullwall ARM_SWING is so fast you can't necessarily see the effect.
Try `start_use_offhand_item` while its holding a shield in offhand. That lasts varyingly between 0 seconds and half a second.

**Comment by fullwall** [comment]
start_use_offhand_item is special... I think I fixed this bug? Can you check again?

**Comment by mcmonkey4eva** [comment]
Not fixed as of `git-Spigot-766dab2-b9a2a74 (MC: 1.14)` and `Citizens version 2.0.25-SNAPSHOT (build 1654)`

**Comment by mcmonkey4eva** [comment]
No longer an issue on current versions. No idea when/how/why it was fixed but it was, a while ago.
