### ISSUE TITLE
Check if NPC is moving?

### ISSUE THREAD

**Issue by kinukin** [CitizensDev/Citizens2#990]
Checking if a NPC is moving (walking) - feature request

Minecraft Version 1.11, Citizens Version 2.0.21-SNAPSHOT <build 1426>

**Comment by mcmonkey4eva** [comment]
For what, a command, the API, ...?

**Comment by kinukin** [comment]
Citizens API

**Comment by mcmonkey4eva** [comment]
`npc.getNavigator().isNavigating()`

**Comment by kinukin** [comment]
Is it compatible with NavigationEvent? 

I want to check if the npc is navigating on every tick

**Comment by mcmonkey4eva** [comment]
There are navigation cancel and complete events.
See here: https://github.com/CitizensDev/CitizensAPI/tree/master/src/main/java/net/citizensnpcs/api/ai/event

If you want to check every tick, use a trait and check in the run method
