### ISSUE TITLE
1.11 I get no cape on the guys with cape..

### ISSUE THREAD

**Issue by HIQEA** [CitizensDev/Citizens2#991]
In this issue, please include:
- Bug
-
- 1.11, 2.0.21 / 1.10

**Comment by mcmonkey4eva** [comment]
Your issue says this includes 1.10
Here's a 1.10 screenshot:
![screen](http://i.mcmonkey.org/81B29195.png)

Or was that a typo and it's 1.11 only?

**Comment by HIQEA** [comment]
I have my server on 1.11 and can only run in on 1.11.

**Comment by mcmonkey4eva** [comment]
There are new commands and functionalities related to this available. Hopefully enough to fix the issue on latest builds.
