### ISSUE TITLE
Pathfinder inactive after StuckAction teleport due to target distance

### ISSUE THREAD

**Issue by liec0dez** [CitizensDev/Citizens2#993]
Citizens: 2.0.21 Snapshot
Spigot: 1.10.2

When setting yourself as target of an NPC and go away far enough to trigger the teleport StuckAction, said NPC will lose interest once teleported. I'm assuming this is valid for any target since to me there is no reason for StuckActions behaving differently based on EntityType...

**Comment by fullwall** [comment]
Are you using the default StuckAction? Are you setting the path again after teleporting?

**Comment by liec0dez** [comment]
@fullwall Yes, this has occured with the default StuckAction and I'm not setting the path again. Is one supposed to do that when NavigationStuckEvent is called? Would make more sense if that was built in...

**Comment by fullwall** [comment]
Yes, you are meant to set the path again after it gets stuck.
