### ISSUE TITLE
Undesired behaviour of Pathfinder while NPC is passenger.

### ISSUE THREAD

**Issue by liec0dez** [CitizensDev/Citizens2#994]
Citizens: 2.0.21 Snapshot
Spigot: 1.10.2

While riding a vehicle, a player (and possibly any other EntityType) NPC's body orientation keeps being messed up by changing vehicle orientation since it is not countering that movement. Leads to head and body facing opposite directions and body turning away from target. Tested with player NPC on horse NPC and both following same target entity.

**Comment by mcmonkey4eva** [comment]
Does the newest build fix this?
There was a commit pushed related to it.

**Comment by fullwall** [comment]
@mcmonkey4eva in IRC there's still some issues.

**Comment by mcmonkey4eva** [comment]
Is this still an issue two years later?

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply
