### ISSUE TITLE
Player NPCs not rotating 

### ISSUE THREAD

**Issue by PerksPrisoner** [CitizensDev/Citizens2#997]
In this bug it appears there is a location problem with the AI as in Snapshot 2.0.21 Build1437 when you tell a npc /npc look they rotate endlessly without being able to identify players. I thought I had the right build to be compatible with 1.11 but it appears not.

**Comment by mcmonkey4eva** [comment]
Try latest dev build? http://ci.citizensnpcs.co/job/Citizens2/

**Comment by GhotiMayo** [comment]
This occurs for me as well with the latest build. 
My plugin frequently updates what NPCs spawned through it are looking at using npc.faceLocation(p.getLocation());

In build 1424, everything worked as it should:

[https://gyazo.com/51f26271b9659979010b4295b71ac4ad](url)

When I switched to the latest build (currently 1446) the behavior changed to this:

[https://gyazo.com/c81603184f416309fb86e7e5c0e7e9a4](url)

**Comment by mcmonkey4eva** [comment]
@fullwall it's not so much "not rotating" as...
Rotating continuously whenever lookclose is enabled, I think.

**Comment by fullwall** [comment]
Yes, however I have been unable to reproduce so far.

**Comment by dwa1275** [comment]
same issue, not rotating

**Comment by PerksPrisoner** [comment]
This post is NECRO'd as foof. Why was in never closed?
