### ISSUE TITLE
Could not load plugin

### ISSUE THREAD

**Issue by bremsun** [CitizensDev/Citizens2#999]
http://pastie.org/10974829
So I am using Citizens API and i tried to make a plugin with it.
But it couldnt load my plugin.
When i remove the part which uses CitizensAPI in my plugin, the server can load the plugin. 
sorry for bad english

**Comment by fullwall** [comment]
You should not shade in CitizensAPI, make sure you have downloaded Citizens2 and put it in your depend in plugin.yml first.

**Comment by bremsun** [comment]
`name: NpcTest
version: 1.0
main: me.bremsun.npctest.NpcTest
description: This is a plugin
depend: [Citizens]`
still wont work
so i should not use maven?
and what exactly i need to do ?

**Comment by mcmonkey4eva** [comment]
That part is fine, but the maven pom.xml file needs to be checked as well. In particular, DO NOT SHADE the CitizensAPI.  Shading is a feature of maven in which it includes a full copy of the external code inside your own jar, which will prevent the Citizens plugin and your plugin from working together properly.

**Comment by bremsun** [comment]
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>   <modelVersion>4.0.0</modelVersion>
>   <groupId>io.github.bremsun</groupId>
>   <artifactId>npctestmaven</artifactId>
>   <version>0.2</version>
>     	<build>
> 		<plugins>
> 			<plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> 				<artifactId>maven-compiler-plugin</artifactId>
> 				<configuration>
> 					<source>1.8</source>
> 					<target>1.8</target>
> 				</configuration>
> 			</plugin>
> 		</plugins>
> 	</build>
> 	<repositories>
> 		<repository>
> 			<id>spigot-repo</id>
> 			<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
> 		</repository>
> 		<repository>
>             <id>citizens-repo</id>
>             <url>http://repo.citizensnpcs.co</url>
>         </repository>
> 		</repositories>
> 	<dependencies>
> 		
> 		<dependency>
> 			<groupId>org.spigotmc</groupId>
> 			<artifactId>spigot-api</artifactId>
> 			<version>1.10-R0.1-SNAPSHOT</version>
> 			<type>jar</type>
> 			<scope>provided</scope>
> 		</dependency>
> 		
> 		<dependency>
> 			<groupId>org.bukkit</groupId>
> 			<artifactId>bukkit</artifactId>
> 			<version>1.10-R0.1-SNAPSHOT</version>
> 			<type>jar</type>
> 			<scope>provided</scope>
> 		</dependency>
> 		
> 		<dependency>
> 			<groupId>net.citizensnpcs</groupId>
> 			<artifactId>citizens</artifactId>
> 			<version>2.0.18-SNAPSHOT</version>
> 			<type>jar</type>
>    			<scope>compile</scope>
> 		</dependency>
> 	</dependencies>
> </project>
heres my pom.xml

**Comment by fullwall** [comment]
CitizensAPI should be <scope>provided</scope>, just like the bukkit dependency.

**Comment by bremsun** [comment]
thx

**Comment by bremsun** [comment]
but it still doesnt work :(

**Comment by fullwall** [comment]
What error do you get?

**Comment by bremsun** [comment]
Thanks, i find the solution now https://www.spigotmc.org/threads/could-not-load-plugin-when-using-citizens-api.198291/#post-2064036
Thx for the help
